At may dalawang tulisan na ipinakong kasama niya, isa sa kanan at isa sa kaliwa.
“Kaya, kapag ikaw ay naglilimos, huwag kang magpapatunog ng trumpeta sa harapan mo, gaya ng ginagawa ng mga mapagkunwari sa mga sinagoga at sa mga lansangan, upang papurihan sila ng mga tao. Katotohanang sinasabi ko sa inyo, tinanggap na nila ang kanilang gantimpala.
Pagpasok niya sa Capernaum ay lumapit sa kanya ang isang senturion na nakikiusap sa kanya,
ay hindi sang-ayon sa kanilang panukala at gawa. Siya'y mula sa Arimatea, isang bayan ng mga Judio, at siya'y naghihintay sa kaharian ng Diyos.
Kanilang tinanong siya, “Guro, kailan mangyayari ang mga bagay na ito? At ano ang magiging tanda kapag malapit nang mangyari ang mga bagay na ito?”
At habang binabasbasan niya sila, kanyang iniwan sila [at dinala siya paitaas sa langit].
Sinabi naman niya sa kanila ang isang talinghaga: “Maaari bang akayin ng bulag ang isa pang bulag? Hindi kaya sila kapwa mahulog sa hukay?
Sumunod sa kanya ang napakaraming tao at sila'y pinagaling niya roon.
na ang Anak ng Tao ay kailangang ibigay sa mga kamay ng mga makasalanan, at ipako sa krus, at muling mabuhay sa ikatlong araw.”
Ang mga tao ay manlulupaypay dahil sa takot, at mangangamba sa mga bagay na darating sa daigdig, sapagkat ang mga kapangyarihan sa mga langit ay mayayanig.
Kayong mga bulag! Sapagkat alin ba ang higit na dakila, ang handog o ang dambana na nagpapabanal sa handog?
Pagkatapos ay pumunta si Jesus na kasama sila sa isang pook na tinatawag na Getsemani, at sinabi niya sa kanyang mga alagad, “Maupo kayo rito, samantalang ako'y pupunta sa dako roon at mananalangin.”
At sinabi niya sa kanila, “Ano ba ang inyong pinag-uusapan sa inyong paglalakad?” At sila'y tumigil na nalulungkot.
Subalit tingnan ninyo, ang nagkakanulo sa akin ay kasama ko, at ang kamay niya ay nasa hapag.
Ngunit magmula ngayon ang Anak ng Tao ay mauupo sa kanan ng kapangyarihan ng Diyos.”
Kunin mo ang para sa iyo at umalis ka na. Nais kong ibigay sa huling nagtrabaho ang kagaya ng ibinigay ko sa iyo.
Kaya sa muling pagkabuhay, alin sa pito ang magiging asawa ng babae? Yamang siya'y napangasawa nilang lahat.”
Noon ay nagtuturo siya sa isa sa mga sinagoga nang araw ng Sabbath.
Pagkatapos ay sumagot si Pedro at sinabi sa kanya, “Narito, iniwan namin ang lahat at sumunod sa iyo. Ano naman ang makakamit namin?”
Siya'y sumama sa kanya. Sinundan siya ng napakaraming tao at siya'y siniksik nila.
Nang pababa na sila sa bundok, iniutos ni Jesus sa kanila na nagsasabi, “Huwag ninyong sasabihin kanino man ang pangitain, hanggang ang Anak ng Tao ay muling buhayin mula sa mga patay.”
“Sapagkat tulad sa isang tao na maglalakbay, tinawag niya ang kanyang sariling mga alipin, at ipinagkatiwala sa kanila ang kanyang mga ari-arian.
Pagkatapos ay dinala sa kanya ang maliliit na bata, upang ipatong niya ang kanyang mga kamay sa kanila at ipanalangin. Ngunit sinaway ng mga alagad ang mga tao.
Kung ipagsakdal ka ng sinuman, at kunin ang iyong baro, ibigay mo rin sa kanya ang iyong balabal.
Sinaway siya ni Jesus, na nagsasabi, “Tumahimik ka, at lumabas ka sa kanya!”
na kung saan ang kanilang mga uod ay hindi namamatay, at ang apoy ay hindi napapatay.]
Ngunit kinuha ng mga magsasaka ang kanyang mga alipin at binugbog nila ang isa, pinatay ang iba, at pinagbabato ang isa pa.
Kung kayo nga na masasama ay marunong magbigay ng mabubuting kaloob sa inyong mga anak, gaano pa kaya ang inyong Ama sa langit na magbibigay ng Espiritu Santo sa mga humihingi sa kanya?”
Tingnan mo, ang iyong Hari ay dumarating sa iyo,
Subalit sa alinmang bayan kayo pumasok at hindi kayo tanggapin, lumabas kayo sa mga lansangan nito at inyong sabihin,
At inilalaan ko sa inyo kung paanong ang Ama ay naglaan para sa akin ng isang kaharian,
Nang makalakad pa siya ng kaunti, nakita niya sina Santiago na anak ni Zebedeo at si Juan na kanyang kapatid na naghahayuma ng mga lambat sa kanilang bangka.
Kung ang mata mo'y nakapagpapatisod sa iyo, dukitin mo ito. Mas mabuti pa sa iyo ang pumasok sa kaharian ng Diyos na may isang mata, kaysa may dalawang mata at mabulid sa impiyerno,
Nang malapit na ang panahon ng pamumunga, sinugo niya ang kanyang mga alipin sa mga magsasaka upang kunin ang mga bunga nito.
At sila'y labis na nalungkot, at isa-isang nagpasimulang magsabi sa kanya, “Ako ba, Panginoon?”
At kapag matagpuan niya ito ay tinatawag niya ang kanyang mga kaibigan at mga kapitbahay, na nagsasabi, ‘Makigalak kayo sa akin, sapagkat natagpuan ko na ang pilak na nawala sa akin.’
at kaluwalhatian sa kataas-taasan!”
At nagpakita sa kanila sina Moises at Elias na nakikipag-usap sa kanya.
Sa kanilang pagbabalik, ibinalita ng mga apostol kay Jesus ang mga bagay na kanilang ginawa. Kanyang isinama sila at palihim na nagtungo sa isang bayan na tinatawag na Bethsaida.
Nang matapos na ang mga araw ng kanyang paglilingkod, siya'y umuwi sa kanyang bahay.
Gayon nga ang nagtitipon ng kayamanan para sa kanyang sarili, subalit hindi mayaman sa Diyos.”
Kaya't isinugo ni Jesus sina Pedro at Juan, na sinasabi, “Humayo kayo at ihanda ninyo ang paskuwa para sa atin, upang ating kainin ito.”
Sapagkat dinakip ni Herodes si Juan, iginapos niya ito at inilagay sa bilangguan dahil kay Herodias, na asawa ng kanyang kapatid na si Felipe.
At kung hindi paiikliin ang mga araw na iyon, ay walang makakaligtas na laman, subalit alang-alang sa mga hinirang ay paiikliin ang mga araw na iyon.
Kaya't pagsikat ng araw, ang mga iyon ay natuyo at dahil sa walang ugat ang mga iyon ay tuluyang nalanta.
Sinabi niya sa mga alagad, “Darating ang mga araw na hahangarin ninyong makita ang isa sa mga araw ng Anak ng Tao at hindi ninyo ito makikita.
Nang mabalitaan iyon ng kanyang sambahayan, lumabas sila upang siya'y pigilan sapagkat sinasabi ng mga tao, “Wala siya sa sarili.”
Siya'y sumagot at sinabi, “Hindi mabuti na kunin ang tinapay ng mga anak at itapon ito sa mga aso.”
na sinasabi sa kanila, “Pumunta kayo sa kasunod na nayon, at kaagad ninyong matatagpuan ang isang babaing asno na nakatali na may kasamang isang batang asno. Kalagan ninyo sila at dalhin ninyo sa akin.
“Subalit kahabag-habag kayong mayayaman,
Sinabi sa kanila ni Jesus, “Hindi ba't ito ang dahilan kaya kayo nagkakamali, hindi ninyo nalalaman ang mga kasulatan, o ang kapangyarihan ng Diyos?
Nang ikatlo ng hapon ay sumigaw si Jesus nang may malakas na tinig, “Eloi, Eloi, lama sabacthani?” na ang kahulugan ay, “Diyos ko, Diyos ko, bakit mo ako pinabayaan?”
Kaya't kung sasamba ka sa akin, ang lahat ng ito ay magiging iyo.”
At biglang sumama sa anghel ang isang malaking hukbo ng langit na nagpupuri sa Diyos at nagsasabi,
Subalit sinabi sa kanya ng Diyos, ‘Hangal, sa gabing ito ay kukunin ang iyong kaluluwa; at kanino kaya mapupunta ang mga bagay na inihanda mo?’
May ilang panahon na siya'y tumatanggi, subalit pagkatapos ay sinabi sa kanyang sarili, ‘Bagaman ako'y hindi natatakot sa Diyos, at hindi gumagalang sa tao,
At siya'y kanilang sinunggaban, pinatay, at itinapon sa labas ng ubasan.
“Magalak kayo at magsaya, sapagkat malaki ang gantimpala ninyo sa langit, sapagkat gayundin nila inusig ang mga propeta na nauna sa inyo.
At kapag kayo'y nakarinig ng mga digmaan at mga kaguluhan, huwag kayong matakot. Sapagkat kailangang mangyari muna ang mga bagay na ito, subalit hindi pa ito ang wakas.”
Si Pedro ay nagsimulang magsabi sa kanya, “Tingnan mo, iniwan namin ang lahat at sumunod kami sa iyo.”
at lumapit sa kanya ang isang ketongin, at lumuhod sa harapan niya na nagsasabi, “Panginoon, kung ibig mo ay malilinis mo ako.”
Sapagkat sa pagbubuhos niya ng pabangong ito sa aking katawan, ginawa niya iyon upang ihanda ako sa paglilibing.
Kanyang kinuha iyon at kumain sa harapan nila.
na maghahanda ng iyong daan sa iyong harapan.’
Sinabi ng isa pa, ‘Bumili ako ng limang magkatuwang na bakang lalaki, at paroroon ako upang sila'y subukin. Hinihiling ko sa iyo na pagpaumanhinan mo ako.’
Nang marinig nila ito ay namangha sila. Kanilang iniwan siya at sila'y umalis.
At sasagot ang Hari at sasabihin sa kanila, ‘Katotohanang sinasabi ko sa inyo, yamang ginawa ninyo ito sa isa sa pinakamaliit sa mga kapatid kong ito, ay sa akin ninyo ginawa.’
Subalit siya'y nanlumo sa sinabing ito, at siya'y umalis na nalulungkot sapagkat siya'y maraming ari-arian.
Sapagkat may mga eunuko, na ipinanganak na gayon mula sa sinapupunan ng kanilang mga ina; at may mga eunuko na ginawang eunuko ng mga tao; at may mga eunuko na ginawang eunuko ang kanilang mga sarili alang-alang sa kaharian ng langit. Ang makakatanggap nito, ay hayaang tumanggap.”
Dinala nila sa kanya ang isang bingi at may kapansanan sa pagsasalita, at siya'y pinakiusapan nila na ipatong ang kanyang kamay sa kanya.
Muli siyang nagsugo ng ibang mga alipin na mas marami pa sa nauna; at gayundin ang ginawa nila sa kanila.
At patawarin mo kami sa aming mga utang, gaya rin namin na nagpapatawad sa mga may utang sa amin.
At nangyari, sa kanyang paghahasik, ang ilang binhi ay nahulog sa tabi ng daan at nagdatingan ang mga ibon at kinain ito.
Sinabi niya sa kanila, “Kayo rin ba ay hindi nakakaunawa? Hindi ba ninyo nalalaman, na anumang nasa labas na pumapasok sa tao ay hindi nakapagpaparumi sa kanya,
Ngunit sinasabi ninyo na kung sabihin ng isang tao sa kanyang ama o ina, ‘Ang anumang tulong na mapapakinabang ninyo sa akin ay Corban, na nangangahulugang handog,’
naging anak ni Salmon kay Rahab si Boaz; naging anak ni Boaz kay Ruth si Obed; at naging anak ni Obed si Jesse;
Sumagot sa kanya si Jesus, “Lumayas ka, Satanas! sapagkat nasusulat, ‘Sambahin mo ang Panginoon mong Diyos, at siya lamang ang iyong paglingkuran.’”
ayon sa ipinaalam sa atin ng mga taong buhat sa pasimula ay mga saksing nakakita at mga tagapangaral ng salita,
At sa takot sa kanya, nanginig ang mga bantay, at naging tulad sa mga patay.
Ngunit nang mapansin niya ang hangin, natakot siya, at nang siya'y papalubog na ay sumigaw siya, “Panginoon, iligtas mo ako!”
Dumating ang manunukso at sinabi sa kanya, “Kung ikaw ang Anak ng Diyos, ipag-utos mo na ang mga batong ito ay maging tinapay.”
Nang isang Sabbath, nagdaraan siya sa mga bukirin ng trigo, at samantalang sila'y nagdaraan ang kanyang mga alagad ay nagsimulang pumitas ng mga uhay.
Noon, ang mga maniningil ng buwis at mga makasalanan ay lumalapit sa kanya upang makinig.
Sinabi sa kanya ni Jesus, “Bakit tinatawag mo akong mabuti? Walang mabuti kundi ang Diyos lamang.
Kaya't naunawaan nila na ang sinabi ni Jesus ay hindi sa pampaalsa ng tinapay mag-ingat kundi sa mga aral ng mga Fariseo at Saduceo.
Habang patungo sa Jerusalem, si Jesus ay dumaan sa pagitan ng Samaria at Galilea.
Kanyang nilapitan siya at tinalian ang kanyang mga sugat pagkatapos buhusan ng langis at alak. Pagkatapos isakay sa kanyang sariling hayop, siya ay dinala sa bahay-panuluyan at inalagaan.
Si Juan ay nakadamit ng balahibo ng kamelyo, may sinturong balat sa kanyang baywang, at kumakain ng mga balang at pulot-pukyutan.
“Magsisi kayo, sapagkat malapit na ang kaharian ng langit.”
Nang nagtatakipsilim na, lumapit sa kanya ang mga alagad niya, na nagsasabi, “Ilang na lugar ito, at lumipas na ang maghapon. Papuntahin mo na ang mga tao sa mga nayon upang makabili sila ng kanilang makakain.”
Gayunma'y sinasabi ko sa inyo, kahit si Solomon sa buong kaluwalhatian niya ay hindi nakapagdamit nang tulad sa isa sa mga ito.
Sumagot siya sa kanila at sinabi, “Bakit lumalabag naman kayo sa utos ng Diyos dahil sa inyong tradisyon?
“Mapapalad ang mga mahabagin, sapagkat sila'y kahahabagan.
At lumapit din ang tumanggap ng isang talento at sinabi niya, ‘Panginoon, alam kong ikaw ay taong malupit, na gumagapas ka roon sa hindi mo hinasikan, at nagtitipon ka roon sa hindi mo kinalatan ng binhi.
Pagkatapos nito, si Jesus ay dinala ng Espiritu Santo sa ilang upang tuksuhin ng diyablo.
At pagharap niya sa mga alagad ay palihim niyang sinabi, “Mapapalad ang mga matang nakakakita ng inyong nakikita.
Katotohanang sinasabi ko sa iyo, hindi ka makakalabas doon hanggang hindi mo nababayaran ang kahuli-hulihang kusing.
Kung kayo nga na masasama ay marunong magbigay ng mabubuting kaloob sa inyong mga anak, gaano pa kaya ang inyong Ama na nasa langit ang magbigay ng mabubuting bagay sa mga humihingi sa kanya?
Bumaba siya na kasama nila at tumayo sa isang patag na lugar. Naroon ang marami sa kanyang mga alagad at ang napakaraming tao buhat sa Judea at sa Jerusalem at sa baybayin ng Tiro at Sidon, na pumaroon upang makinig sa kanya at mapagaling sa kanilang mga sakit;
Nang oras na iyon ay lumapit ang mga alagad kay Jesus, na nagsasabi, “Sino ang pinakadakila sa kaharian ng langit?”
Habang papaalis na ang mga ito, nagpasimulang magsalita si Jesus sa maraming tao tungkol kay Juan: “Ano ang pinuntahan ninyo sa ilang upang makita? Isa bang tambo na inuuga ng hangin?
Sinumang nagsisikap ingatan ang kanyang buhay ay mawawalan nito, subalit ang sinumang nawalan ng kanyang buhay ay maiingatan iyon.
Pagkatapos na siya'y libakin, hinubad nila sa kanya ang balabal, isinuot sa kanya ang mga damit niya, at kanilang inilabas siya upang ipako sa krus.
At pagkaawit nila ng isang himno ay nagtungo sila sa Bundok ng mga Olibo.
Subalit wala silang anak, sapagkat baog si Elizabeth at sila'y kapwa matanda na.
Sapagkat kung saan nagkakatipon ang dalawa o tatlo sa aking pangalan, ay naroroon ako sa gitna nila.”
ni Serug, ni Reu, ni Peleg, ni Eber, ni Sala,
At sumagot si Jesus, “Tigil! Tama na!” At hinawakan niya ang tainga at pinagaling siya.
Kung siya'y magkasala laban sa iyo ng pitong ulit sa isang araw at pitong ulit siyang bumalik sa iyo, na nagsasabi, ‘Nagsisisi ako,’ dapat mo siyang patawarin.”
At kung ang isang bahay naman ay nagkakabaha-bahagi laban sa kanyang sarili, hindi makakatayo ang bahay na iyon.
Sumagot siya at sinabi sa kanila, “Sapagkat sa inyo ipinagkaloob na malaman ang mga hiwaga ng kaharian ng langit, ngunit hindi ipinagkaloob sa kanila.
Subalit dahil batid ni Jesus ang iniisip ng kanilang puso, kumuha siya ng isang maliit na bata at inilagay sa kanyang tabi.
Pagkatapos ay sasabihin niya sa mga nasa kaliwa, ‘Lumayo kayo sa akin, kayong mga sinumpa. Doon kayo sa apoy na walang hanggan na inihanda sa diyablo at sa kanyang mga anghel.
Pagkatapos ay lumapit si Pedro at sinabi sa kanya, “Panginoon, makailang ulit magkakasala ang aking kapatid laban sa akin at siya'y aking patatawarin? Hanggang sa makapito ba?”
Mula roon, siya'y umalis at pumunta sa lupain ng Judea at sa kabila ng Jordan. At muling nagtipon ang napakaraming tao sa paligid niya at tulad ng kanyang nakaugalian, muli niyang tinuruan sila.
Nang makita ito ng mga Fariseo, sinabi nila sa kanyang mga alagad, “Bakit nakikisalo ang inyong guro sa mga maniningil ng buwis at mga makasalanan?”
At kung matagpuan niya ito ay katotohanang sinasabi ko sa inyo, magagalak siya rito nang higit kaysa siyamnapu't siyam na hindi naligaw.
Sinabi sa kanya ng kanyang mga alagad, “Nakikita mong sinisiksik ka ng karamihan, at sinasabi mo pang ‘Sino ang humipo sa akin?’”
Minsan, nang si Jesus ay nananalanging mag-isa, ang mga alagad ay kasama niya at tinanong niya sila, “Ano ang sinasabi ng karamihan kung sino ako?”
Tinanong siya ng maraming tao, “Ano ngayon ang dapat naming gawin?”
At isa sa maraming tao ay sumagot sa kanya, “Guro, dinala ko sa iyo ang aking anak na lalaki na may isang piping espiritu.
Ang iba ay nahulog sa tinikan at lumaki ang mga tinik at sinakal ito, at ito'y hindi namunga.
Ipagkakanulo ng kapatid sa kamatayan ang kapatid at ng ama ang kanyang anak; at maghihimagsik ang mga anak laban sa mga magulang at sila'y ipapapatay.
At nang kanyang malaman na siya'y sakop ni Herodes, kanyang ipinadala siya kay Herodes, na nang panahong iyon ay nasa Jerusalem din.
“Nang pagputul-putulin ang pitong tinapay para sa apat na libo, ilang kaing na punô ng mga pinagputul-putol ang pinulot ninyo?” Sinabi nila sa kanya, “Pito.”
Noon ay may isang lalaki sa Jerusalem na ang pangalan ay Simeon. Ang lalaking ito'y matuwid at masipag sa kabanalan na naghihintay sa kaaliwan ng Israel at nasa kanya ang Espiritu Santo.
“Mag-ingat kayo sa mga bulaang propeta, na lumalapit sa inyo na may damit tupa, ngunit sa loob ay mga ganid na asong-gubat.
Subalit hindi gayon sa inyo, ngunit ang sinumang ibig na maging dakila sa inyo ay kailangang maging lingkod ninyo;
Sapagkat sinabi ni Juan sa kanya, “Hindi ipinahihintulot sa iyo na angkinin mo siya.”
at ilalagay niya ang mga tupa sa kanyang kanan, subalit ang mga kambing ay sa kaliwa.
Ngunit sinabi ng mga Fariseo, “Nagpapalayas siya ng mga demonyo sa pamamagitan ng pinuno ng mga demonyo.”
At sinabi niya sa kanila, “O napakahangal naman ninyo at napakakupad ang mga puso sa pagsampalataya sa lahat ng ipinahayag ng mga propeta!
Sa bawat kapistahan ay nakaugalian na niyang pawalan sa kanila ang isang bilanggo na kanilang hilingin.
at nang hindi nila matagpuan ang kanyang bangkay, sila ay bumalik. Sinabi nilang sila ay nakakita ng isang pangitain ng mga anghel na nagsabing siya'y buháy.
Bakit mo nakikita ang puwing na nasa mata ng iyong kapatid, ngunit hindi mo pinapansin ang troso na nasa iyong sariling mata?
Hindi ba't kasama natin ang lahat ng kanyang mga kapatid na babae? Saan kinuha ng taong ito ang lahat ng mga bagay na ito?”
At nagtanong si Jesus, “Hindi ba sampu ang nalinis? Nasaan ang siyam?
Tumayo sa tabi nila ang isang anghel ng Panginoon at ang kaluwalhatian ng Panginoon ay nagliwanag sa palibot nila, at sila'y lubhang natakot.
Nagsugo siya ng isa pang alipin, subalit ito'y kanilang binugbog din at hiniya, at pinaalis na walang dala.
At kanilang tinanong siya, “Guro, isinulat ni Moises para sa amin na kung ang kapatid na lalaki ng isang tao ay mamatay, na may iniwang asawa subalit walang anak, pakakasalan ng lalaki ang balo at bibigyan ng anak ang kanyang kapatid.
patungo sa dagat, sa ibayo ng Jordan, Galilea ng mga Hentil—
Nang makapasok na siya sa bahay, lumapit sa kanya ang mga lalaking bulag; at sinabi sa kanila ni Jesus, “Sumasampalataya ba kayo na magagawa ko ito?” Sinabi nila sa kanya, “Opo, Panginoon.”
Sila'y kanyang iniwan, at lumabas sa lunsod patungong Betania, at doon siya nagpalipas ng gabi.
At sinabi ng Panginoon, “Pakinggan ninyo ang sinabi ng masamang hukom.
At sinimulan niyang isalaysay sa taong-bayan ang talinghagang ito: “Isang tao ang nagtanim ng ubasan. Ipinagkatiwala niya ito sa mga magsasaka, at pumunta sa ibang lupain nang mahabang panahon.
“Ngunit nang pumasok ang hari upang tingnan ang mga panauhin, may nakita siya roong isang tao na hindi nakadamit pangkasal.
Dumating din ang mga maniningil ng buwis upang magpabautismo at sinabi nila sa kanya, “Guro, ano ang dapat naming gawin?”
Samantalang nagsasalita pa si Jesus sa maraming tao, ang kanyang ina at mga kapatid na lalaki ay nakatayo sa labas at ibig nilang makausap siya.
At pagkakuha niya sa limang tinapay at sa dalawang isda, tumingala siya sa langit, pinagpala, at pinagputul-putol ang mga ito. Ibinigay niya ang mga ito sa mga alagad upang ihain sa napakaraming tao.
At naroon ang isang babae na may espiritu ng karamdaman sa loob ng labingwalong taon. Siya ay baluktot at hindi niya kayang tumayo ng talagang matuwid.
Ngunit mag-ingat kayo; ipinagpauna ko nang sabihin sa inyo ang lahat ng bagay.
At kanyang sinabi sa kanila, “Ang mga hari ng mga Hentil ay nagpapapanginoon sa kanila; at ang mga may awtoridad sa kanila'y tinatawag na mga tagapagpala.
Sumagot naman si Pedro at sinabi sa kanya, “Ipaliwanag mo sa amin ang talinghaga.”
Bawat puno na hindi mabuti ang bunga ay pinuputol, at itinatapon sa apoy.
At kunin ninyo ang pinatabang guya at patayin ito, at tayo'y kumain at magdiwang.
“Luwalhati sa Diyos sa kataas-taasan,
Hindi pa ba ninyo nalalaman na ang anumang pumapasok sa bibig ay tumutuloy sa tiyan, at inilalabas sa daanan ng dumi?
Nang magugol na niyang lahat ay nagkaroon ng matinding taggutom sa lupaing iyon, at siya'y nagsimulang mangailangan.
“Magsikap kayong pumasok sa makipot na pintuan, sapagkat sinasabi ko sa inyo na marami ang magsisikap na pumasok at hindi makakapasok.
Kayo'y ipagkakanulo maging ng mga magulang at mga kapatid, mga kamag-anak at mga kaibigan, at ipapapatay nila ang iba sa inyo.
Ako'y mayroong bautismo na ibabautismo sa akin, at ako'y nababagabag hanggang hindi ito nagaganap!
Mas madali pa para sa isang kamelyo ang dumaan sa butas ng isang karayom kaysa isang mayaman ang pumasok sa kaharian ng Diyos.”
Pagkalabas sa sinagoga, pumasok sila sa bahay ni Simon at ni Andres, kasama sina Santiago at Juan.
kundi puntahan ninyo ang mga nawawalang tupa sa bahay ni Israel.
Nang dumating siya sa bahay, hindi niya ipinahintulot na pumasok na kasama niya ang sinuman, maliban kina Pedro, Juan, Santiago, at ang ama at ina ng bata.
“Simon, Simon, narito, hiningi ni Satanas na ligligin kayo gaya ng trigo,
Kaya't siya'y nagmadali, bumaba, at natutuwa siyang tinanggap.
Kapag inuusig nila kayo sa isang bayan, tumakas kayo tungo sa kasunod, sapagkat katotohanang sinasabi ko sa inyo, ‘Hindi ninyo mapupuntahan lahat ang mga bayan ng Israel, bago dumating ang Anak ng Tao.’
Nasa kamay niya ang kanyang kalaykay upang linisin ang kanyang giikan at tipunin ang trigo sa kanyang kamalig, subalit susunugin niya ang dayami sa apoy na hindi mapapatay.”
Ngunit ano ang pinuntahan ninyo upang makita? Isa bang propeta? Oo, sinasabi ko sa inyo, at higit pa kaysa isang propeta.
“Mapapalad ang mga dukha sa espiritu, sapagkat kanila ang kaharian ng langit.
ni Matatias, ni Amos, ni Nahum, ni Esli, ni Nagai,
Nang sumunod na araw, dumukot siya ng dalawang denario at ibinigay sa may-ari ng bahay-panuluyan at sinabi niya, ‘Alagaan mo siya, at sa anumang karagdagan mo pang gastusin ay babayaran kita sa aking pagbabalik.’
Habang sila'y nagkakatipon sa Galilea, sinabi ni Jesus sa kanila: “Ang Anak ng Tao ay malapit nang ipagkanulo sa kamay ng mga tao.
Sapagkat ang buhay ay higit kaysa pagkain at ang katawan ay higit kaysa damit.
“Narito, ipinapadala ko ang aking sugo sa iyong unahan,
Ang manghahasik ay naghahasik ng salita.
oo, Ama, sapagkat gayon ang mapagpala mong kalooban.
tuwirin ninyo ang kanyang mga landas.
at inilagay sa kanyang sariling bagong libingan, na kanyang inukit sa bato. Pagkatapos ay iginulong niya ang isang malaking bato sa pintuan ng libingan, at siya'y umalis.
Pansinin ninyo ang mga liryo, kung paano silang tumutubo. Hindi sila nagpapagal o humahabi man, subalit sinasabi ko sa inyo, kahit si Solomon, sa buong kaluwalhatian niya ay hindi nakapagbihis na gaya ng isa sa mga ito.
Lumapit sa kanya sina Santiago at Juan na mga anak ni Zebedeo, na nagsasabi sa kanya, “Guro, ibig naming gawin mo sa amin ang anumang aming hingin sa iyo.”
hanggang sa ilagay ko ang iyong mga kaaway
Pumasok siya sa bahay ni Zacarias at bumati kay Elizabeth.
Ang buong lunsod ay nagkatipon sa may pintuan.
Naunawaan nga ng mga alagad na si Juan na Tagapagbautismo ang sinasabi niya sa kanila.
Kaya't sa paghayo ninyo, gawin ninyong alagad ang lahat ng mga bansa, bautismuhan ninyo sila sa pangalan ng Ama at ng Anak at ng Espiritu Santo,
Sinabi ng mga alagad sa kanya, “Kung gayon ang kalagayan ng lalaki sa kanyang asawa, mas mabuti pang huwag mag-asawa.”
Sa paglabas niya sa templo, sinabi sa kanya ng isa sa kanyang mga alagad, “Guro, tingnan mo! Pagkalalaking mga bato, at pagkalalaking mga gusali!”
Ang mga punong pari at ang mga eskriba ay nanatili, at marahas siyang pinagbibintangan.
At ipatawad mo sa amin ang aming mga kasalanan,
Bumagsak ang ulan, at dumating ang baha. Humihip ang mga hangin at hinampas ang bahay na iyon, ngunit hindi iyon bumagsak, sapagkat itinayo sa ibabaw ng bato.
Sapagkat siya'y magiging dakila sa harapan ng Panginoon, at hindi siya iinom ng alak o matapang na inumin. Siya'y mapupuno ng Espiritu Santo mula pa sa sinapupunan ng kanyang ina.
ni Jacob, ni Isaac, ni Abraham, ni Terah, ni Nahor,
Samantalang sila'y nag-uusap at nagtatanungan, si Jesus mismo ay lumapit at naglakbay na kasama nila.
Ang ilan sa nakatayo roon ay nagsabi sa kanila, “Anong ginagawa ninyo na inyong kinakalagan ang batang asno?”
At ang iba'y nahulog sa mabuting lupa, tumubo, at nagbunga ng tig-iisang daan.” Pagkatapos niyang sabihin ang mga bagay na ito, siya ay sumigaw, “Ang may mga taingang pandinig ay makinig.”
upang ipahayag ang taon ng biyaya mula sa Panginoon.”
Sapagkat sinasabi ko sa inyo na ang kasulatang ito ay kailangang matupad sa akin, ‘At ibinilang siya sa mga suwail’; sapagkat ang nasusulat tungkol sa akin ay natutupad.”
Tinawag din siya ni David na Panginoon; kaya't paano siyang magiging anak ni David?” At ang napakaraming tao ay tuwang-tuwa na nakikinig sa kanya.
Gayundin, ang tumanggap ng dalawa ay nakinabang pa ng dalawa.
Si Pilato'y muling nagsalita sa kanila sa kagustuhang palayain si Jesus.
Nang marinig ito ni Jesus, sinabi niya sa kanya, “Isang bagay pa ang kulang sa iyo. Anumang mayroon ka ay ipagbili mo, ipamahagi mo sa mga dukha, at magkakaroon ka ng kayamanan sa langit. At pumarito ka, sumunod ka sa akin.
Lumabas ang buong bayan upang salubungin si Jesus at pagkakita nila sa kanya, pinakiusapan nila siyang umalis sa kanilang nasasakupan.
Si Zaqueo ay tumindig at sinabi sa Panginoon, “Panginoon, ang kalahati ng aking mga pag-aari ay ibinibigay ko sa mga dukha at kung sa pamamagitan ng pandaraya ay may kinuha ako sa kanino mang tao, babayaran ko siya ng apat na ulit.”
At sumumpa siya sa kanya, “Ang anumang hingin mo sa akin ay ibibigay ko sa iyo, kahit na ang kalahati ng aking kaharian.”
Samantalang kanilang pinag-uusapan ang mga bagay na ito, si Jesus ay tumayo sa gitna nila at sinabi sa kanila, “Sumainyo ang kapayapaan.”
Noo'y araw ng Paghahanda, at malapit na ang Sabbath.
iligtas mo ang iyong sarili at bumaba ka sa krus.”
Gayundin naman, kapag nakita ninyong nangyayari ang mga bagay na ito, alam ninyong iyon ay malapit na, nasa mga pintuan na.
Nang patapos na ang araw na iyon, lumapit ang labindalawa at sinabi sa kanya, “Paalisin mo ang mga tao upang sila'y makapunta sa mga nayon at sa mga lupaing nasa palibot at makahanap ng matutuluyan at makakain, sapagkat tayo'y narito sa isang ilang na dako.”
Nagkaroon ng isang pagtatalo sa kanila kung sino sa kanila ang pinakadakila.
Pagkatapos na siya'y kanilang libakin, inalis nila sa kanya ang kulay-ube na balabal at isinuot sa kanya ang kanyang mga damit. At siya'y kanilang inilabas upang ipako sa krus.
Subalit dahil batid niya ang kanilang iniisip ay sinabi niya sa kanila, “Ang bawat kahariang nahahati laban sa kanyang sarili ay nawawasak at ang bahay na laban sa sarili ay nagigiba.
Subalit paghawak niya sa kanyang kamay, siya'y tumawag at sinabi, “Bata, bumangon ka.”
Ibig siyang hadlangan ni Juan, na nagsasabi, “Ako ang dapat mong bautismuhan, at ikaw pa ang lumalapit sa akin?”
At siya'y nangangaral, na nagsasabi, “Dumarating na kasunod ko ang higit na makapangyarihan kaysa akin; hindi ako karapat-dapat yumukod at magkalag ng tali ng kanyang mga sandalyas.
Siya'y maghahari sa sambahayan ni Jacob magpakailanman at hindi magwawakas ang kanyang kaharian.”
Pagkatapos ay kanilang niluraan siya sa kanyang mukha at siya'y kanilang pinagsusuntok; at sinampal siya ng iba,
Sumakay siya sa bangka kasama nila at tumigil ang hangin. At sila'y lubhang nanggilalas,
at ‘Aalalayan ka ng kanilang mga kamay,
At nang sandaling iyon, ang tabing ng templo ay napunit sa dalawa, mula sa itaas hanggang sa ibaba; nayanig ang lupa; at nabiyak ang mga bato.
Ito'y gawa ng Panginoon,
Sinasabi ko sa inyo, Hindi! Subalit malibang kayo'y magsisi, kayong lahat ay mapapahamak ding tulad nila.”
Kayo'y mga saksi ng mga bagay na ito.
Ang lahat ng mga bagay ay ibinigay sa akin ng aking Ama. Walang nakakakilala sa Anak kundi ang Ama; at walang nakakakilala sa Ama, kundi ang Anak, at sinumang piliin ng Anak na pagpahayagan niya.
At kanilang sinabi sa kanya, “Saan mo gustong ihanda namin ito?”
Nang mga araw na iyon, siya ay nagtungo sa bundok upang manalangin at ginugol ang buong magdamag sa pananalangin sa Diyos.
Ngunit nang mapalabas na ang maraming tao, pumasok siya at hinawakan ang kamay ng batang babae at ito ay bumangon.
At sinasabi ko sa inyo, humingi kayo at kayo'y bibigyan; humanap kayo, at kayo'y makakakita; tumuktok kayo at kayo'y pagbubuksan.
Tunay na sinasabi ko sa inyo, ang sinumang hindi tumanggap sa kaharian ng Diyos na tulad sa isang maliit na bata, ay hindi makakapasok doon.”
Pagkalipas ng mahabang panahon, dumating ang panginoon ng mga aliping iyon, at nakipag-ayos sa kanila.
Sinabi niya sa kanya, ‘Ikaw ay mamamahala sa limang lunsod.’
At siya'y kanilang hinubaran at dinamitan ng isang balabal na pulang-pula.
“Kahabag-habag kayong mga busog ngayon,
“Bumalik ka sa iyong bahay at isalaysay mo ang lahat ng mga ginawa ng Diyos para sa iyo.” At siya'y umalis na ipinahahayag sa buong lunsod ang lahat ng mga ginawa ni Jesus sa kanya.
At kaagad na nawala ang kanyang ketong at siya'y naging malinis.
Pagkatapos, siya'y bumalik mula sa lupain ng Tiro at dumaan sa Sidon patungo sa lawa ng Galilea, na tinahak ang lupain ng Decapolis.
At sinabi ng maraming tao, “Ito ang propetang si Jesus, na taga-Nazaret ng Galilea.
Nang mga araw na iyon ay tumindig si Maria at nagmadaling pumunta sa isang bayan ng Judea, sa lupaing maburol.
Magalak kayo sa araw na iyon at lumukso kayo sa tuwa, sapagkat malaki ang inyong gantimpala sa langit, sapagkat gayundin ang ginawa ng kanilang mga ninuno sa mga propeta.
Madalas na siya'y inihahagis nito sa apoy at sa tubig upang siya'y puksain, ngunit kung mayroon kang bagay na magagawa, maawa ka sa amin at tulungan mo kami.”
Pumunta nga ang mga alagad at ginawa ang ayon sa ipinag-utos ni Jesus sa kanila.
Nang mabautismuhan si Jesus, kaagad siyang umahon sa tubig, at nabuksan sa kanya ang kalangitan, at nakita niya ang Espiritu ng Diyos na bumababang tulad sa isang kalapati, at lumalapag sa kanya.
sapagkat pinatatawad naman namin ang bawat nagkakautang sa amin,
“Gayundin naman, ang kaharian ng langit ay tulad ng isang mangangalakal na naghahanap ng magagandang perlas;
Habang kanilang dinadala siyang papalayo, hinuli nila si Simon na taga-Cirene na nanggaling sa bukid, at ipinasan sa kanya ang krus upang dalhin kasunod ni Jesus.
Sila'y mabubuwal sa pamamagitan ng talim ng tabak at dadalhing bihag sa lahat ng mga bansa. Yuyurakan ang Jerusalem ng mga Hentil, hanggang sa matupad ang mga panahon ng mga Hentil.
“Narinig ninyo na sinabi, ‘Huwag kang mangangalunya.’
Sapagkat madali pa sa isang kamelyo ang pumasok sa butas ng isang karayom, kaysa sa isang taong mayaman na pumasok sa kaharian ng Diyos.”
Nang marinig ito ni Pilato, itinanong niya kung ang taong iyon ay taga-Galilea.
Huwag mong ipanumpa maging ang iyong ulo, sapagkat hindi mo magagawang puti o itim ang isang buhok.
Muli, sa ikalawang pagkakataon, umalis siya at nanalangin, na nagsasabi, “Ama ko, kung hindi maaaring lumampas ito, malibang inumin ko ito, ang iyong kalooban ang siyang mangyari.”
“Bakit nagsasalita ng ganito ang taong ito? Siya'y lumalapastangan! Sino ang makapagpapatawad ng mga kasalanan maliban sa Diyos?”
Ituturo niya sa inyo ang isang malaking silid sa itaas na may mga kagamitan at handa na. At doon ay maghanda kayo para sa atin.”
Nag-usap sila sa isa't isa na nagsasabi, “Hindi kasi tayo nagdala ng tinapay.”
Ang balitang ito tungkol sa kanya ay kumalat sa buong Judea at sa lahat ng nakapaligid na lupain.
Ang lahat ng masasamang bagay na ito ay sa loob nagmumula at nakapagpaparumi sa tao.”
Sumagot si Juan at sinabi sa kanilang lahat, “Binabautismuhan ko kayo ng tubig. Subalit dumarating ang higit na makapangyarihan kaysa akin. Ako'y hindi karapat-dapat magkalag ng panali ng kanyang mga sandalyas. Kayo'y babautismuhan niya sa Espiritu Santo at sa apoy.
at nagsumamo sa kanya, na sinasabi, “Ang aking munting anak na babae ay naghihingalo. Pumaroon ka at ipatong mo ang iyong mga kamay sa kanya upang siya'y gumaling at mabuhay.”
Sapagkat sinumang gumaganap ng kalooban ng Diyos, ay siyang aking kapatid na lalaki, kapatid na babae, at ina.”
At siya'y tumanggap ng isang kopa at nang siya'y makapagpasalamat, sinabi niya, “Kunin ninyo ito, at inyong paghati-hatian.
At sinabi niya sa kanila, “Kailanman ba'y hindi ninyo nabasa ang ginawa ni David nang siya at ang kanyang mga kasamahan ay nagutom at nangailangan ng pagkain?
Huwag kayong magdadala ng lalagyan ng salapi, o supot, o mga sandalyas, at huwag ninyong batiin ang sinuman sa daan.
Kumain silang lahat at nabusog. Kinuha nila ang mga lumabis na pinagputul-putol na tinapay, at napuno ang labindalawang kaing.
Pagkatapos ay sinabi niya sa kanila, “Babangon ang isang bansa laban sa bansa at ang isang kaharian laban sa kaharian.
Sinabi ni Jesus sa kanila, “Itinatanong ko sa inyo, ipinahihintulot ba sa kautusan na gumawa ng mabuti, o gumawa ng masama kung Sabbath? Magligtas ng buhay o pumuksa nito?”
May isang babae na labindalawang taon nang dinudugo,
Subalit sila'y napuno ng matinding galit at pinag-usapan nila kung ano ang maaari nilang gawin kay Jesus.
“Ang bawat humihiwalay sa kanyang asawang babae at nag-asawa ng iba ay nagkakasala ng pangangalunya, at ang nag-aasawa sa babaing hiniwalayan ng kanyang asawa ay nagkakasala ng pangangalunya.
At nang ang mga sugo ay bumalik na sa bahay, nadatnan nilang magaling na ang alipin.
Dapat sana'y inilagak mo ang aking salapi sa mga mangangalakal ng salapi, at nang sa aking pagdating ay matanggap ko kung ano ang akin pati na ang pakinabang.
Nakakita siya ng dalawang bangka na nasa tabi ng lawa; wala na roon ang mga mangingisda at naghuhugas na ng kanilang mga lambat.
Sinasabi ko sa inyo, Hindi! Subalit malibang kayo'y magsisi, mapapahamak din kayong lahat tulad nila.
Kinaumagahan, ang lahat ng mga punong pari at ang matatanda sa bayan ay sama-samang nag-usap laban kay Jesus upang siya'y ipapatay.
Subalit nang hatinggabi na ay may sumigaw, ‘Narito na ang lalaking ikakasal! Lumabas kayo upang salubungin siya.’
“Guro, alin ba ang dakilang utos sa kautusan?”
At sinabi niya sa kanila, “Inilalabas ba ang ilawan upang ilagay sa ilalim ng takalan, o sa ilalim ng higaan, at hindi sa talagang lalagyan ng ilawan?
sapagkat ako'y hinirang niya upang ipangaral ang magandang balita sa mga dukha.
Nang matapos na siya sa pagsasalita ay sinabi niya kay Simon, “Pumunta ka sa malalim at ihulog ninyo ang inyong mga lambat upang makahuli.”
Makipagkasundo ka agad sa nagsakdal sa iyo, habang kasama mo pa siya sa daan; baka ibigay ka ng nagsakdal sa iyo sa hukom, at ibigay ka naman ng hukom sa tanod, at ipasok ka sa bilangguan.
Subalit dahil wala silang makitang daan dahil sa dami ng tao, umakyat sila sa bubungan ng bahay at ibinaba siya pati na ang kanyang higaan mula sa binutas nilang bubungan sa gawing gitna, sa harapan ni Jesus.
At nang malapit na ang oras na ikasiyam ay sumigaw si Jesus ng may malakas na tinig, na sinasabi, “Eli, Eli, lama sabacthani?” na ang kahulugan ay “Diyos ko, Diyos ko, bakit mo ako pinabayaan?”
Siya'y muling nagpasimulang magturo sa tabi ng dagat. At nagtipon sa palibot niya ang napakaraming tao, kaya't siya'y sumakay sa isang bangkang nasa lawa at naupo roon. Ang lahat ng tao ay nasa dalampasigan.
Sapagkat siya at ang lahat ng kanyang kasama ay namangha dahil sa mga isdang kanilang nahuli,
Nang malapit na siya sa libis ng bundok ng mga Olibo, ang lahat ng napakaraming mga alagad ay nagpasimulang magalak at magpuri sa Diyos nang may malakas na tinig dahil sa lahat ng mga makapangyarihang gawa na kanilang nakita,
tuwirin ninyo ang kanyang mga landas.’”
Mag-ingat kayo sa inyong sarili. Kung magkasala ang iyong kapatid, sawayin mo siya, at kung siya'y magsisi, patawarin mo siya.
Sa palagay ba ninyo ay pumarito ako upang magdala ng kapayapaan sa lupa? Hindi! Sinasabi ko sa inyo, sa halip ay pagkakabaha-bahagi.
Gayundin naman kayo, na sa labas ay mistulang matuwid sa mga tao, ngunit sa loob ay punô kayo ng pagkukunwari at kasamaan.
At agad siyang dinala ng Espiritu sa ilang.
At inilayo siya ni Pedro at sinimulang pigilan siya, na sinasabi, “Huwag nawang itulot ng Diyos, Panginoon! Hindi kailanman mangyayari ito sa iyo.”
At tingnan ninyo, ipapadala ko sa inyo ang pangako ng aking Ama, subalit manatili kayo sa lunsod, hanggang sa mabihisan kayo ng kapangyarihang galing sa itaas.”
Dahil sa habag ay hinipo ni Jesus ang kanilang mga mata. Kaagad, nakakita silang muli at sila'y sumunod sa kanya.
