Pumunta sila sa mga punong pari at sa matatanda, at nagsabi, “Kami ay namanata sa ilalim ng mahigpit na sumpa, na hindi titikim ng anumang pagkain hanggang sa mapatay namin si Pablo.
Pinagbubuksan siya ng bantay sa pinto; at pinapakinggan ng mga tupa ang kanyang tinig. Tinatawag niya ang kanyang mga tupa sa pangalan, at sila'y inihahatid papalabas.
[At natupad ang kasulatan, na nagsasabi: At siya'y ibinilang sa mga suwail.]
Pagkatapos ay natagpuan siya ni Jesus sa templo, at sinabi sa kanya, “Tingnan mo, ikaw ay gumaling na; huwag ka nang magkasala, baka may mangyari pa sa iyo na lalong masama.”
At ang nahulog sa mabuting lupa ay sila na pagkatapos marinig ang salita, ay iningatan ito sa isang tapat at mabuting puso at nagbubunga na may pagtitiyaga.
ni hindi rin dahil sila'y binhi ni Abraham ay mga anak na silang lahat, kundi, “Kay Isaac tatawagin ang iyong binhi.”
At ngayon ay wala na ako sa sanlibutan, subalit ang mga ito ay nasa sanlibutan, at ako'y papariyan sa iyo. Amang Banal, ingatan mo sila sa iyong pangalan, sila na ibinigay mo sa akin, upang sila'y maging isa, na gaya naman natin na iisa.
Nagtipun-tipon sa palibot niya ang napakaraming tao, kaya't sumakay siya sa isang bangka at umupo roon samantalang ang lahat ng tao ay nakatayo sa baybayin.
‘Bakit nagalit ang mga Hentil,
Kaagad nilang iniwan ang kanilang mga lambat at sumunod sa kanya.
Sa bawat panig ay pinagmamalupitan kami, subalit hindi nadudurog, nililito subalit hindi nawawalan ng pag-asa;
Sinabi sa kanya ni Jesus, “Ako ang daan, at ang katotohanan, at ang buhay. Sinuman ay hindi makakarating sa Ama kundi sa pamamagitan ko.
Sapagkat ang pangako na kanyang mamanahin ang sanlibutan ay hindi dumating kay Abraham o sa kanyang binhi sa pamamagitan ng kautusan kundi sa pamamagitan ng pagiging matuwid ng pananampalataya.
Aming ginigiba ang mga pangangatuwiran at bawat palalong hadlang laban sa karunungan ng Diyos, at binibihag ang bawat pag-iisip upang sumunod kay Cristo;
Doon ay kanilang ipinako siya at kasama niya ang dalawa pa, isa sa bawat tagiliran, at sa gitna nila ay si Jesus.
Nang maipako ng mga kawal si Jesus, kanilang kinuha ang kanyang mga kasuotan at hinati sa apat na bahagi, sa bawat kawal ay isang bahagi. Gayundin ang tunika, at ang tunika ay walang tahi, na hinabing buo mula sa itaas.
At nang sila'y makarating sa isang dakong tinatawag na Golgota, (na ang kahulugan ay, “Ang Dako ng Bungo”),
upang ako'y maging ministro ni Cristo Jesus sa mga Hentil, na naglilingkod sa banal na gawain sa ebanghelyo ng Diyos, upang ang paghahandog ng mga Hentil ay maging kalugud-lugod, yamang ito'y ginawang banal ng Espiritu Santo.
at ibinigay nila ang mga iyon para sa bukid ng magpapalayok, gaya ng iniutos sa akin ng Panginoon.”
Dapat din kayong maging handa, sapagkat ang Anak ng Tao ay darating sa oras na hindi ninyo inaasahan.”
Sumagot ang mga kawal, “Kailanma'y walang taong nagsalita nang gayon.”
Samantalang sila'y kumakain, dumampot siya ng tinapay, at nang kanyang mabasbasan ay kanyang pinagputul-putol, ibinigay sa kanila at sinabi, “Kunin ninyo; ito ang aking katawan.”
Katotohanang sinasabi ko sa inyo, higit pang mapapagtiisan sa araw ng paghuhukom ang mga lupain ng Sodoma at Gomorra, kaysa bayang iyon.
At kung ito ay magbunga sa susunod na taon, ay mabuti; subalit kung hindi, maaari mo na itong putulin.”
Bumalik siya sa ikatlong pagkakataon at sinabi sa kanila, “Natutulog pa rin ba kayo at nagpapahinga? Tama na! Dumating na ang oras; ang Anak ng Tao ay ipinagkakanulo sa mga kamay ng mga makasalanan.
Gumawa si Jesus ng marami pang ibang mga tanda sa harapan ng kanyang mga alagad, na hindi naisulat sa aklat na ito.
Sinabi sa kanya ni Jesus, “Nasusulat din naman, ‘Huwag mong tutuksuhin ang Panginoon mong Diyos.’”
Sinabi ni Jesus, “Pumarito ako sa sanlibutang ito para sa paghatol, upang ang mga hindi nakakakita ay makakita, at upang ang mga nakakakita ay maging mga bulag.”
Kaya't ang mga nasa Judea ay dapat tumakas patungo sa mga bundok; at ang mga nasa loob ng lunsod ay lumabas, at ang mga nasa labas ng lupain ay huwag pumasok doon;
Dumating naman si Simon Pedro na sumusunod sa kanya, pumasok siya sa libingan at nakita niyang nakalatag ang mga telang lino,
Kinabukasan siya ay tumuloy sa isang bayan na tinatawag na Nain, kasama ang kanyang mga alagad at ang napakaraming tao.
Sila'y umuwi at naghanda ng mga pabango at mga panghaplos. At nang araw ng Sabbath sila'y nagpahinga ayon sa kautusan.
Nang siya'y dumating sa Jerusalem, pinagsikapan niyang makisama sa mga alagad. Silang lahat ay natakot sa kanya sapagkat hindi sila naniniwala na siya'y isang alagad.
Subalit ibig naming marinig sa iyo kung ano ang iyong mga iniisip, sapagkat alam namin na maraming nagsasalita ng laban sa sektang ito sa lahat ng mga lugar.”
Sinumang nagmamataas ay ibababa at sinumang nagpapakababa ay itataas.
Ako'y nasa kanila at ikaw ay nasa akin, upang sila'y maging ganap na isa upang malaman ng sanlibutan na ikaw ang nagsugo sa akin at sila'y iyong minahal kung paanong ako'y iyong minahal.
Ngunit kapag ikaw ay naglilimos, huwag mong hayaang malaman ng iyong kaliwang kamay ang ginagawa ng iyong kanang kamay,
Gaya naman ng sinasabi ni David tungkol sa pagiging mapalad ng tao na itinuturing ng Diyos na matuwid na hiwalay sa gawa:
Marami ang pumunta sa kanya at kanilang sinabi, “Si Juan ay hindi gumawa ng tanda, ngunit lahat ng mga bagay na sinabi ni Juan tungkol sa taong ito ay totoo.”
“Mapapalad ang mga nahahapis, sapagkat sila ay aaliwin.
Ako at ang Ama ay iisa.”
“Huwag ninyong isiping pumarito ako upang sirain ang kautusan o ang mga propeta; pumarito ako hindi upang sirain, kundi upang tuparin ang mga ito.
Sapagkat maging ang kanyang mga kapatid man ay hindi sumampalataya sa kanya.
at nakiusap bilang tulong sa kanila laban kay Pablo, na siya ay ilipat sa Jerusalem. Sila'y nagbabalak ng pananambang upang siya'y patayin sa daan.
Ang mga may pandinig ay makinig.”
Sinabi ng mga Judio, “Magpapakamatay kaya siya sapagkat kanyang sinabi, ‘Sa aking pupuntahan ay hindi kayo makakapunta.’”
tungkol sa kanyang Anak na mula sa binhi ni David ayon sa laman
Nang sumunod na araw ay dumating sila sa Cesarea. Sila'y hinihintay ni Cornelio, at tinipon ang kanyang mga kamag-anak at ang kanyang malalapit na kaibigan.
sapagkat tayo ay mga bahagi ng kanyang katawan.
Nagdilim ang kanilang mga pang-unawa, palibhasa'y nahiwalay sa buhay ng Diyos, dahil sa kanilang kamangmangan, dahil sa katigasan ng kanilang mga puso;
Sapagkat inyong narinig ang uri ng aking dating pamumuhay sa Judaismo, kung paanong marahas kong inusig ang iglesya ng Diyos at sinikap na wasakin ito.
At sinabi niya sa kanila, “Ano ang ibig ninyong gawin ko para sa inyo?”
Dumating ang isa pa, na nagsasabi, ‘Panginoon, narito ang iyong mina na aking itinago sa isang panyo;
Katotohanang sinasabi ko sa inyo, Saanman ipangaral ang ebanghelyo sa buong sanlibutan, ang ginawa ng babaing ito ay sasabihin sa pag-alaala sa kanya.”
Ngunit hindi ko hinahanap ang aking sariling kaluwalhatian. Mayroong isa na humahanap nito at siya ang hukom.
Kaya't kinabukasan, dumating si Agripa at si Bernice na may buong karilagan. Nang pumasok na sila sa bulwagan ng hukuman kasama ang mga punong kapitan at ang mga pangunahin sa bayan, ipinasok si Pablo sa utos ni Festo.
Sinabi niya sa kanila, “Ngunit ngayon, ang mayroong supot ng salapi ay dalhin ito, at gayundin ang supot ng pagkain. At ang walang tabak ay ipagbili niya ang kanyang balabal, at bumili ng isang tabak.
Kaya nga, kung ang buong katawan mo ay punô ng liwanag at walang bahaging madilim, ito'y mapupuno ng liwanag, gaya ng ilawang may liwanag na nagliliwanag sa iyo.”
Sinabi ni Herodes, “Si Juan ay pinugutan ko ng ulo, subalit sino ang taong ito na marami akong naririnig tungkol sa kanya na gayong mga bagay?” At pinagsikapan niyang makita si Jesus.
Sila'y lumapit sa kanya, na nagsasabi, “Mabuhay ang Hari ng mga Judio!” At siya'y kanilang pinagsusuntok.
samantalang kami, bilang aming bahagi, ay mag-uukol ng aming sarili sa pananalangin at sa paglilingkod sa salita.”
Tinanong siya ng maraming tao, “Ano ngayon ang dapat naming gawin?”
Sila'y kanilang dinakip at ibinilanggo hanggang sa kinabukasan sapagkat noon ay gabi na.
Sapagkat sa pagkabuhay nilang muli mula sa mga patay, hindi na sila mag-aasawa, o pag-aasawahin pa; kundi tulad sila ng mga anghel sa langit.
Sapagkat hindi pa nila nauunawaan ang kasulatan na kailangang siya'y bumangon mula sa mga patay.
Ngunit ang kasalanan, pagkakita ng pagkakataon sa pamamagitan ng utos, ay gumawa sa akin ng sari-saring pag-iimbot, sapagkat kung walang kautusan ang kasalanan ay patay.
Samantalang sila'y nag-uusap at nagtatanungan, si Jesus mismo ay lumapit at naglakbay na kasama nila.
Tumingala ang lalaki at nagsabi, “Nakakakita ako ng mga tao, na parang mga punungkahoy na naglalakad.”
Ngunit kayo'y wala sa laman, kundi nasa Espiritu, yamang nananatili sa inyo ang Espiritu ng Diyos. Subalit kung ang sinuma'y walang Espiritu ni Cristo, siya'y hindi sa kanya.
At siya'y lumabas, at umiyak nang buong pait.
Ngunit naglakbay sila mula sa Perga at nakarating sa Antioquia ng Pisidia. At nang araw ng Sabbath, sila'y pumasok sa sinagoga at umupo.
Sinabi naman niya sa kanila, “Hindi pa ba ninyo nauunawaan?”
upang silang lahat ay maging isa. Gaya mo, Ama, na nasa akin at ako'y sa iyo, sana sila'y manatili sa atin, upang ang sanlibutan ay sumampalataya na ako'y sinugo mo.
At narito, siya'y hayag na nagsasalita, at sila'y walang anumang sinasabi sa kanya. Tunay kayang nakikilala ng mga pinuno na ito ang Cristo?
Sumagot si Simon, “Ipanalangin ninyo ako sa Panginoon upang wala sa mga sinabi ninyo ang mangyari sa akin.”
Sila ay nagtaka, namangha at nagsabi, “Tingnan ninyo, hindi ba mga taga-Galilea ang lahat ng mga nagsasalitang ito?
Pagkatapos ay umalis ang mga Fariseo at pinag-uusapan nila kung paano siyang mabibitag sa kanyang pananalita.
na maghahanda ng iyong daan sa harapan mo.’
Samantalang sila'y naroroon, dumating ang panahon ng kanyang panganganak.
Kaya nga sundin natin ang mga bagay na magbubunga ng kapayapaan, at ang mga bagay na makapagpapatibay sa isa't isa.
mapagkumbaba, at nakasakay sa isang asno,
At sumagot si Jesus sa kanya, “Nasusulat, ‘Sambahin mo ang Panginoon mong Diyos, at siya lamang ang iyong paglingkuran.’”
kundi sa bawat bansa ang sinumang may takot sa kanya at gumagawa ng matuwid ay kalugud-lugod sa kanya.
At kung hindi kayo naging tapat sa kayamanan ng iba, sino ang sa inyo'y magbibigay ng sarili ninyong pag-aari.
Sumagot si Jesus, “Hindi ba ninyo nabasa ang ginawa ni David, nang siya at ang mga kasamahan niya ay nagutom?
at ‘minamahal’ ang hindi dating minamahal.”
O paano mong nasasabi sa iyong kapatid, ‘Hayaan mong alisin ko ang puwing sa iyong mata,’ samantalang mayroong troso sa iyong sariling mata?
Doo'y natagpuan niya ang isang lalaki na ang pangalan ay Aeneas na lumpo at walong taon nang nakaratay.
Nang magkagayo'y lumakas ang loob ng lahat, at sila nama'y kumain din.
Nagsikap siyang makita kung sino si Jesus, subalit hindi magawa dahil sa karamihan ng mga tao, sapagkat siya'y pandak.
Kung ako ay isang salarin, at nakagawa ng anumang bagay na karapat-dapat sa kamatayan, hindi ako tatakas sa kamatayan. Ngunit kung walang katotohanan ang mga bagay na ipinagsasakdal nila laban sa akin, walang sinumang makapagbibigay sa akin sa kanila. Dudulog ako kay Cesar.”
Subalit ang Diyos na umaaliw sa nalulungkot ay nagpasigla sa amin sa pamamagitan ng pagdating ni Tito,
Muli, dinala siya ng diyablo sa isang napakataas na bundok at ipinakita sa kanya ang lahat ng mga kaharian sa sanlibutan, at ang karangyaan ng mga ito.
Sinabi niya sa kanila, “Dahil sa katigasan ng inyong puso ay ipinahintulot sa inyo ni Moises na inyong hiwalayan ang inyong mga asawang babae; ngunit buhat sa pasimula ay hindi gayon.
Nagtipon ang mga apostol at ang matatanda upang pag-usapan ang bagay na ito.
Nang magtatanghaling-tapat na, nagdilim sa ibabaw ng buong lupain hanggang sa ikatlo ng hapon,
Tumahimik ang buong kapulungan at kanilang pinakinggan sina Bernabe at Pablo na isinasalaysay ang mga tanda at mga kababalaghang ginawa ng Diyos sa pamamagitan nila sa gitna ng mga Hentil.
Sila'y tumindig, ipinagtabuyan siya sa labas ng bayan at dinala siya hanggang sa taluktok ng burol na kinatatayuan ng kanilang bayan, upang siya'y ihulog nila nang patiwarik.
Sumagot siya at sinabi, “Ang naghahasik ng mabuting binhi ay ang Anak ng Tao.
Sila'y may mga apat na libo; at kanyang pinaalis na sila.
Ngunit ito ay yaong ipinahayag sa pamamagitan ni propeta Joel:
Subalit sinasabi ko sa inyo, na sa araw ng paghuhukom ay pananagutan ng mga tao ang bawat salita na binigkas na walang ingat.
Kami ay binabayo ng malakas na bagyo, kaya't nang sumunod na araw ay nagsimula silang magtapon ng mga kargamento sa dagat.
At muling sinabi niya, “Sa ano ko ihahambing ang kaharian ng Diyos?
Subalit alamin ninyo ito, kung nalalaman ng may-ari ng bahay kung anong oras darating ang magnanakaw, siya'y hindi magpapabayang mapasok ang kanyang bahay.
Sapagkat tayo'y iniligtas sa pamamagitan ng pag-asang ito, ngunit ang pag-asang nakikita ay hindi pag-asa, sapagkat sino nga ang umaasa sa nakikita?
Nang makita nila ito, ipinaalam nila sa kanila ang mga sinabi tungkol sa sanggol na ito;
Nakilala nila na siya nga ang dating nakaupo at namamalimos sa Pintuang Maganda ng templo; at sila'y napuno ng pagtataka at pagkamangha sa nangyari sa kanya.
Sapagkat ang Anak ng Tao ay dumating upang hanapin at iligtas ang nawala.”
Sinagot sila ni Jesus, “Ang turo ko ay hindi akin, kundi sa kanya na nagsugo sa akin.
Ipagkakanulo ng kapatid sa kamatayan ang kapatid at ng ama ang kanyang anak; at maghihimagsik ang mga anak laban sa mga magulang at sila'y ipapapatay.
Kaya't natupad ang sinabi sa pamamagitan ng propeta Jeremias, na sinasabi, “At kinuha nila ang tatlumpung pirasong pilak, ang halaga niya na itinuring na halaga ng ilan sa mga anak ng Israel,
Ngunit ito'y kanilang sinabi upang siya'y subukin, upang sa kanya'y may maiparatang sila. Subalit yumuko si Jesus, at isinulat ang kanyang daliri sa lupa.
Nangingilin kayo ng mga araw, mga buwan, mga panahon, at mga taon.
at nang di nila siya matagpuan, bumalik sila sa Jerusalem upang hanapin siya.
Kung gayon, ang mabuti ba ang nagdala ng kamatayan sa akin? Hindi, kailanman! Kundi ang kasalanan na gumagawa ng kamatayan sa akin sa pamamagitan ng mabuti, upang ang kasalanan ay maihayag na kasalanan, at sa pamamagitan ng utos ay maging lubos na makasalanan.
Hindi ba ipinagbibili ang limang maya sa halagang dalawang sentimos? Isa man sa kanila ay hindi nalilimutan ng Diyos.
Ngunit nang marinig ng mga Fariseo na napatahimik ni Jesus ang mga Saduceo, ay nagtipon sila.
Paglakad niya sa malayu-layo, siya'y nagpatirapa sa lupa at idinalangin na kung maaari ay makalampas sa kanya ang oras.
Sa sinagoga ay may isang lalaki na may espiritu ng karumaldumal na demonyo, at siya'y sumigaw nang malakas na tinig,
Sapagkat ako man ay taong inilagay sa ilalim ng kapangyarihan at may mga kawal na nasasakupan ko. At sinasabi ko sa isa, ‘Humayo ka’ at siya'y humahayo; at sa isa naman, ‘Halika,’ at siya'y lumalapit; at sa aking alipin, ‘Gawin mo ito,’ at ito'y kanyang ginagawa.”
“Hindi nakahihigit ang alagad sa kanyang guro, o ang alipin sa kanyang panginoon.
‘Ang batong itinakuwil ng mga tagapagtayo
Tingnan ninyo ang aking mga kamay at mga paa, sapagkat ako nga ito. Hipuin ninyo ako, at tingnan, sapagkat ang isang espiritu'y walang laman at mga buto, na gaya ng inyong nakikita na nasa akin.”
Dahil dito hinuli ako ng mga Judio sa templo at pinagsikapang ako'y patayin.
Ngunit sinasabi ko sa inyo, higit pang mapapagtiisan sa araw ng paghuhukom ang lupain ng Sodoma kaysa inyo.”
At doo'y sinalubong sila ni Jesus, na nagsasabi, “Kapayapaan ay sumainyo.” At paglapit nila sa kanya ay niyakap ang kanyang mga paa at siya'y sinamba.
Pagkatapos na mahigpit siyang binalaan, kaagad niya itong pinaalis.
Nang unang araw ng sanlinggo ay maagang pumunta sa libingan si Maria Magdalena, samantalang madilim pa, at nakitang ang bato ay naalis na sa libingan.
Ang ilan sa kanyang mga alagad ay nagsabi sa isa't isa, “Ano itong sinasabi niya sa atin, ‘Sandali na lamang, at ako'y hindi na ninyo makikita, at muling sandali pa, at ako'y inyong makikita’ at, ‘Sapagkat ako'y pupunta sa Ama?’”
ngunit nang makita nilang siya'y lumalakad sa ibabaw ng dagat, inakala nilang iyon ay isang multo at sila'y sumigaw;
At kanino nahayag ang bisig ng Panginoon?”
Nang madaling-araw na ay lumapit siya sa kanila na lumalakad sa ibabaw ng dagat.
si Simon, na tinawag niyang Pedro, si Andres na kanyang kapatid, si Santiago, si Juan, si Felipe, si Bartolome,
At sumagot siya, “Sinasabi ko sa inyo na kung tatahimik ang mga ito, ang mga bato'y sisigaw.”
Kinuha niya ang isang maliit na bata at inilagay sa gitna nila. Siya'y kanyang kinalong at sa kanila'y sinabi,
gayundin hindi niya ibinubuka ang kanyang bibig.
Kinaumagahan, nagkatipon ang mga Judio, at nagsabwatan sa pamamagitan ng isang sumpa, na hindi sila kakain ni iinom man hanggang sa kanilang mapatay si Pablo.
Sinabi niya, “Halika.” Kaya't bumaba si Pedro sa bangka at lumakad sa ibabaw ng tubig patungo kay Jesus.
Ngunit ang Jerusalem na nasa itaas ay malaya, na siyang ating ina.
Kaya habang patungo ka sa hukom na kasama ang sa iyo'y nagsakdal, sa daan ay sikapin mo nang makipag-ayos sa kanya, kung hindi ay kakaladkarin ka niya sa hukom, at ibibigay ka ng hukom sa punong-tanod, at ipapasok ka ng punong-tanod sa bilangguan.
at noong ako'y nasa Jerusalem ay ipinagbigay-alam ng mga punong pari at ng matatanda sa mga Judio ang tungkol sa kanya na hinihinging humatol ako laban sa kanya.
Dahil sa paglaganap ng kasamaan, ang pag-ibig ng marami ay lalamig.
baka masaktan ang iyong paa sa isang bato.’”
Sino sa inyo ang makakasumbat sa akin tungkol sa kasalanan? Kung sinasabi ko ang katotohanan, bakit hindi kayo sumasampalataya sa akin?
Ang bawat nakikinig sa mga salita kong ito at hindi ginaganap ang mga ito ay matutulad sa isang taong hangal na nagtayo ng kanyang bahay sa buhanginan.
Huwag kayong magdala ng ginto, o pilak, o tanso sa inyong mga lalagyan ng pera;
At ibabagsak ka sa lupa, ikaw at ang iyong mga anak na nasa iyo. Sa iyo'y hindi sila mag-iiwan ng bato sa ibabaw ng kapwa bato; sapagkat hindi mo kinilala ang panahon ng pagdalaw sa iyo.”
Sa pamamagitan nito ay makikilala ng lahat ng mga tao na kayo ay aking mga alagad, kung kayo'y may pag-ibig sa isa't isa.”
Nang makatawid na sila, dumating sila sa lupain ng Genesaret.
Sinabi ni Pilato sa kanila, “Kunin ninyo siya, at siya'y inyong hatulan ayon sa inyong batas.” Sinabi ng mga Judio sa kanya, “Hindi kami pinahihintulutan na ipapatay ang sinumang tao.”
‘Sa pakikinig kayo'y makakarinig, ngunit kailanma'y hindi makakaunawa,
Nang mag-uumaga na, hinimok silang lahat ni Pablo na kumain, na sinasabi, “Ang araw na ito ang ikalabing-apat na araw na kayo'y naghihintay na walang kinakaing anuman.
Sinabi nila, “Sa bautismo ni Juan.”
Sapagkat sinasabi ko sa inyo, malibang humigit ang inyong katuwiran sa katuwiran ng mga eskriba at mga Fariseo, ay hindi kayo makakapasok sa kaharian ng langit.
Subalit sumama sa kanya ang ilang mga tao at nanampalataya. Isa sa kanila si Dionisio na taga-Areopago, at ang isang babaing ang pangalan ay Damaris at iba pang mga kasama nila.
Bumangon kayo, umalis na tayo. Narito, malapit na ang nagkakanulo sa akin.”
Tungkol sa pagkabuhay niya mula sa mga patay, upang hindi na magbalik sa kabulukan, ay ganito ang sinabi niya,
na di tatanggap ng lalong higit pa sa panahong ito, at sa panahong darating ng buhay na walang hanggan.”
Sapagkat sa panahong iyon ay magkakaroon ng matinding paghihirap na hindi pa nangyayari buhat sa pasimula ng sanlibutan hanggang ngayon, at hindi na mangyayari kailanman.
Kayo ay hindi namin hinihigpitan, subalit kayo ay hinihigpitan ng sarili ninyong damdamin.
“Pagkatapos ay ibibigay kayo sa kapighatian at kayo'y papatayin; at kayo'y kapopootan ng lahat ng mga bansa dahil sa aking pangalan.
Mapalad ang babaing sumampalataya na matutupad ang mga bagay na sinabi sa kanya ng Panginoon.”
Nang sila'y hindi magkaisa, umalis sila pagkasabi ni Pablo ng isang pahayag: “Tama ang Espiritu Santo sa pagsasalita sa inyong mga ninuno sa pamamagitan ni propeta Isaias na sinasabi,
Tumayo si Jesus at sinabi sa kanya, “Babae, nasaan sila? Wala na bang ni isang humatol sa iyo?”
Ako'y naging hangal! Pinilit ninyo ako, sapagkat ako ay dapat ninyong purihin: sapagkat ako'y hindi hamak na mababa sa mga dakilang apostol na iyon, kahit na ako'y walang kabuluhan.
Isinugo niya ang dalawa sa kanyang mga alagad at sa kanila'y sinabi, “Pumunta kayo sa lunsod at doo'y sasalubungin kayo ng isang lalaki na may dalang isang bangang tubig. Sundan ninyo siya.
Anumang sinasabi ko sa inyo sa dilim, sabihin ninyo sa liwanag; at ang narinig ninyo sa bulong ay ipagsigawan ninyo sa ibabaw ng mga bubungan.
at ang daan ng kapayapaan ay hindi nila nakilala.”
Ipinakilala ko sa kanila ang pangalan mo, at aking ipapakilala, upang ang pag-ibig mo sa akin ay mapasakanila, at ako'y sa kanila.”
Nang ipapasok na si Pablo sa himpilan, ay sinabi niya sa pinunong kapitan, “Maaari ba akong makipag-usap sa iyo?”
Kayong mga ahas, kayong lahi ng mga ulupong, paano kayo makakatakas sa kahatulan sa impiyerno?
Sapagkat nasusulat,
Napakarami. Ang una sa lahat, ipinagkatiwala sa kanila ang mga aral ng Diyos.
Sinabi sa kanya ni Pedro, “Bakit kayo'y nagkasundo upang subukin ang Espiritu ng Panginoon? Tingnan mo, nasa pintuan ang mga paa ng mga naglibing sa iyong asawa, at kanilang dadalhin ka sa labas.”
Subalit nang sila'y pumasok ay hindi nila nakita ang bangkay.
at sa pagtingin kayo'y titingin, ngunit kailanma'y hindi makakabatid.
Pagkatapos magsalita ng tinig, si Jesus ay natagpuang nag-iisa. At sila'y nanatiling tahimik at hindi sinabi kanino man ng mga araw na iyon ang alinman sa mga bagay na kanilang nakita.
Nang tumingin sila sa itaas, wala silang nakitang sinuman, maliban kay Jesus.
Ganito ang ibig kong sabihin: ang tagapagmana, habang bata pa ay hindi nakahihigit sa mga alipin bagama't siya ang may-ari ng lahat,
Siya'y itinaas ng Diyos sa kanyang kanang kamay bilang Pinuno at Tagapagligtas, upang bigyan ang Israel ng pagkakataong magsisi, at ng kapatawaran ng mga kasalanan.
na sinasabi, “Pumunta kayo sa katapat na nayon at sa pagpasok ninyo roon, ay makikita ninyo ang isang nakataling batang asno na hindi pa nasasakyan ng tao. Kalagan ninyo iyon at dalhin ninyo rito.
iwan mo roon sa harap ng dambana ang kaloob mo, at humayo ka; makipagkasundo ka muna sa iyong kapatid, at saka ka magbalik at maghandog ng iyong kaloob.
At kahuli-hulihan sa lahat ay namatay ang babae.
Siya na nagligtas sa amin mula sa kakilakilabot na kamatayan at patuloy na magliligtas; sa kanya ay inilalagak namin ang ating pag-asa na muli niya kaming ililigtas.
Ang isang lahing masama at mapangalunya ay humahanap ng tanda, ngunit hindi ito bibigyan ng tanda, maliban sa tanda ni Jonas.” Kanyang iniwan sila at siya ay umalis.
(Pupunta sa bukid ang dalawang lalaki; ang isa'y kukunin at ang isa'y iiwan.)
Nang siya'y pinakiusapan nila na tumigil pa roon ng mas mahabang panahon, ay hindi siya pumayag,
tuwirin ninyo ang kanyang mga landas.
Dahil dito'y minamahal ako ng Ama, sapagkat ibinibigay ko ang aking buhay, upang ito'y kunin kong muli.
Si Zacarias na kanyang ama ay napuno ng Espiritu Santo at sinabi ang propesiyang ito,
Noon ay galit na galit si Herodes sa mga taga-Tiro at taga-Sidon. Kaya't sila'y nagkaisang pumaroon sa kanya, at nang mahikayat na nila si Blasto na katiwala ng hari, ay kanilang ipinakiusap ang pagkakasundo, sapagkat ang lupain nila'y umaasa sa lupain ng hari para sa pagkain.
Nasa kamay niya ang kanyang kalaykay at lilinisin niya ang kanyang giikan. Titipunin niya ang kanyang trigo sa kamalig, subalit ang ipa ay susunugin niya sa apoy na hindi mapapatay.”
Ngunit ang mga iba'y nanlilibak na nagsabi, “Sila'y lasing sa bagong alak.”
Samantalang siya'y nakaupo sa Bundok ng mga Olibo, lumapit sa kanya nang sarilinan ang mga alagad, na nagsasabi, “Sabihin mo sa amin, kailan mangyayari ang mga bagay na ito at ano ang tanda ng iyong pagdating, at ng katapusan ng panahon?
Sinabi ng mga apostol sa Panginoon, “Dagdagan mo ang pananampalataya namin.”
Alam din ni Judas, na sa kanya'y nagkanulo, ang lugar sapagkat madalas na si Jesus ay nakikipagtipon doon kasama ng kanyang mga alagad.
Sapagkat sa pamamagitan ng iyong mga salita ay pawawalang-sala ka at sa pamamagitan ng iyong salita ay mahahatulan ka.”
Una, nagpapasalamat ako sa aking Diyos sa pamamagitan ni Jesu-Cristo tungkol sa inyong lahat, sapagkat ang inyong pananampalataya ay ipinahahayag sa buong daigdig.
Bumalik si Jesus sa Galilea na nasa kapangyarihan ng Espiritu at kumalat ang balita tungkol sa kanya sa palibot ng buong lupain.
bilang katiwala ng kaganapan ng panahon, upang tipunin ang lahat ng mga bagay kay Cristo, ang mga bagay na nasa sangkalangitan, at ang mga bagay na nasa ibabaw ng lupa;
Maganda ang patotoo tungkol sa kanya ng mga kapatid sa Listra at Iconio.
Nang magampanan na nila ang lahat ng mga bagay ayon sa kautusan ng Panginoon, bumalik sila sa Galilea, sa kanilang sariling bayang Nazaret.
Nang lumulubog na ang araw, dinala ng lahat sa kanya ang kanilang mga maysakit na sari-sari ang karamdaman at ipinatong niya ang kanyang mga kamay sa bawat isa sa kanila at sila'y pinagaling.
Sapagkat batid niya na dahil sa inggit ay ipinadakip siya ng mga punong pari.
(Nang marinig ito ng buong bayan at ng mga maniningil ng buwis ay kanilang kinilala ang katuwiran ng Diyos, sapagkat sila ay nagpabautismo sa bautismo ni Juan.
Sapagkat ang bawat humihingi ay tumatanggap; at ang humahanap ay nakakatagpo; at ang tumutuktok ay pinagbubuksan.
sa loob ng halos apatnaraan at limampung taon. Pagkatapos ng mga bagay na ito ay kanyang binigyan sila ng mga hukom hanggang kay Samuel na propeta.
At kaagad, sa ikalawang pagkakataon ay tumilaok ang manok at naalala ni Pedro ang sinabi ni Jesus sa kanya, “Bago tumilaok ang manok ng makalawa ay ipagkakaila mo ako ng tatlong ulit.” Nanlumo siya at tumangis.
Hindi siya Diyos ng mga patay, kundi ng mga buhay; maling-mali kayo.”
At ang biyenang babae ni Simon ay nakahiga na nilalagnat at agad nilang sinabi kay Jesus ang tungkol sa kanya.
Pagkalipas ng labing-apat na taon, muli akong nagtungo sa Jerusalem kasama si Bernabe, at isinama ko rin si Tito.
At nalalaman ko na pagpunta ko sa inyo, ay darating akong puspos ng pagpapala ng ebanghelyo ni Cristo.
sapagkat marami ang sumasaksi ng kasinungalingan laban sa kanya, at ang kanilang mga patotoo ay hindi nagkakatugma.
Ngunit sinasabi ko sa inyo na dumating na si Elias, at siya'y hindi nila kinilala kundi ginawa nila sa kanya ang anumang kanilang naibigan. Gayundin naman ang Anak ng Tao ay malapit nang magdusa sa kanila.”
“Kaya, anumang bagay na ibig ninyong gawin sa inyo ng mga tao, gayon ang gawin ninyo sa kanila; sapagkat ito ang kautusan at ang mga propeta.
Dahil dito iiwan ng lalaki ang kanyang ama at ina, magsasama sila ng kanyang asawa, at ang dalawa ay magiging isang laman.
At sumagot si Jesus sa kanila, “Magkaroon kayo ng pananampalataya sa Diyos.
ngunit ang Diyos na sumisiyasat ng mga puso ay nakakaalam kung ano ang kaisipan ng Espiritu, sapagkat siya ang namamagitan dahil sa mga banal ayon sa kalooban ng Diyos.
Alam ni Jesus na ibinigay na ng Ama ang lahat ng mga bagay sa kanyang mga kamay, at siya'y nanggaling sa Diyos at patungo sa Diyos.
ang kanyang katuwiran ay nananatili magpakailanman.”
Sinabi niya sa kanya, “Tiyakin mong wala kang sasabihin kaninuman kundi pumunta ka at magpakita sa pari at maghandog ka para sa pagkalinis sa iyo ayon sa ipinag-utos ni Moises bilang isang patotoo sa kanila.”
At sa itaas ng kanyang ulo ay inilagay nila ang paratang sa kanya, na nasusulat, “ITO SI JESUS ANG HARI NG MGA JUDIO.”
ni ang kataasan, ni ang kalaliman, ni ang alin pa mang nilalang, ay hindi makapaghihiwalay sa atin sa pag-ibig ng Diyos, na na kay Cristo Jesus na Panginoon natin.
Pagkatapos ay humingi sila ng hari at ibinigay sa kanila ng Diyos si Saulo na anak ni Kish na isang lalaki sa lipi ni Benjamin na naghari sa loob ng apatnapung taon.
Sapagkat may kagalakan ninyong pinagtitiisan ang mga hangal, palibhasa'y marurunong kayo!
“Katotohanang sinasabi ko sa inyo, ang pumapasok sa hindi pintuan ng kulungan ng mga tupa kundi umaakyat sa ibang daan, ang taong iyon ay tulisan at magnanakaw.
At ako naman sa aking sarili ay naniniwalang lubos tungkol sa inyo, mga kapatid ko, na kayo man ay punung-puno ng kabutihan, pinuspos ng lahat ng kaalaman, na may kakayahang magturo sa isa't isa.
at ang dalawa ay magiging isang laman!’ Kaya't hindi na sila dalawa, kundi isang laman.
at sinabi sa kanila, “Bakit kayo natutulog? Bumangon kayo at manalangin, upang hindi kayo pumasok sa tukso.”
Dahil dito'y hinayaan sila ng Diyos sa mga mahahalay na pagnanasa. Ipinagpalit ng kanilang mga babae ang likas na pakikipagtalik sa di-likas.
at natutulog at bumabangon siya sa gabi at araw. Sumisibol at lumalaki ang binhi na hindi niya nalalaman kung paano.
Nalalaman ninyo ang salita na kanyang ipinadala sa mga anak ni Israel, na ipinangangaral ang magandang balita ng kapayapaan sa pamamagitan ni Jesu-Cristo—siya'y Panginoon ng lahat,
At ipinasiya ni Pilato na ipagkaloob ang kanilang hinihingi.
Ngunit nang marinig ito ng mga Fariseo ay sinabi nila, “Ang taong ito'y nagpapalayas ng mga demonyo sa pamamagitan lamang ni Beelzebul na pinuno ng mga demonyo.”
Hinuli naman ng iba ang kanyang mga alipin at ginawan ng masama at pinagpapatay.
Nagbigay siya sa kanila ng isa pang talinghaga, na sinasabi, “Ang kaharian ng langit ay tulad sa isang taong naghasik ng mabuting binhi sa kanyang bukid.
Sumagot si Jesus, “Siya iyong aking bibigyan ng tinapay pagkatapos na maisawsaw ko ito.” Kaya't nang maisawsaw niya ang tinapay, ay kinuha niya at ibinigay niya kay Judas, na anak ni Simon Iscariote.
Sinabi niya sa mga alagad, “Darating ang mga araw na hahangarin ninyong makita ang isa sa mga araw ng Anak ng Tao at hindi ninyo ito makikita.
Sa ikalawang pagkakataon ay sinabi niya sa kanya, “Simon, anak ni Juan, minamahal mo ba ako?” Sinabi niya sa kanya, “Opo, Panginoon; nalalaman mo na minamahal kita.” Sinabi niya sa kanya, “Alagaan mo ang aking mga tupa.”
Kaya huwag kayong mabalisa, na magsasabing, ‘Ano ang aming kakainin?’ o, ‘Ano ang aming iinumin?’ o, ‘Ano ang aming isusuot?’
na naglilingkod sa Panginoon ng buong kapakumbabaan at may luha, at may mga pagsubok na dumating sa akin dahil sa mga pagtatangka ng mga Judio.
Nakatayong nanonood ang taong-bayan. Subalit tinutuya naman siya ng mga pinuno, na sinasabi, “Iniligtas niya ang iba, iligtas niya ang kanyang sarili kung siya ang Cristo ng Diyos, ang Pinili.”
Sumagot sila, “Si Jesus na taga-Nazaret.” Sinabi sa kanila ni Jesus, “Ako nga iyon.” Si Judas na nagkanulo sa kanya ay nakatayong kasama nila.
Ngunit siya'y nagsimulang magmura at sumumpa, “Hindi ko nakikilala ang taong ito na inyong sinasabi.”
“Ang kanilang hapag nawa'y maging isang silo, isang bitag,
“O, ‘Sino ang mananaog sa kailaliman?’” (Ito ay upang iakyat si Cristo mula sa mga patay.)
Bagaman ako ang pinakahamak sa lahat ng mga banal, ang biyayang ito ay ibinigay sa akin upang ipangaral sa mga Hentil ang mga di-masukat na mga kayamanan ni Cristo;
hanggang sa lumitaw ang isang hari sa Ehipto na hindi nakakakilala kay Jose.
Walang sinuman sa atin ang nabubuhay sa kanyang sarili, at walang sinumang namamatay sa kanyang sarili.
maliban sa isang bagay na ito na aking isinigaw habang nakatayo sa gitna nila, ‘Tungkol sa pagkabuhay ng mga patay ako'y nililitis sa harapan mo sa araw na ito.’”
Ama, luwalhatiin mo ang iyong pangalan.” At dumating ang isang tinig mula sa langit, “Niluwalhati ko na, at muli kong luluwalhatiin.”
Habang sinasabi niya ang mga bagay na ito sa kanyang pagtatanggol, ay sinabi ni Festo nang may malakas na tinig, “Pablo, ikaw ay baliw; ang labis mong karunungan ay siyang nagpapabaliw sa iyo!”
Nang mahalata ni Jesus na sila'y lalapit at pipilitin siyang gawing hari, siya'y muling umalis na nag-iisa patungo sa bundok.
‘Sinabi ng Panginoon sa aking Panginoon,
At siya'y nanatili roon ng isang taon at anim na buwan, na itinuturo sa kanila ang salita ng Diyos.
Sapagkat papanaw ang Anak ng Tao, ayon sa nasusulat tungkol sa kanya, ngunit kahabag-habag ang taong iyon na sa pamamagitan niya ay ipinagkakanulo ang Anak ng Tao! Mabuti pa sa taong iyon ang hindi na siya ipinanganak.”
Siya ay dumating bilang saksi, upang magpatotoo tungkol sa ilaw, upang sa pamamagitan niya'y sumampalataya ang lahat.
Walang naglalagay ng bagong alak sa mga lumang sisidlang balat. Kapag gayon, papuputukin ng alak ang mga balat at matatapon ang alak at masisira ang mga sisidlang balat. Sa halip, ang bagong alak ay inilalagay sa mga bagong sisidlang balat.”
Nang sama-samang lumapit sa kanya ang mga Fariseo at ang ilan sa mga eskriba na nanggaling sa Jerusalem,
Namangha ang mga Judio, na nagsasabi, “Paanong nagkaroon ang taong ito ng karunungan, gayong hindi naman nag-aral kailanman?”
Bumagsak siya sa lupa at nakarinig ng isang tinig na sa kanya'y nagsasabi, “Saulo, Saulo, bakit mo ako inuusig?”
At sila'y kanyang binautismuhan sa ilog ng Jordan, na ipinahahayag nila ang kanilang mga kasalanan.
“Sandali na lamang, at ako'y hindi na ninyo makikita, at muling sandali pa, at ako'y inyong makikita.”
Nang masabi ni Jesus ang mga salitang ito, siya'y umalis na kasama ng kanyang mga alagad na tumawid sa libis ng Cedron, patungo sa isang pook na may isang halamanan, na pinasok niya at ng kanyang mga alagad.
Sumagot sa kanila si Jesus, “Hindi ba pinili ko kayo, ang labindalawa, at ang isa sa inyo ay diyablo?”
Ngunit tatanggap kayo ng kapangyarihan pagbaba sa inyo ng Espiritu Santo; at kayo'y magiging mga saksi ko sa Jerusalem, sa buong Judea at Samaria, at hanggang sa kadulu-duluhang bahagi ng lupa.”
Sinabi ng isa sa mga alipin ng pinakapunong pari, na kamag-anak ng tinagpasan ni Pedro ng tainga, “Hindi ba ikaw ang nakita kong kasama niya sa halamanan?”
“Humingi kayo, at kayo ay bibigyan; humanap kayo, at kayo ay makakatagpo, tumuktok kayo, at kayo'y pagbubuksan.
Ngunit walang makakapasok sa bahay ng malakas na tao upang samsamin ang kanyang mga ari-arian, malibang gapusin muna niya ang malakas na tao; at kung magkagayo'y malolooban niya ang bahay nito.
Sapagkat sinabi ni Moises, ‘Igalang mo ang iyong ama at ang iyong ina,’ at ‘Ang sinumang lumait sa ama o sa ina ay dapat patayin!’
Ngunit wala silang naunawaan sa mga bagay na ito. Ang salitang ito ay naikubli sa kanila, at hindi nila naunawaan ang sinabi.
inilagay rin niya ang kanyang tatak sa amin, at ibinigay sa amin ang Espiritu sa aming mga puso bilang paunang bayad.
Kami nama'y kanilang binigyan ng maraming parangal; at nang maglalayag na kami ay kanilang isinakay sa barko ang mga bagay na kailangan namin.
Siya'y nakita ng lahat ng mga naninirahan sa Lidda at sa Sharon, at sila'y bumaling sa Panginoon.
At ang nasa bukid ay huwag nang bumalik upang kunin ang kanyang balabal.
Kayo'y magsalita sa isa't isa sa mga awit at mga himno at mga awiting espirituwal, na sa inyong mga puso ay nag-aawitan at gumagawa ng himig sa Panginoon,
Sumagot si Jesus, “Kung ako ma'y nagpapatotoo tungkol sa aking sarili, ang aking patotoo ay totoo; sapagkat nalalaman ko kung saan ako nanggaling, at kung saan ako pupunta. Subalit hindi ninyo nalalaman kung saan ako nanggaling, o kung saan ako pupunta.
Doon ay nakatagpo kami ng mga kapatid, at kami'y pinakiusapan nilang tumigil sa kanila sa loob ng pitong araw. Sa gayo'y nakarating kami sa Roma.
Siya ang pinatotohanan ng lahat ng mga propeta, na ang bawat sumasampalataya sa kanya ay makakatanggap ng kapatawaran sa mga kasalanan sa pamamagitan ng kanyang pangalan.”
Sinabi ng mga Fariseo sa isa't isa, “Tingnan ninyo, wala kayong magagawa. Ang sanlibutan ay sumusunod sa kanya.”
Mga minamahal, huwag ninyong ipaghiganti ang inyong sarili, kundi ipaubaya iyon sa galit ng Diyos; sapagkat nasusulat, “Akin ang paghihiganti; ako ang gaganti, sabi ng Panginoon.”
Wala pang umakyat sa langit, maliban sa kanya na bumabang galing sa langit, ang Anak ng Tao.
Pagkatapos na magkaroon sina Pablo at Bernabe ng hindi maliit na pakikipagtalo at pakikipagsalungatan sa kanila, sina Pablo at Bernabe, at ang ilan sa iba pa ay inatasang pumunta sa Jerusalem, upang talakayin ang suliraning ito sa mga apostol at sa matatanda.
Pagkatapos ay iniutos niya sa kanila na paupuin silang lahat nang pangkat-pangkat sa luntiang damo.
“Nang siya'y apatnapung taong gulang na, naisipan niyang dalawin ang kanyang mga kapatid, na mga anak ni Israel.
Ngunit sumunod si Pedro sa kanya ng may kalayuan, hanggang sa bakuran ng pinakapunong pari. Siya'y pumasok, at umupong kasama ng mga tanod upang makita niya kung ano ang mangyayari.
Yamang marami ang nagsikap mag-ayos ng isang kasaysayan tungkol sa mga bagay na naganap sa gitna natin,
Gayundin naman ang kopa, pagkatapos ng hapunan, na sinasabi, “Ang kopang ito na nabubuhos nang dahil sa inyo ay ang bagong tipan sa aking dugo.
Tumayo nga siya, agad na dinampot ang higaan at umalis sa harapan nilang lahat. Anupa't namangha silang lahat at niluwalhati nila ang Diyos, na nagsasabi, “Kailanma'y hindi pa tayo nakakita ng ganito!”
Kaya't dumating ang mga kawal at binali ang binti ng una at ng isa pa na ipinako sa krus na kasama niya.
At naalala nila ang kanyang mga salita,
‘At ikaw, Bethlehem, sa lupain ng Juda,
Tinawag din siya ni David na Panginoon; kaya't paano siyang magiging anak ni David?” At ang napakaraming tao ay tuwang-tuwa na nakikinig sa kanya.
At kung matagpuan niya ito ay katotohanang sinasabi ko sa inyo, magagalak siya rito nang higit kaysa siyamnapu't siyam na hindi naligaw.
Kinabukasan ay nakita ng mga taong nakatayo sa kabilang pampang ng dagat na doo'y walang ibang bangka maliban sa isa. Nakita rin nila na hindi sumakay sa bangka si Jesus na kasama ng kanyang mga alagad, kundi ang kanyang mga alagad lamang ang umalis.
“Ang sinumang tumatanggap sa isa sa mga ganitong bata sa aking pangalan, ako ang tinatanggap at ang sinumang tumatanggap sa akin ay hindi ako ang tinatanggap, kundi ang nagsugo sa akin.”
Nang dumating ang tanghaling tapat, nagdilim sa buong lupain hanggang sa ikatlo ng hapon.
Subalit kung sasabihin natin, ‘Mula sa mga tao,’ ay babatuhin tayo ng mga taong-bayan, sapagkat sila'y napapaniwala na si Juan ay isang propeta.”
Gayundin, ang tumanggap ng dalawa ay nakinabang pa ng dalawa.
Gumawa ang Diyos ng mga di-pangkaraniwang himala sa pamamagitan ng mga kamay ni Pablo,
Dahil dito'y tinawag nilang muli ang taong dating bulag, at sinabi sa kanya, “Luwalhatiin mo ang Diyos. Nalalaman naming makasalanan ang taong ito.”
Nang mga araw ngang ito ay may lumusong sa Antioquia na mga propetang galing sa Jerusalem.
Samantalang nasa ibaba si Pedro, sa patyo, lumapit ang isa sa mga alilang babae ng pinakapunong pari.
Ngunit nang malaman ni Jesus ay sinabi niya sa kanila, “Bakit ninyo ginugulo ang babae? Sapagkat gumawa siya sa akin ng isang mabuting bagay.
Sapagkat nalalaman ng hari ang mga bagay na ito, at sa kanya'y nagsasalita ako ng buong laya, sapagkat naniniwala ako na sa kanya'y walang nalilingid sa mga bagay na ito; sapagkat ito'y hindi ginawa sa isang sulok.
Subalit hindi nagtagal at bumulusok ang isang maunos na hangin na tinatawag na Euraclidon.
Nang magkagayo'y sumama ang kapitan sa bantay ng templo at sila'y dinala ngunit walang dahas, sapagkat natatakot na baka sila'y batuhin ng taong-bayan.
At nang sandaling iyon, ang tabing ng templo ay napunit sa dalawa, mula sa itaas hanggang sa ibaba; nayanig ang lupa; at nabiyak ang mga bato.
Subalit kinuha siya ni Bernabe, iniharap siya sa mga apostol, isinalaysay sa kanila kung paanong nakita niya sa daan ang Panginoon, na nakipag-usap sa kanya, at kung paanong siya'y nangaral sa Damasco na may katapangan sa pangalan ni Jesus.
Pagkatapos ay sinabi niya sa lalaki, “Iunat mo ang iyong kamay.” At iniunat nga niya, at naibalik ito sa dati, magaling na gaya ng isa.
“Sino sa inyo, na mayroong aliping nag-aararo o nag-aalaga ng mga tupa ang magsasabi sa kanya pagkagaling sa bukid, ‘Pumarito ka agad at maupo sa hapag ng pagkain.’
Subalit sila'y nagtakip ng kanilang mga tainga at sumigaw nang malakas at sama-samang sinugod siya.
Nang sina Silas at Timoteo ay dumating mula sa Macedonia, si Pablo ay naging abala sa pangangaral at pinatotohanan sa mga Judio na ang Cristo ay si Jesus.
Nang makita ito ng maraming tao, sila ay natakot at niluwalhati nila ang Diyos, na nagbigay ng gayong awtoridad sa mga tao.
Walang nag-aalis nito sa akin, kundi kusa kong ibinibigay. May kapangyarihan akong ibigay ito, at may kapangyarihan akong kunin itong muli. Tinanggap ko ang utos na ito mula sa aking Ama.”
Pagkatapos ng halos tatlong oras na pagitan, pumasok ang kanyang asawa na hindi nalalaman ang nangyari.
Inyo bang naranasan ang maraming bagay ng walang kabuluhan?—kung tunay nga na ito ay walang kabuluhan.
“Mapapalad kayong mga dukha,
Si Jesus ay sumigaw ng malakas at nagsabi, “Ama, sa mga kamay mo ay inihahabilin ko ang aking espiritu.” At pagkasabi nito ay nalagot ang kanyang hininga.
Sinuman ay hindi nagtatagpi ng bagong tela sa lumang damit; sapagkat binabatak ng tagpi ang damit at lumalala ang punit.
Bakit mo nakikita ang puwing na nasa mata ng iyong kapatid, ngunit hindi mo pinapansin ang troso na nasa iyong sariling mata?
Sinasabi ng kanyang mga alagad, “Oo nga, ngayo'y nagsasalita kang malinaw, at hindi patalinghaga.
Dinala si Jesus ng mga kawal ng gobernador sa Pretorio at tinipon nila ang buong pangkat ng mga kawal sa paligid niya.
“Sa panahong kanais-nais ay pinakinggan kita,
ay may pagkakaisa naming ipinasiya na humirang ng mga lalaki at isugo sila sa inyo na kasama ng aming mga minamahal na sina Bernabe at Pablo,
Ngunit sinasabi ko sa inyo, isang higit na dakila kaysa templo ang narito.
Sinabi niya rito, “Wala nang sinumang makakakain pa ng bunga mula sa iyo.” Ito'y narinig ng kanyang mga alagad.
Sumagot si Jesus, “Sinasabi mo ba ito mula sa iyong sarili, o may ibang nagsabi sa iyo tungkol sa akin?”
Pagkatapos ay lilitaw ang tanda ng Anak ng Tao sa langit, at tatangis ang lahat ng mga lipi sa lupa, at makikita nila ang Anak ng Tao na dumarating na nasa mga ulap ng langit na may kapangyarihan at dakilang kaluwalhatian.
Nang marinig nila ito, sila'y napoot at ninais na sila'y patayin.
Kayo ang mga anak ng mga propeta, at ng tipan na ibinigay ng Diyos sa inyong mga ninuno, na sinasabi kay Abraham, ‘At sa pamamagitan ng iyong binhi ay pagpapalain ang lahat ng mga angkan sa lupa.’
Sinabi sa kanya ni Tomas, “Panginoon, hindi namin alam kung saan ka pupunta. Paano namin malalaman ang daan?”
At silang lahat ay nag-iyakan, niyakap si Pablo at siya'y hinagkan,
Kaya't sinabi sa kanila ni Jesus, “Ibigay ninyo kay Cesar ang kay Cesar at sa Diyos ang sa Diyos.” At sila'y namangha sa kanya.
At anong pagkakasundo mayroon si Cristo kay Belial? O anong bahagi mayroon ang mananampalataya sa hindi mananampalataya?
Pagkatapos ng mga bagay na ito ay nagpakitang muli si Jesus sa mga alagad sa tabi ng dagat ng Tiberias, at siya'y nagpakita sa ganitong paraan.
at lagi kong hinihiling sa anumang paraan sa pamamagitan ng kalooban ng Diyos, na makapunta sa inyo.
Samantalang siya'y nananalangin, ang anyo ng kanyang mukha ay nagbago at ang kanyang damit ay naging nakasisilaw na puti.
Ang lahat ng ibinibigay sa akin ng Ama ay lalapit sa akin; at ang lumalapit sa akin kailanman ay hindi ko itataboy.
at ang aking balabal ay kanilang pinagpalabunutan.”
pagkainggit, paglalasing, kalayawan, at ang mga katulad nito. Binabalaan ko kayo, gaya ng aking pagbabala noong una sa inyo, na ang mga gumagawa ng gayong mga bagay ay hindi magmamana ng kaharian ng Diyos.
Nang matapos na silang magsalita ay sumagot si Santiago, “Mga kapatid, pakinggan ninyo ako.
Sinabi nila, “Ano ang ibig niyang sabihin na, ‘Sandali na lamang?’ Hindi natin alam kung ano ang sinasabi niya.”
Gayundin naman ang mga nahasik sa batuhan, nang marinig nila ang salita, agad nila itong tinanggap na may galak;
Ngunit ayaw niya. Siya'y umalis at ipinabilanggo ang kapwa alipin hanggang sa mabayaran nito ang utang.
Ngunit darating ang mga araw na kukunin sa kanila ang lalaking ikakasal at kung magkagayo'y mag-aayuno sila sa araw na iyon.
Sumagot si Jesus sa kanya, “Kung ang isang tao ay nagmamahal sa akin, ay kanyang tutuparin ang aking salita, at siya'y mamahalin ng aking Ama, at kami'y lalapit sa kanya, at kami'y gagawa ng tahanang kasama siya.
Kapag inuusig nila kayo sa isang bayan, tumakas kayo tungo sa kasunod, sapagkat katotohanang sinasabi ko sa inyo, ‘Hindi ninyo mapupuntahan lahat ang mga bayan ng Israel, bago dumating ang Anak ng Tao.’
Nang mabalitaan niya na si Jesus ay dumating sa Galilea mula sa Judea, pumunta siya roon at nakiusap sa kanya na siya'y pumunta at pagalingin ang kanyang anak na lalaki sapagkat siya'y malapit nang mamatay.
Sapagkat ang hindi magawa ng kautusan, yamang ito ay pinahina ng laman, ay ginawa ng Diyos sa pagsusugo sa kanyang sariling Anak sa anyo ng makasalanang laman, at tungkol sa kasalanan ay hinatulan niya ang kasalanan sa laman,
Sapagkat ang lahat na umaasa sa mga gawa ng kautusan ay nasa ilalim ng sumpa; sapagkat nasusulat, “Sumpain ang bawat isang hindi sumusunod sa lahat ng bagay na nasusulat sa aklat ng kautusan.”
Nang makita ito ng mga alagad ay nagtaka sila, na nagsasabi, “Paanong natuyo kaagad ang puno ng igos?”
Sa gayo'y lumago at lubos na nanaig ang salita ng Panginoon.
Kaya't ang lumalaban sa may kapangyarihan ay lumalaban sa itinalaga ng Diyos; at ang mga lumalaban ay tatanggap ng kahatulan sa kanilang sarili.
Ang paghikayat na iyon ay hindi nagmula sa tumatawag sa inyo.
Napuno ng kaguluhan ang lunsod at sama-sama nilang nilusob ang tanghalan, at sinunggaban sina Gayo at Aristarco, mga taga-Macedonia, na kasama ni Pablo sa paglalakbay.
Ano nga kung makita ninyong umaakyat ang Anak ng Tao sa kinaroroonan niya nang una?
Ngayon kung ang pagkahulog nila ay siyang kayamanan ng sanlibutan, at ang pagkalugi nila ay siyang kayamanan ng mga Hentil, gaano pa kaya ang lubos na panunumbalik nila?
Nagpakita sa kanya ang isang anghel ng Panginoon na nakatayo sa gawing kanan ng dambana ng insenso.
Sapagkat kayo'y binigyan ko ng halimbawa, upang gawin din ninyo ayon sa ginawa ko sa inyo.
Si Juan ay nagsusuot ng damit na yari sa balahibo ng kamelyo at ng isang pamigkis na balat sa kanyang baywang. Ang kanyang pagkain ay mga balang at pulot-pukyutan.
“Ngayon, ito ang talinghaga: Ang binhi ay ang salita ng Diyos.
upang ipahayag ang taon ng biyaya mula sa Panginoon.”
Ngunit kung ang hindi ko nais ang siya kong ginagawa, sumasang-ayon ako na mabuti ang kautusan.
Gayundin naman kayo, kapag nakita ninyong nangyayari ang mga bagay na ito, nalalaman ninyo na malapit na ang kaharian ng Diyos.
“Huwag kayong humatol at hindi kayo hahatulan. Huwag kayong humusga at hindi kayo huhusgahan. Magpatawad kayo at kayo'y patatawarin.
At kanilang ibibigay siya sa mga Hentil upang kutyain, hagupitin at ipako sa krus; at siya'y muling mabubuhay sa ikatlong araw.”
Isusugo niya ang kanyang mga anghel na may malakas na tunog ng trumpeta at kanilang titipunin ang kanyang mga hinirang mula sa apat na hangin, mula sa isang dulo ng langit hanggang sa kabila.
Dinala nila si Jesus sa pinakapunong pari at nagtipon ang lahat ng mga punong pari, matatanda at mga eskriba.
Nang sumunod na araw, dumukot siya ng dalawang denario at ibinigay sa may-ari ng bahay-panuluyan at sinabi niya, ‘Alagaan mo siya, at sa anumang karagdagan mo pang gastusin ay babayaran kita sa aking pagbabalik.’
“Narito, ipinapadala ko ang aking sugo sa iyong unahan,
Samantalang naglilingkod siya sa Diyos bilang pari at ang kanyang pangkat ang nanunungkulan,
Bakit hindi ninyo nauunawaan ang aking sinasabi? Sapagkat hindi ninyo matanggap ang aking salita.
At ang pito ay walang iniwang anak. Sa kahuli-hulihan, ang babae naman ang namatay.
Siya ang ilawang nagniningas at lumiliwanag, at ninais ninyong kayo'y magalak sumandali sa kanyang liwanag.
Kaya't sinabi sa kanya ni Pilato, “Ayaw mong makipag-usap sa akin? Hindi mo ba alam na ako'y may kapangyarihang ikaw ay pakawalan at may kapangyarihang ikaw ay ipako sa krus?”
sa araw na ito ay naging anak kita.’
Anupa't kami ay nakiusap kay Tito na yamang siya'y nagpasimula ay dapat din niyang tapusin sa inyo ang biyayang ito.
At habang binabasbasan niya sila, kanyang iniwan sila [at dinala siya paitaas sa langit].
O hindi ba ninyo nabasa sa kautusan, kung paanong sa mga araw ng Sabbath ay winalang-galang ng mga pari sa templo ang Sabbath, at hindi sila nagkasala?
Sila ay sumigaw na nagsasabi, “Anong gagawin mo sa amin, O Anak ng Diyos? Naparito ka ba upang pahirapan kami bago dumating ang takdang panahon?”
Ako ang nagpapatotoo tungkol sa aking sarili, at ang Amang nagsugo sa akin ay nagpapatotoo tungkol sa akin.”
“Sino nga ba ang tapat at matalinong alipin na inatasan ng kanyang panginoon na pangasiwaan ang kanyang sambahayan, upang magbigay sa kanila ng pagkain sa tamang panahon?
Kaya't ang mga di-tuli sa laman, subalit tumutupad ng kautusan, ay hahatol sa iyo na may kautusang nakasulat at may pagtutuli ngunit sumusuway sa kautusan.
Sapagkat ang poot ng Diyos ay nahahayag mula sa langit laban sa lahat ng kalikuan at kasamaan ng mga tao, na sa pamamagitan ng kanilang kasamaan ay pinipigil ang katotohanan.
Hindi nila naunawaan na siya ay nagsasalita sa kanila tungkol sa Ama.
Mga kapatid, ang nais ng aking puso at ang dalangin ko sa Diyos alang-alang sa kanila ay ang sila ay maligtas.
sapagkat mas marami pa ang mga anak ng pinabayaan
Mula ng panahong iyon ay pinasimulan ni Jesus na ipaliwanag sa kanyang mga alagad na kailangang pumunta siya sa Jerusalem at magtiis ng maraming bagay sa kamay ng matatanda, ng mga punong pari at mga eskriba. Siya'y papatayin at muling bubuhayin sa ikatlong araw.
Sapagkat kami ay lumalakad sa pamamagitan ng pananampalataya, hindi sa pamamagitan ng paningin.
darating ang panginoon ng aliping iyon sa araw na hindi niya inaasahan, at sa oras na hindi niya nalalaman,
Siyang mayroon ng aking mga utos at tinutupad ang mga iyon ay siyang nagmamahal sa akin, at ang nagmamahal sa akin ay mamahalin ng aking Ama, at siya'y mamahalin ko, at ihahayag ko ang aking sarili sa kanya.”
At sinabi niya sa kanila, “Sa inyo ipinagkaloob ang hiwaga ng kaharian ng Diyos, ngunit sa kanilang nasa labas, ang lahat ng mga bagay ay ginagawa sa mga talinghaga;
Ang mga bagay na ito ay iniuutos ko sa inyo, upang kayo'y magmahalan sa isa't isa.
at ang mga pinahirapan ng masasamang espiritu ay pinagaling.
Sinabi sa kanya ni Jesus, “Ako ang muling pagkabuhay at ang buhay. Ang sumasampalataya sa akin, bagama't siya'y mamatay, ay mabubuhay.
At dumating ang mga tao upang tingnan ang nangyari. Lumapit sila kay Jesus at kanilang nadatnan ang taong nilisan ng mga demonyo na nakaupo sa paanan ni Jesus na may damit at matino ang pag-iisip nito; at sila'y natakot.
Higit ka bang dakila kaysa sa aming amang si Jacob na sa ami'y nagbigay ng balon, at dito'y uminom siya, pati ang kanyang mga anak, at ang kanyang mga hayop?”
Ngunit ano ang pinuntahan ninyo upang makita? Isa bang propeta? Oo, sinasabi ko sa inyo, at higit pa kaysa isang propeta.
Subalit dahil sa mga huwad na kapatid na lihim na ipinasok, na pumasok upang tiktikan ang kalayaan na taglay namin kay Cristo Jesus, upang kami'y alipinin—
Samantalang ang mga tao'y naghihintay, nagtatanong ang lahat sa kanilang mga puso tungkol kay Juan, kung siya ang Cristo.
Sinabi sa kanila ni Jesus, “Kayong lahat ay tatalikod sapagkat nasusulat, ‘Hahampasin ko ang pastol at kakalat ang mga tupa.’
Kaya, alang-alang kay Cristo, ako'y nasisiyahan sa mga kahinaan, paglait, kahirapan, pag-uusig, at mga sakuna, sapagkat kapag ako'y mahina, ako nga'y malakas.
Ngunit upang malaman ninyo na ang Anak ng Tao ay may awtoridad sa ibabaw ng lupa na magpatawad ng mga kasalanan,”—sinabi niya ito sa lumpo, “Sinasabi ko sa iyo, tumindig ka, buhatin mo ang iyong higaan, at umuwi ka sa bahay mo.”
Sapagkat ang kabayaran ng kasalanan ay kamatayan; ngunit ang kaloob ng Diyos na walang bayad ay buhay na walang hanggan kay Cristo Jesus na Panginoon natin.
Ang mga kumain ng mga tinapay ay limang libong lalaki.
na nagsasabi, “Ipahayag mo sa amin, ikaw na Cristo! Sino ang sumuntok sa iyo?”
Si Judas Iscariote naman, na isa sa labindalawa, ay nagpunta sa mga punong pari upang maipagkanulo siya sa kanila.
Ang mula sa Diyos ay nakikinig ng mga salita ng Diyos. Ang dahilan kung bakit hindi ninyo pinakikinggan ang mga ito ay sapagkat kayo'y hindi mula sa Diyos.”
sapagkat sa iyo manggagaling ang isang pinuno,
Ang mga bagay na ito ay sinabi ko sa inyo upang ang aking kagalakan ay mapasainyo, at ang inyong kagalakan ay malubos.
Si Pedro ay lumabas, at sumunod sa kanya. Hindi niya alam na tunay ang nangyayari sa pamamagitan ng anghel, ang akala niya'y nakakakita siya ng isang pangitain.
Tinanong siya ng kanyang mga alagad, “Rabi, sino ang nagkasala, ang taong ito, o ang kanyang mga magulang, kaya siya'y ipinanganak na bulag?”
Sinabi niya sa kanila, “Bakit ninyo ako hinahanap? Hindi ba ninyo nalalaman na dapat ay nasa bahay ako ng aking Ama?”
Si Jesus ay sumigaw at nagsabi, “Ang sumasampalataya sa akin ay hindi sa akin sumasampalataya, kundi doon sa nagsugo sa akin.
[Ito ang labindalawang hinirang niya:] si Simon na kanyang pinangalanang Pedro;
Subalit sila'y lalong nagpipilit na sinasabi, “Ginugulo niya ang sambayanan at nagtuturo sa buong Judea, magbuhat sa Galilea hanggang sa dakong ito.”
Kaya't kayo nga'y maging sakdal, gaya ng inyong Ama sa langit na sakdal.
Mag-ingat kayo sa mga tao, sapagkat ibibigay nila kayo sa mga hukuman at hahagupitin nila kayo sa kanilang mga sinagoga,
Kaya't kanilang kinuha siya, itinapon sa labas ng ubasan, at pinatay.
Pagkatapos, siya'y bumalik mula sa lupain ng Tiro at dumaan sa Sidon patungo sa lawa ng Galilea, na tinahak ang lupain ng Decapolis.
Sinabi sa kanya ni Pedro, “Hindi mo huhugasan ang aking mga paa kailanman.” Sinagot siya ni Jesus, “Kung hindi kita huhugasan, ay hindi ka magkakaroon ng bahagi sa akin.”
“Kaya't kung ang kamay mo o ang paa mo ay nakapagpapatisod sa iyo, putulin mo ito at itapon. Mas mabuti pa sa iyo ang pumasok sa buhay na may kapansanan o lumpo kaysa may dalawang kamay o dalawang paa na maitapon sa apoy na walang katapusan.
Mga alipin, sundin ninyo ang inyong mga panginoon sa laman na may takot at panginginig, sa katapatan ng inyong puso, na gaya ng kay Cristo,
Sinabi ni Pilato sa mga punong pari at sa mga tao, “Wala akong makitang kasalanan sa taong ito.”
Kaya, mga ginoo, lakasan ninyo ang inyong loob, sapagkat ako'y sumasampalataya sa Diyos na mangyayari ito ayon sa sinabi sa akin.
“Mapapalad ang mga nagugutom at nauuhaw sa katuwiran, sapagkat sila ay bubusugin.
Hiniling ko sa iyong mga alagad na palayasin ito subalit hindi nila kaya.”
Pagkaraan ng isang sandali ay nakita siya ng isa pa at sinabi, “Ikaw ay isa rin sa kanila.” Subalit sinabi ni Pedro, “Ginoo, hindi ako.”
At pagkakita niya sa pangitain, sinikap naming pumunta agad sa Macedonia, na naniniwalang kami'y tinawag ng Diyos upang ipangaral ang magandang balita sa kanila.
Lumapit kayo sa akin, kayong lahat na nanlulupaypay at lubhang nabibigatan at kayo'y bibigyan ko ng kapahingahan.
Dumating ang isang babaing balo at siya'y naghulog ng dalawang kusing na ang halaga'y halos isang pera.
Hindi kami naglalagay ng katitisuran ng sinuman, upang walang kapintasang matagpuan sa aming ministeryo.
Mapapalad kayong tumatangis ngayon
At si Satanas ay dudurugin ng Diyos ng kapayapaan sa madaling panahon sa ilalim ng inyong mga paa. Ang biyaya nawa ng ating Panginoong Jesu-Cristo ay sumainyo.
Siya'y pabalik na at nakaupo sa kanyang karwahe, binabasa niya ang propeta Isaias.
Ibigay mo sa amin sa bawat araw ang aming pang-araw-araw na pagkain.
Huwag ninyong tularan ang sanlibutang ito; kundi magbago kayo sa pamamagitan ng pagbabago ng inyong pag-iisip, upang mapatunayan ninyo kung alin ang mabuti, kasiya-siya, at lubos na kalooban ng Diyos.
Dahil sa habag ay hinipo ni Jesus ang kanilang mga mata. Kaagad, nakakita silang muli at sila'y sumunod sa kanya.
Subalit ano ang pinuntahan ninyo upang makita? Isa bang taong nakasuot ng mga damit na malambot? Masdan ninyo, ang nagdadamit ng magagara at namumuhay ng marangya ay nasa mga palasyo ng mga hari.
Sapagkat hindi umakyat si David sa mga langit, ngunit siya rin ang nagsabi,
Pagkatapos ay pumunta si Jesus na kasama sila sa isang pook na tinatawag na Getsemani, at sinabi niya sa kanyang mga alagad, “Maupo kayo rito, samantalang ako'y pupunta sa dako roon at mananalangin.”
ngunit si Esau ay aking kinasuklaman.”
Sa gabi't araw ay palagi siyang nagsisisigaw sa mga libingan at sa mga kabundukan, at sinusugatan ang sarili ng mga bato.
Pagkaraan ng walong araw ay muling nasa loob ng bahay ang kanyang mga alagad, at kasama nila si Tomas. Nakasara ang mga pinto, subalit pumasok si Jesus, at tumayo sa gitna, at sinabi, “Kapayapaan ang sumainyo.”
Sa halip ay sumulat tayo sa kanila, na sila'y lumayo sa mga bagay na pinarumi ng diyus-diyosan at pakikiapid, at sa anumang bagay na binigti, at sa dugo.
Sila'y sumagot sa kanya, “Si Abraham ang aming ama.” Sa kanila'y sinabi ni Jesus, “Kung kayo'y mga anak ni Abraham ay gagawin ninyo ang mga gawa ni Abraham.
na kung saan ang kanilang mga uod ay hindi namamatay, at ang apoy ay hindi napapatay.
Siya'y umahon sa bundok, at tinawag niya ang kanyang mga naibigan at lumapit sila sa kanya.
Si Pedro ay nanatili sa loob ng maraming araw sa Joppa, na kasama ni Simon na isang tagapagluto ng balat.
Siya'y naparito sa kanyang sariling tahanan at siya'y hindi tinanggap ng kanyang sariling bayan.
Kaya't nang tawagin niyang isa-isa ang mga may utang sa kanyang panginoon, ay sinabi niya sa una, ‘Magkano ang utang mo sa aking panginoon?’
Kayong mga hangal, di ba ang gumawa ng labas ay siya ring gumawa ng loob?
Sinabi niya sa kanyang pagtuturo, “Mag-ingat kayo sa mga eskriba, na ibig magpalakad-lakad na may mahahabang damit, at batiin na may paggalang sa mga pamilihan.
Siya'y nagpakita ng lakas sa pamamagitan ng kanyang bisig;
Yamang marami ang nagmamalaki sang-ayon sa pamantayan ng tao, ako ma'y magmamalaki.
Sinabi ni Pilato sa kanila, “Mayroon kayong bantay, humayo kayo, bantayan ninyo sa paraang alam ninyo.”
at ipinahayag na Anak ng Diyos na may kapangyarihan ayon sa Espiritu ng kabanalan, sa pamamagitan ng pagkabuhay mula sa mga patay, na ito'y si Jesu-Cristo na Panginoon natin.
at nagagalak ang aking espiritu sa Diyos na aking Tagapagligtas.
Kaya nga, alalahanin ninyo na noong una, kayo'y mga Hentil sa laman, tinatawag na di-tuli ng mga tinatawag na tuli sa laman, na ginawa ng mga kamay ng tao,
isang katitisuran, at isang ganti sa kanila;
Kaya't si Herodias ay nagtanim ng galit sa kanya at hinangad siyang patayin ngunit hindi niya magawa,
At ipinagbilin niya sa kanila na huwag silang magdadala ng anuman sa kanilang paglalakbay maliban sa isang tungkod; walang tinapay, walang balutan, walang salapi sa kanilang mga pamigkis,
na may lubos na kapakumbabaan at kaamuan, may pagtitiyaga, na magparaya sa isa't isa sa pag-ibig;
Subalit ang isang Samaritano, sa kanyang paglalakbay ay dumating sa kanyang kinaroroonan; at nang kanyang makita ang taong iyon, siya ay nahabag.
Sinabi sa kanya ng mga alagad, “Rabi, ngayo'y pinagsisikapan kang batuhin ng mga Judio, at muli kang pupunta roon?”
“Narinig naming sinabi niya, ‘Gigibain ko ang templong ito na gawa ng mga kamay, at sa loob ng tatlong araw ay magtatayo ako ng iba na hindi gawa ng mga kamay.’”
Naroon ang isang lalaki na may tatlumpu't walong taon nang maysakit.
Pagsapit ng gabi, umupo siyang kasalo ng labindalawang alagad.
At si Crispo, ang pinuno sa sinagoga ay nanampalataya sa Panginoon, kasama ang kanyang buong sambahayan; at marami sa mga taga-Corinto dahil sa pakikinig kay Pablo ay nanampalataya at nabautismuhan.
Ngunit sumagot ang senturion at sinabi, “Panginoon, hindi ako karapat-dapat sa iyo na puntahan mo ang aking bahay, ngunit sabihin mo lamang ang salita at gagaling ang aking alipin.
Sa lahat ng bagay ay ipinakita ko sa inyo na sa ganitong paggawa ay dapat tulungan ang mahihina, at alalahanin ang mga salita ng Panginoong Jesus, na siya mismo ang nagsabi, ‘Higit na mapalad ang magbigay kaysa tumanggap.’”
ay sinabi nila sa kanya, “Guro, nahuli ang babaing ito sa akto ng pangangalunya.
Nang hindi sumikat sa amin ang araw ni ang mga bituin man nang maraming araw, at humahampas pa rin sa amin ang isang malakas na bagyo, nawala ang buong pag-asa naming makakaligtas.
Sinabi niya sa kanila, “Katotohanang sinasabi ko sa inyo, may ilan sa nakatayo rito na hindi makakatikim ng kamatayan, hanggang sa makita nila ang kaharian ng Diyos na dumarating na may kapangyarihan.”
At kaya ng Diyos na pasaganain ang lahat ng biyaya sa inyo, upang sa pagkakaroon ninyo ng sapat sa lahat ng bagay ay palagi kayong sumagana sa bawat mabuting gawa.
Siya'y nagpahayag at hindi ikinaila kundi sinabing, “Hindi ako ang Cristo.”
“Ngunit tungkol sa araw o oras na iyon ay walang nakakaalam, kahit ang mga anghel sa langit, kahit ang Anak, kundi ang Ama.
Sapagkat kami'y natutuwa kung kami'y mahihina at kayo'y malalakas. At ito naman ang idinadalangin namin na kayo ay maging sakdal.
“Mga kapatid, may tiwalang masasabi ko sa inyo ang tungkol sa patriyarkang si David. Siya rin ay namatay at inilibing, at nasa atin ang kanyang libingan hanggang sa araw na ito.
Pagkatapos ay sinabi ng isang anghel ng Panginoon kay Felipe, “Tumindig ka at pumunta patungong timog, sa daang pababa mula sa Jerusalem patungong Gaza.” Ito'y isang ilang na daan.
Sinabi ni Jesus, “Paupuin ninyo ang mga tao.” Madamo sa dakong iyon, kaya't umupo ang mga lalaki na may limang libo ang bilang.
Sumagot si Simon, “Sa palagay ko ay iyong pinatawad niya ng mas malaki.” At sinabi niya sa kanya, “Tama ang hatol mo.”
Sinuman sa kanila ay di nangahas na makisama sa kanila subalit sila'y itinataas ng mga tao.
Subalit hindi lahat ay sumunod sa ebanghelyo. Sapagkat sinasabi ni Isaias, “Panginoon, sino ang naniwala sa aming balita?”
sapagkat isinasaalang-alang namin ang mga bagay na kapuri-puri hindi lamang sa harapan ng Panginoon, kundi maging sa harapan ng mga tao.
O kung humingi siya ng isda ay bibigyan niya ito ng ahas?
At kanyang inutusan sila na mabautismuhan sa pangalan ni Jesu-Cristo. Pagkatapos, siya'y pinakiusapan nilang manatili ng mga ilang araw.
Mayroon akong ibang mga tupa na wala sa kulungang ito. Kailangan ko rin silang dalhin dito at kanilang papakinggan ang aking tinig. Kaya't magkakaroon ng isang kawan na may isang pastol.
“Mag-ingat kayo sa mga eskriba na nagnanais lumakad na may mahahabang damit, at gustung-gusto ang mga pagpupugay sa mga pamilihan, ang pangunahing upuan sa mga sinagoga, at ang mga mararangal na lugar sa mga handaan.
Kung ang sinuman ay hindi manatili sa akin, siya'y itatapong katulad ng sanga at matutuyo, at sila ay titipunin at ihahagis sa apoy at masusunog.
Ngunit sinabi ng mga magsasakang iyon sa isa't isa, ‘Ito ang tagapagmana. Halikayo, patayin natin siya at magiging atin ang mana.’
At sinabi nila sa kanya, “Ang mga alagad ni Juan ay malimit mag-ayuno at mag-alay ng mga panalangin, gayundin ang mga alagad ng mga Fariseo, subalit ang sa iyo ay kumakain at umiinom.”
ni Simeon, ni Juda, ni Jose, ni Jonam, ni Eliakim,
“Binabautismuhan ko nga kayo sa tubig para sa pagsisisi ngunit ang dumarating na kasunod ko ay mas makapangyarihan kaysa akin. Hindi ako karapat-dapat magdala ng kanyang sandalyas. Kanyang babautismuhan kayo sa Espiritu Santo at sa apoy.
Sapagkat ang kanyang mga alagad ay pumunta sa lunsod upang bumili ng pagkain.
ni Jacob, ni Isaac, ni Abraham, ni Terah, ni Nahor,
Tinanong siya ni Pilato, “Ikaw ba ang Hari ng mga Judio?” Sumagot siya sa kanya, “Ikaw ang nagsasabi.”
Sinabi sa kanya ni Jesus, “Hindi ba sinabi ko sa iyo, na kung ikaw ay sasampalataya, ay makikita mo ang kaluwalhatian ng Diyos?”
Kaya't umalis ang mga alagad, nagpunta sa lunsod, at natagpuan ang lahat ayon sa sinabi niya sa kanila. Inihanda nila ang korderong pampaskuwa.
Subalit maging si Tito na kasama ko ay hindi pinilit na patuli, bagama't isang Griyego.
Ngunit sinasabi ko sa inyo, na ang bawat napopoot sa kanyang kapatid ay mananagot sa hukuman at ang sinumang magsabi sa kanyang kapatid, ‘Raca,’ ay mananagot sa Sanhedrin; at ang sinumang magsabi, ‘Ulol ka,’ ay magdurusa sa nag-aapoy na impiyerno.
At sinabi ni Pablo, “Hindi ko alam, mga kapatid, na siya'y pinakapunong pari, sapagkat nasusulat, ‘Huwag mong pagsasalitaan ng masama ang isang pinuno ng iyong bayan.’”
At siya'y dumampot ng tinapay, at nang siya'y makapagpasalamat, kanyang pinagputul-putol, at ibinigay sa kanila, na sinasabi, “Ito'y aking katawan na ibinibigay dahil sa inyo. Gawin ninyo ito sa pag-aalaala sa akin.”
Kung ibinigay sa kanila ng Diyos ang gayunding kaloob na gaya naman ng kanyang ibinigay sa atin nang tayo'y nanampalataya sa Panginoong Jesu-Cristo, sino ba ako na makakahadlang sa Diyos?”
Kung kailangang ako'y magmalaki, ako'y magmamalaki sa mga bagay na nauukol sa aking kahinaan.
Sumagot siya at sinabi, “Ang kasabay kong nagsawsaw ng kanyang kamay sa mangkok ang siyang magkakanulo sa akin.
At tuwing makikita siya ng masasamang espiritu, sila'y nagpapatirapa sa kanyang harapan, at sumisigaw, “Ikaw ang Anak ng Diyos.”
Kaya't pumaroon siya at sumama sa isa sa mga mamamayan sa lupaing iyon na nagpapunta sa kanya sa kanyang mga bukid upang magpakain ng mga baboy.
Bukod sa mga bagay na nasa labas, ako'y araw-araw na nabibigatan sa alalahanin para sa mga iglesya.
Huwag hamakin ng kumakain ang hindi kumakain; at ang hindi kumakain ay huwag humatol sa kumakain; sapagkat sila'y tinanggap ng Diyos.
Habang bumababa sila sa bundok, iniutos niya sa kanila na huwag sabihin kaninuman ang kanilang nakita, hanggang sa ang Anak ng Tao ay magbangon mula sa mga patay.
Siya ay may apat na anak na dalaga na nagsasalita ng propesiya.
kundi magtipon kayo para sa inyong sarili ng mga kayamanan sa langit, na doon ang bukbok at ang kalawang ay hindi makapaninira at ang mga magnanakaw ay hindi rin makakapasok ni makakapagnakaw.
“At mangyayari, na sa lugar na kung saan ay sinabi sa kanila, ‘Kayo'y hindi ko bayan,’
At sinabi nila sa kanya, “Saan, Panginoon?” Sinabi niya sa kanila, “Kung saan naroon ang bangkay ay doon magtitipon ang mga buwitre.”
Subalit batid ni Jesus ang kanilang mga iniisip at sinabi sa kanila, “Bakit ninyo ito pinag-aalinlanganan sa inyong mga puso?
“Kapag inanyayahan ka ng sinuman sa kasalan, huwag kang uupo sa upuang pandangal; baka mayroon siyang inanyayahang higit na kilalang tao kaysa iyo,
Tunay na ang mga tanda ng isang tunay na apostol ay isinagawa sa inyo na may buong pagtitiyaga, sa pamamagitan ng mga tanda at mga kababalaghan at ng mga gawang makapangyarihan.
Subalit ngayon tayo'y nakalagan sa kautusan, yamang tayo'y namatay doon sa umalipin sa atin, upang makapaglingkod sa bagong buhay sa Espiritu, at hindi sa lumang batas na nakasulat.
At nang kanyang malaman na siya'y sakop ni Herodes, kanyang ipinadala siya kay Herodes, na nang panahong iyon ay nasa Jerusalem din.
Nang siya'y makalabas na, ay sinabi ni Jesus, “Ngayon ay niluwalhati ang Anak ng Tao, at ang Diyos ay niluwalhati sa kanya;
Subalit sinagot sila ni Jesus, “Hanggang ngayo'y patuloy sa paggawa ang aking Ama, at ako'y patuloy rin sa paggawa.”
Mula sa mga araw ni Juan na Tagapagbautismo hanggang ngayon, ang kaharian ng langit ay sapilitang pinapasok at sinasakop ng mga taong mararahas.
Sapagkat kung paanong ang Ama ay may buhay sa kanyang sarili, ay pinagkalooban din niya ang Anak na magkaroon ng buhay sa kanyang sarili.
Sapagkat sinasabi niya, “Kung mahipo ko man lamang ang kanyang damit ay gagaling na ako.”
Ngunit hindi kayo dapat tawaging Rabi, sapagkat iisa ang inyong guro, at kayong lahat ay magkakapatid.
Kaya't pagdating ng panginoon ng ubasan, ano kaya ang gagawin niya sa mga magsasakang iyon?”
May lumapit sa kanyang ilang Saduceo, na nagsasabing walang muling pagkabuhay.
At sa oras ng hapunan ay sinugo niya ang kanyang alipin upang sabihin sa mga inanyayahan, ‘Halikayo, sapagkat ang lahat ay handa na.’
Kaya't tumakbo siya at pumunta kay Simon Pedro at sa alagad na minamahal ni Jesus, at sa kanila'y sinabi, “Kinuha nila sa libingan ang Panginoon, at hindi namin alam kung saan nila siya inilagay.”
sinabi niya, “Sa inyo ipinagkaloob na malaman ang mga hiwaga ng kaharian ng Diyos; subalit sa iba'y nagsasalita ako sa mga talinghaga upang sa pagtingin ay hindi sila makakita, at sa pakikinig ay hindi sila makaunawa.
paanong ang pangangasiwa ng Espiritu ay hindi lalong magkakaroon ng kaluwalhatian?
Dinala nila sa kanya ang isang lumpo na nakaratay sa isang higaan. Nang makita ni Jesus ang kanilang pananampalataya, sinabi niya sa lumpo, “Anak, lakasan mo ang iyong loob, pinatatawad na ang iyong mga kasalanan.”
“Huwag kayong matakot, munting kawan, sapagkat nakakalugod sa inyong Ama na ibigay sa inyo ang kaharian.
Sa gayunding paraan ay nilibak siya ng mga punong pari, kasama ng mga eskriba at ng matatanda, na nagsasabi,
sapagkat nalalaman ko ang inyong pananabik, na aking ipinagmamalaki tungkol sa inyo sa mga taga-Macedonia, na ang Acaia ay nakapaghanda na noong nakaraang taon pa, at ang inyong sigasig ay nakapukaw sa karamihan sa kanila.
Nang makalakad pa siya ng kaunti, nakita niya sina Santiago na anak ni Zebedeo at si Juan na kanyang kapatid na naghahayuma ng mga lambat sa kanilang bangka.
Subalit kung naghahanda ka ng piging, anyayahan mo ang mga dukha, ang mga pilay, ang mga lumpo, ang mga bulag,
Hindi na sila mamamatay pa, sapagkat katulad na sila ng mga anghel at sila'y mga anak ng Diyos, palibhasa'y mga anak ng muling pagkabuhay.
Sumagot si Jesus, “Katotohanang sinasabi ko sa iyo, malibang ang isang tao'y ipanganak ng tubig at ng Espiritu, hindi siya makakapasok sa kaharian ng Diyos.
na sinasabi kay Aaron, ‘Igawa mo kami ng mga diyos na mangunguna sa amin; sapagkat tungkol dito kay Moises na naglabas sa amin sa lupain ng Ehipto, ay hindi namin nalalaman kung ano ang nangyari sa kanya.’
Siya'y sumagot sa kanila, “Tatanungin ko rin kayo ng isang tanong, at sabihin ninyo sa akin:
Huwag nga kayong tumulad sa kanila, sapagkat alam na ng inyong Ama ang mga bagay na inyong kinakailangan, bago pa kayo humingi sa kanya.
Kaya sa muling pagkabuhay, alin sa pito ang magiging asawa ng babae? Yamang siya'y napangasawa nilang lahat.”
Isinara niya ang aklat, isinauli ito sa tagapaglingkod at naupo. At ang mga mata ng lahat ng nasa sinagoga ay nakatutok sa kanya.
Subalit sinabi niya, “Ang mga bagay na hindi magagawa ng mga tao ay magagawa ng Diyos.”
Ilan sa mga Fariseo na mula sa maraming tao ay nagsabi sa kanya, “Guro, sawayin mo ang iyong mga alagad.”
Anong uri ng bahay ang itatayo ninyo para sa akin? sabi ng Panginoon,
Nang oras na iyon ay dumating ang kanyang mga alagad. Sila'y nagtaka na siya'y nakikipag-usap sa isang babae, subalit walang nagsabi, “Ano ang gusto mo?” o, “Bakit ka nakikipag-usap sa kanya?”
Sapagkat sa gabing ito ay tumayo sa tabi ko ang isang anghel ng Diyos na nagmamay-ari sa akin, at siya ko namang pinaglilingkuran,
Sila'y magkakabaha-bahagi; ang ama laban sa anak na lalaki, at ang anak na lalaki laban sa ama; ang ina laban sa anak na babae, at ang anak na babae laban sa kanyang ina; ang biyenang babae laban sa kanyang manugang na babae at ang manugang na babae laban sa kanyang biyenang babae.”
Sumagot sa kanya si Simon Pedro, “Panginoon, kanino kami pupunta? Ikaw ang may mga salita ng buhay na walang hanggan.
Marahan kaming naglayag nang maraming araw at may kahirapan kaming nakarating sa tapat ng Cnido. Nang hindi kami pinahintulutan ng hanging makasulong pa, naglayag kami na nanganganlong sa Creta, sa tapat ng Salmone.
kapag inalis ko ang kanilang mga kasalanan.”
kung paanong si Jesus na taga-Nazaret ay binuhusan ng Diyos ng Espiritu Santo at ng kapangyarihan; kung paanong naglibot siya na gumagawa ng mabuti, at nagpapagaling ng lahat ng mga pinahihirapan ng diyablo, sapagkat kasama niya ang Diyos.
Kaya't nagalit ang hari. Sinugo niya ang kanyang mga hukbo, pinuksa ang mga mamamatay-taong iyon, at sinunog ang kanilang lunsod.
ayon sa iyong salita,
Nang makita niya ang kanilang pananampalataya ay sinabi niya, “Lalaki, pinatatawad ka na sa iyong mga kasalanan.”
Nang masabi ni Jesus ang mga bagay na ito, siya'y nabagabag sa espiritu, at nagpatotoo, “Katotohanang sinasabi ko sa inyo, ako'y ipagkakanulo ng isa sa inyo.”
Kung ang isang lalaki ay tumatanggap ng pagtutuli sa Sabbath, upang huwag malabag ang kautusan ni Moises, nagagalit ba kayo sa akin dahil sa pinagaling ko ang buong katawan ng isang tao sa Sabbath?
Ngayon ay nalalaman nila na ang lahat ng mga bagay na ibinigay mo sa akin ay mula sa iyo;
Naroroon ang lahat ng uri ng mga hayop na may apat na paa at ang mga gumagapang sa lupa at ang mga ibon sa himpapawid.
Tayo ay nahatulan ng matuwid, sapagkat tinanggap natin ang nararapat na kabayaran sa ating mga gawa. Subalit ang taong ito'y hindi gumawa ng anumang masama.”
Kung ako'y kilala ninyo ay makikilala rin ninyo ang aking Ama. Mula ngayon siya'y inyong nakikilala at siya'y inyong nakita.”
Nang ito'y kanilang marinig ay isa-isa silang umalis, simula sa mga matatanda. At si Jesus ay naiwang nag-iisa at ang babaing nakatayo sa gitna.
Kung ang paa mo'y nakapagpapatisod sa iyo, putulin mo ito. Mas mabuti pa sa iyo ang pumasok sa buhay na pilay kaysa may dalawang paa ka at maitapon sa impiyerno,
“Kaya, huwag ninyo silang katakutan sapagkat walang bagay na natatakpan na hindi mahahayag; at walang natatago na hindi malalaman.
Sinumang magpakumbaba nang tulad sa batang ito ay siyang pinakadakila sa kaharian ng langit.
At ngayon ay sinabi ko sa inyo bago pa mangyari, upang kung ito'y mangyari, kayo ay maniwala.
Kaya't sinagot nila si Jesus, “Hindi namin nalalaman.” Sinabi naman ni Jesus sa kanila, “Hindi ko rin sasabihin sa inyo kung sa anong awtoridad ko ginagawa ang mga bagay na ito.”
Kaya't sinabi ng ilan sa mga Fariseo, “Ang taong ito'y hindi mula sa Diyos, sapagkat hindi siya nangingilin ng Sabbath.” Subalit sinabi ng iba, “Paanong makakagawa ng gayong mga tanda ang isang taong makasalanan?” At nagkaroon ng pagkakahati-hati sa kanila.
Pagdating ni Maria sa kinaroroonan ni Jesus, at nang makita siya ni Maria, lumuhod ito sa kanyang paanan, na sinasabi sa kanya, “Panginoon, kung ikaw sana'y narito, hindi sana namatay ang aking kapatid.”
na nagtatanong, “Nasaan ang ipinanganak na hari ng mga Judio? Sapagkat nakita namin ang kanyang bituin sa silangan, at naparito kami upang siya'y sambahin.”
Ito ay upang matupad ang sinabi sa pamamagitan ni propeta Isaias: “Kinuha niya ang ating mga sakit at pinasan niya ang ating mga karamdaman.”
at pumikit na ang kanilang mga mata;
Sa oras ding iyon ay tumayo sila at bumalik sa Jerusalem at naratnang nagkakatipon ang labing-isa at ang kanilang mga kasama.
Ngunit siya'y nagkaila, na sinasabi, “Hindi ko nalalaman, ni nauunawaan ang sinasabi mo.” At lumabas siya sa pasilyo [pagkatapos ay tumilaok ang manok].
Pumasok si Satanas kay Judas, na tinatawag na Iscariote, na isa sa labindalawa.
Nang panahong iyon ay narinig ng tetrarkang si Herodes ang balita tungkol kay Jesus.
‘Iginagalang ako ng bayang ito ng kanilang mga labi,
na ang Anak ng Tao ay kailangang ibigay sa mga kamay ng mga makasalanan, at ipako sa krus, at muling mabuhay sa ikatlong araw.”
Sapagkat ipinanganak sa inyo ngayon sa lunsod ni David ang isang Tagapagligtas, na siya ang Cristo, ang Panginoon.
Ang iba ay nahulog sa batuhan na doo'y walang maraming lupa. Agad itong sumibol sapagkat hindi malalim ang lupa.
At lumapit din ang tumanggap ng isang talento at sinabi niya, ‘Panginoon, alam kong ikaw ay taong malupit, na gumagapas ka roon sa hindi mo hinasikan, at nagtitipon ka roon sa hindi mo kinalatan ng binhi.
At sinabi niya sa kanya, “Ano ang ibig mo?” Sinabi niya sa kanya, “Ipag-utos mo na itong dalawa kong anak ay umupo, ang isa sa iyong kanan, at ang isa sa iyong kaliwa, sa iyong kaharian.”
Sapagkat kung umiibig kayo sa mga umiibig lamang sa inyo, anong gantimpala mayroon kayo? Hindi ba gayundin ang ginagawa maging ng mga maniningil ng buwis?
At ngayon, ano pang hinihintay mo? Tumindig ka at magpabautismo, at hugasan ang iyong mga kasalanan, na tumatawag sa kanyang pangalan.’
‘Siya'y mag-uutos sa kanyang mga anghel tungkol sa iyo,’
Nang mapatahimik na ng kalihim ng bayan ang maraming tao, ay kanyang sinabi, “Mga lalaking taga-Efeso, sino sa mga tao ang hindi nakakaalam na ang lunsod ng mga taga-Efeso ay tagapag-ingat ng templo ng dakilang Artemis, at ng banal na batong nahulog mula sa langit?
