na laging nag-aaral at kailanman ay hindi nakakarating sa pagkakilala ng katotohanan.
Kinabukasan, sinabi ni Moises sa bayan, “Kayo'y nagkasala ng malaking kasalanan. Ngayo'y aakyat ako sa Panginoon ; marahil ay aking matutubos ang inyong kasalanan.”
Ito ang mga tuntunin na iniutos ng Panginoon kay Moises, sa mag-asawa at sa mag-ama samantalang ang anak na dalaga ay nasa bahay ng kanyang ama sa panahon ng kanyang kabataan.
May isang babaing Cananea na mula sa lupaing iyon ang lumabas at nagsimulang sumigaw, “Mahabag ka sa akin, O Panginoon, Anak ni David; ang anak kong babae ay pinahihirapan ng isang demonyo.”
na sinasabi, “Ako'y nagkasala sa pagkakanulo ko sa dugong walang sala.” Ngunit sinabi nila, “Ano iyon sa amin? Ikaw ang bahala diyan.”
Habang sinasabi niya ang mga bagay na ito sa kanyang pagtatanggol, ay sinabi ni Festo nang may malakas na tinig, “Pablo, ikaw ay baliw; ang labis mong karunungan ay siyang nagpapabaliw sa iyo!”
“At sa Tabera, sa Massah, sa Kibrot-hataava ay inyong ginalit ang Panginoon .
subalit sinabi ng Diyos, ‘Huwag ninyong kakainin ang bunga ng punungkahoy na nasa gitna ng halamanan; huwag din ninyo itong hihipuin, kundi kayo'y mamamatay.’”
“Kayo ang asin ng lupa; ngunit kung ang asin ay tumabang, paano maibabalik ang alat nito? Wala na itong kabuluhan, maliban sa itapon sa labas at tapakan ng mga tao.
At pinangalanan ng lalaki ang lahat ng hayop at ang mga ibon sa himpapawid, at ang bawat hayop sa parang; subalit para sa lalaki ay walang nakitang katuwang na nababagay para sa kanya.
Gayundin sa araw ng mga unang bunga, sa paghahandog ninyo ng handog na bagong butil sa Panginoon sa inyong pista ng mga sanlinggo, ay magkakaroon kayo ng isang banal na pagtitipon, huwag kayong gagawa ng anumang mabigat na gawain,
Pagkatapos ay nagmamadaling ipinatawag ng Faraon sina Moises at Aaron at kanyang sinabi, “Ako'y nagkasala laban sa Panginoon ninyong Diyos at laban sa inyo.
At sila'y hindi nagsisi sa kanilang mga pagpatay, o sa kanilang pangkukulam, o sa kanilang pakikiapid, o sa kanilang pagnanakaw.
at ang pumatay ng hayop ay magpapalit nito; buhay sa buhay.
ang dambanang ginto, ang langis na pambuhos, ang mabangong insenso, at ang tabing para sa pintuan ng tolda;
at ilulubog ng pari ang kanyang daliri sa dugo, at iwiwisik nang pitong ulit sa harapan ng Panginoon sa harap ng tabing.
Nang sila'y makalabas na sa bayan, at hindi pa sila nakakalayo, sinabi ni Jose sa katiwala ng kanyang bahay, “Bumangon ka, habulin mo ang mga lalaki, at kapag sila'y inabutan mo, ay sabihin mo sa kanila, ‘Bakit ginantihan ninyo ng kasamaan ang kabutihan? Bakit ninyo ninakaw ang aking kopang pilak?
Si Pedro ay lumabas, at sumunod sa kanya. Hindi niya alam na tunay ang nangyayari sa pamamagitan ng anghel, ang akala niya'y nakakakita siya ng isang pangitain.
“‘Ngunit kapag kayo'y nagkamali at hindi ninyo tinupad ang lahat ng utos na ito, na sinabi ng Panginoon kay Moises,
At sisikapin ko rin na pagkatapos ng aking pagpanaw ay inyong maaalala ang mga bagay na ito sa anumang panahon.
ngunit ang bansang kanilang paglilingkuran ay aking hahatulan; at pagkatapos ay aalis sila na may malaking ari-arian.
Sa utos ng Panginoon ay nagkakampo sila, at sa utos ng Panginoon ay naglalakbay sila. Kanilang sinunod ang bilin ng Panginoon , ang utos ng Panginoon sa pamamagitan ni Moises.
Sa ganitong paraan ninyo ihahandog araw-araw, sa loob ng pitong araw ang pagkain na handog na pinaraan sa apoy na mabangong samyo sa Panginoon . Ihahandog ito bukod pa sa palagiang handog na sinusunog at sa inuming handog.
Binigyan ko siya ng panahon upang makapagsisi; ngunit ayaw niyang magsisi sa kanyang pakikiapid.
at ang isa sa inyo ay magsabi sa kanila, “Humayo kayong payapa, magpainit kayo at magpakabusog,” subalit hindi ninyo sila binibigyan ng mga bagay na kailangan ng katawan; anong pakinabang niyon?
At ang ilan sa mga eskriba ay sumagot, “Guro, mahusay ang iyong pagsagot.”
Mag-ingat kayo sa mga tao, sapagkat ibibigay nila kayo sa mga hukuman at hahagupitin nila kayo sa kanilang mga sinagoga,
At siya'y binigyan nila ng alak na hinaluan ng mira, ngunit hindi niya tinanggap iyon.
Kaya't pinili ni Lot para sa kanya ang buong libis ng Jordan; at si Lot ay naglakbay sa silangan at sila'y kapwa naghiwalay.
At sinabi ng Panginoon kay Cain, “Nasaan si Abel na iyong kapatid?” At sinabi niya, “Aywan ko! Ako ba'y tagapagbantay ng aking kapatid?”
Nang iwan niya ang Nazaret, siya ay pumunta at tumira sa Capernaum, na nasa tabing-dagat, na sakop ng Zebulon at Neftali,
Nakikita ng inyong mga mata at ng mga mata ng aking kapatid na si Benjamin, na ang bibig ko mismo ang nagsasalita sa inyo.
ng iyong hayupan at ng mababangis na hayop na nasa iyong lupain. Lahat ng bunga niyon ay magiging inyong pagkain.
Ngunit kung isa lamang ang kanilang hihipan, kung gayon ang mga pinuno, ang mga puno ng mga lipi ng Israel ay magtitipon sa iyo.
At ngayon, maglilihi ka sa iyong sinapupunan at magsisilang ka ng isang anak na lalaki, at tatawagin mo siya sa pangalang Jesus.
At kapag nagtanong sa iyo ang iyong anak sa panahong darating, na sasabihin, ‘Ano ito?’ iyong sasabihin sa kanya, ‘Sa pamamagitan ng lakas ng kamay ay inilabas tayo ng Panginoon sa Ehipto, mula sa bahay ng pagkaalipin.
Kinagabihan, sila'y nagpangkat-pangkat laban sa kaaway, siya at ang kanyang mga alipin, at sila'y kanilang ginapi at hinabol sila hanggang sa Hoba na nasa hilaga ng Damasco.
Nanganak ang panganay ng isang lalaki, at tinawag sa pangalang Moab na siyang ama ng mga Moabita hanggang sa araw na ito.
Unti-unti ko silang papalayasin sa harapan mo, hanggang sa ikaw ay dumami at manahin mo ang lupain.
Nang paalisin ako ng Diyos sa bahay ng aking ama ay sinabi ko sa kanya, ‘Ito ang kabutihan na maipapakita mo sa akin: sa lahat ng lugar na ating pupuntahan ay sabihin mo tungkol sa akin, Siya'y aking kapatid.’”
huwag kang magmalaki sa mga sanga. Ngunit kung magmalaki ka, alalahanin mong hindi ikaw ang nagdadala sa ugat, kundi ang ugat ang nagdadala sa iyo.
Natakpan din ang mga bukal ng kalaliman at ang mga bintana ng langit, at napigil ang ulan sa langit.
Huwag kayong magpapaningas ng apoy sa lahat ng inyong tinitirhan sa araw ng Sabbath.”
Batiin din ninyo ang iglesya na nasa kanilang bahay. Batiin ninyo si Epeneto na minamahal ko, na siyang unang nahikayat kay Cristo sa Asia.
Magdadala ako ng tabak sa inyo upang ipaghiganti ang tipan; at kayo'y matitipon sa loob ng inyong mga lunsod, at magpapadala ako ng salot sa gitna ninyo, at kayo'y babagsak sa kamay ng kaaway.
Kaya't nanirahan ang Israel sa lupain ng mga Amoreo.
Nalalaman ninyo na dahil sa karamdaman ng katawan ay una kong ipinangaral sa inyo ang ebanghelyo.
Sapagkat ang hindi magawa ng kautusan, yamang ito ay pinahina ng laman, ay ginawa ng Diyos sa pagsusugo sa kanyang sariling Anak sa anyo ng makasalanang laman, at tungkol sa kasalanan ay hinatulan niya ang kasalanan sa laman,
At sila'y natuwa at nagkasundong bigyan siya ng salapi.
Kanilang sinabi sa kanya, “Hindi, panginoon ko, kundi ang iyong mga lingkod ay nagsiparito upang bumili ng pagkain.
Sinabi niya, ‘Hindi, amang Abraham, subalit kung ang isang mula sa mga patay ay pumunta sa kanila, sila'y magsisisi.’
“Sa ikawalong araw, kukuha siya ng dalawang korderong lalaki na walang kapintasan, at ng isang korderong babae na isang taong gulang at walang kapintasan, at ng ikasampung bahagi ng harinang hinaluan ng langis, isang handog at ng isang log na langis, bilang pagkaing handog.
Aking sinabi, “Ikakalat ko sila sa malayo, aking aalisin ang alaala nila sa mga tao,”
Ngunit sinabi niya, “Pumarito ang iyong kapatid sa pamamagitan ng pandaraya, at kinuha ang basbas sa iyo.”
At ako'y lalo pang nakikiusap sa inyo na inyong gawin ito, upang ako'y madaling maibalik sa inyo.
Sinabi niya sa tagapag-alaga ng ubasan, ‘Tingnan ninyo, tatlong taon na akong pumaparito na humahanap ng bunga sa punong igos na ito, at wala akong makita. Putulin mo ito. Bakit sinasayang nito ang lupa?’
Aayusin niyang palagi ang mga ilaw sa ibabaw ng ilawan na yari sa lantay na ginto sa harapan ng Panginoon .
Marunong akong magpakababa, at marunong din akong magpakasagana; sa bawat bagay at sa lahat ng bagay ay natutunan ko ang lihim sa kabusugan, at maging sa kagutuman, at maging sa kasaganaan at maging sa kasalatan.
sa mga ito ay kasama kayo na mga tinawag kay Jesu-Cristo:
Nang magmatigas ang Faraon na hindi kami payagang umalis ay pinatay ng Panginoon ang lahat ng mga panganay sa lupain ng Ehipto, ang panganay ng tao at gayundin ang panganay ng hayop. Kaya't aking inihahandog sa Panginoon ang lahat ng mga lalaki na nagbubukas ng bahay-bata; ngunit lahat ng panganay ng aking anak ay aking tinutubos.’
At sinasabi ko sa inyo, humingi kayo at kayo'y bibigyan; humanap kayo, at kayo'y makakakita; tumuktok kayo at kayo'y pagbubuksan.
(At ang mga anak ni Israel ay naglakbay mula sa Beerot Benyaakan hanggang sa Mosera. Doon namatay si Aaron, at doon siya inilibing. Si Eleazar na kanyang anak ay nangasiwa sa katungkulang pari na kapalit niya.
At hinipan ng ikaanim na anghel ang kanyang trumpeta, at narinig ko ang isang tinig mula sa apat na sungay ng dambanang ginto na nasa harapan ng Diyos,
Sinumang lumalait sa kanyang ama o sa kanyang ina ay tiyak na papatayin; kanyang nilait ang kanyang ama o ang kanyang ina, ang kanyang dugo ay nasa kanya.
Subalit nang makita ito ng mga alagad, ay nagalit sila, na nagsasabi, “Anong layunin ng pag-aaksayang ito?
Sinugo sila ni Moises sa pakikipaglaban, isang libo sa bawat lipi, sila at si Finehas na anak ng paring si Eleazar, na may mga kasangkapan ng santuwaryo at may mga trumpeta na panghudyat sa kanyang kamay.
Ngunit hindi sila susunod kailanman sa iba, kundi lalayo sila sa kanya, sapagkat hindi nila kilala ang tinig ng iba.”
Pagkatapos, kukuha sila ng dugo, at ilalagay sa dalawang haligi ng pinto at sa itaas ng pintuan, sa mga bahay na kanilang kakainan.
Pagkatapos nito ay sinabi niya sa mga alagad, “Pumunta tayong muli sa Judea.”
Kung ang isang sinungaling na saksi ay tumindig laban sa kanino man upang sumaksi laban sa kanya tungkol sa isang masamang gawa,
Sapagkat ako'y hindi nagsasalita mula sa aking sarili kundi ang Ama na nagsugo sa akin ay siyang nagbigay sa akin ng utos, kung ano ang dapat kong sabihin, at kung ano ang dapat kong bigkasin.
At lumabas ang isang tinig sa trono, na nagsasabi, “Purihin ninyo ang ating Diyos, kayong lahat na mga alipin niya, at kayong natatakot sa kanya, mga hamak at dakila.”
“Kung ang kanyang alay ay kambing, dadalhin niya ito sa harapan ng Panginoon .
Nagpapasalamat ako sa kanya na nagpapalakas sa akin, kay Cristo Jesus na Panginoon natin, sapagkat ako'y itinuring niyang tapat, na ako'y inilagay sa paglilingkod sa kanya.
“Nangyari ito upang sila'y maniwala na ang Panginoon , ang Diyos ng kanilang mga ninuno, ang Diyos ni Abraham, ang Diyos ni Isaac, at ang Diyos ni Jacob ay nagpakita sa iyo.”
Nang sumunod na araw ay dumaong kami sa Sidon; at pinakitunguhang mabuti ni Julio si Pablo at pinahintulutan siyang pumaroon sa kanyang mga kaibigan upang siya'y matulungan.
Ang mga pangalan ng labindalawang apostol ay ito: ang una ay si Simon na tinatawag na Pedro, si Andres na kanyang kapatid; si Santiago na anak ni Zebedeo, at si Juan na kanyang kapatid;
tulad sa nalulungkot, gayunma'y laging nagagalak; tulad sa mga dukha, gayunma'y pinayayaman ang marami, gaya ng walang pag-aari, gayunma'y mayroon ng lahat ng bagay.
tumayo si Moises sa pintuan ng kampo, at nagsabi, “Sino ang nasa panig ng Panginoon ? Lumapit kayo sa akin.” At lahat ng mga anak ni Levi ay nagtipon sa kanya.
“Magtatalaga ka ng mga hukom at ng mga pinuno sa lahat ng mga bayan na ibinibigay sa iyo ng Panginoon mong Diyos, ayon sa iyong mga lipi, at sila'y maggagawad sa bayan ng matuwid na paghatol.
Kaya't si Moises ay lumabas, at sinabi sa bayan ang mga salita ng Panginoon . Siya'y nagtipon ng pitumpung lalaki sa matatanda sa bayan at kanyang pinatayo sa palibot ng tolda.
Ikaw na nagsasabing huwag mangalunya, nangangalunya ka ba? Ikaw na nasusuklam sa mga diyus-diyosan, ninanakawan mo ba ang mga templo?
Ang lupa mismo ang nagpapasibol sa halaman, una ang usbong, saka ang uhay, pagkatapos ay ang uhay na hitik sa butil.
ang panginoon ng aliping iyon ay darating sa araw na hindi niya inaasahan, at sa oras na hindi niya nalalaman. Siya'y pagpuputul-putulin at isasama sa mga hindi tapat.
Tipunin mo ang mamamayan, ang mga lalaki, mga babae, mga bata, mga dayuhan na nasa loob ng iyong mga bayan upang kanilang marinig at upang sila'y matutong matakot sa Panginoon mong Diyos, at isagawa ang lahat ng mga salita ng kautusang ito;
Huwag aapihin ng sinuman ang kanyang kapwa, kundi matatakot kayo sa inyong Diyos, sapagkat ako ang Panginoon ninyong Diyos.
Sapagkat ang mga pinuno ay hindi kilabot sa mabuting gawa, kundi sa masama. At ibig mo bang huwag magkaroon ng takot sa may kapangyarihan? Gawin mo ang mabuti, at magkakamit ka ng kapurihan mula sa kanya:
Akong si Pablo ay sumusulat nito sa pamamagitan ng aking sariling kamay: Ako ang magbabayad niyon. Hindi ko na ibig banggitin pa na utang mo sa akin pati ang iyong sarili.
At iniluwa ng dagat ang mga patay na nasa kanya, at ibinigay ng kamatayan at ng Hades ang mga patay na nasa kanila, at hinatulan ang bawat tao ayon sa kanilang mga gawa.
Pagkatapos ay sinabi niya sa lalaki, “Iunat mo ang iyong kamay.” At iniunat nga niya, at naibalik ito sa dati, magaling na gaya ng isa.
At kung sa pamamagitan ni Beelzebul ay nagpapalayas ako ng mga demonyo, sa pamamagitan nino sila pinalalayas ng inyong mga anak? Kaya't sila ang magiging mga hukom ninyo.
Para sa kalayaan ay pinalaya tayo ni Cristo; kaya't magpakatatag kayo at huwag pasakop na muli sa pamatok ng pagkaalipin.
Kaya't tutuparin nila ang aking bilin, at hindi nila iyon ipagkakasala, upang sila ay huwag mamatay kapag kanilang nilapastangan ito: Ako ang Panginoon na nagpapabanal sa kanila.
May dalawang lalaking bulag na nakaupo sa tabi ng lansangan. Nang marinig nilang nagdaraan si Jesus, sila'y sumigaw na nagsasabi, “Mahabag ka sa amin, Anak ni David!”
Ang may pandinig ay makinig sa sinasabi ng Espiritu sa mga iglesya. Ang magtagumpay ay hindi masasaktan ng ikalawang kamatayan.
ngunit kapag ito'y naihasik ay tumutubo, nagiging mas malaki kaysa lahat ng mga halaman, at nagsasanga ng malalaki, anupa't ang mga ibon sa himpapawid ay nakakagawa ng mga pugad sa lilim nito.”
Naging mga anak nito sina Zimram, Jokshan, Medan, Midian, Isbak, at Shua.
Kaya't siya'y nangako na may sumpa na kanyang ibibigay ang anumang hilingin nito.
Kinabukasan, nang mabalitaan ng maraming taong dumalo sa pista na si Jesus ay darating sa Jerusalem,
Pagkatapos ay tumayo ang hari, ang gobernador, si Bernice, at ang mga nakaupong kasama nila,
Ito ang mga anak ni Aholibama na asawa ni Esau: ang mga pinunong sina Jeus, Jalam, at Kora. Ito ang mga pinunong nagmula kay Aholibama na anak ni Ana, na asawa ni Esau.
Sapagkat ang isang tipan ay pinagtitibay sa kamatayan, yamang ito'y walang bisa habang nabubuhay pa ang gumawa ng tipan.
Sapagkat kayo rin ang lubos na nakakaalam na ang araw ng Panginoon ay darating na gaya ng magnanakaw sa gabi.
At kung ang sinumang lalaki ay magkamaling kumain ng banal na bagay, iyon ay kanyang daragdagan ng ikalimang bahagi at ibibigay iyon sa pari kasama ng banal na bagay.
Tumindig ka, itayo mo ang bata at alalayan mo siya ng iyong kamay sapagkat siya'y gagawin kong isang malaking bansa.”
“Narinig ninyo na sinabi, ‘Huwag kang mangangalunya.’
Mapalad ang babaing sumampalataya na matutupad ang mga bagay na sinabi sa kanya ng Panginoon.”
Ngunit mas madali pa para sa langit at lupa na lumipas, kaysa maalis ang isang kudlit sa kautusan.
Subalit sinabi niya sa kanila, “Ang aking ina at ang aking mga kapatid ay ang mga nakikinig ng salita ng Diyos at ginagawa ito.”
“Sa ano ko nga ihahambing ang mga tao ng lahing ito at ano ang kanilang katulad?
At kayong mga taga-Filipos, nalalaman naman ninyo, na nang pasimula ng ebanghelyo, nang ako'y umalis sa Macedonia, wala ni isang iglesya na nakipagkaisa sa akin sa pagbibigay at pagtanggap kundi kayo lamang;
Sinabi niya sa kanila, “Dahil sa katigasan ng inyong puso ay ipinahintulot sa inyo ni Moises na inyong hiwalayan ang inyong mga asawang babae; ngunit buhat sa pasimula ay hindi gayon.
Subalit nakita ni Sara ang anak ni Hagar na taga-Ehipto, na ipinanganak kay Abraham, na nakikipaglaro sa anak niyang si Isaac.
Kaya't nang sila'y magkatipon ay sinabi ni Pilato sa kanila, “Sino ang ibig ninyong pakawalan ko sa inyo? Si Barabas, o si Jesus na tinatawag na Cristo?”
Pagkaraan ng dalawang araw ay umalis siya roon at nagtungo sa Galilea,
At ang labindalawang pintuan ay labindalawang perlas, at bawat pinto ay yari sa isang perlas, at ang lansangan ng lunsod ay dalisay na ginto, na gaya ng naaaninag na salamin.
Kaya't si Zilpa na alila ni Lea ay nagkaanak ng isang lalaki kay Jacob.
Sinabi ni Jesus sa kanya, “Katotohanang sinasabi ko sa iyo, sa gabing ito, bago tumilaok ang manok, ay ipagkakaila mo ako ng tatlong ulit.”
Kaya't si Hamor at ang anak niyang si Shekem ay pumunta sa pintuang-bayan ng kanilang lunsod, at sila'y nagsalita sa mga tao sa kanilang lunsod, na sinasabi,
Pagkatapos, ang Israel ay nagpadala ng mga sugo kay Sihon, na hari ng mga Amoreo, na sinasabi,
At sinabi naman ng isa pa, “Ako'y susunod sa iyo, Panginoon, subalit hayaan mo muna akong magpaalam sa mga nasa bahay ko.”
At sa ikalawang pagkakataon ay kanilang sinabi, “Aleluia! At ang usok ng babae ay pumailanglang magpakailanpaman.”
ilalagay mong hari sa iyo ang pipiliin ng Panginoon mong Diyos. Isa sa iyong mga kapatid ang ilalagay mong hari; huwag kang maglalagay ng isang dayuhan na hindi mo kapatid.
Ngunit kung ang pamamaga ay tumigil sa kanyang kinaroroonan, at hindi kumalat, ito ay galos ng bukol; at ipahahayag ng pari na siya ay malinis.
At kung nagpapalayas ako ng mga demonyo sa pamamagitan ni Beelzebul, sa pamamagitan naman nino pinalalayas sila ng inyong mga anak? Kaya't sila ang inyong magiging mga hukom.
ang taong nabalian ng paa o nabalian ng kamay;
Nangunguna sa hukbo ng lipi ng mga anak ni Isacar si Natanael na anak ni Suar.
At ako'y nagpatirapa sa harapan ng Panginoon , gaya nang una, sa loob ng apatnapung araw at apatnapung gabi. Hindi ako kumain ng tinapay ni uminom ng tubig; dahil sa lahat ng inyong kasalanan na inyong ginawa sa paggawa ng masama sa paningin ng Panginoon na inyong ginalit.
Kaya, alang-alang kay Cristo, ako'y nasisiyahan sa mga kahinaan, paglait, kahirapan, pag-uusig, at mga sakuna, sapagkat kapag ako'y mahina, ako nga'y malakas.
mula sa Bamot patungo sa libis na nasa bukid ng Moab, sa tuktok ng Pisga, na pababa sa ilang.
Sa gayo'y nag-utos si Moises tungkol sa kanila sa paring si Eleazar, kay Josue na anak ni Nun, at sa mga pinuno sa mga sambahayan ng mga ninuno ng mga lipi ng mga anak ni Israel.
Samantalang sinisiksik si Jesus ng napakaraming tao upang makinig ng salita ng Diyos, siya'y nakatayo sa tabi ng lawa ng Genesaret.
Subalit nang makaahon na ang kanyang mga kapatid para sa pista, saka naman siya umahon, hindi hayagan kundi palihim.
“Ngayon, ito ang talinghaga: Ang binhi ay ang salita ng Diyos.
Pagkatapos ay susuguin niya ang mga anghel at titipunin ang kanyang mga hinirang mula sa apat na hangin, mula sa mga dulo ng lupa hanggang sa mga dulo ng langit.
Sapagkat kung tatanggihan mong paalisin sila, at sila'y pipigilin mo pa,
“Huwag kang kakain ng anumang bagay na marurumi.
Sapagkat ang tinutukoy ng mga bagay na ito ay kabilang sa ibang angkan, na doon ang sinuma'y hindi naglingkod sa dambana.
Pagkatapos, lihim na ipinatawag ni Herodes ang mga Pantas at inalam sa kanila kung kailan lumitaw ang bituin.
Nang ang Faraon ay nagalit sa kanyang mga lingkod, ibinilanggo niya ako sa bahay ng kapitan ng bantay, ako at ang puno ng mga panadero.
Sa pananampalataya'y tinahak nila ang Dagat na Pula na tulad sa tuyong lupa, ngunit nang tangkaing gawin ito ng mga Ehipcio ay nalunod sila.
Naroon ang isang lalaki na may tatlumpu't walong taon nang maysakit.
Binabati kayo ni Gayo na tinutuluyan ko, at ng buong iglesya. Binabati kayo ni Erasto na ingat-yaman ng lunsod, at ng kapatid na si Cuarto. [
“Sapagkat ipagtanong mo nga ang mga araw na nagdaan na nauna sa iyo, mula nang araw na lalangin ng Diyos ang tao sa ibabaw ng lupa, at mula sa isang hangganan ng langit hanggang sa kabila, kung nagkaroon ng isang bagay na higit na dakila kaysa rito, o may narinig na gaya nito?
Anuman ang inyong ginagawa, ay inyong gawin ng buong puso, na gaya ng sa Panginoon, at hindi sa mga tao;
Nang matapos ni Jesus ang lahat ng mga salitang ito ay sinabi niya sa kanyang mga alagad,
Bakit ang pangalan ng aming ama ay aalisin sa angkan niya, dahil ba sa siya'y walang anak na lalaki? Bigyan ninyo kami ng ari-arian kasama ng mga kapatid ng aming ama.”
At nang taong ikaanimnaraan at isa, nang unang araw ng unang buwan, ay natuyo ang tubig sa ibabaw ng lupa. Inalis ni Noe ang takip ng daong at tumingin siya, at nakita niyang ang ibabaw ng lupa ay natuyo na.
Nilibak at hinampas si Jesus ng mga lalaking nagbabantay sa kanya.
Ang nalabi sa laman at sa tinapay ay susunugin ninyo sa apoy.
Bigyan mo ang bawat humihingi sa iyo; at kapag inagaw ng sinuman ang iyong ari-arian, huwag mo nang bawiin ang mga iyon.
Si Felipe nga ay taga-Bethsaida, sa lunsod nina Andres at Pedro.
Nang ang salot ay tumigil, si Aaron ay bumalik kay Moises sa pintuan ng toldang tipanan.
At nagsalita ang Panginoon kay Moises sa mga kapatagan ng Moab sa tabi ng Jordan, sa Jerico, na sinasabi,
Kanyang gagantihan ang bawat tao ayon sa kanyang mga gawa:
Sapagkat ang salita ng Diyos ay buháy, mabisa, at higit na matalas kaysa alin mang tabak na may dalawang talim, at tumatagos hanggang sa pinaghihiwalayan ng kaluluwa at espiritu, ng mga kasukasuan at ng utak sa buto, at may kakayahang kumilala ng mga pag-iisip at mga hangarin ng puso.
Ang mga anak ni Gershon: sina Libni at Shimei, ayon sa kani-kanilang angkan.
“Mapapalad ang mga mapagpayapa, sapagkat sila ay tatawaging mga anak ng Diyos.
Ang ilan sa mga eskriba ay nagsabi, “Nilalapastangan ng taong ito ang Diyos.”
Subalit manatili ka sa mga bagay na iyong natutunan at matatag na pinaniwalaan, yamang nalalaman mo kung kanino ka natuto,
Sumagot sa kanya si Simon Pedro, “Panginoon, kanino kami pupunta? Ikaw ang may mga salita ng buhay na walang hanggan.
Sapagkat tunay na matuwid sa Diyos na gantihan ng kapighatian ang mga nagpapahirap sa inyo,
Sa kabilang dako, mayroong pagpapawalang-bisa sa naunang utos, sapagkat ito ay mahina at walang pakinabang
Nang marinig ng ilan mula sa maraming tao ang mga salitang ito, sila ay nagsabi, “Tunay na ito nga ang propeta.”
Ngunit ang galit ng Diyos ay nag-aalab sapagkat siya'y pumunta. Ang anghel ng Panginoon ay tumayo sa daan bilang kalaban niya. Siya noon ay nakasakay sa kanyang asno at ang kanyang dalawang alipin ay kasama niya.
subalit kaluwalhatian, karangalan, at kapayapaan sa bawat gumagawa ng mabuti, una'y sa Judio at gayundin sa Griyego:
Iibigin ka niya, pagpapalain, at pararamihin. Pagpapalain din niya ang iyong mga supling, ang bunga ng iyong lupa, ang iyong trigo, ang iyong alak, ang iyong langis, ang karagdagan ng iyong mga bakahan, at ang mga guya ng iyong kawan sa lupain na kanyang ipinangakong ibibigay sa iyo at sa iyong mga ninuno.
Sila'y lumapit sa kanya, na nagsasabi, “Mabuhay ang Hari ng mga Judio!” At siya'y kanilang pinagsusuntok.
Kaya't kinabukasan, dumating si Agripa at si Bernice na may buong karilagan. Nang pumasok na sila sa bulwagan ng hukuman kasama ang mga punong kapitan at ang mga pangunahin sa bayan, ipinasok si Pablo sa utos ni Festo.
Lumapit kayo sa kanya, na isang batong buháy, bagaman itinakuwil ng mga tao gayunma'y pinili at mahalaga sa paningin ng Diyos, at
Nang marinig ito ni Jesus, sinabi niya sa kanya, “Isang bagay pa ang kulang sa iyo. Anumang mayroon ka ay ipagbili mo, ipamahagi mo sa mga dukha, at magkakaroon ka ng kayamanan sa langit. At pumarito ka, sumunod ka sa akin.
Papahintulutan ko ang aking dalawang saksi na magpahayag ng propesiya sa loob ng 1,260 araw, na nakasuot ng damit-sako.”
Ipapangilin ninyo ang aking mga Sabbath, at igagalang ninyo ang aking santuwaryo: Ako ang Panginoon .
Pumunta nga ang mga alagad at ginawa ang ayon sa ipinag-utos ni Jesus sa kanila.
At hindi nila naunawaan ang salitang sinabi niya sa kanila.
Ang mga anak ni Noe na lumabas sa daong ay sina Sem, Ham, at Jafet. Si Ham ay siyang ama ni Canaan.
“Ngunit ang taong marumi at hindi maglilinis ay ititiwalag mula sa gitna ng kapulungan, sapagkat kanyang dinungisan ang santuwaryo ng Panginoon , yamang ang tubig para sa karumihan ay hindi ibinuhos sa kanya, siya'y marumi.
kundi nang siya'y dumating sa Roma, hinanap niya ako nang buong sikap, at ako'y natagpuan niya.
Kaya't dinala nila ang kanilang mga hayop kay Jose, at binigyan sila ni Jose ng pagkain kapalit ng mga kabayo, mga kawan, mga bakahan, at mga asno. Nang taong iyon, sila'y kanyang binigyan ng pagkain kapalit ng lahat nilang mga hayop.
Nang panahong iyon ay narinig ng tetrarkang si Herodes ang balita tungkol kay Jesus.
at kanilang sasabihin sa mga naninirahan sa lupaing ito. Kanilang nabalitaan na ikaw Panginoon ay nasa gitna ng bayang ito, sapagkat ikaw Panginoon ay nagpakita nang mukhaan, at ang iyong ulap ay nakatindig sa ibabaw ng mga iyon, at ikaw ay nangunguna sa kanila, sa isang haliging ulap sa araw, at sa isang haliging apoy sa gabi.
At sinabi ni Aaron sa kanila, “Alisin ninyo ang mga hikaw na ginto na nasa tainga ng inyu-inyong asawa, ng inyong mga anak na lalaki at babae, at dalhin ninyo sa akin.”
pagkawasak at kalungkutan ang nasa kanilang mga landas,
Nang matapos na ni Jesus ang kanyang mga salita sa pandinig ng mga tao, pumasok siya sa Capernaum.
Nang mabalitaan niya na si Jesus ay dumating sa Galilea mula sa Judea, pumunta siya roon at nakiusap sa kanya na siya'y pumunta at pagalingin ang kanyang anak na lalaki sapagkat siya'y malapit nang mamatay.
Nang sila'y makakuha ng piyansa mula kay Jason at sa iba pa, ay kanilang pinakawalan sila.
Kaya nga, ibig kong magsipag-asawa ang mga batang babaing balo, manganak, mamahala ng sambahayan, huwag magbigay sa kaaway ng anumang kadahilanan ng panlilibak,
ni Enos, ni Set, ni Adan, ng Diyos.
Ito ang mga salinlahi ni Isaac, na anak ni Abraham: naging anak ni Abraham si Isaac,
Sinabi niya sa kanila, “Tiyak na sasabihin ninyo sa akin ang kawikaang ito, ‘Manggagamot, pagalingin mo ang iyong sarili.’ Ang anumang aming narinig na ginawa mo sa Capernaum ay gawin mo rin sa iyong lupain.”
“Sinumang tao sa sambahayan ni Israel o sa mga taga-ibang bayan na naninirahang kasama nila na kumain ng anumang dugo, ay aking ihaharap ang aking mukha laban sa taong iyon na kumain ng dugo, at ititiwalag siya sa kanyang bayan.
Subalit dahil batid ni Jesus ang iniisip ng kanilang puso, kumuha siya ng isang maliit na bata at inilagay sa kanyang tabi.
Nagturo siya sa kanilang mga sinagoga at pinuri ng lahat.
“Huwag mong bubusalan ang baka kapag gumigiik.
Kanyang sinabi, “Ako'y makakasama mo; at ito'y magiging tanda sa iyo na ikaw ay aking sinugo: kapag iyong nailabas na sa Ehipto ang bayan, sasambahin ninyo ang Diyos sa bundok na ito.”
At siya'y lumapit sa kanyang ama at sinabi, “Ama ko;” at sinabi niya, “Narito ako; sino ka, anak ko?”
Ngunit umalis ang mga Fariseo at nagpulong laban sa kanya kung papaano siya pupuksain.
Sinabi rin ni Shekem sa ama ni Dina at sa kanyang mga kapatid, “Makatagpo sana ako ng biyaya sa inyong paningin at ang hingin ninyo sa akin ay aking ibibigay.
At ang kanyang pangala'y tatawagin sa Israel, ‘Ang bahay ng hinubaran ng sandalyas.’
upang gumawa ng magagandang dibuho, gumawa sa ginto, sa pilak, at sa tanso,
upang matupad ang sinabi ni propeta Isaias: “Panginoon, sino ang naniwala sa aming balita? At kanino nahayag ang bisig ng Panginoon?”
Pagkatapos ay nagpasimula siyang magsalita ng masama at manumpa, “Hindi ko kilala ang taong iyon.” At kaagad tumilaok ang manok.
Hindi siya ang ilaw, kundi dumating siya upang magpatotoo tungkol sa ilaw.
Dinala niya ang lahat ng ito sa kanya at hinati niya sa gitna, at kanyang inihanay na magkakatapat ang isa't isa subalit hindi niya hinati ang mga ibon.
na may anyo ng kabanalan, ngunit tinatanggihan ang kapangyarihan nito. Lumayo ka rin naman sa mga ito.
Mula sa Mileto ay nagpasugo siya sa Efeso at ipinatawag ang matatanda ng iglesya.
Hindi ba sila ay nasa kabila ng Jordan, sa dakong nilulubugan ng araw, sa lupain ng mga Cananeo na tumatahan sa Araba, sa tapat ng Gilgal na katabi ng mga ensina sa More?
Kaya nga sundin natin ang mga bagay na magbubunga ng kapayapaan, at ang mga bagay na makapagpapatibay sa isa't isa.
Pagkatapos ay inilapit niya ang tupang lalaki na handog na sinusunog, at ipinatong ni Aaron at ng kanyang mga anak ang mga kamay nila sa ulo ng tupa,
Huwag kayong padaya; ang Diyos ay hindi maaaring lokohin, sapagkat ang anumang ihasik ng tao, ay siya rin niyang aanihin.
Gayon ang sinabi ko sa inyo, ngunit hindi kayo nakinig kundi kayo'y naghimagsik laban sa utos ng Panginoon , at naghambog at umakyat sa lupaing maburol.
“Magsalita ka kay Aaron at sa kanyang mga anak at sa lahat ng mga anak ni Israel, at sabihin mo sa kanila: Ito ang iniutos ng Panginoon :
Ngunit kanyang sinabi, “Hindi iyon ingay ng sigaw ng pagtatagumpay, o ingay man ng sigaw ng pagkatalo, kundi ingay ng mga umaawit ang aking naririnig.”
At sinabi ni Lea, “Binigyan ako ng Diyos ng isang mabuting kaloob. Ngayo'y pararangalan ako ng aking asawa, sapagkat nagkaanak ako sa kanya ng anim na lalaki.” At tinawag niya ang kanyang pangalan na Zebulon.
Pagkaraan ng tatlong araw, pagkarating ni Festo sa lalawigan, pumunta siya sa Jerusalem mula sa Cesarea,
Mayroon pa siyang isa, isang minamahal na anak na lalaki. Sa kahuli-hulihan siya'y kanyang isinugo sa kanila na sinasabi, ‘Igagalang nila ang aking anak.’
Nang malapit na ang mga araw upang siya'y tanggapin sa itaas, itinutok niya ang kanyang sarili sa pagpunta sa Jerusalem.
At sinabi ng Panginoon kina Moises at Aaron sa bundok ng Hor, sa hangganan ng lupain ng Edom,
“‘Ni huwag kang magnanakaw.
Kumuha ang bawat isa ng kanyang suuban, at lagyan ninyo ng insenso, at dalhin ninyo sa harap ng Panginoon , na bawat isa'y magdala ng kanyang suuban, na dalawandaan at limampung suuban; ikaw naman at si Aaron, bawat isa sa inyo'y may kanyang suuban.”
Nagdala rin kami ng karagdagang salapi upang ibili ng pagkain. Hindi namin nalalaman kung sino ang naglagay ng aming salapi sa aming mga sako.”
Siya'y naglihi at nanganak ng lalaki at kanyang sinabi, “Inalis ng Diyos sa akin ang aking pagiging kahiyahiya.”
At ang mga balat ng mga batang kambing ay ibinalot sa kanyang mga kamay, at sa makinis na bahagi ng kanyang leeg.
At maririnig ng buong Israel, at matatakot, at hindi na gagawa ng anumang kasamaang gaya nito sa gitna mo.
At napaso ang mga tao sa matinding init, ngunit kanilang nilait ang pangalan ng Diyos na may kapangyarihan sa mga salot na ito; at hindi sila nagsisi upang siya'y luwalhatiin.
Upang kayo'y huwag magmarunong sa inyong sarili, mga kapatid, nais kong malaman ninyo ang hiwagang ito, na ang pagmamatigas ay nangyari sa isang bahagi ng Israel hanggang makapasok ang buong bilang ng mga Hentil.
Huwag ninyo itong kakaining hilaw, o pinakuluan man sa tubig, kundi inihaw sa apoy, pati ang ulo, ang paa at mga lamang loob nito.
Ganito papasok si Aaron sa loob ng dakong banal: may dalang isang guyang toro na handog pangkasalanan, at isang tupang lalaki na handog na sinusunog.
yamang taglay ninyo ang gayunding pakikipaglaban na inyong nakita sa akin, at ngayo'y nababalitaan ninyo tungkol sa akin.
Mula noon, si Jesus ay hindi na naglalakad nang hayagan sa gitna ng mga Judio, kundi pumunta siya sa lupaing malapit sa ilang, sa isang bayan na tinatawag na Efraim. Siya'y nanirahan doon kasama ng mga alagad.
At kung ang iyong alay ay butil na handog na luto sa kawali, dapat na ang iyong handog ay piling harina na walang pampaalsa na hinaluan ng langis.
“Kapag ang isang lalaki ay bagong kasal, hindi siya lalabas upang sumama sa hukbo ni mamamahala ng anumang katungkulan. Siya'y magiging malaya sa bahay sa loob ng isang taon at kanyang pasasayahin ang kanyang asawa na kanyang kinuha.
at si Anas, na pinakapunong pari, si Caifas, si Juan, si Alejandro, at ang buong angkan ng pinakapunong pari.
Sa gayo'y nagkaroon ng kapayapaan at tumatag ang iglesya sa buong Judea, Galilea at Samaria, na namumuhay na may takot sa Panginoon at may kaaliwan ng Espiritu Santo, ito ay dumami.
Ilagay mo ang mga ito sa toldang tipanan sa harap ng patotoo, kung saan ako nakikipagtagpo sa inyo.
Kinabukasan, sinabi ng panganay sa bunso, “Tingnan mo, ako'y sumiping kagabi sa aking ama. Painumin din natin siya ng alak sa gabing ito. Pumasok ka at sumiping sa kanya upang mapanatili natin ang binhi ng ating ama.”
Ibinuhos ng ikapitong anghel ang kanyang mangkok sa himpapawid at lumabas sa templo ang isang malakas na tinig, mula sa trono na nagsasabi, “Naganap na!”
Ang taong lumilikha ng pagkakabaha-bahagi, pagkatapos nang una at ikalawang pagsaway ay iwasan mo;
Ang inyong paggiik ay aabot hanggang sa pag-aani ng mga ubas, at ang pag-aani ng ubas ay aabot sa panahon ng paghahasik; at kakainin ninyo ang inyong pagkain hanggang magkaroon kayo ng sapat at mabubuhay kayong tiwasay sa inyong lupain.
Ngunit ang mga barko ay manggagaling sa baybayin ng Kittim at kanilang pahihirapan ang Ashur at Eber, at siya man ay pupuksain.”
Pagkatapos ng mga bagay na ito, dumating ang salita ng Panginoon kay Abram sa isang pangitain, “Huwag kang matakot, Abram; ako ang iyong kalasag, ang iyong gantimpala ay magiging napakadakila.”
at kung ang sinuman ay mag-alis sa mga salita ng aklat ng propesiyang ito, aalisin ng Diyos ang kanyang bahagi sa punungkahoy ng buhay at sa banal na lunsod, na nakasulat sa aklat na ito.
Sumagot siya sa kanila, “Sino ang aking ina at ang aking mga kapatid?”
at, ‘Aalalayan ka nila ng kanilang mga kamay, baka masaktan mo ang iyong paa sa isang bato.’
Sapagkat tayong lahat ay kailangang humarap sa hukuman ni Cristo upang bawat isa ay tumanggap ng kabayaran sa mga bagay na ginawa niya sa pamamagitan ng katawan, maging mabuti o masama.
At sinabi nila sa isa't isa, “Ito ay sapagkat wala tayong tinapay.”
At sinabi ni Moises, “Ipinapakiusap ko sa iyo na huwag mo kaming iwan, sapagkat nalalaman mo kung paanong magkakampo kami sa ilang, at ikaw ay magiging mata para sa amin.
Ngunit muling nagkaila siya. At pagkaraan ng ilang sandali, sinabing muli ng mga nakatayo roon kay Pedro, “Tunay na ikaw ay isa sa kanila, sapagkat ikaw ay taga-Galilea.”
Nang mapalabas na ang demonyo, nagsalita ang dating pipi. Namangha ang maraming tao at nagsabi, “Wala pang nakitang tulad nito sa Israel.”
Ang Panginoon ay maghahari magpakailanpaman.”
Subalit mabuti ang maging laging masigasig sa mabuting bagay at hindi lamang kapag ako'y kaharap ninyo.
Pasanin ninyo ang aking pamatok, at matuto kayo sa akin; sapagkat ako'y maamo at may mapagpakumbabang puso at makakatagpo kayo ng kapahingahan para sa inyong mga kaluluwa.
Tuwing siya'y aalihan nito, ibinubuwal siya, nagbububula ang kanyang bibig, nagngangalit ang kanyang mga ngipin at siya'y naninigas. Sinabi ko sa iyong mga alagad na palayasin iyon ngunit hindi nila magawa.”
Sa kanya'y nakikipag-usap ako nang harapan, nang maliwanag, at hindi sa malabong salitaan; at ang anyo ng Panginoon ay kanyang nakikita. Bakit hindi kayo natakot na magsalita laban sa aking lingkod na si Moises?”
o sa pakikipag-away ay nanuntok na anupa't namatay, ang nanuntok ay tiyak na papatayin; siya'y mamamatay-tao; ang tagapaghiganti ng dugo ay siyang papatay sa pumatay, kapag kanyang natagpuan siya.
Subalit ang kanilang mga pag-iisip ay tumigas, sapagkat hanggang sa araw na ito, kapag kanilang binabasa ang lumang tipan, ang dating talukbong ay nananatiling hindi itinataas, sapagkat tanging sa pamamagitan ni Cristo ito inaalis.
Ang mga anak ng iyong hinirang na kapatid na babae ay bumabati sa iyo.
Ngunit sinasabi ko sa inyo, ‘Huwag ninyong labanan ang masamang tao.’ At kung ikaw ay sampalin ng sinuman sa kanang pisngi, iharap mo rin sa kanya ang kabila.
Kaya't isinalaysay ng puno ng mga katiwala ng kopa ang kanyang panaginip kay Jose at sinabi sa kanya, “Sa aking panaginip ay may isang puno ng ubas sa aking harapan.
Lumabas si Jesus sa templo at paalis na, nang lumapit sa kanya ang mga alagad niya upang ipakita sa kanya ang mga gusali ng templo.
Nang ito'y marinig ni Jesus, sinabi niya sa kanila, “Ang malalakas ay hindi nangangailangan ng manggagamot, kundi ang mga maysakit. Hindi ako naparito upang tawagin ang mga matuwid, kundi ang mga makasalanan.”
Kanyang pinagbilinan si Josue na anak ni Nun at sinabi, “Ikaw ay magpakalakas at magpakatapang; sapagkat iyong ipapasok ang mga anak ni Israel sa lupaing ipinangakong ibibigay ko sa kanila; at ako'y magiging kasama mo.”
Kanilang sasabihin sa matatanda sa kanyang bayan, ‘Itong aming anak ay matigas ang ulo at mapaghimagsik at ayaw niyang pakinggan ang aming tinig; siya'y matakaw at maglalasing.’
Dahil dito ay nagsasalita ako sa kanila sa pamamagitan ng mga talinghaga, sapagkat sa kanilang pagtingin ay hindi sila nakakakita, at sa kanilang pakikinig ay hindi sila nakakarinig, at hindi sila nakakaunawa.
Ano sa palagay ninyo? Kung ang isang tao ay may sandaang tupa, at isa sa kanila ay naligaw. Hindi ba niya iiwan ang siyamnapu't siyam sa kabundukan, at hahayo upang hanapin ang naligaw?
“Kapag ang lahat ng mga bagay na ito ay dumating sa iyo, ang pagpapala at ang sumpa na inilagay ko sa harapan mo, at iyong bulay-bulayin ang mga iyon sa gitna ng lahat ng mga bansa na pinagtabuyan sa iyo ng Panginoon mong Diyos
Sa ganoon ang buong Israel ay maliligtas; gaya ng nasusulat, “Lalabas mula sa Zion ang Tagapagligtas; ihihiwalay niya ang kasamaan mula sa Jacob.”
Sumagot si Jesus, “Hindi ba ninyo nabasa ang ginawa ni David, nang siya at ang mga kasamahan niya ay nagutom?
At lumabas ang isa pang anghel mula sa templo sa langit na siya rin ay may matalas na karit.
Sinabi ng mga apostol sa Panginoon, “Dagdagan mo ang pananampalataya namin.”
Subalit nangyari ang lahat ng ito, upang matupad ang mga kasulatan ng mga propeta.” Pagkatapos ay iniwan siya ng lahat ng mga alagad at sila'y tumakas.
Sapagkat lahat ng mga panganay sa mga Israelita ay akin, maging tao o hayop. Nang araw na aking lipulin ang lahat ng mga panganay sa lupain ng Ehipto ay aking itinalaga sila para sa akin.
Ang hangganan ay pababa sa Jordan, at ang dulo niyon ay abot sa Dagat ng Asin. Ito ang magiging inyong lupain ayon sa mga hangganan niyon sa palibot.”
Ibinigay din ng Panginoon nating Diyos sa ating kamay si Og, na hari ng Basan, at ang buong lunsod niya; at ating pinuksa siya hanggang sa walang natira sa kanya.
Muling nakilala ni Adan ang kanyang asawa at siya'y nanganak ng isang lalaki, at tinawag ang kanyang pangalan na Set; sapagkat kanyang sinabi, “Binigyan ako ng Diyos ng ibang anak na kahalili ni Abel, sapagkat siya'y pinatay ni Cain.”
Ngunit kung ang mga iyon ay pawawalang-bisa ng kanyang asawa sa araw na marinig, hindi magkakabisa ang anumang bagay na binitiwan ng kanyang mga labi tungkol sa kanyang mga panata o tungkol sa itinali niya sa kanyang sarili. Patatawarin siya ng Panginoon .
Kanilang pinulot ang labindalawang kaing na punô ng pira-pirasong tinapay at mga isda.
Sinabi ng Panginoon kay Moises, “Ang puso ni Faraon ay nagmamatigas, ayaw niyang paalisin ang bayan.
Kanyang ginawa ang lambong na telang asul, kulay-ube, at pula, at hinabing pinong lino na may mga kerubin na gawa ng bihasang manggagawa.
At biglang nagpakita ang isang anghel ng Panginoon at tumanglaw ang isang liwanag sa kulungan. Tinapik niya si Pedro sa tagiliran at siya'y ginising, na sinasabi, “Bumangon kang madali.” At nalaglag ang mga tanikala sa kanyang mga kamay.
Noon, ang buong lupa ay iisa ang wika at magkakatulad ang salita.
O kung siya'y humingi ng itlog, bibigyan kaya niya ng alakdan?
Sila'y umupo sa harapan niya, ang panganay ayon sa kanyang pagkapanganay, at ang bunso ayon sa kanyang pagkabunso. At ang mga lalaki ay nagtinginan sa isa't isa na may pagkamangha.
Kanyang kinuha ang aklat ng tipan, binasa sa pandinig ng bayan, at kanilang sinabi, “Lahat ng sinabi ng Panginoon ay aming gagawin, at kami ay magiging masunurin.”
Kahit hinalughog mo ang lahat ng aking kasangkapan, anong natagpuan mong kasangkapan ng iyong bahay? Ilagay mo rito sa harapan ng aking mga kamag-anak at ng iyong mga kamag-anak at hayaan mong magpasiya sila sa ating dalawa.
Inatasan ni Moises ang bayan ng araw na iyon, na sinasabi:
sapagkat ang namatay ay pinalaya na mula sa kasalanan.
Sila'y naglakbay mula sa Dagat na Pula at nagkampo sa ilang ng Zin.
“Kung sa lupain na ibinibigay sa iyo ng Panginoon mong Diyos upang angkinin ay may matagpuang pinatay na nakabulagta sa parang at hindi malaman kung sinong pumatay sa kanya,
Subalit sumagot ang Panginoon at sinabi sa kanya, “Marta, Marta, nag-aalala ka at nababagabag tungkol sa maraming bagay;
‘Tumindig kayo, at maglakbay. Dumaan kayo sa libis ng Arnon, at ibinigay ko na sa iyong kamay si Sihon na Amoreo, na hari ng Hesbon, at ang kanyang lupain. Pasimulan mong angkinin, at kalabanin mo siya sa digmaan.
Noon ay may mga naninirahan sa Jerusalem na mga relihiyosong Judio, buhat sa bawat bansa sa ilalim ng langit.
kundi dahil din naman sa atin, na ibibilang sa atin na mga sumasampalataya sa kanya na muling bumuhay kay Jesus na ating Panginoon mula sa mga patay,
Sapagkat noo'y araw ng Paghahanda, upang maiwasan na ang mga katawan ay manatili sa krus sa araw ng Sabbath (sapagkat dakila ang araw ng Sabbath na iyon), hiniling ng mga Judio kay Pilato na baliin ang kanilang mga binti at sila'y alisin doon.
na pinalayas sa harapan mo ang mga bansang lalong malalaki at makapangyarihan kaysa sa iyo, upang ikaw ay kanyang papasukin, upang ibigay sa iyo ang kanilang lupain bilang pamana, gaya sa araw na ito.
hanggang makarating tayong lahat sa pagkakaisa ng pananampalataya, at sa ganap na pagkakilala sa Anak ng Diyos, hanggang maging taong may sapat na gulang, hanggang sa sukat ng ganap na kapuspusan ni Cristo.
Ang mga kumain ay apat na libong lalaki, bukod pa sa mga babae at sa mga bata.
At tinanong niya sila, “Ngunit, sino ako ayon sa sinasabi ninyo?” Sumagot si Pedro at sinabi sa kanya, “Ikaw ang Cristo.”
Kaya't siya'y aking ipapahagupit at palalayain.”
aking tinatawag ang langit at ang lupa upang sumaksi laban sa inyo sa araw na ito, upang kayo'y kaagad na mamatay sa lupain na inyong patutunguhan sa kabila ng Jordan upang angkinin, hindi ninyo mapapatagal ang inyong mga araw doon, kundi kayo'y lubos na mapupuksa.
Sinabi ni Juda kay Israel na kanyang ama. “Pasamahin mo sa akin ang bata at hayaan mong kami ay makaalis na upang tayo'y mabuhay at huwag mamatay—kami, ikaw, at ang aming mga anak.
Subalit sa pagnanais niya na ipagmatuwid ang kanyang sarili ay sinabi kay Jesus, “At sino ang aking kapwa?”
At ang nagpakawala ng kambing na ukol kay Azazel ay maglalaba ng kanyang mga damit at paliliguan ang kanyang katawan sa tubig, at pagkatapos ay papasok siya sa kampo.
Mula sa bakol ng tinapay na walang pampaalsa na inilagay sa harapan ng Panginoon , ay kumuha siya ng isang tinapay na walang pampaalsa, at ng isang tinapay na nilangisan at ng isang manipis na tinapay, at inilagay sa ibabaw ng taba at sa ibabaw ng kanang hita.
Ihahandog ni Aaron ang mga Levita sa harap ng Panginoon bilang handog na iwinagayway sa mga anak ni Israel upang kanilang gawin ang paglilingkod sa Panginoon .
Nakarating sila sa Capernaum at nang siya'y nasa bahay na ay tinanong niya sila, “Ano ang pinagtatalunan ninyo sa daan?”
Sinabi ni Jacob kay Laban, “Ibigay mo sa akin ang aking asawa sapagkat naganap na ang aking mga araw at hayaan mong ako'y sumiping sa kanya.”
Pinuksa natin silang lahat, na gaya ng ating ginawa kay Sihon na hari ng Hesbon, ating pinuksa ang bawat lunsod, ang mga lalaki, mga babae, at mga bata.
Sa Cesarea ay may isang lalaki na ang pangalan ay Cornelio, isang senturion ng tinatawag na pulutong Italiano;
Ang tumatanggap sa isang propeta alang-alang sa pangalan ng propeta ay tatanggap ng gantimpala ng isang propeta; at ang tumatanggap sa isang taong matuwid alang-alang sa pangalan ng isang taong matuwid ay tatanggap ng gantimpala ng isang taong matuwid.
Alam nating hindi pinapakinggan ng Diyos ang mga makasalanan, subalit kung ang sinuman ay sumasamba sa Diyos at gumaganap ng kanyang kalooban, ito ang kanyang pinapakinggan.
Ang mga anak ni Neftali ayon sa kanilang mga angkan: kay Jahzeel, ang angkan ng mga Jahzeelita; kay Guni, ang angkan ng mga Gunita.
Noon ay nagtuturo siya sa isa sa mga sinagoga nang araw ng Sabbath.
Ito ay magiging kay Aaron at sa kanyang mga anak, at ito ay kanilang kakainin sa dakong banal, sapagkat ito ay kabanal-banalang bahagi para sa kanya mula sa mga handog sa Panginoon na pinaraan sa apoy, isang walang hanggang bahagi.”
Tinipon nina Moises at Aaron ang kapulungan sa harap ng malaking bato, at kanyang sinabi sa kanila, “Makinig kayo ngayon, mga mapaghimagsik! Ikukuha ba namin kayo ng tubig sa malaking batong ito?”
Makikipagdigma ang mga ito laban sa Kordero at sila'y dadaigin ng Kordero, sapagkat siya'y Panginoon ng mga panginoon at Hari ng mga hari, at ang mga kasama niya ay mga tinawag, mga hinirang at tapat.”
Siya'y iniligtas sa lahat ng kanyang kapighatian, at binigyan siya ng biyaya at karunungan sa harapan ng Faraon na hari ng Ehipto; at kanyang pinili siya upang mamahala sa Ehipto at sa buong bahay niya.
na mga lalaking nagsuong ng kanilang mga buhay sa panganib alang-alang sa pangalan ng ating Panginoong Jesu-Cristo.
At mula noon ay humanap siya ng pagkakataon na maipagkanulo si Jesus.
Ang tipang ito ay hindi ginawa ng Panginoon sa ating mga ninuno, kundi sa atin, sa ating lahat na nariritong buháy sa araw na ito.
Sapagkat saksi ko ang Diyos, na aking pinaglilingkuran sa aking espiritu sa ebanghelyo ng kanyang Anak, na walang tigil na binabanggit ko kayo sa aking panalangin,
at nagsisigawan nang may malakas na tinig, na nagsasabi, “Ang pagliligtas ay sa aming Diyos na nakaupo sa trono, at sa Kordero!”
sapagkat kung gayon ay kailangan siyang paulit-ulit na maghirap mula pa nang lalangin ang sanlibutan. Subalit ngayon, minsanan siyang nahayag sa katapusan ng panahon para sa pag-aalis ng mga kasalanan sa pamamagitan ng pag-aalay ng kanyang sarili.
Nang makita niya ang napakaraming tao, nahabag siya sa kanila, sapagkat sila ay nangangamba at nanlulupaypay na gaya ng mga tupa na walang pastol.
At naalala nila ang kanyang mga salita,
sapagkat nalalaman ko na ang kahihinatnan nito'y sa aking ikaliligtas, sa pamamagitan ng inyong mga panalangin at sa saganang tulong ng Espiritu ni Jesu-Cristo.
Ngunit si Josue na anak ni Nun, at si Caleb na anak ni Jefone ay naiwang buháy sa mga taong iyon na pumaroon upang lihim na siyasatin ang lupain.
Mayroong isang babaing propeta, si Ana na anak ni Fanuel, mula sa lipi ni Aser. Siya ay napakatanda na at may pitong taong namuhay na kasama ng kanyang asawa mula nang sila ay ikasal,
At hindi ako nakakita ng templo roon, sapagkat ang Panginoong Diyos na Makapangyarihan sa lahat at ang Kordero ang siyang templo roon.
Ibigin ninyo ang mga dayuhan, sapagkat kayo'y naging mga dayuhan din sa lupain ng Ehipto.
Kaya't si Moises ay lumabas sa lunsod mula sa Faraon, at iniunat ang kanyang mga kamay sa Panginoon . Ang mga kulog at ang yelong ulan ay tumigil at ang ulan ay hindi na bumuhos sa lupa.
At ang ahas ay nagbuga mula sa kanyang bibig ng tubig sa babae na gaya ng isang ilog upang tangayin siya ng agos.
Siya'y lumapit, at kinuha ang aklat sa kanang kamay ng nakaluklok sa trono.
“Ang isang manghahasik ay humayo upang maghasik ng binhi. Sa kanyang paghahasik, ang ilan ay nahulog sa tabi ng daan, napagyapakan, at ito'y kinain ng mga ibon sa himpapawid.
Sapagkat tayo'y nagiging kabahagi ni Cristo kung ating hinahawakang matatag ang pasimula ng ating pagtitiwala hanggang sa katapusan.
Kung ihahasa ko ang aking makintab na tabak, at ang aking kamay ay humawak sa hatol, ako'y maghihiganti sa aking mga kaaway, at aking gagantihan ang mga napopoot sa akin.
Dinala nila sa kanya ang isang bingi at may kapansanan sa pagsasalita, at siya'y pinakiusapan nila na ipatong ang kanyang kamay sa kanya.
“Kapag ikaw ay gagawa ng isang panata sa Panginoon mong Diyos, huwag kang magiging mabagal sa pagbabayad nito, sapagkat tiyak na hihingin sa iyo ng Panginoon mong Diyos, at ikaw ay magkakasala.
Tumira siya sa ilang ng Paran at ikinuha siya ng kanyang ina ng asawa sa lupain ng Ehipto.
Sinabi ng Panginoon kay Abram, “Tunay na dapat mong malaman na ang iyong binhi ay magiging taga-ibang bayan sa lupaing hindi kanila, at sila'y magiging mga alipin doon, at sila'y pahihirapan sa loob ng apatnaraang taon;
Nararapat bang kami ay magbuwis kay Cesar, o hindi?”
Nang mag-umaga na, nagkatipon ang kapulungan ng matatanda sa bayan, ang mga punong pari, at gayundin ang mga eskriba. Kanilang dinala siya sa kanilang Sanhedrin, at sinabi nila,
Nang magkagayo'y lihim nilang sinulsulan ang ilang lalaki, na nagsasabi, “Narinig naming nagsasalita siya ng mga salitang kalapastanganan laban kay Moises at sa Diyos.”
Aming sinabi sa aking panginoon, ‘Hindi maiiwan ng bata ang kanyang ama, at kung iiwan niya ang kanyang ama, ang kanyang ama ay mamamatay.’
At kanyang sinabi, “Sabihin mo sa akin ang iyong upa, at ibibigay ko sa iyo.”
at mula roo'y sa Filipos, na pangunahing lunsod sa distrito ng Macedonia, at ito'y sakop ng Roma. Kami ay tumigil sa lunsod na ito nang ilang araw.
At isusuot ng pari ang kanyang mahabang kasuotang lino sa ibabaw ng kanyang mga pang-ilalim na lino kasunod ng kanyang katawan; at kukunin niya ang mga abo ng handog na sinusunog na sinunog sa apoy sa ibabaw ng dambana, at ilalagay niya sa tabi ng dambana.
Sila'y naghandog sa mga demonyo na hindi Diyos, sa mga diyos na hindi nila nakilala, sa mga bagong diyos na kalilitaw pa lamang, na hindi kinatakutan ng inyong mga ninuno.
Lumabas ang apoy mula sa harapan ng Panginoon at tinupok ang handog na sinusunog at ang taba sa ibabaw ng dambana. Nang makita iyon ng buong bayan, sila ay nagsigawan at nagpatirapa.
Siya'y aking pinababalik sa iyo, na kasama ang aking sariling puso.
upang, yamang inaring-ganap sa pamamagitan ng kanyang biyaya, tayo'y maging mga tagapagmana ayon sa pag-asa sa buhay na walang hanggan.
Kayo'y bumalik at umiyak sa harapan ng Panginoon , ngunit hindi dininig ng Panginoon ang inyong tinig, ni pinakinggan kayo.
Ang bawat natakot sa salita ng Panginoon sa mga lingkod ni Faraon ay nagpauwi ng kanyang mga alipin at ng kanyang hayop sa mga bahay;
Si Zacarias na kanyang ama ay napuno ng Espiritu Santo at sinabi ang propesiyang ito,
At nabuhay si Terah ng pitumpung taon, at naging anak sina Abram, Nahor at Haran.
Pagkatapos, isa sa labindalawa, na tinatawag na Judas Iscariote ang nagpunta sa mga punong pari,
Si Jetro na pari sa Midian, biyenan ni Moises, ay nakabalita ng lahat na ginawa ng Diyos kay Moises at sa Israel na kanyang bayan, kung paanong inilabas ng Panginoon ang Israel sa Ehipto.
“Ito ang batas tungkol sa handog para sa budhing maysala: ito ay kabanal-banalan.
Tungkol sa mga bagay na isinusulat ko sa inyo, sa harapan ng Diyos, hindi ako nagsisinungaling.
Ako'y ipinakong kasama ni Cristo at hindi na ako ang nabubuhay, kundi si Cristo ang nabubuhay sa akin, at ang buhay na ikinabubuhay ko ngayon sa laman ay ikinabubuhay ko sa pamamagitan ng pananampalataya sa Anak ng Diyos na sa akin ay nagmahal, at nagbigay ng kanyang sarili dahil sa akin.
Dahil sa mga bagay na ito ay dumarating ang poot ng Diyos sa mga anak ng pagsuway.
Sapagkat kanyang hinamak ang salita ng Panginoon , at sinira ang kanyang utos; ang taong iyon ay lubos na ititiwalag. Ang kanyang kasamaan ay tataglayin niya.’”
Sinabi sa kanya ni Jesus, “Babae, anong kinalaman niyon sa akin at sa iyo? Ang aking oras ay hindi pa dumating.”
Nang sumunod na araw, dumukot siya ng dalawang denario at ibinigay sa may-ari ng bahay-panuluyan at sinabi niya, ‘Alagaan mo siya, at sa anumang karagdagan mo pang gastusin ay babayaran kita sa aking pagbabalik.’
Nang marinig nila ang mga bagay na ito, napuno ng galit ang lahat ng nasa sinagoga.
at nakasuot sa inyong mga paa ang pagiging handa para sa ebanghelyo ng kapayapaan.
Dahil sa pagtitiwalang ito, nais kong pumunta muna sa inyo, upang kayo'y magkaroon ng pangalawang biyaya.
At kung siya'y may asawa at mamanata o magbitiw sa kanyang labi ng anumang salita na hindi pinag-isipan na doo'y itinali niya ang kanyang sarili,
Siya'y gumawa ng isang pantakip sa tolda na balat ng mga tupa na kinulayan ng pula, at ng isang takip na balat ng kambing sa ibabaw.
At namatay ang lahat ng laman na gumagalaw sa ibabaw ng lupa: ang mga ibon, mga maamong hayop, mga mailap na hayop, bawat gumagapang sa ibabaw ng lupa, at lahat ng tao.
hanggang sa mapawi ang galit sa iyo ng iyong kapatid at malimutan niya ang ginawa mo sa kanya. Pagkatapos ay magsusugo ako at ipasusundo kita mula roon. Bakit kailangang kapwa kayo mawala sa akin sa isang araw?”
Sinagot sila ni Jesus, “Katotohanang sinasabi ko sa inyo, ako'y inyong hinahanap hindi dahil sa nakakita kayo ng mga tanda, kundi dahil sa kayo'y kumain ng tinapay, at kayo'y nabusog.
Sapagkat kung ang unang tipang iyon ay walang kapintasan, hindi na sana kailangang humanap pa ng pangalawa.
Ang mga Fariseo at mga eskriba ay nagbulung-bulungan, na nagsasabi, “Tinatanggap ng taong ito ang mga makasalanan at kumakaing kasalo nila.”
Baka sabihin ng mga tao sa lupaing pinaglabasan mo sa amin: “Sapagkat hindi sila naipasok ng Panginoon sa lupain na ipinangako sa kanila, at sapagkat napoot siya sa kanila, ay inilabas sila upang patayin sa ilang.”
Sapat na sa alagad ang maging tulad ng kanyang guro at sa alipin ang maging tulad ng kanyang panginoon. Kung tinawag nilang Beelzebul ang panginoon ng sambahayan, gaano pa kaya nila lalaitin ang mga kasambahay niya!
Ngunit si Pedro ay nagpasimulang magpaliwanag sa kanila nang sunud-sunod, na sinasabi:
Kanyang dadalhin ang mga ito sa pari na siyang maghahandog nito, ang una ay para sa handog pangkasalanan. Pipilipitin niya ang ulo mula sa leeg, ngunit hindi ito paghihiwalayin.
Sapagkat siya'y umaasa sa lunsod na may mga kinasasaligan, na ang nagplano at nagtayo ay ang Diyos.
Isang kakilakilabot na bagay ang mahulog sa mga kamay ng Diyos na buháy.
Pagkatapos ay kinuha niya ang taba, ang matabang buntot, at ang lahat ng tabang bumabalot sa lamang-loob, ang lamad ng atay, ang dalawang bato kasama ang taba ng mga iyon, at ang kanang hita.
at sila'y sasagot at sasabihin, ‘Ang aming kamay ay hindi nagpadanak ng dugong ito, ni nakita ng aming mga mata na ito'y dumanak.
Sapagkat sinasabi ko sa inyo na mula ngayon ay hindi na ninyo ako makikita, hanggang sa inyong sabihin, ‘Mapalad ang pumaparito sa pangalan ng Panginoon.’”
Sapagkat maging nang kami ay dumating sa Macedonia, ang aming mga katawan ay hindi nagkaroon ng kapahingahan, kundi pinipighati sa bawat paraan—sa labas ay labanan, sa loob ay takot.
Makikilala ninyo sila sa kanilang mga bunga. Nakakapitas ba ng mga ubas sa mga tinikan, o ng mga igos sa mga dawagan?
Kaya, maging matiyaga kayo, mga kapatid, hanggang sa pagdating ng Panginoon. Hinihintay ng magsasaka ang mahalagang bunga ng lupa, na siya'y nagtitiis para dito hanggang sa ito ay tumanggap ng una at huling ulan.
Kaya't yamang nananatiling bukas para sa ilan upang makapasok doon, at ang mga pinangaralan ng magandang balita nang una ay hindi nakapasok dahil sa pagsuway,
Subalit hawak niya ang pagiging pari magpakailanman, sapagkat siya ay nagpapatuloy magpakailanman.
Ngunit ang maraming nauuna ay mahuhuli, at ang huli ay mauuna.”
“At kukunin mo ang dibdib ng lalaking tupa na itinalaga ni Aaron, at iwawagayway mo ito bilang handog na iwinawagayway sa harapan ng Panginoon ; at iyon ang magiging iyong bahagi.
Totoong nakita ko ang kaapihan ng aking bayang nasa Ehipto, at narinig ko ang kanilang daing, at ako'y bumaba upang sila'y iligtas. Ngayo'y lumapit ka, susuguin kita sa Ehipto.’
Ginawa ni Moises ang ayon sa iniutos ng Panginoon sa kanya at kanyang isinama si Josue. Kanyang iniharap siya sa paring si Eleazar at sa buong kapulungan.
Ang bawat isa ay magbigay ayon sa ipinasiya ng kanyang puso, hindi mabigat sa kalooban, o dala ng pangangailangan, sapagkat iniibig ng Diyos ang nagbibigay na masaya.
“Sapagkat ang pangalan ng Diyos ay nalalait sa mga Hentil dahil sa inyo,” gaya ng nasusulat.
May dalawang babaing magtatrabaho sa isang gilingan; ang isa'y kukunin, at ang isa'y iiwan.
“Kapag natanggal na ng Panginoon mong Diyos sa harapan mo ang mga bansa na iyong papasukin upang samsaman; at nasamsaman mo na sila at nakapanirahan sa kanilang lupain,
Mula sa harap ng Panginoon ay inilabas ni Moises ang lahat ng tungkod sa harap ng lahat ng mga anak ni Israel at kanilang pinagmasdan. Kinuha ng bawat lalaki ang kanyang tungkod.
huwag maging tamad sa pagsisikap, maging maalab sa espiritu, na naglilingkod sa Panginoon.
At sinabi niya sa kanila, “Subalit ano ang sinasabi ninyo kung sino ako?” At sumagot si Pedro, “Ang Cristo ng Diyos.”
at nang maging sakdal, siya ang naging pinagmulan ng walang hanggang kaligtasan ng lahat ng mga sumusunod sa kanya;
Nalalaman ko na kayo'y binhi ni Abraham; subalit pinagsisikapan ninyong ako'y patayin, sapagkat ang salita ko'y walang paglagyan sa inyo.
Sinabi naman ni Jesus sa kanya, “Dahil sa salitang iyan, makakaalis ka na, lumabas na ang demonyo sa iyong anak.”
Ang mga lunsod na inyong ibibigay ay ang inyong anim na lunsod-kanlungan.
Nang marinig nila ito, nasaktan ang kanilang puso at sinabi kay Pedro at sa ibang mga apostol, “Mga ginoo, mga kapatid, anong dapat naming gawin?”
Ang mga anak ni Israel, ang buong kapulungan, ay dumating sa ilang ng Zin nang unang buwan; at ang bayan ay nanatili sa Kadesh. Si Miriam ay namatay, at inilibing doon.
Ito ang aklat ng mga salinlahi ni Adan. Nang lalangin ng Diyos ang tao, siya ay nilalang sa wangis ng Diyos.
At sinabi niya kay Tomas, “Ilagay mo rito ang iyong daliri at tingnan mo ang aking mga kamay. Ilapit mo rito ang iyong kamay at ilagay mo sa aking tagiliran. Huwag kang mag-alinlangan kundi sumampalataya.”
Tinanong siya ni Pilato, “Ikaw ba ang Hari ng mga Judio?” Sumagot siya sa kanya, “Ikaw ang nagsasabi.”
Binigyan ni Jose ng pagkain ang kanyang ama, ang kanyang mga kapatid, at ang buong sambahayan ng kanyang ama, ayon sa bilang ng kanilang mga anak.
Kung ganito ang pakikitungong gagawin mo sa akin ay patayin mo na ako. Kung ako'y nakasumpong ng biyaya sa iyong paningin, huwag mo nang ipakita sa akin ang aking paghihirap.”
Ang laman ng handog pangkapayapaan bilang pasasalamat ay kakainin sa araw ng paghahandog nito; hindi siya magtitira nito hanggang sa umaga.
Inihanda ni Jose ang kanyang karwahe at umahon upang salubungin si Israel na kanyang ama sa Goshen. Siya'y humarap sa kanya, yumakap sa kanya, at umiyak nang matagal sa kanyang leeg.
“Subalit kung hindi niya kaya ang halaga ng isang kordero, siya na nagkasala ay magdadala sa Panginoon bilang handog para sa kasalanang kanyang ginawa, ng dalawang batu-bato o ng dalawang batang kalapati—ang isa'y bilang handog pangkasalanan at ang isa'y bilang handog na sinusunog.
Ang iyong buhay ay mabibitin sa pag-aalinlangan sa harapan mo; at ikaw ay matatakot gabi't araw, at mawawalan ng katiyakan ang iyong buhay.
Sa araw na iyon ay hindi kayo magtatanong sa akin ng anuman. Katotohanang sinasabi ko sa inyo, kung kayo'y hihingi ng anuman sa Ama sa aking pangalan ay ibibigay niya ito sa inyo.
‘Sinabi ng Panginoon sa aking Panginoon, “Maupo ka sa aking kanan, hanggang sa mailagay ko ang iyong mga kaaway sa ilalim ng iyong mga paa”’?
At nabuksan ang templo ng Diyos na nasa langit at nakita sa kanyang templo ang kaban ng kanyang tipan; at nagkaroon ng mga kidlat, ng mga tinig, ng mga kulog, ng lindol, at mabigat na yelong ulan.
Nang magkagayo'y sumagot sina Laban at Betuel at sinabi, “Sa Panginoon ito nagmumula. Kami ay hindi makapagsasabi sa iyo ng masama o ng mabuti.
Subalit bago sila nagsihiga, ang mga lalaki ng lunsod, ang mga lalaki sa Sodoma, maging mga bata at matanda, lahat ng mga tao hanggang sa pinakahuling tao, ay pumalibot sa bahay.
Hindi nag-atubili ang binata na gawin iyon, sapagkat nalugod siya sa anak na babae ni Jacob. Si Shekem ay ang pinakamarangal sa buong sambahayan ng kanyang ama.
Sa iglesya na nasa Antioquia ay may mga propeta at mga guro, si Bernabe, si Simeon na tinatawag na Niger, si Lucio na taga-Cirene, si Manaen na kinakapatid ni Herodes na tetrarka, at si Saulo.
Gayon ang ginawa ng mga anak ni Israel ayon sa lahat na iniutos ng Panginoon kay Moises.
Ang anghel ng Diyos ay nagsalita sa akin sa panaginip, ‘Jacob,’ at sinabi ko, ‘Narito ako.’
At tumakbo si Abraham sa bakahan at kumuha ng isang bata at malusog na baka, at ibinigay sa alipin na nagmamadaling inihanda ito.
kapag mayroon na silang mga dahon ay nakikita mismo ninyo at nalalaman na malapit na ang tag-araw.
at maliwanagan ang lahat ng mga tao kung ano ang pagiging katiwala sa hiwaga, na sa lahat ng panahon ay inilihim ng Diyos na lumalang ng lahat ng mga bagay,
Habang nagkakatipon ang mga Fariseo ay tinanong sila ni Jesus,
Kaya't sabihin mo, narito, ibinibigay ko sa kanya ang aking tipan ng kapayapaan.
Ang mga anak ni Gad ayon sa kanilang mga angkan: kay Zefon, ang angkan ng mga Zefonita; kay Hagui, ang angkan ng mga Haguita; kay Suni, ang angkan ng mga Sunita;
Kung ako'y hindi gumawa sa gitna nila ng mga gawang hindi ginawa ng sinuman, hindi sana sila nagkaroon ng kasalanan. Subalit ngayon ay kanilang nakita at kinapootan nila ako at ang aking Ama.
Sapagkat ganito ang ipinag-utos sa amin ng Panginoon, na sinasabi, ‘Inilagay kitang isang ilaw sa mga Hentil, upang ikaw ay magdala ng kaligtasan hanggang sa dulo ng daigdig.’”
pagsamba sa diyus-diyosan, pangkukulam, alitan, pagtatalo, paninibugho, pagkagalit, pagkamakasarili, pagkakabaha-bahagi, mga pagkakampi-kampi,
At kung si Satanas ay nahahati rin laban sa kanyang sarili, paanong tatatag ang kanyang kaharian? Sapagkat sinasabi ninyong nagpapalayas ako ng mga demonyo sa pamamagitan ni Beelzebul.
Kung paanong ang aming mga ninuno ay pumunta sa Ehipto, at kami ay nanirahan sa Ehipto ng matagal na panahon at pinahirapan kami at ang aming mga ninuno ng mga Ehipcio.
Sinabi sa kanya ng diyablo, “Kung ikaw ang Anak ng Diyos, ipag-utos mo na ang batong ito ay maging tinapay.”
Subalit si Herodes na tetrarka, na sinumbatan niya dahil kay Herodias na asawa ng kanyang kapatid, at dahil sa lahat ng masasamang bagay na ginawa ni Herodes,
Isacar, Zebulon, Benjamin,
Nang magkagayon ay nagsalita sa Faraon ang puno ng mga katiwala ng kopa na sinasabi, “Naaalala ko sa araw na ito ang aking pagkakasala.
Sumagot si Nathanael sa kanya, “Rabi, ikaw ang Anak ng Diyos; ikaw ang Hari ng Israel.”
Kung ang butil na handog ay niluto sa kawali, dapat na ang iyong handog ay piling harina na hinaluan ng langis.
Ito ang tinapay na bumabang galing sa langit, hindi gaya ng tinapay na kinain ng inyong mga ninuno at sila'y namatay. Ang kumakain ng tinapay na ito ay mabubuhay magpakailanman.”
Sapagkat may ilang taong nakapasok nang lihim, ang mga iyon ay matagal nang itinalaga sa kahatulang ito, mga hindi maka-Diyos, na kanilang pinalitan ng kahalayan ang biyaya ng ating Diyos, at itinatatuwa ang kaisa-isa nating Pinuno at Panginoon na si Jesu-Cristo.
Ngunit nang dumating si Cristo na Pinakapunong Pari ng mabubuting bagay na darating, sa pamamagitan ng lalong dakila at lalong sakdal na tabernakulo na hindi gawa ng mga kamay ng tao, samakatuwid ay hindi sa sangnilikhang ito,
gaya nang ginawa sa akin ng mga anak ni Esau na naninirahan sa Seir, at ng mga Moabita na naninirahan sa Ar, hanggang makatawid ako sa Jordan, sa lupaing ibinibigay sa amin ng Panginoon naming Diyos.’
subalit hindi niya pinahalagahan si Cain at ang kanyang handog. Galit na galit si Cain, at nagngitngit ang kanyang mukha.
Minsan ay nanaginip si Jose at nang isalaysay niya ito sa kanyang mga kapatid, lalo pa silang napoot sa kanya.
Nagpapasalamat ako sa Diyos, na aking pinaglilingkuran na may malinis na budhi gaya ng aking mga ninuno, kapag lagi kitang naaalala sa aking mga panalangin gabi't araw.
Doon nila inilibing si Abraham at si Sara na kanyang asawa; at doon nila inilibing si Isaac at si Rebecca na kanyang asawa; at doon ko inilibing si Lea,
Pagpapalain ko ang magbibigay ng pagpapala sa iyo, at susumpain ko ang mga susumpa sa iyo; at sa pamamagitan mo ang lahat ng angkan sa lupa ay pagpapalain.”
Sinabi sa kanya ng Panginoon , “Sino bang gumawa ng bibig ng tao? O sinong gumagawa ng pipi, o bingi, o may paningin, o bulag sa tao? Hindi ba akong Panginoon ?
Pagkatapos, dinala nila ang batang asno kay Jesus at inilagay nila sa ibabaw ng batang asno ang kanilang mga balabal at siya'y sumakay rito.
Ngunit ako'y natatakot na kung paanong si Eva ay dinaya ng ahas sa pamamagitan ng kanyang katusuhan, ang inyong mga pag-iisip ay mailigaw mula sa katapatan at kadalisayan kay Cristo.
Sa harapan hanggang gawing silangan ay may limampung siko.
Hindi siya mag-aasawa sa isang balo, o sa hiniwalayan, o sa isang babaing nadungisan, o sa isang upahang babae; kundi kukuha siya ng isang dalagang malinis sa kanyang sariling bayan bilang asawa.
Subalit ang tungkol sa muling pagkabuhay ng mga patay ay ipinakita maging ni Moises sa kasaysayan tungkol sa mababang punungkahoy, na doon ay tinawag niya ang Panginoon na Diyos ni Abraham, Diyos ni Isaac, at Diyos ni Jacob.
Sumagot si Jesus sa kanila, “Ito ang gawa ng Diyos na inyong sampalatayanan ang kanyang sinugo.”
Sinabi niya sa iba, “Sumunod ka sa akin.” Subalit siya'y sumagot, “Panginoon, hayaan mo muna akong umalis at ilibing ko ang aking ama.”
At sinabi ni Abimelec, “Ano itong ginawa mo sa amin? Paano kung may sumiping sa iyong asawa, at ikaw sana ang naging dahilan upang kami ay magkasala?”
Ang ipinangalan niya sa lugar na iyon ay Bethel, subalit ang dating pangalan ng lunsod ay Luz.
Kaya't lagi kong hinahangad na ipaalala sa inyo ang mga bagay na ito, bagama't inyong nalalaman na, at kayo'y pinapatibay sa katotohanang dumating sa inyo.
Ito'y magiging pinong alabok sa buong lupain ng Ehipto, at magiging pigsang susugat sa tao, at sa hayop sa buong lupain ng Ehipto.”
Nangyari sa kanila ang ayon sa tunay na kawikaan, “Nagbabalik muli ang aso sa kanyang sariling suka,” at, “Ang babaing baboy na nahugasan na, sa paglulublob sa putik.”
Kaya't sina Moises at Aaron ay pinabalik sa Faraon at kanyang sinabi sa kanila, “Humayo kayo, maglingkod kayo sa Panginoon ninyong Diyos; subalit sinu-sino ang aalis?”
Ang Panginoon ay nagpakita kay Abraham sa may punong ensina ni Mamre habang siya'y nakaupo nang kainitan ang araw sa pintuan ng tolda.
At nang ako'y kasama ninyo at nasa pangangailangan, ako'y hindi naging pasanin sa kanino man, sapagkat ang aking mga pangangailangan ay tinustusan ng mga kapatid na galing sa Macedonia. Kaya't aking iniwasan at iiwasan na maging pasanin ninyo sa anumang paraan.
Susuriin ng pari ang pangangati sa ikapitong araw, at kung makitang hindi kumalat ang pangangati sa balat, at tila hindi mas malalim kaysa balat, ipahahayag ng pari na siya ay malinis, at siya'y maglalaba ng kanyang damit at magiging malinis.
na nagsasabi, “Nadatnan naming nakasusing mabuti ang bilangguan, at nakatayo sa mga pintuan ang mga bantay ngunit nang aming buksan ang mga ito ay wala kaming natagpuan sa loob.”
At iyong alalahanin ang lahat ng paraan ng pagpatnubay sa iyo ng Panginoon mong Diyos nitong apatnapung taon sa ilang, upang kanyang pagpakumbabain ka, at subukin ka, upang malaman kung ano ang nasa iyong puso, kung iyong tutuparin ang kanyang mga utos o hindi.
Nagdilim ang kanilang mga pang-unawa, palibhasa'y nahiwalay sa buhay ng Diyos, dahil sa kanilang kamangmangan, dahil sa katigasan ng kanilang mga puso;
Tumingin siya sa buong paligid upang makita kung sino ang gumawa niyon.
Maglalagay ka sa bawat hanay ng dalisay na kamanyang, upang maging handog na tanda para sa tinapay bilang handog na pinaraan sa apoy para sa Panginoon .
Kaya't magalak kayo, O mga langit at kayong mga naninirahan diyan! Kahabag-habag ang lupa at dagat sapagkat ang diyablo'y bumaba sa inyo na may malaking poot, palibhasa'y alam niya na maikli na lamang ang kanyang panahon!”
kay Ozni, ang angkan ng mga Oznita; kay Eri, ang angkan ng mga Erita;
Sapagkat ang sinumang hindi laban sa atin ay panig sa atin.
Dinala ni Moises ang kanilang usapin sa harap ng Panginoon .
At lahat ng mga tao ay maagang pumaparoon sa kanya sa templo upang pakinggan siya.
At isinama ni Balak si Balaam sa tuktok ng Peor na nasa gawing itaas ng ilang.
Hindi mabagal ang Panginoon tungkol sa kanyang pangako, na gaya ng kabagalang itinuturing ng iba, kundi matiyaga sa inyo, na hindi niya ibig na sinuman ay mapahamak, kundi ang lahat ay dumating sa pagsisisi.
Sapagkat kanilang ilalayo ang iyong anak na lalaki sa pagsunod sa akin, upang maglingkod sa ibang mga diyos, sa gayo'y mag-aalab ang galit ng Panginoon laban sa iyo, at mabilis ka niyang pupuksain.
Sinabi niya sa kanya, “Humayo ka, tingnan mo kung mabuti ang kalagayan ng iyong mga kapatid at ng kawan, at balitaan mo ako.” Siya'y kanyang isinugo mula sa libis ng Hebron, at dumating siya sa Shekem.
Ito ay upang matupad ang sinabi sa pamamagitan ng propeta, “Bubuksan ko ang aking bibig sa pagsasalita ng mga talinghaga; isasalaysay ko ang mga natatagong bagay mula pa nang itatag ang sanlibutan.”
Subalit huwag kang maniniwala sa kanila, sapagkat mahigit na apatnapu sa kanilang mga tao ang nag-aabang sa kanya. Sila'y namanata sa ilalim ng isang sumpa na hindi kakain ni iinom man hanggang sa siya'y kanilang mapatay. Ngayo'y handa na sila at naghihintay ng iyong pagsang-ayon.”
At binigkas ni Balaam ang kanyang talinghaga, na sinasabi, “Tumindig ka, Balak, at iyong pakinggan, makinig ka sa akin, ikaw na anak ni Zipor.
Sila'y madaling lumihis sa daan na aking iniutos sa kanila. Sila'y gumawa ng isang hinulmang guya at kanilang sinamba, at hinandugan ito, at kanilang sinabi, ‘Ang mga ito ang iyong mga diyos, O Israel, na naglabas sa iyo mula sa lupain ng Ehipto!’”
Dalhin din ninyo ang inyong kapatid, at muli kayong maglakbay pabalik sa lalaking iyon.
Ayaw sumunod sa kanya ng ating mga ninuno, kundi siya'y kanilang itinakuwil, at sa kanilang mga puso'y bumalik sila sa Ehipto,
Pagkatapos na si Jacob ay makapagbilin sa kanyang mga anak, itinikom niya ang kanyang mga paa sa higaan, siya'y nalagutan ng hininga at naging kasama ng kanyang bayan.
Sapagkat kung tayo'y sumasampalatayang si Jesus ay namatay at muling binuhay ay gayundin naman, sa pamamagitan ni Jesus, ang mga natutulog ay dadalhin ng Diyos na kasama niya.
At lahat ng mga tulos ng tabernakulo, at ng bulwagan sa palibot ay tanso.
Sa pananampalataya si Rahab, na nagbibili ng aliw, ay hindi napahamak na kasama ng mga sumuway, sapagkat payapa niyang tinanggap ang mga espiya.
Inanyayahan din si Jesus at ang kanyang mga alagad sa kasalan.
Nang makatawid na sila, narating nila ang lupain ng Genesaret at dumaong doon.
Sapagkat sila'y nagsasalita ng mga kayabangang walang kabuluhan, at nang-aakit sila sa pagnanasa ng laman sa pamamagitan ng kahalayan sa mga nakatakas mula sa mga namumuhay sa kamalian.
At ipantutubos sa kanya ng pari ang tupang handog para sa budhing maysala sa harapan ng Panginoon, para sa kasalanang kanyang nagawa; at ipatatawad sa kanya ang kasalanan na kanyang nagawa.
Ang sumasampalataya sa Anak ay may buhay na walang hanggan; ngunit ang hindi sumusunod sa Anak ay hindi makakakita ng buhay, kundi ang poot ng Diyos ay nananatili sa kanya.
ang dalawampu't apat na matatanda ay nagpapatirapa sa harapan ng nakaupo sa trono, at sumasamba doon sa nabubuhay magpakailanpaman; at inihahagis nila ang kanilang mga korona sa harapan ng trono, na nagsasabi,
Ang nagbalita ng mga bagay na ito sa mga apostol ay sina Maria Magdalena, Juana, Maria na ina ni Santiago, at iba pang mga babaing kasama nila.
Isa sa mga Fariseo ay humiling kay Jesus na kumaing kasalo niya, at pagpasok niya sa bahay ng Fariseo siya'y naupo sa hapag.
At ipapatong ng mga Levita ang kanilang mga kamay sa mga ulo ng mga batang toro at ihandog mo ang isa na handog pangkasalanan, at ang isa'y handog na sinusunog sa Panginoon , upang itubos sa mga Levita.
Kanilang tinanong siya, “Guro, kailan mangyayari ang mga bagay na ito? At ano ang magiging tanda kapag malapit nang mangyari ang mga bagay na ito?”
At hindi ba dapat na ang babaing ito na anak ni Abraham, na ginapos ni Satanas sa loob ng labingwalong taon ay kalagan sa pagkagapos na ito sa araw ng Sabbath?”
Gumawa sila nang mga araw na iyon ng isang guya, at naghandog ng alay sa diyus-diyosan at nagsaya sa mga gawa ng kanilang mga kamay.
Palibhasa'y nagtiis siya sa pagkatukso, siya'y makasasaklolo sa mga tinutukso.
Ipagbili ninyo ang inyong mga ari-arian at kayo'y magbigay ng limos. Gumawa kayo para sa inyong mga sarili ng mga supot na hindi naluluma, ng isang kayamanan sa langit na hindi nauubos, na doo'y hindi lumalapit ang magnanakaw, o naninira man ang bukbok.
Sapagkat marami ang mga lumalakad na siyang madalas kong sabihin sa inyo, at ngayo'y sinasabi ko sa inyo na may pagluha, na sila ang mga kaaway ng krus ni Cristo.
Kaya't naglagay sila ng mga tagapangasiwa upang pahirapan sila sa kanilang mga sapilitang paggawa. Kanilang ipinagtayo si Faraon ng mga lunsod imbakan, ang Pitom at Rameses.
sila'y kumuha ng mga palapa ng puno ng palma, at lumabas upang sumalubong sa kanya, na sumisigaw, “Hosana! Mapalad siya na dumarating sa pangalan ng Panginoon, ang Hari ng Israel.”
Habang si Jesus ay naglalakad mula roon, nakita niya ang isang tao na tinatawag na Mateo na nakaupo sa tanggapan ng buwis. Sinabi niya sa kanya, “Sumunod ka sa akin.” At siya ay tumayo at sumunod sa kanya.
Ito'y isang tanda sa akin at sa mga anak ni Israel magpakailanman na sa loob ng anim na araw ay ginawa ng Panginoon ang langit at lupa, at sa ikapitong araw siya ay nagpahinga at naginhawahan.’”
Sinabi ni Jose, “Ibigay ninyo ang inyong mga hayop; at bibigyan ko kayo kapalit ng inyong mga hayop, kung naubos na ang salapi.”
Ngunit hindi umimik si Jesus. At sinabi ng pinakapunong pari sa kanya, “Pinanunumpa kita sa harapan ng Diyos na buháy, sabihin mo sa amin kung ikaw nga ang Cristo, ang Anak ng Diyos.”
Sapagkat ang lahat na nasa sanlibutan, ang masamang pagnanasa ng laman, ang pagnanasa ng mga mata, at ang pagmamataas sa buhay, ay hindi mula sa Ama kundi sa sanlibutan.
Sumunod si Simon Pedro kay Jesus, at gayundin ang isa pang alagad. Sapagkat ang alagad na iyon ay kilala ng pinakapunong pari, siya ay pumasok na kasama ni Jesus sa patyo ng pinakapunong pari.
Natagpuan siya ng anghel ng Panginoon sa tabi ng isang bukal sa ilang, sa bukal na nasa daang patungo sa Shur.
Iyong babatuhin siya ng mga bato upang siya'y mamatay, sapagkat kanyang pinagsikapang ilayo ka sa Panginoon mong Diyos, na naglabas sa iyo sa lupain ng Ehipto, sa bahay ng pagkaalipin.
At sinabi ni Moises kay Aaron, “Anong ginawa ng bayang ito sa iyo, na dinalhan mo sila ng isang malaking kasalanan?”
Nang matapos pagbilinan ni Jesus ang kanyang labindalawang alagad, umalis siya roon upang magturo at mangaral sa mga bayan nila.
At sinabi sa kanya ni Jesus, “Ang mga asong-gubat ay may mga lungga at ang mga ibon sa himpapawid ay may mga pugad, subalit ang Anak ng Tao ay walang mapaghiligan man lamang ng kanyang ulo.”
Samantalang nagsasalita pa siya, may mga taong dumating na galing sa bahay ng pinuno ng sinagoga, na nagsasabi, “Namatay na ang anak mong babae. Bakit mo pa inaabala ang Guro?”
Pagkatapos, tayong nabubuhay na natitira ay aagawing kasama nila sa mga ulap, upang salubungin ang Panginoon sa papawirin; at sa gayon ay makakapiling natin ang Panginoon magpakailanman.
Ang Fariseo ay nakatayo at nanalangin sa kanyang sarili ng ganito, ‘Diyos, pinasasalamatan kita na hindi ako gaya ng ibang mga tao, na mga mangingikil, mga di makatarungan, mga mangangalunya, o gaya man ng maniningil ng buwis na ito.
at sinuman sa inyo na nagnanais na maging una ay kailangang maging alipin ninyo,
Lumabas din sa marami ang mga demonyo na nagsisisigaw, “Ikaw ang Anak ng Diyos!” Subalit kanyang sinaway sila, at hindi sila pinahintulutang magsalita, sapagkat alam nilang siya ang Cristo.
At nagsalita ang Panginoon kay Moises, na sinasabi,
Ngunit kinagabihan ay binuksan ng isang anghel ng Panginoon ang mga pintuan ng bilangguan, sila'y inilabas, at sinabi,
ito ay susuriin ng pari, at kung makitang ang buhok ay pumuti sa bahaging makintab, at tila mas malalim kaysa balat, ito ay ketong. Ito ay lumitaw sa paso, at ipahahayag ng pari na siya ay marumi; ito ay sakit na ketong.
Nang madaling-araw, habang madilim pa, pagbangon ni Jesus ay lumabas siya at nagtungo sa isang ilang na lugar, at doon ay nanalangin.
Kaya't sinabi ng Panginoon kay Moises, “Isama mo ang lahat ng pinuno sa bayan at bitayin mo sila sa harap ng araw sa harap ng Panginoon , upang ang matinding galit ng Panginoon ay mapawi sa Israel.
Hahampasin ko sila ng salot, at tatanggalan ko sila ng mana at gagawin kitang isang bansang mas malaki at mas matibay kaysa kanila.”
Kapag sila'y pumapasok sa toldang tipanan ay maghuhugas sila ng tubig, upang sila'y huwag mamatay, o kapag sila'y lumalapit sa dambana upang maglingkod, upang magsunog ng handog sa Panginoon na pinaraan sa apoy.
Kay Timoteo na aking minamahal na anak: Biyaya, kahabagan, kapayapaan nawang mula sa Diyos Ama at kay Cristo Jesus na ating Panginoon.
Gayunma'y sa kabila ng bagay na ito ay hindi kayo sumampalataya sa Panginoon ninyong Diyos,
Nagsalita si Isaac kay Abraham na kanyang ama, “Ama ko.” At kanyang sinabi, “Narito ako, anak.” Sinabi niya, “Narito ang apoy at ang kahoy, ngunit nasaan ang korderong handog na susunugin?”
Maghahandog si Aaron sa ibabaw niyon ng mababangong insenso, tuwing umaga kapag kanyang inaayos ang mga ilaw, ay ihahandog niya iyon,
“Iutos mo sa mga anak ni Israel na kanilang bigyan ang mga Levita mula sa mana na kanilang pag-aari, ng mga lunsod na matitirahan. Ang mga pastulan sa palibot ng mga lunsod na iyon ay ibibigay rin ninyo sa mga Levita.
na nagsasabi, ‘Huwag kang matakot, Pablo. Kailangan mong humarap kay Cesar. At tunay na ipinagkaloob ng Diyos ang kaligtasan sa lahat ng kasama mo sa paglalayag.’
Kayo'y malilinis na sa pamamagitan ng salita na aking sinabi sa inyo.
Sa halip, kapag inaanyayahan ka, pumunta ka at umupo sa pinakamababang lugar upang kung dumating ang nag-anyaya sa iyo, sasabihin niya sa iyo, ‘Kaibigan, pumunta ka sa mas mataas.’ Kung gayo'y magkakaroon ka ng karangalan sa harap ng lahat ng mga kasalo mong nakaupo sa hapag.
Nagsalita ang Panginoon kay Moises, na sinasabi,
at sinabi sa kanila, “Bakit kayo natutulog? Bumangon kayo at manalangin, upang hindi kayo pumasok sa tukso.”
Ang mga unang bunga ng iyong trigo, alak, langis, at ang unang balahibo ng iyong mga tupa ay ibibigay mo sa kanya.
Ngayon, makinig ka sa akin. Bibigyan kita ng payo, at sumaiyo nawa ang Diyos! Ikaw ang magiging kinatawan ng bayan sa harap ng Diyos, at dalhin mo ang kanilang mga usapin sa Diyos.
Maging dalawang araw o isang buwan, o mas mahabang panahon na nakatigil ang ulap sa ibabaw ng tabernakulo na nananatili doon, ay nananatili ang mga anak ni Israel sa mga tolda at hindi naglalakbay, subalit kapag pumaitaas ay naglalakbay sila.
Kahit na noong una ako'y isang lapastangan, mang-uusig at mang-aalipusta, gayunma'y kinahabagan ako, sapagkat sa kamangmangan ay ginawa ko iyon sa kawalan ng pananampalataya,
Nang siya'y kumatok sa tarangkahan ay isang babaing katulong na ang pangalan ay Roda ang lumapit upang alamin kung sino ang kumakatok.
Sapagkat ito ang pag-ibig sa Diyos, na ating tuparin ang kanyang mga utos at ang kanyang mga utos ay hindi pabigat.
Pagkalipas ng ilang sandali ay lumapit ang mga nakatayo roon at sinabi nila kay Pedro, “Talagang ikaw nga ay isa rin sa kanila, sapagkat nahahalata sa iyong pananalita.”
Ang Panginoon ay nagsalita kay Moises, na sinasabi:
“At kapag kayo'y naghahandog sa Panginoon ng alay na mga handog pangkapayapaan, inyong ialay ito upang kayo'y tanggapin.
Sapagkat ang Panginoon ninyong Diyos ay siyang Diyos ng mga diyos, at Panginoon ng mga panginoon, siyang dakilang Diyos, siyang makapangyarihan at siyang kakilakilabot, na hindi nagtatangi ng tao ni tumatanggap ng suhol.
Huwag kayong lalakad ng ayon sa mga kaugalian ng mga bansang aking palalayasin sa harapan ninyo, sapagkat ang lahat ng kasamaang ito ay ginawa nila, at ako ay nasusuklam sa kanila.
At nakita kong lumabas sa bibig ng dragon at mula sa bibig ng halimaw at mula sa bibig ng bulaang propeta ang tatlong espiritung karumaldumal, na gaya ng mga palaka.
Ang Diyos at Ama ng Panginoong Jesus (siyang pinupuri magpakailanpaman) ang nakakaalam na ako'y hindi nagsisinungaling.
Alalahanin mo ang iyong mga lingkod, sina Abraham, Isaac, at Jacob. Huwag mong masdan ang pagmamatigas ng bayang ito, ni ang kasamaan nila, ni ang kasalanan nila.
Siya nga'y bibigyan mo, at ang iyong puso'y huwag magdamdam kapag binibigyan mo siya; sapagkat dahil sa bagay na ito'y pagpapalain ka ng Panginoon mong Diyos sa lahat ng iyong gawa, at sa lahat ng hipuin ng iyong kamay.
Pagkaraan ng halos tatlong buwan, ibinalita kay Juda na sinasabi, “Ang iyong manugang na si Tamar ay nagpaupa, at siya'y buntis sa pagpapaupa.” Sinabi ni Juda, “Ilabas siya upang sunugin.”
Sapagkat sa pagkabuhay nilang muli mula sa mga patay, hindi na sila mag-aasawa, o pag-aasawahin pa; kundi tulad sila ng mga anghel sa langit.
Sumama sa amin ang ilang alagad mula sa Cesarea at dinala kami sa bahay ni Mnason, na taga-Cyprus, isa sa mga naunang alagad, na sa kanya kami manunuluyan.
At sinabi ni Lea, “Maligaya na ako! Tatawagin akong maligaya ng mga babae.” At tinawag niya ang kanyang pangalan na Aser.
Sapagkat kung ang bagay na lumilipas ay may kaluwalhatian, ang nananatili ay may higit pang kaluwalhatian.
Huwag kang yuyukod sa kanilang mga diyos, o maglilingkod man sa mga iyon, o gagawa man ng ayon sa kanilang mga gawa, kundi iyong wawasakin at iyong dudurugin ang kanilang mga haligi.
Nalalaman ninyo na pagkatapos, nang nais niyang magmana ng pagpapala, siya'y itinakuwil sapagkat wala na siyang natagpuang pagkakataon upang magsisi, bagama't pinagsikapan niya iyon na may pagluha.
Sapagkat hindi nakilala ng mga naninirahan sa Jerusalem at ng mga pinuno nila si Jesus ni ang mga tinig ng mga propeta na binabasa tuwing Sabbath, tinupad nila ang mga salitang ito sa pamamagitan ng paghatol sa kanya.
Una niyang natagpuan ang kanyang kapatid na si Simon, at sa kanya'y sinabi, “Natagpuan na namin ang Mesiyas”—na kung isasalin ay Cristo.
“Kukunin mo rin ang taba ng lalaking tupa, at ang matabang buntot, at ang tabang nakabalot sa mga bituka, ang mga taba ng atay, ang dalawang bato, ang taba na nasa ibabaw ng mga iyon, at ang kanang hita (sapagkat iyon ay isang lalaking tupa na itinatalaga),
“Panginoon, pinatay nila ang iyong mga propeta, giniba nila ang iyong mga dambana; at ako'y naiwang nag-iisa, at tinutugis nila ang aking buhay.”
Hindi ako pumarito upang tawagin ang mga matuwid, kundi ang mga makasalanan tungo sa pagsisisi.”
Ngunit kung hindi kayo naniniwala sa kanyang mga sinulat ay paano kayong maniniwala sa aking mga salita?”
Ako'y sumulat ng ilang bagay sa iglesya, ngunit hindi kami tinatanggap ni Diotrefes na nagnanais maging pangunahin sa kanila.
Pinakinggan ng Panginoon ang tinig ng Israel at ibinigay sa kanila ang Cananeo. Kanilang lubos na nilipol sila at ang kanilang mga bayan. Kaya't ang ipinangalan sa dakong iyon ay Horma.
At aking isinulat ang bagay na ito, upang pagdating ko ay huwag akong magkaroon ng kalungkutan mula doon sa mga nararapat magpagalak sa akin, sapagkat nakakatiyak ako sa inyong lahat na ang aking kagalakan ay magiging kagalakan ninyong lahat.
Sila'y umahon mula sa Ehipto, at dumating sa lupain ng Canaan, kay Jacob na kanilang ama.
At dinala sa kanya ng mga anak ni Aaron ang dugo, inilubog niya ang kanyang daliri sa dugo at ipinahid iyon sa ibabaw ng mga sungay ng dambana at ang nalabing dugo ay ibinuhos sa paanan ng dambana.
“Kung ang sinuman ay humiram ng anuman sa kanyang kapwa, at nasaktan ito, o namatay, na hindi kaharap ang may-ari, ang humiram ay magsasauli ng buo.
Natagpuan niya roon ang isang Judio na ang pangalan ay Aquila, isang lalaking tubong Ponto, na kararating pa lamang mula sa Italia, kasama si Priscila na kanyang asawa, sapagkat ipinag-utos ni Claudio na ang lahat ng Judio ay umalis sa Roma. Pumunta si Pablo sa kanila;
Ang mga taong ito'y pawang mga batong natatago sa inyong mga pagsasalu-salong may pag-ibig kapag sila'y nakikipagsalo sa inyo nang walang takot, na ang pinapangalagaan lamang ay ang kanilang sarili. Sila'y mga ulap na walang tubig, na tinatangay ng mga hangin; mga punungkahoy na walang bunga sa pagtatapos ng taglagas, na dalawang ulit na namatay, na binunot hanggang ugat;
At ang usok ng hirap nila ay papailanglang magpakailanpaman; at sila'y walang kapahingahan araw at gabi, silang mga sumasamba sa halimaw at sa larawan nito, at sinumang tumatanggap ng tanda ng kanyang pangalan.
Sapagkat ang sinumang nagnanais na iligtas ang kanyang buhay ay mawawalan nito, subalit sinumang mawalan ng kanyang buhay dahil sa akin ay maililigtas niya ito.
At pinalapit ni Moises ang mga anak ni Aaron, at sila'y dinamitan ng mga kasuotan, binigkisan ng mga pamigkis, at itinali sa kanilang ulo ang mga turbante, gaya ng iniutos ng Panginoon kay Moises.
Sinabi ng Panginoong Diyos, “Tingnan ninyo, ang tao'y naging parang isa sa atin, na nakakakilala ng mabuti at ng masama; at ngayon, baka iunat ang kanyang kamay at pumitas din ng bunga ng punungkahoy ng buhay, at kumain, at mabuhay magpakailanman.”
Pupunta ka sa pari na nangangasiwa nang araw na iyon at sasabihin mo sa kanya, ‘Aking ipinahahayag sa araw na ito sa Panginoon mong Diyos, na ako'y dumating na sa lupaing ipinangako ng Panginoon sa aming mga magulang na ibibigay sa amin.’
Noong nakaraang mga panahon ay hinayaan niya ang lahat ng mga bansa na lumakad sa kanilang mga sariling daan.
Nabuhay si Peleg ng tatlumpung taon, at naging anak si Reu.
At dumating si Sihon upang kami ay harapin, siya at ang kanyang buong bayan, upang makipagdigmaan sa Jahaz.
Sa alinmang bahay kayo pumasok, sabihin muna ninyo, ‘Kapayapaan nawa sa bahay na ito.’
Ako'y nagpapasalamat sa aking Diyos tuwing kayo'y aking naaalala,
Subalit ang kanilang mga mata ay hindi pinahihintulutan na makilala siya.
Kaya't huwag ninyong itakuwil ang inyong pagtitiwala na may dakilang gantimpala.
Ang lupain ay magbubunga, at kakain kayo hanggang sa mabusog at maninirahan kayong tiwasay doon.
Nang dumating sila sa mga alagad, nakita nilang napakaraming tao sa kanilang paligid at ang mga eskriba na nakikipagtalo sa kanila.
Ang balabal na aking iniwan sa Troas kay Carpo ay iyong dalhin pagparito mo, at ang mga aklat, lalung-lalo na ang mga pergamino.
At ng kanilang apatnapung patungang pilak; dalawang patungan sa ilalim ng isang haligi, at dalawang patungan sa ilalim ng ibang haligi.
ngunit sa mga araw na hipan ng ikapitong anghel ang kanyang trumpeta, magaganap ang hiwaga ng Diyos, ayon sa kanyang ipinahayag sa kanyang mga lingkod na propeta.”
Punuin nga ninyo ang takalan ng inyong mga magulang.
Ngunit pinatigas ng Panginoon ang puso ng Faraon at hindi niya dininig sila gaya ng sinabi ng Panginoon kay Moises.
at ang mga ito'y tatayo sa ibabaw ng bundok ng Ebal upang sumumpa: Ruben, Gad, Aser, Zebulon, Dan, at Neftali.
Kung ang sinuman ay nakikinig sa aking mga salita, at hindi tumutupad ng mga iyon ay hindi ko siya hinahatulan, sapagkat hindi ako naparito upang humatol sa sanlibutan, kundi upang iligtas ang sanlibutan.
Subalit sila'y hindi umimik. At siya'y hinawakan ni Jesus, pinagaling, at pinahayo.
Subalit alam niya ang kanilang mga iniisip at sinabi niya sa lalaki na tuyo ang kamay, “Halika at tumayo ka sa gitna.” At siya'y tumindig at tumayo.
Lumapit kayo sa Diyos, at siya'y lalapit sa inyo. Maglinis kayo ng inyong mga kamay, mga makasalanan, at pabanalin ninyo ang inyong mga puso, kayong mga may dalawang pag-iisip.
At inaakala mo ba ito, O tao, na humahatol sa mga gumagawa ng gayong mga bagay, at gayundin ang ginagawa mo, na ikaw ay makakatakas sa hatol ng Diyos?
at ang mga bituin sa langit ay nahulog sa lupa, gaya ng puno ng igos na nalalaglag ang kanyang mga bungang bubot kapag inuuga ng malakas na hangin.
Pagkatapos, ito ay susunugin ng mga anak ni Aaron sa dambana, sa ibabaw ng handog na sinusunog na nasa ibabaw ng kahoy na nakapatong sa apoy, isang handog na pinaraan sa apoy, na mabangong samyo sa Panginoon .
Sapagkat alin ba ang mas madali, ang sabihing, ‘Pinatatawad na ang iyong mga kasalanan?’ o sabihing, ‘Tumindig ka at lumakad?’
Sa pamamagitan nito, itinuturo ng Espiritu Santo na hindi pa naihahayag ang daan patungo sa santuwaryo, habang nakatayo pa ang unang tabernakulo.
Kaya't sabihin mo sa mga anak ni Israel, ‘Ako ang Panginoon at aking ilalabas kayo sa ilalim ng mga pasanin ng mga Ehipcio, at aking hahanguin kayo sa pagkaalipin sa kanila, at aking tutubusin kayo na may nakaunat na kamay at may mga dakilang kahatulan.
Huwag kayong babaling sa mga diyus-diyosan, ni huwag kayong gagawa para sa inyong sarili ng mga diyos na inanyuan; ako ang Panginoon ninyong Diyos.
At binigyan ni Jacob si Esau ng tinapay at nilaga na lentehas. Siya'y kumain, uminom, tumayo, at umalis. Ganyan hinamak ni Esau ang kanyang pagkapanganay.
Hindi ito ibubuhos sa laman ng mga karaniwang tao, ni huwag kayong gagawa ng gaya niyan sa pagkakagawa, ito ay banal at ito'y magiging banal sa inyo.
Nang kanyang makita sila ay sinabi niya sa kanila, “Humayo kayo at kayo'y magpakita sa mga pari.” Habang sila'y umaalis, sila ay nagiging malinis.
“Gagawa ka ng isang pinggan na lantay na ginto, at doo'y iuukit mo na ayon sa ukit ng isang pantatak, ‘Banal sa Panginoon .’
At isinuot sa kanya ang tunika, binigkisan ng pamigkis, inilagay sa kanya ang balabal, ipinatong ang efod, at ibinigkis sa kanya ang pamigkis na efod na mahusay ang pagkakahabi at itinali ito sa kanya.
Nabuhay si Eber ng tatlumpu't apat na taon, at naging anak si Peleg.
At kailan ka namin nakitang maysakit, o nasa bilangguan, at dinalaw ka namin?’
Dadalhin niya ito sa pari at ang pari ay kukuha ng isang dakot mula roon bilang handog na pinakaalaala at ito'y susunugin sa dambana, sa ibabaw ng handog sa Panginoon na pinaraan sa apoy; ito ay handog pangkasalanan.
Ang iyong gagawing mga pasanan ay kahoy na akasya, at babalutin mo ito ng ginto.
At nais namin na ang bawat isa sa inyo ay magpakita ng gayunding sigasig upang inyong malaman ang ganap na katiyakan ng pag-asa hanggang sa katapusan;
Siya'y tumatakas sapagkat siya'y upahan, at walang malasakit sa mga tupa.
Ito ang handog na sinusunog sa bawat Sabbath, bukod pa sa palagiang handog na sinusunog at ang inuming handog niyon.
upang igawad ang hatol sa lahat at upang sumbatan ang bawat kaluluwa sa lahat ng kanilang masamang gawa na kanilang ginawang may kalikuan, at sa lahat ng mga bagay na malupit na sinalita sa kanya ng mga hindi maka-Diyos na makasalanan.”
Siya'y magpapahiram sa iyo, at ikaw ay hindi magpapahiram sa kanya. Siya'y magiging ulo at ikaw ay magiging buntot.
Walang nagtatagpi ng matibay na tela sa damit na luma. Kapag gayon, babatakin ng itinagpi, ang bago mula sa luma at lalong lalaki ang punit.
na sa kanya'y ipinangalan ang bawat sambahayan sa langit at sa lupa,
“‘Sumpain ang sumisira ng puri ng kanyang ama o ng kanyang ina.’ At ang buong bayan ay magsasabi, ‘Amen.’
Kung gayon, ang lahat ng mga lalaki sa kanyang bayan ay babatuhin siya ng mga bato upang siya'y mamatay; gayon mo aalisin ang kasamaan sa gitna mo. Ito'y maririnig ng buong Israel, at sila'y matatakot.
Idalangin ninyo kami, sapagkat kami'y naniniwalang kami ay may mabuting budhi, na nagnanais na mabuhay na marangal sa lahat ng mga bagay.
na sinasabi sa kanila, “Pumunta kayo sa kasunod na nayon, at kaagad ninyong matatagpuan ang isang babaing asno na nakatali na may kasamang isang batang asno. Kalagan ninyo sila at dalhin ninyo sa akin.
at inyong sinabi, ‘Ipinakita sa amin ng Panginoon nating Diyos ang kanyang kaluwalhatian at kadakilaan. Aming narinig ang kanyang tinig mula sa gitna ng apoy; aming nakita sa araw na ito na ang Diyos ay nakikipag-usap sa tao, at ang tao ay nabubuhay pa.
“Nagligtas siya ng iba; hindi niya mailigtas ang kanyang sarili. Siya ang Hari ng Israel; bumaba siya ngayon sa krus, at maniniwala tayo sa kanya.
Nang nagtaas ako ng aking tinig at ako'y nagsisigaw, kanyang naiwan ang suot niya sa aking tabi at tumakas na papalabas.”
Sila'y dumating kina Moises at Aaron at sa buong sambayanan ng mga anak ni Israel, sa ilang ng Paran, sa Kadesh; at kanilang dinalhan sila ng balita at ang buong sambayanan, at kanilang ipinakita sa kanila ang bunga ng lupain.
Sila ba'y mga Hebreo? Ako man. Sila ba'y mga Israelita? Ako man. Sila ba'y mga binhi ni Abraham? Ako man.
“Magsikap kayong pumasok sa makipot na pintuan, sapagkat sinasabi ko sa inyo na marami ang magsisikap na pumasok at hindi makakapasok.
At kung may magtanong sa inyo, ‘Bakit ninyo kinakalagan iyan? Ganito ang inyong sasabihin, ‘Kailangan siya ng Panginoon.’”
Ano ngayon? Ang hinahanap ng Israel ay hindi niya nakamtan, ngunit ito'y nakamtan ng hinirang at ang iba'y pinapagmatigas,
Sinabi ko, ‘Anong gagawin ko, Panginoon?’ Sinabi sa akin ng Panginoon, ‘Tumindig ka at pumunta ka sa Damasco; at doo'y sasabihin sa iyo ang lahat ng mga bagay na itinalagang gawin mo.’
At sinabi niya, “Mga kapatid ko, nakikiusap ako na huwag kayong gumawa ng ganyang kasamaan.
Ngunit sumagot sa ikalawang pagkakataon ang tinig mula sa langit, ‘Ang nilinis ng Diyos ay huwag mong ituring na marumi.’
“Huwag mong tatamnan ang iyong ubasan ng dalawang magkaibang binhi, baka ang lahat ng bunga ay masira, ang binhi na iyong inihasik at ang bunga ng ubasan.
At ako'y nanalangin sa Panginoon , at sinabi, ‘O Panginoong Diyos , huwag mong pupuksain ang iyong bayan at ang iyong mana, na iyong tinubos ng iyong kadakilaan, na iyong inilabas sa Ehipto sa pamamagitan ng makapangyarihang kamay.
Igawa nila ako ng isang santuwaryo upang ako'y makapanirahan sa gitna nila.
Sinabi ng Panginoon kay Aaron, “Pumaroon ka sa ilang upang salubungin si Moises.” Siya'y pumaroon at kanyang nasalubong si Moises sa bundok ng Diyos, at kanyang hinagkan ito.
Subalit ang bukid, kapag naalis sa pagdiriwang, ay magiging banal sa Panginoon , bilang bukid na itinalaga. Ito ay magiging pag-aari ng pari.
Bukod dito, lahat ng mga taga-ibang lupain ay dumating upang bumili ng trigo kay Jose sapagkat matindi ang taggutom sa buong daigdig.
Kapag itinataas ni Moises ang kanyang kamay ay nananalo ang Israel; at kapag kanyang ibinababa ang kanyang kamay ay nananalo ang Amalek.
na ang mga Hentil ay mga kapwa tagapagmana, at mga bahagi ng iisang katawan, at mga kabahagi sa pangako kay Cristo Jesus sa pamamagitan ng ebanghelyo.
Nang dumating ang panahon ng kanyang panganganak, kambal ang nasa kanyang bahay-bata.
At walang nilalang na nakukubli sa harapan niya, kundi ang lahat ng mga bagay ay hubad at hayag sa mga mata niya na ating pagsusulitan.
Ang biyaya ng ating Panginoong Jesu-Cristo ay sumainyo.
Ibinuhos naman ng ikalawa ang kanyang mangkok sa dagat at ito'y naging parang dugo ng isang taong patay; at bawat may buhay na nasa dagat ay namatay.
Pagkatapos nito, siya'y nagtungo sa bawat lunsod at mga nayon na ipinangangaral at ipinahahayag ang magandang balita ng kaharian ng Diyos. Kasama niya ang labindalawa,
Kung ang sinuman ay hindi manatili sa akin, siya'y itatapong katulad ng sanga at matutuyo, at sila ay titipunin at ihahagis sa apoy at masusunog.
Sapagkat maging ang Anak ng Tao ay hindi naparito upang paglingkuran, kundi upang maglingkod at ibigay ang kanyang buhay na pantubos sa marami.”
Kaya't sinabi niya, “Kung gayo'y sa ano kayo binautismuhan?” Sinabi nila, “Sa bautismo ni Juan.”
Si Jesus ay nagpatuloy sa kanyang lakad sa mga bayan at mga nayon na nagtuturo habang naglalakbay patungo sa Jerusalem.
na kahawig ng anumang hayop na nasa lupa, at anumang ibong may pakpak na lumilipad sa himpapawid,
Kinuha nila ang kanilang mga kawan, mga bakahan, mga asno, at anumang nasa bayan, at nasa parang.
At sumagot siya sa kanila, “Ano ba ang iniutos sa inyo ni Moises?”
Sumunod kayo at pasakop sa mga namumuno sa inyo, sapagkat sila'y matamang nagbabantay alang-alang sa inyong mga kaluluwa bilang mga mananagot. Hayaang gampanan nila ito na may kagalakan at hindi nang may hapis, sapagkat kung ganito'y hindi ito magiging kapaki-pakinabang sa inyo.
At itinapon ang malaking dragon, ang matandang ahas, ang tinatawag na Diyablo at Satanas, ang mandaraya sa buong sanlibutan; siya'y itinapon sa lupa at ang kanyang mga anghel ay itinapong kasama niya.
At nagpakita ang Panginoon kay Isaac at sinabi, “Huwag kang bumaba sa Ehipto; manatili ka sa lupaing aking sasabihin sa iyo.
Pagkatapos na magkaroon sina Pablo at Bernabe ng hindi maliit na pakikipagtalo at pakikipagsalungatan sa kanila, sina Pablo at Bernabe, at ang ilan sa iba pa ay inatasang pumunta sa Jerusalem, upang talakayin ang suliraning ito sa mga apostol at sa matatanda.
inyong palalayasin ang lahat ng naninirahan sa lupain sa harap ninyo, at inyong sisirain ang lahat ng kanilang mga batong hinugisan, at inyong sisirain ang lahat ng kanilang mga larawang hinulma, at inyong sisirain ang lahat ng kanilang matataas na dako.
Mula sa langit ay ipinarinig niya sa iyo ang kanyang tinig, upang kanyang turuan ka. Sa ibabaw ng lupa ay kanyang ipinakita sa iyo ang kanyang dakilang apoy, at iyong narinig ang kanyang mga salita sa gitna ng apoy.
Sinabi sa kanya ni Jesus, “Ako nga iyon na kumakausap sa iyo!”
“Ang lipi lamang ni Levi ang hindi mo bibilangin, ni hindi mo kukunin ang bilang nila sa mga anak ni Israel;
Kung ang sinuman ay patungo sa pagkabihag, sa pagkabihag siya patutungo. Kung ang sinuman ay pumapatay sa pamamagitan ng tabak, sa pamamagitan ng tabak siya dapat papatayin. Ito ay panawagan para sa pagtitiis at pananampalataya ng mga banal.
At si Isaac ay naghasik sa lupaing iyon, at umani siya ng taong yaon ng makasandaang ibayo. Pinagpala siya ng Panginoon ,
Kaya't si Israel, dala ang lahat niyang pag-aari ay naglakbay at dumating sa Beer-seba, at doon ay nag-alay ng mga handog sa Diyos ng kanyang amang si Isaac.
at doon kayo kakain sa harapan ng Panginoon ninyong Diyos, at kayo'y magagalak sa lahat ng inyong gagawin, kayo at ang inyong mga sambahayan kung saan kayo pinagpala ng Panginoon mong Diyos.
“Bilangin mo ang mga anak ni Levi, ayon sa mga sambahayan ng kanilang mga ninuno, at mga angkan; bawat lalaki mula isang buwang gulang pataas ay bibilangin mo.”
Gayon ang mangyayari sa katapusan ng sanlibutan. Lalabas ang mga anghel at kanilang ihihiwalay ang masasama sa matutuwid,
At samantalang tinatapos ni Juan ang kanyang gawain ay sinabi niya, ‘Sino ba ako sa inyong akala? Hindi ako siya. Ngunit may dumarating na kasunod ko. Hindi ako karapat-dapat na magkalag ng sandalyas ng kanyang mga paa.’
Dumaan ang mga mangangalakal na mga Midianita; at kanilang iniahon si Jose sa balon, at siya'y ipinagbili sa mga Ismaelita sa halagang dalawampung pirasong pilak. At dinala nila si Jose sa Ehipto.
Ako'y hihirang para sa kanila ng isang propeta na gaya mo mula sa kanilang mga kapatid at aking ilalagay ang aking mga salita sa bibig niya at kanyang sasabihin sa kanila ang lahat ng aking iuutos sa kanya.
Kung tinatawag nga siya ni David na Panginoon, paanong siya'y naging kanyang anak?”
Dinala nila si Jesus sa pinakapunong pari at nagtipon ang lahat ng mga punong pari, matatanda at mga eskriba.
At sa ilawan mismo ay may apat na kopang anyong bulaklak ng almendro, kasama ang mga usbong niyon, at ng mga bulaklak niyon,
At sinabi nila sa isa't isa, “Halikayo! Tayo'y gumawa ng mga tisa at ating lutuing mabuti.” At ang kanilang bato ay tisa at alkitran ang kanilang semento.
Tinanong siya ni Nathanael, “Paano mo ako nakilala?” Si Jesus ay sumagot, “Bago ka tinawag ni Felipe, nang ikaw ay nasa ilalim ng puno ng igos ay nakita kita.”
Pagpasok nila sa bahay ay nakita nila ang sanggol na kasama ng kanyang inang si Maria. Nagpatirapa sila at sumamba sa kanya. Nang buksan nila ang kanilang mga kayamanan ay inihandog nila sa kanya ang mga kaloob na ginto, kamanyang at mira.
Sa gayo'y lumago at lubos na nanaig ang salita ng Panginoon.
Nang siya'y naghihirap sa panganganak, sinabi sa kanya ng hilot, “Huwag kang matakot, sapagkat magkakaroon ka ng isa pang anak na lalaki.”
Ngunit nang mabalitaan ni Jacob na may trigo sa Ehipto, sinugo niyang una ang ating mga ninuno.
Nang ibalita kay Tamar na “Ang iyong biyenang lalaki ay umaahon sa Timna upang pagupitan ang kanyang mga tupa,”
Sinabi niya rito, “Wala nang sinumang makakakain pa ng bunga mula sa iyo.” Ito'y narinig ng kanyang mga alagad.
Nang sumasakay na siya sa bangka, ang lalaking inalihan ng mga demonyo ay nakiusap na siya'y isama niya.
Sa aking unang pagsasanggalang ay walang sinumang kumampi sa akin, bagkus pinabayaan ako ng lahat. Huwag nawang singilin sa kanila ito.
Pumasok si Jesus sa templo, at itinaboy niya ang lahat ng nagtitinda at namimili sa templo, at ibinaligtad niya ang mga mesa ng mga mamamalit ng salapi, at ang mga upuan ng mga nagtitinda ng mga kalapati.
At ibinalik niya ang puno ng mga katiwala ng kopa sa kanyang pagiging katiwala ng kopa, at ibinigay niya ang kopa sa kamay ng Faraon.
Sumagot ang kanyang mga magulang, “Alam naming ito'y aming anak, at siya'y ipinanganak na bulag.
Ginawa ito ni Jesus, ang una sa kanyang mga tanda, sa Cana ng Galilea, at ipinahayag ang kanyang kaluwalhatian; at sumampalataya sa kanya ang kanyang mga alagad.
Ang handog na butil ng mga iyon, na piling harina, na hinaluan ng langis, ay tatlong ikasampung bahagi para sa toro, dalawang ikasampung bahagi para sa lalaking tupa,
Sa pananampalataya, nang ipanganak si Moises ay itinago siya ng tatlong buwan ng kanyang mga magulang, sapagkat kanilang nakitang maganda ang bata, at hindi sila natakot sa utos ng hari.
at nakalasap ng kabutihan ng salita ng Diyos, at ng mga kapangyarihan ng panahong darating,
“Ang mga magulang ay hindi papatayin dahil sa mga anak, ni ang mga anak ay papatayin dahil sa mga magulang; bawat tao'y papatayin dahil sa kanyang sariling kasalanan.
Dapat sana'y inilagak mo ang aking salapi sa mga mangangalakal ng salapi, at nang sa aking pagdating ay matanggap ko kung ano ang akin pati na ang pakinabang.
Gayon nga ang nagtitipon ng kayamanan para sa kanyang sarili, subalit hindi mayaman sa Diyos.”
Mapalad ang aliping iyon, na maratnan ng kanyang panginoon na gayon ang ginagawa.
Dadalhin niya ito sa mga anak ni Aaron na mga pari at siya'y kukuha mula roon ng isang dakot na piling harina at langis, at lahat ng kamanyang nito. Ito ay susunugin ng pari sa ibabaw ng dambana, isang handog na pinakaalaala, isang handog na pinaraan sa apoy, na mabangong samyo sa Panginoon .
samantalang inililibing ng mga Ehipcio ang lahat ng kanilang panganay na nilipol ng Panginoon sa gitna nila, pati ang kanilang mga diyos ay hinatulan ng Panginoon .
Ang lahat na nakapaghandog ng handog na pilak at tanso ay nagdala ng handog sa Panginoon at lahat ng taong may kahoy na akasya na magagamit sa anumang gawain ay nagdala nito.
Narito ako, handang pumariyan sa inyo sa ikatlong pagkakataon. Ako'y hindi magiging pasanin, sapagkat hindi ko hinahanap ang sa inyo, kundi kayo, sapagkat hindi nararapat ipag-impok ng mga anak ang mga magulang, kundi ang mga magulang para sa kanilang mga anak.
Siya'y kinilos nila sa paninibugho sa ibang mga diyos, sa pamamagitan ng mga karumaldumal, kanilang ibinunsod siya sa pagkagalit.
Nang marinig niya na iyon ay si Jesus na taga-Nazaret, nagsimula siyang magsisigaw at magsabi, “Jesus, Anak ni David, mahabag ka sa akin!”
Subalit ibigin ninyo ang inyong mga kaaway at gumawa kayo ng mabuti, magpahiram kayo na hindi umaasa ng kapalit. Malaki ang magiging gantimpala ninyo, at kayo'y magiging mga anak ng Kataas-taasan, sapagkat siya'y mabait sa mga di-mapagpasalamat at sa masasama.
Nang makapagtalaga na sila ng matatanda para sa kanila sa bawat iglesya, matapos manalangin na may pag-aayuno, ay kanilang ipinagtagubilin sila sa Panginoon na kanilang sinampalatayanan.
Sinabi niya sa kanyang mga kapatid, “Ang salapi ko ay isinauli at tingnan din ninyo ang aking sako.” Sila'y nanlupaypay at bawat isa ay takot na nagsasabi sa kanyang kapatid, “Ano itong ginawa ng Diyos sa atin?”
Kaya't siya'y isinama at dinala sa punong kapitan, at sinabi, “Tinawag ako ng bilanggong si Pablo, at ipinakiusap sa aking dalhin ko sa iyo ang binatang ito na mayroong sasabihin sa iyo.”
Ngunit kung ang hindi ko nais ang siya kong ginagawa, sumasang-ayon ako na mabuti ang kautusan.
Sinabi ni Pedro, “Ananias, bakit napadaig ka kay Satanas at nagsinungaling ka sa Espiritu Santo, at itago ang bahagi ng pinagbilhan ng lupa?
at nanumpa sa nabubuhay magpakailanpaman, na siyang lumalang ng langit at ng mga bagay na naroroon, at ng lupa at ng mga bagay na naririto, at ng dagat at ng mga bagay na naririto: “Hindi na maaantala pa,
Subalit batid ni Jesus ang kanilang mga iniisip at sinabi sa kanila, “Bakit ninyo ito pinag-aalinlanganan sa inyong mga puso?
subalit huwag ninyong papatayin sa gayon ding araw ang baka, o tupa at ang kanyang anak.
Masdan ninyo, ang inyong bahay ay iniiwan sa inyong wasak.
Lahat ng kayamanang inalis ng Diyos sa aming ama ay para sa amin at para sa aming mga anak. Ngayon nga, gawin mo ang lahat ng sinabi sa iyo ng Diyos.”
Sinabi ng anak ng Faraon sa kanya, “Dalhin mo ang batang ito at alagaan mo para sa akin at uupahan kita.” Kaya't kinuha ng babae ang bata at inalagaan ito.
Ipagkakanulo ng kapatid sa kamatayan ang kapatid at ng ama ang kanyang anak; at maghihimagsik ang mga anak laban sa mga magulang at sila'y ipapapatay.
At kumalat ang balitang ito sa buong lupaing iyon.
At inilapit niya ang ikalawang tupa, ang tupa ng pagtatalaga, at ipinatong ni Aaron at ng kanyang mga anak ang kanilang mga kamay sa ulo ng tupa.
Gayundin naman, mayroon kang ilan na sumusunod sa aral ng mga Nicolaita.
Subalit tumayo si Pedro at tumakbo sa libingan. Siya'y yumukod at pagtingin niya sa loob ay nakita niya ang mga telang lino na nasa isang tabi. Umuwi siya sa kanyang bahay na nagtataka sa nangyari.]
Ang iba ay nahulog sa mabuting lupa, at namunga. Ang iba ay tig-iisang daan, ang iba ay animnapu, ang iba ay tatlumpu.
At sinumang humipo ng kanyang higaan ay maglalaba ng kanyang mga damit, at maliligo siya sa tubig, at magiging marumi hanggang sa paglubog ng araw.
At naging tao ang Salita at tumahang kasama namin, at nakita namin ang kanyang kaluwalhatian, kaluwalhatiang gaya ng sa tanging Anak ng Ama, puspos ng biyaya at katotohanan.
Ito yaong tungkol sa kanya ay nasusulat, ‘Narito, ipinapadala ko ang aking sugo sa iyong unahan na maghahanda ng iyong daan sa iyong harapan.’
Ngunit sinabi ni Jesus, “Hayaan ninyo ang maliliit na bata, at huwag ninyo silang pagbawalang lumapit sa akin, sapagkat sa mga tulad nila nauukol ang kaharian ng langit.”
Ano sa palagay ninyo?” Sumagot sila at sinabi, “Karapat-dapat siya sa kamatayan.”
“Kailangan dito ang pag-iisip na may karunungan: ang pitong ulo ay pitong bundok na kinauupuan ng babae; sila rin ay pitong hari,
At sa pagtingin ni Jesus sa palibot ay sinabi niya sa kanyang mga alagad, “Napakahirap para sa mga may kayamanan na pumasok sa kaharian ng Diyos.”
Kaya't nang umahon si Pedro sa Jerusalem ay nakipagtalo sa kanya ang mga nasa panig ng pagtutuli,
Bakit mo sinabing, ‘Siya'y aking kapatid?’ na anupa't siya'y aking kinuha upang maging asawa. Kaya't ngayon, narito ang iyong asawa. Siya'y kunin mo at umalis ka.”
Kaya't kailangan na ang mga sinipi mula sa mga bagay sa kalangitan ay linisin ng mga ito, ngunit ang mga bagay sa sangkalangitan ay sa pamamagitan ng higit na mabubuting handog kaysa mga ito.
Yamang siya'y isang propeta at nalalaman niyang nangako ang Diyos sa kanya na ang isa sa kanyang mga inapo ay iluluklok niya sa kanyang trono.
Sapagkat pinagtitiisan ninyo ito kapag inaalipin kayo, o kapag nilalapa kayo, o kapag kayo'y pinagsasamantalahan, o kapag pinagyayabangan, o kapag kayo'y sinasampal sa mukha.
Itinaas ni Aaron ang kanyang mga kamay paharap sa taong-bayan at binasbasan sila. Bumaba siya pagkatapos ng paghahandog ng handog pangkasalanan, ng handog na sinusunog, at ng mga handog pangkapayapaan.
ay papasok ang pari at magsisiyasat. Kung ang salot ay kumalat na sa bahay, ito ay ketong na nakakasira sa bahay; ito'y marumi.
Pagkatapos ay nakita ko roon ang isang puting ulap, at nakaupo sa ulap ang isang katulad ng isang Anak ng Tao na sa kanyang ulo'y may isang gintong korona, at sa kanyang kamay ay may isang matalas na karit.
Pagkatapos maisalaysay ang lahat ng mga bagay sa kanila, sila'y isinugo niya sa Joppa.
Tulad sila sa mga batang nakaupo sa pamilihan at sumisigaw sa isa't isa, na sinasabi, ‘Tinutugtugan namin kayo ng plauta at hindi kayo sumayaw; tumangis kami at hindi kayo umiyak.’
Kumuha siya ng limang kalalakihan mula sa kanyang mga kapatid at kanyang iniharap sila sa Faraon.
Maging sa aking mga aliping lalaki at mga aliping babae, sa mga araw na iyon ay magbubuhos ako mula sa aking Espiritu; at sila'y magsasalita ng propesiya.
Sinumang magpakumbaba nang tulad sa batang ito ay siyang pinakadakila sa kaharian ng langit.
Nabuhay si Adan ng isandaan at tatlumpung taon, at nagkaanak ng isang lalaki na kanyang wangis, ayon sa kanyang larawan, at tinawag ang kanyang pangalan na Set.
Si Efron nga ay nakaupo sa gitna ng mga anak ni Het at sumagot si Efron na Heteo kay Abraham, sa harap ng mga anak ni Het, na naririnig ng lahat ng pumapasok sa pintuan ng bayan,
at lubhang naghirap na sa maraming manggagamot. Nagugol na niya ang lahat ng nasa kanya at hindi siya gumaling ni kaunti man, kundi lalo pang lumubha.
Ngunit kung hindi ninyo gagawin ang ganito, kayo'y magkakasala laban sa Panginoon at tiyak na tutugisin kayo ng inyong kasalanan.
“Magsalita ka sa buong kapulungan ng mga anak ni Israel, at sabihin mo sa kanila: Kayo'y magpakabanal, sapagkat akong Panginoon ninyong Diyos ay banal.
“Kayong matitigas ang ulo at hindi tuli ang puso't mga tainga, kayo'y laging sumasalungat sa Espiritu Santo. Kung ano ang ginawa ng inyong mga ninuno, ay gayundin ang ginagawa ninyo.
At dadalhin mo sa Panginoon ang pagkaing handog na mula sa mga sangkap na ito, at dadalhin ito ng pari sa dambana.
At kung palawakin ng Panginoon mong Diyos ang iyong hangganan gaya ng kanyang ipinangako sa iyong mga ninuno, at ibigay niya sa iyo ang buong lupain na kanyang ipinangakong ibibigay sa iyong mga ninuno;
Sinabi niya sa kanila, “Siya ba'y mabuti ang kalagayan?” At kanilang sinabi, “Oo; at narito ang kanyang anak na si Raquel na dumarating kasama ang mga tupa!”
Subalit sinasabi ko sa inyo, sa mga iba na nasa Tiatira, sa mga hindi nagtataglay ng aral na ito, sa mga hindi natuto ng gaya ng sinasabi ng iba ‘na mga malalalim na bagay ni Satanas,’ hindi ako naglalagay sa inyo ng ibang pabigat.
At sinabi ni Jacob sa kanyang mga kamag-anak, “Magtipon kayo ng mga bato,” at kumuha sila ng mga bato at kanilang ginawang isang bunton at sila'y nagkainan doon sa malapit sa bunton.
Noon ay nag-aayuno ang mga alagad ni Juan at ang mga Fariseo. Sila'y lumapit at sinabi sa kanya, “Bakit nag-aayuno ang mga alagad ni Juan at ang mga alagad ng mga Fariseo, ngunit hindi nag-aayuno ang iyong mga alagad?”
Nang sumapit ang gabi, ang bangka ay nasa gitna ng dagat at siya'y nag-iisa sa lupa.
Kung ang kamay mo ay nakapagpapatisod sa iyo, putulin mo ito. Mas mabuti pa sa iyo ang pumasok sa buhay na baldado, kaysa may dalawang kamay at mapunta sa impiyerno, sa apoy na hindi mapapatay, [
“At kapag kayo ay nananalangin, huwag kayong maging tulad sa mga mapagkunwari; sapagkat ibig nilang tumayo at manalangin sa mga sinagoga at sa mga panulukan ng mga lansangan upang makita sila ng mga tao. Katotohanang sinasabi ko sa inyo, tinanggap na nila ang kanilang gantimpala.
At dinala ni Moises si Aaron at ang kanyang mga anak, at hinugasan sila ng tubig.
Kaya't sinasabi niya, ‘Babalik ako sa aking bahay na pinanggalingan.’ Pagdating niya ay natagpuan niya iyong walang laman, nawalisan at naiayos na.
Kung may sinumang pumilit sa iyo na lumakad ka ng isang milya, lumakad ka ng dalawang milya na kasama niya.
Subalit kapag siya'y gumaling sa kanyang pagdurugo, bibilang siya ng pitong araw, at pagkatapos niyon ay magiging malinis siya.
at bilang isang balo hanggang walumpu't apat na taong gulang. Hindi siya umalis sa templo kundi sumamba roon na may pag-aayuno at panalangin sa gabi at araw.
At sinabi niya sa kanila, “Sa inyo ipinagkaloob ang hiwaga ng kaharian ng Diyos, ngunit sa kanilang nasa labas, ang lahat ng mga bagay ay ginagawa sa mga talinghaga;
At wala pang bumangong propeta sa Israel na gaya ni Moises, na kilala ng Panginoon nang mukhaan.
At habang nakikipag-usap sa kanya, pumasok siya at kanyang naratnan ang maraming taong nagkakatipon.
Paglakad niya sa malayu-layo, siya'y nagpatirapa sa lupa at idinalangin na kung maaari ay makalampas sa kanya ang oras.
Subalit ano ang sinasabi sa kanya ng kasagutan ng Diyos? “Nagtira ako para sa akin ng pitong libong lalaki na hindi lumuhod kay Baal.”
Sa dalawang utos na ito nakasalig ang buong kautusan at ang mga propeta.”
Sapagkat ang kanilang bato ay hindi gaya ng ating Bato, kahit ang ating mga kaaway man ang maging mga hukom.
Sinabi ng Panginoon kay Moises, “Sabihin mo kay Aaron, ‘Iunat mo ang iyong kamay na hawak ang iyong tungkod sa mga ilog, sa mga bambang, sa mga lawa, at magpaahon ka ng mga palaka sa lupain ng Ehipto!’”
Kanilang ginawa ang plata ng banal na korona na lantay na ginto, at nilagyan ito ng sulat na tulad ng ukit ng isang singsing na pantatak: “Banal sa Panginoon .”
ay kukuha ka ng isang pambutas at butasan mo ang kanyang tainga sa pintuan, at siya'y magiging iyong alipin magpakailanman. Gayundin ang iyong gagawin sa iyong aliping babae.
sa gitna ng lansangan ng lunsod. Sa magkabilang panig ng ilog ay naroon ang punungkahoy ng buhay, na namumunga ng labindalawang iba't ibang bunga, na namumunga sa bawat buwan; at ang mga dahon ng punungkahoy ay para sa pagpapagaling sa mga bansa.
“At kukunin mo ang lalaking tupa na itinalaga at ilaga mo ang laman nito sa isang dakong banal.
“Tatlong ulit sa isang taon na ang iyong mga kalalakihan ay haharap sa Panginoon mong Diyos sa lugar na kanyang pipiliin: sa Pista ng Tinapay na walang Pampaalsa, sa Pista ng mga Sanlinggo, at sa Pista ng mga Tolda. Huwag silang haharap sa Panginoon na walang dala.
Lumapit sa kanya sina Santiago at Juan na mga anak ni Zebedeo, na nagsasabi sa kanya, “Guro, ibig naming gawin mo sa amin ang anumang aming hingin sa iyo.”
(ito ang mga anak ni Raquel na ipinanganak kay Jacob: sa kabuuan ay labing-apat na katao).
Sa kanilang lahat ay nagbigay siya ng mga pampalit na bihisan; ngunit kay Benjamin ay nagbigay siya ng tatlong daang pirasong pilak, at limang pampalit na bihisan.
Akin ding itinatag ang aking tipan sa kanila na ibibigay ko sa kanila ang lupain ng Canaan, ang lupain na kung saan sila'y nakipanirahan.
Sinabi niya sa kanila, “Nasaan ang inyong pananampalataya?” At sila'y natakot at namangha, at sinabi sa isa't isa, “Sino nga kaya ito, na kanyang inuutusan maging ang hangin at tubig at sila'y sumusunod sa kanya?”
At sinabi ng anak sa kanya, ‘Ama, nagkasala ako laban sa langit at sa iyo; hindi na ako karapat-dapat na tawaging anak mo.’
Sapagkat pumurol na ang puso ng bayang ito, at mahirap nang makarinig ang kanilang mga tainga, at pumikit na ang kanilang mga mata; baka sila'y makakita sa kanilang mga mata, at makarinig sa kanilang mga tainga, at makaunawa sa kanilang puso, at magbalik-loob, at sila'y aking pagalingin.’
Nagpalayas sila ng maraming demonyo, pinahiran ng langis ang maraming maysakit at pinagaling sila.
Pagkatapos ay lumabas ang mga demonyo sa tao, at pumasok sa mga baboy at ang kawan ay dumaluhong sa bangin patungo sa lawa at nalunod.
Samantalang sinasabi pa ni Pedro ang mga salitang ito, bumaba ang Espiritu Santo sa lahat ng nakikinig ng salita.
Ang mga lahing darating, ang inyong mga anak na babangon pagkamatay ninyo, at ang dayuhan na magmumula sa malayong lupain ay magsasabi, kapag nakita nila ang mga salot ng lupaing iyon, at ang sakit na inilagay ng Panginoon ,
Nang dumating si Jose sa kanyang mga kapatid, siya'y kanilang hinubaran ng kanyang mahabang damit na kanyang suot.
Mag-ingat kayo sa mga aso, mag-ingat kayo sa masasamang manggagawa, mag-ingat kayo sa mga hindi totoong pagtutuli.
Pagkatapos nito, may ibang pitong baka na nagsiahon sa likuran nila, mga payat, at napakapangit ang anyo, at payat na kailanma'y hindi ako nakakita sa buong lupain ng Ehipto ng kagaya ng mga iyon sa kapangitan.
at naging mayaman ang lalaki at patuloy na naging mayaman hanggang sa naging napakayaman.
Siya'y yumuko, siya'y lumugmok na parang leon, at parang isang babaing leon, sinong gigising sa kanya? Pagpalain nawa ang lahat na nagpapala sa iyo, at sumpain ang lahat na sumusumpa sa iyo.”
Nang makita niya na ito'y ikinasiya ng mga Judio, kanya namang isinunod na dakpin si Pedro. Ito ay nang panahon ng pista ng Tinapay na Walang Pampaalsa.
Sinabi ni Pedro, “Panginoon, sinasabi mo ba ang talinghagang ito para sa amin, o para sa lahat?”
Sinabi niya, “Dahil dito'y sinabi ko sa inyo, walang taong makakalapit sa akin, malibang ipagkaloob sa kanya ng Ama.”
Sumagot si Jesus at sinabi sa kanya, “Mapalad ka, Simon na anak ni Jonas! Sapagkat hindi laman at dugo ang nagpahayag nito sa iyo kundi ang aking Ama na nasa langit.
Subalit ang ibang alagad ay lumapit sa bangka na hila ang lambat na punô ng isda, sapagkat sila'y hindi malayo sa lupa, kundi halos siyamnapung metro ang layo.
Kaya tanggapin ninyo siya sa Panginoon nang buong galak; at ang gayong mga tao ay parangalan ninyo,
At iniutos niya sa senturion na siya'y bantayan at bigyan ng kaunting kalayaan at huwag pagbawalan ang kanyang mga kaibigan na tulungan siya sa kanyang mga pangangailangan.
Subalit marami pa ring ibang mga bagay na ginawa si Jesus, na kung susulating isa-isa, sa palagay ko, kahit sa sanlibutan mismo ay hindi magkakasiya ang mga aklat na isusulat.
Siya'y sumusunod kay Pablo at sa amin, na sumisigaw, “Ang mga taong ito ay mga alipin ng Kataas-taasang Diyos, na nagpapahayag sa inyo ng daan ng kaligtasan.”
Kaya't habang nananatiling bukas ang pangakong makapasok sa kanyang kapahingahan, mag-ingat tayo na baka sinuman sa inyo ay hindi makaabot doon.
Mula sa nalabing langis na nasa kanyang kamay ay maglalagay ang pari ng dugo sa dulo ng kanang tainga, sa hinlalaki ng kanang kamay, at sa hinlalaki ng kanang paa ng taong lilinisin, sa ibabaw ng dugo ng handog para sa budhing maysala.
Sa gayunding paraan ay inalipusta siya ng mga tulisan na ipinako sa krus na kasama niya.
“Siya ang Bato, ang kanyang gawa ay sakdal; sapagkat lahat ng kanyang daan ay katarungan. Isang Diyos na tapat at walang kasamaan, siya ay matuwid at banal.
at sasabihin ninyo, ‘Bukod dito, ang iyong lingkod na si Jacob ay nasa hulihan namin.’” Sapagkat kanyang iniisip, “Baka mapaglubag ko ang kanyang galit sa pamamagitan ng regalo na ipinauna ko, at pagkatapos ay makikita ko ang kanyang mukha, marahil ay tatanggapin niya ako.”
Gayundin naman ang mga diakono ay dapat na maging kagalang-galang, hindi dalawang dila, hindi nalululong sa maraming alak, hindi mga sakim sa masamang pagkakakitaan,
Ako ang nagpapatotoo tungkol sa aking sarili, at ang Amang nagsugo sa akin ay nagpapatotoo tungkol sa akin.”
sapagkat sa pamamagitan niya nilalang ang lahat ng mga bagay sa langit at sa lupa, ang mga bagay na nakikita at ang mga bagay na hindi nakikita, maging mga trono o mga pagka-panginoon, maging mga pinuno o mga may kapangyarihan—lahat ng mga bagay ay nilalang sa pamamagitan niya at para sa kanya.
na hindi ako kukuha kahit isang sinulid, o isang panali ng sandalyas, o ng anumang para sa iyo, baka iyong sabihin, ‘Pinayaman ko si Abram.’
Ngayon ang paghatol sa sanlibutang ito. Ngayon ang pinuno ng sanlibutang ito ay palalayasin.
Sapagkat ang sinumang nagnanais iligtas ang kanyang buhay ay mawawalan nito at ang sinumang mawalan ng kanyang buhay dahil sa akin at sa ebanghelyo ay maililigtas iyon.
At muli siyang yumuko, at isinulat ang kanyang daliri sa lupa.
“Ngayon, sinusugo ko kayong tulad ng mga tupa sa gitna ng mga asong-gubat, kaya't maging matalino kayong gaya ng mga ahas at maamong gaya ng mga kalapati.
Samantala, si Pedro ay nakatayo sa pintuan sa labas. Kaya't ang alagad na kilala ng pinakapunong pari ay lumabas at kinausap ang babaing tanod sa pinto, at ipinasok si Pedro.
“At sa anghel ng iglesya sa Filadelfia ay isulat mo: “Ang mga bagay na ito ang sinasabi ng banal, ng totoo, na may susi ni David, na nagbubukas at hindi maisasara ng sinuman, na nagsasara at walang makakapagbukas.
At sinabi niya, “Ikaw nga ba ang aking anak na si Esau?” At sinabi ni Jacob, “Ako nga.”
Subalit may ilan sa kanila, mga lalaking taga-Cyprus at taga-Cirene, nang dumating sa Antioquia, ay nagsalita din sa mga Griyego, na ipinangangaral ang Panginoong Jesus.
at ang nabubuhay. Ako'y namatay, at tingnan mo, ako'y nabubuhay magpakailanpaman, at nasa akin ang mga susi ng kamatayan at ng Hades.
Ito ay nangangahulugang nauunawaan na ang kautusan ay hindi ginawa para sa taong matuwid, kundi para sa mga walang kinikilalang batas at mapaghimagsik, para sa masasama at mga makasalanan, para sa mga hindi banal at lapastangan, para sa mga pumapatay sa ama at sa ina, para sa mga mamamatay-tao,
Sinabi niya sa kanya sa ikatlong pagkakataon, “Simon, anak ni Juan, minamahal mo ba ako?” Nalungkot si Pedro sapagkat tatlong ulit nang sinabi sa kanya, “Minamahal mo ba ako?” At sinabi niya sa kanya, “Panginoon, nalalaman mo ang lahat ng mga bagay. Nalalaman mo na minamahal kita.” Sinabi sa kanya ni Jesus, “Pakainin mo ang aking mga tupa.
Kaya't mayroon kaming salita ng propesiya na lalong tiyak. Mabuti ang inyong ginagawa kung ito'y inyong pagtutuunan ng pansin, gaya sa isang ilawang tumatanglaw sa isang dakong madilim, hanggang sa pagbubukang-liwayway, at ang tala sa umaga ay sumilang sa inyong mga puso.
Sinabi ni Jesus, “Paupuin ninyo ang mga tao.” Madamo sa dakong iyon, kaya't umupo ang mga lalaki na may limang libo ang bilang.
sapagkat ipapakita ko sa kanya kung gaano karaming bagay ang dapat niyang tiisin alang-alang sa aking pangalan.”
Sapagkat nang ako'y dumating mula sa Padan, si Raquel ay namatay sa lupain ng Canaan sa daan, nang malapit nang makarating sa Efrata; at inilibing ko siya roon sa daan ng Efrata” (na siya ring Bethlehem).
At nagsalita ang Panginoon kay Moises, na sinasabi,
Nang mga araw na iyon ay dumating si Juan na Tagapagbautismo na nangangaral sa ilang ng Judea, na nagsasabi,
Nang matapos na siya sa pagsasalita ay sinabi niya kay Simon, “Pumunta ka sa malalim at ihulog ninyo ang inyong mga lambat upang makahuli.”
At ginawa ni Balak ang sinabi ni Balaam, at naghandog ng isang toro at isang lalaking tupa sa bawat dambana.
na naghahangad na makakain mula sa mga nahuhulog sa hapag ng mayaman. Maging ang mga aso ay lumalapit at hinihimuran ang kanyang mga sugat.
Gayundin, hindi ba't si Rahab na masamang babae ay inaring-ganap sa pamamagitan ng mga gawa, nang tanggapin niya ang mga sugo at pinalabas sila sa ibang daan?
Kaya't tuparin mo ang kanyang mga tuntunin at mga utos na aking iniuutos sa iyo sa araw na ito, upang kayo ay mapabuti, at ng inyong mga anak pagkamatay mo, at upang mapahaba mo ang iyong mga araw sa ibabaw ng lupaing ibinibigay sa iyo magpakailanman ng Panginoon mong Diyos.”
at sa pinakamagandang bunga ng matandang bundok, at sa mga pinakamabuti sa mga burol na walang hanggan,
Sinabi sa kanya ni Pilato, “Ano ang katotohanan?” At nang masabi niya ito ay lumabas siyang muli sa mga Judio at sa kanila'y sinabi, “Wala akong makitang anumang kasalanan sa kanya.
Si Jesus, na punô ng Espiritu Santo, ay bumalik mula sa Jordan at dinala ng Espiritu sa ilang,
Ngayong nilinis na ninyo ang inyong mga kaluluwa sa pamamagitan ng inyong pagsunod sa katotohanan, kaya't kayo'y may tunay na pag-ibig sa isa't isa, mag-ibigan kayo sa isa't isa nang buong alab mula sa dalisay na puso.
At sabihin ninyo kay Arquipo, “Sikapin mong gampanan ang ministeryo na tinanggap mo sa Panginoon.”
Sa ganito lamang paraan sila papayag na tumirang kasama natin, upang maging isang bayan: na patuli ang lahat ng lalaki sa atin, na gaya naman nila na mga tuli.
Sinabi ni Abram sa hari ng Sodoma, “Ako'y sumumpa sa Panginoong Diyos na Kataas-taasan, na lumikha ng langit at ng lupa,
Sila'y gumawa ng dalawang singsing na ginto at ikinabit sa dakong ibaba ng dalawang pambalikat ng efod, sa may harapan na malapit sa pagkakadugtong, sa ibabaw ng mainam na pagkayaring pamigkis ng efod.
At kinuha ko ang makasalanang bagay na inyong ginawa, ang guya, at aking sinunog sa apoy, at aking niyapakan at dinurog na mabuti, hanggang sa naging durog na parang alabok; at aking inihagis ang alabok niyon sa batis na umaagos mula sa bundok.
Siya'y dumaing sa Panginoon at itinuro sa kanya ng Panginoon ang isang punungkahoy; inihagis niya ito sa tubig, at ang tubig ay tumamis. Doon, gumawa ang Panginoon para sa kanila ng isang batas at tuntunin. Doon ay sinubok niya sila,
Ngunit tinawag siya ng anghel ng Panginoon mula sa langit, at sinabi, “Abraham, Abraham.” At kanyang sinabi, “Narito ako.”
Sa unang araw ay magkakaroon kayo ng isang banal na pagtitipon at sa ikapitong araw ay magkakaroon din kayo ng isang banal na pagtitipon. Walang anumang gawa na gagawin sa mga araw na iyon; ang nararapat lamang kainin ng bawat tao ang maaaring ihanda ninyo.
Sa pamamagitan niya ay nanampalataya kayo sa Diyos, na bumuhay sa kanya mula sa mga patay at sa kanya'y nagbigay ng kaluwalhatian, kaya't ang inyong pananampalataya at pag-asa ay nakatuon sa Diyos.
At ito'y nahayag sa lahat ng mga naninirahan sa Jerusalem; kaya't tinawag ang bukid na iyon sa kanilang wika na Akeldama, na ang kahulugan ay, ‘Ang Bukid ng Dugo’.)
Muli siyang nagsugo ng ibang mga alipin na mas marami pa sa nauna; at gayundin ang ginawa nila sa kanila.
At siya'y binigyan niya ng kapangyarihang humatol sapagkat siya'y Anak ng Tao.
“Kung mag-away ang dalawang lalaki at makasakit ng isang babaing nagdadalang-tao, na anupa't makunan, at gayunma'y walang pinsalang sumunod, pagbabayarin ang nakasakit, ayon sa iaatang sa kanya ng asawa ng babae; at siya'y magbabayad ng ayon sa ipasiya ng mga hukom.
Ang mga ito'y tatanggap ng kaparusahang walang hanggang pagkapuksa at palalayasin sa harapan ng Panginoon at mula sa kaluwalhatian ng kanyang kalakasan,
At ito ang haba ng buhay ni Ismael, isandaan at tatlumpu't pitong taon; at nalagot ang hininga at namatay; at siya'y naging kasama ng kanyang bayan.
Mula sa tatlumpung taong gulang pataas hanggang sa limampung taong gulang ay iyong bibilangin sila, lahat na maaaring pumasok sa paglilingkod, upang gawin ang gawain sa toldang tipanan.
Dumating nang oras ding iyon ang ilang Fariseo na nagsabi sa kanya, “Lumabas ka na at umalis dito, sapagkat ibig kang patayin ni Herodes.”
“Gayunman, walang sinumang magtatalaga ng panganay sa mga hayop. Ito ay panganay para sa Panginoon , maging baka o tupa ay para sa Panginoon .
Hindi ba dapat kang nahabag sa iyong kapwa alipin, kung paanong nahabag ako sa iyo?’
Ang aking lingkod na si Moises ay hindi gayon; ipinagkatiwala ko sa kanya ang aking buong sambahayan.
At kanilang sinabi, “Ang Panginoon ba'y nagsasalita sa pamamagitan lamang ni Moises? Hindi ba nagsalita rin naman siya sa pamamagitan natin?” At narinig ito ng Panginoon .
Ito ang mga anak ni Ham ayon sa kanilang angkan, wika, mga lupain, at kanilang mga bansa.
Nang ikatlong araw ay kanilang ipinagtatapon ang mga kasangkapan ng barko.
at nilait nila ang Diyos ng langit dahil sa kanilang mga hirap at sa kanilang mga sugat; at hindi sila nagsisi sa kanilang mga gawa.
Kaya't sila'y lumapit sa katiwala ng bahay ni Jose at kinausap nila sa pintuan ng bahay.
Nang sila'y makapagtalaga ng isang araw para sa kanya, nagtungo sila sa kanyang tinutuluyan at napakarami nila. Ipinaliwanag niya sa kanila ang pangyayari buhat umaga hanggang gabi na nagpapatotoo tungkol sa kaharian ng Diyos, at sinikap na sila'y mahikayat tungkol kay Jesus, mula sa kautusan ni Moises at mula sa mga propeta.
at ng ilan na si Elias ay nagpakita, at ng mga iba, na isa sa mga propeta noong unang panahon ay bumangon.
Sinabi ng biyenan ni Moises sa kanya, “Ang iyong ginagawa ay hindi mabuti.
Nagdala rin si Abel ng mga panganay ng kanyang kawan, ang taba ng mga iyon. At pinahalagahan ng Panginoon si Abel at ang kanyang handog,
Sinabi niya sa kanya, “Opo, Panginoon. Sumasampalataya ako na ikaw ang Cristo, ang Anak ng Diyos, ang siyang darating sa sanlibutan.
Si Moises ay nagalit sa mga pinuno ng hukbo, sa mga pinuno ng libu-libo at sa mga pinuno ng daan-daan na nanggaling sa pakikipaglaban.
Sinabi ni Balaam kay Balak, “Ipagtayo mo ako rito ng pitong dambana, at ipaghanda mo ako rito ng pitong toro at pitong lalaking tupa.”
At kung iyon ay alinmang hayop na marumi na hindi maihahandog na alay sa Panginoon , dadalhin niya ang hayop sa harapan ng pari;
Ako'y hindi ninyo pinili, ngunit kayo'y pinili ko, at itinalaga ko kayo upang kayo'y humayo at magbunga, at ang mga bunga ninyo'y mananatili, upang ang anumang inyong hingin sa Ama sa aking pangalan ay ibigay niya sa inyo.
ayon sa iniutos ng Panginoon kay Moises. Gayon niya binilang sila sa ilang ng Sinai.
Ipapatong niya ang kanyang kamay sa ulo ng handog pangkasalanan, at papatayin ang handog pangkasalanan sa lugar ng handog na sinusunog.
At sinabi niya, “Sinong nagsabi sa iyong ikaw ay hubad? Kumain ka ba ng bunga ng punungkahoy, na iniutos ko sa iyong huwag mong kainin?”
“Mga kapatid, mga anak ng lahi ni Abraham, at ang mga sa inyo'y may takot sa Diyos, sa atin ipinadala ang salita ng kaligtasang ito.
“Gumawa ka ng dalawang trumpetang pilak; gagawin mo mula sa pinitpit na pilak at iyong gagamitin sa pagtawag sa kapulungan, at kapag kakalasin na ang mga tolda.
at ang kanilang salita ay kakalat na gaya ng ganggrena. Kasama sa mga ito si Himeneo at si Fileto,
Siya'y inalipusta ng mga nagdaraan at pailing-iling,
Kaya't ang kanyang pananampalataya ay ibinilang na katuwiran sa kanya.
Ngunit kung ang bagay na ito ay totoo na ang mga tanda ng pagkabirhen ay hindi natagpuan sa dalaga,
Si Erasto ay nanatili sa Corinto, ngunit si Trofimo ay iniwan kong maysakit sa Mileto.
Subalit ang ilang mananampalataya na kasapi sa sekta ng mga Fariseo ay tumayo at nagsabi, “Kailangang sila'y tuliin at utusang sundin ang kautusan ni Moises.”
At kanilang ibibigay siya sa mga Hentil upang kutyain, hagupitin at ipako sa krus; at siya'y muling mabubuhay sa ikatlong araw.”
Sa araw na iyon ay marami ang magsasabi sa akin, ‘Panginoon, Panginoon, hindi ba nagpropesiya kami sa iyong pangalan, at nagpalayas ng mga demonyo sa iyong pangalan, at sa iyong pangalan ay gumawa kami ng maraming gawang makapangyarihan?’
Si Zelofehad na anak ni Hefer ay hindi nagkaanak ng lalaki, kundi mga babae. Ang mga pangalan ng mga anak na babae ni Zelofehad ay Mahla, Noa, Hogla, Milca, at Tirsa.
At ginawa nilang mapait ang buhay para kina Isaac at Rebecca.
“Ito ang tipan na aking gagawin sa kanila, pagkatapos ng mga araw na iyon, sabi ng Panginoon; ilalagay ko ang aking mga kautusan sa kanilang mga puso, at isusulat ko ang mga iyon sa kanilang pag-iisip,”
“Huwag kang magpapahiram na may patubo sa iyong kapatid, patubo ng salapi, patubo ng kakainin, patubo ng anumang bagay na ipinapahiram na may patubo.
Inalis ng Faraon sa kamay niya ang kanyang singsing at inilagay sa kamay ni Jose, at siya'y sinuotan ng pinong lino at inilagay ang isang kuwintas na ginto sa kanyang leeg.
Ang mga anak ni Israel ay naglakbay, at nagkampo sa Obot.
Katotohanang sinasabi ko sa inyo, ang alipin ay hindi higit na dakila kaysa kanyang panginoon, o ang sinugo ay higit na dakila kaysa nagsugo sa kanya.
Huwag kayong padala sa sari-sari at kakaibang mga turo, sapagkat mabuti na ang puso ay patibayin ng biyaya; hindi sa pamamagitan ng mga pagkain, na di pinakinabangan ng mga tumupad ng mga iyon.
At sinabi ni Jetro, “Purihin ang Panginoon na nagligtas sa inyo, sa kamay ng mga Ehipcio, at sa kamay ng Faraon.
Hindi na ako karapat-dapat na tawaging anak mo. Ituring mo ako na isa sa iyong mga upahang lingkod.”’
at dahil ang hanapbuhay niya'y tulad din ng kanila, tumuloy siya sa kanila, at sila'y magkakasamang nagtrabaho—parehong paggawa ng tolda ang hanapbuhay nila.
Kaya't mula ngayon ay hindi namin kinikilala ang sinuman ayon sa pananaw ng laman, bagaman kinikilala namin si Cristo ayon sa pananaw ng laman, ngunit ngayon ay hindi na gayon ang aming pagkakilala.
Kaya't sila'y humayo at ipinangaral na ang mga tao ay dapat magsisi.
kundi sa dakong pipiliin ng Panginoon sa isa sa iyong mga lipi, doon mo ihahandog ang iyong mga handog na sinusunog, at doon mo gagawin ang lahat na aking iniuutos sa iyo.
Maging si Simon mismo ay naniwala at pagkatapos mabautismuhan, nanatili siyang kasama ni Felipe. Namangha siya nang makakita ng mga tanda at ng mga dakilang himalang ginawa.
Siya nga ay nagsasalita tungkol kay Judas na anak ni Simon Iscariote, sapagkat siya na isa sa labindalawa ang magkakanulo sa kanya.
Nagsimula ang ilan na duraan siya, tinakpan ang kanyang mukha, at siya'y pinagsusuntok, na sinasabi nila sa kanya, “Hulaan mo!” Kinuha siya ng mga bantay at siya'y pinagsasampal.
“Huwag humatol upang hindi kayo mahatulan.
At ang propetang iyon o ang mapanaginiping iyon ay papatayin, sapagkat siya'y nagsalita ng paghihimagsik laban sa Panginoon ninyong Diyos na naglabas sa inyo sa lupain ng Ehipto, at tumubos sa iyo sa bahay ng pagkaalipin, upang iligaw ka sa daan na iniutos ng Panginoon mong Diyos upang iyong lakaran. Ganito mo aalisin ang kasamaan sa gitna mo.
May isang katawan at isang Espiritu, kung paanong tinawag kayo sa isang pag-asa ng pagkatawag sa inyo,
Lahat ng kalikuan ay kasalanan, at may kasalanang hindi tungo sa kamatayan.
At ang mga anak ni Benjamin: sina Bela, Beker, Asbel, Gera, Naaman, Ehi, Ros, Muppim, Hupim, at si Ard
Nilamon ng mga uhay na lanta ang pitong uhay na mabibintog. Isinalaysay ko ito sa mga salamangkero, subalit walang makapagpaliwanag ng kahulugan niyon sa akin.”
Pagkatapos ay lumabas ang kanyang kapatid, at ang kanyang kamay ay nakakapit sa sakong ni Esau; kaya't ang ipinangalan sa kanya ay Jacob. Si Isaac ay may animnapung taon na nang sila'y ipanganak ni Rebecca.
Sinabi ng Panginoon kay Cain, “Bakit ka nagalit at bakit nagngitngit ang iyong mukha?
Bagaman ako ang pinakahamak sa lahat ng mga banal, ang biyayang ito ay ibinigay sa akin upang ipangaral sa mga Hentil ang mga di-masukat na mga kayamanan ni Cristo;
Ito ang mga anak ni Efraim ayon sa kanilang mga angkan: kay Shutela, ang angkan ng mga Shutelaita; kay Beker, ang angkan ng mga Bekerita; kay Tahan, ang angkan ng mga Tahanita.
Ang tinuturuan ng salita ay dapat magbahagi sa nagtuturo ng lahat ng mga bagay na mabuti.
Kinaumagahan, nagsanggunian kaagad ang mga punong pari kasama ang matatanda at mga eskriba at ang buong Sanhedrin. Ginapos nila si Jesus, inilabas at ibinigay kay Pilato.
Ngunit kung ito'y sa pamamagitan ng biyaya, ito'y hindi na batay sa mga gawa; kung hindi, ang biyaya ay hindi biyaya.
Subalit ang nagpapatibay sa amin na kasama ninyo kay Cristo, at nagpahid sa amin ay ang Diyos,
Siya'y sinamba nila at bumalik sila sa Jerusalem na may malaking kagalakan.
Sinabi sa kanya ni Juan, “Guro, nakita namin ang isang tao na nagpapalayas ng mga demonyo sa pangalan mo at pinagbawalan namin siya, sapagkat hindi siya sumusunod sa atin.”
Ang watawat ng kampo ni Ruben ay sumulong ayon sa kanilang mga pangkat at nangunguna sa kanyang hukbo si Elisur na anak ni Sedeur.
Muli, sa ikalawang pagkakataon, umalis siya at nanalangin, na nagsasabi, “Ama ko, kung hindi maaaring lumampas ito, malibang inumin ko ito, ang iyong kalooban ang siyang mangyari.”
At sinabi sa kanila ni Jesus, “Sumunod kayo sa akin at gagawin ko kayong mga mamamalakaya ng mga tao.”
Kaagad nilang iniwan ang kanilang mga lambat at sumunod sa kanya.
Siya'y dinala muna kay Anas, sapagkat siya'y biyenan ni Caifas, na pinakapunong pari nang panahong iyon.
“Sabihin mo sa mga anak ni Israel na sila'y magdala sa akin ng isang handog; tanggapin ninyo ang handog para sa akin mula sa bawat tao na ang puso ay nagkukusang-loob.
At huwag ninyong katakutan ang mga pumapatay ng katawan, ngunit hindi nakakapatay ng kaluluwa, kundi katakutan ninyo siyang makakapuksa ng kaluluwa at ng katawan sa impiyerno.
Mapalad at banal ang may bahagi sa unang pagkabuhay na muli! Sa mga ito'y walang kapangyarihan ang ikalawang kamatayan, kundi sila'y magiging mga pari ng Diyos at ni Cristo, at maghaharing kasama niya sa loob ng isang libong taon.
Nawa'y palakasin kayo sa buong kapangyarihan, ayon sa kalakasan ng kanyang kaluwalhatian, para sa lahat ng katatagan at pagtitiyaga na may galak;
Dito ay nakatayo ang isang gintong dambana ng insenso at ang kaban ng tipan na ang paligid ay nababalutan ng ginto, na siyang kinaroroonan ng sisidlang-ginto na kinalalagyan ng manna at ng tungkod ni Aaron na namulaklak, at ang mga tapyas na bato ng tipan.
Pagkatapos ay sinabi niya sa kanila, “Ito ang aking mga salitang sinabi ko sa inyo, noong ako'y kasama pa ninyo, na kailangang matupad ang lahat ng mga bagay na nakasulat tungkol sa akin sa kautusan ni Moises, sa mga propeta, at sa mga awit.”
Kanilang dinala rin ang kanilang mga hayop, ang mga pag-aari na kanilang natamo sa lupain ng Canaan, at dumating sa Ehipto si Jacob at ang lahat ng inapong kasama niya.
Bakit inaakala ninyong hindi kapani-paniwalang binubuhay ng Diyos ang mga patay?
“Aking isinusugo ang isang anghel sa unahan mo, upang ingatan ka sa daan, at upang dalhin ka sa dakong aking inihanda.
At sila'y inyong kukunin bilang pamana sa inyong mga anak pagkamatay ninyo upang maging pag-aari; maiaatang ninyo sa kanila ang paglilingkod magpakailanman. Ngunit sa inyong mga kamag-anak na mga anak ni Israel ay huwag kayong mamumuno na may kabagsikan.
Ang mga punong pari naman at ang buong Sanhedrin ay naghahanap ng patotoo laban kay Jesus upang siya'y ipapatay; ngunit wala silang matagpuan,
“Kung nagkataong ang isang pugad ng ibon ay matagpuan mo sa daan, o sa anumang punungkahoy, o sa lupa, na may mga inakay, o mga itlog at lumilimlim ang inahin sa mga inakay, o sa mga itlog, huwag mong kukunin ang inahin na kasama ng mga inakay.
Kanyang sinabi sa kanila, “Ito ang iniutos ng Panginoon , ‘Bukas ay taimtim na pagpapahinga, banal na Sabbath sa Panginoon . Lutuin ninyo ang inyong lulutuin, at pakuluan ninyo ang inyong pakukuluan; at lahat ng lalabis ay itago ninyo, inyong ititira hanggang sa kinabukasan.’”
Sapagkat dumating si Juan na Tagapagbautismo na hindi kumakain ng tinapay at hindi umiinom ng alak at inyong sinasabi, ‘Siya'y may demonyo.’
“Narito ang lingkod ko na aking hinirang, ang minamahal ko na kinalulugdan ng aking kaluluwa. Ilalagay ko sa kanya ang aking Espiritu, at ipahahayag niya ang katarungan sa mga Hentil.
Sapagkat ang lahat ng nagkasala nang walang kautusan ay mapapahamak din nang walang kautusan; at ang lahat ng nagkasala sa ilalim ng kautusan ay sa kautusan hahatulan.
Sinabi ni Jose sa kanyang mga kapatid at sa sambahayan ng kanyang ama, “Ako'y aahon at sasabihin ko sa Faraon, ‘Ang aking mga kapatid, at ang sambahayan ng aking ama na nasa lupain ng Canaan ay pumarito sa akin;
Kaya't siya'y umalis at kinuha ang mga ito at dinala sa kanyang ina. Gumawa ang kanyang ina ng masarap na pagkaing gusto ng kanyang ama.
“At sa anghel ng iglesya sa Tiatira ay isulat mo: Ang mga bagay na ito ay sinasabi ng Anak ng Diyos, na may mga matang gaya ng ningas ng apoy, at ang kanyang mga paa ay gaya ng tansong pinakintab.
At magiging kanya at sa binhing susunod sa kanya ang tipan ng walang hanggang pagkapari, sapagkat siya'y mapanibughuin para sa kanyang Diyos at ginawa ang pagtubos para sa mga anak ni Israel.”
Sa harapan ng Diyos at ni Cristo Jesus, na siyang hahatol sa mga buháy at sa mga patay, at sa pamamagitan ng kanyang pagpapakita at sa kanyang kaharian, ay inaatasan kita:
At ngayon ay sinabi ko sa inyo bago pa mangyari, upang kung ito'y mangyari, kayo ay maniwala.
At kinuha ni Moises ang salaping pantubos sa mga hindi natubos ng mga Levita,
Nang ang araw ng kamatayan ni Israel ay malapit na, tinawag niya ang kanyang anak na si Jose, at sinabi sa kanya, “Kung ako ngayon ay makakatagpo ng biyaya sa iyong paningin, hinihiling ko na ilagay mo ang iyong kamay sa ilalim ng aking hita, at mangako kang maging tapat at tunay sa akin. Huwag mo akong ililibing sa Ehipto.
Sa simula ng inyong mga buwan ay maghahandog kayo ng handog na sinusunog sa Panginoon ; dalawang batang toro at isang lalaking tupa, pitong korderong lalaki na isang taong gulang at walang kapintasan;
Si Josue na anak ni Nun, na iyong lingkod, ay siyang papasok doon. Palakasin mo ang kanyang loob, sapagkat siya ang mangunguna upang ito ay manahin ng Israel.
At kukunin ng pari ang lutong balikat ng tupa, at isang munting tinapay na walang pampaalsa sa bakol, at isang manipis na tinapay na walang pampaalsa, at ilalagay sa mga kamay ng Nazirita, pagkatapos makapag-ahit ng buhok ng kanyang pagkatalaga.
Sila'y naglakbay mula sa Bethel. Nang sila ay may kalayuan pa mula sa Efrata, ay manganganak na si Raquel at siya'y naghihirap sa panganganak.
“Mapapalad ang mga mahabagin, sapagkat sila'y kahahabagan.
“Mapapalad ang mga nagugutom at nauuhaw sa katuwiran, sapagkat sila ay bubusugin.
At sinabi niya, “Pati ba naman kayo'y wala pa ring pang-unawa?
Nang kanilang mailagay na ang mga bilanggo sa gitna nila, sila ay kanilang tinanong, “Sa anong kapangyarihan, o sa anong pangalan ninyo ginawa ito?”
Sinabi niya sa kanila, “Ganyan ang nasusulat, na kailangang magdusa ang Cristo at muling mabuhay mula sa mga patay sa ikatlong araw;
“‘Huwag kang gagawa para sa iyo ng larawang inanyuan na kawangis ng anumang nasa itaas sa langit, o ng nasa ibaba sa lupa, o ng nasa tubig sa ilalim ng lupa.
Sa pananampalataya, binasbasan ni Isaac sina Jacob at Esau tungkol sa mga bagay na mangyayari.
Ngunit nang nauna kami sa barko, naglakbay kami patungo sa Asos, na mula roon ay binabalak naming isama si Pablo, sapagkat gayon ang kanyang ipinasiya, na binalak niyang sa lupa maglakbay.
Doon ay kanilang ipinako siya at kasama niya ang dalawa pa, isa sa bawat tagiliran, at sa gitna nila ay si Jesus.
Ngunit kung sawayin siya ng kanyang asawa sa araw na marinig iyon, mawawalan ng kabuluhan ang kanyang panata at ang binitiwang pangako ng kanyang mga labi na doo'y itinali niya ang kanyang sarili, at patatawarin siya ng Panginoon .
Tumahimik ang buong kapulungan at kanilang pinakinggan sina Bernabe at Pablo na isinasalaysay ang mga tanda at mga kababalaghang ginawa ng Diyos sa pamamagitan nila sa gitna ng mga Hentil.
Sila'y lumapit sa kanya, at nagsabi, “Gagawa kami rito ng mga kulungan para sa aming mga hayop, at ng mga bayan para sa aming mga bata.
‘Ako ang Diyos ng iyong mga ninuno, ang Diyos ni Abraham, at ni Isaac, at ni Jacob.’ Nanginig si Moises at hindi nangahas tumingin.
Sinuman sa binhi ni Aaron na may ketong o may tulo ay hindi kakain ng mga banal na bagay hanggang siya'y maging malinis. At ang humipo ng alinmang bagay na marumi dahil sa patay, o lalaking nilabasan ng binhi nito,
Ngunit ang mga babae, mga bata, mga hayop, ang lahat na nasa mga kawal, ang lahat ng nasamsam doon ay kukunin mo bilang samsam; at kakainin mo ang nasamsam mula sa iyong mga kaaway na ibinigay sa iyo ng Panginoon mong Diyos.
Magtiis kayo alang-alang sa disiplina. Kayo ay pinapakitunguhan ng Diyos bilang mga anak, sapagkat ano ngang anak ang hindi dinidisiplina ng ama?
Kanilang nilagyan ito ng apat na hanay na mga bato: isang hanay sa sardio, topacio, at karbungko na siyang unang hanay.
Bilang pantubos sa dalawandaan at pitumpu't tatlong panganay ng mga anak ni Israel na higit sa bilang ng mga lalaking Levita,
Bukod dito'y hindi mo kami dinala sa isang lupain na dinadaluyan ng gatas at pulot, ni binigyan mo kami ng manang bukid at mga ubasan. Dudukitin mo ba pati ang mga mata ng mga taong ito? Hindi kami pupunta!”
Nang masabi na ni Jesus ang mga bagay na ito, tumingala siya sa langit at sinabi, “Ama, dumating na ang oras, luwalhatiin mo ang iyong Anak, upang luwalhatiin ka ng Anak,
Kinuha ni Rebecca ang pinakamagandang damit ng kanyang panganay na anak na si Esau na nasa kanya sa bahay at isinuot kay Jacob na kanyang bunsong anak.
Napuno ng kaguluhan ang lunsod at sama-sama nilang nilusob ang tanghalan, at sinunggaban sina Gayo at Aristarco, mga taga-Macedonia, na kasama ni Pablo sa paglalakbay.
Si Maria ay kumuha ng isang libra ng mamahaling pabango mula sa purong nardo at pinahiran ang mga paa ni Jesus, at pinunasan ang mga paa nito ng kanyang mga buhok. At ang bahay ay napuno ng amoy ng pabango.
Ang lahat ng ibinibigay sa akin ng Ama ay lalapit sa akin; at ang lumalapit sa akin kailanman ay hindi ko itataboy.
at ang baboy, bagaman may hati ang paa at biyak subalit hindi ngumunguya, ito ay marumi para sa inyo.
Kinaumagahan, ang kanyang diwa ay nabagabag at siya'y nagpasugo at ipinatawag ang lahat ng salamangkero at mga pantas sa Ehipto. Isinalaysay ng Faraon sa kanila ang kanyang panaginip, subalit walang makapagpaliwanag sa Faraon.
Sinabi ni Marta kay Jesus, “Panginoon, kung narito ka sana hindi sana namatay ang kapatid ko.
At tiyakin mong gawin ang mga iyon ayon sa anyong huwaran ng mga iyon na ipinakita sa iyo sa bundok.
Dinala niya ang handog na sinusunog at inihandog ayon sa tuntunin.
Kaya't lumabas si Pilato at sinabi sa kanila, “Anong paratang ang dala ninyo laban sa taong ito?”
Isinalaysay ni Moises sa kanyang biyenan ang lahat ng ginawa ng Panginoon sa Faraon at sa mga Ehipcio alang-alang sa Israel, ang lahat ng hirap na kanilang naranasan sa daan, at kung paanong iniligtas sila ng Panginoon .
Subalit silang lahat ay sama-samang sumigaw, “Alisin ang taong ito, palayain si Barabas para sa amin.”
Umupo siya sa tapat ng kabang-yaman at minasdan ang mga taong naghuhulog ng salapi sa kabang-yaman. Maraming mayayaman ang naghuhulog ng malalaking halaga.
At ibinuhos ng ikaapat ang kanyang mangkok sa araw at pinahintulutan itong pasuin ng apoy ang mga tao.
At ang nakaupo doon ay may anyong katulad ng batong jaspe at sardio, at naliligid ang trono ng isang bahaghari na tulad ng esmeralda.
Nang makarating kami sa Jerusalem, masaya kaming tinanggap ng mga kapatid.
Sinabi ni Pilato sa kanila, “Kunin ninyo siya, at siya'y inyong hatulan ayon sa inyong batas.” Sinabi ng mga Judio sa kanya, “Hindi kami pinahihintulutan na ipapatay ang sinumang tao.”
At makakarinig kayo ng mga digmaan at ng mga bali-balita ng mga digmaan. Mag-ingat kayo na huwag kayong mangamba, sapagkat kailangang mangyari ito, subalit hindi pa ito ang wakas.
May isang senturion doon na may aliping minamahal niya na maysakit at malapit nang mamatay.
Tama; sa kawalan nila ng pananampalataya ay nabali sila, at sa iyong pananampalataya'y nakatayo ka. Huwag kang magmalaki kundi matakot ka.
Malayong gagawa ka ng ganito, na ang banal ay iyong pataying kasama ng masama, anupa't ang banal ay makatulad sa masama! Malayong mangyari iyan! Di ba gagawa ng matuwid ang Hukom ng buong mundo?”
Siya'y tumindig at pumunta sa kanyang ama. Subalit habang nasa malayo pa siya, natanaw siya ng kanyang ama at ito'y awang-awa sa kanya. Ang ama'y tumakbo, niyakap siya at hinagkan.
Nangyari ito upang matupad ang sinabi sa pamamagitan ng propeta, na nagsasabi,
Mula sa iisang bibig ay lumalabas ang pagpupuri at panlalait. Mga kapatid ko, hindi dapat maging ganito.
Sinabi niya, “Bitawan mo ako, sapagkat nagbubukang-liwayway na.” At sinabi ni Jacob, “Hindi kita bibitawan malibang ako ay mabasbasan mo.”
At siya'y lumabas at pumaroon, gaya ng kanyang nakaugalian, sa bundok ng mga Olibo at sumunod naman sa kanya ang mga alagad.
At sinabi ni Moises sa kanila, “Kung gagawin ninyo ang bagay na ito; kung kayo'y maghahandang lumaban upang pumaroon sa harap ng Panginoon sa pakikipaglaban,
Kung mayroong lugar na hindi kayo tanggapin at ayaw kayong pakinggan, sa pag-alis ninyo ay ipagpag ninyo ang alikabok na nasa inyong mga paa bilang patotoo laban sa kanila.”
Habang siya'y naglalakad, nakita niya si Levi na anak ni Alfeo na nakaupo sa tanggapan ng buwis at sinabi sa kanya, “Sumunod ka sa akin.” Tumayo siya at sumunod sa kanya.
Ang lahat na naging araw ni Set ay siyamnaraan at labindalawang taon at siya'y namatay.
hanggang sa bigyan ng Panginoon ng kapahingahan ang inyong mga kapatid, na gaya ninyo, at kanilang angkinin din ang lupain na ibinigay sa kanila ng Panginoon ninyong Diyos sa kabila ng Jordan. Pagkatapos ay babalik ang bawat lalaki sa inyo sa kanyang pag-aari na aking ibinigay sa inyo.’
“Ang mga patriyarka, dahil sa inggit kay Jose ay ipinagbili siya sa Ehipto, ngunit ang Diyos ay kasama niya.
ay iyo ngang ilalabas sa iyong mga pintuang-bayan ang lalaki o babaing iyon na gumawa ng bagay na masama at iyong babatuhin ng mga bato ang lalaki at babae, hanggang sila'y mamatay.
Ang lima sa kanila'y mga hangal at ang lima'y matatalino.
Hindi mo man lamang ipinahintulot sa akin na mahalikan ang aking mga anak na lalaki at babae? Ang ginawa mo'y isang kahangalan.
At umalis mula sa Pafos si Pablo at ang kanyang mga kasama at nakarating sa Perga sa Pamfilia. Ngunit iniwan sila ni Juan at nagbalik sa Jerusalem.
Pinalabas silang lahat ni Pedro, at pagkatapos ay lumuhod at nanalangin siya. Bumaling siya sa bangkay at kanyang sinabi, “Tabita, bumangon ka.” Iminulat niya ang kanyang mga mata, at nang makita niya si Pedro ay naupo siya.
O kung ang sinuman ay nakahipo ng alinmang bagay na marumi, o maging ito ay bangkay ng mabangis na hayop na marumi, o bangkay ng umuusad na marumi, at di niya iyon nalaman, siya'y magiging marumi at nagkakasala.
Ibinaba niya ang mga makapangyarihan sa kanilang mga trono, at itinaas ang mga may abang kalagayan.
sapagkat bihasa ka sa lahat ng mga kaugalian at mga usapin ng mga Judio, kaya ipinapakiusap ko sa iyo na matiyaga mo akong pakinggan.
Kaya't kinuha ng bawat isa ang kanyang suuban, at kanilang nilagyan ng apoy at kanilang pinatungan ng insenso at sila'y tumayo sa pintuan ng toldang tipanan na kasama nina Moises at Aaron.
Sa araw na iyon ay hihingi kayo sa aking pangalan, at hindi ko sinasabi sa inyo na ako'y hihingi sa Ama para sa inyo.
Nang ang kapistahan ay nasa kalagitnaan na ay pumunta si Jesus sa templo at nagturo.
Ang lumapastangan sa pangalan ng Panginoon ay tiyak na papatayin; at babatuhin siya ng buong kapulungan; maging dayuhan o katutubo sa lupain ay papatayin kapag nilapastangan ang Pangalan.
Pagkatapos na muling bigyan ng babala, kanilang hinayaan silang umalis na walang nakitang anumang bagay upang sila'y kanilang maparusahan dahil sa mga tao, sapagkat niluluwalhati nilang lahat ang Diyos dahil sa nangyari.
Hindi kami naglalagay ng katitisuran ng sinuman, upang walang kapintasang matagpuan sa aming ministeryo.
Mula roon, siya'y umalis at pumunta sa lupain ng Judea at sa kabila ng Jordan. At muling nagtipon ang napakaraming tao sa paligid niya at tulad ng kanyang nakaugalian, muli niyang tinuruan sila.
Subalit kung sa kalbong ulo o noo ay magkaroon ng namumula o namumuting sugat, ito ay ketong na sumibol sa kanyang kalbong ulo o sa kanyang kalbong noo.
Ngunit ito ang hindi ko gusto laban sa iyo: pinahintulutan mo ang babaing si Jezebel, na tinatawag ang kanyang sarili na propeta at kanyang tinuturuan at nililinlang ang aking mga lingkod upang makiapid at kumain ng mga bagay na inihandog sa mga diyus-diyosan.
na nag-aabang sa kanya upang hulihin siya sa kanyang sasabihin.
Hinampas nila ang kanyang ulo ng isang tungkod, dinuraan siya at lumuhod sa harapan niya.
Iniwan nila ang daang matuwid at naligaw sila, palibhasa'y sumunod sa daan ni Balaam na anak ni Beor, na umibig sa kabayaran ng kalikuan.
Samantala, si Pedro ay nakaupo sa labas ng bakuran. Lumapit sa kanya ang isang aliping babae, na nagsasabi, “Ikaw ay kasama rin ni Jesus na taga-Galilea.”
“Kung may magningas na apoy at umabot sa mga tinik, na anupa't ang mga mandala, o ang mga uhay, o ang bukid ay masunog, ang nagpaningas ng apoy ay magbabayad ng buo.
Magalak kayo sa araw na iyon at lumukso kayo sa tuwa, sapagkat malaki ang inyong gantimpala sa langit, sapagkat gayundin ang ginawa ng kanilang mga ninuno sa mga propeta.
Pumasok sina Moises at Aaron sa toldang tipanan, at sila'y lumabas at binasbasan ang bayan; at lumitaw ang kaluwalhatian ng Panginoon sa taong-bayan.
Dahil dito hinuli ako ng mga Judio sa templo at pinagsikapang ako'y patayin.
Sinabi nila sa kanya, ‘Kung gayon, bakit ipinag-utos ni Moises sa amin na magbigay ng kasulatan ng paghihiwalay at hiwalayan ang babae?’
na sinasabi, “Ang Anak ng Tao ay kailangang magdusa ng maraming bagay at itakuwil ng matatanda at ng mga punong pari at mga eskriba, at patayin, at sa ikatlong araw ay muling bubuhayin.”
Sapagkat sa isang dako ay sinabi niya ang ganito tungkol sa ikapitong araw, “At nagpahinga ang Diyos nang ikapitong araw sa lahat ng kanyang mga gawa.”
Sapagkat aking kinuha sa mga anak ni Israel, sa kanilang mga alay na mga handog pangkapayapaan, ang dibdib na iwinagayway at ang hitang inialay, at aking ibinigay sa paring si Aaron at sa kanyang mga anak, sa pamamagitan ng isang walang hanggang bahagi na nauukol sa kanila, mula sa mga anak ni Israel.
“Sa ikalabing-apat na araw ng unang buwan, sa paglubog ng araw, ay ang Paskuwa ng Panginoon .
Siya'y itinaas ng Diyos sa kanyang kanang kamay bilang Pinuno at Tagapagligtas, upang bigyan ang Israel ng pagkakataong magsisi, at ng kapatawaran ng mga kasalanan.
At sinabi nila sa kanya, “Kami'y walang natanggap na mga sulat na galing sa Judea tungkol sa iyo, ni walang pumaritong kapatid na nagbalita o nagsalita ng anumang masama tungkol sa iyo.
Nang sabihin niya ang mga bagay na ito, napahiya ang lahat ng kanyang mga kaaway at nagalak ang maraming tao dahil sa lahat ng maluwalhating bagay na kanyang ginawa.
Sa pamamagitan nito ay makikilala ng lahat ng mga tao na kayo ay aking mga alagad, kung kayo'y may pag-ibig sa isa't isa.”
Kaya't nanatili tayo sa libis na nasa tapat ng Bet-peor.
Ngunit ang Panginoon ay tumindig sa tabi ko at ako'y pinalakas niya upang sa pamamagitan ko ay ganap na maipahayag ang mensahe upang mapakinggan ito ng lahat ng mga Hentil. Kaya't ako'y iniligtas sa bibig ng leon.
Subalit kung paanong inusig noon ng ipinanganak ayon sa laman ang ipinanganak ayon sa Espiritu, gayundin naman ngayon.
“Magalak kayo, O mga bansa, kasama ng kanyang bayan; sapagkat ipaghihiganti niya ang dugo ng kanyang mga lingkod, at maghihiganti sa kanyang mga kalaban, at patatawarin ang kanyang lupain, ang kanyang bayan.”
na sinuma'y huwag magkasala o manlamang sa kanyang kapatid sa bagay na ito, sapagkat ang Panginoon ay tagapaghiganti sa lahat ng mga bagay na ito, gaya ng aming sinabi noong una at ibinabala sa inyo.
Kinaumagahan, maagang bumangon si Laban, hinagkan ang kanyang mga anak na lalaki at babae, at binasbasan sila; at umalis siya at bumalik sa kanyang tahanan.
Sumagot si Simon Pedro at sinabi, “Ikaw ang Cristo, ang Anak ng Diyos na buháy.”
“Pagbilang mo sa mga anak ni Israel, magbibigay ang bawat isa sa kanila ng pantubos ng kanyang sarili sa Panginoon , kapag iyong binibilang sila, upang huwag magkaroon ng salot sa gitna nila kapag iyong binibilang sila.
Subalit sinabi ni Jose sa kanila, “Huwag kayong matakot. Sapagkat ako ba ay nasa lugar ng Diyos?
Sapagkat sa katotohanan, nang kami ay kasama ninyo ay aming sinabi noon pa mang una na kami ay makakaranas ng kapighatian; gaya nga ng nangyari, at nalalaman ninyo.
Kaya't pakinggan mo, O Israel, at iyong gawin upang ang lahat ay maging mabuti sa iyo, at upang kayo'y lalo pang dumami, na gaya ng ipinangako sa iyo ng Panginoon , ng Diyos ng iyong mga ninuno, sa lupaing dinadaluyan ng gatas at pulot.
Sapagkat hindi kami sumusulat sa inyo ng ibang mga bagay kundi kung ano ang inyong mababasa at mauunawaan; umaasa ako na lubos ninyong mauunawaan hanggang sa wakas.
Siya'y lumabas at ibinalita sa mga naging kasama ni Jesus, samantalang sila'y nagluluksa at tumatangis.
Nang kami'y tumulak buhat doon, naglayag kami na nanganganlong sa Cyprus, sapagkat pasalungat sa amin ang hangin.
Sapagkat ito'y hindi hamak na bagay sa inyo; sapagkat ito'y inyong buhay, at sa pamamagitan ng bagay na ito ay inyong pahahabain ang inyong mga araw sa lupain na inyong itinawid sa Jordan upang angkinin.”
Tunay na walang engkanto laban sa Jacob, ni panghuhula laban sa Israel. Ngayo'y sasabihin tungkol sa Jacob at sa Israel, ‘Anong ginawa ng Diyos!’
Ang bayan ay pumunta kay Moises at nagsabi, “Kami ay nagkasala, sapagkat kami ay nagsalita laban sa Panginoon at laban sa iyo. Idalangin mo sa Panginoon , na kanyang alisin sa amin ang mga ahas. At idinalangin ni Moises ang bayan.
“‘Ako ang Panginoon mong Diyos na naglabas sa iyo sa lupain ng Ehipto, mula sa bahay ng pagkaalipin.
Anumang walang kaliskis at palikpik ay huwag ninyong kakainin; marumi ito para sa inyo.
Gagawin mo ito sa ganitong paraan: ang haba ng sasakyan ay tatlong daang siko, ang luwang ay limampung siko, at ang taas ay tatlumpung siko.
Ang patuloy na gumagawa ng kasalanan ay sa diyablo; sapagkat buhat pa nang pasimula ay nagkakasala na ang diyablo. Dahil dito, nahayag ang Anak ng Diyos upang wasakin ang mga gawa ng diyablo.
Ako ba ay hindi pinahihintulutang gumawa ng nais ko sa mga bagay na pag-aari ko? O naiinggit ka ba sapagkat ako'y mabuti?’
At nakita ko ang isa pang halimaw na umaahon sa lupa; at ito ay may dalawang sungay na katulad ng sa isang kordero at siya'y nagsasalita na parang dragon.
Ngunit sa mga ito ay wala isa mang lalaki na ibinilang ni Moises at ng paring si Aaron, na bumilang ng mga anak ni Israel sa ilang ng Sinai.
sa ikalawang hanay ay esmeralda, zafiro, at diamante;
Kaya't pinakinggan ni Moises ang kanyang biyenan at ginawa ang lahat ng kanyang sinabi.
Sumagot naman si Pedro at sinabi sa kanya, “Ipaliwanag mo sa amin ang talinghaga.”
ibubukod mo para sa Panginoon ang lahat ng nagbubukas ng bahay-bata. Lahat ng panganay na lalaki ng iyong mga hayop ay sa Panginoon .
Subalit ang mga salitang ito'y inakala nilang walang kabuluhan at hindi nila pinaniwalaan. [
Ito ay mayroong isang malaki at mataas na pader, na may labindalawang pintuan, at sa mga pintuan ay may labindalawang anghel; at sa mga pintuan ay nakasulat ang mga pangalan ng labindalawang lipi ng mga anak ni Israel.
Kanyang ipinatawag sina Moises at Aaron nang gabi at sinabi, “Maghanda kayo, umalis kayo sa gitna ng aking bayan, kayo at ang mga anak ni Israel! Umalis na kayo at sambahin ninyo ang Panginoon , gaya ng inyong sinabi.
“At sa pananalangin ay huwag kayong gumamit ng walang kabuluhang paulit-ulit, na tulad ng ginagawa ng mga Hentil, sapagkat inaakala nilang sila ay pakikinggan dahil sa marami nilang salita.
Sa mga Rubenita at sa mga Gadita ay aking ibinigay ang mula sa Gilead hanggang sa libis ng Arnon, na siyang kalahatian ng libis, bilang hangganan niyon hanggang sa ilog Jaboc, na siyang hangganan ng mga anak ni Ammon;
Ngayon, kung ako'y nakatagpo ng biyaya sa iyong paningin ay ituro mo sa akin ngayon ang iyong mga daan, upang ikaw ay aking makilala, at ako'y makatagpo ng biyaya sa iyong paningin. Alalahanin mo rin na ang bansang ito ay iyong bayan.”
Sapagkat hindi ko ikinahihiya ang ebanghelyo; sapagkat ito ang kapangyarihan ng Diyos para sa kaligtasan ng bawat sumasampalataya, una'y sa Judio at gayundin sa Griyego.
Kaya't ano ngang bunga mayroon kayo sa mga bagay na ngayo'y ikinahihiya ninyo? Sapagkat ang kahihinatnan ng mga bagay na iyon ay kamatayan.
Walang pag-aalinlangan, dakila ang hiwaga ng kabanalan: Siyang nahayag sa laman, pinatunayang matuwid sa espiritu, nakita ng mga anghel, ipinangaral sa mga bansa, sinampalatayanan sa sanlibutan, tinanggap sa itaas sa kaluwalhatian.
Dahil sa habag ay hinipo ni Jesus ang kanilang mga mata. Kaagad, nakakita silang muli at sila'y sumunod sa kanya.
Tumingala ang lalaki at nagsabi, “Nakakakita ako ng mga tao, na parang mga punungkahoy na naglalakad.”
Madalas na siya'y inihahagis nito sa apoy at sa tubig upang siya'y puksain, ngunit kung mayroon kang bagay na magagawa, maawa ka sa amin at tulungan mo kami.”
Kahabag-habag na tao ako! Sino ang magliligtas sa akin mula sa katawang ito ng kamatayan?
Subalit ang mga Levita ay hindi binilang na kasama ng mga anak ni Israel gaya ng iniutos ng Panginoon kay Moises.
Pagkatapos ng mga bagay na ito, umalis si Pablo sa Atenas, at pumunta sa Corinto.
“Bawat umuusad sa ibabaw ng lupa ay marumi; hindi ito maaaring kainin.
Ang Panginoon ay nagalit din sa akin, dahil sa inyo, na nagsasabi, ‘Ikaw man ay hindi papasok doon.
Sinabi ni Moises sa Diyos, “Sino ako upang pumaroon kay Faraon at upang ilabas sa Ehipto ang mga anak ni Israel?”
At ang lahat na naging araw ni Enoc ay tatlong daan at animnapu't limang taon.
Sinabi nila sa kanya, “Ano ang kailangan naming gawin upang aming magawa ang mga gawa ng Diyos?”
Ngunit upang huwag na itong lalo pang kumalat sa bayan, atin silang bigyan ng babala na huwag na silang magsalita pa sa kaninuman sa pangalang ito.”
Kaya't namatay si Jose sa gulang na isandaan at sampung taon; at kanilang inembalsamo siya, at siya'y inilagay sa isang kabaong sa Ehipto.
Mas madali pa para sa isang kamelyo ang dumaan sa butas ng isang karayom kaysa isang mayaman ang pumasok sa kaharian ng Diyos.”
Ito ay magiging pagkakataon upang kayo ay magpatotoo.
Sa pagsasalita tungkol sa “bagong tipan,” ginawa niyang lipas na ang una. At ang ginawang lipas na at tumatanda ay malapit nang maglaho.
Kaya't ikaw at ang iyong buong pangkat ay nagtitipon laban sa Panginoon ; sino si Aaron, na nagrereklamo kayo laban sa kanya?
Nang kanilang marinig iyon, pinuri nila ang Diyos. At sinabi nila sa kanya, “Nakikita mo, kapatid, kung ilang libo sa mga Judio ang sumampalataya; at silang lahat ay pawang masisigasig sa kautusan.
Sapagkat tayo'y mayroong isang Pinakapunong Pari na marunong makiramay sa ating mga kahinaan, isa na tinukso sa lahat ng mga paraan gaya rin naman natin, gayunma'y walang kasalanan.
Ito ay magiging kay Aaron at sa kanyang mga anak, na bahaging ukol sa kanila sa habang panahon na mula sa mga anak ni Israel, sapagkat ito ang bahagi ng mga pari na ihahandog ng mga anak ni Israel, na kinuha sa kanilang mga handog pangkapayapaan. Ito ay kanilang handog sa Panginoon .
Nagsalita ang Panginoon kay Moises, na sinasabi:
Pagkatapos ay kukuha ang pari ng kaunting dugo ng handog pangkasalanan sa pamamagitan ng kanyang daliri at ilalagay sa ibabaw ng mga sungay ng dambana ng handog na sinusunog, at ang nalabing dugo ay ibubuhos niya sa paanan ng dambana.
Ang Panginoon ay bumaba sa ibabaw ng bundok ng Sinai, sa taluktok ng bundok; at tinawag ng Panginoon si Moises sa taluktok ng bundok; at si Moises ay umakyat.
At ating isaalang-alang kung papaano gigisingin ang isa't isa sa pag-ibig at sa mabubuting gawa,
Ngunit gagawin ng mga Levita ang paglilingkod sa toldang tipanan at kanilang papasanin ang kanilang kasamaan; ito'y magiging tuntunin magpakailanman sa buong panahon ng inyong mga salinlahi, at sa gitna ng mga anak ni Israel ay hindi sila magkakaroon ng mana.
Sapagkat tingnan ninyo ang ibinunga sa inyo ng kalungkutang ito na naaayon sa Diyos, kung anong pagtatanggol sa inyong mga sarili, kung anong pagkagalit, kung anong takot, pananabik, sigasig, at kaparusahan! Sa bawat bagay ay pinatunayan ninyo ang inyong pagiging malinis sa bagay na ito.
At nang ikadalawampu't pitong araw ng ikalawang buwan ay natuyo ang lupa.
Sinabi ng iba, “Siya nga.” Ang sabi ng iba, “Hindi, subalit kamukha niya.” Sinabi niya, “Ako nga iyon.”
At si Judas na nagkanulo kay Jesus, nang nakitang hinatulan na ito, ay nagsisi at isinauli ang tatlumpung pirasong pilak sa mga punong pari at sa matatanda,
Sapagkat sa Diyos ay walang salitang hindi mangyayari.”
At pagkaraan ng mga araw na ito, naghanda kami at umahon patungo sa Jerusalem.
At pagkaawit ng isang himno, lumabas sila patungo sa bundok ng mga Olibo.
Sapagkat ang kapangyarihan ng mga kabayo ay nasa kanilang bibig at nasa kanilang mga buntot; ang kanilang mga buntot ay katulad ng mga ahas, na may mga ulo; at sa pamamagitan ng mga ito'y nakakapaminsala sila.
Kung ang iyong kapatid ay malayo sa iyo o kung hindi mo siya kilala, iuuwi mo ito sa iyong bahay at mananatili sa iyo hanggang sa hanapin ng may-ari, at kung gayo'y isasauli mo sa kanya.
Lumapit sa kanya ang napakaraming tao na dala ang mga pilay, mga lumpo, mga bulag, mga pipi, at marami pang iba. Inilagay nila ang mga ito sa kanyang paanan at sila'y pinagaling niya.
Kaya tumindig siya pagkatapos maghapunan, itinabi ang kanyang damit, at siya'y kumuha ng isang tuwalya, at ibinigkis sa kanyang sarili.
na sinasabi, “Mapalad ang Hari na dumarating sa pangalan ng Panginoon! Kapayapaan sa langit, at kaluwalhatian sa kataas-taasan!”
Gayon nila ilalagay ang aking pangalan sa mga anak ni Israel, at pagpapalain ko sila.”
Subalit alalahanin ninyo ang mga nakaraang araw, na pagkatapos na kayo'y maliwanagan, ay nagtiis kayo ng matinding pakikipaglaban na may pagdurusa,
“Sa lahat ng mga nasa tubig ay maaari ninyong kainin ang mga ito: alinmang may mga palikpik at mga kaliskis na nasa tubig, nasa dagat, at sa mga nasa ilog, ay makakain ninyo.
Ang ipinanganak ng laman ay laman at ang ipinanganak ng Espiritu ay espiritu.
na siyang pumatnubay sa iyo sa malaki at kakilakilabot na ilang na mayroong mga makamandag na ahas at mga alakdan, at tigang na lupa na walang tubig; na siyang nagbigay sa iyo ng tubig mula sa batong kiskisan;
At siya'y sumigaw, “Jesus! Anak ni David, maawa ka sa akin.”
Una, nagpapasalamat ako sa aking Diyos sa pamamagitan ni Jesu-Cristo tungkol sa inyong lahat, sapagkat ang inyong pananampalataya ay ipinahahayag sa buong daigdig.
maliban na ang Espiritu Santo ay nagpapatotoo sa akin sa bawat lunsod, na sinasabing ang mga tanikala at ang kapighatian ay naghihintay sa akin.
Upang maaliw sana ang kanilang mga puso, sa kanilang pagkakaisa sa pag-ibig, at magkaroon ang lahat ng mga kayamanan ng buong katiyakan ng pagkaunawa, at magkaroon ng kaalaman ng hiwaga ng Diyos, na si Cristo,
At biglang sumama sa anghel ang isang malaking hukbo ng langit na nagpupuri sa Diyos at nagsasabi,
Bago pa man siya nakatapos ng pagsasalita, si Rebecca na ipinanganak kay Betuel, na anak ni Milca, na asawa ni Nahor na kapatid ni Abraham ay lumabas na pasan ang banga sa kanyang balikat.
Sapagkat ang gayong mga tao ay mga huwad na apostol, mga mandarayang manggagawa, na nagpapanggap na mga apostol ni Cristo.
at kayong mga pinahihirapan ay bigyan ng kapahingahang kasama namin, sa pagkapahayag ng Panginoong Jesus mula sa langit na kasama ang kanyang mga makapangyarihang anghel,
lupaing inaalagaan ng Panginoon mong Diyos. Ang pansin ng Panginoon mong Diyos ay laging naroon, mula sa pasimula ng taon hanggang sa katapusan ng taon.
Sa kanya ay tinuli rin kayo ng pagtutuling hindi gawa ng mga kamay, sa pamamagitan ng paghuhubad ng katawang laman sa pagtutuli ni Cristo;
Sinabi nila sa kanya, “Saan siya naroon?” Sinabi niya, “Hindi ko alam.”
At nang sila'y lumapit ay kanilang sinabi sa kanya, “Guro, nalalaman naming ikaw ay tapat at hindi ka nangingimi kaninuman; sapagkat hindi ka nagtatangi ng mga tao, kundi itinuturo mo ang daan ng Diyos ayon sa katotohanan. Matuwid bang magbayad ng buwis kay Cesar o hindi? Dapat ba kaming magbayad o hindi?”
Gayundin, ipinanganak ng kanyang asawang-lingkod na si Reuma sina Teba, Gaham, Taas, at Maaca.
gayundin sa babaing may sakit ng kanyang karumihan, sa sinuman, babae o lalaki, na dinudugo o may tulo, at lalaki na sumisiping sa babaing marumi.
ngunit nang makita nilang siya'y lumalakad sa ibabaw ng dagat, inakala nilang iyon ay isang multo at sila'y sumigaw;
At may dumating at nagsabi sa kanila, “Tingnan ninyo, ang mga lalaking ibinilanggo ninyo ay nakatayo sa templo at nagtuturo sa mga tao!”
Kinaumagahan habang sila'y nagdaraan, nakita nila ang puno ng igos na natuyo mula sa mga ugat.
O kung kilala na ang baka ay dati nang manunuwag, at hindi ikinulong ng may-ari, magbabayad siya ng baka sa baka, at ang patay na hayop ay magiging kanya.
“Kapag dumating na ang Anak ng Tao na nasa kanyang kaluwalhatian, na kasama niya ang lahat ng mga anghel, siya'y uupo sa trono ng kanyang kaluwalhatian.
“Ang mga taong ito ay mabuting makitungo sa atin; kaya't hayaan natin silang manirahan sa lupain at magsipangalakal sila riyan, sapagkat ang lupain ay sapat ang laki para sa kanila. Ipakasal natin ang ating mga anak sa kanilang mga anak na babae, at ating ibigay sa kanila ang ating mga anak na babae.
“Mapapalad ang mga dukha sa espiritu, sapagkat kanila ang kaharian ng langit.
Pagkatapos ng Sabbath, sa pagbubukang-liwayway ng unang araw ng sanlinggo, si Maria Magdalena at ang isa pang Maria ay pumaroon upang tingnan ang libingan.
Si Pablo, na apostol ni Cristo Jesus sa pamamagitan ng kalooban ng Diyos, at si Timoteo na ating kapatid, sa iglesya ng Diyos na nasa Corinto, kasama ng lahat ng mga banal na nasa buong Acaia:
Italaga ninyo ang inyong mga sarili at kayo'y maging banal; sapagkat ako ang Panginoon ninyong Diyos.
“Gagawin mo ang balabal ng efod na purong asul.
Nangunguna sa hukbo ng lipi ng mga anak ni Zebulon si Eliab na anak ni Helon.
At ginawa ko ito sa Jerusalem; at hindi ko lamang kinulong sa mga bilangguan ang marami sa mga banal, sa pamamagitan ng awtoridad mula sa mga punong pari, kundi nang sila'y ipapatay, ay ibinibigay ko ang aking pagsang-ayon laban sa kanila.
Ngayon, ang pananampalataya ay ang katiyakan sa mga bagay na inaasahan, ang paninindigan sa mga bagay na hindi nakikita.
Sila'y kumain at nabusog. At may lumabis na mga piraso, pitong kaing na puno.
Mga kapatid ko, maaari ba na ang puno ng igos ay magbunga ng olibo, o ng mga igos ang puno ng ubas? Hindi rin maaaring daluyan ng tabang ang maalat na tubig.
Kaya't nararapat na magpasakop, hindi lamang dahil sa galit, kundi dahil din sa budhi.
Kung paanong si Abraham ay sumampalataya sa Diyos, at ito'y ibinilang sa kanya na katuwiran.
Ganito ang ginawa nina Moises at Aaron, at ng buong sambayanan ng mga anak ni Israel sa mga Levita. Ayon sa lahat ng iniutos ng Panginoon kay Moises tungkol sa mga Levita, ay gayon ginawa ng mga anak ni Israel sa kanila.
Lumabas ang isa pang anghel mula sa templo, na sumisigaw nang may malakas na tinig doon sa nakaupo sa ulap, “Ihulog mo ang iyong karit at gumapas ka, sapagkat dumating na ang oras ng paggapas, at hinog na ang aanihin sa lupa.”
na sinasabi, “Ito ang dugo ng tipan na iniutos ng Diyos sa inyo.”
Aming dinala bilang handog sa Panginoon ang nakuha ng bawat lalaki na mga hiyas na ginto, mga panali sa braso, at mga pulseras, mga singsing na pantatak, mga hikaw, at mga kuwintas sa leeg upang ipantubos sa aming mga sarili sa harap ng Panginoon .”
Ang panahon mula nang tayo ay lumabas sa Kadesh-barnea hanggang sa tayo'y nakarating sa batis ng Zared ay tatlumpu't walong taon, hanggang sa ang buong lahi ng mga lalaking mandirigma ay malipol sa gitna ng kampo, gaya ng ipinangako sa kanila ng Panginoon .
Nalalaman mo ang mga utos: ‘Huwag kang mangalunya; Huwag kang pumatay; Huwag kang magnakaw; Huwag kang tumayong saksi sa kasinungalingan; Igalang mo ang iyong ama at ina.’”
Bagaman ang aking kalagayan ay naging isang pagsubok sa inyo, hindi ninyo ako hinamak o kinasuklaman kundi tinanggap na gaya sa isang anghel ng Diyos, gaya ni Cristo Jesus.
Natatandaan ninyo, mga kapatid, ang aming pagpapagal at paghihirap. Gumagawa kami araw at gabi upang huwag kaming maging pasanin sa kaninuman sa inyo. Ipinahayag namin sa inyo ang ebanghelyo ng Diyos.
Dahil dito'y inusig ng mga Judio si Jesus sapagkat ginagawa niya ang mga bagay na ito sa araw ng Sabbath.
Subalit nang malaman ng mga Judiong taga-Tesalonica na ang salita ng Diyos ay ipinangaral din ni Pablo sa Berea, sila ay nagpunta rin doon upang guluhin at sulsulan ang maraming tao.
At ito ay lalo pang naging maliwanag nang lumitaw ang ibang pari, na kagaya ni Melquizedek,
Nang bumangon si Jose mula sa pagkakatulog, ginawa niya ang ipinag-utos sa kanya ng anghel ng Panginoon. Siya'y kanyang tinanggap bilang kanyang asawa.
Pagsapit ng gabi, lumusong ang kanyang mga alagad sa dagat.
Kapag makikipaglaban kayo sa inyong lupain laban sa kaaway na lumulupig sa inyo, inyo ngang patutunugin ang hudyat ng trumpeta; at kayo'y aalalahanin sa harap ng Panginoon ninyong Diyos, at kayo'y maliligtas sa inyong mga kaaway.
At ang nagkakagulong mga tao na nasa gitna nila ay nagkaroon ng matinding pananabik at ang mga anak ni Israel naman ay muling umiyak at nagsabi, “Sana'y mayroon tayong karneng makakain!
Nang magkagayo'y umakyat sina Moises, Aaron, Nadab, at Abihu, at ang pitumpung matatanda sa Israel,
at ang sumpa, kung hindi ninyo diringgin ang mga utos ng Panginoon ninyong Diyos, kundi lilihis sa daan na aking iniuutos sa inyo sa araw na ito, upang sumunod sa ibang mga diyos, na hindi ninyo nakilala.
Ngunit pinatayo siya ni Pedro, na sinasabi, “Tumayo ka, ako man ay tao rin.”
Huwag kang magbibigay ng iyong anak upang italaga iyon sa apoy kay Molec; ni huwag mong lalapastanganin ang pangalan ng iyong Diyos; Ako ang Panginoon .
Siya ang larawan ng Diyos na hindi nakikita, ang panganay sa lahat ng mga nilalang;
Ang pitong bakang magaganda ang anyo at matataba ay kinain ng mga bakang pangit ang anyo at payat. At nagising ang Faraon.
Siya'y bumalik kay Balak na nakatayo sa tabi ng kanyang handog na sinusunog kasama ang lahat ng mga pinuno ng Moab.
Siya'y makakasama mo bilang isang upahang lingkod at bilang isang nakikipanirahan; siya'y maglilingkod sa iyo hanggang sa taon ng pagdiriwang.
Iyong ipapasok ang hapag, at iyong aayusin ang mga bagay na nasa ibabaw niyon; at iyong ipapasok ang ilawan at iyong iaayos ang mga ilaw niyon.
Sasalutin ka ng Panginoon ng bukol sa Ehipto, ng mga ulser, ng pangangati, at ng galis na hindi mapapagaling.
mga tinik at dawag ang sisibol doon para sa iyo, at kakain ka ng tanim sa parang.
Ipinaghanda siya ni Levi ng isang malaking piging sa kanyang bahay at napakaraming maniningil ng buwis at iba pa na nakaupong kasalo nila.
Samantala, nasa bukid ang anak niyang panganay at nang siya'y dumating at papalapit sa bahay, nakarinig siya ng tugtugan at sayawan.
Sapagkat pinatotohanan, “Ikaw ay pari magpakailanman, ayon sa pagkapari ni Melquizedek.”
At sila'y iyong ginawang isang kaharian at mga pari para sa aming Diyos; at sila'y maghahari sa ibabaw ng lupa.”
At iyong isusulat ang mga ito sa pintuan ng iyong bahay at sa mga pasukan ng inyong mga bayan.
Ngunit tungkol sa iyo at sa iyong mga lingkod, alam ko na hindi pa kayo natatakot sa Panginoong Diyos.”
at sa pinakamabuti sa mga bunga ng araw, at sa mga pinakamabuting bunga ng mga buwan,
Sa ikapitong araw ay pitong toro, dalawampung tupang lalaki, labing-apat na korderong lalaki na isang taong gulang at walang kapintasan,
Binili niya sa halagang isandaang pirasong salapi ang bahaging iyon ng lupa na pinagtayuan ng kanyang tolda, sa kamay ng mga anak ni Hamor, na ama ni Shekem.
At siya'y muling nagsalita sa kanya, at nagsabi, “Halimbawang may matatagpuang apatnapu.” At sinabi niya, “Hindi ko gagawin alang-alang sa apatnapu.”
Nang gabing iyon ay agad na pinaalis ng mga kapatid sina Pablo at Silas patungo sa Berea. Nang dumating sila roon, pumasok sila sa sinagoga ng mga Judio.
Humayo ka at sabihin mo sa kanila, “Bumalik kayo sa inyong mga tolda.”
Subalit ngayon, yamang ako ay wala nang lugar para sa gawain sa mga lupaing ito, at yamang matagal ko nang nais na pumunta sa inyo,
Pagkatapos ay umalis siya, at nagsasama pa ng pitong espiritu na higit na masasama kaysa kanya, at sila'y pumapasok at naninirahan doon; at ang huling kalagayan ng taong iyon ay naging masahol pa kaysa una. Gayundin ang mangyayari sa masamang lahing ito.”
At ito ay hindi tulad sa aming inaasahan, kundi ibinigay muna nila ang kanilang sarili sa Panginoon, at sa amin sa pamamagitan ng kalooban ng Diyos.
Mula sa alay na mga handog pangkapayapaan na isang handog sa Panginoon na pinaraan sa apoy, iaalay niya ang taba niyon, ang buong matabang buntot na aalisin sa pinakamalapit sa gulugod, ang tabang bumabalot sa lamang-loob, at ang lahat ng taba ng lamang-loob.
Ang unang lumabas ay mapula na ang buong katawa'y parang mabalahibong damit; kaya't siya'y pinangalanang ng Esau.
Hinimok ko si Tito na humayo at sinugo kong kasama niya ang kapatid. Kayo ba'y dinaya ni Tito? Hindi ba kami kumilos sa iisang espiritu? Hindi ba gayundin ang aming naging mga hakbang?
Pagkahagis sa kanyang balabal, nagmamadali siyang tumayo at lumapit kay Jesus.
Magalak kayo sa pag-asa, maging matiisin sa kapighatian, matiyaga sa pananalangin.
At ngayon, bilang bihag sa Espiritu ay patungo ako sa Jerusalem, na hindi nalalaman ang mga bagay na mangyayari sa akin doon;
Gayundin naman ang mga nahasik sa batuhan, nang marinig nila ang salita, agad nila itong tinanggap na may galak;
“Bukod dito'y nagsalita sa akin ang Panginoon , na sinasabi, ‘Aking nakita ang bayang ito, at aking nakita na ito'y isang bayang matigas ang ulo.
Subalit pinagbantaan sila ng buong sambayanan na babatuhin sila ng mga bato. At ang kaluwalhatian ng Panginoon ay lumitaw sa toldang tipanan sa lahat ng mga anak ni Israel.
Siya'y kanilang ipinako sa krus, at pinaghati-hatian ang kanyang mga damit na kanilang pinagsapalaran, kung alin ang kukunin ng bawat isa.
At bumalik sa kampo si Moises at ang matatanda sa Israel.
At kanyang iginawa iyon ng apat na haliging akasya, at binalot ang mga ito ng ginto, ang kanilang mga kawit ay ginto rin at naghulma siya para sa mga ito ng apat na patungang pilak.
ang tinig ng isang sumisigaw sa ilang: ‘Ihanda ninyo ang daan ng Panginoon, Tuwirin ninyo ang kanyang mga landas,’”
At aking sinabi, aking aalisin kayo sa kapighatian sa Ehipto at dadalhin ko kayo sa lupain ng Cananeo, Heteo, Amoreo, Perezeo, Heveo, at ng Jebuseo, sa isang lupaing dinadaluyan ng gatas at pulot.”’
kaya't pinawawalang kabuluhan ang salita ng Diyos sa pamamagitan ng tradisyon na inyong ipinamana at marami pa kayong ginagawang mga bagay na katulad nito.
Isang dambanang lupa ang iyong gagawin para sa akin, at iyong iaalay doon ang iyong mga handog na sinusunog, mga handog pangkapayapaan, mga tupa, at mga baka. Sa lahat ng dakong aking ipapaalala ang aking pangalan ay pupunta ako sa iyo at pagpapalain kita.
Sinabi ng Faraon kay Jacob, “Gaanong karami na ang mga araw ng mga taon ng iyong buhay?”
Gayundin naman kayo, kapag nakita ninyo ang lahat ng mga bagay na ito, alam ninyong siya'y malapit na, nasa mga pintuan na.
Gaya ng nasusulat, “Dahil sa iyo kami'y pinapatay sa buong araw; kami ay itinuring na mga tupa sa katayan.”
Isinama ni Abram si Sarai na kanyang asawa, at si Lot na anak ng kanyang kapatid, at ang lahat ng pag-aaring kanilang natipon at ang mga taong kanilang nakuha sa Haran; at umalis sila upang pumunta sa lupain ng Canaan at nakarating sila roon.
ni Melqui, ni Adi, ni Cosam, ni Elmadam, ni Er,
At kung hindi paiikliin ang mga araw na iyon, ay walang makakaligtas na laman, subalit alang-alang sa mga hinirang ay paiikliin ang mga araw na iyon.
Sinumang manlalaro ay hindi pinuputungan malibang nakipagpaligsahan siya ayon sa mga alituntunin.
Maliit na bagay pa ba na kami ay iyong pinaalis sa isang lupain na dinadaluyan ng gatas at pulot, upang kami ay patayin sa ilang at gawin mo pa ang iyong sarili na aming pinuno?
Ang mga anak ni Isacar ayon sa kanilang mga angkan: kay Tola, ang angkan ng mga Tolaita; kay Pua, ang angkan ng mga Puanita;
kung natikman nga ninyo na ang Panginoon ay mabuti.
Nagkaanak din si Set ng isang lalaki, at tinawag ang kanyang pangalan na Enos. Nang panahong iyon ang mga tao ay nagsimulang tumawag sa pangalan ng Panginoon .
Subalit ngayon ay ipinahahayag ang pagiging matuwid ng Diyos na hiwalay sa kautusan at pinatotohanan ng kautusan at ng mga propeta;
Kaya't lumapit ang karamihan at nagpasimulang hilingin sa kanya na sa kanila'y gawin ang ayon sa kanyang nakaugalian.
Sapagkat dahil dito ay nagpapagal kami at nagsisikap, sapagkat nakalagak ang aming pag-asa sa Diyos na buháy, na siyang Tagapagligtas ng lahat ng tao, lalo na ng mga nananampalataya.
At kanyang sinabi, “Ako'y mangangahas magsalita sa Panginoon. Kung sakaling may matatagpuan doong dalawampu.” At sinabi niya, “Hindi ko lilipulin alang-alang sa dalawampu.”
Sinabi sa kanya ni Balak, “Ipinapakiusap ko sa iyo na sumama ka sa akin sa ibang lugar, kung saan mo sila makikita. Ang makikita mo lamang ay ang pinakamalapit sa kanila, at hindi mo sila makikitang lahat at sumpain mo sila para sa akin mula roon.”
Narito, may dalawa akong anak na babae na hindi pa nasipingan ng lalaki. Sila'y aking ilalabas sa inyo, at gawin ninyo sa kanila ang ayon sa inyong nais, huwag lamang ninyong gawan ng anuman ang mga lalaking ito, sapagkat sila'y nasa ilalim ng aking bubungan.”
Ang nagsisikap magligtas ng kanyang buhay ay mawawalan nito; at ang mawalan ng kanyang buhay dahil sa akin ay makakatagpo nito.
Akong si Tercio, na sumusulat ng sulat na ito, ay bumabati sa inyo sa Panginoon.
At nabuksan ang kanilang mga mata. Mahigpit silang pinagbilinan ni Jesus, “Ingatan ninyo na walang makakaalam nito.”
At ang bunga ng katuwiran ay itinatanim sa kapayapaan ng mga gumagawa ng kapayapaan.
Kanilang malalaman na ako ang Panginoon nilang Diyos na naglabas sa kanila sa lupain ng Ehipto, upang ako'y manirahang kasama nila. Ako ang Panginoon nilang Diyos.
Ngunit si Festo, sa pagnanais na gawan ng ikalulugod ang mga Judio, ay nagsabi kay Pablo, “Ibig mo bang pumunta sa Jerusalem at doon ka litisin sa mga bagay na ito sa harapan ko?”
At lilingapin ko kayo, at gagawin ko kayong mabunga. Pararamihin ko kayo at papagtibayin ko ang aking tipan sa inyo.
Sapagkat ibinigay sa pamamagitan ni Moises ang kautusan; ang biyaya at ang katotohanan ay dumating sa pamamagitan ni Jesu-Cristo.
Ngunit gagawa ang Panginoon ng pagkakaiba sa mga hayop ng Israel at sa mga hayop ng Ehipto, upang walang mamatay sa lahat ng nauukol sa mga anak ni Israel.’”
Si Chesed, Hazo, Pildas, Jidlaf, at si Betuel.”
Susuriin ito ng pari, at kung makitang ito'y tila mas malalim kaysa balat, at ang balahibo niyon ay pumuti, ipahahayag ng pari na siya ay marumi. Ito ay sakit na ketong na lumitaw mula sa bukol.
At sa dakong hulihan, sa gawing kanluran ng tabernakulo ay gumawa siya ng anim na haligi.
Sapagkat ang ikapu ng mga anak ni Israel na kanilang ihahandog bilang handog sa Panginoon ay aking ibinigay sa mga Levita bilang mana. Kaya't aking sinabi sa kanila, ‘Sa gitna ng mga anak ni Israel ay hindi sila magkakaroon ng mana.’”
Alalahanin ninyo ang salitang sinabi ko sa inyo, ‘Ang alipin ay hindi higit na dakila kaysa kanyang panginoon.’ Kung ako'y kanilang inusig, kayo man ay kanilang uusigin din; kung tinupad nila ang aking salita, ang inyo man ay tutuparin din nila.
ayon sa nasusulat, “Binigyan sila ng Diyos ng espiritu ng pagkakahimbing, ng mga matang hindi tumitingin, at ng mga taingang hindi nakikinig hanggang sa araw na ito.”
Lumaki ang sanggol, at inawat sa pagsuso; at nagdaos ng malaking handaan si Abraham nang araw na ihiwalay sa pagsuso si Isaac.
Sinabi ni Jesus sa kanila, “Ilang tinapay mayroon kayo?” Sinabi nila, “Pito, at ilang maliliit na isda.”
ay inihanda nila ang regalo sa pagdating ni Jose sa tanghali, sapagkat kanilang narinig na doon sila magsisikain.
Maglalagay ang pari ng kaunting dugo sa mga sungay ng dambana ng mabangong insenso sa harapan ng Panginoon , na nasa toldang tipanan at ang nalabi sa dugo ng toro ay ibubuhos sa paanan ng dambana ng handog na sinusunog na nasa pintuan ng toldang tipanan ng kapulungan.
Minsan, nang may oras na ikasiyam ng araw, nakita niyang maliwanag sa isang pangitain ang isang anghel ng Diyos na dumarating at sinasabi sa kanya, “Cornelio.”
hindi na siya muling makukuha upang maging asawa ng kanyang unang asawa na humiwalay sa kanya, pagkatapos na siya'y marumihan; sapagkat iyo'y karumaldumal sa harapan ng Panginoon . Huwag mong dadalhan ng pagkakasala ang lupain na ibinibigay bilang pamana sa iyo ng Panginoon mong Diyos.
At kanyang sinabi sa kanila, “Narito, pagpasok ninyo sa lunsod ay sasalubungin kayo ng isang lalaki na may dalang isang bangang tubig. Sundan ninyo siya hanggang sa bahay na kanyang papasukan.
Tumakbo ang isang binata at nagsabi kay Moises, “Sina Eldad at Medad ay nagsalita ng propesiya sa kampo.”
Sinabi ni Abram kay Lot, “Huwag na tayong magkaroon ng pagtatalo, maging ang ating mga pastol, sapagkat tayo'y magkapatid.
Gayon niya tutubusin ang santuwaryo dahil sa karumihan ng mga anak ni Israel, at dahil sa kanilang mga pagsuway, sa lahat nilang mga kasalanan. Gayon ang kanyang gagawin sa toldang tipanan na nasa kanila, sa gitna ng kanilang mga karumihan.
Siya mismo ang nagdala ng ating mga kasalanan sa kanyang katawan sa punungkahoy, upang tayo'y mamatay sa mga kasalanan at mabuhay sa katuwiran; dahil sa kanyang mga sugat ay gumaling kayo.
Dadalhin nila ang mga tabing ng tabernakulo, ang toldang tipanan, ang takip niyon, ang panakip na balat ng kambing na nasa ibabaw nito, at ang tabing sa pintuan ng toldang tipanan,
Kanilang ikinabit ang dalawang tanikalang lantay na ginto sa dalawang singsing sa mga sulok ng pektoral.
At siya na lilinisin ay maglalaba ng kanyang kasuotan at aahitin ang lahat niyang buhok, at maliligo sa tubig, at siya'y magiging malinis. Pagkatapos ay papasok siya sa kampo, subalit maninirahan sa labas ng kanyang tolda sa loob ng pitong araw.
tig-isang beka bawat ulo, samakatuwid, kalahati ng isang siklo, ayon sa siklo ng santuwaryo, sa bawat isa na nasali sa mga nabilang, magmula sa dalawampung taong gulang pataas, sa anim na raan at tatlong libo at limang daan at limampung lalaki.
Agad nabuksan ang kanyang mga tainga, nakalag ang tali ng kanyang dila, at siya'y nakapagsalita nang malinaw.
“Pagdating ninyo sa lupain ng Canaan na aking ibinigay sa inyo bilang pag-aari, at ako'y naglagay ng sakit na ketong sa isang bahay sa lupaing inyong pag-aari,
“Gagamit sila ng ginto, at ng telang asul, kulay-ube, at pula, at ng hinabing pinong lino.
at ang tanda o ang kababalaghan ay mangyari, na kanyang sabihin sa iyo, ‘Sumunod tayo sa ibang mga diyos,’ na hindi mo kilala, ‘at ating paglingkuran sila,’
Hindi ba't kasama natin ang lahat ng kanyang mga kapatid na babae? Saan kinuha ng taong ito ang lahat ng mga bagay na ito?”
Pagkatapos ay dinala siya ng diyablo sa isang mataas na lugar at ipinakita sa kanya sa isang saglit ang lahat ng mga kaharian sa sanlibutan.
Kaya't inalis ng buong bayan ang mga hikaw na ginto na nasa kanilang mga tainga, at dinala ang mga ito kay Aaron.
O kung isang lalaking tupa, ang iyong ihahanda para sa handog na butil ay dalawang ikasampung bahagi ng isang efa ng piling harina na hinaluan ng ikatlong bahagi ng isang hin ng langis.
At sa takot sa kanya, nanginig ang mga bantay, at naging tulad sa mga patay.
At sinabi niya sa akin, “Naganap na! Ako ang Alpha at ang Omega, ang pasimula at ang wakas. Ang nauuhaw ay aking paiinumin nang walang bayad sa bukal ng tubig ng buhay.
Sinabi sa kanya ng panginoon niya, ‘Magaling! Mabuti at tapat na alipin. Naging tapat ka sa kaunting bagay, pamamahalain kita sa maraming bagay. Pumasok ka sa kagalakan ng iyong panginoon.’
Sinabi sa kanya ng anghel, “Magbihis ka at isuot mo ang iyong mga sandalyas.” At iyon nga ang ginawa niya. At sinabi niya sa kanya, “Ibalot mo sa iyong sarili ang iyong balabal at sumunod ka sa akin.”
Nagkaroon ng hari sa Jeshurun, nang magkatipon ang mga pinuno ng bayan, pati ang lahat ng mga lipi ni Israel.
Gagawin sa kanila ng Panginoon ang gaya ng ginawa niya kina Sihon at Og, na mga hari ng mga Amoreo, at sa kanilang lupain na kanyang winasak.
na sa pamamagitan ng pahayag ay ipinaalam sa akin ang hiwaga, gaya ng nauna kong isinulat sa iilang mga salita.
Ngayon, sapagkat ang mga Amalekita at ang mga Cananeo ay naninirahan sa libis, bumalik kayo bukas at kayo'y maglakbay sa daang patungo sa Dagat na Pula.”
Kaya't magsisi ka. Kung hindi, madali akong darating sa iyo, at didigmain ko sila ng tabak ng aking bibig.
Kung tinawag niyang mga diyos ang mga dinatnan ng salita ng Diyos (at hindi maaaring masira ang kasulatan),
At narinig ko ang isang malakas na tinig sa langit na nagsasabi, “Ngayo'y dumating ang kaligtasan at ang kapangyarihan, at ang kaharian ng ating Diyos, at ang kapangyarihan ng kanyang Cristo, sapagkat itinapon na ang tagapag-paratang sa ating mga kapatid na siyang nagpaparatang sa kanila sa harapan ng ating Diyos, araw at gabi.
Pagkatapos, aking aalisin ang aking kamay, at iyong makikita ang aking likod; subalit ang aking mukha ay hindi makikita.”
Sa isang dayuhan ay maaari kang maningil; ngunit anumang pag-aari mo na nasa iyong kapatid ay ipatatawad mo.
Ngunit kayo'y may kaugalian na maaari kong pakawalan ang isang tao para sa inyo sa Paskuwa. Gusto ba ninyong pakawalan ko para sa inyo ang Hari ng mga Judio?”
Tiyakin ninyong walang sinuman sa inyo na maging gaya ni Esau na mapakiapid, o lapastangan, na kapalit ng isang pinggang pagkain ay ipinagbili ang kanyang sariling pagkapanganay.
Nakita ni Jose ang mga anak ni Efraim hanggang sa ikatlong salinlahi; gayundin ang mga anak ni Makir na anak ni Manases ay ipinanganak sa mga tuhod ni Jose.
At lahat ng lalaking kasambahay niya, maging ang mga aliping ipinanganak sa bahay niya at ang mga binili ng salapi sa taga-ibang lupain ay tinuling kasama niya.
‘At sa mga huling araw, sabi ng Diyos, mula sa aking Espiritu ay magbubuhos ako sa lahat ng laman; at ang inyong mga anak na lalaki at mga anak na babae ay magsasalita ng propesiya, at ang inyong mga kabataang lalaki ay makakakita ng mga pangitain, ang inyong matatandang lalaki ay mananaginip ng mga panaginip.
Hindi ako karapat-dapat sa lahat ng kaawaan, at lahat ng katotohanan na iyong ginawa sa iyong lingkod sapagkat dumaan ako sa Jordang ito na dala ang aking tungkod, at ngayo'y naging dalawang pulutong ako.
At ngayo'y nakikilala ninyo kung ano ang nakakapigil upang siya'y mahayag sa kanyang takdang panahon.
Sapagkat ang Diyos ang nagsabi, “Magningning ang ilaw sa kadiliman,” na siyang tumatanglaw sa aming mga puso upang magbigay-liwanag sa pagkakilala sa kaluwalhatian ng Diyos sa mukha ni Jesu-Cristo.
Ang anak ng alipin ay gagawin ko ring isang bansa, sapagkat siya'y iyong binhi.”
Nang mabalitaan ng Cananeo, na hari ng Arad, na naninirahan sa Negeb, na ang Israel ay daraan sa Atarim, nilabanan niya ang Israel at binihag ang iba sa kanila.
Bawat sakit, at bawat salot na hindi nakasulat sa aklat ng kautusang ito'y ipararating nga sa iyo ng Panginoon , hanggang sa ikaw ay mapuksa.
O kapag ang isang tao ay sumumpa nang padalus-dalos sa pamamagitan ng kanyang mga labi, upang gumawa ng masama o ng mabuti, anumang padalus-dalos na panunumpa na isinumpa ng tao, at iyon ay hindi niya nalaman, siya ay nagkakasala kapag nalaman niya iyon.
