Ang ipinanganak ng laman ay laman at ang ipinanganak ng Espiritu ay espiritu.
Sinabi niya sa kanila, “Sumunod kayo sa akin at gagawin ko kayong mga mamamalakaya ng mga tao.”
Ano nga ang ating sasabihin sa mga bagay na ito? Kung ang Diyos ay kakampi natin, sino ang laban sa atin?
Subalit huwag nawang mangyari sa akin ang magmalaki, maliban sa krus ng ating Panginoong Jesu-Cristo, na sa pamamagitan nito ang sanlibutan ay ipinako sa krus para sa akin, at ako'y sa sanlibutan.
‘Tinutugtugan namin kayo ng plauta at hindi kayo sumayaw;
at hindi ito nagkaugat sa kanilang sarili, kundi panandalian lamang. Kaya't nang dumating ang kapighatian o ang mga pag-uusig dahil sa salita, kaagad silang tumatalikod.
Ang bayang nakaupo sa kadiliman,
Ang mga kasalanan ng ibang tao ay hayag, at nauuna sa kanila sa paghuhukom, ngunit ang kasalanan ng iba ay susunod sa kanila roon.
Sila'y kanyang tinanong, “Ano ang ipinakikipagtalo ninyo sa kanila?”
Nang malapit na ang panahon ng pamumunga, sinugo niya ang kanyang mga alipin sa mga magsasaka upang kunin ang mga bunga nito.
Sinabi ng isa sa kanila, ng isang propeta mismo nila,
Kayo'y sa Diyos, mga munting anak, at inyong dinaig sila sapagkat siyang nasa inyo ay higit na dakila kaysa sa nasa sanlibutan.
Kaya't inyong nakikita na ang mga sumasampalataya ay mga anak ni Abraham.
Ano nga ang kalamangan ng Judio? O ano ang pakinabang sa pagtutuli?
Kayong mga mapagkunwari, tama ang ipinahayag ni Isaias tungkol sa inyo nang sabihin niya,
Sapagkat ang mga mata ng Panginoon ay nasa mga matuwid,
Gaya ng sinasabi,
Maraming tatalikod, magtataksil at mapopoot sa isa't isa.
“Gaya ng aking isinumpa sa aking pagkagalit,
Ang pista ng Tinapay na Walang Pampaalsa, na tinatawag na Paskuwa, ay papalapit na.
Akong si Tercio, na sumusulat ng sulat na ito, ay bumabati sa inyo sa Panginoon.
Kayo'y ipagkakanulo maging ng mga magulang at mga kapatid, mga kamag-anak at mga kaibigan, at ipapapatay nila ang iba sa inyo.
Ano ang salitang ito na kanyang sinabi, ‘Hahanapin ninyo ako, ngunit hindi ninyo ako matatagpuan, at kung saan ako naroroon, ay hindi kayo makakapunta roon’!”
at pumikit na ang kanilang mga mata;
At ganito ko nakita ang mga kabayo sa pangitain: ang mga nakasakay ay may mga baluting gaya ng apoy, ng jacinto at ng asupre; at ang mga ulo ng mga kabayo ay gaya ng mga ulo ng mga leon, at sa kanilang mga bibig ay lumalabas ang apoy, usok at asupre.
Samantalang siya'y nasa isa sa mga lunsod, may dumating na isang lalaki na punô ng ketong. Nang makita niya si Jesus, lumuhod siya at nakiusap sa kanya, “Panginoon, kung nais mo ay maaari mo akong linisin.”
Tumayo si Jesus at sinabi sa kanya, “Babae, nasaan sila? Wala na bang ni isang humatol sa iyo?”
At narinig nila ang isang malakas na tinig mula sa langit na nagsasabi sa kanila, “Umakyat kayo rito!” At sila'y umakyat sa langit sa isang ulap at nakita sila ng kanilang mga kaaway.
Taglay natin ito bilang isang tiyak at matibay na angkla ng kaluluwa, isang pag-asa na pumapasok sa loob ng santuwaryo, sa kabila ng tabing,
sa isang birheng nakatakdang ikasal sa isang lalaki, na ang pangalan ay Jose, mula sa sambahayan ni David. Ang pangalan ng birhen ay Maria.
para sa ikapupuri ng kanyang maluwalhating biyaya, na ipinagkaloob niya ng walang bayad sa atin sa pamamagitan ng Minamahal.
Nang araw ding iyon ay lumapit kay Jesus ang mga Saduceo, na nagsasabing walang pagkabuhay na muli; at kanilang tinanong siya,
Ang mga bagay na ito ay sinabi ko sa inyo upang ang aking kagalakan ay mapasainyo, at ang inyong kagalakan ay malubos.
Ngunit sinasabi ko, hindi ba naunawaan ng Israel? Una ay sinasabi ni Moises,
Sa mga araw ng kanyang buhay dito sa mundo, si Jesus ay naghandog ng mga panalangin at mga pakiusap na may malakas na pagtangis at pagluha sa may kapangyarihang magligtas sa kanya mula sa kamatayan, at siya'y pinakinggan dahil sa kanyang magalang na pagpapasakop.
Nililibak din siya ng mga kawal na lumapit sa kanya, at inalok siya ng suka,
Sila'y sinagot ni Juan, “Ako'y nagbabautismo sa tubig; sa gitna ninyo'y may isang nakatayo na hindi ninyo kilala,
Ang mga bagay na ito ay ginawa ng mga kawal.
Masdan ninyo ang mga bagay na nasa harapan ng inyong mga mata. Kung ang sinuman ay nagtitiwala na siya'y kay Cristo, paalalahanan niyang muli ang kanyang sarili na kung paanong siya'y kay Cristo, kami ay gayundin.
Magsugo ka sa Joppa, at ipatawag mo si Simon, na tinatawag na Pedro. Siya'y nanunuluyan sa bahay ni Simon na tagapagluto ng balat sa tabi ng dagat.’
“Ang bawat humihiwalay sa kanyang asawang babae at nag-asawa ng iba ay nagkakasala ng pangangalunya, at ang nag-aasawa sa babaing hiniwalayan ng kanyang asawa ay nagkakasala ng pangangalunya.
Paglabas niyang muli nang malapit na ang ikaanim na oras at ikasiyam, gayundin ang ginawa niya.
At muli,
Sa lupaing iyon ay may mga pastol ng tupa na nasa parang na nagbabantay sa kanilang kawan sa gabi.
ikaw nga na nagtuturo sa iba, hindi mo ba tuturuan ang iyong sarili? Ikaw na nangangaral sa tao na huwag magnakaw, nagnanakaw ka ba?
Nang tumingin sila sa itaas, wala silang nakitang sinuman, maliban kay Jesus.
Sa naunang mga salinlahi ay hindi ito ipinaalam sa mga anak ng mga tao, na gaya ngayon na ipinahayag na sa kanyang mga banal na apostol at propeta sa pamamagitan ng Espiritu:
Sapagkat nilingap niya ang abang kalagayan ng kanyang alipin.
Kanyang pinawalang-bisa ang kautusang mga batas sa mga alituntunin upang siya ay lumalang sa kanyang sarili ng isang bagong tao, kapalit ng dalawa, sa gayo'y gumagawa ng kapayapaan,
Mag-ingat kayo sa mga aso, mag-ingat kayo sa masasamang manggagawa, mag-ingat kayo sa mga hindi totoong pagtutuli.
bilang pag-alaala sa kanyang kahabagan.
Kaya't ipinapakiusap ko sa inyo na kayo'y kumain; ito ay para sa inyong kaligtasan, sapagkat hindi malalaglag kahit ang isang buhok sa ulo ng sinuman sa inyo.”
Nang marinig nila ang mga bagay na ito, sila ay nagalit at nagngalit ang kanilang mga ngipin laban kay Esteban.
Ngunit magmula ngayon ang Anak ng Tao ay mauupo sa kanan ng kapangyarihan ng Diyos.”
At tumayo siyang umiiyak sa likuran sa may paanan ni Jesus. Pinasimulan niyang basain ang kanyang mga paa ng kanyang mga luha, pinunasan ang mga ito ng kanyang buhok. Patuloy niyang hinagkan ang mga paa ni Jesus at binuhusan ang mga ito ng pabango.
Ako'y naging ministro nito, ayon sa katungkulang ipinagkatiwala ng Diyos sa akin para sa inyo, upang lubos na maipahayag ang salita ng Diyos,
Ang mga bulag at mga pilay ay lumapit sa kanya sa templo at sila'y kanyang pinagaling.
Bawat puno na hindi mabuti ang bunga ay pinuputol, at itinatapon sa apoy.
Ang kaligtasan, at kaluwalhatian, at kapangyarihan ay nauukol sa ating Diyos.
“Huwag ninyong isiping pumarito ako upang sirain ang kautusan o ang mga propeta; pumarito ako hindi upang sirain, kundi upang tuparin ang mga ito.
Kung kailangang ako'y magmalaki, ako'y magmamalaki sa mga bagay na nauukol sa aking kahinaan.
Tinawag nilang Zeus si Bernabe at Hermes si Pablo, sapagkat siya ang pangunahing tagapagsalita.
At samantalang tinatapos ni Juan ang kanyang gawain ay sinabi niya, ‘Sino ba ako sa inyong akala? Hindi ako siya. Ngunit may dumarating na kasunod ko. Hindi ako karapat-dapat na magkalag ng sandalyas ng kanyang mga paa.’
Sapagkat mula sa mga unang salinlahi si Moises ay mayroon sa bawat lunsod na nangangaral tungkol sa kanya, dahil binabasa siya nang malakas tuwing Sabbath sa mga sinagoga.”
Tingnan mo, ang iyong Hari ay dumarating sa iyo,
Oo, kahit ako'y ibuhos bilang inuming handog sa ibabaw ng alay at paglilingkod ng inyong pananampalataya, ako'y natutuwa at nakikigalak sa inyong lahat.
Samantalang nasa inyo ang ilaw, sumampalataya kayo sa ilaw, upang kayo'y maging mga anak ng ilaw.” Nang masabi ni Jesus ang mga bagay na ito siya'y umalis at nagtago sa kanila.
Hinipan ng ikaapat na anghel ang kanyang trumpeta at tinamaan ang ikatlong bahagi ng araw, ang ikatlong bahagi ng buwan, at ang ikatlong bahagi ng bituin kaya't nagdilim ang ikatlong bahagi nila, at ang ikatlong bahagi ng maghapon ay hindi nagliwanag, at gayundin naman ang gabi.
Kung kayo nga'y muling binuhay na kasama ni Cristo, ay hanapin ninyo ang mga bagay na nasa itaas, na kinaroroonan ni Cristo, na nakaupo sa kanan ng Diyos.
sapagkat hindi pa ito dumarating sa kaninuman sa kanila, kundi sila'y nabautismuhan lamang sa pangalan ng Panginoong Jesus.
Niluwalhati kita sa lupa, sa pagtatapos ko ng gawaing ibinigay mo sa akin.
Sinabi nga sa kanila ni Jesus, “Katotohanang sinasabi ko sa inyo, malibang inyong kainin ang laman ng Anak ng Tao at inumin ang kanyang dugo, wala kayong buhay sa inyong sarili.
Sumamba ang aming mga ninuno sa bundok na ito; ngunit sinasabi ninyo na ang lugar na dapat pagsambahan ng mga tao ay sa Jerusalem.”
Kaya't gaya ng sinasabi ng Espiritu Santo,
Nang ako'y dumating sa Troas upang ipangaral ang ebanghelyo ni Cristo, may pintong nabuksan para sa akin sa Panginoon,
Tiyakin ninyong walang sinuman sa inyo na maging gaya ni Esau na mapakiapid, o lapastangan, na kapalit ng isang pinggang pagkain ay ipinagbili ang kanyang sariling pagkapanganay.
Gawin mo ang mga bagay na ito; italaga mo ang iyong sarili sa mga ito upang ang iyong pag-unlad ay makita ng lahat.
na may susi ni David,
yamang itinalaga ng Diyos bilang pinakapunong pari ayon sa pagkapari ni Melquizedek.
Ginagawa nila ang lahat ng kanilang mga gawa upang makita ng mga tao; sapagkat pinalalapad nila ang kanilang mga pilakteria, at pinahahaba ang mga laylayan ng kanilang mga damit.
At ang kaloob na walang bayad ay hindi gaya ng ibinunga ng pagkakasala ng isang tao; sapagkat ang kahatulan na dumating na kasunod ng pagkakasala ng isa ay nagbunga ng paghatol, subalit ang kaloob na walang bayad na kasunod ng maraming pagsuway ay nagbunga ng pag-aaring-ganap.
Kinuha nila ang bangkay ni Jesus, at binalot nila ng mga telang lino na may mga pabango, ayon sa kaugalian ng mga Judio sa paglilibing.
Pagkatapos na siya'y kanilang libakin, inalis nila sa kanya ang kulay-ube na balabal at isinuot sa kanya ang kanyang mga damit. At siya'y kanilang inilabas upang ipako sa krus.
Ngunit kung ang masamang aliping iyon ay magsabi sa kanyang puso, ‘Magtatagal ang aking panginoon,’
Ngunit sinumang magkaila sa akin sa harapan ng mga tao, ay ipagkakaila ko rin naman sa harapan ng aking Ama na nasa langit.
kanilang nakita ang ilan sa kanyang alagad na kumakain ng tinapay na marurumi ang mga kamay, samakatuwid ay hindi hinugasan.
Ngunit ang kasalanan, pagkakita ng pagkakataon sa pamamagitan ng utos, ay gumawa sa akin ng sari-saring pag-iimbot, sapagkat kung walang kautusan ang kasalanan ay patay.
Sumagot sila, “Si Jesus na taga-Nazaret.” Sinabi sa kanila ni Jesus, “Ako nga iyon.” Si Judas na nagkanulo sa kanya ay nakatayong kasama nila.
Mga minamahal, ito ngayon ang ikalawang sulat na isinusulat ko sa inyo; at sa dalawang ito'y ginigising ko ang inyong tapat na pag-iisip sa pamamagitan ng pagpapaalala sa inyo;
Kanyang sinabi, “Sa ano natin maihahambing ang kaharian ng Diyos; o anong talinghaga ang gagamitin natin para dito?
Siya'y kanilang dinamitan ng kulay-ube, at nang makapagtirintas ng isang koronang tinik ay ipinutong nila ito sa kanya.
“Ikaw ay aking Anak,
At anumang bagay na inyong hingin sa panalangin na may pananampalataya ay inyong tatanggapin.”
Pagpasok ninyo sa bahay, batiin ninyo ito.
Makaraan ang tatlong buwan ay naglayag kami sa isang barkong Alejandria na nagpalipas ng tagginaw sa pulo, na ang sagisag ay Ang Magkapatid na Kambal.
Ngayon, nais naming malaman ninyo, mga kapatid, ang biyaya ng Diyos na ipinagkaloob sa mga iglesya ng Macedonia;
“Huwag humatol upang hindi kayo mahatulan.
Subalit hinihiling namin sa inyo, mga kapatid, na inyong igalang ang mga nagpapagal sa inyo, at namumuno sa inyo sa Panginoon at nagtuturo sa inyo;
At kapag natagpuan niya, pinapasan niya ito sa kanyang balikat na nagagalak.
Nang mga araw na iyon, siya ay nagtungo sa bundok upang manalangin at ginugol ang buong magdamag sa pananalangin sa Diyos.
Sumakay siya sa bangka kasama nila at tumigil ang hangin. At sila'y lubhang nanggilalas,
At muling ipinagkaila niya ito nang may panunumpa, “Hindi ko kilala ang taong iyon.”
at sinasabi nila sa mga bundok at sa mga bato, “Mahulog kayo sa amin at itago ninyo kami mula sa mukha ng nakaupo sa trono, at mula sa poot ng Kordero;
Sapagkat kayo'y nahabag sa mga bilanggo, at tinanggap ninyo nang buong galak ang pagkasamsam sa inyong mga ari-arian, palibhasa'y inyong nalalamang mayroon kayong isang pag-aaring higit na mabuti at tumatagal.
sa kapangyarihan ng mga tanda at ng mga kababalaghan, sa kapangyarihan ng Espiritu ng Diyos; kaya't buhat sa Jerusalem at sa palibot-libot hanggang sa Ilirico, ay aking ipinangaral na lubos ang ebanghelyo ni Cristo.
Subalit ang pinuno ng sinagoga, na galit sapagkat si Jesus ay nagpagaling sa Sabbath, ay nagsabi sa maraming tao, “May anim na araw na dapat gumawa, pumarito kayo sa mga araw na iyon at kayo'y pagagalingin at hindi sa araw ng Sabbath.”
At sinasabi ko sa inyo: sinumang ihiwalay ang kanyang asawang babae, maliban sa pakikiapid ang dahilan, at mag-asawa ng iba, ay nagkakasala ng pangangalunya. At ang mag-asawa sa babaing inihiwalay ay nagkakasala ng pangangalunya.”
At ako'y lalo pang nakikiusap sa inyo na inyong gawin ito, upang ako'y madaling maibalik sa inyo.
Tatlong ulit akong nanalangin sa Panginoon tungkol dito na lumayo sana ito sa akin.
Sila'y mga Israelita, na sa kanila ang pagkukupkop, at ang kaluwalhatian, at ang mga tipan, at ang pagtanggap sa kautusan, at ang pagsamba at ang mga pangako;
Gaya ng pagkakilala sa akin ng Ama, at ng pagkakilala ko sa Ama, at ibinibigay ko ang aking buhay para sa mga tupa.
na sinasabi, “Ano ang palagay ninyo tungkol sa Cristo? Kaninong anak siya?” Sinabi nila sa kanya, “Kay David.”
Lumapit ang isang eskriba at nagsabi sa kanya, “Guro, susunod ako sa iyo saan ka man magtungo.”
Ngunit siya'y nagbibigay ng higit pang biyaya. Kaya't sinasabi, “Ang Diyos ay sumasalungat sa mga mapagmataas, subalit nagbibigay ng biyaya sa mga mapagpakumbaba.”
at ako'y mahahabag sa aking kinahahabagan.”
At lumaki ang bata, lumakas, napuno ng karunungan, at sumasakanya ang biyaya ng Diyos.
Sapagkat hindi kami lumampas sa aming hangganan nang kami'y dumating sa inyo. Kami ang unang dumating sa inyo dala ang ebanghelyo ni Cristo.
isang taong masipag sa kabanalan at may takot sa Diyos kasama ang kanyang buong sambahayan, naglilimos ng marami sa mga tao, at laging nananalangin sa Diyos.
Ang isa sa mga ulo nito ay parang pinatay, ngunit ang sugat nito na ikamamatay ay gumaling, at ang buong lupa ay namamanghang sumunod sa halimaw.
Sinabi ng mga Fariseo sa isa't isa, “Tingnan ninyo, wala kayong magagawa. Ang sanlibutan ay sumusunod sa kanya.”
Ang mga nagkawatak-watak ay naglakbay na ipinangangaral ang salita.
At siya'y kanilang hinubaran at dinamitan ng isang balabal na pulang-pula.
kundi ng mahalagang dugo ni Cristo, gaya ng sa korderong walang kapintasan at walang dungis.
Lumapit ang anghel sa kanya, at sinabi, “Magalak ka, ikaw na pinagpala! Ang Panginoon ay sumasaiyo.”
Subalit ang magkaila sa akin sa harap ng mga tao ay ipagkakaila sa harap ng mga anghel ng Diyos.
Sundan mo ang huwaran ng mga wastong salita na narinig mo sa akin, sa pananampalataya at pag-ibig na na kay Cristo Jesus.
Sila'y nagsigawan, “Ilayo siya, ilayo siya, ipako siya sa krus!” Sinabi sa kanila ni Pilato, “Ipapako ko ba sa krus ang inyong Hari?” Sumagot ang mga punong pari, “Wala kaming hari liban kay Cesar.”
at ang mga bagay na iyong narinig sa akin sa harap ng maraming saksi ay siya mo ring ipagkatiwala sa mga taong tapat na makakapagturo rin naman sa iba.
Ngunit maging tagatupad kayo ng salita, at hindi tagapakinig lamang, na dinadaya ninyo ang inyong mga sarili.
Subalit nang unang araw ng sanlinggo sa pagbubukang-liwayway, pumunta sila sa libingan, dala ang mga pabango na kanilang inihanda.
Nang makita niya si Jesus, siya'y sumigaw, lumuhod sa harapan niya, at nagsalita sa malakas na tinig, “Anong pakialam mo sa akin, Jesus, Anak ng Diyos na Kataas-taasan? Nakikiusap ako sa iyo, huwag mo akong pahirapan.”
Pinaratangan siya ng mga punong pari ng maraming bagay.
kundi subukin ninyo ang lahat ng mga bagay; panghawakan ninyo ang mabuti.
At mapalad ang sinumang hindi natitisod sa akin.”
Subalit kinuha siya ni Bernabe, iniharap siya sa mga apostol, isinalaysay sa kanila kung paanong nakita niya sa daan ang Panginoon, na nakipag-usap sa kanya, at kung paanong siya'y nangaral sa Damasco na may katapangan sa pangalan ni Jesus.
Gayon ang mangyayari sa katapusan ng sanlibutan. Lalabas ang mga anghel at kanilang ihihiwalay ang masasama sa matutuwid,
O iyong pitong tinapay para sa apat na libo at kung ilang kaing ang inyong natipon?
Muli niyang sinabi sa kanila, “Aalis ako, at ako'y inyong hahanapin, at mamamatay kayo sa inyong kasalanan. Sa aking pupuntahan ay hindi kayo makakapunta.”
Kaya't sinabi ng mga Judio sa isa't isa, “Saan pupunta ang taong ito na hindi natin siya matatagpuan? Pupunta kaya siya sa mga lupain kung saan nagkalat ang ating mga kababayan sa lupain ng mga Griyego at magtuturo sa mga Griyego?
At sinabi ng mga hangal sa matatalino, ‘Bigyan ninyo kami ng inyong langis, sapagkat namamatay na ang aming mga ilawan.’
Ngayon nga'y wala nang kahatulan sa mga na kay Cristo Jesus.
At sinabi niya sa kanila, “Hindi ba ninyo nalalaman ang talinghagang ito? Paano nga ninyo mauunawaan ang lahat ng mga talinghaga?
Sa pananampalataya si Abraham, nang tawagin, ay sumunod upang pumunta sa isang lugar na kanyang tatanggapin bilang pamana; at siya'y pumunta na hindi nalalaman ang kanyang pupuntahan.
Ang mga bagay na ito ay aking isinusulat sa iyo, na umaasang makakarating sa iyo sa madaling panahon,
Kung ang sinuman ay maglilingkod sa akin ay dapat sumunod sa akin, at kung saan ako naroroon, ay naroroon din ang lingkod ko. Kung ang sinuman ay maglilingkod sa akin, siya'y pararangalan ng Ama.
Nang kami'y makaligtas na, noon namin nalaman na ang pulo ay tinatawag na Malta.
na nagsasabi ng may malakas na tinig,
sapagkat bibigyan ko kayo ng salita at karunungan na hindi malalabanan o matututulan man ng lahat ng sumasalungat sa inyo.
Kaya't mula nang araw na aming marinig ito, hindi kami tumigil ng pananalangin para sa inyo at sa paghiling na kayo'y punuin ng kaalaman ng kanyang kalooban sa buong karunungan at pagkaunawang espirituwal,
Muli siyang tinanong ni Pilato, “Wala ka bang isasagot? Tingnan mo kung gaano karami ang kanilang ibinibintang laban sa iyo.”
Ngayon ang mga ito ay higit na mararangal kaysa mga taga-Tesalonica, sapagkat tinanggap nila ang salita ng buong pananabik na sinisiyasat araw-araw ang mga kasulatan kung tunay nga ang mga bagay na ito.
(na sa mga iyon ay hindi karapat-dapat ang sanlibutan). Sila'y nagpalabuy-laboy sa mga ilang, sa mga kabundukan, sa mga yungib, at sa mga lungga sa lupa.
Ngunit huwag mong susukatin ang patyo sa labas ng templo; pabayaan mo na iyon, sapagkat ibinigay iyon sa mga bansa at kanilang yuyurakan ang banal na lunsod sa loob ng apatnapu't dalawang buwan.
Malapit na noon ang pista ng mga Judio, ang pista ng mga Tabernakulo.
Sapagkat ang anak kong ito ay patay na, at muling nabuhay; siya'y nawala, at natagpuan.’ At sila'y nagsimulang magdiwang.
Sinabi pa niya, “Ang lumalabas sa tao ang nakapagpaparumi sa tao.
Si Judas Iscariote naman, na isa sa labindalawa, ay nagpunta sa mga punong pari upang maipagkanulo siya sa kanila.
Kung inaakala ng sinuman na siya'y relihiyoso, subalit hindi pinipigil ang kanyang dila, kundi dinadaya ang kanyang puso, ang relihiyon ng taong iyon ay walang kabuluhan.
Sinabi niya, “Ako ang tinig ng isang sumisigaw sa ilang na lugar, ‘Tuwirin ninyo ang daan ng Panginoon, gaya ng sinabi ng propeta Isaias.’”
Ang mga eskriba at mga Fariseo ay nagsimulang magtanong, “Sino ba ito na nagsasalita ng mga kalapastanganan? Sino ang makapagpapatawad ng mga kasalanan maliban sa Diyos lamang?”
Sinabi ng iba, ‘Ako'y nagpakasal kaya't hindi ako makakarating.’
Kung inyong patawarin ang mga kasalanan ng sinuman, ang mga iyon ay ipinatatawad sa kanila. Sinumang hindi ninyo patawarin ng mga kasalanan, iyon ay hindi ipinatatawad.”
Sa kanilang pagpapatuloy sa daan, nakarating sila sa may tubig, at sinabi ng eunuko, “Tingnan mo, narito ang tubig! Ano ang nakakahadlang upang akoy mabautismuhan?”
sapagkat kayo'y tatawa.
“Magsilabas kayo sa kanya, bayan ko,
[
Sapagkat kung ginagawa nila ang mga bagay na ito kapag ang punungkahoy ay sariwa, anong mangyayari kapag ito ay tuyo?
“Ikaw ay aking Anak,
Kinagabihan, dumating ang isang mayamang mula sa Arimatea, na ang pangalan ay Jose, na naging alagad din ni Jesus.
Sapagkat kayo, mga kapatid, ay tinawag sa kalayaan; subalit huwag lamang ninyong gagamitin ang inyong kalayaan bilang isang kadahilanan para sa laman, kundi sa pamamagitan ng pag-ibig ay maging alipin kayo ng isa't isa.
Sapagkat lagi ninyong kasama ang mga dukha at kung kailan ninyo nais, magagawan ninyo sila ng mabuti, ngunit ako'y hindi ninyo laging makakasama.
Kasama ng lahat ng mga ito, taglayin ninyo ang kalasag ng pananampalataya, na sa pamamagitan nito ay inyong masusugpo ang mga nag-aapoy na palaso ng masama.
Silang lahat ay kumain at nabusog at pinulot nila ang lahat ng natira, labindalawang kaing ng mga pinagputul-putol.
Kaya't ang sinumang nakakaalam ng paggawa ng mabuti ngunit hindi ito ginagawa, ito ay kasalanan sa kanya.
Kaya tumindig siya pagkatapos maghapunan, itinabi ang kanyang damit, at siya'y kumuha ng isang tuwalya, at ibinigkis sa kanyang sarili.
Pagkatapos magsisigaw at lubhang pangisayin ang bata, lumabas ito at ang bata'y naging anyong patay, kaya't marami ang nagsabing siya'y patay na.
Akong si Pablo ay sumusulat nito sa pamamagitan ng aking sariling kamay: Ako ang magbabayad niyon. Hindi ko na ibig banggitin pa na utang mo sa akin pati ang iyong sarili.
Sapagkat kung mayroong pagnanais, tinatanggap ang kaloob ayon sa tinataglay, at hindi ayon sa hindi tinataglay.
Pagkatapos ay ibinigay niya sa kanya ang tipan ng pagtutuli. Kaya't si Abraham ay naging ama ni Isaac, at ito'y tinuli nang ikawalong araw; at si Isaac ay naging ama ni Jacob, at si Jacob ng labindalawang patriyarka.
Sinabi niya, “Ang kaharian ng Diyos ay gaya ng isang taong naghahasik ng binhi sa lupa,
Subalit kanyang ipinagbilin at ipinag-utos sa kanila na huwag itong sabihin kahit kanino,
Kanyang pinapunta sila sa Bethlehem at sinabi sa kanila, “Humayo kayo at hanapin ninyong mabuti ang sanggol; kapag siya ay inyong natagpuan na, ipagbigay-alam ninyo sa akin, upang ako rin ay makaparoon at siya ay aking sambahin.”
upang kanilang hanapin ang Diyos, baka sakaling siya'y mahagilap nila at siya'y matagpuan, bagaman hindi siya malayo sa bawat isa sa atin.
Samantala, si Jesus ay pumunta sa bundok ng mga Olibo.
At nagkaroon ng malaking kagalakan sa lunsod na iyon.
Subalit kailangan muna siyang magdusa ng maraming bagay at itakuwil ng lahing ito.
Nang ikaanim na buwan, sinugo ng Diyos ang anghel na si Gabriel sa isang bayan ng Galilea, na tinatawag na Nazaret,
Kung kayo'y namatay na kasama ni Cristo mula sa mga simulain ng sanlibutan, bakit kayo'y nabubuhay na parang nasa sanlibutan pa rin? Bakit kayo'y nagpapasakop sa mga alituntuning,
At makikita ng lahat ng laman ang pagliligtas ng Diyos.’”
Nang magawa nila ito, nakahuli sila ng napakaraming isda, at halos masira ang kanilang mga lambat,
Sinabi sa kanya ni Pedro, “Hindi mo huhugasan ang aking mga paa kailanman.” Sinagot siya ni Jesus, “Kung hindi kita huhugasan, ay hindi ka magkakaroon ng bahagi sa akin.”
Sapagkat ako sa pamamagitan ng kautusan ay namatay sa kautusan, upang ako'y mabuhay sa Diyos.
Ngunit sumagot ang matatalino na nagsasabi, ‘Maaaring hindi sapat para sa amin at para sa inyo. Kaya't pumunta kayo sa mga nagtitinda at bumili kayo ng para sa inyo.’
Sapagkat ang sinumang ikahiya ako at ang aking mga salita ay ikahihiya siya ng Anak ng Tao, pagdating niya na nasa kanyang kaluwalhatian, at sa kaluwalhatian ng Ama, at ng mga banal na anghel.
“Ipahahayag ko ang iyong pangalan sa aking mga kapatid,
Sa oras na iyon ay sinabi ni Jesus sa mga napakaraming tao, “Kayo ba'y lumabas na parang laban sa isang tulisan, na may mga tabak at mga pamalo upang dakpin ako? Araw-araw ay nakaupo ako sa templo na nagtuturo, at hindi ninyo ako dinakip.
At pagharap niya sa babae ay sinabi niya kay Simon, “Nakikita mo ba ang babaing ito? Pumasok ako sa iyong bahay, hindi mo ako binigyan ng tubig para sa aking mga paa, subalit binasa niya ang aking mga paa ng kanyang mga luha at pinunasan ang mga ito ng kanyang buhok.
Ito'y napabalita sa buong Joppa at marami ang nanampalataya sa Panginoon.
Ngunit mapapalad ang inyong mga mata, sapagkat ang mga ito'y nakakakita; at ang inyong mga tainga, sapagkat ang mga ito'y nakakarinig.
sapagkat siya'y nasa aking kanang kamay, upang huwag akong matinag;
Si Maria ay nanatiling kasama niya nang may tatlong buwan, at umuwi siya sa kanyang bahay.
Biglang dumating mula sa langit ang isang ugong na gaya ng isang humahagibis na hanging malakas, at pinuno nito ang buong bahay kung saan sila'y nakaupo.
Nakaraan na ang ikalawang kapighatian. Ang ikatlong kapighatian ay napakalapit nang dumating.
Sapagkat tunay na matuwid sa Diyos na gantihan ng kapighatian ang mga nagpapahirap sa inyo,
Si Maria ay kumuha ng isang libra ng mamahaling pabango mula sa purong nardo at pinahiran ang mga paa ni Jesus, at pinunasan ang mga paa nito ng kanyang mga buhok. At ang bahay ay napuno ng amoy ng pabango.
Sinasabi ko sa inyo, sa gabing iyon ay may dalawa sa isang higaan; ang isa'y kukunin, at ang isa'y iiwan.
Sa ganito kayo'y nagagalak, bagama't ngayon sa sandaling panahon ay kailangan ninyong magdanas ng iba't ibang pagsubok,
Sinabi niya sa mga alagad, “Darating ang mga araw na hahangarin ninyong makita ang isa sa mga araw ng Anak ng Tao at hindi ninyo ito makikita.
Sa gayunding paraan, ang tabernakulo at ang lahat ng mga kasangkapang ginagamit sa banal na pagsamba ay pinagwiwisikan niya ng dugo.
kundi sa bawat bansa ang sinumang may takot sa kanya at gumagawa ng matuwid ay kalugud-lugod sa kanya.
At sila'y sasagutin niya, na nagsasabi, ‘Katotohanang sinasabi ko sa inyo, yamang hindi ninyo ito ginawa sa isa sa pinakamaliliit na ito, ay hindi ninyo ito ginawa sa akin.’
Iniligtas niya tayo sa kapangyarihan ng kadiliman at inilipat tayo sa kaharian ng kanyang minamahal na Anak,
“Magalak kayo at magsaya, sapagkat malaki ang gantimpala ninyo sa langit, sapagkat gayundin nila inusig ang mga propeta na nauna sa inyo.
si Felipe at si Bartolome; si Tomas at si Mateo na maniningil ng buwis; si Santiago na anak ni Alfeo, at si Tadeo;
Sapagkat hindi kami natagpuang gumamit kailanman ng mga salitang paimbabaw, gaya ng nalalaman ninyo, ni ng balabal ng kasakiman, saksi namin ang Diyos;
Pinahintulutan silang huwag patayin ang mga ito, kundi pahirapan ng limang buwan at ang kanilang pahirap ay gaya ng pahirap ng alakdan kung kumakagat sa isang tao.
Ngunit upang malaman ninyo na ang Anak ng Tao ay may awtoridad sa ibabaw ng lupa na magpatawad ng mga kasalanan,”—sinabi niya ito sa lumpo, “Sinasabi ko sa iyo, tumindig ka, buhatin mo ang iyong higaan, at umuwi ka sa bahay mo.”
Ngunit siya'y sumagot at sinabi sa kanila, “Hindi ba ninyo nakikita ang lahat ng mga bagay na ito? Katotohanang sinasabi ko, walang matitira ni isang bato rito na nasa ibabaw ng ibang bato na hindi ibabagsak.”
Subalit nalalaman natin na ang hatol ng Diyos sa kanila na nagsisigawa ng gayong mga bagay ay ayon sa katotohanan.
At muli, nang kanyang dinadala ang panganay sa daigdig ay sinasabi niya,
“Humayo kayo, tumayo kayo sa templo at sabihin ninyo sa mga tao ang lahat ng mga salita tungkol sa buhay na ito.”
Pinasasalamatan ba niya ang alipin, sapagkat ginawa niya ang iniutos sa kanya?
“Purihin ninyo ang Panginoon, kayong lahat ng mga Hentil; at purihin siya ng lahat ng mga bayan.”
at ipinahayag na Anak ng Diyos na may kapangyarihan ayon sa Espiritu ng kabanalan, sa pamamagitan ng pagkabuhay mula sa mga patay, na ito'y si Jesu-Cristo na Panginoon natin.
O Timoteo, ingatan mo ang ipinagkatiwala sa iyo. Iwasan mo ang mga usapang walang kabuluhan at ang mga pagsalungat ng huwad na kaalaman;
Tumakbo sila sa palibot ng buong lupaing iyon at pinasimulan nilang dalhin ang mga maysakit na nasa kanilang higaan, saanman nila mabalitaan na naroon siya.
Pagkatapos ay sinabi niya sa alagad, “Narito ang iyong ina!” At mula noon ay dinala siya ng alagad sa kanyang sariling tahanan.
Ang ilan sa mga eskriba ay nagsabi, “Nilalapastangan ng taong ito ang Diyos.”
Hindi mo ako hinalikan, subalit buhat nang ako'y pumasok ay hindi pa siya humihinto ng paghalik sa aking mga paa.
At lubhang nalungkot ang hari, ngunit dahil sa kanyang pangako at sa kanyang mga panauhin, ayaw niyang tumanggi sa kanya.
Nang pumasok si Jesus sa bahay ni Pedro, nakita niya ang biyenang babae nito na nakaratay dahil sa lagnat.
Nang mabalitaan niya na si Jesus ay dumating sa Galilea mula sa Judea, pumunta siya roon at nakiusap sa kanya na siya'y pumunta at pagalingin ang kanyang anak na lalaki sapagkat siya'y malapit nang mamatay.
Sinabi niya sa kanila, “Kapag kayo'y nananalangin, inyong sabihin,
At si Pablo ay pumasok ayon sa kanyang kaugalian, at sa loob ng tatlong Sabbath ay nangatuwiran sa kanila mula sa mga kasulatan,
Subalit ang nagpapatibay sa amin na kasama ninyo kay Cristo, at nagpahid sa amin ay ang Diyos,
at sila'y pagalingin ko.”
ngunit sumagot ang kanyang ina at nagsabi, “Hindi. Ang itatawag sa kanya ay Juan.”
Subalit nang siya'y matauhan ay sinabi niya, ‘Ilan sa mga upahang lingkod ng aking ama ang may sapat at lumalabis na pagkain, ngunit ako rito'y namamatay sa gutom?
“Bakit lumalabag ang iyong mga alagad sa tradisyon ng matatanda? Hindi sila naghuhugas ng kanilang mga kamay bago sila kumain ng tinapay.”
Kung sinasabi nating tayo'y hindi nagkasala, ginagawa natin siyang sinungaling at ang kanyang salita ay wala sa atin.
Sinasabi ko sa inyo, higit pang mapagtitiisan sa araw na iyon ang Sodoma kaysa bayang iyon.
Nang marinig niya ito, dali-dali siyang tumayo at pumunta sa kanya.
tungkol sa sigasig, ay taga-usig ng iglesya; ayon sa katuwirang nasa kautusan ay walang kapintasan.
Maging sa aking mga aliping lalaki at mga aliping babae,
Magtiis kayo alang-alang sa disiplina. Kayo ay pinapakitunguhan ng Diyos bilang mga anak, sapagkat ano ngang anak ang hindi dinidisiplina ng ama?
na dati ninyong nilakaran, ayon sa lakad ng sanlibutang ito, ayon sa pinuno ng kapangyarihan ng himpapawid, ng espiritu na ngayon ay gumagawa sa mga anak ng pagsuway.
sinabi rin niya,
Sapagkat kung hindi pinatawad ng Diyos ang mga anghel nang magkasala sila, kundi sila'y ibinulid sa impiyerno, at nilagyan ng mga tanikala ng kadiliman, upang ingatan hanggang sa paghuhukom;
At sa oras ng paghahandog ng insenso, ang napakaraming tao ay nananalangin sa labas.
Sa lahat ng bagay ay magpasalamat kayo, sapagkat ito ang kalooban ng Diyos kay Cristo Jesus para sa inyo.
Siya'y nagpatirapa sa paanan ni Jesus na nagpapasalamat sa kanya. Siya'y isang Samaritano.
maging sa atin na kanyang tinawag, hindi lamang mula sa mga Judio, kundi mula rin sa mga Hentil?
Muli nilang pinagsikapang siya'y hulihin, subalit siya'y tumakas sa kanilang mga kamay.
Dumating ang mga Fariseo at ang mga Saduceo, at upang subukin siya, hiniling nila sa kanya na magpakita sa kanila ng isang tanda mula sa langit.
Tungkol sa mga anghel ay sinasabi niya,
Nang makaalis na ang mga sugo ni Juan ay nagpasimula siyang magsalita sa maraming tao tungkol kay Juan. “Ano ang pinuntahan ninyo sa ilang upang makita? Isa bang tambo na inuuga ng hangin?
na sinasabi, “Ang mga eskriba at ang mga Fariseo ay umuupo sa upuan ni Moises.
kayong lahat na mga alipin niya,
At inyong hayaan na malubos ng pagtitiis ang gawa nito, upang kayo'y maging sakdal at ganap, na walang anumang kakulangan.
Nakarinig din ako ng isang tinig na nagsasabi sa akin, ‘Tumindig ka, Pedro; magkatay ka at kumain.’
Ngayon, sinunod mong mabuti ang aking aral, pamumuhay, layunin, pananampalataya, pagtitiyaga, pag-ibig, at pagtitiis,
“Kaya't kung ang kamay mo o ang paa mo ay nakapagpapatisod sa iyo, putulin mo ito at itapon. Mas mabuti pa sa iyo ang pumasok sa buhay na may kapansanan o lumpo kaysa may dalawang kamay o dalawang paa na maitapon sa apoy na walang katapusan.
At ano pa ang dapat kong sabihin? Sapagkat kukulangin ako ng panahon kung isasalaysay ko pa ang tungkol kina Gideon, Barak, Samson, Jefta, David, Samuel, at sa mga propeta;
Hindi ba sila ang lumalapastangan sa mabuting pangalan na itinawag sa inyo?
At narinig ko ang isang tinig mula sa langit na nagsasabi, “Isulat mo ito: Mapapalad ang mga patay na namamatay sa Panginoon mula ngayon.” “Oo,” sinasabi ng Espiritu, “sila'y magpapahinga sa kanilang mga gawa, sapagkat ang kanilang mga gawa ay sumusunod sa kanila.”
Sinabi sa kanya ni Nathanael, “Mayroon bang mabuting bagay na maaaring manggaling sa Nazaret?” Sinabi sa kanya ni Felipe, “Halika at tingnan mo.”
Ngunit sa pag-aakala nilang siya'y kasama ng mga manlalakbay, nagpatuloy sila ng isang araw na paglalakbay. Pagkatapos ay kanilang hinahanap siya sa mga kamag-anak at mga kakilala,
Subalit huwag ninyong kaliligtaan ang katotohanang ito, mga minamahal, ang isang araw sa Panginoon ay tulad ng sanlibong taon, at ang sanlibong taon ay tulad ng isang araw.
sapagkat marami ang sumasaksi ng kasinungalingan laban sa kanya, at ang kanilang mga patotoo ay hindi nagkakatugma.
At sinumang magbigay ng kahit isang basong tubig na malamig sa isa sa maliliit na ito sa pangalan ng isang alagad, katotohanang sinasabi ko sa inyo, tiyak na hindi siya mawawalan ng kanyang gantimpala.”
“Alam ko ang iyong mga gawa. Tingnan mo, inilagay ko sa harapan mo ang isang pintong bukas, na hindi maisasara ng sinuman. Alam kong ikaw ay may kaunting kapangyarihan, ngunit tinupad mo ang aking salita, at hindi mo itinakuwil ang aking pangalan.
Subalit silang lahat ay sama-samang sumigaw, “Alisin ang taong ito, palayain si Barabas para sa amin.”
Nang ito'y kanilang mabasa, sila ay nagalak sa pangaral.
‘Ang mga taga-Creta ay laging mga sinungaling, masasamang hayop, mga batugang matatakaw.’
At siya'y kanilang dinaig dahil sa dugo ng Kordero,
“Gayundin naman, ang kaharian ng langit ay tulad ng isang mangangalakal na naghahanap ng magagandang perlas;
At ipatawad mo sa amin ang aming mga kasalanan,
Nang siya'y makita nila ay nagtaka sila at sinabi sa kanya ng kanyang ina, “Anak, bakit ginawa mo sa amin ang ganito? Tingnan mo, ang iyong ama at ako ay naghahanap sa iyo na may pag-aalala.”
Ang pari ni Zeus na ang templo ay nasa harap ng lunsod ay nagdala ng mga baka at mga putong na bulaklak sa mga pintuang-daan, at ibig maghandog kasama ng napakaraming tao.
At nagmamadali siyang pumasok sa kinaroroonan ng hari at humiling na sinasabi, “Ibig kong ibigay mo sa akin ngayon din ang ulo ni Juan na Tagapagbautismo na nasa isang pinggan.”
ang pangangalunya, kasakiman, kasamaan, pandaraya, kahalayan, pagkainggit, paninirang-puri, kapalaluan, at kahangalan.
Tingnan ninyo, siya'y dumarating na nasa mga ulap;
Sapagkat ang mga ayon sa laman ay nagtutuon ng kanilang isipan sa mga bagay ng laman; subalit ang mga ayon sa Espiritu ay sa mga bagay ng Espiritu.
Ako ba'y naghahangad ngayon ng pagsang-ayon ng mga tao o ng Diyos? O sinisikap ko bang bigyang-lugod ang mga tao? Kung ako'y nagbibigay-lugod pa rin sa mga tao, hindi sana ako naging alipin ni Cristo.
Palibhasa'y wala siyang maibayad, ipinag-utos ng panginoon niya na siya'y ipagbili, pati ang kanyang asawa at mga anak, at ang lahat ng kanyang ari-arian upang sila'y makabayad.
Agad nabuksan ang kanyang mga tainga, nakalag ang tali ng kanyang dila, at siya'y nakapagsalita nang malinaw.
Gayundin naman kayong mga lalaki, maging mapagbigay kayo sa inyu-inyong mga asawa sa inyong pagsasama, na binibigyan ng karangalan ang babae bilang isang mas marupok na sisidlan, yamang sila man ay tagapagmana rin ng biyaya ng buhay, upang walang makahadlang sa inyong mga panalangin.
Dinala rin upang pataying kasama niya ang dalawang kriminal.
At sila'y natuwa at nagkasundong bigyan siya ng salapi.
Sinabi niya sa kanila, “Dahil sa katigasan ng inyong puso ay ipinahintulot sa inyo ni Moises na inyong hiwalayan ang inyong mga asawang babae; ngunit buhat sa pasimula ay hindi gayon.
At hindi lamang sangnilikha, kundi pati naman tayo na mayroong mga unang bunga ng Espiritu, na tayo nama'y dumaraing din sa ating mga sarili, sa masidhing paghihintay ng pagkukupkop, ang pagtubos sa ating katawan.
Hindi mabagal ang Panginoon tungkol sa kanyang pangako, na gaya ng kabagalang itinuturing ng iba, kundi matiyaga sa inyo, na hindi niya ibig na sinuman ay mapahamak, kundi ang lahat ay dumating sa pagsisisi.
Gayundin naman, kayong mga kabataan, pasakop kayo sa matatanda. At kayong lahat ay magsuot ng kapakumbabaan sa inyong pakikitungo sa isa't isa, sapagkat “Ang Diyos ay sumasalungat sa mga palalo, ngunit nagbibigay ng biyaya sa mga mapagpakumbaba.”
na ipinaalam niya sa atin ang hiwaga ng kanyang kalooban, ayon sa mabuting layunin na kanyang itinakda kay Cristo,
Ang inyong pagsunod ay naging bantog sa lahat ng mga tao, kaya't nagagalak ako tungkol sa inyo. Ngunit nais kong kayo'y maging marurunong sa kabutihan, at walang sala tungkol sa kasamaan.
Sapagkat sa ganang akin ang mabuhay ay si Cristo, at ang mamatay ay pakinabang.
Siya'y natagpuan nila, at sinabi sa kanya, “Hinahanap ka ng lahat.”
Hindi ko hinihiling na alisin mo sila sa sanlibutan, kundi ingatan mo sila mula sa masama.
Kaya't huwag ninyong paghariin ang kasalanan sa inyong katawang may kamatayan, upang masunod ang mga pagnanasa nito.
naging anak ni Zerubabel si Abiud; naging anak ni Abiud si Eliakim; at naging anak ni Eliakim si Azor;
Subalit sinabi niya sa akin, “Ang aking biyaya ay sapat na sa iyo, sapagkat ang aking kapangyarihan ay nagiging sakdal sa kahinaan.” Ako'y lalong magmamalaki na may galak sa aking kahinaan, upang ang kapangyarihan ni Cristo ay manatili sa akin.
Sumagot si Jesus, “Ang kaharian ko ay hindi mula sa sanlibutang ito. Kung ang kaharian ko ay mula sa sanlibutang ito, ang aking mga tauhan ay makikipaglaban sana upang ako'y huwag maibigay sa mga Judio; ngunit ang aking kaharian ay hindi mula rito.”
Kinabukasan siya ay tumuloy sa isang bayan na tinatawag na Nain, kasama ang kanyang mga alagad at ang napakaraming tao.
O sinong hari, na pupunta sa pakikidigma laban sa ibang hari, ang hindi muna uupo at mag-iisip kung siya na may sampung libo ay kayang humarap sa may dalawampung libo na dumarating laban sa kanya?
At ang mga nasa bato ay sila na pagkatapos makarinig ay tinanggap na may galak ang salita, subalit ang mga ito'y walang ugat; sila'y sumampalataya nang sandaling panahon lamang at sa panahon ng pagsubok ay tumalikod.
Ang kanila lamang hiniling ay aming alalahanin ang mga dukha, na siya namang aking pinananabikang gawin.
at ikinagagalak ko alang-alang sa inyo na ako'y wala roon, upang kayo'y sumampalataya. Gayunma'y tayo na sa kanya.”
At ang magandang balitang ito ng kaharian ay ipahahayag sa buong daigdig bilang patotoo sa lahat ng mga bansa; at pagkatapos ay darating ang wakas.
na naging pari, hindi ayon sa itinatakda ng batas na ukol sa laman, kundi ayon sa kapangyarihan ng isang buhay na hindi mapupuksa.
Kaya pumunta kayo sa mga pangunahing lansangan at anyayahan ninyo sa handaan ng kasalan ang sinumang makita ninyo.’
Ang ama at ina ng bata ay namangha sa mga bagay na sinasabi tungkol sa kanya.
Nang sumunod na araw, nagtipon sa Jerusalem ang kanilang mga pinuno, ang matatanda at ang mga eskriba;
Nang siya ay makita ng mga punong pari at ng mga punong-kawal, sila'y nagsigawan, “Ipako siya sa krus, ipako siya sa krus!” Sinabi sa kanila ni Pilato, “Kunin ninyo siya, at ipako ninyo siya sa krus, sapagkat ako'y walang nakitang kasalanan sa kanya.”
Ngunit, tungkol naman sa Anak ay sinasabi niya,
At ang lahat, ang hamak at ang dakila, ang mayayaman at ang mga dukha, ang mga malaya at ang mga alipin ay pinalagyan nito ng isang tanda sa kanilang kanang kamay o sa noo,
Siya'y sumigaw ng may malakas na tinig, “Ano ang pakialam mo sa akin, Jesus, Anak ng Kataas-taasang Diyos? Ipinapakiusap ko sa iyo, alang-alang sa Diyos, na huwag mo akong pahirapan.”
Sapagkat sa pamamagitan ng mga gawa ng kautusan ay “walang tao na ituturing na ganap sa paningin niya,” sapagkat sa pamamagitan ng kautusan ay ang pagkakilala ng kasalanan.
Sino kang humahatol sa alipin ng iba? Sa kanyang sariling panginoon siya ay tatayo o mabubuwal. Subalit siya'y patatayuin, sapagkat magagawa ng Panginoon na siya'y tumayo.
Maraming darating sa aking pangalan na magsasabi, ‘Ako siya!’ at maililigaw nila ang marami.
Nang siya'y maipahanap na ni Herodes at hindi siya natagpuan, siniyasat niya ang mga tanod at ipinag-utos na sila'y patayin.
Sapagkat ang Diyos ang nagsabi, “Magningning ang ilaw sa kadiliman,” na siyang tumatanglaw sa aming mga puso upang magbigay-liwanag sa pagkakilala sa kaluwalhatian ng Diyos sa mukha ni Jesu-Cristo.
“Kaya't ikaw ay aking pupurihin sa gitna ng mga Hentil, at aawit ako ng papuri sa iyong pangalan.”
at ang lupa ang tuntungan ng aking mga paa.
At mga ama, huwag ninyong ibunsod sa galit ang inyong mga anak, kundi akayin ninyo sila sa pagsasanay at pangaral ng Panginoon.
Samantala, si Saulo na may masidhing pagbabanta ng kamatayan laban sa mga alagad ng Panginoon ay pumunta sa pinakapunong pari.
at manumbalik sa akin, at sila'y aking pagalingin.’
Nalalaman nila mula pa nang una, kung handa silang magpatunay, na alinsunod sa pinakamahigpit na sekta ng aming relihiyon ay namuhay ako bilang isang Fariseo.
At kanyang tinawag siya, at sa kanya'y sinabi, ‘Ano itong nababalitaan ko tungkol sa iyo? Magbigay-sulit ka ng ipinagkatiwala sa iyo, sapagkat hindi ka na maaaring maging katiwala pa.’
Ngunit ang mga iba'y nanlilibak na nagsabi, “Sila'y lasing sa bagong alak.”
Kaya't kinalagan ang apat na anghel, na inihanda para sa oras, araw, buwan at taon upang patayin ang ikatlong bahagi ng mga tao.
Pagkatapos mangyari ang mga bagay na ito, ipinasiya ni Pablo sa Espiritu, na dumaan sa Macedonia at sa Acaia, at pumaroon sa Jerusalem, na sinasabi, “Pagkapanggaling ko roon, ay kinakailangang makita ko rin ang Roma.”
Umalis si Jesus doon at dumaan sa baybayin ng Dagat ng Galilea. Umakyat siya sa bundok at naupo roon.
Noo'y araw ng Paghahanda, at malapit na ang Sabbath.
Lumabas ang buong bayan upang salubungin si Jesus at pagkakita nila sa kanya, pinakiusapan nila siyang umalis sa kanilang nasasakupan.
sa ilalim ng iyong mga paa.”’
Nang kanilang mahalata na sinabi niya ang talinghagang ito laban sa kanila, pinagsikapan nilang hulihin siya, ngunit sila'y natakot sa maraming tao at siya'y iniwan nila at sila'y umalis.
Kaya't umalis ang mga alagad, nagpunta sa lunsod, at natagpuan ang lahat ayon sa sinabi niya sa kanila. Inihanda nila ang korderong pampaskuwa.
at ang mga naiwan ay sumunod, ang ilan ay sa ibabaw ng mga kahoy, at ang iba ay sa bahagi ng barko. Sa gayon ang lahat ay ligtas na nakarating sa lupa.
tungkol sa kanyang Anak na mula sa binhi ni David ayon sa laman
Ngayon, kalabisan na para sa akin na sulatan kayo tungkol sa paglilingkod para sa mga banal,
upang malaman mo ang katiyakan ng mga bagay na itinuro sa iyo.
Kaya, may dalawang taong pupunta sa bukid, ang isa'y kukunin, at ang isa'y iiwan.
Ibig ko sana na ang mga nanggugulo sa inyo ay kapunin nila ang kanilang sarili.
At lumapit din ang tumanggap ng dalawang talento at sinabi niya, ‘Panginoon, binigyan mo ako ng dalawang talento. Heto, ako'y nakinabang ng dalawa pang talento.’
“Sambahin siya ng lahat ng mga anghel ng Diyos.”
Nang kanilang tarukin ay nalamang dalawampung dipa; at pagkasulong ng kaunti ay tinarok nilang muli at nalamang may labinlimang dipa.
Sapagkat ito ang kalooban ng Diyos, ang inyong pagpapakabanal: na kayo'y umiiwas sa pakikiapid;
Nang masakop niya ang bawat bagay, wala siyang iniwan na hindi niya nasasakop. Ngunit ngayon ay hindi pa natin nakikitang nasasakop niya ang lahat ng mga bagay,
Nang matapos na ang kapistahan, sa pagbabalik nila ay nanatili ang batang si Jesus sa Jerusalem, ngunit hindi ito alam ng kanyang mga magulang.
Habang siya'y nakaupong kasalo nila sa hapag, kanyang dinampot ang tinapay at binasbasan. Ito'y kanyang pinagputul-putol at ibinigay sa kanila.
Pagkatapos ay umalis ang mga Fariseo at pinag-uusapan nila kung paano siyang mabibitag sa kanyang pananalita.
Pagkatapos ay nagpunta sila sa isang dako na tinatawag na Getsemani at sinabi niya sa kanyang mga alagad, “Maupo kayo rito habang ako'y nananalangin.”
Kaya't sinabi ni Jesus, “Hayaan ninyo siya. Inilaan niya ito sa araw ng paglilibing sa akin.
Mga munting anak, kayo'y sinusulatan ko
Tumindig ka, bumaba ka at sumama sa kanila na walang pag-aatubili sapagkat sila'y aking sinugo.”
upang aming maipangaral ang ebanghelyo sa mga lupain sa dako pa roon ng lupain ninyo, na hindi nagmamalaki sa mga gawang natapos na sa nasasakupan ng iba.
Sa araw na iyon, ang nasa bubungan na ang pag-aari niya ay nasa bahay, ay huwag nang manaog upang kunin ang mga ito. Gayundin, ang nasa bukid ay huwag nang bumalik.
Ang gayunding bagay ay nangyari din sa Iconio, na doon sina Pablo at Bernabe ay magkasamang pumasok sa sinagoga ng mga Judio, at nagsalita ng gayon na sumampalataya ang marami sa mga Judio at sa mga Griyego.
Siya mismo ay una sa lahat ng mga bagay, at ang lahat ng mga bagay ay nahahawakang sama-sama sa kanya.
Nang sumunod na araw ay dumating sila sa Cesarea. Sila'y hinihintay ni Cornelio, at tinipon ang kanyang mga kamag-anak at ang kanyang malalapit na kaibigan.
Ako'y hindi naging pasanin sa inyo; gayunman sabi ninyo, yamang ako ay tuso, napaglalangan ko kayo sa pamamagitan ng daya.
Ngunit hindi siya sumagot sa kanya kahit isang salita. Lumapit ang kanyang mga alagad at nakiusap sa kanya, na nagsasabi, “Paalisin mo siya, sapagkat nagsisisigaw siya at sumusunod sa hulihan natin.”
Gayundin naman, nararapat ibigin ng mga asawang lalaki ang kanya-kanyang sariling asawa gaya ng kanilang sariling mga katawan. Ang umiibig sa kanyang sariling asawa ay umiibig sa kanyang sarili.
May taong nagpapahalaga sa isang araw nang higit kaysa iba, ngunit may iba namang nagpapahalaga sa bawat araw. Hayaang mapanatag ang bawat tao sa kanyang sariling pag-iisip.
Ngunit palibhasa'y alam ni Jesus ang kanilang mga iniisip ay sinabi niya, “Bakit nag-iisip kayo sa inyong mga puso ng masama?
Nang magkagayo'y isinama ni Pablo ang mga lalaking iyon. Nang sumunod na araw, pagkatapos malinis ang kanyang sarili, pumasok siya sa templo upang ipahayag kung kailan magaganap ang mga araw ng paglilinis, at ang pag-aalay ng handog para sa bawat isa sa kanila.
sapagkat hindi ito pumapasok sa kanyang puso kundi sa tiyan, at ito'y inilalabas sa tapunan ng dumi? Sa ganito'y nililinis niya ang lahat ng pagkain.”
na siyang sa atin ay nagligtas at sa atin ay tumawag ng isang banal na pagtawag, hindi ayon sa ating mga gawa, kundi ayon sa kanyang sariling layunin at biyaya. Ang biyayang ito ay ibinigay sa atin kay Cristo Jesus bago pa nagsimula ang mga panahon,
Sapagkat siya'y nagpagaling ng marami, siniksik siya ng lahat ng maysakit upang siya'y mahipo.
Kaya't sinumang sumuway sa isa sa pinakamaliit sa mga utos na ito, at magturo nang gayon sa mga tao ay tatawaging pinakamaliit sa kaharian ng langit; ngunit ang sinumang tumupad at magturo ng mga ito ay tatawaging dakila sa kaharian ng langit.
Sapagkat habang nabubuhay, kami ay laging ibinibigay sa kamatayan dahil kay Jesus, upang ang buhay ni Jesus ay mahayag sa aming laman na may kamatayan.
Nang bumaba si Jesus mula sa bundok, sinundan siya ng napakaraming tao;
Ngunit siya'y hindi Diyos ng mga patay, kundi ng mga buháy, sapagkat sa kanya silang lahat ay nabubuhay.”
Sa gayon, si Jesus ay naging tagapanagot ng isang higit na mabuting tipan.
Kapag ang babae ay nanganganak, siya ay nahihirapan sapagkat dumating na ang kanyang oras. Ngunit pagkapanganak niya sa sanggol ay hindi na niya naaalala ang hirap dahil sa kagalakan sa pagkapanganak sa isang tao sa sanlibutan.
Nang magtatanghaling-tapat na, nagdilim sa ibabaw ng buong lupain hanggang sa ikatlo ng hapon,
Kaya't magsikap tayong pumasok sa kapahingahang iyon, upang huwag mabuwal ang sinuman sa pamamagitan ng gayong halimbawa ng pagsuway.
Kaya't dumating ang mga kawal at binali ang binti ng una at ng isa pa na ipinako sa krus na kasama niya.
Ito ang alagad na nagpapatotoo sa mga bagay na ito at ang sumulat ng mga ito; at nalalaman namin na ang kanyang patotoo ay tunay.
at sa harapan ng trono, ay may parang isang dagat na salamin na katulad ng kristal. At sa gitna ng trono, at sa palibot ng trono ay may apat na nilalang na buháy na punô ng mga mata sa harapan at sa likuran.
Ang reyna ng Timog ay babangon sa paghuhukom kasama ang mga tao ng lahing ito at kanyang hahatulan sila. Sapagkat siya'y dumating galing sa mga dulo ng daigdig upang makinig sa karunungan ni Solomon, at narito ang isang higit pang dakila kaysa kay Solomon.
Mula roon, siya'y umalis at pumunta sa lupain ng Judea at sa kabila ng Jordan. At muling nagtipon ang napakaraming tao sa paligid niya at tulad ng kanyang nakaugalian, muli niyang tinuruan sila.
“Kaya't naglakbay ako patungo sa Damasco na taglay ang awtoridad at pahintulot ng mga punong pari.
na ipinain ang kanilang leeg para sa aking buhay, sa kanila'y hindi lamang ako ang nagpapasalamat, kundi pati ang lahat ng mga iglesya ng mga Hentil.
Si David mismo ang nagpahayag sa pamamagitan ng Espiritu Santo,
Sinulatan kita na may pagtitiwala sa iyong pagsunod, yamang nalalaman ko na gagawin mo ang higit pa kaysa aking sinasabi.
“Amen. Aleluia!”
Kung ako nga, na Panginoon at Guro ay naghugas ng inyong mga paa, kayo man ay dapat ding maghugas ng mga paa ng isa't isa.
At siya'y inilayo niya ng bukod mula sa maraming tao at isinuot ang kanyang mga daliri sa kanyang mga tainga. Siya'y dumura at hinipo ang kanyang dila.
Siya'y pumasok at nagdaan sa Jerico,
Yamang siya'y isang propeta at nalalaman niyang nangako ang Diyos sa kanya na ang isa sa kanyang mga inapo ay iluluklok niya sa kanyang trono.
kasama niya si Onesimo, tapat at minamahal na kapatid, na siya'y isa sa inyo. Sila ang magbabalita sa inyo tungkol sa lahat ng mga bagay na nangyayari dito.
Si Simon Pedro, alipin at apostol ni Jesu-Cristo,
Kung ang sinuman ay patungo sa pagkabihag, sa pagkabihag siya patutungo. Kung ang sinuman ay pumapatay sa pamamagitan ng tabak, sa pamamagitan ng tabak siya dapat papatayin. Ito ay panawagan para sa pagtitiis at pananampalataya ng mga banal.
na dumarating sa pangalan ng Panginoon!
Sa kanyang paglalakbay, dumating siya sa malapit sa Damasco, biglang kumislap sa palibot niya ang isang liwanag mula sa langit.
Nang makalipas ang maraming araw, nagbalak ang mga Judiong siya'y patayin.
Nais kong dalawin kayo sa aking paglalakbay patungong Macedonia, at buhat sa Macedonia ay bumalik sa inyo, at nang matulungan ninyo ako sa aking paglalakbay patungong Judea.
Kaya't kanilang kinuha siya, itinapon sa labas ng ubasan, at pinatay.
Nang makita niya ang napakaraming tao, nahabag siya sa kanila, sapagkat sila ay nangangamba at nanlulupaypay na gaya ng mga tupa na walang pastol.
At siya'y dumampot ng tinapay, at nang siya'y makapagpasalamat, kanyang pinagputul-putol, at ibinigay sa kanila, na sinasabi, “Ito'y aking katawan na ibinibigay dahil sa inyo. Gawin ninyo ito sa pag-aalaala sa akin.”
Sapagkat bagaman ako ay nagmamalaki ng labis tungkol sa aming kapamahalaan na ibinigay ng Panginoon upang kayo ay patatagin at hindi upang kayo ay gibain, ako ay hindi mapapahiya,
Kung kayo'y magpahiram lamang sa mga taong mayroon kayong inaasahang tatanggapin, ano ang mapapala ninyo? Ang mga makasalanan man ay nagpapahiram sa mga makasalanan, upang tanggapin nilang muli ang gayunding halaga.
Marami ang pumunta sa kanya at kanilang sinabi, “Si Juan ay hindi gumawa ng tanda, ngunit lahat ng mga bagay na sinabi ni Juan tungkol sa taong ito ay totoo.”
Ang aming bibig ay bukas para sa inyo, mga taga-Corinto, ang aming puso ay pinalawak.
Sila ay nagtaka, namangha at nagsabi, “Tingnan ninyo, hindi ba mga taga-Galilea ang lahat ng mga nagsasalitang ito?
baka masaktan mo ang iyong paa sa isang bato.’
Tayong lahat ay dating nabuhay sa gitna ng mga ito, sa mga pagnanasa ng laman, na ating ginagawa ang mga nais ng laman at ng pag-iisip, at tayo noo'y katutubong mga anak ng kapootan, gaya naman ng mga iba.
Dapat silang gumawa ng mabuti, maging mayaman sa mabubuting gawa, bukas ang palad at handang mamahagi,
Samantalang papunta kami sa dakong panalanginan, sinalubong kami ng isang aliping batang babae na may espiritu ng panghuhula at nagdadala ng maraming pakinabang sa kanyang mga amo sa pamamagitan ng panghuhula.
Kaya, maging matiyaga kayo, mga kapatid, hanggang sa pagdating ng Panginoon. Hinihintay ng magsasaka ang mahalagang bunga ng lupa, na siya'y nagtitiis para dito hanggang sa ito ay tumanggap ng una at huling ulan.
Kinuha nila si Jesus, at siya'y lumabas na pasan niya ang krus, patungo sa tinatawag na Pook ng Bungo, na sa wikang Hebreo ay tinatawag na Golgota.
sapagkat ako'y hinirang niya upang ipangaral ang magandang balita sa mga dukha.
Nang magampanan na nila ang lahat ng mga bagay ayon sa kautusan ng Panginoon, bumalik sila sa Galilea, sa kanilang sariling bayang Nazaret.
Kung tayo'y nabubuhay sa pamamagitan ng Espiritu, lumakad din tayo sa patnubay ng Espiritu.
Ang langit at ang lupa ay lilipas, subalit ang aking salita ay hindi lilipas.
Lahat ng kalikuan ay kasalanan, at may kasalanang hindi tungo sa kamatayan.
at ang kanilang salita ay kakalat na gaya ng ganggrena. Kasama sa mga ito si Himeneo at si Fileto,
“Subalit sinasabi ko sa inyo na mga nakikinig, Ibigin ninyo ang inyong mga kaaway, gawan ninyo ng mabuti ang mga napopoot sa inyo,
Nang makarating sila sa bahay ng pinuno ng sinagoga, nakita niya ang pagkakagulo, ang mga pagtangis at malakas na iyakan.
At ikaw, Capernaum, itataas ka ba hanggang sa langit? Ibababa ka hanggang sa Hades. Sapagkat kung sa Sodoma ginawa ang mga makapangyarihang gawa na ginawa sa iyo, nanatili sana iyon hanggang sa araw na ito.
Sumainyo nawang espiritu ang biyaya ng Panginoong Jesu-Cristo.
Punuin nga ninyo ang takalan ng inyong mga magulang.
“Ilalagak ko ang aking pagtitiwala sa kanya.”
At sinabi ng Panginoon, “Pakinggan ninyo ang sinabi ng masamang hukom.
Subalit tinatawagan ko ang Diyos upang sumaksi laban sa akin; upang hindi kayo madamay, hindi na ako muling pumunta sa Corinto.
Iutos at ituro mo ang mga bagay na ito.
Kung paanong si Abraham ay sumampalataya sa Diyos, at ito'y ibinilang sa kanya na katuwiran.
Pagkatapos na muling bigyan ng babala, kanilang hinayaan silang umalis na walang nakitang anumang bagay upang sila'y kanilang maparusahan dahil sa mga tao, sapagkat niluluwalhati nilang lahat ang Diyos dahil sa nangyari.
gaya ng pagkadurog ng mga palayok,
“Kapag dumating na ang Anak ng Tao na nasa kanyang kaluwalhatian, na kasama niya ang lahat ng mga anghel, siya'y uupo sa trono ng kanyang kaluwalhatian.
na inyong tinatanggap ang bunga ng inyong pananampalataya, ang kaligtasan ng inyong mga kaluluwa.
Itong si Melquizedek, hari ng Salem, pari ng Kataas-taasang Diyos, ang siyang sumalubong kay Abraham sa pagbabalik niya galing sa paglipol sa mga hari at siya'y kanyang binasbasan,
“Aleluia!
Kaya nang dumating sa kanya ang mga Samaritano, nakiusap sila sa kanya na manatili sa kanila; at siya'y nanatili roon ng dalawang araw.
Haring Agripa, naniniwala ka ba sa mga propeta? Nalalaman kong naniniwala ka.”
Sapagkat sa isang dako ay sinabi niya ang ganito tungkol sa ikapitong araw, “At nagpahinga ang Diyos nang ikapitong araw sa lahat ng kanyang mga gawa.”
kundi nang siya'y nagpaalam sa kanila, ay sinabi, “Babalik uli ako sa inyo kung loloobin ng Diyos.” At siya'y naglakbay buhat sa Efeso.
Makipagtiis ka ng mga kahirapan, gaya ng mabuting kawal ni Cristo Jesus.
Sapagkat ang buong kautusan ay natutupad sa isang pangungusap, “Ibigin mo ang iyong kapwa na gaya ng iyong sarili.”
Naging anak ni Abraham si Isaac; naging anak ni Isaac si Jacob; at naging anak ni Jacob si Juda at ang mga kapatid nito;
Kayo nga'y mga saksi at sumang-ayon sa mga gawa ng inyong mga ninuno, sapagkat pinatay nila ang mga propeta at itinayo ninyo ang kanilang mga libingan.
Nang sama-samang lumapit sa kanya ang mga Fariseo at ang ilan sa mga eskriba na nanggaling sa Jerusalem,
Ang taong ito'y lumapit kay Pilato at hiningi ang bangkay ni Jesus.
Mula nang oras na ikaanim ay nagdilim sa buong lupain hanggang sa oras na ikasiyam.
Kaya't ang kautusan ay naging ating tagasupil hanggang sa dumating si Cristo, upang tayo'y ariing-ganap sa pamamagitan ng pananampalataya.
Nang makita niya ang kanilang pananampalataya ay sinabi niya, “Lalaki, pinatatawad ka na sa iyong mga kasalanan.”
Kung paanong pumasok siya sa bahay ng Diyos, noong si Abiatar ang pinakapunong pari at kumain siya ng tinapay ng paghahandog, na hindi ipinahihintulot kainin maliban ng mga pari lamang at binigyan pa niya ang kanyang mga kasamahan?”
“Si Claudio Lisias sa kagalang-galang na gobernador Felix, ay bumabati.
Subalit ngayong pinalaya na kayo sa kasalanan at naging mga alipin ng Diyos, na nagbubunga naman ng kabanalan, ang kahihinatnan ay buhay na walang hanggan.
Ang maraming tao ay sama-samang tumindig laban sa kanila; at pinunit ng mga hukom ang mga damit nina Pablo at Silas, at ipinag-utos na hagupitin sila.
Sinabi nila sa kanya, “Kay Cesar.” Pagkatapos ay sinabi niya sa kanila, “Kaya't ibigay ninyo kay Cesar ang kay Cesar at sa Diyos ang sa Diyos.”
Muli niyang pinalapit ang maraming tao at sinabi sa kanila, “Makinig kayong lahat sa akin at inyong unawain.
At sinabi niya sa kanila, “Humayo kayo at inyong sabihin sa asong-gubat na iyon, ‘Narito, nagpapalayas ako ng mga demonyo at nagpapagaling ngayon at bukas, at sa ikatlong araw ay matatapos ko ang aking gawain.
Sumagot siya sa kanila, “Sino ang aking ina at ang aking mga kapatid?”
hanggang sa gawin ko ang mga kaaway mo na tuntungan ng iyong mga paa.”’
Sapagkat dahil dito si Cristo ay namatay at muling nabuhay, upang siya'y maging Panginoon ng mga patay at gayundin ng mga buháy.
At si Crispo, ang pinuno sa sinagoga ay nanampalataya sa Panginoon, kasama ang kanyang buong sambahayan; at marami sa mga taga-Corinto dahil sa pakikinig kay Pablo ay nanampalataya at nabautismuhan.
Sapagkat nabatid niya na dahil sa inggit ay kanilang ibinigay si Jesus sa kanya.
Isang araw, sina Pedro at Juan ay pumanhik sa templo sa oras ng pananalangin, nang ikasiyam na oras.
Nang hindi sumikat sa amin ang araw ni ang mga bituin man nang maraming araw, at humahampas pa rin sa amin ang isang malakas na bagyo, nawala ang buong pag-asa naming makakaligtas.
Tingnan mo nga ang kabaitan at ang kabagsikan ng Diyos: sa mga nahulog ay kabagsikan, ngunit sa iyo ay ang kabaitan ng Diyos kung mananatili ka sa kanyang kabaitan; kung hindi, ikaw man ay puputulin.
Subalit ngayo'y nagtamo si Cristo ng ministeryong higit na marangal, yamang siya'y tagapamagitan sa isang higit na mabuting tipan na pinagtibay sa higit na mabubuting pangako.
Ngunit hindi pa ako mukhaang nakikilala sa mga iglesya ng Judea na kay Cristo.
ayon sa ipinaalam sa atin ng mga taong buhat sa pasimula ay mga saksing nakakita at mga tagapangaral ng salita,
at hindi nila nalalaman hanggang sa dumating ang baha, at tinangay silang lahat, ay gayundin naman ang pagdating ng Anak ng Tao.
Siya ay pumunta kay Jesus nang gabi na, at sinabi sa kanya, “Rabi, nalalaman naming ikaw ay isang guro na mula sa Diyos; sapagkat walang makakagawa ng mga tanda na iyong ginagawa, malibang kasama niya ang Diyos.”
Mapalad ang taong nagtitiis ng pagsubok, sapagkat kapag siya ay subok na, siya'y tatanggap ng putong ng buhay, na ipinangako ng Panginoon sa mga nagmamahal sa kanya.
Nalalaman natin na ang ating dating pagkatao ay kasama niyang ipinako sa krus, upang ang katawang makasalanan ay mawalan ng bisa, at upang tayo'y hindi na magpaalipin pa sa kasalanan;
Kung ang sinuman ay may taingang ipandirinig, hayaan siyang makinig.”
Subalit ang lahat ng mga bagay na ito ay gagawin nila sa inyo dahil sa aking pangalan, sapagkat hindi nila nakikilala ang nagsugo sa akin.
Subalit ang lahat ng tumanggap sa kanya na sumasampalataya sa kanyang pangalan ay kanyang pinagkalooban sila ng karapatan na maging mga anak ng Diyos,
Ako'y mayroong bautismo na ibabautismo sa akin, at ako'y nababagabag hanggang hindi ito nagaganap!
At hindi ba bibigyan ng Diyos ng katarungan ang kanyang mga pinili na sumisigaw sa kanya araw at gabi. Kanya bang matitiis sila?
at ang kaharian ng ating Diyos,
Ito'y sinabi niya upang siya'y subukin sapagkat nalalaman niya sa kanyang sarili kung ano ang gagawin niya.
Samantalang siya'y nakaupo sa liwanag ng apoy, nakita siya ng isang alilang babae, tumitig sa kanya at nagsabi, “Ang taong ito ay kasama rin niya.”
Nang dumating si Jesus sa nasasakupan ng Cesarea Filipos, tinanong niya ang kanyang mga alagad, na sinasabi, “Ano ba ang sinasabi ng mga tao kung sino ang Anak ng Tao?”
Sapagkat itinalaga ang bawat pinakapunong pari upang maghandog ng mga kaloob at ng mga alay. Kaya't kailangan din namang siya'y magkaroon ng kanyang ihahandog.
na ang mga ito ay isang anino ng mga bagay na darating, ngunit ang katawan ay kay Cristo.
At isa sa kanila, na tagapagtanggol ng kautusan, ay nagtanong sa kanya upang siya'y subukin.
Kaya't alalahanin mo kung paano mo ito tinanggap at narinig; tuparin mo ito at magsisi ka. Kaya't kung hindi ka gigising, darating akong gaya ng magnanakaw, at hindi mo malalaman kung anong oras ako darating sa iyo.
Pagkatapos na siya'y makatigil sa kanila nang hindi hihigit sa walo o sampung araw, ay pumunta siya sa Cesarea, at nang sumunod na araw ay umupo siya sa hukuman, at iniutos na dalhin si Pablo.
Kaya't nagalit ako sa lahing ito,
Ito ay malinaw na katibayan ng matuwid na paghatol ng Diyos, upang kayo'y ariing karapat-dapat sa kaharian ng Diyos, na dahil dito'y nagdurusa kayo.
isang batong panulok na pinili at mahalaga;
Sapagkat maghihimagsik ang bansa laban sa bansa at ang kaharian laban sa kaharian; at lilindol sa iba't ibang dako; magkakaroon ng taggutom. Ang mga ito'y pasimula lamang ng paghihirap.
Sinabi ni Jesus sa kanila, “Mga anak, mayroon ba kayong nahuling isda?” Sumagot sila sa kanya, “Wala.”
“Kahabag-habag kayo kapag ang lahat ng mga tao ay nagsasabi ng mabuti tungkol sa inyo, sapagkat gayundin ang ginawa ng kanilang mga ninuno sa mga bulaang propeta.
At mula noon ay humanap siya ng pagkakataon na maipagkanulo si Jesus.
Ang mga may pandinig ay makinig.”
na doon ay tinukso siya ng diyablo sa loob ng apatnapung araw. Hindi siya kumain ng anuman sa mga araw na iyon, at nang makalipas ang mga araw na iyon ay nagutom siya.
upang aking makamit sa anumang paraan ang muling pagkabuhay mula sa mga patay.
At kayo, na nang dati ay hiwalay at mga kaaway sa pag-iisip, sa pamamagitan ng masasamang gawa,
Kaya't umupo sila nang pangkat-pangkat, nang tig-iisandaan at tiglilimampu.
At sinabi niya, “Tinupad ko ang lahat ng mga bagay na ito buhat pa sa aking pagkabata.”
At ang nauuhaw ay pumarito,
Umakyat sila sa malawak na lupa at pinaligiran ang kampo ng mga banal, at ang lunsod na minamahal; ngunit bumaba ang apoy mula sa langit, at sila'y natupok.
Kaya't ang bukid na iyon ay tinawag na Bukid ng Dugo hanggang sa araw na ito.
Sapagkat ibig kong malaman ninyo kung gaano kalaki ang aking pagsisikap alang-alang sa inyo, at sa mga nasa Laodicea, at sa lahat na hindi pa nakakita sa akin nang mukhaan.
doon sila tatawaging ‘mga anak ng Diyos na buháy.’”
Ang mga panahon ng kahangalan ay pinalampas na nga ng Diyos; ngunit ngayo'y ipinag-uutos niya sa lahat ng tao sa lahat ng dako na magsisi,
Subalit sa pagnanais niya na ipagmatuwid ang kanyang sarili ay sinabi kay Jesus, “At sino ang aking kapwa?”
At ang utos na ito na mula sa kanya ay nasa atin, na ang umiibig sa Diyos ay dapat ding umibig sa kanyang kapatid.
At sinabi ng mga nakarinig nito, “Sino kaya ang maliligtas?”
Subalit ibinilanggo ng kasulatan ang lahat ng mga bagay sa ilalim ng kasalanan, upang ang ipinangako sa pamamagitan ng pananampalataya kay Jesu-Cristo ay maibigay sa mga sumasampalataya.
hinatulan niya ang tanyag na mahalay na babae
Kayo'y mga saksi ng mga bagay na ito.
Nais kong makaharap kayo ngayon at baguhin ang aking tono, sapagkat ako'y nag-aalinlangan tungkol sa inyo.
Tingnan ninyo, ang sahod ng mga manggagawa na gumapas sa inyong mga bukid na inyong ipinagkakait ay umiiyak; at ang pag-iyak ng mga umani ay nakarating sa pandinig ng Panginoon ng mga hukbo.
“Nang umakyat siya sa itaas ay dinala niyang bihag ang pagkabihag,
Nang marinig nila ito, sila'y nagalak at nangakong siya'y bibigyan ng salapi. Kaya't naghanap siya ng pagkakataong maipagkanulo siya.
Sila'y lumapit kay Juan, at sa kanya'y sinabi, “Rabi, iyong kasama mo sa kabila ng Jordan na iyong pinatotohanan ay nagbabautismo at ang lahat ay lumalapit sa kanya.”
At sinabi niya sa akin, ‘Humayo ka, sapagkat susuguin kita sa malayo sa mga Hentil.’”
Sinabi ni Jesus sa kanila, “Itinatanong ko sa inyo, ipinahihintulot ba sa kautusan na gumawa ng mabuti, o gumawa ng masama kung Sabbath? Magligtas ng buhay o pumuksa nito?”
[
At kakilakilabot ang nakikita kaya't sinabi ni Moises, “Ako'y natatakot at nanginginig.”
At itinaas ng anghel na aking nakita na nakatayo sa dagat at sa lupa ang kanyang kanang kamay sa langit,
kundi kung paanong kami'y minarapat ng Diyos na pagkatiwalaan ng ebanghelyo ay gayon kami nagsasalita, hindi upang bigyang-lugod ang mga tao, kundi ang Diyos na sumusuri sa aming mga puso.
At ang dila'y isang apoy. Ang dila na kasama ng ating mga sangkap ay isang sanlibutan ng kasamaan. Dinudungisan nito ang buong katawan, at sinusunog ang pag-inog ng kalikasan, at ito mismo ay sinusunog ng impiyerno.
Sapagkat bihirang mangyari na ang isang tao'y mamatay alang-alang sa isang taong matuwid; bagama't alang-alang sa isang mabuting tao marahil ay may mangangahas mamatay.
Pagkatapos ay lumapit nang sarilinan ang mga alagad kay Jesus at sinabi nila, “Bakit hindi namin iyon napalayas?”
iwan mo roon sa harap ng dambana ang kaloob mo, at humayo ka; makipagkasundo ka muna sa iyong kapatid, at saka ka magbalik at maghandog ng iyong kaloob.
“Mag-ingat kayo sa mga eskriba na nagnanais lumakad na may mahahabang damit, at gustung-gusto ang mga pagpupugay sa mga pamilihan, ang pangunahing upuan sa mga sinagoga, at ang mga mararangal na lugar sa mga handaan.
At hinipan ng ikalimang anghel ang kanyang trumpeta at nakita ko ang isang bituin na nahulog sa lupa mula sa langit at sa kanya'y ibinigay ang susi ng hukay ng di-matarok na kalaliman.
Ngunit tumanggi siya at sinabi sa kanya, “Umuwi ka sa iyong mga kaibigan at ibalita mo sa kanila ang lahat ng ginawa ng Panginoon para sa iyo at kung paanong kinaawaan ka niya.”
“Huwag humipo, huwag tumikim, huwag humawak”?
Si Judas, na alipin ni Jesu-Cristo at kapatid ni Santiago, sa mga tinawag, na minamahal ng Diyos Ama, at iniingatan para kay Jesu-Cristo:
Bagaman ang aking kalagayan ay naging isang pagsubok sa inyo, hindi ninyo ako hinamak o kinasuklaman kundi tinanggap na gaya sa isang anghel ng Diyos, gaya ni Cristo Jesus.
Kaya't lagi kong hinahangad na ipaalala sa inyo ang mga bagay na ito, bagama't inyong nalalaman na, at kayo'y pinapatibay sa katotohanang dumating sa inyo.
Bilang mga hinirang ng Diyos, mga banal at minamahal, magbihis kayo ng kahabagan, ng kabaitan, ng kababaang-loob, ng kaamuan, at ng katiyagaan.
Pagmasdan natin si Jesus na siyang nagtatag at nagpasakdal ng ating pananampalataya, na dahil sa kagalakang inilagay sa kanyang harapan ay tiniis niya ang krus, hindi inalintana ang kahihiyan, at siya'y umupo sa kanan ng trono ng Diyos.
at ang lahat ng mga kapatid na kasama ko,
Sinabi niya sa kanila, “Anong mga bagay?” At sinabi nila sa kanya, “Tungkol kay Jesus na taga-Nazaret, na isang propetang makapangyarihan sa gawa at sa salita sa harap ng Diyos at ng buong sambayanan,
Binautismuhan ko kayo sa tubig, ngunit kayo'y babautismuhan niya sa Espiritu Santo.”
Ang mga alipin at ang mga punong-kawal ay nagpapaningas ng siga sapagkat maginaw. Sila'y nakatayo roon at nagpapainit. Si Pedro ay kasama rin nila na nakatayo at nagpapainit.
upang magpatalang kasama ni Maria na kanyang magiging asawa, na noon ay malapit nang manganak.
Ipinagbilin niya sa kanya na huwag sabihin kaninuman. “Humayo ka, magpakita ka sa pari, at maghandog ka ayon sa iniutos ni Moises dahil ikaw ay naging malinis, bilang patotoo sa kanila.”
“At kung ang sinuman ay magbigay ng katitisuran sa isa sa maliliit na ito na sumasampalataya sa akin, mabuti pang bitinan ang kanyang leeg ng isang malaking gilingang bato at itapon sa dagat.
Subalit sinabi ni Jesus sa kanya, “May isang naghanda ng isang malaking hapunan; at marami siyang inanyayahan.
Siya'y kanilang ipinako sa krus, at pinaghati-hatian ang kanyang mga damit na kanilang pinagsapalaran, kung alin ang kukunin ng bawat isa.
“Ang mata ang ilawan ng katawan: Kung tapat ang iyong mata, ang buong katawan mo'y mapupuno ng liwanag.
Ngunit nang malugod ang Diyos na sa akin ay nagbukod, buhat pa sa sinapupunan ng aking ina, at sa akin ay tumawag sa pamamagitan ng kanyang biyaya,
Pagkatapos ay iniwan ni Jesus ang napakaraming tao at pumasok sa bahay. Lumapit sa kanya ang kanyang mga alagad, na nagsasabi, “Ipaliwanag mo sa amin ang talinghaga ng mga damo sa bukid.”
At pagdating nito ay natagpuan nitong nawalisan at maayos na.
Lumapit siya at hinawakan ang babae sa kamay at siya'y ibinangon. Nawala ang kanyang lagnat at siya'y naglingkod sa kanila.
Ngunit nang paligiran siya ng mga alagad, tumayo siya at pumasok sa lunsod. Kinabukasan, umalis siya kasama ni Bernabe patungo sa Derbe.
Sinabi kay Pedro ng babaing tanod sa pinto, “Hindi ba ikaw ay isa sa mga alagad ng taong ito?” Sinabi niya, “Hindi.”
Sinabi sa kanya ni Pedro, “Aeneas, pinapagaling ka ni Jesu-Cristo; bumangon ka, at ayusin mo ang iyong higaan.” Agad naman siyang bumangon.
Kaya ako'y natakot at ako'y umalis at itinago ko sa lupa ang talento mo. Heto, iyo na ang sa iyo.’
Sapagkat siya na makapangyarihan ay gumawa para sa akin ng mga dakilang bagay
Mapalad ang sinumang hindi natitisod sa akin.”
Habang siya'y papunta, sinalubong siya ng kanyang mga alipin na nagsasabing ang kanyang anak ay ligtas na.
Nang masabi ni Jesus ang mga salitang ito, siya'y umalis na kasama ng kanyang mga alagad na tumawid sa libis ng Cedron, patungo sa isang pook na may isang halamanan, na pinasok niya at ng kanyang mga alagad.
Sa harapan ng Diyos at ni Cristo Jesus, na siyang hahatol sa mga buháy at sa mga patay, at sa pamamagitan ng kanyang pagpapakita at sa kanyang kaharian, ay inaatasan kita:
sapagkat tinanggap na ninyo ang inyong kaaliwan.
At nakita ko ang isang makapangyarihang anghel na nagpapahayag sa malakas na tinig, “Sino ang karapat-dapat magbukas ng aklat at magtanggal ng mga tatak nito?”
At alam natin na naparito ang Anak ng Diyos at binigyan niya tayo ng pagkaunawa upang ating makilala siya na totoo; at tayo'y nasa kanya na totoo, sa kanyang Anak na si Jesu-Cristo. Ito ang tunay na Diyos, at buhay na walang hanggan.
Tunay na tinatawag nating mapapalad ang mga nagtiis. Narinig ninyo ang tungkol sa pagtitiis ni Job, at inyong nakita ang layunin ng Panginoon, kung paanong ang Panginoon ay punô ng pagkahabag at pagkamaawain.
at makaunawa ang puso nila,
Sapagkat hindi ang mga tagapakinig ng kautusan ang siyang ganap sa harapan ng Diyos, kundi ang tumutupad sa kautusan ay aariing-ganap.
At ito ay hindi tulad sa aming inaasahan, kundi ibinigay muna nila ang kanilang sarili sa Panginoon, at sa amin sa pamamagitan ng kalooban ng Diyos.
Lumalaki ang mga alon sa dagat dahil sa malakas na hanging humihihip.
Pagkatapos ay tinawag ni Jesus ang kanyang mga alagad, at sinabi, “Nahahabag ako sa napakaraming taong ito, sapagkat tatlong araw na silang sumasama sa akin at wala silang makain; at hindi ko nais na paalisin silang gutom, baka himatayin sila sa daan.”
Magkaisa kayo ng pag-iisip. Huwag ninyong ituon ang inyong pag-iisip sa mga palalong bagay, kundi makiayon kayo sa mga bagay na may kapakumbabaan. Huwag kayong magmagaling sa inyong mga sarili.
Sinabi niya sa tagapag-alaga ng ubasan, ‘Tingnan ninyo, tatlong taon na akong pumaparito na humahanap ng bunga sa punong igos na ito, at wala akong makita. Putulin mo ito. Bakit sinasayang nito ang lupa?’
Ang isa sa dalawang nakarinig ng pagsasalita ni Juan, at sumunod sa kanya, ay si Andres na kapatid ni Simon Pedro.
Ibig ko ngang ang mga lalaki ay manalangin sa bawat dako, na itinataas ang kanilang mga banal na kamay na walang galit at pag-aalinlangan.
At sinabi nila sa kanila ang sinabi ni Jesus at kanilang pinayagan sila.
‘Ang batong itinakuwil ng mga tagapagtayo
Kaya't maging handa kayo, sapagkat hindi ninyo nalalaman kung kailan darating ang panginoon ng bahay, kung sa gabi, sa hatinggabi, sa pagtilaok ng manok, o sa umaga.
Ngunit sa lahat ng mga bagay na ito, tayo'y higit pa sa mga nagtatagumpay sa pamamagitan niya na sa atin ay umibig.
Tinanong siya ni Pilato, “Ikaw ba ang Hari ng mga Judio?” Sumagot siya sa kanya, “Ikaw ang nagsasabi.”
Nang malaman ni Herodes na siya'y dinaya ng mga Pantas, siya ay labis na nagalit. At ipinag-utos niyang patayin ang lahat ng mga batang lalaki sa Bethlehem at sa karatig-pook na may gulang na dalawang taon pababa, ayon sa panahon na kanyang tiniyak mula sa mga Pantas.
Sumagot si Jesus at sinabi sa kanila, “Katotohanang sinasabi ko sa inyo, kung kayo'y may pananampalataya at hindi nag-aalinlangan, hindi lamang ninyo magagawa ang nagawa sa puno ng igos, kundi kahit sabihin ninyo sa bundok na ito, ‘Maalis ka at mapatapon sa dagat,’ ito ay mangyayari.
Kaya't si Abraham, nang makapaghintay na may pagtitiis, ay tumanggap ng pangako.
At nang makita ni Jesus na dumarating na sama-samang tumatakbo ang maraming tao, sinaway niya ang masamang espiritu, na sinasabi, “Ikaw na pipi at binging espiritu, iniuutos ko sa iyo, lumabas ka sa kanya at huwag ka nang papasok muli sa kanya.”
ay iinom din naman ng alak ng poot ng Diyos, na inihahandang walang halo sa kopa ng kanyang poot at pahihirapan sa apoy at asupre sa harapan ng mga banal na anghel at sa harapan ng Kordero.
kung ating ikakaila siya, ay ikakaila rin niya tayo;
At kayo'y mga patay dahil sa inyong mga kasalanan at sa di-pagtutuli ng inyong laman ay kanyang binuhay kayong kasama niya, nang ipinatawad niya sa inyo ang lahat ng mga kasalanan,
Samantalang sinasabi niya sa kanila ang mga bagay na ito, may dumating na isang pinuno at lumuhod sa harapan niya at nagsabi, “Kamamatay pa lamang ng aking anak na babae, ngunit puntahan mo siya at ipatong mo ang iyong kamay sa kanya, at mabubuhay siya.”
Ngayon, mayroon sa aming pitong magkakapatid na lalaki. Nag-asawa ang panganay at siya'y namatay. Sapagkat hindi siya nagkaroon ng anak ay iniwan niya ang kanyang asawa sa kanyang kapatid na lalaki.
Subalit ang kanilang mga mata ay hindi pinahihintulutan na makilala siya.
Bagaman ako'y hindi bihasa sa pagsasalita, gayunma'y hindi sa kaalaman, kundi sa bawat paraan ay ginawa namin itong hayag sa inyo sa lahat ng mga bagay.
Ang mga ito ay kanyang tinipon pati ang mga manggagawa ng mga gayong hanapbuhay, at sinabi, “Mga ginoo, alam ninyo na mula sa gawaing ito ay mayroon tayong pakinabang.
Muli, sa ikalawang pagkakataon, umalis siya at nanalangin, na nagsasabi, “Ama ko, kung hindi maaaring lumampas ito, malibang inumin ko ito, ang iyong kalooban ang siyang mangyari.”
Ang lahat ng nauna sa akin ay mga tulisan at mga magnanakaw, subalit hindi sila pinakinggan ng mga tupa.
Kung paanong ang buháy na Ama ay nagsugo sa akin at ako'y nabubuhay dahil sa Ama, gayundin ang kumakain sa akin ay mabubuhay dahil sa akin.
At narinig ko ang isang tinig mula sa langit, na gaya ng lagaslas ng maraming tubig, at gaya ng ugong ng malakas na kulog; ang tinig na aking narinig ay gaya ng sa mga manunugtog na tumutugtog ng kanilang mga alpa.
Ang unang nilalang ay tulad ng isang leon, ang ikalawang nilalang ay tulad ng isang baka, ang ikatlong nilalang ay may mukha ng isang tao, at ang ikaapat na nilalang ay tulad ng isang agilang lumilipad.
Ngunit sa pamamagitan ng mga handog na ito ay may pagpapaalala ng mga kasalanan taun-taon.
At sa pagpapakita ng punong Pastol, tatanggapin ninyo ang hindi kumukupas na putong ng kaluwalhatian.
At sinabi niya sa kanya, “Panginoon, handa akong sumama sa iyo sa bilangguan at sa kamatayan.”
Sapagkat tunay at matuwid ang kanyang mga paghatol;
Sapagkat si Cristo ay hindi pumasok sa santuwaryo na ginawa ng mga kamay ng tao na mga kahalintulad lamang ng mga tunay na bagay, kundi sa mismong langit, upang dumulog ngayon sa harapan ng Diyos para sa atin.
Nang panahong iyon, inilapat ni Herodes ang kanyang mga kamay upang pagmalupitan ang ilan sa mga kaanib ng iglesya.
Sapagkat ako'y naiipit sa pagitan ng dalawa: ang aking nais ay umalis at makasama si Cristo, sapagkat ito'y higit na mabuti.
Sinabi sa kanya ni Jesus, “Bakit tinatawag mo akong mabuti? Walang mabuti kundi ang Diyos lamang.
Kung ang masang inialay bilang unang bunga ay banal, ay gayundin ang buong limpak; at kung ang ugat ay banal, gayundin ang mga sanga.
At ang tinig na aking narinig mula sa langit ay muling nagsalita sa akin, na nagsasabi, “Humayo ka, kunin mo ang aklat na bukas na nasa kamay ng anghel na nakatayo sa dagat at sa lupa.”
at ang mga tinakpan ang kanilang mga kasalanan.
Kaagad nilang iniwan ang kanilang mga lambat at sumunod sa kanya.
Nang iwan niya ang Nazaret, siya ay pumunta at tumira sa Capernaum, na nasa tabing-dagat, na sakop ng Zebulon at Neftali,
Subalit si Saulo, na tinatawag ding Pablo, na puspos ng Espiritu Santo ay tumitig sa kanya nang mabuti,
Malapit na noon ang Paskuwa na pista ng mga Judio.
Yamang batid ito ni Jesus, ay sinabi sa kanila, “Bakit ninyo pinag-uusapan na wala kayong tinapay? Hindi pa ba ninyo nalalaman ni nauunawaan man? Tumigas na ba ang inyong mga puso?
Kaya't hinihiling ko na huwag kayong manlupaypay sa mga pagdurusa ko dahil sa inyo, na ito'y para sa inyong kaluwalhatian.
Dahil sa paglaganap ng kasamaan, ang pag-ibig ng marami ay lalamig.
At nakita ko ang isang halimaw na umaahon sa dagat, may sampung sungay at pitong ulo, at sa kanyang mga sungay ay may sampung diadema, at sa kanyang mga ulo ay mga pangalan ng kalapastanganan.
Kinikilala namin ito sa lahat ng mga paraan at sa lahat ng mga dako, na may lubos na pasasalamat.
At sinabi nila sa kanya, “Sabihin mo sa amin, sa anong awtoridad mo ginagawa ang mga bagay na ito? O sino ang nagbigay sa iyo ng awtoridad na ito?”
sa Frigia at Pamfilia, sa Ehipto at sa mga lupain ng Libya na sakop ng Cirene at mga panauhing taga-Roma, mga Judio, at gayundin ang mga naging Judio,
Sinabi niya, “Katotohanang sinasabi ko sa inyo, malibang kayo'y magbago at maging tulad sa mga bata, kailanma'y hindi kayo makakapasok sa kaharian ng langit.
Nasa kamay niya ang kanyang kalaykay upang linisin ang kanyang giikan at tipunin ang trigo sa kanyang kamalig, subalit susunugin niya ang dayami sa apoy na hindi mapapatay.”
Ngunit sumagot sa kanila si Pedro at si Juan, “Kung matuwid sa paningin ng Diyos na makinig muna sa inyo sa halip na sa Diyos, kayo ang humatol,
Ito ay inyong natutunan kay Epafras na aming minamahal na kapwa alipin. Siya ay isang tapat na lingkod ni Cristo alang-alang sa inyo,
na nangangaral na may katapangan sa pangalan ng Panginoon. Siya'y nagsalita at nakipagtalo sa mga Helenista at pinagsikapan nilang siya'y patayin.
Iniunat ni Jesus ang kanyang kamay, at hinawakan niya ito na nagsasabi, “Ibig ko. Maging malinis ka.” At nalinis kaagad ang kanyang ketong.
Sa halip, ay ang panloob na pagkatao na may kagandahang walang paglipas, ng isang mahinhin at maamong espiritu na napakahalaga sa paningin ng Diyos.
Ngunit nang makilala nila na siya'y isang Judio, sa loob ng halos dalawang oras silang lahat ay nagsigawan na may isang tinig, “Dakila si Artemis ng mga taga-Efeso!”
sa lipi ni Gad ay 12,000;
upang ang sinuma'y huwag mabagabag ng mga kapighatiang ito. Sa katunayan kayo rin ang nakakaalam na itinalaga kami sa bagay na ito.
At ipinagbilin niya sa kanila na huwag silang magdadala ng anuman sa kanilang paglalakbay maliban sa isang tungkod; walang tinapay, walang balutan, walang salapi sa kanilang mga pamigkis,
Una sa lahat, ay isinasamo ko na gawin ang mga paghiling, mga panalangin, mga pamamagitan, at mga pagpapasalamat patungkol sa lahat ng mga tao;
“Gayundin naman, ang kaharian ng langit ay tulad sa isang lambat na inihagis sa dagat at nakahuli ng iba't ibang uri ng isda.
At dumating sila sa Jerico. Habang nililisan niya ang Jerico, kasama ang kanyang mga alagad at ng napakaraming tao, isang pulubing bulag, si Bartimeo na anak ni Timeo, ay nakaupo sa tabi ng daan.
Ako ay makapagpapatunay na sila ay kusang-loob na nagbigay ayon sa kanilang kakayahan, at higit pa sa kanilang makakaya,
Ito ay upang matupad ang sinabi sa pamamagitan ng propeta,
Sapagkat inaakala kong hindi makatuwiran na sa pagpapadala ng isang bilanggo, ay hindi mailahad ang sakdal laban sa kanya.”
Ginawa ito ni Jesus, ang una sa kanyang mga tanda, sa Cana ng Galilea, at ipinahayag ang kanyang kaluwalhatian; at sumampalataya sa kanya ang kanyang mga alagad.
Purihin ang Diyos at Ama ng ating Panginoong Jesu-Cristo, ang Ama ng mga kaawaan at Diyos ng lahat ng kaaliwan;
Sapagkat, “Ang lahat ng tumatawag sa pangalan ng Panginoon ay maliligtas.”
Sapagkat sinabi niya sa kanya, “Lumabas ka sa taong iyan, ikaw na masamang espiritu.”
Igalang ninyo ang lahat ng mga tao. Ibigin ninyo ang kapatiran. Matakot kayo sa Diyos. Igalang ninyo ang hari.
Pagkalipas ng tatlong araw, kanilang natagpuan siya sa templo na nakaupo sa gitna ng mga guro na nakikinig at nagtatanong sa kanila.
Ito ang ikatlong pagkakataon na ako'y darating sa inyo. Anumang bintang ay dapat pagtibayin ng dalawa o tatlong saksi.
Kayo noo'y mga patay sa inyong mga pagsalangsang at mga kasalanan,
Sa araw na iyon ay malalaman ninyong ako'y nasa aking Ama, at kayo'y nasa akin, at ako'y nasa inyo.
Alam ko ring ikaw ay may pagtitiis at nagsikap ka dahil sa aking pangalan, at hindi ka napagod.
Tumingin siya sa buong paligid upang makita kung sino ang gumawa niyon.
Subalit ngayong nakikilala na ninyo ang Diyos, o sa halip ay kinikilala na kayo ng Diyos, bakit muli kayong nagbabalik sa mahihina at hamak na mga panimulang aral, na sa mga iyon ay nais ninyong muling maging mga alipin?
Subalit mayroon akong ilang bagay na laban sa iyo: sapagkat mayroon ka diyang ilan na sumusunod sa aral ni Balaam, na siyang nagturo kay Balak na maglagay ng katitisuran sa harapan ng mga anak ni Israel, upang kumain sila ng mga bagay na inihandog sa mga diyus-diyosan at upang makiapid.
At walang kabuluhan ang pagsamba nila sa akin,
Hindi ito ang karunungang bumababa mula sa itaas, kundi makalupa, makalaman, may sa demonyo.
“Ang Panginoon ang aking katulong; hindi ako matatakot:
ayon sa kaugalian ng mga pari, napili siya sa pamamagitan ng palabunutan na pumasok sa templo ng Panginoon at magsunog ng insenso.
“Pagbalik ko sa Jerusalem, at habang ako'y nananalangin sa templo ay nawalan ako ng malay,
Huwag kayong padala sa sari-sari at kakaibang mga turo, sapagkat mabuti na ang puso ay patibayin ng biyaya; hindi sa pamamagitan ng mga pagkain, na di pinakinabangan ng mga tumupad ng mga iyon.
Pagkatapos ng mga bagay na ito ay narinig ko ang gaya ng isang malakas na tinig ng napakaraming tao sa langit, na nagsasabi,
alisin ninyo ang dating paraan ng inyong pamumuhay, ang dating pagkatao na pinasama sa pamamagitan ng mapandayang pagnanasa,
Sila'y may buhok na gaya ng buhok ng mga babae, at ang kanilang mga ngipin ay gaya ng sa mga leon.
Pagkatapos na sila'y manatili roon ng ilang panahon, sila'y payapang pinabalik ng mga kapatid sa mga nagsugo sa kanila.
Nabalitaan ng kanyang mga kapitbahay at mga kamag-anak na nagpakita ang Panginoon ng dakilang awa sa kanya at sila'y nakigalak sa kanya.
Sinabi ng pinakapunong pari, “Totoo ba ang mga bagay na ito?”
Katotohanang sinasabi ko sa inyo, na kayo'y iiyak at tatangis, subalit ang sanlibutan ay magagalak. Kayo'y malulungkot, subalit ang inyong kalungkutan ay magiging kagalakan.
O paano bang makakapasok ang sinuman sa bahay ng malakas na tao at nakawin ang mga ari-arian nito, kung hindi muna gagapusin ang malakas na tao? At saka pa lamang niya mapagnanakawan ang bahay nito.
Ako'y labis na nagalak na aking natagpuan ang ilan sa iyong mga anak na lumalakad sa katotohanan, ayon sa utos na ating tinanggap mula sa Ama.
Si Pablo, at sina Silvano at Timoteo, sa iglesya ng mga taga-Tesalonica na sa Diyos Ama at sa Panginoong Jesu-Cristo: Sumainyo nawa ang biyaya at kapayapaan.
Nang makarating ang mga alagad sa kabilang ibayo, nakalimutan nilang magdala ng tinapay.
At sila'y nag-usapan sa isa't isa na sinasabi, “Kung sasabihin natin, ‘Mula sa langit,’ ay sasabihin niya, ‘Bakit hindi ninyo siya pinaniwalaan?’
at pinag-uusapan nila ang tungkol sa lahat ng mga bagay na ito na nangyari.
Kanyang sinagot sila, “Sinabi ko na sa inyo, at hindi kayo nakinig. Bakit ibig ninyong marinig uli? Ibig din ba ninyong maging mga alagad niya?”
Magbatian kayo ng halik ng pag-ibig.
upang kayo na may isang pag-iisip sa pamamagitan ng isang bibig ay luwalhatiin ninyo ang Diyos at Ama ng ating Panginoong Jesu-Cristo.
Sinasabi ko sa inyo, marami ang manggagaling sa silangan at sa kanluran at mauupong kasalo ni Abraham, ni Isaac at ni Jacob sa kaharian ng langit,
laban sa Panginoon, at laban sa kanyang Cristo.’
Sila'y naghandog ng alay alinsunod sa sinasabi sa kautusan ng Panginoon, “dalawang batu-bato, o dalawang batang kalapati.”
Kaya ito ay hindi ayon sa kalooban o pagsisikap ng tao, kundi ayon sa habag ng Diyos.
“Nagligtas siya ng iba; hindi niya mailigtas ang kanyang sarili. Siya ang Hari ng Israel; bumaba siya ngayon sa krus, at maniniwala tayo sa kanya.
(Hindi pa noon dumarating si Jesus sa nayon, kundi naroroon pa sa lugar kung saan siya sinalubong ni Marta.)
At kung saan siya pumasok, sabihin ninyo sa may-ari ng bahay, na sinasabi ng Guro, ‘Nasaan ang aking silid-tuluyan na kung saan maaari kong kainin ang kordero ng Paskuwa na kasalo ng aking mga alagad?’
“Narito, umaahon tayo patungong Jerusalem. Ibibigay ang Anak ng Tao sa mga punong pari at sa mga eskriba; at kanilang hahatulan siya ng kamatayan.
Sinabi niya, “Oo, nagbabayad siya.” At nang dumating siya sa bahay, inunahan na siya ni Jesus tungkol dito, na sinasabi, “Ano sa palagay mo, Simon? Kanino naniningil ng bayad o buwis ang mga hari sa lupa? Sa kanila bang mga anak o sa ibang tao?”
Tingnan ninyo ang mga barko: bagama't napakalalaki at itinutulak ng malalakas na hangin, gayunma'y napapabaling sa pamamagitan ng isang napakaliit na timon saanman naisin ng piloto.
Kayo'y mula sa inyong amang diyablo, at ang nais ninyong gawin ay ang kagustuhan ng inyong ama. Siya'y isang mamamatay-tao buhat pa sa simula, at hindi naninindigan sa katotohanan, sapagkat walang katotohanan sa kanya. Kapag siya ay nagsasalita ng kasinungalingan, siya ay nagsasalita ayon sa kanyang sariling likas, sapagkat siya'y isang sinungaling, at ama ng kasinungalingan.
ni nagsihanap man sa mga tao ng kapurihan, ni sa inyo o sa iba man, bagaman may karapatan kaming humingi bilang mga apostol ni Cristo.
Gayunman, ang kamatayan ay naghari mula kay Adan hanggang kay Moises, kahit sa kanila na hindi nagkasala ng tulad sa paglabag ni Adan, na siyang anyo ng isa na darating.
Sinagot siya ni Jesus, “Ako'y hayagang nagsalita sa sanlibutan. Ako'y laging nagtuturo sa mga sinagoga at sa templo, na pinagtitipunan ng lahat ng mga Judio, at wala akong sinabi sa lihim.
Tayo mismo ay ipinanganak na mga Judio, at hindi mga Hentil na makasalanan,
ni hindi rin nila mapapatunayan sa iyo ang mga bagay na ngayo'y kanilang ibinibintang sa akin.
si Simon, na tinawag niyang Pedro, si Andres na kanyang kapatid, si Santiago, si Juan, si Felipe, si Bartolome,
Ngunit si Felix, na may wastong kaalaman tungkol sa Daan, ay ipinagpaliban ang pagdinig, na sinasabi, “Paglusong ni Lisias na punong kapitan, magpapasiya ako tungkol sa inyong usapin.”
At mula sa Galilea pumunta si Jesus kay Juan sa Jordan upang magpabautismo sa kanya.
Sapagkat sinasabi niya kay Moises,
Narinig ng mga Fariseo na pawang maibigin sa salapi ang lahat ng mga bagay na ito at kanilang tinuya si Jesus.
Sinabi niya sa kanila, “Pumunta tayo sa iba pang mga karatig-bayan upang ako'y makapangaral din naman doon, sapagkat dahil dito ako'y naparito.”
Pagkaiwan sa maraming tao, siya'y kanilang isinama sa bangka, ayon sa kanyang kalagayan. At may iba pang mga bangka na kasama niya.
At sa oras ng hapunan ay sinugo niya ang kanyang alipin upang sabihin sa mga inanyayahan, ‘Halikayo, sapagkat ang lahat ay handa na.’
Sinabi sa kanya ni Pedro, “Panginoon, bakit hindi ako makakasunod sa iyo ngayon? Ang aking buhay ay ibibigay ko para sa iyo.”
Gumising ka, at palakasin mo ang mga bagay na natitira, na malapit nang mamatay, sapagkat hindi ko natagpuang ganap ang iyong mga gawa sa harapan ng aking Diyos.
Mas dakila ka pa ba kaysa sa aming amang si Abraham, na namatay? At namatay ang mga propeta? Ano ang palagay mo sa iyong sarili?”
Nang sumapit ang Sabbath, nagpasimula siyang magturo sa sinagoga at marami sa mga nakinig sa kanya ay namangha na sinasabi, “Saan kinuha ng taong ito ang lahat ng ito? Anong karunungan ito na ibinigay sa kanya? Anong mga makapangyarihang gawa ang ginagawa ng kanyang mga kamay!
ako ngayon ay naging Ama mo.”
May isang lalaking kabilang sa mga Fariseo na ang pangalan ay Nicodemo, isang pinuno ng mga Judio.
Sa ganito nahahayag ang mga anak ng Diyos at ang mga anak ng diyablo: ang sinumang hindi gumagawa ng katuwiran ay hindi sa Diyos, pati ang hindi umiibig sa kanyang kapatid.
Pagkatapos ay kanyang dinala siya sa Jerusalem at inilagay siya sa tuktok ng templo, at sinabi sa kanya, “Kung ikaw ang Anak ng Diyos, magpatihulog ka mula rito,
Sumigaw si Jesus habang nagtuturo sa templo, “Ako'y inyong nakikilala at nalalaman din ninyo kung taga-saan ako. Hindi ako pumarito sa aking sariling awtoridad, subalit ang nagsugo sa akin ay siyang totoo, na hindi ninyo nakikilala.
At kanilang sinabi sa kanya, “Saan mo gustong ihanda namin ito?”
Inutusan niya ang maraming tao na umupo sa lupa. Kinuha niya ang pitong tinapay at pagkatapos magpasalamat, pinagputul-putol niya ang mga ito at ibinigay sa kanyang mga alagad upang ihain. At inihain nila ang mga ito sa maraming tao.
Sapagkat ito'y kapuri-puri, kung dahil sa pagkakilala sa Diyos ay nagtiis ang sinuman ng sakit habang nagdurusa nang hindi nararapat.
“Kahabag-habag kayo, mga bulag na taga-akay na nagsasabi, ‘Kung ipanumpa ninuman ang templo, ay wala iyong kabuluhan, ngunit kung ipanumpa ninuman ang ginto ng templo, siya ay may pananagutan.’
Nang marinig ito ni Pilato, itinanong niya kung ang taong iyon ay taga-Galilea.
at ang kanyang damit ay naging nagniningning na puti na walang sinuman sa lupa na makapagpapaputi ng gayon.
Sumagot si Jesus, “Ako'y walang demonyo, kundi pinararangalan ko ang aking Ama, at inyong sinisira ang aking karangalan.
Sinabi sa kanya ni Felipe, “Panginoon, ipakita mo sa amin ang Ama, at kami ay masisiyahan na.”
Ang may pandinig ay makinig sa sinasabi ng Espiritu sa mga iglesya. Ang magtagumpay ay hindi masasaktan ng ikalawang kamatayan.
Nang sumunod na araw, sumama si Pablo sa amin kay Santiago; at ang lahat ng matatanda ay naroroon.
Sapagkat tayong lahat ay kailangang humarap sa hukuman ni Cristo upang bawat isa ay tumanggap ng kabayaran sa mga bagay na ginawa niya sa pamamagitan ng katawan, maging mabuti o masama.
Sapagkat nalalaman niya kung sino ang magkakanulo sa kanya, kaya't sinabi niya, “Hindi lahat sa inyo ay malilinis.”
At biglang sumama sa anghel ang isang malaking hukbo ng langit na nagpupuri sa Diyos at nagsasabi,
Titindig ako at pupunta sa aking ama, at aking sasabihin sa kanya, “Ama, nagkasala ako laban sa langit at sa iyo.
Huwag sabihin ng sinuman kapag siya'y tinutukso, “Ako'y tinutukso ng Diyos,” sapagkat ang Diyos ay hindi natutukso ng masasama, at hindi rin siya nanunukso sa sinuman.
Ang mga punong pari at ang mga Fariseo ay nag-utos na sinumang nakakaalam ng kinaroroonan ni Jesus ay dapat ipagbigay-alam sa kanila upang siya'y kanilang madakip.
Alam ni Jesus na ibinigay na ng Ama ang lahat ng mga bagay sa kanyang mga kamay, at siya'y nanggaling sa Diyos at patungo sa Diyos.
Ngayon na ang panahong kanais-nais; ngayon na ang araw ng kaligtasan.
Nang mapansin ni Pablo na ang ilan ay mga Saduceo at ang iba'y mga Fariseo, ay sumigaw siya sa Sanhedrin, “Mga ginoo, mga kapatid, ako'y isang Fariseo, anak ng mga Fariseo. Ako'y nililitis tungkol sa pag-asa at muling pagkabuhay ng mga patay.”
Gayundin, ang tumanggap ng dalawa ay nakinabang pa ng dalawa.
Sa pagdalaw ni Pedro sa lahat ng dako sa mga mananampalataya, pumunta rin siya sa mga banal na naninirahan sa Lidda.
Nagtatali sila ng mabibigat na pasanin at mahihirap dalhin, at ipinapatong nila sa mga balikat ng mga tao; ngunit ayaw nila mismong galawin ang mga iyon ng kanilang daliri.
Subalit ang mga taong ito na hindi nakakaalam ng kautusan ay mga sinumpa.”
Subalit tayo'y kailangang mapadpad sa isang pulo.”
sapagkat ipapakita ko sa kanya kung gaano karaming bagay ang dapat niyang tiisin alang-alang sa aking pangalan.”
Magmahalan kayo na may pag-ibig bilang magkakapatid; sa pagpaparangal sa iba ay mag-unahan kayo,
Ako'y naging hangal! Pinilit ninyo ako, sapagkat ako ay dapat ninyong purihin: sapagkat ako'y hindi hamak na mababa sa mga dakilang apostol na iyon, kahit na ako'y walang kabuluhan.
At kung hindi, samantalang malayo pa ang isa ay magpapadala na siya ng isang sugo at hihilingin ang mga kasunduan sa kapayapaan.
Sa pananampalataya, si Jacob nang mamamatay na ay binasbasan niya ang bawat isa sa mga anak ni Jose, at sumamba sa ibabaw ng kanyang tungkod.
Sapagkat tayong lahat ay natitisod sa maraming bagay. Kung ang sinuman ay hindi natitisod sa pananalita, ito ay isang taong sakdal, may kakayahang pigilan ang buong katawan.
sa kanila ay hindi kami sumuko upang magpasakop, kahit isang saglit, upang ang katotohanan ng ebanghelyo ay manatili sa inyo.
Nagkataon na nakaratay ang ama ni Publio na maysakit na lagnat at disenteriya. Pinuntahan siya ni Pablo at nanalangin, at nang maipatong sa kanya ang kanyang mga kamay ay pinagaling siya.
Kaya't habang may pagkakataon, gumawa tayo ng mabuti sa lahat, lalung-lalo na sa mga kabilang sa sambahayan ng pananampalataya.
At pagkaawit nila ng isang himno ay nagtungo sila sa Bundok ng mga Olibo.
Yamang marami ang nagmamalaki sang-ayon sa pamantayan ng tao, ako ma'y magmamalaki.
Mula noo'y sinikap ni Pilato na siya'y pakawalan. Ngunit ang mga Judio ay nagsisigawang, “Kung pakakawalan mo ang taong ito ay hindi ka kaibigan ni Cesar. Ang bawat nag-aangkin na siya'y hari ay nagsasalita ng laban kay Cesar.”
At ang kasulatan, na nakakaalam nang una pa man na aariing-ganap ng Diyos ang mga Hentil sa pamamagitan ng pananampalataya, ay ipinahayag ang ebanghelyo nang una pa man kay Abraham, na sinasabi, “Sa iyo ay pagpapalain ang lahat ng mga bansa.”
na nagpapasalamat sa Ama, na ginawa niya tayong karapat-dapat na makabahagi sa mana ng mga banal sa kaliwanagan.
Pagkatapos ay lumapit sa kanya ang mga alagad ni Juan na nagsasabi, “Bakit kami at ang mga Fariseo ay nag-aayuno ngunit ang mga alagad mo ay hindi nag-aayuno?”
Alin ba ang mas madali, ang sabihing, ‘Pinatatawad na ang iyong mga kasalanan,’ o ang sabihing, ‘Tumindig ka at lumakad?’
Kapag ang isang taong malakas at nasasandatahang mabuti ay nagbabantay sa kanyang sariling palasyo, ang kanyang mga ari-arian ay ligtas.
Nang siya'y naghahanda na sa kanyang paglalakbay, may isang lalaking patakbong lumapit sa kanya, at pagluhod sa kanyang harapan, siya'y tinanong, “Mabuting Guro, ano ang dapat kong gawin upang magmana ng buhay na walang hanggan?”
Ano nga kung sa pagnanais ng Diyos na ipakita ang kanyang poot, at ipakilala ang kanyang kapangyarihan, ay nagtitiis na may pagtitiyaga sa mga kinapopootan niya na inihanda para sa pagkawasak;
Ganito ang ibig kong sabihin: ang tagapagmana, habang bata pa ay hindi nakahihigit sa mga alipin bagama't siya ang may-ari ng lahat,
“Kahabag-habag ka, Corazin! Kahabag-habag ka, Bethsaida! Sapagkat kung sa Tiro at Sidon ginawa ang mga makapangyarihang gawa na ginawa sa inyo, matagal na sana silang nagsisi na may damit-sako at abo.
At kapag ang mga nilalang na buháy ay nagbibigay ng kaluwalhatian, karangalan, at pasasalamat sa nakaupo sa trono, doon sa nabubuhay magpakailanpaman,
Mga panginoon, pakitunguhan ninyo ang inyong mga alipin nang matuwid at makatarungan, yamang nalalaman ninyo na kayo man ay mayroon ding Panginoon sa langit.
Pagkabatid na may lumabas na kapangyarihan mula sa kanya, bumaling si Jesus sa karamihan at nagsabi, “Sino ang humipo sa aking damit?”
Tayo'y huwag nang maging mga bata, na tinatangay-tangay ng mga alon at dinadala-dala ng bawat hangin ng aral, sa pamamagitan ng pandaraya ng mga tao, sa pamamagitan ng kanilang mga katusuhan sa paraang mapandaya.
Pagtalikod ni Pedro, nakita niya ang alagad na minamahal ni Jesus na sumusunod. Siya rin iyong nakahilig na malapit kay Jesus sa hapunan at nagsabi, “Panginoon, sino ang magkakanulo sa iyo?”
ni Maat, ni Matatias, ni Semein, ni Josec, ni Joda,
Ang iba ay nahulog sa batuhan na doo'y walang maraming lupa. Agad itong sumibol sapagkat hindi malalim ang lupa.
hindi sa buong bayan, kundi sa amin na hinirang ng Diyos bilang mga saksi na kumain at uminom na kasalo niya, pagkatapos na siya'y mabuhay mula sa mga patay.
Sinabi sa kanya ni Jesus, “Huwag mo akong hawakan, sapagkat hindi pa ako nakakaakyat sa Ama. Ngunit pumunta ka sa aking mga kapatid, at sabihin mo sa kanila, ‘Aakyat ako sa aking Ama at inyong Ama, sa aking Diyos at inyong Diyos.’”
Ito'y gumagawa ng mga dakilang tanda, pati na ang pagpapababa ng apoy sa lupa mula sa langit sa paningin ng mga tao.
at ang lahat ng mga lipi sa lupa ay tatangis dahil sa kanya.
Subalit ang mga bagay na ito'y sinabi ko sa inyo, upang kung dumating ang kanilang oras ay inyong maalala na sinabihan ko kayo tungkol sa kanila. At ang mga bagay na ito'y hindi ko sinabi sa inyo buhat nang pasimula, sapagkat ako'y kasama ninyo.
Habang nagsasalita pa siya, may isang dumating na mula sa bahay ng pinuno ng sinagoga na nagsasabi, “Patay na ang anak mong babae; huwag mo nang abalahin pa ang Guro.”
Siya'y ginapos nila, dinala sa labas, at ibinigay nila kay Pilato na gobernador.
Siya'y aking pinababalik sa iyo, na kasama ang aking sariling puso.
“Narinig ninyo na sinabi, ‘Ibigin mo ang iyong kapwa, at kapootan mo ang iyong kaaway.’
Sapagkat noo'y araw ng Paghahanda, upang maiwasan na ang mga katawan ay manatili sa krus sa araw ng Sabbath (sapagkat dakila ang araw ng Sabbath na iyon), hiniling ng mga Judio kay Pilato na baliin ang kanilang mga binti at sila'y alisin doon.
na hindi sa pamamagitan ng mga gawa, kundi doon sa tumatawag) ay sinabi sa kanya, “Ang nakatatanda ay maglilingkod sa nakababata.”
Ngayon, ang pananampalataya ay ang katiyakan sa mga bagay na inaasahan, ang paninindigan sa mga bagay na hindi nakikita.
At kanilang binigyan siya ng isang pirasong inihaw na isda.
Si Zaqueo ay tumindig at sinabi sa Panginoon, “Panginoon, ang kalahati ng aking mga pag-aari ay ibinibigay ko sa mga dukha at kung sa pamamagitan ng pandaraya ay may kinuha ako sa kanino mang tao, babayaran ko siya ng apat na ulit.”
Sapagkat mula ngayon ang lima sa isang bahay ay magkakabaha-bahagi; tatlo laban sa dalawa, at dalawa laban sa tatlo.
Nang dumating sila sa napakaraming tao, lumapit sa kanya ang isang tao, lumuhod sa harapan niya,
Pumunta ang lahat upang magpatala, bawat isa sa kanyang sariling bayan.
Bumalik siya sa ikatlong pagkakataon at sinabi sa kanila, “Natutulog pa rin ba kayo at nagpapahinga? Tama na! Dumating na ang oras; ang Anak ng Tao ay ipinagkakanulo sa mga kamay ng mga makasalanan.
Ngunit kung ito'y sa Diyos, hindi ninyo sila makakayang wasakin. Baka matagpuan pa kayong nakikipaglaban sa Diyos!”
Pagkalipas ng mga araw na ito ay naglihi ang kanyang asawang si Elizabeth. Siya ay nagtago nang limang buwan, na nagsasabi,
Kanyang hinawakan siya sa kanang kamay, at siya'y itinindig at agad na lumakas ang kanyang mga paa at mga bukung-bukong.
At sabihin ninyo kay Arquipo, “Sikapin mong gampanan ang ministeryo na tinanggap mo sa Panginoon.”
Siya'y sinaway ng mga nasa unahan at sinabihan siyang tumahimik. Subalit siya'y lalong nagsisigaw, “Anak ni David, maawa ka sa akin.”
