Sumagot si Pablo, “Ako'y Judio, na taga-Tarso sa Cilicia, isang mamamayan ng isang hindi karaniwang lunsod. Nakikiusap ako, pahintulutan mo akong magsalita sa mga taong-bayan.”
Ito ang mga angkan ng mga anak ni Gad ayon sa nabilang sa kanila, apatnapung libo at limang daan.
Nang pumasok ang anak na babae ni Herodias at sumayaw, siya'y nagustuhan ni Herodes at ng kanyang mga panauhin. Sinabi ng hari sa dalaga, “Hingin mo sa akin ang maibigan mo at ibibigay ko sa iyo.”
Sapagkat ang mabuti na aking nais ay hindi ko ginagawa, ngunit ang masama na hindi ko nais ay siya kong ginagawa.
Ngunit si Maria ay nakatayong umiiyak sa labas ng libingan. Habang umiiyak, siya'y yumuko at tumingin sa loob ng libingan.
At agad na isinugo ng mga kapatid si Pablo paalis hanggang sa dagat, ngunit nanatili roon sina Silas at Timoteo.
Ayon sa aking lubos na inaasahan at pag-asa, na sa anuman ay hindi ako mapapahiya, kundi sa buong katapangan, na gaya ng dati, gayundin naman ngayon, ay dadakilain si Cristo sa aking katawan, maging sa pamamagitan ng buhay, o sa pamamagitan ng kamatayan.
sa lugar ng dambana na kanyang ginawa roon nang una; at doon ay tinawag ni Abram ang pangalan ng Panginoon .
“‘Kung ang isang tao ay nagkasala nang hindi sinasadya, ay maghahandog nga siya ng isang kambing na babae na isang taong gulang na handog pangkasalanan.
Pagkatapos ay dumating ang isa sa mga pinuno ng sinagoga na nagngangalang Jairo. Pagkakita sa kanya, nagpatirapa siya sa kanyang paanan,
at ipapatong mo ang turbante sa kanyang ulo, at ipapatong mo ang banal na korona sa turbante.
Nang marinig nila ang mga bagay na ito, sila ay nagalit at nagngalit ang kanilang mga ngipin laban kay Esteban.
At nang sila'y makarating sa isang dakong tinatawag na Golgota, (na ang kahulugan ay, “Ang Dako ng Bungo”),
Sapagkat sinasabi nila, “Ang kanyang mga sulat ay mabibigat at matitindi; subalit ang anyo ng kanyang katawan ay mahina, at ang kanyang pananalita ay walang kabuluhan.”
Ang bautismo ba ni Juan ay mula sa langit, o mula sa mga tao?”
Ikaw ay magkakaroon ng kaligayahan at kagalakan at marami ang matutuwa sa kanyang pagsilang.
Ngunit walang makakapasok sa bahay ng malakas na tao upang samsamin ang kanyang mga ari-arian, malibang gapusin muna niya ang malakas na tao; at kung magkagayo'y malolooban niya ang bahay nito.
At sinabi ni Laban kay Jacob, “Hindi ba't ikaw ay aking kamag-anak? Dapat ka bang maglingkod sa akin nang walang upa? Sabihin mo sa akin, ano ang magiging upa mo?”
Nakikita mo na ang pananampalataya ay gumagawang kalakip ng kanyang mga gawa, at ang pananampalataya ay naging ganap sa pamamagitan ng mga gawa.
“Sino sa inyo, na mayroong aliping nag-aararo o nag-aalaga ng mga tupa ang magsasabi sa kanya pagkagaling sa bukid, ‘Pumarito ka agad at maupo sa hapag ng pagkain.’
Ang mga anak ni Aaron, ang mga pari, ang hihihip ng mga trumpeta; at ang trumpeta ay magiging walang hanggang tuntunin sa inyo sa buong panahon ng inyong mga salinlahi.
Sinabi ni Jacob kina Simeon at Levi, “Ako'y inyong binagabag, na gawin akong kasuklamsuklam sa mga nakatira sa lupain, sa mga Cananeo at mga Perezeo. Iilan lamang ang aking tauhan at sila ay magtitipon laban sa akin, at ako'y kanilang sasalakayin, at ang aking sambahayan ay pupuksain.”
Nang sila'y makarating sa Salamis, kanilang ipinangaral ang salita ng Diyos sa mga sinagoga ng mga Judio. Kasama rin nila si Juan bilang katulong.
Sa muling pagkabuhay, sino sa kanila ang magiging asawa ng babae? Sapagkat siya'y naging asawa ng pito.”
Sumakay sila sa isang bangka at pinasimulan nilang tawirin ang dagat hanggang sa Capernaum. Madilim na noon at hindi pa dumarating sa kanila si Jesus.
At kinuha ni Moises ang tungkod sa harap ng Panginoon , na gaya ng iniutos sa kanya.
At kaagad na nawala ang kanyang ketong at siya'y naging malinis.
Sa katapusan ng dalawang taon, ang Faraon ay nanaginip na siya'y nakatayo sa tabi ng Nilo.
“At mangyayari, na sa lugar na kung saan ay sinabi sa kanila, ‘Kayo'y hindi ko bayan,’ doon sila tatawaging ‘mga anak ng Diyos na buháy.’”
At huwag kayong susumpa sa pamamagitan ng aking pangalan sa kasinungalingan; sa gayo'y lalapastanganin ninyo ang pangalan ng inyong Diyos: Ako ang Panginoon .
Tumawag sila upang magtanong kung si Simon, na tinatawag na Pedro, ay nanunuluyan doon.
ang kanyang bangkay ay hindi dapat manatili nang magdamag sa punungkahoy. Dapat siyang ilibing sa araw ding iyon, sapagkat ang taong binitay ay isinumpa ng Diyos upang huwag mong marumihan ang iyong lupa na ibinibigay sa iyo ng Panginoon mong Diyos bilang pamana.
Siya'y dumampot ng isang kopa at nang siya'y makapagpasalamat ay ibinigay niya sa kanila, at mula roo'y uminom silang lahat.
Ang ilan sa mga Fariseo na kasama niya ay nakarinig ng mga bagay na ito, at sinabi sa kanya, “Kami ba naman ay mga bulag din?”
“Kayo'y mga anak ng Panginoon ninyong Diyos; huwag ninyong susugatan ang inyong sarili, ni kakalbuhin ang inyong noo dahil sa patay.
At nawa'y palaguin at pasaganain kayo ng Panginoon sa pag-ibig sa isa't isa at sa lahat ng tao, gaya naman namin sa inyo.
At kung ito ay kumalat sa balat, ipahahayag ng pari na siya ay marumi; iyon nga ay sakit.
At sinabi sa kanya ng Panginoon, “Kayong mga mapagkunwari! Hindi ba kinakalagan ng bawat isa sa inyo sa Sabbath ang kanyang bakang lalaki o ang kanyang asno mula sa sabsaban at ito'y inilalabas upang painumin?
Nang magkagayo'y isinama ni Pablo ang mga lalaking iyon. Nang sumunod na araw, pagkatapos malinis ang kanyang sarili, pumasok siya sa templo upang ipahayag kung kailan magaganap ang mga araw ng paglilinis, at ang pag-aalay ng handog para sa bawat isa sa kanila.
At susunugin ng pari bilang bahaging pinakaalaala ang bahagi ng butil na niligis at ang bahagi ng langis, pati ang lahat ng kamanyang niyon; ito ay isang handog sa Panginoon na pinaraan sa apoy.
Nang ipapasok na si Pablo sa himpilan, ay sinabi niya sa pinunong kapitan, “Maaari ba akong makipag-usap sa iyo?” At sinabi ng pinunong kapitan, “Marunong ka ba ng Griyego?
Sinabi niya sa kanila, “Pakinggan ninyo ngayon itong aking napanaginip.
Tinanong siya ng kanyang mga alagad, na nagsasabi, “Bakit kaya sinasabi ng mga eskriba na kailangang dumating muna si Elias?”
At walang taong naglalagay ng bagong alak sa mga lumang sisidlang balat. Kung gayon, papuputukin ng bagong alak ang mga balat, at matatapon, at masisira ang mga balat.
Ako'y panatag sa bagay na ito, na ang nagpasimula sa inyo ng mabuting gawa ay siyang magtatapos nito hanggang sa araw ni Jesu-Cristo.
Kung paanong ang katotohanan ni Cristo ay nasa akin, walang makakapigil sa akin sa pagmamalaking ito sa mga lupain ng Acaia.
Bawat libis ay matatambakan, at bawat bundok at burol ay papatagin, at ang liko ay tutuwirin, at ang mga baku-bakong daan ay papantayin.
At sinong lalaki ang may itinanim na isang ubasan at hindi pa niya napapakinabangan ang bunga niyon? Hayaan siyang umalis at bumalik sa kanyang bahay, baka siya'y mamatay sa digmaan at ibang lalaki ang makinabang ng bunga niyon.
At ang nasa bubungan ay huwag nang bumaba, o pumasok upang maglabas ng anuman sa kanyang bahay.
Kaya't sila'y binilang ni Moises ayon sa salita ng Panginoon , gaya ng iniutos sa kanya.
Ang isa sa dalawang nakarinig ng pagsasalita ni Juan, at sumunod sa kanya, ay si Andres na kapatid ni Simon Pedro.
Sapagkat kung saan mayroong paninibugho at pagiging makasarili, doon ay mayroong kaguluhan at bawat gawang masama.
Lahat ng mga angkan ng mga Suhamita, ayon sa nabilang sa kanila, ay animnapu't apat na libo at apatnaraan.
At kung si Cristo ay nasa sa inyo, ang katawan ay patay dahil sa kasalanan; ngunit ang espiritu ay buháy dahil sa katuwiran.
Kaya't naglihi si Bilha at nagkaanak kay Jacob ng isang lalaki.
Sapagkat kung pagkatapos na sila'y makatakas sa mga karumihan ng sanlibutan sa pamamagitan ng pagkakilala sa Panginoon at Tagapagligtas na si Jesu-Cristo, ay muli silang napasabit sa mga ito at nadaig, ang huling kalagayan nila ay mas masama kaysa nang una.
Ang upahan at hindi pastol, at hindi may-ari ng mga tupa, nang makitang dumarating ang asong-gubat ay pinababayaan ang mga tupa at tumatakas. At inaagaw sila ng asong-gubat, at ikinakalat.
Gagawa ka ng dalawang singsing na ginto, at iyong ikakabit sa dalawang pambalikat ng efod, sa dakong ibaba, sa harapan, na malapit sa dugtungan sa ibabaw ng mahusay na hinabing pamigkis ng efod.
Mga kapatid, huwag kayong magbulung-bulungan laban sa isa't isa, upang huwag kayong mahatulan. Tingnan ninyo, ang hukom ay nakatayo sa harapan ng mga pintuan.
Nang makapasok na siya sa bahay, lumapit sa kanya ang mga lalaking bulag; at sinabi sa kanila ni Jesus, “Sumasampalataya ba kayo na magagawa ko ito?” Sinabi nila sa kanya, “Opo, Panginoon.”
Iyong bubuhusan niyon ang toldang tipanan, at ang kaban ng patotoo,
Nakita ng asno ang anghel ng Panginoon at siya'y itinulak sa bakod at naipit ang paa ni Balaam sa bakod at kanyang pinalo uli ang asno.
Ang mga pastol ay dumating at sila'y ipinagtabuyan; ngunit si Moises ay tumindig at sila'y ipinagtanggol, at pinainom ang kanilang kawan.
Kaya't ipinagsama niya ang kanyang mga kamag-anak, at hinabol siya sa loob ng pitong araw hanggang sa kanyang inabutan siya sa bundok ng Gilead.
Siya'y magpapatuloy sa panahon ng kanyang paglilinis sa dugo sa loob ng tatlumpu't tatlong araw; huwag siyang hihipo ng anumang bagay na banal, at huwag siyang papasok sa santuwaryo, hanggang sa matapos ang mga araw ng kanyang paglilinis.
Si Santiago, na alipin ng Diyos at ng Panginoong Jesu-Cristo, ay bumabati sa labindalawang lipi na nasa Pangangalat.
hanggang sa ang iyong mga kaaway ay gawin kong tuntungan ng iyong mga paa.”’
Siya'y sinundan ng napakaraming tao, at ng mga babaing nagdadalamhati at nag-iiyakan para sa kanya.
Sinabi ni Israel kay Jose, “Hindi ba nagpapastol ng kawan sa Shekem ang iyong mga kapatid? Halika, at isusugo kita sa kanila.” Sinabi niya sa kanya, “Narito ako.”
Ang mga lalaki ay natakot sapagkat sila'y dinala sa bahay ni Jose, at sinabi nila, “Dinala tayo rito dahil sa salaping isinauli sa ating mga sako noon, upang magkaroon siya ng pagkakataong dakpin tayo, at tayo'y kunin bilang mga alipin, pati ang ating mga asno.”
ako man ay sasalungat sa inyo na may kabagsikan; at parurusahan ko rin kayo nang pitong ulit dahil sa inyong mga kasalanan.
Sinabi nga niya, “Isang maharlikang tao ang pumunta sa isang malayong lupain, upang tumanggap ng isang kaharian at pagkatapos ay bumalik.
Bawat lalaki sa mga pari ay kakain niyon; ito ay dapat kainin sa dakong banal.
Ikaw ay pupunta sa mga paring Levita, at sa magiging hukom sa mga araw na iyon at iyong sisiyasatin; at kanilang ipapaalam sa iyo ang hatol.
Sumigaw siya nang malakas at sinabi, “Pinagpala ka sa mga babae, at pinagpala ang bunga ng iyong sinapupunan!
Si Jesus ay sumigaw nang malakas at nalagutan ng hininga.
Nang araw ding iyon ay lumabas si Jesus sa bahay at umupo sa tabi ng dagat.
Ngunit sumagot siya at sinabi, “Ako'y hindi sinugo maliban sa mga nawawalang tupa ng sambahayan ni Israel.”
Si Abimelec ay kumuha ng mga tupa at baka, mga aliping lalaki at babae, at ibinigay ang mga ito kay Abraham, at isinauli sa kanya si Sara na kanyang asawa.
sina Patrusim, at Casluim na siyang pinagmulan ng mga Filisteo, at ang Caftoreo.
Ang sinumang gumagawa ng kasalanan ay lumalabag din naman sa kautusan; at ang kasalanan ay ang paglabag sa kautusan.
Dalhin ninyo ang mga pasanin ng isa't isa, at sa gayon ay matutupad ninyo ang kautusan ni Cristo.
At tumayo siyang umiiyak sa likuran sa may paanan ni Jesus. Pinasimulan niyang basain ang kanyang mga paa ng kanyang mga luha, pinunasan ang mga ito ng kanyang buhok. Patuloy niyang hinagkan ang mga paa ni Jesus at binuhusan ang mga ito ng pabango.
Kaya't sinabi ni Jose sa Faraon, “Ang panaginip ng Faraon ay iisa; ipinakita ng Diyos sa Faraon ang malapit na niyang gawin.
At nang masabi niya ang mga ito ay sumigaw siya ng malakas na tinig, “Lazaro, lumabas ka!”
Nakikiusap ako kina Euodias at Sintique, na magkaisa sila ng pag-iisip sa Panginoon.
sapagkat hindi pa ito dumarating sa kaninuman sa kanila, kundi sila'y nabautismuhan lamang sa pangalan ng Panginoong Jesus.
Nang ako'y umakyat sa bundok upang tanggapin ang mga tapyas na bato, samakatuwid ay ang mga tapyas ng tipan na ginawa ng Panginoon sa inyo, nanatili ako sa bundok ng apatnapung araw at apatnapung gabi. Hindi ako kumain ng tinapay ni uminom ng tubig.
Kaya't sinasabi ko sa inyo, ang marami niyang kasalanan ay pinatawad na, sapagkat siya ay nagmahal ng malaki. Subalit ang pinatatawad ng kaunti ay nagmamahal nang kaunti.”
Sa kahuli-huliha'y sinugo niya sa kanila ang kanyang anak na lalaki, na nagsasabi, ‘Igagalang nila ang aking anak.’
Sinabi naman sa kanya ng Panginoon , “Ano iyang nasa iyong kamay?” Kanyang sinabi, “Isang tungkod.”
Mga kapatid ko, kung ang sinuman sa inyo ay naliligaw mula sa katotohanan, at siya'y pinapanumbalik ng sinuman,
“Lahat ng mga ito na nasa tubig ay maaari ninyong kainin: anumang may mga kaliskis at mga palikpik, ay maaari ninyong kainin.
Maging si Herodes man, sapagkat kanyang ibinalik siya sa atin at tingnan ninyo, wala siyang ginawang anumang nararapat sa kamatayan.
at ang humalili sa bukol ay isang pamamaga na maputi, o isang pantal na makintab na namumula, ito ay ipapakita sa pari.
Sapagkat paano ngayon malalaman na ako'y nakatagpo ng biyaya sa iyong paningin, ako at ang iyong bayan? Hindi ba dahil sa ikaw ay lumalakad na kasama namin, kaya't kami ay naiiba, ako at ang iyong bayan, sa lahat ng bayan sa balat ng lupa?”
At huwag mong ililitaw ang kahubaran ng kapatid na babae ng iyong ina, ni ng kapatid na babae ng iyong ama, sapagkat hinubaran niya ang kanyang malapit na kamag-anak; sila ay kapwa mananagot ng kanilang kasamaan.
Kung paano ang upahan sa taun-taon ay gayon siya maninirahan sa kanya; siya'y huwag maghahari sa kanya na may kabagsikan sa iyong paningin.
at hindi para sa bansa lamang, kundi upang tipunin niya sa iisa ang mga anak ng Diyos na nagkahiwa-hiwalay.
Sinabihan ni Cain ang kanyang kapatid na si Abel, at nangyari nang sila'y nasa parang, tumindig si Cain laban kay Abel na kanyang kapatid, at ito'y kanyang pinatay.
At ang pangalan ng anak na babae ni Aser ay Sera.
At ang iba'y nahulog sa mga tinikan, at ang mga tinik ay tumubong kasama nito at ito'y sinakal.
Si Abram ay walumpu't anim na taon nang ipanganak ni Hagar si Ismael sa kanya.
at ibinigay sa kanya ang aklat ni propeta Isaias. Binuksan niya ang aklat, at natagpuan ang dako na kung saan ay nasusulat:
kung gayon sa araw na kanyang itakda na ibigay ang kanyang mga ari-arian bilang pamana sa kanyang mga anak, siya ay hindi pinahihintulutang gawing panganay ang anak ng minamahal na higit sa anak ng kinapopootan na siyang panganay.
Nang maalala ni Pedro ay sinabi niya sa kanya, “Rabi, tingnan mo! Ang puno ng igos na iyong isinumpa ay tuyo na.”
Kung kayo nga'y muling binuhay na kasama ni Cristo, ay hanapin ninyo ang mga bagay na nasa itaas, na kinaroroonan ni Cristo, na nakaupo sa kanan ng Diyos.
Muling babalik ang pari sa ikapitong araw at gagawa ng pagsusuri, at kung kumalat na ang salot sa mga dingding ng bahay,
Pagkaraan ng tatlong araw, tinipon niya ang mga pinuno ng mga Judio at nang sila'y matipon na, ay sinabi niya sa kanila, “Mga kapatid, bagaman wala akong ginawang anuman laban sa bayan, o sa mga kaugalian ng ating mga ninuno, ay ibinigay akong bilanggo buhat sa Jerusalem sa mga kamay ng mga taga-Roma.
Sapagkat mamagalingin ko pang ako ay sumpain at mawalay kay Cristo alang-alang sa aking mga kapatid, na aking mga kamag-anak ayon sa laman.
Nang ibig niyang lumipat sa Acaia, pinalakas ng mga kapatid ang kanyang loob at sinulatan nila ang mga alagad na siya'y tanggapin. Nang siya'y dumating, kanyang lubos na tinulungan ang mga taong sa pamamagitan ng biyaya ay sumampalataya.
At sinabi sa kanya, “Humayo ka, maghugas ka sa imbakan ng tubig ng Siloam” (na ang kahulugan ay Sinugo). Humayo nga siya at naghugas at bumalik na nakakakita.
Nang dumating sila sa lugar na tinatawag na Bungo, kanilang ipinako siya sa krus, kasama ng mga kriminal, isa sa kanyang kanan at isa sa kanyang kaliwa.
Sapagkat hindi kami natagpuang gumamit kailanman ng mga salitang paimbabaw, gaya ng nalalaman ninyo, ni ng balabal ng kasakiman, saksi namin ang Diyos;
Nang makita ni Herodes si Jesus, siya ay tuwang-tuwa, sapagkat matagal na niyang nais na makita siya sapagkat nakabalita siya ng tungkol sa kanya; at siya'y umaasang makakita ng ilang himalang ginawa niya.
Kaya't sila'y humukay ng ibang balon at muli nilang pinagtalunan, at ito ay tinawag niya sa pangalang Sitnah.
“Kapag ikaw ay magpapahiram sa iyong kapwa ng anumang bagay, huwag kang papasok sa kanyang bahay upang kunin ang kanyang sangla.
Kayo'y maghahandog ng isang handog na sinusunog na mabangong samyo sa Panginoon , ng isang batang toro, isang lalaking tupa, pitong korderong lalaki na isang taong gulang at walang kapintasan.
At sinabi ng Panginoon kay Moises, “Magdala ka ng mababangong pabango ng estacte, onix, at galbano; mababangong pabango na may purong kamanyang (na bawat isa'y magkakapareho ng bahagi),
Pagkatapos ay dumating naman ang ibang mga birhen, na nagsasabi, ‘Panginoon, Panginoon, pagbuksan mo kami.’
Sapagkat madalas na siya'y ginagapos ng mga kadena at mga tanikala ngunit nilalagot niya ang mga tanikala, at pinagpuputul-putol ang mga kadena. Walang taong may lakas na makasupil sa kanya.
Sa kanilang kalagayan, binulag ng diyos ng sanlibutang ito ang pag-iisip ng mga hindi mananampalataya, upang huwag nilang makita ang liwanag ng ebanghelyo ng kaluwalhatian ni Cristo, na siyang larawan ng Diyos.
At sila'y kumuha ng bunga ng lupain at ibinaba iyon sa atin, at ibinalita, ‘Ang lupaing ibinibigay sa atin ng Panginoon ay mabuti.’
At tungkol sa mga malalabi sa inyo, dadalhan ko sila ng takot sa kanilang mga puso sa mga lupain ng kanilang mga kaaway. Hahabulin sila ng tunog ng isang dahong nalalaglag, at sila'y tatakas na parang tumatakas sa tabak. Sila'y mabubuwal bagaman walang humahabol sa kanila.
Sinabi ni Balaam kay Balak, “Ngayon, ako'y naparito sa iyo. Mayroon ba ako ngayong anumang kapangyarihan na makapagsalita ng anumang bagay? Ang salitang inilagay ng Diyos sa aking bibig ang aking sasabihin.”
ang iba'y inyong iligtas, na agawin ninyo mula sa apoy; at ang iba'y inyong kahabagan na may takot; na inyong kapootan maging ang damit na nadungisan ng laman.
sapagkat ang buong lupaing natatanaw mo ay ibibigay ko sa iyo, at sa iyong binhi magpakailanman.
Nang inyong marinig ang tinig mula sa gitna ng kadiliman, samantalang ang bundok ay nagliliyab sa apoy ay lumapit kayo sa akin, ang lahat ng mga pinuno sa inyong mga lipi, at ang inyong matatanda;
Nang ako'y kasama ninyo sa templo araw-araw, hindi ninyo binuhat ang inyong mga kamay laban sa akin. Subalit ito ang inyong oras, at ng kapangyarihan ng kadiliman.”
Huwag tayong maging palalo, na ginagalit ang isa't isa at naiinggit sa isa't isa.
mga mapanirang-puri, mga napopoot sa Diyos, mga walang-pakundangan, mga palalo, mga mapagmataas, mga manggagawa ng masasamang bagay, mga suwail sa mga magulang,
at tatalikod sa pakikinig sa katotohanan ang kanilang mga tainga, at babaling sa mga kathang-isip.
at ang buong toro ay ilalabas niya sa kampo sa isang dakong malinis, sa lugar na pinagtatapunan ng mga abo, at kanyang susunugin sa apoy sa ibabaw ng kahoy; ito ay susunugin sa lugar na pinagtatapunan ng mga abo.
At sinabi niya sa kanila, “Ipinahihintulot ba na gumawa ng mabuti sa araw ng Sabbath, o ang gumawa ng masama, magligtas ng buhay, o pumuksa nito?” Ngunit sila'y tahimik.
upang ipahayag ang taon ng biyaya mula sa Panginoon.”
Pagsapit ng gabi, pagkalubog ng araw, kanilang dinala sa kanya ang lahat ng mga maysakit at ang mga inaalihan ng mga demonyo.
Kaya't nakikita natin na sila'y hindi nakapasok dahil sa kawalan ng pananampalataya.
Sinabi niya sa kanila, “Sino sa inyo ang mayroong kaibigan at kayo ay pumunta sa kanya nang hatinggabi at magsabi sa kanya, ‘Kaibigan, pahiramin mo ako ng tatlong tinapay;
Ipinatawag ng hari ng Ehipto ang mga hilot at sinabi sa kanila, “Bakit ninyo ginawa ang bagay na ito at hinayaan ninyong mabuhay ang mga batang lalaki?”
Samantalang nakatitig sila sa langit at siya'y papalayo, biglang may dalawang lalaki ang tumayo sa tabi nila na may puting damit,
Sinabi ng mga alagad sa kanya, “Panginoon, kung siya'y natutulog, siya'y gagaling.”
“Subalit kapag pumasok ang pari at maingat na tiningnan ito at ang salot ay hindi na kumalat sa bahay pagkatapos na mapalitadahan, ipahahayag ng pari na malinis ang bahay, sapagkat ang sakit ay napagaling na.
Ngayon, mayroong pitong magkakapatid na lalaki. Nag-asawa ang panganay, at namatay na walang anak;
Ngunit siya'y nagsimulang magmura at sumumpa, “Hindi ko nakikilala ang taong ito na inyong sinasabi.”
Ang nagsasabing siya'y nasa liwanag at napopoot sa kanyang kapatid ay nasa kadiliman pa hanggang ngayon.
Subalit hindi nila naunawaan ang pananalitang ito at ito'y inilihim sa kanila, upang ito'y hindi nila mabatid. At natakot silang magtanong sa kanya tungkol sa salitang ito.
ay sinabi nila sa kanya, “Guro, nahuli ang babaing ito sa akto ng pangangalunya.
Siya ang aming ipinahahayag, na binabalaan ang bawat tao at tinuturuan ang bawat tao, sa buong karunungan, upang ang lahat ay maiharap naming sakdal kay Cristo.
Tinawag ito ni Laban na Jegarsahadutha, subalit tinawag ito ni Jacob na Gilead.
Iginawa niya iyon ng dalawang gintong argolya sa ilalim ng molde, sa dakong itaas ng dalawang panig, sa ibabaw ng dalawang panig, na pagsusuotan ng mga pasanan upang mabuhat.
Tumindig ka at pumunta sa Padan-aram, sa bahay ni Betuel na ama ng iyong ina. Mag-asawa ka roon mula sa mga anak ni Laban na kapatid na lalaki ng iyong ina.
Samantalang papunta kami sa dakong panalanginan, sinalubong kami ng isang aliping batang babae na may espiritu ng panghuhula at nagdadala ng maraming pakinabang sa kanyang mga amo sa pamamagitan ng panghuhula.
Anumang lumalakad sa pamamagitan ng kanyang tiyan, at lahat ng lumalakad sa pamamagitan ng apat na paa, at anumang mayroong maraming paa, maging sa lahat ng bagay na umuusad sa ibabaw ng lupa, ay huwag ninyong kakainin; sapagkat ang mga ito ay marumi.
Sa palagay ko ay hindi ako pahuhuli sa mga dakilang apostol na ito.
“Kung ikaw ang Cristo, sabihin mo sa amin.” Subalit sinabi niya sa kanila, “Kung sasabihin ko sa inyo, hindi ninyo ako paniniwalaan;
Dahil dito, marami sa kanyang mga alagad ay tumalikod at hindi na sumama sa kanya.
“Ang mga anak ni Israel ay magkakampo, bawat lalaki sa tabi ng kanyang sariling watawat, na may sagisag ng mga sambahayan ng kanyang mga ninuno; magkakampo sila na nakaharap sa toldang tipanan sa palibot nito.
At inilipat ni Abram ang kanyang tolda, at humayo at nanirahan sa gitna ng mga punong ensina ni Mamre na nasa Hebron, at siya'y nagtayo roon ng dambana sa Panginoon .
Kaya't sinabi ni Juan sa napakaraming tao na dumating upang magpabautismo sa kanya, “Kayong lahi ng mga ulupong! Sino ang nagbabala sa inyo na tumakas sa poot na darating?
Dalhin mo sina Aaron at Eleazar na kanyang anak sa bundok ng Hor.
Sila'y binibigyan ko ng buhay na walang hanggan, at kailanma'y hindi sila mapapahamak, at hindi sila aagawin ng sinuman sa aking kamay.
Kaya't namatay si Raquel at inilibing sa daang patungo sa Efrata, na siyang Bethlehem.
Kaya ikaw, kasama ang mga Levita at ang mga dayuhang naninirahang kasama mo, ay magdiriwang sa lahat ng kasaganaang ibinigay sa iyo ng Panginoon at sa iyong sambahayan.
Pagkaraan ng limang araw, ang pinakapunong pari na si Ananias ay lumusong na kasama ang ilang matatanda, at ang isang Tertulio na tagapagsalita na siyang nagharap ng sakdal sa gobernador laban kay Pablo.
“Ito ang batas para sa Nazirita na nagpanata. Ang kanyang alay sa Panginoon ay magiging ayon sa kanyang panata bilang Nazirita, bukod pa sa kanyang nakayanan; ayon sa kanyang panata na kanyang ipinangako ay gayon niya dapat gawin, ayon sa batas para sa kanyang pagkabukod bilang isang Nazirita.”
Sa gayon inalis ng Diyos ang mga hayop ng inyong ama, at ibinigay sa akin.
Halikayo, atin siyang ipagbili sa mga Ismaelita, at huwag natin siyang pagbuhatan ng kamay, sapagkat siya'y ating kapatid, at ating laman.” At pinakinggan siya ng kanyang mga kapatid.
Dinala nila sa mga Fariseo ang lalaki na dating bulag.
Sapagkat ang iyong lingkod ang siyang naging panagot sa bata sa aking ama, na nagsasabi, ‘Kapag hindi ko siya dinala sa iyo, papasanin ko ang sisi ng aking ama magpakailanman.’
“Kung ang isang lalaki ay sumiping sa isang aliping babae na nakatakdang ipakasal sa isang lalaki, at hindi pa natutubos ang babae, o hindi pa nabibigyan ng kalayaan, ay dapat magkaroon ng pagsisiyasat. Hindi sila papatayin yamang siya'y hindi pa malaya.
Sapagkat sa kanya tayo'y nabubuhay, at kumikilos, at nasa kanya ang ating pagkatao; tulad ng sinabi ng ilan sa inyong mga makata, ‘Sapagkat tayo rin ay kanyang supling.’
Nais kong manatili siyang kasama ko upang siya'y makatulong sa akin bilang kapalit mo sa panahon ng aking pagiging bilanggo para sa ebanghelyo.
Pagkatapos ay iniutos niya sa kanila na paupuin silang lahat nang pangkat-pangkat sa luntiang damo.
Kaya't si Simon Pedro ay sumampa sa bangka, at hinila ang lambat sa lupa na punô ng malalaking isda, na isandaan at limampu't tatlo, at kahit gayon karami ay hindi nasira ang lambat.
Nang makatawid na sila, dumating sila sa lupain ng Genesaret.
isang Panginoon, isang pananampalataya, isang bautismo,
Sinabi ng isa sa kanila, ng isang propeta mismo nila, ‘Ang mga taga-Creta ay laging mga sinungaling, masasamang hayop, mga batugang matatakaw.’
Ipapatong ng matatanda ng kapulungan ang kanilang kamay sa ulo ng toro sa harapan ng Panginoon , at papatayin ang toro sa harapan ng Panginoon .
Subalit kapag nakarinig kayo ng mga digmaan at ng mga bali-balita ng mga digmaan, huwag kayong mabahala. Ang mga bagay na ito'y dapat mangyari ngunit hindi pa iyon ang wakas.
Kung kayo nga na masasama ay marunong magbigay ng mabubuting kaloob sa inyong mga anak, gaano pa kaya ang inyong Ama sa langit na magbibigay ng Espiritu Santo sa mga humihingi sa kanya?”
Huwag ninyong hihiwaan ang inyong laman dahil sa namatay; ni huwag kayong maglalagay ng tatu na tanda sa inyong sarili: Ako ang Panginoon .
At ito ang sinabi niya tungkol sa Juda: “Dinggin mo, Panginoon , ang tinig ng Juda, at dalhin mo siya sa kanyang bayan: sa pamamagitan ng iyong mga kamay ay ipaglaban siya, at maging katulong laban sa kanyang mga kaaway.”
At walang sinuman sa langit, o sa ibabaw man ng lupa, o sa ilalim man ng lupa, ang makapagbukas ng aklat o makatingin man sa loob nito.
“Kahabag-habag ka, Corazin! Kahabag-habag ka, Bethsaida! Sapagkat kung sa Tiro at Sidon ginawa ang mga makapangyarihang gawa na ginawa sa inyo, matagal na sana silang nagsisi na may damit-sako at abo.
Sinabi ng Diyos, “Magkaroon ang lupa ng mga buháy na nilalang, ayon sa kanya-kanyang uri: ng mga hayop at mga nilalang na gumagapang, at ng maiilap na hayop sa lupa ayon sa kanya-kanyang uri.” At ito ay nangyari.
Aking ibinigay ang mga Levita na kaloob kay Aaron at sa kanyang mga anak mula sa mga anak ni Israel upang gawin nila ang paglilingkod sa mga anak ni Israel sa toldang tipanan, upang ipantubos sa mga anak ni Israel, at nang huwag magkaroon ng salot sa mga anak ni Israel kapag ang mga anak ni Israel ay lumalapit sa santuwaryo.”
Hindi isang bagong hikayat, baka siya magpalalo at mahulog sa kahatulan ng diyablo.
Ngunit sinabi niya, “Oo, Panginoon. Subalit maging ang mga aso ay kumakain ng mga mumo na nalalaglag mula sa hapag ng kanilang mga panginoon.”
Sumagot si Jesus at sinabi sa kanila, “Humayo kayo at sabihin ninyo kay Juan ang inyong naririnig at nakikita:
Subalit kapag ang sambayanan ay magtitipon ay hihihip kayo, ngunit huwag kayong magpapatunog ng hudyat.
At nalalaman natin na sa lahat ng mga bagay ang Diyos ay gumagawa sa ikabubuti ng mga umiibig sa kanya, sa kanila na mga tinawag alinsunod sa kanyang layunin.
Ang mga panahon ng kahangalan ay pinalampas na nga ng Diyos; ngunit ngayo'y ipinag-uutos niya sa lahat ng tao sa lahat ng dako na magsisi,
Gaya ng inyong bahagyang pagkakilala sa amin, na kami ay inyong maipagmalaki gaya ninyo na aming ipinagmamalaki sa araw ng Panginoong Jesus.
at limang biga sa mga tabla ng kabilang panig ng tabernakulo, at limang biga sa mga tabla ng tabernakulo sa dakong hulihan pakanluran.
At si Satanas ay dudurugin ng Diyos ng kapayapaan sa madaling panahon sa ilalim ng inyong mga paa. Ang biyaya nawa ng ating Panginoong Jesu-Cristo ay sumainyo.
Mapalad ang bumabasa at ang nakikinig ng mga salita ng propesiya at tumutupad ng mga bagay na nasusulat dito, sapagkat ang panahon ay malapit na.
Kaya't sinabi kay Pilato ng mga punong pari ng mga Judio, “Huwag mong isulat, ‘Ang Hari ng mga Judio,’ kundi, ‘Sinasabi ng taong ito, Ako ang Hari ng mga Judio.’”
Akong si Juan ang nakarinig at nakakita ng mga bagay na ito. At nang aking marinig at makita, nagpatirapa ako upang sumamba sa harapan ng anghel na nagpakita sa akin ng mga bagay na ito.
Ngunit nang makita ng mga punong pari at mga eskriba ang mga kahanga-hangang bagay na kanyang ginawa, at ang mga batang sumisigaw sa templo at nagsasabi, “Hosana sa Anak ni David,” ay nagalit sila.
Kasama siya ng proconsul na si Sergio Paulo na isang lalaking matalino. Kanyang ipinatawag sina Bernabe at Saulo at nais na mapakinggan ang salita ng Diyos.
Ngunit kayo, mga minamahal, alalahanin ninyo ang mga salitang sinabi noong una ng mga apostol ng ating Panginoong Jesu-Cristo,
isang ilaw upang magpahayag sa mga Hentil, at para sa kaluwalhatian ng iyong bayang Israel.”
Dinala nila ito kay Jesus at ipinatong nila ang kanilang mga damit sa batang asno at isinakay nila si Jesus doon.
kaya't kinawayan nila ang mga kasamahan nilang nasa ibang bangka upang lumapit at tulungan sila. Sila'y lumapit at pinuno ng isda ang dalawang bangka, anupa't sila'y nagpasimulang lumubog.
Sinabi ng Panginoong Diyos sa babae, “Ano itong iyong ginawa?” Sinabi ng babae, “Dinaya ako ng ahas, at ako'y kumain.”
Sumigaw si Jesus habang nagtuturo sa templo, “Ako'y inyong nakikilala at nalalaman din ninyo kung taga-saan ako. Hindi ako pumarito sa aking sariling awtoridad, subalit ang nagsugo sa akin ay siyang totoo, na hindi ninyo nakikilala.
Wala siyang nakitang kasamaan sa Jacob, ni wala siyang nakitang kasamaan sa Israel. Ang Panginoon nilang Diyos ay kasama nila, at ang sigaw ng hari ay nasa gitna nila.
Kanyang pinaluhod ang mga kamelyo sa labas ng bayan, sa tabi ng balon ng tubig nang papalubog na ang araw, panahon nang paglabas ng mga babae upang umigib ng tubig.
At sinabi ng Panginoon kay Moises, “Ibalik mo ang tungkod ni Aaron sa harap ng patotoo, upang ingatan bilang tanda laban sa mga mapaghimagsik; at nang iyong wakasan ang kanilang mga pagrereklamo laban sa akin, upang hindi sila mamatay.”
Sapagkat sinumang gumawa ng alinman sa mga karumaldumal na ito, ang mga taong gumagawa ng mga iyon ay ititiwalag sa kanilang bayan.
‘Paraanin mo ako sa iyong lupain. Sa lansangan lamang ako daraan, hindi ako liliko sa kanan ni sa kaliwa.
Ito ay dadalhin ng pari sa dambana, puputulan ng ulo, susunugin sa ibabaw ng dambana, at ang dugo'y patutuluin sa tabi ng dambana.
At lumabas ang mga hari ng Sodoma, Gomorra, Adma, Zeboyin, Bela na si Zoar; at sila'y sumama sa pakikidigma sa libis ng Siddim
Lumapit ang isang eskriba at nagsabi sa kanya, “Guro, susunod ako sa iyo saan ka man magtungo.”
Dahil dito, iyon ay batay sa pananampalataya, upang maging ayon sa biyaya; upang ang pangako ay maging tiyak para sa lahat ng binhi, hindi lamang sa nasa kautusan, kundi pati naman sa nasa pananampalataya ni Abraham (na ama nating lahat,
Si Abraham ay nag-asawa ng iba at ang kanyang pangalan ay Ketura.
bansang may mabangis na mukha na hindi igagalang ang pagkatao ng matanda, ni mahahabag sa bata.
na lubhang nayayamot sapagkat nagtuturo sila sa mga tao, at nagpapahayag na kay Jesus ay may muling pagkabuhay sa mga patay.
Puspusin nawa kayo ng Diyos ng pag-asa, ng buong kagalakan at kapayapaan sa pananampalataya, upang kayo'y sumagana sa pag-asa sa pamamagitan ng kapangyarihan ng Espiritu Santo.
“Kapag pinalawak ng Panginoon mong Diyos ang iyong nasasakupan, gaya ng kanyang ipinangako sa iyo, at iyong sasabihin, ‘Ako'y kakain ng karne,’ sapagkat ikaw ay nasasabik sa karne, ay makakakain ka ng karne hangga't nais mo.
At muli kong pinatotohanan sa bawat taong nagpatuli na siya'y may pananagutang tumupad sa buong kautusan.
Huwag lamang siyang magpaparami ng mga kabayo para sa kanyang sarili, ni pababalikin niya ang bayan sa Ehipto upang siya'y makapagparami ng mga kabayo, sapagkat sinabi sa inyo ng Panginoon , ‘Huwag na ninyong babalikan mula ngayon ang daang iyon.’
Nang sumapit na ang gabi, sila ay lumabas sa lunsod.
Hindi ko sila papalayasin sa harapan mo sa loob ng isang taon; baka ang lupa'y maging ilang, at ang mababangis na hayop ay magsidami laban sa iyo.
sapagkat bibigyan ko kayo ng salita at karunungan na hindi malalabanan o matututulan man ng lahat ng sumasalungat sa inyo.
Kaya't mula nang araw na aming marinig ito, hindi kami tumigil ng pananalangin para sa inyo at sa paghiling na kayo'y punuin ng kaalaman ng kanyang kalooban sa buong karunungan at pagkaunawang espirituwal,
Ibinuka niya ang kanyang bibig upang magsalita ng mga kalapastanganan sa Diyos, upang lapastanganin ang kanyang pangalan at ang kanyang tahanan gayundin ang mga naninirahan sa langit.
Kanilang tinipon ang mga ito nang buntun-bunton at ang lupain ay bumaho.
Pagkatapos ng mga ito ay nagpakita siya sa ibang anyo sa dalawa sa kanila noong sila'y naglalakad patungo sa bukid.
Sinabi ni Pedro kay Jesus, “Panginoon, mabuti na tayo ay naririto. Kung ibig mo, ay gagawa ako rito ng tatlong tolda, isa sa iyo, isa kay Moises, at isa kay Elias.”
Kung paanong pumasok siya sa bahay ng Diyos, noong si Abiatar ang pinakapunong pari at kumain siya ng tinapay ng paghahandog, na hindi ipinahihintulot kainin maliban ng mga pari lamang at binigyan pa niya ang kanyang mga kasamahan?”
Ako ba ngayo'y naging kaaway ninyo sa pagsasabi ko sa inyo ng katotohanan?
Ang dalawang dulo ng dalawang tanikala ay iyong ilalapat sa dalawang enggaste, at iyong ilalagay sa mga pambalikat ng efod, sa harapan.
Kaya't kinuha ng paring si Eleazar ang mga tansong suuban na inihandog ng mga nasunog; at kanilang pinitpit bilang pantakip sa dambana,
Humingi siya sa pinakapunong pari ng mga sulat para sa mga sinagoga sa Damasco upang kung siya'y makatagpo ng sinumang kabilang sa Daan, mga lalaki o mga babae, ay dadalhin niya silang nakagapos sa Jerusalem.
Mula sa kanila ay makakain ninyo ang mga ito: ang balang ayon sa kanyang uri; ang lukton ayon sa kanyang uri, ang kuliglig ayon sa kanyang uri, at ang tipaklong ayon sa kanyang uri.
At nangyari, pagkatapos ng salot, nagsalita ang Panginoon kay Moises at kay Eleazar na anak ng paring si Aaron, na sinasabi,
ang Resen, sa pagitan ng Ninive at ng Cale na isang malaking bayan.
Kung siya'y walang anak na babae, inyong ibibigay ang kanyang mana sa kanyang mga kapatid.
Gagawin kong parang alabok ng lupa ang iyong binhi, at kung mabibilang ng sinuman ang alabok ng lupa, ang iyong binhi ay mabibilang din.
Ang luwang ng bulwagan sa kanluran ay magkakaroon ng mga tabing na may limampung siko, ang haligi ng mga iyon ay sampu at ang mga patungan ng mga iyon ay sampu.
Ngayon, ako'y nagagalak hindi sapagkat kayo'y nalungkot, kundi sapagkat kayo'y nalungkot tungo sa pagsisisi, sapagkat kayo'y pinalumbay nang naaayon sa Diyos, upang kayo'y huwag magdusa ng kalugihan sa pamamagitan namin.
Subalit sinabi ni Abram kay Sarai, “Ang iyong alila ay nasa iyong kapangyarihan. Gawin mo sa kanya ang mabuti sa iyong paningin.” Pinagmalupitan siya ni Sarai at si Hagar ay tumakas.
“Tutuparin ninyo ang aking mga tuntunin. Huwag mong palalahian ang iyong mga hayop sa ibang uri; huwag mong hahasikan ang iyong bukid ng magkaibang binhi; ni huwag kang magsusuot ng damit na hinabi mula sa dalawang magkaibang uri ng hibla.
Sinabi ng mga alagad sa kanya, “Kung gayon ang kalagayan ng lalaki sa kanyang asawa, mas mabuti pang huwag mag-asawa.”
Sinabi ng Panginoon kay Aaron, “Ako'y narito, ibinigay ko sa iyo ang katungkulan sa mga handog na para sa akin, lahat ng mga banal na bagay ng mga anak ni Israel. Ibinigay ko sa iyo ang mga ito bilang bahagi; at sa iyong mga anak bilang marapat na bahagi ninyo magpakailanman.
Kung sila'y mag-asawa sa kaninuman sa mga anak ng ibang mga lipi ng mga anak ni Israel ay aalisin ang mana nila na mula sa mana ng aming mga ninuno, at idaragdag sa mana ng lipi na kinabibilangan nila; sa gayo'y aalisin ito sa manang nauukol sa amin.
Kaya't sinabi ng ilan sa mga Fariseo, “Ang taong ito'y hindi mula sa Diyos, sapagkat hindi siya nangingilin ng Sabbath.” Subalit sinabi ng iba, “Paanong makakagawa ng gayong mga tanda ang isang taong makasalanan?” At nagkaroon ng pagkakahati-hati sa kanila.
Nalalaman ninyo na siya'y nahayag upang mag-alis ng mga kasalanan; at sa kanya'y walang kasalanan.
Gayunma'y hindi pinakinggan ng Panginoon mong Diyos si Balaam; kundi ginawang pagpapala ng Panginoon mong Diyos ang sumpa sa iyo sapagkat minamahal ka ng Panginoon mong Diyos.
Sinabi nila, “Si Cornelio na isang senturion, isang taong matuwid at may takot sa Diyos, at may mabuting patotoo sa buong bansa ng mga Judio, ay pinagbilinan ng isang banal na anghel na ikaw ay ipatawag sa kanyang bahay upang marinig ang iyong mga salita.”
Subalit humarap sa kanila si Jesus at sinabi, “Mga anak na babae ng Jerusalem, huwag ninyo akong iyakan, kundi iyakan ninyo ang inyong mga sarili at ang inyong mga anak.
Sapagkat hahatulan ng Panginoon ang kanyang bayan, at mahahabag sa kanyang mga lingkod. Kapag nakita niyang ang kanilang kapangyarihan ay wala na, at wala ng nalalabi, bihag man o malaya.
upang umukit ng mga batong pang-enggaste, upang gumawa ng mga nililok na kahoy, at upang gumawa sa lahat ng sari-saring gawain.
Sapagkat ang Panginoon mong Diyos ay lumalakad sa gitna ng iyong kampo upang iligtas ka at ibigay ang iyong mga kaaway sa harapan mo, kaya't ang iyong kampo ay magiging banal upang huwag siyang makakita ng anumang kahiyahiyang bagay sa gitna ninyo at lumayo sa iyo.
sa loob ng halos apatnaraan at limampung taon. Pagkatapos ng mga bagay na ito ay kanyang binigyan sila ng mga hukom hanggang kay Samuel na propeta.
Nakita ni Maria Magdalena at ni Mariang ina ni Jose kung saan siya inilagay.
Sila'y masigasig sa inyo, subalit hindi para sa mabuting layunin; nais nilang ihiwalay kayo, upang kayo'y maging masigasig sa kanila.
Patuloy na pinangunahan ni Moises ang Israel mula sa Dagat na Pula, at sila'y lumabas sa ilang ng Shur; sila'y lumakad ng tatlong araw sa ilang at hindi nakatagpo ng tubig.
Lumabas ang mga Fariseo at agad nakipagsanggunian sa mga Herodiano laban sa kanya kung paanong siya'y mapupuksa nila.
Ang haliging ulap sa araw at ang haliging apoy sa gabi ay hindi umalis sa unahan ng taong-bayan.
Nang sumunod na araw, sumama si Pablo sa amin kay Santiago; at ang lahat ng matatanda ay naroroon.
At lumapit din ang tumanggap ng isang talento at sinabi niya, ‘Panginoon, alam kong ikaw ay taong malupit, na gumagapas ka roon sa hindi mo hinasikan, at nagtitipon ka roon sa hindi mo kinalatan ng binhi.
Itong si Jesus, ‘ang bato na itinakuwil ninyong mga tagapagtayo ang siyang naging batong panulukan.’
Pumupunta sa kanya ang mga tao mula sa buong lupain ng Judea at ang lahat ng mga taga-Jerusalem; at sila'y binabautismuhan niya sa Ilog Jordan, na nagpapahayag ng kanilang mga kasalanan.
Nang marinig ito ni Jesus ay namangha siya, at sinabi sa mga sumusunod sa kanya, “Katotohanang sinasabi ko sa inyo, kahit sa Israel man ay hindi ako nakatagpo ng ganito kalaking pananampalataya.
Pumasok ang lalaki sa bahay at kinalagan ang mga kamelyo. Binigyan ni Laban ng dayami at pagkain ang mga kamelyo, at ng tubig upang ipaghugas ng kanyang mga paa at mga paa ng mga taong kasama niya.
Sumagot si Jesus, “Sinabi ko sa inyo na, ‘Ako nga’. Kung ako ang inyong hinahanap, hayaan ninyong makaalis ang mga taong ito.”
Paanong hindi ninyo naunawaan na ang sinabi ko ay hindi tungkol sa tinapay? Ngunit mag-ingat kayo sa lebadura ng mga Fariseo at mga Saduceo!”
Halika, painumin natin ng alak ang ating ama, at tayo'y sumiping sa kanya upang mapanatili natin ang binhi ng ating ama.”
kapag naipaalam na sa kanya ang kasalanang kanyang nagawa, siya ay magdadala ng kanyang handog, isang lalaking kambing na walang kapintasan.
Mananatili kayo sa pintuan ng toldang tipanan gabi't araw sa loob ng pitong araw, at inyong tutuparin ang kautusan ng Panginoon , upang huwag kayong mamatay; sapagkat gayon ang iniutos sa akin.”
Pinahintulutan silang huwag patayin ang mga ito, kundi pahirapan ng limang buwan at ang kanilang pahirap ay gaya ng pahirap ng alakdan kung kumakagat sa isang tao.
Sinabi niya, ‘Ito ang aking gagawin. Gigibain ko ang aking mga kamalig at magtatayo ako ng mas malalaki at doon ko titipunin ang lahat ng aking mga butil at mga pag-aari.’
at kanilang nakita ang Diyos ng Israel. Sa ilalim ng kanyang mga paa ay mayroong parang isang tuntungan na yari sa mga batong zafiro, at tulad ng langit sa kaliwanagan.
Ngunit sinabi ng iba, “Pabayaan ninyo siya, tingnan natin kung darating si Elias upang iligtas siya.”
Habang umaahon si Jesus patungo sa Jerusalem, ibinukod niya ang labindalawang alagad, at sa daan ay sinabi niya sa kanila,
Kaya't idalangin ninyo na huwag mangyari ang pagtakas ninyo sa taglamig o sa Sabbath.
Ngunit ito'y sinabi niya, hindi dahil nagmamalasakit siya sa mga dukha, kundi sapagkat siya'y isang magnanakaw. At palibhasa'y nasa kanya ang supot ay kinukuha niya ang inilalagay doon.
Nang makaalis na sila, ang isang anghel ng Panginoon ay nagpakita kay Jose sa panaginip, na nagsasabi, “Bumangon ka at dalhin mo ang sanggol at ang kanyang ina, at tumakas kayo patungo sa Ehipto. Manatili kayo roon hanggang sabihin ko sa iyo, sapagkat hahanapin ni Herodes ang sanggol upang siya ay patayin.”
At anumang inyong ginagawa, sa salita, o sa gawa, gawin ninyong lahat sa pangalan ng Panginoong Jesus, na nagpapasalamat kayo sa Diyos Ama sa pamamagitan niya.
Kanyang pinuspos siya ng Espiritu ng Diyos, ng kakayahan, katalinuhan, kaalaman, at kahusayan sa lahat ng sari-saring gawain;
at tayo'y hindi niya itinangi sa kanila, kundi nilinis ang kanilang mga puso sa pamamagitan ng pananampalataya.
Sila'y mga espiritu ng mga demonyo na gumagawa ng mga tanda; pumupunta sa mga hari ng buong daigdig, upang tipunin sila sa digmaan ng dakilang araw ng Diyos na Makapangyarihan sa lahat.
Katotohanang sinasabi ko sa iyo, hindi ka makakalabas doon hanggang hindi mo nababayaran ang kahuli-hulihang kusing.
at iyon ay mamamalagi sa kanya, at kanyang babasahin sa lahat ng mga araw ng kanyang buhay, upang siya'y matutong matakot sa Panginoon niyang Diyos, upang isagawa ang lahat ng mga salita ng kautusang ito at ng mga tuntuning ito;
at maririnig ng iba at matatakot, at hindi na sila gagawa pa ng gayong kasamaan sa gitna mo.
Ang kapayapaa'y sumainyo nawa. Binabati ka ng mga kaibigan. Batiin mo ang mga kaibigan sa kani-kanilang pangalan.
Nagsalita ang Panginoon kay Moises, na sinasabi,
Nang araw ding iyon, nang sumapit na ang gabi ay sinabi niya sa kanila, “Tumawid tayo sa kabilang ibayo.”
Subalit sinabi niya sa kanila, “Hindi ba ninyo nabasa ang ginawa ni David nang nagutom siya at ang mga kasamahan niya;
Siya'y nanunuluyan kay Simon, isang tagapagluto ng balat, na ang bahay ay nasa tabi ng dagat.”
sa pamamagitan ng magiliw na habag ng ating Diyos, kapag ang pagbubukang-liwayway buhat sa itaas ay sumilay sa atin,
Sumagot sa kanila si Jesus, “Hindi ba pinili ko kayo, ang labindalawa, at ang isa sa inyo ay diyablo?”
Sinabi sa kanya, ‘Iwan mo ang iyong lupain at ang iyong mga kamag-anak at pumunta ka sa lupaing ipapakita ko sa iyo.’
Maging hayag nawa sa inyo na ang kaligtasang ito ng Diyos ay ipinadala sa mga Hentil at sila'y makikinig.” [
bukod sa mga Sabbath sa Panginoon , at bukod sa inyong mga kaloob, bukod sa lahat ng inyong panata, bukod sa lahat ng inyong mga kusang-loob na handog na inyong ibibigay sa Panginoon .
Gumawa siya ng mga pasanang kahoy na akasya, at binalot ang mga ito ng ginto.
upang ang tao ng Diyos ay maging ganap, nasasangkapang lubos sa lahat ng mga gawang mabuti.
laging nagpapasalamat sa lahat ng mga bagay sa pangalan ng ating Panginoong Jesu-Cristo, sa Diyos na ating Ama.
Sinabi ng Faraon kay Jose, “Yamang itinuro sa iyo ng Diyos ang lahat ng ito, ay walang matalino o pantas na gaya mo.
Mula sa kanyang alay na handog pangkapayapaan, bilang isang handog sa Panginoon na pinaraan sa apoy, ihahandog niya ang lahat ng tabang bumabalot sa lamang-loob at lahat ng tabang nasa lamang-loob,
Kanilang inilagay siya sa bilangguan hanggang sa ang hatol ay ipahayag sa kanila ng Panginoon .
Huwag uubusin ang bunga ng inyong ubasan, ni huwag ninyong titipunin ang mga nalaglag sa inyong ubasan; iiwan ninyo ang mga iyon para sa mga dukha at sa dayuhan: ako ang Panginoon ninyong Diyos.
At sinabi ng Panginoon , “Tingnan ninyo, sila'y iisang bayan at may isang wika; at ito ay pasimula pa lamang ng kanilang gagawin, at ngayon, walang makakapigil sa anumang kanilang binabalak gawin.
Anumang sinasabi ko sa inyo sa dilim, sabihin ninyo sa liwanag; at ang narinig ninyo sa bulong ay ipagsigawan ninyo sa ibabaw ng mga bubungan.
Gayundin naman, kayong mga kabataan, pasakop kayo sa matatanda. At kayong lahat ay magsuot ng kapakumbabaan sa inyong pakikitungo sa isa't isa, sapagkat “Ang Diyos ay sumasalungat sa mga palalo, ngunit nagbibigay ng biyaya sa mga mapagpakumbaba.”
Nang magkagayo'y sinabi sa kanya ni Pablo, “Sasaktan ka ng Diyos, ikaw na pinaputing pader! Nakaupo ka ba riyan upang ako'y hatulan ayon sa kautusan, ngunit ako'y ipinahahampas mo nang labag sa kautusan?”
Sinenyasan nila ang kanyang ama, kung ano ang ibig niyang itawag sa sanggol.
Pagtingala niya sa langit, siya'y nagbuntong-hininga, at sinabi sa kanya, “Effata,” na nangangahulugang “Mabuksan.”
at sa harapan ng trono, ay may parang isang dagat na salamin na katulad ng kristal. At sa gitna ng trono, at sa palibot ng trono ay may apat na nilalang na buháy na punô ng mga mata sa harapan at sa likuran.
Nang magkagayo'y tumayo ang anghel ng Panginoon sa isang makipot na daan sa pagitan ng mga ubasan na may bakod sa magkabilang panig.
Ang pangalan mo ay hindi na tatawaging Abram, kundi Abraham ang magiging pangalan mo; sapagkat ikaw ay ginawa kong ama ng maraming bansa.
At ito'y ibinaba niya, binalot ng isang telang lino, at inilagay sa isang libingang hinukay sa bato, na doo'y wala pang naililibing.
At nang mga araw na ito, tumindig si Pedro sa gitna ng mga kapatid at nagsabi (at nagkakatipon ang maraming tao, na may isandaan at dalawampu),
kapag dumating siya sa araw na iyon upang luwalhatiin sa kanyang mga banal, at kamanghaan ng lahat ng mga sumasampalataya, sapagkat ang aming patotoo sa inyo ay pinaniwalaan.
At sinabi ni Lamec sa kanyang mga asawa, “Ada at Zilla, pakinggan ninyo ang aking tinig. Kayong mga asawa ni Lamec ay makinig sa aking mga salita. Pumatay ako ng isang tao, dahil sa pagsugat sa akin, at ng isang binata, dahil sa ako'y sinaktan.
Ngunit ang Panginoon ay nagalit sa akin dahil sa inyo, at hindi ako pinakinggan. At sinabi sa akin ng Panginoon , ‘Huwag ka nang magsalita pa sa akin ng tungkol sa bagay na ito.
sa lipi ni Simeon ay 12,000; sa lipi ni Levi ay 12,000; sa lipi ni Isacar ay 12,000;
Ang isang kordero ay iyong ihahandog sa umaga, at ang isang kordero ay iyong ihahandog sa paglubog ng araw,
na kayo'y pinangaralan at pinalakas ang loob ninyo, at nagpatotoo, upang kayo'y lumakad nang nararapat sa Diyos, na siyang tumawag sa inyo sa kanyang sariling kaharian at kaluwalhatian.
Ang buhay ni Sara ay tumagal ng isandaan at dalawampu't pitong taon. Ito ang naging mga taon ng buhay ni Sara.
Sapagkat siya ang ating kapayapaan, na kanyang pinag-isa ang dalawa, at sa pamamagitan ng kanyang laman ay giniba ang gitnang pader ng alitang humahati.
Sapagkat ang bawat bahay ay may nagtayo, subalit ang nagtayo ng lahat ng mga bagay ay ang Diyos.
Iyong babalutin ito ng lantay na ginto, at igagawa mo ng isang moldeng ginto sa palibot.
Kaya't si Lot ay lumabas at kinausap ang kanyang mga manugang na noon ay mapapangasawa ng kanyang mga anak na babae, at sinabi, “Tumindig kayo, magsialis kayo sa lugar na ito; sapagkat gugunawin ng Panginoon ang bayan.” Subalit ang akala ng kanyang mga manugang ay nagbibiro siya.
Dadalhin ko kayo sa lupain na aking ipinangakong ibibigay kina Abraham, Isaac, at Jacob; at aking ibibigay ito sa inyo bilang pamana. Ako ang Panginoon .’”
Nang siya'y mapahintulutan na niya, si Pablo ay tumayo sa mga baytang at isinenyas ang kamay sa mga tao, at nang magkaroon ng malaking katahimikan, nagsalita siya sa wikang Hebreo, na sinasabi:
at ang mga Jebuseo, Amoreo, ang mga Gergeseo;
kung paanong ang Anak ng Tao ay naparito hindi upang paglingkuran, kundi upang maglingkod, at upang ibigay ang kanyang buhay na pantubos sa marami.”
Sapagkat mula ngayon ang lima sa isang bahay ay magkakabaha-bahagi; tatlo laban sa dalawa, at dalawa laban sa tatlo.
Katotohanang sinasabi ko sa inyo, may ilan sa nakatayo rito, na hindi makakatikim ng kamatayan, hanggang makita nila ang Anak ng Tao na dumarating sa kanyang kaharian.”
Ang huli ay gumagawa dahil sa pag-ibig, palibhasa'y nalalaman na ako'y itinalaga sa pagtatanggol sa ebanghelyo;
Nagsimulang dumami ang mga tao sa balat ng lupa at nagkaanak sila ng mga babae.
Kapag sinira ko ang tungkod ninyong tinapay, sampung babae ang magluluto ng inyong tinapay sa isa lamang hurno, at ipamamahagi sa inyo ang inyong tinapay sa pamamagitan ng timbangan. Kayo'y kakain ngunit hindi kayo mabubusog.
Sa akin kayo ay magiging isang kaharian ng mga pari at isang banal na bansa. Ito ang mga salitang sasabihin mo sa mga anak ni Israel.”
Si Moises ay bumalik kay Jetro na kanyang biyenan at nagsabi sa kanya, “Pahintulutan mo akong bumalik sa aking mga kapatid sa Ehipto at titingnan ko kung sila'y buháy pa.” Sinabi ni Jetro kay Moises, “Humayo kang payapa.”
Gayunman, dapat ibigin ng bawat isa sa inyo ang kanyang sariling asawa gaya ng kanyang sarili, at igalang ng babae ang kanyang asawa.
Sa mga anak ni Levi, narito, aking ibinigay ang lahat ng ikasampung bahagi sa Israel bilang mana, na ganti sa kanilang paglilingkod na kanilang ipinaglilingkod, samakatuwid ay sa paglilingkod sa toldang tipanan.
Sinasabi ko sa inyo, mabilis niyang bibigyan sila ng katarungan. Gayunman, pagparito ng Anak ng Tao, makakatagpo kaya siya ng pananampalataya sa lupa?”
Binabati kayo ni Aristarco na kasama kong bilanggo, at ni Marcos na pinsan ni Bernabe—tungkol sa kanya'y tumanggap kayo ng mga utos—kung magpupunta siya sa inyo, siya ay inyong tanggapin,
Kinaumagahan, si Jacob ay maagang bumangon at kinuha ang batong kanyang inilagay sa ulunan niya, at kanyang itinayo bilang bantayog at kanyang binuhusan ng langis.
Nang araw ding iyon ay iniutos ng Faraon sa mga tagapangasiwa sa mga tao at sa kanilang mga kapatas,
Huwag kayong tatanggap ng suhol sa kaninumang tumakas sa kanyang lunsod-kanlungan, upang siya'y makabalik at manirahan sa kanyang lupain bago mamatay ang pinakapunong pari.
Pinarami kayo ng Panginoon ninyong Diyos, at kayo ngayon ay gaya ng mga bituin sa langit sa dami.
Ilalagay mo ang luklukan ng awa sa ibabaw ng kaban ng tipan, sa dakong kabanal-banalan.
Ginawa rin niya ang hapag na yari sa kahoy na akasya, na dalawang siko ang haba at isang siko ang luwang at isang siko at kalahati ang taas niyon.
Nang marinig ng alipin ni Abraham ang kanilang mga salita, siya ay nagpatirapa sa lupa sa harap ng Panginoon .
At iniutos ng Panginoong Diyos sa lalaki, na sinabi, “Malaya kang makakakain mula sa lahat ng punungkahoy sa halamanan,
Ang mga iyon ay marumi para sa inyo; huwag ninyong kakainin ang laman ng mga iyan, at ang bangkay ng mga iyan ay inyong pandidirihan.
“Guluhin ninyo ang mga Midianita, at inyong daigin sila;
ay inyong sasabihin, ‘Ang iyong mga lingkod ay naging tagapag-alaga ng hayop mula sa aming pagkabata hanggang sa ngayon, kami at ang aming mga ninuno,’ upang kayo'y patirahin sa lupain ng Goshen, sapagkat bawat pastol ay kasuklamsuklam sa mga Ehipcio.”
Dinala ni Esau ang kanyang mga asawa, ang kanyang mga anak na lalaki at babae, ang lahat ng tao sa kanyang bahay, ang kanyang hayop, lahat ng kanyang kawan, at ang lahat na kanyang tinipon sa lupain ng Canaan, at pumunta sa isang lupaing malayo sa kanyang kapatid na si Jacob.
Tumindig ang buong karamihan at dinala si Jesus sa harap ni Pilato.
Subalit kapag dumating na ang Espiritu ng katotohanan, papatnubayan niya kayo sa buong katotohanan. Sapagkat hindi siya magsasalita nang mula sa kanyang sarili, kundi ang anumang bagay na kanyang marinig, iyon ang kanyang sasabihin at kanyang ipahahayag sa inyo ang mga bagay na darating.
Dalhin ninyo rito sa akin ang inyong bunsong kapatid upang aking malaman na kayo'y hindi mga espiya, kundi kayo'y mga tapat. Saka ko isasauli sa inyo ang inyong kapatid at kayo'y makakapangalakal sa lupain.’”
Tinawag niya ang isa sa mga alipin at itinanong kung ano ang kahulugan nito.
Ang mga babae na sumama sa kanya mula sa Galilea ay sumunod at tiningnan ang libingan at kung paano inilagay ang kanyang bangkay.
Kapag dinungisan ng anak na babae ng isang pari ang kanyang sarili sa pamamagitan ng pagpapaupa ay kanyang nilalapastangan ang kanyang ama; siya'y susunugin sa apoy.
ay gayundin naman si Cristo, na inihandog na minsan upang dalhin ang mga kasalanan ng marami, ay magpapakita sa ikalawang pagkakataon, hindi upang harapin ang kasalanan, kundi upang iligtas ang mga sabik na naghihintay sa kanya.
Sinabi niya sa kanila, ‘Isang kaaway ang gumawa nito.’ At sinabi sa kanya ng mga alipin, ‘Ibig mo bang kami'y pumaroon at tipunin ang mga iyon?’
Ang magiging katungkulan ng mga anak ni Gershon sa toldang tipanan ay ang tabernakulo, ang tolda at ang takip nito at ang tabing sa pintuan ng toldang tipanan,
“Bago ako nakatapos sa pagsasalita sa aking puso, nakita ko si Rebecca na lumalabas na pasan ang kanyang banga sa kanyang balikat. Siya ay lumusong sa bukal at umigib at aking sinabi sa kanya, ‘Makikiinom ako sa iyo.’
At kapag si Moises ay pumapasok sa tolda, bumababa ang haliging ulap at tumitigil sa pintuan ng tolda, at ang Panginoon ay nakikipag-usap kay Moises.
Sinumang nasa parang na humawak sa pinatay ng tabak, o sa bangkay, o sa buto ng tao, o sa libingan, ay magiging marumi sa loob ng pitong araw.
Habang sila'y nagpapatuloy ng pagtatanong sa kanya, tumayo siya at sinabi sa kanila, “Ang walang kasalanan sa inyo ang siyang unang bumato sa kanya.”
“Kung ang sinuman ay magpatago sa kanyang kapwa ng salapi o pag-aari, at ito'y ninakaw sa bahay ng taong iyon, at pagkatapos, kung matagpuan ang magnanakaw, magbabayad siya ng doble.
“Mayroon bang anumang bagay na napakahirap sa Panginoon ? Sa takdang panahon ay babalik ako sa iyo, sa tamang panahon, at si Sara ay magkakaanak ng isang lalaki.”
Dumating noon sa Efeso ang isang Judio na ang pangalan ay Apolos, na tubong Alejandria. Siya ay mahusay magsalita at dalubhasa sa mga kasulatan.
Subalit hinihiling namin sa inyo, mga kapatid, na inyong igalang ang mga nagpapagal sa inyo, at namumuno sa inyo sa Panginoon at nagtuturo sa inyo;
At ang kanang hita ay ibibigay ninyo sa pari bilang handog mula sa alay ng inyong mga handog pangkapayapaan.
At sinabi nila sa kanya, “Wala kang kamag-anak na may ganitong pangalan.”
Ngunit anumang panata ng isang babaing balo, o ng isang hiniwalayan ng asawa ay magkakabisa sa bawat bagay na doo'y itinali niya ang kanyang sarili.
Subalit hindi gayon sa inyo, ngunit ang sinumang ibig na maging dakila sa inyo ay kailangang maging lingkod ninyo;
Anim na araw na gagawin ang mga gawain, subalit ang ikapitong araw ay Sabbath na ganap na kapahingahan, isang banal na pagpupulong. Huwag kayong gagawa ng anumang gawain; ito ay Sabbath sa Panginoon sa lahat ng inyong mga paninirahan.
Ganito rin kayo maghahandog ng handog sa Panginoon sa inyong buong ikasampung bahagi, na inyong tinatanggap sa mga anak ni Israel; at ganito ninyo ibibigay sa paring si Aaron ang handog sa Panginoon .
“Sabihin mo sa mga anak ni Israel, ‘Inyong ipapangilin ang aking mga Sabbath, sapagkat ito'y isang tanda sa akin at sa inyo sa buong panahon ng inyong mga salinlahi, upang inyong makilala na akong Panginoon ang nagpapabanal sa inyo.
At magmula kay Moises at sa mga propeta ay ipinaliwanag niya sa kanila ang mga bagay tungkol sa kanya sa lahat ng mga kasulatan.
sapagkat pinalitan nila ng kasinungalingan ang katotohanan ng Diyos at sila'y sumamba at naglingkod sa nilalang sa halip na sa Lumalang, na siyang pinupuri magpakailanman! Amen.
Dadalhin nila sa loob niyon ang karangalan at kapurihan ng mga bansa;
At nagsalita ang Panginoon kay Moises, na sinasabi,
Bakit kailangang sabihin ng mga Ehipcio, ‘Dahil sa masamang layunin ay kanyang inilabas sila upang patayin sila sa mga bundok, at upang lipulin sila mula sa balat ng lupa?’ Iurong mo ang iyong mabangis na poot, at baguhin mo ang iyong isip sa kasamaang ito laban sa iyong bayan.
‘Pagkatapos ng mga bagay na ito, ako'y babalik, at muli kong itatayo ang tolda ni David na bumagsak; muli kong itatatag ang guho nito, at ito'y aking itatayo:
Ngunit sinabi ni Moises sa Panginoon , “O Panginoon, ako'y hindi mahusay magsalita, mula pa noon o kahit na mula nang magsalita ka sa iyong lingkod; sapagkat ako'y makupad sa pananalita at umid ang dila.”
Bumalik ang pitumpu na may kagalakan na nagsabi, “Panginoon, maging ang mga demonyo ay nagpapasakop sa amin sa iyong pangalan!”
Sapagkat ang mga mata ng Panginoon ay nasa mga matuwid, at ang kanyang mga tainga ay bukas sa kanilang mga panalangin. Ngunit ang mukha ng Panginoon ay laban sa mga gumagawa ng masama.”
Subalit sila'y kinilabutan at natakot at inakala nila na nakakakita sila ng isang espiritu.
Tinawag niya ang kanyang pangalan na Noe, na sinabi, “Ito ang magbibigay sa atin ng ginhawa mula sa ating gawa at sa pagpapagod ng ating mga kamay, dahil sa lupang sinumpa ng Panginoon .”
At binigkas niya ang kanyang talinghaga, na sinasabi: “Ang sabi ni Balaam na anak ni Beor, ang sabi ng taong bukas ang mga mata,
“Narito, umaahon tayo patungong Jerusalem. Ibibigay ang Anak ng Tao sa mga punong pari at sa mga eskriba; at kanilang hahatulan siya ng kamatayan.
Muli siyang naghintay ng pitong araw, at pinalipad ang kalapati at ito ay hindi na muling nagbalik sa kanya.
Ngayon nga'y pahanapin ang Faraon ng isang taong matalino at pantas at pamahalain siya sa lupain ng Ehipto.
Kanyang inilagay ang dambanang ginto sa loob ng toldang tipanan sa harap ng lambong.
At sinabi ni Jose sa kanyang ama, “Hindi ganyan, ama ko. Yamang ang isang ito ang panganay, ipatong mo ang iyong kanang kamay sa kanyang ulo.”
Nang sumapit na ang gabi, ang mga pugo ay umahon at tinakpan ang kampo at sa kinaumagahan ay nakalatag sa palibot ng kampo ang hamog.
Samantalang naglilingkod siya sa Diyos bilang pari at ang kanyang pangkat ang nanunungkulan,
Pinagkalooban niya ang iba na maging mga apostol, ang iba'y propeta, ang iba'y ebanghelista, at ang iba'y pastor at mga guro;
Naiwang nag-iisa si Jacob at nakipagbuno sa kanya ang isang lalaki hanggang sa magbukang-liwayway.
At lumaki ang bata, lumakas, napuno ng karunungan, at sumasakanya ang biyaya ng Diyos.
Kundi itinatakuwil namin ang mga kahiyahiyang bagay na nakatago. Kami ay tumatangging gumawa ng katusuhan o gamitin sa pandaraya ang salita ng Diyos, kundi sa pamamagitan ng pagpapahayag ng katotohanan ay ipinapakilala namin ang aming sarili sa bawat budhi ng mga tao sa harapan ng Diyos.
siya'y pinigilan niya sa pamamagitan ng kanyang suot, na sinasabi, “Sipingan mo ako!” Subalit naiwan ni Jose ang kanyang suot sa kamay niya, at siya'y tumakas papalabas ng bahay.
Nalalaman natin na ang ating dating pagkatao ay kasama niyang ipinako sa krus, upang ang katawang makasalanan ay mawalan ng bisa, at upang tayo'y hindi na magpaalipin pa sa kasalanan;
“At ilalapit ng pari ang babae, at pahaharapin sa Panginoon .
Sapagkat ako'y nagutom at binigyan ninyo ako ng pagkain. Ako'y nauhaw, at binigyan ninyo ako ng inumin. Ako'y taga-ibang bayan, at ako'y inyong pinatuloy.
Sa may kalayuan sa kanila ay may isang kawan ng maraming baboy na nanginginain.
Pagkatapos ay kukunin niya ang dalawang kambing at ilalagay niya sa harapan ng Panginoon sa pintuan ng toldang tipanan.
Sinabi ni Moises, “Hinihiling ko sa iyo na ipakita mo sa akin ang iyong kaluwalhatian.”
At sabihin mo sa mga anak ni Israel, ‘Kumuha kayo ng isang kambing na lalaki bilang handog pangkasalanan, at ng isang batang baka, at isang kordero na kapwa na may gulang na isang taon at walang kapintasan, bilang handog na sinusunog,
Tumagal ang tubig sa ibabaw ng lupa ng isandaan at limampung araw.
Pagkatapos na sila'y manatili roon ng ilang panahon, sila'y payapang pinabalik ng mga kapatid sa mga nagsugo sa kanila. [
Iyong ipapangilin ang Pista ng mga Sanlinggo, ang mga unang bunga ng pag-aani ng trigo, at ang kapistahan ng pagtitipon ng ani sa katapusan ng taon.
At sumagot si Jacob kay Laban, “Sapagkat ako'y natakot; iniisip ko na baka kunin mo nang sapilitan sa akin ang iyong mga anak.
Nakita ng Diyos na ang liwanag ay mabuti, at ibinukod ng Diyos ang liwanag sa kadiliman.
“Kaya't ang kaharian ng langit ay maihahambing sa isang hari, na nagnais na makipag-ayos sa kanyang mga alipin tungkol sa kanilang mga utang.
At sinabi niya sa kanila, “Ihulog ninyo ang lambat sa kanang bahagi ng bangka at mayroon kayong makikita.” Inihulog nga nila, at hindi na nila ito mahila dahil sa dami ng mga isda.
Ngunit ang kambing na nabunot para kay Azazel ay ilalagay na buháy sa harapan ng Panginoon upang itubos sa kanya, at payaunin sa ilang kay Azazel.
“Ngunit kung hindi kayo makikinig sa akin, at hindi tutuparin ang lahat ng mga utos na ito,
At nang dumating si Jesus sa lugar na iyon, siya'y tumingala, at sinabi sa kanya, “Zaqueo, dali ka at bumaba ka; sapagkat kailangang ako'y tumuloy sa bahay mo ngayon.”
Kaya't ang bukid na iyon ay tinawag na Bukid ng Dugo hanggang sa araw na ito.
At binasbasan ng Diyos ang ikapitong araw at kanyang ginawang banal, sapagkat sa araw na iyon ay nagpahinga ang Diyos sa lahat ng gawain na kanyang ginawa.
Nang makita ni Jesus na siya'y sumagot na may katalinuhan, sinabi niya sa kanya, “Hindi ka malayo sa kaharian ng Diyos.” Pagkatapos noon, wala nang nangahas na magtanong pa sa kanya ng anuman.
Subalit ipapakita ko sa inyo kung sino ang inyong dapat katakutan; katakutan ninyo siya na pagkatapos pumatay ay may kapangyarihang magtapon sa impiyerno. Oo, sinasabi ko sa inyo, siya ang inyong katakutan.
At tungkol kay Dan ay kanyang sinabi, “Si Dan ay anak ng leon, na lumukso mula sa Basan.”
Sinabi ni Jesus sa kanila, “Mga anak, mayroon ba kayong nahuling isda?” Sumagot sila sa kanya, “Wala.”
Tanging ang mga punungkahoy na nalalaman mong hindi nagbubunga ng pagkain ang iyong sisirain at puputulin; at magtatayo ka ng mga kuta laban sa bayang lumalaban sa iyo hanggang sa maibuwal mo.
At nagsalita si Moises sa Panginoon , na sinasabi,
Ang paring naglilinis sa taong lilinisin ay tatayo sa harapan ng Panginoon sa pintuan ng toldang tipanan kasama ng mga bagay na ito.
sapagkat hindi nila nauunawaan ang tungkol sa mga tinapay, kundi tumigas ang kanilang mga puso.
siya ay muling nagtakda ng isang araw, “Ngayon,” na pagkatapos ng ilang panahon ay sinabi sa pamamagitan ni David, gaya ng sinabi noong una, “Ngayon, kung marinig ninyo ang kanyang tinig, huwag ninyong papagmatigasin ang inyong mga puso.”
Kaya't umalis si Pedro kasama ang isa pang alagad at pumunta sila sa libingan.
Samantalang ginagawa ko ito, natagpuan nila ako sa templo na ginagawa ang rituwal ng paglilinis, na walang maraming tao ni kaguluhan.
Siya'y nagpakita ng lakas sa pamamagitan ng kanyang bisig; pinagwatak-watak niya ang mga palalo sa mga haka ng kanilang puso.
Katotohanang sinasabi ko sa inyo, ang sinumang tumatanggap sa aking sinugo ay tumatanggap sa akin, at ang tumatanggap sa akin ay tinatanggap siya na nagsugo sa akin.”
Sa pamamagitan ni Silvano, na itinuturing kong tapat nating kapatid, ay sinulatan ko kayo nang maikli upang pasiglahin kayo at magpatotoo na ito ang tunay na biyaya ng Diyos. Manindigan kayo rito.
Si Jose ay nag-imbak ng napakaraming trigo na gaya ng buhangin sa dagat, hanggang sa huminto siya sa pagtatala nito, sapagkat hindi na ito mabilang.
Narinig ito ng mga punong pari at ng mga eskriba at sila'y naghanap ng paraan kung paano nila siya mapapatay, sapagkat natatakot sila sa kanya dahil maraming tao ang namangha sa kanyang aral.
Nang marinig ni Jesus ang mga bagay na ito ay namangha siya sa kanya. Lumingon siya at sinabi sa maraming tao na sumusunod sa kanya, “Sinasabi ko sa inyo, maging sa Israel ay hindi pa ako nakakita ng ganito kalaking pananampalataya.”
Inilibing si Esteban ng mga taong masipag sa kabanalan, at sila'y tumangis nang malakas dahil sa kanya.
na huwag nating pabayaan ang ating pagtitipon, gaya ng ugali ng iba, kundi palakasin ang loob ng isa't isa, lalung-lalo na kapag inyong nakikita na papalapit na ang Araw.
sila'y hahawak ng mga ahas, at kung makainom sila ng bagay na nakamamatay, hindi ito makakasama sa kanila, ipapatong nila ang kanilang mga kamay sa mga maysakit, at sila'y gagaling.”
Nang masabi ni Jesus ang mga salitang ito, siya'y umalis na kasama ng kanyang mga alagad na tumawid sa libis ng Cedron, patungo sa isang pook na may isang halamanan, na pinasok niya at ng kanyang mga alagad.
Siya'y sumigaw at sinabi, ‘Amang Abraham, maawa ka sa akin, at suguin mo si Lazaro, upang itubog niya sa tubig ang dulo ng kanyang daliri, at palamigin ang aking dila, sapagkat naghihirap ako sa apoy na ito.’
Nang magkagayo'y lumapit si Juda sa kanya, at sinabi, “O panginoon ko, pahintulutan mo ang iyong lingkod na magsalita sa pandinig ng aking panginoon, at huwag nawang magningas ang iyong galit laban sa iyong lingkod, sapagkat ikaw ay kagaya ng Faraon.
sapagkat ang bumabati sa kanya ay nakikibahagi sa kanyang masasamang gawa.
Gayunma'y sinasabi ko sa inyo, kahit si Solomon sa buong kaluwalhatian niya ay hindi nakapagdamit nang tulad sa isa sa mga ito.
Huwag kayong magtatangi ng tao sa paghatol; inyong parehong papakinggan ang hamak at ang dakila; huwag kayong matatakot sa mukha ng tao; sapagkat ang paghatol ay sa Diyos, at ang bagay na napakahirap sa inyo ay inyong dadalhin sa akin, at aking papakinggan.’
Pagkatapos, sinabi niya sa kanyang mga alipin, ‘Handa na ang kasalan, ngunit hindi karapat-dapat ang mga inanyayahan.
ay mangyayari na kung iyon ay ginawa nang hindi sinasadya, at hindi nalalaman ng kapulungan, ang buong kapulungan ay maghahandog ng isang batang toro na handog na sinusunog, na mabangong samyo sa Panginoon , kasama ng handog na butil niyon at handog na inumin niyon, ayon sa batas at isang lalaking kambing na handog pangkasalanan.
Kaya't tinawag ni Abraham ang lugar na iyon Yahweh-yireh. Kaya't sinasabi hanggang sa araw na ito: “Sa bundok ng Panginoon ito ay ipagkakaloob.”
Nang gabing iyon, ang Diyos ay dumating kay Balaam at sinabi sa kanya, “Kung ang mga taong iyan ay pumarito upang tawagin ka ay bumangon ka, sumama ka sa kanila. Ngunit ang salita lamang na sasabihin ko sa iyo ang siya mong gagawin.”
Kanilang pinakinggan siya hanggang sa pagkakataong ito ngunit pagkatapos ay sumigaw sila, “Alisin sa lupa ang ganyang tao! Sapagkat hindi siya karapat-dapat mabuhay.”
Sinabi ng Panginoon kay Moises, “Humayo ka, umakyat ka mula rito, ikaw at ang bayan na iyong inilabas mula sa lupain ng Ehipto, patungo sa lupain na aking ipinangako kina Abraham, Isaac, at Jacob, na aking sinasabi, ‘Sa iyong mga anak at inapo ay aking ibibigay iyon!’
Tiningnan niya ang mga nakaupo sa palibot niya at sinabi, “Narito ang aking ina at ang aking mga kapatid!
Sa lahat ng inyong natanggap na kaloob ay inyong ihahandog ang bawat handog na ukol sa Panginoon , ang lahat ng pinakamabuti sa mga iyon, samakatuwid ay ang banal na bahagi niyon.
Ngunit kung hindi siya makinig ay magsama ka pa ng isa o dalawa, upang sa bibig ng dalawa o tatlong saksi ay mapagtibay ang bawat salita.
kung paanong si Jesus na taga-Nazaret ay binuhusan ng Diyos ng Espiritu Santo at ng kapangyarihan; kung paanong naglibot siya na gumagawa ng mabuti, at nagpapagaling ng lahat ng mga pinahihirapan ng diyablo, sapagkat kasama niya ang Diyos.
Subalit aking ibubukod sa araw na iyon ang lupain ng Goshen na tinitirhan ng aking bayan, upang huwag magkaroon doon ng pulu-pulutong na langaw, upang iyong malaman na ako ang Panginoon sa lupaing ito.
Sapagkat nang sila'y makaahon sa libis ng Escol at makita ang lupain, ay kanilang pinanghina ang loob ng mga anak ni Israel upang huwag pumasok sa lupain na ibinigay ng Panginoon sa kanila.
Umakyat si Jesus sa bundok at doo'y naupo siya na kasama ng kanyang mga alagad.
at kay Jesus na tagapamagitan ng bagong tipan, at sa dugong iwinisik na nagsasalita ng lalong mabuti kaysa dugo ni Abel.
At dumating ang isa sa pitong anghel na may pitong mangkok at nagsalita sa akin na nagsasabi, “Halika. Ipapakita ko sa iyo ang hatol sa tanyag na mahalay na babae na nakaupo sa ibabaw ng maraming tubig;
Sapagkat ang lahat ng mga propeta at ang kautusan ay nagpropesiya hanggang kay Juan;
ay sinabi ni Rebecca kay Jacob na kanyang anak, “Narinig ko ang iyong ama na nagsasabi kay Esau na iyong kapatid,
Dapat din ninyo kaming tulungan sa pamamagitan ng panalangin upang marami ang magpasalamat alang-alang sa amin para sa pagpapalang ipinagkaloob sa amin bilang kasagutan sa maraming mga panalangin.
Kaya't sinasabi ko sa inyo, ang bawat kasalanan at paglapastangan ay ipatatawad sa mga tao; ngunit ang paglapastangan laban sa Espiritu ay hindi ipatatawad.
Ang magtagumpay ay magmamana ng mga bagay na ito; at ako'y magiging Diyos niya at siya'y magiging anak ko.
Pagkatapos noo'y pumunta si Abimelec sa kanya mula sa Gerar, kasama si Ahuzath na kanyang tagapayo, at si Ficol na kapitan ng kanyang hukbo.
“Ngunit kung hindi mo papakinggan ang tinig ng Panginoon mong Diyos sa pamamagitan ng pagsasagawa ng lahat ng kanyang mga utos at tuntunin na aking iniuutos sa iyo sa araw na ito, ang lahat ng sumpang ito ay darating sa iyo at aabot sa iyo.
Sapagkat kinulong ng Diyos ang lahat sa pagsuway upang siya'y mahabag sa lahat.
upang walang sinumang makabili o makapagbili, maliban ang may tanda, samakatuwid, ng pangalan ng halimaw o ng bilang ng pangalan nito.
“Subalit tungkol sa araw at oras na iyon ay walang nakakaalam, kahit ang mga anghel sa langit, ni ang Anak kundi ang Ama lamang.
Subalit ang magtiis hanggang sa wakas ay siyang maliligtas.
at inyong nakita ang kanilang mga karumaldumal na bagay, at ang kanilang mga diyus-diyosan na yari sa kahoy, bato, pilak at ginto na nasa gitna nila.)
Hindi upang ihandog na paulit-ulit ang kanyang sarili, gaya ng pinakapunong pari na pumapasok sa Dakong Banal taun-taon na may dalang dugo na hindi mula sa kanya,
ang kaban ng patotoo at ang mga pasanan niyon, at ang luklukan ng awa;
Nang siya'y dumating sa kanya, siya'y nakatayo sa tabi ng kanyang handog na sinusunog na kasama ang mga pinuno sa Moab. At sinabi sa kanya ni Balak, “Anong sinabi ng Panginoon ?”
Ilalagay niya ang insenso sa ibabaw ng apoy sa harapan ng Panginoon upang ang mga usok ng insenso ay tumakip sa luklukan ng awa na nasa ibabaw ng patotoo, upang huwag siyang mamatay.
“Huwag mong babanggitin ang pangalan ng Panginoon mong Diyos sa walang kabuluhan, sapagkat hindi pawawalang-sala ng Panginoon ang sinumang gumagamit ng kanyang pangalan sa walang kabuluhan.
upang kayo'y maging mga anak ng inyong Ama na nasa langit, sapagkat pinasisikat niya ang kanyang araw sa masasama at sa mabubuti, at nagpapaulan sa mga matuwid at sa mga di-matuwid.
Lagi kaming nagpapasalamat sa Diyos na Ama ng ating Panginoong Jesu-Cristo, sa aming pananalangin para sa inyo,
Sa ikawalong araw ay magdadala siya ng dalawang batu-bato o dalawang batang kalapati sa pari sa pintuan ng toldang tipanan.
At nagsalita ang Panginoon kay Moises, na sinasabi,
At aking iniutos kay Josue nang panahong iyon, na sinasabi, ‘Nakita ng iyong mga mata ang lahat ng ginawa ng Panginoon mong Diyos sa dalawang haring ito; gayon ang gagawin ng Panginoon sa lahat ng mga kahariang iyong daraanan.
Bukod dito'y sinabi ng Panginoon kay Moises,
“Kapag ikaw ay lalapit sa isang bayan upang makipaglaban ay iyo ngang ihahayag ang kapayapaan doon.
Pagkaahon niya sa tubig, nakita niyang biglang nabuksan ang kalangitan, at ang Espiritu na bumababa sa kanya na tulad sa isang kalapati.
Ngunit ililigtas ang babae sa pamamagitan ng panganganak, kung sila'y mananatiling may kaayusan sa pananampalataya, pag-ibig at sa kabanalan.
Ang Faraon ay nagsugo, at walang namatay kahit isa sa kawan ng mga Israelita. Ngunit ang puso ni Faraon ay nagmatigas, at hindi niya pinayagang umalis ang taong-bayan.
ang dambana ng handog na sinusunog, at ang parilyang tanso niyon, ang mga pasanan niyon, lahat ng mga kasangkapan niyon, ang hugasan at ang patungan niyon.
Yamang gumagawa kaming kasama niya, nananawagan din kami sa inyo na huwag ninyong tanggapin ang biyaya ng Diyos nang walang kabuluhan.
Sa katapus-tapusan, mga kapatid, magalak kayo. Isaayos ninyo ang mga bagay-bagay; palakasin ninyo ang isa't isa, magkaisa kayo ng pag-iisip, mabuhay kayo sa kapayapaan at ang Diyos ng pag-ibig at ng kapayapaan ay mapapasainyo.
Kapag kayo'y dinala nila sa paglilitis at kayo'y ipinadakip, huwag kayong mabalisa kung ano ang inyong sasabihin, ngunit sabihin ninyo ang anumang ipagkaloob sa inyo sa oras na iyon, sapagkat hindi kayo ang magsasalita, kundi ang Espiritu Santo.
Subalit sila'y nagtakip ng kanilang mga tainga at sumigaw nang malakas at sama-samang sinugod siya.
Lumapit ang isa sa mga eskriba, at narinig niya ang kanilang pagtatalo, at palibhasa'y nalalamang mabuti ang pagkasagot niya sa kanila ay tinanong siya, “Alin ang pangunahing utos sa lahat?”
“Ang mga pinakauna ng mga unang bunga ng iyong lupa ay iyong dadalhin sa bahay ng Panginoon mong Diyos. “Huwag mong pakukuluan ang batang kambing sa gatas ng kanyang ina.
Kanyang sinabi, “Ako ang Diyos, ang Diyos ng iyong ama; huwag kang matakot na pumunta sa Ehipto sapagkat doo'y gagawin kitang isang dakilang bansa.
Samantala, si Tiquico ay sinugo ko sa Efeso.
Subalit tungkol sa Israel ay sinasabi niya, “Sa buong araw ay iniunat ko ang aking mga kamay sa isang suwail at mapagsalungat na bayan.”
na iniingatan ang pananampalataya at ang mabuting budhi. Sa pamamagitan ng pagtatakuwil sa budhi, ang ibang tao ay nakaranas ng pagkawasak ng barko sa kanilang pananampalataya;
At sa ikalimang taon ay makakakain na kayo ng bunga niyon upang lalong magbunga ang mga ito para sa inyo: Ako ang Panginoon ninyong Diyos.
At sa loob ng maraming mga araw ay nakita siya ng mga kasama niyang pumunta buhat sa Galilea patungo sa Jerusalem, na siyang mga saksi niya ngayon sa taong-bayan.
At kanyang ginawa ang dambana ng insenso na yari sa kahoy na akasya; isang siko ang haba at isang siko ang luwang niyon; parisukat iyon, at dalawang siko ang taas; ang mga sungay niyon ay kaisang piraso niyon.
Sinabi sa kanya ni Jesus, “Ako ang daan, at ang katotohanan, at ang buhay. Sinuman ay hindi makakarating sa Ama kundi sa pamamagitan ko.
Nang araw ding iyon, pumasok sa daong si Noe, sina Sem, Ham, at Jafet na mga anak ni Noe, ang asawa ni Noe, at ang tatlong asawa ng kanyang mga anak na kasama nila,
Nang buksan niya ang ikalimang tatak ay nakita ko sa ilalim ng dambana ang mga kaluluwa ng mga pinaslang dahil sa salita ng Diyos, at dahil sa patotoong taglay nila.
Kaya't tinanong niya ang mga tagapamahala ng Faraon na mga kasama niya sa bilangguan sa bahay ng kanyang panginoon, “Bakit balisa kayo ngayon?”
Nang makita siya ni Shekem, anak ni Hamor na Heveo na siyang pinuno sa lupain, kanyang kinuha siya at sapilitang sinipingan.
at ang kumain ng bangkay nito ay maglalaba ng kanyang damit, at magiging marumi hanggang sa paglubog ng araw; at ang bumuhat ng bangkay nito ay maglalaba ng kanyang damit, at magiging marumi hanggang sa paglubog ng araw.
Sa ikaanim na araw, kapag sila'y maghahanda ng kanilang dala, iyon ay doble ang dami ng kanilang pinupulot sa araw-araw.”
Kayo'y maninirahang kasama namin, at ang lupain ay magiging bukas sa inyo. Mangalakal kayo at magkaroon kayo ng mga pag-aari dito.”
na sa kanya'y nakiapid ang mga hari sa lupa, at ang mga naninirahan sa lupa ay nalasing sa alak ng kanyang pakikiapid.
Nang makaraan ang tatlong taon, nagtungo ako sa Jerusalem upang dalawin si Cefas, at namalaging kasama niya ng labinlimang araw.
tinuturuan nang may kaamuan ang mga sumasalungat, baka sakaling pagkalooban ng Diyos ng pagsisisi tungo sa pagkakilala sa katotohanan,
(Nang sabihing, “Umakyat siya,” anong ibig sabihin nito, kundi siya'y bumaba rin sa mas mababang bahagi ng lupa?
“Kung muling bumalik ang salot, at lumitaw sa bahay pagkatapos na maalis ang mga bato at pagkatapos ipakayod ang bahay, at pagkatapos na mapalitadahan,
na siyang nagpakain sa iyo ng manna sa ilang, na hindi nakilala ng iyong mga ninuno; upang kanyang papagkumbabain at subukin ka, at gawan ka ng mabuti sa bandang huli.
Sumagot sila, “Si Jesus na taga-Nazaret.” Sinabi sa kanila ni Jesus, “Ako nga iyon.” Si Judas na nagkanulo sa kanya ay nakatayong kasama nila.
Ngunit sinabi ni Jesus, “Huwag ninyo siyang pagbawalan, sapagkat walang taong gumagawa ng makapangyarihang gawa sa pangalan ko ang agad na makapagsasalita ng masama tungkol sa akin.
Gayunman ay hindi niya hinayaang mawalan siya ng saksi sa paggawa ng mabuti—na nagbigay sa inyo ng ulan mula sa langit at ng masasaganang panahon, at pinupuno kayo ng pagkain at ang inyong mga puso ng kagalakan.”
At ito ay aming ginagawa upang huwag kaming malamangan ni Satanas, sapagkat kami ay hindi mangmang tungkol sa kanyang mga balak.
Ito ang mga pangalan ng mga anak ni Aaron, na mga paring binuhusan ng langis, na kanyang itinalaga upang maglingkod bilang mga pari.
Ngunit kapag ikaw ay naglilimos, huwag mong hayaang malaman ng iyong kaliwang kamay ang ginagawa ng iyong kanang kamay,
At kung matagpuan niya ito ay katotohanang sinasabi ko sa inyo, magagalak siya rito nang higit kaysa siyamnapu't siyam na hindi naligaw.
Sumagot sa kanya ang lalaking may sakit, “Ginoo, walang taong maglusong sa akin sa tipunan ng tubig kapag kinakalawkaw ang tubig; at samantalang ako'y lumalapit ay nakalusong na muna ang iba bago ako.”
Kaya't ako'y nakikiusap sa inyo na papagtibayin ninyo ang inyong pag-ibig sa kanya.
at upang ang mga Hentil ay lumuwalhati sa Diyos dahil sa kanyang kahabagan, gaya ng nasusulat, “Kaya't ikaw ay aking pupurihin sa gitna ng mga Hentil, at aawit ako ng papuri sa iyong pangalan.”
Nang kanyang mapangisay siya, ang masamang espiritu ay sumigaw nang malakas na tinig, at lumabas sa tao.
“Kaya't ingatan ninyong mabuti ang inyong sarili. Yamang wala kayong nakitang anumang anyo nang araw na magsalita ang Panginoon sa inyo sa Horeb mula sa gitna ng apoy,
Huwag ninyong gagawin ang gaya ng ginagawa sa lupain ng Ehipto na inyong tinirahan; at huwag din ninyong gagawin ang gaya ng ginagawa nila sa lupain ng Canaan, na pinagdadalhan ko sa inyo. Huwag kayong lalakad ng ayon sa mga alituntunin nila.
“Dadalhin ka ng Panginoon at ang haring ilalagay mo upang manguna sa iyo sa isang bansang hindi mo nakilala, maging ng iyong mga ninuno at doo'y maglilingkod ka sa ibang mga diyos na yari sa kahoy at bato.
Idinadalangin ko na ang inyong pag-ibig ay lalo pang sumagana sa kaalaman at sa lahat ng pang-unawa;
Ngunit ito'y kanilang sinabi upang siya'y subukin, upang sa kanya'y may maiparatang sila. Subalit yumuko si Jesus, at isinulat ang kanyang daliri sa lupa.
“Magsugo ka ng mga lalaki upang lihim na siyasatin ang lupain ng Canaan, na aking ibibigay sa mga anak ni Israel. Isang lalaki sa bawat isa sa mga lipi ng kanilang mga ninuno ay susuguin ninyo, na bawat isa'y pinuno sa kanila.”
Kapag napainom na siya ng tubig, at mangyari kung kanyang dinungisan ang kanyang sarili, at siya'y nagtaksil sa kanyang asawa, ang tubig na nagdadala ng sumpa ay papasok sa kanya at magbubunga ng matinding hapdi. Ang kanyang katawan ay mamamaga at ang kanyang hita ay lalaylay; at ang babae ay magiging sumpa sa gitna ng kanyang bayan.
Subalit siya'y tumanggi at sinabi niya sa asawa ng kanyang panginoon, “Tingnan mo, ang aking panginoon ay hindi nakikialam sa akin tungkol sa anumang bagay na nasa bahay, at lahat ng kanyang pag-aari ay ipinamahala sa aking kamay.
Sumagot si Jesus sa kanya, “Ikaw ay isang guro sa Israel at hindi mo nauunawaan ang mga bagay na ito?
Ngunit taglay namin ang kayamanang ito sa mga sisidlang-lupa, upang ipakita na ang nag-uumapaw na kapangyarihan ay mula sa Diyos, at hindi mula sa amin.
sa pag-asa sa buhay na walang hanggan. Bago pa nagsimula ang mga panahon, ito ay ipinangako ng Diyos na hindi nagsisinungaling.
Sinabi sa kanila ni Jesus, “Dalhin ninyo rito ang ilang isdang nahuli ninyo ngayon.”
At kanyang itinaboy ang lalaki; at inilagay sa silanganan ng halamanan ng Eden ang mga kerubin at ang isang nagniningas na tabak na umiikot, upang bantayan ang daang patungo sa punungkahoy ng buhay.
Subalit kung maliwanag na sasabihin ng alipin, ‘Mahal ko ang aking amo, ang aking asawa, at ang aking mga anak, ako'y hindi aalis na malaya;’
At sinagot siya ng anghel, “Ako si Gabriel na tumatayo sa harapan ng Diyos. Ako'y sinugo upang makipag-usap at ipahayag sa iyo itong magandang balita.
Subalit kung may anumang pinsalang sumunod, magbibigay ka nga ng buhay para sa buhay,
Ngunit hindi kayo dapat tawaging Rabi, sapagkat iisa ang inyong guro, at kayong lahat ay magkakapatid.
Naghahanap ng paraan ang mga punong pari at ang mga eskriba kung paano nila maipapapatay si Jesus sapagkat natatakot sila sa mga tao.
At kapag ang mga nilalang na buháy ay nagbibigay ng kaluwalhatian, karangalan, at pasasalamat sa nakaupo sa trono, doon sa nabubuhay magpakailanpaman,
Kaya't siya'y nagmadali, bumaba, at natutuwa siyang tinanggap.
Alam ni Jesus na ibinigay na ng Ama ang lahat ng mga bagay sa kanyang mga kamay, at siya'y nanggaling sa Diyos at patungo sa Diyos.
Kayo mismo ay aking mga saksi na sinabi kong, ‘Hindi ako ang Cristo, kundi ako'y sinugong una sa kanya.’
At sinabi ni Abimelec, “Ang lupain ko ay nasa harapan mo; manirahan ka kung saan mo gusto.”
At kapag tinawag kayo ng Faraon, at sasabihin, ‘Ano ang inyong hanapbuhay?’
Ang mga bagay na ito ay isinulat ko sa inyo upang inyong malaman na kayo'y mayroong buhay na walang hanggan sa inyong nananampalataya sa pangalan ng Anak ng Diyos.
Maghahandog din kayo ng isang kambing na lalaki bilang handog pangkasalanan, at ng dalawang korderong lalaki na isang taong gulang bilang alay na mga handog pangkapayapaan.
Sapagkat tayong lahat ay natitisod sa maraming bagay. Kung ang sinuman ay hindi natitisod sa pananalita, ito ay isang taong sakdal, may kakayahang pigilan ang buong katawan.
Mula sa mga araw ni Juan na Tagapagbautismo hanggang ngayon, ang kaharian ng langit ay sapilitang pinapasok at sinasakop ng mga taong mararahas.
patungkol sa mga hari at sa lahat ng nasa mataas na katungkulan upang tayo'y mamuhay na tahimik at payapa sa buong kabanalan at paggalang.
Sapagkat ang Hesbon ay siyang bayan ni Sihon na hari ng mga Amoreo, na siyang nakipaglaban sa unang hari sa Moab, at sumakop ng buong lupain niyon sa kanyang kamay hanggang sa Arnon.
Nang marinig ito ni Jesus, umalis siya roon na sakay ng isang bangka tungo sa isang ilang na lugar na wala siyang kasama. Nang mabalitaan ito ng maraming tao, naglakad silang sumunod sa kanya mula sa mga bayan.
Sapagkat ang bawat isa na gumagawa ng masama ay napopoot sa ilaw, at hindi lumalapit sa ilaw, upang ang kanyang mga gawa ay huwag malantad.
Nang masabi ni Jesus ang mga bagay na ito, siya'y nabagabag sa espiritu, at nagpatotoo, “Katotohanang sinasabi ko sa inyo, ako'y ipagkakanulo ng isa sa inyo.”
Pitong araw na kakain kayo ng tinapay na walang pampaalsa, at sa ikapitong araw ay magkakaroon ng isang kapistahan sa Panginoon .
Agad siyang bumagsak sa kanyang paanan at namatay. Pumasok ang mga kabinataan at natagpuan nilang patay siya. Siya'y kanilang inilabas at inilibing sa tabi ng kanyang asawa.
Ang mga punong pari at ang mga Fariseo ay nag-utos na sinumang nakakaalam ng kinaroroonan ni Jesus ay dapat ipagbigay-alam sa kanila upang siya'y kanilang madakip.
Ang toro na handog pangkasalanan at ang kambing na handog pangkasalanan, na ang dugo ay ipinasok upang ipantubos sa dakong banal ay ilalabas sa kampo; at susunugin nila sa apoy ang mga balat, ang laman, at ang dumi ng mga iyon.
gayundin ang pangalawa;
Kaya't nanirahan si Esau sa bundok ng Seir. Si Esau ay si Edom.
Sa kanyang paglalakad, nakita niya ang isang lalaking bulag mula pa sa kanyang pagkapanganak.
At alam kong ako'y lagi mong pinapakinggan. Ngunit ito'y sinabi ko alang-alang sa maraming taong nasa palibot, upang sila'y sumampalataya na ako ay sinugo mo.”
Araw-araw, sa templo at sa mga bahay-bahay, hindi sila tumigil sa pagtuturo at pangangaral na si Jesus ang Cristo.
Tinawag niya ang pangalan ng dakong iyon na Massah at Meriba, dahil sa pakikipagtalo ng mga anak ni Israel, at dahil kanilang sinubok ang Panginoon , na kanilang sinasabi, “Ang Panginoon ba'y nasa kalagitnaan natin o wala?”
Sapagkat sinabi ng Panginoon tungkol sa kanila, “Sila'y tiyak na mamamatay sa ilang.” At walang natira kahit isang tao sa kanila, liban kay Caleb na anak ni Jefone, at kay Josue na anak ni Nun.
Kundi iyong lilipulin sila: ang Heteo, Amoreo, Cananeo, Perezeo, Heveo, at ang Jebuseo, gaya ng iniutos sa iyo ng Panginoon mong Diyos,
Nang makita ng buong kapulungan na si Aaron ay patay na, ang buong sambahayan ni Israel ay tumangis para kay Aaron sa loob ng tatlumpung araw.
Mga kapatid, kunin ninyong halimbawa ng pagtitiis at ng pagtitiyaga ang mga propeta na nagsalita sa pangalan ng Panginoon.
Gagawin mo ang dambana na may guwang sa gitna sa pamamagitan ng mga tabla. Tulad ng ipinakita sa iyo sa bundok ay gayon ang gagawin nila.
Kung hindi, ang tagapaghiganti ng dugo, samantalang nag-iinit sa galit, ay hahabulin ang nakamatay at aabutan siya, sapagkat ang daan ay mahaba, at siya'y saktan ng malubha, gayong siya'y hindi dapat patayin yamang hindi niya naging kaaway nang panahong nakaraan.
At sinabi ng Panginoon sa akin, ‘Tumindig ka, at pangunahan mo ang taong-bayan; sila'y papasok at kanilang aangkinin ang lupain na aking ipinangako sa kanilang mga ninuno upang ibigay sa kanila.’
at sinabi niya, “Ikaw na anak ng diyablo, at kaaway ng lahat ng katuwiran, punung-puno ng lahat ng pandaraya at panlilinlang, hindi ka ba titigil sa pagbaluktot sa matutuwid na daan ng Panginoon?
Nang malapit na siya sa libis ng bundok ng mga Olibo, ang lahat ng napakaraming mga alagad ay nagpasimulang magalak at magpuri sa Diyos nang may malakas na tinig dahil sa lahat ng mga makapangyarihang gawa na kanilang nakita,
Sapagkat kakaunti ang ari-arian mo bago ako dumating, at ito ay dumami nang sagana. Pinagpala ka ng Panginoon saan man ako bumaling; at ngayo'y kailan naman ako maghahanda ng para sa aking sariling bahay?”
Nakita ng kanyang amo na ang Panginoon ay kasama niya, at ang lahat ng ginagawa ni Jose ay umuunlad sa kanyang kamay.
Subalit sinabi ng ahas sa babae, “Tiyak na hindi kayo mamamatay.
“Ito ang iyong gagawin sa kanila upang italaga sila, at makapaglingkod sa akin bilang mga pari. Kumuha ka ng isang guyang toro at ng dalawang lalaking tupa na walang kapintasan,
At nagsipag-asawa sina Abram at Nahor. Ang pangalan ng asawa ni Abram ay Sarai, at ang pangalan ng asawa ni Nahor ay Milca, na anak na babae ni Haran na ama nina Milca at Iscah.
Sinabi ng paring si Eleazar sa mga mandirigma ng hukbo na pumunta sa pakikipaglaban, “Ito ang tuntunin ng kautusan na iniutos ng Panginoon kay Moises:
Magsasabi siya sa iyo ng mga salitang ikaliligtas mo, ikaw at ng buong sambahayan mo.’
Kukunin ng pari mula sa butil na handog ang bahaging pinakaalaala nito at susunugin sa ibabaw ng dambana, isang handog na pinaraan sa apoy, na mabangong samyo sa Panginoon .
Lalaki at babae silang nilalang, at sila'y binasbasan at tinawag na Adan ang kanilang pangalan, nang araw na sila'y lalangin.
Sinumang gumawa ng gaya niyan, o sinumang gumamit niyan sa isang dayuhan ay ititiwalag sa kanyang bayan.’”
Kung maghihimagsik si Satanas laban sa kanyang sarili at magkabaha-bahagi, hindi siya makakatayo, kundi siya'y magwawakas.
Gagawin kong ilang ang lupain, at ang inyong mga kaaway na nakatira roon ay magtataka.
mula sa dugo ni Abel hanggang sa dugo ni Zacarias, na pinatay sa pagitan ng dambana at ng santuwaryo. Oo, sinasabi ko sa inyo, na ito'y hihingin sa lahing ito.
Gagawa ka ng isang bintana sa sasakyan at tapusin mo ito ng isang siko sa dakong itaas. Ilalagay mo ang pintuan ng sasakyan sa kanyang tagiliran. Gagawin mo ito na may una, ikalawa at ikatlong palapag.
Pagkatapos, siya'y bumalik mula sa lupain ng Tiro at dumaan sa Sidon patungo sa lawa ng Galilea, na tinahak ang lupain ng Decapolis.
at ang dambana ng insenso, kasama ang mga pasanan niyon, ang langis na pambuhos, ang mabangong insenso, at ang tabing para sa pintuan na nasa pasukan ng tabernakulo;
at ang lahat ng mga kapatid na kasama ko, Sa mga iglesya ng Galacia:
Lahat ng mga ito ay inilagay niya sa mga kamay ni Aaron at sa kamay ng kanyang mga anak, at iwinawagayway bilang handog na iwinawagayway sa harapan ng Panginoon .
Ngunit kung ang pari ay bumili ng isang tao sa pamamagitan ng kanyang salapi, siya ay makakakain din nito; gayundin ang ipinanganak sa kanyang bahay ay makakakain ng kanyang tinapay.
“Kung magkaroon ng usapin ang mga tao at sila'y pumunta sa hukuman, at sila'y hahatulan; kanilang pawawalang-sala ang matuwid at parurusahan ang salarin.
“Sabihin mo kay Aaron at sa kanyang mga anak, ito ang kautusan tungkol sa handog pangkasalanan: sa dakong pinagpapatayan ng handog na sinusunog ay doon papatayin sa harapan ng Panginoon ang handog pangkasalanan; ito ay kabanal-banalang bagay.
“Simon, Simon, narito, hiningi ni Satanas na ligligin kayo gaya ng trigo,
Ang mga bagay na ito ay sinabi ko sa inyo, upang sa akin ay magkaroon kayo ng kapayapaan. Sa sanlibutan ay nahaharap kayo sa paguusig. Ngunit lakasan ninyo ang inyong loob, dinaig ko na ang sanlibutan.”
Sinabi naman niya sa kanila ang isang talinghaga: “Maaari bang akayin ng bulag ang isa pang bulag? Hindi kaya sila kapwa mahulog sa hukay?
Ang dalawang lipi na ito, at ang kalahating lipi ay tumanggap na ng kanilang mana sa kabila ng Jordan sa dakong silangan ng Jerico, sa dakong sinisikatan ng araw.”
At kumuha siya ng isang saro at nang makapagpasalamat ay ibinigay sa kanila, na nagsasabi, “Uminom kayong lahat nito,
Ilalabas niya ang toro sa kampo at susunugin ito gaya ng pagkasunog sa unang toro; ito ay handog pangkasalanan para sa kapulungan.
Kinaumagahan, si Lea pala iyon! At kanyang sinabi kay Laban, “Ano itong ginawa mo sa akin? Hindi ba pinaglingkuran kita dahil kay Raquel? Bakit mo ako dinaya?”
At nang malapit na ang ikalabing-isang oras, lumabas siya at nakakita siya ng iba na nakatayo; at sinabi niya sa kanila, ‘Bakit nakatayo kayo rito sa buong maghapon na walang ginagawa?’
Si Juan ay nagsusuot ng damit na yari sa balahibo ng kamelyo at ng isang pamigkis na balat sa kanyang baywang. Ang kanyang pagkain ay mga balang at pulot-pukyutan.
Subalit nang dumating ang anak mong ito na lumustay ng iyong kabuhayan sa masasamang babae ay ipinagpatay mo pa siya ng pinatabang guya.’
Kapwa ninyo ilalabas ang lalaki at babae. Sa labas ng kampo ninyo sila ilalagay upang hindi madungisan ang kanilang kampo na aking tinitirhan.”
“At iaalay ni Aaron ang toro bilang handog pangkasalanan para sa kanyang sarili, at itutubos niya sa kanya at sa kanyang sambahayan.
Huwag kang mag-aasawa sa kanila, ang iyong anak na babae ay huwag mong ibibigay sa kanyang anak na lalaki, ni ang kanyang anak na babae ay kukunin mo para sa iyong mga anak na lalaki.
Subalit sa araw na makitaan siya ng lamang buháy, siya ay magiging marumi.
Sila'y pumihit at umahon sa lupaing maburol at dumating sa libis ng Escol, at kanilang lihim na siniyasat.
Limampung silo ang ginawa niya sa isang tabing, at limampung silo ang ginawa niya sa gilid ng tabing na nasa ikalawang pangkat: ang mga silo ay magkakatapat sa isa't isa.
Ngunit hindi niya ito nakilala hanggang sa maipanganak nito ang isang lalaki na pinangalanan niyang Jesus.
Ang alipin ng Panginoon ay hindi dapat makipag-away, kundi maamo sa lahat, mahusay magturo, matiyaga,
Siya'y kukuha mula sa kapulungan ng mga anak ni Israel ng dalawang kambing na lalaki bilang handog pangkasalanan, at ng isang tupang lalaki bilang handog na sinusunog.
At siya'y may isang kapatid na tinatawag na Maria na naupo sa paanan ng Panginoon at nakinig sa kanyang salita.
Si Moises ay nagsugo upang tiktikan ang Jazer, at kanilang sinakop ang mga bayan niyon at pinalayas nila ang mga Amoreo na naroroon.
At tungkol kay Zebulon ay kanyang sinabi, “Magalak ka, Zebulon, sa iyong paglabas; at ikaw, Isacar, sa iyong mga tolda.
Ang taong-bayan ay tumayo sa malayo at si Moises ay lumapit sa makapal na kadiliman na kinaroroonan ng Diyos.
Gayunma'y sinasabi ko sa inyo ang katotohanan. Makakabuti sa inyo na ako'y umalis, sapagkat kung hindi ako aalis, ang Mang-aaliw ay hindi darating sa inyo. Ngunit kung ako'y umalis, siya'y susuguin ko sa inyo.
Sinasabi ni Pablo sa kanyang pagtatanggol, “Hindi ako nagkasala ng anuman laban sa kautusan ng mga Judio, ni laban sa templo, ni laban kay Cesar.”
Sapagkat may tatlong nagpapatotoo:
At sina Moises at Aaron ay pumunta sa harapan ng toldang tipanan.
At ang nagkanulo sa kanya ay nagbigay sa kanila ng isang hudyat, na sinasabi, “Ang aking halikan ay iyon na; hulihin ninyo siya at dalhin siyang may bantay.”
Ikaw at ang iyong anak na lalaki at babae, at ang iyong aliping lalaki at babae, ang Levita, ang dayuhan, ang ulila, at ang babaing balo na kasama ng iyong mga bayan ay magagalak sa iyong pagpipista.
Ngunit, kanyang sinabi, “Hindi mo maaaring makita ang aking mukha; sapagkat hindi ako maaaring makita ng tao at siya'y mabubuhay.”
Kaya't ang mga Judio'y nagtalu-talo, na sinasabi, “Paanong maipakakain sa atin ng taong ito ang kanyang laman?”
Noon, taun-taon ay nagtutungo ang kanyang mga magulang sa Jerusalem sa kapistahan ng Paskuwa.
Mayroong isang tao na isinugo mula sa Diyos na ang pangalan ay Juan.
Ang matatanda ng Moab at Midian ay pumaroon na dala sa kanilang kamay ang mga upa para sa panghuhula; at sila'y dumating kay Balaam at sinabi nila sa kanya ang mga sinabi ni Balak.
At mangyayari na gagawin ko sa inyo ang inisip kong gawin sa kanila.’”
Subalit ang Panginoon ay nagsalita kay Moises at kay Aaron, at pinagbilinan sila tungkol sa mga anak ni Israel, at kay Faraon na hari ng Ehipto, upang ilabas ang mga anak ni Israel sa lupain ng Ehipto.
Katotohanang sinasabi ko sa inyo, sa mga ipinanganak ng mga babae ay wala pang lumitaw ni isa na higit na dakila kaysa kay Juan na Tagapagbautismo; gayunman, ang pinakamaliit sa kaharian ng langit ay higit na dakila kaysa kanya.
Sila'y sinidlan ng malaking takot at sinabi sa isa't isa, “Sino nga ito, na pati ang hangin at ang dagat ay sumusunod sa kanya?”
Umiyak si Jesus.
Ngunit kung manganak siya ng babae, siya ay magiging marumi sa loob ng dalawang linggo, gaya ng sa kanyang panahon ng pagkakaroon ng regla; siya'y magpapatuloy sa panahon ng kanyang paglilinis sa dugo sa loob ng animnapu't anim na araw.
na nangangaral na may katapangan sa pangalan ng Panginoon. Siya'y nagsalita at nakipagtalo sa mga Helenista at pinagsikapan nilang siya'y patayin.
Ngunit sinabi nila, “Huwag sa kapistahan, baka magkagulo ang mga taong-bayan.”
“Sabihin mo kay Aaron, sa kanyang mga anak, at sa lahat ng mga anak ni Israel: Sinuman sa sambahayan ni Israel o sa mga dayuhan sa Israel, na maghahandog ng kanyang alay, maging kabayaran sa isang panata o bilang inialay sa Panginoon bilang handog na sinusunog,
“Tuparin mo ang mga iniutos ko sa iyo sa araw na ito. Tingnan mo, aking pinalalayas sa harap mo ang mga Amoreo, mga Cananeo, mga Heteo, mga Perezeo, mga Heveo, at ang mga Jebuseo.
at may lahat ng mapandayang kasamaan para sa mga napapahamak, sapagkat tumanggi silang ibigin ang katotohanan upang sila'y maligtas.
Makipaglaban ka sa mabuting pakikipaglaban ng pananampalataya, panghawakan mo ang buhay na walang hanggan na dito'y tinawag ka, at ipinahayag mo ang mabuting pagpapahayag sa harapan ng maraming mga saksi.
ikaw at ang iyong anak na lalaki at babae, ang iyong aliping lalaki at babae, ang Levita na nasa loob ng iyong mga bayan, ang dayuhan, ang ulila, ang babaing balo na kasama mo ay magagalak sa harapan ng Panginoon sa lugar na pipiliin ng Panginoon mong Diyos na titirahan ng kanyang pangalan.
ang kamay ng Panginoon ay magbibigay ng matinding salot sa iyong hayop na nasa parang, sa mga kabayo, mga asno, mga kamelyo, mga baka, at sa mga kawan.
Walang babaing makukunan, o magiging baog man sa iyong lupain; aking lulubusin ang bilang ng iyong mga araw.
Lahat ng mga balong hinukay ng mga alipin ng kanyang amang si Abraham ay pinagtatabunan at pinuno ng lupa ng mga Filisteo.
At si Moises ay nagsalita sa mga anak ni Israel upang ipangilin ang paskuwa.
Pagkatapos, iyong dadalhin ang kanyang mga anak, at susuotan mo sila ng mga tunika,
At sinabi niya sa kanila, “Tinanggap ba ninyo ang Espiritu Santo nang kayo'y nanampalataya?” Sinabi nila, “Hindi, ni hindi pa namin narinig na may Espiritu Santo.”
Kaya't nagbalik siya kay Juda, at sinabi, “Hindi ko siya natagpuan; at sinabi rin ng mga tao sa lugar na iyon, ‘Walang upahang babae rito.’”
Kinabukasan, pagkatapos ng araw ng Paghahanda, ang mga punong pari at ang mga Fariseo ay nagpulong sa harapan ni Pilato,
kundi magsusuot ng sandalyas at hindi magsusuot ng dalawang tunika.
Ang mga angkan ng mga Gershonita ay magkakampo sa likuran ng tabernakulo sa dakong kanluran.
Subalit sinabi ni Jesus sa kanya, “Hayaan mong ilibing ng mga patay ang kanilang sariling patay. Subalit para sa iyo, humayo ka at ipahayag mo ang kaharian ng Diyos.”
sina Ofir, Havila, at Jobab. Lahat ng ito ay mga naging anak ni Joktan.
Kaya't isinugo sila ng iglesya sa kanilang paglalakbay, at pagdaan nila sa Fenicia at Samaria, iniulat nila ang pagbabagong-loob ng mga Hentil at sila'y nakapagbigay ng malaking kagalakan sa lahat ng mga kapatid.
At pinasimulan nilang pagpugayan siya, “Mabuhay, Hari ng mga Judio!”
Tinatawagan ko ang langit at ang lupa bilang saksi laban sa inyo sa araw na ito, na aking inilagay sa harapan mo ang buhay at kamatayan, ang pagpapala at sumpa. Kaya't piliin mo at ng iyong binhi ang buhay upang ikaw ay mabuhay.
Nang buksan niya ang ikatlong tatak, narinig ko ang ikatlong nilalang na buháy, na nagsasabi, “Halika!” At nakita ko ang isang kabayong itim; at ang nakasakay rito ay may isang timbangan sa kanyang kamay.
Siya ay iyong ituturing na banal, sapagkat siya ang naghahandog ng tinapay ng inyong Diyos. Siya'y magiging banal sa inyo; sapagkat akong Panginoon na nagpapabanal sa inyo ay banal.
Sinabi ni Jesus, “Sino ang humawak sa akin?” Nang tumatanggi ang lahat, sinabi ni Pedro, “Guro, pinapalibutan ka at sinisiksik ng napakaraming tao.”
Subalit ang taong-bayan ay nauhaw roon at sila ay nagreklamo laban kay Moises at sinabi, “Bakit mo kami inilabas mula sa Ehipto, upang patayin mo sa uhaw, kami, ang aming mga anak, at ang aming kawan?”
Sinabi ni Moises kay Hobab na anak ni Reuel na Midianita, biyenan ni Moises: “Kami ay naglalakbay patungo sa dakong sinabi ng Panginoon , ‘Aking ibibigay sa inyo.’ Sumama ka sa amin at gagawan ka namin ng mabuti sapagkat ang Panginoon ay nangako ng mabuti tungkol sa Israel.”
kapag nalaman na ang kasalanang kanilang nagawa, ang kapulungan ay magdadala ng isang guyang toro bilang handog pangkasalanan, at dadalhin ito sa harapan ng toldang tipanan.
Kanyang aalisin ang lahat ng taba ng toro na handog pangkasalanan; ang tabang bumabalot sa lamang-loob at ang lahat ng tabang nasa lamang-loob;
Kukuha siya mula sa dambana na nasa harapan ng Panginoon ng isang suuban na punô ng mga baga, at ng dalawang dakot ng masarap na dinikdik na insenso at kanyang dadalhin sa loob ng tabing.
Kahit kailangan mong umalis sapagkat nasasabik ka na sa bahay ng iyong ama, bakit mo ninakaw ang aking mga diyos?”
Samantalang sila'y kumakain, dumampot siya ng tinapay, at nang kanyang mabasbasan ay kanyang pinagputul-putol, ibinigay sa kanila at sinabi, “Kunin ninyo; ito ang aking katawan.”
Kaya, kung sasabihin nila sa inyo, ‘Tingnan ninyo, siya'y nasa ilang,’ huwag kayong lumabas. ‘Tingnan ninyo, siya'y nasa mga silid,’ huwag ninyong paniwalaan.
Nagtipun-tipon sa palibot niya ang napakaraming tao, kaya't sumakay siya sa isang bangka at umupo roon samantalang ang lahat ng tao ay nakatayo sa baybayin.
Sinabi ng isa sa mga alipin ng pinakapunong pari, na kamag-anak ng tinagpasan ni Pedro ng tainga, “Hindi ba ikaw ang nakita kong kasama niya sa halamanan?”
Sa hihip ng iyong ilong ang tubig ay natipon, ang mga agos ay tumayong parang isang bunton; Ang mga kalaliman ay namuo sa gitna ng dagat.
At pinagpakitaan niya ng magandang loob si Abram dahil kay Sarai at nagkaroon si Abram ng mga tupa, baka, lalaking asno, aliping lalaki at alilang babae, babaing asno, at mga kamelyo.
Ang Panginoon , ang Diyos ng langit, na kumuha sa akin sa sambahayan ng aking ama, at sa lupaing aking tinubuan ay nagsalita at sumumpa sa akin na nagsasabi, ‘Sa iyong binhi ay ibibigay ko ang lupaing ito;’ magsusugo siya ng kanyang anghel sa unahan mo, at ikukuha mo roon ng asawa ang aking anak.
Ngunit kung tayo'y lumalakad sa liwanag, na tulad niya na nasa liwanag, may pakikisama tayo sa isa't isa, at ang dugo ni Jesus na kanyang Anak ang lumilinis sa atin sa lahat ng kasalanan.
subalit ako ay nanalangin para sa iyo upang ang iyong pananampalataya ay huwag mawala; kung makabalik ka nang muli, ay palakasin mo ang iyong mga kapatid.”
Ang alipin ay walang palagiang lugar sa sambahayan. Ang anak ay may lugar doon magpakailanman.
Si Abraham ay maagang bumangon at inihanda ang kanyang asno. Isinama niya ang dalawa sa kanyang mga batang tauhan at si Isaac na kanyang anak. Nagsibak siya ng kahoy para sa handog na susunugin; at siya'y naghanda at pumunta sa lugar na sinabi sa kanya ng Diyos.
Nang makita ni Jesus ang napakaraming tao sa palibot niya, ipinag-utos niyang tumawid sa kabilang pampang.
Kinaumagahan, ang lahat ng mga punong pari at ang matatanda sa bayan ay sama-samang nag-usap laban kay Jesus upang siya'y ipapatay.
Sapagkat aking itinataas ang aking kamay sa langit, at sumusumpa, ‘Buháy ako magpakailanman.
Sinabi ng Panginoon kay Moises, “Umikli na ba ang kamay ng Panginoon ? Ngayo'y makikita mo kung ang aking salita ay matutupad sa iyo o hindi.”
Hindi ba sila ang lumalapastangan sa mabuting pangalan na itinawag sa inyo?
Lahat ng mga panganay na lalaki ayon sa bilang ng mga pangalan, mula sa isang buwang gulang pataas, doon sa nabilang sa kanila ay dalawampu't dalawang libo dalawandaan at pitumpu't tatlo.
Sumagot si Jesus, “Siya iyong aking bibigyan ng tinapay pagkatapos na maisawsaw ko ito.” Kaya't nang maisawsaw niya ang tinapay, ay kinuha niya at ibinigay niya kay Judas, na anak ni Simon Iscariote.
at aking sinasabi sa iyo, “Pahintulutan mong umalis ang aking anak upang siya'y makasamba sa akin.” Kung ayaw mo siyang paalisin, aking papatayin ang iyong anak na panganay.’”
“Mag-ingat ka lamang sa iyong sarili, at ingatan mo ang iyong kaluluwa ng buong sikap, baka malimutan mo ang mga bagay na nakita ng iyong mga mata, at baka mahiwalay sa iyong puso ang lahat ng araw ng iyong buhay. Ipaalam mo ito sa iyong mga anak at sa mga anak ng iyong mga anak.
at pinag-uusapan nila ang tungkol sa lahat ng mga bagay na ito na nangyari.
Kanilang tinawagan si Lot at sinabi, “Saan naroon ang mga lalaking dumating sa iyo nang gabing ito? Ilabas mo sila sa amin upang makilala namin sila.”
Kinaumagahan, si Balaam ay bumangon at inihanda ang kanyang asno, at sumama sa mga pinuno ng Moab.
At narito, siya'y hayag na nagsasalita, at sila'y walang anumang sinasabi sa kanya. Tunay kayang nakikilala ng mga pinuno na ito ang Cristo?
Nakikiusap ako sa iyo, tanggapin mo ang kaloob na dala ko sa iyo sapagkat lubos na ang ipinagkaloob sa akin ng Diyos, at mayroon ako ng lahat na kailangan ko.” Kaya't hinimok ni Jacob si Esau at kanyang tinanggap.
Noon ay araw ng Sabbath nang gumawa ng putik si Jesus, at binuksan ang kanyang mga mata.
ang mga kurtina sa bulwagan, ang tabing sa pasukan ng bulwagan na nasa palibot ng tabernakulo at ng dambana, at ang mga tali ng mga iyon, at ang lahat ng kasangkapan sa kanilang paglilingkod; at gagawin nila ang lahat na marapat na gawin sa mga iyon.
Sinabi ni Jacob, “Ipagbili mo muna sa akin ngayon ang iyong pagkapanganay.”
Sinasabi ko sa inyo, sa mga ipinanganak ng mga babae ay walang higit na dakila kay Juan, subalit ang pinakamaliit sa kaharian ng Diyos ay higit na dakila kaysa kanya.”
Kaya't kumuha si Abraham ng mga tupa at baka at ibinigay kay Abimelec; at silang dalawa ay gumawa ng isang tipan.
Ang mga pastulan sa mga lunsod na inyong ibibigay sa mga Levita ay isang libong siko sa palibot mula sa pader ng lunsod hanggang sa dakong labas.
Sinabi sa akin ng Panginoon , ‘Pinasimulan ko nang ibigay sa iyo si Sihon at ang kanyang lupain, pasimulan mong kunin upang matirahan ang kanyang lupain.’
Sapagkat hindi ang mga tagapakinig ng kautusan ang siyang ganap sa harapan ng Diyos, kundi ang tumutupad sa kautusan ay aariing-ganap.
Sinabi ni Esau sa kanyang ama, “Wala ka na bang basbas maliban sa isa, ama ko? Basbasan mo rin ako, ama ko.” At sumigaw si Esau at umiyak.
Lumapit sa kanya ang isang ketongin na nakikiusap at nakaluhod na nagsasabi, “Kung gusto mo, maaari mo akong linisin.”
at ang mga anak ni Bilha, na alila ni Raquel: sina Dan at Neftali;
Ang mga angkan ng mga anak ni Kohat ay magkakampo sa tagiliran ng tabernakulo, sa gawing timog.
na sinasabi, “Bigyan din ninyo ako ng kapangyarihang ito, upang sinumang patungan ko ng aking mga kamay ay tumanggap ng Espiritu Santo.”
Siya'y muling pumasok sa palasyo ng gobernador, at sinabi kay Jesus, “Taga-saan ka?” Ngunit hindi siya sinagot ni Jesus.
Sapagkat ang Diyos ay hindi masama; hindi niya kaliligtaan ang inyong gawa at ang pag-ibig na inyong ipinakita sa kanyang pangalan, sa inyong paglilingkod sa mga banal, gaya ng ginagawa ninyo ngayon.
Pagkatapos, sinabi ng Panginoon kay Moises, “Pumunta ka kay Faraon at sabihin mo sa kanya, ‘Ganito ang sabi ng Panginoon : Pahintulutan mong umalis ang aking bayan, upang sila'y makasamba sa akin.
At nagsalita ang Panginoon kay Moises, na sinasabi,
sa lipi ni Aser ay 12,000; sa lipi ni Neftali ay 12,000; sa lipi ni Manases ay 12,000;
Tumakas ang babae sa ilang, at doon ay ipinaghanda siya ng Diyos ng isang lugar, upang doon siya'y alagaan nila ng isang libo dalawang daan at animnapung araw.
Maglalagay kayo ng isang pinuno sa bawat lipi upang maghati ng lupain bilang mana.
Ngunit kung ang Panginoon ay lumikha ng isang bagong bagay, at ibuka ng lupa ang kanyang bibig at sila'y lamunin, kasama ng lahat ng nauukol sa kanila, at sila'y buháy na ibaba sa Sheol, inyo ngang malalaman na hinamak ng mga taong ito ang Panginoon .”
At sinabi sa kanya ni Jesus, “Dumating sa bahay na ito ngayon ang kaligtasan, sapagkat siya man ay anak din ni Abraham.
Nang dumarami ang nagkakatipong mga tao, nagsimula siyang magsalita, “Ang lahing ito'y isang masamang lahi. Ito'y humahanap ng isang tanda, subalit walang tanda na ibibigay dito maliban sa tanda ni Jonas.
Mga anak, huling oras na! Gaya ng inyong narinig na darating ang anti-Cristo, kahit ngayon ay lumitaw na ang maraming anti-Cristo. Kaya nalalaman nating huling oras na.
Ito nga ang ikatlong pagpapakita ni Jesus sa mga alagad, pagkatapos na siya'y bumangon mula sa mga patay.
Sa ikalabing-apat na araw ng unang buwan ay paskuwa ng Panginoon .
Ngunit darating ang araw ng Panginoon na gaya ng isang magnanakaw, at ang kalangitan ay maglalaho kasabay ng malakas na ingay at ang mga sangkap ay matutupok sa apoy at ang lupa at ang mga gawang naroon ay masusunog.
Kanyang inilagay sa ibabaw ng pambalikat ng efod upang maging mga batong pang-alaala para sa mga anak ni Israel; gaya ng iniutos ng Panginoon kay Moises.
Humayo ka at tipunin mo ang matatanda sa Israel at sabihin mo sa kanila, ‘Ang Panginoon , ang Diyos ng inyong mga ninuno, ang Diyos nina Abraham, Isaac, at Jacob ay nagpakita sa akin, na nagsasabi, “Tunay na kayo'y aking dinalaw at aking nakita ang ginagawa sa inyo sa Ehipto.
oo, Ama, sapagkat gayon ang mapagpala mong kalooban.
Sila'y sinagot ni Juan, “Ako'y nagbabautismo sa tubig; sa gitna ninyo'y may isang nakatayo na hindi ninyo kilala,
kung kayo'y nagpapatuloy na matatag at matibay sa pananampalataya, at hindi nakikilos sa pag-asa sa ebanghelyo na inyong narinig, na ipinangaral sa lahat ng mga nilalang sa silong ng langit. Akong si Pablo ay naging ministro ng ebanghelyong ito.
Habang nagsasalita pa siya, may isang dumating na mula sa bahay ng pinuno ng sinagoga na nagsasabi, “Patay na ang anak mong babae; huwag mo nang abalahin pa ang Guro.”
Ngunit kahabag-habag ang mga buntis at ang mga nagpapasuso sa mga araw na iyon!
Ito'y sinabi niya upang ipahiwatig kung sa anong kamatayan luluwalhatiin niya ang Diyos. At pagkatapos nito ay sinabi niya sa kanya, “Sumunod ka sa akin.”
Nang marinig ni Esau ang mga salita ng kanyang ama ay sumigaw siya nang malakas at umiyak na may kapaitan at sinabi sa kanyang ama, “Basbasan mo rin ako, aking ama.”
na siyang magbabago ng ating hamak na katawan upang maging katulad ng katawan ng kanyang kaluwalhatian, ayon sa kapangyarihan na kumikilos sa kanya upang maipailalim sa kanyang sarili ang lahat ng mga bagay.
Kanyang tinanong sila tungkol sa kanilang kalagayan, at sinabi, “Mayroon bang kapayapaan ang inyong ama, ang matanda na inyong sinabi? Buháy pa ba siya?”
At nang masabi niya ito ay kanyang ipinakita sa kanila ang kanyang mga kamay at tagiliran. Kaya't ang mga alagad ay nagalak nang makita nila ang Panginoon.
Ngunit tinawag sila ni Jesus at sinabi sa kanila, “Alam ninyo na ang mga pinuno ng mga Hentil ay nangingibabaw na panginoon sa kanila, at ang mga dakila sa kanila ay gumagamit ng kapangyarihan sa kanila.
Madalas ko silang pinarurusahan sa lahat ng mga sinagoga at pinipilit ko silang manlapastangan; at sa nag-aalab na pagkagalit sa kanila ay pinag-uusig ko sila maging sa mga lunsod sa ibang lupain.
Kung kailangang ako'y magmalaki, ako'y magmamalaki sa mga bagay na nauukol sa aking kahinaan.
Kaya, mga kapatid, hindi tayo mga anak ng babaing alipin, kundi ng babaing malaya.
Sapagkat sinumang mayroon ay lalong bibigyan, at magkakaroon siya ng kasaganaan; ngunit sinumang wala, pati ang nasa kanya ay kukunin.
higit na mataas kaysa lahat ng pamunuan, kapamahalaan, kapangyarihan, at paghahari, at sa bawat pangalan na pinangalanan, hindi lamang sa panahong ito, kundi maging sa darating na panahon.
Ngunit nang dumating si Cefas sa Antioquia, sumalungat ako sa kanya nang mukhaan, sapagkat siya'y nahatulang nagkasala.
Siya ang ulo ng katawan, ang iglesya; siya ang pasimula, ang panganay mula sa mga patay, upang siya ay maging pangunahin sa lahat ng mga bagay.
Kayo mismo ang aming sulat na nasusulat sa aming mga puso, nakikilala at nababasa ng lahat ng mga tao:
Kora, Gatam, at Amalek. Ito ang mga pinunong nagmula kay Elifaz sa lupain ng Edom; ito ang mga anak ni Ada.
Batiin ninyo si Filologo at si Julia, si Nereo at ang kanyang kapatid na babae, at si Olimpas, at ang lahat ng mga banal na kasama nila.
Kaya't sila'y umakyat, at kanilang lihim na siniyasat ang lupain mula sa ilang ng Zin hanggang sa Rehob, sa pagpasok sa Hamat.
Sinabi nga sa kanila ni Jesus, “Katotohanang sinasabi ko sa inyo, malibang inyong kainin ang laman ng Anak ng Tao at inumin ang kanyang dugo, wala kayong buhay sa inyong sarili.
“Walang taong pagkatapos magsindi ng ilawan ay tinatakpan ito ng isang takalan, o kaya'y inilalagay ito sa ilalim ng higaan, kundi inilalagay ito sa talagang lalagyan upang makita ng mga pumapasok ang liwanag.
Sumagot siya at sinabi sa kanila, “Kayong lahing walang pananampalataya, hanggang kailan pa ako makikisama sa inyo? Hanggang kailan pa ako magtitiis sa inyo? Dalhin ninyo siya sa akin.”
Ang mga anak ni Dan: si Husim.
Nang ikalabimpitong araw ng ikapitong buwan, sumadsad ang daong sa ibabaw ng mga bundok ng Ararat.
Silang lahat ay nakinig sa kanya buhat sa pinakaaba hanggang sa pinakadakila, na sinasabi, “Ang taong ito ang kapangyarihan ng Diyos na tinatawag na Dakila.”
At dumagsa ang tubig sa ibabaw ng lupa at inapawan ang lahat ng matataas na mga bundok na nasa silong ng langit.
Sa ikatlong araw, nang mahapdi pa ang mga sugat ng mga tinuli, ang dalawa sa mga anak ni Jacob, sina Simeon at Levi, na mga kapatid ni Dina, ay kumuha ng kanilang tabak, palihim na pumasok sa bayan, at kanilang pinatay ang lahat ng mga lalaki.
Sapagkat ang tinapay ng Diyos ay ang bumababang mula sa langit at nagbibigay ng buhay sa sanlibutan.
Nang magkagayo'y ang mga kapatas sa mga anak ni Israel ay naparoon at dumaing kay Faraon, “Bakit mo ginaganito ang iyong mga alipin?
Ang tabing ng templo ay nahati sa dalawa, mula sa itaas hanggang sa ibaba.
Huwag mong ipatong na madalian ang iyong mga kamay sa kanino man, ni huwag kang makiisa sa mga kasalanan ng iba; panatilihin mong malinis ang iyong sarili.
“Huwag mong ipagpapaliban ang paghahandog ng mula sa iyong mga ani, at ng mula sa umagos sa iyong mga pisaan. “Ang panganay sa iyong mga anak na lalaki ay ibibigay mo sa akin.
Igagawa mo ito ng isang gilid sa palibot na may isang dangkal ang luwang, at igagawa mo ng isang moldeng ginto ang palibot ng gilid niyon.
Si Rebecca ay may isang kapatid na ang pangalan ay Laban. Tumakbong papalabas si Laban patungo sa lalaki na nasa bukal.
Kanilang sinabi sa kanya, “Si Jose ay buháy pa! Sa katunaya'y siya ang pinuno sa buong lupain ng Ehipto.” Siya ay nabigla; hindi siya makapaniwala sa kanila.
at iaalay ng pari ang handog na sinusunog at ang butil na handog sa ibabaw ng dambana. Gayon gagawin ng pari ang pagtubos para sa kanya, at siya'y magiging malinis.
Kaya't sila'y kumuha ng abo sa hurno, at tumayo sa harap ni Faraon. Isinaboy ito ni Moises sa himpapawid at naging pigsang sumusugat sa tao at sa hayop.
“At huwag mong aapihin, o pahihirapan ang dayuhan, sapagkat kayo'y mga dayuhan din sa lupain ng Ehipto.
“Huwag kayong sasangguni sa mga nakikiugnay sa masasamang espiritu ni sa mga mangkukulam; huwag ninyo silang hanapin upang madungisan nila: Ako ang Panginoon ninyong Diyos.
lalo na dahil sa kalabisan ng mga pahayag. Kaya't upang ako'y huwag magyabang ng labis, binigyan ako ng isang tinik sa laman, isang sugo ni Satanas upang ako'y saktan, upang ako'y huwag magmalaki ng labis.
Ang inyong mga kayamanan ay bulok na, at ang inyong mga damit ay kinakain na ng bukbok.
At ngayo'y nakatayo ako rito upang litisin dahil sa pag-asa sa pangakong ginawa ng Diyos sa aming mga ninuno;
ang sabi niya, na nakarinig ng mga salita ng Diyos, at nakaalam ng karunungan ng Kataas-taasan, na siyang nakakita ng pangitain ng Makapangyarihan sa lahat, na nakalugmok ngunit bukas ang kanyang mga mata.
Kung ang salarin ay nararapat hagupitin, padadapain siya ng hukom sa lupa, at hahagupitin sa kanyang harapan na may bilang ng hagupit ayon sa kanyang pagkakasala.
Tungkol sa ebanghelyo, sila'y mga kaaway alang-alang sa inyo; subalit tungkol sa paghirang, sila'y mga minamahal alang-alang sa mga ninuno.
Sinabi ni Moises sa mga anak ni Israel, “Tingnan ninyo, tinawag ng Panginoon sa pangalan si Bezaleel na anak ni Uri, na anak ni Hur, sa lipi ni Juda.
At sinabi sa akin ng isa sa matatanda, “Huwag kang umiyak. Tingnan mo, ang Leon sa lipi ni Juda, ang Ugat ni David, ay nagtagumpay upang mabuksan niya ang aklat at ang pitong tatak nito.”
Kanyang ihahandog sa Panginoon ang lalaking tupa bilang handog pangkapayapaan na kalakip ng bakol ng mga tinapay na walang pampaalsa. Ihahandog din ng pari ang handog na butil niyon at ang handog na inumin niyon.
Ang mga ibinigay sa akin ng aking Ama ay higit na dakila kaysa lahat, at walang makakaagaw ng mga ito sa kamay ng Ama.
Nagkaroon pa siya ng ibang panaginip at isinalaysay sa kanyang mga kapatid, at sinabi, “Ako'y nagkaroon ng isa pang panaginip: ang araw, ang buwan, at ang labing-isang bituin ay yumuko sa akin.”
Ang mga hari sa lupa, ang mga prinsipe, ang mga pinuno ng hukbo, ang mayayaman, ang malalakas at ang bawat alipin at ang bawat malaya, ay nagtago sa mga yungib, sa mga bato at sa mga bundok;
Subalit ngayon ay na kay Cristo Jesus, kayo na noong una ay malayo, ay inilapit sa pamamagitan ng dugo ni Cristo.
Dapat silang gumawa ng mabuti, maging mayaman sa mabubuting gawa, bukas ang palad at handang mamahagi,
Muli nilang pinagsikapang siya'y hulihin, subalit siya'y tumakas sa kanilang mga kamay.
At ipinagluksa ng mga anak ni Israel si Moises nang tatlumpung araw sa mga kapatagan ng Moab, at natapos ang mga araw ng pagtangis at pagluluksa para kay Moises.
“‘Sumpain ang sumisiping sa asawa ng kanyang ama, sapagkat kanyang inililitaw ang balabal ng kanyang ama.’ At ang buong bayan ay magsasabi, ‘Amen.’
“Ito naman ang iyong ihahandog sa ibabaw ng dambana: dalawang kordero na tig-iisang taong gulang, araw-araw sa habang panahon.
Gayundin ang iyong gagawin sa kanyang asno; gayundin ang iyong gagawin sa kanyang damit, at gayundin ang iyong gagawin sa bawat nawalang bagay ng iyong kapatid na nawala sa kanya at iyong natagpuan. Huwag kang magkait ng tulong.
Sapagkat tunay at matuwid ang kanyang mga paghatol; hinatulan niya ang tanyag na mahalay na babae na nagpasama sa daigdig sa pamamagitan ng kanyang pakikiapid, at ipinaghiganti ng Diyos ang dugo ng kanyang mga alipin laban sa babae.”
Kaya't sa paghayo ninyo, gawin ninyong alagad ang lahat ng mga bansa, bautismuhan ninyo sila sa pangalan ng Ama at ng Anak at ng Espiritu Santo,
At huwag din ninyong ihandog ang mga bahagi ng inyong katawan sa kasalanan bilang kasangkapan ng kasamaan tungo sa kasalanan, kundi ihandog ninyo ang inyong sarili sa Diyos, na tulad sa mga buháy mula sa mga patay, at ang mga bahagi ng inyong katawan bilang kasangkapan ng pagiging matuwid tungo sa Diyos.
Dumating ang manunukso at sinabi sa kanya, “Kung ikaw ang Anak ng Diyos, ipag-utos mo na ang mga batong ito ay maging tinapay.”
Kapag ako'y humimlay na kasama ng aking mga ninuno, ilabas mo ako mula sa Ehipto, at ilibing mo ako sa kanilang libingan.” At sinabi ni Jose, “Aking gagawin ang ayon sa iyong sinabi.”
Nang sabihin niya ito, nagkaroon ng pagtatalo ang mga Fariseo at mga Saduceo; at nahati ang kapulungan.
Nasa pamamahala ni Aaron at ng kanyang mga anak ang buong paglilingkod ng mga anak ng mga Gershonita, ang lahat ng kanilang dadalhin at ang lahat ng kanilang gagawin; at inyong ituturo sa kanila ang mga nauukol sa kanilang dadalhin.
Siya'y gumawa ng limampung kawit na tanso upang pagdugtung-dugtungin ang tolda, upang ang mga iyon ay maging isa.
Ang inyong mga bangkay ay mabubuwal sa ilang na ito; at ang lahat na nabilang sa inyo ayon sa inyong kabuuang bilang, mula sa dalawampung taong gulang pataas na nagreklamo laban sa akin,
Ang iyong kanang kamay, O Panginoon ay maluwalhati sa kapangyarihan, ang iyong kanang kamay, O Panginoon ang dumudurog sa kaaway.
Ginawa sa kanya ng kanyang mga anak ang ayon sa iniutos sa kanila.
Siyasatin ninyo ang inyong mga sarili kung kayo'y nasa pananampalataya; subukin ninyo ang inyong mga sarili. Hindi ba ninyo nalalaman na si Jesu-Cristo ay nasa inyo? malibang kayo'y nabigo sa pagsubok.
Gayundin naman, sa pagnanais ng Diyos na maipakita sa mga tagapagmana ng pangako na hindi maaaring mabago ang kanyang pasiya, pinagtibay niya ito sa pamamagitan ng isang sumpa;
Misma, Duma, Massa,
Sapagkat sa ganitong paraan ay masaganang ibibigay sa inyo ang pagpasok sa walang hanggang kaharian ng ating Panginoon at Tagapagligtas na si Jesu-Cristo.
Ang Panginoon ay nagsalita sa inyo mula sa gitna ng apoy. Narinig ninyo ang tunog ng mga salita, ngunit wala kayong anyong nakita; tanging tinig lamang.
Pagkatapos ay ipinadala siyang nakagapos ni Anas kay Caifas na pinakapunong pari.
“Huwag kang maghahandog sa Panginoon mong Diyos ng baka o tupa na may dungis o anumang kapintasan; sapagkat ito'y karumaldumal sa Panginoon mong Diyos.
at sinasabi, “Kung ikaw ang Hari ng mga Judio, iligtas mo ang iyong sarili!”
“Gayundin naman, ang kaharian ng langit ay tulad ng isang mangangalakal na naghahanap ng magagandang perlas;
Ngunit sa pamamagitan ng mga handog na ito ay may pagpapaalala ng mga kasalanan taun-taon.
Hindi kami nangangahas na ibilang o ihambing ang aming sarili sa ilan sa mga nagmamalaki sa kanilang sarili. Subalit silang sumusukat sa kanilang sarili sa pamamagitan ng kanilang sarili, at inihahambing ang kanilang sarili sa isa't isa, sila ay hindi nakakaunawa.
Gayundin naman kayo, kapag nakita ninyong nangyayari ang mga bagay na ito, nalalaman ninyo na malapit na ang kaharian ng Diyos.
Ni huwag siyang magpaparami ng mga asawa para sa kanyang sarili, upang huwag maligaw ang kanyang puso, ni huwag siyang magpaparami ng pilak at ginto.
Ibibigay ninyo ito sa paring si Eleazar, at kanyang ilalabas sa kampo at papatayin sa kanyang harapan.
Pagpasok ni Pedro, sinalubong siya ni Cornelio at nagpatirapa sa kanyang paanan, at siya'y sinamba.
Ngunit paano nga silang tatawag sa kanya na hindi nila sinampalatayanan? At paano sila sasampalataya sa kanya na hindi nila napakinggan? At paano sila makikinig kung walang mangangaral?
Sa halip, ay ang panloob na pagkatao na may kagandahang walang paglipas, ng isang mahinhin at maamong espiritu na napakahalaga sa paningin ng Diyos.
Sinabi niya sa kanila, “Sumunod kayo sa akin at gagawin ko kayong mga mamamalakaya ng mga tao.”
Hindi sila taga-sanlibutan, na gaya ko na hindi taga-sanlibutan.
Ito ang mga angkan ni Neftali ayon sa kanilang mga angkan at ang nabilang sa kanila ay apatnapu't limang libo at apatnaraan.
Subalit pinipilit nilang hingin na ipinagsisigawan na siya'y ipako sa krus. At nanaig ang kanilang mga tinig.
ang dalawang bato at ang tabang nasa ibabaw nito na malapit sa mga balakang, at ang lamad na nasa ibabaw ng atay ay aalisin niya kasama ng mga bato,
At nang oras na iyon ay nagkaroon ng isang malakas na lindol, at nagiba ang ikasampung bahagi ng lunsod; may namatay sa lindol na pitong libong katao at ang mga iba ay natakot, at nagbigay ng luwalhati sa Diyos ng langit.
Doo'y magtatayo ka ng isang batong dambana sa Panginoon mong Diyos, na hindi gagamitan ng kasangkapang bakal.
Ang tanging bagay na nais kong matutunan mula sa inyo ay ito: Tinanggap ba ninyo ang Espiritu sa pamamagitan ng mga gawa ng kautusan, o sa pamamagitan ng pakikinig sa pananampalataya?
ang pangangalunya, kasakiman, kasamaan, pandaraya, kahalayan, pagkainggit, paninirang-puri, kapalaluan, at kahangalan.
“‘Ni huwag kang sasaksi sa kasinungalingan laban sa iyong kapwa.
Kaya't kanilang kinuha ang mahabang damit ni Jose, at sila'y pumatay ng isang lalaking kambing, at kanilang inilubog ang mahabang damit sa dugo.
tuwing hahatulan tayo ng ating puso; sapagkat ang Diyos ay higit na dakila kaysa ating puso, at nalalaman niya ang lahat ng mga bagay.
Sinasadya nilang hindi pansinin ang katotohanang ito, na sa pamamagitan ng salita ng Diyos ay nagkaroon ng langit nang unang panahon at inanyuan ang lupa mula sa tubig at sa pamamagitan ng tubig,
Ang mga higante ay nasa lupa nang mga araw na iyon, at kahit pagkatapos noon. Sila ang naging anak nang makipagtalik ang mga anak ng Diyos sa mga anak na babae ng tao. Ang mga ito ang naging makapangyarihan nang unang panahon, mga bantog na mandirigma.
gaya ng nasusulat, “Tingnan ninyo, inilalagay ko sa Zion ang isang batong ikabubuwal at batong katitisuran, at ang sumasampalataya sa kanya'y hindi malalagay sa kahihiyan.”
At sinabi niya sa kanila, “Pumunta kayo ng bukod sa isang dakong ilang at magpahinga kayo nang sandali.” Sapagkat marami ang nagpaparoo't parito at sila'y hindi man lamang nagkaroon ng panahong kumain.
Subalit nang si Galio ay proconsul ng Acaia, ang mga Judio ay nagkaisang dakpin si Pablo at siya'y dinala sa harapan ng hukuman.
Kung paanong sina Janes at Jambres ay sumalungat kay Moises, ang mga ito'y sumasalungat din sa katotohanan, mga taong masasama ang pag-iisip at mga nagtakuwil sa pananampalataya.
Gumawa rin siya ng isang luklukan ng awa na lantay na ginto na dalawang siko at kalahati ang haba, at isang siko at kalahati ang luwang.
Pagkalipas ng mga araw na ito ay naglihi ang kanyang asawang si Elizabeth. Siya ay nagtago nang limang buwan, na nagsasabi,
Subalit ang nakikinig at hindi ginagawa ang mga ito ay tulad sa isang tao na nagtayo ng bahay sa lupa na walang pundasyon. Nang ito'y hampasin ng ilog ay kaagad na nagiba at malaki ang pagkasira ng bahay na iyon.”
Kaya't hindi ka na alipin kundi anak; at kung anak, ay tagapagmana.
Ang mga apostol ay nagtipon sa harap ni Jesus at ibinalita nila sa kanya ang lahat ng kanilang ginawa at itinuro.
upang maging alaala sa mga anak ni Israel, upang sinumang ibang tao na hindi pari, na hindi mga anak ni Aaron ay huwag lumapit upang magsunog ng insenso sa harap ng Panginoon at nang huwag maging tulad ni Kora at ng kanyang mga kasama; gaya ng sinabi ng Panginoon kay Eleazar sa pamamagitan ni Moises.
“Ang buwang ito'y magiging pasimula ng inyong mga buwan; ito ang magiging unang buwan ng taon para sa inyo.
Kung kayo'y mga taong tapat, maiwan ang isa sa inyong magkakapatid kung saan kayo nakabilanggo; at ang iba ay humayo upang magdala ng trigo dahil sa taggutom sa inyong mga sambahayan.
Sila'y naglakbay mula sa Elim at nagkampo sa tabi ng Dagat na Pula.
Kaya't ang mga pinuno ng Edom ay nagimbal; sa matatapang sa Moab, ang panginginig sa kanila ay sumakmal, at naupos ang lahat ng taga-Canaan.
upang mapasainyong lahat ang matuwid na dugo na dumanak sa ibabaw ng lupa buhat sa dugo ni Abel na matuwid, hanggang sa dugo ni Zacarias na anak ni Baraquias na inyong pinaslang sa pagitan ng templo at ng dambana.
At kanyang sinabi, “Sumpain si Canaan! Siya'y magiging alipin ng mga alipin sa kanyang mga kapatid.”
Maglalagay ako sa iyo at sa babae ng pagkapoot sa isa't isa, at sa iyong binhi at sa kanyang binhi. Ito ang dudurog ng iyong ulo, at ikaw ang dudurog ng kanyang sakong.”
Kanyang pinagbibintangan siya ng mga kahiyahiyang bagay sa pagsasabing, “Hindi ko natagpuan sa iyong anak ang mga katibayan ng pagkabirhen;” gayunma'y ito ang mga tanda ng pagkabirhen ng aking anak.’ At kanilang ilaladlad ang kasuotan sa harapan ng matatanda sa bayan.
Sapagkat mula sa kanya, at sa pamamagitan niya, at para sa kanya ang lahat ng mga bagay. Sumakanya nawa ang kaluwalhatian magpakailanman. Amen.
Nang makita ng dragon na siya'y itinapon sa lupa, inusig niya ang babaing nanganak ng sanggol na lalaki.
at noong ako'y nasa Jerusalem ay ipinagbigay-alam ng mga punong pari at ng matatanda sa mga Judio ang tungkol sa kanya na hinihinging humatol ako laban sa kanya.
at sa pamamagitan niya ay pagkasunduin ng Diyos sa kanyang sarili ang lahat ng mga bagay, sa lupa man o sa langit, na ginagawa ang kapayapaan sa pamamagitan ng dugo ng kanyang krus.
Ang inyong pagsunod ay naging bantog sa lahat ng mga tao, kaya't nagagalak ako tungkol sa inyo. Ngunit nais kong kayo'y maging marurunong sa kabutihan, at walang sala tungkol sa kasamaan.
ang napakaraming pagsubok na nakita ng iyong mga mata, ang mga tanda, mga kababalaghan, ang makapangyarihang kamay, at ang unat na bisig na sa pamamagitan nito ay inilabas ka ng Panginoon mong Diyos, gayundin ang gagawin ng Panginoon mong Diyos sa lahat ng mga bayang iyong kinatatakutan.
Sinabi niya, “Pinagkasunduan ng mga Judio na sa iyo'y ipakiusap na iyong dalhin bukas si Pablo sa Sanhedrin, na kunwari'y may sisiyasatin pa silang mabuti tungkol sa kanya.
Iyong ibibigay ang mga Levita kay Aaron at sa kanyang mga anak. Sila'y lubos na ibinigay sa kanya mula sa mga anak ni Israel.
Sinabi ng Diyos kay Abraham, “Huwag kang magdamdam ng dahil sa bata at dahil sa iyong aliping babae. Makinig ka sa lahat ng sasabihin sa iyo ni Sara sapagkat sa pamamagitan ni Isaac papangalanan ang iyong binhi.
At sinabi niya sa kanila, “Ano ba ang inyong pinag-uusapan sa inyong paglalakad?” At sila'y tumigil na nalulungkot.
Subalit kung ang lalaki ay walang kamag-anak na mapagbabayaran ng sala, ang kabayaran sa sala ay mapupunta sa Panginoon para sa pari, bukod sa lalaking tupa na pantubos sa kanya.
Sapagkat, “Ang lahat ng laman ay gaya ng damo, at ang lahat ng kaluwalhatian nito ay gaya ng bulaklak ng damo. Ang damo'y natutuyo, at ang bulaklak ay nalalanta,
Baka kung mailagay na niya ang pundasyon at hindi makayang tapusin, ang lahat ng mga makakakita ay magpapasimulang siya'y libakin,
Si Judas Iscariote naman, na isa sa labindalawa, ay nagpunta sa mga punong pari upang maipagkanulo siya sa kanila.
Sapagkat lagi ninyong kasama ang mga dukha, ngunit ako'y hindi ninyo laging makakasama.
Ang mga anak ni Het ay sumagot kay Abraham,
Ang mga anak ni Simeon ayon sa kanilang mga angkan: kay Nemuel, ang angkan ng mga Nemuelita; kay Jamin, ang angkan ng mga Jaminita; kay Jakin, ang angkan ng mga Jakinita;
Sapagkat hindi na sila nangahas magtanong pa sa kanya ng anuman.
Ngayon sa kanya na may kakayahang mag-ingat sa inyo mula sa pagkatisod, at sa inyo'y makapaghaharap na walang kapintasan sa harapan ng kanyang kaluwalhatian na may malaking kagalakan,
Kapag ikaw ay lumapit sa nakatayong trigo ng iyong kapwa, mapipitas mo ng iyong kamay ang mga uhay; ngunit huwag kang gagamit ng karit sa nakatayong trigo ng iyong kapwa.
Nabuhay si Eber ng apatnaraan at tatlumpung taon pagkatapos na maipanganak si Peleg, at nagkaanak pa ng mga lalaki at mga babae.
Nang sabihin niya sa itaas na, “Hindi mo ibig at hindi mo rin kinalugdan ang alay at mga handog, at mga buong handog na sinusunog at mga alay para sa kasalanan” na inihahandog ayon sa kautusan,
Maghanda ka sa kinaumagahan, at umakyat ka kinaumagahan sa bundok ng Sinai at humarap ka sa akin doon sa tuktok ng bundok.
Siya'y lumuhod at sumigaw nang malakas, “Panginoon, huwag mo silang papanagutin sa kasalanang ito.” At pagkasabi niya nito ay namatay siya.
Nang ang ulat ay naibalita sa sambahayan ng Faraon, “Dumating na ang mga kapatid ni Jose,” ito ay minabuti ni Faraon at ng kanyang mga lingkod.
Huwag kang susunod sa ibang mga diyos, sa mga diyos ng mga bansang nasa palibot mo;
O hindi ba ninyo nalalaman na tayong lahat na mga nabautismuhan kay Cristo Jesus ay mga nabautismuhan tungo sa kanyang kamatayan?
Sapagkat ako man ay taong inilagay sa ilalim ng kapangyarihan at may mga kawal na nasasakupan ko. At sinasabi ko sa isa, ‘Humayo ka’ at siya'y humahayo; at sa isa naman, ‘Halika,’ at siya'y lumalapit; at sa aking alipin, ‘Gawin mo ito,’ at ito'y kanyang ginagawa.”
Kaya ang taong-bayan ay nagpahinga sa ikapitong araw.
Siya'y sinaway ng mga nasa unahan at sinabihan siyang tumahimik. Subalit siya'y lalong nagsisigaw, “Anak ni David, maawa ka sa akin.”
Noon ay may isang alagad sa Joppa na ang pangalan ay Tabita, na sa Griyego ay Dorcas. Siya'y puspos ng mabubuting gawa at ng pagkakawanggawa.
Samantalang sinisikap nilang patayin siya, dumating ang balita sa pinunong kapitan ng mga kawal na ang buong Jerusalem ay nagkakagulo.
Kung ang kanan mong mata ang sanhi ng iyong pagkakasala, dukitin mo ito at itapon, sapagkat mabuti pang mawalan ka ng isa sa mga bahagi ng iyong katawan kaysa ang buong katawan mo ay mapatapon sa impiyerno.
Binautismuhan ko kayo sa tubig, ngunit kayo'y babautismuhan niya sa Espiritu Santo.”
Siya'y mananatiling marumi hangga't nasa kanya ang karamdaman; siya'y marumi. Siya ay maninirahang mag-isa sa labas ng kampo.
Nang siya'y alipustain, hindi siya gumanti; nang siya'y magdusa, hindi siya nagbanta, kundi ipinagkatiwala ang kanyang sarili doon sa humahatol na may katarungan.
Ngunit ang kanilang balak ay nalaman ni Saulo. Kanilang binantayan ang mga pintuan araw at gabi upang siya'y patayin;
At sinabi ng nakaupo sa trono, “Masdan ninyo, ginagawa kong bago ang lahat ng mga bagay.” Sinabi rin niya, “Isulat mo, sapagkat ang mga salitang ito ay tapat at tunay.”
Sinabi niya, “Tingnan ninyo, maaga pa, hindi pa oras upang tipunin ang mga hayop; painumin ninyo ang mga tupa, at inyo silang pastulin.”
Sa ikapitong araw ay titingnan siya ng pari, at kung ito ay kumalat na sa balat, ipahahayag ng pari na siya ay marumi. Ito ay sakit na ketong.
Nang panahong iyon, si Abimelec at si Ficol na kapitan ng kanyang hukbo ay nagsalita kay Abraham, “Sumasaiyo ang Diyos sa lahat mong ginagawa.
At sinabi niya sa kanila, “Ano ang ibig ninyong gawin ko para sa inyo?”
Gaya ng nasusulat, “Si Jacob ay aking minahal, ngunit si Esau ay aking kinasuklaman.”
“‘Ni huwag mong iimbutin ang asawa ng iyong kapwa; ni huwag mong pagnanasaan ang bahay ng iyong kapwa, ang kanyang bukid, ni ang kanyang aliping lalaki, o aliping babae, ni ang kanyang baka, ni ang kanyang asno, ni anumang bagay ng iyong kapwa.’
Subalit mayroon akong patotoo na lalong dakila kaysa kay Juan. Ang mga gawaing ibinigay sa akin ng aking Ama upang ganapin, ang mga gawaing ito na aking ginagawa ay nagpapatotoo tungkol sa akin na ako'y sinugo ng Ama.
Makinig kayo! Akong si Pablo ay nagsasabi sa inyo na kung kayo'y patutuli, si Cristo ay hindi magiging pakinabang sa inyo.
at ng kasia, limang daan, ayon sa siklo ng santuwaryo, at ng langis ng olibo na isang hin;
Ngunit ang mga salita ni Esau na kanyang panganay ay naibalita kay Rebecca. Kaya't siya'y nagsugo at ipinatawag si Jacob na kanyang bunso at sinabi sa kanya, “Inaaliw ng iyong kapatid na si Esau ang kanyang sarili sa pagpaplanong ikaw ay patayin.
At sinabi sa kanila ni Moises, “Kung ang mga anak ni Gad at ang mga anak ni Ruben ay tatawid na kasama ninyo sa Jordan, ang lahat ng lalaki na may sandata sa pakikipaglaban, sa harap ng Panginoon ; at kung ang lupain ay mapasuko sa harap ninyo ay ibibigay ninyo sa kanila bilang ari-arian ang lupain ng Gilead.
At kanyang ihahandog ang kanyang alay sa Panginoon , na isang korderong lalaki na isang taon na walang kapintasan, bilang handog na sinusunog, at isang korderong babae na isang taon na walang kapintasan bilang handog pangkasalanan at isang lalaking tupa na walang kapintasan bilang handog pangkapayapaan,
Ang dugo ay magiging sa inyo'y isang tanda sa mga bahay na inyong kinaroroonan; kapag aking nakita ang dugo, lalampasan ko kayo at walang salot na papatay sa inyo, kapag pinuksa ko ang lupain ng Ehipto.
Subalit dahil sa mga huwad na kapatid na lihim na ipinasok, na pumasok upang tiktikan ang kalayaan na taglay namin kay Cristo Jesus, upang kami'y alipinin—
Nang makita ni Jacob si Raquel na anak ni Laban, na kapatid ng kanyang ina, at ang mga tupa ni Laban, lumapit si Jacob at iginulong ang bato mula sa labi ng balon at pinainom ang kawan ni Laban.
At sinabi niya sa kanyang mga alagad, “Kaya nga sinasabi ko sa inyo, huwag kayong mabalisa sa inyong buhay, kung ano ang inyong kakainin; o sa inyong katawan, kung ano ang inyong isusuot.
Ngunit kapag nag-aayuno ka, lagyan mo ng langis ang iyong ulo, at maghilamos ka ng iyong mukha;
Ngunit nang dumating ang pagdiriwang ng kaarawan ni Herodes, sumayaw sa gitna nila ang anak na babae ni Herodias, at ito ay ikinatuwa ni Herodes.
Samantalang nasa ibaba si Pedro, sa patyo, lumapit ang isa sa mga alilang babae ng pinakapunong pari.
Lumapit siya kay Simon Pedro na nagtanong sa kanya, “Panginoon, huhugasan mo ba ang aking mga paa?”
Kaya't sinasabi rin niya sa isa pang awit, ‘Hindi mo hahayaan na ang iyong Banal ay makakita ng pagkabulok.’
Kaya't ipag-utos mo na bantayan ang libingan hanggang sa ikatlong araw, baka pumaroon ang kanyang mga alagad at siya'y nakawin, at sabihin sa mga tao, ‘Siya'y bumangon mula sa mga patay,’ at magiging masahol pa ang huling pandaraya kaysa una.”
Yamang naghahanap kayo ng katibayan na si Cristo ay nagsasalita sa akin, na siya ay hindi mahina sa pakikitungo sa inyo, kundi makapangyarihan sa inyo.
Sinabi sa kanya ni Jesus, “Kung ibig mong maging ganap, humayo ka, ipagbili mo ang iyong mga ari-arian at ibigay mo sa mga dukha, at magkakaroon ka ng kayamanan sa langit; pagkatapos ay pumarito ka, at sumunod ka sa akin.”
Ang mabuting tao ay naglalabas ng mabubuting bagay mula sa kanyang mabuting kayamanan, at ang masamang tao ay naglalabas ng masasamang bagay mula sa kanyang masamang kayamanan.
At pagkapagsalita sa kanila ni Moises ay naglagay siya ng isang talukbong sa kanyang mukha.
Kaya't namangha ang mga tao, na nagsasabi, “Anong uring tao ito na maging ang mga hangin at ang dagat ay sumusunod sa kanya?”
At kapag nabasa na ang sulat na ito sa inyo, ay ipabasa rin ninyo sa iglesya ng mga taga-Laodicea; at basahin naman ninyo ang sulat na mula sa Laodicea.
Subalit ang mga taong ito na hindi nakakaalam ng kautusan ay mga sinumpa.”
Kukunin mo lahat ng taba na nakabalot sa bituka, at ang mga taba ng atay, at ang dalawang bato at ang taba ng mga iyon, at susunugin mo sa ibabaw ng dambana.
Ang watawat ng kampo ng mga anak ni Efraim ay sumulong ayon sa kanilang mga pangkat at nangunguna sa kanyang hukbo si Elisama na anak ni Amihud.
na nakatagpo ng biyaya sa paningin ng Diyos, at huminging makatagpo ng isang tahanang ukol sa Diyos ni Jacob.
Ngunit maraming mga una na mahuhuli, at mga huli na mauuna.
Ngunit siya, palibhasa'y puspos ng Espiritu Santo, ay tumitig sa langit at nakita niya ang kaluwalhatian ng Diyos, at si Jesus na nakatayo sa kanan ng Diyos.
Isuot ninyo ang buong kasuotang pandigma ng Diyos upang kayo'y makatagal laban sa mga pakana ng diyablo.
Samantalang sila'y sumasamba sa Panginoon at nag-aayuno, sinabi ng Espiritu Santo, “Ibukod ninyo para sa akin sina Bernabe at Saulo sa gawaing itinawag ko sa kanila.”
At pagsagot ni Jesus ay sinabi niya sa kanya, “Simon, mayroon akong sasabihin sa iyo.” At sinabi niya, “Guro, sabihin mo.”
“Mga kapatid, may tiwalang masasabi ko sa inyo ang tungkol sa patriyarkang si David. Siya rin ay namatay at inilibing, at nasa atin ang kanyang libingan hanggang sa araw na ito.
Sa isang dayuhan ay makapagpapahiram ka na may patubo, ngunit sa iyong kapatid ay huwag kang magpapahiram na may patubo upang pagpalain ka ng Panginoon mong Diyos sa lahat ng gagawin mo sa lupain na malapit mo nang pasukin upang angkinin.
Subalit sumagot siya sa kanyang ama, ‘Tingnan mo, maraming taon nang ako'y naglingkod sa iyo, at kailanma'y hindi ako sumuway sa iyong utos. Gayunman ay hindi mo ako binigyan kailanman ng kahit isang batang kambing upang makipagsaya sa aking mga kaibigan.
Ang mga eskriba at ang mga Fariseo ay nagmamatyag sa kanya kung siya'y magpapagaling sa Sabbath upang makakita sila ng maibibintang laban sa kanya.
Hanggang sa kinabukasan pagkalipas ng ikapitong Sabbath, bibilang kayo ng limampung araw; pagkatapos ay mag-aalay kayo ng handog na bagong butil sa Panginoon .
Nang nagtatakipsilim na, lumapit sa kanya ang mga alagad niya, na nagsasabi, “Ilang na lugar ito, at lumipas na ang maghapon. Papuntahin mo na ang mga tao sa mga nayon upang makabili sila ng kanilang makakain.”
Iwasan mo ang mga usapang walang kabuluhan at hangal, yamang nalalaman mo na namumunga ang mga ito ng mga away.
Sapagkat hindi umakyat si David sa mga langit, ngunit siya rin ang nagsabi, ‘Sinabi ng Panginoon sa aking Panginoon; “Maupo ka sa kanan ko,
At nanginig nang husto si Isaac, at sinabi, “Sino nga iyong kumuha ng usa at dinala sa akin, at ako'y kumain noon bago ka dumating, at siya'y aking binasbasan? Kaya't siya'y magiging mapalad!”
Pagkatapos ng mga bagay na ito ay nakita ko ang isa pang anghel na nananaog mula sa langit, na may dakilang kapangyarihan; at ang lupa ay naliwanagan ng kanyang kaluwalhatian.
Pagkatapos na sila'y mapalaya, pumunta sila sa kanilang mga kasamahan at iniulat ang lahat ng sinabi sa kanila ng mga punong pari at ng matatanda.
Subalit batid niya ang kanilang katusuhan at sinabi sa kanila,
Tumingin ako at nakita ko ang isang kabayong puti, at ang nakasakay doon ay may isang pana; binigyan siya ng isang korona at siya'y humayong lumulupig, at upang lumupig.
Ngunit sumagot siya sa kanila, “Humahanap ng tanda ang isang masama at mapangalunyang lahi; ngunit walang tanda na ibibigay sa kanya, liban sa tanda ng propeta Jonas.
Nakita siya ng lahat ng tao na lumalakad at nagpupuri sa Diyos.
“Ako ang Panginoon mong Diyos na naglabas sa iyo sa lupain ng Ehipto, mula sa bahay ng pagkaalipin.
Magmadali ka, tumakas ka roon; sapagkat wala akong magagawa hanggang sa dumating ka roon.” Kaya't ang pangalang itinawag sa bayang iyon ay Zoar.
Ngunit sinabi ni Moises sa Diyos, “Pagdating ko sa mga anak ni Israel at sasabihin ko sa kanila, ‘Sinugo ako sa inyo ng Diyos ng inyong mga ninuno,’ at sasabihin nila sa akin, ‘Ano ang kanyang pangalan?’ Anong sasabihin ko sa kanila?”
Pakawalan mo ang inahin, ngunit ang inakay ay makukuha mo para sa iyo; para sa kabutihan mo at upang ikaw ay mabuhay nang mahaba.
At kung ito ay hayop na marumi, ito ay kanyang tutubusin ayon sa iyong inihalaga at idaragdag ang ikalimang bahagi niyon; o kung hindi tutubusin ay ipagbibili ayon sa iyong inihalaga.
Nagsalita ang Panginoon kay Moises, na sinasabi,
Magsasama kayo ng isang lalaki mula sa bawat lipi; na bawat isa'y pinuno sa sambahayan ng kanyang mga ninuno.
Samantalang kanilang pinag-uusapan ang mga bagay na ito, si Jesus ay tumayo sa gitna nila at sinabi sa kanila, “Sumainyo ang kapayapaan.”
Akong si Juan, na inyong kapatid at inyong karamay sa kapighatian at sa kaharian at sa pagtitiis alang-alang kay Jesus ay nasa pulo na tinatawag na Patmos, dahil sa salita ng Diyos at sa patotoo ni Jesus.
Sinabi ni Balaam sa Diyos, “Si Balak na anak ni Zipor, hari ng Moab ay nagpasugo sa akin na sinasabi,
Hindi na ako magsasalita pa ng marami sa inyo, sapagkat dumarating ang pinuno ng sanlibutan. Siya'y walang kapangyarihan sa akin.
Nabuhay si Reu ng dalawang daan at pitong taon pagkatapos na maipanganak si Serug, at nagkaanak pa ng mga lalaki at mga babae.
Sapagkat ako ang Panginoon na naglabas sa inyo mula sa lupain ng Ehipto, upang maging inyong Diyos; kayo nga'y magpakabanal, sapagkat ako'y banal.”
Sapagkat nasusulat, “Magalak ka, ikaw na baog, ikaw na hindi nanganganak; bigla kang umawit at sumigaw, ikaw na hindi nakakaranas ng sakit sa panganganak; sapagkat mas marami pa ang mga anak ng pinabayaan kaysa mga anak ng may asawa.”
Minamahal ng Ama ang Anak at inilagay sa kanyang kamay ang lahat ng mga bagay.
Isinulat ko sa inyo ang mga bagay na ito tungkol sa mga mandaraya sa inyo.
Makinig kayo, minamahal kong mga kapatid. Hindi ba pinili ng Diyos ang mga dukha sa sanlibutang ito upang maging mayayaman sa pananampalataya at mga tagapagmana ng kaharian na kanyang ipinangako sa mga nagmamahal sa kanya?
at ikaw ay mangangapa sa katanghaliang-tapat na gaya ng bulag na nag-aapuhap sa kadiliman at hindi ka giginhawa sa iyong mga lakad. Ikaw ay laging aapihin at pagnanakawan, at walang taong tutulong sa iyo.
Samantalang siya'y nakahawak kina Pedro at Juan, sama-samang nagtakbuhan sa kanila ang mga tao, na lubhang namangha, sa tinatawag na portiko ni Solomon.
Sapagkat walang taong nagnanais makilala ang gumagawa ng anumang bagay sa lihim. Kung ginagawa mo ang mga bagay na ito ay ipakilala mo ang iyong sarili sa sanlibutan.”
Kaya't si Moises ay dumaing sa Panginoon , na nagsasabi, “Anong aking gagawin sa bayang ito? Kulang na lamang ay batuhin nila ako.”
Tungkol naman sa lunsod ng mga Levita, sa mga bahay sa mga lunsod na kanilang pag-aari, ang mga Levita ay makakatubos sa anumang panahon.
Huwag niyang babaguhin o papalitan ang mabuti ng masama o ang masama ng mabuti; at kung sa anumang paraan ay palitan ng iba ang isang hayop, kapwa magiging banal ang kapalit at ang pinalitan.
Subalit ngayo'y pinagsisikapan ninyo akong patayin, isang taong nagsasabi sa inyo ng katotohanan na aking narinig sa Diyos. Ito'y hindi ginawa ni Abraham.
Muli niyang ipapadala sa iyo ang lahat ng mga sakit sa Ehipto, na iyong kinatakutan at kakapit sa iyo.
Kakainin ni Aaron at ng kanyang mga anak ang laman ng tupa, at ang tinapay na nasa bakol sa pintuan ng toldang tipanan.
At sinabi niya sa akin, “Ang mga salitang ito'y tapat at tunay. Ang Panginoon, ang Diyos ng mga espiritu ng mga propeta, ay nagsugo ng kanyang anghel upang ipakita sa kanyang mga alipin ang mga bagay na kailangang mangyari kaagad.
Sapagkat may kapangyarihan niyang dinaig nang hayagan ang mga Judio, ipinapakita niya sa pamamagitan ng mga kasulatan na ang Cristo ay si Jesus.
at aming isinugo si Timoteo, na aming kapatid at kamanggagawa ng Diyos sa ebanghelyo ni Cristo, upang kayo'y kanyang patibayin at pasiglahin tungkol sa inyong pananampalataya;
At ibabagsak ka sa lupa, ikaw at ang iyong mga anak na nasa iyo. Sa iyo'y hindi sila mag-iiwan ng bato sa ibabaw ng kapwa bato; sapagkat hindi mo kinilala ang panahon ng pagdalaw sa iyo.”
Kahabag-habag ang mga nagdadalang-tao at ang mga nagpapasuso ng mga sanggol sa mga araw na iyon!
mga taksil, matitigas ang ulo, mga palalo, mga maibigin sa kalayawan sa halip na mga maibigin sa Diyos;
Sa lahat ng bagay ay ipinakita ko sa inyo na sa ganitong paggawa ay dapat tulungan ang mahihina, at alalahanin ang mga salita ng Panginoong Jesus, na siya mismo ang nagsabi, ‘Higit na mapalad ang magbigay kaysa tumanggap.’”
Sinabi nila, “Kailangan pa ba natin ng saksi? Tayo na mismo ang nakarinig mula sa kanyang bibig.”
Pagkatapos ay kukuha ng kaunting dugo nito ang pari sa pamamagitan ng kanyang daliri at ilalagay sa ibabaw ng mga sungay ng dambana ng handog na sinusunog, at ang nalabi sa dugo niyon ay ibubuhos niya sa paanan ng dambana.
Sinabi niya sa kanila, “Nalalaman ninyo na hindi ipinahihintulot sa isang Judio na makisama o lumapit sa isang banyaga; ngunit ipinakita sa akin ng Diyos, na huwag kong tawagin ang isang tao na marumi o karumaldumal.
Bawat haligi ay mayroong dalawang mitsa na nagdudugtong sa isa't isa; gayon ang ginawa niya sa lahat ng haligi ng tabernakulo.
At ito ang batas tungkol sa kanyang pagiging marumi dahil sa kanyang tulo. Maging ang kanyang katawan ay may tulo, o huminto na ang tulo sa kanyang katawan, ito ay karumihan sa kanya.
Dumagsa ang tubig at lumaki nang husto sa ibabaw ng lupa, at lumutang ang daong sa ibabaw ng tubig.
Huwag kayong padaya sa mga salitang walang katuturan, sapagkat dahil sa mga bagay na ito'y dumarating ang galit ng Diyos sa mga anak ng pagsuway.
Ipahayag mo ang mga bagay na ito. Mangaral ka at sumaway na may buong kapamahalaan. Huwag mong hayaang hamakin ka ng sinuman.
“Kaya't inyong ilalagak ang mga salita kong ito sa inyong puso at sa inyong kaluluwa at inyong itatali na pinakatanda sa inyong kamay at magiging pinakatali sa inyong noo.
“Isama mo si Aaron at ang kanyang mga anak, ang mga kasuotan, ang langis na pambuhos, ang torong handog pangkasalanan, ang dalawang tupang lalaki, at ang bakol ng mga tinapay na walang pampaalsa,
Noon ay dinadala sa kanya maging ang mga sanggol, upang kanyang hawakan sila. Subalit nang makita ito ng mga alagad, sila'y sinaway nila.
Kanilang papakinggan ang iyong tinig. Ikaw at ang matatanda sa Israel ay pupunta sa hari ng Ehipto, at inyong sasabihin sa kanya, ‘Ang Panginoon , ang Diyos ng mga Hebreo ay nakipagtagpo sa amin at ngayo'y pahintulutan mo kami na maglakbay ng tatlong araw sa ilang. Nais naming makapaghandog sa Panginoon naming Diyos.’
Sinabi ng Panginoon kay Moises sa Midian, “Humayo ka, bumalik ka sa Ehipto; sapagkat patay na ang lahat ng tao na nagtatangka sa iyong buhay.”
at kanilang tinanggap mula kay Moises ang lahat ng handog na dinala ng mga anak ni Israel na magagamit sa gawang paglilingkod sa santuwaryo upang gawin. Kanilang patuloy silang dinalhan ng kusang handog tuwing umaga,
Ngunit sinabi ni Pablo, “Hindi ako baliw, kagalang-galang na Festo; kundi mga salita ng katotohanan at katuwiran ang sinasabi ko.
Kaya't nagpasugo ang Faraon at ipinatawag si Jose, at madali siyang inilabas sa bilangguan. At nang siya'y makapag-ahit at makapagpalit ng damit ay pumunta sa Faraon.
Lamang, panghawakan natin ang ating naabot na.
Kaya't sinikap nilang siya'y hulihin, subalit walang taong sumunggab sa kanya, sapagkat hindi pa dumating ang kanyang oras.
Kaya't sila'y ipinatawag nila at inutusan na sa anumang paraan ay huwag na silang magsalita ni magturo sa pangalan ni Jesus.
At nang matapos na ang aming mga araw doon, umalis kami at nagpatuloy sa aming paglalakbay, at silang lahat, kasama ang mga asawa at mga anak, ay inihatid kami sa aming patutunguhan hanggang sa labas ng bayan. Pagkatapos naming lumuhod sa baybayin at nanalangin,
At sinaway siya ng marami na siya'y tumahimik, ngunit siya'y lalong nagsisigaw, “Anak ni David, mahabag ka sa akin!”
Sapagkat sinabi nila, “Huwag sa kapistahan, baka magkagulo ang taong-bayan.”
Subalit ang lalaking malinis at wala sa paglalakbay na hindi mangingilin ng paskuwa ay ititiwalag sa kanyang bayan sapagkat siya'y hindi nag-alay ng handog sa Panginoon sa takdang panahon, ang taong iyon ay mananagot sa kanyang kasalanan.
Pagkasabi niya ng mga bagay na ito, habang sila'y nakatingin, dinala siya sa itaas at siya'y ikinubli ng ulap sa kanilang mga paningin.
Ang mga bagay na inyong natutunan, tinanggap, narinig at nakita sa akin, ang mga bagay na ito ang gawin ninyo; at ang Diyos ng kapayapaan ay sasainyo.
At sinumang tao sa mga anak ni Israel, o sa mga taga-ibang bayan na naninirahang kasama ninyo na humuli ng hayop o ng ibon na makakain, ay ibubuhos niya ang dugo niyon at tatabunan ng lupa.
At muling nagkaroon ng pagkakabaha-bahagi sa mga Judio dahil sa mga salitang ito.
Sa pamamagitan nito'y naluluwalhati ang aking Ama, na kayo'y magbunga ng marami, at maging mga alagad ko.
Sinabi ni Jose sa kanyang ama, “Sila'y aking mga anak, na ibinigay ng Diyos sa akin dito.” Kanyang sinabi, “Dalhin mo sila sa akin, at sila'y aking babasbasan.”
Lumabas nga si Jesus, na may koronang tinik at balabal na kulay-ube. Sinabi ni Pilato sa kanila, “Narito ang tao!”
Pagkatapos na siya'y kanilang libakin, inalis nila sa kanya ang kulay-ube na balabal at isinuot sa kanya ang kanyang mga damit. At siya'y kanilang inilabas upang ipako sa krus.
na naglilingkod sa Panginoon ng buong kapakumbabaan at may luha, at may mga pagsubok na dumating sa akin dahil sa mga pagtatangka ng mga Judio.
Nalaman ito ng lahat ng naninirahan sa Efeso, mga Judio at gayundin ng mga Griyego; at sinidlan silang lahat ng takot, at pinuri ang pangalan ng Panginoong Jesus.
Pagkakalooban ko ang bayang ito ng biyaya sa paningin ng mga Ehipcio at sa pag-alis ninyo ay hindi kayo aalis na walang dala.
Katotohanang sinasabi ko sa inyo, kung ang sinuman ay tutupad ng aking salita, hindi siya makakakita ng kamatayan kailanman.”
Huwag silang gagawa ng kalbong bahagi sa kanilang ulo, o gugupitin man ang dulo ng kanilang balbas, o hihiwaan man ang kanilang laman.
Nang marinig ng taong-bayan ang masasamang balitang ito ay tumangis sila, at walang taong nagsuot ng kanyang mga palamuti.
“Ang isang lalaki o ang isang babae na sumasangguni sa masasamang espiritu, o mangkukulam, ay tiyak na papatayin. Sila'y babatuhin hanggang mamatay, ang kanilang dugo ay pasan nila.”
Kaya't pinasimulan niyang sumbatan ang mga lunsod na ginawan niya ng karamihan sa kanyang mga makapangyarihang gawa sapagkat hindi sila nagsisi.
At sinabi sa kanila ni Jesus, “Maaari bang magluksa ang mga panauhin sa kasalan samantalang kasama pa nila ang lalaking ikakasal? Ngunit darating ang mga araw na ang lalaking ikakasal ay kukunin sa kanila, at saka sila mag-aayuno.
Sinulatan kita na may pagtitiwala sa iyong pagsunod, yamang nalalaman ko na gagawin mo ang higit pa kaysa aking sinasabi.
at mga bahay na punô ng lahat ng mabubuting bagay, na hindi mo pinunô, at mga balon na hindi mo hinukay, mga ubasan at mga puno ng olibo na hindi mo itinanim, at ikaw ay kakain at mabubusog,
Sinabi niya sa kanya, ‘Hinahatulan kita mula sa sarili mong bibig, ikaw na masamang alipin. Alam mo na ako'y taong mahigpit, na kumukuha ng hindi ko itinabi, at gumagapas ng hindi ko inihasik.
Subalit ang mga kamay ni Moises ay nangalay, kaya't sila'y kumuha ng isang bato at inilagay sa ibaba, at kanyang inupuan. Inalalayan nina Aaron at Hur ang kanyang mga kamay, ang isa'y sa isang panig, at ang isa'y sa kabilang panig; at ang kanyang mga kamay ay nanatili sa itaas hanggang sa paglubog ng araw.
“Magsalita ka sa mga anak ni Israel, at sabihin mo sa kanila: Kapag ang isang tao ay gumawa ng isang maliwanag na panata sa Panginoon tungkol sa katumbas ng isang tao,
Ang lalaki ay maliligtas sa kasamaan ngunit ang babae ay mananagot sa kanyang kasamaan.”
Tumagal ang baha ng apatnapung araw sa ibabaw ng lupa. Lumaki ang tubig at lumutang ang daong, at ito'y tumaas sa ibabaw ng lupa.
Bawat mapapasama sa pagbilang ay magbibigay nito: kalahati ng isang siklo ayon sa siklo ng santuwaryo: (ang isang siklo ay dalawampung gera), kalahating siklo bilang handog sa Panginoon .
Nang sumunod na araw, pagbaba nila mula sa bundok ay sinalubong siya ng napakaraming tao.
Nagpasimulang magsalita si Felipe, at simula sa kasulatang ito ay ipinangaral niya sa kanya ang magandang balita ni Jesus.
Nalagot ang hininga ni Isaac at namatay; at siya'y naging kasama ng kanyang bayan, matanda na at puspos ng mga araw. Inilibing siya ng kanyang mga anak na sina Esau at Jacob.
makatotohanang pananalita, kapangyarihan ng Diyos, sa pamamagitan ng mga sandata ng katuwiran sa kanang kamay at sa kaliwa,
Ito ang Moises, na nagsabi sa mga anak ni Israel, ‘Pipili para sa inyo ang Diyos ng isang propeta mula sa inyong mga kapatid, gaya ng pagpili niya sa akin.’
“Gagawa ka rin ng mga tabing na balahibo ng kambing bilang tolda sa ibabaw ng tabernakulo; labing-isang tabing ang iyong gagawin.
at inyong pinatay ang May-akda ng buhay, na muling binuhay ng Diyos mula sa mga patay; mga saksi kami sa bagay na ito.
Nang si Jesus ay muling tumawid sakay ng bangka sa kabilang ibayo, nagtipon sa palibot niya ang napakaraming tao; at siya'y nasa tabi ng dagat.
Nagsalita ang Panginoon kay Moises, na sinasabi,
Nang umahon sila sa tubig, inagaw ng Espiritu ng Panginoon si Felipe; at hindi na siya nakita ng eunuko at nagagalak na nagpatuloy siya sa kanyang lakad.
Kaya't ihanda ninyo sa gawain ang inyong mga pag-iisip; na supilin ninyo ang inyong sarili at ilagak ang inyong pag-asa sa biyayang darating sa inyo kapag inihayag na si Jesu-Cristo.
“Kapag may nag-away at sinaktan ng isang tao ang kanyang kapwa sa pamamagitan ng bato o ng kanyang kamay, at hindi namatay ang tao, kundi naratay sa higaan;
O iyong pitong tinapay para sa apat na libo at kung ilang kaing ang inyong natipon?
at limang biga para sa mga haligi ng kabilang panig ng tabernakulo, at limang biga sa mga haligi ng panig ng tabernakulo sa likod, sa gawing kanluran.
Wala siya rito, kundi muling nabuhay. Alalahanin ninyo kung paanong siya ay nagsalita sa inyo noong siya'y nasa Galilea pa,
Nag-usap sila sa isa't isa na nagsasabi, “Hindi kasi tayo nagdala ng tinapay.”
Gayundin naman, ang mga babae ay dapat na maging kagalang-galang, hindi mapanirang-puri, kundi mapagpigil, tapat sa lahat ng mga bagay.
Sa ibabaw ng kaing ay naroon ang lahat ng uri ng pagkain para sa Faraon. Subalit ito ay kinakain ng mga ibon mula sa kaing na nasa ibabaw ng aking ulo.”
Ngunit kung ito'y sa Diyos, hindi ninyo sila makakayang wasakin. Baka matagpuan pa kayong nakikipaglaban sa Diyos!”
Aking susuguin ang sindak sa unahan mo, at lilituhin ko ang buong bayan na iyong paroroonan, at aking patatalikurin sa iyo ang lahat ng iyong mga kaaway.
Lahat ng mga babae na ang mga puso ay pinakilos na may kakayahan ay naghabi ng balahibo ng kambing.
Inutusan ko ang inyong mga hukom nang panahong iyon: ‘Pakinggan ninyo ang mga usapin ng inyong mga kapatid, at hatulan ng matuwid ang tao at ang kanyang kapatid, at ang dayuhan na kasama niya.
Kasunod niyon inialay niya ang handog ng bayan. Kinuha niya ang kambing na handog pangkasalanan na para sa bayan, at pinatay ito at inihandog bilang handog pangkasalanan, gaya ng una.
Gayundin ang isang Levita, nang dumating siya sa lugar na iyon at kanyang nakita ang taong iyon, siya ay dumaan sa kabilang panig.
At ang ibang nag-aalinlangan ay inyong kahabagan;
na ang mga ito, sa pamamagitan ng pananampalataya'y lumupig ng mga kaharian, naglapat ng katarungan, nagtamo ng mga pangako, nagpatikom ng mga bibig ng mga leon,
Sabihan mo rin ang matatandang babae na maging magalang sa kanilang asal, hindi mapanirang-puri, ni paalipin man sa alak; dapat silang magturo ng kabutihan,
Ihaharap mo ang mga Levita sa harap ng toldang tipanan at titipunin mo ang buong sambayanan ng mga anak ni Israel.
Kanilang sinabi, “Hindi ba ito'y si Jesus, ang anak ni Jose, na kilala natin ang kanyang ama at ina? Paano niya nasasabi, ‘Ako'y bumabang galing sa langit?’”
At sinabi niya, “Masdan mo, ako'y matanda na at hindi ko nalalaman ang araw ng aking kamatayan.
Kanilang dinala ang lahat ng kanilang nakuha, at ang lahat ng kanilang nasamsam, maging tao at hayop.
Pagkatapos ay sinabi ng Panginoon kay Moises, “Puntahan mo ang Faraon, sapagkat aking pinatigas ang puso niya at ng kanyang mga lingkod, upang aking maipakita itong aking mga tanda sa gitna nila,
At ang halaga ng pantubos sa kanila, mula sa isang buwang gulang ay iyong tutubusin, ayon sa halaga ng limang siklong pilak, ayon sa siklo ng santuwaryo (na dalawampung gera ).
Sumainyo nawang espiritu ang biyaya ng Panginoong Jesu-Cristo.
Kaya't sa ganang akin, nasasabik din akong ipangaral ang ebanghelyo sa inyong mga nasa Roma.
Kung gayon, bakit hindi mo inilagay ang aking salapi sa bangko at nang sa aking pagbalik ay makuha ko iyon pati ng tinubo?’
Sinabi ni Moises, “Kapag binigyan kayo ng Panginoon sa pagsapit ng gabi ng karneng makakain, at sa kinaumagahan ay ng pagkaing makakabusog, sapagkat naririnig ng Panginoon ang inyong mga pagrereklamo na inyong sinasabi laban sa kanya, at ano kami? Ang inyong mga pagrereklamo ay hindi laban sa amin, kundi laban sa Panginoon .”
“Ako ang tunay na puno ng ubas, at ang aking Ama ang tagapag-alaga.
Tingnan ninyo, ipinagpauna ko nang sinabi sa inyo.
“Kapag inanyayahan ka ng sinuman sa kasalan, huwag kang uupo sa upuang pandangal; baka mayroon siyang inanyayahang higit na kilalang tao kaysa iyo,
Ang mga bagay na ito ay isang paghahambing, sapagkat ang mga babaing ito'y dalawang tipan. Ang isa ay si Hagar na mula sa bundok ng Sinai na nanganganak para sa pagkaalipin.
Ikaw ay magiging katatakutan, isang kawikaan at isang bukambibig sa lahat ng bayang pagdadalhan sa iyo ng Panginoon .
At siya'y lumabas, at umiyak nang buong pait.
At kapag ang isang tao ay naghandog sa Panginoon ng handog pangkapayapaan, sa pagtupad ng isang panata o kaya'y kusang-loob na handog mula sa bakahan o sa kawan, ito ay kailangang sakdal upang matanggap; ito ay kailangang walang kapintasan.
Nang ikatlo ng hapon ay sumigaw si Jesus nang may malakas na tinig, “Eloi, Eloi, lama sabacthani?” na ang kahulugan ay, “Diyos ko, Diyos ko, bakit mo ako pinabayaan?”
Ikakalat kayo ng Panginoon sa mga bayan, at kayo'y maiiwang iilan sa bilang sa gitna ng mga bansa na pagtatabuyan sa inyo ng Panginoon .
ang ibang bahagi ng Gilead, at ang buong Basan na kaharian ni Og, ang buong lupain ng Argob, ay aking ibinigay sa kalahating lipi ni Manases. (Ang buong Basan ay tinatawag na lupain ng mga Refaim.
Sapagkat ang kautusan ng Espiritu ng buhay na na kay Cristo Jesus ay nagpalaya sa atin mula sa kautusan ng kasalanan at ng kamatayan.
At mula sa Hades na kanyang pinagdurusahan ay tumingala siya at nakita sa malayo si Abraham at si Lazaro sa kanyang kandungan.
Paano nga ito ibinilang? Iyon ba'y bago siya tinuli o nang tuli na siya? Iyon ay hindi pagkatapos na siya ay tuliin, kundi bago siya tinuli.
Ang maraming tao ay nagkakaisang nakikinig sa mga sinabi ni Felipe nang kanilang marinig siya at nakita ang mga tanda na ginawa niya.
“Kapag ang isang tao ay magtatalaga sa Panginoon ng bahagi ng bukid na kanyang minana, ang iyong paghahalaga ay ayon sa binhi nito; isang omer na binhi ng sebada sa halagang limampung siklong pilak.
“At sa anghel ng iglesya sa Pergamo ay isulat mo: Ang mga bagay na ito ay sinasabi ng may matalas na tabak na may dalawang talim.
upang hanapin ng nalabi sa mga tao ang Panginoon, at ng lahat ng mga Hentil na tinatawag sa aking pangalan,
Habang si Pedro ay nasa bilangguan, ang iglesya ay taimtim na nanalangin sa Diyos para sa kanya.
Hindi maaaring mamunga ng masama ang mabuting puno at mamunga ng mabuti ang masamang puno.
Kanyang tinanggap ang ginto mula sa kanila at hinubog ito sa pamamagitan ng isang kagamitang panlilok, at ginawang isang hinulmang guya. At kanilang sinabi, “Ang mga ito ang iyong mga diyos, O Israel, na naglabas sa iyo mula sa lupain ng Ehipto!”
na nagpupuri sa Diyos, at nagtatamo ng lugod sa lahat ng tao. At idinaragdag sa kanila ng Panginoon araw-araw ang mga naliligtas.
Ang insensong inyong gagawin, ayon sa mga sangkap niyon ay huwag ninyong gagawin para sa inyong sarili; iyon ay aariin mong banal sa Panginoon .
Dinala siya ni Isaac sa tolda ni Sara na kanyang ina. Kinuha niya si Rebecca at siya'y naging asawa niya, at siya'y kanyang minahal. Kaya't naaliw si Isaac pagkamatay ng kanyang ina.
At sinuman ay hindi kumukuha ng karangalang ito para sa kanyang sarili, kundi siya ay tinatawag ng Diyos, na gaya ni Aaron.
Nang masabi na niya ito, at makakuha ng tinapay, ay nagpasalamat siya sa Diyos sa harapan ng lahat. Ito'y kanyang pinagputul-putol at nagsimulang kumain.
Una sa lahat, ay isinasamo ko na gawin ang mga paghiling, mga panalangin, mga pamamagitan, at mga pagpapasalamat patungkol sa lahat ng mga tao;
“Ganito ang ginawa ng Panginoon sa akin nang mga araw na ako'y kanyang bigyang-pansin upang alisin ang aking kahihiyan sa gitna ng mga tao.”
Ang mga sugo ay bumalik kay Jacob, na nagsasabi, “Nakarating kami sa iyong kapatid na si Esau, at siya ay darating din upang sumalubong sa iyo, at kasama niya ang apatnaraang tao.”
Lumapit ang ama sa ikalawa, at gayundin ang sinabi. Sumagot siya at sinabi, ‘Pupunta po ako,’ ngunit hindi pumunta.
Kung sinasabi nating tayo'y hindi nagkasala, ginagawa natin siyang sinungaling at ang kanyang salita ay wala sa atin.
Subalit nang siya'y matauhan ay sinabi niya, ‘Ilan sa mga upahang lingkod ng aking ama ang may sapat at lumalabis na pagkain, ngunit ako rito'y namamatay sa gutom?
Sinabi nila sa kanya, ‘Panginoon, siya'y mayroong sampung mina.’
Pagtawid mo sa Jordan, ilalagay ninyo ang mga batong ito na iniuutos ko sa iyo sa araw na ito, sa bundok ng Ebal at iyong tatapalan ng plaster.
At ang kaloob na walang bayad ay hindi gaya ng ibinunga ng pagkakasala ng isang tao; sapagkat ang kahatulan na dumating na kasunod ng pagkakasala ng isa ay nagbunga ng paghatol, subalit ang kaloob na walang bayad na kasunod ng maraming pagsuway ay nagbunga ng pag-aaring-ganap.
Kaya't yamang napapalibutan tayo ng gayong kakapal na bilang ng mga saksi, itabi natin ang bawat pabigat at ang pagkakasalang madaling bumibitag sa atin, at tumakbo tayong may pagtitiis sa takbuhing inilagay sa harapan natin.
Magbigay sa mga pangangailangan ng mga banal at magmagandang-loob sa mga dayuhan.
Ginawa ng Panginoon ang ayon sa salita ni Moises: inalis niya ang mga pulu-pulutong na langaw mula sa Faraon, sa kanyang mga lingkod, at sa kanyang bayan; walang natira kahit isa.
Kaya maging handa kayo, sapagkat hindi ninyo nalalaman ang araw o ang oras.
Ngayon kung ang pagkahulog nila ay siyang kayamanan ng sanlibutan, at ang pagkalugi nila ay siyang kayamanan ng mga Hentil, gaano pa kaya ang lubos na panunumbalik nila?
Kanyang binalaan sila na sinabi, “Mag-ingat kayo, iwasan ninyo ang lebadura ng mga Fariseo at ang lebadura ni Herodes.”
At saka, talagang siya'y kapatid ko, anak ng aking ama, subalit hindi anak ng aking ina; at siya'y naging asawa ko.
Kanilang minamatyagan si Jesus kung kanyang pagagalingin ang lalaki sa araw ng Sabbath upang siya'y maparatangan nila.
“Kaya nga,” sinabi niya, “ang mga lalaking may awtoridad sa inyo ay sumama sa akin, at kung may anumang pagkakasala ang taong ito, magharap sila ng sakdal laban sa kanya.”
Nang malaman ng isang babaing makasalanan sa lunsod na siya'y nakaupo sa hapag sa bahay ng Fariseo, nagdala ito ng isang sisidlang alabastro na may pabango.
na siyang katawan niya, ang kapuspusan niya na pumupuspos ng lahat sa lahat.
Sapagkat bihirang mangyari na ang isang tao'y mamatay alang-alang sa isang taong matuwid; bagama't alang-alang sa isang mabuting tao marahil ay may mangangahas mamatay.
Sapagkat siya at ang lahat ng kanyang kasama ay namangha dahil sa mga isdang kanilang nahuli,
Sapagkat kay Cristo Jesus, kayong lahat ay mga anak ng Diyos sa pamamagitan ng pananampalataya.
Magiging kanila ang mga lunsod upang tirahan; at ang kanilang mga pastulan ay para sa kanilang mga kawan, mga pag-aari, at sa lahat nilang mga hayop.
Ito ang mga utos at ang mga batas, na iniutos ng Panginoon sa pamamagitan ni Moises sa mga anak ni Israel sa mga kapatagan ng Moab sa tabi ng Jordan sa Jerico.
Ang sinumang napopoot sa kanyang kapatid ay isang mamamatay-tao, at nalalaman ninyong ang buhay na walang hanggan ay hindi nananatili sa sinumang mamamatay-tao.
Subalit alinmang walang mga palikpik at mga kaliskis sa mga nasa dagat, nasa ilog, at sa alinmang mga gumagalaw sa mga nasa tubig, at sa lahat ng may buhay sa tubig, ay marumi para sa inyo.
“Kung ang sinuman ay matagpuang nagnanakaw ng sinuman sa kanyang mga kapatid sa mga anak ni Israel, at kanyang inalipin siya o ipinagbili siya, ang magnanakaw na iyon ay papatayin. Gayon mo aalisin ang kasamaan sa gitna mo.
Ngunit si Tomas, isa sa labindalawa na tinatawag na Kambal ay hindi nila kasama nang dumating si Jesus.
Itinaas niya ang kanyang paningin at nakita ang tatlong lalaki na nakatayo na malapit sa kanya. Nang sila'y kanyang makita, tumakbo siya upang sila'y salubungin mula sa pintuan ng tolda, at yumuko siya sa lupa.
Subalit nang magtangka ang mga mandaragat na makaalis sa barko at ibinaba ang bangka sa dagat, na ang idinadahilan ay maghuhulog sila ng mga angkla sa unahan,
Pagkatapos ng mga iyon, magkakaroon ng pitong taong taggutom at ang lahat ng kasaganaan sa lupain ng Ehipto ay malilimutan at sasalantain ng taggutom ang lupain.
Kaya't kanilang iningatan ang pananalitang ito sa kanilang sarili, na pinag-uusapan kung ano ang kahulugan ng pagbangon mula sa mga patay.
Samakatuwid, ay hindi mga anak sa laman ang mga anak ng Diyos, kundi ang mga anak ng pangako ay siyang itinuturing bilang binhi.
Subalit ang bunga ng Espiritu ay pag-ibig, kagalakan, kapayapaan, pagtitiyaga, kagandahang-loob, kabutihan, katapatan,
Nakakita ako ng mga trono, at ang mga nakaupo sa mga iyon ay pinagkalooban ng kapangyarihang humatol. Nakita ko rin ang mga kaluluwa ng mga pinugutan ng ulo dahil sa patotoo kay Jesus, at dahil sa salita ng Diyos, at ang mga hindi sumamba sa halimaw, o sa kanyang larawan man, at hindi tumanggap ng tanda sa kanilang noo at sa kanilang kamay. Sila'y nabuhay at nagharing kasama ni Cristo sa loob ng isang libong taon.
At sinabi ng mga nakarinig nito, “Sino kaya ang maliligtas?”
Ngunit ang aking lingkod na si Caleb, sapagkat siya'y nagtaglay ng ibang espiritu at sumunod nang lubos sa akin, ay dadalhin ko sa lupain na kanyang pinaroonan; at aariin ng kanyang mga binhi.
dahil sa pag-asa na nakalaan para sa inyo sa langit, na inyong narinig noong una sa salita ng katotohanan, ang ebanghelyo,
o ng anumang bato na ikamamatay ng tao, na hindi niya nakikita at kanyang naihagis sa kanya, na anupa't namatay at hindi niya kaaway, at hindi niya pinaghahangaran ng masama;
At nakita namin doon ang mga Nefilim, ang mga anak ni Anak, na mula sa mga Nefilim; at kami sa aming sariling paningin ay naging parang mga tipaklong, at gayundin kami sa kanilang paningin.”
Mga minamahal, huwag kayong magtaka tungkol sa mahigpit na pagsubok na dumarating sa inyo upang kayo'y subukin, na waring may isang kataka-takang bagay na nangyayari sa inyo.
At ang lahat ng mga kakilala niya at ang mga babaing sa kanya'y sumunod buhat sa Galilea ay nakatayo sa malayo at nakita ang mga bagay na ito.
Binalot niya iyon ng lantay na ginto, at iginawa niya ng isang moldeng ginto sa palibot.
At kung hindi, samantalang malayo pa ang isa ay magpapadala na siya ng isang sugo at hihilingin ang mga kasunduan sa kapayapaan.
Huwag mong ililitaw ang kahubaran ng asawa ng iyong kapatid na lalaki; siya ay kahubaran ng iyong kapatid na lalaki.
Kunin mo ang para sa iyo at umalis ka na. Nais kong ibigay sa huling nagtrabaho ang kagaya ng ibinigay ko sa iyo.
Mga mangangalunya! Hindi ba ninyo nalalaman na ang pakikipagkaibigan sa sanlibutan ay pakikipag-away sa Diyos? Kaya't sinumang nagnanais na maging kaibigan ng sanlibutan ay nagiging kaaway ng Diyos.
Ito ang patotoo ni Juan nang suguin ng mga Judio ang mga pari at mga Levita mula sa Jerusalem upang siya'y tanungin, “Sino ka ba?”
Ibinangon ng Diyos ng ating mga ninuno si Jesus, na inyong pinatay nang ibitin siya sa isang punungkahoy.
Ngunit sumagot si Jesus at sinabi, “Hindi ninyo nalalaman ang inyong hinihingi. Kaya ba ninyong inuman ang kopa na malapit ko nang inuman? Sinabi nila sa kanya, “Kaya namin.”
At hihingin ko sa Ama, at kayo'y bibigyan niya ng isa pang Mang-aaliw, upang makasama ninyo siya magpakailanman.
Kaya't sinabi nila sa isa't isa, “Maglagay tayo ng isang pinuno at tayo'y magbalik sa Ehipto.”
“Alalahanin mo ang ginawa sa iyo ng Amalek sa daan nang ikaw ay lumabas sa Ehipto;
“Makinig kayo. Ang isang manghahasik ay lumabas upang maghasik.
upang huwag nila kayong turuang gumawa ng ayon sa lahat nilang karumaldumal na mga gawa na kanilang ginawa sa kanilang mga diyos upang kayo'y magkasala laban sa Panginoon ninyong Diyos.
at nang sila'y makalayo, ay sinabi nila sa isa't isa, “Ang taong ito ay walang anumang ginagawa na marapat sa kamatayan o sa mga tanikala.”
Hindi dahil sa kami ay walang karapatan, kundi upang maibigay namin ang aming mga sarili sa inyo bilang huwaran na dapat tularan.
at ipinagpalit nila ang kaluwalhatian ng Diyos na hindi nasisira sa mga imaheng kahawig ng tao na nasisira, at ng mga ibon, ng mga hayop na may apat na paa at ng mga gumagapang.
Sapagkat sa aking pagdaraan, at sa pagmamasid ng mga bagay na inyong sinasamba, ay nakatagpo din naman ako ng isang dambana na may sulat na ganito, ‘SA ISANG DI-KILALANG DIYOS.’ Kaya't ang sinasamba ninyo na hindi kilala ay siyang ipahahayag ko sa inyo.
Sa patnubay ng Espiritu ay pumasok siya sa templo. Nang ipasok ng mga magulang sa templo ang sanggol na si Jesus upang gawin sa kanya ang naaayon sa kaugalian sa ilalim ng kautusan,
Kaya't mag-ingat kayo kung paano kayo nakikinig, sapagkat siyang mayroon ay lalo pang bibigyan at ang sinumang wala, pati na ang inaakala niyang nasa kanya ay kukunin.”
“Ako'y namalagi sa bundok, gaya ng una, apatnapung araw at apatnapung gabi, at ako'y pinakinggan din noon ng Panginoon ; ayaw ng Panginoon na puksain ka.
Kung siya'y pumasok na mag-isa, siya ay aalis na mag-isa, kung siya ay pumasok na may asawa, ang kanyang asawa nga ay aalis na kasama niya.
Sapagkat tayong sumasampalataya ay pumapasok sa kapahingahang iyon, gaya ng sinabi ng Diyos, “Gaya ng aking isinumpa sa aking pagkagalit, sila'y hindi papasok sa aking kapahingahan,” bagama't ang mga gawa niya mula nang itatag ang sanlibutan ay natapos na.
Ako ang tinapay ng buhay.
Sapagkat sinabi ni Juan sa kanya, “Hindi ipinahihintulot sa iyo na angkinin mo siya.”
Alam din ni Judas, na sa kanya'y nagkanulo, ang lugar sapagkat madalas na si Jesus ay nakikipagtipon doon kasama ng kanyang mga alagad.
At ang mga kumain ay may limang libong lalaki, bukod pa sa mga babae at sa mga bata.
Ang babae ay nakadamit ng kulay-ube at ng matingkad na pula, nagagayakan ng ginto at ng mahahalagang bato at mga perlas, at hawak sa kanyang kamay ang isang kopang ginto na punô ng mga karumaldumal at mga bagay na marurumi ng kanyang pakikiapid,
Mga kapatid, ako ay nagsasalita ayon sa tao, kapag napagtibay na ang tipan ng isang tao, walang makapagdaragdag o makapagpapawalang-bisa nito.
Dumating ang ikalawa, na nagsasabi, ‘Panginoon, tumubo ang iyong mina ng limang mina.’
At binuka niya ang kanyang bibig at tinuruan sila, na sinasabi:
Kaya't inihagis ng anghel ang kanyang karit sa lupa, at tinipon ang mga ubas sa lupa, at inihagis sa malaking pisaan ng ubas ng poot ng Diyos.
Kumuha kayo sa inyo ng isang handog para sa Panginoon ; sinumang may mapagbigay na puso ay magdala ng handog sa Panginoon : ginto, pilak, at tanso;
at upang kayo'y mabuhay nang matagal sa lupain na ipinangako ng Panginoon sa inyong mga ninuno na ibibigay sa kanila at sa kanilang binhi, isang lupaing dinadaluyan ng gatas at pulot.
Sabihin ninyo sa akin, kayong nagnanais mapasailalim ng kautusan, hindi ba ninyo naririnig ang kautusan?
mag-ingat ka upang huwag kang mabitag na sumunod sa kanila, pagkatapos na sila'y mapuksa sa harapan mo. Huwag kang mag-usisa ng tungkol sa kanilang mga diyos, na magsabi, ‘Paanong naglingkod ang mga bansang ito sa kanilang mga diyos? Gayundin ang gagawin ko.’
Susuriin ng pari ang bagay na may sakit pagkatapos na malabhan; at kung makitang ang sakit ay hindi nagbago ng anyo nito, at kung hindi kumalat ang sakit, ito ay marumi. Susunugin mo ito sa apoy, maging ang bahaging may ketong ay nasa likuran o sa harapan.
Sapagkat tunay na sinasabi ko sa inyo, ang sinumang magpainom sa inyo ng isang tasang tubig dahil sa kayo'y kay Cristo, ay hindi mawawalan ng kanyang gantimpala.
Hindi sa tinatanggap ko ang patotoong mula sa tao, subalit sinasabi ko ang mga bagay na ito upang kayo'y maligtas.
Siya'y bumaba sa Capernaum, na isang bayan ng Galilea. At siya'y nagturo sa kanila sa araw ng Sabbath.
Sinabi niya sa kanila, “Ako'y lubhang nalulungkot, hanggang sa kamatayan; manatili kayo rito at manatiling gising.”
Sila'y namumulot tuwing umaga, bawat tao ayon sa kanyang kailangan, ngunit kapag ang araw ay umiinit na, ito ay natutunaw.
Nawa'y ibigay niya sa iyo ang pagpapala ni Abraham, sa iyo at sa lahat ng iyong binhi; upang ariin mo ang lupaing iyong pinaglakbayan na ibinigay ng Diyos kay Abraham.”
Nabalitaan ng Cananeo na hari sa Arad, na naninirahan sa Negeb sa lupain ng Canaan, ang pagdating ng mga anak ni Israel.
“Mag-ingat kayo sa mga bulaang propeta, na lumalapit sa inyo na may damit tupa, ngunit sa loob ay mga ganid na asong-gubat.
Sila'y inawitan ni Miriam: “Umawit kayo sa Panginoon , sapagkat siya'y maluwalhating nagtagumpay; nang inihagis niya sa dagat ang kabayo at ang doo'y nakasakay.”
“Ngunit nang nalalapit na ang panahong ipinangako ng Diyos kay Abraham, ang ating sambayanan ay lumago at dumami sa Ehipto,
Tingnan ninyo kung sa gaano kalalaking mga titik sumusulat ako sa inyo sa pamamagitan ng aking sariling kamay!
Sinabi sa kanila ni Jesus, “Hindi pa dumating ang aking oras, subalit ang inyong oras ay laging naririyan.
Siya'y natakot, at kanyang sinabi, “Kakilakilabot ang lugar na ito! Ito'y walang iba kundi ang bahay ng Diyos, at ito ang pintuan ng langit.”
at ako'y magiging ama sa inyo, at kayo'y magiging aking mga anak na lalaki at babae, sabi ng Panginoong Makapangyarihan sa lahat.”
Pagkakabitin mo ang limang tabing, at gayundin ang anim na tabing, at ititiklop mo ang ikaanim na tabing sa harapan ng tolda.
Ngunit si Pedro, na nakatayong kasama ng labing-isa, ay nagtaas ng kanyang tinig, at nagpahayag sa kanila, “Kayong mga kalalakihan ng Judea at kayong lahat na naninirahan sa Jerusalem, malaman sana ninyo ito, at makinig kayo sa aking sasabihin.
Ang nagpapahalaga sa araw ay nagpapahalaga nito sa Panginoon; at ang kumakain ay kumakain para sa Panginoon, sapagkat siya'y nagpapasalamat sa Diyos; at ang hindi kumakain para sa Panginoon ay hindi kumakain at nagpapasalamat sa Diyos.
Sila'y mga Israelita, na sa kanila ang pagkukupkop, at ang kaluwalhatian, at ang mga tipan, at ang pagtanggap sa kautusan, at ang pagsamba at ang mga pangako;
Sinabi ni Jacob, “O Diyos ng aking amang si Abraham, at Diyos ng aking amang si Isaac, O Panginoon , na nagsabi sa akin, ‘Bumalik ka sa iyong lupain at sa iyong kamag-anak at gagawa ako ng mabuti sa iyo.’
Ngunit ang tao na makagawa ng anuman nang buong kapusukan, maging katutubo sa lupain o dayuhan ay lumalapastangan sa Panginoon at ang taong iyon ay ititiwalag sa gitna ng kanyang bayan.
Kung hindi siya kinalugdan ng kanyang amo na umangkin sa kanya bilang asawa, ay kanyang ipapatubos siya; wala siyang karapatang ipagbili siya sa isang dayuhan, yamang siya'y hindi niya pinakitunguhan nang tapat.
Ganito ang pagkapanganak kay Jesu-Cristo. Nang si Maria na kanyang ina ay nakatakdang ikasal kay Jose, bago sila magsama, si Maria ay natuklasang nagdadalang-tao sa pamamagitan ng Espiritu Santo.
Nagsalita ang Panginoon kay Moises, na sinasabi,
At maliwanag na sinabi niya ang salitang ito. Inilayo siya ni Pedro at pinasimulang siya'y sawayin.
Nakita ng Diyos ang lahat ng kanyang nilikha at ito ay napakabuti. Nagkaroon ng gabi at nagkaroon ng umaga nang ikaanim na araw.
Kaya't magsalita kayo at kumilos na gaya ng mga taong hahatulan sa pamamagitan ng kautusan ng kalayaan.
Gayon niya lilinisin ang bahay sa pamamagitan ng dugo ng ibon, ng agos ng tubig, ng ibong buháy, ng kahoy na sedro, ng isopo, at ng pulang sinulid;
Itatatag ka ng Panginoon na isang banal na bayan para sa kanya, gaya ng kanyang ipinangako sa iyo, kung iyong gaganapin ang mga utos ng Panginoon mong Diyos, at lalakad ka sa kanyang mga daan.
At kanyang sinabi, “Ako ngayo'y nakikipagtipan. Sa harap ng iyong buong bayan ay gagawa ako ng mga kababalaghan na kailanma'y hindi ginawa sa buong lupa, o sa alinmang bansa; at ang buong bayan na kasama ay makakakita ng gawa ng Panginoon , sapagkat kakilakilabot na bagay ang aking gagawing kasama mo.
Ako'y totoong nagagalak sa Panginoon, na ngayon sa wakas ay inyong muling binuhay ang inyong pagmamalasakit sa akin; na dito'y katotohanang nagkaroon kayo ng malasakit, ngunit wala kayong pagkakataon.
Siya'y nagpatirapa sa paanan ni Jesus na nagpapasalamat sa kanya. Siya'y isang Samaritano.
Kaya't isinulat ni Moises ang awit na ito nang araw ding iyon at itinuro sa mga anak ni Israel.
Kumain silang lahat at nabusog.
Ang tumanggap ng limang talento ay umalis kaagad at ipinangalakal niya ang mga iyon, at nakinabang siya ng lima pang talento.
Sinabi niya, “Sino ka, Panginoon?” At siya'y sumagot, “Ako si Jesus na iyong inuusig.
Sila'y muling pumunta sa Jerusalem. Samantalang naglalakad siya sa templo, lumapit sa kanya ang mga punong pari, ang mga eskriba, at ang matatanda.
Lahat ng katutubo sa lupain ay gagawa ng mga bagay na ito sa ganitong paraan, sa paghahandog ng handog na pinaraan sa apoy, na mabangong samyo sa Panginoon .
Pagkatapos, si Balaam ay tumindig at bumalik sa kanyang lugar; at si Balak ay umalis na rin.
Kung tayo'y nabubuhay sa pamamagitan ng Espiritu, lumakad din tayo sa patnubay ng Espiritu.
Nagsalita ang Panginoon kay Moises, na sinasabi,
Ang tubig ay bumalik at tinakpan ang mga karwahe, ang mga mangangabayo, ang buong hukbo ng Faraon na sumunod sa kanila sa dagat; walang natira kahit isa sa kanila.
Ruben, ikaw ang aking panganay, ang aking kalakasan, ang siyang pasimula ng aking kapangyarihan, ang pinakamataas sa karangalan at kalakasan, at siyang kasakdalan ng kapangyarihan.
Kaya, mga kapatid, yamang mayroon tayong pagtitiwala na pumasok sa santuwaryo sa pamamagitan ng dugo ni Jesus,
“‘Sumpain ang sumisiping sa kanyang kapatid na babae, sa anak ng kanyang ama, o sa anak na babae ng kanyang ina.’ At ang buong bayan ay magsasabi, ‘Amen.’
na doo'y naunang pumasok para sa atin si Jesus, na naging pinakapunong pari magpakailanman ayon sa pagkapari ni Melquizedek.
At nang bumaba sila sa bangka, agad siyang nakilala ng mga tao.
“Sabihin ninyo sa mga anak ni Israel: Ito ang mga bagay na may buhay na maaari ninyong kainin sa lahat ng mga hayop na nasa lupa.
At sumakay sa daong si Noe at ang kanyang mga anak, ang kanyang asawa, at ang mga asawa ng kanyang mga anak upang umiwas sa tubig ng baha.
Kaya't natupad ang kasulatan na nagsasabi, “Si Abraham ay sumampalataya sa Diyos, at iyo'y ibinilang sa kanya na katuwiran,” at siya'y tinawag na kaibigan ng Diyos.
Bumagsak ako sa lupa, at narinig ko ang isang tinig na nagsasabi sa akin, ‘Saulo, Saulo, bakit mo ako pinag-uusig?’
“Gagawa ka ng pektoral ng kahatulan, na gawa ng bihasang manggagawa. Gagawin mo iyon na gaya ng pagkagawa sa efod; gagawin mo iyon na yari sa ginto, telang asul, kulay-ube, pula, at hinabing pinong lino.
Ang taong-bayan ay nagsisigaw, “Tinig ng diyos at hindi ng tao!”
Sinabi ng hari ng Sodoma kay Abram, “Ibigay mo sa akin ang mga tao at kunin mo ang mga ari-arian para sa iyong sarili.”
Sapagkat ang mga kaloob at ang pagtawag ng Diyos ay hindi mababago.
At ilalagay mo sa hapag ang tinapay na handog sa harap ko palagi.
At pagkatapos siya'y nagpakita sa labing-isa samantalang sila'y nakaupo sa hapag-kainan; sila'y kanyang pinagsabihan dahil sa kawalan nila ng pananampalataya at katigasan ng puso, sapagkat hindi nila pinaniwalaan ang mga nakakita sa kanya pagkatapos na siya'y muling mabuhay.
Huwag kayong padaya kanino man sa anumang paraan, sapagkat ito'y hindi darating malibang maunang maganap ang pagtalikod, at mahayag ang taong makasalanan, ang anak ng kapahamakan.
Ngunit nang naniwala sila kay Felipe na nangangaral ng mabuting balita tungkol sa kaharian ng Diyos at sa pangalan ni Jesu-Cristo, sila ay nabautismuhan, mga lalaki at mga babae.
kay Semida, ang angkan ng mga Semidaita; at kay Hefer, ang angkan ng mga Heferita.
Pagkatapos nito, si Moises at si Aaron ay pumunta kay Faraon at sinabi, “Ganito ang sabi ng Panginoon , ang Diyos ng Israel, ‘Hayaan mong umalis ang aking bayan upang magdiwang sila ng kapistahan sa ilang para sa akin.’”
Umalis si Jesus doon at pumasok sa kanilang sinagoga.
Ngunit kanino siya galit nang apatnapung taon? Hindi ba sa mga nagkasala, na ang mga katawan ay nabuwal sa ilang?
At muling sumigaw si Jesus ng may malakas na tinig at nalagot ang kanyang hininga.
Sapagkat walang bagay na nakatago na hindi ihahayag; o walang nalilihim na hindi ilalantad sa liwanag.
Si Abraham ay siyamnapu't siyam na taong gulang nang tuliin ang balat ng kanyang maselang bahagi.
Sapagkat narito, darating ang mga araw, na kanilang sasabihin, ‘Mapapalad ang mga baog, at ang mga tiyan na kailanma'y hindi nagdalang-tao, at ang mga dibdib na kailanman ay hindi nagpasuso!’
Nang gabing si Pedro ay malapit nang ilabas ni Herodes, natutulog siya sa pagitan ng dalawang kawal na nakagapos ng dalawang tanikala at ang mga bantay sa harap ng pintuan ay nagbabantay sa bilangguan.
sapagkat minamasdan niya ang kanyang sarili at umaalis, at agad niyang nalilimutan kung ano ang kanyang katulad.
Ang mga hayop lamang ang para sa ating sarili, at sinamsaman ang mga lunsod na ating sinakop.
Sinasabi ko sa inyo, nanaog patungo sa kanyang bahay ang taong ito na inaring-ganap sa halip na ang isa. Sapagkat ang bawat nagmamataas sa kanyang sarili ay ibababa, ngunit ang nagpapakababa sa kanyang sarili ay itataas.”
Kukunin niya ang ibong buháy, ang kahoy na sedro, ang lanang pula at ang isopo, at itutubog ang mga ito at ang ibong buháy sa dugo ng ibong pinatay sa ibabaw ng tubig na umaagos.
At pupunuan ng aking Diyos ang bawat kailangan ninyo ayon sa kanyang mga kayamanan sa kaluwalhatian kay Cristo Jesus.
Ngunit siya'y sinaway sa kanyang sariling pagsuway; isang asnong hindi makapagsalita ang nagsalita sa tinig ng tao at pinigil ang kabaliwan ng propeta.
Nasaan na ngayon ang inyong kagandahang-loob? Sapagkat ako'y nagpapatotoo sa inyo, na kung maaari sana ay dinukit na ninyo ang inyong mga mata at ibinigay sa akin.
Kayong mga mangmang at mga bulag! Alin ba ang higit na dakila, ang ginto, o ang templo na nagpapabanal sa ginto?
Nagsalita si Ruben sa kanyang ama, “Maaari mong ipapatay ang aking dalawang anak kung hindi ko siya maibabalik sa iyo. Ibigay mo siya sa akin at siya'y ibabalik ko sa iyo.”
Sapagkat kanino sa mga anghel sinabi ng Diyos kailanman, “Ikaw ay aking Anak, ako ngayon ay naging iyong Ama?” At muli, “Ako'y magiging kanyang Ama, at siya'y magiging aking Anak?”
Sa paglalakbay namin mula roon, dumating kami nang sumunod na araw sa tapat ng Chios. Nang sumunod na araw ay tumawid kami patungong Samos, at nakarating kami sa Mileto nang sumunod na araw.
Subalit nais mo bang malaman, O taong hangal, na ang pananampalataya na walang mga gawa ay baog?
Pagdating nila sa Efeso sila'y iniwan niya roon; ngunit pumasok muna siya sa sinagoga at nakipagtalo sa mga Judio.
Lumapit ang pinunong kapitan at tinanong si Pablo, “Sabihin mo sa akin, ikaw ba'y mamamayang Romano?” At sinabi niya, “Oo.”
Nang marinig niyang ako'y nagtaas ng tinig at nagsisigaw, naiwan niya ang kanyang suot sa aking tabi at tumakas, at lumabas ng bahay.”
Kaya't huwag ninyong paghariin ang kasalanan sa inyong katawang may kamatayan, upang masunod ang mga pagnanasa nito.
Kinabukasan, si Moises ay naupo bilang hukom ng bayan, at ang taong-bayan ay tumayo sa palibot ni Moises mula sa umaga hanggang sa gabi.
Kukunin ng matatanda sa lunsod na iyon ang lalaki at siya'y hahagupitin;
At ginawa ni Noe ang ayon sa lahat ng iniutos sa kanya ng Panginoon .
Ang kasaganaan sa lupain ay hindi maaalala dahil sa taggutom na susunod; sapagkat ito'y magiging napakatindi.
Ang hindi nagmamahal sa akin ay hindi tumutupad ng aking mga salita, at ang salitang inyong narinig ay hindi akin, kundi sa Amang nagsugo sa akin.
Nang mabalitaan ni Balak na si Balaam ay dumarating, lumabas siya upang salubungin siya sa bayan ng Moab, na nasa hangganan ng Arnon, na siyang dulong bahagi ng hangganan.
ang asawa ng kanyang kapatid ay lalapit sa kanya sa harapan ng matatanda at huhubarin ang sandalyas sa kanyang mga paa, at luluraan siya sa mukha; at siya'y sasagot at sasabihin, ‘Ganyan ang gagawin sa lalaking ayaw magtindig ng sambahayan ng kanyang kapatid.’
Lahat ay lumihis, sama-sama silang nawalan ng kabuluhan; walang gumagawa ng mabuti, wala, wala kahit isa.”
pinili at itinalaga ng Diyos Ama, at ginawang banal ng Espiritu upang sumunod kay Jesu-Cristo at mawisikan ng kanyang dugo: Biyaya at kapayapaan nawa ang sa inyo'y sumagana.
Umulan sa ibabaw ng lupa sa loob ng apatnapung araw at apatnapung gabi.
Ngunit lumingon siya at sinabi kay Pedro, “Layuan mo ako, Satanas! Ikaw ay isang katitisuran sa akin; sapagkat hindi mo iniisip ang mga bagay ng Diyos, kundi ang mga bagay ng tao.”
Iwinisik niya ang iba nito sa ibabaw ng dambana ng pitong ulit, at binuhusan ng langis ang dambana at ang lahat ng kasangkapan niyon, ang hugasan at ang tuntungan niyon, upang italaga ang mga iyon.
Gayunma'y, kung tumagal ang alipin ng isa o dalawang araw, hindi siya parurusahan; sapagkat siya'y kanyang salapi.
Sapagkat nalalaman niya kung sino ang magkakanulo sa kanya, kaya't sinabi niya, “Hindi lahat sa inyo ay malilinis.”
Kaya't ang mga nasa Judea ay dapat tumakas patungo sa mga bundok; at ang mga nasa loob ng lunsod ay lumabas, at ang mga nasa labas ng lupain ay huwag pumasok doon;
Aking makikita siya, ngunit hindi ngayon; aking pagmamasdan siya, ngunit hindi sa malapit: Lalabas ang isang bituin sa Jacob, at may isang setro na lilitaw sa Israel, at dudurugin ang noo ng Moab, at lilipulin ang lahat ng mga anak ng kaguluhan.
Sinabi sa kanila ni Jesus, “Hindi ba't ito ang dahilan kaya kayo nagkakamali, hindi ninyo nalalaman ang mga kasulatan, o ang kapangyarihan ng Diyos?
Ang aming mga bata, mga asawa, kawan at buong bakahan ay mananatili riyan sa mga bayan ng Gilead.
Kaya't iniwan ni Moises ang Faraon at nanalangin sa Panginoon .
At sinundan siya ng napakaraming tao mula sa Galilea, Decapolis, Jerusalem, Judea at mula sa ibayo ng Jordan.
Sapagkat ipinasiya ko sa aking sarili, na hindi na ako muling paririyan sa inyo na may malungkot na pagdalaw.
Ngunit nang marinig ng mga Fariseo na napatahimik ni Jesus ang mga Saduceo, ay nagtipon sila.
Siya'y tulad sa isang taong nagtatayo ng bahay, na humukay ng malalim at inilagay ang pundasyon sa ibabaw ng bato. Nang dumating ang isang baha, humampas ang tubig sa bahay na iyon, ngunit hindi ito natinag, sapagkat mahusay ang pagkakatayo nito.
Iyong ilalagay ang dalawang bato sa ibabaw ng pambalikat ng efod, upang maging mga batong alaala para sa mga anak ni Israel; at papasanin ni Aaron ang kanilang mga pangalan sa harapan ng Panginoon , sa ibabaw ng kanyang dalawang balikat, upang maging alaala.
Nang masaksihan ng buong bayan ang mga kulog at kidlat, ang tunog ng trumpeta at ang bundok na umuusok, ay natakot sila at nanginig, at sila'y tumayo sa malayo.
Silang lahat ay may labindalawang lalaki.
Sapagkat dito kami ay dumaraing, na nasasabik mabihisan ng aming makalangit na tahanan,
Bilang ganti, nagsasalita akong tulad sa mga bata; palawakin din ninyo ang inyong mga puso.
Katotohanang sinasabi ko sa inyo, ang sumasampalataya sa akin ay gagawin din ang mga gawang aking ginagawa, at lalong dakilang mga gawa kaysa rito ang gagawin niya, sapagkat ako'y pupunta sa Ama.
at nagsabi, “Panginoon, mahabag ka sa aking anak na lalaki, sapagkat siya'y may epilepsiya at lubhang nahihirapan; sapagkat madalas siyang bumabagsak sa apoy at sa tubig.
At nagkaroon ng mainitang pagtatalo, anupa't sila'y naghiwalay, at isinama ni Bernabe si Marcos, at naglayag patungong Cyprus.
Kapag nagsimulang mangyari ang mga bagay na ito, tumingala kayo at itaas ninyo ang inyong mga ulo, sapagkat malapit na ang katubusan ninyo.”
Ang mga ito'y ang dalawang punong olibo at ang dalawang ilawan na nakatayo sa harapan ng Panginoon ng lupa.
Saan ako kukuha ng karne upang ibigay sa buong bayang ito? Sapagkat sila'y umiyak sa akin, na nagsasabi, ‘Bigyan mo kami ng karneng makakain namin.’
Pagkatapos, ipinag-utos ng pinakapunong paring si Ananias sa mga nakatayong malapit sa kanya na siya'y hampasin sa bibig.
Ang langit ay nahawi na gaya ng isang balumbong nilululon, at ang bawat bundok at pulo ay naalis sa kanilang kinalalagyan.
“Kaya't sundin ninyo ang lahat ng utos na aking iniuutos sa inyo sa araw na ito, upang kayo'y lumakas, makapasok at angkinin ang lupain na inyong tatawirin;
ni huwag mo ring papanigan ang dukha sa kanyang usapin.
Mag-ingat ka na huwag makipagtipan sa mga nakatira sa lupain na iyong patutunguhan, baka ito'y maging isang bitag sa gitna mo.
Nabuhay si Enos ng siyamnapung taon at naging anak niya si Kenan.
Nagalit ang mga bansa, ngunit dumating ang iyong poot, at ang panahon upang hatulan ang mga patay, at upang bigyan ng gantimpala ang iyong mga alipin, ang mga propeta, at ang mga banal, at ang mga natatakot sa iyong pangalan, ang mga hamak at dakila, at upang puksain mo ang mga pumupuksa sa lupa.”
na sa pamamagitan ng paniniwala dito ang ilan ay nalihis sa pananampalataya. Sumainyo nawa ang biyaya.
Nang dumating ang ikalabing-apat na gabi, samantalang kami'y ipinapadpad ng hangin sa kabila ng Dagat ng Adriatico, nang maghahating-gabi na ay inakala ng mga mandaragat na sila'y papalapit na sa lupa.
Hinawakan niya sa kamay ang lalaking bulag at dinala niya sa labas ng nayon. Nang maduraan ang kanyang mga mata at maipatong ang kanyang mga kamay sa kanya, kanyang tinanong siya, “May nakikita ka bang anuman?”
