Huwag kayong padaya kanino man sa anumang paraan, sapagkat ito'y hindi darating malibang maunang maganap ang pagtalikod, at mahayag ang taong makasalanan, ang anak ng kapahamakan.
Sapagkat hindi namin ipinangangaral ang aming sarili, kundi si Cristo Jesus bilang Panginoon, at kami ay inyong mga lingkod dahil kay Cristo.
Umahon si Lot papalabas sa Zoar at tumira sa bundok kasama ang kanyang dalawang anak na babae sapagkat siya'y takot na tumira sa Zoar. Siya'y tumira sa isang yungib kasama ang kanyang dalawang anak na babae.
Ngunit kung ang Panginoon ay lumikha ng isang bagong bagay, at ibuka ng lupa ang kanyang bibig at sila'y lamunin, kasama ng lahat ng nauukol sa kanila, at sila'y buháy na ibaba sa Sheol, inyo ngang malalaman na hinamak ng mga taong ito ang Panginoon .”
Ikaw ay magkakaanak ng mga lalaki at mga babae, ngunit sila'y hindi magiging iyo; sapagkat sila'y pupunta sa pagkabihag.
Ipapatong niya ang kanyang kamay sa ulo ng kanyang alay, at papatayin ito sa pintuan ng toldang tipanan; at iwiwisik ng mga anak ni Aaron na mga pari ang dugo sa palibot ng dambana.
Sapagkat nakita nila noong una na kasama niya sa lunsod si Trofimo na taga-Efeso, at iniisip nilang ipinasok siya ni Pablo sa templo.
Kinaumagahan, si Balaam ay bumangon at sinabi sa mga pinuno ni Balak, “Umuwi na kayo sa inyong lupain, sapagkat ang Panginoon ay tumanggi na ako'y sumama sa inyo.”
ngunit ang mga alalahanin ng sanlibutan, ang pang-akit ng mga kayamanan, at ang mga pagnanasa sa ibang bagay ay pumasok at sinakal ang salita at ito'y hindi nakapamunga.
Sapagkat ang mabuti na aking nais ay hindi ko ginagawa, ngunit ang masama na hindi ko nais ay siya kong ginagawa.
Ngunit kayo'y may kaugalian na maaari kong pakawalan ang isang tao para sa inyo sa Paskuwa. Gusto ba ninyong pakawalan ko para sa inyo ang Hari ng mga Judio?”
Nahikayat ang ilan sa kanila at sumama kina Pablo at kay Silas, gayundin ang napakaraming mga Griyegong masisipag sa kabanalan, at hindi kakaunting mga pangunahing babae.
Ang huli ay gumagawa dahil sa pag-ibig, palibhasa'y nalalaman na ako'y itinalaga sa pagtatanggol sa ebanghelyo;
Nabuhay si Reu ng dalawang daan at pitong taon pagkatapos na maipanganak si Serug, at nagkaanak pa ng mga lalaki at mga babae.
Si Josue na anak ni Nun, na lingkod ni Moises, na isa sa kanyang mga piling lalaki ay sumagot, “Aking panginoong Moises, pagbawalan mo sila!”
At tuwing makikita siya ng masasamang espiritu, sila'y nagpapatirapa sa kanyang harapan, at sumisigaw, “Ikaw ang Anak ng Diyos.”
sa ikatlong hanay ay jacinto, agata, at ametista;
Gayunma'y ang Kataas-taasan ay hindi naninirahan sa mga bahay na gawa ng mga kamay; gaya ng sinasabi ng propeta,
Pagsapit ng gabi, umupo siyang kasalo ng labindalawang alagad.
Sapagkat bagaman ako ay nagmamalaki ng labis tungkol sa aming kapamahalaan na ibinigay ng Panginoon upang kayo ay patatagin at hindi upang kayo ay gibain, ako ay hindi mapapahiya,
Noon ay dinadala sa kanya maging ang mga sanggol, upang kanyang hawakan sila. Subalit nang makita ito ng mga alagad, sila'y sinaway nila.
at ako'y laging lalakad sa gitna ninyo. Ako'y magiging inyong Diyos, at kayo'y magiging aking bayan.
Siya'y nasa ilang ng apatnapung araw, at tinukso siya ni Satanas. Kasama siya ng mababangis na hayop at pinaglingkuran siya ng mga anghel.
Tumigil ka sa kanya nang ilang araw hanggang sa mapawi ang galit ng iyong kapatid,
Mga kapatid, ngayon ay nananawagan ako sa inyo na inyong pagtiisan ang aking salita ng pangaral, sapagkat sa pamamagitan ng iilang mga salita ay sumulat ako sa inyo.
Sinumang hindi nagpapasan ng kanyang sariling krus at sumusunod sa akin ay hindi maaaring maging alagad ko.
at may ibang lalaking sumiping sa kanya, at ito'y nakubli sa mga mata ng kanyang asawa at siya ay hindi nahalata kahit na dinungisan niya ang kanyang sarili at walang saksi laban sa kanya, at hindi siya nahuli sa akto,
Subalit sinabi ni Esau, “Sapat na ang nasa akin, kapatid ko. Ang nasa iyo ay sa iyo na.”
Ang taong-bayan ay nagsisigaw, “Tinig ng diyos at hindi ng tao!”
At sinabi niya sa kanya, “Guro, ang lahat ng mga bagay na ito'y aking tinupad mula pa sa aking kabataan.”
Ngunit sila'y sinagot niya, “Ang nagpagaling sa akin ang siyang nagsabi sa akin, ‘Buhatin mo ang iyong higaan, at lumakad ka.’”
Minamaliit pa ba ninyo na kayo'y ibinukod ng Diyos ng Israel sa sambayanan ng Israel, upang ilapit niya kayo sa kanya, upang gawin ninyo ang paglilingkod sa tabernakulo ng Panginoon , at upang kayo'y tumayo sa harap ng kapulungan na mangasiwa sa kanila?
Sa gayunding paraan ay nilibak siya ng mga punong pari, kasama ng mga eskriba at ng matatanda, na nagsasabi,
Pagkatapos ay lumabas ang kanyang kapatid na may pulang sinulid sa kamay; at tinawag na Zera ang kanyang pangalan.
maging sa atin na kanyang tinawag, hindi lamang mula sa mga Judio, kundi mula rin sa mga Hentil?
Dadalhin ng kambing ang lahat ng mga kasamaan nila sa lupaing walang naninirahan, at pakakawalan niya ang kambing sa ilang.
Siya'y nagutom at nagnais kumain; subalit samantalang inihahanda nila ito, nawalan siya ng malay
Patawarin mo, O Panginoon , ang iyong bayang Israel na iyong tinubos, at huwag mong ilagay ang dugong walang sala sa gitna ng iyong bayang Israel, at ang dugo'y ipatatawad sa kanila.’
Kaya't sinabi sa kanila ni Jesus, “Ibigay ninyo kay Cesar ang kay Cesar at sa Diyos ang sa Diyos.” At sila'y namangha sa kanya.
Ang mula sa Diyos ay nakikinig ng mga salita ng Diyos. Ang dahilan kung bakit hindi ninyo pinakikinggan ang mga ito ay sapagkat kayo'y hindi mula sa Diyos.”
sa mga diyos ng mga bayan na nasa palibot ninyo na malapit sa iyo, o malayo sa iyo, mula sa isang dulo ng lupa hanggang sa kabilang dulo ng lupa;
At nawa'y palaguin at pasaganain kayo ng Panginoon sa pag-ibig sa isa't isa at sa lahat ng tao, gaya naman namin sa inyo.
Anumang hayop na may hati ang paa, biyak, at ngumunguya—ang mga gayon ay maaari ninyong kainin.
upang hingin sa lahing ito ang dugo ng lahat ng mga propeta na dumanak mula pa nang itatag ang sanlibutan;
Sumama sa amin ang ilang alagad mula sa Cesarea at dinala kami sa bahay ni Mnason, na taga-Cyprus, isa sa mga naunang alagad, na sa kanya kami manunuluyan.
Sapagkat may ilang taong nakapasok nang lihim, ang mga iyon ay matagal nang itinalaga sa kahatulang ito, mga hindi maka-Diyos, na kanilang pinalitan ng kahalayan ang biyaya ng ating Diyos, at itinatatuwa ang kaisa-isa nating Pinuno at Panginoon na si Jesu-Cristo.
Nang halos matapos na ang pitong araw, ang mga Judiong taga-Asia, nang makita siya sa templo, ay inudyukan ang maraming tao at siya'y kanilang dinakip,
Nagtayo si Jacob ng isang haliging batong bantayog kung saan ay nakipag-usap ang Diyos sa kanya. Binuhusan niya ito ng inuming handog at ng langis.
Ngunit nagsalita kaagad sa kanila si Jesus, na nagsasabi, “Lakasan ninyo ang inyong loob; ako ito. Huwag kayong matakot.”
Sinabi sa kanya ng diyablo, “Kung ikaw ang Anak ng Diyos, ipag-utos mo na ang batong ito ay maging tinapay.”
Sumainyo nawa ang biyaya at kapayapaang mula sa Diyos na ating Ama at sa Panginoong Jesu-Cristo.
Aking ninakawan ang ibang mga iglesya sa pamamagitan ng pagtanggap ng sahod mula sa kanila upang makapaglingkod sa inyo.
Nabalitaan ng kanyang mga kapitbahay at mga kamag-anak na nagpakita ang Panginoon ng dakilang awa sa kanya at sila'y nakigalak sa kanya.
“Ngunit kung ang sinuman ay napopoot sa kanyang kapwa, at kanyang inabangan siya, kanyang sinalakay siya at kanyang saktan siya ng malubha, anupa't namatay, at siya'y tumakas sa isa sa mga lunsod na ito,
Umalis sila at kanilang natagpuan ang batang asno na nakatali sa pintuan sa labas ng lansangan. At kinalagan nila ito.
Sapagkat batid niya na dahil sa inggit ay ipinadakip siya ng mga punong pari.
Mga kapatid, huwag kayong magbulung-bulungan laban sa isa't isa, upang huwag kayong mahatulan. Tingnan ninyo, ang hukom ay nakatayo sa harapan ng mga pintuan.
Ang bawat mabuting kaloob at ang bawat sakdal na kaloob ay pawang buhat sa itaas, na nanggagaling sa Ama ng mga ilaw, na sa kanya ay walang pag-iiba, o anino man ng pagbabago.
At sinabi ng anghel ng Panginoon kay Balaam, “Sumama ka sa mga lalaki ngunit ang salita lamang na aking sasabihin sa iyo ang siyang sasabihin mo.” Kaya't sumama si Balaam sa mga pinuno ni Balak.
At kung si Cristo ay nasa sa inyo, ang katawan ay patay dahil sa kasalanan; ngunit ang espiritu ay buháy dahil sa katuwiran.
Nang magkagayo'y nagpatuloy si Jacob sa kanyang paglalakbay, at nagtungo sa lupain ng mga tao sa silangan.
Ang mga ito'y mga bukal na walang tubig, mga ulap na tinatangay ng unos. Sa kanila'y inilaan ang pusikit na kadiliman.
Sa kanyang paglalakad, nakita niya ang isang lalaking bulag mula pa sa kanyang pagkapanganak.
Lahat ng mga kasangkapan ng tabernakulo, sa bawat paglilingkod doon, at lahat ng mga tulos niyon, at lahat ng mga tulos ng bulwagan ay tanso.
Sumasampalataya ka na ang Diyos ay iisa; mabuti ang iyong ginagawa. Ang mga demonyo man ay sumasampalataya at nanginginig pa.
“Huwag ninyong ibigay sa mga aso ang mga banal na bagay; at huwag kayong magtapon ng inyong mga perlas sa harap ng mga baboy; baka yurakan nila ang mga ito ng kanilang mga paa, at pagbalingan kayo at lapain.
At doo'y makikipagtagpo ako sa mga anak ni Israel, at ito ay pakakabanalin ng aking kaluwalhatian.
“Bukod dito'y sasabihin mo sa mga Levita, ‘Pagkuha ninyo sa mga anak ni Israel ng ikasampung bahagi na aking ibinigay sa inyo mula sa kanila bilang inyong mana, ay inyong ihahandog bilang handog na ibinigay sa Panginoon , ang ikasampung bahagi ng ikasampung bahagi.
at kanilang pinapait ang kanilang buhay sa pamamagitan ng mahirap na paglilingkod, sa luwad at sa tisa, at sa lahat ng uri ng gawain sa bukid; at sa lahat ng kanilang gawain ay malupit silang pinapaglingkod.
Nang maipanganak na ni Raquel si Jose, sinabi ni Jacob kay Laban, “Hayaan mo na akong umalis upang ako'y makapunta sa aking sariling lugar at sa aking lupain.
At iwinagayway ni Aaron ang mga dibdib at ang kanang hita na handog na iwinawagayway sa harapan ng Panginoon ; gaya ng iniutos ni Moises.
At nakalimutan na ninyo ang pangaral na sinasabi niya sa inyo bilang mga anak, “Anak ko, huwag mong ipagwalang-bahala ang disiplina ng Panginoon; huwag kang manlupaypay kung ikaw ay sinasaway niya;
Sinabi nga niya, “Isang maharlikang tao ang pumunta sa isang malayong lupain, upang tumanggap ng isang kaharian at pagkatapos ay bumalik.
Sapagkat sinasabi ko sa inyo, na mula ngayon ay hindi na ako iinom ng katas ng ubas, hanggang sa dumating ang kaharian ng Diyos.”
Naglakbay pa si Israel at itinayo ang kanyang tolda sa dako pa roon ng tore ng Eder.
Nakita ni Jose ang kanyang mga kapatid at nakilala sila, subalit siya'y nagkunwaring iba sa kanila, at nagsalita ng marahas na mga bagay sa kanila. Sinabi niya sa kanila, “Saan kayo nanggaling?” Sinabi nila, “Mula sa lupain ng Canaan, upang bumili ng pagkain.”
ng iyong hayupan at ng mababangis na hayop na nasa iyong lupain. Lahat ng bunga niyon ay magiging inyong pagkain.
Habang patungo sa Jerusalem, si Jesus ay dumaan sa pagitan ng Samaria at Galilea.
“Kapag kordero ang kanyang dinala bilang handog pangkasalanan, siya ay magdadala ng babaing walang kapintasan.
“Tatlong ulit sa isang taon na ang iyong mga kalalakihan ay haharap sa Panginoon mong Diyos sa lugar na kanyang pipiliin: sa Pista ng Tinapay na walang Pampaalsa, sa Pista ng mga Sanlinggo, at sa Pista ng mga Tolda. Huwag silang haharap sa Panginoon na walang dala.
“Subalit kung ipahahayag nila ang kanilang kasamaan at ang kasamaan ng kanilang mga ninuno, sapagkat sila'y nagtaksil laban sa akin, at sapagkat sila'y lumakad ng laban sa akin,
Sapagkat papanaw ang Anak ng Tao, ayon sa nasusulat tungkol sa kanya, ngunit kahabag-habag ang taong iyon na sa pamamagitan niya ay ipinagkakanulo ang Anak ng Tao! Mabuti pa sa taong iyon ang hindi na siya ipinanganak.”
at ang hindi nagpapasan ng kanyang krus at sumusunod sa akin ay hindi karapat-dapat sa akin.
Nagbigay siya sa kanila ng isa pang talinghaga, na sinasabi, “Ang kaharian ng langit ay tulad sa isang butil ng binhi ng mustasa na kinuha ng isang tao, at inihasik sa kanyang bukid.
Kinaumagahan, pinapagmadali ng mga anghel si Lot, na sinasabi, “Bumangon ka, isama mo ang iyong asawa at ang iyong dalawang anak na babae na narito, baka pati ikaw ay madamay sa parusa sa bayan.”
At nagsalita ang Diyos kay Noe at sa mga anak na kasama niya, na sinasabi,
Ang sinumang gumagawa ng kasalanan ay lumalabag din naman sa kautusan; at ang kasalanan ay ang paglabag sa kautusan.
At kayo, mga kapatid, tulad ni Isaac, ay mga anak ng pangako.
Sinabi ni Jesus sa kanila, “Itinatanong ko sa inyo, ipinahihintulot ba sa kautusan na gumawa ng mabuti, o gumawa ng masama kung Sabbath? Magligtas ng buhay o pumuksa nito?”
Ipinamahala ng bantay sa bilangguan sa pangangalaga ni Jose ang lahat na mga bilanggo na nasa bilangguan; at anumang ginagawa nila roon ay siya ang gumagawa.
Sila'y binibigyan ko ng buhay na walang hanggan, at kailanma'y hindi sila mapapahamak, at hindi sila aagawin ng sinuman sa aking kamay.
Ang kanilang kahihinatnan ay kapahamakan, ang kanilang tiyan ang kanilang diyos, at ang kanilang kahihiyan ang kanilang kapurihan, na nakatuon ang isip sa mga bagay na makalupa.
Silang lahat ay nakinig sa kanya buhat sa pinakaaba hanggang sa pinakadakila, na sinasabi, “Ang taong ito ang kapangyarihan ng Diyos na tinatawag na Dakila.”
Huwag mong sabihin sa iyong puso, ‘Ang aking kapangyarihan at ang lakas ng aking kamay ang siyang nagbigay sa akin ng kayamanang ito.’
at ang mga pinahirapan ng masasamang espiritu ay pinagaling.
Ipinatong niya ang kanyang mga kamay sa kanila, at umalis doon.
Ang anghel ng Panginoon ay nagpakita sa kanya sa isang ningas ng apoy na mula sa gitna ng isang mababang punungkahoy. Siya'y nagmasid at ang punungkahoy ay nagliliyab ngunit ito'y hindi nasusunog.
Kung tayo nga'y naglalagay ng mga preno sa bibig ng mga kabayo upang sumunod sila sa atin, ibinabaling natin ang kanilang buong katawan.
ay iyong lilipulin ang mga naninirahan sa lunsod na iyon sa pamamagitan ng talim ng tabak at iyong lubos na pupuksain ang lahat ng naroon at ang mga hayop doon sa pamamagitan ng talim ng tabak.
Dumating ang araw ng Tinapay na Walang Pampaalsa, na noon ay kailangang ihandog ang kordero ng Paskuwa.
Nang marinig ito ni Moises, siya ay sumang-ayon.
Sinabi ni Aaron, “Huwag mag-alab ang galit ng aking Panginoon; kilala mo ang taong-bayan, na sila'y mahilig sa kasamaan.
Huwag mong ililitaw ang kahubaran ng isang babae at ng kanyang anak na babae; huwag mong papakisamahan ang anak na babae ng kanyang anak na lalaki o ang anak na babae ng kanyang anak na babae, upang lumitaw ang kanyang kahubaran; sila'y malapit na kamag-anak; ito ay masama.
“Gayundin, sa ikalabinlimang araw ng ikapitong buwan, kapag inyong tinipon ang bunga ng lupain, ipagdiriwang ninyo ang mga kapistahan ng Panginoon sa loob ng pitong araw; ang una at ikawalong araw ay Sabbath.
Kung hindi ko ginagawa ang mga gawa ng aking Ama, ay huwag kayong sumampalataya sa akin.
Ang lalaki at ang kanyang asawa ay kapwa hubad, ngunit sila'y hindi nahihiya.
Sinabi ni Balaam kay Balak, “Ngayon, ako'y naparito sa iyo. Mayroon ba ako ngayong anumang kapangyarihan na makapagsalita ng anumang bagay? Ang salitang inilagay ng Diyos sa aking bibig ang aking sasabihin.”
pagpalain ninyo ang mga sumusumpa sa inyo at ipanalangin ninyo ang mga umaapi sa inyo.
Pagkatapos ng mga bagay na ito, dumating ang salita ng Panginoon kay Abram sa isang pangitain, “Huwag kang matakot, Abram; ako ang iyong kalasag, ang iyong gantimpala ay magiging napakadakila.”
Sa ikapitong araw ay magkakaroon kayo ng isang banal na pagtitipon. Huwag kayong gagawa ng anumang mabigat na gawain.
“Panginoon, ngayon ay hayaan mong ang iyong alipin ay pumanaw na may kapayapaan, ayon sa iyong salita,
“Kung sa lupain na ibinibigay sa iyo ng Panginoon mong Diyos upang angkinin ay may matagpuang pinatay na nakabulagta sa parang at hindi malaman kung sinong pumatay sa kanya,
Ngunit sila'y tumahimik, sapagkat sa daan ay pinagtatalunan nila kung sino ang pinakadakila.
na pinawi ang sulat-kamay na laban sa atin na nasa mga tuntuning salungat sa atin, at ito'y kanyang inalis at ipinako sa krus.
Ngunit kung ang pangangati ay kumalat na sa balat pagkatapos ng kanyang paglilinis,
Malapit sa lugar na iyon ay may mga lupaing pag-aari ng pinuno ng pulong iyon, na ang pangalan ay Publio, na tumanggap sa amin at kinupkop kami na may kagandahang-loob sa loob ng tatlong araw.
Sapagkat mamagalingin ko pang ako ay sumpain at mawalay kay Cristo alang-alang sa aking mga kapatid, na aking mga kamag-anak ayon sa laman.
Sinunggaban nilang lahat si Sostenes, ang pinuno sa sinagoga, at siya'y binugbog sa harapan ng hukuman. Ngunit hindi pinansin ni Galio ang mga bagay na ito.
Sumagot si Jesus, “Kung ako ma'y nagpapatotoo tungkol sa aking sarili, ang aking patotoo ay totoo; sapagkat nalalaman ko kung saan ako nanggaling, at kung saan ako pupunta. Subalit hindi ninyo nalalaman kung saan ako nanggaling, o kung saan ako pupunta.
Nagkaroon ng isang pagtatalu-talo sa gitna nila, kung sino kaya sa kanila ang ituturing na pinakadakila.
Sapagkat hindi kami natagpuang gumamit kailanman ng mga salitang paimbabaw, gaya ng nalalaman ninyo, ni ng balabal ng kasakiman, saksi namin ang Diyos;
At lahat ng mga tao ay maagang pumaparoon sa kanya sa templo upang pakinggan siya.
Hadad, Tema, Jetur, Nafis, at si Kedema.
Sa isang dayuhan ay makapagpapahiram ka na may patubo, ngunit sa iyong kapatid ay huwag kang magpapahiram na may patubo upang pagpalain ka ng Panginoon mong Diyos sa lahat ng gagawin mo sa lupain na malapit mo nang pasukin upang angkinin.
Ang pangalan ng babaing Midianita na napatay ay Cozbi, na anak ni Zur; siya'y pinuno sa bayan ng isang sambahayan ng mga sambayanan sa Midian.
Ang iyong gagawing mga pasanan ay kahoy na akasya, at babalutin mo ito ng ginto.
Kahabag-habag kayo, mga eskriba't mga Fariseo, mga mapagkunwari! Sapagkat sinasakmal ninyo ang mga bahay ng mga babaing balo, at inyong dinadahilan ang mahahabang panalangin: kaya't tatanggap kayo ng lalong mabigat na parusa.]
Walang nagtatagpi ng matibay na tela sa damit na luma. Kapag gayon, babatakin ng itinagpi, ang bago mula sa luma at lalong lalaki ang punit.
At kahit ang aming ebanghelyo ay natatalukbungan pa, ito ay may talukbong lamang sa mga napapahamak.
Pumili kayo ng mga lalaking matatalino, may pang-unawa at may karanasan mula sa inyong mga lipi, at sila'y aking itatalaga bilang mga pinuno ninyo.’
“Sa taóng ito ng pagdiriwang, ang bawat isa sa inyo ay babalik sa kanyang ari-arian.
Pagkatapos, lalabhan ng pari ang kanyang mga damit at kanyang paliliguan ang kanyang katawan sa tubig, at pagkatapos ay papasok siya sa kampo at ang pari ay magiging marumi hanggang sa paglubog ng araw.
Kaya't sinabi sa kanya ng ibang mga alagad, “Nakita namin ang Panginoon.” Ngunit sinabi niya sa kanila, “Malibang makita ko sa kanyang mga kamay ang bakas ng mga pako, at mailagay ko ang aking daliri sa binutas ng mga pako, at mailagay ko ang aking kamay sa kanyang tagiliran ay hindi ako maniniwala.”
At ang mga naging araw ni Terah ay dalawandaan at limang taon, at namatay si Terah sa Haran.
“‘Huwag mong gagamitin ang pangalan ng Panginoon mong Diyos sa walang kabuluhan; sapagkat hindi ituturing ng Panginoon na walang sala ang gumamit ng kanyang pangalan sa walang kabuluhan.
Subalit bago mangyari ang lahat ng mga bagay na ito ay pagbubuhatan nila kayo ng kanilang mga kamay at uusigin. Dadalhin kayo sa mga sinagoga, sa mga bilangguan at ihaharap kayo sa mga hari at mga gobernador dahil sa aking pangalan.
Ngunit ang Jerusalem na nasa itaas ay malaya, na siyang ating ina.
Napuno sila ng lahat ng uri ng kasamaan, kalikuan, kasakiman, kahalayan; at punô ng inggit, pagpaslang, pag-aaway, pandaraya, katusuhan, mahihilig sa tsismis,
upang ang tao ng Diyos ay maging ganap, nasasangkapang lubos sa lahat ng mga gawang mabuti.
Aayusin ng mga paring anak ni Aaron ang mga bahagi, ang ulo, at ang taba sa kahoy na nakapatong sa apoy na nasa ibabaw ng dambana;
Pagkatapos ay sinabi ni Jesus sa kanila, “Huwag kayong matakot. Humayo kayo at sabihin ninyo sa aking mga kapatid na pumunta sila sa Galilea, at doon ay makikita nila ako.”
na iyong inihanda sa harapan ng lahat ng mga tao,
Pagkatapos na siya'y libakin, hinubad nila sa kanya ang balabal, isinuot sa kanya ang mga damit niya, at kanilang inilabas siya upang ipako sa krus.
Noong unang panahon, ang Diyos ay nagsalita sa ating mga ninuno sa iba't ibang panahon at sa iba't ibang paraan sa pamamagitan ng mga propeta,
At biglang may dalawang lalaking nakikipag-usap sa kanya, sina Moises at Elias,
At upang malaman din ninyo ang mga bagay tungkol sa akin at ang aking kalagayan, si Tiquico ang siyang magsasalaysay sa inyo ng lahat ng mga bagay. Siya na aking minamahal na kapatid at tapat na lingkod sa Panginoon.
Nang sila'y nagkakatipon, siya'y kanilang tinanong, “Panginoon, ito ba ang panahon na panunumbalikin mo ang kaharian sa Israel?”
Sinabi ni Jesus sa kanila, “Kung kayo'y mga bulag, hindi kayo magkakaroon ng kasalanan. Subalit ngayong sinasabi ninyo, ‘Kami'y nakakakita,’ nananatili ang inyong kasalanan.”
siya ay ketongin, siya'y marumi. Ipahahayag ng pari na siya ay marumi; ang kanyang sakit ay nasa kanyang ulo.
At si Jesus ay tumigil at ipinag-utos na dalhin ang tao sa kanya. Nang lumapit ito ay kanyang tinanong,
Kung may magsabi sa inyo, ‘Narito ang Cristo!’ o, ‘Tingnan ninyo naroon siya!’ huwag ninyong paniwalaan.
Ang nagsasabing siya'y nasa liwanag at napopoot sa kanyang kapatid ay nasa kadiliman pa hanggang ngayon.
Samantalang sila'y naglalayag siya'y nakatulog. Dumating ang unos sa lawa, at sila'y napupuno ng tubig at nanganganib.
Sapagkat walang taong nagnanais makilala ang gumagawa ng anumang bagay sa lihim. Kung ginagawa mo ang mga bagay na ito ay ipakilala mo ang iyong sarili sa sanlibutan.”
Siya ang ulo ng katawan, ang iglesya; siya ang pasimula, ang panganay mula sa mga patay, upang siya ay maging pangunahin sa lahat ng mga bagay.
Nalalaman ninyo na ang aking buong lakas ay ipinaglingkod ko sa inyong ama.
At kanyang iginawa iyon ng apat na haliging akasya, at binalot ang mga ito ng ginto, ang kanilang mga kawit ay ginto rin at naghulma siya para sa mga ito ng apat na patungang pilak.
Pumaroon ka ngayon sa kawan, at dalhin mo sa akin ang dalawang magandang batang kambing at gagawin kong masarap na pagkain para sa iyong ama, ayon sa kanyang ibig.
At naglakbay sila sa lupain ng Frigia at Galacia, dahil pinagbawalan sila ng Espiritu Santo na ipangaral ang salita sa Asia.
At pinatay niya ang handog na susunugin. Ibinigay sa kanya ng mga anak ni Aaron ang dugo, at kanyang iwinisik sa palibot ng dambana.
Ngunit ako'y natatakot na kung paanong si Eva ay dinaya ng ahas sa pamamagitan ng kanyang katusuhan, ang inyong mga pag-iisip ay mailigaw mula sa katapatan at kadalisayan kay Cristo.
Ang mga tao ay manlulupaypay dahil sa takot, at mangangamba sa mga bagay na darating sa daigdig, sapagkat ang mga kapangyarihan sa mga langit ay mayayanig.
Nang makita ng mga tao ang tandang ginawa niya ay kanilang sinabi, “Totoong ito nga ang propeta na darating sa sanlibutan.”
Narinig ninyo ang kanyang paglapastangan! Ano ang inyong pasiya?” At hinatulan nilang lahat na siya'y dapat mamatay.
Pagpapalain ko ang magbibigay ng pagpapala sa iyo, at susumpain ko ang mga susumpa sa iyo; at sa pamamagitan mo ang lahat ng angkan sa lupa ay pagpapalain.”
ngunit sumagot ang kanyang ina at nagsabi, “Hindi. Ang itatawag sa kanya ay Juan.”
At si Moises ay tumayo at pumaroon kina Datan at Abiram; at ang matatanda sa Israel ay sumunod sa kanya.
Muli na naman siyang tinanong ng mga Fariseo kung paano siya nagkaroon ng paningin. At sinabi niya sa kanila, “Nilagyan niya ng putik ang aking mga mata, at hinugasan ko, at ako'y nakakita.”
Magsipag-asawa kayo sa amin; ibigay ninyo sa amin ang inyong mga anak na babae, at ibibigay namin sa inyo ang aming mga anak na babae.
“Huwag kang magkakaroon sa iyong supot ng dalawang uri ng pabigat, isang malaki at isang maliit.
“Si Claudio Lisias sa kagalang-galang na gobernador Felix, ay bumabati.
Ang magiging pinuno sa sambahayan ng mga ninuno ng mga Gershonita ay si Eliasaf na anak ni Lael.
At sinabi ni Lea, “Maligaya na ako! Tatawagin akong maligaya ng mga babae.” At tinawag niya ang kanyang pangalan na Aser.
Dinala ni Esau ang kanyang mga asawa, ang kanyang mga anak na lalaki at babae, ang lahat ng tao sa kanyang bahay, ang kanyang hayop, lahat ng kanyang kawan, at ang lahat na kanyang tinipon sa lupain ng Canaan, at pumunta sa isang lupaing malayo sa kanyang kapatid na si Jacob.
Sinabi niya ang mga salitang ito sa kabang-yaman habang nagtuturo siya sa templo. Subalit walang taong humuli sa kanya, sapagkat hindi pa dumating ang kanyang oras.
Kaya't dinala ng mga lalaki ang handog at ang dobleng dami ng salapi at si Benjamin. Sila'y pumunta sa Ehipto, at humarap kay Jose.
Sapagkat sa araw na ito, ang pari ay gagawa ng pagtubos sa inyo upang linisin kayo sa lahat ng inyong mga kasalanan; kayo ay magiging malinis sa harapan ng Panginoon .
Ilan sa mga pilosopong Epicureo at Estoico ay nakipagtalo rin sa kanya. At sinabi ng ilan, “Anong nais sabihin ng madaldal na ito?” Sinabi ng iba, “Parang siya'y isang tagapagbalita ng mga ibang diyos”—sapagkat ipinangangaral niya si Jesus at ang pagkabuhay.
gayunma'y alang-alang sa pag-ibig ay nanaisin ko pang makiusap sa iyo—akong si Pablo ay matanda na, at ngayon ay isa ring bilanggo ni Cristo Jesus.
Pagkaiwan sa maraming tao, siya'y kanilang isinama sa bangka, ayon sa kanyang kalagayan. At may iba pang mga bangka na kasama niya.
Nang matanggap ni Jesus ang suka ay sinabi niya, “Natupad na.” At itinungo ang kanyang ulo, at siya ay namatay.
Ang iba nama'y nahulog sa batuhan na doo'y kakaunti lamang ang lupa; at kaagad silang sumibol yamang hindi malalim ang lupa.
Tungkol sa ebanghelyong ito ako'y naging lingkod ayon sa kaloob ng biyaya ng Diyos na sa akin ay ibinigay ayon sa paggawa ng kanyang kapangyarihan.
Sinabi ng isa sa kanila, ng isang propeta mismo nila, ‘Ang mga taga-Creta ay laging mga sinungaling, masasamang hayop, mga batugang matatakaw.’
Ito ay kanyang kakatayin sa hilagang bahagi ng dambana sa harapan ng Panginoon . Iwiwisik ng mga anak ni Aaron, na mga pari, ang dugo niyon sa palibot ng dambana.
At sinaway siya ng marami na siya'y tumahimik, ngunit siya'y lalong nagsisigaw, “Anak ni David, mahabag ka sa akin!”
At may isang lalaki mula sa maraming tao ang sumigaw, “Guro, nakikiusap ako sa iyo na tingnan mo ang aking anak na lalaki, sapagkat siya'y aking kaisa-isang anak.
at hindi ito dinala sa pintuan ng toldang tipanan, upang ihandog bilang alay sa Panginoon , sa harapan ng tabernakulo ng Panginoon , ang dugo ay ipaparatang sa taong iyon. Siya'y nagbubo ng dugo, at ang taong iyon ay ititiwalag sa kanyang bayan.
Kung ihahasa ko ang aking makintab na tabak, at ang aking kamay ay humawak sa hatol, ako'y maghihiganti sa aking mga kaaway, at aking gagantihan ang mga napopoot sa akin.
“Karapat-dapat ka, O Panginoon at Diyos namin, na tumanggap ng kaluwalhatian at karangalan at kapangyarihan, sapagkat nilikha mo ang lahat ng mga bagay at dahil sa iyong kalooban ay nabuhay sila at nalikha.
Sinuman ay hindi nagtatagpi ng bagong tela sa lumang damit; sapagkat binabatak ng tagpi ang damit at lumalala ang punit.
At huwag tayong manghinawa sa paggawa ng mabuti, sapagkat sa takdang panahon ay mag-aani tayo, kung hindi tayo manlulupaypay.
Kanilang aalisin ang mga abo sa dambana at lalatagan ito ng isang telang kulay-ube.
Hindi isang bagong hikayat, baka siya magpalalo at mahulog sa kahatulan ng diyablo.
Ang lahat ng mga bagay na ito'y sinabi ni Jesus sa maraming tao sa pamamagitan ng mga talinghaga, at wala siyang sinabi sa kanila na hindi sa pamamagitan ng talinghaga.
Tumakas ang mga tagapag-alaga ng mga iyon; at pagpasok nila sa bayan ay sinabi nila ang buong pangyayari at ang nangyari sa mga inalihan ng mga demonyo.
“Sabihin mo sa mga anak ni Israel, ‘Kung ang asawa ng sinumang lalaki ay lumihis ng landas at hindi naging tapat sa kanya,
At nalalaman natin na sa lahat ng mga bagay ang Diyos ay gumagawa sa ikabubuti ng mga umiibig sa kanya, sa kanila na mga tinawag alinsunod sa kanyang layunin.
Sapagkat naghahatid ka ng mga kakaibang bagay sa aming mga tainga; kaya't ibig naming malaman kung ano ang kahulugan ng mga bagay na ito.”
Sapagkat hindi kami sumusulat sa inyo ng ibang mga bagay kundi kung ano ang inyong mababasa at mauunawaan; umaasa ako na lubos ninyong mauunawaan hanggang sa wakas.
at kanilang tinanggap mula kay Moises ang lahat ng handog na dinala ng mga anak ni Israel na magagamit sa gawang paglilingkod sa santuwaryo upang gawin. Kanilang patuloy silang dinalhan ng kusang handog tuwing umaga,
At si Satanas ay dudurugin ng Diyos ng kapayapaan sa madaling panahon sa ilalim ng inyong mga paa. Ang biyaya nawa ng ating Panginoong Jesu-Cristo ay sumainyo.
Binabati kayo ng lahat ng mga banal, lalung-lalo na ng mga kasambahay ni Cesar.
Kaya't muli niyang tinanong sila, “Sino ang inyong hinahanap?” At sinabi nila, “Si Jesus na taga-Nazaret.”
Ngunit sinabi niya sa akin, “Huwag mong gawin iyan! Ako'y kapwa mo alipin at ng iyong mga kapatid na mga propeta, at ng mga tumutupad ng mga salita ng aklat na ito. Ang Diyos ang sambahin mo.”
Dahil sa habag ng panginoon sa aliping iyon, siya ay pinalaya at pinatawad sa kanyang utang.
Ngunit ang salita ng Diyos ay patuloy na lumago at lumaganap.
Nang magdadapit-hapon na ng araw na iyon, na unang araw ng linggo, habang nakasara ang mga pinto sa kinaroroonan ng mga alagad dahil sa takot sa mga Judio, dumating si Jesus at tumayo sa gitna, at sa kanila'y sinabi, “Kapayapaan ang sumainyo.”
Siya'y maghahari sa sambahayan ni Jacob magpakailanman at hindi magwawakas ang kanyang kaharian.”
Sinasabi ko sa inyo, sa gabing iyon ay may dalawa sa isang higaan; ang isa'y kukunin, at ang isa'y iiwan.
Sumagot siya sa kanila, “Ang may dalawang tunika ay magbahagi sa wala, at ang may pagkain ay gayundin ang gawin.”
ngunit may isang ulap na pumaitaas buhat sa lupa at dinilig ang buong kapatagan ng lupa.
Katotohanang sinasabi ko sa inyo, ang sinumang sumasampalataya ay may buhay na walang hanggan.
At kinuha ni Moises ang tungkod sa harap ng Panginoon , na gaya ng iniutos sa kanya.
tunay na pagpapalain kita, at pararamihin ko ang iyong binhi, na gaya ng mga bituin sa langit at mga buhangin sa baybayin ng dagat; at makakamit ng iyong binhi ang pintuang-bayan ng kanyang mga kaaway.
“Hanggang kailan magrereklamo laban sa akin ang masamang kapulungang ito? Aking narinig ang mga reklamo ng mga anak ni Israel na kanilang sinasabi laban sa akin.
At ihaharap ni Aaron ang kambing na nabunot para sa Panginoon , at ihahandog ito bilang handog pangkasalanan.
“Kaya't nang mapuksa at mamatay sa gitna ng bayan ang lahat ng lalaking mandirigma,
Kaya't si Simon Pedro ay sumampa sa bangka, at hinila ang lambat sa lupa na punô ng malalaking isda, na isandaan at limampu't tatlo, at kahit gayon karami ay hindi nasira ang lambat.
Si Abram ay patuloy na naglakbay hanggang sa Negeb.
upang kayo'y maging mga anak ng inyong Ama na nasa langit, sapagkat pinasisikat niya ang kanyang araw sa masasama at sa mabubuti, at nagpapaulan sa mga matuwid at sa mga di-matuwid.
Dahil dito, iyon ay batay sa pananampalataya, upang maging ayon sa biyaya; upang ang pangako ay maging tiyak para sa lahat ng binhi, hindi lamang sa nasa kautusan, kundi pati naman sa nasa pananampalataya ni Abraham (na ama nating lahat,
Nang makita niya ang singsing at mga pulseras sa mga kamay ng kanyang kapatid, at pagkarinig sa mga salita ni Rebecca na kanyang kapatid, na sinasabi, “Gayon ang sinabi sa akin ng lalaki;” ay lumapit siya sa lalaki at nakitang ito'y nakatayo sa tabi ng mga kamelyo sa bukal.
kaya't ikaw ay masisiraan ng isip dahil sa tanawin na makikita ng iyong mga mata.
Ang bawat tao na hindi makinig sa propetang iyon ay lubos na pupuksain mula sa bayan.’
Puspusin nawa kayo ng Diyos ng pag-asa, ng buong kagalakan at kapayapaan sa pananampalataya, upang kayo'y sumagana sa pag-asa sa pamamagitan ng kapangyarihan ng Espiritu Santo.
Huwag ninyong gagawin ang gaya ng mga bagay na ating ginagawa dito sa araw na ito, na ginagawa ng bawat isa ang matuwid sa kanyang paningin;
Gayundin tayo, nang tayo'y mga bata pa, tayo'y naalipin sa mga panimulang aral ng sanlibutan.
“Kung may matagpuan sa gitna mo, sa loob ng alinman sa iyong mga bayan na ibinigay sa iyo ng Panginoon mong Diyos, na lalaki o babae na gumagawa ng kasamaan sa paningin ng Panginoon mong Diyos, na lumalabag sa kanyang tipan,
Ngunit hindi nila naunawaan ang kanyang sinabi at natakot silang magtanong sa kanya.
ni huwag mo ring papanigan ang dukha sa kanyang usapin.
At kung may magtanong sa inyo, ‘Bakit ninyo kinakalagan iyan? Ganito ang inyong sasabihin, ‘Kailangan siya ng Panginoon.’”
At nang masabi na niya ang mga salitang ito'y nagsialis ang mga Judio, at sila-sila'y nagtalong mabuti.]
Ang mga tao'y sumamba sa dragon sapagkat ibinigay niya ang kanyang kapangyarihan sa halimaw; at sinamba nila ang halimaw, na sinasabi, “Sino ang katulad ng halimaw at sinong makakalaban dito?”
Sasabihin mo sa kanya, ‘Sinugo ako sa iyo ng Panginoon , ang Diyos ng mga Hebreo, na sinasabi, “Payagan mong umalis ang aking bayan, upang sila'y makasamba sa akin sa ilang.” Ngunit hanggang ngayon hindi mo pa tinutupad.’
Bumalik siya sa ikatlong pagkakataon at sinabi sa kanila, “Natutulog pa rin ba kayo at nagpapahinga? Tama na! Dumating na ang oras; ang Anak ng Tao ay ipinagkakanulo sa mga kamay ng mga makasalanan.
At ang mga kumain ay may limang libong lalaki, bukod pa sa mga babae at sa mga bata.
At sa takot sa kanya, nanginig ang mga bantay, at naging tulad sa mga patay.
upang kay Cristo Jesus ang pagpapala ni Abraham ay dumating sa mga Hentil, upang ating tanggapin ang pangako ng Espiritu sa pamamagitan ng pananampalataya.
Lahat ng haligi sa palibot ng bulwagan ay pagkakabitin ng mga baras na pilak; ang mga kawit ng mga iyon ay pilak, at ang mga patungan ay tanso.
Si Josue na anak ni Nun, at si Caleb na anak ni Jefone, na mga kasama ng mga nagsiyasat nang lihim sa lupain, ay pinunit ang kanilang mga damit.
Sa kanyang pagpapakababa ay ipinagkait sa kanya ang katarungan. Sino ang makapaglalarawan sa kanyang lahi? Sapagkat inalis sa lupa ang kanyang buhay.”
gaya ng ginawa niya sa araw na ito, ay gayon ang iniutos ng Panginoon na gawin ninyo upang ipantubos sa inyo.
Sila'y lumiko at umahon sa daan ng Basan. Si Og na hari sa Basan ay lumabas laban sa kanila, siya at ang buong bayan niya, upang makipaglaban sa Edrei.
Sinumang magpadanak ng dugo ng tao, ang dugo ng taong iyon ay papadanakin ng ibang tao; sapagkat nilalang ang tao sa larawan ng Diyos.
Tunay na walang engkanto laban sa Jacob, ni panghuhula laban sa Israel. Ngayo'y sasabihin tungkol sa Jacob at sa Israel, ‘Anong ginawa ng Diyos!’
Sinabi ng Panginoon kay Abram, “Umalis ka sa iyong lupain, sa iyong mga kamag-anak, sa bahay ng iyong ama, at pumunta ka sa lupaing ituturo ko sa iyo.
Sa likod ng tabernakulo, sa gawing kanluran, ay gagawa ka ng anim na haligi.
Sapagkat bagaman pinalungkot ko kayo sa pamamagitan ng aking sulat, hindi ko ito ipinagdaramdam: (bagama't aking dinamdam, sapagkat aking nalaman na ang sulat na ito ay nakapagpalungkot sa inyo, bagama't sa maikling panahon lamang).
Nang marinig ni Abram na nabihag ang kanyang kamag-anak, pinangunahan niya ang kanyang tatlong daan at labingwalong mga sanay na tauhan na ipinanganak sa kanyang bahay, at kanilang hinabol sila hanggang sa Dan.
“Ito'y magiging alituntunin magpakailanman para sa inyo: sa ikapitong buwan ng ikasampung araw ng buwan ay magpakasakit kayo sa inyong mga sarili, at huwag gagawa ng anumang gawain, ang mamamayan, ni ang taga-ibang bayan na nakatira sa inyong kalagitnaan.
Kaya't naunawaan nila na ang sinabi ni Jesus ay hindi sa pampaalsa ng tinapay mag-ingat kundi sa mga aral ng mga Fariseo at Saduceo.
Ngunit si Josue na anak ni Nun, at si Caleb na anak ni Jefone ay naiwang buháy sa mga taong iyon na pumaroon upang lihim na siyasatin ang lupain.
Ngayo'y isinasamo ko sa inyo, mga kapatid, na tandaan ninyo ang mga lumilikha ng pagkakabaha-bahagi at ng mga katitisuran na laban sa mga aral na inyong natutunan; lumayo kayo sa kanila.
Sinabi niya sa kanila, “Kayo'y mga taga-ibaba, ako'y taga-itaas. Kayo'y mga taga-sanlibutang ito; ako'y hindi taga-sanlibutang ito.
Nalalaman ninyo na siya'y nahayag upang mag-alis ng mga kasalanan; at sa kanya'y walang kasalanan.
Ngunit kung ang bagay na ito ay totoo na ang mga tanda ng pagkabirhen ay hindi natagpuan sa dalaga,
Subalit sinabi ni Pedro, “Hindi maaari, Panginoon; sapagkat kailanma'y hindi ako kumain ng anumang bagay na marumi at karumaldumal.”
At siya'y dumampot ng tinapay, at nang siya'y makapagpasalamat, kanyang pinagputul-putol, at ibinigay sa kanila, na sinasabi, “Ito'y aking katawan na ibinibigay dahil sa inyo. Gawin ninyo ito sa pag-aalaala sa akin.”
Hindi mo pinansin ang Batong nanganak sa iyo, at kinalimutan mo ang Diyos na lumalang sa iyo.
Bawat mapasama sa pagbilang, mula sa dalawampung taong gulang pataas, ay magbibigay ng handog sa Panginoon .
ang lalaking sumiping sa kanya ay magbibigay sa ama ng dalaga ng limampung siklong pilak, at ang dalaga ay magiging kanyang asawa. Sapagkat kanyang nilapastangan siya, hindi niya maaaring hiwalayan ang dalaga hangga't siya ay nabubuhay.
Nang makita ng proconsul ang nangyari, siya'y naniwala sapagkat siya'y namangha sa turo ng Panginoon.
Subalit sinabi sa kanya ni Pedro, “Kahit tumalikod man ang lahat, ako'y hindi.”
Mga kapatid, ako ay nagsasalita ayon sa tao, kapag napagtibay na ang tipan ng isang tao, walang makapagdaragdag o makapagpapawalang-bisa nito.
Subalit ang mga anak ni Israel ay lumakad sa tuyong lupa sa gitna ng dagat; at ang tubig ay naging isang pader sa kanilang gawing kanan at sa kanilang kaliwa.
Pagkatapos makipagpulong sa matatanda, nagpanukala sila na magbigay ng sapat na salapi sa mga kawal,
Kapag ang isang dayuhan ay maninirahang kasama mo, at mangingilin ng paskuwa ng Panginoon , tutuliin lahat ang kanyang mga kalalakihan at saka lamang siya makakalapit at makakapangilin. Siya'y magiging tulad sa ipinanganak sa lupain ninyo. Subalit sinumang hindi tuli ay hindi makakakain niyon.
Kinabukasan, lumabas kami at dumating sa Cesarea; at pumasok kami sa bahay ni Felipe na ebanghelista, na isa sa pito, at nanatili kaming kasama niya.
“Kahabag-habag kayo, mga eskriba at mga Fariseo, mga mapagkunwari! Sapagkat tulad kayo sa mga pinaputing libingan na magandang tingnan sa labas, ngunit sa loob ay punô ng mga buto ng mga patay at ng lahat ng uri ng karumihan.
at si Anas, na pinakapunong pari, si Caifas, si Juan, si Alejandro, at ang buong angkan ng pinakapunong pari.
na sinasabi, “Ako'y nagkasala sa pagkakanulo ko sa dugong walang sala.” Ngunit sinabi nila, “Ano iyon sa amin? Ikaw ang bahala diyan.”
Huwag mong ipanumpa maging ang iyong ulo, sapagkat hindi mo magagawang puti o itim ang isang buhok.
Sumagot si Efron kay Abraham,
Subalit kapag dumating na ang Espiritu ng katotohanan, papatnubayan niya kayo sa buong katotohanan. Sapagkat hindi siya magsasalita nang mula sa kanyang sarili, kundi ang anumang bagay na kanyang marinig, iyon ang kanyang sasabihin at kanyang ipahahayag sa inyo ang mga bagay na darating.
At natisod sila sa kanya. Ngunit sinabi sa kanila ni Jesus, “Ang isang propeta ay di nawawalan ng karangalan, maliban sa kanyang sariling bayan at sambahayan.”
Kung sakaling magkukulang ng lima sa limampung banal, lilipulin mo ba ang buong bayan dahil sa limang kulang?” At sinabi niya, “Hindi ko lilipulin kung makatagpo ako roon ng apatnapu't lima.”
Dadalhin niya ito sa mga anak ni Aaron na mga pari at siya'y kukuha mula roon ng isang dakot na piling harina at langis, at lahat ng kamanyang nito. Ito ay susunugin ng pari sa ibabaw ng dambana, isang handog na pinakaalaala, isang handog na pinaraan sa apoy, na mabangong samyo sa Panginoon .
Ang laman ng handog pangkapayapaan bilang pasasalamat ay kakainin sa araw ng paghahandog nito; hindi siya magtitira nito hanggang sa umaga.
Sapagkat sa gayunding dahilan ay nagbabayad din kayo ng buwis, sapagkat ang namamahala ay mga lingkod ng Diyos na patuloy na nangangasiwa sa bagay na ito.
Ano sa palagay mo, alin sa tatlong ito, ang naging kapwa tao sa nahulog sa kamay ng mga tulisan?”
Tatlong ulit sa bawat taon na ang lahat ng iyong mga kalalakihan ay haharap sa Panginoong Diyos .
Pagkatapos ay pumunta si Jesus na kasama sila sa isang pook na tinatawag na Getsemani, at sinabi niya sa kanyang mga alagad, “Maupo kayo rito, samantalang ako'y pupunta sa dako roon at mananalangin.”
[Ngunit ang ganito'y hindi lumalabas kundi sa pamamagitan ng panalangin at ayuno.]”
Ngunit batid ni Jesus ang kanilang kasamaan, sinabi niya, “Bakit ninyo ako sinusubok, mga mapagkunwari?
Pagkatapos nito ay sinabi niya sa mga alagad, “Pumunta tayong muli sa Judea.”
At ang lahat ng mga kakilala niya at ang mga babaing sa kanya'y sumunod buhat sa Galilea ay nakatayo sa malayo at nakita ang mga bagay na ito.
Ang mga ito rin ang nilakaran ninyo noong una, nang kayo'y nabubuhay pa sa mga bagay na ito.
Anim na araw na gagawin ang gawain, subalit ang ikapitong araw ay banal na Sabbath na taimtim na pagpapahinga sa Panginoon ; sinumang gumawa ng anumang gawa sa araw na iyon ay papatayin.
Nang sila'y dumating, tinipon nila ang iglesya at iniulat ang lahat ng mga bagay na ginawa ng Diyos sa pamamagitan nila, at kung paanong binuksan niya para sa mga Hentil ang pinto ng pananampalataya.
Sila'y mga espiritu ng mga demonyo na gumagawa ng mga tanda; pumupunta sa mga hari ng buong daigdig, upang tipunin sila sa digmaan ng dakilang araw ng Diyos na Makapangyarihan sa lahat.
Sinabi nila sa kanya, “Sa Bethlehem ng Judea, sapagkat ganito ang isinulat ng propeta:
ay iyo ngang ilalabas sa iyong mga pintuang-bayan ang lalaki o babaing iyon na gumawa ng bagay na masama at iyong babatuhin ng mga bato ang lalaki at babae, hanggang sila'y mamatay.
“At ito ang kalagayan ng nakamatay ng tao na tatakas doon at mabubuhay: sinumang makapatay sa kanyang kapwa nang di sinasadya, na hindi niya naging kaaway nang panahong nakaraan;
Minamahal, huwag mong tularan ang masama, kundi ang mabuti. Ang gumagawa ng mabuti ay sa Diyos; ang gumagawa ng masama ay hindi nakakita sa Diyos.
mula sa lipi ni Jose, samakatuwid ay sa lipi ni Manases ay si Gaddi na anak ni Susi;
“Sinasabi ko sa iyo, tumayo ka, damputin mo ang iyong higaan, at umuwi ka.”
Nang makapasok na siya sa bahay, lumapit sa kanya ang mga lalaking bulag; at sinabi sa kanila ni Jesus, “Sumasampalataya ba kayo na magagawa ko ito?” Sinabi nila sa kanya, “Opo, Panginoon.”
Iniabot ni Pedro sa kanya ang kanyang kamay at siya'y itinindig. Pagkatapos tawagin ang mga banal at ang mga babaing balo, siya'y iniharap niyang buháy.
Walang taong itinalaga sa pagkawasak ang matutubos; siya ay tiyak na papatayin.
Lumalaki ang mga alon sa dagat dahil sa malakas na hanging humihihip.
Kanilang sinulsulan ang mga taong-bayan, maging ang matatanda, at ang mga eskriba. Siya'y kanilang hinarap, hinuli at dinala sa Sanhedrin.
Nang ako'y kanilang nasiyasat na, ibig sana akong palayain ng mga taga-Roma, sapagkat walang anumang kadahilanang marapat sa kamatayan na natagpuan sa akin.
At nagsalita ang Panginoon kay Moises, na sinasabi,
Kanya ring iginawa ng tabing ang pintuan ng tolda ng telang asul, kulay-ube at pula, hinabing pinong lino, na ginawa ng mambuburda;
Subalit ang masasamang tao at mga mandaraya ay lalong sasama nang sasama, sila'y mandaraya at madadaya.
Kaya kayo'y tumulad sa Diyos, gaya ng mga anak na minamahal,
Sa loob ng tatlong araw ay itataas ng Faraon ang iyong ulo, at ibabalik ka sa iyong katungkulan, at ibibigay mo ang kopa ni Faraon sa kanyang kamay, gaya ng karaniwang dati mong ginagawa nang ikaw ay kanyang katiwala.
Gayundin ang Sodoma at Gomorra, at ang mga lunsod sa palibot ng mga ito, na gumawa naman ng pakikiapid at nalulong sa kakaibang laman, ay inilagay bilang halimbawa, na nagdaranas ng kaparusahan sa apoy na walang hanggan.
Kaya't tutuparin nila ang aking bilin, at hindi nila iyon ipagkakasala, upang sila ay huwag mamatay kapag kanilang nilapastangan ito: Ako ang Panginoon na nagpapabanal sa kanila.
“Pagkatapos niyang matubos ang dakong banal, ang toldang tipanan, at ang dambana, ay ihahandog niya ang kambing na buháy.
Ang mga anak ni Gomer: sina Askenaz, Rifat, at Togarma.
Nang pumasok si Jesus sa bahay ni Pedro, nakita niya ang biyenang babae nito na nakaratay dahil sa lagnat.
Gayundin naman, kayong mga kabataan, pasakop kayo sa matatanda. At kayong lahat ay magsuot ng kapakumbabaan sa inyong pakikitungo sa isa't isa, sapagkat “Ang Diyos ay sumasalungat sa mga palalo, ngunit nagbibigay ng biyaya sa mga mapagpakumbaba.”
At samantalang sila'y nagsisigawan, na inihahagis ang kanilang mga damit, at nagsasabog ng alikabok sa hangin,
At kung tutubusin ng nagtalaga ang kanyang bahay, siya ay magdaragdag ng ikalimang bahagi ng salapi na inihalaga roon, at ito ay magiging kanya.
Nang sumapit ang Sabbath, nagpasimula siyang magturo sa sinagoga at marami sa mga nakinig sa kanya ay namangha na sinasabi, “Saan kinuha ng taong ito ang lahat ng ito? Anong karunungan ito na ibinigay sa kanya? Anong mga makapangyarihang gawa ang ginagawa ng kanyang mga kamay!
At ang nakaupo doon ay may anyong katulad ng batong jaspe at sardio, at naliligid ang trono ng isang bahaghari na tulad ng esmeralda.
At nagsalita ang Panginoon kay Moises, na sinasabi,
Sumampalataya siya sa Panginoon ; at ito'y ibinilang na katuwiran sa kanya.
“Ama, kung ibig mo, ilayo mo sa akin ang kopang ito; gayunma'y huwag ang kalooban ko ang mangyari kundi ang sa iyo.” [
na nagsabi, “Kayong mga lalaking taga-Galilea, bakit kayo'y nakatayong tumitingin sa langit? Itong si Jesus, na dinala sa langit mula sa inyo ay darating na gaya rin ng inyong nakitang pagpunta niya sa langit.”
at kayong mga pinahihirapan ay bigyan ng kapahingahang kasama namin, sa pagkapahayag ng Panginoong Jesus mula sa langit na kasama ang kanyang mga makapangyarihang anghel,
Maglalagay ako sa iyo at sa babae ng pagkapoot sa isa't isa, at sa iyong binhi at sa kanyang binhi. Ito ang dudurog ng iyong ulo, at ikaw ang dudurog ng kanyang sakong.”
At aking ibinigay ang Gilead kay Makir.
At narinig ko ang bilang ng mga tinatakan, 144,000, tinatakan mula sa bawat lipi ng mga anak ni Israel:
Ngayon nga ay umalis ka patungo sa iyong lugar. Aking inisip na lubos kitang gantimpalaan ngunit pinigil ng Panginoon ang iyong gantimpala.”
na kayo'y pinangaralan at pinalakas ang loob ninyo, at nagpatotoo, upang kayo'y lumakad nang nararapat sa Diyos, na siyang tumawag sa inyo sa kanyang sariling kaharian at kaluwalhatian.
Tumira siya sa ilang ng Paran at ikinuha siya ng kanyang ina ng asawa sa lupain ng Ehipto.
upang ang Diyos ng ating Panginoong Jesu-Cristo, ang Ama ng kaluwalhatian, ay magkaloob sa inyo ng espiritu ng karunungan at ng pahayag sa isang ganap na pagkakilala sa kanya,
Ginawa sa kanya ng kanyang mga anak ang ayon sa iniutos sa kanila.
Kanyang sinabi sa matatanda, “Hintayin ninyo kami rito hanggang sa kami ay bumalik sa inyo, at sina Aaron at Hur ay kasama ninyo; sinumang magkaroon ng usapin ay lumapit sa kanila.”
At sinabi ng isa, “Ako ay tiyak na babalik sa iyo sa tamang panahon, at si Sara na iyong asawa ay magkakaanak ng isang lalaki.” Si Sara noon ay nakikinig sa may pintuan ng tolda na nasa likuran niya.
Ngunit ang bilang ng mga tisa na kanilang dating ginagawa ay siya rin ninyong iaatang sa kanila. Wala kayong babawasin sapagkat sila'y mga tamad. Kaya't sila'y dumadaing na nagsasabi, ‘Hayaan mo kaming umalis at maghandog sa aming Diyos.’
At ang buong lunsod ay nagkagulo at ang mga tao'y sama-samang nagtakbuhan. Kanilang hinuli si Pablo, siya'y kinaladkad palabas sa templo at agad isinara ang mga pinto.
at sa bawat nilikhang may buhay na kasama ninyo, ang mga ibon, ang maamong hayop at bawat mailap na hayop sa lupa na kasama ninyo, sa lahat ng lumabas sa daong, sa bawat hayop sa lupa.
“Ngunit sinumang maglagay ng batong katitisuran sa isa sa maliliit na ito na sumasampalataya sa akin, ay mas mabuti pa sa kanya na bitinan ang kanyang leeg ng isang malaking batong gilingan, at siya'y malunod sa kalaliman ng dagat.
Subalit sinabi niya, “Sa halip, mapalad silang nakikinig sa salita ng Diyos at sinusunod ito.”
At sinabi nila sa kanya, “Mayroon lamang tayong limang tinapay at dalawang isda.”
Itinayo ng mga anak ni Gad ang Dibon, ang Atarot, ang Aroer,
Ito ang aklat ng mga salinlahi ni Adan. Nang lalangin ng Diyos ang tao, siya ay nilalang sa wangis ng Diyos.
Huwag mong aanihin ang kusang tumubo sa iyong inanihan, at huwag mong titipunin ang mga ubas ng iyong ubasan na hindi mo inalagaan; iyon ay magiging taon ng ganap na kapahingahan sa lupain.
Si Moises ay lumabas upang salubungin ang kanyang biyenan, at kanyang niyukuran at hinalikan. Sila'y nagtanungan sa isa't isa ng kanilang kalagayan at sila'y pumasok sa tolda.
Kanilang papakinggan ang iyong tinig. Ikaw at ang matatanda sa Israel ay pupunta sa hari ng Ehipto, at inyong sasabihin sa kanya, ‘Ang Panginoon , ang Diyos ng mga Hebreo ay nakipagtagpo sa amin at ngayo'y pahintulutan mo kami na maglakbay ng tatlong araw sa ilang. Nais naming makapaghandog sa Panginoon naming Diyos.’
sapagkat anumang bagay na nakikita ay liwanag. Kaya't sinasabi, “Gumising ka, ikaw na natutulog, at bumangon mula sa mga patay, at si Cristo ay magliliwanag sa iyo.”
At bilang handog na inumin ay iyong ihahandog ang ikatlong bahagi ng isang hin ng alak na mabangong samyo sa Panginoon .
Subalit sumagot siya sa kanyang ama, ‘Tingnan mo, maraming taon nang ako'y naglingkod sa iyo, at kailanma'y hindi ako sumuway sa iyong utos. Gayunman ay hindi mo ako binigyan kailanman ng kahit isang batang kambing upang makipagsaya sa aking mga kaibigan.
Sapagkat ang gumagawa ng masama ay pagbabayarin sa kasamaang kanyang ginawa; at walang itinatanging tao.
Sinabi niya, “Dalhin mo na sa akin upang makakain ako ng usa ng aking anak, upang mabasbasan ka.” Inilapit niya ito sa kanya at kumain siya, at siya'y dinalhan niya ng alak, at siya'y uminom.
Ngunit kanyang sinabi, “O Panginoon, iba na ang iyong suguin.”
Ang ginto, pilak, tanso, bakal, lata, tingga,
Akong si Pablo ay sumusulat ng pagbating ito ng sarili kong kamay. Alalahanin ninyo ang aking mga tanikala. Sumainyo nawa ang biyaya.
“Gagawa ka rin ng mga tabing na balahibo ng kambing bilang tolda sa ibabaw ng tabernakulo; labing-isang tabing ang iyong gagawin.
Siya'y gumawa ng isang pantakip sa tolda na balat ng mga tupa na kinulayan ng pula, at ng isang takip na balat ng kambing sa ibabaw.
At mangyari na ang dalagang aking pagsabihan, ‘Pakibaba mo ang iyong banga upang ako'y makainom;’ at kanyang sasabihin, ‘Uminom ka, at paiinumin ko pati ang iyong mga kamelyo;’ ay siyang pinili mo para sa iyong lingkod na si Isaac; at sa ganito ay malalaman kong nagpakita ka ng tapat na pag-ibig sa aking panginoon.”
Sinabi ng Diyos, “Magkaroon ng mga tanglaw sa kalawakan ng langit upang ihiwalay ang araw sa gabi; at ang mga ito ay maging palatandaan para sa mga panahon, sa mga araw, at sa mga taon,
At kumuha si Moises ng langis na pambuhos, at ng dugong nasa ibabaw ng dambana, at iwinisik kay Aaron at sa kanyang mga suot, gayundin sa kanyang mga anak at sa mga suot ng kanyang mga anak. Itinalaga niya si Aaron at ang kanyang mga suot, ang kanyang mga anak, gayundin ang mga suot ng kanyang mga anak.
Kaya't nanirahan ang Israel sa lupain ng mga Amoreo.
Nakikita ng inyong mga mata at ng mga mata ng aking kapatid na si Benjamin, na ang bibig ko mismo ang nagsasalita sa inyo.
Sa ikatlong araw, nang mahapdi pa ang mga sugat ng mga tinuli, ang dalawa sa mga anak ni Jacob, sina Simeon at Levi, na mga kapatid ni Dina, ay kumuha ng kanilang tabak, palihim na pumasok sa bayan, at kanilang pinatay ang lahat ng mga lalaki.
Gayundin naman kayo, kapag nakita ninyong nangyayari ang mga bagay na ito, nalalaman ninyo na malapit na ang kaharian ng Diyos.
Ito ang Espiritu ng katotohanan na hindi kayang tanggapin ng sanlibutan; sapagkat siya'y hindi nito nakikita o nakikilala man. Siya'y nakikilala ninyo, sapagkat siya'y nananatiling kasama ninyo at siya ay mapapasa inyo.
Ikaw ang magiging pinuno sa aking bahay, at ayon sa iyong salita ay susunod ang aking buong bayan; tanging tungkol lamang sa pagkahari magiging mataas ako kaysa iyo.”
Sinabi niya, “Ano ang katulad ng kaharian ng Diyos at sa ano ko ito ihahambing?
Sa kanyang matinding paghihirap ay nanalangin siya ng higit na taimtim, at ang kanyang pawis ay naging gaya ng malalaking patak ng dugo na tumutulo sa lupa.]
Ito ay kakainin sa araw na ito na inialay, o sa kinabukasan. Ang nalabi sa ikatlong araw ay susunugin sa apoy.
(sapagkat ang kautusan ay walang pinasasakdal), sa gayon ay ipinapakilala ang isang higit na mabuting pag-asa, na sa pamamagitan nito ay lumalapit tayo sa Diyos.
At ikaw, Capernaum, itataas ka ba hanggang sa langit? Ibababa ka hanggang sa Hades. Sapagkat kung sa Sodoma ginawa ang mga makapangyarihang gawa na ginawa sa iyo, nanatili sana iyon hanggang sa araw na ito.
At sa pagnanais ni Pilato na bigyang-kasiyahan ang taong-bayan, pinalaya si Barabas para sa kanila. Pagkatapos na ipahagupit si Jesus, siya'y ibinigay niya upang ipako sa krus.
Ang Panginoon , ang Diyos ng langit, na kumuha sa akin sa sambahayan ng aking ama, at sa lupaing aking tinubuan ay nagsalita at sumumpa sa akin na nagsasabi, ‘Sa iyong binhi ay ibibigay ko ang lupaing ito;’ magsusugo siya ng kanyang anghel sa unahan mo, at ikukuha mo roon ng asawa ang aking anak.
Si Moises ay tumalikod at bumaba sa bundok, dala ang dalawang tapyas ng tipan sa kanyang mga kamay, mga tapyas na may sulat sa magkabilang panig niyon, sa isang panig at sa kabilang panig ay nakasulat ang mga iyon.
Kanilang inilagay siya sa kulungan, sapagkat hindi pa ipinahahayag kung ano ang gagawin sa kanya.
Hindi kayo maaaring kapootan ng sanlibutan, ngunit ako'y kinapopootan nito, sapagkat ako'y nagpapatotoo laban dito na masasama ang kanyang mga gawa.
“Ang manakit sa kanyang ama o sa kanyang ina ay papatayin.
At nagpatirapa si Abram, at sinabi ng Diyos sa kanya,
Ngunit nang magsasalita na si Pablo ay sinabi ni Galio sa mga Judio, “Kung ito'y tungkol sa masamang gawa o mabigat na kasalanan, ay may dahilan akong pagtiisan kayong mga Judio,
Subalit hinihiling namin sa inyo, mga kapatid, na inyong igalang ang mga nagpapagal sa inyo, at namumuno sa inyo sa Panginoon at nagtuturo sa inyo;
kapag siya'y nagkasala at naunawaan na niya ang kanyang kasalanan, isasauli niya ang ninakaw, o ang nakuha sa pangingikil, o ang habiling inihabilin sa kanya, o ang bagay na nawala na kanyang natagpuan,
“Kapag ang isang tao ay magtatalaga ng kanyang bahay upang maging banal sa Panginoon , ay hahalagahan ito ng pari, kung mabuti o masama; ayon sa ihahalaga ng pari ay magiging gayon.
Ito ang mga anak ni Gilead: kay Jezer, ang angkan ng mga Jezerita; kay Helec, ang angkan ng mga Helecita;
At doo'y nagpakita sa kanila si Elias na kasama si Moises at sila'y nakikipag-usap kay Jesus.
Kung ang isang babae ay lumapit sa alinmang hayop at nakipagtalik dito, papatayin mo ang babae at ang hayop; sila'y tiyak na papatayin at ang kanilang dugo ay nasa kanila.
At kung ang isang dayuhan ay nakikipamayan kasama ninyo, o sinumang kasama ninyo sa buong panahon ng inyong mga salinlahi, at maghahandog ng handog na pinaraan sa apoy, na mabangong samyo sa Panginoon ay kanyang gagawin ang gaya ng inyong ginagawa.
Bukod dito'y sinabi ng Panginoon kay Moises,
Tumindig ang buong karamihan at dinala si Jesus sa harap ni Pilato.
Kaya't dahil sa mga pagnanasa ng kanilang mga puso ay hinayaan sila ng Diyos sa karumihan, upang lapastanganin ang kanilang mga katawan sa kani-kanilang sarili;
at hindi makakapasok doon ang anumang bagay na marumi, o ang sinumang gumagawa ng karumaldumal o ng kasinungalingan, kundi sila lamang na nakasulat sa aklat ng buhay ng Kordero.
“Ipaghiganti mo ang mga anak ni Israel sa mga Midianita; pagkatapos nito'y ititipon ka sa iyong bayan.”
Sinabi ng Panginoon kay Moises,
Nagtipon ang mga apostol at ang matatanda upang pag-usapan ang bagay na ito.
Halika, ikaw ay aking susuguin kay Faraon upang iyong ilabas sa Ehipto ang aking bayan, ang mga anak ni Israel.”
At namangha ang kanyang mga magulang, subalit ipinagbilin ni Jesus sa kanila na huwag sabihin kaninuman ang nangyari.
Sapagkat ang mga mata ng Panginoon ay nasa mga matuwid, at ang kanyang mga tainga ay bukas sa kanilang mga panalangin. Ngunit ang mukha ng Panginoon ay laban sa mga gumagawa ng masama.”
At hinamak siya at nilibak ni Herodes at ng mga kawal na kasama niya. Sinuotan siya ng maringal na damit at ibinalik kay Pilato.
At sinabi ni Lamec sa kanyang mga asawa, “Ada at Zilla, pakinggan ninyo ang aking tinig. Kayong mga asawa ni Lamec ay makinig sa aking mga salita. Pumatay ako ng isang tao, dahil sa pagsugat sa akin, at ng isang binata, dahil sa ako'y sinaktan.
Sila'y naglakbay mula sa bundok ng Hor patungo sa Dagat na Pula upang umikot sa lupain ng Edom; at ang damdamin ng mga tao ay nainip sa daan.
Habang sila'y nagkakatipon sa Galilea, sinabi ni Jesus sa kanila: “Ang Anak ng Tao ay malapit nang ipagkanulo sa kamay ng mga tao.
Sa mga ibon ayon sa kanilang uri, sa mga hayop ayon sa kanilang uri, sa bawat gumagapang sa lupa ayon sa kanilang uri, dalawa sa bawat uri ang isasama mo upang ang mga iyon ay manatiling buháy.
Kaya't tinanong niya ang mga tagapamahala ng Faraon na mga kasama niya sa bilangguan sa bahay ng kanyang panginoon, “Bakit balisa kayo ngayon?”
ang hapag pati ang lahat ng mga kasangkapan niyon, at ang tinapay na handog;
At kapag tinawag kayo ng Faraon, at sasabihin, ‘Ano ang inyong hanapbuhay?’
Sindak at panghihilakbot ang sa kanila'y umabot, dahil sa kadakilaan ng iyong bisig, sila'y parang batong di makakilos; hanggang sa makaraan, O Panginoon , ang iyong bayan, hanggang ang bayan na iyong binili ay makaraan.
Magbibigay ako ng kapayapaan sa lupain, at mahihiga kayo, at wala kayong katatakutan. Aking aalisin sa lupain ang mababangis na hayop, at hindi daraanan ng tabak ang inyong lupain.
Kaya't hinihiling ko na huwag kayong manlupaypay sa mga pagdurusa ko dahil sa inyo, na ito'y para sa inyong kaluwalhatian.
At sinabi ni Raquel sa kanyang ama, “Huwag magalit ang aking panginoon na ako'y hindi makatayo sa harap mo; sapagkat dinatnan ako ngayon.” Kaya't kanyang hinanap, ngunit hindi natagpuan ang mga diyos ng sambahayan.
Nang marinig ni Elizabeth ang bati ni Maria, gumalaw ang sanggol sa kanyang sinapupunan at napuno si Elizabeth ng Espiritu Santo.
Dahil dito, sa pagkakaroon namin ng ministeryong ito sa pamamagitan ng aming tinanggap na habag, kami ay hindi pinanghihinaan ng loob.
Kaya't kanilang kinuha ang mahabang damit ni Jose, at sila'y pumatay ng isang lalaking kambing, at kanilang inilubog ang mahabang damit sa dugo.
Nalalaman natin na ang ating dating pagkatao ay kasama niyang ipinako sa krus, upang ang katawang makasalanan ay mawalan ng bisa, at upang tayo'y hindi na magpaalipin pa sa kasalanan;
“Ang mga anak ni Israel ay magkakampo, bawat lalaki sa tabi ng kanyang sariling watawat, na may sagisag ng mga sambahayan ng kanyang mga ninuno; magkakampo sila na nakaharap sa toldang tipanan sa palibot nito.
Masdan ninyo, ang inyong bahay ay iniiwan sa inyong wasak.
Huwag nga kayong tumulad sa kanila, sapagkat alam na ng inyong Ama ang mga bagay na inyong kinakailangan, bago pa kayo humingi sa kanya.
At kanyang ihahandog ang isa sa mga batu-bato o sa mga inakay ng kalapati, kung alin ang kanyang kaya.
At aking sinabi sa kanila, ‘Sinumang may ginto ay hubarin ito,’ at kanila namang ibinigay sa akin, at aking inihagis sa apoy at lumabas ang guyang ito!”
“Ang laman na mapasagi sa anumang bagay na marumi ay hindi kakainin; ito ay susunugin sa apoy. Tanging ang lahat na malinis ang makakakain ng gayong laman.
Subalit si Noe ay nakatagpo ng biyaya sa paningin ng Panginoon .
at isinulat sa pamamagitan ng kamay nila: “Ang mga apostol at ang matatanda, ang mga kapatid, sa mga kapatid na nasa mga Hentil sa Antioquia at Siria at Cilicia, ay bumabati.
Sapagkat paano ngayon malalaman na ako'y nakatagpo ng biyaya sa iyong paningin, ako at ang iyong bayan? Hindi ba dahil sa ikaw ay lumalakad na kasama namin, kaya't kami ay naiiba, ako at ang iyong bayan, sa lahat ng bayan sa balat ng lupa?”
Kaya't ang aking katapatan ay sasagot para sa akin sa huli, kapag ikaw ay dumating upang tingnan ang upa mo sa akin. Ang lahat na walang batik at walang dungis sa mga kambing, at hindi maitim sa mga tupa na matatagpuan mo sa akin, ay ituturing mong nakaw.”
Sapagkat ang laman ay nagnanasa laban sa Espiritu, at ang Espiritu ay laban sa laman; sapagkat ang mga ito ay laban sa isa't isa, upang hindi ninyo magawa ang mga bagay na nais ninyong gawin.
Umalis si Jesus doon at dumaan sa baybayin ng Dagat ng Galilea. Umakyat siya sa bundok at naupo roon.
Ako'y nakikiusap sa iyo para sa aking anak na si Onesimo na ako'y naging kanyang ama nang ako'y nasa bilangguan.
Ang mga bagay na ito ay ginawa ng mga kawal. Samantala, nakatayo sa tabi ng krus ni Jesus ang kanyang ina, at ang kapatid ng kanyang ina, si Maria na asawa ni Cleopas, at si Maria Magdalena.
Sinabi ng Panginoon kina Moises at Aaron:
At sasabihin mo sa mga anak ni Israel, “Sinumang lumait sa kanyang Diyos ay mananagot sa kanyang kasalanan.
Kung siya'y magkasala laban sa iyo ng pitong ulit sa isang araw at pitong ulit siyang bumalik sa iyo, na nagsasabi, ‘Nagsisisi ako,’ dapat mo siyang patawarin.”
Pagkatapos ay sasabihin niya sa mga nasa kaliwa, ‘Lumayo kayo sa akin, kayong mga sinumpa. Doon kayo sa apoy na walang hanggan na inihanda sa diyablo at sa kanyang mga anghel.
Nang pasimula, nilikha ng Diyos ang langit at ang lupa.
Ngunit ang maraming nauuna ay mahuhuli, at ang huli ay mauuna.”
At pagharap niya sa mga alagad ay palihim niyang sinabi, “Mapapalad ang mga matang nakakakita ng inyong nakikita.
yamang taglay ninyo ang gayunding pakikipaglaban na inyong nakita sa akin, at ngayo'y nababalitaan ninyo tungkol sa akin.
Si Moises ay nag-atas sa atin ng isang kautusan, isang pamana para sa kapulungan ni Jacob.
Kaya't sinabi nila sa isa't isa, “Huwag natin itong punitin, kundi tayo'y magpalabunutan kung kanino mapupunta.” Ito ay upang matupad ang kasulatan, na nagsasabi, “Pinaghatian nila ang aking mga kasuotan, at ang aking balabal ay kanilang pinagpalabunutan.”
Ang mga pinuno ay magsasalita sa mga kawal, ‘Sinong tao ang nagtayo ng isang bagong bahay, at hindi pa niya naitatalaga? Hayaan siyang umalis at bumalik sa kanyang bahay, baka siya'y mamatay sa pakikipaglaban at ibang tao ang magtalaga.
Sinabi ni Balaam kay Balak, “Ipagtayo mo ako rito ng pitong dambana, at ipaghanda mo ako rito ng pitong toro at pitong lalaking tupa.”
Subalit kung ang singaw ay kumakalat sa balat pagkatapos na siya'y magpakita sa pari para sa kanyang paglilinis, siya ay muling magpapakita sa pari.
Sapagkat sinabi niya sa kanya, “Lumabas ka sa taong iyan, ikaw na masamang espiritu.”
Ngunit, tungkol naman sa Anak ay sinasabi niya, “Ang iyong trono, O Diyos, ay magpakailanman; at ang setro ng katuwiran ang siyang setro ng iyong kaharian.
Sinabi ni Pilato sa kanila, “Kunin ninyo siya, at siya'y inyong hatulan ayon sa inyong batas.” Sinabi ng mga Judio sa kanya, “Hindi kami pinahihintulutan na ipapatay ang sinumang tao.”
Ngunit dumating ang pangulong pinunong si Lisias at sapilitang inagaw siya sa aming mga kamay, at inutusan ang mga nagbintang sa kanya na humarap sa inyo.]
Kapag babae, ang katumbas ay tatlumpung siklo.
Sa simula ang mga bagay na ito ay hindi naunawaan ng kanyang mga alagad. Ngunit nang si Jesus ay niluwalhati na, saka nila naalala na ang mga bagay na ito ay sinulat tungkol sa kanya, at nangyari ang mga bagay na ito sa kanya.
Sa pamamagitan ni Silvano, na itinuturing kong tapat nating kapatid, ay sinulatan ko kayo nang maikli upang pasiglahin kayo at magpatotoo na ito ang tunay na biyaya ng Diyos. Manindigan kayo rito.
At ibinalik niya ang puno ng mga katiwala ng kopa sa kanyang pagiging katiwala ng kopa, at ibinigay niya ang kopa sa kamay ng Faraon.
Sapagkat tinuturuan niya ang kanyang mga alagad na sa kanila'y sinasabi, “Ang Anak ng Tao ay ipagkakanulo sa mga kamay ng tao at siya'y papatayin nila. Tatlong araw matapos siyang patayin, siya'y muling mabubuhay.”
Subalit dahil wala silang makitang daan dahil sa dami ng tao, umakyat sila sa bubungan ng bahay at ibinaba siya pati na ang kanyang higaan mula sa binutas nilang bubungan sa gawing gitna, sa harapan ni Jesus.
Sinabi niya, “Tingnan ninyo, nakikita kong bukas ang mga langit at ang Anak ng Tao na nakatindig sa kanan ng Diyos.”
Sa likod ng ikalawang tabing ay ang tabernakulo na tinatawag na Dakong Kabanal-banalan.
Ngunit ang isa sa nakatayo roon ay bumunot ng kanyang tabak, tinaga ang alipin ng pinakapunong pari, at tinigpas ang kanyang tainga.
Ngunit dahil sa sinabi ko ang mga bagay na ito sa inyo, napuno ng lungkot ang inyong puso.
Subalit kung naghahanda ka ng piging, anyayahan mo ang mga dukha, ang mga pilay, ang mga lumpo, ang mga bulag,
Subalit sinabi ni Juda sa kanya, “Ang lalaking iyon ay mahigpit na nagbabala sa amin, na sinasabi, ‘Hindi ninyo makikita ang aking mukha malibang kasama ninyo ang inyong kapatid.’
Ingatan ninyo ang inyong sarili, upang huwag ninyong maiwala ang mga bagay na aming pinagpaguran, kundi upang tumanggap kayo ng lubos na gantimpala.
Mula noon si Jesus ay nagpasimulang mangaral na nagsasabi, “Magsisi kayo, sapagkat malapit na ang kaharian ng langit.”
Ipagpatuloy ninyo ang inyong paglalakbay at pumunta kayo sa lupaing maburol ng mga Amoreo, at sa lahat nitong kalapit na lugar, sa Araba na lupaing maburol at sa kapatagan, sa Negeb, at sa baybayin ng dagat, sa lupain ng mga Cananeo, sa Lebanon, hanggang sa malaking ilog ng Eufrates.
Matapos makipagkasundo sa mga manggagawa ng isang denario sa isang araw ay kanyang isinugo sila sa kanyang ubasan.
At ang Panginoon ay bumaba sa ulap at nagsalita sa kanya; at kumuha sa espiritung nasa kanya at isinalin sa pitumpung matatanda at nangyari, na nang bumaba sa kanila ang espiritu ay nagpropesiya sila. Ngunit hindi na nila iyon ginawa muli.
Kaya't sinabi niya kay Abraham, “Palayasin mo ang aliping ito at ang kanyang anak, sapagkat hindi magmamana ang anak ng aliping ito na kahati ng aking anak na si Isaac.”
Sa mga anak ni Levi, narito, aking ibinigay ang lahat ng ikasampung bahagi sa Israel bilang mana, na ganti sa kanilang paglilingkod na kanilang ipinaglilingkod, samakatuwid ay sa paglilingkod sa toldang tipanan.
“Isang Ananias, na lalaking masipag sa kabanalan ayon sa kautusan, at may magandang patotoo tungkol sa kanya ang mga Judio na naninirahan doon,
Sinabi ng Panginoon kay Moises, “Bumaba ka agad! Ang iyong bayan na inilabas mo mula sa lupain ng Ehipto ay nagpapakasama.
Agad niyang tinawag sila at iniwan nila si Zebedeo na kanilang ama sa bangka na kasama ng mga upahang tauhan at sumunod sa kanya.
Sa kapulungan ay magkakaroon ng isang tuntunin sa inyo, at sa dayuhang nakikipamayang kasama ninyo, isang tuntunin magpakailanman sa buong panahon ng inyong mga salinlahi. Kung paano kayo ay magiging gayundin ang dayuhan sa harap ng Panginoon .
May isang babaing Cananea na mula sa lupaing iyon ang lumabas at nagsimulang sumigaw, “Mahabag ka sa akin, O Panginoon, Anak ni David; ang anak kong babae ay pinahihirapan ng isang demonyo.”
Sinabi ni Cornelio, “Apat na araw na ang nakakaraan, mga ganitong oras, nang ikasiyam na oras, ako'y nananalangin sa aking bahay nang biglang tumindig sa harapan ko ang isang lalaki na may nagniningning na damit.
Lahat ng mga Ehipcio ay humukay sa palibot ng ilog upang makakuha ng tubig na maiinom, sapagkat hindi nila mainom ang tubig sa ilog.
Ginawa ni Moises ang ayon sa iniutos ng Panginoon sa kanya at kanyang isinama si Josue. Kanyang iniharap siya sa paring si Eleazar at sa buong kapulungan.
Sinabi sa kanya ni Jesus, “Humayo ka na, ang anak mo ay mabubuhay.” Pinaniwalaan ng lalaki ang salitang sinabi sa kanya ni Jesus, at siya'y humayo sa kanyang lakad.
sapagkat ang mga nagsasabi ng gayong mga bagay ay nagpapakilalang sila ay naghahanap ng sariling bayan.
na sa kanya'y nakiapid ang mga hari sa lupa, at ang mga naninirahan sa lupa ay nalasing sa alak ng kanyang pakikiapid.
Nang makita ito ng maraming tao, sila ay natakot at niluwalhati nila ang Diyos, na nagbigay ng gayong awtoridad sa mga tao.
At nagpakita ang Panginoon kay Isaac at sinabi, “Huwag kang bumaba sa Ehipto; manatili ka sa lupaing aking sasabihin sa iyo.
Siya na nagligtas sa amin mula sa kakilakilabot na kamatayan at patuloy na magliligtas; sa kanya ay inilalagak namin ang ating pag-asa na muli niya kaming ililigtas.
at kakaladkarin nila kayo sa harap ng mga gobernador at mga hari dahil sa akin, upang magpatotoo sa kanila at sa mga Hentil.
Ngunit sa mga duwag, sa mga hindi nananampalataya, mga karumaldumal, mga mamamatay-tao, mga mapakiapid, mga mangkukulam, mga sumasamba sa mga diyus-diyosan, at sa lahat na mga sinungaling, ang kanilang bahagi ay sa lawa na nagliliyab sa apoy at asupre, na siyang ikalawang kamatayan.”
at si Isaac ay apatnapung taon nang siya'y mag-asawa kay Rebecca, na anak ni Betuel na Arameo sa Padan-aram, kapatid na babae ni Laban na Arameo.
“‘Sumpain ang tumatanggap ng suhol upang pumatay ng isang taong walang sala.’ At ang buong bayan ay magsasabi, ‘Amen.’
Sapagkat kinulong ng Diyos ang lahat sa pagsuway upang siya'y mahabag sa lahat.
At ang lahat, ang hamak at ang dakila, ang mayayaman at ang mga dukha, ang mga malaya at ang mga alipin ay pinalagyan nito ng isang tanda sa kanilang kanang kamay o sa noo,
Ngunit nang marinig ng mga Fariseo na napatahimik ni Jesus ang mga Saduceo, ay nagtipon sila.
“Ngunit nang pumasok ang hari upang tingnan ang mga panauhin, may nakita siya roong isang tao na hindi nakadamit pangkasal.
Sa gitna ng mga bansang ito ay hindi ka makakasumpong ng ginhawa, at mawawalan ng kapahingahan ang talampakan ng iyong paa, kundi bibigyan ka doon ng Panginoon ng isang nanginginig na puso, lumalabong paningin, at nanghihinang kaluluwa.
na naging pari, hindi ayon sa itinatakda ng batas na ukol sa laman, kundi ayon sa kapangyarihan ng isang buhay na hindi mapupuksa.
Kanyang ginawa ang efod na ginto, na telang asul, kulay-ube, pula, at hinabing pinong lino.
At bakit ninyo kami pinaahon mula sa Ehipto upang dalhin kami sa masamang lugar na ito? Hindi ito lugar na bukirin, o ng igos, o ng ubasan, o ng mga granada; at dito'y walang tubig na mainom.”
Ipag-uutos ng pari na alisan ng laman ang bahay bago siya pumasok upang tingnan ang sakit, upang ang lahat na nasa bahay ay huwag maging marumi; at pagkatapos ay papasok ang pari upang tingnan ang bahay.
Sa akin kayo ay magiging isang kaharian ng mga pari at isang banal na bansa. Ito ang mga salitang sasabihin mo sa mga anak ni Israel.”
“Magsisi kayo, sapagkat malapit na ang kaharian ng langit.”
Nang sila'y makapagtalaga ng isang araw para sa kanya, nagtungo sila sa kanyang tinutuluyan at napakarami nila. Ipinaliwanag niya sa kanila ang pangyayari buhat umaga hanggang gabi na nagpapatotoo tungkol sa kaharian ng Diyos, at sinikap na sila'y mahikayat tungkol kay Jesus, mula sa kautusan ni Moises at mula sa mga propeta.
Lahat ng mga panganay ay akin, nang araw na aking lipulin ang lahat ng mga panganay sa lupain ng Ehipto ay aking itinalaga para sa akin ang lahat ng mga panganay sa Israel, maging tao at hayop man. Sila'y magiging akin; ako ang Panginoon .”
“Huwag kayong magnanakaw, ni mandaraya, ni magsisinungaling sa isa't isa.
lahat ng mga lunsod sa kapatagan, at ang buong Gilead, at ang buong Basan, hanggang Saleca at Edrei, ang mga lunsod ng kaharian ni Og sa Basan.
Ang isang kordero ay iyong ihahandog sa umaga; at ang isang kordero ay iyong ihahandog sa hapon;
“Ang nag-iisang saksi ay hindi mangingibabaw laban sa isang tao sa anumang kasamaan o kasalanang kanyang nagawa; sa patotoo ng dalawa o tatlong saksi ay pagtitibayin ang usapin.
Kaya't natupad ang sinabi sa pamamagitan ng propeta Jeremias, na sinasabi, “At kinuha nila ang tatlumpung pirasong pilak, ang halaga niya na itinuring na halaga ng ilan sa mga anak ng Israel,
Ngunit ililigtas ang babae sa pamamagitan ng panganganak, kung sila'y mananatiling may kaayusan sa pananampalataya, pag-ibig at sa kabanalan.
Pagkatapos, sinabi ng Panginoon kay Moises, “Sabihin mo kay Aaron; ‘Iunat mo ang iyong tungkod, at hampasin mo ang alabok ng lupa, upang ito ay maging mga kuto sa buong lupain ng Ehipto.’”
Iyong ipapangilin ang Pista ng mga Sanlinggo, ang mga unang bunga ng pag-aani ng trigo, at ang kapistahan ng pagtitipon ng ani sa katapusan ng taon.
Para sa ating kapakanan, ginawa niyang may kasalanan siya na hindi nakakilala ng kasalanan, upang sa kanya tayo'y maging katuwiran ng Diyos.
Sapagkat kami'y walang magagawang anuman laban sa katotohanan, kundi tanging para sa katotohanan.
Sinabi sa kanya ni Jesus, “Humayo ka, pinagaling ka ng iyong pananampalataya.” Agad na nagbalik ang kanyang paningin at siya'y sumunod sa kanya sa daan.
“Kayong matitigas ang ulo at hindi tuli ang puso't mga tainga, kayo'y laging sumasalungat sa Espiritu Santo. Kung ano ang ginawa ng inyong mga ninuno, ay gayundin ang ginagawa ninyo.
Mas madali pa para sa isang kamelyo ang dumaan sa butas ng isang karayom kaysa isang mayaman ang pumasok sa kaharian ng Diyos.”
Huwag ninyong pahihirapan ang sinumang babaing balo, o batang ulila.
Nang si Juda at ang kanyang mga kapatid ay dumating sa bahay ni Jose, siya'y nandoon pa, at sila'y nagpatirapa sa lupa sa harapan niya.
Kaya't mula ngayon ay nakalaan na sa akin ang putong ng katuwiran, na ibibigay sa akin ng Panginoon na tapat na hukom sa araw na iyon, at hindi lamang sa akin, kundi sa lahat din naman ng mga naghahangad sa kanyang pagpapakita.
Subalit tungkol sa Israel ay sinasabi niya, “Sa buong araw ay iniunat ko ang aking mga kamay sa isang suwail at mapagsalungat na bayan.”
na iniingatan ang pananampalataya at ang mabuting budhi. Sa pamamagitan ng pagtatakuwil sa budhi, ang ibang tao ay nakaranas ng pagkawasak ng barko sa kanilang pananampalataya;
Nagsalita ang Panginoon kay Moises, na sinasabi,
Mula sa binhi ng taong ito, ang Diyos ay nagkaloob ng isang Tagapagligtas sa Israel na si Jesus, gaya ng kanyang ipinangako.
Kanyang binalot ang mga tabla ng ginto, at gumawa ng mga gintong argolya na mga daraanan ng mga biga, at binalot ang mga biga ng ginto.
“Binulag niya ang kanilang mga mata, at pinatigas niya ang kanilang mga puso; upang sila'y huwag makakita sa pamamagitan ng kanilang mga mata, at makaunawa sa pamamagitan ng kanilang puso, at magbalik-loob, at sila'y pagalingin ko.”
Tinawag niya ang kanyang pangalan na Noe, na sinabi, “Ito ang magbibigay sa atin ng ginhawa mula sa ating gawa at sa pagpapagod ng ating mga kamay, dahil sa lupang sinumpa ng Panginoon .”
At narinig ko ang gaya ng isang tinig sa gitna ng apat na nilalang na buháy na nagsasabi, “Isang takal na trigo para sa isang denario at sa isang denario ay tatlong takal na sebada; ngunit huwag mong pinsalain ang langis at ang alak!”
Nang ibalita kay Tamar na “Ang iyong biyenang lalaki ay umaahon sa Timna upang pagupitan ang kanyang mga tupa,”
Hinihiling ko sa iyo na iligtas mo ako sa kamay ng aking kapatid na si Esau. Ako'y natatakot sa kanya, baka siya'y dumating at kaming lahat ay pagpapatayin niya, ang mga ina pati ang mga anak.
Subalit ang taba, ang mga bato, at ang lamad na nasa atay ng handog pangkasalanan ay sinunog niya sa ibabaw ng dambana, gaya ng iniutos ng Panginoon kay Moises.
Sa hihip ng iyong ilong ang tubig ay natipon, ang mga agos ay tumayong parang isang bunton; Ang mga kalaliman ay namuo sa gitna ng dagat.
Gayundin, iniutos niya sa ikalawa, sa ikatlo, at sa lahat ng sumusunod sa mga kawan, na sinasabi, “Sasabihin ninyo ang gayunding bagay kay Esau, kapag nakasalubong ninyo siya,
At ako'y kanyang dinalang nasa Espiritu sa isang ilang at nakita ko ang isang babae na nakasakay sa isang halimaw na pula, na punô ng mga pangalan ng kalapastanganan na may pitong ulo at sampung sungay.
Kanyang sinindihan ang mga ilaw sa harap ng Panginoon ; gaya ng iniutos ng Panginoon kay Moises.
Kung nililinis ng sinuman ang kanyang sarili mula sa mga bagay na ito ay magiging tanging kagamitan, itinalaga at mahalaga sa may-ari ng bahay, handa sa lahat ng mabuting gawa.
Ito ay ayon sa walang hanggang panukala na kanyang ginawa kay Cristo Jesus na Panginoon natin,
ito ay susuriin ng pari, at kung may namumuti na nangingintab na pantal sa balat ng kanyang laman; ito ay isang singaw na sumibol sa balat; siya'y malinis.
Ang iyong suot ay hindi naluma, hindi namaga ang iyong paa sa loob ng apatnapung taon.
tungkol sa katuwiran, sapagkat ako'y pupunta sa Ama, at hindi na ninyo ako makikita;
Ang babaing ito ay isang Griyego, isang Sirofenisa, ayon sa lahi. Nakiusap siya kay Jesus na palayasin ang demonyo sa kanyang anak na babae.
at doon nila ipinangaral ang magandang balita.
Ang inyong pinatatawad ay ipinatatawad ko rin. Ang aking pinatawad, kung ako'y nagpapatawad ay alang-alang sa inyo, sa harapan ni Cristo.
Ngunit siya'y nagsimulang magmura at sumumpa, “Hindi ko nakikilala ang taong ito na inyong sinasabi.”
Mamunga kayo nang nararapat sa pagsisisi.
Sapagkat nagmumula sa puso ang masasamang pag-iisip, pagpatay, pangangalunya, pakikiapid, pagnanakaw, pagsaksi sa kasinungalingan, at paglapastangan.
Dumating ang isang babaing Samaritana upang umigib ng tubig. Sinabi sa kanya ni Jesus, “Bigyan mo ako ng inumin.”
Bagkus, inyong patawarin siya at aliwin, baka siya ay madaig ng labis na kalungkutan.
at upang ang mga Hentil ay lumuwalhati sa Diyos dahil sa kanyang kahabagan, gaya ng nasusulat, “Kaya't ikaw ay aking pupurihin sa gitna ng mga Hentil, at aawit ako ng papuri sa iyong pangalan.”
At sumagot ang buong bayan at nagsabi, “Pananagutan namin at ng aming mga anak ang kanyang dugo.”
Ngunit kayong humawak ng matatag sa Panginoon ninyong Diyos ay buháy na lahat sa araw na ito.’
Kung ang lalaking nilalabasan ng binhi ay sumiping sa isang babae, silang dalawa ay maliligo sa tubig, at magiging marumi hanggang sa paglubog ng araw.
“Ipararating ng Panginoon sa iyo ang sumpa, ang pagkalito at pagkabigo sa lahat ng iyong gagawin, hanggang sa ikaw ay mabuwal at mapuksa dahil sa kasamaan ng iyong mga gawa, sapagkat pinabayaan mo ako.
Ngunit ang iyong mga lingkod ay tatawid, bawat lalaki na may sandata sa pakikipaglaban, sa harap ng Panginoon upang makipaglaban gaya ng sinabi ng aking panginoon.”
Sinabi sa kanila ni Jesus, “Hindi pa dumating ang aking oras, subalit ang inyong oras ay laging naririyan.
Mula sa limampung taong gulang ay titigil sila sa katungkulan sa paglilingkod at hindi na sila maglilingkod.
Ito ang mga pangalan ng mga anak ni Aaron, na mga paring binuhusan ng langis, na kanyang itinalaga upang maglingkod bilang mga pari.
Halikayo, atin siyang ipagbili sa mga Ismaelita, at huwag natin siyang pagbuhatan ng kamay, sapagkat siya'y ating kapatid, at ating laman.” At pinakinggan siya ng kanyang mga kapatid.
Kinabukasan, muling naroon si Juan kasama ng dalawa sa kanyang mga alagad.
Sapagkat ang Diyos ang nagsabi, “Magningning ang ilaw sa kadiliman,” na siyang tumatanglaw sa aming mga puso upang magbigay-liwanag sa pagkakilala sa kaluwalhatian ng Diyos sa mukha ni Jesu-Cristo.
Kaya't huwag ninyong paghariin ang kasalanan sa inyong katawang may kamatayan, upang masunod ang mga pagnanasa nito.
Mayroon doong isang sisidlang punô ng maasim na alak, kaya't naglagay sila ng isang esponghang basa ng suka sa isang sanga ng isopo, kanilang inilagay sa kanyang bibig.
subalit mula sa punungkahoy ng pagkakilala ng mabuti at masama ay huwag kang kakain; sapagkat sa araw na ikaw ay kumain niyon ay tiyak na mamamatay ka.”
ngunit pinagpapakitaan ko ng wagas na pag-ibig ang libu-libong umiibig sa akin at tumutupad ng aking mga utos.
Itututok ko ang aking mukha laban sa inyo, at kayo'y masasaktan sa harapan ng inyong mga kaaway. Ang mga napopoot sa inyo ay maghahari sa inyo, at kayo'y tatakas nang walang humahabol sa inyo.
Isang dambanang lupa ang iyong gagawin para sa akin, at iyong iaalay doon ang iyong mga handog na sinusunog, mga handog pangkapayapaan, mga tupa, at mga baka. Sa lahat ng dakong aking ipapaalala ang aking pangalan ay pupunta ako sa iyo at pagpapalain kita.
Ang mga bulag at mga pilay ay lumapit sa kanya sa templo at sila'y kanyang pinagaling.
At sinabi sa kanila ni Jesus, “Hindi ko rin naman sasabihin sa inyo kung sa anong awtoridad ko ginagawa ang mga bagay na ito.”
Gawin ninyo ang lahat ng mga bagay na walang pabulong-bulong at pagtatalo,
Sinabi ng mga apostol sa Panginoon, “Dagdagan mo ang pananampalataya namin.”
Mula noon, si Jesus ay hindi na naglalakad nang hayagan sa gitna ng mga Judio, kundi pumunta siya sa lupaing malapit sa ilang, sa isang bayan na tinatawag na Efraim. Siya'y nanirahan doon kasama ng mga alagad.
Inanyayahan din si Jesus at ang kanyang mga alagad sa kasalan.
Subalit siya'y nagtagal. Kaya't dahil sa habag sa kanya ng Panginoon , hinawakan ng mga lalaki ang kanyang kamay at ang kamay ng kanyang asawa, at ang kamay ng kanyang dalawang anak na babae; at siya'y inilabas nila at iniwan sa labas ng bayan.
At doo'y tutustusan kita, sapagkat may limang taong taggutom pa; baka ikaw, at ang iyong sambahayan, at ang lahat ng iyo ay maging dukha.’
Ang mga bagay na ito ay isinulat ko sa inyo upang inyong malaman na kayo'y mayroong buhay na walang hanggan sa inyong nananampalataya sa pangalan ng Anak ng Diyos.
at sa kanyang kapatid na dalaga na malapit sa kanya, sapagkat siya ay walang asawa, ay maaaring madungisan niya ang kanyang sarili dahil sa dalaga.
yamang inyong nalalaman na ang pagsubok sa inyong pananampalataya ay nagbubunga ng pagtitiis.
Tumindig siya at umuwi sa kanyang bahay.
patungkol sa mga hari at sa lahat ng nasa mataas na katungkulan upang tayo'y mamuhay na tahimik at payapa sa buong kabanalan at paggalang.
Inilagay ni Moises ang mga tungkod sa harap ng Panginoon sa tolda ng patotoo.
Kayong lahi ng mga ulupong! Paano kayo makapagsasalita ng mabubuting bagay gayong kayo ay masasama? Sapagkat sa kasaganaan ng puso ay nagsasalita ang bibig.
Natagpuan ni Felipe si Nathanael, at sinabi sa kanya, “Natagpuan namin iyong isinulat ni Moises sa Kautusan, at gayundin ng mga propeta, si Jesus na taga-Nazaret, ang anak ni Jose.”
Kaya't ang maraming tao na kasama niya, nang tawagin niya si Lazaro mula sa libingan, at siya'y buhayin mula sa mga patay, ay siyang nagpapatunay.
Dalhin ninyo ang inyong mga kawan at ang inyong mga baka, gaya ng inyong sinabi, at kayo'y umalis na; at idalangin ninyo na ako ay pagpalain!”
Nang ito'y hindi pa nabibili, hindi ba iyon ay nanatiling iyo? At nang maipagbili na, hindi ba nasa iyo ring kapangyarihan? Bakit inisip mo pa ang bagay na ito sa iyong puso? Hindi ka nagsinungaling sa mga tao, kundi sa Diyos.”
Noon ay mayroong isang tao na maysakit, si Lazaro na taga-Betania, ang nayon nina Maria at Marta na kanyang mga kapatid.
at papatayin ang isa sa mga ibon sa isang sisidlang lupa sa ibabaw ng tubig na umaagos,
“Anong ibig mong gawin ko sa iyo?” At sinabi niya, “Panginoon, ako sana'y muling makakita.”
Nagtungo ang mga anak na lalaki ni Jacob sa mga pinatay, at kanilang sinamsaman ang bayan, sapagkat pinagsamantalahan ang kanilang kapatid.
At muli siyang yumuko, at isinulat ang kanyang daliri sa lupa.
Pinapakinggan ng aking mga tupa ang aking tinig, at sila'y aking kilala, at sila'y sumusunod sa akin.
Sapagkat bago pa ang mga araw na ito ay lumitaw na si Teudas, na nagsabing siya'y dakila; at sumama sa kanya ang may apatnaraang tao ang bilang, ngunit siya'y pinatay at ang lahat ng sumunod sa kanya ay nagkawatak-watak at nawalan ng kabuluhan.
Sinabi ni Moises sa kanila, “Sinuman ay huwag magtira niyon hanggang sa umaga.”
Kaya't kanyang dinala siya sa parang ng Sofim, sa tuktok ng Pisga, at nagtayo roon ng pitong dambana, at naghandog ng isang toro at ng isang lalaking tupa sa bawat dambana.
Paglapit ninyo sa labanan, ang pari ay lalapit at magsasalita sa mga kawal,
Kung ang mga taong ito ay mamatay sa karaniwang kamatayan ng lahat ng tao, o dumating sa kanila ang likas na kapalaran ng lahat ng tao, hindi nga ako sinugo ng Panginoon .
Subalit nais mo bang malaman, O taong hangal, na ang pananampalataya na walang mga gawa ay baog?
Gagawin mo ang mga haligi para sa tabernakulo: dalawampung haligi sa gawing timog;
Sapagkat sinumang gumagawa ng mga bagay na ito ay karumaldumal sa Panginoon , at dahil sa mga karumaldumal na gawaing ito ay pinalalayas sila ng Panginoon mong Diyos sa harapan mo.
Baka sabihin ng mga tao sa lupaing pinaglabasan mo sa amin: “Sapagkat hindi sila naipasok ng Panginoon sa lupain na ipinangako sa kanila, at sapagkat napoot siya sa kanila, ay inilabas sila upang patayin sa ilang.”
Samantalang sila'y sumasamba sa Panginoon at nag-aayuno, sinabi ng Espiritu Santo, “Ibukod ninyo para sa akin sina Bernabe at Saulo sa gawaing itinawag ko sa kanila.”
(Pupunta sa bukid ang dalawang lalaki; ang isa'y kukunin at ang isa'y iiwan.)
Sinabi ni Laban, “Hindi ganyan ang kaugalian dito sa aming lupain, na ibinibigay ang bunso bago ang panganay.
Sinabi ni Ruben sa kanila, “Huwag kayong magpadanak ng dugo. Ihulog ninyo siya sa balong ito na nasa ilang, subalit huwag ninyong pagbuhatan ng kamay;” upang siya'y kanyang mailigtas sa kanilang kamay at maibalik sa kanyang ama.
Kaya't nilalang ng Diyos ang tao ayon sa kanyang sariling larawan, ayon sa larawan ng Diyos siya nilalang. Sila'y kanyang nilalang na lalaki at babae.
at ng dalawang tanikalang lantay na ginto, pinilipit tulad ng lubid; at iyong ikakabit ang nilubid na tanikala sa enggaste.
Naging anak ni Joktan sina Almodad, Shelef, Hazar-mavet, at si Jerah,
Ito ang mga angkan ni Levi: ang angkan ng mga Libnita, ang angkan ng mga Hebronita, ang angkan ng mga Mahlita, ang angkan ng mga Musita, ang angkan ng mga Korahita. At naging anak ni Kohat si Amram.
Nang titigan ko iyon ay nakita ko ang mga hayop sa lupa na may apat na paa at mga hayop na mababangis at mga hayop na gumagapang at mga ibon sa himpapawid.
Sinabi sa kanya ni Jesus, “Kung ibig kong siya'y manatili hanggang sa ako'y dumating ay ano nga sa iyo? Sumunod ka sa akin.”
Tinawag ng lalaki ang kanyang asawa na Eva sapagkat siya ang naging ina ng lahat ng mga nabubuhay.
Igagawa mo ito ng dalawang argolyang ginto sa ilalim ng molde, sa dakong itaas ng dalawang tagiliran mo iyon gagawin; iyon ay magiging suotan ng mga pasanan upang mabuhat ito.
At agad siyang dinala ng Espiritu sa ilang.
Ang ikalimampung taon ay taon ng pagdiriwang para sa inyo, huwag kayong maghahasik ni aanihin ang tumubo sa kanyang sarili, ni titipunin ang mula sa ubasang hindi inalagaan;
At ikaw, Capernaum, itataas ka ba hanggang sa langit? Ikaw ay ibababa sa Hades.
Ang lahat na naging araw ni Kenan ay siyamnaraan at sampung taon at siya'y namatay.
Kaagad bumangon ang batang babae at nagpalakad-lakad (siya'y may labindalawang taon na). Kaagad silang namangha ng ganoon na lamang.
“Anim na araw na gagawa ka, ngunit sa ikapitong araw ay magpapahinga ka; sa panahon ng pagbubungkal at sa pag-aani ay magpapahinga ka.
Pagkatapos ay kukunin mo ang langis na pambuhos at bubuhusan mo ang tabernakulo at ang lahat na naroon, at iyong pakakabanalin, at ang lahat ng kasangkapan niyon ay magiging banal.
Kung ano ang handog pangkasalanan ay gayundin ang handog para sa budhing maysala, ang dalawa'y may iisang batas. Ang pari na gumawa ng pagtubos sa pamamagitan nito ay siyang tatanggap nito.
Ipapangilin ninyo ang aking mga Sabbath, at igagalang ninyo ang aking santuwaryo: Ako ang Panginoon .
Pagkakuha niya sa aklat, ang apat na nilalang na buháy at ang dalawampu't apat na matatanda ay nagpatirapa sa harapan ng Kordero, na ang bawat isa'y may alpa, at mga mangkok na ginto na punô ng insenso, na siyang mga panalangin ng mga banal.
“Mag-ingat ka sa salot na ketong. Masikap mong gawin ang ayon sa lahat ng ituturo sa iyo ng mga paring Levita. Kung paanong iniutos ko sa kanila ay gayon mo isasagawa.
Ilalabas niya ang toro sa kampo at susunugin ito gaya ng pagkasunog sa unang toro; ito ay handog pangkasalanan para sa kapulungan.
Subalit ang tungkol sa muling pagkabuhay ng mga patay ay ipinakita maging ni Moises sa kasaysayan tungkol sa mababang punungkahoy, na doon ay tinawag niya ang Panginoon na Diyos ni Abraham, Diyos ni Isaac, at Diyos ni Jacob.
Kung ang sinuman ay hindi manatili sa akin, siya'y itatapong katulad ng sanga at matutuyo, at sila ay titipunin at ihahagis sa apoy at masusunog.
Kaya't siya'y patuloy na nangaral sa mga sinagoga ng Judea.
Ngunit kung sawayin siya ng kanyang ama sa araw na narinig niya ito, alinman sa kanyang panata o pangako na kanyang ginawa ay hindi magkakabisa, at patatawarin siya ng Panginoon sapagkat sinaway siya ng kanyang ama.
Sapagkat kung paano sa mga araw na iyon bago bumaha, sila'y kumakain at umiinom, at nag-aasawa at pinag-aasawa, hanggang sa araw na pumasok si Noe sa barko,
Bibiyakin niya ito sa mga pakpak, ngunit hindi hahatiin. Ito'y susunugin ng pari sa ibabaw ng dambana, sa ibabaw ng kahoy na nasa apoy, bilang isang handog na sinusunog. Ito ay isang handog na pinaraan sa apoy, na isang mabangong samyo sa Panginoon .
Kaya't nang makita ni Esau na hindi nakakalugod ang mga anak ng Canaan kay Isaac na kanyang ama;
Tinanong siya ng kanyang mga alagad, na nagsasabi, “Bakit kaya sinasabi ng mga eskriba na kailangang dumating muna si Elias?”
na ang Anak ng Tao ay kailangang ibigay sa mga kamay ng mga makasalanan, at ipako sa krus, at muling mabuhay sa ikatlong araw.”
Si Jesus ay nagpatuloy sa kanyang lakad sa mga bayan at mga nayon na nagtuturo habang naglalakbay patungo sa Jerusalem.
kay Isacar: si Natanael na anak ni Suar;
Ang nalabing langis na nasa kamay ng pari ay ilalagay niya sa ulo ng taong lilinisin, upang ipantubos sa kanya sa harapan ng Panginoon .
“Huwag ninyong susubukin ang Panginoon ninyong Diyos, gaya ng pagsubok ninyo sa kanya sa Massah.
Ang hita na inialay at ang dibdib na iwinawagayway ay kanilang dadalhin kasama ng mga handog na pinaraan sa apoy, ang mga taba, ay kanilang dadalhin upang iwagayway bilang handog na iwinawagayway sa harapan ng Panginoon . Ito ay bahagi mo at ng iyong mga anak, gaya ng iniutos ng Panginoon .”
Paano ko madadalang mag-isa ang mabigat na pasan ninyo at ng inyong mga alitan?
ang mga tulos ng tabernakulo, ang mga tulos ng bulwagan, at ang mga lubid ng mga iyon;
Mayroon ding nakasulat na pamagat sa itaas niya, “Ito'y ang Hari ng mga Judio.”
Sa isang malaking bahay ay hindi lamang may mga kasangkapang ginto at pilak, kundi mayroon din namang kahoy at luwad, at ang iba'y sa natatanging paggagamitan at ang iba'y para sa karaniwan.
At ilalagay ng pari ang langis na nasa kanyang kamay sa dulo ng kanang tainga, at hinlalaki ng kanang kamay, at sa hinlalaki ng kanang paa ng taong lilinisin sa ibabaw ng pinaglagyan ng dugo ng handog para sa budhing maysala.
na sinasabi, “Ang Anak ng Tao ay kailangang magdusa ng maraming bagay at itakuwil ng matatanda at ng mga punong pari at mga eskriba, at patayin, at sa ikatlong araw ay muling bubuhayin.”
Lahat ng lumalapit sa tabernakulo ng Panginoon ay mamamatay. Kami bang lahat ay malilipol?”
Gayunma'y makikita mo ang lupain sa harapan mo, ngunit hindi ka makakapasok sa lupain na aking ibinibigay sa mga anak ni Israel.”
Ang Panginoon ay bumaba sa ibabaw ng bundok ng Sinai, sa taluktok ng bundok; at tinawag ng Panginoon si Moises sa taluktok ng bundok; at si Moises ay umakyat.
Sumampalataya kayo sa akin na ako'y nasa Ama at ang Ama ay nasa akin. Subalit kung hindi ay sumampalataya kayo sa akin dahil sa mga gawa.
Pagkaraan ng ilang mga araw, si Felix ay dumating na kasama si Drusila na kanyang asawa, na isang Judio, at ipinatawag si Pablo, at siya'y pinakinggang magsalita tungkol sa pananampalataya kay Cristo Jesus.
At ang ahas ay nagbuga mula sa kanyang bibig ng tubig sa babae na gaya ng isang ilog upang tangayin siya ng agos.
Sapagkat may tatlong nagpapatotoo:
Subalit pinagbantaan sila ng buong sambayanan na babatuhin sila ng mga bato. At ang kaluwalhatian ng Panginoon ay lumitaw sa toldang tipanan sa lahat ng mga anak ni Israel.
Sinabi niya sa kanyang pagtuturo, “Mag-ingat kayo sa mga eskriba, na ibig magpalakad-lakad na may mahahabang damit, at batiin na may paggalang sa mga pamilihan.
Kakainin mo ito sa loob ng iyong mga bayan; ang marumi at ang malinis ay kapwa kakain nito, na para itong maliit na usa o malaking usa.
tumayo si Moises sa pintuan ng kampo, at nagsabi, “Sino ang nasa panig ng Panginoon ? Lumapit kayo sa akin.” At lahat ng mga anak ni Levi ay nagtipon sa kanya.
Sapagkat kung kayo'y sumasampalataya kay Moises ay sasampalataya kayo sa akin, sapagkat siya'y sumulat tungkol sa akin.
Sumigaw siya nang malakas at sinabi, “Pinagpala ka sa mga babae, at pinagpala ang bunga ng iyong sinapupunan!
Mula sa iisang bibig ay lumalabas ang pagpupuri at panlalait. Mga kapatid ko, hindi dapat maging ganito.
Sinabi ng Panginoon kay Aaron, “Ako'y narito, ibinigay ko sa iyo ang katungkulan sa mga handog na para sa akin, lahat ng mga banal na bagay ng mga anak ni Israel. Ibinigay ko sa iyo ang mga ito bilang bahagi; at sa iyong mga anak bilang marapat na bahagi ninyo magpakailanman.
Sa ikaapat na araw ay sampung toro, dalawang lalaking tupa, labing-apat na korderong lalaki na isang taong gulang na walang kapintasan,
Pinagmamadali sila ng mga tagapangasiwa na sinasabi, “Tapusin ninyo ang inyong mga gawa, ang inyong gawain sa araw-araw na gaya nang mayroon kayong dayami.”
Ngunit upang malaman ninyo na sa lupa ay may awtoridad ang Anak ng Tao na magpatawad ng mga kasalanan,” kaya't sinabi niya sa lumpo, “Tumindig ka, buhatin mo ang iyong higaan, at umuwi ka sa bahay mo.”
Nang ito'y marinig ni Jesus, sinabi niya sa kanila, “Ang malalakas ay hindi nangangailangan ng manggagamot, kundi ang mga maysakit. Hindi ako naparito upang tawagin ang mga matuwid, kundi ang mga makasalanan.”
At marami sa kanila ang nagsasabi, “Mayroon siyang demonyo, at siya'y nauulol, bakit ninyo siya pinapakinggan?”
Itinaas ni Aaron ang kanyang mga kamay paharap sa taong-bayan at binasbasan sila. Bumaba siya pagkatapos ng paghahandog ng handog pangkasalanan, ng handog na sinusunog, at ng mga handog pangkapayapaan.
Lahat nang nakarinig sa kanya ay namangha, at nagsabi, “Hindi ba ito ang lalaking pumuksa sa Jerusalem sa mga tumatawag sa pangalang ito? At naparito siya para sa layuning ito, upang sila'y dalhing nakagapos sa harap ng mga punong pari.”
ang mga nasa Judea ay tumakas na patungo sa mga bundok.
Inyong tutuparin ang lahat ng aking mga tuntunin, at ang lahat ng aking kahatulan, at gagawin ninyo ang mga iyon: Ako ang Panginoon .”
Sapagkat sinabi ng Panginoon kay Moises, “Sabihin mo sa mga anak ni Israel, ‘Kayo'y isang bayang matigas ang ulo; kung ako'y aakyat na kasama ninyo nang sandali, ay malilipol ko kayo. Kaya't ngayo'y alisin ninyo ang inyong mga palamuti upang aking malaman kung ano ang aking gagawin sa inyo.’”
Sapagkat ang hiwaga ng kasamaan ay gumagawa na; tanging siya na sa ngayon ay pumipigil niyon ang gagawa ng gayon hanggang sa siya ay maalis.
Sapagkat ang pag-ibig sa salapi ay ugat ng lahat ng uri ng kasamaan; na ang ilang nagnasa rito ay napalayo sa pananampalataya at tinusok ang kanilang mga sarili ng maraming kalungkutan.
“Lahat ng panganay na lalaki na ipinanganak sa iyong bakahan at sa iyong kawan ay iyong itatalaga sa Panginoon mong Diyos. Huwag mong pagtatrabahuhin ang panganay ng iyong baka, ni gugupitan ang panganay ng iyong kawan.
Kaya't sina Moises at Aaron ay umalis sa harapan ni Faraon; at si Moises ay nanawagan sa Panginoon tungkol sa mga palaka na kanyang dinala kay Faraon.
“Huwag mong ipagpapaliban ang paghahandog ng mula sa iyong mga ani, at ng mula sa umagos sa iyong mga pisaan. “Ang panganay sa iyong mga anak na lalaki ay ibibigay mo sa akin.
Inilibing siya ng kanyang mga anak na sina Isaac at Ismael sa yungib ng Macpela, sa parang ni Efron na anak ni Zohar na Heteo, na nasa tapat ng Mamre,
“Bibilangin mo rin ang bilang ng mga anak ni Gershon, ayon sa mga sambahayan ng kanilang mga ninuno ayon sa kanilang mga angkan;
Magkakaroon ng labindalawang bato na may mga pangalan ayon sa mga pangalan ng anak ni Israel; magiging tulad ng mga pantatak, bawat isa'y may ukit na pangalan, na ukol sa labindalawang lipi.
At tumayo ang dragon sa buhanginan ng dagat.
Nang siya'y pinakiusapan nila na tumigil pa roon ng mas mahabang panahon, ay hindi siya pumayag,
At ang kanyang mga kapatid ay nainggit sa kanya, subalit pinag-isipan ng kanyang ama ang bagay na iyon.
Kaagad siyang lumapit kay Jesus, at sinabi, “Magandang gabi, Rabi!” at kanyang hinagkan siya.
Nang sumikat ang araw, nainitan ito at dahil sa walang ugat, ito'y natuyo.
At sila'y muling nagsigawan, “Ipako siya sa krus.”
At nakiusap kay Jesus ang lahat ng mga tao sa palibot ng lupain ng mga Gadareno na umalis na siya sa kanila, sapagkat sila'y lubhang natakot. Siya'y sumakay sa bangka at bumalik.
Kumuha sina Sem at Jafet ng isang balabal, inilagay sa balikat nilang dalawa, lumakad ng paatras, at tinakpan ang kahubaran ng kanilang ama. At ang mukha nila ay patalikod, at hindi nila nakita ang kahubaran ng kanilang ama.
Nang maipangaral na nila ang ebanghelyo sa lunsod na iyon, at ginawang mga alagad ang marami, nagbalik sila sa Listra, sa Iconio, at sa Antioquia,
Samantalang siya'y nasa Betania, sa bahay ni Simon na ketongin, habang siya'y nakaupo sa hapag-kainan, dumating ang isang babae na may dalang isang sisidlang alabastro na punô ng mamahaling pabangong purong nardo, binasag niya ang sisidlan at ibinuhos ang pabango sa kanyang ulo.
“Kapag ang lahat ng mga bagay na ito ay dumating sa iyo, ang pagpapala at ang sumpa na inilagay ko sa harapan mo, at iyong bulay-bulayin ang mga iyon sa gitna ng lahat ng mga bansa na pinagtabuyan sa iyo ng Panginoon mong Diyos
tinuli nang ikawalong araw, mula sa lahi ng Israel, mula sa lipi ni Benjamin, isang Hebreo na isinilang ng Hebreo; tungkol sa kautusan, ay Fariseo,
“At kapag kayo'y naghahandog sa Panginoon ng alay na mga handog pangkapayapaan, inyong ialay ito upang kayo'y tanggapin.
Ang balitang ito tungkol sa kanya ay kumalat sa buong Judea at sa lahat ng nakapaligid na lupain.
Nang makita ito ng mga anak ni Israel ay sinabi nila sa isa't isa, “Ano ito?” Sapagkat hindi nila alam kung ano iyon. At sinabi ni Moises sa kanila, “Ito ang tinapay na ibinigay ng Panginoon sa inyo upang kainin.
“Sa lahat ng araw ng kanyang pagbubukod ng kanyang sarili para sa Panginoon , ay hindi siya lalapit sa bangkay.
“Kung ang kanyang kaloob para sa handog na sinusunog ay mula sa kawan, sa mga tupa, o sa mga kambing, siya ay maghahandog ng isang lalaking walang kapintasan.
Ipapatong niya ang kanyang kamay sa ulo ng handog na sinusunog at ito ay tatanggapin para sa ikatutubos niya.
ang may-ari ng bahay ay lalapit sa pari at sasabihin, ‘Mayroon yatang isang uri ng sakit sa aking bahay.’
Dadaan ako sa lahat mong kawan ngayon, at aking aalisin doon ang lahat ng tupa na batik-batik at may dungis, at ang bawat maitim na tupa, at ang may dungis at batik-batik sa mga kambing, at sila ang aking magiging upa.
Nagdala nga sila ng isa at sinabi niya sa kanila, “Kaninong larawan at pangalan ang nakaukit?” Sinabi nila sa kanya, “Kay Cesar.”
na sinasabi, “Guro, sinabi ni Moises, ‘Kung mamatay ang isang tao na walang anak, pakakasalan ng kanyang kapatid na lalaki ang asawa niya, at magkakaroon ng mga anak para sa kanyang kapatid na lalaki.’
Ang nagsisikap magligtas ng kanyang buhay ay mawawalan nito; at ang mawalan ng kanyang buhay dahil sa akin ay makakatagpo nito.
Sinagot sila ni Jesus, “Ngayon ba ay sumasampalataya na kayo?
Sinabi ng Panginoon kay Moises, “Bakit tumatawag ka sa akin? Sabihin mo sa mga anak ni Israel na sila'y magpatuloy.
Nabuhay si Arfaxad ng apatnaraan at tatlong taon pagkatapos na maipanganak si Shela, at nagkaanak pa ng mga lalaki at mga babae.
Kaya't tumingin si Abraham, at nakita niya ang isang tupang lalaki sa likuran niya na ang mga sungay ay sumabit sa mga tinik. Lumapit si Abraham at kinuha ang tupa, at siyang inialay na handog na susunugin kapalit ng kanyang anak.
Ngunit kung tayo'y lumalakad sa liwanag, na tulad niya na nasa liwanag, may pakikisama tayo sa isa't isa, at ang dugo ni Jesus na kanyang Anak ang lumilinis sa atin sa lahat ng kasalanan.
Ngunit siya'y hindi Diyos ng mga patay, kundi ng mga buháy, sapagkat sa kanya silang lahat ay nabubuhay.”
Kaya't sinabi ng mga Judio sa isa't isa, “Saan pupunta ang taong ito na hindi natin siya matatagpuan? Pupunta kaya siya sa mga lupain kung saan nagkalat ang ating mga kababayan sa lupain ng mga Griyego at magtuturo sa mga Griyego?
Sinabi niya kay Sara, “Tingnan mo, nagbigay ako ng isang libong pirasong pilak sa iyong kapatid. Ito'y magpapawalang-sala sa iyo sa paningin ng lahat ng kasama mo; ikaw ay ganap na napawalang-sala.”
Ngunit sinasabi ko sa inyo, Ibigin ninyo ang inyong mga kaaway, at idalangin ninyo ang umuusig sa inyo,
Pagkatapos ay sasabihin ng Hari sa mga nasa kanyang kanan, ‘Halikayo, mga pinagpala ng aking Ama, manahin ninyo ang kahariang inihanda para sa inyo mula sa pagkatatag ng sanlibutan.
Sapagkat may apoy na nag-aalab sa aking galit, at nagniningas hanggang sa Sheol, at lalamunin ang lupa pati ang tubo nito, at pag-aapuyin ang saligan ng mga bundok.
At ang natira sa mga tao na hindi napatay sa mga salot na ito ay hindi nagsisi sa mga gawa ng kanilang mga kamay ni inihinto ang pagsamba sa mga demonyo at sa mga diyus-diyosang ginto, pilak, tanso, bato, at kahoy na hindi nakakakita, ni nakakarinig, ni nakakalakad man.
Apat na kariton at walong baka ang kanyang ibinigay sa mga anak ni Merari, ayon sa kanilang paglilingkod, sa ilalim ng pamamahala ni Itamar na anak ng paring si Aaron.
Alalahanin ninyo ang mga namumuno sa inyo, silang nagsalita sa inyo ng salita ng Diyos; tingnan ninyo ang kinalabasan ng kanilang pamumuhay, tularan ninyo ang kanilang pananampalataya.
Gayundin naman ang mga punong pari, kasama ng mga eskriba ay nilibak siya na sinasabi sa isa't isa, “Iniligtas niya ang iba; hindi niya mailigtas ang kanyang sarili.
Umalis si Felipe at sinabi kay Andres. Sumama si Andres kay Felipe, at kanilang sinabi kay Jesus.
Si Moises ay sumagot at nagsabi, “Ngunit hindi nila ako papaniwalaan o papakinggan man sapagkat kanilang sasabihin, ‘Ang Panginoon ay hindi nagpakita sa iyo.’”
Umahon ka sa taluktok ng Pisga at igala mo ang iyong paningin sa dakong kanluran, sa hilaga, sa timog, at sa silangan, at masdan mo sapagkat hindi ka makatatawid sa Jordang ito.
Nang makaraan ang may isang oras, may isa pa na nagpipilit na nagsasabi, “Tiyak na ang taong ito'y kasama rin niya, sapagkat siya'y taga-Galilea.”
Ang Panginoon ay nagpakita kay Abraham sa may punong ensina ni Mamre habang siya'y nakaupo nang kainitan ang araw sa pintuan ng tolda.
Mula ngayon ay huwag lalapit ang mga anak ni Israel sa toldang tipanan, baka sila'y magtaglay ng kasalanan, at mamatay.
Nasusulat sa mga propeta, ‘At tuturuan silang lahat ng Diyos.’ Ang bawat nakarinig at natuto sa Ama ay lumalapit sa akin.
At naghandog si Jacob ng handog sa bundok, at tinawag ang kanyang mga kamag-anak upang kumain ng tinapay; at sila'y kumain ng tinapay, at nanatili sa bundok.
Muli niyang sinabi sa kanila, “Aalis ako, at ako'y inyong hahanapin, at mamamatay kayo sa inyong kasalanan. Sa aking pupuntahan ay hindi kayo makakapunta.”
At ang mga tandang ito ay tataglayin ng mga nananampalataya: sa paggamit ng aking pangalan ay magpapalayas sila ng mga demonyo, magsasalita sila ng mga bagong wika;
At kanila ngang tinawag si Rebecca at kanilang sinabi sa kanya, “Sasama ka ba sa lalaking ito?” At sinabi niya, “Sasama ako.”
Sa halip, ang bagong alak ay dapat ilagay sa mga bagong sisidlang balat.
Sinabi sa kanya ng Diyos sa panaginip, “Oo, nalalaman ko na sa katapatan ng iyong puso ay ginawa mo ito, at hinadlangan din naman kita na magkasala ng laban sa akin kaya't hindi ko ipinahintulot na galawin mo siya.
Bawat panata o bawat pananagutan na pinagtibay ng sumpa, na makapagpapahirap ng sarili, ay mabibigyang bisa ng kanyang asawa, o mapawawalang bisa ng kanyang asawa.
(Iyon ay kilala rin na lupain ng mga Refaim: ang mga Refaim ang nanirahan doon noong una, ngunit sila ay tinawag na mga Zamzumim ng mga Ammonita,
Sapagkat hindi ang mga tagapakinig ng kautusan ang siyang ganap sa harapan ng Diyos, kundi ang tumutupad sa kautusan ay aariing-ganap.
Nang si Esau ay apatnapung taong gulang, siya ay nag-asawa kay Judith na anak ni Beeri na Heteo, at kay Basemat na anak ni Elon na Heteo.
Siya'y inalipusta ng mga nagdaraan at pailing-iling,
Sa ganitong paraan lamang kami papayag: kung kayo'y magiging gaya namin, na ang lahat ng lalaki sa inyo ay tuliin.
Hinampas nila ang kanyang ulo ng isang tungkod, dinuraan siya at lumuhod sa harapan niya.
Maging si Simon mismo ay naniwala at pagkatapos mabautismuhan, nanatili siyang kasama ni Felipe. Namangha siya nang makakita ng mga tanda at ng mga dakilang himalang ginawa.
upang silang lahat ay maging isa. Gaya mo, Ama, na nasa akin at ako'y sa iyo, sana sila'y manatili sa atin, upang ang sanlibutan ay sumampalataya na ako'y sinugo mo.
na doon ay sinubok ako ng inyong mga ninuno, bagaman nakita nila ang aking mga gawa sa loob ng
Subalit aking papatigasin ang puso ni Faraon at aking pararamihin ang aking mga tanda at mga kababalaghan sa lupain ng Ehipto.
Si Eleazar na anak ng paring si Aaron ay siyang magiging pinuno ng mga pinuno ng mga Levita at mamamahala sa mga may tungkulin sa santuwaryo.
Nakikiusap ako kina Euodias at Sintique, na magkaisa sila ng pag-iisip sa Panginoon.
Ang may pandinig ay makinig sa sinasabi ng Espiritu sa mga iglesya.
Ngunit kung sawayin siya ng kanyang asawa sa araw na marinig iyon, mawawalan ng kabuluhan ang kanyang panata at ang binitiwang pangako ng kanyang mga labi na doo'y itinali niya ang kanyang sarili, at patatawarin siya ng Panginoon .
Tingnan ninyo kung ano ang lupain, at ang mga taong naninirahan doon, kung sila'y malakas o mahina, kung sila'y kaunti o marami;
Sa halip, hindi ba niya sasabihin sa kanya, ‘Ipaghanda mo ako ng hapunan, magbigkis ka, paglingkuran mo ako, hanggang sa ako'y makakain at makainom, pagkatapos ay kumain ka at uminom’?
At nang makita ito nina Santiago at Juan na kanyang mga alagad ay sinabi nila, “Panginoon, ibig mo bang kami ay magpababa ng apoy mula sa langit upang sila'y tupukin?”
Mga anak, huling oras na! Gaya ng inyong narinig na darating ang anti-Cristo, kahit ngayon ay lumitaw na ang maraming anti-Cristo. Kaya nalalaman nating huling oras na.
Ngunit nang dumating sila kay Jesus at makitang patay na, ay hindi na nila binali ang kanyang mga binti.
At siya'y nagsalita ng talinghaga, na sinasabi: “Sinong mabubuhay kapag ginawa ito ng Diyos?
Ngunit sa pamamagitan ng gayunding salita ang kasalukuyang langit at lupa ay iningatan para sa apoy, na inilalaan sa araw ng paghuhukom at sa paglipol sa masasamang tao.
Kanyang isinuot ang mga pasanan sa mga argolya na nasa mga tagiliran ng dambana, upang mabuhat iyon; ginawa niya itong may guwang na may mga tabla.
Nang sila'y dumating kay Reuel na kanilang ama ay sinabi nito, “Bakit napakadali ninyong dumating ngayon?”
sapagkat sinabi niya sa kanyang sarili, “Kung mahihipo ko lamang ang kanyang damit ay gagaling ako.”
Iisa ang tagapagbigay ng kautusan at hukom, siya na may kapangyarihang magligtas at pumuksa. Kaya, sino ka na humahatol sa iyong kapwa?
Iniligtas niya tayo sa kapangyarihan ng kadiliman at inilipat tayo sa kaharian ng kanyang minamahal na Anak,
Nang oras na iyon ay pinagaling ni Jesus ang marami sa mga sakit, salot at masasamang espiritu, at ang maraming bulag ay binigyan niya ng paningin.
Sabihin mo nga sa amin, ano sa palagay mo? Matuwid bang magbuwis kay Cesar, o hindi?”
Pagkatapos ng mga bagay na ito, si Jose na taga-Arimatea, na isang lihim na alagad ni Jesus, dahil sa takot sa mga Judio, ay nakiusap kay Pilato na makuha niya ang bangkay ni Jesus, at siya'y pinahintulutan ni Pilato. Kaya't siya'y pumunta roon at kinuha ang kanyang bangkay.
Kaya siya'y nagpahanda ng maraming pagkain para sa kanila, at sila'y kumain at uminom.
Ang mga lunsod na inyong ibibigay ay ang inyong anim na lunsod-kanlungan.
Suguin ninyo ang isa sa inyo at dalhin dito ang inyong kapatid, habang kayo ay nasa bilangguan upang masubok ang inyong mga salita, kung may katotohanan sa inyo; at kung wala, kung paanong nabubuhay ang Faraon, ay tunay na mga espiya nga kayo.”
Nang marinig ni Pilato ang salitang ito ay lalo siyang natakot.
Sinabi niya, “Katotohanang sinasabi ko sa inyo, malibang kayo'y magbago at maging tulad sa mga bata, kailanma'y hindi kayo makakapasok sa kaharian ng langit.
Sinabi ni Agripa kay Pablo, “May pahintulot kang magsalita para sa iyong sarili.” Iniunat ni Pablo ang kanyang kamay at ginawa ang kanyang pagtatanggol:
Bukod sa mga bagay na nasa labas, ako'y araw-araw na nabibigatan sa alalahanin para sa mga iglesya.
At kung kayo'y kay Cristo, kayo nga'y mga binhi ni Abraham, mga tagapagmana ayon sa pangako.
Habang papaalis na ang mga ito, nagpasimulang magsalita si Jesus sa maraming tao tungkol kay Juan: “Ano ang pinuntahan ninyo sa ilang upang makita? Isa bang tambo na inuuga ng hangin?
Purihin nawa ang Diyos at Ama ng ating Panginoong Jesu-Cristo, na siyang nagpapala sa atin kay Cristo ng bawat pagpapalang espirituwal sa sangkalangitan,
na nagbigay ng kanyang sarili dahil sa ating mga kasalanan, upang tayo'y kanyang mailigtas mula sa kasalukuyang masamang kapanahunan, ayon sa kalooban ng ating Diyos at Ama,
at siya rin namang sa amin ay nagpahayag ng inyong pag-ibig sa Espiritu.
Magsisimula ba kaming muli na purihin ang aming sarili? O kailangan ba namin, gaya ng iba, ng mga sulat ng papuri sa inyo, o mula sa inyo?
Subalit sinabi nila, “Ang amin bang kapatid ay ituturing na parang isang masamang babae?”
Batiin ninyo si Filologo at si Julia, si Nereo at ang kanyang kapatid na babae, at si Olimpas, at ang lahat ng mga banal na kasama nila.
Kanilang ipinangilin ang paskuwa nang ikalabing-apat na araw ng unang buwan, sa paglubog ng araw, sa ilang ng Sinai. Ayon sa lahat ng iniutos ng Panginoon kay Moises ay gayon ginawa ng mga anak ni Israel.
Pagkatapos ng mga bagay na ito, pumunta si Jesus sa kabilang pampang ng dagat ng Galilea, na siya ring Dagat ng Tiberias.
“Huwag kayong humatol at hindi kayo hahatulan. Huwag kayong humusga at hindi kayo huhusgahan. Magpatawad kayo at kayo'y patatawarin.
At sinabi niya sa kanila, “Tama ang pahayag ni Isaias tungkol sa inyo na mga mapagkunwari, ayon sa nasusulat, ‘Iginagalang ako ng bayang ito ng kanilang mga labi, subalit ang kanilang puso ay malayo sa akin.
Kaya't hindi nakapagpigil si Jose sa harapan ng mga nakatayo sa tabi niya, at siya ay sumigaw, “Paalisin ninyo ang lahat ng tao sa aking harapan.” Kaya't walang taong nakatayo sa harapan niya nang si Jose ay magpakilala sa kanyang mga kapatid.
Nakita ng Diyos na ang daigdig ay naging masama sapagkat pinasama ng lahat ng tao ang kanilang gawa sa lupa.
Ang mga nagkawatak-watak ay naglakbay na ipinangangaral ang salita.
At sinabi ng Panginoon , “Ang aking Espiritu ay hindi laging mananatili sa tao, sapagkat siya'y laman. Subalit ang kanyang mga araw ay magiging isandaan at dalawampung taon.”
At tumakbo si Esau upang salubungin siya, niyakap siya, niyapos siya sa leeg, hinagkan at sila ay nag-iyakan.
At siya'y binigyan niya ng kapangyarihang humatol sapagkat siya'y Anak ng Tao.
Iyong sasabihin sa Faraon, ‘Ganito ang sabi ng Panginoon , ang Israel ang aking panganay na anak,
Samantalang sila'y kumakain, dumampot siya ng tinapay, at nang kanyang mabasbasan ay kanyang pinagputul-putol, ibinigay sa kanila at sinabi, “Kunin ninyo; ito ang aking katawan.”
Huwag mong ipatong na madalian ang iyong mga kamay sa kanino man, ni huwag kang makiisa sa mga kasalanan ng iba; panatilihin mong malinis ang iyong sarili.
“Kung ang isang tao ay magnakaw ng isang baka, o ng tupa at patayin, o ipagbili, siya'y magbabayad ng limang baka para sa isang baka, at ng apat na tupa para sa isang tupa. Ang magnanakaw ay gagawa ng pagsasauli; kung wala siyang maisauli, siya'y ipagbibili dahil sa kanyang pagnanakaw.
Umakyat nga si Moises sa bundok at tinakpan ng ulap ang bundok.
“Hindi, panginoon ko, pakinggan mo ako. Ang parang ay ibinibigay ko sa iyo, at ang yungib na naroroon ay ibinibigay ko sa iyo. Sa harapan ng mga anak ng aking bayan ay ibinibigay ko sa iyo, ilibing mo ang iyong patay.”
Maging kanino man ito matagpuan sa iyong mga lingkod, siya ay mamatay, at pati kami ay magiging alipin ng aming panginoon.”
Ngunit kapag pumuti ang lamang buháy, ay lalapit siya sa pari;
Nang magkagayo'y sinabi ng mga salamangkero sa Faraon, “Ito ay daliri ng Diyos.” Ngunit ang puso ni Faraon ay nagmatigas at hindi niya pinakinggan sila, gaya nang sinabi ng Panginoon .
Ngunit kung ang baka ay dati nang nanunuwag at naisumbong na sa may-ari ngunit hindi niya ikinulong, anupa't nakamatay ng isang lalaki, o isang babae, babatuhin ang baka at ang may-ari niyon ay papatayin din.
upang hindi na nila iaalay ang kanilang mga alay sa mga demonyong kambing na sanhi ng kanilang pagtataksil. Ito ay magiging alituntunin magpakailanman sa kanila sa buong panahon ng kanilang salinlahi.
At nalalaman ko na ang taong iyon (kung nasa katawan man, o nasa labas ng katawan, hindi ko alam; ang Diyos ang nakakaalam),
Kaya't magsalita kayo at kumilos na gaya ng mga taong hahatulan sa pamamagitan ng kautusan ng kalayaan.
Kaya't kinabukasan, dumating si Agripa at si Bernice na may buong karilagan. Nang pumasok na sila sa bulwagan ng hukuman kasama ang mga punong kapitan at ang mga pangunahin sa bayan, ipinasok si Pablo sa utos ni Festo.
Ang bayan ay nagsalita laban sa Diyos at laban kay Moises, “Bakit ninyo kami iniahon mula sa Ehipto, upang mamatay sa ilang? Sapagkat walang pagkain at walang tubig at ang kaluluwa namin ay nasusuya na sa walang kuwentang pagkaing ito.”
Alalahanin mo ang ginawa ng Panginoon mong Diyos kay Miriam sa daan nang kayo'y lumalabas sa Ehipto.
Tungkol sa ebanghelyo, sila'y mga kaaway alang-alang sa inyo; subalit tungkol sa paghirang, sila'y mga minamahal alang-alang sa mga ninuno.
Tinipon ni Moises ang buong sambayanan ng mga anak ni Israel, at sinabi sa kanila, “Ito ang mga salita na iniutos ng Panginoon na inyong gagawin.
Sapagkat pinagsisikapan nilang lahat ang para sa kanilang sariling kapakanan, hindi ang mga bagay ni Jesu-Cristo.
Ang mga anak ni Merari ayon sa kanilang mga angkan ay sina Mahli at Musi. Ito ang mga angkan ng mga Levita ayon sa mga sambahayan ng kanilang mga ninuno.
Kaya't sinabi ng ilan sa mga Fariseo, “Ang taong ito'y hindi mula sa Diyos, sapagkat hindi siya nangingilin ng Sabbath.” Subalit sinabi ng iba, “Paanong makakagawa ng gayong mga tanda ang isang taong makasalanan?” At nagkaroon ng pagkakahati-hati sa kanila.
Nang siya'y naghihirap sa panganganak, sinabi sa kanya ng hilot, “Huwag kang matakot, sapagkat magkakaroon ka ng isa pang anak na lalaki.”
Kaya nga, tayong nasa hustong gulang ay magkaroon ng parehong kaisipan; at kung iba ang inyong iniisip tungkol sa anumang bagay, ito rin ay ipahahayag sa inyo ng Diyos.
hindi ako tumitigil ng pagpapasalamat para sa inyo, na binabanggit kayo sa aking mga panalangin,
Siya lamang ang walang kamatayan at naninirahan sa liwanag na di-malapitan; na hindi nakita ng sinumang tao, o makikita man. Sumakanya nawa ang karangalan at paghaharing walang hanggan. Amen.
Sinabi nila sa kanya, “Ano ang ginawa niya sa iyo? Paano niya binuksan ang iyong mga mata?”
Kanilang tatawagin ang mga bayan sa bundok; maghahandog sila ng mga matuwid na alay; sapagkat kanilang sisipsipin ang mga kasaganaan ng mga dagat, at ang natatagong kayamanan sa buhanginan.”
Pagtawid mo sa Jordan, ilalagay ninyo ang mga batong ito na iniuutos ko sa iyo sa araw na ito, sa bundok ng Ebal at iyong tatapalan ng plaster.
at iyong bibigkisan ng mga pamigkis si Aaron at ang kanyang mga anak, at itatali mo ang mga turbante sa kanilang ulo, at mapapasakanila ang pagkapari sa pamamagitan ng isang panghabam-panahong batas. Gayon mo itatalaga si Aaron at ang kanyang mga anak.
at makakakita ka sa mga bihag ng isang magandang babae at magkaroon ka ng pagnanais na kunin siya para sa iyo bilang asawa,
At ang mga naninirahan sa ibabaw ng lupa ay magagalak tungkol sa kanila at magkakatuwa, at sila'y magpapalitan ng mga handog, sapagkat ang dalawang propetang ito ay nagpahirap sa mga naninirahan sa ibabaw ng lupa.
At muling ipinagkaila niya ito nang may panunumpa, “Hindi ko kilala ang taong iyon.”
At huwag din ninyong ihandog ang mga bahagi ng inyong katawan sa kasalanan bilang kasangkapan ng kasamaan tungo sa kasalanan, kundi ihandog ninyo ang inyong sarili sa Diyos, na tulad sa mga buháy mula sa mga patay, at ang mga bahagi ng inyong katawan bilang kasangkapan ng pagiging matuwid tungo sa Diyos.
at nang hindi nila matagpuan ang kanyang bangkay, sila ay bumalik. Sinabi nilang sila ay nakakita ng isang pangitain ng mga anghel na nagsabing siya'y buháy.
Ang mga anak ni Zebulon: sina Sered, Elon, at si Jalel
Lumapit ang pinunong kapitan at tinanong si Pablo, “Sabihin mo sa akin, ikaw ba'y mamamayang Romano?” At sinabi niya, “Oo.”
sila'y hahawak ng mga ahas, at kung makainom sila ng bagay na nakamamatay, hindi ito makakasama sa kanila, ipapatong nila ang kanilang mga kamay sa mga maysakit, at sila'y gagaling.”
Ang lahat na nakapaghandog ng handog na pilak at tanso ay nagdala ng handog sa Panginoon at lahat ng taong may kahoy na akasya na magagamit sa anumang gawain ay nagdala nito.
At ang watawat ng kampo ng mga anak ni Dan na siyang nasa hulihan ng lahat ng mga kampo ay lumakad ayon sa kanilang mga pangkat at nangunguna sa kanyang hukbo si Ahiezer na anak ni Amisadai.
Sinabi ni Moises sa bayan, “Huwag kayong matakot, magpakatatag kayo, at masdan ninyo ang pagliligtas ng Panginoon na kanyang gagawin sa inyo ngayon; sapagkat ang mga Ehipcio na inyong nakikita ngayon ay hindi na ninyo muling makikita kailanman.
Nang makita ni Jose na ipinatong ng kanyang ama ang kanyang kanang kamay sa ulo ni Efraim, ito ay naging masama sa kanyang paningin. Kaya't hinawakan niya ang kamay ng kanyang ama upang ilipat mula sa ulo ni Efraim tungo sa ulo ni Manases.
Aking binabalaan ang mga nagkasala noong una at lahat ng iba pa, at binabalaan ko sila ngayon habang wala pa, gaya ng ginawa ko nang ako'y kaharap sa ikalawa kong pagdalaw, na kapag ako'y muling dumating, sila ay hindi ko na pagbibigyan.
Sinu-sino ba sila na matapos makarinig ay naghimagsik? Hindi ba ang lahat ng umalis sa Ehipto sa pamamagitan ni Moises?
Makakalaya ka sa aking sumpa, kapag ikaw ay dumating sa aking mga kamag-anak; kahit hindi nila ibigay sa iyo ang babae ay makakalaya ka sa aking sumpa.’
Sapagkat kung ang mga bagay na ito ay nasa inyo at dumarami, hindi kayo magiging mga walang saysay o mga walang bunga sa pagkakilala sa ating Panginoong Jesu-Cristo.
“At ngayon, O Israel, pakinggan mo ang mga tuntunin at ang mga batas, na aking itinuturo at inyong gawin ang mga ito upang kayo'y mabuhay, at pumasok at angkinin ang lupaing ibinibigay sa inyo ng Panginoong Diyos ng inyong mga ninuno.
Sinasabi ng kanyang mga alagad, “Oo nga, ngayo'y nagsasalita kang malinaw, at hindi patalinghaga.
Anim na araw na kakain ka ng tinapay na walang pampaalsa, at sa ikapitong araw ay magiging isang taimtim na pagtitipon sa Panginoon mong Diyos; huwag kang gagawa ng anumang gawa sa araw na iyan.
“Kayo'y yaong patuloy na kasama ko sa mga pagsubok sa akin.
Sapagkat ang Anak ng Tao ay panginoon ng Sabbath.”
Sa gayon, si Jesus ay naging tagapanagot ng isang higit na mabuting tipan.
Sapagkat sinasabi nila, “Ang kanyang mga sulat ay mabibigat at matitindi; subalit ang anyo ng kanyang katawan ay mahina, at ang kanyang pananalita ay walang kabuluhan.”
Nagturo siya araw-araw sa templo. Ngunit pinagsisikapan ng mga punong pari, ng mga eskriba, at ng mga pinuno ng bayan na siya'y patayin.
at umalis at naglingkod sa ibang mga diyos, at sumamba sa kanila, o sa araw, sa buwan, o sa anumang bagay na nasa langit na ipinagbabawal ko,
Sa pinakauna sa inyong masang harina ay magbibigay kayo sa Panginoon ng isang handog sa buong panahon ng inyong mga salinlahi.
Samantalang naguguluhan si Pedro sa kanyang sarili, kung ano ang kahulugan ng pangitaing kanyang nakita, biglang dumating ang mga taong sinugo ni Cornelio. Nang maipagtanong ang bahay ni Simon, tumayo sila sa harapan ng pintuan.
Sapagkat, “Ang lahat ng tumatawag sa pangalan ng Panginoon ay maliligtas.”
Sa halip, ay ang panloob na pagkatao na may kagandahang walang paglipas, ng isang mahinhin at maamong espiritu na napakahalaga sa paningin ng Diyos.
Tingnan ninyo ang aking mga kamay at mga paa, sapagkat ako nga ito. Hipuin ninyo ako, at tingnan, sapagkat ang isang espiritu'y walang laman at mga buto, na gaya ng inyong nakikita na nasa akin.” [
Kung hindi ako dumating at nagsalita sa kanila ay hindi sana sila nagkasala. Subalit ngayo'y wala na silang maidadahilan sa kanilang kasalanan.
Ginawa nga ni Balak ang sinabi ni Balaam. Sina Balak at Balaam ay naghandog sa bawat dambana ng isang toro at isang lalaking tupa.
Nang dumating ang oras ay naupo siya sa hapag, at ang mga apostol ay kasama niya.
At kanyang papatayin ang toro sa harapan ng Panginoon ; ang dugo ay ihahandog ng mga anak ni Aaron, na mga pari, at iwiwisik ito sa palibot ng dambana na nasa pintuan ng toldang tipanan.
“At sa anghel ng iglesya sa Sardis ay isulat mo: Ang mga bagay na ito ay sinasabi ng may pitong Espiritu ng Diyos at may pitong bituin: “Alam ko ang iyong mga gawa, sa pangalan ikaw ay nabubuhay, ngunit ikaw ay patay.
Inilabas kami ng Panginoon sa Ehipto ng kamay na makapangyarihan, ng unat na bisig, ng malaking pagkasindak, ng mga tanda, at ng mga kababalaghan;
na ipahayag ang kanyang Anak sa akin, upang siya'y aking ipangaral sa mga Hentil; hindi ako sumangguni sa sinumang laman at dugo;
Ngunit ang babae palibhasa'y nalalaman ang nangyari sa kanya ay lumapit na natatakot at nanginginig, nagpatirapa sa harap niya, at sinabi sa kanya ang buong katotohanan.
“‘Huwag kang gagawa para sa iyo ng larawang inanyuan na kawangis ng anumang nasa itaas sa langit, o ng nasa ibaba sa lupa, o ng nasa tubig sa ilalim ng lupa.
Ito ang mga pangalan ng mga anak ni Esau: si Elifaz, na anak ni Ada na asawa ni Esau, si Reuel na anak ni Basemat, na asawa ni Esau.
tuwing hahatulan tayo ng ating puso; sapagkat ang Diyos ay higit na dakila kaysa ating puso, at nalalaman niya ang lahat ng mga bagay.
na dapat ninyong maalala ang mga salitang ipinahayag noong una ng mga banal na propeta, at ang utos ng Panginoon at Tagapagligtas sa pamamagitan ng inyong mga apostol!
Ang mga naging araw ni Adan pagkatapos na maipanganak si Set ay walong daang taon; at nagkaanak pa siya ng mga lalaki at mga babae.
Sapagkat ang kautusan ng Espiritu ng buhay na na kay Cristo Jesus ay nagpalaya sa atin mula sa kautusan ng kasalanan at ng kamatayan.
Ang lupa mismo ang nagpapasibol sa halaman, una ang usbong, saka ang uhay, pagkatapos ay ang uhay na hitik sa butil.
Natagpuan niya roon ang isang Judio na ang pangalan ay Aquila, isang lalaking tubong Ponto, na kararating pa lamang mula sa Italia, kasama si Priscila na kanyang asawa, sapagkat ipinag-utos ni Claudio na ang lahat ng Judio ay umalis sa Roma. Pumunta si Pablo sa kanila;
mga taksil, matitigas ang ulo, mga palalo, mga maibigin sa kalayawan sa halip na mga maibigin sa Diyos;
Ang haba ng bawat tabing ay tatlumpung siko, at apat na siko ang luwang ng bawat tabing; ang labing-isang tabing ay magkakapareho ng sukat.
Susuguin ko sa inyo ang maiilap na hayop sa parang, at aagawan kayo nito ng inyong mga anak. At papatayin ko ang inyong mga hayop, at gagawin kayong iilan, at ang inyong mga lansangan ay mawawalan ng mga tao.
gayundin si Santiago at si Juan, mga anak ni Zebedeo, na mga kasamahan ni Simon. At sinabi ni Jesus kay Simon, “Huwag kang matakot, mula ngayon ay mamamalakaya ka ng mga tao.”
Ang Diyos ba ay nagbibigay sa inyo ng Espiritu at gumagawa ng mga himala sa gitna ninyo sa pamamagitan ng inyong pagtupad sa mga gawa ng kautusan, o sa pakikinig sa pananampalataya?
at natutulog at bumabangon siya sa gabi at araw. Sumisibol at lumalaki ang binhi na hindi niya nalalaman kung paano.
At sinabi nila sa buong kapulungan ng mga anak ni Israel, “Ang lupain na aming pinuntahan upang lihim na siyasatin ay isang napakagandang lupain.
Kaya't iniwan niya ang Faraon at nakiusap sa Panginoon .
Kaya't sinabi ni Jose sa Faraon, “Ang panaginip ng Faraon ay iisa; ipinakita ng Diyos sa Faraon ang malapit na niyang gawin.
isang kambing na lalaki na handog pangkasalanan, bukod pa sa handog pangkasalanan na pantubos at sa palagiang handog na sinusunog, at sa handog na butil, at sa mga inuming handog ng mga iyon.
Ang mga anak ni Israel ay pumasok sa gitna ng dagat sa ibabaw ng tuyong lupa, ang tubig ay naging isang pader sa kanila, sa kanilang gawing kanan at sa kanilang kaliwa.
Kaya't pagdating ng panginoon ng ubasan, ano kaya ang gagawin niya sa mga magsasakang iyon?”
Muli siyang naghintay ng pitong araw, at pinalipad ang kalapati at ito ay hindi na muling nagbalik sa kanya.
Naglagay ang Panginoong Diyos ng isang halamanan sa silangan ng Eden, at inilagay niya roon ang taong kanyang nilalang.
Kung ang iyong kapatid ay malayo sa iyo o kung hindi mo siya kilala, iuuwi mo ito sa iyong bahay at mananatili sa iyo hanggang sa hanapin ng may-ari, at kung gayo'y isasauli mo sa kanya.
Sapagkat mula sa kanya, at sa pamamagitan niya, at para sa kanya ang lahat ng mga bagay. Sumakanya nawa ang kaluwalhatian magpakailanman. Amen.
Makinig ka! Ako'y nakatayo sa may pintuan at tumutuktok; kung diringgin ng sinuman ang aking tinig at buksan ang pinto, ako'y papasok sa kanya, at kakaing kasalo niya, at siya'y kasalo ko.
“Kaya nga,” sinabi niya, “ang mga lalaking may awtoridad sa inyo ay sumama sa akin, at kung may anumang pagkakasala ang taong ito, magharap sila ng sakdal laban sa kanya.”
upang kayo'y lumakad nang nararapat sa Panginoon, na lubos na nakakalugod sa kanya, namumunga sa bawat gawang mabuti, at lumalago sa pagkakilala sa Diyos.
Ang inyong pagsunod ay naging bantog sa lahat ng mga tao, kaya't nagagalak ako tungkol sa inyo. Ngunit nais kong kayo'y maging marurunong sa kabutihan, at walang sala tungkol sa kasamaan.
Kayo'y inibig at pinili ng Panginoon hindi dahil sa kayo'y mas marami kaysa alinmang bayan ni sapagkat kayo ang pinakakaunti sa lahat ng mga tao;
Nang lumalaki ang kaguluhan, sa takot ng pinunong kapitan na baka lurayin nila si Pablo, ay pinababa ang mga kawal, sapilitang ipinakuha siya at siya'y ipinasok sa himpilan.
Ngunit si Jesus ay hindi sumagot ng anuman, anupa't nanggilalas si Pilato.
At nangyari, nang gunawin ng Diyos ang mga lunsod ng libis, naalala ng Diyos si Abraham, at inilabas si Lot nang gunawin ang mga lunsod na tinirahan niya.
At siya'y lumabas, at umiyak nang buong pait.
kay Aser: si Fegiel na anak ni Ocran;
Sapagkat, “Ang lahat ng laman ay gaya ng damo, at ang lahat ng kaluwalhatian nito ay gaya ng bulaklak ng damo. Ang damo'y natutuyo, at ang bulaklak ay nalalanta,
Subalit kung sabihin ng alipin iyon sa kanyang sarili, ‘Matatagalan pa ang pagdating ng aking panginoon;’ at pinasimulan niyang bugbugin ang mga aliping lalaki at mga aliping babae; at siya'y kumain, uminom, at naglasing,
Siya'y muling nagsugo sa kanila ng isa pang alipin at ito'y kanilang pinalo sa ulo at nilait.
At kung hindi paiikliin ang mga araw na iyon, ay walang makakaligtas na laman, subalit alang-alang sa mga hinirang ay paiikliin ang mga araw na iyon.
Nang sumbatan ni Abraham si Abimelec dahil sa isang balon ng tubig na sinamsam sa kanya ng mga tauhan ni Abimelec,
Ang matatanda ng Moab at Midian ay pumaroon na dala sa kanilang kamay ang mga upa para sa panghuhula; at sila'y dumating kay Balaam at sinabi nila sa kanya ang mga sinabi ni Balak.
At sinabi sa kanya ni Jesus, “Dumating sa bahay na ito ngayon ang kaligtasan, sapagkat siya man ay anak din ni Abraham.
Pagkaraan ng walong araw ay muling nasa loob ng bahay ang kanyang mga alagad, at kasama nila si Tomas. Nakasara ang mga pinto, subalit pumasok si Jesus, at tumayo sa gitna, at sinabi, “Kapayapaan ang sumainyo.”
“Kung mayroong sinumang lalaki sa inyo na hindi malinis dahil sa anumang nangyari sa kanya sa kinagabihan, lalabas siya sa kampo; hindi siya papasok sa loob ng kampo.
sina Patrusim, at Casluim na siyang pinagmulan ng mga Filisteo, at ang Caftoreo.
Hindi gaya ng ibang mga pinakapunong pari, hindi niya kailangang maghandog ng alay araw-araw, una para sa kanyang sariling mga kasalanan, at saka para sa mga kasalanan ng bayan; ito'y ginawa niyang minsan magpakailanman nang kanyang ihandog ang kanyang sarili.
Kaya't bumalik si Moises sa Panginoon , at sinabi, “O, ang bayang ito'y nagkasala ng malaking kasalanan; at gumawa sila para sa kanilang sarili ng mga diyos na ginto.
Nang marinig nila ang mga bagay na ito, sila ay nagalit at nagngalit ang kanilang mga ngipin laban kay Esteban.
Sila'y umupo sa harapan niya, ang panganay ayon sa kanyang pagkapanganay, at ang bunso ayon sa kanyang pagkabunso. At ang mga lalaki ay nagtinginan sa isa't isa na may pagkamangha.
upang ikaw ay matakot sa Panginoon mong Diyos, na iyong ingatan ang lahat niyang mga tuntunin at ang kanyang mga utos na aking iniutos sa iyo, at sa iyong anak, at sa anak ng iyong anak sa lahat ng araw ng iyong buhay; at upang ang iyong mga araw ay humaba.
O hindi ba ninyo nalalaman na tayong lahat na mga nabautismuhan kay Cristo Jesus ay mga nabautismuhan tungo sa kanyang kamatayan?
At may dumating na mga lalaking may dalang isang lalaking lumpo na nasa isang higaan at sinikap nilang maipasok ang lumpo sa bahay at mailagay sa harap ni Jesus.
At sinabi nina Moises at Aaron sa lahat ng mga anak ni Israel, “Pagsapit ng gabi, inyong malalaman na ang Panginoon ang siyang naglabas sa inyo sa lupain ng Ehipto,
Bukod dito, may isang malaking banging inilagay sa pagitan natin, upang ang mga nagnanais tumawid buhat dito patungo sa inyo ay hindi maaari at wala ring makatatawid mula riyan patungo sa amin.’
Kaya't siya'y naging kasa-kasama nila sa Jerusalem,
Nabalitaan nila ang tungkol sa iyo na itinuturo mo raw sa lahat ng mga Judio na kasama ng mga Hentil na talikdan si Moises, at sinasabi sa kanila na huwag tuliin ang kanilang mga anak ni sumunod sa mga kaugalian.
Kanyang pinapunta sila sa Bethlehem at sinabi sa kanila, “Humayo kayo at hanapin ninyong mabuti ang sanggol; kapag siya ay inyong natagpuan na, ipagbigay-alam ninyo sa akin, upang ako rin ay makaparoon at siya ay aking sambahin.”
Pagkatapos mag-usap, ibinili nila ang mga iyon ng bukid ng magpapalayok upang paglibingan ng mga dayuhan.
Sinumang bumuhat ng kanilang mga bangkay ay maglalaba ng kanyang mga damit, at magiging marumi hanggang sa paglubog ng araw.
Nang siya'y alipustain, hindi siya gumanti; nang siya'y magdusa, hindi siya nagbanta, kundi ipinagkatiwala ang kanyang sarili doon sa humahatol na may katarungan.
sapagkat ipapakita ko sa kanya kung gaano karaming bagay ang dapat niyang tiisin alang-alang sa aking pangalan.”
Kanyang ginagamit ang buong kapangyarihan ng unang halimaw na nasa kanyang paningin, at pinasasamba niya ang lupa at ang mga naninirahan dito sa unang halimaw na ang sugat na ikamamatay ay gumaling na.
At kanyang sinabi, “Hindi ba't tumpak na ang pangalan niya ay Jacob? Dalawang ulit niya akong inagawan. Kinuha niya ang aking pagkapanganay at ngayo'y kinuha ang basbas sa akin.” At kanyang sinabi, “Wala ka bang inilaang basbas para sa akin?”
Huwag ninyong kakainin ang kanilang laman at huwag ninyong hihipuin ang kanilang mga bangkay; ang mga iyon ay marumi para sa inyo.
At mula roon ay naglakbay si Abraham sa lupain ng timog, at nanirahan sa pagitan ng Kadesh at Shur. Samantalang naninirahan bilang isang dayuhan sa Gerar,
Sapagkat ang sinumang nagnanais iligtas ang kanyang buhay ay mawawalan nito at ang sinumang mawalan ng kanyang buhay dahil sa akin at sa ebanghelyo ay maililigtas iyon.
Sapagkat bagaman ang mga anak ay hindi pa isinisilang, at hindi pa nakakagawa ng anumang mabuti o masama, (upang ang layunin ng Diyos ay manatili alinsunod sa pagpili,
Huwag mo silang yuyukuran o paglilingkuran man sila, sapagkat akong Panginoon mong Diyos ay Diyos na mapanibughuin, na aking dinadalaw ang kasamaan ng mga magulang hanggang sa mga anak, sa ikatlo at sa ikaapat na salinlahi ng mga napopoot sa akin,
Ang umaani ay tumatanggap ng upa, at nagtitipon ng bunga para sa buhay na walang hanggan, upang ang naghahasik at ang umaani ay magkasamang magalak.
subalit siya ay nasa ilalim ng mga tagapangalaga at mga katiwala hanggang sa panahong itinakda ng ama.
Ang isa pang kordero ay iyong ihahandog sa hapon, at iyong ihahandog na kasama nito ang handog na butil at handog na inumin tulad ng sa umaga, na mabangong samyo, na isang handog sa Panginoon na pinaraan sa apoy.
Hinihiling ko na kunin mo ngayon ang iyong mga sandata, ang iyong lalagyan ng pana, at ang iyong busog. Pumunta ka sa parang at ihuli mo ako ng usa.
kundi maghahandog kayo sa Panginoon ng isang handog na pinaraan sa apoy, na handog na sinusunog: dalawang batang toro, isang lalaking tupa, pitong korderong lalaki na isang taong gulang, na walang kapintasan;
Ito ang mga naging anak ni Levi ayon sa kanilang mga pangalan: sina Gershon, Kohat, at Merari.
Sinabi ni Moises, “Gaya ng sinabi mo! Hindi ko na muling makikita ang iyong mukha.”
Si Moises ay hindi makapasok sa toldang tipanan, sapagkat nanatili sa ibabaw niyon ang ulap, at pinuspos ng kaluwalhatian ng Panginoon ang tabernakulo.
Sumagot si Isaac na kanyang ama, “Tingnan mo, papalayo sa taba ng lupa ang iyong tahanan, at papalayo sa hamog ng langit sa itaas;
Ngunit si Marta ay naaabala sa maraming paglilingkod. Siya'y lumapit sa kanya at sinabi, “Panginoon, wala bang anuman sa iyo na pinabayaan ako ng aking kapatid na maglingkod na mag-isa? Sabihin mo nga sa kanya na tulungan ako.”
Pagkatapos ay dinala siya ng diyablo sa banal na lunsod at inilagay siya sa taluktok ng templo,
At kung sa pamamagitan ni Beelzebul ay nagpapalayas ako ng mga demonyo, sa pamamagitan nino sila pinalalayas ng inyong mga anak? Kaya't sila ang magiging mga hukom ninyo.
Ang nasa bukid ay huwag nang bumalik upang kumuha ng kanyang balabal.
Siya'y ipinaghanda nila roon ng isang hapunan. Si Marta ay naglilingkod, at si Lazaro ay isa sa nakaupo sa may hapag-kainan na kasalo niya.
At samantalang tinatapos ni Juan ang kanyang gawain ay sinabi niya, ‘Sino ba ako sa inyong akala? Hindi ako siya. Ngunit may dumarating na kasunod ko. Hindi ako karapat-dapat na magkalag ng sandalyas ng kanyang mga paa.’
Ang isa sa mga kasama ni Jesus ay nag-unat ng kanyang kamay at bumunot ng kanyang tabak. Tinaga niya ang alipin ng pinakapunong pari at tinagpas ang tainga nito.
Sapagkat natatakot ako na baka pagdating ko ay matagpuan ko kayong hindi gaya ng nais ko, at ako ay inyong matagpuang hindi gaya ng nais ninyo; na baka mayroong pag-aaway, paninibugho, galit, pagiging makasarili, paninirang-puri, tsismis, mga kapalaluan, at kaguluhan.
Ngunit lumingon siya at sinabi kay Pedro, “Layuan mo ako, Satanas! Ikaw ay isang katitisuran sa akin; sapagkat hindi mo iniisip ang mga bagay ng Diyos, kundi ang mga bagay ng tao.”
At kapopootan kayo ng lahat dahil sa aking pangalan. Ngunit ang magtiis hanggang sa wakas ay maliligtas.
Kaya't si Moises ay tumabas ng dalawang tapyas na bato na gaya ng una; kinaumagahan, siya ay bumangon nang maaga at umakyat sa bundok ng Sinai, gaya ng iniutos ng Panginoon sa kanya, at hinawakan ang dalawang tapyas na bato.
“At kapag kayo ay nananalangin, huwag kayong maging tulad sa mga mapagkunwari; sapagkat ibig nilang tumayo at manalangin sa mga sinagoga at sa mga panulukan ng mga lansangan upang makita sila ng mga tao. Katotohanang sinasabi ko sa inyo, tinanggap na nila ang kanilang gantimpala.
Ang inyong pananalita nawa'y laging may biyaya, na may timplang asin, upang inyong malaman kung paano ninyo dapat sagutin ang bawat isa.
Sumagot sa kanya si Simon Pedro, “Panginoon, kanino kami pupunta? Ikaw ang may mga salita ng buhay na walang hanggan.
Gagawa ka ng dalawang singsing na ginto, at ilalagay mo sa dalawang sulok ng pektoral sa laylayan niyon na nasa dakong kabaligtaran ng efod.
Kapag napainom na siya ng tubig, at mangyari kung kanyang dinungisan ang kanyang sarili, at siya'y nagtaksil sa kanyang asawa, ang tubig na nagdadala ng sumpa ay papasok sa kanya at magbubunga ng matinding hapdi. Ang kanyang katawan ay mamamaga at ang kanyang hita ay lalaylay; at ang babae ay magiging sumpa sa gitna ng kanyang bayan.
na sinasabi kay Aaron, ‘Igawa mo kami ng mga diyos na mangunguna sa amin; sapagkat tungkol dito kay Moises na naglabas sa amin sa lupain ng Ehipto, ay hindi namin nalalaman kung ano ang nangyari sa kanya.’
Sinabi ni Pedro kay Jesus, “Panginoon, mabuti na tayo ay naririto. Kung ibig mo, ay gagawa ako rito ng tatlong tolda, isa sa iyo, isa kay Moises, at isa kay Elias.”
‘Ang langit ang aking luklukan, at ang lupa ang tuntungan ng aking mga paa. Anong uri ng bahay ang itatayo ninyo para sa akin? sabi ng Panginoon, o anong dako ang aking pahingahan?
Mga asawang lalaki, mahalin ninyo ang inyu-inyong mga asawa, gaya ni Cristo na nagmahal sa iglesya, at ibinigay ang kanyang sarili alang-alang sa kanya;
Nang siya'y maipahanap na ni Herodes at hindi siya natagpuan, siniyasat niya ang mga tanod at ipinag-utos na sila'y patayin. At buhat sa Judea si Pedro ay pumunta sa Cesarea, at doon nanirahan.
Subalit sila'y napuno ng matinding galit at pinag-usapan nila kung ano ang maaari nilang gawin kay Jesus.
Ngunit siya'y muling binuhay ng Diyos, pagkatapos palayain sa mga hirap ng kamatayan, sapagkat hindi maaaring siya'y mapigilan nito.
Gayunma'y hindi pinakinggan ng Panginoon mong Diyos si Balaam; kundi ginawang pagpapala ng Panginoon mong Diyos ang sumpa sa iyo sapagkat minamahal ka ng Panginoon mong Diyos.
Ito ay tulad sa pampaalsa na kinuha ng isang babae at inihalo sa tatlong takal na harina, hanggang sa ito'y nahaluang lahat ng pampaalsa.”
At sumagot si Jesus sa kanya, “Sinasabi, ‘Huwag mong tutuksuhin ang Panginoon mong Diyos.’”
“Ang isang lalaki o ang isang babae na sumasangguni sa masasamang espiritu, o mangkukulam, ay tiyak na papatayin. Sila'y babatuhin hanggang mamatay, ang kanilang dugo ay pasan nila.”
Subalit sinasabi ko sa inyo, na sa araw ng paghuhukom ay pananagutan ng mga tao ang bawat salita na binigkas na walang ingat.
Ngunit ang matibay na saligan ng Diyos ay nananatiling matatag na may tatak na ganito: “Kilala ng Panginoon ang mga kanya,” at, “Lumayo sa kalikuan ang bawat tumatawag sa pangalan ng Panginoon.”
“Mga kapatid, may tiwalang masasabi ko sa inyo ang tungkol sa patriyarkang si David. Siya rin ay namatay at inilibing, at nasa atin ang kanyang libingan hanggang sa araw na ito.
na hindi ka gagawa sa amin ng masama, gaya rin na hindi ka namin ginalaw, at wala kaming ginawa sa iyong di mabuti, at pinaalis ka naming payapa. Ikaw ngayon ang pinagpala ng Panginoon .”
At ganito ko nakita ang mga kabayo sa pangitain: ang mga nakasakay ay may mga baluting gaya ng apoy, ng jacinto at ng asupre; at ang mga ulo ng mga kabayo ay gaya ng mga ulo ng mga leon, at sa kanilang mga bibig ay lumalabas ang apoy, usok at asupre.
Kaya't sila'y ipinatawag nila at inutusan na sa anumang paraan ay huwag na silang magsalita ni magturo sa pangalan ni Jesus.
Ngunit wala silang naunawaan sa mga bagay na ito. Ang salitang ito ay naikubli sa kanila, at hindi nila naunawaan ang sinabi.
Mag-ingat kayo sa mga aso, mag-ingat kayo sa masasamang manggagawa, mag-ingat kayo sa mga hindi totoong pagtutuli.
“Kaya, huwag ninyo silang katakutan sapagkat walang bagay na natatakpan na hindi mahahayag; at walang natatago na hindi malalaman.
Ngunit pagtitig sa kanya ni Pedro, kasama si Juan, ay sinabi, “Tingnan mo kami.”
Sa ikatlong bagong buwan, pagkatapos na ang mga anak ni Israel ay makaalis sa lupain ng Ehipto, dumating sila nang araw ding iyon sa ilang ng Sinai.
yamang si Abraham ay magiging isang dakila at makapangyarihang bansa, at ang lahat ng bansa sa lupa ay pagpapalain sa pamamagitan niya?
Nang mabalitaan ng Faraon ang bagay na ito, ninais niyang patayin si Moises. Subalit si Moises ay tumakas mula kay Faraon at nanirahan sa lupain ng Midian. Siya'y umupo sa tabi ng isang balon.
“Kung ang isang lalaki ay may dalawang asawa na ang isa'y minamahal, at ang isa'y kinapopootan, at kapwa magkaanak sa kanya ang minamahal at ang kinapopootan, at kung ang naging panganay ay sa kinapopootan,
Maaari din kayong bumili mula sa mga anak ng mga dayuhan na nakikipanirahan sa inyo, at sa kanilang mga sambahayan na kasama ninyo, na kanilang ipinanganak sa inyong lupain, at sila'y magiging inyong pag-aari.
handog na butil ng mga iyon at ang mga handog na inumin para sa mga toro, sa mga lalaking tupa, at sa mga kordero ayon sa kanilang bilang, alinsunod sa tuntunin;
Dinala nila si Jesus sa pinakapunong pari at nagtipon ang lahat ng mga punong pari, matatanda at mga eskriba.
Ang mga punong pari at ang mga eskriba ay nanatili, at marahas siyang pinagbibintangan.
Si Pablo, bilanggo ni Cristo Jesus, at si kapatid na Timoteo, Kay Filemon na aming minamahal na kaibigan at kamanggagawa,
Ito ay iyo rin, ang handog na iwinagayway na kanilang kaloob, samakatuwid ay ang lahat ng mga handog na iwinagayway ng mga anak ni Israel; ibinigay ko ang mga ito sa iyo, at sa iyong mga anak na lalaki at babae na kasama mo bilang walang hanggang bahagi magpakailanman. Bawat malinis sa iyong bahay ay kakain niyon.
Kung ako nga, na Panginoon at Guro ay naghugas ng inyong mga paa, kayo man ay dapat ding maghugas ng mga paa ng isa't isa.
ang mga taga-Arvad, Zemareo, Hamateo at pagkatapos ay kumalat ang mga angkan ng Cananeo.
Kasunod niyon inialay niya ang handog ng bayan. Kinuha niya ang kambing na handog pangkasalanan na para sa bayan, at pinatay ito at inihandog bilang handog pangkasalanan, gaya ng una.
Subalit ngayong dumating na ang pananampalataya, tayo ay wala na sa ilalim ng tagasupil.
Nang matikman ng pinuno ng handaan ang tubig na naging alak, at hindi niya alam kung saan ito nanggaling (subalit nalalaman ng mga lingkod na kumuha ng tubig), tinawag ng pinuno ng handaan ang lalaking bagong kasal.
Isinulat ko sa inyo ang mga bagay na ito tungkol sa mga mandaraya sa inyo.
Umiwas kayo sa pag-ibig sa salapi at kayo'y masiyahan na kung anong mayroon kayo, sapagkat sinabi niya, “Sa anumang paraan ay hindi kita iiwan, o pababayaan man.”
Gagawin ka ng Panginoon na ulo at hindi buntot; ikaw ay magiging sa ibabaw lamang, at hindi ka mapapasailalim—kung iyong papakinggan ang mga utos ng Panginoon mong Diyos na aking iniuutos sa iyo sa araw na ito, na iyong susundin at gagawin.
Ngunit sinabi ni Pedro, “Wala akong pilak at ginto, ngunit ang nasa akin ay siya kong ibinibigay sa iyo. Sa pangalan ni Jesu-Cristong taga-Nazaret, tumayo ka at lumakad.”
Gayunman, may mga bangkang dumating mula sa Tiberias malapit sa pook na kanilang kinainan ng tinapay, pagkatapos na makapagpasalamat ang Panginoon.
Ito ang bagay na iniutos ng Panginoon , ‘Pumulot ang bawat tao ayon sa kanyang kailangan, isang omer para sa bawat tao ayon sa bilang ng mga tao, na mayroon ang bawat isa sa kanilang mga tolda.’”
Ang mga iyon ay iwawagayway ng pari kasama ng tinapay ng mga unang bunga, bilang handog na iwinawagayway sa harapan ng Panginoon , kasama ng dalawang kordero; ang mga iyon ay magiging banal sa Panginoon para sa pari.
Ngunit kung siya'y walang sapat upang maibalik sa kanya, kung gayon ang ipinagbili niya ay mapapasa-kamay ng bumili nito hanggang sa taon ng pagdiriwang; at sa pagdiriwang, ito ay bibitiwan at siya ay babalik sa kanyang pag-aari.
Nang marinig ng ilan mula sa maraming tao ang mga salitang ito, sila ay nagsabi, “Tunay na ito nga ang propeta.”
Magkakaroon ka ng mga puno ng olibo sa lahat ng iyong mga nasasakupan ngunit hindi ka magpapahid ng langis; sapagkat ang iyong olibo ay malalagas.
Isisilid mo ito sa isang bakol, at dadalhin mo ang mga ito na nasa bakol, kasama ang toro at ang dalawang lalaking tupa.
At nakita ko ang tulad sa isang dagat na kristal na may halong apoy, at ang mga dumaig sa halimaw at sa larawan nito, at sa bilang ng pangalan nito na nakatayo sa tabi ng dagat na kristal at may hawak na mga alpa ng Diyos.
Ngunit si Pablo ay nanatili pa ng ilang araw, pagkatapos ay nagpaalam na sa mga kapatid, at buhat doo'y naglakbay patungo sa Siria, at kasama niya sina Priscila at Aquila. Inahit niya ang kanyang buhok sa Cencrea, sapagkat siya'y may panata.
at aming isinugo si Timoteo, na aming kapatid at kamanggagawa ng Diyos sa ebanghelyo ni Cristo, upang kayo'y kanyang patibayin at pasiglahin tungkol sa inyong pananampalataya;
At hindi ba bibigyan ng Diyos ng katarungan ang kanyang mga pinili na sumisigaw sa kanya araw at gabi. Kanya bang matitiis sila?
At sinabi nila sa kanila ang sinabi ni Jesus at kanilang pinayagan sila.
at sila'y matauhan at makawala sa bitag ng diyablo na bumihag sa kanila upang gawin ang kanyang kalooban.
“At ngayon, nalalaman ko na kayong lahat na aking nilibot na pinapangaralan ng kaharian, ay hindi na muling makikita pa ang aking mukha.
kapag mayroon na silang mga dahon ay nakikita mismo ninyo at nalalaman na malapit na ang tag-araw.
Kukunin ng pari mula sa butil na handog ang bahaging pinakaalaala nito at susunugin sa ibabaw ng dambana, isang handog na pinaraan sa apoy, na mabangong samyo sa Panginoon .
Tumindig ka, bumaba ka at sumama sa kanila na walang pag-aatubili sapagkat sila'y aking sinugo.”
ng mga pabango at langis para sa ilawan at para sa langis na pambuhos, at para sa mabangong insenso.
kung gayon ay mag-uutos ang pari, at kanilang lalabhan ang kinaroroonan ng sakit, at ito ay ibubukod na muli sa loob ng pitong araw.
Nakita ng mga anak ng Diyos na magaganda ang mga anak na babae ng mga tao. At sila'y kumuha ng kani-kanilang mga asawa mula sa lahat ng kanilang pinili.
sila'y naging manhid at ibinigay ang kanilang sarili sa kahalayan, sakim sa paggawa ng bawat uri ng karumihan.
Ipahayag mo ang mga bagay na ito. Mangaral ka at sumaway na may buong kapamahalaan. Huwag mong hayaang hamakin ka ng sinuman.
at kung ano ang kanyang ginawa kay Datan at kay Abiram, na mga anak ni Eliab, na anak ni Ruben; kung paanong ibinuka ng lupa ang kanyang bibig at nilamon sila, ang kanilang mga sambahayan, ang kanilang mga tolda, at bawat bagay na may buhay na sumunod sa kanila sa gitna ng buong Israel;
Ang apoy sa ibabaw ng dambana ay pananatilihing nagniningas doon, at hindi ito papatayin. Ang pari ay magsusunog ng kahoy sa ibabaw niyon tuwing umaga, at aayusin niya sa ibabaw niyon ang handog na kanyang susunugin, at kanyang susunugin ito kasama ang taba ng mga handog pangkapayapaan.
Naipasiya ko na ang aking gagawin, upang matanggap ako ng mga tao sa kanilang bahay kapag pinaalis na ako sa pagiging katiwala.’
Sinabi niya sa kanyang mga anak, “Saan siya naroon? Bakit ninyo iniwan ang lalaking iyon? Tawagin ninyo siya upang makakain ng tinapay.”
Alam ko na hindi kayo papahintulutan ng hari ng Ehipto na umalis maliban sa pamamagitan ng isang makapangyarihang kamay.
at mga batong onix, at mga batong pang-enggaste, para sa efod at para sa pektoral.
At sinabi ko, ‘Sino ka ba, Panginoon?’ At sinabi ng Panginoon, ‘Ako'y si Jesus na iyong pinag-uusig.
Nang makita niyang naiwan ang kanyang suot sa kamay niya at tumakas sa labas ng bahay,
Tungkol sa mga lunsod na inyong ibibigay mula sa ari-arian ng mga anak ni Israel ay kukuha kayo ng marami mula sa malalaking lipi at sa maliliit na lipi ay kukuha kayo ng kaunti; bawat isa ayon sa kanyang mana na kanyang minamana ay magbibigay ng kanyang mga lunsod sa mga Levita.”
Kumain ng manna sa ilang ang inyong mga ninuno, at sila'y namatay.
Nang makita nila ang katapangan nina Pedro at Juan, at nang malamang sila'y mga taong walang pinag-aralan at mga karaniwan lamang, ay namangha sila at kanilang nakilala na sila'y mga kasama ni Jesus.
Hindi ko pinag-imbutan ang pilak, o ang ginto, o ang damit ninuman.
Habang bumababa sila sa bundok, iniutos niya sa kanila na huwag sabihin kaninuman ang kanilang nakita, hanggang sa ang Anak ng Tao ay magbangon mula sa mga patay.
Sinabi nila sa kanya, “Sa anong awtoridad mo ginagawa ang mga bagay na ito? O sino ang nagbigay sa iyo ng awtoridad na gawin ang mga bagay na ito?”
At ito ang tungkulin nilang dalhin ayon sa lahat ng paglilingkod nila sa toldang tipanan: ang mga tabla ng tabernakulo, ang mga biga, ang mga haligi, at ang mga patungan.
sapagkat si Juan ay nagbautismo sa tubig; subalit hindi na aabutin ng maraming araw mula ngayon, na kayo'y babautismuhan sa Espiritu Santo.”
“Ngunit kung sa pagkabigla ay kanyang maitulak na walang alitan, o mahagisan niya ng anumang bagay na hindi tinambangan,
Ang sisidlang-lupa na mahipo ng may tulo ay babasagin, at ang lahat ng sisidlang-kahoy ay babanlawan ng tubig.
Nang masabi niya ang mga bagay na ito, siya'y dumura sa lupa, at gumawa ng putik mula sa dura, at pinahiran ng putik ang mga mata ng lalaki.
Isa sa kanyang mga alagad, na minamahal ni Jesus, ang nakahilig malapit kay Jesus.
Ang mga anak ni Neftali: sina Jahzeel, Guni, Jeser, at si Shilem
Pabanalin mo sila sa katotohanan; ang salita mo ay katotohanan.
Sapagkat ang pabangong ito'y maipagbibili ng higit sa tatlong daang denario, at maipamimigay sa mga dukha.” At kanilang pinagalitan ang babae.
At may isang binata na ang pangalan ay Eutico na nakaupo sa bintana. Nakatulog siya nang mahimbing samantalang si Pablo ay nagsasalita nang mahaba; at dahil natalo ng antok ay nahulog siya mula sa ikatlong palapag, at siya'y patay na binuhat.
Silang lahat ay may labindalawang lalaki.
Pagkaraan ng maraming araw, ang hari ng Ehipto ay namatay. Ang bayang Israel ay dumaing dahil sa pagkaalipin at sila'y humingi ng tulong. Ang kanilang daing dahil sa pagkaalipin ay nakarating sa Diyos.
“Hinahatulan ba ng ating kautusan ang isang tao, malibang siya'y atin munang dinggin at alamin kung ano ang kanyang ginagawa?”
“Magsalita ka sa buong kapulungan ng mga anak ni Israel, at sabihin mo sa kanila: Kayo'y magpakabanal, sapagkat akong Panginoon ninyong Diyos ay banal.
Kaya ngayo'y hayaan mo ako upang ang aking poot ay mag-alab laban sa kanila, at aking lipulin sila. Ngunit ikaw ay aking gagawing isang dakilang bansa.”
at nadungisan ang lupain, kaya't aking dadalawin ang kanyang kasamaan at isinusuka ng lupain ang mga naninirahan doon.
At sinabi sa kanila ni Jesus, “Maaari bang magluksa ang mga panauhin sa kasalan samantalang kasama pa nila ang lalaking ikakasal? Ngunit darating ang mga araw na ang lalaking ikakasal ay kukunin sa kanila, at saka sila mag-aayuno.
Sino sa inyo na dahil sa pagkabalisa ay mapapahaba ang kanyang buhay?
At, ngayo'y bumangon kayo na kapalit ng inyong mga ninuno, supling ng mga taong makasalanan, upang dagdagan pa ninyo ang matinding galit ng Panginoon sa Israel.
Inyong ingatang gawin ang gaya ng iniutos sa inyo ng Panginoon ninyong Diyos; huwag kayong liliko sa kanan o sa kaliwa.
At di rin nila sasabihin, ‘Tingnan ninyo, naririto o naroroon!’ Sapagkat masdan ninyo, ang kaharian ng Diyos ay nasa inyo.”
At kanilang itinago hanggang sa kinaumagahan, gaya ng iniutos sa kanila ni Moises; at hindi ito bumaho, at hindi nagkaroon ng uod.
“Kung ang iyong kapatid ay naghirap, at ipinagbili ang bahagi ng kanyang mga pag-aari, ang kanyang pinakamalapit na kamag-anak ay darating at tutubusin ang ipinagbili ng kanyang kapatid.
Nagsalita ang Panginoon kay Moises, na sinasabi,
Nagsimulang dumami ang mga tao sa balat ng lupa at nagkaanak sila ng mga babae.
Pitong araw na isusuot ang mga ito ng anak na magiging pari kapalit niya, kapag siya'y pumapasok sa toldang tipanan upang maglingkod sa dakong banal.
At ang nahulog sa mabuting lupa ay sila na pagkatapos marinig ang salita, ay iningatan ito sa isang tapat at mabuting puso at nagbubunga na may pagtitiyaga.
At tumindig nga siya at umalis. May isang lalaking taga-Etiopia, isang eunuko at tagapamahala ni Candace na reyna ng mga taga-Etiopia. Siya ang namamahala ng buong kayamanan ng reyna. Ang eunuko ay nagpunta sa Jerusalem upang sumamba.
Hindi nag-atubili ang binata na gawin iyon, sapagkat nalugod siya sa anak na babae ni Jacob. Si Shekem ay ang pinakamarangal sa buong sambahayan ng kanyang ama.
sa kalinisan, kaalaman, pagtitiyaga, kagandahang-loob, kabanalan ng espiritu, tunay na pag-ibig,
Nang makita ito ni Moises, namangha siya sa tanawin; at sa kanyang paglapit upang tingnan ay dumating ang tinig ng Panginoon:
Ibubuka ng mga kerubin nang paitaas ang kanilang pakpak, na nilililiman ang luklukan ng awa ng kanilang mga pakpak. Sila'y nakaharap sa isa't isa; ang mukha ng kerubin ay nakaharap sa luklukan ng awa.
Nakilala nila na siya nga ang dating nakaupo at namamalimos sa Pintuang Maganda ng templo; at sila'y napuno ng pagtataka at pagkamangha sa nangyari sa kanya.
Sapagkat siya'y nagpagaling ng marami, siniksik siya ng lahat ng maysakit upang siya'y mahipo.
Ang Diyos ang naglalabas sa kanya sa Ehipto; may lakas na gaya ng mabangis na toro. Kanyang lalamunin ang mga bansa na kanyang mga kaaway, at kanyang babaliin ang kanilang mga buto, at papanain sila ng kanyang mga palaso.
Kaya't tumakbo si Felipe doon, at kanyang narinig na binabasa niya si Isaias na propeta, at sinabi niya, “Nauunawaan mo ba ang binabasa mo?”
Kaya't ihanda ninyo sa gawain ang inyong mga pag-iisip; na supilin ninyo ang inyong sarili at ilagak ang inyong pag-asa sa biyayang darating sa inyo kapag inihayag na si Jesu-Cristo.
Sinabi nila kay Moises, “Magsalita ka sa amin, at aming papakinggan, subalit huwag mong pagsalitain ang Diyos sa amin, baka kami ay mamatay.”
Hindi ba't kasama natin ang lahat ng kanyang mga kapatid na babae? Saan kinuha ng taong ito ang lahat ng mga bagay na ito?”
At tiyakin mong gawin ang mga iyon ayon sa anyong huwaran ng mga iyon na ipinakita sa iyo sa bundok.
At sumagot si Jesus, “Tigil! Tama na!” At hinawakan niya ang tainga at pinagaling siya.
Nang matapos na ni Jesus ang mga talinghagang ito, iniwan niya ang pook na iyon.
Gayundin naman, ang mga babae ay dapat na maging kagalang-galang, hindi mapanirang-puri, kundi mapagpigil, tapat sa lahat ng mga bagay.
Sinabi ni Juda, “Pabayaan mong ariin niya ang mga iyon, baka tayo'y pagtawanan. Tingnan mo, ipinadala ko itong anak ng kambing at hindi mo siya natagpuan.”
Nang marinig nila ito, sila'y napoot at ninais na sila'y patayin.
“Huwag kang magkakalat ng di-totoong balita. Huwag kang makikipagkapit-kamay sa taong masama upang maging isang saksing may masamang hangarin.
Pagkatapos, ang lahat ng mga anak ni Israel ay lumapit at kanyang ibinigay sa kanila sa pamamagitan ng utos ang lahat ng salita ng Panginoon na binigkas sa kanya sa bundok ng Sinai.
“Ang Panginoon nating Diyos ay nagsalita sa atin sa Horeb, na nagsasabi, ‘Kayo'y matagal nang naninirahan sa bundok na ito.
Susunugin ng pari ang taba sa ibabaw ng dambana, subalit ang dibdib ay magiging kay Aaron at sa kanyang mga anak.
Ginawa nila iyon at pinaupo silang lahat.
Ngunit si Tomas, isa sa labindalawa na tinatawag na Kambal ay hindi nila kasama nang dumating si Jesus.
tayo'y lumapit na may tapat na puso sa lubos na katiyakan ng pananampalataya, na ang mga puso ay winisikang malinis mula sa isang masamang budhi at nahugasan ang ating katawan ng dalisay na tubig.
Sabihan mo rin ang matatandang babae na maging magalang sa kanilang asal, hindi mapanirang-puri, ni paalipin man sa alak; dapat silang magturo ng kabutihan,
Mula sa tatlumpung taong gulang hanggang sa limampung taong gulang, lahat ng maaaring pumasok sa paglilingkod, upang gumawa ng gawain sa toldang tipanan.
Subalit mayroon akong patotoo na lalong dakila kaysa kay Juan. Ang mga gawaing ibinigay sa akin ng aking Ama upang ganapin, ang mga gawaing ito na aking ginagawa ay nagpapatotoo tungkol sa akin na ako'y sinugo ng Ama.
Sinabi ni Jacob, “Ipagbili mo muna sa akin ngayon ang iyong pagkapanganay.”
Ang mga anak ni Neftali ayon sa kanilang mga angkan: kay Jahzeel, ang angkan ng mga Jahzeelita; kay Guni, ang angkan ng mga Gunita.
Sinabi ng Panginoon kay Moises, “Bumangon kang maaga sa kinaumagahan, at tumayo ka sa harap ng Faraon. Sabihin mo sa kanya, ‘Ganito ang sabi ng Panginoon , ang Diyos ng mga Hebreo: Payagan mong umalis ang aking bayan upang sila'y makasamba sa akin.
“Sabihin mo sa mga anak ni Israel, ‘Pagpasok ninyo sa lupain na inyong titirahan na ibibigay ko sa inyo,
At pagdating ng jubileo ng mga anak ni Israel ay idaragdag ang kanilang mana sa mana ng lipi na kanilang kinabibilangan; sa gayo'y ang kanilang mana ay aalisin sa mana ng lipi ng aming mga ninuno.”
At dumating ang isa sa pitong anghel na may pitong mangkok at nagsalita sa akin na nagsasabi, “Halika. Ipapakita ko sa iyo ang hatol sa tanyag na mahalay na babae na nakaupo sa ibabaw ng maraming tubig;
Sinabi niya sa mga alagad, “Darating ang mga araw na hahangarin ninyong makita ang isa sa mga araw ng Anak ng Tao at hindi ninyo ito makikita.
“Sinong tulad mo, O Panginoon , sa mga diyos? Sinong gaya mo, dakila sa kabanalan, nakakasindak sa maluluwalhating gawa, na gumagawa ng mga kababalaghan?
Katotohanang sinasabi ko sa inyo, ang alipin ay hindi higit na dakila kaysa kanyang panginoon, o ang sinugo ay higit na dakila kaysa nagsugo sa kanya.
Nang araw ding iyon ay lumapit kay Jesus ang mga Saduceo, na nagsasabing walang pagkabuhay na muli; at kanilang tinanong siya,
Pansinin ninyo ang mga uwak. Hindi sila naghahasik, ni gumagapas man. Sila'y walang imbakan ni kamalig man, subalit sila'y pinapakain ng Diyos. Gaano pang higit kayong mahalaga kaysa mga ibon!
Subalit ibinilanggo ng kasulatan ang lahat ng mga bagay sa ilalim ng kasalanan, upang ang ipinangako sa pamamagitan ng pananampalataya kay Jesu-Cristo ay maibigay sa mga sumasampalataya.
Ikakapit sa iyo ng Panginoon ang salot hanggang sa maubos ka sa lupa na iyong pupuntahan upang angkinin.
Kaya't ang mga nasa Judea ay dapat tumakas patungo sa mga bundok; at ang mga nasa loob ng lunsod ay lumabas, at ang mga nasa labas ng lupain ay huwag pumasok doon;
Ako mismo ay haharap laban sa taong iyon, at ititiwalag ko siya mula sa kanyang bayan, sapagkat ibinigay niya ang kanyang anak kay Molec, kaya't nadungisan ang aking santuwaryo, at nilapastangan ang aking banal na pangalan.
Nang sila'y nakaupo na at kumakain, sinabi ni Jesus, “Katotohanang sinasabi ko sa inyo, ipagkakanulo ako ng isa sa inyo, ang kasalo kong kumakain.”
baka kayo'y magpakasama, at kayo'y gumawa para sa inyong sarili ng isang larawang inanyuan na kawangis ng alinmang larawan, na katulad ng lalaki o babae,
Ngunit sinabi sa akin ng Panginoon , ‘Huwag kang matakot sa kanya, sapagkat ibinigay ko na siya sa iyong kamay, at ang kanyang buong bayan, at ang kanyang lupain. At gagawin mo sa kanya ang gaya ng ginawa mo kay Sihon na hari ng mga Amoreo, na nanirahan sa Hesbon.’
Ngunit kung ikaw na tinatawag na Judio ay umaasa sa kautusan, at nagmamalaki sa Diyos,
Sinabi rin naman niya sa nag-anyaya sa kanya, “Kapag naghahanda ka ng isang tanghalian o ng isang hapunan, huwag mong tawagin ang iyong mga kaibigan, o ang iyong mga kapatid, o ang iyong mga kamag-anak, o mayayamang kapitbahay, baka ikaw naman ay kanilang anyayahan at ikaw ay gantihan.
At dinala niya akong nasa Espiritu sa isang malaki at mataas na bundok, at ipinakita sa akin ang banal na lunsod ng Jerusalem, na bumababa mula sa langit buhat sa Diyos,
Siya'y lumuhod at sumigaw nang malakas, “Panginoon, huwag mo silang papanagutin sa kasalanang ito.” At pagkasabi niya nito ay namatay siya.
At ang bukid, ang mga bukas na lupain sa kanilang mga lunsod, ay hindi maipagbibili sapagkat ito ay isang walang hanggang pag-aari.
gayundin nina Marcos, Aristarco, Demas, at ni Lucas na aking mga kamanggagawa.
Pagkatapos ng maraming talakayan, tumindig si Pedro at sinabi sa kanila, “Mga ginoo, mga kapatid, nalalaman ninyo na noong mga unang araw ay pumili ang Diyos sa inyo, na sa pamamagitan ng aking bibig ay mapakinggan ng mga Hentil ang salita ng ebanghelyo, at sila'y manampalataya.
Nang mga araw ngang ito ay may lumusong sa Antioquia na mga propetang galing sa Jerusalem.
Hindi nila sinisindihan ang isang ilawan at inilalagay sa ilalim ng isang takalan, kundi sa talagang patungan at nagbibigay ng liwanag sa lahat ng nasa bahay.
Sasabihin mo sa mga anak ni Israel, ‘Ito ang aking magiging banal na langis na pambuhos sa buong panahon ng inyong mga salinlahi.
Nanatili silang matibay sa turo ng mga apostol at sa pagsasama-sama, sa pagpuputul-putol ng tinapay at sa mga pananalangin.
at kapag sinisindihan ni Aaron ang mga ilawan sa gabi, kanyang ihahandog iyon bilang isang insensong patuloy na handog sa harapan ng Panginoon sa buong panahon ng inyong mga salinlahi.
Si Rebecca ay may isang kapatid na ang pangalan ay Laban. Tumakbong papalabas si Laban patungo sa lalaki na nasa bukal.
Siya'y ginawa mong mababa kaysa mga anghel nang sandaling panahon; siya'y pinutungan mo ng kaluwalhatian at ng karangalan, at siya'y inilagay mo sa ibabaw ng mga gawa ng iyong mga kamay.
Kaya, mga ginoo, lakasan ninyo ang inyong loob, sapagkat ako'y sumasampalataya sa Diyos na mangyayari ito ayon sa sinabi sa akin.
Una sa lahat, ay isinasamo ko na gawin ang mga paghiling, mga panalangin, mga pamamagitan, at mga pagpapasalamat patungkol sa lahat ng mga tao;
“At kung kayo'y hindi ko maturuan sa pamamagitan ng mga bagay na ito, kundi lumakad nang laban sa akin,
At dinaya ni Jacob si Laban na Arameo, sapagkat hindi sinabi sa kanya na siya'y tatakas.
Sinabi niya sa kanila, “Dahil sa katigasan ng inyong puso ay ipinahintulot sa inyo ni Moises na inyong hiwalayan ang inyong mga asawang babae; ngunit buhat sa pasimula ay hindi gayon.
Kung sinasabi nating tayo'y hindi nagkasala, ginagawa natin siyang sinungaling at ang kanyang salita ay wala sa atin.
At kung ito ay magbunga sa susunod na taon, ay mabuti; subalit kung hindi, maaari mo na itong putulin.”
Ako'y makapagpapatotoo na sila'y may sigasig para sa Diyos, subalit hindi ayon sa kaalaman.
Sapagkat kung paanong ang kidlat ay kumikislap at pinaliliwanag ang langit mula sa isang panig hanggang sa kabila, gayundin naman ang Anak ng Tao sa kanyang araw.
Kami ay dumaing sa Panginoon , sa Diyos ng aming mga ninuno at pinakinggan ng Panginoon ang aming tinig, kanyang nakita ang aming kahirapan, ang aming gawa, at ang aming kaapihan.
Mapapalad ang naghuhugas ng kanilang damit, upang sila'y magkaroon ng karapatan sa punungkahoy ng buhay at makapasok sa lunsod sa pamamagitan ng mga pintuan.
Sapagkat kilala natin ang nagsabi, “Akin ang paghihiganti, ako ang gaganti.” At muli, “Huhukuman ng Panginoon ang kanyang bayan.”
Magbigay sa mga pangangailangan ng mga banal at magmagandang-loob sa mga dayuhan.
Nang magkagayo'y tinawag ni Faraon sina Moises at Aaron at sinabi, “Pakiusapan ninyo ang Panginoon na alisin ang mga palaka sa akin at sa aking bayan, at aking papayagang umalis ang bayan upang sila'y makapaghandog sa Panginoon .”
“Kahabag-habag kayo, mga bulag na taga-akay na nagsasabi, ‘Kung ipanumpa ninuman ang templo, ay wala iyong kabuluhan, ngunit kung ipanumpa ninuman ang ginto ng templo, siya ay may pananagutan.’
Ngayon kung ang pagkahulog nila ay siyang kayamanan ng sanlibutan, at ang pagkalugi nila ay siyang kayamanan ng mga Hentil, gaano pa kaya ang lubos na panunumbalik nila?
sapagkat natatakot si Herodes kay Juan. Nalalaman niyang si Juan ay isang lalaking matuwid at banal at siya'y ipinagtanggol niya. Nang kanyang mapakinggan siya, labis siyang nabagabag gayunma'y masaya siyang nakinig sa kanya.
Sapagkat malapit na naming lipulin ang lugar na ito dahil sa napakalakas na ng sigaw laban sa bayang ito sa harap ng Panginoon ; at kami ay sinugo ng Panginoon upang ito ay aming lipulin.”
Sila nga'y dali-daling umalis sa libingan na may takot at malaking kagalakan, at tumakbo sila upang magbalita sa kanyang mga alagad.
maliban sa isang bagay na ito na aking isinigaw habang nakatayo sa gitna nila, ‘Tungkol sa pagkabuhay ng mga patay ako'y nililitis sa harapan mo sa araw na ito.’”
Subalit alam niya ang kanilang mga iniisip at sinabi niya sa lalaki na tuyo ang kamay, “Halika at tumayo ka sa gitna.” At siya'y tumindig at tumayo.
Tayo'y itinalaga sa pagkukupkop upang maging kanyang mga anak sa pamamagitan ni Jesu-Cristo, ayon sa kabutihan ng kanyang kalooban,
Hindi na magkakaroon pa ng gabi, at sila'y hindi nangangailangan ng liwanag ng ilawan, ni ng liwanag man ng araw, sapagkat ang Panginoong Diyos ang magbibigay-liwanag sa kanila, at sila'y maghahari magpakailanpaman.
Sinabi niya sa kanila, “Huwag na kayong sumingil pa ng higit kaysa iniutos sa inyo.”
at nalalaman natin na ang tao ay hindi inaaring-ganap sa pamamagitan ng mga gawa ng kautusan, kundi sa pamamagitan ng pananampalataya kay Jesu-Cristo, at tayo ay sumasampalataya kay Cristo Jesus, upang ariing-ganap sa pamamagitan ng pananampalataya kay Cristo, at hindi sa pamamagitan ng mga gawa ng kautusan, sapagkat sa pamamagitan ng mga gawa ng kautusan ay hindi aariing-ganap ang sinumang laman.
Ngunit kung ang mga iyon ay pawawalang-bisa ng kanyang asawa sa araw na marinig, hindi magkakabisa ang anumang bagay na binitiwan ng kanyang mga labi tungkol sa kanyang mga panata o tungkol sa itinali niya sa kanyang sarili. Patatawarin siya ng Panginoon .
at tatlumpu't dalawang libong tao lahat, mga babae na hindi pa nakakilala ng lalaki sa pamamagitan ng pagsiping sa mga ito.
Ang sinumang napopoot sa kanyang kapatid ay isang mamamatay-tao, at nalalaman ninyong ang buhay na walang hanggan ay hindi nananatili sa sinumang mamamatay-tao.
Kinuha ni Moises ang dibdib at iwinagayway ito bilang handog na iwinawagayway sa harapan ng Panginoon . Ito ang bahagi ni Moises sa tupa ng pagtatalaga, gaya ng iniutos ng Panginoon kay Moises.
“Huwag magkakaroon ng bayarang babae sa mga anak na babae ng Israel, ni magkakaroon ng bayarang lalaki sa mga anak na lalaki ng Israel.
Mula noo'y sinikap ni Pilato na siya'y pakawalan. Ngunit ang mga Judio ay nagsisigawang, “Kung pakakawalan mo ang taong ito ay hindi ka kaibigan ni Cesar. Ang bawat nag-aangkin na siya'y hari ay nagsasalita ng laban kay Cesar.”
Natagpuan siya ng anghel ng Panginoon sa tabi ng isang bukal sa ilang, sa bukal na nasa daang patungo sa Shur.
Nang hindi sumikat sa amin ang araw ni ang mga bituin man nang maraming araw, at humahampas pa rin sa amin ang isang malakas na bagyo, nawala ang buong pag-asa naming makakaligtas.
Si Jose ay inatasan ng kapitan ng bantay na mamahala sa kanila at sila'y kanyang pinaglingkuran. Sila'y nasa bilangguan nang maraming mga araw.
Nang makatawid na sila, narating nila ang lupain ng Genesaret at dumaong doon.
Sapagkat kung si Abraham ay itinuring na ganap sa pamamagitan ng mga gawa, ay mayroon sana siyang ipagmamalaki, ngunit hindi sa Diyos.
Sapagkat nasusulat na si Abraham ay nagkaroon ng dalawang anak, isa mula sa aliping babae, at ang isa ay sa babaing malaya.
Ngunit ang babae'y binigyan ng dalawang pakpak ng malaking agila upang makalipad siya mula sa harap ng ahas patungo sa ilang hanggang sa kanyang lugar, na pinaalagaan sa kanya ng isang panahon, at mga panahon, at kalahati ng isang panahon.
At sinabi niya sa kanila, “Kayo ang mga nagmamatuwid sa inyong sarili sa paningin ng mga tao, subalit nalalaman ng Diyos ang inyong mga puso. Sapagkat ang dinadakila ng mga tao ay kasuklamsuklam sa paningin ng Diyos.
Nanguna sa hukbo ng lipi ng mga anak ni Gad si Eliasaf na anak ni Deuel.
Nang sila'y hindi magkaisa, umalis sila pagkasabi ni Pablo ng isang pahayag: “Tama ang Espiritu Santo sa pagsasalita sa inyong mga ninuno sa pamamagitan ni propeta Isaias na sinasabi,
Si Moises at ang paring si Eleazar, at ang lahat ng mga pinuno sa kapulungan, ay lumabas upang salubungin sila sa labas ng kampo.
Tuwing ang ulap ay pumapaitaas mula sa ibabaw ng tolda, naglalakbay ang mga anak ni Israel at sa dakong tigilan ng ulap ay doon tumitigil ang mga anak ni Israel.
Mga minamahal, huwag kayong magtaka tungkol sa mahigpit na pagsubok na dumarating sa inyo upang kayo'y subukin, na waring may isang kataka-takang bagay na nangyayari sa inyo.
Nang siya'y dumating sa pook na iyon, ay sinabi niya sa kanila, “Manalangin kayo upang hindi kayo pumasok sa panahon ng pagsubok.”
Siya'y gumawa ng mga patayong haliging yari sa kahoy na akasya para sa tabernakulo.
Subalit ang hindi nakakaalam at gumawa ng mga bagay na karapat-dapat sa mga palo ay papaluin ng kaunti. Ngunit sa bawat binigyan ng marami ay marami ang hihingin sa kanya, at sa kanya na pinagkatiwalaan ng marami ay higit na marami ang kanilang hihingin sa kanya.
Sa ikawalong araw ay kukuha siya ng dalawang batu-bato o ng dalawang batang kalapati, at dadalhin niya sa pari sa pintuan ng toldang tipanan.
Sinaway ni Jesus ang demonyo at lumabas ito sa bata. Gumaling ang bata nang oras ding iyon.
Sapagkat kung ang sinuman ay tagapakinig ng salita at hindi tagatupad, siya ay katulad ng isang tao na tinitingnan ang kanyang likas na mukha sa salamin;
O iniisip ba ninyo na walang kabuluhan ang sinasabi ng kasulatan na, “Ang espiritu na pinatira niya sa atin ay nagnanasa na may paninibugho?”
Nang marinig ng kapitan ng templo at ng mga punong pari ang mga salitang ito, naguluhan sila at nagtataka kung ano kaya ang nangyayari.
Kaya't nang sabihin niya, “Sa ibang tao,” ay sinabi sa kanya ni Jesus, “Kung gayo'y hindi na pinagbabayad ang mga anak.
Nalalaman ko na ang kanyang utos ay buhay na walang hanggan. Kaya't ang mga bagay na sinasabi ko ay aking sinasabi ayon sa sinabi ng Ama.”
Kung minsan ang ulap ay nananatili mula sa hapon hanggang sa kinaumagahan. Kapag ang ulap ay pumaitaas sa kinaumagahan ay naglalakbay sila. Maging araw o gabi kapag ang ulap ay pumaitaas ay naglalakbay sila.
At iyong aalalahanin na ikaw ay naging alipin sa lupain ng Ehipto; kaya't iniuutos ko na gawin mo ito.
na nagsasabi, “Anong pakialam mo sa amin, Jesus ng Nazaret? Naparito ka ba upang kami'y puksain? Alam ko kung sino ka, ang Banal ng Diyos.”
at sasabihin sa kanila, ‘Pakinggan mo, O Israel, kayo'y lumapit sa araw na ito sa pakikidigma sa inyong mga kaaway; huwag manlupaypay ang inyong puso; huwag kayong matakot, ni manginig, ni maduwag dahil sa kanila;
Dahil dito hinuli ako ng mga Judio sa templo at pinagsikapang ako'y patayin.
Patnubayan nawa ng Panginoon ang inyong mga puso sa pag-ibig ng Diyos at sa katatagan ni Cristo.
“Kailangan dito ang pag-iisip na may karunungan: ang pitong ulo ay pitong bundok na kinauupuan ng babae; sila rin ay pitong hari,
Subalit nang malaman ng mga Judiong taga-Tesalonica na ang salita ng Diyos ay ipinangaral din ni Pablo sa Berea, sila ay nagpunta rin doon upang guluhin at sulsulan ang maraming tao.
Lumapit ang anghel sa kanya, at sinabi, “Magalak ka, ikaw na pinagpala! Ang Panginoon ay sumasaiyo.”
Sinabi naman niya sa kanila ang isang talinghaga: “Maaari bang akayin ng bulag ang isa pang bulag? Hindi kaya sila kapwa mahulog sa hukay?
Alalahanin mo ang iyong mga lingkod, sina Abraham, Isaac, at Jacob. Huwag mong masdan ang pagmamatigas ng bayang ito, ni ang kasamaan nila, ni ang kasalanan nila.
“Huwag kang gagawa para sa iyong sarili ng inukit na larawan o ng anumang kawangis ng anumang nasa langit sa itaas, o ng nasa lupa sa ibaba, o ng nasa tubig sa ilalim ng lupa.
palibhasa'y naging higit na mataas kaysa mga anghel, palibhasa'y nagmana ng higit na marilag na pangalan kaysa kanila.
Subalit nalalaman ko na ang pag-ibig ng Diyos ay wala sa inyo.
Ngunit nalalaman niya ang mga iniisip nila, at sinabi niya sa kanila, “Ang bawat kahariang nahahati laban sa kanyang sarili ay mawawasak; at ang bawat lunsod o bahay na nahahati laban sa kanyang sarili ay hindi makakatayo.
Gayunma'y sinasabi ko sa inyo ang katotohanan. Makakabuti sa inyo na ako'y umalis, sapagkat kung hindi ako aalis, ang Mang-aaliw ay hindi darating sa inyo. Ngunit kung ako'y umalis, siya'y susuguin ko sa inyo.
Ang reyna ng timog ay tatayo sa paghuhukom na kasama ng lahing ito, at hahatulan niya ito, sapagkat nanggaling siya sa mga dulo ng daigdig upang makinig sa karunungan ni Solomon; at masdan ninyo, may isang higit na dakila kaysa kay Solomon ang narito.
Binuksan niya ang hukay ng di-matarok na kalaliman at umakyat ang usok mula sa hukay, na gaya ng usok ng isang malaking hurno at nagdilim ang araw at ang himpapawid dahil sa usok ng hukay.
sa kanila ay hindi kami sumuko upang magpasakop, kahit isang saglit, upang ang katotohanan ng ebanghelyo ay manatili sa inyo.
At nagtanong si Jesus, “Hindi ba sampu ang nalinis? Nasaan ang siyam?
at ipangaral ang pagsisisi at pagpapatawad ng mga kasalanan sa kanyang pangalan sa lahat ng mga bansa, mula sa Jerusalem.
Ang mga hari sa lupa, ang mga prinsipe, ang mga pinuno ng hukbo, ang mayayaman, ang malalakas at ang bawat alipin at ang bawat malaya, ay nagtago sa mga yungib, sa mga bato at sa mga bundok;
“Tuparin mo ang mga iniutos ko sa iyo sa araw na ito. Tingnan mo, aking pinalalayas sa harap mo ang mga Amoreo, mga Cananeo, mga Heteo, mga Perezeo, mga Heveo, at ang mga Jebuseo.
Ibigin ninyo ang mga dayuhan, sapagkat kayo'y naging mga dayuhan din sa lupain ng Ehipto.
Bakit pa mayroong kautusan? Ito ay idinagdag dahil sa mga paglabag, hanggang sa dumating ang binhi na siyang pinangakuan; at ito'y ibinigay sa pamamagitan ng mga anghel sa kamay ng isang tagapamagitan.
Kakainin mo ang mga ito sa harapan ng Panginoon mong Diyos sa dakong pipiliin ng Panginoon mong Diyos, ikaw at ng iyong anak na lalaki at babae, at ng iyong mga aliping lalaki at babae, at ng Levita na nasa loob ng iyong mga bayan; at ikaw ay magagalak sa lahat ng iyong gagawin sa harapan ng Panginoon mong Diyos.
Sa lahat ng pagkain na maaaring kainin na mabuhusan ng tubig ay magiging marumi; at lahat ng inuming maaaring inumin sa alinman sa mga gayong sisidlan ay magiging marumi.
Ngunit siya'y sumagot at sinabi sa kanya, “Panginoon, kahit na ang mga aso sa ilalim ng hapag ay kumakain ng mga nalaglag na pagkain ng mga anak.”
Sinabi sa kanila ni Jesus, “Ang pagkain ko ay ang gawin ang kalooban ng nagsugo sa akin at tapusin ang kanyang gawain.
Nang matapos na ang kapistahan, sa pagbabalik nila ay nanatili ang batang si Jesus sa Jerusalem, ngunit hindi ito alam ng kanyang mga magulang.
Lumapit ang isa sa mga eskriba, at narinig niya ang kanilang pagtatalo, at palibhasa'y nalalamang mabuti ang pagkasagot niya sa kanila ay tinanong siya, “Alin ang pangunahing utos sa lahat?”
Nagreklamo ang bayan kay Moises, na sinasabi, “Anong aming iinumin?”
Subalit sinabi ni Jacob kay Rebecca na kanyang ina, “Si Esau na aking kapatid ay taong mabalahibo at ako'y taong makinis.
isang kambing na lalaki na handog pangkasalanan; bukod pa sa palagiang handog na sinusunog, at sa handog na butil niyon at sa inuming handog niyon.
“Magalak kayo at magsaya, sapagkat malaki ang gantimpala ninyo sa langit, sapagkat gayundin nila inusig ang mga propeta na nauna sa inyo.
Ang tubig ay bumalik at tinakpan ang mga karwahe, ang mga mangangabayo, ang buong hukbo ng Faraon na sumunod sa kanila sa dagat; walang natira kahit isa sa kanila.
Dumating noon ang taggutom sa buong Ehipto at sa Canaan, at nagkaroon ng malaking kahirapan, at walang matagpuang pagkain ang ating mga ninuno.
Sapagkat kay Cristo Jesus, ang pagtutuli o di-pagtutuli ay walang kabuluhan, kundi ang pananampalataya na gumagawa sa pamamagitan ng pag-ibig.
Nang siya'y kanilang makita sa kabilang pampang ng dagat, kanilang sinabi sa kanya, “Rabi, kailan ka dumating dito?”
At sinabi niya, “Ikaw nga ba ang aking anak na si Esau?” At sinabi ni Jacob, “Ako nga.”
Kaya nga lumabas kayo sa kanila, at humiwalay kayo, sabi ng Panginoon, at huwag kayong humipo ng anumang bagay na marumi, at kayo'y aking tatanggapin,
Doon ako makikipagtagpo sa iyo, at mula sa ibabaw ng luklukan ng awa, sa gitna ng dalawang kerubin na nasa ibabaw ng kaban ng tipan ay ibibigay ko sa iyo ang lahat ng mga utos ko para sa mga anak ni Israel.
Ang mga Parto, at mga Medo, at mga Elamita, at mga naninirahan sa Mesopotamia, sa Judea, at sa Capadocia, sa Ponto at sa Asia,
Sapagkat ang mga nakilala niya nang una pa ay itinalaga naman niya na maging katulad sa larawan ng kanyang Anak, upang siya ang maging panganay sa maraming magkakapatid;
O ang Diyos ba ay Diyos ng mga Judio lamang? Hindi ba Diyos din siya ng mga Hentil? Oo, ng mga Hentil din naman;
Kaya't ipinagsama niya ang kanyang mga kamag-anak, at hinabol siya sa loob ng pitong araw hanggang sa kanyang inabutan siya sa bundok ng Gilead.
At lumabas ang isang hangin galing sa Panginoon , at ito'y nagdala ng mga pugo mula sa dagat, at pinalapag sa kampo na may isang araw lakarin sa dakong ito, at isang araw lakarin sa kabilang dako sa palibot ng kampo, mga dalawang siko ang kapal sa ibabaw ng lupa.
Anim na araw kang gagawa at iyong gagawin ang lahat ng iyong gawain;
Sapagkat kung ginagawa nila ang mga bagay na ito kapag ang punungkahoy ay sariwa, anong mangyayari kapag ito ay tuyo?
‘Ang Panginoon ay mabagal sa pagkagalit at sagana sa tapat na pag-ibig, na nagpapatawad ng kasamaan at ng pagsuway, ngunit kailanman ay hindi pinapawalang-sala ang may sala, na dinadalaw ang kasamaan ng mga magulang sa mga anak sa ikatlo at sa ikaapat na salinlahi.
Ngunit sumagot siya sa kanila, “Bigyan ninyo sila ng makakain.” At sinabi nila sa kanya, “Aalis ba kami upang bumili ng dalawang daang denariong tinapay at ipapakain namin sa kanila?”
Kapayapaan at kaawaan nawa ang sumakanilang lahat na lumalakad sa alituntuning ito, at maging sa Israel ng Diyos.
Kaya si Jesus man ay nagdusa sa labas ng pintuan ng lunsod upang gawing banal ang mga tao sa pamamagitan ng kanyang sariling dugo.
maging ito ay paayon o pahalang; o ng lino o ng balahibo ng tupa, maging sa balat o sa alinmang yari sa balat,
“‘Sumpain ang bumabaluktot ng katarungan para sa dayuhan, sa ulila at sa babaing balo.’ At ang buong bayan ay magsasabi, ‘Amen.’
Nang marinig ng taong-bayan ang masasamang balitang ito ay tumangis sila, at walang taong nagsuot ng kanyang mga palamuti.
o ng anumang bato na ikamamatay ng tao, na hindi niya nakikita at kanyang naihagis sa kanya, na anupa't namatay at hindi niya kaaway, at hindi niya pinaghahangaran ng masama;
Noon, ang mga maniningil ng buwis at mga makasalanan ay lumalapit sa kanya upang makinig.
Gagawin sa kanila ng Panginoon ang gaya ng ginawa niya kina Sihon at Og, na mga hari ng mga Amoreo, at sa kanilang lupain na kanyang winasak.
Paggising niya ay sinaway niya ang hangin at sinabi sa dagat, “Pumayapa ka. Tumahimik ka!” Tumigil nga ang hangin at nagkaroon ng katahimikan.
Kayong mga bulag! Sapagkat alin ba ang higit na dakila, ang handog o ang dambana na nagpapabanal sa handog?
Sa kanilang pagpapatuloy sa daan, nakarating sila sa may tubig, at sinabi ng eunuko, “Tingnan mo, narito ang tubig! Ano ang nakakahadlang upang akoy mabautismuhan?” [
Ngunit sinabi ni Jesus, “Huwag ninyo siyang pagbawalan, sapagkat walang taong gumagawa ng makapangyarihang gawa sa pangalan ko ang agad na makapagsasalita ng masama tungkol sa akin.
Hindi ko kayang dalhing mag-isa ang buong bayang ito, sapagkat ang pasanin ay napakabigat para sa akin.
Kaya't sinasabi sa aklat ng Mga Pakikipaglaban ng Panginoon , Ang Waheb sa Sufa, at ang mga libis ng Arnon,
Ngayon, si Hagar ay bundok ng Sinai sa Arabia at katumbas ng kasalukuyang Jerusalem, sapagkat siya'y nasa pagkaalipin kasama ng kanyang mga anak.
Ang magiging katungkulan ng mga anak ni Gershon sa toldang tipanan ay ang tabernakulo, ang tolda at ang takip nito at ang tabing sa pintuan ng toldang tipanan,
Aking papatigasin ang puso ng Faraon, at kanyang hahabulin sila. Ako ay pararangalan sa pamamagitan ng Faraon, at sa lahat ng kanyang hukbo. Malalaman ng mga Ehipcio na ako ang Panginoon .” At gayon ang kanilang ginawa.
Ang lupain ng Ehipto ay nasa harapan mo; patirahin mo ang iyong ama at ang iyong mga kapatid sa pinakamabuti sa lupain, patirahin mo sila sa lupain ng Goshen at kung may alam ka sa kanilang may kakayahan, gawin mo silang mga tagapamahala ng aking mga hayop.”
Ito ang tipang aking gagawin sa sambahayan ni Israel pagkatapos ng mga araw na iyon, sabi ng Panginoon: ilalagay ko ang aking mga kautusan sa kanilang pag-iisip, at isusulat ko ang mga iyon sa kanilang mga puso, at ako'y magiging Diyos nila, at sila'y magiging bayan ko.
Iyong itatayo na buong bato ang dambana ng Panginoon mong Diyos, at maghahandog ka roon ng mga handog na sinusunog sa Panginoon mong Diyos.
Kaya't nakikita natin na sila'y hindi nakapasok dahil sa kawalan ng pananampalataya.
Nagmakaawa siya sa kanya na huwag silang palayasin sa lupain.
Pinalapit naman ang mga anak ni Aaron, at nilagyan ni Moises ng dugo ang dulo ng kanilang kanang tainga, ang hinlalaki ng kanilang kanang kamay at ng kanang paa; at iwinisik ni Moises ang dugo sa palibot ng dambana.
Nabuhay si Matusalem ng isandaan at walumpu't pitong taon at naging anak niya si Lamec.
Nais kong malaman ninyo na ang ating kapatid na si Timoteo ay pinalaya na; at kung siya'y dumating agad, kasama ko siyang makikita kayo.
Nang ipapasok na si Pablo sa himpilan, ay sinabi niya sa pinunong kapitan, “Maaari ba akong makipag-usap sa iyo?” At sinabi ng pinunong kapitan, “Marunong ka ba ng Griyego?
Ang mga pasanan ay isusuot sa mga argolya, upang ang mga pasanan ay malagay sa dalawang tagiliran ng dambana kapag ito'y binubuhat.
Nang makilala niya ang tinig ni Pedro, sa tuwa'y hindi niya binuksan ang pintuan, kundi tumakbo sa loob at ipinagbigay-alam na nakatayo si Pedro sa harap ng pintuan.
At si Abram ay napakayaman sa hayop, pilak, at ginto.
Subalit ngayon tayo'y nakalagan sa kautusan, yamang tayo'y namatay doon sa umalipin sa atin, upang makapaglingkod sa bagong buhay sa Espiritu, at hindi sa lumang batas na nakasulat.
At ito ang handog na inyong kukunin sa kanila: ginto, pilak, tanso,
Kaagad, samantalang nagsasalita pa siya, dumating si Judas na isa sa labindalawa. Kasama niya ang maraming tao na may mga tabak at mga pamalo, na mula sa mga punong pari, sa mga eskriba at sa matatanda.
upang ang pangalan ng ating Panginoong Jesus ay luwalhatiin sa inyo, at kayo'y sa kanya, ayon sa biyaya ng ating Diyos at ng Panginoong Jesu-Cristo.
Ang maraming tao ay nagkakaisang nakikinig sa mga sinabi ni Felipe nang kanilang marinig siya at nakita ang mga tanda na ginawa niya.
Nang magkagayo'y tumayo ang anghel ng Panginoon sa isang makipot na daan sa pagitan ng mga ubasan na may bakod sa magkabilang panig.
“Kung sila'y hindi maniwala sa iyo, ni makinig sa unang tanda, kanilang paniniwalaan ang huling tanda.
Ngunit sinabi ng mga Fariseo, “Nagpapalayas siya ng mga demonyo sa pamamagitan ng pinuno ng mga demonyo.”
Pagkatapos ay pinanumpa ni Jose ang mga anak ni Israel, na sinasabi, “Kapag dinalaw kayo ng Diyos, dadalhin ninyo ang aking mga buto mula rito.”
Isinama niya si Pedro at ang dalawang anak ni Zebedeo, at nagpasimula siyang malungkot at mabagabag.
Pagkatapos na mahigpit siyang binalaan, kaagad niya itong pinaalis.
Sinabi ni Sarai kay Abram, “Ako'y hinadlangan ng Panginoon na magkaanak. Sumiping ka sa aking alilang babae; marahil ay magkakaanak ako sa pamamagitan niya.” At pinakinggan ni Abram ang sinabi ni Sarai.
Gayundin naman ang kopa, pagkatapos ng hapunan, na sinasabi, “Ang kopang ito na nabubuhos nang dahil sa inyo ay ang bagong tipan sa aking dugo.
Isa sa kanila na ang pangalan ay Agabo, ang tumayo at ipinaalam sa pamamagitan ng Espiritu na magkakaroon ng matinding taggutom sa buong sanlibutan; at ito'y nangyari sa kapanahunan ni Claudio.
Sa pagkakataong iyon niyanig ng kanyang tinig ang lupa. Subalit ngayo'y nangako siya na sinasabi, “Minsan pang yayanigin ko, hindi lamang ang lupa, kundi pati ang langit.”
‘Tumindig kayo, at maglakbay. Dumaan kayo sa libis ng Arnon, at ibinigay ko na sa iyong kamay si Sihon na Amoreo, na hari ng Hesbon, at ang kanyang lupain. Pasimulan mong angkinin, at kalabanin mo siya sa digmaan.
Sinabi ng katiwala sa kanyang sarili, ‘Anong gagawin ko yamang inaalis sa akin ng aking panginoon ang pagiging katiwala? Hindi ko kayang maghukay at nahihiya akong mamalimos.
“Kapag ang isang tao ay nagkaroon ng pamamaga sa balat ng kanyang katawan, o langib, o kaya'y singaw, at sa balat ng kanyang katawan ay naging salot na ketong, dadalhin siya sa paring si Aaron, o sa isa sa kanyang mga anak na pari.
Huwag kayong tatanggap ng suhol sa kaninumang tumakas sa kanyang lunsod-kanlungan, upang siya'y makabalik at manirahan sa kanyang lupain bago mamatay ang pinakapunong pari.
na pagdurusahan ang parusa sa paggawa ng masama. Itinuturing nilang isang kaligayahan ang magpakalayaw kung araw. Sila ay mga bahid at dungis, na nagpapakalayaw sa kanilang mga daya, habang sila'y nakikisalo sa inyong mga handaan.
Tinubos tayo ni Cristo mula sa sumpa ng kautusan nang siya'y naging sumpa para sa atin—sapagkat nasusulat, “Sumpain ang bawat binibitay sa punungkahoy”—
At anumang bagay na inyong hingin sa panalangin na may pananampalataya ay inyong tatanggapin.”
Siya'y pinasakay niya sa karwahe na para sa ikalawang pinakamataas na pinuno; at sila'y sumisigaw sa unahan niya, “Lumuhod kayo!” Sa gayo'y inilagay siya bilang puno sa buong lupain ng Ehipto.
Si Isacar ay isang malakas na asno, na nahihiga sa gitna ng mga kawan ng mga tupa;
Nauna ang mga ito at hinintay kami sa Troas,
Ngayon, ang Diyos ng kapayapaan na bumuhay mula sa mga patay sa ating Panginoong Jesus, ang dakilang pastol ng mga tupa, sa pamamagitan ng dugo ng walang hanggang tipan,
Isang gabi, sinabi ng Panginoon kay Pablo sa isang pangitain, “Huwag kang matakot, kundi magsalita ka, at huwag kang tumahimik;
“Pagbalik ko sa Jerusalem, at habang ako'y nananalangin sa templo ay nawalan ako ng malay,
Pinunit ni Jacob ang kanyang mga suot, at nilagyan niya ng damit-sako ang kanyang mga balakang, at ipinagluksa ng maraming araw ang kanyang anak.
at lagi kong hinihiling sa anumang paraan sa pamamagitan ng kalooban ng Diyos, na makapunta sa inyo.
Sinabi ng Panginoon kay Moises, “Dumaan ka sa harap ng taong-bayan, at isama mo ang matatanda ng Israel; at dalhin mo ang tungkod na iyong ipinalo sa ilog, at humayo ka.
Gayundin ang iyong gagawin sa kanyang asno; gayundin ang iyong gagawin sa kanyang damit, at gayundin ang iyong gagawin sa bawat nawalang bagay ng iyong kapatid na nawala sa kanya at iyong natagpuan. Huwag kang magkait ng tulong.
At ang lahat na naging araw ni Enoc ay tatlong daan at animnapu't limang taon.
Isang gabi, ang katiwala ng kopa at ang panadero ng hari sa Ehipto na nasa bilangguan ay kapwa nanaginip, at ang bawat panaginip ay may kanya-kanyang kahulugan.
Sinabi sa kanya ni Pedro, “Hindi mo huhugasan ang aking mga paa kailanman.” Sinagot siya ni Jesus, “Kung hindi kita huhugasan, ay hindi ka magkakaroon ng bahagi sa akin.”
At susunugin sa paningin niya ang dumalagang baka; ang balat nito at ang laman, ang dugo, at ang dumi nito ay susunugin.
“Ang mga magulang ay hindi papatayin dahil sa mga anak, ni ang mga anak ay papatayin dahil sa mga magulang; bawat tao'y papatayin dahil sa kanyang sariling kasalanan.
At nakita kong nakatayo sa araw ang isang anghel, at siya'y sumigaw nang may malakas na tinig, na nagsasabi sa lahat ng mga ibong lumilipad sa gitna ng himpapawid, “Halikayo at magkatipon sa dakilang hapunan ng Diyos,
pinili at itinalaga ng Diyos Ama, at ginawang banal ng Espiritu upang sumunod kay Jesu-Cristo at mawisikan ng kanyang dugo: Biyaya at kapayapaan nawa ang sa inyo'y sumagana.
Nabuhay si Lamec ng isandaan at walumpu't dalawang taon at nagkaanak ng isang lalaki.
Dumating ang mga alagad ni Juan, kinuha ang bangkay at inilibing ito. Pagkatapos, sila'y umalis at ibinalita kay Jesus.
Ito ay gagawin sa kawaling may langis; ito ay mamasahing mabuti at pipira-pirasuhin tulad sa butil na handog, at ihahandog ito bilang mabangong samyo sa Panginoon .
Sinabi ng Panginoon kay Moises, “Ganito ang sasabihin mo sa mga anak ni Israel: ‘Kayo ang nakakita na ako'y nakipag-usap sa inyo mula sa langit.
Kaya't sinabi ni Jesus, “Hayaan ninyo siya. Inilaan niya ito sa araw ng paglilibing sa akin.
Nang malapit na siya sa libis ng bundok ng mga Olibo, ang lahat ng napakaraming mga alagad ay nagpasimulang magalak at magpuri sa Diyos nang may malakas na tinig dahil sa lahat ng mga makapangyarihang gawa na kanilang nakita,
Pagkatapos, ang Panginoon ay nagsugo ng mga makamandag na ahas sa mga taong-bayan, at tinuklaw ng mga ito ang mga tao, kaya't marami sa Israel ang namatay.
Si Jesus, pagtingin sa kanya ay minahal siya at sinabi, “Isang bagay ang kulang sa iyo. Humayo ka, ipagbili mo ang lahat at ibigay mo ang salapi sa dukha, at magkakaroon ka ng kayamanan sa langit. At pumarito ka, sumunod ka sa akin.”
Sa ikalabing-apat na araw ng unang buwan ay paskuwa ng Panginoon .
Ngunit ang mga salamangkero ay gumawa ng gayundin sa pamamagitan ng kanilang mga lihim na karunungan at nagpaahon ng mga palaka sa lupain ng Ehipto.
At binuksan niya ang kanilang mga pag-iisip upang maunawaan nila ang mga kasulatan.
Hindi sa nais naming maging panginoon sa inyong pananampalataya, kundi kami ay mga kamanggagawa ninyo para sa inyong kagalakan, sapagkat kayo'y nakatayong matatag sa inyong pananampalataya.
kung paanong ang Anak ng Tao ay naparito hindi upang paglingkuran, kundi upang maglingkod, at upang ibigay ang kanyang buhay na pantubos sa marami.”
Sapagkat siya at ang lahat ng kanyang kasama ay namangha dahil sa mga isdang kanilang nahuli,
Igagawa mo iyon ng isang parilyang tanso na tila lambat ang yari; at ang ibabaw ng nilambat ay igagawa mo ng apat na argolyang tanso sa apat na sulok niyon.
Inilabas ni Moises ang bayan sa kampo upang katagpuin ang Diyos; at sila'y tumayo sa paanan ng bundok.
Ang taong ito'y tinuruan sa Daan ng Panginoon; at palibhasa'y may maalab na espiritu, nagsalita siya at nagturo nang wasto tungkol kay Jesus, bagaman ang nalalaman lamang niya ay ang bautismo ni Juan.
Sapagkat nalalaman namin na kung mawasak ang aming tolda sa lupa, mayroon kaming isang gusaling mula sa Diyos, bahay na hindi gawa ng mga kamay, walang hanggan sa sangkalangitan.
Kayo ay hindi namin hinihigpitan, subalit kayo ay hinihigpitan ng sarili ninyong damdamin.
Ako'y naparito na isang ilaw sa sanlibutan, upang ang sinumang sumampalataya sa akin ay huwag manatili sa kadiliman.
Nang makasakay na sila sa bangka, ay huminto na ang hangin.
Sapagkat minabuti ng Espiritu Santo at namin na huwag kayong pagpasanin ng higit na mabigat na pasanin maliban sa mga bagay na ito na kailangan:
At ibabagsak ka sa lupa, ikaw at ang iyong mga anak na nasa iyo. Sa iyo'y hindi sila mag-iiwan ng bato sa ibabaw ng kapwa bato; sapagkat hindi mo kinilala ang panahon ng pagdalaw sa iyo.”
“Alam ko ang iyong mga gawa, ang iyong pag-ibig, pananampalataya, paglilingkod at pagtitiis, at ang iyong mga huling gawa ay higit kaysa mga una.
Pagpalain ka nawa ng Panginoon at ingatan ka.
Kanilang pinakinggan siya hanggang sa pagkakataong ito ngunit pagkatapos ay sumigaw sila, “Alisin sa lupa ang ganyang tao! Sapagkat hindi siya karapat-dapat mabuhay.”
nagpapatuloy ako tungo sa mithiin para sa gantimpala ng dakilang pagtawag ng Diyos kay Cristo Jesus.
Kanyang hinahatulan nang matuwid ang ulila at babaing balo, at iniibig ang mga nakikipamayan, na binibigyan niya ng pagkain at kasuotan.
“Kung may magningas na apoy at umabot sa mga tinik, na anupa't ang mga mandala, o ang mga uhay, o ang bukid ay masunog, ang nagpaningas ng apoy ay magbabayad ng buo.
Kaya't hinubad ng mga anak ni Israel ang kanilang mga palamuti, magmula sa bundok ng Horeb.
Sa paglipas ng panahon ay nagdala si Cain ng isang handog sa Panginoon mula sa mga bunga ng lupa.
Ang may pandinig ay makinig sa sinasabi ng Espiritu sa mga iglesya.
sa gayo'y magtitipon sila para sa kanilang sarili ng isang mabuting saligan para sa hinaharap upang sila'y makapanghawak sa tunay na buhay.
Nang maitaas na ito, gumawa sila ng paraan upang matalian ng lubid ang barko. Dahil sa takot na baka sila mapapadpad sa Sirte, ibinaba nila ang mga layag at sa gayo'y naanod sila.
At dinala ang ulo ni Juan na nasa isang pinggan at ibinigay ito sa dalaga at ibinigay naman ito ng dalaga sa kanyang ina.
