Buhat nang magsimula ang sanlibutan ay hindi narinig kailanman na binuksan ng sinuman ang mga mata ng isang taong ipinanganak na bulag.
Ngunit sumagot siya at sinabi, ‘Katotohanang sinasabi ko sa inyo, hindi ko kayo nakikilala.’
Ang buong bilang ng mga sumampalataya ay may pagkakaisa sa puso at kaluluwa; sinuma'y walang nagsabing kanya ang anuman sa kanyang mga ari-arian, kundi lahat nilang pag-aari ay para sa lahat.
upang kayo'y maging mga anak ng inyong Ama na nasa langit, sapagkat pinasisikat niya ang kanyang araw sa masasama at sa mabubuti, at nagpapaulan sa mga matuwid at sa mga di-matuwid.
Sinabi ni Pedro kay Jesus, “Panginoon, mabuti na tayo ay naririto. Kung ibig mo, ay gagawa ako rito ng tatlong tolda, isa sa iyo, isa kay Moises, at isa kay Elias.”
“upang maging mabuti ang inyong kalagayan at ikaw ay mabuhay nang matagal sa ibabaw ng lupa.”
Siya'y kanilang tinanong, “Sino ang taong nagsabi sa iyo, ‘Buhatin mo ang iyong higaan at lumakad ka?’”
Kapag nagsimulang mangyari ang mga bagay na ito, tumingala kayo at itaas ninyo ang inyong mga ulo, sapagkat malapit na ang katubusan ninyo.”
Ngunit nang makita ng kanyang mga amo na wala na ang inaasahan nilang pakinabang ay hinuli nila sina Pablo at Silas, at kinaladkad sila sa pamilihan, sa harapan ng mga pinuno.
Hindi sa kami ay may kakayahan mula sa aming sarili upang angkinin ang anuman na nagmula sa amin, kundi ang aming kakayahan ay mula sa Diyos;
“Kaya't naglakbay ako patungo sa Damasco na taglay ang awtoridad at pahintulot ng mga punong pari.
Sumagot ang mga Judio sa kanya, “Hindi ba tama ang aming sinabi na ikaw ay isang Samaritano at mayroon kang demonyo?”
Subalit sinabi ni Abraham, ‘Nasa kanila si Moises at ang mga propeta, hayaan mo silang makinig sa kanila.’
Ngunit kung sa pamamagitan ng Espiritu ng Diyos ay nagpapalayas ako ng mga demonyo, dumating na nga sa inyo ang kaharian ng Diyos.
Sinasabi ko sa inyo, Hindi! Subalit malibang kayo'y magsisi, mapapahamak din kayong lahat tulad nila.
kaamuan, at pagpipigil sa sarili. Laban sa mga ito ay walang kautusan.
na nagsasabi, “Ikaw na gigiba sa templo, at sa ikatlong araw ay itatayo ito, iligtas mo ang iyong sarili! Kung ikaw ang Anak ng Diyos, bumaba ka sa krus!”
Si Jesus, pagtingin sa kanya ay minahal siya at sinabi, “Isang bagay ang kulang sa iyo. Humayo ka, ipagbili mo ang lahat at ibigay mo ang salapi sa dukha, at magkakaroon ka ng kayamanan sa langit. At pumarito ka, sumunod ka sa akin.”
na dumarating sa pangalan ng Panginoon!
Sinabi ng isang tinig mula sa langit, “Ito ang minamahal kong Anak, sa kanya ako lubos na nalulugod.”
Kaya't umalis si Ananias at pumasok sa bahay. Ipinatong niya ang kanyang mga kamay kay Saulo at sinabi niya, “Kapatid na Saulo, isinugo ako ng Panginoong Jesus na nagpakita sa iyo sa daan sa iyong pagpunta rito upang muli mong tanggapin ang iyong paningin, at mapuspos ka ng Espiritu Santo.”
sapagkat hindi nila nauunawaan ang tungkol sa mga tinapay, kundi tumigas ang kanilang mga puso.
Isa pa sa mga alagad ay nagsabi sa kanya, “Panginoon, hayaan mo muna akong makauwi at mailibing ko ang aking ama.”
May taong naniniwala na makakain ang lahat ng mga bagay; ngunit ang mahina ay kumakain ng mga gulay.
Nang sumunod na araw, nagtipon sa Jerusalem ang kanilang mga pinuno, ang matatanda at ang mga eskriba;
Aking ninakawan ang ibang mga iglesya sa pamamagitan ng pagtanggap ng sahod mula sa kanila upang makapaglingkod sa inyo.
Madalas ko silang pinarurusahan sa lahat ng mga sinagoga at pinipilit ko silang manlapastangan; at sa nag-aalab na pagkagalit sa kanila ay pinag-uusig ko sila maging sa mga lunsod sa ibang lupain.
Walang sinumang nakakita kailanman sa Diyos. Ang Diyos na tanging Anak na nasa kandungan ng Ama ang nagpakilala sa kanya.
Gaya ng nasusulat,
Sumigaw siya nang malakas at sinabi, “Pinagpala ka sa mga babae, at pinagpala ang bunga ng iyong sinapupunan!
Subalit nalalaman natin kung saan nagmula ang taong ito, subalit ang Cristo, pagdating niya ay walang makakaalam kung saan siya magmumula.”
Kaya't sinasabi rin niya sa isa pang awit,
Ipinagbilin niya sa kanya na huwag sabihin kaninuman. “Humayo ka, magpakita ka sa pari, at maghandog ka ayon sa iniutos ni Moises dahil ikaw ay naging malinis, bilang patotoo sa kanila.”
Dumating sila sa Bethsaida. At dinala nila sa kanya ang isang lalaking bulag at ipinakiusap sa kanyang hipuin siya.
Nang marinig niya na iyon ay si Jesus na taga-Nazaret, nagsimula siyang magsisigaw at magsabi, “Jesus, Anak ni David, mahabag ka sa akin!”
Paanong hindi ninyo naunawaan na ang sinabi ko ay hindi tungkol sa tinapay? Ngunit mag-ingat kayo sa lebadura ng mga Fariseo at mga Saduceo!”
Hanggang ngayo'y wala pa kayong hinihinging anuman sa pangalan ko. Kayo'y humingi at kayo'y tatanggap, upang malubos ang inyong kagalakan.
sapagkat siya'y mabuting lalaki at puspos ng Espiritu Santo at ng pananampalataya. At napakaraming tao ang idinagdag sa Panginoon.
na sa kanya ang buong katawan na nakalapat na mabuti at nagkakaisa sa pamamagitan ng bawat litid, ayon sa paggawa sa sukat ng bawat bahagi ay nagpapalaki sa katawan tungo sa ikatitibay ng sarili sa pag-ibig.
Pagpasok niya sa Capernaum ay lumapit sa kanya ang isang senturion na nakikiusap sa kanya,
Sumagot naman si Pedro at sinabi sa kanya, “Ipaliwanag mo sa amin ang talinghaga.”
Sinabi ng babae sa kanya, “Nalalaman ko na darating ang Mesiyas (ang tinatawag na Cristo). Pagdating niya, ay ipahahayag niya sa amin ang lahat ng mga bagay.”
Habang sila'y nagtataka tungkol dito, biglang may dalawang lalaki na nakasisilaw ang mga damit ang tumayo sa tabi nila.
Sapagkat hindi ang mga tagapakinig ng kautusan ang siyang ganap sa harapan ng Diyos, kundi ang tumutupad sa kautusan ay aariing-ganap.
“Mag-ingat kayo na huwag ninyong gawin ang inyong kabanalan sa harap ng mga tao upang makita nila. Sapagkat kung gayon, wala kayong gantimpala mula sa inyong Ama na nasa langit.
Nang siya'y makita nila ay nagtaka sila at sinabi sa kanya ng kanyang ina, “Anak, bakit ginawa mo sa amin ang ganito? Tingnan mo, ang iyong ama at ako ay naghahanap sa iyo na may pag-aalala.”
Si Pedro ay sumunod sa kanya sa malayo, hanggang sa loob ng patyo ng pinakapunong pari; at nakiumpok siya sa mga kawal, at nagpainit ng sarili sa apoy.
Gaya naman ng sinasabi niya sa Hoseas,
Pagkatapos ay sinabi ni Jesus sa kanila, “Huwag kayong matakot. Humayo kayo at sabihin ninyo sa aking mga kapatid na pumunta sila sa Galilea, at doon ay makikita nila ako.”
At inilalaan ko sa inyo kung paanong ang Ama ay naglaan para sa akin ng isang kaharian,
Nagpapatotoo siya ng kanyang nakita at narinig, ngunit walang taong tumatanggap ng kanyang patotoo.
Pabanalin mo sila sa katotohanan; ang salita mo ay katotohanan.
Ito nga ang ikatlong pagpapakita ni Jesus sa mga alagad, pagkatapos na siya'y bumangon mula sa mga patay.
na umaaliw sa atin sa lahat ng ating kapighatian, upang maaliw natin ang nasa anumang kapighatian, sa pamamagitan ng kaaliwan na inialiw sa atin ng Diyos.
Ang gumagamit sa langit sa pagsumpa ay nanunumpa sa trono ng Diyos at sa kanya na nakaupo doon.
Sinasabi ko sa inyo, nanaog patungo sa kanyang bahay ang taong ito na inaring-ganap sa halip na ang isa. Sapagkat ang bawat nagmamataas sa kanyang sarili ay ibababa, ngunit ang nagpapakababa sa kanyang sarili ay itataas.”
Muling sinabi sa kanila ni Jesus, “Kapayapaan ang sumainyo. Kung paanong sinugo ako ng Ama ay sinusugo ko rin naman kayo.”
Tumindig ang pinakapunong pari at sinabi sa kanya, “Wala ka bang isasagot? Ano itong ibinibintang ng mga ito laban sa iyo?”
Ngunit siya'y sumagot at sinabi sa kanya, “Panginoon, kahit na ang mga aso sa ilalim ng hapag ay kumakain ng mga nalaglag na pagkain ng mga anak.”
Pasakop kayo sa isa't isa dahil sa takot kay Cristo.
Gayon nga ang nagtitipon ng kayamanan para sa kanyang sarili, subalit hindi mayaman sa Diyos.”
At ang ilan sa mga eskriba ay sumagot, “Guro, mahusay ang iyong pagsagot.”
Makinig kayo! Akong si Pablo ay nagsasabi sa inyo na kung kayo'y patutuli, si Cristo ay hindi magiging pakinabang sa inyo.
kami ay nagpaalam sa isa't isa. Pagkatapos, lumulan na kami sa barko at sila'y umuwi na sa kanilang mga bahay.
Sapagkat kung paano sa mga araw na iyon bago bumaha, sila'y kumakain at umiinom, at nag-aasawa at pinag-aasawa, hanggang sa araw na pumasok si Noe sa barko,
Sumagot si Pilato, “Ang naisulat ko ay naisulat ko na.”
At di rin nila sasabihin, ‘Tingnan ninyo, naririto o naroroon!’ Sapagkat masdan ninyo, ang kaharian ng Diyos ay nasa inyo.”
ni Matatias, ni Amos, ni Nahum, ni Esli, ni Nagai,
kanilang hahagupitin siya at papatayin at sa ikatlong araw siya ay muling mabubuhay.”
Siya'y maghahari sa sambahayan ni Jacob magpakailanman at hindi magwawakas ang kanyang kaharian.”
Kumain silang lahat at nabusog. Kinuha nila ang mga lumabis na pinagputul-putol na tinapay, at napuno ang labindalawang kaing.
Sinabi sa kanya ni Jesus, “Maria.” Humarap siya, at sinabi sa kanya sa wikang Hebreo, “Rabboni!” (na ang ibig sabihin ay Guro).
na nagpapatotoo sa mga Judio at gayundin sa mga Griyego tungkol sa pagsisisi tungo sa Diyos at pananampalataya sa ating Panginoong Jesu-Cristo.
Sinenyasan nila ang kanyang ama, kung ano ang ibig niyang itawag sa sanggol.
Sila'y kanyang tinanong, “Ano ang ipinakikipagtalo ninyo sa kanila?”
at ibinigay sa kanya ang aklat ni propeta Isaias. Binuksan niya ang aklat, at natagpuan ang dako na kung saan ay nasusulat:
Sino ang makapaglalarawan sa kanyang lahi?
Siya'y humiwalay sa kanila na may agwat na isang pukol ng bato. Siya'y lumuhod at nanalangin,
Habang naglalakad sila sa daan ay may nagsabi sa kanya, “Ako'y susunod sa iyo saan ka man magpunta.”
Sa simula ay ang Salita, at ang Salita ay kasama ng Diyos, at ang Salita ay Diyos.
Sinabi nila sa kanya, “Dadalhin niya ang mga masasamang taong iyon sa kakilakilabot na kamatayan at ang ubasan ay ipagkakatiwala niya sa ibang mga magsasaka na magbibigay sa kanya ng mga bunga sa kanilang kapanahunan.”
Sinabi niya sa kanila, “Dahil maliit ang inyong pananampalataya. Sapagkat katotohanang sinasabi ko sa inyo, kung mayroon kayong pananampalataya na kasinglaki ng butil ng binhi ng mustasa, sasabihin ninyo sa bundok na ito, ‘Lumipat ka roon mula rito,’ at ito'y lilipat; at sa inyo ay walang hindi maaaring mangyari.
Gaya ng inyong bahagyang pagkakilala sa amin, na kami ay inyong maipagmalaki gaya ninyo na aming ipinagmamalaki sa araw ng Panginoong Jesus.
Kaya't kanyang tinanong siya ng matagal subalit si Jesus ay hindi sumagot ng anuman.
At sa pamamagitan ng pananampalataya sa kanyang pangalan, ang kanyang pangalan ang nagpalakas sa taong ito na inyong nakikita at nakikilala. Ang pananampalataya sa pamamagitan ni Jesus ang nagkaloob sa taong ito ng ganitong sakdal na kalusugan sa harapan ninyong lahat.
sinasabi ba ninyo tungkol sa kanya na hinirang ng Ama at sinugo sa sanlibutan, ‘Ikaw ay lumalapastangan,’ sapagkat sinasabi ko, ‘Ako ay Anak ng Diyos?’
Sapagkat nasusulat na si Abraham ay nagkaroon ng dalawang anak, isa mula sa aliping babae, at ang isa ay sa babaing malaya.
Tumakbo kaagad ang isa sa kanila at kumuha ng isang espongha, pinuno ito ng suka, inilagay sa isang tambo, at ibinigay sa kanya upang inumin.
Ipinatong ni Jesus ang kanyang mga kamay sa kanya at kaagad siyang naunat at niluwalhati niya ang Diyos.
Ngunit si Pablo ay nanatili pa ng ilang araw, pagkatapos ay nagpaalam na sa mga kapatid, at buhat doo'y naglakbay patungo sa Siria, at kasama niya sina Priscila at Aquila. Inahit niya ang kanyang buhok sa Cencrea, sapagkat siya'y may panata.
Hindi pa ba ninyo nalalaman na ang anumang pumapasok sa bibig ay tumutuloy sa tiyan, at inilalabas sa daanan ng dumi?
Kung mayroong lugar na hindi kayo tanggapin at ayaw kayong pakinggan, sa pag-alis ninyo ay ipagpag ninyo ang alikabok na nasa inyong mga paa bilang patotoo laban sa kanila.”
At hinamak siya at nilibak ni Herodes at ng mga kawal na kasama niya. Sinuotan siya ng maringal na damit at ibinalik kay Pilato.
Sapagkat kung tayo'y naging kasama niya na katulad ng kanyang kamatayan, ay magkakagayon din naman tayo sa kanyang muling pagkabuhay.
At nang siya'y papalapit na sa pintuan ng bayan, inilalabas ang isang taong namatay. Siya'y nag-iisang anak na lalaki ng kanyang ina na isang balo. Kasama niya ang napakaraming tao mula sa bayan.
Nang mag-umaga na, nagkatipon ang kapulungan ng matatanda sa bayan, ang mga punong pari, at gayundin ang mga eskriba. Kanilang dinala siya sa kanilang Sanhedrin, at sinabi nila,
Ito ang mga nasa tabi ng daan na nahasikan ng salita. Nang kanilang mapakinggan ito, agad dumating si Satanas at inagaw ang salitang inihasik sa kanila.
Sila'y kanyang pinapanhik sa kanyang bahay at hinainan sila ng pagkain. Siya at ang kanyang buong sambahayan ay nagalak na sumampalataya siya sa Diyos.
at mga tanda sa lupa sa ibaba, dugo, at apoy, at makapal na usok.
Kung ang sinuman ay maglilingkod sa akin ay dapat sumunod sa akin, at kung saan ako naroroon, ay naroroon din ang lingkod ko. Kung ang sinuman ay maglilingkod sa akin, siya'y pararangalan ng Ama.
At ginawa nga ng mga tumanggap ng salapi ang ayon sa itinuro sa kanila. Ang salitang ito ay kumalat sa mga Judio hanggang sa araw na ito.
Si Pablo na apostol—hindi mula sa mga tao, o sa pamamagitan man ng tao, kundi sa pamamagitan ni Jesu-Cristo, at ng Diyos Ama, na muling bumuhay sa kanya mula sa mga patay—
Kung siya'y ating pabayaan ng ganito, ang lahat ng mga tao ay maniniwala sa kanya. Darating ang mga Romano at wawasakin ang ating Templo at ang ating bansa.”
ngunit yamang ito ay usapin tungkol sa mga salita at mga pangalan at sa inyong sariling kautusan, kayo na ang bahala rito; wala akong hangad na maging hukom sa mga bagay na ito.”
Kailangang ako'y magmalaki, kahit ito'y hindi kapaki-pakinabang, ngunit ako ay magpapatuloy sa mga pangitain at mga pahayag ng Panginoon.
Lahat ay nagsalita ng mabuti tungkol sa kanya at namangha sa mga mapagpalang salita na lumabas sa kanyang bibig. At sinabi nila, “Hindi ba ito ay anak ni Jose?”
“Darating ang ugat ni Jesse,
Sinabi niya, ‘Hindi, amang Abraham, subalit kung ang isang mula sa mga patay ay pumunta sa kanila, sila'y magsisisi.’
Sumagot siya sa kanila at sinabi, “Bakit lumalabag naman kayo sa utos ng Diyos dahil sa inyong tradisyon?
Sumagot si Jesus, “Ang pangunahin ay, ‘Pakinggan mo Israel: Ang Panginoon nating Diyos, ang Panginoon ay iisa.
“Ang isang manghahasik ay humayo upang maghasik ng binhi. Sa kanyang paghahasik, ang ilan ay nahulog sa tabi ng daan, napagyapakan, at ito'y kinain ng mga ibon sa himpapawid.
Walang may higit pang dakilang pag-ibig kaysa rito, na ibigay ng isang tao ang kanyang buhay dahil sa kanyang mga kaibigan.
Ang bahagi ng kasulatan na binabasa niya ay ito:
Kung paanong minahal ako ng Ama, ay gayundin naman minamahal ko kayo. Manatili kayo sa aking pagmamahal.
At sinabi sa kanya ng diyablo, “Ibibigay ko sa iyo ang lahat ng kapangyarihang ito, at ang kaluwalhatian nila, sapagkat ito'y naibigay na sa akin, at ibinibigay ko kung kanino ko ibig.
At sa kanyang pintuan ay nakahandusay ang isang pulubi na ang pangala'y Lazaro, na punô ng mga sugat,
Sapagkat kayo, mga kapatid, ay tinawag sa kalayaan; subalit huwag lamang ninyong gagamitin ang inyong kalayaan bilang isang kadahilanan para sa laman, kundi sa pamamagitan ng pag-ibig ay maging alipin kayo ng isa't isa.
Noo'y ikasiyam ng umaga nang siya'y kanilang ipinako sa krus.
Sana'y mapagtiisan ninyo ako sa kaunting kahangalan. Subalit tunay na nagtitiis kayo sa akin!
Sapagkat kung kayo'y sumasampalataya kay Moises ay sasampalataya kayo sa akin, sapagkat siya'y sumulat tungkol sa akin.
Sapagkat ako'y bumaba mula sa langit hindi upang gawin ko ang aking sariling kalooban, kundi ang kalooban ng nagsugo sa akin.
Subalit marami pa ring ibang mga bagay na ginawa si Jesus, na kung susulating isa-isa, sa palagay ko, kahit sa sanlibutan mismo ay hindi magkakasiya ang mga aklat na isusulat.
May dalawang taong nanghiram sa isang taong nagpapautang. Ang isa'y umutang ng limang daang denario at ang isa'y limampu.
“Mapapalad ang mga inuusig dahil sa katuwiran, sapagkat kanila ang kaharian ng langit.
Siya'y kanilang tinanong, “Kung gayo'y, ikaw ba si Elias?” At sinabi niya, “Hindi ako.” “Ikaw ba ang propeta?” At siya'y sumagot, “Hindi.”
Subalit nalalaman ko na ang pag-ibig ng Diyos ay wala sa inyo.
“Pumasok kayo sa makipot na pintuan, sapagkat maluwang ang pintuan at malapad ang daang patungo sa kapahamakan, at marami ang pumapasok doon.
“Kayong mga Israelita, pakinggan ninyo ang mga salitang ito: Si Jesus na taga-Nazaret, isang lalaking pinatunayan ng Diyos sa inyo sa pamamagitan ng mga gawang makapangyarihan, mga kababalaghan at mga tanda na ginawa ng Diyos sa pamamagitan niya sa gitna ninyo, gaya ng nalalaman ninyo—
“Ako'y naparito upang maghagis ng apoy sa lupa at nais ko sana na ito ay nagniningas na!
At kanilang sinabi, “Manampalataya ka sa Panginoong Jesus at maliligtas ka, ikaw at ang iyong sambahayan.”
baka sila'y makakita sa kanilang mga mata,
hanggang sa araw na ito.”
Kaya't sinabi ng kanyang mga magulang, “Siya'y may sapat na gulang na, tanungin ninyo siya.”
At sinabi niya sa kanya, ‘Magaling, mabuting alipin. Sapagkat naging tapat ka sa kakaunti, mamahala ka sa sampung lunsod.’
Siya'y bumaba sa Capernaum, na isang bayan ng Galilea. At siya'y nagturo sa kanila sa araw ng Sabbath.
Hindi sa may ibang ebanghelyo, kundi mayroong ilan na nanggugulo sa inyo at nagnanais na baluktutin ang ebanghelyo ni Cristo.
At bakit? Sapagkat hindi ko kayo minamahal? Alam ito ng Diyos!
Sinabi niya sa kanya, ‘Hinahatulan kita mula sa sarili mong bibig, ikaw na masamang alipin. Alam mo na ako'y taong mahigpit, na kumukuha ng hindi ko itinabi, at gumagapas ng hindi ko inihasik.
Kaya't kunin ninyo ang buong baluti ng Diyos, upang kayo'y makatagal sa araw na masama, at kung magawa na ninyo ang lahat ay tumayong matatag.
Kayo noo'y mga patay sa inyong mga pagsalangsang at mga kasalanan,
Hindi ba sinabi ng kasulatan na ang Cristo ay manggagaling sa binhi ni David, at mula sa Bethlehem, ang bayan ni David?”
Nang makakain na sila nang sapat, pinagaan nila ang barko sa pamamagitan ng pagtatapon ng trigo sa dagat.
Tinawag niya ang maraming tao pati ang kanyang mga alagad, at sa kanila'y sinabi, “Kung ang sinuman ay nagnanais sumunod sa akin, siya ay tumanggi sa kanyang sarili, pasanin ang kanyang krus at sumunod sa akin.
Ano nga ang ating sasabihin? Ang kautusan ba'y kasalanan? Huwag nawang mangyari. Gayunma'y hindi ko sana nakilala ang kasalanan, kung hindi sa pamamagitan ng kautusan; sapagkat hindi ko sana nakilala ang pag-iimbot kung hindi sinasabi ng kautusan, “Huwag kang mag-iimbot.”
At titipunin sa harapan niya ang lahat ng mga bansa at kanyang pagbubukud-bukurin ang mga tao na gaya ng pagbubukud-bukod ng pastol sa mga tupa at sa mga kambing,
Pagkatapos sila'y dumating sa lupain ng mga Gadareno, na katapat ng Galilea.
Kaya't isinugo namin sina Judas at Silas na magsasabi sa inyo ng gayunding mga bagay sa pamamagitan ng salita ng bibig.
Kaya't sa ganang akin, nasasabik din akong ipangaral ang ebanghelyo sa inyong mga nasa Roma.
Nabalitaan ni Jesus na siya'y pinalayas nila at nang kanyang makita siya, ay sinabi niya, “Sumasampalataya ka ba sa Anak ng Tao?”
Ang nanggagaling sa itaas ay mataas sa lahat, ang galing sa lupa ay taga-lupa nga, at nagsasalita tungkol sa mga bagay sa lupa; ang nanggagaling sa langit ay mataas sa lahat.
Sa alinmang bahay kayo pumasok, doon kayo tumigil, at buhat doo'y umalis kayo.
ni ipahihintulot man na ang iyong Banal ay makakita ng kabulukan.
At sinabi naman ng isa pa, “Ako'y susunod sa iyo, Panginoon, subalit hayaan mo muna akong magpaalam sa mga nasa bahay ko.”
“Ganito ang ginawa ng Panginoon sa akin nang mga araw na ako'y kanyang bigyang-pansin upang alisin ang aking kahihiyan sa gitna ng mga tao.”
At sinabi sa kanila ni Pedro, “Magsisi kayo, at magpabautismo ang bawat isa sa inyo sa pangalan ni Jesu-Cristo upang mapatawad ang inyong mga kasalanan; at tatanggapin ninyo ang kaloob ng Espiritu Santo.
Kinabukasan, lumabas kami at dumating sa Cesarea; at pumasok kami sa bahay ni Felipe na ebanghelista, na isa sa pito, at nanatili kaming kasama niya.
“Kayo'y yaong patuloy na kasama ko sa mga pagsubok sa akin.
Ililigtas kita sa mga kababayan mo at sa mga Hentil, na sa kanila'y isinusugo kita,
At kung may sinumang magsabi sa inyo, ‘Masdan ninyo, narito ang Cristo!’ o, ‘Nariyan siya!’ huwag ninyong paniwalaan.
Si Juan ay nakadamit ng balahibo ng kamelyo, may sinturong balat sa kanyang baywang, at kumakain ng mga balang at pulot-pukyutan.
Ano sa palagay mo, alin sa tatlong ito, ang naging kapwa tao sa nahulog sa kamay ng mga tulisan?”
Paanong naririnig natin, ng bawat isa sa atin, ang ating sariling wikang kinagisnan?
Nagtatali sila ng mabibigat na pasanin at mahihirap dalhin, at ipinapatong nila sa mga balikat ng mga tao; ngunit ayaw nila mismong galawin ang mga iyon ng kanilang daliri.
Ngunit sinabi ni Pablo, “Hindi ako baliw, kagalang-galang na Festo; kundi mga salita ng katotohanan at katuwiran ang sinasabi ko.
Nang mga araw na iyon, siya'y nagkasakit at namatay. Nang siya'y mahugasan na nila, kanilang ibinurol siya sa isang silid sa itaas.
Sapagkat kung ipahahayag mo sa pamamagitan ng iyong bibig si Jesus na Panginoon, at sasampalataya ka sa iyong puso na binuhay siyang muli ng Diyos mula sa mga patay, ay maliligtas ka.
upang kung mabihisan na niyon ay hindi kami matagpuang hubad.
At sasagot ang Hari at sasabihin sa kanila, ‘Katotohanang sinasabi ko sa inyo, yamang ginawa ninyo ito sa isa sa pinakamaliit sa mga kapatid kong ito, ay sa akin ninyo ginawa.’
At sabihin ninyo sa may-ari ng bahay, ‘Sinasabi ng Guro sa iyo, “Saan ang silid para sa panauhin na doon ay aking kakainin ang Paskuwa na kasalo ng aking mga alagad?”’
ang mga nasa Judea ay tumakas na patungo sa mga bundok.
Subalit nang unang araw ng sanlinggo sa pagbubukang-liwayway, pumunta sila sa libingan, dala ang mga pabango na kanilang inihanda.
Kaya ang pananampalataya ay nanggagaling sa pakikinig, at ang pakikinig ay sa pamamagitan ng salita ni Cristo.
Mula noon, si Jesus ay hindi na naglalakad nang hayagan sa gitna ng mga Judio, kundi pumunta siya sa lupaing malapit sa ilang, sa isang bayan na tinatawag na Efraim. Siya'y nanirahan doon kasama ng mga alagad.
Sinabi ni Jesus sa kanila, “Tatanungin ko kayo ng isang tanong. Sagutin ninyo ako at sasabihin ko sa inyo kung sa anong awtoridad ko ginagawa ang mga bagay na ito.
Nang dumating si Pablo sa hagdanan, siya'y binuhat na ng mga kawal dahil sa karahasan ng napakaraming tao.
Samantalang sinisiksik si Jesus ng napakaraming tao upang makinig ng salita ng Diyos, siya'y nakatayo sa tabi ng lawa ng Genesaret.
Para sa gayong tao, ang kaparusahang ito ng nakararami ay sapat na.
Ngunit inyong itinakuwil ang Banal at ang Matuwid at inyong hininging ipagkaloob sa inyo ang isang mamamatay-tao,
Ang hindi nagmamahal sa akin ay hindi tumutupad ng aking mga salita, at ang salitang inyong narinig ay hindi akin, kundi sa Amang nagsugo sa akin.
Ang Espiritu mismo ang nagpapatotoo kasama ng ating espiritu na tayo'y mga anak ng Diyos.
At sinabi nila sa kanila ang sinabi ni Jesus at kanilang pinayagan sila.
Nang matupad na nila ang lahat ng mga bagay na nasusulat tungkol sa kanya, kanilang ibinaba siya sa punungkahoy at inilagay sa isang libingan.
Sinabi ni Pedro, “Ananias, bakit napadaig ka kay Satanas at nagsinungaling ka sa Espiritu Santo, at itago ang bahagi ng pinagbilhan ng lupa?
Kaya't muling sinabi sa kanila ni Jesus, “Katotohanang sinasabi ko sa inyo, ako ang pintuan ng mga tupa.
Sapagkat sinasabi ng kasulatan, “Ang bawat sumasampalataya sa kanya ay hindi malalagay sa kahihiyan.”
Ngunit nang dumating ang pagdiriwang ng kaarawan ni Herodes, sumayaw sa gitna nila ang anak na babae ni Herodias, at ito ay ikinatuwa ni Herodes.
Nakakita si Jesus ng isang batang asno, at sumakay siya roon, gaya ng nasusulat,
Ang ilan sa nakatayo roon ay nagsabi sa kanila, “Anong ginagawa ninyo na inyong kinakalagan ang batang asno?”
Nang magkulang ng alak, sinabi ng ina ni Jesus sa kanya, “Wala silang alak.”
Sa sinumang sumampal sa iyo sa pisngi, iharap mo naman ang kabila, at sa sinumang umagaw ng iyong balabal, huwag mong ipagkait pati ang iyong tunika.
Ang sumasampalataya sa Anak ay may buhay na walang hanggan; ngunit ang hindi sumusunod sa Anak ay hindi makakakita ng buhay, kundi ang poot ng Diyos ay nananatili sa kanya.
Hinawakan niya ang kamay ng bata at sinabi sa kanya, “Talitha cum,” na ang kahulugan ay “Munting batang babae, sinasabi ko sa iyo, bumangon ka!”
At pagdating niya, kanyang susumbatan ang sanlibutan tungkol sa kasalanan, sa katuwiran, at sa kahatulan:
Pagkatapos na matanggap ang kapirasong tinapay, si Satanas ay pumasok sa kanya. Sinabi sa kanya ni Jesus, “Gawin mong mabilis ang iyong gagawin.”
Ito ang dahilan kaya't madalas akong nahahadlangan sa pagpunta sa inyo.
Sinasabi ko nga, natisod ba sila upang mahulog? Huwag nawang mangyari. Subalit sa pagkahulog nila'y dumating ang kaligtasan sa mga Hentil, upang pukawin sila sa paninibugho.
Ang maraming tao ay sama-samang tumindig laban sa kanila; at pinunit ng mga hukom ang mga damit nina Pablo at Silas, at ipinag-utos na hagupitin sila.
At sila'y pinaalis niya sa hukuman.
Puspusin nawa kayo ng Diyos ng pag-asa, ng buong kagalakan at kapayapaan sa pananampalataya, upang kayo'y sumagana sa pag-asa sa pamamagitan ng kapangyarihan ng Espiritu Santo.
ay ipinag-utos ng pinunong kapitan na siya'y ipasok sa himpilan at sinabing siya'y siyasatin na may paghagupit upang malaman niya kung anong dahilan at sila'y nagsigawan nang gayon laban sa kanya.
Pagkatapos na sila'y manatili roon ng ilang panahon, sila'y payapang pinabalik ng mga kapatid sa mga nagsugo sa kanila.
Ngunit sinabi niya sa kanila, “Huwag kayong magtaka; hinahanap ninyo si Jesus na taga-Nazaret na ipinako sa krus. Siya'y muling binuhay. Wala siya rito. Tingnan ninyo ang dakong pinaglagyan nila sa kanya!
Pumasok din ang alagad na unang dumating sa libingan at kanyang nakita at siya'y naniwala.
Kaya, may dalawang taong pupunta sa bukid, ang isa'y kukunin, at ang isa'y iiwan.
at ipinagpalit nila ang kaluwalhatian ng Diyos na hindi nasisira sa mga imaheng kahawig ng tao na nasisira, at ng mga ibon, ng mga hayop na may apat na paa at ng mga gumagapang.
Sapagkat ang Diyos ang nagsabi, “Magningning ang ilaw sa kadiliman,” na siyang tumatanglaw sa aming mga puso upang magbigay-liwanag sa pagkakilala sa kaluwalhatian ng Diyos sa mukha ni Jesu-Cristo.
At paglabas niya nang ikatlong oras, nakita niya ang iba sa pamilihan na nakatayong walang ginagawa.
Sinabi naman ni Jesus sa kanila, “Kayo ba'y lumabas na may mga tabak at mga pamalo upang dakpin ako na parang isang tulisan?
Tumakbo sila sa palibot ng buong lupaing iyon at pinasimulan nilang dalhin ang mga maysakit na nasa kanilang higaan, saanman nila mabalitaan na naroon siya.
Sinabi sa kanila ni Simon Pedro, “Mangingisda ako.” Sinabi nila sa kanya, “Kami ay sasama rin sa iyo.” Sila'y umalis at sumakay sa bangka. Nang gabing iyon ay wala silang nahuli.
Nang marinig ito ng napakaraming tao, namangha sila sa kanyang aral.
Siya'y sinundan ng napakaraming tao, at ng mga babaing nagdadalamhati at nag-iiyakan para sa kanya.
Kaya't sa dahilang ito, tinawag ko kayo upang makipagkita at makipag-usap sa inyo, yamang dahil sa pag-asa ng Israel ay nagagapos ako ng tanikalang ito.”
Nang masabi na ni Jesus ang mga bagay na ito, tumingala siya sa langit at sinabi, “Ama, dumating na ang oras, luwalhatiin mo ang iyong Anak, upang luwalhatiin ka ng Anak,
At siya'y may isang kapatid na tinatawag na Maria na naupo sa paanan ng Panginoon at nakinig sa kanyang salita.
Katotohanang sinasabi ko sa inyo, kung ang sinuman ay tutupad ng aking salita, hindi siya makakakita ng kamatayan kailanman.”
At tumindig nga siya at umalis. May isang lalaking taga-Etiopia, isang eunuko at tagapamahala ni Candace na reyna ng mga taga-Etiopia. Siya ang namamahala ng buong kayamanan ng reyna. Ang eunuko ay nagpunta sa Jerusalem upang sumamba.
Isa sa mga Fariseo ay humiling kay Jesus na kumaing kasalo niya, at pagpasok niya sa bahay ng Fariseo siya'y naupo sa hapag.
Nakita ng mga kasamahan ko noon ang liwanag, ngunit hindi nila narinig ang tinig ng nagsalita sa akin.
Sapagkat nang kayo ay mga alipin pa ng kasalanan, kayo'y malalaya tungkol sa pagiging matuwid.
Nagsugo siya at pinapugutan niya ng ulo si Juan sa bilangguan.
Sinabi sa kanya ni Jesus, “Babae, maniwala ka sa akin na darating ang oras na inyong sasambahin ang Ama, hindi sa bundok na ito o sa Jerusalem.
Ngunit kinuha ng mga magsasaka ang kanyang mga alipin at binugbog nila ang isa, pinatay ang iba, at pinagbabato ang isa pa.
Lahat nang nakarinig sa kanya ay namangha, at nagsabi, “Hindi ba ito ang lalaking pumuksa sa Jerusalem sa mga tumatawag sa pangalang ito? At naparito siya para sa layuning ito, upang sila'y dalhing nakagapos sa harap ng mga punong pari.”
at tayo'y hindi niya itinangi sa kanila, kundi nilinis ang kanilang mga puso sa pamamagitan ng pananampalataya.
Sapagkat sa pagbubuhos niya ng pabangong ito sa aking katawan, ginawa niya iyon upang ihanda ako sa paglilibing.
Sapagkat ang sinumang ikinahihiya ako at ang aking mga salita sa mapangalunya at makasalanang salinlahing ito ay ikahihiya rin naman siya ng Anak ng Tao, pagdating niyang nasa kaluwalhatian ng kanyang Ama na kasama ng mga banal na anghel.”
at sa mga nakaupo sa lupain at lilim ng kamatayan,
sapagkat hindi kami tumitingin sa mga bagay na nakikita, kundi sa mga bagay na hindi nakikita, sapagkat ang mga bagay na nakikita ay may katapusan, subalit ang mga bagay na hindi nakikita ay walang hanggan.
Ngunit sinabi sa kanya ng Panginoon, “Pumunta ka sapagkat siya'y isang kasangkapang pinili ko upang dalhin ang aking pangalan sa harapan ng mga Hentil at ng mga hari, at ng mga anak ni Israel;
Ito ang unang pagtatala na ginawa nang si Quirinio ay gobernador sa Siria.
Sumagot sa kanya si Jesus, “Lumayas ka, Satanas! sapagkat nasusulat, ‘Sambahin mo ang Panginoon mong Diyos, at siya lamang ang iyong paglingkuran.’”
Sinabi nila sa kanya, “Babae, bakit ka umiiyak?” Sinabi niya sa kanila, “Sapagkat kinuha nila ang aking Panginoon, at hindi ko alam kung saan nila siya inilagay.”
At ang nasa bubungan ay huwag nang bumaba, o pumasok upang maglabas ng anuman sa kanyang bahay.
Sapagkat sinasabi ng kasulatan kay Faraon, “Dahil sa layuning ito, ay itinaas kita, upang aking maipakita sa pamamagitan mo ang aking kapangyarihan, at upang ang aking pangalan ay maipahayag sa buong lupa.”
Ang maraming tao na sumunod sa kanya ay patuloy na sumisigaw, “Alisin siya!”
Subalit nang dumating ang anak mong ito na lumustay ng iyong kabuhayan sa masasamang babae ay ipinagpatay mo pa siya ng pinatabang guya.’
“Ngayon ay nababagabag ang aking kaluluwa. At ano ang aking sasabihin? ‘Ama, iligtas mo ako sa oras na ito?’ Ngunit dahil dito ay dumating ako sa oras na ito.
Sa kautusan ay ipinag-utos sa amin ni Moises na batuhin ang mga ganyan. Ano ngayon ang iyong masasabi tungkol sa kanya?”
Biglang nabuksan ang kanyang bibig, nakalaya ang kanyang dila, at siya'y nagsalita na pinupuri ang Diyos.
Kanyang gagantihan ang bawat tao ayon sa kanyang mga gawa:
Nang matikman ng pinuno ng handaan ang tubig na naging alak, at hindi niya alam kung saan ito nanggaling (subalit nalalaman ng mga lingkod na kumuha ng tubig), tinawag ng pinuno ng handaan ang lalaking bagong kasal.
Kaya't marami sa mga Judio na sumama kay Maria at nakakita ng ginawa niya ang sumampalataya sa kanya.
Pumunta ang lahat upang magpatala, bawat isa sa kanyang sariling bayan.
“Kung magkasala laban sa iyo ang iyong kapatid, pumaroon ka at sabihin mo sa kanya ang kanyang pagkakamali kapag kayong dalawa lamang. Kung pakinggan ka niya, ay napanumbalik mo ang iyong kapatid.
At pagkaawit nila ng isang himno ay nagtungo sila sa Bundok ng mga Olibo.
Sa pagdaan ni Jesus sa tabi ng dagat ng Galilea, nakita niya sina Simon at ang kanyang kapatid na si Andres na naghahagis ng lambat sa dagat, sapagkat sila'y mga mangingisda.
Muli siyang tinanong ni Pilato, “Wala ka bang isasagot? Tingnan mo kung gaano karami ang kanilang ibinibintang laban sa iyo.”
Ngayon, mayroong pitong magkakapatid na lalaki. Nag-asawa ang panganay, at namatay na walang anak;
Nabalitaan ng mga apostol at ng mga kapatid na nasa Judea na tinanggap din ng mga Hentil ang salita ng Diyos.
Hinawakan niya sa kamay ang lalaking bulag at dinala niya sa labas ng nayon. Nang maduraan ang kanyang mga mata at maipatong ang kanyang mga kamay sa kanya, kanyang tinanong siya, “May nakikita ka bang anuman?”
Sapagkat hindi mo hahayaan ang kaluluwa ko sa Hades,
Sumagot siya sa kanila, “Sino ang aking ina at ang aking mga kapatid?”
Pagkatapos ng Sabbath, sa pagbubukang-liwayway ng unang araw ng sanlinggo, si Maria Magdalena at ang isa pang Maria ay pumaroon upang tingnan ang libingan.
At sinabi sa kanya, “Humayo ka, maghugas ka sa imbakan ng tubig ng Siloam” (na ang kahulugan ay Sinugo). Humayo nga siya at naghugas at bumalik na nakakakita.
Ano sa palagay ninyo?” Sumagot sila at sinabi, “Karapat-dapat siya sa kamatayan.”
Nang panahong iyon ay nagkaroon ng malaking gulo tungkol sa Daan.
Alalahanin ninyo ang asawa ni Lot.
Nakikilala ko siya sapagkat ako'y mula sa kanya, at siya ang nagsugo sa akin.”
“Ang kanilang bibig ay punô ng panunumpa at kapaitan.”
Ngunit sinabi sa kanya ni Pedro, “Ang iyong salapi'y mapahamak na kasama mo, sapagkat inakala mong makukuha mo ang kaloob ng Diyos sa pamamagitan ng salapi!
Sila'y tinuruan niya ng maraming bagay sa pamamagitan ng mga talinghaga at sa kanyang pagtuturo ay sinabi niya sa kanila,
Sina Pedro at Juan, pagkatapos na makapagpatotoo at masabi na nila ang salita ng Panginoon, ay bumalik sa Jerusalem na ipinangaral ang ebanghelyo sa maraming nayon ng mga Samaritano.
Ngayon, ang mga pangako ay ginawa kay Abraham at sa kanyang binhi. Hindi sinasabi, “At sa mga binhi,” na tungkol sa marami; kundi tungkol sa iisa, “At sa iyong binhi,” na si Cristo.
Nagsimulang magsalita si Pedro at kanyang sinabi, “Tunay ngang nauunawaan ko na walang kinikilingan ang Diyos,
At nang makita ng mga alagad na siya ay lumalakad sa ibabaw ng dagat, nasindak sila, na nagsasabi, ‘Multo!’ Nagsigawan sila sa takot.
Ngunit hindi sila makasalungat sa karunungan at sa Espiritu na sa pamamagitan nito'y nagsasalita siya.
Pagkaraan ng tatlong araw, tinipon niya ang mga pinuno ng mga Judio at nang sila'y matipon na, ay sinabi niya sa kanila, “Mga kapatid, bagaman wala akong ginawang anuman laban sa bayan, o sa mga kaugalian ng ating mga ninuno, ay ibinigay akong bilanggo buhat sa Jerusalem sa mga kamay ng mga taga-Roma.
Pagkatapos ay lumapit kay Jesus ang ina ng mga anak ni Zebedeo, na kasama ang kanyang mga anak na lalaki. Siya'y lumuhod sa kanya at may hiniling na isang bagay sa kanya.
at itatapon nila ang mga ito sa pugon ng apoy. Doon ay magkakaroon ng pagtangis at pagngangalit ng mga ngipin.
Lumabas ang buong bayan upang salubungin si Jesus at pagkakita nila sa kanya, pinakiusapan nila siyang umalis sa kanilang nasasakupan.
Agad niyang tinawag sila at iniwan nila si Zebedeo na kanilang ama sa bangka na kasama ng mga upahang tauhan at sumunod sa kanya.
Pagkatapos nilang manalangin, nayanig ang dakong pinagtitipunan nila at silang lahat ay napuno ng Espiritu Santo, at kanilang ipinahayag na may katapangan ang salita ng Diyos.
Nagharap sila ng mga sinungaling na saksi na nagsabi, “Ang taong ito'y hindi tumitigil sa pagsasalita ng mga salitang laban sa Dakong Banal na ito at sa Kautusan.
ngunit sumagot ang kanyang ina at nagsabi, “Hindi. Ang itatawag sa kanya ay Juan.”
Nang marinig niya ito, tumakas si Moises at naging dayuhan sa lupain ng Midian, kung saan siya'y naging ama ng dalawang lalaki.
na sinasabi, “Guro, sinabi ni Moises, ‘Kung mamatay ang isang tao na walang anak, pakakasalan ng kanyang kapatid na lalaki ang asawa niya, at magkakaroon ng mga anak para sa kanyang kapatid na lalaki.’
Ang kanyang anyo ay tulad sa kidlat at ang kanyang pananamit ay maputing parang busilak.
“Ang mga patriyarka, dahil sa inggit kay Jose ay ipinagbili siya sa Ehipto, ngunit ang Diyos ay kasama niya.
[
Pagkatapos ay sinabi niya sa alagad, “Narito ang iyong ina!” At mula noon ay dinala siya ng alagad sa kanyang sariling tahanan.
Nais kong makaharap kayo ngayon at baguhin ang aking tono, sapagkat ako'y nag-aalinlangan tungkol sa inyo.
Inihulog nila ang mga angkla at kanilang iniwan iyon sa dagat samantalang kinakalag ang mga tali ng mga ugit. Nang maitaas na nila sa hangin ang layag sa unahan ay nagtungo sila sa baybayin.
Nang matapos pagbilinan ni Jesus ang kanyang labindalawang alagad, umalis siya roon upang magturo at mangaral sa mga bayan nila.
na nang siya'y nasa Galilea, ay sumunod sa kanya at naglingkod sa kanya; at marami pang ibang mga babae na umahong kasama niya sa Jerusalem.
at pinasimulan niyang bugbugin ang mga kapwa niya alipin, at nakisalo at nakipag-inuman sa mga lasing,
Magkakaroon ng malalakas na lindol, at sa iba't ibang dako ay magkakaroon ng taggutom at mga salot, at magkakaroon ng mga bagay na kakilakilabot, at ng mga dakilang tanda mula sa langit.
At ito ang buhay na walang hanggan, na ikaw ay makilala nila na iisang Diyos na tunay, at si Jesu-Cristo na iyong sinugo.
Ibig siyang hadlangan ni Juan, na nagsasabi, “Ako ang dapat mong bautismuhan, at ikaw pa ang lumalapit sa akin?”
Katotohanang sinasabi ko sa inyo, maliban na ang butil ng trigo ay mahulog sa lupa at mamatay, ito ay mananatiling nag-iisa. Ngunit kung ito'y mamatay, ay nagbubunga ng marami.
At bumalik ang alipin, at iniulat ang mga bagay na ito sa kanyang panginoon. Sa galit ng may-ari ng bahay ay sinabi sa kanyang alipin, ‘Pumunta ka agad sa mga lansangan at sa makikipot na daan ng bayan, at dalhin mo rito ang mga dukha, ang mga pilay, ang mga bulag, at ang mga lumpo.’
Ngunit kung paanong ang Diyos ay tapat, ang aming sinasabi sa inyo ay hindi “Oo at Hindi.”
Subalit sinabi sa kanya ng Diyos, ‘Hangal, sa gabing ito ay kukunin ang iyong kaluluwa; at kanino kaya mapupunta ang mga bagay na inihanda mo?’
Sapagkat sa pamamagitan niya, kapwa tayong makakalapit sa isang Espiritu patungo sa Ama.
Siya'y iniligtas sa lahat ng kanyang kapighatian, at binigyan siya ng biyaya at karunungan sa harapan ng Faraon na hari ng Ehipto; at kanyang pinili siya upang mamahala sa Ehipto at sa buong bahay niya.
Gayundin naman kayo, kapag nagawa na ninyo ang lahat ng mga bagay na iniutos sa inyo, inyong sabihin, ‘Kami'y mga aliping walang kabuluhan, ginawa lamang namin ang aming katungkulan.’”
Sinabi sa kanya ni Jesus, “Ako nga iyon na kumakausap sa iyo!”
idalangin ninyo sa Panginoon ng anihin, na magpadala ng mga manggagawa sa kanyang aanihin.”
Sapagkat pumarito ako upang paglabanin ang lalaki at ang kanyang ama, ang anak na babae at ang kanyang ina, at ang manugang na babae at ang kanyang biyenang babae.
Katotohanang sinasabi ko sa inyo, sinumang hindi tumatanggap sa kaharian ng Diyos na gaya ng isang maliit na bata ay hindi makakapasok doon.”
Ito ay ayon sa walang hanggang panukala na kanyang ginawa kay Cristo Jesus na Panginoon natin,
Ngunit ito'y sinabi niya tungkol sa Espiritu, na tatanggapin ng mga sumasampalataya sa kanya, sapagkat hindi pa ipinagkakaloob ang Espiritu, sapagkat si Jesus ay hindi pa niluluwalhati.
‘Ibibigay ko sa iyo ang banal at mga maaasahang pangako kay David.’
Mga minamahal, yamang taglay natin ang mga pangakong ito, linisin natin ang ating mga sarili mula sa bawat karumihan ng laman at espiritu, na ginagawang sakdal ang kabanalan sa pagkatakot sa Diyos.
“Ngunit nang pumasok ang hari upang tingnan ang mga panauhin, may nakita siya roong isang tao na hindi nakadamit pangkasal.
Kanyang isinama sina Pedro, Santiago at Juan, at nagsimula siyang malungkot at mabagabag.
Ngunit may isang lalaki na ang pangalan ay Ananias ang nagbili ng isang ari-arian, na may pagsang-ayon ng kanyang asawang si Safira.
Ngunit nang paligiran siya ng mga alagad, tumayo siya at pumasok sa lunsod. Kinabukasan, umalis siya kasama ni Bernabe patungo sa Derbe.
Sapagkat marami ang darating sa aking pangalan, na nagsasabi, ‘Ako ang Cristo’ at ililigaw nila ang marami.
[
Sapagkat malapit ang Lidda sa Joppa, nang mabalitaan ng mga alagad na si Pedro ay naroroon, nagsugo sila sa kanya ng dalawang tao at ipinakiusap sa kanya, “Pumarito ka sa amin sa lalong madaling panahon.”
Sinabi sa kanya ni Jesus, “Siya'y nakita mo na, at siya ang nakikipag-usap sa iyo.”
Kung ang kanan mong mata ang sanhi ng iyong pagkakasala, dukitin mo ito at itapon, sapagkat mabuti pang mawalan ka ng isa sa mga bahagi ng iyong katawan kaysa ang buong katawan mo ay mapatapon sa impiyerno.
Sino ang hahatol? Si Cristo Jesus na namatay, oo, siyang muling binuhay mula sa mga patay, na siya ring nasa kanan ng Diyos, na siya ring namamagitan para sa atin.
Kung ang mga bagay na aking sinira ay aking muling itayo, pinatutunayan ko sa aking sarili na ako'y suwail.
Magbatian kayo ng banal na halik. Binabati kayo ng lahat ng mga iglesya ni Cristo.
Nagtangka pa siya na lapastanganin ang templo ngunit dinakip namin siya.
naging anak ni Aram si Aminadab; naging anak ni Aminadab si Naashon; at naging anak ni Naashon si Salmon;
Sumagot si Jesus at sinabi sa kanila, “Tatanungin ko rin kayo ng isang tanong, at kung sasabihin ninyo sa akin ang sagot ay sasabihin ko naman sa inyo kung sa anong awtoridad ginagawa ko ang mga bagay na ito.
Subalit ang mula sa alipin ay ipinanganak ayon sa laman, at ang mula sa babaing malaya ay sa pamamagitan ng pangako.
Subalit ano ang sinasabi ng kasulatan? “Palayasin ang aliping babae at ang kanyang anak, sapagkat hindi magmamana ang anak ng babaing alipin na kasama ng anak ng babaing malaya.”
Kanyang sinagot sila, “Sinabi ko na sa inyo, at hindi kayo nakinig. Bakit ibig ninyong marinig uli? Ibig din ba ninyong maging mga alagad niya?”
Nang makaraan na sina Pablo at Silas sa Amfipolis at sa Apolonia ay nakarating sila sa Tesalonica, kung saan ay may isang sinagoga ng mga Judio.
Sinabi ni Jesus sa kanila, “Itinatanong ko sa inyo, ipinahihintulot ba sa kautusan na gumawa ng mabuti, o gumawa ng masama kung Sabbath? Magligtas ng buhay o pumuksa nito?”
At sasabihin nila sa inyo, ‘Tingnan ninyo, naroroon’ o ‘Tingnan ninyo, naririto!’ Huwag kayong pumaroon o sumunod sa kanila.
Nang sumunod na araw, lumapit siya sa kanila samantalang sila'y nag-aaway, at ibig sana niyang sila'y pagkasunduin, na sinasabi, ‘Mga ginoo, kayo'y magkapatid; bakit kayo nag-aaway?’
At sila'y dumaan sa Pisidia at nagtungo sa Pamfilia.
Kung may magsabi sa inyo, ‘Narito ang Cristo!’ o, ‘Tingnan ninyo naroon siya!’ huwag ninyong paniwalaan.
At ang nagkanulo sa kanya ay nagbigay sa kanila ng isang hudyat, na sinasabi, “Ang aking halikan ay iyon na; hulihin ninyo siya at dalhin siyang may bantay.”
Subalit kung ang ating kasamaan ay nagpapatibay sa katarungan ng Diyos, ano ang ating sasabihin? Ang Diyos ba ay di-makatarungan sa paglalapat ng parusa sa atin? (Nagsasalita ako sa paraan ng tao.)
Ibinangon ng Diyos ng ating mga ninuno si Jesus, na inyong pinatay nang ibitin siya sa isang punungkahoy.
Ngunit kapag nag-aayuno ka, lagyan mo ng langis ang iyong ulo, at maghilamos ka ng iyong mukha;
Sinabi nga niya, “Isang maharlikang tao ang pumunta sa isang malayong lupain, upang tumanggap ng isang kaharian at pagkatapos ay bumalik.
sapagkat bibigyan ko kayo ng salita at karunungan na hindi malalabanan o matututulan man ng lahat ng sumasalungat sa inyo.
Sila ay nakiusap sa kanya na huwag silang utusang bumalik sa di-matarok na kalaliman.
At siya'y lumabas at pumaroon, gaya ng kanyang nakaugalian, sa bundok ng mga Olibo at sumunod naman sa kanya ang mga alagad.
Siya'y kanilang dinamitan ng kulay-ube, at nang makapagtirintas ng isang koronang tinik ay ipinutong nila ito sa kanya.
Tinawag nilang Zeus si Bernabe at Hermes si Pablo, sapagkat siya ang pangunahing tagapagsalita.
‘Tingnan ninyo, mga mapanlibak!
Ang mga bagay na ito ay isang paghahambing, sapagkat ang mga babaing ito'y dalawang tipan. Ang isa ay si Hagar na mula sa bundok ng Sinai na nanganganak para sa pagkaalipin.
Nang marinig ito ni Jesus, sinabi niya sa kanya, “Isang bagay pa ang kulang sa iyo. Anumang mayroon ka ay ipagbili mo, ipamahagi mo sa mga dukha, at magkakaroon ka ng kayamanan sa langit. At pumarito ka, sumunod ka sa akin.
Iniunat ni Jesus ang kanyang kamay, at hinawakan niya ito na nagsasabi, “Ibig ko. Maging malinis ka.” At nalinis kaagad ang kanyang ketong.
Subalit ngayo'y pinagsisikapan ninyo akong patayin, isang taong nagsasabi sa inyo ng katotohanan na aking narinig sa Diyos. Ito'y hindi ginawa ni Abraham.
Nang bumaba si Jesus mula sa bundok, sinundan siya ng napakaraming tao;
Mula nang oras na ikaanim ay nagdilim sa buong lupain hanggang sa oras na ikasiyam.
Siya'y ginapos nila, dinala sa labas, at ibinigay nila kay Pilato na gobernador.
Bumagsak ako sa lupa, at narinig ko ang isang tinig na nagsasabi sa akin, ‘Saulo, Saulo, bakit mo ako pinag-uusig?’
Ano nga kung sa pagnanais ng Diyos na ipakita ang kanyang poot, at ipakilala ang kanyang kapangyarihan, ay nagtitiis na may pagtitiyaga sa mga kinapopootan niya na inihanda para sa pagkawasak;
Lumabas sila sa lunsod, at pumunta sa kanya.
Ngunit sinumang magkaila sa akin sa harapan ng mga tao, ay ipagkakaila ko rin naman sa harapan ng aking Ama na nasa langit.
Nalalaman nila ang mga iniuutos ng Diyos, na ang mga gumagawa ng gayong mga bagay ay karapat-dapat sa kamatayan, ngunit hindi lamang nila ginagawa ang gayon kundi sinasang-ayunan pa ang gumagawa ng mga iyon.
Sa pamamagitan nito'y naluluwalhati ang aking Ama, na kayo'y magbunga ng marami, at maging mga alagad ko.
Sila'y sumagot sa kanya, “Ikaw ba'y taga-Galilea rin? Siyasatin mo at iyong makikita na sa Galilea ay walang lumitaw na propeta.”
Pinaalis na niya ang maraming mga tao. Sumakay siya sa isang bangka at nagtungo sa nasasakupan ng Magdala.
Samantala, si Saulo na may masidhing pagbabanta ng kamatayan laban sa mga alagad ng Panginoon ay pumunta sa pinakapunong pari.
sapagkat ako'y hinirang niya upang ipangaral ang magandang balita sa mga dukha.
Magbatian ang isa't isa ng banal na halik.
sapagkat hindi pa ito dumarating sa kaninuman sa kanila, kundi sila'y nabautismuhan lamang sa pangalan ng Panginoong Jesus.
Kumain ng manna sa ilang ang inyong mga ninuno, at sila'y namatay.
Ngunit nang mabalitaan ni Jacob na may trigo sa Ehipto, sinugo niyang una ang ating mga ninuno.
Ngunit ang maraming nauuna ay mahuhuli, at ang huli ay mauuna.”
Humingi siya sa pinakapunong pari ng mga sulat para sa mga sinagoga sa Damasco upang kung siya'y makatagpo ng sinumang kabilang sa Daan, mga lalaki o mga babae, ay dadalhin niya silang nakagapos sa Jerusalem.
At tayong lahat, na walang talukbong ang mukha, na nakikita ang kaluwalhatian ng Panginoon gaya ng sa isang salamin, ay nababago sa gayunding larawan, mula sa kaluwalhatian tungo sa kaluwalhatian, sapagkat ito ay mula sa Panginoon na siyang Espiritu.
Katotohanang sinasabi ko sa inyo, ang nakikinig ng aking salita at sumasampalataya sa kanya na nagsugo sa akin ay may buhay na walang hanggan, at hindi darating sa kahatulan kundi lumipat na sa buhay mula sa kamatayan.
“Sinasabi ko sa iyo, tumayo ka, damputin mo ang iyong higaan, at umuwi ka.”
Sinabi niya ang mga bagay na ito sa sinagoga, samantalang siya'y nagtuturo sa Capernaum.
Katotohanang sinasabi ko sa inyo, hindi lilipas ang lahing ito, hanggang sa maganap ang lahat ng mga bagay na ito.
Ngunit upang malaman ninyo na ang Anak ng Tao ay may awtoridad sa lupa na magpatawad ng mga kasalanan”—sinabi niya sa lumpo—
Sapagkat ang pangangasiwa sa paglilingkod na ito ay hindi lamang pumupuno sa pangangailangan ng mga banal, kundi umaapaw rin sa pamamagitan ng maraming pasasalamat sa Diyos.
Sa halip, ang bagong alak ay dapat ilagay sa mga bagong sisidlang balat.
‘Ang langit ang aking luklukan,
Nang makita ng mga tao ang tandang ginawa niya ay kanilang sinabi, “Totoong ito nga ang propeta na darating sa sanlibutan.”
Subalit kung paanong siya'y nakakakita ngayon, ay hindi namin alam, o kung sino ang nagbukas ng kanyang mga mata, ay hindi namin kilala. Tanungin ninyo siya, siya'y may sapat na gulang na, at siya'y magsasalita para sa kanyang sarili.”
Samantala, ang iba ay sumisigaw ng isang bagay, at ang ilan ay iba naman, sapagkat ang kapulungan ay nasa kaguluhan at hindi nalalaman ng karamihan kung bakit sila'y nagkakatipon.
Pagpasok nila sa bahay ay nakita nila ang sanggol na kasama ng kanyang inang si Maria. Nagpatirapa sila at sumamba sa kanya. Nang buksan nila ang kanilang mga kayamanan ay inihandog nila sa kanya ang mga kaloob na ginto, kamanyang at mira.
Katotohanang sinasabi ko sa inyo, may ilan sa nakatayo rito, na hindi makakatikim ng kamatayan, hanggang makita nila ang Anak ng Tao na dumarating sa kanyang kaharian.”
Habang kanilang dinadala siyang papalayo, hinuli nila si Simon na taga-Cirene na nanggaling sa bukid, at ipinasan sa kanya ang krus upang dalhin kasunod ni Jesus.
At pagdating nito ay natagpuan nitong nawalisan at maayos na.
na ipinain ang kanilang leeg para sa aking buhay, sa kanila'y hindi lamang ako ang nagpapasalamat, kundi pati ang lahat ng mga iglesya ng mga Hentil.
Ikaw na nagsasabing huwag mangalunya, nangangalunya ka ba? Ikaw na nasusuklam sa mga diyus-diyosan, ninanakawan mo ba ang mga templo?
Siya'y sumigaw at sinabi, ‘Amang Abraham, maawa ka sa akin, at suguin mo si Lazaro, upang itubog niya sa tubig ang dulo ng kanyang daliri, at palamigin ang aking dila, sapagkat naghihirap ako sa apoy na ito.’
Ang kanyang awa ay sa mga natatakot sa kanya
Aking nakita at pinatotohanan kong ito ang Anak ng Diyos.”
Ngunit kung ang Espiritu niyaong bumuhay na muli kay Jesus ay nananatili sa inyo, siya na bumuhay na muli kay Cristo mula sa mga patay ay magbibigay ng buhay sa inyong mga katawang may kamatayan, sa pamamagitan ng kanyang Espiritu na naninirahan sa inyo.
[
Sumagot si Jesus, “Kung nalalaman mo ang kaloob ng Diyos, at kung sino ang sa iyo'y nagsasabi, ‘Bigyan mo ako ng inumin;’ ikaw ay hihingi sa kanya, at ikaw ay bibigyan niya ng tubig na buháy.”
Subalit bago mangyari ang lahat ng mga bagay na ito ay pagbubuhatan nila kayo ng kanilang mga kamay at uusigin. Dadalhin kayo sa mga sinagoga, sa mga bilangguan at ihaharap kayo sa mga hari at mga gobernador dahil sa aking pangalan.
Nabalitaan ito ni Haring Herodes, sapagkat ang pangalan ni Jesus ay naging tanyag. Sinasabi ng iba, “Si Juan na Tagapagbautismo ay muling nabuhay mula sa mga patay at dahil dito, gumagawa ang mga kapangyarihang ito sa kanya.”
Ngunit nang marinig ng binata ang ganitong salita, umalis siyang nalulungkot, sapagkat napakarami niyang ari-arian.
Sinagot sila ni Jesus, “Dumating na ang oras upang ang Anak ng Tao ay luwalhatiin.
Dahil dito, akong si Pablo ay bilanggo ni Cristo Jesus alang-alang sa inyong mga Hentil,—
“O Jerusalem, Jerusalem, na pumapatay ng mga propeta at bumabato sa mga isinusugo sa kanya! Makailang ulit kong ninais na tipunin ang iyong mga anak, na gaya ng pagtitipon ng inahing manok sa kanyang mga sisiw sa ilalim ng kanyang mga pakpak, at ayaw ninyo!
Ngunit sinabi sa kanya ni Jesus, “Sumunod ka sa akin; at hayaan mong ang mga patay ang maglibing sa sarili nilang mga patay.”
At siya'y binigyan nila ng alak na hinaluan ng mira, ngunit hindi niya tinanggap iyon.
At pagkaraan ng mga araw na ito, naghanda kami at umahon patungo sa Jerusalem.
Kaya't kayo'y maging handa at alalahanin ninyo na sa loob ng tatlong taon ay hindi ako tumigil sa gabi at araw ng pagbibigay-babala na may pagluha sa bawat isa.
Sinabi nila sa kanya, “Panginoon, mabuksan nawa ang mga mata namin.”
Kaya't tumakbo si Felipe doon, at kanyang narinig na binabasa niya si Isaias na propeta, at sinabi niya, “Nauunawaan mo ba ang binabasa mo?”
at ang hindi nagpapasan ng kanyang krus at sumusunod sa akin ay hindi karapat-dapat sa akin.
Nang panahong iyon, inilapat ni Herodes ang kanyang mga kamay upang pagmalupitan ang ilan sa mga kaanib ng iglesya.
At muli,
At habang nagsasalita pa siya, dumating si Judas, na isa sa labindalawa, at kasama niya ang napakaraming tao na may mga tabak at mga pamalo, mula sa mga punong pari at sa matatanda ng bayan.
Sinabi niya sa kanila, “Kayo'y mga taga-ibaba, ako'y taga-itaas. Kayo'y mga taga-sanlibutang ito; ako'y hindi taga-sanlibutang ito.
Nang magkagayo'y umalis siya sa lupain ng mga Caldeo at nanirahan sa Haran. At mula roon, pagkamatay ng kanyang ama, ay inilipat siya ng Diyos sa lupain na inyong tinitirhan ngayon.
At sinabi niya, “Walang sinuman, Panginoon.” Sinabi ni Jesus, “Hindi rin kita hinahatulan. Humayo ka na at mula ngayo'y huwag ka nang magkasala.” ]
At sinagot siya ng anghel, “Ako si Gabriel na tumatayo sa harapan ng Diyos. Ako'y sinugo upang makipag-usap at ipahayag sa iyo itong magandang balita.
Nagkaroon ng isang pagtatalo sa kanila kung sino sa kanila ang pinakadakila.
Kaya't tumindig si Pablo sa gitna ng Areopago, at sinabi, “Mga lalaking taga-Atenas, napapansin ko na sa lahat ng bagay kayo'y lubhang relihiyoso.
Ngayon, kalabisan na para sa akin na sulatan kayo tungkol sa paglilingkod para sa mga banal,
Ang may pandinig ay makinig.
Kaya't mamunga kayo ng karapat-dapat sa pagsisisi at huwag ninyong sabihin sa inyong sarili, ‘Si Abraham ang aming ama.’ Sapagkat sinasabi ko sa inyo na magagawa ng Diyos na magbangon mula sa mga batong ito ng magiging anak ni Abraham.
At hindi siya nagsalita sa kanila maliban sa talinghaga ngunit sa kanyang sariling mga alagad ay sarilinan niyang ipinapaliwanag ang lahat ng mga bagay.
Sapagkat kung paanong sumasagana sa atin ang mga pagdurusa ni Cristo, sa pamamagitan ni Cristo ay sumasagana rin sa atin ang kaaliwan.
Kunin mo ang para sa iyo at umalis ka na. Nais kong ibigay sa huling nagtrabaho ang kagaya ng ibinigay ko sa iyo.
Si Jesus ay muling nagsalita sa kanila sa mga talinghaga, na sinasabi,
hindi ako tumitigil ng pagpapasalamat para sa inyo, na binabanggit kayo sa aking mga panalangin,
Nang dumarami ang nagkakatipong mga tao, nagsimula siyang magsalita, “Ang lahing ito'y isang masamang lahi. Ito'y humahanap ng isang tanda, subalit walang tanda na ibibigay dito maliban sa tanda ni Jonas.
Sapagkat kung ikaw nga na pinutol mula sa likas na olibong ligaw, at salungat sa kalikasan, ay isinanib ka sa pinayabong na punong olibo; gaano pa nga ang mga ito, na mga likas na sanga na maisasanib sa kanilang sariling punong olibo?
At mula sa kanyang kapuspusan ay tumanggap tayong lahat, biyaya na sinundan pa ng ibang biyaya.
Ngunit maraming nakakita sa kanilang pag-alis at sila'y nakilala. Kaya't tumakbo sila mula sa lahat ng mga bayan at nauna pang dumating sa kanila.
Subalit tungkol sa Israel ay sinasabi niya, “Sa buong araw ay iniunat ko ang aking mga kamay sa isang suwail at mapagsalungat na bayan.”
‘Ang batong itinakuwil ng mga nagtayo ng gusali,
Sa lugar ng pinagpakuan sa kanya ay may isang halamanan, at sa halamana'y may isang bagong libingan na kailanma'y hindi pa nalalagyan ng sinuman.
Ngunit sila'y tumahimik, sapagkat sa daan ay pinagtatalunan nila kung sino ang pinakadakila.
Siya'y sumusunod kay Pablo at sa amin, na sumisigaw, “Ang mga taong ito ay mga alipin ng Kataas-taasang Diyos, na nagpapahayag sa inyo ng daan ng kaligtasan.”
Ngunit ang bangka ng mga sandaling iyon ay malayong-malayo na sa dalampasigan na hinahampas ng mga alon, sapagkat pasalungat sa kanila ang hangin.
at ang lahat ng mga kapatid na kasama ko,
Ngunit samantalang natutulog ang mga tao, dumating ang kaaway at naghasik ng mga damo sa triguhan, at umalis.
Nang malaman ng maraming mga Judio na siya'y naroroon, sila'y pumunta hindi dahil kay Jesus lamang, kundi upang makita nila si Lazaro, na muling binuhay mula sa mga patay.
At aking isinulat ang bagay na ito, upang pagdating ko ay huwag akong magkaroon ng kalungkutan mula doon sa mga nararapat magpagalak sa akin, sapagkat nakakatiyak ako sa inyong lahat na ang aking kagalakan ay magiging kagalakan ninyong lahat.
tuwirin ninyo ang kanyang mga landas.’”
Nang sila'y makapagtalaga ng isang araw para sa kanya, nagtungo sila sa kanyang tinutuluyan at napakarami nila. Ipinaliwanag niya sa kanila ang pangyayari buhat umaga hanggang gabi na nagpapatotoo tungkol sa kaharian ng Diyos, at sinikap na sila'y mahikayat tungkol kay Jesus, mula sa kautusan ni Moises at mula sa mga propeta.
at kung kayo'y aking tanungin ay hindi kayo sasagot.
Si Pilato ay muling lumabas at sa kanila'y sinabi, “Tingnan ninyo, ilalabas ko siya sa inyo upang inyong malaman na wala akong nakitang anumang kasalanan sa kanya.”
Siya'y kinuha nila at dinala sa Areopago, at tinanong, “Maaari ba naming malaman kung ano itong bagong aral na sinasabi mo?
at si Judas na anak ni Santiago, at si Judas Iscariote na naging taksil.
Sinabi sa kanila ni Jesus, “Hindi ba't ito ang dahilan kaya kayo nagkakamali, hindi ninyo nalalaman ang mga kasulatan, o ang kapangyarihan ng Diyos?
Bagama't gumawa siya sa harapan nila ng maraming mga tanda, sila ay hindi naniwala sa kanya;
Ngunit sumagot siya at sinabi, ‘Ayaw ko’; ngunit pagkatapos ay nagbago ang kanyang isip at pumunta rin.
tunay na ang kasalanan ay nasa sanlibutan bago pa dumating ang kautusan, ngunit hindi ibinibilang ang kasalanan kung walang kautusan.
Isang gabi, sinabi ng Panginoon kay Pablo sa isang pangitain, “Huwag kang matakot, kundi magsalita ka, at huwag kang tumahimik;
Kaya't yamang tayo'y inaring-ganap sa pamamagitan ng pananampalataya, mayroon tayong kapayapaan sa Diyos sa pamamagitan ng ating Panginoong Jesu-Cristo.
Lahat ng ito ay mula sa Diyos, na tayo'y pinagkasundo niya sa kanyang sarili sa pamamagitan ni Cristo, at ibinigay niya sa amin ang ministeryo ng pakikipagkasundo.
“At pagkatapos ng paghihirap sa mga panahong iyon ay magdidilim ang araw, at ang buwan ay hindi magbibigay ng kanyang liwanag, at mahuhulog ang mga bituin mula sa langit, at yayanigin ang mga kapangyarihan sa langit.
Ako ang pintuan. Ang sinumang pumasok sa pamamagitan ko ay maliligtas, at papasok at lalabas, at makakatagpo ng pastulan.
at sinabi niya sa kanila, ‘Pumunta rin kayo sa ubasan, at anumang nararapat ay ibibigay ko sa inyo.’ At pumunta sila.
Tingnan ninyo ang mga ibon sa himpapawid: hindi sila naghahasik, o gumagapas, o nag-iimbak man sa mga kamalig, ngunit pinapakain sila ng inyong Ama na nasa langit. Hindi ba higit na mahalaga kayo kaysa kanila?
At sinabi niya, “Ang may taingang pandinig ay makinig.”
At sinabi ng Panginoon, “Sino nga ba ang tapat at matalinong katiwala na pagkakatiwalaan ng kanyang panginoon sa kanyang mga alipin, upang sila'y bigyan ng kanilang bahaging pagkain sa tamang panahon?
Noon ay nagtuturo siya sa isa sa mga sinagoga nang araw ng Sabbath.
Dinala rin ito ng ating mga ninuno na kasama ni Josue nang kanilang sakupin ang mga bansa na pinalayas ng Diyos sa harapan ng ating mga ninuno. Ito ay nanatili roon hanggang sa mga araw ni David,
At sinabi niya sa kanila, “Hindi ba ninyo nalalaman ang talinghagang ito? Paano nga ninyo mauunawaan ang lahat ng mga talinghaga?
Sapagkat silang lahat ay naglagay mula sa kanilang kasaganaan, samantalang siya mula sa kanyang kahirapan ay inilagay ang lahat ng kanyang kabuhayan.”
At hindi lamang gayon, kundi nagagalak rin tayo sa ating mga kapighatian sa pagkaalam na ang kapighatian ay nagbubunga ng pagtitiis,
Purihin nawa ang Diyos at Ama ng ating Panginoong Jesu-Cristo, na siyang nagpapala sa atin kay Cristo ng bawat pagpapalang espirituwal sa sangkalangitan,
Dumating ang mga Fariseo at upang subukin siya ay kanilang itinanong, “Ipinahihintulot ba sa lalaki na makipaghiwalay sa kanyang asawa?”
na nagsasabi, ‘Huwag kang matakot, Pablo. Kailangan mong humarap kay Cesar. At tunay na ipinagkaloob ng Diyos ang kaligtasan sa lahat ng kasama mo sa paglalayag.’
Nahikayat ang ilan sa kanila at sumama kina Pablo at kay Silas, gayundin ang napakaraming mga Griyegong masisipag sa kabanalan, at hindi kakaunting mga pangunahing babae.
‘ang bato na itinakuwil ninyong mga tagapagtayo
Hinirang ng Diyos nitong bayang Israel ang ating mga ninuno, at ginawang dakila ang bayan nang sila'y nakipamayan sa Ehipto, at sa pamamagitan ng nakataas na bisig ay kanyang inilabas sila roon.
at aasa ang mga Hentil sa kanyang pangalan.”
Sapagkat sinabi ng Diyos, ‘Igalang mo ang iyong ama at ang iyong ina;’ at ‘Ang magsalita ng masama sa ama o sa ina, ay dapat mamatay.’
Ang taong ito'y hinuli ng mga Judio, at papatayin sana nila, ngunit nang malaman kong siya'y mamamayan ng Roma dumating ako na may kasamang mga kawal at siya'y iniligtas ko.
Dahil dito'y inusig ng mga Judio si Jesus sapagkat ginagawa niya ang mga bagay na ito sa araw ng Sabbath.
At may isang lalaki mula sa maraming tao ang sumigaw, “Guro, nakikiusap ako sa iyo na tingnan mo ang aking anak na lalaki, sapagkat siya'y aking kaisa-isang anak.
At sinabi niya, ‘Kung gayo'y ipinapakiusap ko sa iyo, ama, na isugo mo siya sa bahay ng aking ama,
na sinasabi, “Naganap na ang panahon at malapit na ang kaharian ng Diyos: kayo'y magsisi at manampalataya sa ebanghelyo.”
At siya'y tumanggap ng isang kopa at nang siya'y makapagpasalamat, sinabi niya, “Kunin ninyo ito, at inyong paghati-hatian.
At bigla na lamang sa kanilang sinagoga ay may isang tao na may masamang espiritu; at siya'y sumigaw,
Subalit si Judas Iscariote, isa sa kanyang mga alagad na magkakanulo sa kanya, ay nagsabi,
at ito'y kamanghamangha sa ating mga mata?’
Pagkatapos ay sasagot din sila, na nagsasabi, ‘Panginoon, kailan ka namin nakitang gutom, o uhaw, o isang taga-ibang bayan, o hubad, o maysakit, o nasa bilangguan, at hindi ka namin pinaglingkuran?’
Sumagot siya, “Ang taong tinatawag na Jesus ay gumawa ng putik, at pinahiran ang aking mga mata, at sinabi sa akin, ‘Pumunta ka sa Siloam, at maghugas ka.’ Kaya't ako'y umalis at naghugas, at nagkaroon ako ng paningin.”
Akong si Tercio, na sumusulat ng sulat na ito, ay bumabati sa inyo sa Panginoon.
Ang mga ito'y lumapit kay Felipe, na taga-Bethsaida ng Galilea, at sinabi sa kanya, “Ginoo, ibig sana naming makita si Jesus.”
Pagkaraan ng tatlong araw, pagkarating ni Festo sa lalawigan, pumunta siya sa Jerusalem mula sa Cesarea,
Sinabi niya sa kanila, “Sumunod kayo sa akin at gagawin ko kayong mga mamamalakaya ng mga tao.”
sa ilalim ng iyong mga paa.”’
Subalit sumagot siya sa kanyang ama, ‘Tingnan mo, maraming taon nang ako'y naglingkod sa iyo, at kailanma'y hindi ako sumuway sa iyong utos. Gayunman ay hindi mo ako binigyan kailanman ng kahit isang batang kambing upang makipagsaya sa aking mga kaibigan.
at makaunawa ang puso nila,
Tumayo sa harapan nila ang pinakapunong pari at tinanong si Jesus, “Wala ka bang isasagot? Ano itong pinatotohanan nila laban sa iyo?”
Sinabi sa kanya ni Jesus, “Umalis ka na! Tawagin mo ang iyong asawa at bumalik ka rito.”
“Purihin ang Panginoon, ang Diyos ng Israel,
Bumangon kayo, lumakad tayo. Masdan ninyo, malapit na ang nagkakanulo sa akin.”
umalis siya sa Judea at muling bumalik sa Galilea.
Ang maraming tao ay nagkakaisang nakikinig sa mga sinabi ni Felipe nang kanilang marinig siya at nakita ang mga tanda na ginawa niya.
at makaunawa sa pamamagitan ng kanilang puso, at magbalik-loob,
Habang patungo sa Jerusalem, si Jesus ay dumaan sa pagitan ng Samaria at Galilea.
at alalahanin ang kanyang banal na tipan,
Pagkatapos na siya'y magdusa ay buháy siyang nagpakita sa kanila sa pamamagitan ng maraming mga katunayan. Nagpakita siya sa kanila sa loob ng apatnapung araw at nagsalita ng mga bagay tungkol sa kaharian ng Diyos.
Ito ang tinapay na bumababang galing sa langit, upang ang sinumang makakain nito ay hindi mamatay.
Kaya mga kapatid, pumili kayo sa inyo ng pitong lalaking may mabuting pagkatao, puspos ng Espiritu at ng karunungan, na aming maitatalaga sa tungkuling ito,
Ngayon pa lamang ay nakalagay na ang palakol sa ugat ng mga punungkahoy. Kaya't ang bawat punungkahoy na di mabuti ang bunga ay pinuputol at itinatapon sa apoy.”
Hindi ba ninyo nalalaman na kung kanino ninyo inihahandog ang inyong mga sarili bilang alipin sa pagsunod, kayo'y mga alipin niya na inyong sinusunod; maging ng kasalanan tungo sa kamatayan, o ng pagsunod tungo sa pagiging matuwid?
Kaya't sumagot si Jesus at sinabi sa kanila, “Katotohanang sinasabi ko sa inyo, hindi makakagawa ng anuman ang Anak sa kanyang sarili kundi ang nakikita niyang ginagawa ng Ama. Sapagkat ang lahat ng mga bagay na kanyang ginagawa ay siya ring ginagawa ng Anak.
At sinabi ng mga hangal sa matatalino, ‘Bigyan ninyo kami ng inyong langis, sapagkat namamatay na ang aming mga ilawan.’
Sapagkat ako'y nagagalak sa kautusan ng Diyos sa kaibuturan ng aking pagkatao.
Nagdala nga sila ng isa at sinabi niya sa kanila, “Kaninong larawan at pangalan ang nakaukit?” Sinabi nila sa kanya, “Kay Cesar.”
Sumagot si Jesus sa kanya, “Ang ginagawa ko'y hindi mo pa nauunawaan ngayon, ngunit malalaman mo pagkatapos ng mga ito.”
Pansinin ninyo ang mga uwak. Hindi sila naghahasik, ni gumagapas man. Sila'y walang imbakan ni kamalig man, subalit sila'y pinapakain ng Diyos. Gaano pang higit kayong mahalaga kaysa mga ibon!
Katotohanang sinasabi ko sa iyo, hindi ka makakalabas doon hanggang hindi mo nababayaran ang kahuli-hulihang kusing.
Sapagkat sa biyaya kayo'y naligtas sa pamamagitan ng pananampalataya, at ito'y hindi sa pamamagitan ng inyong sarili, ito'y kaloob ng Diyos;
Subalit hindi ninyo siya kilala, ngunit kilala ko siya. Kung aking sasabihing hindi ko siya kilala ay magiging katulad ninyo ako na sinungaling. Subalit kilala ko siya, at tinutupad ko ang kanyang salita.
Ang nakararami sa mga tao ay naglatag ng kanilang mga balabal sa daan, at ang iba'y pumutol ng mga sanga ng mga punungkahoy at inilatag ang mga ito sa daan.
at huwag bigyan ng pagkakataon ang diyablo.
Pumasok siya sa Jerusalem at pumunta sa templo. Nang matingnan niya sa palibot ang lahat ng bagay, palibhasa'y hapon na, pumunta siya sa Betania na kasama ang labindalawa.
Nang gumagabi na, lumapit sa kanya ang kanyang mga alagad at nagsabi, “Ito ay isang ilang na dako at gumagabi na.
Sinabi niya, “Sino ka, Panginoon?” At siya'y sumagot, “Ako si Jesus na iyong inuusig.
Baka sa bigla niyang pagdating ay matagpuan niya kayong natutulog.
sapagkat ang namatay ay pinalaya na mula sa kasalanan.
Sinasabi ko nga, itinakuwil ba ng Diyos ang kanyang bayan? Huwag nawang mangyari. Sapagkat ako man ay Israelita, mula sa binhi ni Abraham, mula sa lipi ni Benjamin.
“Panginoon, sino ang naniwala sa aming balita?
subalit kaluwalhatian, karangalan, at kapayapaan sa bawat gumagawa ng mabuti, una'y sa Judio at gayundin sa Griyego:
Sumagot si Juan, “Hindi makakatanggap ng anuman ang isang tao, malibang ito'y ipinagkaloob sa kanya mula sa langit.
“Bumalik ka sa iyong bahay at isalaysay mo ang lahat ng mga ginawa ng Diyos para sa iyo.” At siya'y umalis na ipinahahayag sa buong lunsod ang lahat ng mga ginawa ni Jesus sa kanya.
Sinabi niya sa kanila, “Kapag kayo'y nananalangin, inyong sabihin,
na dati ninyong nilakaran, ayon sa lakad ng sanlibutang ito, ayon sa pinuno ng kapangyarihan ng himpapawid, ng espiritu na ngayon ay gumagawa sa mga anak ng pagsuway.
Subalit sinabi sa kanya ni Jesus, “Walang sinumang humahawak sa araro at tumitingin sa mga nasa likuran ang karapat-dapat sa kaharian ng Diyos.”
Nagturo siya at sinabi, “Hindi ba nasusulat, ‘Ang aking bahay ay tatawaging bahay-panalanginan para sa lahat ng mga bansa?’ Ngunit ginawa ninyo itong yungib ng mga magnanakaw.”
“Ang tinig ng isang sumisigaw sa ilang:
Kayo'y manatili sa akin, at ako'y sa inyo. Gaya ng sanga na hindi magbubunga buhat sa kanyang sarili malibang nakakabit sa puno, gayundin naman kayo, malibang kayo'y manatili sa akin.
At huwag ninyong laging hanapin kung ano ang inyong kakainin, kung ano ang inyong iinumin, at huwag kayong mabalisa.
at muli kong itatayo ang tolda ni David na bumagsak;
Subalit nang makaahon na ang kanyang mga kapatid para sa pista, saka naman siya umahon, hindi hayagan kundi palihim.
Sinabi niya, ‘Cornelio, dininig ang dalangin mo, at ang iyong mga limos ay inalala sa harapan ng Diyos.
Kaya't sinabi ni Jesus kay Pedro, “Ibalik mo ang iyong tabak sa kaluban. Hindi ko ba iinuman ang kopang ibinigay sa akin ng Ama?”
Sapagkat ito ang kalooban ng aking Ama, na ang bawat nakakakita sa Anak at sa kanya'y sumampalataya ay magkaroon ng buhay na walang hanggan, at muli ko siyang bubuhayin sa huling araw.”
Tumakbo ang isa, binasa ng suka ang isang espongha, inilagay sa isang tungkod, at ipinainom sa kanya na sinasabi, “Pabayaan ninyo; tingnan natin kung darating si Elias upang siya'y ibaba.”
na lubhang nayayamot sapagkat nagtuturo sila sa mga tao, at nagpapahayag na kay Jesus ay may muling pagkabuhay sa mga patay.
“Tulad ng tupa na dinala sa katayan;
Kung ang masang inialay bilang unang bunga ay banal, ay gayundin ang buong limpak; at kung ang ugat ay banal, gayundin ang mga sanga.
Sapagkat kay Cristo Jesus, ang pagtutuli o di-pagtutuli ay walang kabuluhan, kundi ang pananampalataya na gumagawa sa pamamagitan ng pag-ibig.
Nang makita ng senturion at ng mga kasamahan niyang nagbabantay kay Jesus ang lindol at ang mga bagay na nangyari, sila'y lubhang natakot, at nagsabi, “Tunay na ito ang Anak ng Diyos.”
At may tinig na nanggaling sa ulap na nagsasabi, “Ito ang aking Anak, ang aking Pinili, makinig kayo sa kanya!”
At sinabi nila sa isa't isa, “Ito ay sapagkat wala tayong tinapay.”
At sinabi niya sa kanila, “Ang sinumang makipaghiwalay sa kanyang asawang babae at mag-asawa sa iba ay nagkakasala ng pangangalunya laban sa kanya.
Pagkatapos ay kinuha ni Pilato si Jesus at siya'y hinagupit.
Ngunit kahabag-habag ang mga buntis at ang mga nagpapasuso sa mga araw na iyon!
Kaya't sila'y pinatuloy niya at naging kanyang panauhin. Nang sumunod na araw, bumangon siya at umalis na kasama nila, at siya'y sinamahan ng ilang kapatid mula sa Joppa.
Nagsalaysay siya sa kanila ng isang talinghaga: “Ang lupain ng taong mayaman ay namunga ng sagana.
maliban na ang Espiritu Santo ay nagpapatotoo sa akin sa bawat lunsod, na sinasabing ang mga tanikala at ang kapighatian ay naghihintay sa akin.
Pagpasok niya sa templo, lumapit sa kanya ang mga punong pari at ang matatanda ng bayan habang siya'y nagtuturo, at sinabi nila, “Sa anong awtoridad mo ginagawa ang mga bagay na ito, at sino ang nagbigay sa iyo ng awtoridad na ito?”
“Mapapalad ang mga dukha sa espiritu, sapagkat kanila ang kaharian ng langit.
Siya'y lumukso, tumayo at nagpalakad-lakad; pumasok siya sa templo na kasama nila, lumalakad, lumulukso, at nagpupuri sa Diyos.
Ang dahilan kung bakit ang maraming tao ay sumalubong sa kanya ay sapagkat nabalitaan nila na ginawa niya ang tandang ito.
Tumingin siya sa buong paligid upang makita kung sino ang gumawa niyon.
Magbigay kayo at iyon ay ibibigay sa inyo—hustong takal, siniksik, niliglig, at umaapaw, ang ilalagay nila sa inyong kandungan. Sapagkat sa panukat na inyong ipanukat ay doon din kayo susukatin.
Subalit sinabi niya sa kanila, “Bigyan ninyo sila ng makakain.” At sinabi nila, “Mayroon tayong hindi hihigit sa limang tinapay at dalawang isda, malibang kami'y umalis at bumili ng pagkain para sa lahat ng mga taong ito.”
ay sinabi niya sa malakas na tinig, “Tumindig ka nang matuwid sa iyong mga paa.” At ang lalaki ay lumukso at nagpalakad-lakad.
Ngunit kung dinadamitan ng Diyos nang ganito ang damo sa parang na ngayon ay buháy, at sa kinabukasan ay itinatapon sa pugon, gaano pa kaya kayo na kanyang dadamitan, O kayong maliliit ang pananampalataya?
Ipinangangaral namin sa inyo ang mabuting balita ng pangako ng Diyos sa ating mga ninuno,
at isinulat sa pamamagitan ng kamay nila:
Labis na namangha ang lahat at niluwalhati nila ang Diyos. Napuno sila ng takot, na nagsasabi, “Nakakita kami ngayon ng mga bagay na kataka-taka.”
Kayo'y sinugo ko upang anihin ang hindi ninyo pinagpaguran; iba ang nagpagod at kayo'y pumasok sa kanilang pinagpaguran.”
Nang kami'y makaligtas na, noon namin nalaman na ang pulo ay tinatawag na Malta.
Kayo'y malilinis na sa pamamagitan ng salita na aking sinabi sa inyo.
Bumaba siya na kasama nila at tumayo sa isang patag na lugar. Naroon ang marami sa kanyang mga alagad at ang napakaraming tao buhat sa Judea at sa Jerusalem at sa baybayin ng Tiro at Sidon, na pumaroon upang makinig sa kanya at mapagaling sa kanilang mga sakit;
At sinabi niya, “Mag-ingat kayo na hindi kayo mailigaw, sapagkat marami ang darating sa aking pangalan, na magsasabi, ‘Ako siya!’ at, ‘Malapit na ang panahon!’ Huwag kayong sumunod sa kanila.
tayo'y naging katulad sana ng Sodoma,
at sila'y aking pagalingin.’
hindi gaya ni Moises, na naglagay ng talukbong sa kanyang mukha upang hindi makita ng mga anak ni Israel ang katapusan ng bagay na lumilipas.
Ako ang puno ng ubas, kayo ang mga sanga. Ang nananatili sa akin at ako'y sa kanya ay siyang nagbubunga ng marami. Sapagkat kung kayo'y hiwalay sa akin ay wala kayong magagawa.
Noon ay nag-aayuno ang mga alagad ni Juan at ang mga Fariseo. Sila'y lumapit at sinabi sa kanya, “Bakit nag-aayuno ang mga alagad ni Juan at ang mga alagad ng mga Fariseo, ngunit hindi nag-aayuno ang iyong mga alagad?”
naging anak ni Asaf si Jehoshafat; naging anak ni Jehoshafat si Joram; at naging anak ni Joram si Uzias;
Katotohanang sinasabi ko sa inyo, dumarating ang oras at ngayon na nga, na maririnig ng patay ang tinig ng Anak ng Diyos at ang makarinig ay mabubuhay.
at pinakasalan ng pangatlo ang babae, at namatay ang pito na pawang walang iniwang anak.
Kung tinatawag nga siya ni David na Panginoon, paanong siya'y naging kanyang anak?”
At si Isaias ay buong tapang na nagsasabi,
At kung saan siya pumasok, sabihin ninyo sa may-ari ng bahay, na sinasabi ng Guro, ‘Nasaan ang aking silid-tuluyan na kung saan maaari kong kainin ang kordero ng Paskuwa na kasalo ng aking mga alagad?’
siya ang babangon upang maghari sa mga Hentil;
Nagpatotoo si Juan tungkol sa kanya at sumigaw, “Siya yaong aking sinasabi, ‘Ang dumarating na kasunod ko ay naging una sa akin sapagkat siya'y nauna sa akin.’”
Ako'y taga-ibang bayan, at hindi ninyo ako pinatuloy. Hubad, at hindi ninyo ako dinamitan; maysakit at nasa bilangguan, at hindi ninyo dinalaw.’
Tatlong ulit na ako'y hinampas ng mga pamalo, minsan ako'y pinagbabato. Tatlong ulit na akong nawasakan ng barko, isang araw at isang gabing ako'y nasa laot;
Nang sumasakay na siya sa bangka, ang lalaking inalihan ng mga demonyo ay nakiusap na siya'y isama niya.
Bagama't ibig niyang ipapatay si Juan, natakot siya sa mga tao sapagkat kanilang itinuturing si Juan na isang propeta.
Kayo na ang pumunta sa pista. Ako'y hindi pupunta sa pistang ito, sapagkat hindi pa dumating ang aking oras.”
Ngunit sila'y sinagot niya, “Ang nagpagaling sa akin ang siyang nagsabi sa akin, ‘Buhatin mo ang iyong higaan, at lumakad ka.’”
Sapagkat si David, pagkatapos niyang maglingkod ayon sa kalooban ng Diyos sa kanyang sariling salinlahi, ay namatay at isinama sa kanyang mga ninuno, at nakakita ng pagkabulok.
Iniisip ninyo na sa buong panahon ay ipinagtatanggol namin ang aming sarili sa harapan ninyo. Sa paningin ng Diyos kami ay nagsasalita kay Cristo. At ang lahat ng mga bagay ay para sa inyong ikatitibay, mga minamahal.
O Teofilo, sa unang aklat ay isinulat ko ang tungkol sa lahat ng ginawa at itinuro ni Jesus mula sa simula,
Nakita rin niya ang isang mahirap na babaing balo na naglalagay ng dalawang kusing.
Kaya't ang Anak ng Tao ay Panginoon maging ng Sabbath.”
Nang kanyang mabatid ito, pumunta siya sa bahay ni Maria, ang ina ni Juan na tinatawag na Marcos, na kinaroroonan ng maraming nagkakatipon at nananalangin.
na sinasabi, “Ang mga eskriba at ang mga Fariseo ay umuupo sa upuan ni Moises.
upang mapatunayan sa panahong kasalukuyan na siya'y matuwid at upang siya'y maging ganap at taga-aring-ganap sa taong mayroong pananampalataya kay Jesus.
Yamang aming nabalitaan na ang ilang tao mula sa amin ay nagsabi ng mga bagay upang bagabagin kayo at ginugulo ang inyong mga isip gayong hindi namin sila binigyan ng tagubilin,
Nang si Pablo ay tawagin, sinimulan siyang paratangan ni Tertulio, na sinasabi,
Sumusunod sa kanya ang napakaraming tao sapagkat nakita nila ang mga tanda na ginagawa niya sa mga maysakit.
Nagalak ang inyong amang si Abraham na makita niya ang aking araw. Nakita niya ito at siya'y nagalak.”
Sumampalataya kayo sa akin na ako'y nasa Ama at ang Ama ay nasa akin. Subalit kung hindi ay sumampalataya kayo sa akin dahil sa mga gawa.
At kung ano ang aking ginagawa ay patuloy kong gagawin, upang alisin ang pagkakataon doon sa mga nagnanais ng pagkakataon na kilalanin bilang mga kapantay namin tungkol sa ipinagmamalaki nila.
Ilan sa mga pilosopong Epicureo at Estoico ay nakipagtalo rin sa kanya. At sinabi ng ilan, “Anong nais sabihin ng madaldal na ito?” Sinabi ng iba, “Parang siya'y isang tagapagbalita ng mga ibang diyos”—sapagkat ipinangangaral niya si Jesus at ang pagkabuhay.
Nang kanilang mahalata na sinabi niya ang talinghagang ito laban sa kanila, pinagsikapan nilang hulihin siya, ngunit sila'y natakot sa maraming tao at siya'y iniwan nila at sila'y umalis.
