“Bukod dito'y nagsalita sa akin ang Panginoon , na sinasabi, ‘Aking nakita ang bayang ito, at aking nakita na ito'y isang bayang matigas ang ulo.
sapagkat nalalaman ko na ang kahihinatnan nito'y sa aking ikaliligtas, sa pamamagitan ng inyong mga panalangin at sa saganang tulong ng Espiritu ni Jesu-Cristo.
Huwag kang sisiping sa asawa ng iyong kapwa, at dungisan ang iyong sarili kasama niya.
Subalit kung ayaw ninyo kaming pakinggan na kayo'y matuli, ay kukunin namin ang aming anak na babae at kami ay aalis.”
“Katotohanang sinasabi ko sa inyo, ang pumapasok sa hindi pintuan ng kulungan ng mga tupa kundi umaakyat sa ibang daan, ang taong iyon ay tulisan at magnanakaw.
Sumama ka sa mga lalaking ito, isagawa ninyo ang seremonya ng paglilinis at ipagbayad mo sila para maahit ang kanilang mga ulo. At malalaman ng lahat na walang katotohanan ang mga bagay na kanilang nabalitaan tungkol sa iyo kundi ikaw mismo ay sumasang-ayon sa pagtupad sa kautusan.
Mag-ingat ka rin sa kanya, sapagkat tunay na kanyang sinalungat ang aming ipinangangaral.
At nalalaman ko na pagpunta ko sa inyo, ay darating akong puspos ng pagpapala ng ebanghelyo ni Cristo.
Kung sila'y mag-asawa sa kaninuman sa mga anak ng ibang mga lipi ng mga anak ni Israel ay aalisin ang mana nila na mula sa mana ng aming mga ninuno, at idaragdag sa mana ng lipi na kinabibilangan nila; sa gayo'y aalisin ito sa manang nauukol sa amin.
At muling sinabi niya, “Sa ano ko ihahambing ang kaharian ng Diyos?
walang katutubong pag-ibig, mga walang habag, mga mapanirang-puri, mga walang pagpipigil sa sarili, mababangis, mga hindi maibigin sa mabuti,
Nang makita ng bayan na nagtatagal si Moises ng pagpanaog sa bundok, ay nagtipon ang bayan kay Aaron, at sinabi sa kanya, “Tumindig ka at igawa mo kami ng mga diyos na mangunguna sa amin; sapagkat ang Moises na ito na naglabas sa amin mula sa lupain ng Ehipto, ay hindi namin alam kung ano na ang nangyari sa kanya.”
Nakipaglaban sila sa Midian gaya ng iniutos ng Panginoon kay Moises, at kanilang pinatay ang bawat lalaki.
Ngunit sinabi niya, ‘Huwag; baka sa pagtitipon ninyo ng mga damo ay inyong mabunot pati ang trigo.
Pagkatapos ay sasagutin siya ng mga matuwid, na nagsasabi, ‘Panginoon, kailan ka namin nakitang gutom, at pinakain ka namin, o uhaw, at binigyan ka ng inumin?
Nang bumagsak kaming lahat sa lupa ay narinig ko ang isang tinig na nagsasalita sa akin sa wikang Hebreo, ‘Saulo, Saulo, bakit mo ako inuusig? Makakasakit sa iyo ang sumikad sa matutulis.’
Ibinigay sa akin ng Panginoon ang dalawang tapyas na bato na sinulatan ng daliri ng Diyos. Nasa mga iyon ang lahat ng mga sinabi ng Panginoon sa inyo sa bundok mula sa gitna ng apoy nang araw ng pagtitipon.
Sinabi ng Diyos, “Lalangin natin ang tao sa ating larawan, ayon sa ating wangis; at magkaroon sila ng pamamahala sa mga isda sa dagat, sa mga ibon sa himpapawid, sa mga hayop, sa buong lupa, at sa bawat gumagapang sa ibabaw ng lupa.”
naging anak ni Salmon kay Rahab si Boaz; naging anak ni Boaz kay Ruth si Obed; at naging anak ni Obed si Jesse;
upang mamahala sa araw at sa gabi, at upang ihiwalay ang liwanag sa kadiliman. At nakita ng Diyos na ito ay mabuti.
kundi kayo'y maghahandog sa Panginoon ng isang handog na sinusunog na mabangong samyo; isang batang toro, isang tupang lalaki, pitong korderong lalaki na isang taong gulang, mga walang kapintasan para sa inyo.
Pakiusapan ninyo ang Panginoon , sapagkat nagkaroon na ng sapat na kulog at yelong ulan. Papayagan kong umalis na kayo at hindi na kayo mananatili pa.”
Sa pamamagitan ng tatlong salot na ito ay pinatay ang ikatlong bahagi ng mga tao sa pamamagitan ng apoy at ng usok at ng asupre na lumalabas sa kanilang mga bibig.
Huwag lalapastanganin ng mga pari ang mga banal na bagay ng mga anak ni Israel, na kanilang inihahandog sa Panginoon ;
Ang pamigkis na mainam ang pagkayari na nasa ibabaw ng efod upang ibigkis, ay kaputol at gaya ng pagkayari ng efod—ginto, telang asul, kulay-ube, pula, at hinabing pinong lino; gaya ng iniutos ng Panginoon kay Moises.
ngunit ang mga lamang-loob at ang mga paa ay huhugasan ng tubig. At ihahandog ng pari ang kabuuan at susunugin sa dambana; ito ay isang handog na sinusunog, isang handog na pinaraan sa apoy, na isang mabangong samyo sa Panginoon .
Sa pagbubukas ng isa sa kanyang sako upang bigyan ng pagkain ang kanyang asno sa tuluyan, nakita niya ang kanyang salapi, at nakita niya na ito ay nasa ibabaw ng kanyang sako.
Nang panahong iyon, inilapat ni Herodes ang kanyang mga kamay upang pagmalupitan ang ilan sa mga kaanib ng iglesya.
At nagsalita ang Panginoon kay Moises, na sinasabi,
Kaya't lagi kong hinahangad na ipaalala sa inyo ang mga bagay na ito, bagama't inyong nalalaman na, at kayo'y pinapatibay sa katotohanang dumating sa inyo.
Nang mga araw ni Amrafel, hari ng Shinar, ni Arioc na hari ng Elasar, ni Kedorlaomer na hari ng Elam, at ni Tidal na hari ng mga Goiim,
gayundin naman ang mga ito na ngayon ay naging mga masuwayin upang sa pamamagitan ng habag na ipinakita sa inyo, sila rin ay tumanggap ngayon ng habag.
bukod pa sa handog na sinusunog sa bagong buwan, at sa handog na butil niyon, at sa palagiang handog na sinusunog at sa handog na butil niyon, at sa mga inuming handog niyon, ayon sa kanilang tuntunin na mabangong samyo na handog sa Panginoon na pinaraan sa apoy.
gayundin ang kanilang handog na butil na piling handog na harina na hinaluan ng langis, tatlong ikasampung bahagi ang inyong ihahandog para sa isang toro, at dalawang ikasampung bahagi para sa lalaking tupa;
Huwag ninyong kaliligtaan ang paggawa ng mabuti at ang pamamahagi, sapagkat ang Diyos ay nalulugod sa mga gayong handog.
Si Zaqueo ay tumindig at sinabi sa Panginoon, “Panginoon, ang kalahati ng aking mga pag-aari ay ibinibigay ko sa mga dukha at kung sa pamamagitan ng pandaraya ay may kinuha ako sa kanino mang tao, babayaran ko siya ng apat na ulit.”
At sinabi ni Jesus sa kanya, “Ingatan mong huwag sabihin kaninuman, kundi humayo ka, magpakita ka sa pari, at ihandog mo ang kaloob na ipinag-utos ni Moises bilang patotoo sa kanila.”
Makikipagdigma ang mga ito laban sa Kordero at sila'y dadaigin ng Kordero, sapagkat siya'y Panginoon ng mga panginoon at Hari ng mga hari, at ang mga kasama niya ay mga tinawag, mga hinirang at tapat.”
Unang namatay si Haran kaysa sa kanyang amang si Terah sa lupaing kanyang tinubuan, sa Ur ng mga Caldeo.
Ang ahas nga ay higit na tuso kaysa alinman sa mga mailap na hayop sa parang na nilikha ng Panginoong Diyos. Sinabi niya sa babae, “Sinabi ba ng Diyos, ‘Huwag ninyong kakainin ang mula sa alinmang punungkahoy sa halamanan?’”
Sa oras ding iyon ay tumayo sila at bumalik sa Jerusalem at naratnang nagkakatipon ang labing-isa at ang kanilang mga kasama.
Tumingin siya at nakita niya ang kanyang kapatid na si Benjamin, ang anak ng kanyang ina, at kanyang sinabi, “Ito ba ang inyong bunsong kapatid na inyong sinabi sa akin?” Kanyang sinabi, “Pagpalain ka nawa ng Diyos, anak ko.”
“Kapag ipinanganak ang isang baka, tupa, o kambing, ito ay mananatili sa kanyang ina sa loob ng pitong araw; at mula sa ikawalong araw hanggang sa haharapin ito ay tatanggapin bilang alay, handog na pinaraan sa apoy para sa Panginoon ;
Nang sumapit na ang gabi, sila ay lumabas sa lunsod.
At kakainin ninyo ang laman ng inyong mga anak na lalaki, at kakainin ninyo ang laman ng inyong mga anak na babae.
Ang panahon na nanirahan ang mga anak ni Israel sa Ehipto ay apatnaraan at tatlumpung taon.
At pinagpakitaan niya ng magandang loob si Abram dahil kay Sarai at nagkaroon si Abram ng mga tupa, baka, lalaking asno, aliping lalaki at alilang babae, babaing asno, at mga kamelyo.
At umalis ang Panginoon pagkatapos na makipag-usap kay Abraham at si Abraham ay nagbalik sa kanyang lugar.
“Kung iyong makita ang baka ng iyong kaaway o ang kanyang asno na nakawala, ito ay ibabalik mo sa kanya.
Kaya't si Lot ay lumabas at kinausap ang kanyang mga manugang na noon ay mapapangasawa ng kanyang mga anak na babae, at sinabi, “Tumindig kayo, magsialis kayo sa lugar na ito; sapagkat gugunawin ng Panginoon ang bayan.” Subalit ang akala ng kanyang mga manugang ay nagbibiro siya.
Bawat anak na babae na nagmamay-ari sa anumang lipi ng mga anak ni Israel ay mag-aasawa sa isa sa mga angkan ng lipi ng kanyang ama, upang mapanatili ng bawat isa sa mga anak ni Israel ang mana ng kanyang mga ninuno.
Nagkaanak si Noe ng tatlong lalaki: sina Sem, Ham, at Jafet.
Kanyang sinabi, “Kung ngayo'y nakatagpo ako ng biyaya sa iyong paningin, O Panginoon, ay ipahintulot nawa ng Panginoon, idinadalangin ko sa iyo, na humayo ka sa kalagitnaan namin. Bagaman ang bayang ito ay matigas ang ulo, ipatawad mo ang aming kasamaan at mga kasalanan, at tanggapin mo kami bilang iyong mana.”
Batiin din ninyo ang iglesya na nasa kanilang bahay. Batiin ninyo si Epeneto na minamahal ko, na siyang unang nahikayat kay Cristo sa Asia.
Subalit ang ikapitong taon ay magiging ganap na kapahingahan sa lupain, isang Sabbath sa Panginoon ; huwag mong hahasikan ang iyong bukid, ni pupungusan ang iyong ubasan.
At nagsalita ang Panginoon kay Moises, na sinasabi,
Ngayon ay maliwanag na walang sinumang inaaring-ganap sa harapan ng Diyos sa pamamagitan ng kautusan, sapagkat “Ang matuwid ay mabubuhay sa pamamagitan ng pananampalataya.”
Sapagkat ang hindi magawa ng kautusan, yamang ito ay pinahina ng laman, ay ginawa ng Diyos sa pagsusugo sa kanyang sariling Anak sa anyo ng makasalanang laman, at tungkol sa kasalanan ay hinatulan niya ang kasalanan sa laman,
Nagsugo siya ng isa pang alipin, subalit ito'y kanilang binugbog din at hiniya, at pinaalis na walang dala.
Sumagot si Jose sa Faraon, na sinasabi, “Hindi ako, ang Diyos ang sasagot sa kapayapaan ng Faraon.”
Sinabi ng isa pa, ‘Bumili ako ng limang magkatuwang na bakang lalaki, at paroroon ako upang sila'y subukin. Hinihiling ko sa iyo na pagpaumanhinan mo ako.’
Muli siyang susuriin ng pari sa ikapitong araw, at kung makitang ang bahaging may karamdaman ay namutla, at ang sakit ay hindi kumalat sa balat, kung gayon ay ipahahayag siya ng pari na malinis. Iyon ay isa lamang singaw at lalabhan niya ang kanyang damit, at magiging malinis.
Nang ibigay ng Kataas-taasan sa mga bansa ang kanilang pamana, nang kanyang ihiwalay ang mga anak ng tao, kanyang inilagay ang mga hangganan ng mga bayan, ayon sa bilang ng mga anak ni Israel.
Kinaumagahan, maaga silang gumising at sila'y nagsumpaan. Sila'y pinalakad na ni Isaac sa kanilang patutunguhan at iniwan nilang payapa si Isaac.
(na sa mga iyon ay hindi karapat-dapat ang sanlibutan). Sila'y nagpalabuy-laboy sa mga ilang, sa mga kabundukan, sa mga yungib, at sa mga lungga sa lupa.
Subalit kahabag-habag kayong mga Fariseo! Sapagkat nagbibigay kayo ng ikapu ng yerbabuena, ng ruda at ng bawat gulayin, ngunit pinababayaan ninyo ang katarungan at ang pag-ibig ng Diyos. Dapat lamang ninyong gawin ang mga ito, na hindi pinababayaan ang iba.
Sabihin mo sa kanila, ‘Sinuman sa lahat ng inyong binhi sa buong panahon ng inyong salinlahi na lumapit sa mga banal na bagay na itinalaga ng mga anak ni Israel sa Panginoon na nasa kalagayang marumi, ang taong iyon ay ititiwalag sa aking harapan: Ako ang Panginoon .
Kahuli-hulihan, mga kapatid, anumang bagay na totoo, anumang bagay na kagalang-galang, anumang bagay na matuwid, anumang bagay na malinis, anumang bagay na kaibig-ibig, anumang bagay na kapuri-puri, kung mayroong anumang kagalingan, at kung may anumang nararapat papurihan, ay isipin ninyo ang mga bagay na ito.
Sa pamamagitan niya'y tumanggap kami ng biyaya at pagka-apostol, para sa pagsunod sa pananampalataya sa lahat ng mga bansa, dahil sa kanyang pangalan;
Sa katapusan ng apatnaraan at tatlumpung taon, nang araw ding iyon, ang lahat ng mga hukbo ng Panginoon ay umalis sa lupain ng Ehipto.
Samantalang sinasabi niya ang mga bagay na ito, dumating ang isang ulap, at sila'y nililiman. Sila'y natakot nang sila'y pumasok sa ulap.
Nang suguin kayo ng Panginoon mula sa Kadesh-barnea, na sinasabi, ‘Umakyat kayo at angkinin ninyo ang lupain na ibinigay ko sa inyo;’ pagkatapos ay naghimagsik kayo laban sa utos ng Panginoon ninyong Diyos, at hindi ninyo siya pinaniniwalaan, ni pinakinggan ang kanyang tinig.
Sila'y may mga buntot na gaya ng sa mga alakdan at may mga pantusok; at sa kanilang mga buntot ay naroroon ang kanilang kapangyarihan upang pinsalain ang mga tao ng limang buwan.
Huwag mong ililitaw ang kahubaran ng iyong ama, na siyang kahubaran ng iyong ina. Siya'y iyong ina; huwag mong ililitaw ang kanyang kahubaran.
Ngunit kahabag-habag ang mga buntis at ang mga nagpapasuso sa mga araw na iyon!
Sinabi sa kanya ni Balak, “Ipinapakiusap ko sa iyo na sumama ka sa akin sa ibang lugar, kung saan mo sila makikita. Ang makikita mo lamang ay ang pinakamalapit sa kanila, at hindi mo sila makikitang lahat at sumpain mo sila para sa akin mula roon.”
Mas dakila ka pa ba kaysa sa aming amang si Abraham, na namatay? At namatay ang mga propeta? Ano ang palagay mo sa iyong sarili?”
Sila'y hindi magkakitaan, at walang tumindig na sinuman sa kinaroroonan niya sa loob ng tatlong araw; ngunit lahat ng mga anak ni Israel ay may liwanag sa kanilang tirahan.
Sumagot siya, “Sino ba siya, Ginoo, upang ako'y sumampalataya sa kanya?”
Kapag ang isang propeta ay nagsasalita sa pangalan ng Panginoon , kung ang bagay na sinasabi ay hindi naganap ni nagkatotoo, ang salitang iyon ay hindi sinabi ng Panginoon ; ang propetang iyon ay nagsalita nang may kapangahasan, huwag mo siyang katatakutan.
Hindi ba ninyo nauunawaan na mas mabuti para sa inyo na ang isang tao ay mamatay alang-alang sa bayan, kaysa mapahamak ang buong bansa?”
Narinig ko ang gaya ng isang tinig ng napakaraming tao, gaya ng lagaslas ng maraming tubig, at gaya ng dagundong ng malalakas na kulog na nagsasabi, “Aleluia! Sapagkat naghahari ang Panginoon nating Diyos na Makapangyarihan sa lahat.
Ang mga iyon ay mga mapagbulong, mga mareklamo, na lumalakad ayon sa kanilang mga sariling pagnanasa at ang kanilang bibig ay nagsasalita ng mga pagmamataas, na pakunwaring pumupuri sa mga tao para sa sariling kapakinabangan.
Nagpapasalamat ako sa kanya na nagpapalakas sa akin, kay Cristo Jesus na Panginoon natin, sapagkat ako'y itinuring niyang tapat, na ako'y inilagay sa paglilingkod sa kanya.
Kanyang sinabi, “Huwag kang lumapit dito. Hubarin mo ang sandalyas sa iyong mga paa sapagkat ang dakong iyong kinatatayuan ay banal na lupa.”
Ngunit sinabi ni Pablo, “Hindi ako baliw, kagalang-galang na Festo; kundi mga salita ng katotohanan at katuwiran ang sinasabi ko.
Hindi maaaring mamunga ng masama ang mabuting puno at mamunga ng mabuti ang masamang puno.
waring mga hindi kilala, gayunma'y kilalang-kilala, tulad sa naghihingalo, at narito, kami ay buháy; gaya ng mga pinarurusahan, subalit hindi pinapatay;
Anim na araw na gagawin ang gawain, subalit ang ikapitong araw ay Sabbath ng taimtim na pagpapahinga, banal sa Panginoon ; sinumang gumawa ng anumang gawa sa araw ng Sabbath ay walang pagsalang papatayin.
Huwag kang kakain ng tinapay na may pampaalsa. Pitong araw na kakainin mo sa paskuwa ang tinapay na walang pampaalsa, ang tinapay ng kahirapan; sapagkat umalis kang nagmamadali sa lupain ng Ehipto, upang iyong maalala ang araw nang umalis ka sa lupain ng Ehipto sa lahat ng mga araw ng iyong buhay.
Sa kanya'y nakikipag-usap ako nang harapan, nang maliwanag, at hindi sa malabong salitaan; at ang anyo ng Panginoon ay kanyang nakikita. Bakit hindi kayo natakot na magsalita laban sa aking lingkod na si Moises?”
Ang mga anak ni Zebulon ayon sa kanilang mga angkan: kay Sered, ang angkan ng mga Seredita: kay Elon, ang angkan ng mga Elonita; kay Jalel, ang angkan ng mga Jalelita.
Nang hindi nila ito mailapit sa kanya dahil sa karamihan ng tao, kanilang tinanggal ang bubungan sa tapat ng kanyang kinaroroonan. Nang kanilang mabutas iyon, ibinaba nila ang higaang kinahihigan ng lumpo.
Subalit kung may dumating na mas malakas kaysa kanya at siya'y talunin, kukunin nito sa kanya ang lahat ng sandata na kanyang pinagtiwalaan at ipamimigay nito ang mga nasamsam niya.
Kundi ang salita ay napakalapit sa iyo, ito ay nasa iyong bibig, at nasa iyong puso, kaya't ito ay iyong magagawa.
“Sa ikalabing-apat na araw ng unang buwan, sa paglubog ng araw, ay ang Paskuwa ng Panginoon .
Sapagkat ang mga pinuno ay hindi kilabot sa mabuting gawa, kundi sa masama. At ibig mo bang huwag magkaroon ng takot sa may kapangyarihan? Gawin mo ang mabuti, at magkakamit ka ng kapurihan mula sa kanya:
Marahil ito ang dahilan kung bakit nahiwalay siya sa iyo nang ilang panahon, upang siya'y mapasaiyo magpakailanman;
Ang kamatayan at ang Hades ay itinapon sa lawa ng apoy. Ito ang ikalawang kamatayan, ang lawa ng apoy;
idalangin ninyo sa Panginoon ng anihin, na magpadala ng mga manggagawa sa kanyang aanihin.”
Sinumang hindi tumanggap sa inyo, o duminig sa inyong mga salita, pag-alis ninyo sa bahay o bayang iyon, ay ipagpag ninyo ang alabok ng inyong mga paa.
Ganito ang ibig kong sabihin: ang tagapagmana, habang bata pa ay hindi nakahihigit sa mga alipin bagama't siya ang may-ari ng lahat,
Huwag ninyong hihiwaan ang inyong laman dahil sa namatay; ni huwag kayong maglalagay ng tatu na tanda sa inyong sarili: Ako ang Panginoon .
“Kaya't kung ang kamay mo o ang paa mo ay nakapagpapatisod sa iyo, putulin mo ito at itapon. Mas mabuti pa sa iyo ang pumasok sa buhay na may kapansanan o lumpo kaysa may dalawang kamay o dalawang paa na maitapon sa apoy na walang katapusan.
Iyong itatalaga si Aaron at ang kanyang mga anak, at kanilang gaganapin ang kanilang pagkapari; at ang ibang lalapit ay papatayin.”
Pagkabatid ni Jesus sa kanyang espiritu na nagtatanong sila ng gayon sa kanilang mga sarili, agad niyang sinabi sa kanila, “Bakit nagtatanong kayo ng ganito sa inyong mga puso?
At sinabi niya, “Pumasok ka, pinagpala ng Panginoon . Bakit ka nakatayo sa labas? Naihanda ko na ang bahay at ang lugar para sa mga kamelyo.”
Ngunit kung sa pamamagitan ng Espiritu ng Diyos ay nagpapalayas ako ng mga demonyo, dumating na nga sa inyo ang kaharian ng Diyos.
Subalit ang sinasabi ni Jesus ay tungkol sa pagkamatay ni Lazaro, subalit inakala nila na ang tinutukoy niya ay ang karaniwang pagtulog.
kundi ipinangaral muna sa mga nasa Damasco, at pagkatapos ay sa Jerusalem, at sa buong lupain ng Judea, at sa mga Hentil, na sila'y magsisi at magbagong-loob sa Diyos at gumawa ng mga gawang naaangkop sa pagsisisi.
Kaya't sinabi ni Jacob sa kanyang sambahayan, at sa lahat niyang kasama, “Alisin ninyo ang mga banyagang diyos na nasa inyo, at maglinis kayo ng inyong sarili, at palitan ninyo ang inyong mga suot.
At dito, ang mga taong may kamatayan ay tumatanggap ng ikasampung bahagi, subalit sa kabilang dako ay ang isa na pinatutunayang nabubuhay.
Sapagkat kayo rin ang lubos na nakakaalam na ang araw ng Panginoon ay darating na gaya ng magnanakaw sa gabi.
“Kapag ang isang dayuhan ay nanirahang kasama ninyo sa inyong lupain, huwag ninyo siyang gagawan ng masama.
At pinainom din nila ng alak ang kanilang ama nang gabing iyon. Tumindig ang bunso at sumiping sa ama. Hindi nalaman ng ama nang siya'y mahiga ni nang siya'y bumangon.
‘At ikaw, Bethlehem, sa lupain ng Juda, sa anumang paraan ay hindi ka pinakamaliit sa mga pangunahing bayan ng Juda; sapagkat sa iyo manggagaling ang isang pinuno, na magiging pastol ng aking bayang Israel.’”
Ngunit ang lupain ay pababayaan nila, at tatamasahin ang kanyang mga Sabbath sa pagiging sira nang sila ay wala; samantalang sila'y magbabayad dahil sa kanilang kasamaan, sapagkat itinakuwil nila ang aking mga tuntunin, at kinapootan nila ang aking mga batas.
At hindi sila nakasagot sa mga bagay na ito.
Paano mo masasabi sa iyong kapatid, ‘Kapatid hayaan mong alisin ko ang puwing na nasa iyong mata,’ samantalang hindi mo nakikita ang troso na nasa iyong sariling mata? Ikaw na mapagkunwari, alisin mo muna ang troso na nasa iyong sariling mata, at makakakita ka nang malinaw upang maalis mo ang puwing na nasa mata ng iyong kapatid.
Subalit sinabi ng ilan sa mga Fariseo, “Bakit ginagawa ninyo ang hindi ipinahihintulot sa araw ng Sabbath?”
Hindi sa nagsasalita ako dala ng pangangailangan, sapagkat aking natutunan ang masiyahan sa anumang kalagayang aking kinaroroonan.
O iyong pitong tinapay para sa apat na libo at kung ilang kaing ang inyong natipon?
Subalit ang asawa ni Lot ay lumingon sa likuran niya, at siya ay naging haliging asin.
At sila'y nagsabwatan upang hulihin si Jesus sa pamamagitan ng daya, at patayin siya.
Sila'y lumapit kay Juan, at sa kanya'y sinabi, “Rabi, iyong kasama mo sa kabila ng Jordan na iyong pinatotohanan ay nagbabautismo at ang lahat ay lumalapit sa kanya.”
At hindi ako nakakita ng templo roon, sapagkat ang Panginoong Diyos na Makapangyarihan sa lahat at ang Kordero ang siyang templo roon.
Sinabi niya sa kanila, “Siya ba'y mabuti ang kalagayan?” At kanilang sinabi, “Oo; at narito ang kanyang anak na si Raquel na dumarating kasama ang mga tupa!”
“Sino nga ba ang tapat at matalinong alipin na inatasan ng kanyang panginoon na pangasiwaan ang kanyang sambahayan, upang magbigay sa kanila ng pagkain sa tamang panahon?
Siya'y tinanong ni Jacob, “Hinihiling ko sa iyo na sabihin mo sa akin ang iyong pangalan.” At kanyang sinabi, “Bakit itinatanong mo ang aking pangalan?” At siya'y binasbasan doon.
Nakita ni Balak na anak ni Zipor ang lahat ng ginawa ng Israel sa mga Amoreo.
Subalit ang taong nilisan ng mga demonyo ay nakiusap na siya'y makasama niya. Subalit siya'y pinaalis niya, na sinasabi,
At nagpatirapa ang dalawampu't apat na matatanda at ang apat na nilalang na buháy, at sumamba sa Diyos na nakaupo sa trono, na nagsasabi, “Amen. Aleluia!”
“Huwag kang maghahandog sa Panginoon mong Diyos ng baka o tupa na may dungis o anumang kapintasan; sapagkat ito'y karumaldumal sa Panginoon mong Diyos.
Gayunman, huwag ninyong kakainin ang mga ito sa mga ngumunguya o doon sa mga may hati ang paa: ang kamelyo, bagaman ngumunguya, ngunit walang hati ang paa, ito ay marumi para sa inyo,
“Hayaang ang mga salitang ito ay pumasok sa inyong mga tainga, sapagkat ang Anak ng Tao ay ibibigay sa mga kamay ng mga tao.”
Huwag mong mumurahin ang bingi, ni maglalagay ng katitisuran sa harap ng bulag, kundi katakutan mo ang iyong Diyos: Ako ang Panginoon .
At kapag ang kaban ay isinulong na, sinasabi ni Moises, “Bumangon ka, O Panginoon , at mangalat nawa ang mga kaaway mo, at tumakas sa harap mo ang napopoot sa iyo.”
“Alamin mo na hindi ibinibigay sa iyo ng Panginoon mong Diyos ang mabuting lupaing ito upang angkinin ng dahil sa iyong pagiging matuwid; sapagkat ikaw ay isang bayang matigas ang ulo.
Ngunit kung nais kong magmalaki ay hindi ako magiging hangal, sapagkat ako'y magsasabi ng katotohanan. Ngunit nagpipigil ako upang walang sinumang mag-isip ng higit tungkol sa akin kaysa kanyang nakita o narinig sa akin,
Ang mga anak ni Israel ay naglakbay at nagkampo sa mga kapatagan ng Moab sa kabila ng Jordan sa Jerico.
At sinabi sa kanila ni Moises, “Kung ang mga anak ni Gad at ang mga anak ni Ruben ay tatawid na kasama ninyo sa Jordan, ang lahat ng lalaki na may sandata sa pakikipaglaban, sa harap ng Panginoon ; at kung ang lupain ay mapasuko sa harap ninyo ay ibibigay ninyo sa kanila bilang ari-arian ang lupain ng Gilead.
Bawat libis ay matatambakan, at bawat bundok at burol ay papatagin, at ang liko ay tutuwirin, at ang mga baku-bakong daan ay papantayin.
Sumagot si Jesus sa kanila, “Ito ang gawa ng Diyos na inyong sampalatayanan ang kanyang sinugo.”
Kung kayo'y umiibig sa mga umiibig sa inyo, ano ang mapapala ninyo? Ang mga makasalanan man ay umiibig sa mga umiibig sa kanila.
Sinabi sa kanila ni Jesus, “Kayong lahat ay tatalikod sapagkat nasusulat, ‘Hahampasin ko ang pastol at kakalat ang mga tupa.’
Ang mga palaka ay aalis sa iyo at sa iyong mga bahay, sa iyong mga lingkod, at sa iyong bayan; mananatili na lamang sila sa Nilo.”
kundi papatayin mo siya. Ikaw ang mangunguna upang patayin siya, at pagkatapos ay ang buong bayan.
At walang nilalang na nakukubli sa harapan niya, kundi ang lahat ng mga bagay ay hubad at hayag sa mga mata niya na ating pagsusulitan.
habang madilim ang araw; at napunit sa gitna ang tabing ng templo.
Walang sinumang dakila kaysa akin sa bahay na ito; walang anumang bagay ang ipinagkait sa akin, maliban sa iyo, sapagkat ikaw ay kanyang asawa. Paano ngang magagawa ko itong malaking kasamaan at kasalanan laban sa Diyos?”
Kung saan may kapatawaran ng mga ito, ay wala ng pag-aalay para sa kasalanan.
Sumapit siya sa isang lunsod ng Samaria na tinatawag na Sicar, malapit sa bahagi ng lupang ibinigay ni Jacob kay Jose na kanyang anak.
Binabati kayo ni Gayo na tinutuluyan ko, at ng buong iglesya. Binabati kayo ni Erasto na ingat-yaman ng lunsod, at ng kapatid na si Cuarto. [
At nagalit sa akin ang Panginoon dahil sa inyong mga salita, at sumumpa na ako'y hindi tatawid sa Jordan, at hindi ako papasok sa mabuting lupaing ibinibigay ng Panginoon mong Diyos sa iyo bilang pamana.
Pagtiisan ninyo ang isa't isa, at kung ang sinuman ay may reklamo laban sa kanino man, magpatawaran kayo sa isa't isa, kung paanong pinatawad kayo ng Panginoon, ay gayundin naman ang inyong gawin.
Dahil sa paglaganap ng kasamaan, ang pag-ibig ng marami ay lalamig.
na lalabas sa harapan nila, at papasok sa harapan nila, mangunguna sa kanila palabas at magdadala sa kanila papasok upang ang kapulungan ng Panginoon ay huwag maging parang mga tupa na walang pastol.”
At sinabi ng Panginoon kay Noe, “Ikaw at ang iyong buong sambahayan ay sumakay sa daong sapagkat nakita kong ikaw lamang ang matuwid sa harap ko sa lahing ito.
sapagkat ito ang mga araw ng paghihiganti, upang matupad ang lahat ng mga bagay na nasusulat.
Kung ihahandog niya iyon bilang pasasalamat, ihahandog niyang kasama ng alay ang mga maninipis na tinapay na walang pampaalsa na hinaluan ng langis, mga munting tinapay na hinaluan ng langis, at manipis na tinapay na gawa sa magandang uri ng harina na hinaluan ng langis.
Subalit sinaway siya ni Jesus, at sinabi, “Tumahimik ka at lumabas sa kanya!” At nang ang lalaki ay nailugmok ng demonyo sa gitna nila, ay lumabas siya sa lalaki na hindi ito sinaktan.
Mayroon ba sa inyong nagdurusa? Manalangin siya. Mayroon bang masaya? Umawit siya ng papuri.
Isama mo rin ang iyong mga kapatid mula sa lipi ni Levi, na lipi ng iyong ama upang sila'y makasama mo at maglingkod sa iyo samantalang ikaw at ang iyong mga anak na kasama mo ay nasa harap ng tolda ng patotoo.
Sila'y naglakbay mula sa Haserot at nagkampo sa Ritma.
Kanyang gagantihan ang bawat tao ayon sa kanyang mga gawa:
Ngunit kanino sa mga anghel sinabi niya kailanman, “Maupo ka sa aking kanan, hanggang sa ang iyong mga kaaway ay gawin kong tuntungan ng iyong mga paa?”
Subalit kanyang sinabi, “Kayo'y mga tamad, kayo'y mga tamad! Kaya't inyong sinasabi, ‘Hayaan mo kaming umalis at maghandog sa Panginoon :’
Ito ang aklat ng lahi ni Jesu-Cristo, na anak ni David, na anak ni Abraham.
Ngunit kung hindi ninyo pinatatawad ang mga tao sa kanilang mga kasalanan, hindi rin naman kayo patatawarin ng inyong Ama sa inyong mga kasalanan.
Ngayon, sinunod mong mabuti ang aking aral, pamumuhay, layunin, pananampalataya, pagtitiyaga, pag-ibig, at pagtitiis,
Pagsapit ng gabi, lumusong ang kanyang mga alagad sa dagat.
Dapat kaming laging magpasalamat sa Diyos, mga kapatid, dahil sa inyo, gaya ng nararapat, sapagkat ang inyong pananampalataya ay lumalagong lubha, at ang pag-ibig ng bawat isa sa inyo para sa isa't isa ay nadaragdagan.
Siya ay marunong makitungo na may kaamuan sa mga mangmang at naliligaw, yamang siya man ay napapaligiran ng kahinaan.
Sinabi niya ang mga bagay na ito sa sinagoga, samantalang siya'y nagtuturo sa Capernaum.
Sinabi ni Balak kay Balaam, “Di ba ikaw ay aking pinapuntahan upang tawagin? Bakit nga ba hindi ka naparito sa akin? Hindi ba kita kayang parangalan?”
subalit kaluwalhatian, karangalan, at kapayapaan sa bawat gumagawa ng mabuti, una'y sa Judio at gayundin sa Griyego:
“Kapag dinala ka ng Panginoon mong Diyos sa lupain na iyong pinaroroonan upang angkinin ito, at pinalayas ang maraming bansa sa harapan mo, ang Heteo, Gergeseo, Amoreo, Cananeo, Perezeo, Heveo, at ang Jebuseo, na pitong bansang higit na malalaki at makapangyarihan kaysa iyo;
Hindi ko hinihiling na alisin mo sila sa sanlibutan, kundi ingatan mo sila mula sa masama.
Nang makaraan ang ilang araw, si Haring Agripa at si Bernice ay dumating sa Cesarea upang batiin si Festo.
Lumapit kayo sa kanya, na isang batong buháy, bagaman itinakuwil ng mga tao gayunma'y pinili at mahalaga sa paningin ng Diyos, at
Kung kayo nga'y hindi naging tapat sa kayamanan ng kalikuan, sino ang magtitiwala sa inyo ng mga tunay na kayamanan?
At sinabi nila sa akin, “Kailangang muli kang magpahayag ng propesiya tungkol sa maraming mga bayan at mga bansa, mga wika at mga hari.”
Iwiwisik ng pari ang dugo sa ibabaw ng dambana ng Panginoon , sa pintuan ng toldang tipanan at susunugin ang taba na mabangong samyo sa Panginoon ,
Katotohanang sinasabi ko sa inyo, na anumang inyong talian sa lupa ay yaong tatalian sa langit; at anumang inyong kalagan sa lupa ay yaong kakalagan sa langit.
Siya'y nagpakita ng lakas sa pamamagitan ng kanyang bisig; pinagwatak-watak niya ang mga palalo sa mga haka ng kanilang puso.
Ang tubig ay nagpatuloy ng paghupa hanggang sa ikasampung buwan. Nang unang araw ng ikasampung buwan, nakita ang mga taluktok ng mga bundok.
Ito ang tubig ng Meriba na kung saan nakipag-away ang mga anak ni Israel sa Panginoon at ipinakita niya sa kanila na siya ay banal.
Sundan mo ang huwaran ng mga wastong salita na narinig mo sa akin, sa pananampalataya at pag-ibig na na kay Cristo Jesus.
Kaya't si Israel, dala ang lahat niyang pag-aari ay naglakbay at dumating sa Beer-seba, at doon ay nag-alay ng mga handog sa Diyos ng kanyang amang si Isaac.
Pagkatapos ay dinala kay Jesus ang isang bulag at pipi na inaalihan ng demonyo, at kanyang pinagaling ito kaya't ang dating pipi ay nakapagsalita at nakakita.
Ngunit tungkol sa inyo, ang inyong mga bangkay ay mabubuwal sa ilang na ito.
Pakabanalin mo ang mga iyon upang maging kabanal-banalan; sinumang humawak sa mga iyon ay magiging banal.
pagkawasak at kalungkutan ang nasa kanilang mga landas,
Nang maitabi na nila sa lupa ang kanilang mga bangka ay iniwan nila ang lahat, at sumunod sa kanya.
Siya'y kailangang tumaas, nguni't ako'y kailangang bumaba.”
kaya sila'y dumating at humingi sa kanila ng paumanhin. At sila'y kanilang inilabas at hiniling sa kanila na lisanin ang lunsod.
Kaya nga, ibig kong magsipag-asawa ang mga batang babaing balo, manganak, mamahala ng sambahayan, huwag magbigay sa kaaway ng anumang kadahilanan ng panlilibak,
Ito ang magiging palatandaan ninyo: Matatagpuan ninyo ang isang sanggol na balot ng lampin at nakahiga sa isang sabsaban.”
Dali-dali niyang ibinaba ang kanyang banga sa kanyang balikat, at sinabi, ‘Uminom ka, at paiinumin ko pati ang iyong mga kamelyo,’ sa gayo'y uminom ako, at pinainom niya pati ang mga kamelyo.
at tatagos ang isang tabak sa iyong sariling kaluluwa upang mahayag ang iniisip ng marami.”
Ang bawat upuang sapin na sakyan ng may tulo ay magiging marumi.
Sinabi niya sa kanila, “Nasaan ang inyong pananampalataya?” At sila'y natakot at namangha, at sinabi sa isa't isa, “Sino nga kaya ito, na kanyang inuutusan maging ang hangin at tubig at sila'y sumusunod sa kanya?”
Sa patnubay ng Espiritu ay pumasok siya sa templo. Nang ipasok ng mga magulang sa templo ang sanggol na si Jesus upang gawin sa kanya ang naaayon sa kaugalian sa ilalim ng kautusan,
Ikaw ay tatayo sa labas, at ang taong iyong pinahihiram ang maglalabas ng sangla sa iyo.
Sinabi niya, “Sinong naglagay sa iyo bilang pinuno at hukom sa amin? Iniisip mo bang patayin ako, gaya nang pagpatay mo sa Ehipcio?” Natakot si Moises at kanyang inisip, “Tiyak na ang bagay na ito ay alam na.”
At siya'y may ari-arian na mga kawan, mga bakahan, at malaking sambahayan; at kinainggitan siya ng mga Filisteo.
Pagkatapos ay tinawag ni Jesus ang kanyang labindalawang alagad, at kanyang binigyan sila ng kapangyarihan sa masasamang espiritu, upang kanilang mapalayas sila at pagalingin nila ang bawat sakit at karamdaman.
at sasabihin ninyo, ‘Bukod dito, ang iyong lingkod na si Jacob ay nasa hulihan namin.’” Sapagkat kanyang iniisip, “Baka mapaglubag ko ang kanyang galit sa pamamagitan ng regalo na ipinauna ko, at pagkatapos ay makikita ko ang kanyang mukha, marahil ay tatanggapin niya ako.”
“Huwag mong babaluktutin ang katarungan sa dayuhan ni sa ulila; ni huwag mong kukuning sangla ang damit ng babaing balo;
Huwag kayong magpapaningas ng apoy sa lahat ng inyong tinitirhan sa araw ng Sabbath.”
Sinabi ni Jesus, “Alisin ninyo ang bato.” Si Marta, na kapatid ng namatay, ay nagsabi sa kanya, “Panginoon, nangangamoy na siya ngayon, sapagkat apat na araw na siyang patay.”
At titipunin sa harapan niya ang lahat ng mga bansa at kanyang pagbubukud-bukurin ang mga tao na gaya ng pagbubukud-bukod ng pastol sa mga tupa at sa mga kambing,
Mga kapatid ko, maaari ba na ang puno ng igos ay magbunga ng olibo, o ng mga igos ang puno ng ubas? Hindi rin maaaring daluyan ng tabang ang maalat na tubig.
sapagkat ang buong lupaing natatanaw mo ay ibibigay ko sa iyo, at sa iyong binhi magpakailanman.
Ngunit unawain mo ito, na sa mga huling araw ay darating ang mga panahon ng kapighatian.
Nang unang araw ng sanlinggo, nang kami ay nagtitipon upang magputul-putol ng tinapay, si Pablo ay nagsalita sa kanila; yamang nagbabalak siya na umalis kinabukasan, nagpatuloy siya sa pagsasalita hanggang hatinggabi.
“Kaya't inyong ilalagak ang mga salita kong ito sa inyong puso at sa inyong kaluluwa at inyong itatali na pinakatanda sa inyong kamay at magiging pinakatali sa inyong noo.
Sila'y mga Israelita, na sa kanila ang pagkukupkop, at ang kaluwalhatian, at ang mga tipan, at ang pagtanggap sa kautusan, at ang pagsamba at ang mga pangako;
Ang palayok na pinaglagaan nito ay babasagin; at kung ito'y inilaga sa sisidlang tanso, ito ay lilinisin at babanlawan ng tubig.
Makinig kayo! Akong si Pablo ay nagsasabi sa inyo na kung kayo'y patutuli, si Cristo ay hindi magiging pakinabang sa inyo.
at sa ilang, na doon ay inyong nakita kung paanong dinala kayo ng Panginoon ninyong Diyos, na gaya ng pagdadala ng tao sa kanyang anak, sa lahat ng daang inyong nilakaran hanggang sa makarating kayo sa dakong ito.’
At ito ang batas tungkol sa kanyang pagiging marumi dahil sa kanyang tulo. Maging ang kanyang katawan ay may tulo, o huminto na ang tulo sa kanyang katawan, ito ay karumihan sa kanya.
ang toldang tipanan at ang kaban ng patotoo, at ang luklukan ng awa na nasa ibabaw niyon, at ang lahat ng kasangkapan ng tolda,
May dalawang anak na babae si Laban; ang pangalan ng panganay ay Lea, at ang bunso ay si Raquel.
Nang makaraan ang ilang taon ay naparito ako upang magdala sa aking bansa ng mga limos at mag-alay ng mga handog.
Dumating ang isang babaing balo at siya'y naghulog ng dalawang kusing na ang halaga'y halos isang pera.
Sapagkat ipinag-utos niya sa masamang espiritu na lumabas sa tao. Madalas siyang inaalihan nito kaya't siya'y binabantayan at iginagapos ng mga tanikala at mga posas, subalit kanyang pinapatid ang mga gapos at siya'y itinaboy ng demonyo sa mga ilang.
Kaya't si Moises ay gumawa ng isang ahas na tanso at ipinatong sa isang tikin, at kapag may nakagat ng ahas, at tumingin ang taong iyon sa ahas na tanso ay nabubuhay.
“‘Huwag kang magkakaroon ng ibang mga diyos sa harapan ko.
Ano nga ang ating sasabihin? May kawalang-katarungan ba sa Diyos? Huwag nawang mangyari.
Kaming lahat ay mga anak ng isa lamang lalaki. Kami ay mga taong tapat; ang iyong mga lingkod ay hindi mga espiya.”
Sinabi ni Laban, “Mas mabuti na ibigay ko siya sa iyo kaysa ibigay ko siya sa iba; tumira ka sa akin.”
At si Isaac ay naghasik sa lupaing iyon, at umani siya ng taong yaon ng makasandaang ibayo. Pinagpala siya ng Panginoon ,
Huwag mong gagawin ang gayon sa Panginoon mong Diyos, sapagkat bawat karumaldumal sa Panginoon na kanyang kinapopootan ay kanilang ginagawa sa kanilang mga diyos; sapagkat pati na ang kanilang mga anak na lalaki at babae ay kanilang sinusunog sa apoy para sa kanilang mga diyos.
At napaso ang mga tao sa matinding init, ngunit kanilang nilait ang pangalan ng Diyos na may kapangyarihan sa mga salot na ito; at hindi sila nagsisi upang siya'y luwalhatiin.
Upang kayo'y huwag magmarunong sa inyong sarili, mga kapatid, nais kong malaman ninyo ang hiwagang ito, na ang pagmamatigas ay nangyari sa isang bahagi ng Israel hanggang makapasok ang buong bilang ng mga Hentil.
Ngunit sinabi ni Moises, “Dapat ding magbigay ka sa aming kamay ng mga alay at mga handog na sinusunog upang aming maihandog sa Panginoon naming Diyos.
at ibubuhos ng pari ang langis sa ibabaw ng palad ng kanyang kaliwang kamay.
upang sumagana ang inyong pagmamapuri kay Cristo Jesus sa akin sa pamamagitan ng aking muling pagharap sa inyo.
Muli nilang pinagsikapang siya'y hulihin, subalit siya'y tumakas sa kanilang mga kamay.
Katotohanang sinasabi ko sa iyo, nang ikaw ay bata pa, binibigkisan mo ang iyong sarili at lumalakad ka kung saan mo ibig; ngunit pagtanda mo'y iuunat mo ang iyong mga kamay, at bibigkisan ka ng iba, at dadalhin ka kung saan hindi mo ibig.”
“Huwag mong ibabalik sa kanyang panginoon ang isang aliping tumakas sa kanyang panginoon at pumunta sa iyo.
Habang si Pedro at si Juan ay nagsasalita pa sa taong-bayan, lumapit sa kanila ang mga pari, ang pinuno sa templo, at ang mga Saduceo,
Nang makalipas ang maraming araw, nagbalak ang mga Judiong siya'y patayin.
Nangyari nga, pagkatapos na masabi niya ang lahat ng salitang ito, ang lupa na nasa ilalim nila ay nahati.
Pagkatapos ay sinabi niya, “O huwag sanang magalit ang Panginoon, at ako'y magsasalita. Kung sakaling may matatagpuan doong tatlumpu.” At sinabi niya, “Hindi ko gagawin kung makakatagpo ako roon ng tatlumpu.”
Ibinuhos ng ikapitong anghel ang kanyang mangkok sa himpapawid at lumabas sa templo ang isang malakas na tinig, mula sa trono na nagsasabi, “Naganap na!”
Ang taong lumilikha ng pagkakabaha-bahagi, pagkatapos nang una at ikalawang pagsaway ay iwasan mo;
Ilalagay mo ang mga iyon sa dalawang hanay, anim sa bawat hanay, sa ibabaw ng hapag na dalisay na ginto.
Sinugo sila ni Moises sa pakikipaglaban, isang libo sa bawat lipi, sila at si Finehas na anak ng paring si Eleazar, na may mga kasangkapan ng santuwaryo at may mga trumpeta na panghudyat sa kanyang kamay.
kaya't pinawawalang kabuluhan ang salita ng Diyos sa pamamagitan ng tradisyon na inyong ipinamana at marami pa kayong ginagawang mga bagay na katulad nito.
Hindi makayanan ng lupain na sila'y manirahang magkasama sapagkat napakarami ng kanilang pag-aari.
Ang nagpapatotoo sa mga bagay na ito ay nagsasabi, “Oo, ako'y malapit nang dumating.” Amen. Pumarito ka Panginoong Jesus!
Nang makalakad pa siya ng kaunti, nakita niya sina Santiago na anak ni Zebedeo at si Juan na kanyang kapatid na naghahayuma ng mga lambat sa kanilang bangka.
(ito ay ayon sa nasusulat sa kautusan ng Panginoon, “Ang bawat panganay na lalaki ay tatawaging banal sa Panginoon”).
Kaya't maging nasa tahanan o malayo sa tahanan, ang aming mithiin ay ang bigyan siya ng kasiyahan.
Ngunit dumating ang isang pagkakataon na si Herodes sa kanyang kaarawan ay nagbigay ng isang salu-salo para sa kanyang mga mahistrado, mga pinuno ng hukbo at mga pangunahing tao sa Galilea.
Kung ganito ang pakikitungong gagawin mo sa akin ay patayin mo na ako. Kung ako'y nakasumpong ng biyaya sa iyong paningin, huwag mo nang ipakita sa akin ang aking paghihirap.”
Ang tabing ng templo ay nahati sa dalawa, mula sa itaas hanggang sa ibaba.
Kung kayo nga na masasama ay marunong magbigay ng mabubuting kaloob sa inyong mga anak, gaano pa kaya ang inyong Ama na nasa langit ang magbigay ng mabubuting bagay sa mga humihingi sa kanya?
Kanyang nilagyan ng bara ang gulong ng kanilang mga karwahe kaya't ang mga iyon ay hirap na hirap sa pag-ikot; kaya't sinabi ng mga Ehipcio, “Takbuhan na natin ang Israel, sapagkat ipinaglalaban sila ng Panginoon laban sa mga Ehipcio.”
Ngayon, ang mga pangako ay ginawa kay Abraham at sa kanyang binhi. Hindi sinasabi, “At sa mga binhi,” na tungkol sa marami; kundi tungkol sa iisa, “At sa iyong binhi,” na si Cristo.
ay sinabi niya, “Umalis na kayo, sapagkat hindi patay ang batang babae kundi natutulog lamang.” At siya ay pinagtawanan nila.
Kaya't siya'y tinanong ng mga Fariseo at mga eskriba, “Bakit ang iyong mga alagad ay hindi lumalakad ayon sa tradisyon ng matatanda, kundi kumakain ng tinapay na marurumi ang mga kamay?”
sapagkat nabalitaan ko ang iyong pag-ibig para sa lahat ng mga banal at ang pananampalataya mo sa Panginoong Jesus.
Ngunit kung kanyang hampasin ang kanyang kapwa ng isang kasangkapang bakal, na anupa't namatay, siya nga'y mamamatay-tao; ang mamamatay-tao ay tiyak na papatayin.
hindi gaya ni Moises, na naglagay ng talukbong sa kanyang mukha upang hindi makita ng mga anak ni Israel ang katapusan ng bagay na lumilipas.
Kung sa inyo'y dumating ang sinuman at hindi dala ang aral na ito, huwag ninyong tanggapin sa inyong bahay, at huwag ninyo siyang batiin,
“Isang tinig ang narinig sa Rama, pananangis at malakas na panaghoy, tinatangisan ni Raquel ang kanyang mga anak; ayaw niyang paaliw, sapagkat wala na sila.”
Nang makita siya ni Juda ay inakalang siya'y upahang babae, sapagkat nagtakip ng kanyang mukha.
Nang marinig ng mga punong pari at ng mga Fariseo ang kanyang mga talinghaga, nahalata nilang siya'y nagsasalita tungkol sa kanila.
Si Maria Magdalena at ang isa pang Maria ay naroon at nakaupo sa tapat ng libingan.
Ibibigay sila ng Panginoon sa harapan mo, at iyong gagawin sa kanila ang ayon sa lahat ng utos na aking iniutos sa iyo.
Ang mga pari na mga anak ni Levi ay lalapit sapagkat sila ang pinili ng Panginoon mong Diyos na mangasiwa sa kanya at upang magbasbas sa pangalan ng Panginoon ; at sa pamamagitan ng kanilang salita ay pagpapasiyahan ang bawat pagtatalo at bawat pananakit.
Ngunit ano ang pinuntahan ninyo upang makita? Isa bang taong nakasuot ng malalambot na damit? Tingnan ninyo, ang mga nagsusuot ng malambot na damit ay nasa mga bahay ng mga hari.
Ngunit ang mga bagay na lumalabas sa bibig ay nagmumula sa puso at siyang nagpaparumi sa tao.
upang ikaw ay makipagtipan sa Panginoon mong Diyos, at sa kanyang pangako na ginagawa sa iyo ng Panginoon mong Diyos sa araw na ito;
Sa ganoon ang buong Israel ay maliligtas; gaya ng nasusulat, “Lalabas mula sa Zion ang Tagapagligtas; ihihiwalay niya ang kasamaan mula sa Jacob.”
At sumagot si Jesus sa kanya, “Nasusulat, ‘Sambahin mo ang Panginoon mong Diyos, at siya lamang ang iyong paglingkuran.’”
At lumabas ang isa pang anghel mula sa templo sa langit na siya rin ay may matalas na karit.
Noon ay sumama sa kanya ang napakaraming tao. Siya'y humarap sa kanila at sa kanila'y sinabi,
Ang tumanggap ng limang talento ay umalis kaagad at ipinangalakal niya ang mga iyon, at nakinabang siya ng lima pang talento.
Subalit ang lalaking malinis at wala sa paglalakbay na hindi mangingilin ng paskuwa ay ititiwalag sa kanyang bayan sapagkat siya'y hindi nag-alay ng handog sa Panginoon sa takdang panahon, ang taong iyon ay mananagot sa kanyang kasalanan.
ang hangganan ay pababa mula sa Shefam hanggang sa Ribla, sa dakong silangan ng Ain; at ang hangganan ay pababa at abot hanggang sa gilid ng dagat ng Cineret sa dakong silangan.
gaya nang ginawa sa akin ng mga anak ni Esau na naninirahan sa Seir, at ng mga Moabita na naninirahan sa Ar, hanggang makatawid ako sa Jordan, sa lupaing ibinibigay sa amin ng Panginoon naming Diyos.’
At kay Adan ay kanyang sinabi, “Sapagkat nakinig ka sa tinig ng iyong asawa, at kumain ka ng bunga ng punungkahoy na aking iniutos sa iyo na, ‘Huwag kang kakain niyon,’ sumpain ang lupa dahil sa iyo. Kakain ka mula sa kanya sa pamamagitan ng iyong mabigat na paggawa sa lahat ng mga araw ng iyong buhay;
At sinabi ni Moises sa bayan, “Kayong mga lalaki ay maghanda ng sandata para sa pakikipaglaban upang labanan ang Midianita at igawad ang paghihiganti ng Panginoon sa Midian.
Sinabi niya sa kanila, “Bakit kayo natakot? Wala ba kayong pananampalataya?”
Ang mga anak ni Izar: si Kora, si Nefeg, at si Zicri.
Kaya't si Moises ay nagbigay ng utos at ipinahayag nila sa buong kampo na sinasabi, “Huwag nang gumawa ang lalaki o babae man ng anumang higit pa para sa handog sa santuwaryo.” Kaya't pinigilan ang taong-bayan sa pagdadala;
Ang mga alagad, ayon sa kakayahan ng bawat isa, ay nagpasiyang magpadala ng tulong sa mga kapatid na naninirahan sa Judea;
Palawakin ng Diyos si Jafet, at siya'y titira sa mga tolda ni Sem; at si Canaan ay magiging alipin niya.”
Nang sumunod na araw, pagbaba nila mula sa bundok ay sinalubong siya ng napakaraming tao.
Si Ruben ay sumagot sa kanila, “Hindi ba sinabi ko sa inyo, huwag kayong magkasala laban sa bata; at ayaw kayong makinig? Kaya ngayon ay dumating ang pagtutuos para sa kanyang dugo.”
“Tatlong beses sa bawat taon na magdiriwang ka ng pista para sa akin.
ang mga kawan ay nagsisiping sa harap ng mga sanga kaya't ang kawan ay nagkaanak ng mga may guhit, may batik at may dungis.
Hindi ko iyon kinain habang ako'y nagluluksa, ni inilabas ko nang ako'y marumi, ni ibinigay ko upang gamitin sa patay. Aking pinakinggan ang tinig ng Panginoon kong Diyos; aking ginawa ayon sa lahat ng iniutos mo sa akin.
sapagkat ang namatay ay pinalaya na mula sa kasalanan.
Sila'y naglakbay mula sa Dofca at nagkampo sa Alus.
At sinong lalaki ang may itinanim na isang ubasan at hindi pa niya napapakinabangan ang bunga niyon? Hayaan siyang umalis at bumalik sa kanyang bahay, baka siya'y mamatay sa digmaan at ibang lalaki ang makinabang ng bunga niyon.
Sapagkat ang sinumang nagnanais na iligtas ang kanyang buhay ay mawawalan nito, subalit sinumang mawalan ng kanyang buhay dahil sa akin ay maililigtas niya ito.
‘Ngayon, tumindig kayo at tumawid sa batis ng Zared.’ At tayo'y tumawid sa batis ng Zared.
upang pumalit sa paglilingkod na ito at sa pagka-apostol na tinalikuran ni Judas, upang siya'y pumunta sa sarili niyang lugar.”
kundi dahil din naman sa atin, na ibibilang sa atin na mga sumasampalataya sa kanya na muling bumuhay kay Jesus na ating Panginoon mula sa mga patay,
Sinabi kay Pedro ng babaing tanod sa pinto, “Hindi ba ikaw ay isa sa mga alagad ng taong ito?” Sinabi niya, “Hindi.”
Ikakalat kayo ng Panginoon sa mga bayan, at kayo'y maiiwang iilan sa bilang sa gitna ng mga bansa na pagtatabuyan sa inyo ng Panginoon .
na sa kanya'y ipinangalan ang bawat sambahayan sa langit at sa lupa,
“Gayundin naman, ang kaharian ng langit ay tulad ng isang mangangalakal na naghahanap ng magagandang perlas;
Pagbaba niya sa pampang nakita niya ang napakaraming tao at nahabag siya sa kanila, sapagkat sila'y tulad sa mga tupa na walang pastol. At sila'y sinimulan niyang turuan ng maraming bagay.
Kaya't isinugo ni Jesus sina Pedro at Juan, na sinasabi, “Humayo kayo at ihanda ninyo ang paskuwa para sa atin, upang ating kainin ito.”
“Kaya't ingatan ninyong mabuti ang inyong sarili. Yamang wala kayong nakitang anumang anyo nang araw na magsalita ang Panginoon sa inyo sa Horeb mula sa gitna ng apoy,
At ang ipinangalan sa ikalawa ay Efraim sapagkat sinabi niya, “Ako'y pinalago ng Diyos sa lupain ng aking pagdadalamhati.”
Nang patapos na ang araw na iyon, lumapit ang labindalawa at sinabi sa kanya, “Paalisin mo ang mga tao upang sila'y makapunta sa mga nayon at sa mga lupaing nasa palibot at makahanap ng matutuluyan at makakain, sapagkat tayo'y narito sa isang ilang na dako.”
Kukuha siya ng dalawang ibon para sa paglilinis ng bahay, ng kahoy na sedro, ng pulang sinulid, at ng isopo,
Bawat lalaki sa mga pari ay kakain niyon; ito ay dapat kainin sa dakong banal.
At ang mga lalaking iyon ay nagsabi sa kanila, “Kami ay marurumi dahil sa paghawak sa bangkay ng isang tao. Bakit kami ay pipigilin sa pag-aalay ng handog sa Panginoon sa kanyang takdang panahon na kasama ng mga anak ni Israel?”
Sinabi pa niya, “Ang lumalabas sa tao ang nakapagpaparumi sa tao.
Nawa'y ibigay niya sa iyo ang pagpapala ni Abraham, sa iyo at sa lahat ng iyong binhi; upang ariin mo ang lupaing iyong pinaglakbayan na ibinigay ng Diyos kay Abraham.”
At dumating si Sihon upang kami ay harapin, siya at ang kanyang buong bayan, upang makipagdigmaan sa Jahaz.
Noon ay may isang alagad sa Joppa na ang pangalan ay Tabita, na sa Griyego ay Dorcas. Siya'y puspos ng mabubuting gawa at ng pagkakawanggawa.
Nang makarating si Jesus sa kabilang pampang, sa lupain ng mga Gadareno, ay sinalubong siya ng dalawang inaalihan ng mga demonyo na lumabas mula sa mga libingan. Napakabangis nila kaya't walang makadaan doon.
Sinasabi ko ang mga bagay na aking nakita sa aking Ama, at kayo, ginagawa naman ninyo ang mga bagay na narinig ninyo mula sa inyong ama.”
ay kumuha ng mga tao. Sila'y tumindig sa harap ni Moises, na kasama ng ilang mga anak ni Israel. Sila'y dalawandaan at limampung pinuno na mga lalaking kilala at pinili mula sa kapulungan.
Isa sa mga dalubhasa sa kautusan ay sumagot sa kanya, “Guro, sa pagsasabi mo nito, pati kami ay iyong nilalait.”
Hindi niya kakainin ang anumang kusang namatay o nilapa ng hayop, sapagkat marurumihan niya ang kanyang sarili sa pamamagitan nito: Ako ang Panginoon .’
Dalhin mo sina Aaron at Eleazar na kanyang anak sa bundok ng Hor.
At sinabi niya sa akin, “Ang tubig na iyong nakita, na kinauupuan ng mahalay na babae ay mga bayan, napakaraming tao, mga bansa, at mga wika.
Nang magkagayo'y umalis siya sa lupain ng mga Caldeo at nanirahan sa Haran. At mula roon, pagkamatay ng kanyang ama, ay inilipat siya ng Diyos sa lupain na inyong tinitirhan ngayon.
‘Pagkatapos ng mga bagay na ito, ako'y babalik, at muli kong itatayo ang tolda ni David na bumagsak; muli kong itatatag ang guho nito, at ito'y aking itatayo:
Sapagkat gaya ng kidlat na nanggagaling sa silangan at nagliliwanag hanggang sa kanluran, gayundin naman ang pagdating ng Anak ng Tao.
Kaya't alamin mo sa araw na ito at ilagay sa iyong puso, na ang Panginoon ay siyang Diyos sa itaas sa langit at sa ibaba sa lupa; wala nang iba pa.
Una, nagpapasalamat ako sa aking Diyos sa pamamagitan ni Jesu-Cristo tungkol sa inyong lahat, sapagkat ang inyong pananampalataya ay ipinahahayag sa buong daigdig.
sa lipi ni Simeon ay 12,000; sa lipi ni Levi ay 12,000; sa lipi ni Isacar ay 12,000;
Sapagkat pinatotohanan, “Ikaw ay pari magpakailanman, ayon sa pagkapari ni Melquizedek.”
Sapagkat makipot ang pintuan at masikip ang daang patungo sa buhay, at kakaunti ang nakakatagpo niyon.
Nang ako'y kasama ninyo sa templo araw-araw, hindi ninyo binuhat ang inyong mga kamay laban sa akin. Subalit ito ang inyong oras, at ng kapangyarihan ng kadiliman.”
Tunay na ipinangangaral ng iba si Cristo dahil sa pagkainggit at sa pakikipagpaligsahan, ngunit ang iba naman ay dahil sa mabuting kalooban.
sapagkat ginulo nila kayo ng kanilang mga pandaraya sa inyo sa nangyari sa Peor, at sa pangyayari kay Cozbi, na anak na babae ng pinuno sa Midian, na kanilang kapatid na namatay nang araw ng salot dahil sa pangyayari sa Peor.
Sapagkat sa Diyos ay walang salitang hindi mangyayari.”
At ang lunsod ay hindi nangangailangan ng araw, o ng buwan man, upang magbigay-liwanag sa kanya, sapagkat ang liwanag niya ay ang kaluwalhatian ng Diyos, at ang ilaw doon ay ang Kordero.
Mula roon ay naglakbay sila hanggang Gudgoda, at mula sa Gudgoda hanggang sa Jotbata, na lupain ng mga batis ng tubig.
Kaya't sila'y kumuha ng abo sa hurno, at tumayo sa harap ni Faraon. Isinaboy ito ni Moises sa himpapawid at naging pigsang sumusugat sa tao at sa hayop.
Nang makita ng dragon na siya'y itinapon sa lupa, inusig niya ang babaing nanganak ng sanggol na lalaki.
Ako'y labis na umiyak, sapagkat walang natagpuang sinuman na karapat-dapat magbukas ng aklat, o tumingin sa loob nito.
“Kahabag-habag kayo kapag ang lahat ng mga tao ay nagsasabi ng mabuti tungkol sa inyo, sapagkat gayundin ang ginawa ng kanilang mga ninuno sa mga bulaang propeta.
Si Jose ay nanirahan sa Ehipto, siya at ang sambahayan ng kanyang ama; at si Jose ay nabuhay ng isandaan at sampung taon.
“‘Aking dadaganan sila ng mga kasamaan; aking uubusin ang aking pana sa kanila.
Mahigpit niyang ipinag-utos sa kanila na walang dapat makaalam nito; at sinabi niya sa kanila na ang bata ay bigyan ng makakain.
Huwag mong hahanapin ang kanilang kapayapaan o ang kanilang pag-unlad sa lahat ng iyong mga araw magpakailanman.
At ang bunso ay nanganak din ng isang lalaki, at tinawag sa pangalang Benammi na siyang ama ng mga anak ni Ammon hanggang sa araw na ito.
At inilipat ni Abram ang kanyang tolda, at humayo at nanirahan sa gitna ng mga punong ensina ni Mamre na nasa Hebron, at siya'y nagtayo roon ng dambana sa Panginoon .
kanilang hahagupitin siya at papatayin at sa ikatlong araw siya ay muling mabubuhay.”
“At magkakaroon ng mga tanda sa araw, at buwan, at mga bituin, at sa lupa'y magkakaroon ng kahirapan sa mga bansa, na nalilito dahil sa ugong ng dagat at mga daluyong.
Nasiyahan ang buong kapulungan sa kanilang sinabi at pinili nila si Esteban, lalaking puspos ng pananampalataya at ng Espiritu Santo, kasama sina Felipe, Procoro, Nicanor, Timon, Parmenas, at si Nicolas na isang naging Judio na taga-Antioquia.
Sila'y sumagot, “Ang lalaki ay masusing nagtanong tungkol sa amin at sa ating pamilya, na sinasabi, ‘Buháy pa ba ang inyong ama? May kapatid pa ba kayo?’ Sumagot kami sa kanyang mga tanong. Paano namin malalaman na kanyang sasabihin, ‘Dalhin ninyo rito ang inyong kapatid?’”
Ibinigay ni Laban kay Lea ang kanyang alilang babae na si Zilpa upang kanyang maging alila.
Maganda ang patotoo tungkol sa kanya ng mga kapatid sa Listra at Iconio.
Kanyang aalisin ang lahat ng taba ng toro na handog pangkasalanan; ang tabang bumabalot sa lamang-loob at ang lahat ng tabang nasa lamang-loob;
Sapagkat alam ko na pagkamatay ko, kayo'y magiging masama at maliligaw sa daang itinuro sa inyo at ang kasamaan ay sasapit sa inyo sa mga huling araw. Sapagkat inyong gagawin ang masama sa paningin ng Panginoon , upang siya'y galitin ninyo sa pamamagitan ng mga gawa ng inyong mga kamay.”
“Isama mo si Aaron at ang kanyang mga anak, ang mga kasuotan, ang langis na pambuhos, ang torong handog pangkasalanan, ang dalawang tupang lalaki, at ang bakol ng mga tinapay na walang pampaalsa,
Dahil dito, bagama't kay Cristo ay mayroon akong sapat na lakas ng loob upang utusan kitang gawin ang kinakailangan,
At binigyan ang bawat isa sa kanila ng isang puting balabal at sa kanila'y sinabi na magpahinga pa sila ng kaunting panahon, hanggang sa mabuo ang bilang ng kanilang mga kapwa alipin at ng kanilang mga kapatid, na mga papataying tulad nila.
na nanguna sa inyo sa daan, upang ihanap kayo ng dakong mapagtatayuan ng inyong mga tolda na nasa apoy kapag gabi, at nasa ulap kapag araw, upang ituro sa inyo ang daang dapat ninyong lakaran.
Sinabi ni Moises, “Pagkaalis ko sa harapan mo ay aking hihilingin sa Panginoon na bukas ay umalis ang mga pulu-pulutong na langaw mula sa Faraon, sa kanyang mga lingkod, at sa kanyang bayan; ngunit huwag nang mandaya pang muli ang Faraon sa hindi pagpayag na humayo ang bayan upang maghandog sa Panginoon .”
At kung hindi niya tubusin ang bukid, o kung ipinagbili niya ang bukid sa ibang tao, ito ay hindi na matutubos.
Ang mga anak ni Aram: sina Uz, Hul, Geter, at Mas.
Tingnan ninyo, ipinagpauna ko nang sinabi sa inyo.
Tingnan ninyo, ibinigay sa inyo ng Panginoon ang Sabbath, kaya't kanyang ibinibigay sa inyo sa ikaanim na araw ang pagkain na para sa dalawang araw; manatili ang bawat tao sa kanyang kinaroroonan, huwag umalis ang sinuman sa kanyang kinaroroonan, sa ikapitong araw.”
“At kung ang sinumang pangkaraniwang tao sa mga mamamayan ay magkasala nang hindi sinasadya sa paggawa ng bagay na hindi dapat gawin, laban sa isa sa mga utos ng Panginoon at nagkasala,
Siya'y nagsunog doon ng mabangong insenso; gaya ng iniutos ng Panginoon kay Moises.
Sapagkat inyong narinig ang uri ng aking dating pamumuhay sa Judaismo, kung paanong marahas kong inusig ang iglesya ng Diyos at sinikap na wasakin ito.
at hindi kumakapit sa Ulo, na sa kanya'y ang buong katawan, na tinutustusan at pinagsasanib sa pamamagitan ng mga kasukasuan at mga litid ay lumalago ng paglagong mula sa Diyos.
Gawin ninyo ito: Kumuha kayo ng mga suuban, si Kora at ang kanyang buong pangkat.
Nasa sa kanya ang buhay at ang buhay ay siyang ilaw ng mga tao.
Minsan, nang si Jesus ay nananalanging mag-isa, ang mga alagad ay kasama niya at tinanong niya sila, “Ano ang sinasabi ng karamihan kung sino ako?”
At lumaki ang bata, lumakas, napuno ng karunungan, at sumasakanya ang biyaya ng Diyos.
Sapagkat walang sinumang napoot sa kanyang sariling katawan, kundi inaalagaan at iniingatan ito, gaya naman ni Cristo sa iglesya;
Gaya ng inyong bahagyang pagkakilala sa amin, na kami ay inyong maipagmalaki gaya ninyo na aming ipinagmamalaki sa araw ng Panginoong Jesus.
Ang babae na iyong nakita ay ang dakilang lunsod na naghahari sa mga hari sa lupa.”
Lahat ng mga babaing may kakayahan ay naghabi sa pamamagitan ng kanilang mga kamay, at dinala ang kanilang mga hinabi na telang asul, kulay-ube at pula, at hinabing pinong lino.
Nakita ng Panginoon na napakasama na ng tao sa lupa, at ang bawat haka ng mga pag-iisip ng kanyang puso ay palagi na lamang masama.
At kinalong niya sila, ipinatong ang kanyang mga kamay sa kanila at binasbasan sila.
ay sinabi ni Rebecca kay Jacob na kanyang anak, “Narinig ko ang iyong ama na nagsasabi kay Esau na iyong kapatid,
Sapagkat minamahal ng Ama ang Anak, at sa kanya'y ipinapakita ang lahat ng mga bagay na kanyang ginagawa, at lalong dakilang mga gawa kaysa mga ito ang ipapakita niya sa kanya upang kayo'y mamangha.
at nakalasap ng kabutihan ng salita ng Diyos, at ng mga kapangyarihan ng panahong darating,
Sila'y magkakabaha-bahagi; ang ama laban sa anak na lalaki, at ang anak na lalaki laban sa ama; ang ina laban sa anak na babae, at ang anak na babae laban sa kanyang ina; ang biyenang babae laban sa kanyang manugang na babae at ang manugang na babae laban sa kanyang biyenang babae.”
Tumingin ako, at nakita kong kayo'y nagkasala laban sa Panginoon ninyong Diyos. Kayo'y gumawa para sa inyo ng isang guyang inanyuan. Kayo'y madaling lumihis sa daan na iniutos sa inyo ng Panginoon .
ngunit ang mga anak ng kaharian ay itatapon sa kadilimang nasa labas. Doon nga ang pagtangis at pagngangalit ng mga ngipin.”
Samantalang sinasabi pa ni Pedro ang mga salitang ito, bumaba ang Espiritu Santo sa lahat ng nakikinig ng salita.
“At kung ang kanyang alay sa Panginoon bilang handog pangkapayapaan ay mula sa kawan, maging lalaki o babae, ito ay ihahandog niya na walang kapintasan.
At yamang itinakda sa mga tao ang mamatay na minsan, at pagkatapos nito ay ang paghuhukom,
Iyon ay isang sagisag ng panahong kasalukuyan, na sa panahong yaon ang mga kaloob at ang mga alay na inihahandog ay hindi makapagpapasakdal sa budhi ng sumasamba,
Ang mga iyon ay susunugin ng pari sa ibabaw ng dambana, isang handog sa Panginoon na pinaraan sa apoy; ito ay handog para sa budhing maysala.
Ngunit kung ayaw nitong sumuko nang mapayapa sa iyo kundi makikipaglaban sa iyo, kukubkubin mo nga ito;
Ang mahulog sa ibabaw ng batong ito ay madudurog, subalit dudurugin nito ang sinumang mabagsakan niya.]”
Ako ay may malaking pagtitiwala sa inyo, ako ay may malaking pagmamapuri sa inyo, ako'y punô ng kaaliwan. Ako'y nag-uumapaw sa kagalakan sa lahat ng aming kapighatian.
“Kayo ang asin ng lupa; ngunit kung ang asin ay tumabang, paano maibabalik ang alat nito? Wala na itong kabuluhan, maliban sa itapon sa labas at tapakan ng mga tao.
Kaya't ang pananampalataya na nag-iisa, kung ito ay walang mga gawa ay patay.
Tungkol sa mga anghel ay sinasabi niya, “Ginagawa niyang mga hangin ang mga anghel, at ang kanyang mga lingkod ay ningas ng apoy.”
Bagama't siya'y isang Anak, siya'y natuto ng pagsunod sa pamamagitan ng mga bagay na kanyang tiniis,
Mahigpit na iniutos niya sa kanila na huwag nilang sasabihin kaninuman ang tungkol sa kanya.
“Iyong hahabihin ang kasuotan na anyong parisukat mula sa pinong lino, at iyong gagawin ang turbante mula sa pinong lino, at iyong palalagyan ng burda ang pamigkis.
Ibig mo ba akong patayin, gaya ng pagpatay mo kahapon sa Ehipcio?’
at tatlong ikasampung bahagi ng isang efa ng piling harina bilang handog na butil na hinaluan ng langis para sa bawat toro; at dalawang ikasampung bahagi ng piling harina bilang handog na butil, na hinaluan ng langis para sa isang lalaking tupa;
Kaya't inisip ko na kailangang himukin ang mga kapatid na maunang pumariyan sa inyo, at ihanda agad ang inyong kaloob na ipinangako nang una, upang ito'y maihanda bilang isang kusang-loob na handog at hindi sapilitan.
“Sapagkat ang pangalan ng Diyos ay nalalait sa mga Hentil dahil sa inyo,” gaya ng nasusulat.
At ang pangalawa ay katulad nito, ‘Ibigin mo ang iyong kapwa na gaya ng iyong sarili.’
Huwag mong kakainin sa loob ng iyong mga bayan ang ikasampung bahagi ng iyong trigo, o ng iyong alak, o ng iyong langis, o ng mga panganay sa iyong bakahan o sa iyong kawan, ni anuman sa iyong mga ipinangakong handog na iyong ipapanata, ni ang iyong mga kusang handog, ni ang handog na iwinawagayway ng iyong kamay.
Subalit dumating ang kautusan na nagbunga ng pagdami ng pagsuway, ngunit kung saan marami ang kasalanan, ay lalong dumarami ang biyaya;
huwag maging tamad sa pagsisikap, maging maalab sa espiritu, na naglilingkod sa Panginoon.
At sinabi niya sa babae, “Pinatatawad na ang iyong mga kasalanan.”
na sinasabi, “Ipahahayag ko ang iyong pangalan sa aking mga kapatid, sa gitna ng kapulungan ay aawitan kita ng mga himno.”
Nang huling araw ng dakilang araw ng pista, si Jesus ay tumayo at sumigaw na nagsasabi, “Kung ang sinuman ay nauuhaw, lumapit siya sa akin at uminom.
Siya'y kanilang pinagtawanan, ngunit pinalabas niya ang lahat at isinama niya ang ama at ang ina ng bata at ang kanyang mga kasamahan. Pumasok sila sa kinaroroonan ng bata.
ay pipili kayo ng mga lunsod na magiging lunsod-kanlungan para sa inyo, upang ang nakamatay ng sinumang tao nang hindi sinasadya ay makatakas patungo doon.
Ang Jesus na ito'y muling binuhay ng Diyos, at tungkol dito'y mga saksi kaming lahat.
Nang kami ay dumaing sa Panginoon ay pinakinggan niya ang aming tinig, at nagsugo siya ng isang anghel, at inilabas kami sa Ehipto. At ngayon, kami ay nasa Kadesh, na isang bayan na nasa dulo ng iyong nasasakupan.
Sa pawis ng iyong mukha ay kakain ka ng tinapay, hanggang ikaw ay bumalik sa lupa; sapagkat diyan ka kinuha. Ikaw ay alabok at sa alabok ka babalik.”
Sila'y nagsigawan, “Ilayo siya, ilayo siya, ipako siya sa krus!” Sinabi sa kanila ni Pilato, “Ipapako ko ba sa krus ang inyong Hari?” Sumagot ang mga punong pari, “Wala kaming hari liban kay Cesar.”
Nang magtakip-silim na, sapagkat noon ay araw ng Paghahanda, ang araw bago ang Sabbath,
Kaya't kanyang pinahayo ang kanyang mga kapatid, at sila'y umalis at kanyang sinabi sa kanila, “Huwag kayong mag-aaway sa daan.”
Ngunit samantalang ang karne ay nasa kanilang mga ngipin pa bago ito naubos ay nagningas ang galit ng Panginoon laban sa bayan at pinatay ng Panginoon ang mga tao ng matinding salot.
Dadalhin niya sa Panginoon ang kanyang handog para sa budhing maysala dahil sa kasalanang nagawa niya, isang babaing hayop mula sa kawan, isang kordero o isang kambing bilang handog pangkasalanan, at ang pari ay gagawa ng pagtubos para sa kanya.
Sinugo ako ng Diyos na una sa inyo upang magpanatili para sa inyo ng mga matitira sa daigdig at upang panatilihing buháy para sa inyo ang maraming nakaligtas.
Pagkatapos, ito ay susunugin ng mga anak ni Aaron sa dambana, sa ibabaw ng handog na sinusunog na nasa ibabaw ng kahoy na nakapatong sa apoy, isang handog na pinaraan sa apoy, na mabangong samyo sa Panginoon .
Ang mga iyon ay magiging isang tanda at isang kababalaghan sa iyo, at sa iyong lahi magpakailanman.
Kapayapaan ang iniiwan ko sa inyo, ang aking kapayapaan ay ibinibigay ko sa inyo. Hindi gaya ng ibinibigay ng sanlibutan ang ibinibigay ko sa inyo. Huwag mabagabag ang inyong puso, o matakot man.
Nangyari ito upang matupad ang sinabi sa pamamagitan ng propeta, na nagsasabi,
na nagsasabi, “Pinasasalamatan ka namin, O Panginoong Diyos na Makapangyarihan sa lahat, ang ngayon at ang nakaraan, sapagkat kinuha mo ang iyong dakilang kapangyarihan, at ikaw ay naghari.
At kanyang sinabi, “O Panginoon , Diyos ng aking panginoong si Abraham, hinihiling ko sa iyong pagkalooban mo ako ng tagumpay ngayon, at ikaw ay magmagandang-loob sa aking panginoong si Abraham.
Nang araw ding iyon ay tinuli si Abraham at si Ismael na kanyang anak.
Sinabi niya, “Ang iyong pangalan ay hindi na tatawaging Jacob, kundi Israel; sapagkat ikaw ay nakipaglaban sa Diyos at sa mga tao, at ikaw ay nagtagumpay.”
Nang mag-umaga na, malaki ang kaguluhang nangyari sa mga kawal tungkol sa kung anong nangyari kay Pedro.
Sapagkat hindi ako mangangahas magsalita ng anumang bagay, maliban sa mga ginawa ni Cristo sa pamamagitan ko, upang sumunod ang mga Hentil, sa salita at sa gawa,
At kanyang sinabi, “Maliit pa bang bagay na kinuha mo ang aking asawa? Ibig mo pa rin bang kunin ang mga mandragora ng aking anak?” Sinabi ni Raquel, “Kaya't sisiping siya sa iyo ngayong gabi para sa mga mandragora ng iyong anak.”
Siya'y magiging isang taong gaya ng mailap na asno, ang kanyang kamay laban sa lahat, at ang kamay ng lahat ay laban sa kanya; at habang nabubuhay ay kalaban ng lahat niyang mga kapatid.
na sinasabi sa kanila, “Nasusulat, ‘Ang aking bahay ay magiging bahay-dalanginan,’ subalit ginawa ninyo itong yungib ng mga magnanakaw.”
Kaya nga, alalahanin ninyo na noong una, kayo'y mga Hentil sa laman, tinatawag na di-tuli ng mga tinatawag na tuli sa laman, na ginawa ng mga kamay ng tao,
Nang papalapit na sila sa Jerusalem at makarating sa Betfage, sa bundok ng mga Olibo, nagsugo si Jesus ng dalawang alagad,
At sinabi ni Aaron kay Moises, “O panginoon ko, huwag mo kaming parusahan, sapagkat gumawa kaming may kahangalan, at kami ay nagkasala.
Ang mga anak ni Manases: kay Makir, ang angkan ng mga Makirita; at naging anak ni Makir si Gilead; kay Gilead, ang angkan ng mga Gileadita.
“Huwag mabagabag ang inyong puso. Sumampalataya kayo sa Diyos, sumampalataya rin naman kayo sa akin.
Kaya't sinasabi rin niya sa isa pang awit, ‘Hindi mo hahayaan na ang iyong Banal ay makakita ng pagkabulok.’
Nais kong makaharap kayo ngayon at baguhin ang aking tono, sapagkat ako'y nag-aalinlangan tungkol sa inyo.
Ang lahat ay namangha sa kadakilaan ng Diyos. Subalit habang ang lahat ay namamangha sa lahat ng kanyang ginagawa ay sinabi niya sa kanyang mga alagad,
Nang mabalitaan ng Cananeo, na hari ng Arad, na naninirahan sa Negeb, na ang Israel ay daraan sa Atarim, nilabanan niya ang Israel at binihag ang iba sa kanila.
Nang iwan sila ng mga anghel patungo sa langit, sinabi ng mga pastol sa isa't isa, “Pumunta tayo ngayon sa Bethlehem at tingnan natin ang nangyaring ito na ipinaalam sa atin ng Panginoon.”
upang ipakita ang habag sa ating mga magulang, at alalahanin ang kanyang banal na tipan,
yamang nalalaman na anumang mabuting bagay na gawin ng bawat tao, ito ay kanyang muling tatanggapin mula sa Panginoon, maging alipin o malaya.
Subalit siya'y tumanggi at sinabi niya sa asawa ng kanyang panginoon, “Tingnan mo, ang aking panginoon ay hindi nakikialam sa akin tungkol sa anumang bagay na nasa bahay, at lahat ng kanyang pag-aari ay ipinamahala sa aking kamay.
At muli siyang nanalangin, at ang langit ay nagbigay ng ulan, at ang lupa ay sinibulan ng bunga nito.
Pagtalikod ni Pedro, nakita niya ang alagad na minamahal ni Jesus na sumusunod. Siya rin iyong nakahilig na malapit kay Jesus sa hapunan at nagsabi, “Panginoon, sino ang magkakanulo sa iyo?”
Ito'y sinabi niya upang siya'y subukin sapagkat nalalaman niya sa kanyang sarili kung ano ang gagawin niya.
Dumating naman si Simon Pedro na sumusunod sa kanya, pumasok siya sa libingan at nakita niyang nakalatag ang mga telang lino,
at sa kanya ay ibinahagi ni Abraham ang ikasampung bahagi ng lahat. Una, ang kahulugan ng kanyang pangalan ay hari ng katuwiran; ikalawa, siya rin ay hari ng Salem, na ang kahulugan ay hari ng kapayapaan.
‘Ikaw ay daraan sa araw na ito sa hangganan ng Moab sa Ar.
at ang tadyang na kinuha ng Panginoong Diyos sa lalaki ay ginawang isang babae, at dinala siya sa lalaki.
At ang Diyos ay pumailanglang mula sa tabi niya kung saan siya ay nakipag-usap sa kanya.
Ang siya'y ibigin nang buong puso, buong pagkaunawa, buong lakas, at ibigin ang kapwa niya na gaya ng kanyang sarili, ay higit pa kaysa lahat ng mga handog na sinunog at mga alay.”
Akong si Pablo ay sumusulat ng pagbating ito ng aking sariling kamay. Ito ang palatandaan sa bawat sulat ko; gayon ako sumusulat.
Sinabi ni Jacob kay Jose, “Ang Diyos na Makapangyarihan sa lahat ay nagpakita sa akin sa Luz sa lupain ng Canaan, at binasbasan ako,
Ito ang mga angkan ng mga anak ni Noe, ayon sa kanilang lahi, at bansa. Sa mga ito nagsimulang kumalat ang mga bansa pagkatapos ng baha.
Sinabi ni Moises sa Diyos, “Sino ako upang pumaroon kay Faraon at upang ilabas sa Ehipto ang mga anak ni Israel?”
At dinala nila ang batang lalaki sa kanya. Nang makita siya ng espiritu, agad nitong pinangisay ang bata at siya'y nalugmok sa lupa, at nagpagulung-gulong na bumubula ang bibig.
Sana'y mapagtiisan ninyo ako sa kaunting kahangalan. Subalit tunay na nagtitiis kayo sa akin!
Naghulma siya para doon ng apat na argolyang ginto at inilagay ang mga argolya sa apat na sulok na ukol sa apat na paa niyon.
“Kapag inyong ginagapas ang anihin sa inyong lupain, huwag ninyong gagapasan ang inyong bukid hanggang sa mga sulok nito, ni huwag ninyong titipunin ang mga nalaglag sa inyong ginapasan.
Kaya't siya'y nagmadali, bumaba, at natutuwa siyang tinanggap.
upang parangalan ng lahat ang Anak, na gaya rin ng kanilang pagpaparangal sa Ama. Ang hindi nagpaparangal sa Anak ay hindi nagpaparangal sa Ama na sa kanya'y nagsugo.
Ibinalita sa kanila ng mga nakakita kung paano pinagaling ang inalihan ng mga demonyo.
Ang mga ito ang naging anak ni Midian: Efa, Efer, Hanoc, Abida, at Eldaa. Lahat ng ito ay mga anak ni Ketura.
Sinabi sa kanya ni Isaac na kanyang ama, “Anak ko, lumapit ka ngayon at humalik ka sa akin.”
Sapagkat sinumang wala ng mga bagay na ito ay bulag at ang nasa malapit lamang ang nakikita, at nakalimutan na siya ay nilinis mula sa kanyang dating mga kasalanan.
Ang mga salamangkero ay nagsikap sa pamamagitan ng kanilang mga lihim na kaalaman na magpalabas ng mga kuto, ngunit hindi nila nagawa. Kaya't nagkaroon ng kuto sa tao at sa hayop.
Sila'y pinapangakuan nila ng kalayaan, gayong sila mismo'y mga alipin ng kabulukan; sapagkat sinuman ay inaalipin ng anumang lumupig sa kanila.
Ang bawat natakot sa salita ng Panginoon sa mga lingkod ni Faraon ay nagpauwi ng kanyang mga alipin at ng kanyang hayop sa mga bahay;
Subalit sinabi ni Abram kay Sarai, “Ang iyong alila ay nasa iyong kapangyarihan. Gawin mo sa kanya ang mabuti sa iyong paningin.” Pinagmalupitan siya ni Sarai at si Hagar ay tumakas.
Ako ba'y nagkasala sa pagpapakababa ko sa aking sarili upang kayo'y maitaas, dahil sa ipinangaral ko sa inyo nang walang bayad ang ebanghelyo ng Diyos?
bawat uwak ayon sa kanyang uri;
Pagkatapos ay kumilos ang pinakapunong pari at ang lahat ng mga kasama niya (na sekta ng mga Saduceo) at sila'y napuno ng inggit.
At iyong pupuksain ang lahat ng mga tao na ibibigay sa iyo ng Panginoon mong Diyos; huwag kang mahahabag sa kanila; ni maglilingkod sa kanilang mga diyos, sapagkat iyon ay magiging isang bitag sa iyo.
Ngayon, sa kanya na makakagawa ng higit na sagana kaysa lahat ng ating hinihingi o iniisip, ayon sa kapangyarihang gumagawa sa atin,
Nang mabalitaan iyon ng kanyang sambahayan, lumabas sila upang siya'y pigilan sapagkat sinasabi ng mga tao, “Wala siya sa sarili.”
ang tao na humipo sa gayon ay magiging marumi hanggang sa paglubog ng araw. Huwag siyang kakain ng mga banal na bagay, kundi paliliguan niya ang kanyang katawan sa tubig.
At narinig ko ang isang malakas na tinig sa langit na nagsasabi, “Ngayo'y dumating ang kaligtasan at ang kapangyarihan, at ang kaharian ng ating Diyos, at ang kapangyarihan ng kanyang Cristo, sapagkat itinapon na ang tagapag-paratang sa ating mga kapatid na siyang nagpaparatang sa kanila sa harapan ng ating Diyos, araw at gabi.
bagama't ako'y may dahilang magtiwala rin sa laman. Kung ang iba ay may dahilang magtiwala sa laman, ay lalo na ako:
At sinabi niya sa kanya, “Hayaan mo munang mapakain ang mga anak sapagkat hindi marapat na kunin ang tinapay ng mga anak at ihagis ito sa mga aso.”
Kaya't sinabi ng Panginoon kay Moises, “Isama mo si Josue na anak ni Nun, isang lalaking nagtataglay ng Espiritu, at ipatong mo ang iyong kamay sa kanya.
Subalit kung sasabihin natin, ‘Mula sa mga tao,’ ay babatuhin tayo ng mga taong-bayan, sapagkat sila'y napapaniwala na si Juan ay isang propeta.”
Ngayon, ako'y pupunta sa aking bayan. Pumarito ka at aking ipahahayag sa iyo ang gagawin ng bayang ito sa iyong bayan sa mga huling araw.”
na sa pamamagitan din nito ang daigdig noon ay inapawan ng tubig at nagunaw.
Masikap ninyong ingatan ang mga utos ng Panginoon ninyong Diyos, at ang kanyang mga patotoo, at ang kanyang mga tuntunin na kanyang iniutos sa iyo.
Samantalang naninirahan si Israel sa lupaing iyon, si Ruben ay humayo at sumiping kay Bilha na asawang-lingkod ng kanyang ama at ito'y nabalitaan ni Israel. Labindalawa nga ang anak na lalaki ni Jacob.
Lumapit kayo sa akin, kayong lahat na nanlulupaypay at lubhang nabibigatan at kayo'y bibigyan ko ng kapahingahan.
Nang gabing iyon, lumapit sa kanya ang Panginoon at sinabi, “Lakasan mo ang iyong loob! Sapagkat kung paano kang nagpatotoo tungkol sa akin sa Jerusalem, ay kailangang magpatotoo ka rin sa Roma.”
ang sabi niya na nakarinig ng mga salita ng Diyos, na nakakita ng pangitain ng Makapangyarihan sa lahat, na nakalugmok ngunit bukas ang mga mata.
Kapag kayo'y dinala nila sa paglilitis at kayo'y ipinadakip, huwag kayong mabalisa kung ano ang inyong sasabihin, ngunit sabihin ninyo ang anumang ipagkaloob sa inyo sa oras na iyon, sapagkat hindi kayo ang magsasalita, kundi ang Espiritu Santo.
at gumawa ka ng insenso, na pabangong ayon sa pagtitimpla ng manggagawa ng pabango, hinaluan ng asin, dalisay at banal.
Kanyang sinabi, “Aking narinig na may trigo sa Ehipto. Bumaba kayo roon, at bumili kayo ng para sa atin, upang tayo'y mabuhay at huwag mamatay.”
At sinabi sa kanya ng Panginoon, ‘Alisin mo ang mga sandalyas sa iyong mga paa sapagkat ang dakong kinatatayuan mo ay lupang banal.
Kaya't akin na ngayon ang dalawa mong anak na ipinanganak sa iyo sa lupain ng Ehipto bago ako pumarito sa iyo: sina Efraim at Manases, gaya nina Ruben at Simeon.
Sapagkat kung tayo'y sumasampalatayang si Jesus ay namatay at muling binuhay ay gayundin naman, sa pamamagitan ni Jesus, ang mga natutulog ay dadalhin ng Diyos na kasama niya.
May anim na sangang lumalabas sa mga tagiliran niyon; ang tatlong sanga ng ilawan ay sa isang tagiliran, at ang tatlong sanga ng ilawan ay sa kabilang tagiliran;
na kanyang binuksan para sa atin ang isang bago at buháy na daan, sa pamamagitan ng tabing, samakatuwid ay sa kanyang laman,
Sa simula ay kasama na siya ng Diyos.
At tinanong siya ni Jesus, “Ano ang pangalan mo?” Sumagot siya, “Lehiyon ang pangalan ko sapagkat marami kami.”
Iniwan nila ang daang matuwid at naligaw sila, palibhasa'y sumunod sa daan ni Balaam na anak ni Beor, na umibig sa kabayaran ng kalikuan.
Ang pari na kanyang hihirangin at itatalaga upang maging pari na kapalit ng kanyang ama, ay siyang gagawa ng pagtubos na suot ang mga banal na kasuotang lino.
At sinabi sa kanya, “Ang bawat tao ay unang naghahain ng mataas na uring alak, pagkatapos ay ang mababang uring alak kapag ang mga panauhin ay nakainom na. Subalit hanggang ngayon ay itinabi mo ang mabuting alak.”
Ang unang nilalang ay tulad ng isang leon, ang ikalawang nilalang ay tulad ng isang baka, ang ikatlong nilalang ay may mukha ng isang tao, at ang ikaapat na nilalang ay tulad ng isang agilang lumilipad.
At nang makapagpaningas sila ng apoy sa gitna ng patyo at makaupong magkakasama, si Pedro ay nakiupong kasama nila.
Ang mga eskriba at ang mga Fariseo ay nagmamatyag sa kanya kung siya'y magpapagaling sa Sabbath upang makakita sila ng maibibintang laban sa kanya.
Sinabi ni Moises sa kanila, “Maghintay kayo upang aking marinig ang ipag-uutos ng Panginoon tungkol sa inyo.”
Kung gayon, bakit hindi mo inilagay ang aking salapi sa bangko at nang sa aking pagbalik ay makuha ko iyon pati ng tinubo?’
mula sa dugo ni Abel hanggang sa dugo ni Zacarias, na pinatay sa pagitan ng dambana at ng santuwaryo. Oo, sinasabi ko sa inyo, na ito'y hihingin sa lahing ito.
“Ang Moises na ito na kanilang itinakuwil, na sinasabi, ‘Sino ang sa iyo'y naglagay na pinuno at hukom?’ ang siyang sinugo ng Diyos na maging pinuno at tagapagligtas sa pamamagitan ng anghel na sa kanya'y nagpakita sa mababang punungkahoy.
ang buong sambahayan ni Jose, ang kanyang mga kapatid, at ang sambahayan ng kanyang ama. Tanging ang kanilang mga anak lamang, mga kawan, at bakahan, ang iniwan nila sa lupain ng Goshen.
At sinasabi ko sa inyo, humingi kayo at kayo'y bibigyan; humanap kayo, at kayo'y makakakita; tumuktok kayo at kayo'y pagbubuksan.
upang, yamang inaring-ganap sa pamamagitan ng kanyang biyaya, tayo'y maging mga tagapagmana ayon sa pag-asa sa buhay na walang hanggan.
Siya'y kanilang dinala sa pook na tinatawag na Golgota na ang kahulugan ay ‘Ang pook ng bungo.’
Kasama ng lahat ng mga ito, taglayin ninyo ang kalasag ng pananampalataya, na sa pamamagitan nito ay inyong masusugpo ang mga nag-aapoy na palaso ng masama.
Kaya't pagkatapos ay maliwanag na sinabi sa kanila ni Jesus, “Namatay si Lazaro,
Sapagkat kung nasaan ang iyong kayamanan, naroon din naman ang iyong puso.
Iyong bubuhusan niyon ang toldang tipanan, at ang kaban ng patotoo,
At sinabi ni Israel, “Sapat na! Si Jose na aking anak ay buháy pa. Dapat akong pumunta at makita siya bago ako mamatay.”
Sinabi sa kanya ng panginoon niya, ‘Magaling! Mabuti at tapat na alipin. Naging tapat ka sa kaunting bagay, pamamahalain kita sa maraming bagay. Pumasok ka sa kagalakan ng iyong panginoon.’
Sapagkat ang lahat na nasa sanlibutan, ang masamang pagnanasa ng laman, ang pagnanasa ng mga mata, at ang pagmamataas sa buhay, ay hindi mula sa Ama kundi sa sanlibutan.
Katotohanang sinasabi ko sa inyo, na kayo'y iiyak at tatangis, subalit ang sanlibutan ay magagalak. Kayo'y malulungkot, subalit ang inyong kalungkutan ay magiging kagalakan.
Kinagabihan, sila'y nagpangkat-pangkat laban sa kaaway, siya at ang kanyang mga alipin, at sila'y kanilang ginapi at hinabol sila hanggang sa Hoba na nasa hilaga ng Damasco.
mag-ingat ka upang huwag kang mabitag na sumunod sa kanila, pagkatapos na sila'y mapuksa sa harapan mo. Huwag kang mag-usisa ng tungkol sa kanilang mga diyos, na magsabi, ‘Paanong naglingkod ang mga bansang ito sa kanilang mga diyos? Gayundin ang gagawin ko.’
at ang mga kasuotang mahusay ang pagkagawa, ang mga banal na kasuotan para kay Aaron na pari, at ang mga kasuotan ng kanyang mga anak, para sa kanilang paglilingkod bilang mga pari;
Sa may kalayuan sa kanila ay may isang kawan ng maraming baboy na nanginginain.
At dumating ang mga tao upang tingnan ang nangyari. Lumapit sila kay Jesus at kanilang nadatnan ang taong nilisan ng mga demonyo na nakaupo sa paanan ni Jesus na may damit at matino ang pag-iisip nito; at sila'y natakot.
Kung ang isang kaharian ay nagkakabaha-bahagi laban sa kanyang sarili, hindi makakatayo ang kahariang iyon.
Pagkatapos, tayong nabubuhay na natitira ay aagawing kasama nila sa mga ulap, upang salubungin ang Panginoon sa papawirin; at sa gayon ay makakapiling natin ang Panginoon magpakailanman.
Ngunit nararapat lamang na magsaya at magalak, sapagkat ang kapatid mong ito ay patay at muling nabuhay; siya'y nawala at natagpuan.’”
At sinumang tumanggap sa isang batang ganito sa aking pangalan ay tumatanggap sa akin.
Nang ikalabinlimang taon ng paghahari ni Tiberio Cesar, si Poncio Pilato ang gobernador sa Judea, at tetrarka sa Galilea si Herodes. Ang kanyang kapatid na si Felipe ang tetrarka sa lupain ng Iturea at Traconite, at si Lisanias ang tetrarka sa Abilinia,
at kung ang lupain ay mataba o payat, kung mayroong kahoy o wala. Magpakatapang kayo at magdala kayo rito ng mga bunga ng lupain.” Ang panahong iyon ay panahon ng mga unang hinog na ubas.
Sinuman sa kanila ay di nangahas na makisama sa kanila subalit sila'y itinataas ng mga tao.
at ang liebre, bagaman ngumunguya, subalit walang hati ang paa, ito ay marumi para sa inyo,
kanilang binigyan siya ng alak na may kahalong apdo upang inumin. Ngunit nang kanyang matikman ay ayaw niyang inumin.
“Bilangin mo ang buong kapulungan ng mga anak ni Israel mula sa dalawampung taong gulang pataas ayon sa mga sambahayan ng kanilang mga ninuno, ang lahat sa Israel na may kakayahang makipagdigma.
ay hindi papasok sa lupaing aking ipinangako na patitirahan ko sa inyo, maliban kay Caleb na anak ni Jefone at kay Josue na anak ni Nun.
Pitong araw na iyong gagawan ng katubusan ang dambana, at iyong pakakabanalin ito, at ang dambana ay magiging kabanal-banalan; anumang humipo sa dambana ay magiging banal.
Ngayon, nawa'y mismong ang Panginoon ng kapayapaan ang magbigay sa inyo ng kapayapaan sa lahat ng panahon at sa lahat ng paraan. Ang Panginoon ay sumainyo nawang lahat.
Aking sinabi sa inyo, ‘Inyong narating ang lupaing maburol ng mga Amoreo na ibinibigay sa atin ng Panginoon nating Diyos.
Tinawag ni Abraham na Isaac ang anak na ipinanganak sa kanya ni Sara.
Ilalagay mo ang lahat ng ito sa mga kamay ni Aaron at sa mga kamay ng kanyang mga anak; at iyong iwawagayway ang mga ito bilang handog na iwinawagayway sa harapan ng Panginoon .
Sa lipi ng mga anak ni Simeon ay si Samuel na anak ni Amihud.
Subalit hindi nagtagal at bumulusok ang isang maunos na hangin na tinatawag na Euraclidon.
Hindi ako nagsasalita tungkol sa inyong lahat; nakikilala ko ang aking mga hinirang. Ngunit ito ay upang matupad ang kasulatan, ‘Ang kumain ng aking tinapay ay nagtaas ng kanyang sakong laban sa akin.’
Kung hindi nga ninyo magawa ang ganoong kaliit na bagay, bakit mag-aalala kayo tungkol sa mga ibang bagay?
Pinatay nila ang mga hari sa Midian: sina Evi, Rekem, Zur, Hur, at Reba, limang hari sa Midian. Sina Balaam na anak ni Beor ay kanilang pinatay rin ng tabak.
At habang nagsasalita ang ilan tungkol sa templo, kung paanong ito'y napalamutian ng magagandang bato at ng mga handog ay kanyang sinabi,
Iyong ilalapat ang hatol na kanilang ipinaalam sa iyo mula sa lugar na pipiliin ng Panginoon ; at masikap na isasagawa ang lahat na kanilang ituturo sa iyo.
Kapag itinataas ni Moises ang kanyang kamay ay nananalo ang Israel; at kapag kanyang ibinababa ang kanyang kamay ay nananalo ang Amalek.
Nanguna sa hukbo ng lipi ng mga anak ni Simeon si Selumiel na anak ni Zurishadai.
Kahit na noong una ako'y isang lapastangan, mang-uusig at mang-aalipusta, gayunma'y kinahabagan ako, sapagkat sa kamangmangan ay ginawa ko iyon sa kawalan ng pananampalataya,
Habang si Pedro ay nasa bilangguan, ang iglesya ay taimtim na nanalangin sa Diyos para sa kanya.
Sapagkat ito ang pag-ibig sa Diyos, na ating tuparin ang kanyang mga utos at ang kanyang mga utos ay hindi pabigat.
“Kapag dumating na ang Anak ng Tao na nasa kanyang kaluwalhatian, na kasama niya ang lahat ng mga anghel, siya'y uupo sa trono ng kanyang kaluwalhatian.
Pagkatapos nito, maghuhubad siya ng kanyang mga suot at magbibihis ng ibang mga kasuotan, at ilalabas ang mga abo sa kampo sa isang malinis na pook.
“Pagkatapos ay papatayin niya ang kambing na handog pangkasalanan na para sa bayan, at dadalhin ang dugo niyon sa loob ng tabing. Ang gagawin sa dugo ay ang gaya ng ginawa sa dugo ng toro, at iwiwisik iyon sa ibabaw ng luklukan ng awa at sa harapan ng luklukan ng awa.
Ako'y pumihit at bumaba mula sa bundok, at aking isinilid ang mga tapyas sa kaban na aking ginawa, at ang mga iyon ay naroroon, na gaya ng iniutos sa akin ng Panginoon .
Huwag kang magbibigay ng iyong anak upang italaga iyon sa apoy kay Molec; ni huwag mong lalapastanganin ang pangalan ng iyong Diyos; Ako ang Panginoon .
At nakita kong lumabas sa bibig ng dragon at mula sa bibig ng halimaw at mula sa bibig ng bulaang propeta ang tatlong espiritung karumaldumal, na gaya ng mga palaka.
Sino ang mahina, at ako ba'y hindi mahina? Sino ang natitisod, at ako'y di nag-iinit?
Sa gayo'y pumihit ako at bumaba mula sa bundok, at ang bundok ay nagniningas sa apoy, at ang dalawang tapyas ng tipan ay nasa aking dalawang kamay.
Maaari ninyong kainin ang lahat ng ibong malilinis.
Sinabi ni Israel kay Jose, “Hindi ba nagpapastol ng kawan sa Shekem ang iyong mga kapatid? Halika, at isusugo kita sa kanila.” Sinabi niya sa kanya, “Narito ako.”
Subalit siya'y nanlumo sa sinabing ito, at siya'y umalis na nalulungkot sapagkat siya'y maraming ari-arian.
kami ay nagpaalam sa isa't isa. Pagkatapos, lumulan na kami sa barko at sila'y umuwi na sa kanilang mga bahay.
Samantalang nakikipag-usap pa siya sa kanila, dumating si Raquel kasama ang mga tupa ng kanyang ama; sapagkat siya ang nag-aalaga ng mga iyon.
Tunay na sa ganitong kalagayan, ang dating may kaluwalhatian ay nawalan ng kanyang kaluwalhatian, dahil sa kaluwalhatiang nakahihigit dito.
sapagkat iyon lamang ang kanyang saplot, iyon ang kanyang pantakip sa kanyang katawan, ano pa ang kanyang ipapantulog? At kapag siya'y dumaing sa akin ay aking diringgin sapagkat ako'y mahabagin.
Sa pananampalataya si Noe, nang mabigyan ng Diyos ng babala tungkol sa mga bagay na hindi pa nakikita, ay pinakinggan ang babala at gumawa ng isang daong para sa kaligtasan ng kanyang sambahayan. Sa pamamagitan nito ay hinatulan niya ang sanlibutan, at siya'y naging tagapagmana ng katuwirang ayon sa pananampalataya.
Nang mawasak na niya ang pitong bansa sa lupain ng Canaan, ibinigay niya sa kanila ang kanilang lupain bilang pamana,
Mga kapatid, kunin ninyong halimbawa ng pagtitiis at ng pagtitiyaga ang mga propeta na nagsalita sa pangalan ng Panginoon.
Isusuot ito ni Aaron kapag siya'y nangangasiwa at ang tunog niyon ay maririnig kapag siya'y pumapasok sa dakong banal sa harapan ng Panginoon , at kapag siya'y lumalabas, upang siya'y huwag mamatay.
“Panginoon, pinatay nila ang iyong mga propeta, giniba nila ang iyong mga dambana; at ako'y naiwang nag-iisa, at tinutugis nila ang aking buhay.”
ni Cainan, ni Arfaxad, ni Sem, ni Noe, ni Lamec,
Nang mabalitaan niya na si Jesus ay dumating sa Galilea mula sa Judea, pumunta siya roon at nakiusap sa kanya na siya'y pumunta at pagalingin ang kanyang anak na lalaki sapagkat siya'y malapit nang mamatay.
Minamahal, ginagawa mo ang tapat na gawa tuwing gagawa ka ng paglilingkod sa mga kapatid, at gayundin sa mga taga-ibang bayan,
Ang balong hinukay ng mga pinuno, na pinalalim ng mga maharlika ng bayan, ng kanilang setro at mga tungkod.” At mula sa ilang, sila'y nagpatuloy patungo sa Matana,
Sapagkat kung kayo'y palungkutin ko, sino ang magpapagalak sa akin, kundi iyong pinalungkot ko?
Tingnan mo, ang salapi na aming natagpuan sa ibabaw ng aming mga sako ay aming isinauli sa iyo mula sa lupain ng Canaan. Paano naming mananakaw ang pilak at ginto sa bahay ng iyong panginoon?
Sapagkat sinumang kumain ng taba ng hayop na iyon kung saan ang handog ay pinaraan sa apoy para sa Panginoon , ay ititiwalag sa kanyang bayan.
“Kung mag-away ang dalawang lalaki at makasakit ng isang babaing nagdadalang-tao, na anupa't makunan, at gayunma'y walang pinsalang sumunod, pagbabayarin ang nakasakit, ayon sa iaatang sa kanya ng asawa ng babae; at siya'y magbabayad ng ayon sa ipasiya ng mga hukom.
Nilikha niya mula sa isa ang bawat bansa ng mga tao upang manirahan sa ibabaw ng buong lupa. Itinakda niya ang mga panahon at mga hangganan ng kanilang titirhan,
Pagkasabi nito, siya'y lumingon at nakitang nakatayo si Jesus. Subalit hindi niya alam na iyon ay si Jesus.
ay iinom din naman ng alak ng poot ng Diyos, na inihahandang walang halo sa kopa ng kanyang poot at pahihirapan sa apoy at asupre sa harapan ng mga banal na anghel at sa harapan ng Kordero.
at ang ilang babae na pinagaling mula sa masasamang espiritu at sa mga sakit: si Maria na tinatawag na Magdalena, na mula sa kanya'y pitong demonyo ang lumabas,
Bawat butil na handog ng pari ay susunuging buo, hindi ito kakainin.”
Kinuha ng Panginoong Diyos ang lalaki at inilagay sa halamanan ng Eden upang ito ay kanyang bungkalin at ingatan.
“Kung ang magkapatid ay naninirahang magkasama, at isa sa kanila'y namatay at walang anak, ang asawang babae ng namatay ay huwag mag-aasawa ng isang dayuhan o sa labas ng pamilya. Ang kapatid na lalaki ng kanyang asawa ay sisiping sa kanya, kukunin siya bilang asawa, at tutuparin sa kanya ang tungkulin ng kapatid na namatay.
nalaman ito ng mga apostol at sila'y tumakas patungo sa Listra at Derbe, na mga lunsod ng Licaonia at sa palibot na lupain,
At naging anak ni Canaan sina Sidon, na kanyang panganay, at si Het,
isang lunsod na malaki, marami at matataas na gaya ng mga Anakim; ngunit sila ay pinuksa ng Panginoon nang harapan. Sila'y sinamsaman at nanirahang kapalit nila.
na lumapit sa kanyang likuran, hinawakan ang laylayan ng kanyang damit, at agad na tumigil ang kanyang pagdurugo.
Sapagkat si Cristo ang kinauuwian ng kautusan upang maging matuwid ang bawat sumasampalataya.
Lumingon ang Panginoon at tumingin kay Pedro. At naalala ni Pedro ang salita ng Panginoon, kung paanong sinabi niya sa kanya, “Bago tumilaok ang manok ngayon, ay ipagkakaila mo ako ng tatlong ulit.”
Sapagkat kung ang dugo ng mga kambing at ng mga toro, at ang abo ng dumalagang baka na iwiniwisik sa mga nadungisan ay makapagpapabanal sa ikalilinis ng laman,
Sa unang araw ay magkakaroon kayo ng banal na pagpupulong; huwag kayong gagawa ng anumang mabigat na gawain.
Nang sama-samang lumapit sa kanya ang mga Fariseo at ang ilan sa mga eskriba na nanggaling sa Jerusalem,
Magsikap kang pumarito agad sa akin,
upang gumawa ng magagandang dibuho, gumawa sa ginto, sa pilak, at sa tanso,
Nang tumunog ang pitong kulog, susulat sana ako, ngunit narinig ko ang isang tinig mula sa langit na nagsasabi, “Tatakan mo ang mga bagay na sinabi ng pitong kulog, at huwag mong isulat ang mga ito.”
Sa kahuli-huliha'y sinugo niya sa kanila ang kanyang anak na lalaki, na nagsasabi, ‘Igagalang nila ang aking anak.’
Sapagkat kung hindi mo papayagang umalis ang aking bayan ay magsusugo ako ng pulu-pulutong na langaw sa iyo, sa iyong mga lingkod, sa iyong bayan, at sa loob ng inyong mga bahay. Ang mga bahay ng mga Ehipcio ay mapupuno ng pulu-pulutong na langaw, at gayundin ang lupang kinaroroonan nila.
“Sa araw na ito ay iniuutos sa iyo ng Panginoon mong Diyos na tuparin mo ang mga tuntunin at mga batas na ito; iyo ngang maingat na tutuparin ng buong puso at kaluluwa mo.
Kung siya'y ating pabayaan ng ganito, ang lahat ng mga tao ay maniniwala sa kanya. Darating ang mga Romano at wawasakin ang ating Templo at ang ating bansa.”
Subalit sinabi sa kanya ng Diyos, ‘Hangal, sa gabing ito ay kukunin ang iyong kaluluwa; at kanino kaya mapupunta ang mga bagay na inihanda mo?’
Nang matapos na ng diyablo ang lahat ng panunukso, lumayo siya sa kanya hanggang sa isa pang pagkakataon.
Mga kapatid ko, huwag kayong magkaroon ng pagtatangi habang tinataglay ninyo ang pananampalataya sa ating Panginoong Jesu-Cristo, ang Panginoon ng kaluwalhatian.
At inaakala mo ba ito, O tao, na humahatol sa mga gumagawa ng gayong mga bagay, at gayundin ang ginagawa mo, na ikaw ay makakatakas sa hatol ng Diyos?
Sila'y sumigaw nang may malakas na tinig, “Kailan pa, O Makapangyarihang Panginoon, banal at totoo, bago mo hatulan at ipaghiganti ang aming dugo sa mga naninirahan sa ibabaw ng lupa?”
Subalit si Miguel na arkanghel nang makipaglaban sa diyablo, at nakipagtalo tungkol sa katawan ni Moises, ay hindi nangahas gumamit ng isang hatol na may pag-alipusta laban sa kanya, kundi sinabi, “Sawayin ka nawa ng Panginoon.”
Ngunit kapag nag-aayuno ka, lagyan mo ng langis ang iyong ulo, at maghilamos ka ng iyong mukha;
Taglay natin ito bilang isang tiyak at matibay na angkla ng kaluluwa, isang pag-asa na pumapasok sa loob ng santuwaryo, sa kabila ng tabing,
Nang araw ding iyon ay iniutos ng Faraon sa mga tagapangasiwa sa mga tao at sa kanilang mga kapatas,
At siya'y kukuha ng dugo ng toro at iwiwisik ito sa pamamagitan ng kanyang daliri sa ibabaw ng luklukan ng awa, at sa harapan ng luklukan ng awa ay iwiwisik niya ng pitong ulit ang dugo sa pamamagitan ng kanyang daliri.
Tumindig si Rebecca at ang kanyang mga abay, at sila ay sumakay sa mga kamelyo, at sumunod sa lalaki; at dinala ng alipin si Rebecca at humayo.
Ito'y babalutin mo ng lantay na ginto, ang mga tagiliran sa palibot, at ang mga sungay; at igagawa mo ito ng isang moldeng ginto sa palibot.
“Mabuti ang asin, subalit kung ang asin ay mawalan ng kanyang lasa, paano maibabalik ang alat nito?
Kanilang gagawin ang efod na ginto, at may telang asul, kulay-ube, pula, at hinabing pinong lino, na ginawa ng isang bihasang manggagawa.
Hindi ito lulutuing may pampaalsa. Aking ibinigay iyon bilang kanilang bahagi mula sa handog sa akin na pinaraan sa apoy; ito ay kabanal-banalan gaya ng handog pangkasalanan at handog para sa budhing maysala.
At naging anak ni Mizraim sina Ludim, Anamim, Lehabim, at Naphtuhim,
Sumagot si Jesus at sinabi sa kanila, “Mag-ingat kayo na huwag kayong mailigaw ng sinuman.
Ang dalawang bato, at ang tabang nasa loob nito na malapit sa mga balakang, at ang lamad na nasa atay ay aalisin niya kasama ng mga bato.
“Kukunin mo rin ang taba ng lalaking tupa, at ang matabang buntot, at ang tabang nakabalot sa mga bituka, ang mga taba ng atay, ang dalawang bato, ang taba na nasa ibabaw ng mga iyon, at ang kanang hita (sapagkat iyon ay isang lalaking tupa na itinatalaga),
apatnapung taon. Kaya't nagalit ako sa lahing ito, at aking sinabi, ‘Sila'y laging naliligaw sa kanilang puso, at hindi nila nalaman ang aking mga daan.’
Tinanong siya ng kanyang mga alagad, “Rabi, sino ang nagkasala, ang taong ito, o ang kanyang mga magulang, kaya siya'y ipinanganak na bulag?”
Inyong ihahandog ang mga ito bukod pa sa handog na sinusunog sa umaga, bilang palagiang handog na sinusunog.
Sinabi sa kanya ni Jesus, “Huwag mo akong hawakan, sapagkat hindi pa ako nakakaakyat sa Ama. Ngunit pumunta ka sa aking mga kapatid, at sabihin mo sa kanila, ‘Aakyat ako sa aking Ama at inyong Ama, sa aking Diyos at inyong Diyos.’”
Sasaktan ka ng Panginoon ng pagkabaliw, ng pagkabulag, at ng pagkalito ng isipan;
Sinabi ni Pilato sa kanila, “Mayroon kayong bantay, humayo kayo, bantayan ninyo sa paraang alam ninyo.”
At siya'y dumating at ipinangaral ang kapayapaan sa inyo na malalayo, at kapayapaan sa mga malalapit.
upang itaas ka sa lahat ng bansa na kanyang nilikha, sa ikapupuri, sa ikababantog, sa ikararangal; at upang ikaw ay maging isang banal na bayan sa Panginoon mong Diyos, gaya ng kanyang sinabi.”
At lahat ng matatanda sa bayang iyon na malapit sa pinatay ay maghuhugas ng kanilang kamay sa ibabaw ng dumalagang baka na binali ang leeg sa libis;
Sila'y pinagbabato hanggang mamatay, nilagari, pinagpapatay sa tabak, sila'y naglibot na may suot na balat ng mga tupa at kambing, mga naghihirap, pinag-uusig, inaapi
Kaya't hindi kalooban ng inyong Ama na nasa langit na ang isa sa maliliit na ito ay mapahamak.
“‘Ipangilin mo ang araw ng Sabbath, at ingatan mo itong banal, gaya ng iniuutos sa iyo ng Panginoon mong Diyos.
At sinasabi ko sa inyo, mula ngayon ay hindi na ako iinom ng katas ng ubas na ito hanggang sa araw na iyon na iinumin kong panibago na kasalo kayo sa kaharian ng aking Ama.”
Nang panahong iyon, lumusong si Juda papalayo sa kanyang mga kapatid, at tumira malapit sa isang Adullamita na ang pangalan ay Hira.
At sinabi ng Panginoon kay Moises, “Hanggang kailan ako hahamakin ng bayang ito? At hanggang kailan sila hindi maniniwala sa akin, sa kabila ng mga tanda na aking ginawa sa kanila?
Sapagkat pinagtitiisan ninyo ito kapag inaalipin kayo, o kapag nilalapa kayo, o kapag kayo'y pinagsasamantalahan, o kapag pinagyayabangan, o kapag kayo'y sinasampal sa mukha.
Subalit ipapakita ko sa inyo kung sino ang inyong dapat katakutan; katakutan ninyo siya na pagkatapos pumatay ay may kapangyarihang magtapon sa impiyerno. Oo, sinasabi ko sa inyo, siya ang inyong katakutan.
Gayundin naman ang mangyayari sa araw na ang Anak ng Tao ay mahayag.
Ano ngayon? Ang hinahanap ng Israel ay hindi niya nakamtan, ngunit ito'y nakamtan ng hinirang at ang iba'y pinapagmatigas,
Nang siya'y mapahintulutan na niya, si Pablo ay tumayo sa mga baytang at isinenyas ang kamay sa mga tao, at nang magkaroon ng malaking katahimikan, nagsalita siya sa wikang Hebreo, na sinasabi:
At sinabi, “Panginoon ko, kung ako'y nakatagpo ng biyaya sa inyong paningin ay hinihiling ko sa inyo na huwag mong lampasan ang iyong lingkod.
Nabalitaan ng mga apostol at ng mga kapatid na nasa Judea na tinanggap din ng mga Hentil ang salita ng Diyos.
Dapat niyang kilalaning panganay ang anak ng kinapopootan sa pamamagitan ng pagbibigay sa kanya ng dalawang bahagi sa lahat ng mayroon siya, sapagkat siya ang pasimula ng kanyang lakas at ang karapatan ng pagkapanganay ay kanya.
Hayaan mong lipulin ko sila, at aking burahin ang kanilang pangalan sa ilalim ng langit; at gagawin kitang isang bansang higit na makapangyarihan at malaki kaysa kanila.’
Aking ilalagay ang iyong hangganan mula sa Dagat na Pula hanggang sa dagat ng Filistia, at mula sa ilang hanggang sa Eufrates sapagkat aking ibibigay sa iyong kamay ang mga nananahan sa lupain at iyong papalayasin sila sa harapan mo.
Kanyang sinabi, “Ihagis mo sa lupa.” Kanyang inihagis ito sa lupa at ito'y naging isang ahas. Si Moises ay lumayo sa ahas.
“At kung ang iyong kapatid na kasama mo ay naghirap at ipinagbili sa iyo, huwag mong iaatang sa kanya ang paglilingkod ng isang alipin.
Pagkatapos nito, pitong uhay na payat at tinuyo ng hanging silangan ang tumubong kasunod ng mga iyon.
Kanyang sinabi sa kanila, “Ito ang iniutos ng Panginoon , ‘Bukas ay taimtim na pagpapahinga, banal na Sabbath sa Panginoon . Lutuin ninyo ang inyong lulutuin, at pakuluan ninyo ang inyong pakukuluan; at lahat ng lalabis ay itago ninyo, inyong ititira hanggang sa kinabukasan.’”
Sapagkat sa biyaya kayo'y naligtas sa pamamagitan ng pananampalataya, at ito'y hindi sa pamamagitan ng inyong sarili, ito'y kaloob ng Diyos;
Narito, si Rebecca ay nasa harap mo, dalhin mo, at humayo ka. Siya'y maging asawa ng anak ng iyong panginoon, gaya ng sinabi ng Panginoon .”
Hindi ba silang lahat ay mga espiritung nasa banal na gawain, na sinugo upang maglingkod sa kapakanan ng mga magmamana ng kaligtasan?
Ang biyaya ng ating Panginoong Jesu-Cristo ay sumainyo.
Saan ako kukuha ng karne upang ibigay sa buong bayang ito? Sapagkat sila'y umiyak sa akin, na nagsasabi, ‘Bigyan mo kami ng karneng makakain namin.’
Mapapalad kayo kung kayo'y kapootan ng mga tao, kung kayo'y layuan at kayo'y alipustain, at itakuwil ang inyong pangalan na tila masama dahil sa Anak ng Tao.
Nang masabi ni Jesus ang mga bagay na ito, siya'y nabagabag sa espiritu, at nagpatotoo, “Katotohanang sinasabi ko sa inyo, ako'y ipagkakanulo ng isa sa inyo.”
Ang mga angkan ng mga anak ni Kohat ay magkakampo sa tagiliran ng tabernakulo, sa gawing timog.
Sapagkat hindi niya alam kung ano ang sasabihin dahil sila'y lubhang natakot.
kundi nang siya'y nagpaalam sa kanila, ay sinabi, “Babalik uli ako sa inyo kung loloobin ng Diyos.” At siya'y naglakbay buhat sa Efeso.
Kaya't ang anumang sinabi ninyo sa dilim ay maririnig sa liwanag at ang ibinulong ninyo sa mga lihim na silid ay ipagsisigawan sa mga bubungan.
‘Tunay na walang taong lumabas sa Ehipto, mula sa dalawampung taong gulang pataas na makakakita ng lupain na aking ipinangako kina Abraham, Isaac, at Jacob; sapagkat sila'y hindi lubos na sumunod sa akin;
Tuparin ninyo at inyong gawin, sapagkat ito ang inyong magiging karunungan at kaalaman sa paningin ng mga tao na makakarinig ng mga tuntuning ito, at magsasabi, ‘Tunay na ang dakilang bansang ito ay matalino at may pagkaunawa.’
Lumapit din si Lea at ang kanyang mga anak, at nagsiyuko, pagkatapos ay nagsilapit sina Jose at Raquel, at nagsiyuko.
“Nahahabag ako sa maraming tao sapagkat tatlong araw ko na silang kasama at walang makain.
Ang iba'y nagtiis ng pagkalibak at paghagupit, at maging ng mga tanikala at pagkabilanggo.
At nagkaroon ng digmaan sa langit, si Miguel at ang kanyang mga anghel ay nakipagdigma sa dragon. Ang dragon at ang kanyang mga anghel ay nakipagdigma,
Lumabas si Isaac sa parang upang maglakad-lakad ng dapit-hapon. Itinaas niya ang kanyang mga paningin at nakita niyang may dumarating na mga kamelyo.
Ngunit nang paligiran siya ng mga alagad, tumayo siya at pumasok sa lunsod. Kinabukasan, umalis siya kasama ni Bernabe patungo sa Derbe.
Sila'y naglakbay mula sa Rimon-peres at nagkampo sa Libna.
“Kapag ikaw ay nagkaanak at nagkaanak ang inyong mga anak, at nagtagal kayo sa lupain, at nagpakasama kayo, at gumawa kayo ng larawang inanyuan na katulad ng anumang bagay, at gumawa kayo ng masama sa paningin ng Panginoon mong Diyos, upang siya ay galitin;
Sumagot si Nicodemo sa kanya, “Paanong mangyayari ang mga bagay na ito?”
Tumayo ang ilan at sumaksi ng kasinungalingan laban sa kanya, na sinasabi,
Kung ang sinuman ay may pandinig ay makinig:
Subalit ang mga anak ng naging mga asawang-lingkod ni Abraham ay binigyan ni Abraham ng mga kaloob. Habang nabubuhay pa siya ay inilayo niya ang mga ito kay Isaac na kanyang anak. Kanyang pinapunta sila sa lupaing silangan.
Kanyang sinaliksik, simula sa panganay hanggang sa bunso, at natagpuan ang kopa sa sako ni Benjamin.
ang pagpapala, kung inyong diringgin ang mga utos ng Panginoon ninyong Diyos na aking iniutos sa inyo sa araw na ito;
Sinagot naman sila ni Pilato, “Ibig ba ninyong pawalan ko sa inyo ang Hari ng mga Judio?”
Gaano pa ngang higit na mahalaga ang isang tao kaysa isang tupa! Kaya't matuwid na gumawa ng mabuti sa araw ng Sabbath.”
Hinirang ng Diyos nitong bayang Israel ang ating mga ninuno, at ginawang dakila ang bayan nang sila'y nakipamayan sa Ehipto, at sa pamamagitan ng nakataas na bisig ay kanyang inilabas sila roon.
Sapagkat ang kanilang ari-arian ay totoong napakalaki para sa kanila na manirahang magkasama. Ang lupain na kanilang pinaglakbayan ay hindi sila makayang tustusan dahilan sa kanilang mga hayop.
Ang mga unang bunga ng iyong trigo, alak, langis, at ang unang balahibo ng iyong mga tupa ay ibibigay mo sa kanya.
“Sabihin ninyo sa anak na babae ng Zion, Tingnan mo, ang iyong Hari ay dumarating sa iyo, mapagkumbaba, at nakasakay sa isang asno, at sa isang batang asno na anak ng babaing asno.”
Samantalang siya'y nakaupo sa bundok ng mga Olibo sa tapat ng templo, tinanong siya nang lihim nina Pedro, Santiago, Juan, at Andres,
At ang mga iyon ay magkahiwalay sa ilalim ngunit magkakabit at nauugnay na mainam sa itaas, sa unang argolya. Gayon ang ginawa niya sa dalawa para sa dalawang sulok.
Ang lahat ng naging araw ni Noe ay siyamnaraan at limampung taon. At siya ay namatay.
Si Elias ay isang taong may likas na gaya rin ng sa atin, at siya'y taimtim na nanalangin upang huwag umulan, at hindi umulan sa lupa sa loob ng tatlong taon at anim na buwan.
Nang makita ng senturion ang nangyari, pinuri niya ang Diyos at sinabi, “Tunay na ito'y isang taong matuwid.”
At ito'y nagpatuloy sa loob ng dalawang taon, kaya't ang lahat ng mga naninirahan sa Asia ay nakarinig ng salita ng Panginoon, ang mga Judio at gayundin ang mga Griyego.
nang ang mga anak na lalaki ni Jacob ay magsiuwi mula sa parang. Nang ito'y kanilang mabalitaan, galit na galit ang mga lalaki, sapagkat gumawa si Shekem ng kalapastanganan sa Israel sa pamamagitan ng pagsiping sa anak ni Jacob, sapagkat ang gayong bagay ay di-nararapat gawin.
Ganito ang sinabi ng Diyos, na ang kanyang binhi ay maninirahan sa lupain ng iba, at sila'y magiging alipin nila at aapihin nang apatnaraang taon.
Ito ang salaysay tungkol sa pamilya ni Jacob: Si Jose, na may labimpitong taong gulang, ay nagpapastol ng kawan kasama ng kanyang mga kapatid. Siya ay kasama ng mga anak nina Bilha at Zilpa, na mga asawa ng kanyang ama; at ibinalita ni Jose sa kanilang ama ang kasamaan nila.
Ngunit hinawakan siya ni Jesus sa kamay, at siya'y ibinangon at nagawa niyang tumayo.
At si Jesus ay umalis kasama ng kanyang mga alagad patungo sa lawa. Sumunod ang napakaraming tao mula sa Galilea.
Samantala, si Tiquico ay sinugo ko sa Efeso.
Nang pasimulan na niya ang pagkukuwenta, iniharap sa kanya ang isang nagkakautang sa kanya ng sampung libong talento.
Nang dumating ang panahon ng kanyang panganganak, kambal ang nasa kanyang tiyan.
Hindi nila naunawaan na siya ay nagsasalita sa kanila tungkol sa Ama.
Siya'y naparito sa kanyang sariling tahanan at siya'y hindi tinanggap ng kanyang sariling bayan.
Kung nabubuhay tayo, sa Panginoon tayo'y nabubuhay; o kung namamatay tayo, sa Panginoon tayo'y namamatay. Kaya't mabuhay man tayo o mamatay, tayo'y sa Panginoon.
Ngunit nang makapaghandog si Cristo ng isa lamang alay para sa mga kasalanan para sa lahat ng panahon, siya ay umupo sa kanan ng Diyos,
Sapagkat ang bawat bahay ay may nagtayo, subalit ang nagtayo ng lahat ng mga bagay ay ang Diyos.
“Kapag ang isang lalaki ay kumuha ng isang babae at pinakasalan, at kung ang babae ay hindi kalugdan ng kanyang paningin, sapagkat natagpuan niya itong may isang kahiyahiyang bagay, lalagda ang lalaki ng isang kasulatan ng paghihiwalay at ibibigay niya sa kanyang kamay. Kanyang palalabasin siya sa kanyang bahay,
at sinasabi ninyo, ‘Kung nabuhay sana kami sa mga araw ng aming mga ninuno, hindi kami makikibahagi sa kanila sa dugo ng mga propeta.’
At siya'y may isang kapatid na tinatawag na Maria na naupo sa paanan ng Panginoon at nakinig sa kanyang salita.
At kung nagpapalayas ako ng mga demonyo sa pamamagitan ni Beelzebul, sa pamamagitan naman nino pinalalayas sila ng inyong mga anak? Kaya't sila ang inyong magiging mga hukom.
Pagkatapos nilang makapag-almusal, sinabi ni Jesus kay Simon Pedro, “Simon, anak ni Juan, minamahal mo ba ako nang higit kaysa mga ito?” Sinabi niya sa kanya, “Opo, Panginoon, nalalaman mo na minamahal kita.” Sinabi ni Jesus sa kanya, “Pakainin mo ang aking mga kordero.”
Sila'y naglakbay mula sa Sucot at nagkampo sa Etam na nasa gilid ng ilang.
Nang makita ni Aaron at ng lahat ng mga anak ni Israel si Moises, ang balat ng kanyang mukha ay nagliliwanag at sila'y natakot na lumapit sa kanya.
Kaya, alang-alang kay Cristo, ako'y nasisiyahan sa mga kahinaan, paglait, kahirapan, pag-uusig, at mga sakuna, sapagkat kapag ako'y mahina, ako nga'y malakas.
Tipunin mo ang matatanda sa iyong mga lipi at ang inyong mga pinuno upang masabi ko ang mga salitang ito sa kanilang pandinig, at tawagin ang langit at ang lupa upang sumaksi laban sa kanila.
Nang bigla silang tumingin sa paligid, wala silang nakitang sinumang kasama nila maliban kay Jesus lamang.
Nang lumulubog na ang araw, dinala ng lahat sa kanya ang kanilang mga maysakit na sari-sari ang karamdaman at ipinatong niya ang kanyang mga kamay sa bawat isa sa kanila at sila'y pinagaling.
Ang pari ni Zeus na ang templo ay nasa harap ng lunsod ay nagdala ng mga baka at mga putong na bulaklak sa mga pintuang-daan, at ibig maghandog kasama ng napakaraming tao.
Gawin ng Faraon na maglagay ng mga tagapamahala sa lupain, at kunin ang ikalimang bahagi ng bunga ng lupain ng Ehipto sa loob ng pitong taong kasaganaan.
(Sapagkat sinasabi ng mga Saduceo na walang muling pagkabuhay, o anghel, o espiritu; ngunit pinaniniwalaan ng mga Fariseo ang lahat ng ito.)
Lahat ng mga lunsod na inyong ibibigay sa mga Levita ay apatnapu't walong lunsod; kasama ang kanilang mga pastulan.
At pinatotohanan ng mga apostol na may dakilang kapangyarihan ang pagkabuhay ng Panginoong Jesus at sumakanilang lahat ang dakilang biyaya.
Siya ay sumigaw nang may malakas na tinig, na gaya ng leon na umuungal; at pagkasigaw niya, ang pitong kulog ay umugong.
ni Maat, ni Matatias, ni Semein, ni Josec, ni Joda,
Tutuparin ninyo ang aking mga tuntunin, at isasagawa ang mga iyon, ako ang Panginoon na nagpapabanal sa inyo.
Kaya sinasabi ko sa inyo, ‘Kukunin sa inyo ang kaharian ng Diyos at ibibigay sa isang bansang nagbibigay ng bunga nito.’ [
At sinabi ni Lea, “Binigyan ako ng Diyos ng isang mabuting kaloob. Ngayo'y pararangalan ako ng aking asawa, sapagkat nagkaanak ako sa kanya ng anim na lalaki.” At tinawag niya ang kanyang pangalan na Zebulon.
At may bumangong isang bagong hari sa Ehipto na hindi kilala si Jose.
Nang malapit na sila sa Jerusalem, sa may Betfage at Betania, malapit sa bundok ng mga Olibo, sinugo ni Jesus ang dalawa sa kanyang mga alagad,
O paano mong nasasabi sa iyong kapatid, ‘Hayaan mong alisin ko ang puwing sa iyong mata,’ samantalang mayroong troso sa iyong sariling mata?
Sa dakong pinagpapatayan nila ng handog na sinusunog ay doon papatayin ang handog para sa budhing maysala at ang dugo niyon ay iwiwisik niya sa palibot ng dambana.
“Alam ko kung saan ka naninirahan, sa kinaroroonan ng trono ni Satanas. Ngunit iniingatan mong mabuti ang aking pangalan, at hindi mo ipinagkaila ang pananampalataya mo sa akin, kahit nang mga araw ni Antipas na aking tapat na saksi, na pinatay sa gitna ninyo, kung saan nakatira si Satanas.
Subalit itinanggi niya ito at sinabi, “Babae, hindi ko siya nakikilala.”
at sinabi sa kanya, “Ikaw ba iyong darating o maghihintay kami ng iba?”
“Subalit kapag tiningnan ng pari, at nakitang nangitim ang dakong may sakit pagkatapos na malabhan, ito ay hahapakin mula sa kasuotan, o mula sa paayon, o mula sa pahalang.
At ang bunga ng katuwiran ay itinatanim sa kapayapaan ng mga gumagawa ng kapayapaan.
At walang taong naglalagay ng bagong alak sa mga lumang sisidlang balat. Kung gayon, papuputukin ng bagong alak ang mga balat, at matatapon, at masisira ang mga balat.
Sumagot si Simon Pedro at sinabi, “Ikaw ang Cristo, ang Anak ng Diyos na buháy.”
Ngunit sumagot ang kanyang panginoon at sinabi sa kanya, ‘Ikaw na masama at tamad na alipin! Alam mo palang ako'y gumagapas sa hindi ko hinasikan, at nagtitipon sa hindi ko kinalatan ng binhi.
Nang mabalitaan ni Balak na si Balaam ay dumarating, lumabas siya upang salubungin siya sa bayan ng Moab, na nasa hangganan ng Arnon, na siyang dulong bahagi ng hangganan.
Dumating sila sa Bethsaida. At dinala nila sa kanya ang isang lalaking bulag at ipinakiusap sa kanyang hipuin siya.
Sa ami'y ipinagbilin niya na mangaral sa mga tao at sumaksi na siya ang itinalaga ng Diyos na maging hukom ng mga buháy at ng mga patay.
Nabuhay si Eber ng tatlumpu't apat na taon, at naging anak si Peleg.
Sapagkat maliwanag na ang ating Panginoon ay nagmula sa Juda at tungkol sa liping iyon ay walang sinabing anuman si Moises tungkol sa mga pari.
Sapagkat sinasabi ni David tungkol sa kanya, ‘Nakita ko ang Panginoon na laging kasama ko, sapagkat siya'y nasa aking kanang kamay, upang huwag akong matinag;
Yamang marami ang nagmamalaki sang-ayon sa pamantayan ng tao, ako ma'y magmamalaki.
na iniutos ng Panginoon kay Moises sa bundok ng Sinai, nang araw na iniutos sa mga anak ni Israel na kanilang dalhin ang kanilang mga handog sa Panginoon sa ilang ng Sinai.
“Kapag ang buhok ng sinuman ay nalalagas mula sa kanyang ulo, siya ay kalbo, gayunma'y malinis.
At narinig ko ang isang tinig mula sa langit na nagsasabi, “Isulat mo ito: Mapapalad ang mga patay na namamatay sa Panginoon mula ngayon.” “Oo,” sinasabi ng Espiritu, “sila'y magpapahinga sa kanilang mga gawa, sapagkat ang kanilang mga gawa ay sumusunod sa kanila.”
Si Pedro ay nanatili sa loob ng maraming araw sa Joppa, na kasama ni Simon na isang tagapagluto ng balat.
Sumagot si Jesus, “Hindi ba ninyo nabasa ang ginawa ni David, nang siya at ang mga kasamahan niya ay nagutom?
Siya'y humilig sa leeg ng kanyang kapatid na si Benjamin, at umiyak; at si Benjamin ay umiyak sa kanyang leeg.
Ngunit ang mga iba'y nanlilibak na nagsabi, “Sila'y lasing sa bagong alak.”
Hindi ang pumapasok sa bibig ang nagpaparumi sa tao, kundi ang lumalabas sa bibig ang nagpaparumi.”
At iginawa ng Panginoong Diyos si Adan at ang kanyang asawa ng mga kasuotang balat at sila'y dinamitan.
Sinabi niya, “Itong pitong babaing kordero ay iyong kukunin sa akin upang ikaw ay maging saksi ko na hinukay ko ang balong ito.”
at magkaroon ng kapangyarihang magpalayas ng mga demonyo:
Igawa ninyo ng mga lunsod ang inyong mga bata, at ng mga kulungan ang inyong mga tupa; at gawin ninyo ang inyong sinabi.”
Kukuha siya mula sa dambana na nasa harapan ng Panginoon ng isang suuban na punô ng mga baga, at ng dalawang dakot ng masarap na dinikdik na insenso at kanyang dadalhin sa loob ng tabing.
Dinala rin ito ng ating mga ninuno na kasama ni Josue nang kanilang sakupin ang mga bansa na pinalayas ng Diyos sa harapan ng ating mga ninuno. Ito ay nanatili roon hanggang sa mga araw ni David,
Nang makita siya ni Pedro ay sinabi niya kay Jesus, “Panginoon, at paano naman ang taong ito?”
Sapagkat ang mga bansang ito na iyong aagawan ay nakikinig sa mga manggagaway at mga manghuhula; ngunit tungkol sa iyo, hindi ka pinahintulutan ng Panginoon mong Diyos na gawin mo ang gayon.
Ngunit sinabi niya, “Pumarito ang iyong kapatid sa pamamagitan ng pandaraya, at kinuha ang basbas sa iyo.”
Akin siyang iniraratay sa higaan at ang mga nakikiapid sa kanya ay ihahagis ko sa malaking kapighatian, maliban na kung sila'y magsisi sa kanyang mga gawa.
at sinabi sa kanila, “Nakikita ko na ang pagturing sa akin ng inyong ama ay hindi na gaya nang dati; subalit ang Diyos ng aking ama ay kasama ko.
Kinabukasan, pagkatapos ng araw ng Paghahanda, ang mga punong pari at ang mga Fariseo ay nagpulong sa harapan ni Pilato,
Siya'y naninirahan sa mga libingan at wala nang makapigil sa kanya kahit na may tanikala.
Umuwi nga siya at nadatnan ang anak na nakahiga sa higaan at wala na ang demonyo.
Ngayon pa lamang ay nakalagay na ang palakol sa ugat ng mga punungkahoy. Ang bawat punungkahoy na hindi mabuti ang bunga ay pinuputol at inihahagis sa apoy.
Ang nalabi sa handog ay kakainin ni Aaron at ng kanyang mga anak. Ito ay kakainin na walang pampaalsa sa dakong banal; kakainin nila ito sa bulwagan ng toldang tipanan.
Huwag nga kayong matakot; kayo ay higit na mahalaga kaysa maraming maya.
“Bumangon ka at dalhin mo ang sanggol at ang kanyang ina, at pumunta kayo sa lupain ng Israel, sapagkat patay na ang mga naghahangad sa buhay ng sanggol.”
Ang nalabing langis na nasa kamay ng pari ay ilalagay niya sa ulo ng taong lilinisin, at ang pari ay gagawa ng pagtubos para sa kanya sa harapan ng Panginoon .
At sinabi ni Maria, “Narito ako na alipin ng Panginoon; mangyari sa akin ang ayon sa iyong salita.” Pagkatapos, iniwan siya ng anghel.
Pagsapit ng gabi, pagkalubog ng araw, kanilang dinala sa kanya ang lahat ng mga maysakit at ang mga inaalihan ng mga demonyo.
Kanyang pinili ang pinakamabuti sa lupain para sa kanya, sapagkat doon nakatago ang bahagi ng isang pinuno, at siya'y dumating sa mga pinuno ng bayan, kanyang isinagawa ang katuwiran ng Panginoon , at ang kanyang mga batas sa Israel.”
Samantalang iniisip ni Pedro ang tungkol sa pangitain, sinabi sa kanya ng Espiritu, “Tingnan mo, may tatlong taong naghahanap sa iyo.
Sumagot si Jesus, “Ang pangunahin ay, ‘Pakinggan mo Israel: Ang Panginoon nating Diyos, ang Panginoon ay iisa.
Subalit ano ang sinasabi sa kanya ng kasagutan ng Diyos? “Nagtira ako para sa akin ng pitong libong lalaki na hindi lumuhod kay Baal.”
Dahil sa habag ay hinipo ni Jesus ang kanilang mga mata. Kaagad, nakakita silang muli at sila'y sumunod sa kanya.
Kanyang pinasakay siya sa matataas na dako ng lupa, at siya'y kumain ng bunga ng bukirin, at kanyang pinainom ng pulot na mula sa bato, at ng langis na mula sa batong kiskisan.
Si Moises noon ay walumpung taong gulang at si Aaron ay walumpu't tatlong taong gulang nang sila'y makipag-usap kay Faraon.
Ang isandaang talentong pilak ay ginamit sa pagbubuo ng mga patungan ng santuwaryo, at ng mga patungan ng mga haligi ng tabing; sandaang patungan sa sandaang talento, isang talento sa bawat patungan.
Ngunit hindi magkakaroon ng dukha sa inyo sapagkat pagpapalain ka ng Panginoon sa lupain na ibinibigay sa iyo ng Panginoon mong Diyos na pinakamana upang iyong angkinin,
At hindi na roon magkakaroon pa ng isinumpa. Ngunit ang trono ng Diyos at ng Kordero ay matatagpuan doon, at siya'y paglilingkuran ng kanyang mga alipin;
at ng tinapay na walang pampaalsa, mga bibingkang walang pampaalsa na hinaluan ng langis, at maninipis na tinapay na walang pampaalsa na pinahiran ng langis. Gagawin mo ang mga ito sa piling harinang trigo.
“Magdiriwang ka sa buwan ng Abib, at ipangingilin ang paskuwa sa Panginoon mong Diyos; sapagkat sa buwan ng Abib ay inilabas ka ng Panginoon mong Diyos sa Ehipto sa gabi.
Tinawag niya ang maraming tao pati ang kanyang mga alagad, at sa kanila'y sinabi, “Kung ang sinuman ay nagnanais sumunod sa akin, siya ay tumanggi sa kanyang sarili, pasanin ang kanyang krus at sumunod sa akin.
Kaya't ngayon, hinihiling ko na ipahintulot mo na ang iyong lingkod ang maiwan bilang isang alipin sa aking panginoon sa halip na ang bata at iyong ipahintulot na ang bata ay umahong kasama ng kanyang mga kapatid.
Hindi ba ito ang kopang iniinuman ng aking panginoon, at sa pamamagitan nito siya ay nanghuhula? Kayo'y gumawa ng masama sa paggawa ng ganyan.’”
Ngunit sinabi sa kanila ng hari ng Ehipto, “Moises at Aaron, bakit ninyo inilalayo ang bayan sa kanilang mga gawain? Pumaroon kayo sa inyong mga gawain.”
“Bakit tinatawag ninyo akong, ‘Panginoon, Panginoon,’ ngunit hindi ninyo ginagawa ang sinasabi ko?
Ipinatong ni Jesus ang kanyang mga kamay sa kanya at kaagad siyang naunat at niluwalhati niya ang Diyos.
Pagkaraan ng tatlong araw, tinipon niya ang mga pinuno ng mga Judio at nang sila'y matipon na, ay sinabi niya sa kanila, “Mga kapatid, bagaman wala akong ginawang anuman laban sa bayan, o sa mga kaugalian ng ating mga ninuno, ay ibinigay akong bilanggo buhat sa Jerusalem sa mga kamay ng mga taga-Roma.
Nang siya'y mag-isa na, ang mga nasa palibot niya kasama ang labindalawa ay nagtanong sa kanya tungkol sa mga talinghaga.
sapagkat mahal niya ang ating bansa at nagtayo siya ng sinagoga para sa atin.”
Nalalaman ninyo ang salita na kanyang ipinadala sa mga anak ni Israel, na ipinangangaral ang magandang balita ng kapayapaan sa pamamagitan ni Jesu-Cristo—siya'y Panginoon ng lahat,
Ngunit hindi kayo binigyan ng Panginoon ng isipang makakaunawa, at ng mga matang makakakita, at ng mga pandinig na makakarinig, hanggang sa araw na ito.
Si Esau ay nag-asawa mula sa mga anak ng Canaan; kay Ada na anak ni Elon na Heteo, kay Aholibama, anak ni Ana na anak ni Zibeon na Heveo;
Kaya't higit akong masigasig na suguin siya, upang, pagkakitang muli ninyo sa kanya, kayo'y magalak at mabawasan ang aking kalungkutan.
Pagkatapos ay iningatan niya ang kasuotan ni Jose hanggang sa pagdating ng kanyang amo sa kanyang bahay.
At ito ang haba ng buhay ni Abraham, isandaan at pitumpu't limang taon.
Pagkatapos, si Balaam ay tumindig at bumalik sa kanyang lugar; at si Balak ay umalis na rin.
At si Bernabe ay nagtungo sa Tarso upang hanapin si Saulo.
Subalit dahil batid niya ang kanilang iniisip ay sinabi niya sa kanila, “Ang bawat kahariang nahahati laban sa kanyang sarili ay nawawasak at ang bahay na laban sa sarili ay nagigiba.
Kaya't kanilang tinipon ang mga ito at nakapuno ng labindalawang kaing ng mga pinagputul-putol na limang tinapay na sebada na lumabis sa mga kumain.
Ngunit nang dumating ang pagdiriwang ng kaarawan ni Herodes, sumayaw sa gitna nila ang anak na babae ni Herodias, at ito ay ikinatuwa ni Herodes.
Pagkatapos ay sinabi niya sa alagad, “Narito ang iyong ina!” At mula noon ay dinala siya ng alagad sa kanyang sariling tahanan.
Ngunit iniisip kong kailangan pa ring isugo sa inyo si Epafrodito, na aking kapatid, kamanggagawa, at kapwa kawal, ang inyong sugo at lingkod para sa aking pangangailangan.
Hindi nila ako natagpuang nakikipagtalo sa kanino o kaya'y nanggugulo sa maraming tao sa templo man o sa mga sinagoga, ni sa lunsod,
Kaya't tumakbo siya at pumunta kay Simon Pedro at sa alagad na minamahal ni Jesus, at sa kanila'y sinabi, “Kinuha nila sa libingan ang Panginoon, at hindi namin alam kung saan nila siya inilagay.”
Nang sila'y dumating sa tapat ng Misia, ay pinagsikapan nilang makapasok sa Bitinia ngunit hindi sila pinahintulutan ng Espiritu ni Jesus.
subalit sa mga huling araw na ito ay nagsalita siya sa atin sa pamamagitan ng Anak, na kanyang itinalagang tagapagmana ng lahat ng mga bagay, na sa pamamagitan din niya'y ginawa ang mga sanlibutan.
kung gayo'y susuriin siya ng pari, at kung makitang ang ketong ay kumalat na sa kanyang buong katawan, kanyang ipahahayag na siya'y malinis na sa sakit. Yamang ito'y pumuting lahat, siya'y malinis.
Pagkatapos ay sinabi ni Jesus sa kanila, “Kayong lahat ay tatalikod dahil sa akin sa gabing ito; sapagkat nasusulat, ‘Sasaktan ko ang pastol, at ang mga tupa ng kawan ay magkakawatak-watak.’
Sinabi ng Panginoon kay Moises, “Ikaw ay malapit ng mamatay na kasama ng iyong mga ninuno. Ang bayang ito'y babangon at makikiapid sa mga di-kilalang diyos sa lupain na kanilang paroroonan upang makasama nila, at ako'y tatalikuran nila at sisirain ang aking tipan na aking ginawa sa kanila.
At sumagot si Jacob kay Laban, “Sapagkat ako'y natakot; iniisip ko na baka kunin mo nang sapilitan sa akin ang iyong mga anak.
Gayundin naman ang mga diakono ay dapat na maging kagalang-galang, hindi dalawang dila, hindi nalululong sa maraming alak, hindi mga sakim sa masamang pagkakakitaan,
Ang nagsasalita nang mula sa kanyang sarili ay humahanap ng kanyang sariling kaluwalhatian; subalit ang humahanap ng kaluwalhatian ng nagsugo sa kanya ay siyang totoo, at sa kanya'y walang kasinungalingan.
na dumating sa inyo. Gayundin naman kung paanong ito ay namumunga at lumalago sa buong sanlibutan, ay gayundin naman sa inyo, mula nang araw na inyong marinig at maunawaan ang biyaya ng Diyos sa katotohanan.
sa lugar ng dambana na kanyang ginawa roon nang una; at doon ay tinawag ni Abram ang pangalan ng Panginoon .
Pagdating ni Maria sa kinaroroonan ni Jesus, at nang makita siya ni Maria, lumuhod ito sa kanyang paanan, na sinasabi sa kanya, “Panginoon, kung ikaw sana'y narito, hindi sana namatay ang aking kapatid.”
Kaya't umupo sila nang pangkat-pangkat, nang tig-iisandaan at tiglilimampu.
Kayo na ang pumunta sa pista. Ako'y hindi pupunta sa pistang ito, sapagkat hindi pa dumating ang aking oras.”
Iniunat ni Jesus ang kanyang kamay, at hinawakan niya ito na nagsasabi, “Ibig ko. Maging malinis ka.” At nalinis kaagad ang kanyang ketong.
Kapag ang babae ay nanganganak, siya ay nahihirapan sapagkat dumating na ang kanyang oras. Ngunit pagkapanganak niya sa sanggol ay hindi na niya naaalala ang hirap dahil sa kagalakan sa pagkapanganak sa isang tao sa sanlibutan.
Ngunit mayroon ka pang ilan sa Sardis na hindi dinungisan ang kanilang mga damit; at sila'y kasama kong lalakad na nakaputi, sapagkat sila'y karapat-dapat.
Nakipagtalo ang mga pastol ng Gerar sa mga pastol ni Isaac, na sinasabi, “Ang tubig ay amin.” Kanyang tinawag ang pangalan ng balon na Esec sapagkat sila'y nakipagtalo sa kanya.
Iniutos sa akin ng Espiritu na ako'y sumama sa kanila at huwag mag-atubili. At sinamahan din ako nitong anim na kapatid; at pumasok kami sa bahay ng lalaki.
Sa kanyang kanang kamay ay may pitong bituin at mula sa kanyang bibig ay lumabas ang isang matalas na tabak na may dalawang talim, at ang kanyang mukha ay gaya ng araw na matinding sumisikat.
Ito ay nangangahulugang nauunawaan na ang kautusan ay hindi ginawa para sa taong matuwid, kundi para sa mga walang kinikilalang batas at mapaghimagsik, para sa masasama at mga makasalanan, para sa mga hindi banal at lapastangan, para sa mga pumapatay sa ama at sa ina, para sa mga mamamatay-tao,
Sapagkat ang mga bagay na ito ay nangyari upang matupad ang kasulatan, “Kahit isa mang buto niya'y hindi mababali.”
Sapagkat kami ay hindi sumunod sa mga kathang-isip na ginawang may katusuhan nang aming ipaalam sa inyo ang kapangyarihan at pagdating ng ating Panginoong Jesu-Cristo, kundi kami ay mga saksing nakakita ng kanyang kadakilaan.
Sapagkat lumulusong ang isang anghel ng Panginoon sa mga tanging panahon sa tipunan ng tubig at kinakalawkaw ang tubig; at ang unang manaog sa tipunan ng tubig, pagkatapos na makalawkaw ang tubig ay gumagaling sa anumang sakit na dinaramdam.]
Tumindig si Saulo mula sa lupa; at pagmulat ng kanyang mga mata, ay wala siyang makita; kaya't kanilang inakay siya sa kamay at ipinasok siya sa Damasco.
(ito ang mga anak ni Raquel na ipinanganak kay Jacob: sa kabuuan ay labing-apat na katao).
Ito ang mga pinili mula sa kapulungan, na mga pinuno sa mga lipi ng kani-kanilang mga ninuno. Sila ang mga puno ng mga angkan ng Israel.
Habang sila'y nagtataka tungkol dito, biglang may dalawang lalaki na nakasisilaw ang mga damit ang tumayo sa tabi nila.
Kaya't mamunga kayo ng karapat-dapat sa pagsisisi at huwag ninyong sabihin sa inyong sarili, ‘Si Abraham ang aming ama.’ Sapagkat sinasabi ko sa inyo na magagawa ng Diyos na magbangon mula sa mga batong ito ng magiging anak ni Abraham.
ang sabi niya, na nakarinig ng mga salita ng Diyos, at nakaalam ng karunungan ng Kataas-taasan, na siyang nakakita ng pangitain ng Makapangyarihan sa lahat, na nakalugmok ngunit bukas ang kanyang mga mata.
Sa halip, kapag inaanyayahan ka, pumunta ka at umupo sa pinakamababang lugar upang kung dumating ang nag-anyaya sa iyo, sasabihin niya sa iyo, ‘Kaibigan, pumunta ka sa mas mataas.’ Kung gayo'y magkakaroon ka ng karangalan sa harap ng lahat ng mga kasalo mong nakaupo sa hapag.
Ang biyaya'y sumainyo nawang lahat. Amen.
Ngunit kung mula roon ay iyong hahanapin ang Panginoon mong Diyos, siya ay iyong matatagpuan kung iyong hahanapin ng buong puso at buong kaluluwa.
“Umakyat ka sa bundok na ito ng Abarim, sa bundok ng Nebo na nasa lupain ng Moab, na nasa tapat ng Jerico. Tanawin mo ang lupain ng Canaan, na aking ibinibigay sa mga anak ni Israel bilang pag-aari.
Ang lahat ng sa akin ay iyo, at ang sa iyo ay akin, at ako'y naluluwalhati sa kanila.
At biglang sumama sa anghel ang isang malaking hukbo ng langit na nagpupuri sa Diyos at nagsasabi,
Ngayong nilinis na ninyo ang inyong mga kaluluwa sa pamamagitan ng inyong pagsunod sa katotohanan, kaya't kayo'y may tunay na pag-ibig sa isa't isa, mag-ibigan kayo sa isa't isa nang buong alab mula sa dalisay na puso.
Ang lahat na mga bagay tungkol sa akin ay ipababatid sa inyo ni Tiquico, na minamahal na kapatid at tapat na ministro, at kapwa alipin sa Panginoon.
Tumanaw si Jacob at nakita niyang si Esau ay dumarating na may kasamang apatnaraang katao. Kaya't kanyang pinaghiwalay ang mga bata kina Lea at Raquel, at sa dalawang aliping babae.
Nagpatuloy si Abram ng kanyang paglalakbay mula sa Negeb hanggang sa Bethel, hanggang sa dakong kinaroroonan ng kanyang tolda sa pagitan ng Bethel at ng Ai;
At lahat ng mga tulos ng tabernakulo, at ng bulwagan sa palibot ay tanso.
Nang ako'y umakyat sa bundok upang tanggapin ang mga tapyas na bato, samakatuwid ay ang mga tapyas ng tipan na ginawa ng Panginoon sa inyo, nanatili ako sa bundok ng apatnapung araw at apatnapung gabi. Hindi ako kumain ng tinapay ni uminom ng tubig.
Nang magkagayo'y inawit ni Moises at ng mga Israelita ang awit na ito sa Panginoon , na sinasabi, “Ako'y aawit sa Panginoon , sapagkat siya'y maluwalhating nagtagumpay; kanyang inihagis sa dagat ang kabayo at ang doo'y nakasakay.
At sinabi niya, “Sino ang magsasabi kay Abraham na si Sara ay magpapasuso ng mga anak? Ngunit ako'y nagkaanak pa sa kanya ng isang lalaki sa kanyang katandaan.”
Binigyan ng Panginoon ang bayan ng biyaya sa paningin ng mga Ehipcio. Bukod dito, ang lalaking si Moises ay naging dakila sa lupain ng Ehipto, sa paningin ng mga lingkod ng Faraon, at sa paningin ng mga tao.
Sa pamamagitan niya ay nanampalataya kayo sa Diyos, na bumuhay sa kanya mula sa mga patay at sa kanya'y nagbigay ng kaluwalhatian, kaya't ang inyong pananampalataya at pag-asa ay nakatuon sa Diyos.
At nang mga araw na ito, tumindig si Pedro sa gitna ng mga kapatid at nagsabi (at nagkakatipon ang maraming tao, na may isandaan at dalawampu),
Ngunit sinabi ni Jesus, “Hayaan ninyo ang maliliit na bata, at huwag ninyo silang pagbawalang lumapit sa akin, sapagkat sa mga tulad nila nauukol ang kaharian ng langit.”
Nang oras na iyon ay dumating ang kanyang mga alagad. Sila'y nagtaka na siya'y nakikipag-usap sa isang babae, subalit walang nagsabi, “Ano ang gusto mo?” o, “Bakit ka nakikipag-usap sa kanya?”
Huwag kayong gagawa ng mga diyos na pilak na iaagapay sa akin ni huwag kayong gagawa para sa inyo ng mga diyos na ginto.
Sapagkat tunay na matuwid sa Diyos na gantihan ng kapighatian ang mga nagpapahirap sa inyo,
at sinabi niya sa akin, “Uminom ka, at iiigib ko rin ang iyong mga kamelyo,” ay siyang maging babaing pinili ng Panginoon sa anak ng aking panginoon.’
Ang Panginoon ay nagsalita kay Moises sa ilang ng Sinai sa toldang tipanan, nang unang araw ng ikalawang buwan, sa ikalawang taon pagkalabas nila sa lupain ng Ehipto, na sinasabi:
sapagkat ang Espiritu Santo ang magtuturo sa inyo sa oras ding iyon kung ano ang dapat ninyong sabihin.”
Tungkol sa iyong mga aliping lalaki at aliping babae na maaaring mayroon ka mula sa mga bansang nasa palibot ninyo, sila'y bibilhin ninyo bilang mga aliping lalaki at aliping babae.
Pinaalis na niya ang maraming mga tao. Sumakay siya sa isang bangka at nagtungo sa nasasakupan ng Magdala.
“Ganito mo ibubukod ang mga Levita mula sa mga anak ni Israel at ang mga Levita ay magiging akin.
Ihaharap mo ang mga Levita sa harap ng toldang tipanan at titipunin mo ang buong sambayanan ng mga anak ni Israel.
At kapag tinipon ko ang mga ulap sa ibabaw ng lupa, ang bahaghari ay makikita sa ulap.
Yamang maraming panahon na ang nawala at ang paglalayag ay mapanganib na, sapagkat maging ang pag-aayuno ay nakalampas na, ay pinayuhan sila ni Pablo,
at nilait nila ang Diyos ng langit dahil sa kanilang mga hirap at sa kanilang mga sugat; at hindi sila nagsisi sa kanilang mga gawa.
Nakilala ni Jose ang kanyang mga kapatid, subalit siya'y hindi nila nakilala.
Mula roo'y lumigid kami at nakarating sa Regio; at pagkaraan ng isang araw ay humihip ang hanging habagat, at nang ikalawang araw ay nakarating kami sa Puteoli.
Isa sa mga Fariseo ay humiling kay Jesus na kumaing kasalo niya, at pagpasok niya sa bahay ng Fariseo siya'y naupo sa hapag.
Sinabi ni Moises kay Josue, “Pumili ka para sa atin ng mga lalaki, lumabas ka at lumaban kay Amalek. Bukas ay tatayo ako sa taluktok ng burol na hawak ang tungkod ng Diyos sa aking kamay.”
Kaya't pinatulog nang mahimbing ng Panginoong Diyos ang lalaki, at habang siya'y natutulog, kinuha niya ang isa sa kanyang mga tadyang at pinaghilom ang laman sa lugar na iyon;
Gaya ng pagkakilala sa akin ng Ama, at ng pagkakilala ko sa Ama, at ibinibigay ko ang aking buhay para sa mga tupa.
Sinabi ng paring si Eleazar sa mga mandirigma ng hukbo na pumunta sa pakikipaglaban, “Ito ang tuntunin ng kautusan na iniutos ng Panginoon kay Moises:
At binigkas niya ang kanyang talinghaga, na sinasabi: “Ang sabi ni Balaam na anak ni Beor, ang sabi ng taong bukas ang mga mata,
“At kapag ang isang tao ay nagbili ng kanyang tirahang bahay sa isang napapaderang lunsod, maaari niya itong tubusin sa loob ng isang taon pagkatapos na ito'y maipagbili sapagkat sa buong taon ay magkakaroon siya ng karapatang tumubos.
Nang siya'y makalabas na, ay sinabi ni Jesus, “Ngayon ay niluwalhati ang Anak ng Tao, at ang Diyos ay niluwalhati sa kanya;
Si Pedro ay sumunod sa kanya sa malayo, hanggang sa loob ng patyo ng pinakapunong pari; at nakiumpok siya sa mga kawal, at nagpainit ng sarili sa apoy.
At dadalhin mo sa Panginoon ang pagkaing handog na mula sa mga sangkap na ito, at dadalhin ito ng pari sa dambana.
Ito ang kasaysayan tungkol sa langit at lupa, sa araw na likhain ng Panginoong Diyos ang langit at lupa.
Sa halos apatnapung taon ay kanyang pinagtiyagaan sila sa ilang.
at kanyang ipahahayag ang kanyang kasalanang nagawa at kanyang pagbabayarang lubos ang kanyang sala, at dadagdagan pa niya ng ikalimang bahagi at ibibigay sa ginawan ng pagkakasala.
kung tayo'y hindi tapat, siya'y nananatiling tapat; sapagkat hindi niya maipagkakaila ang kanyang sarili.
Habang sila'y kumakain ay dumampot si Jesus ng tinapay, binasbasan niya ito at pinagputul-putol, at ibinigay sa mga alagad, at sinabi, “Kumuha kayo, kainin ninyo; ito ang aking katawan.”
Kaya't ang kanyang pananampalataya ay ibinilang na katuwiran sa kanya.
“Ang babae ay huwag mananamit ng nauukol sa lalaki, ni ang lalaki ay magsusuot ng damit ng babae; sapagkat sinumang gumagawa ng mga bagay na ito ay karumaldumal sa Panginoon mong Diyos.
Sa aking unang pagsasanggalang ay walang sinumang kumampi sa akin, bagkus pinabayaan ako ng lahat. Huwag nawang singilin sa kanila ito.
Nang makapagtalaga na sila ng matatanda para sa kanila sa bawat iglesya, matapos manalangin na may pag-aayuno, ay kanilang ipinagtagubilin sila sa Panginoon na kanilang sinampalatayanan.
Siya'y papatayin nila ngunit siya'y muling mabubuhay sa ikatlong araw.” At sila'y labis na nalungkot.
Kaya't sinumang sumuway sa isa sa pinakamaliit sa mga utos na ito, at magturo nang gayon sa mga tao ay tatawaging pinakamaliit sa kaharian ng langit; ngunit ang sinumang tumupad at magturo ng mga ito ay tatawaging dakila sa kaharian ng langit.
Ang mga anak ni Aser ayon sa kanilang mga angkan: kay Imna, ang angkan ng mga Imnaita; kay Isui, ang angkan ng mga Isuita; kay Beriah, ang angkan ng mga Beriahita.
Minsan, nagluto si Jacob ng nilaga. Dumating si Esau mula sa parang at siya'y gutom na gutom.
Sapagkat kung ang unang tipang iyon ay walang kapintasan, hindi na sana kailangang humanap pa ng pangalawa.
Sapagkat hindi nila kayo sinalubong sa daan na may tinapay at tubig nang kayo'y dumating mula sa Ehipto; at sapagkat inupahan nila laban sa iyo si Balaam na anak ni Beor mula sa Petor ng Mesopotamia upang sumpain ka.
Nang makita ng puno ng mga panadero na ang kahulugan ay mabuti ay sinabi niya kay Jose, “Ako'y nanaginip din, at may tatlong kaing ng maputing tinapay ang nasa ibabaw ng aking ulo.
Sapagkat ang Hesbon ay siyang bayan ni Sihon na hari ng mga Amoreo, na siyang nakipaglaban sa unang hari sa Moab, at sumakop ng buong lupain niyon sa kanyang kamay hanggang sa Arnon.
Kinabukasan, nang mabalitaan ng maraming taong dumalo sa pista na si Jesus ay darating sa Jerusalem,
Sa pananampalataya'y itinatag niya ang paskuwa at ang pagwiwisik ng dugo, upang huwag silang galawin ng Mamumuksa ng mga panganay.
Kaya't ang taong-bayan ay nakipagtalo kay Moises at nagsabi, “Bigyan mo kami ng tubig na maiinom.” At sinabi ni Moises sa kanila, “Bakit kayo nakikipagtalo sa akin? Bakit ninyo sinusubok ang Panginoon ?”
At naroon ang isang babae na may espiritu ng karamdaman sa loob ng labingwalong taon. Siya ay baluktot at hindi niya kayang tumayo ng talagang matuwid.
upang kanilang hanapin ang Diyos, baka sakaling siya'y mahagilap nila at siya'y matagpuan, bagaman hindi siya malayo sa bawat isa sa atin.
Siya'y namatay para sa lahat, upang ang mga nabubuhay ay huwag nang mabuhay pa para sa kanilang sarili, kundi para sa kanya na alang-alang sa kanila ay namatay at muling nabuhay.
At sinabi niya, “Ang may taingang pandinig ay makinig.”
Wasakin ninyo ang lahat ng mga dako kung saan naglilingkod sa kanilang diyos ang mga bansang inyong aagawan, sa ibabaw ng matataas na bundok, at sa ibabaw ng mga burol, at sa lilim ng bawat luntiang punungkahoy.
Sapagkat lumabas ang masasamang espiritu sa maraming sinapian na nagsisisigaw nang malakas; at maraming lumpo at pilay ang pinagaling.
Nang sila'y makasagwan na ng may lima hanggang anim na kilometro ay kanilang nakita si Jesus na lumalakad sa ibabaw ng dagat at papalapit sa bangka. Sila'y natakot,
At ang nasa bubungan ay huwag nang bumaba, o pumasok upang maglabas ng anuman sa kanyang bahay.
At nilibot ni Jesus ang buong Galilea, na nagtuturo sa mga sinagoga nila, at ipinangangaral ang ebanghelyo ng kaharian, at nagpapagaling ng lahat ng sakit at ng lahat ng karamdaman na nasa mga tao.
Huwag mong kakainin iyon para sa ikabubuti mo, at ng iyong mga anak pagkamatay mo, kung iyong gagawin ang matuwid sa paningin ng Panginoon .
na ang mga Hentil ay mga kapwa tagapagmana, at mga bahagi ng iisang katawan, at mga kabahagi sa pangako kay Cristo Jesus sa pamamagitan ng ebanghelyo.
Lahat ng kalikuan ay kasalanan, at may kasalanang hindi tungo sa kamatayan.
Sapagkat ang iyong lingkod ang siyang naging panagot sa bata sa aking ama, na nagsasabi, ‘Kapag hindi ko siya dinala sa iyo, papasanin ko ang sisi ng aking ama magpakailanman.’
Subalit kasama ni Jose ang Panginoon at nagpakita sa kanya ng tapat na pag-ibig, at pinagkalooban siya ng biyaya sa paningin ng bantay sa bilangguan.
At naglabas ang alipin ng mga alahas na pilak at ginto, at mga damit, at ibinigay kay Rebecca. Nagbigay rin siya ng mahahalagang bagay sa kanyang kapatid na lalaki at sa kanyang ina.
At sinabi ng lalaki, “Sa wakas, ito'y buto ng aking mga buto at laman ng aking laman. Siya'y tatawaging Babae, sapagkat sa Lalaki siya kinuha.”
Sapagkat tayo'y kanyang pinakamahusay na gawa, na nilalang kay Cristo Jesus para sa mabubuting gawa, na inihanda ng Diyos nang una pa upang siya nating lakaran.
At ang pangalan ng anak na babae ni Aser ay Sera.
Para sa kalayaan ay pinalaya tayo ni Cristo; kaya't magpakatatag kayo at huwag pasakop na muli sa pamatok ng pagkaalipin.
Ngunit mag-ingat kayo; ipinagpauna ko nang sabihin sa inyo ang lahat ng bagay.
Ngunit kung ito'y sa pamamagitan ng biyaya, ito'y hindi na batay sa mga gawa; kung hindi, ang biyaya ay hindi biyaya.
Sapagkat ang lahat ng mga pangako ng Diyos sa kanya ay “Oo.” Kaya't sa pamamagitan niya ay aming sinasambit ang “Amen,” sa ikaluluwalhati ng Diyos.
Siya'y sinundan ng napakaraming tao, at ng mga babaing nagdadalamhati at nag-iiyakan para sa kanya.
Sa halip, may isang babae na ang munting anak na batang babae na may masamang espiritu, na nakabalita tungkol sa kanya ay agad na lumapit at nagpatirapa sa kanyang paanan.
“Pagkatapos ay isusulat ng pari ang mga sumpang ito sa isang aklat, at kanyang tatanggalin sa tubig ng kapaitan.
Ang lima sa kanila'y mga hangal at ang lima'y matatalino.
Nang panahong iyon ay mayroon silang isang bilanggo na kilala sa kasamaan, na tinatawag na Jesus Barabas.
Pagkasabi niya nito ay ipinakita niya sa kanila ang kanyang mga kamay at mga paa.]
Sinabi nila, “Ano ang ibig niyang sabihin na, ‘Sandali na lamang?’ Hindi natin alam kung ano ang sinasabi niya.”
Inyong sasambahin ang Panginoon ninyong Diyos, at aking pagpapalain ang inyong tinapay at ang inyong tubig, at aalisin ko ang sakit sa gitna ninyo.
Hinawakan niya ang kamay ng babae, at nawala ang kanyang lagnat. Bumangon siya at naglingkod kay Jesus.
At kung matapos na ang isang libong taon, si Satanas ay pakakawalan sa kanyang bilangguan,
Si Pablo, na apostol ni Cristo-Jesus sa pamamagitan ng kalooban ng Diyos, at si Timoteo na ating kapatid,
Kaya't si Abraham, nang makapaghintay na may pagtitiis, ay tumanggap ng pangako.
Ito'y isang taong nabilanggo dahil sa isang paghihimagsik na nangyari sa lunsod, at dahil sa pagpatay ng tao.
At kanyang sinabi, “Malayo nawa sa akin ang gumawa nito; ang taong kinatagpuan ng kopa ay siyang magiging aking alipin, at kayo ay umuwing may kapayapaan sa inyong ama.”
Ngunit aking natagpuang wala siyang ginawang anuman na marapat sa kamatayan; at yamang siya mismo ay dumudulog sa emperador, ipinasiya kong siya'y ipadala.
Kung iyong pahihirapan sila sa anumang paraan, at dumaing sa akin, tiyak na aking diringgin ang kanilang daing;
“Iyong sabihin ang ganito sa mga anak ni Israel: Sa ikalabinlimang araw ng ikapitong buwang ito ay pitong araw na Kapistahan ng mga Kubol sa Panginoon .
Si Jesus ay nagsimulang magsabi sa kanila, “Mag-ingat kayo, na baka mailigaw kayo ng sinuman.
Kung di mo siya magustuhan ay pababayaan mo siyang pumunta kung saan niya ibig. Ngunit huwag mo siyang ipagbibili para sa salapi, huwag mo siyang ituring na alipin, yamang ipinahiya mo siya.
na sinasabi, “Kung iyong diringgin ng buong tiyaga ang tinig ng Panginoon mong Diyos, at iyong gagawin ang matuwid sa kanyang mga mata, at iyong susundin ang kanyang mga utos, at iyong tutuparin ang lahat ng kanyang mga batas, wala akong ilalagay na karamdaman sa iyo, na gaya ng inilagay ko sa mga Ehipcio; sapagkat ako ang Panginoon na nagpapagaling sa iyo.”
Siya'y pumasok sa bahay ng Diyos, kinuha at kinain ang tinapay na handog, at binigyan pati ang kanyang mga kasamahan na hindi ipinahihintulot kainin maliban ng mga pari lamang?”
Ang labindalawang ito ay isinugo ni Jesus, at inutusan na sinasabi, “Huwag kayong pupunta sa pook ng mga Hentil, at huwag kayong papasok sa alinmang bayan ng mga Samaritano;
Sapagkat ang lahat ng nagkasala nang walang kautusan ay mapapahamak din nang walang kautusan; at ang lahat ng nagkasala sa ilalim ng kautusan ay sa kautusan hahatulan.
Magmadali kayo at pumunta kayo sa aking ama, at sabihin ninyo sa kanya, ‘Ganito ang sabi ng iyong anak na si Jose: Ginawa ako ng Diyos na panginoon sa buong Ehipto, pumarito ka sa akin, huwag kang magtagal.
At sinabi ni Abimelec, “Ano itong ginawa mo sa amin? Paano kung may sumiping sa iyong asawa, at ikaw sana ang naging dahilan upang kami ay magkasala?”
Kaya't magsisi ka. Kung hindi, madali akong darating sa iyo, at didigmain ko sila ng tabak ng aking bibig.
Gayunma'y hindi namatay ang mga anak ni Kora.
Subalit manatili ka sa mga bagay na iyong natutunan at matatag na pinaniwalaan, yamang nalalaman mo kung kanino ka natuto,
Tinatawag ninyo akong Guro at Panginoon at tama kayo, sapagkat ako nga.
Si Jesus ay sumigaw nang malakas at nalagutan ng hininga.
Ang mga anak ni Isacar: sina Tola, Pua, Job, at si Simron.
Sa ganitong paraan ninyo ihahandog araw-araw, sa loob ng pitong araw ang pagkain na handog na pinaraan sa apoy na mabangong samyo sa Panginoon . Ihahandog ito bukod pa sa palagiang handog na sinusunog at sa inuming handog.
“Gayunma'y hindi kayo umakyat, kundi naghimagsik kayo laban sa utos ng Panginoon ninyong Diyos,
Ang nabilang sa kanila, ayon sa bilang ng lahat ng mga lalaki, mula sa isang buwang gulang pataas, ay pitong libo at limang daan.
Lumabas si Hamor na ama ni Shekem upang makipag-usap kay Jacob,
Siya'y sinamba nila at bumalik sila sa Jerusalem na may malaking kagalakan.
At habang binabasbasan niya sila, kanyang iniwan sila [at dinala siya paitaas sa langit].
Ang napahasik naman sa mabuting lupa, ay iyong nakikinig ng salita at inuunawa ito, na siyang talagang namumunga. Ang isa ay isandaan, ang iba ay animnapu, at ang iba ay tatlumpu.”
na lubhang nayayamot sapagkat nagtuturo sila sa mga tao, at nagpapahayag na kay Jesus ay may muling pagkabuhay sa mga patay.
Subalit sila'y nagsigawan, “Ipako sa krus, ipako siya sa krus.”
Ito ang kautusang inilagay ni Moises sa harapan ng mga anak ni Israel.
pagkatapos ay idinagdag niya, “Narito, ako'y dumating upang gawin ang iyong kalooban.” Inalis niya ang una, upang maitatag ang ikalawa,
Doon ay nanatili siya ng tatlong buwan. Nang siya'y maglalakbay na patungong Siria, nagkaroon ng masamang balak ang mga Judio, kaya't ipinasiya niyang bumalik na dumaan sa Macedonia.
Si Jesus na nakakaalam ng lahat ng mga bagay na mangyayari sa kanya ay lumabas, at sa kanila'y sinabi, “Sino ang inyong hinahanap?”
Ngunit kung kanyang pawawalang-bisa ito pagkatapos na kanyang marinig, tataglayin nga niya ang kasamaan ng kanyang asawa.
Pagkatapos na magkaroon sina Pablo at Bernabe ng hindi maliit na pakikipagtalo at pakikipagsalungatan sa kanila, sina Pablo at Bernabe, at ang ilan sa iba pa ay inatasang pumunta sa Jerusalem, upang talakayin ang suliraning ito sa mga apostol at sa matatanda.
Ngunit kami ay maghahandang lumaban upang magpauna sa mga anak ni Israel hanggang sa aming madala sila sa kanilang lugar; at ang aming mga bata ay maninirahan sa mga bayang may pader dahil sa mga naninirahan sa lupain.
Nang sumunod na araw, lumapit siya sa kanila samantalang sila'y nag-aaway, at ibig sana niyang sila'y pagkasunduin, na sinasabi, ‘Mga ginoo, kayo'y magkapatid; bakit kayo nag-aaway?’
“Pagdating ninyo sa lupain at nakapagtanim na kayo ng sari-saring punungkahoy bilang pagkain, ay ituturing ninyo ang bunga niyon na ipinagbabawal; tatlong taon itong ipagbabawal para sa inyo; hindi ito dapat kainin.
Isinugo sila ni Moises upang lihim na siyasatin ang lupain ng Canaan at sinabi sa kanila, “Umakyat kayo sa Negeb at umakyat kayo sa mga kaburulan.
gagawin mo sa kanya ang gaya ng kanyang inisip gawin sa kanyang kapatid; sa gayo'y iyong aalisin ang kasamaan sa gitna mo;
Sapagkat kailangan ninyo ng pagtitiis, upang kapag inyong nagampanan ang kalooban ng Diyos ay tanggapin ninyo ang pangako.
Ang mga haligi ng mga iyon ay dalawampu, at ang mga patungan ay dalawampu, yari sa tanso; ang mga kawit ng mga haligi at ang mga kawit ay pilak.
Nang ikatlo ng hapon ay sumigaw si Jesus nang may malakas na tinig, “Eloi, Eloi, lama sabacthani?” na ang kahulugan ay, “Diyos ko, Diyos ko, bakit mo ako pinabayaan?”
Kaya't lumayo sila sa tolda nina Kora, Datan at Abiram. Sina Datan at Abiram ay lumabas at tumayo sa pintuan ng kanilang mga tolda kasama ng kanilang mga asawa, mga anak, at mga bata.
Kung kayo'y mananatili sa akin, at ang mga salita ko'y mananatili sa inyo, hingin ninyo ang anumang inyong nais, at ito'y gagawin para sa inyo.
Kaya't iniutos ni Abimelec sa buong bayan, “Ang gumalaw sa lalaking ito o sa kanyang asawa ay mamamatay.”
Marami sa mga gumagamit ng mga salamangka ay tinipon ang kanilang mga aklat at sinunog sa paningin ng madla; at kanilang binilang ang halaga niyon, at napag-alamang may limampung libong pirasong pilak.
Ngunit nang ito ay marinig ni Jesus ay sinabi niya, “Ang sakit na ito'y hindi tungo sa kamatayan, kundi para sa ikaluluwalhati ng Diyos, upang ang Anak ng Diyos ay luwalhatiin sa pamamagitan nito.”
Kung ako'y nagpapatotoo para sa aking sarili, ang patotoo ko ay hindi totoo.
Mula sa bakol ng tinapay na walang pampaalsa na inilagay sa harapan ng Panginoon , ay kumuha siya ng isang tinapay na walang pampaalsa, at ng isang tinapay na nilangisan at ng isang manipis na tinapay, at inilagay sa ibabaw ng taba at sa ibabaw ng kanang hita.
Pagkatapos ng mga bagay na ito, tinitigan si Jose ng asawa ng kanyang panginoon at sinabi, “Sipingan mo ako.”
Ako ang pintuan. Ang sinumang pumasok sa pamamagitan ko ay maliligtas, at papasok at lalabas, at makakatagpo ng pastulan.
Gagawa ka ng mga pasanang yari sa kahoy na akasya at iyong babalutin ng ginto.
At ang kanang hita ay ibibigay ninyo sa pari bilang handog mula sa alay ng inyong mga handog pangkapayapaan.
Nang masabi na ni Jesus ang mga bagay na ito, tumingala siya sa langit at sinabi, “Ama, dumating na ang oras, luwalhatiin mo ang iyong Anak, upang luwalhatiin ka ng Anak,
Ang isang omer ay ikasampung bahagi ng isang efa.
At kanilang sinabi sa kanya, “Saan mo gustong ihanda namin ito?”
Subalit sinabi ni Jesus sa kanila, “Hindi ninyo nalalaman ang inyong hinihingi. Kaya ba ninyong uminom sa kopang aking iinuman; o mabautismuhan sa bautismo na ibinabautismo sa akin?”
At ibinuhos ng ikaapat ang kanyang mangkok sa araw at pinahintulutan itong pasuin ng apoy ang mga tao.
Ang may pandinig ay makinig sa sinasabi ng Espiritu sa mga iglesya.”
Nang aming matapos na ang paglalakbay buhat sa Tiro, dumating kami sa Tolemaida; at binati namin ang mga kapatid at kami'y nanatiling kasama nila ng isang araw.
At ito ang buhay na walang hanggan, na ikaw ay makilala nila na iisang Diyos na tunay, at si Jesu-Cristo na iyong sinugo.
Muli siyang nagsugo ng ibang mga alipin, na sinasabi, ‘Sabihin ninyo sa mga inanyayahan: Narito, naihanda ko na ang aking handaan; pinatay na ang aking mga baka at matatabang hayop at handa na ang lahat. Halina kayo sa handaan ng kasalan.’
Samantalang siya'y nasa isa sa mga lunsod, may dumating na isang lalaki na punô ng ketong. Nang makita niya si Jesus, lumuhod siya at nakiusap sa kanya, “Panginoon, kung nais mo ay maaari mo akong linisin.”
Tama; sa kawalan nila ng pananampalataya ay nabali sila, at sa iyong pananampalataya'y nakatayo ka. Huwag kang magmalaki kundi matakot ka.
Ang sinumang lalaking hindi tuli, na hindi tinuli ang balat ng maselang bahagi ay ititiwalag sa kanyang bayan; sinira niya ang aking tipan.”
Nang siya'y makita ni Jesus, kanyang tinawag siya at sinabi sa kanya, “Babae, pinalaya ka na sa iyong sakit.”
Ngunit kung hindi siya makinig ay magsama ka pa ng isa o dalawa, upang sa bibig ng dalawa o tatlong saksi ay mapagtibay ang bawat salita.
Sapagkat ang araw ay sumisikat na may nakakapasong init at tinutuyo ang damo at nilalagas ang bulaklak nito, at nawawala ang kagandahan nito. Gayundin ang taong mayaman ay malalanta sa gitna ng kanyang abalang pamumuhay.
Kahit hinalughog mo ang lahat ng aking kasangkapan, anong natagpuan mong kasangkapan ng iyong bahay? Ilagay mo rito sa harapan ng aking mga kamag-anak at ng iyong mga kamag-anak at hayaan mong magpasiya sila sa ating dalawa.
At sa pandinig ng lahat ng mga tao ay sinabi niya sa kanyang mga alagad,
at bawat may sandata sa inyo ay tatawid sa Jordan sa harap ng Panginoon , hanggang sa kanyang mapalayas ang kanyang mga kaaway sa harap niya;
Ang iba ay nahulog sa mabuting lupa at namunga, na tumataas, lumalago at namumunga ng tatlumpu, animnapu, at isandaan.”
Pumunta ang taong ito kay Pilato at hiningi ang bangkay ni Jesus. At ipinag-utos ni Pilato na ibigay iyon.
Kasunod nito ay ipinanganak niya ang kanyang kapatid na si Abel. Si Abel ay tagapag-alaga ng mga tupa at si Cain ay magbubungkal ng lupa.
(tinatawag ng mga taga-Sidon ang Hermon na Sirion, at ito ay tinatawag ng mga Amoreo na Senir),
Sinabi sa kanya, ‘Iwan mo ang iyong lupain at ang iyong mga kamag-anak at pumunta ka sa lupaing ipapakita ko sa iyo.’
Iyong aalalahanin na ikaw ay naging alipin sa Ehipto. Masikap mong gawin ang mga tuntuning ito.
Ginagawa nila ang lahat ng kanilang mga gawa upang makita ng mga tao; sapagkat pinalalapad nila ang kanilang mga pilakteria, at pinahahaba ang mga laylayan ng kanilang mga damit.
Sapagkat kakaunti ang ari-arian mo bago ako dumating, at ito ay dumami nang sagana. Pinagpala ka ng Panginoon saan man ako bumaling; at ngayo'y kailan naman ako maghahanda ng para sa aking sariling bahay?”
Nang sila'y makarating sa Salamis, kanilang ipinangaral ang salita ng Diyos sa mga sinagoga ng mga Judio. Kasama rin nila si Juan bilang katulong.
Sa pagdalaw ni Pedro sa lahat ng dako sa mga mananampalataya, pumunta rin siya sa mga banal na naninirahan sa Lidda.
At susunugin ng pari bilang bahaging pinakaalaala ang bahagi ng butil na niligis at ang bahagi ng langis, pati ang lahat ng kamanyang niyon; ito ay isang handog sa Panginoon na pinaraan sa apoy.
Kung may gulang na mula sa limang taon hanggang sa may dalawampung taon, ang itutumbas mo ay dalawampung siklo ang sa lalaki at ang sa babae ay sampung siklo.
At ako, palibhasa'y naguguluhan tungkol sa pagsisiyasat ng mga bagay na ito, ay itinanong ko kung ibig niyang pumunta sa Jerusalem at doon siya litisin tungkol sa mga bagay na ito.
mula sa lipi ni Juda ay si Caleb na anak ni Jefone;
Hindi na ako magsasalita pa ng marami sa inyo, sapagkat dumarating ang pinuno ng sanlibutan. Siya'y walang kapangyarihan sa akin.
Sapagkat ang tinapay ng Diyos ay ang bumababang mula sa langit at nagbibigay ng buhay sa sanlibutan.
Subalit kung ang anak na babae ng pari ay balo o hiwalay sa asawa at walang anak at bumalik sa bahay ng kanyang ama na gaya rin nang kanyang kabataan, siya ay makakakain ng tinapay ng kanyang ama, ngunit ang sinumang dayuhan ay hindi makakakain niyon.
Kanilang sinabi, “Anong gagawin natin sa mga taong ito? Sapagkat hayag sa lahat ng naninirahan sa Jerusalem ang isang kapansin-pansing tanda na ginawa sa pamamagitan nila; at hindi natin ito maikakaila.
Sapagkat sinasabi niya, “Sa panahong kanais-nais ay pinakinggan kita, at tinulungan kita sa araw ng kaligtasan.” Ngayon na ang panahong kanais-nais; ngayon na ang araw ng kaligtasan.
Inutusan naman sila ni Jesus na huwag nilang sabihin ito kaninuman; ngunit habang lalo niyang ipinagbabawal sa kanila, lalo namang masigasig nilang ipinamamalita ito.
Gayunman, ang mga ito'y maaari ninyong kainin sa lahat ng may pakpak na umuusad na may apat na paa, na may mga hita sa itaas ng mga paa, na ginagamit upang makalundag sa lupa.
“At sa anghel ng iglesya sa Tiatira ay isulat mo: Ang mga bagay na ito ay sinasabi ng Anak ng Diyos, na may mga matang gaya ng ningas ng apoy, at ang kanyang mga paa ay gaya ng tansong pinakintab.
At sinabi niya sa kanila, “Nakita ko si Satanas na nahulog na gaya ng kidlat mula sa langit.
Ngunit may ilan doon na pagalit na sinabi sa kanilang sarili, “Bakit sinayang nang ganito ang pabango?
Subalit ang mga taong ito, ay gaya ng mga hayop na walang bait, na ipinanganak na talagang mga hayop upang hulihin at patayin. Kanilang inaalipusta ang mga bagay na hindi nila nauunawaan at kapag ang mga nilalang na ito ay nilipol, sila ay lilipulin din,
Dapat sana'y inilagak mo ang aking salapi sa mga mangangalakal ng salapi, at nang sa aking pagdating ay matanggap ko kung ano ang akin pati na ang pakinabang.
Kung magbalak ang sinuman sa kanyang kapwa na patayin siya nang pataksil, aalisin mo siya sa aking dambana upang siya'y mamatay.
Nang marinig nila ang mga bagay na ito, napuno ng galit ang lahat ng nasa sinagoga.
Ang Panginoon ay nagsalita kay Moises, na sinasabi:
Madalas ko silang pinarurusahan sa lahat ng mga sinagoga at pinipilit ko silang manlapastangan; at sa nag-aalab na pagkagalit sa kanila ay pinag-uusig ko sila maging sa mga lunsod sa ibang lupain.
Hindi pa ba ninyo nauunawaan o natatandaan ang limang tinapay para sa limang libo at kung ilang kaing ang inyong natipon?
At sinabi niya sa babae, “Iniligtas ka ng iyong pananampalataya, humayo kang payapa.”
Sapagkat kanino sa mga anghel sinabi ng Diyos kailanman, “Ikaw ay aking Anak, ako ngayon ay naging iyong Ama?” At muli, “Ako'y magiging kanyang Ama, at siya'y magiging aking Anak?”
Dadalhin niya sa pari ang kanyang handog para sa budhing maysala sa Panginoon , ang isang tupang lalaki na walang kapintasan na mula sa kawan, ayon sa iyong halagang itinakda para sa isang handog para sa budhing maysala.
Kung ang isang lalaki ay sumiping sa isang babaing may regla, at ilitaw ang kahubaran niya; kanyang hinubaran ang kanyang daloy at kanyang pinalitaw ang daloy ng kanyang dugo; at sila'y kapwa ititiwalag sa kalagitnaan ng kanilang bayan.
At may dumating at nagsabi sa kanila, “Tingnan ninyo, ang mga lalaking ibinilanggo ninyo ay nakatayo sa templo at nagtuturo sa mga tao!”
Makaraan ang tatlong buwan ay naglayag kami sa isang barkong Alejandria na nagpalipas ng tagginaw sa pulo, na ang sagisag ay Ang Magkapatid na Kambal.
Kahabag-habag kayong mga dalubhasa sa kautusan, sapagkat kinuha ninyo ang susi ng karunungan. Kayo mismo ay hindi pumasok, at inyong hinadlangan ang mga pumapasok.”
Ngayon ang paghatol sa sanlibutang ito. Ngayon ang pinuno ng sanlibutang ito ay palalayasin.
“At kayo'y aking inutusan nang panahong iyon, na sinasabi, ‘Ibinigay sa inyo ng Panginoon ninyong Diyos ang lupaing ito upang angkinin; kayong lahat na mandirigma ay daraang may sandata sa harapan ng inyong mga kapatid na mga anak ni Israel.
Ang balabal na aking iniwan sa Troas kay Carpo ay iyong dalhin pagparito mo, at ang mga aklat, lalung-lalo na ang mga pergamino.
Sapagkat ang lahat na sa inyo na binautismuhan kay Cristo ay ibinihis si Cristo.
Sa labas ay namimighati ang tabak, at sa mga silid ay malaking takot; kapwa mawawasak ang binata at dalaga, ang sanggol pati ng lalaking may uban.
na sinuma'y huwag magkasala o manlamang sa kanyang kapatid sa bagay na ito, sapagkat ang Panginoon ay tagapaghiganti sa lahat ng mga bagay na ito, gaya ng aming sinabi noong una at ibinabala sa inyo.
Nagsisagot sina Raquel at Lea, at sinabi sa kanya, “Mayroon pa bang natitirang bahagi at mana para sa amin sa bahay ng aming ama?
Bagama't ibig niyang ipapatay si Juan, natakot siya sa mga tao sapagkat kanilang itinuturing si Juan na isang propeta.
“Ang mga banal na kasuotan ni Aaron ay magiging sa kanyang mga anak pagkamatay niya, upang buhusan ng langis ang mga iyon, at upang italaga sa mga iyon.
Magtipun-tipon kayo at makinig, kayong mga anak ni Jacob; at inyong pakinggan si Israel na inyong ama.
Sapagkat sa katotohanan, nang kami ay kasama ninyo ay aming sinabi noon pa mang una na kami ay makakaranas ng kapighatian; gaya nga ng nangyari, at nalalaman ninyo.
at inyong sinabi, ‘Ipinakita sa amin ng Panginoon nating Diyos ang kanyang kaluwalhatian at kadakilaan. Aming narinig ang kanyang tinig mula sa gitna ng apoy; aming nakita sa araw na ito na ang Diyos ay nakikipag-usap sa tao, at ang tao ay nabubuhay pa.
Sapagkat ang aming ipinagmamalaki ay ito, ang patotoo ng aming budhi; kami ay namuhay ng wasto sa sanlibutan, at lalo na sa inyo, na may kapayakan at maka-Diyos na katapatan, hindi ayon sa karunungan ng laman, kundi sa biyaya ng Diyos.
Muli siyang umalis at nanalangin na sinabi ang gayunding mga salita.
Sapagkat nalalaman ng hari ang mga bagay na ito, at sa kanya'y nagsasalita ako ng buong laya, sapagkat naniniwala ako na sa kanya'y walang nalilingid sa mga bagay na ito; sapagkat ito'y hindi ginawa sa isang sulok.
O kung sila'y mga pantas, kanilang mauunawaan ito, at malalaman nila ang kanilang wakas!
Siya'y yumuko, siya'y lumugmok na parang leon, at parang isang babaing leon, sinong gigising sa kanya? Pagpalain nawa ang lahat na nagpapala sa iyo, at sumpain ang lahat na sumusumpa sa iyo.”
“Paraanin mo ako sa iyong lupain. Kami ay hindi liliko sa bukid o sa ubasan. Kami ay hindi iinom ng tubig mula sa mga balon; kami ay daraan sa Daan ng Hari hanggang sa makaraan kami sa iyong nasasakupan.”
upang ang nakamatay ng tao ay makatakas patungo doon, na nakamatay sa kanyang kapwa na hindi sinasadya, na hindi niya naging kaaway nang nakaraan; na sa pagtakas sa isa sa mga lunsod na ito ay maaari niyang iligtas ang kanyang buhay:
At iyong titipunin sa liwasan ang lahat ng nasamsam doon, at iyong susunugin sa apoy ang lunsod, at ang lahat ng nasamsam doon, bilang handog na sinusunog para sa Panginoon mong Diyos. Ito ay magiging isang bunton magpakailanman; hindi na muling maitatayo.
Nabuhay si Kenan pagkatapos na maipanganak si Mahalalel ng walong daan at apatnapung taon, at nagkaanak pa ng mga lalaki at mga babae.
Ang patuloy na gumagawa ng kasalanan ay sa diyablo; sapagkat buhat pa nang pasimula ay nagkakasala na ang diyablo. Dahil dito, nahayag ang Anak ng Diyos upang wasakin ang mga gawa ng diyablo.
Pagkatapos ay lumapit nang sarilinan ang mga alagad kay Jesus at sinabi nila, “Bakit hindi namin iyon napalayas?”
Kung ang sinuman ay patungo sa pagkabihag, sa pagkabihag siya patutungo. Kung ang sinuman ay pumapatay sa pamamagitan ng tabak, sa pamamagitan ng tabak siya dapat papatayin. Ito ay panawagan para sa pagtitiis at pananampalataya ng mga banal.
Sinabi ng Panginoon kay Moises, “Umahon ka sa bundok na ito ng Abarim, at tanawin mo ang lupain na aking ibinigay sa mga anak ni Israel.
ang dalawampung haligi at ang kanilang mga patungan ay dapat yari sa tanso, ngunit ang kawit ng mga haligi at ang mga baras na sabitan ng mga iyon ay pilak.
Kanyang sinabi, “May kamay sa watawat ng Panginoon . Ang Panginoon ay makikipagdigma kay Amalek mula sa isang salinlahi hanggang sa susunod na salinlahi.”
Ang napahasik sa mga tinikan ay iyong nakikinig ng salita; ngunit ang kabalisahan ng sanlibutan at ang daya ng mga kayamanan ay sumasakal sa salita at iyon ay nagiging walang bunga.
Iba't ibang lahi, mga kawan, mga baka, at napakaraming hayop ang umahon ding kasama nila.
Samantalang siya'y nakaupo sa liwanag ng apoy, nakita siya ng isang alilang babae, tumitig sa kanya at nagsabi, “Ang taong ito ay kasama rin niya.”
At nakita ko ang isang makapangyarihang anghel na nagpapahayag sa malakas na tinig, “Sino ang karapat-dapat magbukas ng aklat at magtanggal ng mga tatak nito?”
Iyon ay inyong iingatan hanggang sa ikalabing-apat na araw ng buwang ito, at papatayin ng buong kapulungan ng kapisanan ng Israel ang kanilang mga kordero sa paglubog ng araw.
Nasa kamay niya ang kanyang kalaykay at lilinisin niya ang kanyang giikan. Titipunin niya ang kanyang trigo sa kamalig, subalit ang ipa ay susunugin niya sa apoy na hindi mapapatay.”
Ang lahat ng mga lunsod nito'y napapaligiran ng matataas na pader, mga pintuang-lunsod at mga halang; bukod pa ang napakaraming mga nayong walang pader.
Nang makalapit siya sa kampo, at kanyang makita ang guya at ang pagsasayawan, ang galit ni Moises ay nag-alab, at kanyang ibinato ang mga tapyas na nasa kanyang mga kamay at binasag ang mga ito sa paanan ng bundok.
Kaya't sa ganang akin, nasasabik din akong ipangaral ang ebanghelyo sa inyong mga nasa Roma.
Kaya't ano ngang bunga mayroon kayo sa mga bagay na ngayo'y ikinahihiya ninyo? Sapagkat ang kahihinatnan ng mga bagay na iyon ay kamatayan.
Walang pag-aalinlangan, dakila ang hiwaga ng kabanalan: Siyang nahayag sa laman, pinatunayang matuwid sa espiritu, nakita ng mga anghel, ipinangaral sa mga bansa, sinampalatayanan sa sanlibutan, tinanggap sa itaas sa kaluwalhatian.
Ano sa palagay ninyo? Kung ang isang tao ay may sandaang tupa, at isa sa kanila ay naligaw. Hindi ba niya iiwan ang siyamnapu't siyam sa kabundukan, at hahayo upang hanapin ang naligaw?
Nang mabalitaan ito ng kanyang mga alagad, pumaroon sila at kinuha ang kanyang bangkay at inilagay sa isang libingan.
Sinabi pa niya sa kanila, “Maganda ang paraan ng inyong pagtanggi sa utos ng Diyos, upang masunod ang inyong mga tradisyon.
Malaman nawa ng lahat ng mga tao ang inyong kahinahunan. Ang Panginoon ay malapit na.
Nang makita niya si Pedro na nagpapainit, siya'y kanyang tinitigan at sinabi, “Ikaw man ay kasama rin ni Jesus na taga-Nazaret.”
ni hindi rin naman siya pinaglilingkuran ng mga kamay ng tao, na para bang mayroon siyang kailangan, yamang siya ang nagbibigay sa lahat ng tao ng buhay at ng hininga, at ng lahat ng bagay na ito.
Ang laman at balat ay sinunog niya sa apoy sa labas ng kampo.
At sila'y kumuha ng bunga ng lupain at ibinaba iyon sa atin, at ibinalita, ‘Ang lupaing ibinibigay sa atin ng Panginoon ay mabuti.’
Nang siya'y lumabas nang sumunod na araw, may dalawang lalaking Hebreo na naglalaban; at kanyang sinabi sa gumawa ng masama, “Bakit mo sinasaktan ang iyong kasama?”
Sumiping si Cain sa kanyang asawa, at siya'y naglihi at ipinanganak si Enoc. Siya'y nagtayo ng isang lunsod at tinawag ang lunsod ayon sa pangalan ng kanyang anak na si Enoc.
Ang Ama'y hindi humahatol sa kanino mang tao, kundi ipinagkaloob niya sa Anak ang buong paghatol;
Walang kaligtasan sa kanino pa man, sapagkat walang ibang pangalan sa ilalim ng langit na ibinigay sa mga tao na ating ikaliligtas.”
Si Juda'y isang anak ng leon. Aking anak, ikaw ay umahon mula sa pagkahuli, siya'y yumuko, siya'y lumugmok na parang leon; at gaya ng isang babaing leon, sinong makakagising sa kanya?
Tumingala ang lalaki at nagsabi, “Nakakakita ako ng mga tao, na parang mga punungkahoy na naglalakad.”
Nang siya'y malapit na sa Betfage at Betania, sa bundok na tinatawag na Olibo, ay sinugo niya ang dalawa sa mga alagad,
At nais namin na ang bawat isa sa inyo ay magpakita ng gayunding sigasig upang inyong malaman ang ganap na katiyakan ng pag-asa hanggang sa katapusan;
Si Miriam ay pitong araw na kinulong sa labas ng kampo at ang bayan ay hindi umalis upang maglakbay hanggang si Miriam ay nadalang muli sa loob.
Habang naroon kami ng ilang araw, isang propeta na ang pangalan ay Agabo ang dumating mula sa Judea.
Sapagkat kung ang salita na ipinahayag sa pamamagitan ng mga anghel ay may bisa, at ang bawat paglabag at pagsuway ay tumanggap ng kaukulang parusa,
Iyong ipapasuot ang mga ito kay Aaron na iyong kapatid at sa kanyang mga anak na kasama niya, bubuhusan mo sila ng langis, itatalaga, ibubukod upang maglingkod sa akin bilang mga pari.
Nagsalita ang Panginoon kay Moises, na sinasabi,
Titimplahan mo ng asin ang lahat ng iyong butil na handog. Huwag mong hayaang ang iyong butil na handog ay mawalan ng asin sa pakikipagtipan ng iyong Diyos; lahat ng iyong mga alay ay ihahandog mong may asin.
Bukod dito'y pipili ka sa buong bayan ng mga lalaking may kakayahan, gaya ng mga may takot sa Diyos, mga lalaking mapagkakatiwalaan at mga napopoot sa suhol. Ilagay mo ang mga lalaking iyon na mamuno sa kanila, mamuno sa libu-libo, sa daan-daan, sa lima-limampu, at sa sampu-sampu.
Sapagkat inihanda ang unang tabernakulo na kinaroroonan ng ilawan, dulang, at ng mga tinapay na handog; ito ay tinatawag na Dakong Banal.
ay iyong ihahandog nga na kasama ng toro ang isang handog na butil na tatlong ikasampung bahagi ng isang efa ng piling harina na hinaluan ng kalahating hin ng langis.
Sapagkat ang kalungkutang naaayon sa Diyos ay nagbubunga ng pagsisisi tungo sa kaligtasan na hindi ipagdaramdam, subalit ang makasanlibutang kalungkutan ay nagbubunga ng kamatayan.
Kumuha ka ng tigpipito sa bawat malinis na hayop, lalaki at babae; at dalawa sa mga hayop na hindi malinis, lalaki at babae.
At kung ako'y humatol man, ang hatol ko'y totoo, sapagkat hindi ako nag-iisa, kundi ako at ang Ama na nagsugo sa akin.
Ako'y naging hubad at inyong dinamitan. Ako'y nagkasakit at ako'y inyong dinalaw. Ako'y nabilanggo at ako'y inyong pinuntahan.’
Ito ay magpapahinga sa lahat ng mga araw ng pagkasira na hindi nito ipinagpahinga sa inyong mga Sabbath nang kayo'y naninirahan doon.
At nang matapos na ang aming mga araw doon, umalis kami at nagpatuloy sa aming paglalakbay, at silang lahat, kasama ang mga asawa at mga anak, ay inihatid kami sa aming patutunguhan hanggang sa labas ng bayan. Pagkatapos naming lumuhod sa baybayin at nanalangin,
May pitong lalaking magkakapatid. Nag-asawa ang panganay at nang mamatay siya ay walang naiwang anak.
Ang bilang ng mga hukbong nangangabayo ay makalawang sampung libong tigsasampung libo; aking narinig ang bilang nila.
“Kapag ikaw ay lumabas upang makipagdigma laban sa iyong mga kaaway, at ibibigay sila ng Panginoon mong Diyos sa iyong mga kamay, at dadalhin mo silang bihag,
Sumagot siya at sinabi, “Ang naghahasik ng mabuting binhi ay ang Anak ng Tao.
Ang Paskuwa nga ng mga Judio ay malapit na, at maraming umahon tungo sa Jerusalem mula sa lupaing iyon bago magpaskuwa, upang linisin ang kanilang mga sarili.
At isinalaysay ni Jesus sa kanila ang isang talinghaga kung paanong sila'y dapat laging manalangin at huwag manlupaypay.
Gaya ng mga kabanal-banalang bagay ay kakain ka ng mga iyan: bawat lalaki ay kakain niyon; iyon ay banal na bagay para sa iyo.
Ang magiging pinuno sa sambahayan ng mga ninuno ng mga angkan ng mga Kohatita ay si Elisafan na anak ni Uziel.
kundi tungkol lamang sa mga pagkain at mga inumin at iba't ibang paghuhugas, na mga alituntunin tungkol sa katawan na ipinatutupad hanggang sa ang panahon ay dumating upang maisaayos ang mga bagay.
Pagkatapos ay kinuha ni Moises ang mga iyon sa kanilang mga kamay, at sinunog sa ibabaw ng dambana kasama ng handog na sinusunog bilang handog sa pagtatalaga na mabangong samyo. Ito ay handog sa Panginoon na pinaraan sa apoy.
Hindi ko siya nakilala, dahil dito'y naparito ako na nagbabautismo sa tubig upang siya'y mahayag sa Israel.”
Ikaw ay pinagpakumbaba niya nang ginutom ka niya, at pinakain ka niya ng manna, na hindi mo nakilala, ni hindi nakilala ng iyong mga ninuno, upang kanyang maipaunawa sa iyo na hindi lamang sa tinapay nabubuhay ang tao, kundi sa bawat salitang lumalabas sa bibig ng Panginoon .
Subalit sinabi ni Abraham, ‘Anak, alalahanin mo na sa iyong buhay ay tinanggap mo ang iyong mabubuting bagay, at si Lazaro naman ay ang masasamang bagay. Subalit ngayon ay inaaliw siya rito at ikaw ay nagdurusa.
Nang magkagayo'y lumapit ang mga anak na babae ni Zelofehad, na anak ni Hefer, na anak ni Gilead, na anak ni Makir, na anak ni Manases, sa mga angkan ni Manases, na anak ni Jose. Ito ang mga pangalan ng kanyang mga anak: Mahla, Noa, Hogla, Milca, at Tirsa.
Ngunit nang nauna kami sa barko, naglakbay kami patungo sa Asos, na mula roon ay binabalak naming isama si Pablo, sapagkat gayon ang kanyang ipinasiya, na binalak niyang sa lupa maglakbay.
At kayo, na nang dati ay hiwalay at mga kaaway sa pag-iisip, sa pamamagitan ng masasamang gawa,
Ikaw ay magkakaroon ng kaligayahan at kagalakan at marami ang matutuwa sa kanyang pagsilang.
Si Uz ang kanyang panganay, si Buz na kanyang kapatid, at si Kemuel na ama ni Aram;
At bakit? Sapagkat hindi ko kayo minamahal? Alam ito ng Diyos!
Anupa't ipinagmamalaki namin kayo sa mga iglesya ng Diyos dahil sa inyong pagtitiis at pananampalataya sa lahat ng mga pag-uusig sa inyo at sa mga kapighatiang inyong tinitiis.
Ang iyong mga ninuno ay lumusong sa Ehipto na may pitumpung katao; at ngayo'y ginawa ka ng Panginoon mong Diyos na kasindami ng mga bituin sa langit.
Sapagkat ibig kong malaman ninyo kung gaano kalaki ang aking pagsisikap alang-alang sa inyo, at sa mga nasa Laodicea, at sa lahat na hindi pa nakakita sa akin nang mukhaan.
Kaya't sinabi nila sa kanya, “Nasaan ang iyong Ama?” Sumagot si Jesus, “Hindi nga ninyo ako kilala o ang aking Ama. Kung ako'y inyong kilala ay kilala rin sana ninyo ang aking Ama.”
At sinabi niya sa kanila, “Ang sinumang makipaghiwalay sa kanyang asawang babae at mag-asawa sa iba ay nagkakasala ng pangangalunya laban sa kanya.
Ang Diyos ay kasama ng bata at siya'y lumaki, at nanirahan sa ilang at naging sanay sa paggamit ng pana.
Ang Israel ay gumawa ng sumpa sa Panginoon at nagsabi, “Kung tunay na ibibigay mo ang bayang ito sa aking kamay, aking lubos na gigibain ang kanilang mga bayan.”
Sa ikawalong araw ay kanyang dadalhin ang mga iyon sa pari sa pintuan ng toldang tipanan para sa kanyang paglilinis sa harapan ng Panginoon .
Sa gabi't araw ay palagi siyang nagsisisigaw sa mga libingan at sa mga kabundukan, at sinusugatan ang sarili ng mga bato.
Ngunit kinagabihan ay binuksan ng isang anghel ng Panginoon ang mga pintuan ng bilangguan, sila'y inilabas, at sinabi,
Nakarating sila sa Capernaum at nang siya'y nasa bahay na ay tinanong niya sila, “Ano ang pinagtatalunan ninyo sa daan?”
Kung hindi niya gawin ang tatlong bagay na ito para sa kanya, siya ay aalis na walang bayad, na walang itinubos na salapi.
Kaya't, narito, nagsusugo ako sa inyo ng mga propeta, ng mga pantas, at ng mga eskriba, na ang iba sa kanila'y inyong papatayin at ipapako sa krus, at ang iba nama'y inyong hahagupitin sa inyong mga sinagoga, at inyong uusigin sa bayan-bayan,
Tinawag ni Jacob ang pangalan ng lugar na iyon na Peniel na sinasabi, “Sapagkat nakita ko ang Diyos sa harapan, at naligtas ang aking buhay.”
Kayo'y mga saksi ng mga bagay na ito.
Ngunit kung gayo'y paanong matutupad ang mga kasulatan, na ganito ang kinakailangang mangyari?”
O Timoteo, ingatan mo ang ipinagkatiwala sa iyo. Iwasan mo ang mga usapang walang kabuluhan at ang mga pagsalungat ng huwad na kaalaman;
Tutuparin nga ninyo ang aking mga alituntunin at mga batas; na kapag tinupad ng isang tao, siya ay mabubuhay. Ako ang Panginoon .
At sabihin mo sa lahat ng may kakayahan na aking pinagkalooban ng kasanayan na kanilang gawin ang kasuotan ni Aaron, upang siya'y italaga sa pagkapari para sa akin.
panunumpain ng pari ang babae ng panunumpang sumpa, at sasabihin ng pari sa babae, ‘Gagawin ka ng Panginoon na sumpa at kahihiyan sa gitna ng iyong bayan, kapag pinalaylay ng Panginoon ang iyong hita at pinamaga ang iyong katawan.
Sapagkat inaakala kong hindi makatuwiran na sa pagpapadala ng isang bilanggo, ay hindi mailahad ang sakdal laban sa kanya.”
Kaya't maging ang unang tipan ay hindi pinagtibay ng walang dugo.
Nagpalayas sila ng maraming demonyo, pinahiran ng langis ang maraming maysakit at pinagaling sila.
Huwag sabihin ng sinuman kapag siya'y tinutukso, “Ako'y tinutukso ng Diyos,” sapagkat ang Diyos ay hindi natutukso ng masasama, at hindi rin siya nanunukso sa sinuman.
Kaya't nararapat na magpasakop, hindi lamang dahil sa galit, kundi dahil din sa budhi.
Tungkol sa mga bagay na isinusulat ko sa inyo, sa harapan ng Diyos, hindi ako nagsisinungaling.
Kanilang ipapatong doon ang lahat ng mga kasangkapan ng dambana na ginagamit sa paglilingkod doon, ang apuyan at ang mga pantusok, ang mga pala at ang mga mangkok, lahat ng mga kasangkapan ng dambana. Kanilang lalatagan iyon ng isang panakip na balat ng kambing, at kanilang ilalagay sa mga pasanan niyon.
Pagkatapos ay nakita ko roon ang isang puting ulap, at nakaupo sa ulap ang isang katulad ng isang Anak ng Tao na sa kanyang ulo'y may isang gintong korona, at sa kanyang kamay ay may isang matalas na karit.
Ngayon, kung may kasakdalan sa pamamagitan ng pagkapari ng mga Levita, (sapagkat batay dito ay tinanggap ng bayan ang kautusan), ano pa ang karagdagang pangangailangan upang lumitaw ang isa pang pari, ayon sa pagkapari ni Melquizedek, sa halip na ayon sa pagkapari ni Aaron?
Ibinigay ni Moises ang buwis, na ukol sa handog sa Panginoon , sa paring si Eleazar, gaya ng iniutos ng Panginoon kay Moises.
‘Matagal na ninyong naligid ang bundok na ito; lumiko kayo sa dakong hilaga.
At sinasabi ko sa inyo, makipagkaibigan kayo para sa inyong mga sarili sa pamamagitan ng mga kayamanan ng kalikuan upang kung ito'y maubos na, ay kanilang tanggapin kayo sa mga walang hanggang tahanan.
Subalit ang kautusan ay hindi nakasalig sa pananampalataya; sa halip, “Ang gumagawa ng mga iyon ay mabubuhay sa mga iyon.”
Natatandaan ninyo, mga kapatid, ang aming pagpapagal at paghihirap. Gumagawa kami araw at gabi upang huwag kaming maging pasanin sa kaninuman sa inyo. Ipinahayag namin sa inyo ang ebanghelyo ng Diyos.
Sinabi sa kanya ni Jesus, “Umalis ka na! Tawagin mo ang iyong asawa at bumalik ka rito.”
na ipinapaliwanag at pinatutunayan na kailangang magdusa ang Cristo at muling mabuhay mula sa mga patay; at sinasabi, “Itong Jesus na aking ipinangangaral sa inyo ay siyang Cristo.”
Sapagkat tayo'y mayroong isang Pinakapunong Pari na marunong makiramay sa ating mga kahinaan, isa na tinukso sa lahat ng mga paraan gaya rin naman natin, gayunma'y walang kasalanan.
at sinasabi, “Kung ikaw ang Hari ng mga Judio, iligtas mo ang iyong sarili!”
Kaya't sinabi ng mga Judio sa taong pinagaling, “Ngayo'y araw ng Sabbath, at hindi ipinahihintulot na buhatin mo ang iyong higaan.”
at kung ang diwa ng paninibugho ay dumating sa kanya, at siya'y maninibugho sa kanyang asawa na dumungis sa kanyang sarili o kung ang diwa ng paninibugho ay dumating sa kanya at siya'y naninibugho sa kanyang asawa, bagaman hindi niya dinungisan ang kanyang sarili,
Kanyang ihahandog sa Panginoon ang lalaking tupa bilang handog pangkapayapaan na kalakip ng bakol ng mga tinapay na walang pampaalsa. Ihahandog din ng pari ang handog na butil niyon at ang handog na inumin niyon.
Iyong ipagdiriwang ang pista ng pag-aani ng mga unang bunga ng iyong pagpapagal, na iyong inihasik sa bukid. Ipagdiriwang mo rin ang pista ng pag-aani, sa katapusan ng taon, kapag inaani mo mula sa bukid ang bunga ng iyong pagpapagal.
Mag-ingat kayo, baka ang inyong puso ay madaya, at kayo'y maligaw, at maglingkod sa ibang mga diyos, at sumamba sa kanila.
Tumawag sila upang magtanong kung si Simon, na tinatawag na Pedro, ay nanunuluyan doon.
Ganito papasok si Aaron sa loob ng dakong banal: may dalang isang guyang toro na handog pangkasalanan, at isang tupang lalaki na handog na sinusunog.
dahil sa pag-asa na nakalaan para sa inyo sa langit, na inyong narinig noong una sa salita ng katotohanan, ang ebanghelyo,
Nakita ng kanyang amo na ang Panginoon ay kasama niya, at ang lahat ng ginagawa ni Jose ay umuunlad sa kanyang kamay.
Ang Diyos ang naglalabas sa kanila sa Ehipto. Siya'y may lakas na gaya ng mabangis na toro.
Huwag kayong gagawa ng anumang gawa sa araw ding ito, sapagkat ito ay araw ng pagtubos, upang gumawa ng pagtubos para sa inyo sa harapan ng Panginoon ninyong Diyos.
Mayroong labindalawang bato na may mga pangalan ayon sa mga pangalan ng mga anak ni Israel; ang mga iyon ay gaya ng mga singsing-pantatak, bawat isa'y may nakaukit na pangalan na ukol sa labindalawang lipi.
Ikaw ay pasasaganain ng Panginoon sa ikabubuti mo, sa bunga ng iyong katawan, at sa bunga ng iyong mga hayop, at sa bunga ng iyong lupa, sa lupaing ipinangako ng Panginoon sa iyong mga ninuno upang ibigay sa iyo.
Ang pangalan ng una ay Pishon na siyang umaagos sa palibot ng buong lupain ng Havila, na doo'y may ginto;
ni Aminadab, ni Admin, ni Arni, ni Hesrom, ni Perez, ni Juda,
Nang sabihin niya ang mga bagay na ito, napahiya ang lahat ng kanyang mga kaaway at nagalak ang maraming tao dahil sa lahat ng maluwalhating bagay na kanyang ginawa.
Bawat pinakapunong pari na pinili mula sa mga tao ay pinangasiwa sa mga bagay na may kaugnayan sa Diyos, para sa kanilang kapakanan, upang siya'y makapaghandog ng mga kaloob at ng mga alay para sa mga kasalanan.
Siya'y lumapit, at kinuha ang aklat sa kanang kamay ng nakaluklok sa trono.
Humayo ka at sabihin mo sa kanila, “Bumalik kayo sa inyong mga tolda.”
Ang Faraon ay nagsugo, at walang namatay kahit isa sa kawan ng mga Israelita. Ngunit ang puso ni Faraon ay nagmatigas, at hindi niya pinayagang umalis ang taong-bayan.
Ang Panginoon ay nagsalita kay Moises nang araw ding iyon,
Kapag ang isang lalaki ay namanata ng isang panata sa Panginoon , o sumumpa ng isang sumpa, na itinali ang kanyang sarili sa pamamagitan ng isang panata, ay huwag niyang sisirain ang kanyang salita. Kanyang tutuparin ang ayon sa lahat ng lumabas sa kanyang bibig.
At kanyang sinabi, “Kung dumating si Esau sa isang pulutong at kanyang puksain ito, ang pulutong na natitira ay tatakas.”
At sinabi ni Abraham sa Diyos, “Bakit hindi na lang si Ismael ang magmana ng mga ipinangako ninyo sa akin?”
Nang sila'y makalabas sa bilangguan, pumunta sila kay Lydia; at nang makita nila ang mga kapatid, ay kanilang inaliw sila, pagkatapos ay umalis.
“‘Ni huwag kang mangangalunya.
Subalit ngayon, yamang ako ay wala nang lugar para sa gawain sa mga lupaing ito, at yamang matagal ko nang nais na pumunta sa inyo,
“Kaya't ang bawat kumikilala sa akin sa harapan ng mga tao ay kikilalanin ko rin sa harapan ng aking Ama na nasa langit.
na nakikiusap sa amin nang matindi tungkol sa biyaya na makibahagi sa paglilingkod sa mga banal.
nagngangalit na alon sa dagat, na pinabubula ang kanilang sariling kahihiyan; mga pagala-galang bituin, na silang pinaglaanan ng pusikit na kadiliman magpakailanman.
Nang marinig ng alipin ni Abraham ang kanilang mga salita, siya ay nagpatirapa sa lupa sa harap ng Panginoon .
Narito ako, handang pumariyan sa inyo sa ikatlong pagkakataon. Ako'y hindi magiging pasanin, sapagkat hindi ko hinahanap ang sa inyo, kundi kayo, sapagkat hindi nararapat ipag-impok ng mga anak ang mga magulang, kundi ang mga magulang para sa kanilang mga anak.
At tinanong nila siya, “Bakit sinasabi ng mga eskriba na kinakailangang dumating muna si Elias?”
Magalak kayo sa pag-asa, maging matiisin sa kapighatian, matiyaga sa pananalangin.
Kanilang dinalang buháy ang binata, at lubusan silang naaliw.
Siya'y natagpuan nila, at sinabi sa kanya, “Hinahanap ka ng lahat.”
“Pakinggan mo, O Israel, ikaw ay tatawid sa Jordan sa araw na ito, upang iyong pasukin at agawin ang mga bansang higit na dakila at makapangyarihan kaysa iyo, na mga bayang malaki at may pader hanggang sa langit,
At kapag hinipan ninyo ang hudyat sa ikalawang pagkakataon, lulusong ang mga kampo na nasa dakong timog. Sila'y hihihip ng isang hudyat sa tuwing sila'y maglalakbay.
Katotohanang sinasabi ko sa inyo, Saanman ipangaral ang ebanghelyo sa buong sanlibutan, ang ginawa ng babaing ito ay sasabihin sa pag-alaala sa kanya.”
“Sabihin mo kay Aaron, ‘Kapag sinindihan mo ang mga ilaw ay magbibigay liwanag ang pitong ilaw sa harap ng ilawan.’”
sapagkat ang nadala nila ay sapat na sa paggawa ng lahat ng gagawin, at higit pa.
Siya'y ginapos nila, dinala sa labas, at ibinigay nila kay Pilato na gobernador.
Kanilang sinabi, “Iniligtas kami ng isang Ehipcio mula sa kamay ng mga pastol at saka iniigib pa niya kami ng tubig at pinainom ang kawan.”
May isang babae na labindalawang taon nang dinudugo,
Sinabi ni Moises sa Panginoon , “Ang bayan ay hindi makakaakyat sa bundok ng Sinai, sapagkat ikaw mismo ang nagbilin sa amin na iyong sinasabi, ‘Lagyan mo ng hangganan sa palibot ang bundok, at iyong ariing banal ito.’”
Huwag na ninyong alalahanin pa ang inyong pag-aari, sapagkat ang pinakamabuti ng buong lupain ng Ehipto ay sa inyo.’”
At tungkol sa muling pagkabuhay ng mga patay, hindi ba ninyo nabasa ang sinabi sa inyo ng Diyos,
Gaya ng nasusulat, “Dahil sa iyo kami'y pinapatay sa buong araw; kami ay itinuring na mga tupa sa katayan.”
Sa kanilang paglalakbay sa silangan, nakatagpo sila ng isang kapatagan sa lupain ng Shinar, at sila'y tumira doon.
Ito ang unang pagtatala na ginawa nang si Quirinio ay gobernador sa Siria.
Sinabi niya sa kanila, “Kaninong larawan ito at ang nakasulat?”
Kaya't ikaw, anak ko, maging malakas ka sa biyayang na kay Cristo Jesus,
At nagsalita ang Panginoon kay Moises, na sinasabi,
Ito ang mga angkan ni Manases, at ang nabilang sa kanila ay limampu't dalawang libo at pitong daan.
kung natikman nga ninyo na ang Panginoon ay mabuti.
mga tinik at dawag ang sisibol doon para sa iyo, at kakain ka ng tanim sa parang.
Subalit ngayon ay ipinahahayag ang pagiging matuwid ng Diyos na hiwalay sa kautusan at pinatotohanan ng kautusan at ng mga propeta;
Katotohanang sinasabi ko sa inyo, hindi lilipas ang lahing ito, hanggang sa maganap ang lahat ng mga bagay na ito.
Sapagkat dahil dito ay nagpapagal kami at nagsisikap, sapagkat nakalagak ang aming pag-asa sa Diyos na buháy, na siyang Tagapagligtas ng lahat ng tao, lalo na ng mga nananampalataya.
Tungkol kay Ismael ay narinig kita. Pinagpala ko siya at siya'y gagawin kong mabunga at lubos kong pararamihin. Labindalawang prinsipe ang kanyang magiging anak, at siya'y gagawin kong malaking bansa.
Ang mga anak ni Israel, ang buong kapulungan, ay dumating sa ilang ng Zin nang unang buwan; at ang bayan ay nanatili sa Kadesh. Si Miriam ay namatay, at inilibing doon.
Hayaan mong dalhan ko kayo rito ng kaunting tubig, at maghugas kayo ng inyong mga paa, at magpahinga kayo sa lilim ng kahoy.
Sinabi niya sa kanila, “Bakit kayo natatakot, O kayong maliliit ang pananampalataya?” Kaya't bumangon siya at sinaway ang mga hangin at ang dagat, at nagkaroon ng lubos na kapayapaan.
Akong si Tercio, na sumusulat ng sulat na ito, ay bumabati sa inyo sa Panginoon.
Sapagkat ang bawat humihingi ay tumatanggap; at ang humahanap ay nakakatagpo; at ang tumutuktok ay pinagbubuksan.
Unawain ninyo ito, minamahal kong mga kapatid: ang bawat tao ay dapat na maging mabilis sa pakikinig, marahan sa pagsasalita, mabagal sa pagkagalit;
Pagpuputul-putulin mo ang tupa at huhugasan mo ang mga lamang-loob at ang mga hita, at ipapatong mo sa mga piraso at sa ulo nito.
Samantalang tinatalakay niya ang tungkol sa katuwiran, pagpipigil sa sarili, at sa paghuhukom na darating, nangilabot si Felix at sumagot, “Umalis ka muna ngayon at kapag nagkaroon ako ng pagkakataon ay ipatatawag kita.”
Noon, ang anak na lalaki ng isang babaing Israelita na ang ama'y Ehipcio ay pumunta sa mga anak ni Israel. Nag-away sa kampo ang anak ng babaing Israelita at ang isang Israelita.
Kayo'y humihingi, at hindi tumatanggap, sapagkat humihingi kayo sa masamang dahilan, upang gugulin ninyo ito sa inyong mga kalayawan.
Ginawa ng Panginoon ang ayon sa salita ni Moises; at ang mga palaka ay namatay sa mga bahay, sa mga looban at sa mga kabukiran.
Tumindig ka, itayo mo ang bata at alalayan mo siya ng iyong kamay sapagkat siya'y gagawin kong isang malaking bansa.”
Ang Panginoon ay nagsalita kina Moises at Aaron, na sinasabi,
sa pagputol ng mga batong pang-enggaste, at sa pag-ukit sa kahoy, upang gumawa sa lahat ng mahuhusay na gawa.
At ang iyong iaalay na handog na inumin ay kalahating hin ng alak na handog na pinaraan sa apoy, na mabangong samyo sa Panginoon .
Sa pamamagitan nito ay makikilala ng lahat ng mga tao na kayo ay aking mga alagad, kung kayo'y may pag-ibig sa isa't isa.”
ayon sa nasusulat, “Binigyan sila ng Diyos ng espiritu ng pagkakahimbing, ng mga matang hindi tumitingin, at ng mga taingang hindi nakikinig hanggang sa araw na ito.”
Ginunaw niya ang mga lunsod na iyon, at ang buong libis at ang lahat ng nakatira sa mga lunsod at ang tumutubo sa lupa.
Susuguin ng Anak ng Tao ang kanyang mga anghel, at titipunin nila sa labas ng kanyang kaharian ang lahat ng mga sanhi ng pagkakasala at ang mga gumagawa ng kasamaan;
Sinabi sa kanila ni Jose, “Iyan ang sinabi ko sa inyo, ‘Kayo'y mga espiya!’
“Kung ang kanyang alay ay isang handog na sinusunog mula sa bakahan, mag-aalay siya ng isang lalaking walang kapintasan. Ito ay kanyang dadalhin sa pintuan ng toldang tipanan, upang siya ay tanggapin sa harapan ng Panginoon .
Sapagkat malapit ang Lidda sa Joppa, nang mabalitaan ng mga alagad na si Pedro ay naroroon, nagsugo sila sa kanya ng dalawang tao at ipinakiusap sa kanya, “Pumarito ka sa amin sa lalong madaling panahon.”
Sapagkat ang Panginoon mong Diyos ay lumalakad sa gitna ng iyong kampo upang iligtas ka at ibigay ang iyong mga kaaway sa harapan mo, kaya't ang iyong kampo ay magiging banal upang huwag siyang makakita ng anumang kahiyahiyang bagay sa gitna ninyo at lumayo sa iyo.
Siya'y darating at pupuksain niya ang mga magsasakang ito, at ibibigay ang ubasan sa iba.” At nang marinig nila ito ay sinabi nila, “Huwag nawang mangyari.”
At ang naghandog ng kanyang alay nang unang araw ay si Naashon na anak ni Aminadab sa lipi ni Juda.
Nabuhay si Nahor ng isandaan at labinsiyam na taon pagkatapos na maipanganak si Terah, at nagkaanak pa ng mga lalaki at mga babae.
Muling babalik ang pari sa ikapitong araw at gagawa ng pagsusuri, at kung kumalat na ang salot sa mga dingding ng bahay,
Siya mismo ang nagdala ng ating mga kasalanan sa kanyang katawan sa punungkahoy, upang tayo'y mamatay sa mga kasalanan at mabuhay sa katuwiran; dahil sa kanyang mga sugat ay gumaling kayo.
Ang sumasampalataya at mabautismuhan ay maliligtas; ngunit ang hindi sumasampalataya ay parurusahan.
Ang mga patungan para sa mga haligi ay tanso, ngunit ang mga kawit ng mga haligi at ang mga panali ay pilak; at ang mga balot ng mga itaas ay pilak; at ang lahat ng haligi ng bulwagan ay may taling pilak.
Subalit kung ang pamamaga ay maputi sa balat ng kanyang katawan, at makitang ito ay hindi malalim kaysa balat, at ang balahibo niyon ay hindi pumuti, ibubukod ng pari ang may karamdaman sa loob ng pitong araw.
Ginawa niya iyon at ang lahat ng mga kasangkapan niyon mula sa isang talentong lantay na ginto.
Hindi ba ito ang karpintero, ang anak ni Maria at kapatid nina Santiago, Jose, Judas, at Simon? Hindi ba naritong kasama natin ang kanyang mga kapatid na babae?” At sila'y natisod sa kanya.
ay susuriin nga ng pari ang karamdaman, at kung ang anyo ay mas malalim kaysa balat, at ang buhok doon ay madilaw at manipis, ipahahayag ng pari na siya ay marumi; ito ay pangangati na isang uri ng ketong sa ulo o sa baba.
Ilalagay mo ang luklukan ng awa sa ibabaw ng kaban ng tipan, sa dakong kabanal-banalan.
Kung paano kinakain ang maliit at malaking usa ay gayon mo ito kakainin; ang marumi at ang malinis ay kapwa makakakain niyon.
Hindi siya makikipagtalo, o sisigaw, o maririnig ng sinuman ang kanyang tinig sa mga lansangan.
Nang makita nila ito, ipinaalam nila sa kanila ang mga sinabi tungkol sa sanggol na ito;
Iyong bubuhusan ng langis si Aaron at ang kanyang mga anak, at itatalaga sila, upang sila'y maglingkod sa akin bilang mga pari.
Ang manna ay gaya ng butil ng kulantro at ang kulay niyon ay gaya ng kulay ng bedelio.
Si Jesus ay dinala ng mga dumakip sa kanya kay Caifas, na pinakapunong pari, na kung saan nagkatipon ang mga eskriba at matatanda.
Ang magtagumpay ay magmamana ng mga bagay na ito; at ako'y magiging Diyos niya at siya'y magiging anak ko.
Kayong mga bulag na taga-akay! Sinasala ninyo ang niknik, ngunit nilulunok ninyo ang kamelyo!
at kanilang ginawa ito at ipinadala nila sa matatanda sa pamamagitan ng mga kamay nina Bernabe at Saulo.
“‘Tingnan ninyo ngayon, ako, samakatuwid ay Ako nga, at walang diyos liban sa akin; ako'y pumapatay at ako'y bumubuhay; ako'y sumusugat at ako'y nagpapagaling; at walang makakaligtas sa aking kamay.
Tutuliin ng Panginoon mong Diyos ang iyong puso at ang puso ng iyong binhi, upang ibigin mo ang Panginoon mong Diyos ng buong puso at kaluluwa mo, upang ikaw ay mabuhay.
maging noong tayo'y mga patay sa pamamagitan ng ating mga pagsuway, binuhay niya tayo kay Cristo—sa pamamagitan ng biyaya kayo'y naligtas,
Ang mga Kohatita ay sumulong na dala ang mga banal na bagay at itinayo ng iba ang tabernakulo bago sila dumating.
Subalit mayroon akong ilang bagay na laban sa iyo: sapagkat mayroon ka diyang ilan na sumusunod sa aral ni Balaam, na siyang nagturo kay Balak na maglagay ng katitisuran sa harapan ng mga anak ni Israel, upang kumain sila ng mga bagay na inihandog sa mga diyus-diyosan at upang makiapid.
Ang mga bagay na ito'y sinabi ng kanyang mga magulang sapagkat natatakot sila sa mga Judio. Sapagkat pinagkaisahan na ng mga Judio, na kung ang sinuman ay magpahayag na si Jesus ang Cristo ay palalayasin mula sa sinagoga.
ngunit hindi sila nagwagi, ni wala ng lugar para sa kanila sa langit.
Sinabi ni Moises, “Itinalaga ninyo ang inyong sarili ngayon sa paglilingkod sa Panginoon , bawat isa sa halaga ng kanyang anak na lalaki o kapatid na lalaki, kaya't kayo ay nagdala sa inyo ng pagpapala sa araw na ito.”
at ang malaking lawin, at ang falkon, ayon sa kanilang uri;
At ngayon ay wala na ako sa sanlibutan, subalit ang mga ito ay nasa sanlibutan, at ako'y papariyan sa iyo. Amang Banal, ingatan mo sila sa iyong pangalan, sila na ibinigay mo sa akin, upang sila'y maging isa, na gaya naman natin na iisa.
At kung walang pananampalataya ay hindi maaaring kalugdan ng Diyos, sapagkat ang sinumang lumalapit sa kanya ay dapat sumampalatayang may Diyos at siya ang tagapagbigay-gantimpala sa mga masigasig na humahanap sa kanya.
Huwag nawang pumasok ang aking kaluluwa sa kanilang payo; huwag isama ang aking espiritu sa kanilang kapisanan; Sapagkat sa kanilang galit ay pumatay sila ng tao, at sa kanilang sariling kalooban ay nilumpo nila ang baka.
At sinabi ni Sarai kay Abram, “Mapasaiyo nawa ang kasamaang ginawa sa akin, ibinigay ko ang aking alila sa iyong kandungan; at nang kanyang makita na siya'y naglihi ay hinamak ako sa kanyang paningin. Ang Panginoon ang humatol sa akin at sa iyo.”
Silang lahat ay nagtaka at naguluhang sinasabi sa isa't isa, “Ano ang kahulugan nito?”
Subalit dumating ang Diyos kay Laban na Arameo sa panaginip sa gabi, at sinabi sa kanya, “Ingatan mong huwag kang magsalita kay Jacob ng mabuti o masama man.”
