Sapagkat bagaman sa panahong ito'y dapat na kayo'y mga guro na, kailangang muling may magturo sa inyo ng mga unang simulain ng aral ng Diyos. Kayo'y nangangailangan ng gatas, at hindi ng pagkaing matigas.
ay aalalahanin ko ang aking tipan kay Jacob, at akin ding aalalahanin ang aking tipan kay Isaac, at aalalahanin ko rin ang aking tipan kay Abraham, at aking aalalahanin ang lupain.
upang sa pangalan ni Jesus ay lumuhod ang bawat tuhod, sa langit at sa lupa, at sa ilalim ng lupa,
Subalit kapag ang sambayanan ay magtitipon ay hihihip kayo, ngunit huwag kayong magpapatunog ng hudyat.
O hinahamak mo ang mga kayamanan ng kanyang kabutihan, pagtitiis, at pagtitiyaga na hindi mo nababatid na ang kabutihan ng Diyos ang umaakay sa iyo sa pagsisisi?
Nang makaalis na ang mga sugo ni Juan ay nagpasimula siyang magsalita sa maraming tao tungkol kay Juan. “Ano ang pinuntahan ninyo sa ilang upang makita? Isa bang tambo na inuuga ng hangin?
At nakita ko ang isang bagong langit at ang isang bagong lupa; sapagkat ang unang langit at ang unang lupa ay lumipas na, at ang dagat ay wala na.
sapagkat sa pamamagitan niya nilalang ang lahat ng mga bagay sa langit at sa lupa, ang mga bagay na nakikita at ang mga bagay na hindi nakikita, maging mga trono o mga pagka-panginoon, maging mga pinuno o mga may kapangyarihan—lahat ng mga bagay ay nilalang sa pamamagitan niya at para sa kanya.
Sinabi sa kanya ng Panginoon , “Dalawang bansa ang nasa iyong bahay-bata, at ang dalawang bayan na ipapanganak mo ay magiging hati; ang isa ay magiging higit na malakas kaysa isa, at ang nakatatanda ay maglilingkod sa nakababata.”
Ang mga Levita ay naglinis ng kanilang sarili sa kasalanan, at naglaba ng kanilang mga damit. Sila'y inihandog ni Aaron bilang handog na iwinagayway sa harap ng Panginoon ; at si Aaron ay gumawa ng pagtubos sa kanila upang linisin sila.
Nang bumangon si Jose mula sa pagkakatulog, ginawa niya ang ipinag-utos sa kanya ng anghel ng Panginoon. Siya'y kanyang tinanggap bilang kanyang asawa.
Nang katanghalian, O hari, ay nakita ko sa daan ang isang liwanag mula sa langit na higit na maliwanag kaysa araw, na nagningning sa palibot ko at sa mga naglalakbay na kasama ko.
Baka kapag ikaw ay nakakain at nabusog at nakapagtayo ng magagandang bahay, at nakatira sa mga iyon;
Ayon sa bilang ng mga taon pagkaraan ng pagdiriwang, ay bibili ka sa iyong kapwa, ayon sa bilang ng taon ng mga pananim, ay magbibili siya sa iyo.
Baka magkaroon sa gitna ninyo ng lalaki, o babae, o angkan, o lipi na ang puso'y humiwalay sa araw na ito sa ating Panginoong Diyos , upang maglingkod sa mga diyos ng mga bansang iyon; baka magkaroon sa gitna ninyo ng isang ugat na nakalalason at ng mapait na bunga;
Iginawa niya iyon ng dalawang gintong argolya sa ilalim ng molde, sa dakong itaas ng dalawang panig, sa ibabaw ng dalawang panig, na pagsusuotan ng mga pasanan upang mabuhat.
Naunawaan nga ng mga alagad na si Juan na Tagapagbautismo ang sinasabi niya sa kanila.
Ipinahayag mo sa araw na ito na ang Panginoon ay iyong Diyos, at ikaw ay lalakad sa kanyang mga daan, at iyong gaganapin ang kanyang mga tuntunin at mga utos at mga batas, at iyong papakinggan ang kanyang tinig.
Bakit mo nakikita ang puwing na nasa mata ng iyong kapatid, ngunit hindi mo napupuna ang troso na nasa iyong sariling mata?
Kaya't ang alagad na minamahal ni Jesus ay nagsabi kay Pedro, “Ang Panginoon iyon.” Kaya't nang marinig ni Simon Pedro na iyon ang Panginoon, ay nagbigkis siya ng kanyang tunika (sapagkat siya'y walang damit), at tumalon sa dagat.
Hindi lamang sa inyo ko ginagawa ang tipang ito at ang pangakong ito;
Paanong naririnig natin, ng bawat isa sa atin, ang ating sariling wikang kinagisnan?
Sa ikalawang pagkakataon ay sinabi niya sa kanya, “Simon, anak ni Juan, minamahal mo ba ako?” Sinabi niya sa kanya, “Opo, Panginoon; nalalaman mo na minamahal kita.” Sinabi niya sa kanya, “Alagaan mo ang aking mga tupa.”
At sinabi ni Aaron kay Moises, “Tingnan mo, kanilang inihandog nang araw na ito ang kanilang handog pangkasalanan, at ang kanilang handog na sinusunog sa harapan ng Panginoon ; gayunman ang gayong mga bagay ay nangyari sa akin! Kung ako nga'y nakakain ngayon ng handog para sa kasalanan, ito kaya ay kalugud-lugod sa paningin ng Panginoon ?”
Maaaring sabihin na maging si Levi, na siyang tumatanggap ng mga ikasampung bahagi ay nagbayad ng ikasampung bahagi sa pamamagitan ni Abraham,
“Huwag kang maghahandog sa Panginoon mong Diyos ng baka o tupa na may dungis o anumang kapintasan; sapagkat ito'y karumaldumal sa Panginoon mong Diyos.
Maglalagay ka sa bawat hanay ng dalisay na kamanyang, upang maging handog na tanda para sa tinapay bilang handog na pinaraan sa apoy para sa Panginoon .
Sumagot si Jesus at sinabi, “O lahing walang pananampalataya at napakasama, hanggang kailan ko pa kayo makakasama? Gaano katagal akong magtitiis sa inyo? Dalhin ninyo siya rito.”
Siya'y manganganak ng isang lalaki, at ang pangalang itatawag mo sa kanya ay Jesus, sapagkat ililigtas niya ang kanyang bayan sa kanilang mga kasalanan.”
hanggang sa mapawi ang galit sa iyo ng iyong kapatid at malimutan niya ang ginawa mo sa kanya. Pagkatapos ay magsusugo ako at ipasusundo kita mula roon. Bakit kailangang kapwa kayo mawala sa akin sa isang araw?”
sa kanila ang mga patriyarka, at sa kanila nagmula ang Cristo ayon sa laman, na siyang nangingibabaw sa lahat, Diyos na maluwalhati magpakailanman. Amen.
Inyo ring nakikita at naririnig na hindi lamang sa Efeso, kundi halos sa buong Asia, na ang Pablong ito ay nakaakit at naglayo ng napakaraming tao, na sinasabing hindi mga diyos ang ginagawa ng mga kamay.
Ang tunay na babaing balo at naiwang nag-iisa ay umaasa sa Diyos at nagpapatuloy sa mga pagdaing at mga panalangin gabi't araw;
maliban na ang Espiritu Santo ay nagpapatotoo sa akin sa bawat lunsod, na sinasabing ang mga tanikala at ang kapighatian ay naghihintay sa akin.
o sinumang humipo ng anumang gumagapang na makakapagparumi sa kanya o humipo sa lalaking makakapagparumi sa kanya, sa pamamagitan ng alinman sa kanyang karumihan,
At nakita ko ang isa pang tanda sa langit, dakila at kamanghamangha: pitong anghel na may pitong salot, na siyang mga panghuli, sapagkat sa mga ito'y matatapos ang poot ng Diyos.
Ipapatong niya ang kanyang kamay sa ulo ng kanyang alay, at papatayin ito sa pintuan ng toldang tipanan; at iwiwisik ng mga anak ni Aaron na mga pari ang dugo sa palibot ng dambana.
Nang sila'y dumating kay Reuel na kanilang ama ay sinabi nito, “Bakit napakadali ninyong dumating ngayon?”
Ang ulap ng Panginoon ay nasa itaas nila kapag araw, tuwing sila'y susulong mula sa kampo.
Sinabi sa kanila ni Jesus, “Hindi ba't ito ang dahilan kaya kayo nagkakamali, hindi ninyo nalalaman ang mga kasulatan, o ang kapangyarihan ng Diyos?
Bumalik ang mga kawal sa mga punong pari at sa mga Fariseo, at sinabi ng mga ito sa kanila, “Bakit hindi ninyo siya dinakip?”
maliban sa isang bagay na ito na aking isinigaw habang nakatayo sa gitna nila, ‘Tungkol sa pagkabuhay ng mga patay ako'y nililitis sa harapan mo sa araw na ito.’”
Subalit mabuti ang maging laging masigasig sa mabuting bagay at hindi lamang kapag ako'y kaharap ninyo.
Ngunit kung kanyang pawawalang-bisa ito pagkatapos na kanyang marinig, tataglayin nga niya ang kasamaan ng kanyang asawa.
Kumuha sila ng isang batang toro at ng handog na butil niyon, na mainam na harina na hinaluan ng langis, at kukuha ka ng ibang batang toro na handog pangkasalanan.
Nang magkagayo'y sumagot sina Laban at Betuel at sinabi, “Sa Panginoon ito nagmumula. Kami ay hindi makapagsasabi sa iyo ng masama o ng mabuti.
na sinasabi, ‘Tinugtugan namin kayo ng plauta, ngunit hindi kayo sumayaw; tumangis kami, ngunit hindi kayo nahapis.’
Iniutos sa akin ng Panginoon nang panahong iyon na turuan ko kayo ng mga tuntunin at mga batas upang inyong gawin sa lupaing inyong paroroonan upang angkinin.
Gayundin naman kayong mga lalaki, maging mapagbigay kayo sa inyu-inyong mga asawa sa inyong pagsasama, na binibigyan ng karangalan ang babae bilang isang mas marupok na sisidlan, yamang sila man ay tagapagmana rin ng biyaya ng buhay, upang walang makahadlang sa inyong mga panalangin.
Wala pang umakyat sa langit, maliban sa kanya na bumabang galing sa langit, ang Anak ng Tao.
Kaya't sinabi ni Jose sa Faraon, “Ang panaginip ng Faraon ay iisa; ipinakita ng Diyos sa Faraon ang malapit na niyang gawin.
Sapagkat ang mabuti na aking nais ay hindi ko ginagawa, ngunit ang masama na hindi ko nais ay siya kong ginagawa.
Walang sinumang aakyat na kasama mo, at huwag hayaang may makitang sinuman sa buong bundok; kahit ang mga kawan at ang mga baka ay huwag manginain sa harapan ng bundok na iyon.”
Ipinatong nina Pedro at Juan ang kanilang mga kamay sa kanila at tinanggap nila ang Espiritu Santo.
Ang kamay ng mga saksi ay siyang unang papatay sa kanya at pagkatapos ay ang kamay ng buong bayan. Ganito mo aalisin ang kasamaan sa gitna mo.
Pagkatapos ay inilapit niya ang tupang lalaki na handog na sinusunog, at ipinatong ni Aaron at ng kanyang mga anak ang mga kamay nila sa ulo ng tupa,
Pagkatapos ay sinabi ni Jesus sa mga Judiong sumasampalataya sa kanya, “Kung kayo'y mananatili sa aking salita, tunay ngang kayo'y mga alagad ko.
Ngunit ako'y natatakot na kung paanong si Eva ay dinaya ng ahas sa pamamagitan ng kanyang katusuhan, ang inyong mga pag-iisip ay mailigaw mula sa katapatan at kadalisayan kay Cristo.
Apat na kariton at walong baka ang kanyang ibinigay sa mga anak ni Merari, ayon sa kanilang paglilingkod, sa ilalim ng pamamahala ni Itamar na anak ng paring si Aaron.
Silang lahat ay nagsama-sama sa libis ng Siddim na siyang Dagat na Patay.
Ngunit ang mga babae, mga bata, mga hayop, ang lahat na nasa mga kawal, ang lahat ng nasamsam doon ay kukunin mo bilang samsam; at kakainin mo ang nasamsam mula sa iyong mga kaaway na ibinigay sa iyo ng Panginoon mong Diyos.
Sapagkat ito ang kalooban ng Diyos, ang inyong pagpapakabanal: na kayo'y umiiwas sa pakikiapid;
At huwag mong ililitaw ang kahubaran ng kapatid na babae ng iyong ina, ni ng kapatid na babae ng iyong ama, sapagkat hinubaran niya ang kanyang malapit na kamag-anak; sila ay kapwa mananagot ng kanilang kasamaan.
Siya na nagligtas sa amin mula sa kakilakilabot na kamatayan at patuloy na magliligtas; sa kanya ay inilalagak namin ang ating pag-asa na muli niya kaming ililigtas.
At ang Diyos na nakakaalam ng puso ng tao ay nagpatotoo sa kanila sa pamamagitan ng pagbibigay sa kanila ng Espiritu Santo tulad nang nangyari sa atin;
Alinsunod sa kanyang sariling kalooban, tayo ay ipinanganak niya sa pamamagitan ng salita ng katotohanan, upang tayo'y maging isang uri ng mga unang bunga sa kanyang mga nilalang.
Ngunit sinabi sa kanila ni Pilato, “Bakit, anong kasamaan ang kanyang ginawa?” Subalit sila'y lalong nagsigawan, “Ipako siya sa krus.”
At sinabi niya sa kanya, ‘Dumating ang kapatid mo at pinatay ng iyong ama ang pinatabang guya, dahil sa siya'y tinanggap niyang ligtas at malusog.’
“‘Sumpain ang sumisiping sa kanyang biyenang babae.’ At ang buong bayan ay magsasabi, ‘Amen.’
Sinabi niya, “Ako ang tinig ng isang sumisigaw sa ilang na lugar, ‘Tuwirin ninyo ang daan ng Panginoon, gaya ng sinabi ng propeta Isaias.’”
“Gayunman, walang sinumang magtatalaga ng panganay sa mga hayop. Ito ay panganay para sa Panginoon , maging baka o tupa ay para sa Panginoon .
Kanyang kinuha ang aklat ng tipan, binasa sa pandinig ng bayan, at kanilang sinabi, “Lahat ng sinabi ng Panginoon ay aming gagawin, at kami ay magiging masunurin.”
Mga minamahal, kung tayo'y hindi hinahatulan ng ating puso, tayo ay may kapanatagan sa harapan ng Diyos;
Sinabi niya sa kanyang pagtuturo, “Mag-ingat kayo sa mga eskriba, na ibig magpalakad-lakad na may mahahabang damit, at batiin na may paggalang sa mga pamilihan.
gayundin ang pangalawa;
Nang magkulang ng alak, sinabi ng ina ni Jesus sa kanya, “Wala silang alak.”
Makaraan ang ilang araw, tinipon ng nakababatang anak ang lahat ng kanya, at naglakbay patungo sa isang malayong lupain at doo'y nilustay ang kanyang kabuhayan sa maaksayang pamumuhay.
Ito ang paglilingkod ng mga angkan ng mga anak ni Merari ayon sa lahat ng paglilingkod nila sa toldang tipanan, sa ilalim ng pamamahala ni Itamar na anak ng paring si Aaron.”
Ngayon ay nais kong ipaalala sa inyo, bagama't alam na alam ninyo ang mga bagay na ito, na minsang iniligtas ng Panginoon ang isang bayan mula sa lupain ng Ehipto, pagkatapos ay nilipol niya ang mga hindi sumampalataya.
Sapagkat inihahanda tayo nitong magaan at panandaliang kapighatian para sa walang hanggan at di-masukat na kaluwalhatian,
Sa kanyang anak na si Raquel ay ibinigay ni Laban bilang alilang babae ang kanyang alilang si Bilha.
Pagpuputul-putulin mo ang tupa at huhugasan mo ang mga lamang-loob at ang mga hita, at ipapatong mo sa mga piraso at sa ulo nito.
Nang sila'y makaraan sa una at sa pangalawang bantay, dumating sila sa pintuang-bakal na patungo sa lunsod. Ito'y kusang nabuksan sa kanila, sila'y lumabas at dumaan sa isang lansangan at agad siyang iniwan ng anghel.
Lalo ninyong pabigatin ang gawain ng mga lalaki upang kanilang pagpagalan at huwag nilang pansinin ang mga kabulaanang salita.”
At ang inyong mga anak ay magiging palaboy sa ilang na apatnapung taon, at magdurusa dahil sa kawalan ninyo ng pananampalataya, hanggang sa ang huli sa inyong mga bangkay ay humandusay sa ilang.
Nang dumating ang panahon ay nagsugo siya ng isang alipin sa mga magsasaka upang siya'y bigyan mula sa bunga ng ubasan, subalit binugbog siya ng mga magsasaka, at pinaalis na walang dala.
mga pagkabugbog, mga pagkabilanggo, mga kaguluhan, mga paggawa, mga pagpupuyat, mga pagkagutom,
na nanguna sa inyo sa daan, upang ihanap kayo ng dakong mapagtatayuan ng inyong mga tolda na nasa apoy kapag gabi, at nasa ulap kapag araw, upang ituro sa inyo ang daang dapat ninyong lakaran.
“Ang pangangasiwaan ni Eleazar na anak ng paring si Aaron ay ang langis sa ilaw, ang mabangong insenso, ang patuloy na handog na butil, ang langis na pambuhos, ang pamamahala sa buong tabernakulo at ng lahat na nandoon, ang santuwaryo at ang mga sisidlan niyon.”
Sapagkat ako'y magiging mahabagin sa kanilang mga kasamaan, at ang kanilang mga kasalanan ay hindi ko na aalalahanin pa.”
Kung ang sinuman ay may taingang ipandirinig, hayaan siyang makinig.”
Anumang walang kaliskis at palikpik ay huwag ninyong kakainin; marumi ito para sa inyo.
“Mayroon bang anumang bagay na napakahirap sa Panginoon ? Sa takdang panahon ay babalik ako sa iyo, sa tamang panahon, at si Sara ay magkakaanak ng isang lalaki.”
At si Balaam ay sumama kay Balak at sila'y pumunta sa Kiryat-huzot.
Nagturo siya at sinabi, “Hindi ba nasusulat, ‘Ang aking bahay ay tatawaging bahay-panalanginan para sa lahat ng mga bansa?’ Ngunit ginawa ninyo itong yungib ng mga magnanakaw.”
Ang mga anak ni Israel ay kumain ng manna sa loob ng apatnapung taon, hanggang sa sila'y dumating sa lupaing matitirahan. Sila'y kumain ng manna hanggang sa sila'y dumating sa mga hangganan ng lupain ng Canaan.
At ang dila'y isang apoy. Ang dila na kasama ng ating mga sangkap ay isang sanlibutan ng kasamaan. Dinudungisan nito ang buong katawan, at sinusunog ang pag-inog ng kalikasan, at ito mismo ay sinusunog ng impiyerno.
Kung paano sa mga araw ni Noe, gayundin naman ang pagdating ng Anak ng Tao.
Pumili kayo ng mga lalaking matatalino, may pang-unawa at may karanasan mula sa inyong mga lipi, at sila'y aking itatalaga bilang mga pinuno ninyo.’
Ang panahon na nanirahan ang mga anak ni Israel sa Ehipto ay apatnaraan at tatlumpung taon.
Ngunit pinatayo siya ni Pedro, na sinasabi, “Tumayo ka, ako man ay tao rin.”
Ngunit ang aking matuwid na lingkod ay mabubuhay sa pananampalataya. Ngunit kung siya'y tumalikod, ang aking kaluluwa ay hindi malulugod sa kanya.”
Magsasama kayo ng isang lalaki mula sa bawat lipi; na bawat isa'y pinuno sa sambahayan ng kanyang mga ninuno.
kanela, pampalasa, kamanyang, mira at insenso; alak at langis, at mainam na harina at trigo, mga baka at mga tupa, mga kabayo at mga karwahe, at mga alipin; at ng mga kaluluwa ng mga tao.
sina Obal, Abimael, at Sheba,
Ang pangalan ng ikatlong ilog ay Tigris na siyang umaagos sa silangan ng Asiria. At ang ikaapat na ilog ay ang Eufrates.
Sapagkat ang pagtutuli o ang di-pagtutuli ay walang kabuluhan, kundi ang bagong nilalang.
Ito ay magiging isang patuloy na handog na sinusunog sa buong panahon ng inyong mga salinlahi sa pintuan ng toldang tipanan, sa harapan ng Panginoon ; kung saan ko kayo tatagpuin, upang makipag-usap ako roon sa iyo.
Sapagkat ang mga anak ni Israel ay mga lingkod ko. Sila'y aking mga lingkod na inilabas ko sa lupain ng Ehipto: Ako ang Panginoon ninyong Diyos.
At iyong papag-asawahin ang iyong mga anak na lalaki sa kanilang mga anak na babae, at ang kanilang mga anak na babae na nagpapakasama sa kanilang mga diyos ay pasusunurin ang inyong mga anak na magpakasama sa kanilang mga diyos.
At kung iyong sasabihin sa iyong puso, ‘Paano namin malalaman ang salita na hindi sinabi ng Panginoon ?’
At ipinasiya ni Pilato na ipagkaloob ang kanilang hinihingi.
Ngunit darating ang mga araw na kukunin sa kanila ang lalaking ikakasal at kung magkagayo'y mag-aayuno sila sa araw na iyon.
Sapagkat inihanda ang unang tabernakulo na kinaroroonan ng ilawan, dulang, at ng mga tinapay na handog; ito ay tinatawag na Dakong Banal.
Pumunta sa kanya ang mga mamamayan ng Jerusalem, ang buong Judea, at ang buong lupain sa paligid ng Jordan.
Nang makita ng Panginoon na siya'y pumunta sa kabila upang tumingin ay tinawag siya ng Diyos mula sa gitna ng mababang punungkahoy, “Moises, Moises.” Sumagot siya, “Narito ako.”
Sapagkat ang isang tao'y hindi Judio sa panlabas lamang; ni ang pagtutuli ay hindi panlabas o sa laman.
At sumagot si Jesus, “Tigil! Tama na!” At hinawakan niya ang tainga at pinagaling siya.
Ipinanganak ni Ada si Elifaz kay Esau; at ipinanganak ni Basemat si Reuel;
At sinabi sa kanya ng mga alagad, “Saan tayo kukuha sa ilang na lugar ng sapat na tinapay upang mapakain ang ganito karaming tao?”
At sinabi ni Israel, “Sapat na! Si Jose na aking anak ay buháy pa. Dapat akong pumunta at makita siya bago ako mamatay.”
Sinabi sa kanya ng anghel, “Huwag kang matakot, Maria, sapagkat nakatagpo ka ng paglingap sa Diyos.
Sapagkat may isang tao na ang pangalan ay Demetrio, isang panday-pilak na gumagawa ng mga dambanang pilak ni Artemis, ay nagbibigay ng hindi maliit na pinagkakakitaan sa mga panday.
Sapagkat ang pumasok sa kanyang kapahingahan ay nagpahinga rin sa kanyang mga gawa, gaya ng Diyos sa kanyang mga gawa.
Kapayapaan at kaawaan nawa ang sumakanilang lahat na lumalakad sa alituntuning ito, at maging sa Israel ng Diyos.
At maghari sa inyong puso ang kapayapaan ni Cristo, na doon ay tinawag din naman kayo sa isang katawan. At kayo'y maging mapagpasalamat.
Si Ruben ay sumagot sa kanila, “Hindi ba sinabi ko sa inyo, huwag kayong magkasala laban sa bata; at ayaw kayong makinig? Kaya ngayon ay dumating ang pagtutuos para sa kanyang dugo.”
Samantalang tinatalakay niya ang tungkol sa katuwiran, pagpipigil sa sarili, at sa paghuhukom na darating, nangilabot si Felix at sumagot, “Umalis ka muna ngayon at kapag nagkaroon ako ng pagkakataon ay ipatatawag kita.”
Sinabi sa kanya ng panginoon niya, ‘Magaling! Mabuti at tapat na alipin. Naging tapat ka sa kaunting bagay, pamamahalain kita sa maraming bagay. Pumasok ka sa kagalakan ng iyong panginoon.’
“Ang mga bagay na ito'y sinabi sa inyo upang kayo'y huwag matisod.
Nabuhay si Noe ng tatlong daan at limampung taon pagkaraan ng baha.
Narito ang panawagan para sa pagtitiis ng mga banal, sa mga tumutupad sa mga utos ng Diyos, at humahawak ng matatag sa pananampalataya ni Jesus.
Kung iyong pahihirapan sila sa anumang paraan, at dumaing sa akin, tiyak na aking diringgin ang kanilang daing;
Naghulma siya para doon ng apat na argolyang ginto at inilagay ang mga argolya sa apat na sulok na ukol sa apat na paa niyon.
Ngunit kayo, mga minamahal, alalahanin ninyo ang mga salitang sinabi noong una ng mga apostol ng ating Panginoong Jesu-Cristo,
Bumagsak ang ulan, at dumating ang baha. Humihip ang mga hangin at hinampas ang bahay na iyon, ngunit hindi iyon bumagsak, sapagkat itinayo sa ibabaw ng bato.
Ngunit sumagot si Jesus sa kanya, “Hayaan mong mangyari ito ngayon, sapagkat ganito ang nararapat sa atin upang matupad ang buong katuwiran.” At siya ay sumang-ayon.
at kung ano ang lupain na kanilang tinatahanan, kung mabuti o masama; at kung ano ang mga lunsod na kanilang tinatahanan, kung sa mga kampo o sa mga may pader,
Lumapit din si Lea at ang kanyang mga anak, at nagsiyuko, pagkatapos ay nagsilapit sina Jose at Raquel, at nagsiyuko.
Nagsalita ang Panginoon kay Moises, na sinasabi,
Hinipan ng unang anghel ang kanyang trumpeta at umulan ng yelo at apoy na may halong dugo, at itinapon ang mga ito sa lupa. Ang ikatlong bahagi ng lupa ay nasunog, at ang ikatlong bahagi ng mga punungkahoy ay nasunog, at ang lahat ng luntiang damo ay nasunog.
“Siya'y hindi nagkasala, at walang natagpuang pandaraya sa kanyang bibig.”
Pagkatapos ay dinala nila si Jesus mula kay Caifas hanggang sa palasyo ng gobernador. Noon ay maaga pa at sila'y hindi pumasok sa punong-himpilan, upang hindi marumihan, at upang sila'y makakain ng kordero ng paskuwa.
Muling nakilala ni Adan ang kanyang asawa at siya'y nanganak ng isang lalaki, at tinawag ang kanyang pangalan na Set; sapagkat kanyang sinabi, “Binigyan ako ng Diyos ng ibang anak na kahalili ni Abel, sapagkat siya'y pinatay ni Cain.”
na hindi ka gagawa sa amin ng masama, gaya rin na hindi ka namin ginalaw, at wala kaming ginawa sa iyong di mabuti, at pinaalis ka naming payapa. Ikaw ngayon ang pinagpala ng Panginoon .”
Nang masabi sa hari ng Ehipto na ang taong-bayan ay tumakas, ang puso ng Faraon at ng kanyang mga lingkod ay nagbago tungkol sa taong-bayan, at kanilang sinabi, “Ano itong ating ginawa, na ating hinayaang umalis ang Israel, upang huwag na tayong mapaglingkuran?”
upang kung sa pagtingin ay hindi sila makakita; at sa pakikinig ay hindi sila makaunawa, baka sila'y magbalik-loob at mapatawad.”
“Bukod dito'y nagsalita sa akin ang Panginoon , na sinasabi, ‘Aking nakita ang bayang ito, at aking nakita na ito'y isang bayang matigas ang ulo.
At samantalang sila'y nagsisigawan, na inihahagis ang kanilang mga damit, at nagsasabog ng alikabok sa hangin,
at siya'y may pahintulot mula sa mga punong pari na gapusin ang lahat ng mga tumatawag sa iyong pangalan.”
Inyong wawasakin ang kanilang mga dambana, at sisirain ninyo ang kanilang mga haligi at inyong ibubuwal ang kanilang mga sagradong poste.
Nakita ni Maria Magdalena at ni Mariang ina ni Jose kung saan siya inilagay.
At sa pagpasok niya sa isang nayon, sinalubong siya ng sampung lalaking ketongin, na nakatayo sa malayo.
Nalaman ito ng lahat ng naninirahan sa Efeso, mga Judio at gayundin ng mga Griyego; at sinidlan silang lahat ng takot, at pinuri ang pangalan ng Panginoong Jesus.
at nang makatagpo ng isang mamahaling perlas ay umalis at ipinagbili ang lahat ng kanyang ari-arian at binili iyon.
Nagsimula silang ipagsakdal siya na sinasabi, “Natagpuan namin ang taong ito na inililigaw ang aming bansa, at pinagbabawalan kaming magbuwis kay Cesar, at sinasabi na siya mismo ang Cristo, ang hari.”
Si Pablo, apostol ni Cristo Jesus sa pamamagitan ng kalooban ng Diyos, sa mga banal [na nasa Efeso], at sa mga mananampalataya kay Cristo Jesus:
At paglabas niya nang ikatlong oras, nakita niya ang iba sa pamilihan na nakatayong walang ginagawa.
At ang sinasabi ko sa inyo ay sinasabi ko sa lahat: Maging handa kayo.”
Ang maraming tao na sumunod sa kanya ay patuloy na sumisigaw, “Alisin siya!”
Nang marinig ni Marta na si Jesus ay dumarating, siya ay pumunta at sinalubong siya, samantalang si Maria ay naiwan sa bahay.
Pag-uwi niya sa tahanan, tinatawag niya ang kanyang mga kaibigan at ang kanyang mga kapitbahay na sinasabi sa kanila, ‘Makigalak kayo sa akin, sapagkat natagpuan ko na ang aking tupang nawala.’
Sapagkat ang asawang babae ay itinali ng kautusan sa asawang lalaki habang ito ay nabubuhay; ngunit kung mamatay ang asawang lalaki, siya ay nakalagan na sa kautusan ng asawang lalaki.
Huwag kayong maghahandog ng hindi banal na insenso sa ibabaw niyon, o ng handog na susunugin, o ng handog na butil man at huwag kayong magbubuhos ng handog na inumin sa ibabaw niyon.
“Nang pagputul-putulin ang pitong tinapay para sa apat na libo, ilang kaing na punô ng mga pinagputul-putol ang pinulot ninyo?” Sinabi nila sa kanya, “Pito.”
Itinuon niya ang kanyang pansin sa kanila na umaasang mayroong tatanggapin mula sa kanila.
“Pakinggan mo, O Israel: ang Panginoon nating Diyos ay iisang Panginoon ;
Dumating siya sa Nazaret na kanyang nilakhan. Siya'y pumasok sa sinagoga nang araw ng Sabbath, tulad ng kanyang nakaugalian at tumindig siya upang bumasa,
Si Noe ay isang magbubukid at siyang pinakaunang nagtanim ng ubasan.
Gayundin naman kayo, na sa labas ay mistulang matuwid sa mga tao, ngunit sa loob ay punô kayo ng pagkukunwari at kasamaan.
Ang lahat na naging araw ni Matusalem ay siyamnaraan at animnapu't siyam na taon at siya'y namatay.
sapagkat hindi kayo ang magsasalita, kundi ang Espiritu ng inyong Ama ang magsasalita sa pamamagitan ninyo.
Sinabi niya sa kanila, “Kumuha kayo ngayon, at inyong dalhin sa pinuno ng handaan.” At kanila ngang dinala.
(na sa mga iyon ay hindi karapat-dapat ang sanlibutan). Sila'y nagpalabuy-laboy sa mga ilang, sa mga kabundukan, sa mga yungib, at sa mga lungga sa lupa.
At sa mga ito rin naman si Enoc, na ikapitong salinlahi mula kay Adan, ay nagpahayag na sinasabi, “Narito, dumating ang Panginoon na kasama ang kanyang laksa-laksang mga banal,
Sapagkat si Cristo man ay hindi nagbigay-lugod sa kanyang sarili; kundi gaya ng nasusulat, “Ang mga pag-alipusta ng mga umaalipusta sa iyo ay nahulog sa akin.”
“Kung muling bumalik ang salot, at lumitaw sa bahay pagkatapos na maalis ang mga bato at pagkatapos ipakayod ang bahay, at pagkatapos na mapalitadahan,
Ang lumapastangan sa pangalan ng Panginoon ay tiyak na papatayin; at babatuhin siya ng buong kapulungan; maging dayuhan o katutubo sa lupain ay papatayin kapag nilapastangan ang Pangalan.
Halika, ikaw ay aking susuguin kay Faraon upang iyong ilabas sa Ehipto ang aking bayan, ang mga anak ni Israel.”
At ang mga bagay na ito'y gagawin nila sapagkat hindi nila nakikilala ang Ama o ako man.
at ng dalawang tanikalang lantay na ginto, pinilipit tulad ng lubid; at iyong ikakabit ang nilubid na tanikala sa enggaste.
At naroon ang isang babae na may espiritu ng karamdaman sa loob ng labingwalong taon. Siya ay baluktot at hindi niya kayang tumayo ng talagang matuwid.
At sumagot siya sa kanila, “Humayo kayo at sabihin ninyo kay Juan ang inyong nakikita at naririnig: ang mga bulag ay nakakakita, ang mga pilay ay nakakalakad, ang mga ketongin ay nalilinis, ang mga bingi ay nakakarinig, ang mga patay ay muling binubuhay, sa mga dukha ay ipinangangaral ang magandang balita.
At kanilang ibinigay sa kanya ang handog na sinusunog, na isa-isang putol, at ang ulo at iyon ay sinunog niya sa ibabaw ng dambana.
At sinabi sa kanya ni Jesus, “Kaibigan, gawin mo ang layunin ng pagparito mo.” Pagkatapos ay lumapit sila at kanilang hinawakan si Jesus at siya'y kanilang dinakip.
Umiyak si Jesus.
“Ang isang Amonita o Moabita ay hindi maaaring pumasok sa kapulungan ng Panginoon ; hanggang sa ikasampung salinlahi ay wala sa kanilang maaaring pumasok sa kapulungan ng Panginoon magpakailanman.
Sinabi ni Moises kay Josue, “Pumili ka para sa atin ng mga lalaki, lumabas ka at lumaban kay Amalek. Bukas ay tatayo ako sa taluktok ng burol na hawak ang tungkod ng Diyos sa aking kamay.”
Si Moises ay tumalikod at bumaba sa bundok, dala ang dalawang tapyas ng tipan sa kanyang mga kamay, mga tapyas na may sulat sa magkabilang panig niyon, sa isang panig at sa kabilang panig ay nakasulat ang mga iyon.
Kaya't ang sinumang nakakaalam ng paggawa ng mabuti ngunit hindi ito ginagawa, ito ay kasalanan sa kanya.
At bakit hindi ninyo hatulan para sa inyong sarili kung ano ang matuwid?
“Habang ako'y naglalakbay at papalapit na sa Damasco, nang magtatanghaling-tapat na, biglang sumikat mula sa langit ang isang malaking liwanag sa palibot ko.
Ano nga ang kalamangan ng Judio? O ano ang pakinabang sa pagtutuli?
“Iyong pinatnubayan sa iyong wagas na pag-ibig ang iyong tinubos na bayan, sa iyong kalakasan ay inihatid mo sila sa banal mong tahanan.
At sinabi niya sa kanila, “Kung sang-ayon kayo na ilibing ko ang aking patay upang mawala ito sa aking paningin ay pakinggan ninyo ako, at mamagitan kayo para sa akin kay Efron na anak ni Zohar,
Si Sarai na asawa ni Abram ay hindi nagkaanak sa kanya; at siya'y may isang alilang babae na taga-Ehipto, na ang pangalan ay Hagar.
Sinabi ng Diyos, “Hindi! Ang iyong asawang si Sara ay tiyak na magkakaanak sa iyo, at tatawagin mo siya sa pangalang Isaac. Itatatag ko ang aking tipan sa kanya bilang isang walang hanggang tipan, at sa kanyang lahi pagkamatay niya.
Lumapit sa kanya sina Santiago at Juan na mga anak ni Zebedeo, na nagsasabi sa kanya, “Guro, ibig naming gawin mo sa amin ang anumang aming hingin sa iyo.”
Kung igagawa mo ako ng isang dambanang bato ay huwag mong itatayo ito na may mga tapyas na bato, sapagkat kung iyong gamitin ang iyong patalim doon ay iyong nilapastangan iyon.
Sapagkat marami ang tinawag, ngunit kakaunti ang pinili.”
Baka itingin mo ang iyong mga mata sa langit, at kung iyong makita ang araw, buwan, bituin, at lahat ng hukbo ng sangkalangitan ay matukso ka at iyong sambahin at paglingkuran sila na inilagay ng Panginoon ninyong Diyos sa lahat ng mga bayan na nasa ilalim ng buong langit.
Tama; sa kawalan nila ng pananampalataya ay nabali sila, at sa iyong pananampalataya'y nakatayo ka. Huwag kang magmalaki kundi matakot ka.
Sila'y nagsimulang malungkot at isa-isang nagsabi sa kanya, “Ako ba?”
Pitong araw na ipagdiriwang mo ang pista sa Panginoon mong Diyos sa lugar na pipiliin ng Panginoon , sapagkat pagpapalain ka ng Panginoon mong Diyos sa lahat ng iyong bunga, at sa lahat ng gawa ng iyong mga kamay, at ikaw ay lubos na magagalak.
Narinig ko ang gaya ng isang tinig ng napakaraming tao, gaya ng lagaslas ng maraming tubig, at gaya ng dagundong ng malalakas na kulog na nagsasabi, “Aleluia! Sapagkat naghahari ang Panginoon nating Diyos na Makapangyarihan sa lahat.
Pinalabas silang lahat ni Pedro, at pagkatapos ay lumuhod at nanalangin siya. Bumaling siya sa bangkay at kanyang sinabi, “Tabita, bumangon ka.” Iminulat niya ang kanyang mga mata, at nang makita niya si Pedro ay naupo siya.
Subalit humarap siya at sila'y sinaway. At sila'y pumunta sa ibang nayon.
Sa halip, kapag inaanyayahan ka, pumunta ka at umupo sa pinakamababang lugar upang kung dumating ang nag-anyaya sa iyo, sasabihin niya sa iyo, ‘Kaibigan, pumunta ka sa mas mataas.’ Kung gayo'y magkakaroon ka ng karangalan sa harap ng lahat ng mga kasalo mong nakaupo sa hapag.
Ngunit sinaway sila ng maraming tao upang sila'y tumahimik, ngunit lalo silang nagsisigaw na nagsasabi, “Mahabag ka sa amin Panginoon, Anak ni David!”
Nang umalis na ang anghel na kumausap sa kanya, tinawag niya ang dalawa sa kanyang mga alila at ang isang tapat na kawal mula sa mga naglilingkod sa kanya.
anupa't kayo'y naging halimbawa sa lahat ng mananampalatayang nasa Macedonia at nasa Acaia.
Sinamsam nila ang kanilang buong kayamanan, ang lahat ng kanilang mga anak at mga asawa at lahat na nasa bahay.
Kanyang inaasahan din na siya'y bibigyan ni Pablo ng salapi. Kaya't madalas niyang ipinapatawag si Pablo, at sa kanya'y nakikipag-usap.
At sila'y nagmamadaling pumunta at kanilang natagpuan sina Maria at Jose, at ang sanggol na nakahiga sa sabsaban.
‘At ang bansang aalipin sa kanila ay aking hahatulan,’ sabi ng Diyos. ‘Pagkatapos ng mga bagay na ito ay lalabas sila at sasambahin nila ako sa dakong ito.’
Gayon mo aalisin ang pagkakasala ng dugong walang sala sa gitna mo, kapag gagawin mo ang matuwid sa paningin ng Panginoon .
At ang mga anghel na hindi nag-ingat ng kanilang sariling katungkulan, kundi iniwan ang kanilang sariling tirahan, ay iginapos niya sa mga tanikalang walang hanggan sa pinakamalalim na kadiliman hanggang sa paghuhukom sa dakilang araw.
At kung ito ay nakikita pa sa kasuotang iyon, maging sa paayon, o sa pahalang, o sa alinmang yari sa balat, ito ay sakit na kumakalat; susunugin mo sa apoy ang kinaroroonan ng sakit.
At siya'y may isang kapatid na tinatawag na Maria na naupo sa paanan ng Panginoon at nakinig sa kanyang salita.
Sinabi niya ang mga salitang ito sa kabang-yaman habang nagtuturo siya sa templo. Subalit walang taong humuli sa kanya, sapagkat hindi pa dumating ang kanyang oras.
Sinabi ng pinuno sa kanya, “Ginoo, pumunta ka na bago mamatay ang aking anak.”
Subalit aking isinugo ang mga kapatid upang ang aming pagmamalaki tungkol sa inyo ay huwag mawalan ng kabuluhan sa bagay na ito, upang ayon sa aking sinabi, kayo'y makapaghanda,
Nagpalayas sila ng maraming demonyo, pinahiran ng langis ang maraming maysakit at pinagaling sila.
Ngunit si Festo, sa pagnanais na gawan ng ikalulugod ang mga Judio, ay nagsabi kay Pablo, “Ibig mo bang pumunta sa Jerusalem at doon ka litisin sa mga bagay na ito sa harapan ko?”
Ngunit kung mula roon ay iyong hahanapin ang Panginoon mong Diyos, siya ay iyong matatagpuan kung iyong hahanapin ng buong puso at buong kaluluwa.
Ngunit ang mga bahay sa mga nayon na walang pader sa palibot ay ibibilang na mga bukirin sa lupain. Ito ay matutubos at ito ay mababawi sa panahon ng pagdiriwang.
Sa Damasco, binantayan ng gobernador na sakop ng haring Aretas ang lunsod ng Damasco upang ako'y dakpin,
At sinabi ni Abimelec kay Abraham, “Ano itong pitong babaing kordero na iyong ibinukod?”
sapagkat iyon ay magbubunga ng pagpasan nila ng kasamaan at pagkakasala sa pamamagitan ng pagkain ng kanilang mga banal na bagay; sapagkat ako ang Panginoon na nagpapabanal sa kanila.”
Ang mga pangsipit at ang patungan ay magiging lantay na ginto.
Sapagkat kayong lahat ay pawang mga anak ng liwanag at mga anak ng araw; tayo'y hindi ng gabi ni ng kadiliman man.
Dadaan ako sa lahat mong kawan ngayon, at aking aalisin doon ang lahat ng tupa na batik-batik at may dungis, at ang bawat maitim na tupa, at ang may dungis at batik-batik sa mga kambing, at sila ang aking magiging upa.
Ang napahasik naman sa mabuting lupa, ay iyong nakikinig ng salita at inuunawa ito, na siyang talagang namumunga. Ang isa ay isandaan, ang iba ay animnapu, at ang iba ay tatlumpu.”
Ilagak ninyo sa kanya ang lahat ng inyong kabalisahan, sapagkat siya'y nagmamalasakit sa inyo.
at ang turbanteng yari sa pinong lino, at ang mga gora na yari sa pinong lino, at ang mga salawal na lino na yari sa hinabing pinong lino,
“‘Sumpain ang bumabaluktot ng katarungan para sa dayuhan, sa ulila at sa babaing balo.’ At ang buong bayan ay magsasabi, ‘Amen.’
O hindi ba ninyo nalalaman, mga kapatid (sapagkat ako'y nagsasalita sa mga nakakaalam ng kautusan), na ang kautusan ay umiiral lamang sa tao habang siya'y nabubuhay pa?
Mapalad ang babaing sumampalataya na matutupad ang mga bagay na sinabi sa kanya ng Panginoon.”
Nang matanaw niya si Jesus sa malayo, tumakbo siya at si Jesus ay kanyang sinamba.
Si Moises ay sumagot at nagsabi, “Ngunit hindi nila ako papaniwalaan o papakinggan man sapagkat kanilang sasabihin, ‘Ang Panginoon ay hindi nagpakita sa iyo.’”
“Sapagkat ang kaharian ng langit ay tulad sa isang tao na pinuno ng sambahayan, na maagang lumabas sa umaga upang umupa ng mga manggagawa para sa kanyang ubasan.
Nang makita ng mga tagapag-alaga ang nangyari, tumakbo sila at ibinalita iyon sa lunsod at sa kabukiran.
“Igagawa mo ng isang tabing ang pintuan ng tolda, na telang asul, kulay-ube, at pula, at hinabing pinong lino na ginawa ng mambuburda.
Sa gayunding paraan ay inalipusta siya ng mga tulisan na ipinako sa krus na kasama niya.
Ganito ang mga paglalakbay ng mga anak ni Israel, ayon sa kanilang mga hukbo, nang sila'y sumulong.
Kaya't ang kanyang pananampalataya ay ibinilang na katuwiran sa kanya.
Ang paniniwalang nasa iyo ay taglayin mo sa iyong sarili sa harapan ng Diyos. Mapalad ang hindi humahatol sa kanyang sarili dahil sa bagay na kanyang sinasang-ayunan.
Sabihin mo sa kanila, ‘Sinuman sa lahat ng inyong binhi sa buong panahon ng inyong salinlahi na lumapit sa mga banal na bagay na itinalaga ng mga anak ni Israel sa Panginoon na nasa kalagayang marumi, ang taong iyon ay ititiwalag sa aking harapan: Ako ang Panginoon .
kundi pumunta ka sa bahay ng aking ama at sa aking mga kamag-anak at ikuha mo roon ng asawa ang aking anak.’
Nang siya'y bumalik, pagkatapos matanggap ang kaharian, sinabi niyang tawagin ang mga aliping binigyan niya ng salapi, upang malaman niya kung ano ang kanilang tinubo sa pangangalakal.
sapagkat siya'y mayroong kaisa-isang anak na babae, mga labindalawang taong gulang, at ito'y naghihingalo. Sa kanyang pagpunta, siniksik siya ng maraming tao.
Ito'y sinabi niya upang siya'y subukin sapagkat nalalaman niya sa kanyang sarili kung ano ang gagawin niya.
Ngunit ang mga iba'y nanlilibak na nagsabi, “Sila'y lasing sa bagong alak.”
At aking isinulat ang bagay na ito, upang pagdating ko ay huwag akong magkaroon ng kalungkutan mula doon sa mga nararapat magpagalak sa akin, sapagkat nakakatiyak ako sa inyong lahat na ang aking kagalakan ay magiging kagalakan ninyong lahat.
at tinanong sila, “Ito ba ang inyong anak, na sinasabi ninyong ipinanganak na bulag? Paanong nakakakita na siya ngayon?”
Ngunit mas madali pa para sa langit at lupa na lumipas, kaysa maalis ang isang kudlit sa kautusan.
Huwag uubusin ang bunga ng inyong ubasan, ni huwag ninyong titipunin ang mga nalaglag sa inyong ubasan; iiwan ninyo ang mga iyon para sa mga dukha at sa dayuhan: ako ang Panginoon ninyong Diyos.
Sapagkat tunay na sinasabi ko sa inyo, ang sinumang magpainom sa inyo ng isang tasang tubig dahil sa kayo'y kay Cristo, ay hindi mawawalan ng kanyang gantimpala.
Walang babaing makukunan, o magiging baog man sa iyong lupain; aking lulubusin ang bilang ng iyong mga araw.
Pagkatapos ay sinabi niya, “O huwag sanang magalit ang Panginoon, at ako'y magsasalita. Kung sakaling may matatagpuan doong tatlumpu.” At sinabi niya, “Hindi ko gagawin kung makakatagpo ako roon ng tatlumpu.”
Sa pananampalataya, binasbasan ni Isaac sina Jacob at Esau tungkol sa mga bagay na mangyayari.
“Nahahabag ako sa maraming tao sapagkat tatlong araw ko na silang kasama at walang makain.
At ang Levita, sapagkat siya'y walang bahagi ni pamana na kasama mo, at ang dayuhan, ang ulila, ang babaing balo na nasa loob ng iyong mga bayan ay pupunta roon at kakain at mabubusog, upang pagpalain ka ng Panginoon mong Diyos sa lahat ng gawain na iyong ginagawa.
Nang masaksihan ng buong bayan ang mga kulog at kidlat, ang tunog ng trumpeta at ang bundok na umuusok, ay natakot sila at nanginig, at sila'y tumayo sa malayo.
“At ngayon, nalalaman ko na kayong lahat na aking nilibot na pinapangaralan ng kaharian, ay hindi na muling makikita pa ang aking mukha.
Ngunit siya'y tumahimik at hindi nagsalita ng anuman. Tinanong siyang muli ng pinakapunong pari at sinabi sa kanya, “Ikaw ba ang Cristo, ang Anak ng Pinagpala?”
Ito ang mga hayop na maaari ninyong kainin: ang baka, ang tupa, at ang kambing,
Nang si Esau ay apatnapung taong gulang, siya ay nag-asawa kay Judith na anak ni Beeri na Heteo, at kay Basemat na anak ni Elon na Heteo.
At siya'y nagsalita ng talinghaga, na sinasabi: “Sinong mabubuhay kapag ginawa ito ng Diyos?
“Bilangin mo ang buong kapulungan ng mga anak ni Israel mula sa dalawampung taong gulang pataas ayon sa mga sambahayan ng kanilang mga ninuno, ang lahat sa Israel na may kakayahang makipagdigma.
Kung hindi niya kayang bumili ng kordero, siya ay kukuha ng dalawang batu-bato o ng dalawang batang kalapati, ang isa'y bilang handog na sinusunog at ang isa'y handog pangkasalanan. Ang pari ay gagawa ng pagtubos para sa kanya, at siya'y magiging malinis.”
subalit sa ikalawa ay nag-iisang pumapasok ang pinakapunong pari, minsan sa isang taon, na may dalang dugo bilang handog niya para sa kanyang sarili at sa mga kasalanang nagawa nang di sinasadya ng taong-bayan.
Pagkatapos ng mga bagay na ito, si Jose na taga-Arimatea, na isang lihim na alagad ni Jesus, dahil sa takot sa mga Judio, ay nakiusap kay Pilato na makuha niya ang bangkay ni Jesus, at siya'y pinahintulutan ni Pilato. Kaya't siya'y pumunta roon at kinuha ang kanyang bangkay.
Ang naging tahanan nila ay mula sa Mesha, patungo sa Sefar, na siyang bundok sa silangan.
Sinabi nila sa kanya, “Dadalhin niya ang mga masasamang taong iyon sa kakilakilabot na kamatayan at ang ubasan ay ipagkakatiwala niya sa ibang mga magsasaka na magbibigay sa kanya ng mga bunga sa kanilang kapanahunan.”
“Kung ang sinuman ay nakagawa ng pagsira sa pagtitiwala at nagkasala nang hindi sinasadya sa mga banal na bagay ng Panginoon , magdadala siya sa Panginoon ng handog para sa budhing maysala ng isang tupang lalaki na walang kapintasan mula sa kawan, na ayon sa halagang itinakda ng santuwaryo para sa siklong pilak. Ito ay handog para sa budhing maysala.
upang ang sinumang sumampalataya sa kanya ay magkaroon ng buhay na walang hanggan.
Huwag silang mag-aasawa ng isang babaing upahan o babaing nadungisan, ni mag-aasawa sa isang babaing hiwalay na sa kanyang asawa, sapagkat ang pari ay banal sa kanyang Diyos.
Ang pangangasiwaan ng mga anak ni Merari ay ang mga balangkas ng tabernakulo, ang mga biga, ang mga haligi, ang mga patungan, at ang lahat ng kasangkapan—lahat ng paglilingkod doon na may kinalaman sa mga ito;
At tungkol kay Neftali ay kanyang sinabi, “O Neftali, na busog ng mabuting kalooban, at puspos ng pagpapala ng Panginoon ; angkinin mo ang kanluran at ang timog.”
“Ngunit nang pumasok ang hari upang tingnan ang mga panauhin, may nakita siya roong isang tao na hindi nakadamit pangkasal.
Ang mga tao'y sumamba sa dragon sapagkat ibinigay niya ang kanyang kapangyarihan sa halimaw; at sinamba nila ang halimaw, na sinasabi, “Sino ang katulad ng halimaw at sinong makakalaban dito?”
“At papasok si Aaron sa toldang tipanan at huhubarin ang mga suot na lino na isinuot niya nang siya'y pumasok sa dakong banal at iiwan niya ang mga iyon doon.
Isipin mo ang sinasabi ko, sapagkat bibigyan ka ng Panginoon ng pagkaunawa sa lahat ng mga bagay.
Samantalang sinasabi niya ang mga bagay na ito ay marami ang sumasampalataya sa kanya.
“Mapapalad ang mga inuusig dahil sa katuwiran, sapagkat kanila ang kaharian ng langit.
Ngunit sinabi ng Panginoon kay Moises, “Ang sinumang nagkasala laban sa akin ay siya kong buburahin sa aking aklat.
Binigyan ko siya ng panahon upang makapagsisi; ngunit ayaw niyang magsisi sa kanyang pakikiapid.
Maging sa aking mga aliping lalaki at mga aliping babae, sa mga araw na iyon ay magbubuhos ako mula sa aking Espiritu; at sila'y magsasalita ng propesiya.
At ngayon, Panginoon, tingnan mo ang kanilang mga banta at ipagkaloob mo sa iyong mga alipin na masabi ang iyong salita ng may buong katapangan,
Kung may sinumang pumilit sa iyo na lumakad ka ng isang milya, lumakad ka ng dalawang milya na kasama niya.
Gustung-gusto nila ang mararangal na lugar sa mga handaan at ang mga pangunahing upuan sa mga sinagoga,
Tingnan mo nga ang kabaitan at ang kabagsikan ng Diyos: sa mga nahulog ay kabagsikan, ngunit sa iyo ay ang kabaitan ng Diyos kung mananatili ka sa kanyang kabaitan; kung hindi, ikaw man ay puputulin.
Malalaman ng mga Ehipcio na ako ang Panginoon , kapag ako ay nakakuha na ng karangalan kay Faraon, sa kanyang mga karwahe, at sa kanyang mga mangangabayo.”
Ang pari ay kukuha ng banal na tubig sa isang lalagyang luwad at dadampot ang pari ng alabok na nasa lapag ng tabernakulo at ilalagay sa tubig.
Kung ang kanan mong mata ang sanhi ng iyong pagkakasala, dukitin mo ito at itapon, sapagkat mabuti pang mawalan ka ng isa sa mga bahagi ng iyong katawan kaysa ang buong katawan mo ay mapatapon sa impiyerno.
Ang lalaki ngang si Moises ay napakaamo, higit kaysa lahat ng lalaki sa ibabaw ng lupa.
Kanila namang sinugo sa kanya ang ilang Fariseo at Herodiano, upang siya'y mahuli nila sa pananalita.
Kaya't kunin ninyo sa kanya ang talento, at ibigay ninyo sa kanya na may sampung talento.
Pinarami kayo ng Panginoon ninyong Diyos, at kayo ngayon ay gaya ng mga bituin sa langit sa dami.
inaasahan kong makita ka agad at tayo'y mag-usap nang harapan.
Ako ang tinapay na buháy na bumabang galing sa langit. Kung ang sinuman ay kumain ng tinapay na ito, siya'y mabubuhay magpakailanman, at ang tinapay na aking ibibigay sa ikabubuhay ng sanlibutan ay ang aking laman.”
Sinasabi naman ng iba, “Hindi ito ang mga salita ng isang may demonyo. Kaya ba ng demonyo na magbukas ng mga mata ng bulag?”
At si Crispo, ang pinuno sa sinagoga ay nanampalataya sa Panginoon, kasama ang kanyang buong sambahayan; at marami sa mga taga-Corinto dahil sa pakikinig kay Pablo ay nanampalataya at nabautismuhan.
Nagtayo siya roon ng isang dambana at tinawag niya ang lugar na iyon na El-bethel; sapagkat ang Diyos ay nagpakita sa kanya roon, nang siya'y tumakas mula sa kanyang kapatid.
Si Isacar ay isang malakas na asno, na nahihiga sa gitna ng mga kawan ng mga tupa;
Kung ang taong ito'y hindi galing sa Diyos, siya ay hindi makakagawa ng anuman.”
Ako ba'y naghahangad ngayon ng pagsang-ayon ng mga tao o ng Diyos? O sinisikap ko bang bigyang-lugod ang mga tao? Kung ako'y nagbibigay-lugod pa rin sa mga tao, hindi sana ako naging alipin ni Cristo.
upang dumami ang inyong mga araw at ang mga araw ng inyong mga anak, sa lupain na ipinangako ng Panginoon sa inyong mga ninuno na ibibigay sa kanila, gaya ng mga araw ng langit sa ibabaw ng lupa.
Nang marinig ni Jesus ang mga bagay na ito ay namangha siya sa kanya. Lumingon siya at sinabi sa maraming tao na sumusunod sa kanya, “Sinasabi ko sa inyo, maging sa Israel ay hindi pa ako nakakita ng ganito kalaking pananampalataya.”
at nagsumamo sa kanya, na sinasabi, “Ang aking munting anak na babae ay naghihingalo. Pumaroon ka at ipatong mo ang iyong mga kamay sa kanya upang siya'y gumaling at mabuhay.”
ni hindi rin nila mapapatunayan sa iyo ang mga bagay na ngayo'y kanilang ibinibintang sa akin.
‘Ngayon, tumindig kayo at tumawid sa batis ng Zared.’ At tayo'y tumawid sa batis ng Zared.
“Ang bawat taong may kakayahan sa inyo ay pumarito, at gawin ang lahat ng iniutos ng Panginoon :
Nang siya'y naghahanda na sa kanyang paglalakbay, may isang lalaking patakbong lumapit sa kanya, at pagluhod sa kanyang harapan, siya'y tinanong, “Mabuting Guro, ano ang dapat kong gawin upang magmana ng buhay na walang hanggan?”
Subalit kung naghahanda ka ng piging, anyayahan mo ang mga dukha, ang mga pilay, ang mga lumpo, ang mga bulag,
Kora, Gatam, at Amalek. Ito ang mga pinunong nagmula kay Elifaz sa lupain ng Edom; ito ang mga anak ni Ada.
Sapagkat sa biyaya kayo'y naligtas sa pamamagitan ng pananampalataya, at ito'y hindi sa pamamagitan ng inyong sarili, ito'y kaloob ng Diyos;
Tinanong siya ng mga taong taga-roon tungkol sa kanyang asawa, at sinabi niya, “Siya'y aking kapatid;” sapagkat takot siyang sabihin na, “Siya'y aking asawa.” Inakala niya na “baka ako'y patayin ng mga taong taga-rito, dahil kay Rebecca; dahil sa siya'y may magandang anyo.”
Ngunit ako, mga kapatid, kung ipinangangaral ko pa ang pagtutuli, bakit pa ako inuusig? Kung gayon, ang katitisuran ng krus ay inalis na.
Sinabi niya sa kanila, “Nalalaman ninyo na hindi ipinahihintulot sa isang Judio na makisama o lumapit sa isang banyaga; ngunit ipinakita sa akin ng Diyos, na huwag kong tawagin ang isang tao na marumi o karumaldumal.
Ngayon ay nalalaman nila na ang lahat ng mga bagay na ibinigay mo sa akin ay mula sa iyo;
At ang mga pintuan niyon ay hindi isasara kailanman sa araw; sapagkat hindi magkakaroon doon ng gabi.
Sapagkat dinadala ka ng Panginoon mong Diyos sa isang mabuting lupain, ang lupain ng mga batis ng tubig, ng mga bukal at ng mga kalaliman, na bumubukal sa mga libis at mga bundok,
Si Jetro, na biyenan ni Moises ay kumuha ng handog na sinusunog at mga alay para sa Diyos. Si Aaron ay dumating kasama ang lahat ng matatanda sa Israel upang kumain ng tinapay na kasalo ng biyenan ni Moises sa harap ng Diyos.
At kanyang inutusan sila na mabautismuhan sa pangalan ni Jesu-Cristo. Pagkatapos, siya'y pinakiusapan nilang manatili ng mga ilang araw.
Subalit ipapakita ko sa inyo kung sino ang inyong dapat katakutan; katakutan ninyo siya na pagkatapos pumatay ay may kapangyarihang magtapon sa impiyerno. Oo, sinasabi ko sa inyo, siya ang inyong katakutan.
Sinabi sa kanila ni Jesus, “Katotohanang sinasabi ko sa inyo, bago pa man si Abraham ay Ako Nga.”
At ang apat na nilalang na buháy ay nagsabi, “Amen!” At ang matatanda ay nagpatirapa at sumamba.
Nang tumingin sila sa itaas, wala silang nakitang sinuman, maliban kay Jesus.
Ngunit huwag mong susukatin ang patyo sa labas ng templo; pabayaan mo na iyon, sapagkat ibinigay iyon sa mga bansa at kanilang yuyurakan ang banal na lunsod sa loob ng apatnapu't dalawang buwan.
Nang mag-umaga na, hindi nila napansin ang lupa, ngunit nababanaagan nila ang isang look na may baybayin, at sila'y nagbalak na maisadsad doon ang barko.
Kaya't sinabi sa kanya ni Pilato, “Ayaw mong makipag-usap sa akin? Hindi mo ba alam na ako'y may kapangyarihang ikaw ay pakawalan at may kapangyarihang ikaw ay ipako sa krus?”
“Magsalita ka kay Aaron at sa kanyang mga anak at sa lahat ng mga anak ni Israel, at sabihin mo sa kanila: Ito ang iniutos ng Panginoon :
Kaya't kanyang binasbasan sila nang araw na iyon, na sinasabi, “Sa pamamagitan mo ang Israel ay magpapala, na magsasabi, ‘Gawin ka nawa ng Diyos na gaya ni Efraim at gaya ni Manases.’”
at si Judas Iscariote na siyang nagkanulo sa kanya.
Sinunggaban nilang lahat si Sostenes, ang pinuno sa sinagoga, at siya'y binugbog sa harapan ng hukuman. Ngunit hindi pinansin ni Galio ang mga bagay na ito.
Sinabi ng eunuko kay Felipe, “Ipinapakiusap ko, tungkol kanino sinasabi ito ng propeta, sa kanya bang sarili, o sa iba?”
Sinabi sa kanya ni Jesus, “Bakit tinatawag mo akong mabuti? Walang mabuti kundi ang Diyos lamang.
Sinabi sa kanya ng babae, “Ginoo, nakikita kong ikaw ay isang propeta.
na nakatagpo ng biyaya sa paningin ng Diyos, at huminging makatagpo ng isang tahanang ukol sa Diyos ni Jacob.
At itatayo mo ang tabernakulo ayon sa planong ipinakita sa iyo sa bundok.
Ang Jesus na ito'y muling binuhay ng Diyos, at tungkol dito'y mga saksi kaming lahat.
Hindi kami nagmamalaki nang lampas sa sukat, samakatuwid ay sa pinagpaguran ng iba, subalit ang aming pag-asa ay habang ang inyong pananampalataya ay lumalago, ang aming saklaw sa inyo ay lumawak nawa,
Kanyang inilagay ang dambana ng handog na sinusunog sa pintuan ng toldang tipanan, at nag-alay doon ng handog na sinusunog, at ng handog na harina; gaya ng iniutos ng Panginoon kay Moises.
Manalangin nga kayo nang ganito: Ama naming nasa langit, sambahin nawa ang pangalan mo.
Ngayon, nawa'y sumaating Diyos at Ama ang kaluwalhatian magpakailanman. Amen.
Pinakasalan ng pangalawa ang balo at namatay na walang naiwang anak at gayundin naman ang pangatlo.
Ngunit kanino mo man matagpuan ang iyong mga diyos ay hindi mabubuhay. Sa harapan ng ating mga kamag-anak, ituro mo kung anong iyo na nasa akin, at kunin mo iyon.” Hindi nalalaman ni Jacob na si Raquel ang nagnakaw noon.
At tumayo ang dragon sa buhanginan ng dagat.
Ang langit at ang lupa ay lilipas, ngunit ang aking mga salita ay hindi lilipas.
Ngunit hindi magkakaroon ng dukha sa inyo sapagkat pagpapalain ka ng Panginoon sa lupain na ibinibigay sa iyo ng Panginoon mong Diyos na pinakamana upang iyong angkinin,
Narinig niya ang tungkol kay Jesus, lumapit siya sa karamihan sa likuran niya, at hinipo ang kanyang damit.
Igagawa mo ng mga banal na kasuotan si Aaron na iyong kapatid para sa kaluwalhatian at kagandahan.
Ang Panginoon ay nagsalita kay Moises, na sinasabi,
Tingnan ninyo ang mga barko: bagama't napakalalaki at itinutulak ng malalakas na hangin, gayunma'y napapabaling sa pamamagitan ng isang napakaliit na timon saanman naisin ng piloto.
Ang mga iyon ay susunugin ng pari sa ibabaw ng dambana, isang handog sa Panginoon na pinaraan sa apoy; ito ay handog para sa budhing maysala.
Tinulungan niya ang Israel na kanyang alipin, bilang pag-alaala sa kanyang kahabagan.
Pagkatapos noo'y pumunta si Abimelec sa kanya mula sa Gerar, kasama si Ahuzath na kanyang tagapayo, at si Ficol na kapitan ng kanyang hukbo.
Sinabi sa kanya ni Jesus, “Bakit mo ako tinatawag na mabuti? Walang mabuti kundi ang Diyos lamang.
Aking pagmamatigasin ang puso ng mga Ehipcio upang sundan nila kayo at ako'y magkakaroon ng karangalan kay Faraon at sa buo niyang hukbo, sa kanyang mga karwahe, at sa kanyang mga mangangabayo.
Ang mga hukbo ng langit ay sumusunod sa kanya na mga nakasakay sa mga kabayong puti, at sila'y may damit na pinong lino na maputi at dalisay.
at iniuutos ko sa iyo sa araw na ito na ibigin mo ang Panginoon mong Diyos, lumakad ka sa kanyang mga daan. Tuparin mo ang kanyang mga utos, ang kanyang mga tuntunin, at mga batas upang ikaw ay mabuhay at dumami, at pagpalain ka ng Panginoon mong Diyos sa lupain na iyong pinapasok upang angkinin.
Sinabi niya rito, “Wala nang sinumang makakakain pa ng bunga mula sa iyo.” Ito'y narinig ng kanyang mga alagad.
sapagkat nabalitaan ko ang iyong pag-ibig para sa lahat ng mga banal at ang pananampalataya mo sa Panginoong Jesus.
Tumindig ang buong karamihan at dinala si Jesus sa harap ni Pilato.
“Igalang mo ang iyong ama at ang iyong ina, upang ang iyong mga araw ay humaba sa lupaing ibinibigay sa iyo ng Panginoon mong Diyos.
ang kanilang alak ay kamandag ng mga dragon, at mabagsik na kamandag ng mga ahas.
Minsan ako'y nabubuhay na hiwalay sa kautusan; subalit nang dumating ang utos, ay muling nabuhay ang kasalanan,
Siya nga'y bibigyan mo, at ang iyong puso'y huwag magdamdam kapag binibigyan mo siya; sapagkat dahil sa bagay na ito'y pagpapalain ka ng Panginoon mong Diyos sa lahat ng iyong gawa, at sa lahat ng hipuin ng iyong kamay.
Ngayon, nawa'y mismong ang Panginoon ng kapayapaan ang magbigay sa inyo ng kapayapaan sa lahat ng panahon at sa lahat ng paraan. Ang Panginoon ay sumainyo nawang lahat.
Kayo'y huwag gagawa ng anumang gawa; ito ay isang walang hanggang tuntunin sa buong panahon ng inyong salinlahi sa lahat ng inyong tirahan.
Hubaran mo si Aaron ng kanyang mga kasuotan at isuot mo kay Eleazar na kanyang anak at si Aaron ay ititipon sa kanyang bayan, at doon siya mamamatay.”
Pagkatapos makipag-usap sa kanya, ang Diyos ay pumaitaas na mula kay Abraham.
“Si Aaron ay ititipon sa kanyang bayan. Siya'y hindi papasok sa lupain na aking ibinigay sa mga anak ni Israel, sapagkat kayo'y naghimagsik laban sa aking utos sa tubig ng Meriba.
Kanyang sinaliksik, simula sa panganay hanggang sa bunso, at natagpuan ang kopa sa sako ni Benjamin.
Purihin ang Diyos at Ama ng ating Panginoong Jesu-Cristo, ang Ama ng mga kaawaan at Diyos ng lahat ng kaaliwan;
At isinuot sa kanya ang tunika, binigkisan ng pamigkis, inilagay sa kanya ang balabal, ipinatong ang efod, at ibinigkis sa kanya ang pamigkis na efod na mahusay ang pagkakahabi at itinali ito sa kanya.
Kaya't sinabi sa kanila ng anghel, “Huwag kayong matakot, sapagkat narito, dala ko sa inyo ang magandang balita ng malaking kagalakan para sa buong bayan.
Kung siya'y walang anak na babae, inyong ibibigay ang kanyang mana sa kanyang mga kapatid.
Habang sinasabi niya ang mga bagay na ito sa kanyang pagtatanggol, ay sinabi ni Festo nang may malakas na tinig, “Pablo, ikaw ay baliw; ang labis mong karunungan ay siyang nagpapabaliw sa iyo!”
Tulad ng mga masunuring mga anak, huwag kayong gumaya sa masasamang pagnanasa ng inyong kamangmangan noong una.
Ang mga anak ni Levi: sina Gershon, Kohat, at si Merari.
Ngunit samantalang natutulog ang mga tao, dumating ang kaaway at naghasik ng mga damo sa triguhan, at umalis.
Sinabi ni Jacob sa kanya, “Nalalaman mo kung paano akong naglingkod sa iyo, at kung anong naging kalagayan ng iyong mga hayop nang dahil sa akin.
Ngunit kayo'y wala sa laman, kundi nasa Espiritu, yamang nananatili sa inyo ang Espiritu ng Diyos. Subalit kung ang sinuma'y walang Espiritu ni Cristo, siya'y hindi sa kanya.
“‘Sumpain ang tumatanggap ng suhol upang pumatay ng isang taong walang sala.’ At ang buong bayan ay magsasabi, ‘Amen.’
Baka sabihin ng mga tao sa lupaing pinaglabasan mo sa amin: “Sapagkat hindi sila naipasok ng Panginoon sa lupain na ipinangako sa kanila, at sapagkat napoot siya sa kanila, ay inilabas sila upang patayin sa ilang.”
Si Pablo, na apostol ni Cristo Jesus ayon sa utos ng Diyos na ating Tagapagligtas, at ni Cristo Jesus na ating pag-asa,
“Tingnan mo, inilagay ko sa harapan mo sa araw na ito ang buhay at kabutihan, kamatayan at kasamaan;
Ako'y bumaba upang iligtas sila mula sa kamay ng mga Ehipcio at upang sila'y dalhin sa isang mabuting lupain at malawak, mula sa lupaing iyon, sa isang lupaing dinadaluyan ng gatas at pulot, sa lugar ng mga Cananeo, Heteo, Amoreo, Perezeo, Heveo at Jebuseo.
At sinabi sa kanila ni Jesus, “Hindi ko rin naman sasabihin sa inyo kung sa anong awtoridad ko ginagawa ang mga bagay na ito.”
Isinalaysay niya ang talinghagang ito: “Ang isang tao ay may isang puno ng igos na nakatanim sa kanyang ubasan. Siya'y pumunta upang maghanap ng bunga roon, subalit walang nakita.
Ngunit kapag hinog na ang bunga, agad niyang kinukuha ang karit, sapagkat dumating na ang pag-aani.”
Sapagkat nang sabihin ni Moises ang bawat utos sa buong bayan ayon sa kautusan, kumuha siya ng dugo ng baka at ng mga kambing, na may tubig at mapulang balahibo at isopo, at winisikan niya ang aklat at gayundin ang buong bayan,
Noon, ang mga maniningil ng buwis at mga makasalanan ay lumalapit sa kanya upang makinig.
at ang lahat ng pagpapalang ito ay darating sa iyo at aabot sa iyo, kung iyong susundin ang tinig ng Panginoon mong Diyos.
Kung paanong ang buháy na Ama ay nagsugo sa akin at ako'y nabubuhay dahil sa Ama, gayundin ang kumakain sa akin ay mabubuhay dahil sa akin.
Nang marinig ito ng isa sa nakaupong kasalo niya sa hapag ay sinabi nito sa kanya, “Mapalad ang kakain ng tinapay sa kaharian ng Diyos.”
At kapopootan kayo ng lahat dahil sa aking pangalan. Ngunit ang magtiis hanggang sa wakas ay maliligtas.
Subalit dahil batid ni Jesus ang iniisip ng kanilang puso, kumuha siya ng isang maliit na bata at inilagay sa kanyang tabi.
Subalit sina Nadab at Abihu ay namatay sa harap ng Panginoon nang sila'y maghandog ng kakaibang apoy sa harap ng Panginoon sa ilang ng Sinai, at sila'y walang anak. Kaya't sina Eleazar at Itamar ay nanungkulan bilang mga pari sa harap ni Aaron na kanilang ama.
At ito ay lalo pang naging maliwanag nang lumitaw ang ibang pari, na kagaya ni Melquizedek,
Sapagkat malapit ang Lidda sa Joppa, nang mabalitaan ng mga alagad na si Pedro ay naroroon, nagsugo sila sa kanya ng dalawang tao at ipinakiusap sa kanya, “Pumarito ka sa amin sa lalong madaling panahon.”
Ngunit tungkol sa inyo, bumalik kayo at maglakbay sa ilang sa daang patungo sa Dagat na Pula.’
sapagkat bibigyan ko kayo ng salita at karunungan na hindi malalabanan o matututulan man ng lahat ng sumasalungat sa inyo.
Iniutos sa kanila ni Moises, “Sa katapusan ng bawat pitong taon, sa takdang panahon ng taon ng pagpapalaya, sa Pista ng mga Tolda,
Sinabi ng Panginoon kay Moises, “Sabihin mo ang ganito sa mga pari na mga anak ni Aaron: Hindi dapat dungisan ng sinuman ang kanyang sarili nang dahil sa patay na kasama ng kanyang bayan,
Nang magkagayo'y lihim nilang sinulsulan ang ilang lalaki, na nagsasabi, “Narinig naming nagsasalita siya ng mga salitang kalapastanganan laban kay Moises at sa Diyos.”
Kaya't aking hinawakan ang dalawang tapyas at inihagis ng aking dalawang kamay, at winasak ang mga ito sa harapan ng inyong paningin.
“Kapag inyong ginagapas ang anihin sa inyong lupain, huwag ninyong gagapasan ang inyong bukid hanggang sa mga sulok nito, ni huwag ninyong titipunin ang mga nalaglag sa inyong ginapasan.
Kaya't naglagay sila ng mga tagapangasiwa upang pahirapan sila sa kanilang mga sapilitang paggawa. Kanilang ipinagtayo si Faraon ng mga lunsod imbakan, ang Pitom at Rameses.
Nanalangin si Isaac sa Panginoon para sa kanyang asawa, sapagkat siya'y baog; at dininig ng Panginoon ang kanyang panalangin at si Rebecca na kanyang asawa ay naglihi.
Kung ang isang babae ay lumapit sa alinmang hayop at nakipagtalik dito, papatayin mo ang babae at ang hayop; sila'y tiyak na papatayin at ang kanilang dugo ay nasa kanila.
Manirahan nawang sagana sa inyo ang salita ni Cristo ayon sa lahat ng karunungan; magturo at magpaalalahanan kayo sa isa't isa sa pamamagitan ng mga salmo at ng mga himno at mga awiting espirituwal, na umaawit na may pasasalamat sa Diyos sa inyong mga puso.
Huwag kayong lalabas sa pintuan ng toldang tipanan sa loob ng pitong araw, hanggang sa maganap ang mga araw ng inyong pagtatalaga. Kailangan ang pitong araw upang maitalaga kayo;
Kayong mga bulag na taga-akay! Sinasala ninyo ang niknik, ngunit nilulunok ninyo ang kamelyo!
Pagkatapos ay kukuha ang pari sa pamamagitan ng kanyang daliri ng kaunting dugo mula sa handog pangkasalanan at ilalagay sa ibabaw ng mga sungay ng dambana ng handog na sinusunog, at ang nalabi sa dugo'y ibubuhos sa paanan ng dambana ng handog na sinusunog.
Sapagkat batid ninyo kung anong mga tagubilin ang ibinigay namin sa inyo sa pamamagitan ng Panginoong Jesus.
Ako'y tumanggap ng utos na magbigay ng pagpapala: kanyang pinagpala, at hindi ko na mababago iyon.
Dumating ang mga alagad ni Juan, kinuha ang bangkay at inilibing ito. Pagkatapos, sila'y umalis at ibinalita kay Jesus.
Sumainyo nawa ang biyaya at kapayapaang mula sa Diyos Ama at sa Panginoong Jesu-Cristo.
Ngunit sinasabi ko sa inyo, higit pang mapagtitiisan sa araw ng paghuhukom ang Tiro at Sidon kaysa inyo.
Iyo ngang sasabihin sa iyong anak, ‘Kami ay naging mga alipin ng Faraon sa Ehipto, at inilabas kami ng Panginoon sa Ehipto sa pamamagitan ng makapangyarihang kamay.
Hindi na ako karapat-dapat na tawaging anak mo. Ituring mo ako na isa sa iyong mga upahang lingkod.”’
Huwag ninyong kakainin ang kanilang laman at huwag ninyong hihipuin ang kanilang mga bangkay; ang mga iyon ay marumi para sa inyo.
ang ibang bahagi ng Gilead, at ang buong Basan na kaharian ni Og, ang buong lupain ng Argob, ay aking ibinigay sa kalahating lipi ni Manases. (Ang buong Basan ay tinatawag na lupain ng mga Refaim.
At sinabi niya sa kanya, ‘Magaling, mabuting alipin. Sapagkat naging tapat ka sa kakaunti, mamahala ka sa sampung lunsod.’
Madalas ko silang pinarurusahan sa lahat ng mga sinagoga at pinipilit ko silang manlapastangan; at sa nag-aalab na pagkagalit sa kanila ay pinag-uusig ko sila maging sa mga lunsod sa ibang lupain.
na may kaluwalhatian ng Diyos, ang kanyang ningning ay katulad ng isang totoong mahalagang bato, na gaya ng batong jaspe, na malinaw na gaya ng kristal.
At ang bunga sa Sabbath ng lupain ay magiging pagkain mo, at ng iyong aliping lalaki at aliping babae, ng iyong upahang lingkod, ng mga dayuhang naninirahang kasama mo;
Pinabalik ng Panginoon ang isang napakalakas na hanging habagat na siyang tumangay sa mga balang, at itinaboy ang mga ito sa Dagat na Pula; walang natira kahit isang balang sa buong nasasakupan ng Ehipto.
Subalit alalahanin mo ako kapag ikaw ay napabuti na, at hinihiling ko sa iyo na gumawa ka ng mabuti sa akin, at banggitin mo ako sa Faraon, at ako'y ilabas mo sa bahay na ito.
Kinabukasan, nakita ni Juan si Jesus na lumalapit sa kanya, at kanyang sinabi, “Narito ang Kordero ng Diyos, na nag-aalis ng kasalanan ng sanlibutan!
At si Pedro na puspos ng Espiritu Santo ay sumagot sa kanila, “Kayong mga pinuno ng bayan at matatanda,
Magkakaroon ng pitong taong kasaganaan sa buong lupain ng Ehipto.
At sinimulan niyang isalaysay sa taong-bayan ang talinghagang ito: “Isang tao ang nagtanim ng ubasan. Ipinagkatiwala niya ito sa mga magsasaka, at pumunta sa ibang lupain nang mahabang panahon.
At tungkol kay Jose ay kanyang sinabi, “Pagpalain nawa ng Panginoon ang kanyang lupain, sa pinakamabuti mula sa langit, sa hamog, at sa kalaliman na nasa ilalim,
Mula sa langit ay ipinarinig niya sa iyo ang kanyang tinig, upang kanyang turuan ka. Sa ibabaw ng lupa ay kanyang ipinakita sa iyo ang kanyang dakilang apoy, at iyong narinig ang kanyang mga salita sa gitna ng apoy.
At tinaga ng isa sa kanila ang alipin ng pinakapunong pari at tinagpas ang kanang tainga nito.
Ang bawat natakot sa salita ng Panginoon sa mga lingkod ni Faraon ay nagpauwi ng kanyang mga alipin at ng kanyang hayop sa mga bahay;
Nagsalita ang Panginoon kay Moises, na sinasabi:
Sinabi ng tao, “Umalis na sila dito, sapagkat narinig kong sinabi nila, ‘Tayo na sa Dotan.’” Sinundan ni Jose ang kanyang mga kapatid, at natagpuan niya sila sa Dotan.
at sinabi sa kanya, “Ikaw ba iyong darating o maghihintay kami ng iba?”
At kanyang isinulat sa mga tapyas ang ayon sa unang nasulat, ang sampung utos na sinabi ng Panginoon sa inyo sa bundok mula sa gitna ng apoy nang araw ng pagtitipon; at ang mga iyon ay ibinigay sa akin ng Panginoon .
At sinabi niya sa kanila, “Humayo kayo at inyong sabihin sa asong-gubat na iyon, ‘Narito, nagpapalayas ako ng mga demonyo at nagpapagaling ngayon at bukas, at sa ikatlong araw ay matatapos ko ang aking gawain.
“Pakinggan mo kami, panginoon ko. Ikaw ay isang makapangyarihang prinsipe sa gitna namin. Ilibing mo ang iyong patay sa pinakamabuti sa aming mga libingan. Walang sinuman sa amin ang magkakait sa iyo ng kanyang libingan upang paglibingan ng iyong patay.”
Mayroon ba sa mga pinuno, o sa mga Fariseo na sumasampalataya sa kanya?
Dinala nila sa kanya ang isang bingi at may kapansanan sa pagsasalita, at siya'y pinakiusapan nila na ipatong ang kanyang kamay sa kanya.
Kaya't ipag-utos mo na bantayan ang libingan hanggang sa ikatlong araw, baka pumaroon ang kanyang mga alagad at siya'y nakawin, at sabihin sa mga tao, ‘Siya'y bumangon mula sa mga patay,’ at magiging masahol pa ang huling pandaraya kaysa una.”
At kanyang sinabi, “Hindi ba't tumpak na ang pangalan niya ay Jacob? Dalawang ulit niya akong inagawan. Kinuha niya ang aking pagkapanganay at ngayo'y kinuha ang basbas sa akin.” At kanyang sinabi, “Wala ka bang inilaang basbas para sa akin?”
Nabalitaan ng kanyang mga kapitbahay at mga kamag-anak na nagpakita ang Panginoon ng dakilang awa sa kanya at sila'y nakigalak sa kanya.
Nang makita niya na ito'y ikinasiya ng mga Judio, kanya namang isinunod na dakpin si Pedro. Ito ay nang panahon ng pista ng Tinapay na Walang Pampaalsa.
kasama niya si Onesimo, tapat at minamahal na kapatid, na siya'y isa sa inyo. Sila ang magbabalita sa inyo tungkol sa lahat ng mga bagay na nangyayari dito.
At tinanong siya ni Pilato, “Ikaw ba ang Hari ng mga Judio?” Sumagot siya at sinabi, “Ikaw ang nagsasabi.”
Kaya kayo'y tumulad sa Diyos, gaya ng mga anak na minamahal,
At may isang dalubhasa sa kautusan ang tumindig upang si Jesus ay subukin na nagsasabi, “Guro, anong dapat kong gawin upang magmana ng buhay na walang hanggan?”
At sumagot ang anghel sa kanya, “Bababa sa iyo ang Espiritu Santo at lililiman ka ng kapangyarihan ng Kataas-taasan. Kaya't ang batang banal ay tatawaging Anak ng Diyos.
Sinabi sa kanya ni Simon Pedro, “Panginoon, saan ka pupunta?” Sumagot si Jesus, “Sa pupuntahan ko ay hindi ka makakasunod sa akin ngayon; ngunit pagkatapos ay makakasunod ka.”
Sapagkat sa kanilang buong paglalakbay ang ulap ng Panginoon ay nasa ibabaw ng tabernakulo sa araw, at may apoy sa loob niyon sa gabi, sa paningin ng buong sambahayan ng Israel.
“Sino sa inyo, na mayroong aliping nag-aararo o nag-aalaga ng mga tupa ang magsasabi sa kanya pagkagaling sa bukid, ‘Pumarito ka agad at maupo sa hapag ng pagkain.’
Sinabi niya sa kanya, “Tiyakin mong wala kang sasabihin kaninuman kundi pumunta ka at magpakita sa pari at maghandog ka para sa pagkalinis sa iyo ayon sa ipinag-utos ni Moises bilang isang patotoo sa kanila.”
Kanyang inilagay sa ibabaw ng pambalikat ng efod upang maging mga batong pang-alaala para sa mga anak ni Israel; gaya ng iniutos ng Panginoon kay Moises.
Ito'y magiging pinong alabok sa buong lupain ng Ehipto, at magiging pigsang susugat sa tao, at sa hayop sa buong lupain ng Ehipto.”
“Sinabi ko sa inyo ang mga bagay na ito sa paraang patalinghaga. Darating ang oras, na hindi na ako magsasalita sa inyo nang patalinghaga, kundi maliwanag na sa inyo'y sasabihin ko ang tungkol sa Ama.
Di ba nasa harapan mo ang buong lupain? Humiwalay ka sa akin. Kapag kinuha mo ang nasa kaliwa, ako ay pupunta sa kanan; o kapag kinuha mo ang nasa kanan, ako ay pupunta sa kaliwa.”
Siya'y bumalik kay Balak na nakatayo sa tabi ng kanyang handog na sinusunog kasama ang lahat ng mga pinuno ng Moab.
O kung humingi siya ng isda ay bibigyan niya ito ng ahas?
At ang lahat, ang hamak at ang dakila, ang mayayaman at ang mga dukha, ang mga malaya at ang mga alipin ay pinalagyan nito ng isang tanda sa kanilang kanang kamay o sa noo,
Nagpatuloy si Abram ng kanyang paglalakbay mula sa Negeb hanggang sa Bethel, hanggang sa dakong kinaroroonan ng kanyang tolda sa pagitan ng Bethel at ng Ai;
At si Judas na sa kanya'y nagkanulo, ay sumagot at nagsabi, “Hindi ako iyon, Rabi?” Sinabi niya sa kanya, “Ikaw ang nagsabi.”
“‘Sumpain ang sumisiping sa asawa ng kanyang ama, sapagkat kanyang inililitaw ang balabal ng kanyang ama.’ At ang buong bayan ay magsasabi, ‘Amen.’
Huwag ninyong pahihirapan ang sinumang babaing balo, o batang ulila.
Kung gaano siya nagmalaki at namuhay sa kalayawan, ay gayundin ang ibigay ninyo sa kanyang pahirap at pagluluksa. Sapagkat sinasabi niya sa kanyang puso, ‘Ako'y nakaupong isang reyna. Hindi ako balo at hindi ko makikita kailanman ang pagluluksa.’
at mapalaya silang lahat na dahil sa takot sa kamatayan sa buong buhay nila ay nasa ilalim ng pagkaalipin.
Lumapit siya kay Simon Pedro na nagtanong sa kanya, “Panginoon, huhugasan mo ba ang aking mga paa?”
Sinabi nila sa kanya, ‘Sapagkat walang umuupa sa amin.’ Sinabi niya sa kanila, ‘Pumunta rin kayo sa ubasan.’
At nagpatirapa si Abram, at sinabi ng Diyos sa kanya,
Sapagkat ang kamatayan na ikinamatay niya ay kanyang ikinamatay sa kasalanan nang minsanan; ngunit ang buhay na kanyang ikinabubuhay ay kanyang ikinabubuhay sa Diyos.
Ngunit mayroon ka pang ilan sa Sardis na hindi dinungisan ang kanilang mga damit; at sila'y kasama kong lalakad na nakaputi, sapagkat sila'y karapat-dapat.
Nang makita ni Balaam na ikinatuwa ng Panginoon na pagpalain ang Israel, hindi siya pumunta na gaya nang una, upang maghanap ng tanda, kundi kanyang iniharap ang kanyang mukha sa dakong ilang.
Ang sinumang nagkakaila sa Anak, ay hindi sumasakanya ang Ama. Ang nagpapahayag sa Anak ay sumasakanya rin ang Ama.
Nang magawa nila ito, nakahuli sila ng napakaraming isda, at halos masira ang kanilang mga lambat,
Alam natin na tayo'y sa Diyos at ang buong sanlibutan ay nasa ilalim ng kapangyarihan ng masama.
Subalit kapag ang ulap ay hindi napapaitaas ay hindi sila naglalakbay hanggang sa araw na iyon ay pumaitaas.
“Huwag kayong gagawa ng kalikuan sa paghatol; huwag kang magtatangi sa pagkatao ng dukha ni itatangi ang pagkatao ng makapangyarihan, kundi hahatulan mo ang iyong kapwa ayon sa katarungan.
Magiging mapalad ka sa iyong pagpasok at magiging mapalad ka sa iyong paglabas.
At sa kanya'y sinabi, “Huwag mong sasaktan ang bata, o gawan man siya ng anuman, sapagkat ngayon ay nalalaman ko na ikaw ay may takot sa Diyos, at hindi mo ipinagkait sa akin ang iyong anak, ang iyong kaisa-isang anak.”
Nang makain na nila ang mga iyon ay walang makapagsasabi na kinain nila ang mga iyon sapagkat ang kanilang anyo ay pangit ding gaya ng una. At nagising ako.
“Kukuha ka ng piling harina, at sa pamamagitan nito ay magluluto ka ng labindalawang tinapay; dalawang ikasampung bahagi ng efa ang sa bawat tinapay.
At ito ang batas tungkol sa kanyang pagiging marumi dahil sa kanyang tulo. Maging ang kanyang katawan ay may tulo, o huminto na ang tulo sa kanyang katawan, ito ay karumihan sa kanya.
Yamang gumagawa kaming kasama niya, nananawagan din kami sa inyo na huwag ninyong tanggapin ang biyaya ng Diyos nang walang kabuluhan.
Ako'y pumihit at bumaba mula sa bundok, at aking isinilid ang mga tapyas sa kaban na aking ginawa, at ang mga iyon ay naroroon, na gaya ng iniutos sa akin ng Panginoon .
Inalala ng Diyos si Raquel, at pinakinggan siya at binuksan ang kanyang bahay-bata.
Pagkatapos ng mga bagay na ito, sinabi kay Jose, “Ang iyong ama ay may sakit.” Kaya't isinama niya ang kanyang dalawang anak, sina Manases at Efraim.
Ang umupo sa anumang bagay na inupuan ng may tulo ay maglalaba ng kanyang mga damit, at maliligo siya sa tubig, at magiging marumi hanggang sa paglubog ng araw.
Kaya't hindi kalooban ng inyong Ama na nasa langit na ang isa sa maliliit na ito ay mapahamak.
“Gagawa ka ng isang tabing na asul at kulay-ube, at pula at hinabing pinong lino; na may mga kerubin na mahusay na ginawa.
Dahil dito, sapagkat narinig ko rin naman ang inyong pananampalataya sa Panginoong Jesus, at ang inyong pag-ibig sa lahat ng mga banal,
Sumasakanila ang kamay ng Panginoon at ang napakalaking bilang na sumampalataya ay nagbalik-loob sa Panginoon.
At buhat sa langit ay nagpaulan ang Panginoon sa Sodoma at Gomorra ng asupre at apoy.
At huwag kayong makibahagi sa mga gawa ng kadiliman na walang ibubunga, kundi inyong ilantad ang mga ito.
Sapagkat tayo'y mayroong isang Pinakapunong Pari na marunong makiramay sa ating mga kahinaan, isa na tinukso sa lahat ng mga paraan gaya rin naman natin, gayunma'y walang kasalanan.
Nang titigan ko iyon ay nakita ko ang mga hayop sa lupa na may apat na paa at mga hayop na mababangis at mga hayop na gumagapang at mga ibon sa himpapawid.
Kaya't marami sa mga Judio na sumama kay Maria at nakakita ng ginawa niya ang sumampalataya sa kanya.
At nang makita ni Jesus na dumarating na sama-samang tumatakbo ang maraming tao, sinaway niya ang masamang espiritu, na sinasabi, “Ikaw na pipi at binging espiritu, iniuutos ko sa iyo, lumabas ka sa kanya at huwag ka nang papasok muli sa kanya.”
At sinabi niya, “Bakit, anong kasamaan ang ginawa niya?” Ngunit lalo silang nagsigawan, na nagsasabi, “Ipako siya sa krus!”
Sapagkat ang kautusan ay gumagawa ng galit; ngunit kung saan walang kautusan ay wala ring paglabag.
At nakita ko sa kanang kamay ng nakaupo sa trono ang isang aklat na may sulat sa loob at sa likod, na tinatakan ng pitong tatak.
Kaya't ang Anak ng Tao ay Panginoon maging ng Sabbath.”
Ngunit ang mga barko ay manggagaling sa baybayin ng Kittim at kanilang pahihirapan ang Ashur at Eber, at siya man ay pupuksain.”
Ngunit ang aking lingkod na si Caleb, sapagkat siya'y nagtaglay ng ibang espiritu at sumunod nang lubos sa akin, ay dadalhin ko sa lupain na kanyang pinaroonan; at aariin ng kanyang mga binhi.
Ngunit nang marinig ito ng mga Fariseo ay sinabi nila, “Ang taong ito'y nagpapalayas ng mga demonyo sa pamamagitan lamang ni Beelzebul na pinuno ng mga demonyo.”
Samakatuwid ay upang kapwa tayo mapalakas sa pamamagitan ng pananampalataya ng isa't isa, na ito'y sa inyo at sa akin.
Huwag ninyong hayaan na agawan kayo ng gantimpala sa pamamagitan ng kusang pagpapakababa at pagsamba sa mga anghel, na pinanghahawakan ang mga bagay na kanyang nakita, na nagyayabang nang walang dahilan sa pamamagitan ng kanyang makalamang pag-iisip,
At sinabi ng Diyos kay Abraham, “Tungkol kay Sarai na iyong asawa, huwag siyang tatawaging Sarai, kundi Sara ang magiging pangalan niya.
Sinabi ni Jesus sa kanila, “Tatanungin ko kayo ng isang tanong. Sagutin ninyo ako at sasabihin ko sa inyo kung sa anong awtoridad ko ginagawa ang mga bagay na ito.
Itinaas niya ang kanyang paningin at nakita ang tatlong lalaki na nakatayo na malapit sa kanya. Nang sila'y kanyang makita, tumakbo siya upang sila'y salubungin mula sa pintuan ng tolda, at yumuko siya sa lupa.
May ilang panahon na siya'y tumatanggi, subalit pagkatapos ay sinabi sa kanyang sarili, ‘Bagaman ako'y hindi natatakot sa Diyos, at hindi gumagalang sa tao,
“‘Ni huwag kang magnanakaw.
“Hindi ba't mahigpit naming ipinagbawal sa inyo na huwag kayong magturo sa pangalang ito, ngunit tingnan ninyo, pinuno ninyo ang Jerusalem ng inyong aral, at ibig pa ninyong iparatang sa amin ang dugo ng taong ito!”
Pagkatapos, sinabi ng Panginoon kay Moises, “Sabihin mo kay Aaron; ‘Iunat mo ang iyong tungkod, at hampasin mo ang alabok ng lupa, upang ito ay maging mga kuto sa buong lupain ng Ehipto.’”
At si Satanas ay dudurugin ng Diyos ng kapayapaan sa madaling panahon sa ilalim ng inyong mga paa. Ang biyaya nawa ng ating Panginoong Jesu-Cristo ay sumainyo.
At ang nahulog sa mabuting lupa ay sila na pagkatapos marinig ang salita, ay iningatan ito sa isang tapat at mabuting puso at nagbubunga na may pagtitiyaga.
Kaya't sila'y lumusong mula sa bundok ng Panginoon ng tatlong araw na paglalakbay; at ang kaban ng tipan ng Panginoon ay nasa unahan nila sa loob ng tatlong araw nilang paglalakbay, upang ihanap sila ng dakong kanilang mapagpapahingahan.
Samantalang naaantala pa ang lalaking ikakasal ay inantok silang lahat at nakatulog.
Mula noon si Jesus ay nagpasimulang mangaral na nagsasabi, “Magsisi kayo, sapagkat malapit na ang kaharian ng langit.”
Dumating ang mga Fariseo at upang subukin siya ay kanilang itinanong, “Ipinahihintulot ba sa lalaki na makipaghiwalay sa kanyang asawa?”
Mula sa limampung taong gulang ay titigil sila sa katungkulan sa paglilingkod at hindi na sila maglilingkod.
At lahat ng damit at balat na kinaroroonan ng binhi ay lalabhan sa tubig, at magiging marumi hanggang paglubog ng araw.
Hindi mabagal ang Panginoon tungkol sa kanyang pangako, na gaya ng kabagalang itinuturing ng iba, kundi matiyaga sa inyo, na hindi niya ibig na sinuman ay mapahamak, kundi ang lahat ay dumating sa pagsisisi.
Nang ang ulap ay lumayo sa tolda, si Miriam ay naging ketongin na kasimputi ng niyebe. Tiningnan ni Aaron si Miriam, at nakita na ito'y ketongin.
“Ito ang batas tungkol sa alay na mga handog pangkapayapaan na ihahandog sa Panginoon .
Ipahayag mo ang mga bagay na ito. Mangaral ka at sumaway na may buong kapamahalaan. Huwag mong hayaang hamakin ka ng sinuman.
Mula nang panahon na si Jose ay pamahalain sa kanyang bahay at sa lahat ng kanyang pag-aari, pinagpala ng Panginoon ang bahay ng taga-Ehipto. Ang pagpapala ng Panginoon ay dumating sa lahat ng kanyang pag-aari, sa bahay at sa parang.
Kaya't nang ipasundo ako, sumama ako nang walang pagtutol. Ngayon, itinatanong ko kung bakit mo ako ipinasundo.”
Ang Panginoon ay nagsalita sa inyo mula sa gitna ng apoy. Narinig ninyo ang tunog ng mga salita, ngunit wala kayong anyong nakita; tanging tinig lamang.
Kaya't ang mga anak ni Israel ay mangingilin ng Sabbath, na iingatan ang Sabbath sa buong panahon ng kanilang mga salinlahi, bilang isang palagiang tipan.
Huwag kayong magdadala ng lalagyan ng salapi, o supot, o mga sandalyas, at huwag ninyong batiin ang sinuman sa daan.
Kaya't siya'y nagmadali, bumaba, at natutuwa siyang tinanggap.
Sumagot si Laban kay Jacob, “Ang mga anak na babae ay aking mga anak at ang mga anak ay mga anak ko, at ang mga kawan ay aking mga kawan at ang lahat ng iyong nakikita ay akin. Subalit anong magagawa ko ngayon sa mga anak kong babae, o sa kanilang mga anak na ipinanganak nila?
Ano sa palagay mo, alin sa tatlong ito, ang naging kapwa tao sa nahulog sa kamay ng mga tulisan?”
“Kung sa kabila nito ay hindi ninyo ako susundin, kundi kayo'y sasalungat sa akin;
At lima sa inyo'y hahabol sa isandaan, at isandaan sa inyo'y hahabol sa sampung libo; at ang inyong mga kaaway ay mabubuwal sa harapan ninyo sa pamamagitan ng tabak.
Pagkatapos ay aalis siya sa iyo, siya at ang kanyang mga anak, at babalik siya sa kanyang sariling sambahayan, at babalik sa pag-aari ng kanyang mga magulang.
Huwag kayong makipamatok sa mga hindi mananampalataya, sapagkat anong pagsasama mayroon ang katuwiran at kasamaan? O anong pagsasama mayroon ang liwanag sa kadiliman?
At kami ay patuloy na nagpapasalamat sa Diyos, na nang inyong tanggapin ang salita ng Diyos na inyong narinig sa amin ay inyong tinanggap iyon hindi bilang salita ng mga tao, kundi, ayon sa katotohanan, ay bilang salita ng Diyos, na gumagawa naman sa inyo na sumasampalataya.
Kung kayo'y humingi ng anuman sa pangalan ko ay gagawin ko.
Kaya't kung paanong sa pamamagitan ng isang tao ay pumasok ang kasalanan sa sanlibutan, at sa pamamagitan ng kasalanan ay ang kamatayan, kaya't dumating sa lahat ng mga tao ang kamatayan, sapagkat ang lahat ay nagkasala;
“At ngayon, O Israel, ano ba ang hinihingi sa iyo ng Panginoon mong Diyos? Kundi matakot ka sa Panginoon mong Diyos, lumakad ka sa lahat ng kanyang mga daan, at ibigin mo siya, at paglingkuran mo ang Panginoon mong Diyos ng buong puso at ng buong kaluluwa mo,
At ang mga alagad ay napuspos ng kagalakan at ng Espiritu Santo.
Siya'y tinanong ni Jacob, “Hinihiling ko sa iyo na sabihin mo sa akin ang iyong pangalan.” At kanyang sinabi, “Bakit itinatanong mo ang aking pangalan?” At siya'y binasbasan doon.
upang kayo'y huwag maging mga tamad, kundi mga taga-tulad kayo sa kanila na sa pamamagitan ng pananampalataya at ng pagtitiis ay nagmamana ng mga pangako.
Kaagad nilang iniwan ang kanilang mga lambat at sumunod sa kanya.
Mula sa nalabing langis na nasa kanyang kamay ay maglalagay ang pari ng dugo sa dulo ng kanang tainga, sa hinlalaki ng kanang kamay, at sa hinlalaki ng kanang paa ng taong lilinisin, sa ibabaw ng dugo ng handog para sa budhing maysala.
Pinapakiusapan kitang manatili sa Efeso gaya noong patungo ako sa Macedonia, na iyong atasan ang ilang tao na huwag magturo ng ibang aral,
Ito ang mga angkan ng mga anak ni Efraim ayon sa nabilang sa kanila, tatlumpu't dalawang libo at limang daan. Ito ang mga anak ni Jose, ayon sa kanilang mga angkan.
“Sabihin mo kay Aaron, ‘Kapag sinindihan mo ang mga ilaw ay magbibigay liwanag ang pitong ilaw sa harap ng ilawan.’”
na nagsasabi, “Kahabag-habag, kahabag-habag ang dakilang lunsod, siyang nagsusuot ng pinong lino at ng kulay-ube, at pula, at napapalamutian ng ginto, mahahalagang bato at perlas!
Siya yaong aking sinasabi, ‘Kasunod ko'y dumarating ang isang lalaki na higit pa sa akin, sapagkat siya'y nauna sa akin.
Nang siya ay makita ng mga punong pari at ng mga punong-kawal, sila'y nagsigawan, “Ipako siya sa krus, ipako siya sa krus!” Sinabi sa kanila ni Pilato, “Kunin ninyo siya, at ipako ninyo siya sa krus, sapagkat ako'y walang nakitang kasalanan sa kanya.”
Hayaang ang babae'y matuto sa katahimikan na may buong pagpapasakop.
Nagtanim si Abraham ng isang punungkahoy ng tamarisko sa Beer-seba, at doon ay tinawag niya ang pangalan ng Panginoon , ang Walang Hanggang Diyos.
At ginawa ni Noe ang ayon sa lahat ng iniutos sa kanya ng Panginoon .
Nang kanyang mabatid ito, pumunta siya sa bahay ni Maria, ang ina ni Juan na tinatawag na Marcos, na kinaroroonan ng maraming nagkakatipon at nananalangin.
At kumalat ang balitang ito sa buong lupaing iyon.
Kaya't pumayag siya at humanap ng tamang pagkakataon upang kanyang maipagkanulo siya sa kanila na hindi kaharap ang maraming tao.
Ito ang paglilingkod ng mga angkan ng mga Gershonita sa toldang tipanan at ang gawain nila ay nasa ilalim ng pamamahala ni Itamar na anak ng paring si Aaron.
Nang masabi ni Jesus ang mga bagay na ito, siya'y nabagabag sa espiritu, at nagpatotoo, “Katotohanang sinasabi ko sa inyo, ako'y ipagkakanulo ng isa sa inyo.”
ay pipili kayo ng mga lunsod na magiging lunsod-kanlungan para sa inyo, upang ang nakamatay ng sinumang tao nang hindi sinasadya ay makatakas patungo doon.
Samantalang siya'y nakaupo sa bundok ng mga Olibo sa tapat ng templo, tinanong siya nang lihim nina Pedro, Santiago, Juan, at Andres,
Kaya't sa loob ng isang araw ay darating ang mga salot sa kanya, kamatayan, pagluluksa at gutom; at siya'y lubos na susunugin sa apoy; sapagkat makapangyarihan ang Panginoong Diyos na humatol sa kanya.”
Nang magkagayo'y nagpatuloy si Jacob sa kanyang paglalakbay, at nagtungo sa lupain ng mga tao sa silangan.
Ang mga iyon ay marumi para sa inyo; huwag ninyong kakainin ang laman ng mga iyan, at ang bangkay ng mga iyan ay inyong pandidirihan.
Kanyang pinapunta sila sa Bethlehem at sinabi sa kanila, “Humayo kayo at hanapin ninyong mabuti ang sanggol; kapag siya ay inyong natagpuan na, ipagbigay-alam ninyo sa akin, upang ako rin ay makaparoon at siya ay aking sambahin.”
Ano sa palagay ninyo?” Sumagot sila at sinabi, “Karapat-dapat siya sa kamatayan.”
At iniutos ng Panginoon sa amin na gawin ang lahat ng mga tuntuning ito, na matakot sa Panginoon nating Diyos, sa ikabubuti natin magpakailanman, upang ingatan niya tayong buháy, gaya sa araw na ito.
At tinanong siya ni Jesus, “Anong pangalan mo?” At sinabi niya, “Lehiyon;” sapagkat maraming demonyo ang pumasok sa kanya.
At ito ang kahatulan, na naparito ang ilaw sa sanlibutan, at inibig pa ng mga tao ang kadiliman kaysa ilaw sapagkat ang kanilang mga gawa ay masasama.
na nag-aabang sa kanya upang hulihin siya sa kanyang sasabihin.
Huwag kang mag-aararo na may isang baka at isang asno ang magkatuwang.
pinag-uusig, subalit hindi pinababayaan; inilulugmok, subalit hindi napupuksa;
Kinuha ni Jesus ang mga tinapay at nang makapagpasalamat ay ipinamahagi niya sa mga nakaupo. Binigyan din sila ng mga isda hanggang gusto nila.
ngunit sa mga araw na hipan ng ikapitong anghel ang kanyang trumpeta, magaganap ang hiwaga ng Diyos, ayon sa kanyang ipinahayag sa kanyang mga lingkod na propeta.”
“Kaya, anumang bagay na ibig ninyong gawin sa inyo ng mga tao, gayon ang gawin ninyo sa kanila; sapagkat ito ang kautusan at ang mga propeta.
Ang kumakain ng aking laman at umiinom ng aking dugo ay nananatili sa akin, at ako'y sa kanya.
Sa simula ay kasama na siya ng Diyos.
Sapagkat ang bawat nilalang ng Diyos ay mabuti at walang anumang dapat tanggihan, kung tinatanggap ito na may pagpapasalamat;
At sinabi ni Moises kina Aaron, Eleazar, at Itamar na kanyang mga anak, “Huwag ninyong ilugay ang buhok ng inyong ulo, o punitin man ninyo ang inyong mga damit upang huwag kayong mamatay at nang siya'y huwag magalit laban sa buong kapulungan. Tungkol sa inyong mga kapatid, ang buong sambahayan ni Israel, sila ay tataghoy sa apoy na pinapag-alab ng Panginoon .
At kanyang tinawag siya, at sa kanya'y sinabi, ‘Ano itong nababalitaan ko tungkol sa iyo? Magbigay-sulit ka ng ipinagkatiwala sa iyo, sapagkat hindi ka na maaaring maging katiwala pa.’
Noon ay inaalagaan ni Moises ang kawan ni Jetro na kanyang biyenan na pari sa Midian; kanyang pinatnubayan ang kawan sa kabila ng ilang at nakarating sa bundok ng Diyos, sa Horeb.
Ang puso ng Faraon ay nagmatigas at hindi niya pinayagang umalis ang bayan ng Israel; gaya ng sinabi ng Panginoon sa pamamagitan ni Moises.
Ang buong Israel na nasa palibot nila ay tumakas sa sigawan nila; sapagkat kanilang sinabi, “Baka pati tayo'y lamunin ng lupa!”
na nagsasabi, ‘Nagsimula ang taong ito na magtayo, at hindi na kayang tapusin.’
Nang marinig ng alipin ni Abraham ang kanilang mga salita, siya ay nagpatirapa sa lupa sa harap ng Panginoon .
At isinalaysay ni Jesus sa kanila ang isang talinghaga kung paanong sila'y dapat laging manalangin at huwag manlupaypay.
Ang magiging pinuno sa sambahayan ng mga ninuno ng mga angkan ng mga Kohatita ay si Elisafan na anak ni Uziel.
Maraming ilaw sa silid sa itaas na pinagtipunan namin.
Kapag ang kampo ay susulong na, papasok si Aaron sa loob at ang kanyang mga anak, at kanilang ibababa ang lambong ng tabing, at kanilang tatakpan niyon ang kaban ng patotoo.
Kanilang nilagyan ito ng apat na hanay na mga bato: isang hanay sa sardio, topacio, at karbungko na siyang unang hanay.
Sinabi sa kanya ni Jesus, “Kung ibig mong maging ganap, humayo ka, ipagbili mo ang iyong mga ari-arian at ibigay mo sa mga dukha, at magkakaroon ka ng kayamanan sa langit; pagkatapos ay pumarito ka, at sumunod ka sa akin.”
at isusulat mo nang malinaw sa mga batong iyon ang lahat ng mga salita ng kautusang ito.”
Tulad sila sa mga batang nakaupo sa pamilihan at sumisigaw sa isa't isa, na sinasabi, ‘Tinutugtugan namin kayo ng plauta at hindi kayo sumayaw; tumangis kami at hindi kayo umiyak.’
lalung-lalo na sa mga nagpapasasa sa kanilang laman sa pagnanasa, at hinahamak ang maykapangyarihan. Sila'y pangahas, matitigas ang ulo, at hindi natatakot na alipustain ang mga maluwalhati,
At paglampas nila sa Misia ay nagtungo sila sa Troas.
Sapagkat nalalaman natin na ang buong sangnilikha ay sama-samang dumaraing at naghihirap sa pagdaramdam hanggang ngayon.
Sinabi ni Moises kay Faraon, “Pakisabi mo sa akin kung kailan ako makikiusap para sa iyo, sa iyong mga lingkod, at sa iyong bayan upang ang mga palaka ay maalis mula sa iyo at sa inyong mga bahay, at manatili na lamang sa Nilo.”
Ngunit kayo'y pinahiran ng Banal, at nalalaman ninyo ang lahat ng mga bagay.
Sila'y mapupugnaw sa gutom, at lalamunin ng maningas na init, at ng nakalalasong salot; at ang mga ngipin ng mga hayop ay isusugo ko sa kanila, pati ng kamandag ng gumagapang sa alabok.
Kaya't ang pangalan ng dakong iyon ay tinawag na Tabera, sapagkat ang apoy ng Panginoon ay nagningas laban sa kanila.
Ang mga Fariseo at mga eskriba ay nagbulung-bulungan, na nagsasabi, “Tinatanggap ng taong ito ang mga makasalanan at kumakaing kasalo nila.”
At sinabi niya, “Tinupad ko ang lahat ng mga bagay na ito buhat pa sa aking pagkabata.”
“Ang nag-iisang saksi ay hindi mangingibabaw laban sa isang tao sa anumang kasamaan o kasalanang kanyang nagawa; sa patotoo ng dalawa o tatlong saksi ay pagtitibayin ang usapin.
Sinabi ng Panginoon sa kanya, “Bumaba ka, at ikaw ay umakyat kasama si Aaron, ngunit ang mga pari at ang taong-bayan ay huwag mong palampasin sa mga hangganan upang umakyat sa Panginoon , baka siya ay hindi makapagpigil sa kanila.”
Sinabi ni Jesus sa kanila, “Mga anak, mayroon ba kayong nahuling isda?” Sumagot sila sa kanya, “Wala.”
At agad siyang dinala ng Espiritu sa ilang.
Nang ikatlong araw ay tumingin si Abraham at kanyang natanaw ang lugar na iyon sa malayo.
Kanilang siniyasat kung anong pagkatao o kapanahunan na tinutukoy ng Espiritu ni Cristo na sumasakanila, nang ipahayag ang mangyayaring pagdurusa ni Cristo, at ang kaluwalhatiang susunod sa mga ito.
Dito nahayag ang pag-ibig ng Diyos sa atin, sapagkat sinugo ng Diyos ang kanyang bugtong na Anak sa sanlibutan upang tayo'y mabuhay sa pamamagitan niya.
Lumabas din sa marami ang mga demonyo na nagsisisigaw, “Ikaw ang Anak ng Diyos!” Subalit kanyang sinaway sila, at hindi sila pinahintulutang magsalita, sapagkat alam nilang siya ang Cristo.
At iaalay mo ang iyong mga handog na sinusunog, ang laman at ang dugo, sa ibabaw ng dambana ng Panginoon mong Diyos, at ang dugo ng iyong mga alay ay ibubuhos sa ibabaw ng dambana ng Panginoon mong Diyos; at iyong kakainin ang karne.
Sa pamamagitan nito, itinuturo ng Espiritu Santo na hindi pa naihahayag ang daan patungo sa santuwaryo, habang nakatayo pa ang unang tabernakulo.
Nang sila'y mailabas na nila, ay sinabi nila, “Tumakas ka alang-alang sa iyong buhay. Huwag kang lumingon o huminto man sa buong libis; tumakas ka hanggang sa bundok, sapagkat kung hindi, ikaw ay mamamatay.”
Si Erasto ay nanatili sa Corinto, ngunit si Trofimo ay iniwan kong maysakit sa Mileto.
At sila'y dumating sa lugar na sinabi sa kanya ng Diyos. Nagtayo roon si Abraham ng isang dambana, inayos ang kahoy, at tinalian si Isaac na kanyang anak at inilagay sa ibabaw ng kahoy na nasa ibabaw ng dambana.
Gaya ng nasusulat, “Ang nagtipon ng marami ay hindi nagkaroon ng labis, at ang nagtipon ng kaunti ay hindi kinulang.”
Ihahandog ng pari ang isa na handog pangkasalanan at ang isa'y handog na sinusunog at itutubos sa kanya, sapagkat siya'y nagkasala dahil sa bangkay, at itatalaga niya ang kanyang ulo sa araw ding iyon.
Subalit inaalipusta ng mga ito ang anumang bagay na hindi nila nauunawaan, at sa pamamagitan ng mga bagay na likas nilang nalalaman, kagaya ng mga hayop na walang pag-iisip, sila'y winawasak.
Ang bahaging nalalabi sa mga tabing ng tolda, na siyang kalahati ng tabing na nalalabi ay ilalaylay sa likuran ng tabernakulo.
Sa pinakauna sa inyong masang harina ay magbibigay kayo sa Panginoon ng isang handog sa buong panahon ng inyong mga salinlahi.
Sila'y maglilingkod para sa iyo at para sa buong tolda. Huwag lamang silang lalapit sa mga kasangkapan ng santuwaryo, ni sa dambana, upang hindi sila mamatay, maging kayo man.
[Sinabi ni Jesus, “Ama, patawarin mo sila, sapagkat hindi nila nalalaman ang kanilang ginagawa.”] At sila ay nagpalabunutan upang paghatian ang kanyang damit.
Sapagkat ito ang dahilan kung bakit ako sumulat, upang aking masubok kayo at malaman kung kayo'y masunurin sa lahat ng mga bagay.
Si Jetro, na biyenan ni Moises ay dumating na kasama ang kanyang mga anak at ang kanyang asawa kay Moises sa ilang kung saan siya humimpil sa bundok ng Diyos.
Samantalang naguguluhan si Pedro sa kanyang sarili, kung ano ang kahulugan ng pangitaing kanyang nakita, biglang dumating ang mga taong sinugo ni Cornelio. Nang maipagtanong ang bahay ni Simon, tumayo sila sa harapan ng pintuan.
Kaya't lumayo sila sa tolda nina Kora, Datan at Abiram. Sina Datan at Abiram ay lumabas at tumayo sa pintuan ng kanilang mga tolda kasama ng kanilang mga asawa, mga anak, at mga bata.
upang bigyan ng pagkakaiba ang marumi at ang malinis, at ang may buhay na maaaring kainin at ang may buhay na hindi maaaring kainin.
Tumayo si Jesus at sumunod sa kanya, kasama ang kanyang mga alagad.
Sapagkat ang sinumang nagnanais iligtas ang kanyang buhay ay mawawalan nito at ang sinumang mawalan ng kanyang buhay dahil sa akin at sa ebanghelyo ay maililigtas iyon.
Tinawag niya ang maraming tao pati ang kanyang mga alagad, at sa kanila'y sinabi, “Kung ang sinuman ay nagnanais sumunod sa akin, siya ay tumanggi sa kanyang sarili, pasanin ang kanyang krus at sumunod sa akin.
Sinabi sa kanya ni Jesus, “Nakikita mo ba ang malalaking gusaling ito? Walang matitira ditong isa mang bato sa ibabaw ng kapwa bato na hindi ibabagsak.”
“Gayundin, sa ikalabinlimang araw ng ikapitong buwan, kapag inyong tinipon ang bunga ng lupain, ipagdiriwang ninyo ang mga kapistahan ng Panginoon sa loob ng pitong araw; ang una at ikawalong araw ay Sabbath.
At ipinako sa krus na kasama niya ang dalawang tulisan; isa sa kanan, at isa sa kanyang kaliwa.
at sinabi niya kay Kora at sa kanyang buong pangkat, “Sa kinaumagahan ay ipapakita ng Panginoon kung sino ang kanya, at kung sino ang banal, at kung sino ang palalapitin niya sa kanya. Samakatuwid, ang piliin niya ay siyang kanyang palalapitin sa kanya.
“Ito ang iyong gagawin sa kanila upang italaga sila, at makapaglingkod sa akin bilang mga pari. Kumuha ka ng isang guyang toro at ng dalawang lalaking tupa na walang kapintasan,
na ipinanganak hindi sa dugo, o sa kalooban ng laman, o sa kalooban ng tao, kundi ng Diyos.
at upang makilala ang pag-ibig ni Cristo na higit sa kaalaman upang kayo'y mapuno ng lahat ng kapuspusan ng Diyos.
Umalis sila at kanilang natagpuan ang batang asno na nakatali sa pintuan sa labas ng lansangan. At kinalagan nila ito.
Kakainin mo ang mga ito sa harapan ng Panginoon mong Diyos sa dakong pipiliin ng Panginoon mong Diyos, ikaw at ng iyong anak na lalaki at babae, at ng iyong mga aliping lalaki at babae, at ng Levita na nasa loob ng iyong mga bayan; at ikaw ay magagalak sa lahat ng iyong gagawin sa harapan ng Panginoon mong Diyos.
Tapat ang sa inyo'y tumatawag, na gagawa rin naman nito.
Sapagkat nanganganib tayong maparatangang nanggugulo sa araw na ito, palibhasa'y wala tayong maibibigay na dahilan upang bigyang-katuwiran ang gulong ito.”
Kinabukasan, sinabi ng panganay sa bunso, “Tingnan mo, ako'y sumiping kagabi sa aking ama. Painumin din natin siya ng alak sa gabing ito. Pumasok ka at sumiping sa kanya upang mapanatili natin ang binhi ng ating ama.”
Nang makita ng mga katutubo ang hayop na nakabitin sa kanyang kamay, ay sinabi sa isa't isa, “Tiyak na mamamatay-tao ang taong ito. Kahit siya'y nakatakas sa dagat, gayunma'y hindi hinayaan ng Katarungan na siya'y mabuhay.”
Tinatawagan ko ang langit at ang lupa bilang saksi laban sa inyo sa araw na ito, na aking inilagay sa harapan mo ang buhay at kamatayan, ang pagpapala at sumpa. Kaya't piliin mo at ng iyong binhi ang buhay upang ikaw ay mabuhay.
Sasabihin mo nga, “Ang mga sanga ay nabali upang ako ay maisanib.”
“Sapagkat nasusulat sa aklat ng Mga Awit, ‘Hayaang mawalan ng tao ang kanyang tahanan, at huwag bayaang tumira doon ang sinuman;’ at, ‘Hayaang kunin ng iba ang kanyang katungkulan.’
Subalit dumarating ang oras at ngayon na nga, na sasambahin ng mga tunay na sumasamba ang Ama sa espiritu at katotohanan, sapagkat hinahanap ng Ama ang gayong mga sumasamba sa kanya.
Subalit isang araw, nang siya'y pumasok sa bahay upang gawin ang kanyang gawain at walang sinumang tao sa bahay,
Gaya ng nasusulat, “Siya'y nagsabog, siya'y nagbigay sa mga dukha; ang kanyang katuwiran ay nananatili magpakailanman.”
At siya'y gumawa ng mga bigang kahoy na akasya; lima sa mga tabla ng isang panig ng tabernakulo,
Ngunit pinatigas ng Panginoon ang puso ng Faraon at hindi niya dininig sila gaya ng sinabi ng Panginoon kay Moises.
na aming nalalaman na ang bumuhay sa Panginoong Jesus ay siya ring bubuhay sa amin na kasama ni Jesus, at dadalhin kaming kasama ninyo sa kanyang harapan.
Ang mga anak nina Gad at Ruben ay sumagot, “Kung ano ang sinabi ng Panginoon sa iyong mga lingkod ay gayon ang gagawin namin.
At ang mga anak ni Levi na tumanggap ng katungkulang pari ay mayroong utos ayon sa kautusan na maglikom ng ikasampung bahagi mula sa taong-bayan, samakatuwid ay sa kanilang mga kapatid, bagaman ang mga ito ay mga nagmula sa balakang ni Abraham.
kung gayon sa araw na kanyang itakda na ibigay ang kanyang mga ari-arian bilang pamana sa kanyang mga anak, siya ay hindi pinahihintulutang gawing panganay ang anak ng minamahal na higit sa anak ng kinapopootan na siyang panganay.
Paglapit sa amin, kinuha niya ang sinturon ni Pablo, at ginapos niya ang kanyang sariling mga paa't kamay, at sinabi, “Ganito ang sinasabi ng Espiritu Santo, ‘Ganito gagapusin ng mga Judio sa Jerusalem ang lalaking may-ari ng sinturong ito, at siya'y kanilang ibibigay sa mga kamay ng mga Hentil.’”
Sapagkat kung noon ngang tayo'y mga kaaway, ay pinakipagkasundo tayo sa Diyos sa pamamagitan ng kamatayan ng kanyang Anak, lalo ngayong ipinagkasundo na, ay maliligtas tayo sa pamamagitan ng kanyang buhay.
O ang labingwalo na nabagsakan ng tore sa Siloam at sila'y napatay, inaakala ba ninyo na sila'y higit na maysala kaysa lahat ng taong naninirahan sa Jerusalem?
Sapagkat ang mga dukha ay laging nasa inyo; ngunit ako'y hindi laging nasa inyo.”
Nang sila'y malapit na sa nayong kanilang paroroonan, nauna siya na parang magpapatuloy pa.
Susumpain ka sa iyong pagpasok at susumpain ka sa iyong paglabas.
Pagkatapos ay umalis ang mga Fariseo at pinag-uusapan nila kung paano siyang mabibitag sa kanyang pananalita.
Marami sa bilang ang dating mga pari, sapagkat sila'y hinadlangan ng kamatayan upang makapagpatuloy sa panunungkulan.
at inyong pinansin ang may suot ng damit na maganda, at sinabi, “Maupo ka rito,” at sa dukha ay inyong sinabi, “Tumayo ka riyan,” o “Maupo ka sa ibaba ng tuntungan ng aking mga paa,”
At walang salita niya na nananatili sa inyo sapagkat hindi kayo sumasampalataya sa kanyang sinugo.
At hindi lamang iyon; kundi gayundin kay Rebecca nang siya'y naglihi sa pamamagitan ng isang lalaki, na si Isaac na ating ama.
Ang mga punong pari naman at ang buong Sanhedrin ay naghahanap ng patotoo laban kay Jesus upang siya'y ipapatay; ngunit wala silang matagpuan,
Kanyang hinagkan ang lahat niyang mga kapatid, at umiyak sa kanila; at pagkatapos ay nakipag-usap sa kanya ang kanyang mga kapatid.
Nagkaanak si Eber ng dalawang lalaki; ang pangalan ng una'y Peleg; sapagkat sa mga araw niya'y nahati ang lupa; at ang pangalan ng kanyang kapatid ay Joktan.
Sinabi sa kanya ni Jesus, “Siya'y nakita mo na, at siya ang nakikipag-usap sa iyo.”
“Ang mga paring Levita, na buong lipi ni Levi, ay hindi magkakaroon ng bahagi ni mana na kasama ng Israel. Sila'y kakain ng mga handog sa Panginoon na pinaraan sa apoy, at ng kanyang mana.
Nang ipadala ni Juda ang anak ng kambing sa pamamagitan ng kanyang kaibigang Adullamita, upang tanggapin ang sangla mula sa kamay ng babae, siya ay hindi niya natagpuan.
Sapagkat ang pangangasiwa sa paglilingkod na ito ay hindi lamang pumupuno sa pangangailangan ng mga banal, kundi umaapaw rin sa pamamagitan ng maraming pasasalamat sa Diyos.
At sinabi ng Panginoon kay Abraham, “Bakit tumawa si Sara, na sinasabi, ‘Tunay kayang ako'y manganganak, kahit matanda na ako?’”
At tinawag ni Isaac si Jacob, at siya'y binasbasan, pinagbilinan, at sinabi sa kanya, “Huwag kang mag-aasawa sa mga anak ng Canaan.
Subalit huwag nawang mangyari sa akin ang magmalaki, maliban sa krus ng ating Panginoong Jesu-Cristo, na sa pamamagitan nito ang sanlibutan ay ipinako sa krus para sa akin, at ako'y sa sanlibutan.
Pinagmamadali sila ng mga tagapangasiwa na sinasabi, “Tapusin ninyo ang inyong mga gawa, ang inyong gawain sa araw-araw na gaya nang mayroon kayong dayami.”
Nangunguna sa hukbo ng lipi ng mga anak ni Zebulon si Eliab na anak ni Helon.
Ngunit ngayon ay itakuwil ninyo ang lahat ng mga ito: galit, poot, masamang pag-iisip, panlalait, at maruming pananalita mula sa inyong bibig.
Nang siya ay nasa Jerusalem nang kapistahan ng Paskuwa, marami ang sumampalataya sa kanyang pangalan, nang kanilang makita ang mga ginawa niyang tanda.
Dinala ni Moises ang mga buto ni Jose sapagkat mahigpit niyang pinapanumpa ang mga anak ni Israel, na sinasabi, “Tiyak na bibigyang-pansin kayo ng Diyos, at inyong dadalhin ang aking mga buto mula rito na kasama ninyo.”
Ang lahat na naging araw ni Mahalalel ay walong daan at siyamnapu't limang taon at siya'y namatay.
Ngunit siya'y binuhay ng Diyos mula sa mga patay.
Ngunit nang nauna kami sa barko, naglakbay kami patungo sa Asos, na mula roon ay binabalak naming isama si Pablo, sapagkat gayon ang kanyang ipinasiya, na binalak niyang sa lupa maglakbay.
At nakita niya ang dalawang anghel na nakaputi, na nakaupo sa hinigaan ng katawan ni Jesus, ang isa'y sa ulunan, at ang isa'y sa paanan.
Subalit sinabi sa kanya ng anghel, “Huwag kang matakot, Zacarias, sapagkat pinakinggan ang panalangin mo at ang asawa mong si Elizabeth ay magsisilang sa iyo ng isang anak na lalaki at tatawagin mo siya sa pangalang Juan.
Sapagkat kinulong ng Diyos ang lahat sa pagsuway upang siya'y mahabag sa lahat.
upang ikaw ay matakot sa Panginoon mong Diyos, na iyong ingatan ang lahat niyang mga tuntunin at ang kanyang mga utos na aking iniutos sa iyo, at sa iyong anak, at sa anak ng iyong anak sa lahat ng araw ng iyong buhay; at upang ang iyong mga araw ay humaba.
Sa pagdalaw ni Pedro sa lahat ng dako sa mga mananampalataya, pumunta rin siya sa mga banal na naninirahan sa Lidda.
Subalit sinabi ni Jesus sa kanya, “May isang naghanda ng isang malaking hapunan; at marami siyang inanyayahan.
Kaya't natupad ang sinabi sa pamamagitan ni propeta Jeremias:
Kaya't isinalaysay niya sa kanila ang talinghagang ito:
Muli niyang sinabi sa kanila, “Aalis ako, at ako'y inyong hahanapin, at mamamatay kayo sa inyong kasalanan. Sa aking pupuntahan ay hindi kayo makakapunta.”
Sinabi niya, “Sa isang lunsod ay may hukom na hindi natatakot sa Diyos at walang taong iginagalang.
Katotohanang sinasabi ko sa iyo, kami ay nagsasalita tungkol sa nalalaman namin, at nagpapatotoo sa nakita namin, subalit hindi ninyo tinanggap ang aming patotoo.
Pagkatapos ay dinala siya ng diyablo sa isang mataas na lugar at ipinakita sa kanya sa isang saglit ang lahat ng mga kaharian sa sanlibutan.
Ngunit ang maraming nauuna ay mahuhuli, at ang huli ay mauuna.”
Ito ay lumagay sa pagitan ng hukbo ng Ehipto at ng hukbo ng Israel. Mayroong ulap at kadiliman, gayunma'y binigyan sila ng liwanag sa gabi at ang isa't isa ay hindi nagkalapit sa buong magdamag.
At ang bawat bagay na nilalang na nasa langit, at nasa ibabaw ng lupa, at nasa ilalim ng lupa, at nasa ibabaw ng dagat, at lahat ng mga bagay na nasa mga ito ay narinig kong nagsasabi, “Sa kanya na nakaupo sa trono at sa Kordero ay ang kapurihan, karangalan, kaluwalhatian, at kapangyarihan, magpakailanpaman.
sapagkat dumating na ang dakilang araw ng kanilang pagkapoot, at sino ang makakatagal?”
Huwag mong hayaang hamakin ng sinuman ang iyong kabataan; kundi ikaw ay maging halimbawa ng mga mananampalataya sa pananalita, pag-uugali, pag-ibig, pananampalataya, at sa kalinisan.
Dumating ang isa pang anghel at tumayo sa harap ng dambana, na may hawak na isang gintong lalagyan ng insenso; at binigyan siya ng maraming insenso, upang idagdag ito sa mga panalangin ng lahat ng mga banal sa ibabaw ng dambanang ginto, na nasa harapan ng trono.
O kaya'y hayaan ang mga tao ring ito na magsabi kung anong masamang gawa ang natagpuan nila nang ako'y tumayo sa harapan ng Sanhedrin,
Sapagkat ang bawat isa na gumagawa ng masama ay napopoot sa ilaw, at hindi lumalapit sa ilaw, upang ang kanyang mga gawa ay huwag malantad.
Nang dumating sila sa napakaraming tao, lumapit sa kanya ang isang tao, lumuhod sa harapan niya,
Kukunin ng pari ang isa sa mga korderong lalaki at ihahandog bilang handog para sa budhing maysala, at ang log ng langis, at iwawagayway bilang handog na iwinawagayway sa harapan ng Panginoon .
Kaya habang patungo ka sa hukom na kasama ang sa iyo'y nagsakdal, sa daan ay sikapin mo nang makipag-ayos sa kanya, kung hindi ay kakaladkarin ka niya sa hukom, at ibibigay ka ng hukom sa punong-tanod, at ipapasok ka ng punong-tanod sa bilangguan.
Sila'y muling pumunta sa Jerusalem. Samantalang naglalakad siya sa templo, lumapit sa kanya ang mga punong pari, ang mga eskriba, at ang matatanda.
Iniutos niya sa una, “Kapag ikaw ay natagpuan ni Esau na aking kapatid, at tanungin ka, ‘Kanino ka? Saan ka pupunta? At kanino itong nasa unahan mo?’
Kaya't sa iba pang maraming pangaral ay ipinahayag niya sa mga tao ang magandang balita.
Sapagkat sa isang dako ay sinabi niya ang ganito tungkol sa ikapitong araw, “At nagpahinga ang Diyos nang ikapitong araw sa lahat ng kanyang mga gawa.”
(ito ang mga anak ni Zilpa na siyang ibinigay ni Laban kay Lea na kanyang anak na babae, at ang mga ito ay kanyang ipinanganak kay Jacob, labing-anim na katao).
At ang Panginoon ay bumaba sa ulap at nagsalita sa kanya; at kumuha sa espiritung nasa kanya at isinalin sa pitumpung matatanda at nangyari, na nang bumaba sa kanila ang espiritu ay nagpropesiya sila. Ngunit hindi na nila iyon ginawa muli.
Sumakanya nawa ang kapangyarihan magpakailanman. Amen.
Ang balitang ito tungkol sa kanya ay kumalat sa buong Judea at sa lahat ng nakapaligid na lupain.
“Ang ketonging may sakit ay magsusuot ng punit na damit, at ang buhok ng kanyang ulo ay ilulugay, at tatakpan niya ang itaas na bahagi ng kanyang nguso, at siya'y sisigaw, ‘Marumi, marumi.’
Patnubayan nawa ng Panginoon ang inyong mga puso sa pag-ibig ng Diyos at sa katatagan ni Cristo.
Ang Diyos ang naglalabas sa kanya sa Ehipto; may lakas na gaya ng mabangis na toro. Kanyang lalamunin ang mga bansa na kanyang mga kaaway, at kanyang babaliin ang kanilang mga buto, at papanain sila ng kanyang mga palaso.
Nang idanak ang dugo ni Esteban na iyong saksi, ako mismo ay nakatayo sa malapit, na sumasang-ayon at nag-iingat sa mga damit ng mga pumatay sa kanya.’
Sapagkat minabuti ng Macedonia at ng Acaia na gumawa ng isang ambagang laan sa mga dukha sa mga banal na nasa Jerusalem.
Ibigay mo sa akin ang aking mga asawa at ang aking mga anak, na siyang dahilan ng paglilingkod ko sa iyo, at hayaan mo akong umalis sapagkat nalalaman mo ang paglilingkod na ibinigay ko sa iyo.”
Tunay na sa pamamagitan nito ang mga tao noong una ay tumanggap ng patotoo.
Kaya't si Israel ay nanirahan sa lupain ng Ehipto, sa lupain ng Goshen; at sila'y nagkaroon ng mga pag-aari roon, at sumagana at naging napakarami.
At iginawa ng Panginoong Diyos si Adan at ang kanyang asawa ng mga kasuotang balat at sila'y dinamitan.
Pagkatapos sabihin ni Moises ang lahat ng mga salitang ito sa buong Israel,
Kaya't panatag nating masasabi, “Ang Panginoon ang aking katulong; hindi ako matatakot: Anong magagawa sa akin ng tao?”
Kaya't sinabi ng kanyang mga magulang, “Siya'y may sapat na gulang na, tanungin ninyo siya.”
“Huwag kang magtatanim ng anumang puno tulad ng sagradong poste sa tabi ng dambana na iyong gagawin para sa Panginoon mong Diyos.
Ipapatong niya ang kanyang kamay sa ulo ng kambing, at papatayin niya ito sa dakong pinagkakatayan ng handog na sinusunog sa harapan ng Panginoon ; ito ay handog pangkasalanan.
At ang mga iyon ay magkahiwalay sa ilalim ngunit magkakabit at nauugnay na mainam sa itaas, sa unang argolya. Gayon ang ginawa niya sa dalawa para sa dalawang sulok.
Kayo'y maging handa at manalangin, upang hindi kayo madaig ng tukso. Ang espiritu ay tunay na nagnanais subalit ang laman ay mahina.”
Ibinigay siya ng Panginoon nating Diyos sa harapan natin; at ginapi natin siya at ang kanyang mga anak, at ang kanyang buong bayan.
huwag kang magmalaki sa mga sanga. Ngunit kung magmalaki ka, alalahanin mong hindi ikaw ang nagdadala sa ugat, kundi ang ugat ang nagdadala sa iyo.
Kaya't kanilang kinuha ang mahabang damit ni Jose, at sila'y pumatay ng isang lalaking kambing, at kanilang inilubog ang mahabang damit sa dugo.
Nakakita siya ng dalawang bangka na nasa tabi ng lawa; wala na roon ang mga mangingisda at naghuhugas na ng kanilang mga lambat.
Kanilang sinabi sa kanya, “Kami ay dumating sa lupaing iyon na kung saan ay sinugo mo kami, at tunay na iyon ay dinadaluyan ng gatas at pulot; at ito ang bunga niyon.
Sa kanilang paglalakbay sa silangan, nakatagpo sila ng isang kapatagan sa lupain ng Shinar, at sila'y tumira doon.
“Bilangin mo ang buong sambayanan ng mga anak ni Israel, ayon sa mga angkan nila, sa mga sambahayan ng kani-kanilang mga ninuno, ayon sa bilang ng mga pangalan, bawat lalaki, bawat isa.
Subalit ang magtiis hanggang sa wakas ay siyang maliligtas.
At sinabi niya sa kanila, “Subalit ano ang sinasabi ninyo kung sino ako?” At sumagot si Pedro, “Ang Cristo ng Diyos.”
Nang mga araw na iyon, nang malaki na si Moises, nagtungo siya sa kanyang mga kapatid, at nakita ang kanilang sapilitang paggawa. Kanyang nakita ang isang Ehipcio na binubugbog ang isang Hebreo na isa sa kanyang mga kapatid.
Sapagkat narinig nilang nagsasalita ang mga ito ng mga wika at nagpupuri sa Diyos. Nang magkagayo'y ipinahayag ni Pedro,
Kaya, mga banal na kapatid, mga kabahagi sa makalangit na pagkatawag, isaalang-alang ninyo na si Jesus, ang Apostol at Pinakapunong Pari ng ating pagpapahayag,
ngunit ang isang ito ay naging pari na may panunumpa, “Nanumpa ang Panginoon at hindi siya magbabago ng kanyang isip, ‘Ikaw ay pari magpakailanman.’”
Pagkatapos na sila'y mapalaya, pumunta sila sa kanilang mga kasamahan at iniulat ang lahat ng sinabi sa kanila ng mga punong pari at ng matatanda.
isang kambing na lalaki upang ipantubos sa inyo.
Bilang mga hinirang ng Diyos, mga banal at minamahal, magbihis kayo ng kahabagan, ng kabaitan, ng kababaang-loob, ng kaamuan, at ng katiyagaan.
ay sinabi ni Rebecca kay Jacob na kanyang anak, “Narinig ko ang iyong ama na nagsasabi kay Esau na iyong kapatid,
At sa araw ng Sabbath ay pumunta kami sa labas ng pintuan sa may tabi ng ilog na sa palagay namin ay may dakong panalanginan, at kami'y umupo, at nakipag-usap sa mga babaing nagtitipon doon.
O hangal na mga taga-Galacia! Sino ang gumayuma sa inyo? Sa harapan ng inyong mga mata ay hayagang ipinakita si Jesu-Cristo na ipinako sa krus!
Kaya't iniutos ni Abimelec sa buong bayan, “Ang gumalaw sa lalaking ito o sa kanyang asawa ay mamamatay.”
Nang maipatong na ni Pablo sa kanila ang kanyang mga kamay, bumaba sa kanila ang Espiritu Santo at sila'y nagsalita ng mga wika at nagpropesiya.
At palibhasa'y hindi nila minabuting kilalanin ang Diyos, hinayaan sila ng Diyos sa isang mahalay na pag-iisip, upang gawin ang mga bagay na hindi nararapat.
Sa ikalabinlimang araw ng buwang ito ay magkakaroon ng isang pista; pitong araw na kakain kayo ng tinapay na walang pampaalsa.
Ngayon ay hayag ang mga gawa ng laman, ang mga ito ay pakikiapid, karumihan, kahalayan,
Kapag ang bahaghari ay nasa ulap, ito ay aking makikita at maaalala ang walang hanggang tipan sa pagitan ng Diyos at ng bawat nilalang na may buhay na nasa ibabaw ng lupa.”
Sinabi nila, “Ang Panginoon ay nag-utos sa aking panginoon na ibigay sa pamamagitan ng palabunutan ang lupain na pinakamana sa mga anak ni Israel at inutusan din naman ng Panginoon ang aking panginoon na ibigay ang mana ni Zelofehad na aming kapatid sa kanyang mga anak na babae.
Sa paglabas niya sa templo, sinabi sa kanya ng isa sa kanyang mga alagad, “Guro, tingnan mo! Pagkalalaking mga bato, at pagkalalaking mga gusali!”
Ang mga ito rin ang nilakaran ninyo noong una, nang kayo'y nabubuhay pa sa mga bagay na ito.
“Subalit kung diringgin mong mabuti ang kanyang tinig at gagawin mo ang lahat ng aking sinasabi ay magiging kaaway ako ng iyong mga kaaway, at kalaban ng iyong mga kalaban.
At gayon ang ginawa ni Aaron. Kanyang sinindihan ang mga ilaw upang magliwanag sa harap ng ilawan, gaya ng iniutos ng Panginoon kay Moises.
“Bakit tinatawag ninyo akong, ‘Panginoon, Panginoon,’ ngunit hindi ninyo ginagawa ang sinasabi ko?
At kanyang sinabi sa kanila, “Ang mga hari ng mga Hentil ay nagpapapanginoon sa kanila; at ang mga may awtoridad sa kanila'y tinatawag na mga tagapagpala.
“Kung ipagbili ng isang lalaki ang kanyang anak na babae bilang isang alipin, hindi siya aalis na gaya ng pag-alis ng mga aliping lalaki.
kaya't ako'y naging laban sa kanila, at sila'y aking dinala sa lupain ng kanilang mga kaaway; subalit kung magpapakumbaba ang kanilang mga pusong hindi tuli, at magbayad sa kanilang kasamaan;
Bakit ka lihim na tumakas at dinaya mo ako at hindi ka nagsabi sa akin? Naihatid sana kita na may pagsasaya at awitan, may tambol at may alpa.
at itatapon sila sa pugon ng apoy. Doon ay magkakaroon ng pagtangis at pagngangalit ng mga ngipin.
Subalit sinasabi ko, lumakad kayo ayon sa Espiritu, at huwag ninyong bigyang-kasiyahan ang mga pagnanasa ng laman.
Sapagkat nais kong malaman ninyo, mga kapatid, na ang ebanghelyo na aking ipinangaral ay hindi ayon sa tao.
Subalit ang mga kamay ni Moises ay nangalay, kaya't sila'y kumuha ng isang bato at inilagay sa ibaba, at kanyang inupuan. Inalalayan nina Aaron at Hur ang kanyang mga kamay, ang isa'y sa isang panig, at ang isa'y sa kabilang panig; at ang kanyang mga kamay ay nanatili sa itaas hanggang sa paglubog ng araw.
Sinabi nila sa kanya, “Kay Cesar.” Pagkatapos ay sinabi niya sa kanila, “Kaya't ibigay ninyo kay Cesar ang kay Cesar at sa Diyos ang sa Diyos.”
Hindi mo ako hinalikan, subalit buhat nang ako'y pumasok ay hindi pa siya humihinto ng paghalik sa aking mga paa.
kung paanong ang Anak ng Tao ay naparito hindi upang paglingkuran, kundi upang maglingkod, at upang ibigay ang kanyang buhay na pantubos sa marami.”
“Magdiriwang ka sa buwan ng Abib, at ipangingilin ang paskuwa sa Panginoon mong Diyos; sapagkat sa buwan ng Abib ay inilabas ka ng Panginoon mong Diyos sa Ehipto sa gabi.
Pinayagan ni Moises na umalis na ang kanyang biyenan at siya'y umuwi sa sariling lupain.
upang kanilang maturuan ang mga kabataang babae na ibigin ang kani-kanilang mga asawa, ibigin ang kanilang mga anak,
Tulad ng isang tao na umalis upang maglakbay. Sa pag-alis niya sa kanyang bahay, at pagkabigay ng tagubilin sa kanyang mga alipin, sa bawat isa ang kanyang gawain, ay inutusan ang tanod sa pinto na magbantay.
Nang makita ni Simon na ibinibigay ang Espiritu sa pamamagitan ng pagpapatong ng mga kamay ng mga apostol, sila'y inalok niya ng salapi,
Si Jacob ay nagpanata na sinasabi, “Kung makakasama ko ang Diyos at ako'y iingatan sa daang ito na aking nilalakaran, at ako'y bibigyan niya ng tinapay na makakain, at damit na maisuot,
Silang lahat ay nagtaka at naguluhang sinasabi sa isa't isa, “Ano ang kahulugan nito?”
Ibibigay ninyo ito sa paring si Eleazar, at kanyang ilalabas sa kampo at papatayin sa kanyang harapan.
Subalit ang Diyos na umaaliw sa nalulungkot ay nagpasigla sa amin sa pamamagitan ng pagdating ni Tito,
at nakita niya sa pangitain ang isang lalaking ang pangalan ay Ananias na pumapasok, at ipinapatong ang kanyang mga kamay sa kanya upang muli niyang tanggapin ang kanyang paningin.”
Si Maria ang siyang nagbuhos sa Panginoon ng pabango, at pinunasan ang mga paa nito ng kanyang buhok. Ang kanyang kapatid na si Lazaro ay may sakit.
Mga ama, huwag ninyong ibunsod sa galit ang inyong mga anak, baka manghina ang loob nila.
At kung magkagayo'y mahahayag ang taong makasalanan na siyang pupuksain ng Panginoong Jesus sa pamamagitan ng hininga ng kanyang bibig, at lilipulin sa pamamagitan ng pagkahayag ng kanyang pagdating.
“Alinmang butil na handog na iaalay ninyo sa Panginoon , ay gawin ninyong walang pampaalsa. Huwag kayong magsusunog ng anumang pampaalsa ni ng anumang pulot bilang handog na pinaraan sa apoy para sa Panginoon .
Narinig ninyong sinabi ko sa inyo, ‘Ako ay aalis, at babalik ako sa inyo. Kung ako'y inyong minamahal, kayo'y magagalak sapagkat ako'y pupunta sa Ama; sapagkat ang Ama ay higit na dakila kaysa akin.’
“Sabihin mo sa mga anak ni Israel, ‘Pagpasok ninyo sa lupaing aking pagdadalhan sa inyo,
“Ito ang nauukol sa mga Levita: mula dalawampu't limang taong gulang pataas ay papasok upang gampanan ang gawaing paglilingkod sa toldang tipanan.
Lahat ng mga bagay ay aking magagawa sa pamamagitan niyang nagpapalakas sa akin.
Sa ami'y ipinagbilin niya na mangaral sa mga tao at sumaksi na siya ang itinalaga ng Diyos na maging hukom ng mga buháy at ng mga patay.
Sumagot siya sa kanila, “Sino ang aking ina at ang aking mga kapatid?”
Nagtayo si Jacob ng isang haliging batong bantayog kung saan ay nakipag-usap ang Diyos sa kanya. Binuhusan niya ito ng inuming handog at ng langis.
Ang tanging bagay na nais kong matutunan mula sa inyo ay ito: Tinanggap ba ninyo ang Espiritu sa pamamagitan ng mga gawa ng kautusan, o sa pamamagitan ng pakikinig sa pananampalataya?
Lumalaki ang mga alon sa dagat dahil sa malakas na hanging humihihip.
Ang mga ito ang inilagay ng Diyos sa kalawakan ng langit upang tumanglaw sa ibabaw ng lupa,
Mag-ingat kayo, baka ang inyong puso ay madaya, at kayo'y maligaw, at maglingkod sa ibang mga diyos, at sumamba sa kanila.
Ito ay iyong lulutuin at kakainin sa lugar na pipiliin ng Panginoon mong Diyos. Kinaumagahan ay babalik ka at uuwi sa iyong mga tolda.
At lumapit din ang tumanggap ng dalawang talento at sinabi niya, ‘Panginoon, binigyan mo ako ng dalawang talento. Heto, ako'y nakinabang ng dalawa pang talento.’
Sapagkat ang buhay ay higit kaysa pagkain at ang katawan ay higit kaysa damit.
At ang mga punong pari at ang buong Sanhedrin ay humanap ng mga bulaang saksi laban kay Jesus upang kanilang maipapatay siya.
at ang mga Horeo sa kanilang kabundukan ng Seir hanggang Elparan na nasa tabi ng ilang.
at sa kanyang noo ay nakasulat ang isang pangalan, ang isang hiwaga: “dakilang Babilonia, ina ng mga mahalay na babae at ng mga karumaldumal sa lupa.”
At ngayon, idinadalangin ko sa iyo, hayaan mong ang kapangyarihan ng Panginoon ay maging dakila, ayon sa iyong ipinangako,
“At kung kayo'y hindi ko maturuan sa pamamagitan ng mga bagay na ito, kundi lumakad nang laban sa akin,
Si Dan ay hahatol sa kanyang bayan, bilang isa sa mga lipi ni Israel.
Makaraan ang ilang araw, sinabi ni Pablo kay Bernabe, “Balikan natin at dalawin ang mga kapatid sa bawat bayang pinangaralan natin ng salita ng Panginoon, at tingnan natin kung ano ang kalagayan nila.”
Pagkaraan ng maraming araw, ang hari ng Ehipto ay namatay. Ang bayang Israel ay dumaing dahil sa pagkaalipin at sila'y humingi ng tulong. Ang kanilang daing dahil sa pagkaalipin ay nakarating sa Diyos.
Kaya't ikaw, anak ko, maging malakas ka sa biyayang na kay Cristo Jesus,
(tinatawag ng mga taga-Sidon ang Hermon na Sirion, at ito ay tinatawag ng mga Amoreo na Senir),
Upang kayo'y huwag magmarunong sa inyong sarili, mga kapatid, nais kong malaman ninyo ang hiwagang ito, na ang pagmamatigas ay nangyari sa isang bahagi ng Israel hanggang makapasok ang buong bilang ng mga Hentil.
At sa kanyang pintuan ay nakahandusay ang isang pulubi na ang pangala'y Lazaro, na punô ng mga sugat,
Sumagot si Simon, “Sa palagay ko ay iyong pinatawad niya ng mas malaki.” At sinabi niya sa kanya, “Tama ang hatol mo.”
Kanilang tinalian ito ng isang panaling asul, upang ilapat sa ibabaw ng turbante; gaya ng iniutos ng Panginoon kay Moises.
Oo, iniibig niya ang bayan: lahat ng kanyang mga banal ay nasa iyong kamay; sila'y sumunod sa iyong mga yapak, na tumatanggap ng tagubilin mula sa iyo.
Pinagsikapan ng lahat na siya'y mahipo, sapagkat may kapangyarihang nanggagaling sa kanya at pinagaling niya ang lahat.
Ginawa ni Bezaleel ang kaban na yari sa kahoy na akasya; dalawang siko at kalahati ang haba niyon, at isang siko't kalahati ang luwang at may isang siko at kalahati ang taas niyon.
Ano nga kung ang ilan ay hindi tapat? Ang kanila bang kawalan ng katapatan ay nagpapawalang saysay sa katapatan ng Diyos?
“Tatlong beses sa bawat taon na magdiriwang ka ng pista para sa akin.
Samantalang nasa kanilang kagalakan ay hindi pa sila naniniwala at nagtataka, sinabi niya sa kanila, “Mayroon ba kayo ritong anumang makakain?”
na iniingatan ang pananampalataya at ang mabuting budhi. Sa pamamagitan ng pagtatakuwil sa budhi, ang ibang tao ay nakaranas ng pagkawasak ng barko sa kanilang pananampalataya;
“Ilapit mo ang lipi ni Levi, at ilagay mo sila sa harap ng paring si Aaron upang sila'y maglingkod sa kanya.
At sinabi niya sa kanya, “O sige, pinapayagan din kita sa bagay na ito at hindi ko na gugunawin ang lunsod na iyong binanggit.
Isusulat ko sa mga tapyas ang mga salita na nasa unang mga tapyas na iyong binasag, at iyong isisilid ang mga iyan sa kaban.’
Pagkatapos ng mga bagay na ito, tinitigan si Jose ng asawa ng kanyang panginoon at sinabi, “Sipingan mo ako.”
Kaya't inisip ko na kailangang himukin ang mga kapatid na maunang pumariyan sa inyo, at ihanda agad ang inyong kaloob na ipinangako nang una, upang ito'y maihanda bilang isang kusang-loob na handog at hindi sapilitan.
at doon ay may isang lalaki na ang pangalan ay Zaqueo. Siya'y isang punong maniningil ng buwis at mayaman.
Ang isang bukal ba ay binubukalan ng matamis at mapait?
Ngunit dahil sa sinabi ko ang mga bagay na ito sa inyo, napuno ng lungkot ang inyong puso.
at ang baboy, bagaman may hati ang paa at biyak subalit hindi ngumunguya, ito ay marumi para sa inyo.
Sila namang nagpapatuloy sa pagkakasala ay sawayin mo sa harapan ng lahat, upang ang iba nama'y matakot.
“Mapapalad ang mga nagugutom at nauuhaw sa katuwiran, sapagkat sila ay bubusugin.
Pagkasabi nito, siya'y lumingon at nakitang nakatayo si Jesus. Subalit hindi niya alam na iyon ay si Jesus.
at ang lahat ng mga kapatid na kasama ko, Sa mga iglesya ng Galacia:
Pagkatapos ay tinakpan ng ulap ang toldang tipanan at pinuno ng kaluwalhatian ng Panginoon ang tabernakulo.
Nang sila'y papalabas na sa Jerico, sumunod sa kanya ang napakaraming tao.
upang ito'y aking maipahayag, gaya ng aking nararapat na sabihin.
Sapagkat sa loob ng isang oras ay nalipol ang ganito kalaking kayamanan!” At ang bawat pinuno ng barko, ang bawat naglalayag saan mang dako, ang mga mandaragat, at lahat ng naghahanap-buhay sa dagat, ay nakatayo sa malayo,
Ako'y nagagalak sapagkat ako'y mayroong buong pagtitiwala sa inyo.
Manatili kayo rito, gaya ng iba, upang aking malaman kung ano pa ang sasabihin sa akin ng Panginoon .”
At sinong lalaki ang naitakdang ikasal sa isang babae at di pa niya nakukuha? Hayaan siyang umalis at bumalik sa kanyang bahay, baka siya'y mamatay sa pakikipaglaban, at ibang lalaki ang kumuha sa kanya.’
Lumakad si Enoc na kasama ng Diyos, pagkatapos na maipanganak si Matusalem ng tatlong daang taon, at nagkaanak pa siya ng mga lalaki at mga babae.
Ngunit sinasabi ninyo na sinumang magsabi sa kanyang ama o sa kanyang ina, ‘Anumang pakikinabangin mo mula sa akin ay ipinagkaloob ko na sa Diyos.’ Ang taong iyon ay hindi na kailangang gumalang pa sa kanyang ama.
Sa paglalayag na nanganganlong sa isang maliit na pulo na tinatawag na Cauda, ay bahagya naming napatakbo ang bangka.
At humayo sila, at natagpuan ito ayon sa sinabi niya sa kanila, at inihanda nila ang Paskuwa.
Ang nabilang sa kanila ay dalawampu't tatlong libo, lahat ng lalaki mula sa isang buwang gulang pataas: dahil hindi sila binilang kasama ng mga anak ni Israel, sapagkat sila'y hindi binigyan ng mana sa gitna ng mga anak ni Israel.
Yamang nakita niya ito bago pa mangyari, nagsalita si David tungkol sa muling pagkabuhay ng Cristo: ‘Hindi siya pinabayaan sa Hades, ni ang kanya mang katawan ay nakakita ng kabulukan.’
Sapagkat hindi nakilala ng mga naninirahan sa Jerusalem at ng mga pinuno nila si Jesus ni ang mga tinig ng mga propeta na binabasa tuwing Sabbath, tinupad nila ang mga salitang ito sa pamamagitan ng paghatol sa kanya.
Kaya't pinaalis ng punong kapitan ang binata, at ipinagbilin sa kanya, “Huwag mong sasabihin kaninuman na ipinagbigay-alam mo sa akin ang mga bagay na ito.”
Walang sinuman na pagkatapos magsindi ng ilawan ay inilalagay ito sa isang tagong lugar o sa ilalim ng takalan, kundi sa patungan ng ilaw upang makita ng mga pumapasok ang liwanag.
Matapos makipagkasundo sa mga manggagawa ng isang denario sa isang araw ay kanyang isinugo sila sa kanyang ubasan.
Pagkatapos ay sasagutin siya ng mga matuwid, na nagsasabi, ‘Panginoon, kailan ka namin nakitang gutom, at pinakain ka namin, o uhaw, at binigyan ka ng inumin?
Sinabi ng Panginoon, “Kung mayroon kayong pananampalataya na kasinglaki ng isang binhi ng mustasa, masasabi ninyo sa puno ng sikomorong ito, ‘Mabunot ka, at matanim ka sa dagat,’ susundin kayo nito.
Ang paring naghahandog ng handog na sinusunog ng sinumang tao ay siyang magmamay-ari ng balat ng handog na sinusunog na inialay.
Nang sila'y dumating, tinipon nila ang iglesya at iniulat ang lahat ng mga bagay na ginawa ng Diyos sa pamamagitan nila, at kung paanong binuksan niya para sa mga Hentil ang pinto ng pananampalataya.
Ngunit winawasak ni Saul ang iglesya sa pamamagitan ng pagpasok sa bahay-bahay, kinakaladkad ang mga lalaki't babae, at sila'y ipinapasok sa bilangguan.
Kaya't ano ngang bunga mayroon kayo sa mga bagay na ngayo'y ikinahihiya ninyo? Sapagkat ang kahihinatnan ng mga bagay na iyon ay kamatayan.
Sapagkat sa ilang ng Zin, sa pakikipagtalo ng kapulungan ay naghimagsik kayo laban sa aking utos na kilalanin ninyo akong banal sa harap ng mga mata nila doon sa tubig.” (Ito ang tubig ng Meriba sa Kadesh sa ilang ng Zin.)
Huwag mong dadalhin ang upa sa isang masamang babae, o ang pasahod sa isang aso sa bahay ng Panginoon mong Diyos para sa anumang panata, sapagkat ang mga ito ay kapwa karumaldumal sa Panginoon mong Diyos.
At bumaba sa kanya ang Espiritu Santo na may anyong katawan na tulad sa isang kalapati. May isang tinig na nagmula sa langit, “Ikaw ang pinakamamahal kong Anak, sa iyo ako lubos na nalulugod.”
“Pagkatapos niyang matubos ang dakong banal, ang toldang tipanan, at ang dambana, ay ihahandog niya ang kambing na buháy.
Ano nga? Magkakasala ba tayo, dahil tayo'y wala sa ilalim ng kautusan, kundi nasa ilalim ng biyaya? Huwag nawang mangyari.
At nakita ko ang isa pang halimaw na umaahon sa lupa; at ito ay may dalawang sungay na katulad ng sa isang kordero at siya'y nagsasalita na parang dragon.
Pagkatapos ay pumunta siyang muli sa Cana ng Galilea na doo'y kanyang ginawang alak ang tubig. At sa Capernaum ay naroroon ang isang pinuno ng pamahalaan na ang anak na lalaki ay maysakit.
Ngunit sumagot ang kanyang panginoon at sinabi sa kanya, ‘Ikaw na masama at tamad na alipin! Alam mo palang ako'y gumagapas sa hindi ko hinasikan, at nagtitipon sa hindi ko kinalatan ng binhi.
Sinabi ng Panginoon kay Moises, “Gagawin ko ang bagay na ito na iyong sinabi, sapagkat ikaw ay nakatagpo ng biyaya sa aking paningin, at ikaw ay aking nakikilala sa pangalan.”
maging matino, dalisay, masipag sa gawaing bahay, mabait, na nagpapasakop sa kani-kanilang asawa, upang huwag lapastanganin ang salita ng Diyos.
Kapag ang isang lalaki ay namanata ng isang panata sa Panginoon , o sumumpa ng isang sumpa, na itinali ang kanyang sarili sa pamamagitan ng isang panata, ay huwag niyang sisirain ang kanyang salita. Kanyang tutuparin ang ayon sa lahat ng lumabas sa kanyang bibig.
“Iyong iuutos sa mga anak ni Israel na sila'y magdala sa iyo ng dalisay na langis ng binayong olibo para sa ilawan, upang ang ilawan ay palaging may sindi.
Sapagkat ipinanganak sa inyo ngayon sa lunsod ni David ang isang Tagapagligtas, na siya ang Cristo, ang Panginoon.
At kahuli-hulihan sa lahat ay namatay ang babae.
Subalit sinabi ng ama sa kanyang mga alipin, ‘Dali, dalhin ninyo rito ang pinakamagandang kasuotan at isuot ninyo sa kanya. Lagyan ninyo ng singsing ang kanyang daliri, at mga sandalyas ang kanyang mga paa.
Ngayon ang salitang, “Minsan pa,” ay nagpapahiwatig ng pag-aalis ng mga bagay na niyanig, gaya ng mga bagay na ginawa, upang manatili ang mga bagay na hindi nayayanig.
hanggang sa bigyan ng Panginoon ng kapahingahan ang inyong mga kapatid, na gaya ninyo, at kanilang angkinin din ang lupain na ibinigay sa kanila ng Panginoon ninyong Diyos sa kabila ng Jordan. Pagkatapos ay babalik ang bawat lalaki sa inyo sa kanyang pag-aari na aking ibinigay sa inyo.’
Sapagkat siya'y ipinako mula sa kahinaan, subalit nabubuhay sa pamamagitan ng kapangyarihan ng Diyos. Kami ay mahihina sa kanya, ngunit sa pakikitungo sa inyo, kami ay mabubuhay na kasama niya sa kapangyarihan ng Diyos.
“Kapag may dalawang lalaking nag-aaway at ang asawang babae ng isa ay lumapit upang iligtas ang kanyang asawa sa kamay ng nananakit sa kanya sa pamamagitan ng pag-uunat niya ng kanyang kamay at paghawak sa maselang bahagi ng lalaki,
Ito ang mga tuntunin na iniutos ng Panginoon kay Moises, sa mag-asawa at sa mag-ama samantalang ang anak na dalaga ay nasa bahay ng kanyang ama sa panahon ng kanyang kabataan.
Ginawa sa kanya ng kanyang mga anak ang ayon sa iniutos sa kanila.
“Magkakaroon ka rin ng isang pook sa labas ng kampo na ikaw ay lalabas doon;
Ang biyaya ng ating Panginoong Jesu-Cristo ay sumainyo nawang espiritu.
Ako'y dumarating na madali; panghawakan mong matibay ang nasa iyo, upang walang makaagaw ng iyong korona.
Pagtingala niya sa langit, siya'y nagbuntong-hininga, at sinabi sa kanya, “Effata,” na nangangahulugang “Mabuksan.”
anim sa kanilang mga pangalan ay sa isang bato, at ang mga pangalan ng anim na natitira ay sa isa pang bato, ayon sa kanilang kapanganakan.
Sa pananampalataya ay nauunawaan natin na ang mga sanlibutan ay nilikha sa pamamagitan ng salita ng Diyos, anupa't ang mga bagay na nakikita ay nagmula sa mga bagay na hindi nakikita.
“Huwag kayong humatol at hindi kayo hahatulan. Huwag kayong humusga at hindi kayo huhusgahan. Magpatawad kayo at kayo'y patatawarin.
kalakal na ginto at pilak, mahalagang bato at mga perlas, pinong lino, kulay-ube, sutla at pula; ng sari-saring mababangong kahoy, at bawat kasangkapang garing, bawat kasangkapang mahalagang kahoy, tanso, bakal, marmol,
Lamang ay tiyakin mong hindi mo kakainin ang dugo, sapagkat ang dugo ay siyang buhay; at huwag mong kakainin ang buhay na kasama ng laman.
Maraming tao ang naglatag ng kanilang balabal sa daan at ang iba'y naglatag ng mga sanga na kanilang pinutol mula sa mga bukid.
Ngunit kung ang pamamaga ay tumigil sa kanyang kinaroroonan, at hindi kumalat, ito ay galos ng bukol; at ipahahayag ng pari na siya ay malinis.
Humabol ang mga Ehipcio at pumasok na kasunod nila sa gitna ng dagat, lahat ng mga kabayo ng Faraon, ang kanyang mga karwahe, at ang kanyang mga mangangabayo.
Nang ikawalong araw ay dumating sila upang tuliin ang sanggol. Siya'y tatawagin sana nila na Zacarias, ayon sa pangalan ng kanyang ama,
Lagi kaming nagpapasalamat sa Diyos na Ama ng ating Panginoong Jesu-Cristo, sa aming pananalangin para sa inyo,
Katotohanang sinasabi ko sa inyo, na anumang inyong talian sa lupa ay yaong tatalian sa langit; at anumang inyong kalagan sa lupa ay yaong kakalagan sa langit.
Lumakad si Enoc na kasama ng Diyos; at hindi na siya natagpuan sapagkat siya'y kinuha ng Diyos.
Ang ikalimampung taon ay taon ng pagdiriwang para sa inyo, huwag kayong maghahasik ni aanihin ang tumubo sa kanyang sarili, ni titipunin ang mula sa ubasang hindi inalagaan;
Hindi mapapabulaanan na ang nakabababa ay binabasbasan ng nakatataas.
Nawa'y ibigay niya sa iyo ang pagpapala ni Abraham, sa iyo at sa lahat ng iyong binhi; upang ariin mo ang lupaing iyong pinaglakbayan na ibinigay ng Diyos kay Abraham.”
Apatnapung hagupit ang ibibigay sa kanya, huwag lalampas; baka kung siya'y hagupitin niya nang higit sa bilang na ito, ang iyong kapatid ay maging hamak sa iyong paningin.
Ang inyong mga kayamanan ay bulok na, at ang inyong mga damit ay kinakain na ng bukbok.
Ang mga anak ni Het ay sumagot kay Abraham,
at nakiusap bilang tulong sa kanila laban kay Pablo, na siya ay ilipat sa Jerusalem. Sila'y nagbabalak ng pananambang upang siya'y patayin sa daan.
Huwag mo siyang titingnan na may pagkahabag kundi aalisin mo ang pagkakasala ng dugong walang sala mula sa Israel para sa ikabubuti mo.
subalit sinabi ni Jesus sa kanya, “Judas, ipinagkakanulo mo ba ang Anak ng Tao sa pamamagitan ng isang halik?”
na may mabuting patotoo tungkol sa mabubuting gawa; na siya'y nagpalaki ng mga anak, na siya'y nagpatuloy ng mga panauhin sa kanyang tahanan, naghugas ng mga paa ng mga banal, dumamay sa mga naghihirap, at itinalaga niya ang sarili sa paggawa ng mabuti sa lahat ng paraan.
“Tuparin mo ang mga iniutos ko sa iyo sa araw na ito. Tingnan mo, aking pinalalayas sa harap mo ang mga Amoreo, mga Cananeo, mga Heteo, mga Perezeo, mga Heveo, at ang mga Jebuseo.
upang malaman ng inyong salinlahi na pinatira ko sa mga kubol ang mga anak ni Israel nang sila'y aking ilabas sa lupain ng Ehipto: Ako ang Panginoon ninyong Diyos.”
Ang Panginoon ay nagsalita kay Moises,
“Ngayon ay nababagabag ang aking kaluluwa. At ano ang aking sasabihin? ‘Ama, iligtas mo ako sa oras na ito?’ Ngunit dahil dito ay dumating ako sa oras na ito.
isang ikasampung bahagi para sa bawat kordero sa pitong kordero;
Ibibigay sila ng Panginoon sa harapan mo, at iyong gagawin sa kanila ang ayon sa lahat ng utos na aking iniutos sa iyo.
at ang apatnapung patungang pilak ng mga ito, dalawang patungan sa ilalim ng isang haligi, at dalawang patungan sa ilalim ng kabilang haligi.
Ang panahon mula nang tayo ay lumabas sa Kadesh-barnea hanggang sa tayo'y nakarating sa batis ng Zared ay tatlumpu't walong taon, hanggang sa ang buong lahi ng mga lalaking mandirigma ay malipol sa gitna ng kampo, gaya ng ipinangako sa kanila ng Panginoon .
at nang maging sakdal, siya ang naging pinagmulan ng walang hanggang kaligtasan ng lahat ng mga sumusunod sa kanya;
Iniutos ni Jose sa kanyang mga manggagamot na naglilingkod sa kanya na embalsamuhin ang kanyang ama, at inembalsamo ng mga manggagamot si Israel.
Kaya ibinigay nila kay Jacob ang lahat ng mga banyagang diyos na nasa kanilang kamay at ang mga hikaw na nasa kanilang mga tainga; at itinago iyon ni Jacob sa ilalim ng punong ensina na malapit sa Shekem.
Sapagkat kay Cristo Jesus, ang pagtutuli o di-pagtutuli ay walang kabuluhan, kundi ang pananampalataya na gumagawa sa pamamagitan ng pag-ibig.
Nang matikman ng pinuno ng handaan ang tubig na naging alak, at hindi niya alam kung saan ito nanggaling (subalit nalalaman ng mga lingkod na kumuha ng tubig), tinawag ng pinuno ng handaan ang lalaking bagong kasal.
Sila'y kanyang iniwan, at lumabas sa lunsod patungong Betania, at doon siya nagpalipas ng gabi.
Gayunman, maging sa mga pinuno ay maraming sumampalataya sa kanya; subalit dahil sa takot sa mga Fariseo ay hindi nila ito ipinahayag, baka sila'y mapalayas sa sinagoga,
Nang makapagtalaga na sila ng matatanda para sa kanila sa bawat iglesya, matapos manalangin na may pag-aayuno, ay kanilang ipinagtagubilin sila sa Panginoon na kanilang sinampalatayanan.
upang maging alaala sa mga anak ni Israel, upang sinumang ibang tao na hindi pari, na hindi mga anak ni Aaron ay huwag lumapit upang magsunog ng insenso sa harap ng Panginoon at nang huwag maging tulad ni Kora at ng kanyang mga kasama; gaya ng sinabi ng Panginoon kay Eleazar sa pamamagitan ni Moises.
At sinabi nila sa kanya, “Sabihin mo sa amin, sa anong awtoridad mo ginagawa ang mga bagay na ito? O sino ang nagbigay sa iyo ng awtoridad na ito?”
Nang dumating ang tanghaling tapat, nagdilim sa buong lupain hanggang sa ikatlo ng hapon.
“Kung ang alay ay handog pangkapayapaan, at ang ihahandog niya ay mula sa bakahan, maging lalaki o babae, ito ay ihahandog niya na walang kapintasan sa harapan ng Panginoon .
Kayo'y sinugo ko upang anihin ang hindi ninyo pinagpaguran; iba ang nagpagod at kayo'y pumasok sa kanilang pinagpaguran.”
At sa ganito'y nalalaman natin na siya'y kilala natin, kung tinutupad natin ang kanyang mga utos.
Ang Panginoon ang aking awit at kalakasan, at siya'y naging aking kaligtasan; Ito ang aking Diyos, at aking pupurihin siya, siya'y aking itataas, ang Diyos ng aking ama.
Siya'y pinasakay niya sa karwahe na para sa ikalawang pinakamataas na pinuno; at sila'y sumisigaw sa unahan niya, “Lumuhod kayo!” Sa gayo'y inilagay siya bilang puno sa buong lupain ng Ehipto.
Sila'y inalis ni Jose mula sa kanyang mga tuhod, at iniyuko ang kanyang mukha sa lupa.
At sinasabi ni David, “Ang kanilang hapag nawa'y maging isang silo, isang bitag, isang katitisuran, at isang ganti sa kanila;
Bukod dito, lahat ng mga taga-ibang lupain ay dumating upang bumili ng trigo kay Jose sapagkat matindi ang taggutom sa buong daigdig.
Kanyang kakainin ang anak ng iyong hayop at ang bunga ng iyong lupa, hanggang sa ikaw ay mawasak. Wala ring ititira sa iyong trigo, alak, o langis, ng karagdagan ng iyong bakahan, o ng anak ng iyong kawan, hanggang sa ikaw ay mapuksa niya.
subalit ang mga itinuturing na karapat-dapat makaabot sa panahong iyon at sa muling pagkabuhay mula sa mga patay, ay hindi nag-aasawa o pinag-aasawa.
Ang laman ng handog pangkapayapaan bilang pasasalamat ay kakainin sa araw ng paghahandog nito; hindi siya magtitira nito hanggang sa umaga.
Nang kinakalagan nila ang batang asno, ay sinabi sa kanila ng mga may-ari nito, ‘Bakit ninyo kinakalagan ang batang asno?’
Nang makita ito ng mga alagad ay nagtaka sila, na nagsasabi, “Paanong natuyo kaagad ang puno ng igos?”
At susunugin ng pari bilang bahaging pinakaalaala ang bahagi ng butil na niligis at ang bahagi ng langis, pati ang lahat ng kamanyang niyon; ito ay isang handog sa Panginoon na pinaraan sa apoy.
Kung gayon, ang kautusan ba ay salungat sa mga pangako ng Diyos? Huwag nawang mangyari. Sapagkat kung ibinigay ang isang kautusan na makapagbibigay-buhay, samakatuwid, ang katuwiran ay sa pamamagitan ng kautusan.
At nang masabi niya ito, sila'y hiningahan niya, at sa kanila'y sinabi, “Tanggapin ninyo ang Espiritu Santo.
Sa kabila ng Jordan sa lupain ng Moab, pinasimulan ni Moises na ipaliwanag ang kautusang ito gaya ng sumusunod:
Subalit ang sinumang may mga pag-aari sa sanlibutang ito, at nakikita ang kanyang kapatid na nangangailangan, at pinagsasarhan niya ito ng kanyang damdamin, paanong nananatili ang pag-ibig ng Diyos sa kanya?
Nang magkagayo'y inawit ni Moises at ng mga Israelita ang awit na ito sa Panginoon , na sinasabi, “Ako'y aawit sa Panginoon , sapagkat siya'y maluwalhating nagtagumpay; kanyang inihagis sa dagat ang kabayo at ang doo'y nakasakay.
Nakita ng kanyang mga kapatid na siya'y minahal ng kanilang ama nang higit kaysa lahat niyang mga kapatid; at siya'y kinapootan nila at hindi sila nakipag-usap nang payapa sa kanya.
ni hindi rin naman siya pinaglilingkuran ng mga kamay ng tao, na para bang mayroon siyang kailangan, yamang siya ang nagbibigay sa lahat ng tao ng buhay at ng hininga, at ng lahat ng bagay na ito.
At iniutos ng Panginoong Diyos sa lalaki, na sinabi, “Malaya kang makakakain mula sa lahat ng punungkahoy sa halamanan,
Itaas mo ang iyong tungkod at iunat mo ang iyong kamay sa ibabaw ng dagat, at hawiin mo, upang ang mga anak ni Israel ay makaraan sa tuyong lupa sa gitna ng dagat.
at ng mga Amoreo, Cananeo, Gergeseo, at ng mga Jebuseo.”
At sila'y nagsimulang magtanungan sa isa't isa, kung sino sa kanila ang gagawa nito.
At lumabas ang isang tinig sa trono, na nagsasabi, “Purihin ninyo ang ating Diyos, kayong lahat na mga alipin niya, at kayong natatakot sa kanya, mga hamak at dakila.”
upang kanyang pakabanalin siya, na nilinis sa pamamagitan ng paghuhugas ng tubig sa salita,
“Lahat ng ikasampung bahagi ng lupain, maging sa binhi ng lupain, o sa bunga ng punungkahoy ay sa Panginoon ; ito ay banal sa Panginoon .
Kaya't huwag ninyong paghariin ang kasalanan sa inyong katawang may kamatayan, upang masunod ang mga pagnanasa nito.
Dahil sa paglaganap ng kasamaan, ang pag-ibig ng marami ay lalamig.
upang itaas ka sa lahat ng bansa na kanyang nilikha, sa ikapupuri, sa ikababantog, sa ikararangal; at upang ikaw ay maging isang banal na bayan sa Panginoon mong Diyos, gaya ng kanyang sinabi.”
Inyong sabihin sa aking ama kung paanong ako'y iginagalang sa Ehipto, at ang lahat ng inyong nakita. Magmadali kayo at dalhin ninyo rito ang aking ama.”
Nang hindi ako makakita dahil sa kaningningan ng liwanag na iyon, hinawakan ang aking kamay ng mga kasamahan ko, at dinala ako sa Damasco.
Nang si Arfaxad ay tatlumpu't limang taon, naging anak niya si Shela.
Samantalang siya'y nagsasalita, inanyayahan siya ng isang Fariseo na kumaing kasalo niya. Kaya't siya'y pumasok at naupo sa hapag-kainan.
Mapalad ang alipin na kung dumating ang kanyang panginoon ay maratnan siyang gayon ang kanyang ginagawa.
Kung inaakala ng sinuman na siya'y relihiyoso, subalit hindi pinipigil ang kanyang dila, kundi dinadaya ang kanyang puso, ang relihiyon ng taong iyon ay walang kabuluhan.
Ngunit nalalaman natin na ang kautusan ay mabuti, kung ginagamit ng tao sa matuwid na paraan.
Bagaman, sa Panginoon mong Diyos ang langit, at ang langit ng mga langit, ang lupa, at ng lahat na naroroon,
At nang ang mga sugo ay bumalik na sa bahay, nadatnan nilang magaling na ang alipin.
Sapagkat si Adan ang unang nilalang, pagkatapos ay si Eva;
At mula sa kanyang kapuspusan ay tumanggap tayong lahat, biyaya na sinundan pa ng ibang biyaya.
Ito ang mga anak ni Zibeon: sina Aya at Ana. Ito rin si Ana na nakatagpo ng maiinit na bukal sa ilang, habang kanyang inaalagaan ang mga asno ni Zibeon na kanyang ama.
Pagkatapos, ang lahat ng mga anak ni Israel ay lumapit at kanyang ibinigay sa kanila sa pamamagitan ng utos ang lahat ng salita ng Panginoon na binigkas sa kanya sa bundok ng Sinai.
At sinabi nina Moises at Aaron sa lahat ng mga anak ni Israel, “Pagsapit ng gabi, inyong malalaman na ang Panginoon ang siyang naglabas sa inyo sa lupain ng Ehipto,
Ihaharap iyon ng pari sa harapan ng Panginoon , at ihahandog ang kanyang handog pangkasalanan at ang kanyang handog na sinusunog.
Subalit si Jesus, palibhasa'y nalalaman niya na ang kanyang mga alagad ay nagbubulungan tungkol dito, ay nagsalita sa kanila, “Ito ba ay nakakatisod sa inyo?
Kinabukasan, pagkatapos ng araw ng Paghahanda, ang mga punong pari at ang mga Fariseo ay nagpulong sa harapan ni Pilato,
at dahil sa makapangyarihang kamay at sa dakila at kakilakilabot na ginawa ni Moises sa paningin ng buong Israel.
Muling nagpakita ang Diyos kay Jacob nang siya'y manggaling sa Padan-aram, at siya'y pinagpala.
Pumunta ka kay Faraon kinaumagahan habang siya'y patungo sa tubig. Tumayo ka sa tabi ng ilog upang harapin siya, at ang tungkod na naging ahas ay hawakan mo.
Huwag mong ililitaw ang kahubaran ng asawa ng iyong kapatid na lalaki; siya ay kahubaran ng iyong kapatid na lalaki.
O paano mong nasasabi sa iyong kapatid, ‘Hayaan mong alisin ko ang puwing sa iyong mata,’ samantalang mayroong troso sa iyong sariling mata?
kapag naipaalam na sa kanya ang kasalanang kanyang nagawa, siya ay magdadala ng kanyang handog, isang lalaking kambing na walang kapintasan.
Nang makita siya ni Pedro ay sinabi niya kay Jesus, “Panginoon, at paano naman ang taong ito?”
Sila'y tumindig, ipinagtabuyan siya sa labas ng bayan at dinala siya hanggang sa taluktok ng burol na kinatatayuan ng kanilang bayan, upang siya'y ihulog nila nang patiwarik.
Kung ang sinuman ay patungo sa pagkabihag, sa pagkabihag siya patutungo. Kung ang sinuman ay pumapatay sa pamamagitan ng tabak, sa pamamagitan ng tabak siya dapat papatayin. Ito ay panawagan para sa pagtitiis at pananampalataya ng mga banal.
Ngunit sinabi sa akin ng Panginoon , ‘Huwag kang matakot sa kanya, sapagkat ibinigay ko na siya sa iyong kamay, at ang kanyang buong bayan, at ang kanyang lupain. At gagawin mo sa kanya ang gaya ng ginawa mo kay Sihon na hari ng mga Amoreo, na nanirahan sa Hesbon.’
Nakikita ng inyong mga mata at ng mga mata ng aking kapatid na si Benjamin, na ang bibig ko mismo ang nagsasalita sa inyo.
Sapagkat siya ay itinuring na karapat-dapat sa higit na kaluwalhatian kaysa kay Moises, yamang ang nagtayo ng bahay ay may higit na karangalan kaysa bahay.
Ngayo'y isinasamo ko sa inyo, mga kapatid, na tandaan ninyo ang mga lumilikha ng pagkakabaha-bahagi at ng mga katitisuran na laban sa mga aral na inyong natutunan; lumayo kayo sa kanila.
Ilalagay niya ang insenso sa ibabaw ng apoy sa harapan ng Panginoon upang ang mga usok ng insenso ay tumakip sa luklukan ng awa na nasa ibabaw ng patotoo, upang huwag siyang mamatay.
Sinabi ng isang tinig mula sa langit, “Ito ang minamahal kong Anak, sa kanya ako lubos na nalulugod.”
Ngunit kung siya ay mas dukha kaysa inyong itinakdang katumbas, siya ay patatayuin sa harapan ng pari, at tutumbasan siya ng pari; siya ay tutumbasan ng pari ayon sa kakayahan niya na may panata.
na umakyat sa langit at nasa kanan ng Diyos, na ipinasakop sa kanya ang mga anghel, ang mga kapamahalaan at ang mga kapangyarihan.
Kung tayo nga'y naglalagay ng mga preno sa bibig ng mga kabayo upang sumunod sila sa atin, ibinabaling natin ang kanilang buong katawan.
Mayroon pa akong maraming bagay na sasabihin sa inyo, ngunit hindi ninyo kayang dalhin sa ngayon.
Susunugin mo ang buong tupa sa ibabaw ng dambana; ito ay handog na sinusunog para sa Panginoon . Ito ay mabangong samyo, isang handog sa pamamagitan ng apoy para sa Panginoon .
Kanyang sinabi sa kanila, “Ito ang iniutos ng Panginoon , ‘Bukas ay taimtim na pagpapahinga, banal na Sabbath sa Panginoon . Lutuin ninyo ang inyong lulutuin, at pakuluan ninyo ang inyong pakukuluan; at lahat ng lalabis ay itago ninyo, inyong ititira hanggang sa kinabukasan.’”
At nakita ko ang isa pang anghel na umaakyat mula sa sikatan ng araw, na taglay ang tatak ng Diyos na buháy at siya'y sumigaw nang may malakas na tinig sa apat na anghel na pinagkalooban ng kapangyarihang pinsalain ang lupa at ang dagat,
Bukod sa mga bagay na nasa labas, ako'y araw-araw na nabibigatan sa alalahanin para sa mga iglesya.
Kung inyong patawarin ang mga kasalanan ng sinuman, ang mga iyon ay ipinatatawad sa kanila. Sinumang hindi ninyo patawarin ng mga kasalanan, iyon ay hindi ipinatatawad.”
Nagreklamo ang bayan kay Moises, na sinasabi, “Anong aming iinumin?”
Nalalaman ninyo na pagkatapos, nang nais niyang magmana ng pagpapala, siya'y itinakuwil sapagkat wala na siyang natagpuang pagkakataon upang magsisi, bagama't pinagsikapan niya iyon na may pagluha.
Huwag magkakaroon ng sinumang tao sa toldang tipanan kapag siya'y pumasok upang gumawa ng pagtubos sa loob ng dakong banal hanggang sa lumabas siya at matubos ang sarili, at ang kanyang kasambahay, at ang buong kapulungan ng Israel.
Kung siya'y mamanata sa bahay ng kanyang asawa, o kanyang itinali ang kanyang sarili sa isang pananagutan na kaakbay ng isang sumpa,
at ang mga anak ni Zilpa na alilang babae ni Lea: sina Gad at Aser. Ito ang mga anak ni Jacob na ipinanganak sa kanya sa Padan-aram.
At kapag nakalapag ay kanyang sinasabi, “Bumalik ka, O Panginoon ng laksang libu-libong Israelita.”
Subalit kapag nakarinig kayo ng mga digmaan at ng mga bali-balita ng mga digmaan, huwag kayong mabahala. Ang mga bagay na ito'y dapat mangyari ngunit hindi pa iyon ang wakas.
Kaya't isinama ni Moises ang kanyang asawa at ang kanyang mga anak; kanyang pinasakay sila sa isang asno at siya'y bumalik sa lupain ng Ehipto. Dinala ni Moises ang tungkod ng Diyos sa kanyang kamay.
Subalit kung hindi niya labhan ang mga iyon, ni paliguan ang kanyang katawan, ay tataglayin niya ang kanyang kasalanan.”
At sinabi ng mga hangal sa matatalino, ‘Bigyan ninyo kami ng inyong langis, sapagkat namamatay na ang aming mga ilawan.’
Si Jesus, pagtingin sa kanya ay minahal siya at sinabi, “Isang bagay ang kulang sa iyo. Humayo ka, ipagbili mo ang lahat at ibigay mo ang salapi sa dukha, at magkakaroon ka ng kayamanan sa langit. At pumarito ka, sumunod ka sa akin.”
At ang mga balat ng mga batang kambing ay ibinalot sa kanyang mga kamay, at sa makinis na bahagi ng kanyang leeg.
Ang inyong mga bangkay ay mabubuwal sa ilang na ito; at ang lahat na nabilang sa inyo ayon sa inyong kabuuang bilang, mula sa dalawampung taong gulang pataas na nagreklamo laban sa akin,
Sinumang nagsasalita ay gawin iyon nang tulad sa nagsasalita ng mga aral ng Diyos; sinumang naglilingkod ay tulad sa naglilingkod mula sa kalakasang ibinibigay ng Diyos, upang ang Diyos ay maluwalhati sa lahat ng mga bagay sa pamamagitan ni Jesu-Cristo. Sa kanya ang kaluwalhatian at ang kapangyarihan magpakailanman. Amen.
Pinalapit naman ang mga anak ni Aaron, at nilagyan ni Moises ng dugo ang dulo ng kanilang kanang tainga, ang hinlalaki ng kanilang kanang kamay at ng kanang paa; at iwinisik ni Moises ang dugo sa palibot ng dambana.
“Igagawa mo ng mga patayong haligi ang tabernakulo mula sa kahoy na akasya.
Sa lugar ng pinagpakuan sa kanya ay may isang halamanan, at sa halamana'y may isang bagong libingan na kailanma'y hindi pa nalalagyan ng sinuman.
Nagkataon na nakaratay ang ama ni Publio na maysakit na lagnat at disenteriya. Pinuntahan siya ni Pablo at nanalangin, at nang maipatong sa kanya ang kanyang mga kamay ay pinagaling siya.
Dumating nang oras ding iyon ang ilang Fariseo na nagsabi sa kanya, “Lumabas ka na at umalis dito, sapagkat ibig kang patayin ni Herodes.”
Pagkaraan ng isang sandali ay nakita siya ng isa pa at sinabi, “Ikaw ay isa rin sa kanila.” Subalit sinabi ni Pedro, “Ginoo, hindi ako.”
Kapayapaan ang iniiwan ko sa inyo, ang aking kapayapaan ay ibinibigay ko sa inyo. Hindi gaya ng ibinibigay ng sanlibutan ang ibinibigay ko sa inyo. Huwag mabagabag ang inyong puso, o matakot man.
Nang makita ni Jesus na siya'y sumagot na may katalinuhan, sinabi niya sa kanya, “Hindi ka malayo sa kaharian ng Diyos.” Pagkatapos noon, wala nang nangahas na magtanong pa sa kanya ng anuman.
Ako ang Alpha at ang Omega, ang una at ang huli, ang pasimula at ang wakas.”
Sapagkat kayo'y sumuway sa akin sa gitna ng mga anak ni Israel sa tubig ng Meriba ng Kadesh, sa ilang ng Zin; sapagkat hindi ninyo ako itinuring na banal sa gitna ng mga anak ni Israel.
Mula kay Kohat ang angkan ng mga Amramita at mga Izarita, at mga Hebronita, at mga Uzielita. Ito ang mga angkan ng mga Kohatita.
Si Moises at ang mga paring Levita ay nagsalita sa buong Israel, na sinasabi, “Tumahimik ka at pakinggan mo, O Israel; sa araw na ito ay naging bayan ka ng Panginoon mong Diyos.
Ngunit nang maghabol si Pablo na siya'y bantayan para sa pasiya ng emperador, ay ipinag-utos kong bantayan siya hanggang sa siya'y maipadala ko kay Cesar.”
Kaya't magsisi ka. Kung hindi, madali akong darating sa iyo, at didigmain ko sila ng tabak ng aking bibig.
Tumanaw si Jacob at nakita niyang si Esau ay dumarating na may kasamang apatnaraang katao. Kaya't kanyang pinaghiwalay ang mga bata kina Lea at Raquel, at sa dalawang aliping babae.
Ang huli ay gumagawa dahil sa pag-ibig, palibhasa'y nalalaman na ako'y itinalaga sa pagtatanggol sa ebanghelyo;
Hindi ba silang lahat ay mga espiritung nasa banal na gawain, na sinugo upang maglingkod sa kapakanan ng mga magmamana ng kaligtasan?
Pitong araw na kakain kayo ng tinapay na walang pampaalsa, at sa ikapitong araw ay magkakaroon ng isang kapistahan sa Panginoon .
Ngunit kung iiwasan mong gumawa ng panata, ito ay hindi magiging kasalanan sa iyo.
subalit siya ay nasa ilalim ng mga tagapangalaga at mga katiwala hanggang sa panahong itinakda ng ama.
Ngunit ngayon, kung maaari ay patawarin mo ang kanilang kasalanan—at kung hindi, ay burahin mo ako sa aklat na isinulat mo.”
Pagkatapos nito, siya'y nagtungo sa bawat lunsod at mga nayon na ipinangangaral at ipinahahayag ang magandang balita ng kaharian ng Diyos. Kasama niya ang labindalawa,
Ngunit ayaw kong gumawa ng anuman na wala kang pahintulot upang ang iyong kabutihang-loob ay hindi maging sapilitan kundi ayon sa sarili mong kalooban.
“Sabihin mo sa mga anak ni Israel, Ang naghahandog sa Panginoon ng handog pangkapayapaan ay magdadala sa Panginoon ng handog na mula sa kanyang mga handog pangkapayapaan.
Kaya't may natitira pang isang pamamahingang Sabbath para sa bayan ng Diyos.
Pagkatapos niyang mailibing ang kanyang ama, bumalik si Jose sa Ehipto, kasama ang kanyang mga kapatid at ang lahat ng umalis na kasama niya sa paglilibing sa kanyang ama.
At nagsalita ang Panginoon kay Moises sa bundok ng Sinai, na sinasabi,
Sinabi niya sa kanila, “Ganito ang sabi ng Panginoong Diyos ng Israel, ‘Ilagay ng bawat lalaki ang kanyang tabak sa kanyang tagiliran. Humayo kayong paroo't parito sa mga pintuan sa buong kampo, at patayin ng bawat lalaki ang kanyang kapatid na lalaki, ng bawat lalaki ang kanyang kasama, at ng bawat lalaki ang kanyang kapwa.’”
Sinabi sa kanya ni Simon Pedro, “Panginoon, hindi ang aking mga paa lamang, kundi pati ang aking mga kamay at ang aking ulo.”
upang kayo na may isang pag-iisip sa pamamagitan ng isang bibig ay luwalhatiin ninyo ang Diyos at Ama ng ating Panginoong Jesu-Cristo.
Kaya't sila'y dumampot ng mga bato upang ibato sa kanya, subalit nagtago si Jesus at lumabas sa templo.
Hindi siya nakagawa roon ng anumang makapangyarihang gawa, maliban sa ipinatong niya ang kanyang mga kamay sa ilang mga maysakit at pinagaling sila.
Hindi, sapagkat siya'y aking pinili upang kanyang tagubilinan ang kanyang mga anak at sambahayan pagkamatay niya, na maingatan ang daan ng Panginoon sa pamamagitan ng paggawa ng kabanalan at kahatulan; upang maibigay ng Panginoon kay Abraham ang ipinangako niya sa kanya.”
Sapagkat sinumang mayroon ay lalong bibigyan, at magkakaroon siya ng kasaganaan; ngunit sinumang wala, pati ang nasa kanya ay kukunin.
Tiyakin ninyo na ang sinuman ay huwag gumanti ng masama sa masama, kundi lagi ninyong naisin ang mabuti para sa isa't isa at sa lahat.
At nagkataong bumababa sa daang iyon ang isang pari. Nang kanyang makita ito, siya ay dumaan sa kabilang panig.
At pagkatanaw niya sa malayo ng isang puno ng igos na may mga dahon, lumapit siya upang tingnan kung may matatagpuan siya roon. At nang siya'y makalapit doon, wala siyang natagpuang anuman kundi mga dahon, sapagkat hindi pa panahon ng mga igos.
Itinaas ni Aaron ang kanyang mga kamay paharap sa taong-bayan at binasbasan sila. Bumaba siya pagkatapos ng paghahandog ng handog pangkasalanan, ng handog na sinusunog, at ng mga handog pangkapayapaan.
Ayon sa bilang ng inyong ihahanda, ay gayon ninyo gagawin sa bawat isa ayon sa kanilang bilang.
At kung ang daan ay napakahaba para sa iyo, na anupa't hindi mo madala ang ikapu kapag pinagpala ka ng Diyos, sapagkat napakalayo sa iyo ang dakong pinili ng Panginoon mong Diyos na paglalagyan ng kanyang pangalan,
sila, at bawat mailap na hayop ayon sa kani-kanilang uri, bawat maamong hayop ayon sa kani-kanilang uri, bawat gumagapang sa ibabaw ng lupa ayon sa kanilang uri, at bawat ibon ayon sa kanilang uri, lahat ng sari-saring ibon.
At sinabi ng anghel ng Panginoon kay Balaam, “Sumama ka sa mga lalaki ngunit ang salita lamang na aking sasabihin sa iyo ang siyang sasabihin mo.” Kaya't sumama si Balaam sa mga pinuno ni Balak.
Kahit nakikiusap siya kay Jose araw-araw, ay hindi siya pumayag na siya'y sumiping o makisama sa kanya.
Kahit kailangan mong umalis sapagkat nasasabik ka na sa bahay ng iyong ama, bakit mo ninakaw ang aking mga diyos?”
At ang iba'y nahulog sa mga tinikan, at ang mga tinik ay tumubong kasama nito at ito'y sinakal.
At ang bunso ay nanganak din ng isang lalaki, at tinawag sa pangalang Benammi na siyang ama ng mga anak ni Ammon hanggang sa araw na ito.
Ang mga lalaki ay natakot sapagkat sila'y dinala sa bahay ni Jose, at sinabi nila, “Dinala tayo rito dahil sa salaping isinauli sa ating mga sako noon, upang magkaroon siya ng pagkakataong dakpin tayo, at tayo'y kunin bilang mga alipin, pati ang ating mga asno.”
Sinabi niya, “Dalhin mo na sa akin upang makakain ako ng usa ng aking anak, upang mabasbasan ka.” Inilapit niya ito sa kanya at kumain siya, at siya'y dinalhan niya ng alak, at siya'y uminom.
Tumindig si Abraham sa harap ng kanyang patay at nagsalita sa mga anak ni Het,
Gayon niya lilinisin ang bahay sa pamamagitan ng dugo ng ibon, ng agos ng tubig, ng ibong buháy, ng kahoy na sedro, ng isopo, at ng pulang sinulid;
Sinabi ng Panginoon kay Moises, “Iunat mo ang iyong kamay paharap sa langit, upang magdilim sa lupain ng Ehipto ng isang kadilimang mararamdaman.”
Hindi niya ito sinabi mula sa kanyang sarili, kundi bilang pinakapunong pari nang panahong iyon siya'y nagpropesiya na si Jesus ay mamamatay para sa bansa;
Ang ikalabinlimang araw ng buwang ito ay Kapistahan ng Tinapay na Walang Pampaalsa sa Panginoon . Kakain kayo ng tinapay na walang pampaalsa sa loob ng pitong araw.
Ang handog na butil ng mga iyon, na piling harina na hinaluan ng langis, ay tatlong ikasampung bahagi para sa toro, dalawang ikasampung bahagi para sa isang lalaking tupa,
At kanyang iginawa iyon ng apat na haliging akasya, at binalot ang mga ito ng ginto, ang kanilang mga kawit ay ginto rin at naghulma siya para sa mga ito ng apat na patungang pilak.
Ngunit sinasabi ko sa inyo, ‘Huwag ninyong labanan ang masamang tao.’ At kung ikaw ay sampalin ng sinuman sa kanang pisngi, iharap mo rin sa kanya ang kabila.
At aling dakilang bansa ang may mga tuntunin at mga batas na napakatuwid na gaya ng buong kautusang ito na aking inilagay sa harapan ninyo sa araw na ito?
Nang magising ang bantay ng bilangguan at makitang bukas ang mga pinto ng bilangguan, binunot niya ang kanyang tabak at magpapakamatay na sana dahil sa pag-aakalang nakatakas ang mga bilanggo.
Minahal ni Israel si Jose nang higit kaysa lahat niyang anak, sapagkat siya ang anak ng kanyang katandaan at siya'y gumawa ng isang mahabang damit na kanyang suot.
Nang panahong iyon, inilapat ni Herodes ang kanyang mga kamay upang pagmalupitan ang ilan sa mga kaanib ng iglesya.
Walang aliping makapaglilingkod sa dalawang panginoon, sapagkat kapopootan niya ang isa, at iibigin ang ikalawa, o kaya'y magiging tapat sa isa at hahamakin ang ikalawa. Hindi kayo makapaglilingkod sa Diyos at sa mga kayamanan.”
Sila'y umuwi at naghanda ng mga pabango at mga panghaplos. At nang araw ng Sabbath sila'y nagpahinga ayon sa kautusan.
At sumagot siya, “Katotohanang sinasabi ko sa iyo, ngayon ikaw ay makakasama ko sa Paraiso.”
Subalit hindi gayon sa inyo, ngunit ang sinumang ibig na maging dakila sa inyo ay kailangang maging lingkod ninyo;
Subalit umasa kami na siya ang tutubos sa Israel. Oo, at bukod sa lahat ng mga ito, ngayon ang ikatlong araw buhat nang mangyari ang mga bagay na ito.
Ako'y namamangha na napakabilis ninyong iniwan siya na tumawag sa inyo sa biyaya ni Cristo at bumaling kayo sa ibang ebanghelyo.
Nang aming matapos na ang paglalakbay buhat sa Tiro, dumating kami sa Tolemaida; at binati namin ang mga kapatid at kami'y nanatiling kasama nila ng isang araw.
Kaya't alalahanin mo kung paano mo ito tinanggap at narinig; tuparin mo ito at magsisi ka. Kaya't kung hindi ka gigising, darating akong gaya ng magnanakaw, at hindi mo malalaman kung anong oras ako darating sa iyo.
Ni huwag kayong patawag na mga tagapagturo; sapagkat iisa ang inyong tagapagturo, ang Cristo.
Subalit kung sasabihin natin, ‘Mula sa mga tao,’ ay babatuhin tayo ng mga taong-bayan, sapagkat sila'y napapaniwala na si Juan ay isang propeta.”
Ngunit inudyukan ng mga hindi nananampalatayang Judio ang mga Hentil, at nilason ang kanilang isipan laban sa mga kapatid.
Natagpuan niya roon ang isang Judio na ang pangalan ay Aquila, isang lalaking tubong Ponto, na kararating pa lamang mula sa Italia, kasama si Priscila na kanyang asawa, sapagkat ipinag-utos ni Claudio na ang lahat ng Judio ay umalis sa Roma. Pumunta si Pablo sa kanila;
baka sakaling kung ang ilang taga-Macedonia ay dumating na kasama ko at kayo'y maratnang hindi handa, kami ay mapapahiya upang hindi na namin sabihing pati kayo, sa pagtitiwalang ito.
At ang Panginoon ay nagpakita ng mga tanda at ng mga kababalaghan, dakila at matindi, laban sa Ehipto, kay Faraon, at sa kanyang buong sambahayan, sa harapan ng aming paningin;
Sapagkat sa ano kayo naging huli sa ibang mga iglesya, maliban sa ako'y hindi naging pasanin ninyo? Patawarin ninyo ako sa pagkakamaling ito.
Kaya, alang-alang kay Cristo, ako'y nasisiyahan sa mga kahinaan, paglait, kahirapan, pag-uusig, at mga sakuna, sapagkat kapag ako'y mahina, ako nga'y malakas.
Subalit ang maniningil ng buwis, na nakatayo sa malayo ay ayaw itingin man lamang ang kanyang mga mata sa langit, kundi dinadagukan ang kanyang dibdib, na nagsasabi, ‘Diyos, mahabag ka sa akin na isang makasalanan.’
Kanilang iginawa ang efod ng mga pambalikat, na magkakabit sa dalawang dulo.
Kanyang inilagay ang ilawan sa toldang tipanan, sa tapat ng hapag, sa gawing timog ng tabernakulo.
Tumakbo ang alipin upang salubungin siya at sinabi, “Makikiinom ako ng kaunting tubig sa iyong banga.”
At sina Moises at Aaron ay pumunta sa harapan ng toldang tipanan.
ni ang kataasan, ni ang kalaliman, ni ang alin pa mang nilalang, ay hindi makapaghihiwalay sa atin sa pag-ibig ng Diyos, na na kay Cristo Jesus na Panginoon natin.
Nagsugo siya ng isa pa at ito'y kanilang pinatay; gayundin sa marami pang iba. Binugbog ang ilan at ang iba'y pinatay.
Sinabi ng kaaway, ‘Aking hahabulin, aking aabutan, Hahatiin ko ang samsam, ang aking nais sa kanila ay masisiyahan, aking bubunutin ang aking tabak, lilipulin sila ng aking kamay.’
“Huwag mong hahayaang maligaw ang baka ng iyong kapatid o ang kanyang tupa, o ikaw ay magkait ng tulong sa kanila; ibabalik mo ang mga iyon sa iyong kapatid.
ay kanyang sinabi sa kanila, “Ilagay ninyo sa puso ang lahat ng mga salita na aking pinapatotohanan sa inyo sa araw na ito, na inyong iuutos sa inyong mga anak upang gawin ang lahat ng mga salita ng kautusang ito.
Mga ama, kayo'y sinusulatan ko, sapagkat inyong nakilala siyang nagbuhat pa nang pasimula. Mga kabataang lalaki, kayo'y sinusulatan ko sapagkat inyong dinaig ang masama.
Sinabi naman nila sa kanya, “Ano ngayon ang tanda na iyong ginagawa na aming makikita upang sumampalataya kami sa iyo? Ano ang iyong ginagawa?
na sinasabi, “Ako'y nagkasala sa pagkakanulo ko sa dugong walang sala.” Ngunit sinabi nila, “Ano iyon sa amin? Ikaw ang bahala diyan.”
Sinabi sa kanila ni Jesus, “Kung ang Diyos ang inyong ama, ay inibig ninyo sana ako, sapagkat ako'y nagmula sa Diyos at ngayon ay naririto ako. Hindi ako naparito mula sa aking sarili kundi sinugo niya ako.
Nang hindi sumikat sa amin ang araw ni ang mga bituin man nang maraming araw, at humahampas pa rin sa amin ang isang malakas na bagyo, nawala ang buong pag-asa naming makakaligtas.
Pagpalain ninyo ang mga umuusig sa inyo; pagpalain ninyo, at huwag ninyong sumpain.
Nang matanda na si Isaac, malabo na ang kanyang mga mata at anupa't hindi na makakita. Tinawag niya si Esau na kanyang panganay at sinabi sa kanya, “Anak ko.” At kanyang sinabi, “Narito ako.”
Sapagkat ito'y sinasabi namin sa inyo sa pamamagitan ng salita ng Panginoon, na tayong nabubuhay, na natitira hanggang sa pagdating ng Panginoon, ay hindi mauuna sa anumang paraan sa mga natutulog.
at kasama ng unang kordero ang ikasampung bahagi ng mainam na harina na may halong ikaapat na bahagi ng isang hin ng langis na hinalo; at ang ikaapat na bahagi ng isang hin na alak, ang handog na inumin.
na naglilingkod sa Panginoon ng buong kapakumbabaan at may luha, at may mga pagsubok na dumating sa akin dahil sa mga pagtatangka ng mga Judio.
gaya nang ginawa sa akin ng mga anak ni Esau na naninirahan sa Seir, at ng mga Moabita na naninirahan sa Ar, hanggang makatawid ako sa Jordan, sa lupaing ibinibigay sa amin ng Panginoon naming Diyos.’
Sinabi ni Moises sa bayan, “Huwag kayong matakot, sapagkat ang Diyos ay naparito upang subukin kayo, at upang ang takot sa kanya ay sumainyo, upang huwag kayong magkasala.”
At sumagot si Jesus sa kanya, “Nasusulat, ‘Sambahin mo ang Panginoon mong Diyos, at siya lamang ang iyong paglingkuran.’”
Pumasok din ang alagad na unang dumating sa libingan at kanyang nakita at siya'y naniwala.
Sa katapusan ng dalawang taon, ang Faraon ay nanaginip na siya'y nakatayo sa tabi ng Nilo.
Sinabi sa kanila ni Jose, “Iyan ang sinabi ko sa inyo, ‘Kayo'y mga espiya!’
Kaya nang mahugasan niya ang kanilang mga paa, at makuha ang kanyang mga damit at muling maupo, ay sinabi niya sa kanila, “Nalalaman ba ninyo kung ano ang ginawa ko sa inyo?
At sumagot sa kanya si Jesus, “Nasusulat, ‘Ang tao ay hindi nabubuhay sa tinapay lamang.’”
O Makatarungang Ama, hindi ka nakikilala ng sanlibutan, ngunit nakikilala kita, at nakikilala ng mga ito na ikaw ang nagsugo sa akin.
Kayo'y magkakaroon ng isang batas sa kanya na nagkasala nang hindi sinasadya, sa kanya na katutubo sa bayan ng Israel, at sa dayuhan na nakikipamayan sa kanila.
Pagkatapos ay lumabas ang kanyang kapatid, at ang kanyang kamay ay nakakapit sa sakong ni Esau; kaya't ang ipinangalan sa kanya ay Jacob. Si Isaac ay may animnapung taon na nang sila'y ipanganak ni Rebecca.
Ito ay kakainin sa araw na ito na inialay, o sa kinabukasan. Ang nalabi sa ikatlong araw ay susunugin sa apoy.
At sinabi niya sa kanya, “Ang lahat ng mga ito ay ibibigay ko sa iyo, kung ikaw ay magpapatirapa at sasamba sa akin.”
Nalalaman ko na ang kanyang utos ay buhay na walang hanggan. Kaya't ang mga bagay na sinasabi ko ay aking sinasabi ayon sa sinabi ng Ama.”
Pagkaraan ng limang araw, ang pinakapunong pari na si Ananias ay lumusong na kasama ang ilang matatanda, at ang isang Tertulio na tagapagsalita na siyang nagharap ng sakdal sa gobernador laban kay Pablo.
At nagpagaling siya ng maraming iba't ibang may karamdaman at nagpalayas siya ng maraming demonyo. Hindi niya pinahintulutang magsalita ang mga demonyo, sapagkat siya'y kilala nila.
At ikaw, bakit mo hinahatulan ang iyong kapatid? O ikaw naman, bakit hinahamak mo ang iyong kapatid? Sapagkat tayong lahat ay tatayo sa harapan ng hukuman ng Diyos.
Maging sa inyong kautusan ay nasusulat na ang patotoo ng dalawang tao ay totoo.
Muling nagkaila si Pedro at kaagad tumilaok ang isang manok.
Pakabanalin mo ang mga iyon upang maging kabanal-banalan; sinumang humawak sa mga iyon ay magiging banal.
Batiin din ninyo ang iglesya na nasa kanilang bahay. Batiin ninyo si Epeneto na minamahal ko, na siyang unang nahikayat kay Cristo sa Asia.
(kahit hindi nagbabautismo si Jesus, kundi ang kanyang mga alagad)
Ngunit ito ang mabuti na nasa iyo: kinapopootan mo ang mga gawa ng mga Nicolaita na kinapopootan ko rin.
Ngunit ikaw ay maging matino sa lahat ng mga bagay, magtiis ka ng mga kahirapan, gampanan mo ang gawain ng isang ebanghelista, ganapin mong lubos ang iyong ministeryo.
Hindi itinakuwil ng Diyos ang kanyang bayan na nang una pa'y kilala na niya. O hindi ba ninyo nalalaman ang sinasabi ng kasulatan tungkol kay Elias? Kung paanong nagmakaawa siya sa Diyos laban sa Israel?
Kapwa sila dinala ni Jose, si Efraim sa kanyang kanang kamay patungo sa kaliwang panig ni Israel, at si Manases sa kanyang kaliwang kamay patungo sa kanang panig ni Israel, at kanyang inilapit sila sa kanya.
inilagay niya ang sanggol sa kanyang mga bisig, pinuri ang Diyos, at sinabi,
“At sa pananalangin ay huwag kayong gumamit ng walang kabuluhang paulit-ulit, na tulad ng ginagawa ng mga Hentil, sapagkat inaakala nilang sila ay pakikinggan dahil sa marami nilang salita.
Siya'y nagsunog doon ng mabangong insenso; gaya ng iniutos ng Panginoon kay Moises.
At sinabi ni Jose sa kanyang mga kapatid, “Ako'y malapit nang mamatay; ngunit kayo'y tiyak na dadalawin ng Diyos, at dadalhin kayo mula sa lupaing ito hanggang sa lupain na kanyang ipinangako kina Abraham, Isaac at Jacob.”
Sapagkat hindi ang mga tagapakinig ng kautusan ang siyang ganap sa harapan ng Diyos, kundi ang tumutupad sa kautusan ay aariing-ganap.
Ang mga haligi ay apat, at ang mga patungan ay apat, tanso; ang mga kawit ay pilak, at ang mga balot ng itaas nito, at ang mga panali ay pilak.
Ama, nais kong ang mga ibinigay mo sa akin ay makasama ko kung saan ako naroroon, upang makita nila ang kaluwalhatiang ibinigay mo sa akin, sapagkat ako'y iyong minahal bago pa natatag ang sanlibutan.
Paliwanagin ninyo nang gayon ang inyong ilaw sa harap ng mga tao; upang makita nila ang inyong mabubuting gawa, at luwalhatiin nila ang inyong Ama na nasa langit.
Kanyang sinabi, “Sumumpa ka sa akin;” at sumumpa siya sa kanya. At yumuko si Israel sa ulunan ng kanyang higaan.
na nagsabi, “Kayong mga lalaking taga-Galilea, bakit kayo'y nakatayong tumitingin sa langit? Itong si Jesus, na dinala sa langit mula sa inyo ay darating na gaya rin ng inyong nakitang pagpunta niya sa langit.”
Nang mabalitaan niya na si Lazaro ay may sakit, siya'y nanatili ng dalawang araw pa sa dating lugar na kinaroroonan niya.
Sa kanya'y nakikipag-usap ako nang harapan, nang maliwanag, at hindi sa malabong salitaan; at ang anyo ng Panginoon ay kanyang nakikita. Bakit hindi kayo natakot na magsalita laban sa aking lingkod na si Moises?”
Nangingilin kayo ng mga araw, mga buwan, mga panahon, at mga taon.
Muling sinabi sa kanila ni Jesus, “Kapayapaan ang sumainyo. Kung paanong sinugo ako ng Ama ay sinusugo ko rin naman kayo.”
Nabalitaan ng mga apostol at ng mga kapatid na nasa Judea na tinanggap din ng mga Hentil ang salita ng Diyos.
Nang ikatlo ng hapon ay sumigaw si Jesus nang may malakas na tinig, “Eloi, Eloi, lama sabacthani?” na ang kahulugan ay, “Diyos ko, Diyos ko, bakit mo ako pinabayaan?”
Kundi kami ay naging malumanay sa gitna ninyo, gaya ng isang ina na nag-aaruga sa kanyang mga anak.
Ito'y magiging alituntuning walang hanggan sa inyo, na tubusin ang mga anak ni Israel minsan sa isang taon dahil sa lahat nilang mga kasalanan.” At ginawa ni Moises ang ayon sa iniutos ng Panginoon .
Subalit dumating ang Diyos kay Laban na Arameo sa panaginip sa gabi, at sinabi sa kanya, “Ingatan mong huwag kang magsalita kay Jacob ng mabuti o masama man.”
kapag pinakinggan mo ang tinig ng Panginoon mong Diyos, at iyong sinunod ang lahat ng kanyang mga utos na aking iniuutos sa iyo sa araw na ito, at iyong ginawa ang matuwid sa paningin ng Panginoon mong Diyos.
Nang ang ulat ay naibalita sa sambahayan ng Faraon, “Dumating na ang mga kapatid ni Jose,” ito ay minabuti ni Faraon at ng kanyang mga lingkod.
Pagkatapos ay dinala siya ng mga kawal sa bulwagan na siyang Pretorio; at kanilang tinipon ang buong batalyon.
Sina Nadab at Abihu ay namatay nang sila'y maghandog ng kakaibang apoy sa harap ng Panginoon .
Kaya't nagbalik si Esau nang araw ding iyon sa kanyang lakad patungo sa Seir.
Walang anu-ano'y inaalihan siya ng isang espiritu at biglang nagsisigaw. Siya'y pinangingisay nito hanggang sa bumula ang kanyang bibig, at siya'y binubugbog, at halos ayaw siyang hiwalayan.
Nang makita siya ni Juda ay inakalang siya'y upahang babae, sapagkat nagtakip ng kanyang mukha.
Sapagkat kung silang nasa kautusan ang siyang mga tagapagmana, walang kabuluhan ang pananampalataya, at pinawawalang saysay ang pangako.
sinabi rin niya, “At ang kanilang mga kasalanan at mga kasamaan ay hindi ko na aalalahanin pa.”
Sapagkat nang kayo ay mga alipin pa ng kasalanan, kayo'y malalaya tungkol sa pagiging matuwid.
Siya'y maghahari sa sambahayan ni Jacob magpakailanman at hindi magwawakas ang kanyang kaharian.”
Sa panahon ng inyong pag-aani ay ibibigay ninyo ang ikalimang bahagi sa Faraon, at ang apat na bahagi ay para sa inyo, para sa binhi sa bukid at bilang pagkain ninyo, ng inyong mga kasambahay, at ng inyong mga anak.”
Kaya't si Moises ay lumabas, at sinabi sa bayan ang mga salita ng Panginoon . Siya'y nagtipon ng pitumpung lalaki sa matatanda sa bayan at kanyang pinatayo sa palibot ng tolda.
Pagkatapos ay kinuha niya ang taba, ang matabang buntot, at ang lahat ng tabang bumabalot sa lamang-loob, ang lamad ng atay, ang dalawang bato kasama ang taba ng mga iyon, at ang kanang hita.
Pagkatapos ay susuguin niya ang mga anghel at titipunin ang kanyang mga hinirang mula sa apat na hangin, mula sa mga dulo ng lupa hanggang sa mga dulo ng langit.
“Ngunit kapag nakita ninyo ang karumaldumal na paglapastangan na nakatayo sa dakong hindi niya dapat kalagyan (unawain ng bumabasa), kung magkagayo'y dapat nang tumakas sa mga bundok ang mga nasa Judea.
subalit isang bagay ang kailangan. Pinili ni Maria ang mabuting bahagi na hindi kukunin sa kanya.”
“‘Ni huwag kang sasaksi sa kasinungalingan laban sa iyong kapwa.
Ang umiibig sa kanyang kapatid ay nananatili sa liwanag, at sa kanya'y walang anumang kadahilanang ikatitisod.
“Kapag ikaw ay lalabas sa kampo laban sa iyong mga kaaway, lalayo ka sa bawat masamang bagay.
At habang nagsasalita pa siya, dumating si Judas, na isa sa labindalawa, at kasama niya ang napakaraming tao na may mga tabak at mga pamalo, mula sa mga punong pari at sa matatanda ng bayan.
Gayundin sa araw ng mga unang bunga, sa paghahandog ninyo ng handog na bagong butil sa Panginoon sa inyong pista ng mga sanlinggo, ay magkakaroon kayo ng isang banal na pagtitipon, huwag kayong gagawa ng anumang mabigat na gawain,
Sapagkat tayo'y kanilang dinidisiplina nang maikling panahon ayon sa kanilang minamabuti, ngunit dinidisiplina niya tayo alang-alang sa ikabubuti natin, upang tayo'y makabahagi sa kanyang kabanalan.
Mula sa kanila ay makakain ninyo ang mga ito: ang balang ayon sa kanyang uri; ang lukton ayon sa kanyang uri, ang kuliglig ayon sa kanyang uri, at ang tipaklong ayon sa kanyang uri.
Nang marinig ito ni Moises, siya ay nagpatirapa;
At nakita ko ang mga patay, mga dakila at mga hamak, na nakatayo sa harapan ng trono, at binuksan ang mga aklat. Binuksan din ang isa pang aklat, ang aklat ng buhay. At ang mga patay ay hinatulan ayon sa kanilang mga gawa, ayon sa nakatala sa mga aklat.
Sapagkat sino sa lahat ng laman na nakarinig ng tinig ng buháy na Diyos na nagsasalita mula sa gitna ng apoy, na gaya namin, at nabuhay pa?
Ito ang bagay na iniutos ng Panginoon , ‘Pumulot ang bawat tao ayon sa kanyang kailangan, isang omer para sa bawat tao ayon sa bilang ng mga tao, na mayroon ang bawat isa sa kanilang mga tolda.’”
At iyong sasabihin sa mga anak ni Israel, “Kung ang isang lalaki ay mamatay at walang anak na lalaki, inyong isasalin ang kanyang mana sa kanyang anak na babae.
Ang mga anak ni Izar: si Kora, si Nefeg, at si Zicri.
Gayon ipinahayag ni Moises ang mga takdang kapistahan ng Panginoon sa bayan ng Israel.
Ganito rin kayo maghahandog ng handog sa Panginoon sa inyong buong ikasampung bahagi, na inyong tinatanggap sa mga anak ni Israel; at ganito ninyo ibibigay sa paring si Aaron ang handog sa Panginoon .
Sapagkat ang kaisipan ng laman ay pagkapoot laban sa Diyos; sapagkat hindi ito napapasakop sa kautusan ng Diyos, ni hindi nga maaari;
Ngunit tungkol sa pag-iibigan ng magkakapatid ay hindi ninyo kailangan na kayo'y sulatan ng sinuman, sapagkat kayo man ay tinuruan ng Diyos na mag-ibigan sa isa't isa.
“Ang isang anak sa labas ay hindi maaaring pumasok sa kapulungan ng Panginoon ; kahit na hanggang sa ikasampung salinlahi ay walang papasok sa kanyang mga anak sa kapulungan ng Panginoon .
Subalit ang taba, ang mga bato, at ang lamad na nasa atay ng handog pangkasalanan ay sinunog niya sa ibabaw ng dambana, gaya ng iniutos ng Panginoon kay Moises.
At siya'y lumapit sa kanyang ama at sinabi, “Ama ko;” at sinabi niya, “Narito ako; sino ka, anak ko?”
“Sabihin mo sa mga anak ni Israel: Kapag ang isang tao ay nagkasala nang hindi sinasadya sa alinman sa mga iniutos ng Panginoon tungkol sa mga bagay na hindi dapat gawin, at nakagawa ang alinman sa mga ito:
Subalit alalahanin ninyo ang mga nakaraang araw, na pagkatapos na kayo'y maliwanagan, ay nagtiis kayo ng matinding pakikipaglaban na may pagdurusa,
Pagkatapos ay lumapit nang sarilinan ang mga alagad kay Jesus at sinabi nila, “Bakit hindi namin iyon napalayas?”
At sinabi niya kay Tomas, “Ilagay mo rito ang iyong daliri at tingnan mo ang aking mga kamay. Ilapit mo rito ang iyong kamay at ilagay mo sa aking tagiliran. Huwag kang mag-alinlangan kundi sumampalataya.”
Subalit ang lahat ng tumanggap sa kanya na sumasampalataya sa kanyang pangalan ay kanyang pinagkalooban sila ng karapatan na maging mga anak ng Diyos,
Sapagkat ang aming ebanghelyo ay hindi dumating sa inyo sa salita lamang, kundi sa kapangyarihan din at sa Espiritu Santo at sa lubos na pagtitiwala, kung paanong nalalaman ninyo kung anong pagkatao ang aming pinatunayan sa inyo alang-alang sa inyo.
Pagkatapos ng maraming talakayan, tumindig si Pedro at sinabi sa kanila, “Mga ginoo, mga kapatid, nalalaman ninyo na noong mga unang araw ay pumili ang Diyos sa inyo, na sa pamamagitan ng aking bibig ay mapakinggan ng mga Hentil ang salita ng ebanghelyo, at sila'y manampalataya.
Nabuhay si Adan ng isandaan at tatlumpung taon, at nagkaanak ng isang lalaki na kanyang wangis, ayon sa kanyang larawan, at tinawag ang kanyang pangalan na Set.
Ipapatong niya ang kanyang kamay sa ulo niyon, at papatayin iyon sa harapan ng toldang tipanan at iwiwisik ng mga anak ni Aaron ang dugo sa palibot ng dambana.
Nang unang araw ng Tinapay na Walang Pampaalsa, nang kanilang inihahandog ang kordero ng Paskuwa, sinabi sa kanya ng kanyang mga alagad, “Saan mo kami ibig pumunta at ipaghanda ka upang makakain ng kordero ng Paskuwa?”
At sa palibot ng trono ay may dalawampu't apat na trono, at ang nakaupo sa mga trono ay dalawampu't apat na matatanda, na nakasuot ng mapuputing damit; at sa kanilang mga ulo ay may mga koronang ginto.
“Ang laman na mapasagi sa anumang bagay na marumi ay hindi kakainin; ito ay susunugin sa apoy. Tanging ang lahat na malinis ang makakakain ng gayong laman.
Subalit iniunat ng mga lalaki ang kanilang kamay at binatak si Lot sa loob ng bahay at kanilang sinarhan ang pintuan.
Kaya't sa ganang akin, nasasabik din akong ipangaral ang ebanghelyo sa inyong mga nasa Roma.
At natagpuan sa kanya ang dugo ng mga propeta at ng mga banal, at ng lahat ng mga pinatay sa lupa.”
Lumaki ang sanggol at lumakas sa espiritu. At siya ay nasa mga ilang hanggang sa araw ng kanyang pagpapakita sa Israel.
Sinabi nila, “Ano ang ibig niyang sabihin na, ‘Sandali na lamang?’ Hindi natin alam kung ano ang sinasabi niya.”
Samantalang naglilingkod siya sa Diyos bilang pari at ang kanyang pangkat ang nanunungkulan,
Ngunit nang makita ng mga magsasaka ang anak, sinabi nila sa kanilang sarili, ‘Ito ang tagapagmana; halikayo, patayin natin siya at kunin natin ang kanyang mana.’
tungkol sa katuwiran, sapagkat ako'y pupunta sa Ama, at hindi na ninyo ako makikita;
Tinawag ng Diyos ang liwanag na Araw, at ang kadiliman ay tinawag niyang Gabi. Nagkaroon ng gabi at nagkaroon ng umaga nang unang araw.
Sinabi niya, “Tingnan ninyo, maaga pa, hindi pa oras upang tipunin ang mga hayop; painumin ninyo ang mga tupa, at inyo silang pastulin.”
Pagkalubog ng araw, siya ay magiging malinis at pagkatapos ay makakakain na siya ng mga banal na bagay, sapagkat iyon ay kanyang pagkain.
Ang Panginoon ay nagdaan sa harapan niya, at nagpahayag, “Ang Panginoon , ang Panginoon , isang Diyos na puspos ng kahabagan at mapagpala, hindi magagalitin, at sagana sa wagas na pag-ibig at katapatan,
At kung tutubusin ng nagtalaga ang kanyang bahay, siya ay magdaragdag ng ikalimang bahagi ng salapi na inihalaga roon, at ito ay magiging kanya.
Subalit nang malaman ito ng napakaraming tao, sila ay sumunod sa kanya. Sila'y masaya niyang tinanggap at nagsalita sa kanila tungkol sa kaharian ng Diyos at pinagaling niya ang mga nangangailangan ng pagpapagaling.
bukod pa sa handog na sinusunog sa bagong buwan, at sa handog na butil niyon, at sa palagiang handog na sinusunog at sa handog na butil niyon, at sa mga inuming handog niyon, ayon sa kanilang tuntunin na mabangong samyo na handog sa Panginoon na pinaraan sa apoy.
na ang mga Hentil ay mga kapwa tagapagmana, at mga bahagi ng iisang katawan, at mga kabahagi sa pangako kay Cristo Jesus sa pamamagitan ng ebanghelyo.
At binigkas niya ang kanyang talinghaga, na sinasabi: “Ang sinabi ni Balaam na anak ni Beor, ang sinabi ng lalaking bukas ang mga mata,
Tinanong din siya ng mga kawal, “At kami, anong dapat naming gawin?” At sinabi niya sa kanila, “Huwag kayong mangikil ng salapi kaninuman sa pamamagitan ng dahas o maling paratang at masiyahan kayo sa inyong sahod.”
Susunugin ng pari ang taba sa ibabaw ng dambana, subalit ang dibdib ay magiging kay Aaron at sa kanyang mga anak.
“Kung ang magkapatid ay naninirahang magkasama, at isa sa kanila'y namatay at walang anak, ang asawang babae ng namatay ay huwag mag-aasawa ng isang dayuhan o sa labas ng pamilya. Ang kapatid na lalaki ng kanyang asawa ay sisiping sa kanya, kukunin siya bilang asawa, at tutuparin sa kanya ang tungkulin ng kapatid na namatay.
Pagkatapos ng mga iyon, magkakaroon ng pitong taong taggutom at ang lahat ng kasaganaan sa lupain ng Ehipto ay malilimutan at sasalantain ng taggutom ang lupain.
Kaya't sila'y binilang ni Moises ayon sa salita ng Panginoon , gaya ng iniutos sa kanya.
Siya'y dumaing sa Panginoon at itinuro sa kanya ng Panginoon ang isang punungkahoy; inihagis niya ito sa tubig, at ang tubig ay tumamis. Doon, gumawa ang Panginoon para sa kanila ng isang batas at tuntunin. Doon ay sinubok niya sila,
na nagsasabi, “Ikaw na gigiba sa templo, at sa ikatlong araw ay itatayo ito, iligtas mo ang iyong sarili! Kung ikaw ang Anak ng Diyos, bumaba ka sa krus!”
Ginawa nila iyon at pinaupo silang lahat.
Kanilang ginawa ang mga batong onix na pinalibutan ng ginto, na ayos ukit ng isang pantatak, ayon sa mga pangalan ng mga anak ni Israel.
Bibigyan mo siya ng ilan sa iyong awtoridad upang sundin siya ng buong kapulungan ng mga anak ni Israel.
Sapagkat sinabi ng Panginoon kay Moises,
Sinasabi ko sa inyo, nanaog patungo sa kanyang bahay ang taong ito na inaring-ganap sa halip na ang isa. Sapagkat ang bawat nagmamataas sa kanyang sarili ay ibababa, ngunit ang nagpapakababa sa kanyang sarili ay itataas.”
subalit nahayag na ngayon, at sa pamamagitan ng mga kasulatan ng mga propeta, ay ipinakilala sa lahat ng mga bansa tungo sa pagsunod sa pananampalataya, ayon sa utos ng Diyos na walang hanggan—
Kaya't sinabi ng mga Judio sa taong pinagaling, “Ngayo'y araw ng Sabbath, at hindi ipinahihintulot na buhatin mo ang iyong higaan.”
Hinahanap nga siya ng mga Judio sa pista, at kanilang sinasabi, “Saan siya naroroon?”
Ngunit naglakbay sila mula sa Perga at nakarating sa Antioquia ng Pisidia. At nang araw ng Sabbath, sila'y pumasok sa sinagoga at umupo.
Nang makarating kami sa Jerusalem, masaya kaming tinanggap ng mga kapatid.
Lumapit sa kanya ang isang ketongin na nakikiusap at nakaluhod na nagsasabi, “Kung gusto mo, maaari mo akong linisin.”
“Sa anghel ng iglesya sa Efeso ay isulat mo: Ang mga bagay na ito ay sinasabi ng may hawak ng pitong bituin sa kanyang kanang kamay, na lumalakad sa gitna ng pitong gintong ilawan.
Akong si Juan, na inyong kapatid at inyong karamay sa kapighatian at sa kaharian at sa pagtitiis alang-alang kay Jesus ay nasa pulo na tinatawag na Patmos, dahil sa salita ng Diyos at sa patotoo ni Jesus.
Subalit nang ito ay narinig ni Ruben, kanyang iniligtas siya sa kanilang mga kamay, at sinabi, “Huwag nating patayin.”
Ang mga anak ni Gershon: sina Libni at Shimei, ayon sa kani-kanilang angkan.
Kung sakaling magkukulang ng lima sa limampung banal, lilipulin mo ba ang buong bayan dahil sa limang kulang?” At sinabi niya, “Hindi ko lilipulin kung makatagpo ako roon ng apatnapu't lima.”
na siyang pumatnubay sa iyo sa malaki at kakilakilabot na ilang na mayroong mga makamandag na ahas at mga alakdan, at tigang na lupa na walang tubig; na siyang nagbigay sa iyo ng tubig mula sa batong kiskisan;
at makakakita ka sa mga bihag ng isang magandang babae at magkaroon ka ng pagnanais na kunin siya para sa iyo bilang asawa,
Iyong ilalagay doon ang kaban ng patotoo, at iyong tatabingan ng lambong ang kaban.
Sinabi ng Panginoon kay Moises at kay Aaron, “Ito ang tuntunin ng paskuwa: walang sinumang banyaga na kakain niyon.
upang walang sinumang makabili o makapagbili, maliban ang may tanda, samakatuwid, ng pangalan ng halimaw o ng bilang ng pangalan nito.
“Guluhin ninyo ang mga Midianita, at inyong daigin sila;
Mahigpit niyang ipinag-utos sa kanila na walang dapat makaalam nito; at sinabi niya sa kanila na ang bata ay bigyan ng makakain.
Sapagkat sinasabi ko sa inyo, malibang humigit ang inyong katuwiran sa katuwiran ng mga eskriba at mga Fariseo, ay hindi kayo makakapasok sa kaharian ng langit.
ay iyo ngang usisain at siyasatin, at itanong na mabuti; at kung totoo na nagawa sa gitna mo ang gayong karumaldumal na bagay;
Pumunta siya sa likod ng lalaking Israelita sa loob ng tolda, at tinuhog silang pareho, ang lalaking Israelita at ang babae, tagos sa katawan nito. Sa gayon ang salot ay huminto sa mga anak ni Israel.
Ilagay mo ang mga ito sa toldang tipanan sa harap ng patotoo, kung saan ako nakikipagtagpo sa inyo.
Sila'y naglakbay mula sa Rameses nang ikalabinlimang araw ng unang buwan. Kinabukasan, pagkatapos ng paskuwa ay buong tapang na umalis ang mga anak ni Israel sa paningin ng lahat ng mga Ehipcio,
Gayon nga ang nagtitipon ng kayamanan para sa kanyang sarili, subalit hindi mayaman sa Diyos.”
Sapagkat sila'y buong ibinigay sa akin mula sa mga anak ni Israel; kinuha ko silang kapalit ng lahat ng nagbubukas ng bahay-bata, ng mga panganay sa lahat ng mga Israelita.
Namangha ang mga Judio, na nagsasabi, “Paanong nagkaroon ang taong ito ng karunungan, gayong hindi naman nag-aral kailanman?”
Gumawa ang Diyos ng mga di-pangkaraniwang himala sa pamamagitan ng mga kamay ni Pablo,
Siya'y kanilang dinala sa pook na tinatawag na Golgota na ang kahulugan ay ‘Ang pook ng bungo.’
Nais ng ilan sa kanila na siya'y hulihin, subalit walang taong sumunggab sa kanya.
at hindi niya kailangan ang sinuman upang magpatotoo tungkol sa tao, sapagkat alam niya ang isinasaloob ng tao.
“Kayo ang ilaw ng sanlibutan. Ang isang lunsod na nakatayo sa ibabaw ng isang burol ay hindi maitatago.
Sinabi ni Pedro, “Ananias, bakit napadaig ka kay Satanas at nagsinungaling ka sa Espiritu Santo, at itago ang bahagi ng pinagbilhan ng lupa?
Sumagot siya sa kanila at sinabi, “Bakit lumalabag naman kayo sa utos ng Diyos dahil sa inyong tradisyon?
Sapagkat kung kayo'y palungkutin ko, sino ang magpapagalak sa akin, kundi iyong pinalungkot ko?
Ang ipauulan ng Panginoon sa iyong lupa ay abo at alabok; mula sa langit ay bababa ito sa iyo hanggang sa ikaw ay mawasak.
Kaya't tumindig si Pablo sa gitna ng Areopago, at sinabi, “Mga lalaking taga-Atenas, napapansin ko na sa lahat ng bagay kayo'y lubhang relihiyoso.
“Kung magkagayon, ang toldang tipanan ay susulong na kasama ng pangkat ng mga Levita sa gitna ng mga kampo, ayon sa kanilang pagkakampo ay gayon sila susulong, na bawat lalaki ay sa kanya-kanyang lugar ayon sa kanilang mga watawat.
at sinunod ni Jacob ang kanyang ama at ina at pumunta sa Padan-aram.
Kaya't sinabi niya kay Abraham, “Palayasin mo ang aliping ito at ang kanyang anak, sapagkat hindi magmamana ang anak ng aliping ito na kahati ng aking anak na si Isaac.”
At sinabi niya sa kanya, ‘Anak, ikaw ay palagi kong kasama, ang lahat ng sa akin ay sa iyo.
“Sa mga ito hahatiin ang lupain bilang mana ayon sa bilang ng mga pangalan.
Ipapatong niya ang kanyang kamay sa ulo ng handog pangkasalanan at papatayin ito bilang handog pangkasalanan sa lugar na pinagpapatayan ng handog na sinusunog.
Bukod dito, tayo'y nagkaroon ng mga ama sa laman upang tayo'y disiplinahin, at sila'y ating iginagalang. Hindi ba dapat na tayo'y lalong pasakop sa Ama ng mga espiritu upang tayo'y mabuhay?
Kakainin mo ito, ikaw at ng iyong sambahayan sa harapan ng Panginoon mong Diyos taun-taon sa lugar na pipiliin ng Panginoon .
