Pinalaya niya ang taong kanilang hinihiling, ang taong ibinilanggo dahil sa paghihimagsik at sa pagpatay, subalit kanyang ibinigay si Jesus gaya ng nais nila.
Ngunit samantalang natutulog ang mga tao, dumating ang kaaway at naghasik ng mga damo sa triguhan, at umalis.
ayon sa kaugalian ng mga pari, napili siya sa pamamagitan ng palabunutan na pumasok sa templo ng Panginoon at magsunog ng insenso.
At ang sinumang magsabi ng isang salita laban sa Anak ng Tao ay patatawarin; ngunit ang sinumang magsalita laban sa Espiritu Santo ay hindi patatawarin maging sa panahong ito o sa darating.
Gayunma'y kailangang ako'y magpatuloy sa aking lakad ngayon at bukas at sa makalawa, sapagkat hindi maaari na ang isang propeta ay mamatay sa labas ng Jerusalem.’
gayundin si Santiago at si Juan, mga anak ni Zebedeo, na mga kasamahan ni Simon. At sinabi ni Jesus kay Simon, “Huwag kang matakot, mula ngayon ay mamamalakaya ka ng mga tao.”
Nalungkot ang hari, ngunit dahil sa kanyang mga sumpa at sa mga panauhin, ipinag-utos niyang ibigay iyon.
ako'y natakot sa iyo, sapagkat ikaw ay taong mahigpit, kinukuha mo ang hindi mo itinabi, at ginagapas mo ang hindi mo inihasik.’
at ang pagbibigay-galang sa kanila sa mga pamilihan, at ang sila'y tawagin ng mga tao, ‘Rabi.’
Kayong mga bulag na taga-akay! Sinasala ninyo ang niknik, ngunit nilulunok ninyo ang kamelyo!
Inabot kaagad ni Jesus ang kamay niya at hinawakan siya, na sinasabi sa kanya, “O ikaw na maliit ang pananampalataya, bakit ka nag-alinlangan?”
At sinabi niya sa kanila, “Sino sa inyo, kung ang anak o bakang lalaki ay nahulog sa hukay, hindi ba agad ninyo iaahon sa araw ng Sabbath?”
sapagkat bibigyan ko kayo ng salita at karunungan na hindi malalabanan o matututulan man ng lahat ng sumasalungat sa inyo.
Ang mga nasa tabi ng daan ay ang mga nakinig, pagkatapos ay dumating ang diyablo, at inagaw ang salita mula sa kanilang mga puso upang hindi sila sumampalataya at maligtas.
Tinulungan niya ang Israel na kanyang alipin,
na nagsasabi, “Ikaw na gigiba sa templo, at sa ikatlong araw ay itatayo ito, iligtas mo ang iyong sarili! Kung ikaw ang Anak ng Diyos, bumaba ka sa krus!”
at ang muling pagkakaroon ng paningin sa mga bulag, upang palayain ang mga naaapi,
Sila ay nakiusap sa kanya na huwag silang utusang bumalik sa di-matarok na kalaliman.
Kung mabalitaan ito ng gobernador, hihikayatin namin siya, at ilalayo namin kayo sa gulo.”
May isang lumapit sa kanya at nagsabi, “Guro, anong mabuting bagay ang dapat kong gawin upang magkaroon ako ng buhay na walang hanggan?”
Bigyan mo ang bawat humihingi sa iyo; at kapag inagaw ng sinuman ang iyong ari-arian, huwag mo nang bawiin ang mga iyon.
subalit ako ay nanalangin para sa iyo upang ang iyong pananampalataya ay huwag mawala; kung makabalik ka nang muli, ay palakasin mo ang iyong mga kapatid.”
Ngunit kung sasabihin natin, ‘Mula sa mga tao,’ natatakot tayo sa napakaraming tao, sapagkat kinikilala ng lahat na propeta si Juan.”
Nang maalala ni Pedro ay sinabi niya sa kanya, “Rabi, tingnan mo! Ang puno ng igos na iyong isinumpa ay tuyo na.”
At pinuri ng panginoon ang madayang katiwala, sapagkat siya'y gumawang may katusuhan, sapagkat ang mga anak ng sanlibutang ito ay higit na tuso sa pakikitungo sa sarili nilang lahi kaysa mga anak ng liwanag.
At sila'y nagsilabas at nagsitakas mula sa libingan, sapagkat sila'y sinidlan ng sindak at pagkamangha, at wala silang sinabi kaninuman sapagkat sila'y natakot.
Subalit ilimos ninyo ang mga bagay na nasa loob at ang lahat ng mga bagay ay magiging malinis para sa inyo.
Nang magdadapit-hapon na, sinabi ng panginoon ng ubasan sa kanyang katiwala, ‘Tawagin mo ang mga manggagawa, at bayaran mo sila ng mga upa mula sa mga nahuli hanggang sa mga nauna.’
Siya'y kanilang dinamitan ng kulay-ube, at nang makapagtirintas ng isang koronang tinik ay ipinutong nila ito sa kanya.
Mapalad ang dumarating na kaharian ng ating amang si David! Hosana sa kataas-taasan!”
Gayundin naman kayo, kapag nagawa na ninyo ang lahat ng mga bagay na iniutos sa inyo, inyong sabihin, ‘Kami'y mga aliping walang kabuluhan, ginawa lamang namin ang aming katungkulan.’”
Sapagkat alin ang higit na dakila, ang nakaupo ba sa hapag, o ang naglilingkod? Hindi ba ang nakaupo sa hapag? Subalit ako'y kasama ninyo na gaya ng isang naglilingkod.
Subalit kanyang ipinagbilin at ipinag-utos sa kanila na huwag itong sabihin kahit kanino,
Lumapit ang isang eskriba at nagsabi sa kanya, “Guro, susunod ako sa iyo saan ka man magtungo.”
Ngunit sinabi ni Jesus sa kanila, “Hindi na kailangang umalis pa sila; bigyan ninyo sila ng makakain.”
At may dumating na mga lalaking may dalang isang lalaking lumpo na nasa isang higaan at sinikap nilang maipasok ang lumpo sa bahay at mailagay sa harap ni Jesus.
Pagkatapos ay lumabas ang mga demonyo sa tao, at pumasok sa mga baboy at ang kawan ay dumaluhong sa bangin patungo sa lawa at nalunod.
Kaya't ang pinagsama ng Diyos ay huwag hayaang paghiwalayin ng tao.”
Sumagot sila, “Kaya namin.” Sinabi naman ni Jesus sa kanila, “Ang kopang aking iinuman ay iinuman ninyo; at sa bautismo na ibinabautismo sa akin ay babautismuhan kayo.
Sila'y namangha sa kanyang pagtuturo, sapagkat ang kanyang salita ay may kapangyarihan.
ang siyang naging ulo ng panulukan;
Pagkatapos ay dumating ang mga alagad at sinabi sa kanya, “Alam mo bang nasaktan ang mga Fariseo nang marinig nila ang pananalitang ito?”
Pagkatapos ay sinabi ni Jesus sa kanyang mga alagad, “Kung ang sinuman ay ibig sumunod sa akin, tanggihan niya ang kanyang sarili, at pasanin ang kanyang krus, at sumunod sa akin.
Huwag kayong magdala ng ginto, o pilak, o tanso sa inyong mga lalagyan ng pera;
Ngunit upang hindi sila matisod sa atin, pumunta ka sa dagat at maghulog ka ng bingwit. Kunin mo ang unang isdang mahuhuli at kapag ibinuka mo ang kanyang bibig, matatagpuan mo ang isang siklo. Kunin mo iyon at ibigay mo sa kanila, para sa akin at sa iyo.”
At pagbaba niya sa lupa, siya'y sinalubong ng isang lalaking galing sa bayan na may mga demonyo. Matagal na siyang hindi nagsusuot ng damit at hindi tumitira sa bahay, kundi sa mga libingan.
“Walang taong pagkatapos magsindi ng ilawan ay tinatakpan ito ng isang takalan, o kaya'y inilalagay ito sa ilalim ng higaan, kundi inilalagay ito sa talagang lalagyan upang makita ng mga pumapasok ang liwanag.
Sinabi ng mga apostol sa Panginoon, “Dagdagan mo ang pananampalataya namin.”
Nang makatawid na sila, dumating sila sa lupain ng Genesaret.
Sinabi nila sa kanya, “Kay Cesar.” Pagkatapos ay sinabi niya sa kanila, “Kaya't ibigay ninyo kay Cesar ang kay Cesar at sa Diyos ang sa Diyos.”
Siya'y umalis at nakipag-usap sa mga punong pari at mga punong-kawal kung paanong kanyang maipagkakanulo siya sa kanila.
Sinabi niya sa kanila, “Kaninong larawan ito at ang nakasulat?”
Kung ang isang kaharian ay nagkakabaha-bahagi laban sa kanyang sarili, hindi makakatayo ang kahariang iyon.
Kanilang minamatyagan si Jesus kung kanyang pagagalingin ang lalaki sa araw ng Sabbath upang siya'y maparatangan nila.
Sinasabi ko sa inyo, bagaman hindi siya bumangon at magbigay sa kanya ng anuman dahil siya ay kanyang kaibigan, ngunit dahil sa kanyang pamimilit siya'y babangon at ibibigay ang anumang kailanganin niya.
Nagdala nga sila ng isa at sinabi niya sa kanila, “Kaninong larawan at pangalan ang nakaukit?” Sinabi nila sa kanya, “Kay Cesar.”
Kung gayon, bakit hindi mo inilagay ang aking salapi sa bangko at nang sa aking pagbalik ay makuha ko iyon pati ng tinubo?’
“Kahabag-habag kayo, mga eskriba at mga Fariseo, mga mapagkunwari! Sapagkat nag-iikapu kayo ng yerbabuena, ng anis at ng komino, at inyong pinababayaan ang higit na mahahalagang bagay ng kautusan: ang katarungan, ang habag, at ang pananampalataya. Subalit dapat sana ninyong gawin ang mga ito nang hindi pinababayaan ang iba.
Bukod dito, binigla kami ng ilan sa mga babaing kasamahan namin. Sila ay maagang pumunta sa libingan,
Kaya't ang mga nasa Judea ay dapat tumakas patungo sa mga bundok; at ang mga nasa loob ng lunsod ay lumabas, at ang mga nasa labas ng lupain ay huwag pumasok doon;
Nang si Jesus ay nasa Betania, sa bahay ni Simon na ketongin,
Nagtalo sila sa isa't isa, “Kung sabihin natin, ‘Mula sa langit’ ay sasabihin niya, ‘Bakit nga hindi ninyo siya pinaniwalaan?’
“Kaya, anumang bagay na ibig ninyong gawin sa inyo ng mga tao, gayon ang gawin ninyo sa kanila; sapagkat ito ang kautusan at ang mga propeta.
Pagdating niya sa oras ding iyon, siya'y nagpasalamat sa Diyos at nagsalita nang tungkol sa sanggol sa lahat ng naghihintay para sa katubusan ng Jerusalem.
Ang mga eskriba at ang mga Fariseo ay nagmamatyag sa kanya kung siya'y magpapagaling sa Sabbath upang makakita sila ng maibibintang laban sa kanya.
Kaya't sa muling pagkabuhay, sino ang magiging asawa ng babaing iyon sapagkat siya'y naging asawa ng pito.
Nang maitabi na nila sa lupa ang kanilang mga bangka ay iniwan nila ang lahat, at sumunod sa kanya.
Sapagkat ang sinumang nagnanais iligtas ang kanyang buhay ay mawawalan nito at ang sinumang mawalan ng kanyang buhay dahil sa akin at sa ebanghelyo ay maililigtas iyon.
“Mapapalad kayong mga dukha,
Sinabi sa kanya ng anghel, “Huwag kang matakot, Maria, sapagkat nakatagpo ka ng paglingap sa Diyos.
At mayroon din namang mga babae na nakatanaw mula sa malayo; kabilang sa kanila ay si Maria Magdalena, si Mariang ina ni Santiago na mas bata at ni Jose, at si Salome;
Paggising niya ay sinaway niya ang hangin at sinabi sa dagat, “Pumayapa ka. Tumahimik ka!” Tumigil nga ang hangin at nagkaroon ng katahimikan.
Ngunit siya'y hindi Diyos ng mga patay, kundi ng mga buháy, sapagkat sa kanya silang lahat ay nabubuhay.”
si Juan na Tagapagbautismo ay dumating sa ilang at ipinangangaral ang bautismo ng pagsisisi sa ikapagpapatawad ng mga kasalanan.
Ngunit siya'y nasa hulihan ng bangka at natutulog na may inuunan. Siya'y ginising nila, at sinabi sa kanya, “Guro, hindi ka ba nababahala na mapapahamak tayo?”
ay maglingkod sa kanya nang walang takot,
Nang pumasok si Jesus sa bahay ni Pedro, nakita niya ang biyenang babae nito na nakaratay dahil sa lagnat.
Hindi ako pumarito upang tawagin ang mga matuwid, kundi ang mga makasalanan tungo sa pagsisisi.”
‘Ang batong itinakuwil ng mga tagapagtayo
Nagkaroon ng isang pagtatalu-talo sa gitna nila, kung sino kaya sa kanila ang ituturing na pinakadakila.
At sa alinmang bayan kayo pumasok at kayo'y kanilang tanggapin ay kainin ninyo ang anumang inihahain sa inyo.
Pagkatapos ay lumapit kay Jesus ang ina ng mga anak ni Zebedeo, na kasama ang kanyang mga anak na lalaki. Siya'y lumuhod sa kanya at may hiniling na isang bagay sa kanya.
Pagsapit ng gabi, umupo siyang kasalo ng labindalawang alagad.
Ngunit ang alipin ding iyon, sa kanyang paglabas, ay natagpuan ang isa sa mga kapwa niya alipin na nagkautang sa kanya ng isandaang denario. Sinunggaban niya ito, sinakal, at sinabihan, ‘Bayaran mo ang utang mo.’
Nang malaman ito ni Jesus ay umalis siya roon. Sinundan siya ng marami at pinagaling niya silang lahat,
At nagtaka si Pilato na siya'y patay na. Ipinatawag niya ang senturion at itinanong niya sa kanya kung patay na nga siya.
Nang panahong iyon ay narinig ng tetrarkang si Herodes ang balita tungkol kay Jesus.
“Huwag ninyong isiping pumarito ako upang sirain ang kautusan o ang mga propeta; pumarito ako hindi upang sirain, kundi upang tuparin ang mga ito.
Dalawang ulit akong nag-aayuno sa isang linggo, nagbibigay ako ng ikapu sa lahat ng aking kinikita!’
kanilang binigyan siya ng alak na may kahalong apdo upang inumin. Ngunit nang kanyang matikman ay ayaw niyang inumin.
Tinawag niya ang sampu sa kanyang mga alipin at binigyan sila ng sampung mina, at sinabi sa kanila, ‘Ipangalakal ninyo ito hanggang sa ako'y dumating.’
Ngunit lumingon siya at sinabi kay Pedro, “Layuan mo ako, Satanas! Ikaw ay isang katitisuran sa akin; sapagkat hindi mo iniisip ang mga bagay ng Diyos, kundi ang mga bagay ng tao.”
Ang mga apostol ay nagtipon sa harap ni Jesus at ibinalita nila sa kanya ang lahat ng kanilang ginawa at itinuro.
Tumindig ang pinakapunong pari at sinabi sa kanya, “Wala ka bang isasagot? Ano itong ibinibintang ng mga ito laban sa iyo?”
At ipinasiya ni Pilato na ipagkaloob ang kanilang hinihingi.
Tingnan ninyo, sa inyo'y iniwan ang inyong bahay. At sinasabi ko sa inyo, hindi ninyo ako makikita, hanggang sa inyong sabihin, ‘Mapalad ang dumarating sa pangalan ng Panginoon.’”
Habang patungo sila roon, ang ilan sa mga bantay ay pumunta sa lunsod at ibinalita sa mga punong pari ang lahat ng mga bagay na nangyari.
Sapagkat sa muling pagkabuhay ay hindi sila nag-aasawa o pinag-aasawa pa kundi sila'y tulad sa mga anghel sa langit.
At pagkatanaw niya sa malayo ng isang puno ng igos na may mga dahon, lumapit siya upang tingnan kung may matatagpuan siya roon. At nang siya'y makalapit doon, wala siyang natagpuang anuman kundi mga dahon, sapagkat hindi pa panahon ng mga igos.
Sa pagpapatuloy nila sa kanilang lakad, pumasok siya sa isang nayon. Isang babaing ang pangalan ay Marta ang tumanggap kay Jesus sa kanyang bahay.
At sinabi niya sa kanya, “Tumpak ang sagot mo, gawin mo ito at mabubuhay ka.”
Pagkatapos mag-usap, ibinili nila ang mga iyon ng bukid ng magpapalayok upang paglibingan ng mga dayuhan.
si Simon, na tinawag niyang Pedro, si Andres na kanyang kapatid, si Santiago, si Juan, si Felipe, si Bartolome,
“Kahabag-habag kayo, mga eskriba at mga Fariseo, mga mapagkunwari! Sapagkat nililinis ninyo ang labas ng kopa at ng pinggan, ngunit sa loob ay punô sila ng kasakiman at kalayawan.
Subalit tinanggihan ng mga Fariseo at ng mga dalubhasa sa Kautusan ang layunin ng Diyos para sa kanila sa hindi nila pagpapabautismo sa kanya.)
Ngunit sinabi sa kanila ni Pilato, “Bakit, anong kasamaan ang kanyang ginawa?” Subalit sila'y lalong nagsigawan, “Ipako siya sa krus.”
Pagkatapos ay nagpunta sila sa isang dako na tinatawag na Getsemani at sinabi niya sa kanyang mga alagad, “Maupo kayo rito habang ako'y nananalangin.”
Ang langit at ang lupa ay lilipas, subalit ang aking salita ay hindi lilipas.
kaya't kinawayan nila ang mga kasamahan nilang nasa ibang bangka upang lumapit at tulungan sila. Sila'y lumapit at pinuno ng isda ang dalawang bangka, anupa't sila'y nagpasimulang lumubog.
Pagkatapos ay makikita nila ang Anak ng Tao na dumarating na nasa isang ulap na may kapangyarihan at dakilang kaluwalhatian.
At sa kanyang paglakad mula roon ay nakita niya sa bangka ang dalawa pang magkapatid, si Santiago na anak ni Zebedeo at si Juan na kanyang kapatid, kasama si Zebedeo na kanilang ama, na nag-aayos ng lambat; at kanyang tinawag sila.
Nang marinig ni Juan sa bilangguan ang mga gawa ng Cristo, nagpasabi siya sa pamamagitan ng kanyang mga alagad,
Si Pedro at ang kanyang mga kasamahan ay nakatulog nang mahimbing, subalit nang sila'y nagising ay nakita nila ang kanyang kaluwalhatian at ang dalawang lalaking nakatayong kasama niya.
sa sambahayan ni David na kanyang lingkod,
Katotohanang sinasabi ko sa inyo, ang lahat ng mga bagay na ito ay darating sa lahing ito.
kundi magtipon kayo para sa inyong sarili ng mga kayamanan sa langit, na doon ang bukbok at ang kalawang ay hindi makapaninira at ang mga magnanakaw ay hindi rin makakapasok ni makakapagnakaw.
Hinawakan niya ang kamay ng bata at sinabi sa kanya, “Talitha cum,” na ang kahulugan ay “Munting batang babae, sinasabi ko sa iyo, bumangon ka!”
ay minabuti ko naman, pagkatapos na siyasating mabuti ang lahat ng mga pangyayari buhat sa pasimula, na sumulat ng isang maayos na salaysay para sa iyo, kagalang-galang na Teofilo,
Pagkalipas ng ilang sandali ay lumapit ang mga nakatayo roon at sinabi nila kay Pedro, “Talagang ikaw nga ay isa rin sa kanila, sapagkat nahahalata sa iyong pananalita.”
At nang siya'y maipako nila sa krus, pinaghati-hatian nila ang kanyang mga damit sa pamamagitan ng palabunutan.
At muling sinabi niya, “Sa ano ko ihahambing ang kaharian ng Diyos?
Ito ay upang matupad ang sinabi sa pamamagitan ni propeta Isaias, na sinasabi:
Sapagkat ang pabangong ito'y maipagbibili ng higit sa tatlong daang denario, at maipamimigay sa mga dukha.” At kanilang pinagalitan ang babae.
Nang malaman niya sa senturion, ipinagkaloob niya ang bangkay kay Jose.
Kaya't umupo sila nang pangkat-pangkat, nang tig-iisandaan at tiglilimampu.
Kapag kayo'y dinala nila sa paglilitis at kayo'y ipinadakip, huwag kayong mabalisa kung ano ang inyong sasabihin, ngunit sabihin ninyo ang anumang ipagkaloob sa inyo sa oras na iyon, sapagkat hindi kayo ang magsasalita, kundi ang Espiritu Santo.
Umalis sila roon at nagdaan sa Galilea at ayaw niyang malaman ito ng sinuman.
Ngayon pa lamang ay nakalagay na ang palakol sa ugat ng mga punungkahoy. Ang bawat punungkahoy na hindi mabuti ang bunga ay pinuputol at inihahagis sa apoy.
At nagbuntong-hininga siya nang malalim sa kanyang espiritu at sinabi, “Bakit humahanap ng tanda ang salinlahing ito? Katotohanan ang sinasabi ko sa inyo, walang tanda na ibibigay sa salinlahing ito.”
Sinabi ni Herodes, “Si Juan ay pinugutan ko ng ulo, subalit sino ang taong ito na marami akong naririnig tungkol sa kanya na gayong mga bagay?” At pinagsikapan niyang makita si Jesus.
Ngunit sumagot ang kanyang panginoon at sinabi sa kanya, ‘Ikaw na masama at tamad na alipin! Alam mo palang ako'y gumagapas sa hindi ko hinasikan, at nagtitipon sa hindi ko kinalatan ng binhi.
Siya'y tumindig at pumunta sa kanyang ama. Subalit habang nasa malayo pa siya, natanaw siya ng kanyang ama at ito'y awang-awa sa kanya. Ang ama'y tumakbo, niyakap siya at hinagkan.
Ngunit kung ang masamang aliping iyon ay magsabi sa kanyang puso, ‘Magtatagal ang aking panginoon,’
Kaya't siya'y aking ipapahagupit at palalayain.”
Ikaw ay magkakaroon ng kaligayahan at kagalakan at marami ang matutuwa sa kanyang pagsilang.
Nang sila'y papalabas na sa Jerico, sumunod sa kanya ang napakaraming tao.
Isinalaysay niya ang talinghagang ito: “Ang isang tao ay may isang puno ng igos na nakatanim sa kanyang ubasan. Siya'y pumunta upang maghanap ng bunga roon, subalit walang nakita.
Kaya't hindi kalooban ng inyong Ama na nasa langit na ang isa sa maliliit na ito ay mapahamak.
Nang malaman ni Herodes na siya'y dinaya ng mga Pantas, siya ay labis na nagalit. At ipinag-utos niyang patayin ang lahat ng mga batang lalaki sa Bethlehem at sa karatig-pook na may gulang na dalawang taon pababa, ayon sa panahon na kanyang tiniyak mula sa mga Pantas.
sila'y hahawak ng mga ahas, at kung makainom sila ng bagay na nakamamatay, hindi ito makakasama sa kanila, ipapatong nila ang kanilang mga kamay sa mga maysakit, at sila'y gagaling.”
Bumaba ngayon mula sa krus ang Cristo, ang Hari ng Israel upang aming makita at paniwalaan.” At tinutuya rin siya ng mga kasama niyang nakapako sa krus.
Sinabi sa kanya ni Juan, “Guro, nakita namin ang isang tao na nagpapalayas ng mga demonyo sa pangalan mo at pinagbawalan namin siya, sapagkat hindi siya sumusunod sa atin.”
Sapagkat kung ginagawa nila ang mga bagay na ito kapag ang punungkahoy ay sariwa, anong mangyayari kapag ito ay tuyo?
At sumagot ang buong bayan at nagsabi, “Pananagutan namin at ng aming mga anak ang kanyang dugo.”
Kung may magsabi sa inyo, ‘Narito ang Cristo!’ o, ‘Tingnan ninyo naroon siya!’ huwag ninyong paniwalaan.
Ang lahat ay namangha sa kadakilaan ng Diyos. Subalit habang ang lahat ay namamangha sa lahat ng kanyang ginagawa ay sinabi niya sa kanyang mga alagad,
At ang nasa bubungan ay huwag nang bumaba, o pumasok upang maglabas ng anuman sa kanyang bahay.
at nagagalak ang aking espiritu sa Diyos na aking Tagapagligtas.
‘Ihanda ninyo ang daan ng Panginoon,
At sinabi nila, “Panginoon, tingnan ninyo, narito ang dalawang tabak.” Sinabi naman niya sa kanila, “Tama na iyan.”
na nagsasabi, “Ipahayag mo sa amin, ikaw na Cristo! Sino ang sumuntok sa iyo?”
Si Jesus ay muling nagsalita sa kanila sa mga talinghaga, na sinasabi,
Sapagkat sinasabi niya, “Kung mahipo ko man lamang ang kanyang damit ay gagaling na ako.”
“Kaya't nang makalabas mula sa isang tao ang maruming espiritu, nagpagala-gala ito sa mga dakong walang tubig na humahanap ng mapapagpahingahan, ngunit wala siyang matagpuan.
Lumapit ang mga alagad, at sinabi nila sa kanya, “Bakit ka nagsasalita sa kanila sa pamamagitan ng mga talinghaga?”
Nagbulung-bulungan ang mga Fariseo at ang kanilang mga eskriba laban sa kanyang mga alagad na sinasabi, “Bakit kayo'y kumakain at umiinom na kasalo ng mga maniningil ng buwis at ng mga makasalanan?”
Pagkabatid na may lumabas na kapangyarihan mula sa kanya, bumaling si Jesus sa karamihan at nagsabi, “Sino ang humipo sa aking damit?”
Ibibigay ko sa iyo ang mga susi ng kaharian ng langit, at anumang iyong talian sa lupa ay tatalian sa langit; at anumang iyong kalagan sa lupa ay kakalagan sa langit.”
Ang nasa bukid ay huwag nang bumalik upang kumuha ng kanyang balabal.
Subalit ang pinuno ng sinagoga, na galit sapagkat si Jesus ay nagpagaling sa Sabbath, ay nagsabi sa maraming tao, “May anim na araw na dapat gumawa, pumarito kayo sa mga araw na iyon at kayo'y pagagalingin at hindi sa araw ng Sabbath.”
Sinabi naman niya sa kanila, “Hindi pa ba ninyo nauunawaan?”
Mapalad ang aliping iyon, na maratnan ng kanyang panginoon na gayon ang ginagawa.
At sinabi niya sa lahat, “Kung ang sinuman ay nagnanais sumunod sa akin, tanggihan niya ang kanyang sarili at magpasan ng kanyang krus araw-araw at sumunod sa akin.
sapagkat nasusulat,
at ang ilang babae na pinagaling mula sa masasamang espiritu at sa mga sakit: si Maria na tinatawag na Magdalena, na mula sa kanya'y pitong demonyo ang lumabas,
Ngunit kahabag-habag ang mga buntis at ang mga nagpapasuso sa mga araw na iyon!
Pagkatapos ay sasabihin ng Hari sa mga nasa kanyang kanan, ‘Halikayo, mga pinagpala ng aking Ama, manahin ninyo ang kahariang inihanda para sa inyo mula sa pagkatatag ng sanlibutan.
Walang sinuman na pagkatapos magsindi ng ilawan ay inilalagay ito sa isang tagong lugar o sa ilalim ng takalan, kundi sa patungan ng ilaw upang makita ng mga pumapasok ang liwanag.
At sumagot siya, “Sinasabi ko sa inyo na kung tatahimik ang mga ito, ang mga bato'y sisigaw.”
“Ang tumatanggap sa inyo ay tumatanggap sa akin at ang tumatanggap sa akin ay tumatanggap sa nagsugo sa akin.
At sinabi niya sa kanyang mga lingkod, “Ito ay si Juan na Tagapagbautismo na muling binuhay sa mga patay; kaya't nagagawa niya ang mga kababalaghang ito.”
ngunit ang mga alalahanin ng sanlibutan, ang pang-akit ng mga kayamanan, at ang mga pagnanasa sa ibang bagay ay pumasok at sinakal ang salita at ito'y hindi nakapamunga.
Dinala ko siya sa iyong mga alagad, ngunit siya'y hindi nila mapagaling.
Kung ang sinuman ay may taingang ipandirinig, hayaan siyang makinig.”
at sinabi sa kanila, “Dinala ninyo sa akin ang taong ito na gaya ng isang nag-uudyok na maghimagsik ang bayan. At narito, nang aking siyasatin siya sa harapan ninyo, hindi ko nakitang nagkasala ang taong ito ng alinman sa mga bagay na ibinibintang ninyo laban sa kanya.
At nang sila'y makarating sa isang dakong tinatawag na Golgota, (na ang kahulugan ay, “Ang Dako ng Bungo”),
Nang madaling-araw, habang madilim pa, pagbangon ni Jesus ay lumabas siya at nagtungo sa isang ilang na lugar, at doon ay nanalangin.
At siya'y dumampot ng tinapay, at nang siya'y makapagpasalamat, kanyang pinagputul-putol, at ibinigay sa kanila, na sinasabi, “Ito'y aking katawan na ibinibigay dahil sa inyo. Gawin ninyo ito sa pag-aalaala sa akin.”
At sila'y bumalik at ipinagbigay-alam ito sa mga iba ngunit hindi rin sila naniwala.
Subalit pinipilit nilang hingin na ipinagsisigawan na siya'y ipako sa krus. At nanaig ang kanilang mga tinig.
Walang bagay na natatakpan na hindi mabubunyag, at walang bagay na natatago na hindi malalaman.
Sinabi niya sa kanila, “Nasusulat, ‘Ang aking bahay ay tatawaging bahay-panalanginan,’ ngunit ginagawa ninyo itong yungib ng mga magnanakaw.”
Kung ang paa mo'y nakapagpapatisod sa iyo, putulin mo ito. Mas mabuti pa sa iyo ang pumasok sa buhay na pilay kaysa may dalawang paa ka at maitapon sa impiyerno,
“Ang kaharian ng langit ay tulad sa nakatagong kayamanan sa isang bukid; na natagpuan ng isang tao, at tinabunan niya ito. Sa kanyang kagalakan ay umalis siya at ipinagbili ang lahat ng kanyang ari-arian at binili ang bukid na iyon.
Magbantay kayo, sapagkat hindi ninyo nalalaman kung anong araw darating ang inyong Panginoon.
Nang marinig niya na iyon ay si Jesus na taga-Nazaret, nagsimula siyang magsisigaw at magsabi, “Jesus, Anak ni David, mahabag ka sa akin!”
Dumating ang una, na nagsasabi, ‘Panginoon, tumubo ang iyong mina ng sampung mina pa.’
Kung ang kanan mong mata ang sanhi ng iyong pagkakasala, dukitin mo ito at itapon, sapagkat mabuti pang mawalan ka ng isa sa mga bahagi ng iyong katawan kaysa ang buong katawan mo ay mapatapon sa impiyerno.
At nang siya'y nakaupo sa hapag-kainan sa bahay ni Levi, maraming maniningil ng buwis at mga makasalanan ang nakaupong kasalo ni Jesus at ng kanyang mga alagad sapagkat marami silang sumunod sa kanya.
Sapagkat ang Anak ng Tao ay dumating upang hanapin at iligtas ang nawala.”
Subalit sinabi ng ilan sa mga Fariseo, “Bakit ginagawa ninyo ang hindi ipinahihintulot sa araw ng Sabbath?”
Nakatayong nanonood ang taong-bayan. Subalit tinutuya naman siya ng mga pinuno, na sinasabi, “Iniligtas niya ang iba, iligtas niya ang kanyang sarili kung siya ang Cristo ng Diyos, ang Pinili.”
Nagsugo siya at pinapugutan niya ng ulo si Juan sa bilangguan.
“Narinig din ninyo na sinabi sa mga tao noong unang panahon, ‘Huwag mong sisirain ang iyong panata kundi tutuparin mo ang iyong mga ipinanata sa Panginoon.’
Noon, taun-taon ay nagtutungo ang kanyang mga magulang sa Jerusalem sa kapistahan ng Paskuwa.
At sinabi sa kanila ni Jesus, “Ang mga anak ng panahong ito ay nag-aasawa at pinag-aasawa,
Nang lumulubog na ang araw, dinala ng lahat sa kanya ang kanilang mga maysakit na sari-sari ang karamdaman at ipinatong niya ang kanyang mga kamay sa bawat isa sa kanila at sila'y pinagaling.
Sapagkat kung nasaan ang iyong kayamanan, naroon din naman ang iyong puso.
Kayo'y mag-ingat, kayo'y magbantay, sapagkat hindi ninyo nalalaman kung kailan ang panahon.
Nang malapit na siya at nakita ang lunsod, ito'y kanyang iniyakan,
At sinabi sa kanila ni Jesus, “Sumunod kayo sa akin at gagawin ko kayong mga mamamalakaya ng mga tao.”
Si Judas Iscariote naman, na isa sa labindalawa, ay nagpunta sa mga punong pari upang maipagkanulo siya sa kanila.
Ngunit sila'y tumahimik, sapagkat sa daan ay pinagtatalunan nila kung sino ang pinakadakila.
Nang magtatanghaling-tapat na, nagdilim sa ibabaw ng buong lupain hanggang sa ikatlo ng hapon,
Kayong lahi ng mga ulupong! Paano kayo makapagsasalita ng mabubuting bagay gayong kayo ay masasama? Sapagkat sa kasaganaan ng puso ay nagsasalita ang bibig.
Ang bautismo ni Juan, saan ba ito nagmula? Mula ba sa langit o mula sa mga tao?” At nagtalo sila sa isa't isa na nagsasabi, “Kung sasabihin natin, ‘Mula sa langit,’ sasabihin niya sa atin, ‘Bakit nga hindi ninyo siya pinaniwalaan?’
Magkakaroon ng pagtangis at pagngangalit ng mga ngipin kapag nakita na ninyo sina Abraham, Isaac, Jacob at ang lahat ng mga propeta sa kaharian ng Diyos, at kayo mismo'y inihahagis sa labas.
At sabihin ninyo sa may-ari ng bahay, ‘Sinasabi ng Guro sa iyo, “Saan ang silid para sa panauhin na doon ay aking kakainin ang Paskuwa na kasalo ng aking mga alagad?”’
At sinabi ni Pilato sa kanya, “Hindi mo ba naririnig kung gaano karaming bagay ang kanilang ipinaparatang laban sa iyo?”
Sapagkat sinasabi ko sa inyo, na alinman sa mga taong iyon na inanyayahan ay hindi makakatikim ng aking hapunan.”
Ngunit sinasabi ko sa inyo, tunay na dumating na si Elias at ginawa nila sa kanya ang anumang kanilang naibigan ayon sa nasusulat tungkol sa kanya.”
Kinuha niya ang limang tinapay at ang dalawang isda, tumingala siya sa langit, pinagpala at pinagputul-putol ang mga tinapay at ibinigay niya sa mga alagad upang ipamahagi sa mga tao. At ipinamahagi niya sa kanilang lahat ang dalawang isda.
Mapapalad kayong nagugutom ngayon,
Nang siya'y naghahanda na sa kanyang paglalakbay, may isang lalaking patakbong lumapit sa kanya, at pagluhod sa kanyang harapan, siya'y tinanong, “Mabuting Guro, ano ang dapat kong gawin upang magmana ng buhay na walang hanggan?”
“Sa puno nga ng igos ay pag-aralan ninyo ang talinghaga: kapag nananariwa ang kanyang sanga, at sumusupling ang mga dahon, ay nalalaman ninyo na malapit na ang tag-araw.
Dinala rin upang pataying kasama niya ang dalawang kriminal.
May pitong lalaking magkakapatid. Nag-asawa ang panganay at nang mamatay siya ay walang naiwang anak.
Kaya't tumakbo siya sa unahan at umakyat sa isang puno ng sikomoro upang makita siya, sapagkat siya'y daraan sa daang iyon.
At kung karapat-dapat ang sambahayan, hayaang mapunta roon ang inyong kapayapaan, ngunit kung hindi karapat-dapat, hayaang mabalik sa inyo ang inyong kapayapaan.
Ngunit nang makita ito ng mga Fariseo, sinabi nila sa kanya, “Tingnan mo, ginagawa ng mga alagad mo ang hindi ipinahihintulot na gawin sa Sabbath.”
Kapag tumayo na ang may-ari ng bahay at maisara na ang pinto, magsisimula kayong tumayo sa labas at tutuktok sa pintuan, na magsasabi, ‘Panginoon, pagbuksan mo kami.’ At siya'y sasagot sa inyo, ‘Hindi ko alam kung saan kayo nanggaling.’
Ito yaong tungkol sa kanya ay nasusulat,
Sila'y kanyang tinanong, “Ano ang ipinakikipagtalo ninyo sa kanila?”
kung paanong ang Anak ng Tao ay naparito hindi upang paglingkuran, kundi upang maglingkod, at upang ibigay ang kanyang buhay na pantubos sa marami.”
Gayundin naman ang mga punong pari, kasama ng mga eskriba ay nilibak siya na sinasabi sa isa't isa, “Iniligtas niya ang iba; hindi niya mailigtas ang kanyang sarili.
Noo'y ikasiyam ng umaga nang siya'y kanilang ipinako sa krus.
May isang babae na labindalawang taon nang dinudugo, at di mapagaling ng sinuman,
Nilalamon nila ang mga bahay ng mga balo, at sa pagkukunwari ay nananalangin sila ng mahahaba. Sila ay tatanggap ng lalong malaking kahatulan.”
Sapagkat ako man ay taong inilagay sa ilalim ng kapangyarihan at may mga kawal na nasasakupan ko. At sinasabi ko sa isa, ‘Humayo ka’ at siya'y humahayo; at sa isa naman, ‘Halika,’ at siya'y lumalapit; at sa aking alipin, ‘Gawin mo ito,’ at ito'y kanyang ginagawa.”
na nagtatanong, “Nasaan ang ipinanganak na hari ng mga Judio? Sapagkat nakita namin ang kanyang bituin sa silangan, at naparito kami upang siya'y sambahin.”
Ngayon, mayroong pitong magkakapatid na lalaki. Nag-asawa ang panganay, at namatay na walang anak;
Nang sumapit na ang gabi, sila ay lumabas sa lunsod.
Pagkatapos ay dinala siya ng diyablo sa isang mataas na lugar at ipinakita sa kanya sa isang saglit ang lahat ng mga kaharian sa sanlibutan.
si Mateo, si Tomas, si Santiago na anak ni Alfeo, si Simon na tinatawag na Masigasig,
Ngunit si Jesus ay hindi sumagot ng anuman, anupa't nanggilalas si Pilato.
Sila'y nagsisigaw at nagsabi, “Jesus, Panginoon, maawa ka sa amin.”
“Katotohanang sinasabi ko sa inyo na patatawarin ang lahat ng mga kasalanan ng anak ng mga tao at anumang paglapastangan na kanilang sabihin.
Ang nagsisikap magligtas ng kanyang buhay ay mawawalan nito; at ang mawalan ng kanyang buhay dahil sa akin ay makakatagpo nito.
Sinabi pa niya, “Ang lumalabas sa tao ang nakapagpaparumi sa tao.
Saka ipinatong na muli sa kanyang mga mata ang kanyang mga kamay; siya'y tumitig at bumalik ang kanyang paningin. Nakita niya ang lahat ng bagay na maliwanag.
Kaya't siya ay bumangon at dinala ang sanggol at ang ina nito nang gabing iyon, at pumunta sila sa Ehipto.
Ang pasimula ng ebanghelyo ni Jesu-Cristo, ang Anak ng Diyos.
Nang dumating sila kay Jesus, nakiusap silang mabuti sa kanya na sinasabi, “Siya ay karapat-dapat na gawan mo nito,
Ang hindi panig sa akin ay laban sa akin, at ang hindi ko kasamang nagtitipon ay nagkakalat.
Sapagkat sinasabi ko sa inyo, na maraming propeta at mga hari ang naghangad na makita ang inyong nakikita at hindi nila nakita, at marinig ang inyong naririnig at hindi nila narinig.”
Sinabi sa kanila ni Pilato, “At anong gagawin ko kay Jesus na tinatawag na Cristo?” Sinabi nilang lahat, “Ipako siya sa krus!”
Ngunit nang makita ng mga punong pari at mga eskriba ang mga kahanga-hangang bagay na kanyang ginawa, at ang mga batang sumisigaw sa templo at nagsasabi, “Hosana sa Anak ni David,” ay nagalit sila.
ni Melea, ni Mena, ni Matata, ni Natan, ni David,
Sa ikatlong pagkakataon ay kanyang sinabi sa kanila, “Bakit, anong kasamaan ang ginawa ng taong ito? Wala akong nakitang anumang batayan para sa parusang kamatayan. Kaya't siya'y aking ipapahagupit at saka palalayain.”
Sapagkat sinasabi ni Juan kay Herodes, “Hindi ipinahihintulot sa iyo na angkinin mo ang asawa ng iyong kapatid.”
Ngunit palibhasa'y alam ni Jesus ang kanilang mga iniisip ay sinabi niya, “Bakit nag-iisip kayo sa inyong mga puso ng masama?
At huwag ninyong katakutan ang mga pumapatay ng katawan, ngunit hindi nakakapatay ng kaluluwa, kundi katakutan ninyo siyang makakapuksa ng kaluluwa at ng katawan sa impiyerno.
Pagkatapos sila'y dumating sa lupain ng mga Gadareno, na katapat ng Galilea.
Subalit sinasabi ko sa inyo, na sa araw ng paghuhukom ay pananagutan ng mga tao ang bawat salita na binigkas na walang ingat.
Nang tanungin siya ng kanyang mga alagad kung ano ang kahulugan ng talinghagang ito,
At sinabi niya sa kanya, “Anak, pinagaling ka ng iyong pananampalataya, humayo kang payapa.”
Ngunit sumagot ang senturion at sinabi, “Panginoon, hindi ako karapat-dapat sa iyo na puntahan mo ang aking bahay, ngunit sabihin mo lamang ang salita at gagaling ang aking alipin.
Ngunit itong aking mga kaaway, na ayaw na ako'y maghari sa kanila, ay dalhin ninyo rito at patayin sila sa harapan ko.’”
Sila'y magkakabaha-bahagi; ang ama laban sa anak na lalaki, at ang anak na lalaki laban sa ama; ang ina laban sa anak na babae, at ang anak na babae laban sa kanyang ina; ang biyenang babae laban sa kanyang manugang na babae at ang manugang na babae laban sa kanyang biyenang babae.”
at kung paanong siya ay ibinigay ng mga punong pari at ng mga pinuno upang hatulan ng kamatayan, at siya'y ipinako sa krus.
Nang makasakay si Jesus sa bangka, sumunod sa kanya ang kanyang mga alagad.
Mula ng panahong iyon ay pinasimulan ni Jesus na ipaliwanag sa kanyang mga alagad na kailangang pumunta siya sa Jerusalem at magtiis ng maraming bagay sa kamay ng matatanda, ng mga punong pari at mga eskriba. Siya'y papatayin at muling bubuhayin sa ikatlong araw.
Sinundan siya ng isang binata na walang suot kundi isang telang lino lamang at siya'y kanilang sinunggaban.
Nang siya'y makita ni Jesus, kanyang tinawag siya at sinabi sa kanya, “Babae, pinalaya ka na sa iyong sakit.”
sa isang birheng nakatakdang ikasal sa isang lalaki, na ang pangalan ay Jose, mula sa sambahayan ni David. Ang pangalan ng birhen ay Maria.
Subalit umasa kami na siya ang tutubos sa Israel. Oo, at bukod sa lahat ng mga ito, ngayon ang ikatlong araw buhat nang mangyari ang mga bagay na ito.
Dumating sila sa kabilang ibayo ng dagat, sa lupain ng mga Geraseno.
At nang lumapit ang mga nauna, ang akala nila'y tatanggap sila ng mas malaking halaga; ngunit tumanggap din ang bawat isa sa kanila ng isang denario.
At ibabagsak ka sa lupa, ikaw at ang iyong mga anak na nasa iyo. Sa iyo'y hindi sila mag-iiwan ng bato sa ibabaw ng kapwa bato; sapagkat hindi mo kinilala ang panahon ng pagdalaw sa iyo.”
Ngunit alam ito ni Jesus kaya't sinabi niya, “O kayong maliliit ang pananampalataya, bakit kayo'y nagtatalo na wala kayong tinapay?
Pumunta ang taong ito kay Pilato at hiningi ang bangkay ni Jesus. At ipinag-utos ni Pilato na ibigay iyon.
Narinig ninyo ang kanyang paglapastangan! Ano ang inyong pasiya?” At hinatulan nilang lahat na siya'y dapat mamatay.
At namangha ang mga alagad sa kanyang mga salita. Ngunit muling sumagot sa kanila si Jesus, “Mga anak, napakahirap pumasok sa kaharian ng Diyos.
At sa lunsod na iyon ay may isang babaing balo na laging pumupunta sa kanya, na nagsasabi, ‘Bigyan mo ako ng katarungan laban sa aking kaaway.’
At nagpagaling siya ng maraming iba't ibang may karamdaman at nagpalayas siya ng maraming demonyo. Hindi niya pinahintulutang magsalita ang mga demonyo, sapagkat siya'y kilala nila.
Pagkatapos ay bumalik ang mga pastol na niluluwalhati at pinupuri ang Diyos dahil sa lahat ng kanilang narinig at nakita, ayon sa sinabi sa kanila.
Kung mayroong lugar na hindi kayo tanggapin at ayaw kayong pakinggan, sa pag-alis ninyo ay ipagpag ninyo ang alikabok na nasa inyong mga paa bilang patotoo laban sa kanila.”
Ang tumanggap ng limang talento ay umalis kaagad at ipinangalakal niya ang mga iyon, at nakinabang siya ng lima pang talento.
“Mag-ingat kayo sa mga eskriba na nagnanais lumakad na may mahahabang damit, at gustung-gusto ang mga pagpupugay sa mga pamilihan, ang pangunahing upuan sa mga sinagoga, at ang mga mararangal na lugar sa mga handaan.
Kapayapaan sa langit,
At ang mga nasa bato ay sila na pagkatapos makarinig ay tinanggap na may galak ang salita, subalit ang mga ito'y walang ugat; sila'y sumampalataya nang sandaling panahon lamang at sa panahon ng pagsubok ay tumalikod.
at para sa kaluwalhatian ng iyong bayang Israel.”
At lumaki ang bata, lumakas, napuno ng karunungan, at sumasakanya ang biyaya ng Diyos.
At sinasabi ko naman sa iyo, na ikaw ay Pedro, at sa ibabaw ng batong ito ay itatayo ko ang aking iglesya; at ang mga pintuan ng Hades ay hindi magwawagi laban sa kanya.
Nang matanaw niya si Jesus sa malayo, tumakbo siya at si Jesus ay kanyang sinamba.
Dumating ang Anak ng Tao na kumakain at umiinom at inyong sinasabi, ‘Tingnan ninyo, ang isang taong matakaw at maglalasing, kaibigan ng mga maniningil ng buwis at ng mga makasalanan!’
Kinuha ni Jose ang bangkay at binalot niya iyon ng isang malinis na telang lino,
Dumating ang isang babaing balo at siya'y naghulog ng dalawang kusing na ang halaga'y halos isang pera.
Habang nagsasalita pa siya, may isang dumating na mula sa bahay ng pinuno ng sinagoga na nagsasabi, “Patay na ang anak mong babae; huwag mo nang abalahin pa ang Guro.”
Ang Fariseo ay nagtaka nang makita si Jesus na hindi muna naghugas bago kumain.
At nagsugo pa siya ng ikatlo. Ito ay kanilang sinugatan at pinagtabuyan.
Ituturo niya sa inyo ang isang malaking silid sa itaas na may mga kagamitan. Doon kayo maghanda.”
at pagbabalik mula sa libingan, ibinalita nila ang lahat ng mga bagay na ito sa labing-isa, at sa lahat ng iba pa.
at sa lupa'y kapayapaan sa mga taong kinalulugdan niya.”
At biglang may dalawang lalaking nakikipag-usap sa kanya, sina Moises at Elias,
Ngunit hindi nila naunawaan ang kanyang sinabi at natakot silang magtanong sa kanya.
