At sinabi ni Laban kay Jacob, “Tingnan mo ang buntong ito at ang haligi na aking inilagay sa gitna natin.
At sino ang gagawa ng masama sa inyo kung kayo'y masigasig sa paggawa ng mabuti?
Pagkatapos, si Moises at ang matatanda sa Israel ay nag-utos sa taong-bayan, na sinasabi, “Tuparin ninyo ang lahat ng utos na iniuutos ko sa iyo sa araw na ito.
Sa Cesarea ay may isang lalaki na ang pangalan ay Cornelio, isang senturion ng tinatawag na pulutong Italiano;
Ngunit nang makita ito ni Simon Pedro, lumuhod siya sa paanan ni Jesus, na nagsasabi, “Lumayo ka sa akin, sapagkat ako'y taong makasalanan, O Panginoon.”
At sinabi niya sa kanila, “Humayo kayo sa buong sanlibutan, at inyong ipangaral ang ebanghelyo sa lahat ng nilikha.
Batiin ninyo si Asincrito, si Flegonte, si Hermes, si Patrobas, si Hermas, at ang mga kapatid na kasama nila.
lalo na dahil sa kalabisan ng mga pahayag. Kaya't upang ako'y huwag magyabang ng labis, binigyan ako ng isang tinik sa laman, isang sugo ni Satanas upang ako'y saktan, upang ako'y huwag magmalaki ng labis.
Lumapit sa kanya ang napakaraming tao na dala ang mga pilay, mga lumpo, mga bulag, mga pipi, at marami pang iba. Inilagay nila ang mga ito sa kanyang paanan at sila'y pinagaling niya.
Nakipaglaban ako ng mabuting pakikipaglaban, natapos ko na ang aking takbuhin, iningatan ko ang pananampalataya.
Bawat dakong matuntungan ng talampakan ng inyong paa ay magiging inyo; ang inyong magiging sakop ay mula sa ilang hanggang sa Lebanon, mula sa ilog, sa Ilog Eufrates, hanggang sa dagat kanluran.
At mula sa mga iyon, siya ay mag-aalay ng isang tinapay sa bawat handog, bilang isang handog sa Panginoon ; ito ay mapupunta sa paring magwiwisik ng dugo ng mga handog pangkapayapaan.
Kaya't nang sumibol ang mga halaman at namunga ay lumitaw rin ang damo.
Ang apoy sa ibabaw ng dambana ay pananatilihing nagniningas doon, at hindi ito papatayin. Ang pari ay magsusunog ng kahoy sa ibabaw niyon tuwing umaga, at aayusin niya sa ibabaw niyon ang handog na kanyang susunugin, at kanyang susunugin ito kasama ang taba ng mga handog pangkapayapaan.
Ganito ang ibig kong sabihin: ang tagapagmana, habang bata pa ay hindi nakahihigit sa mga alipin bagama't siya ang may-ari ng lahat,
Sapagkat silang lahat ay naghulog mula sa kanilang kasaganaan, ngunit siya sa kanyang kasalatan ay inihulog ang lahat ng nasa kanya, ang kanyang buong kabuhayan.”
Siya nga ay nagsasalita tungkol kay Judas na anak ni Simon Iscariote, sapagkat siya na isa sa labindalawa ang magkakanulo sa kanya.
Sinabi niya sa kanila, “Kayo rin ba ay hindi nakakaunawa? Hindi ba ninyo nalalaman, na anumang nasa labas na pumapasok sa tao ay hindi nakapagpaparumi sa kanya,
At sinabi niya, “Purihin ang Panginoon , ang Diyos ni Sem! At si Canaan ay magiging alipin niya.
Ang Panginoong ating Diyos ay nakipagtipan sa atin sa Horeb.
Sapagkat aling dakilang bansa ang may Diyos na napakalapit sa kanila, na gaya ng Panginoon nating Diyos tuwing tumatawag tayo sa kanya?
Huwag kayong magsinungaling sa isa't isa, yamang hinubad na ninyo ang dating pagkatao pati ang mga gawa nito,
Ngunit sumagot ang matatalino na nagsasabi, ‘Maaaring hindi sapat para sa amin at para sa inyo. Kaya't pumunta kayo sa mga nagtitinda at bumili kayo ng para sa inyo.’
At mula roon ay nagpatuloy sila patungo sa Beer, na siyang balon kung saan sinabi ng Panginoon kay Moises, “Tipunin mo ang bayan at bibigyan ko sila ng tubig.”
Subalit ang kautusan ay hindi nakasalig sa pananampalataya; sa halip, “Ang gumagawa ng mga iyon ay mabubuhay sa mga iyon.”
Sumagot si Jesus, “May isang taong bumaba mula sa Jerusalem patungo sa Jerico at siya'y nahulog sa kamay ng mga tulisan, hinubaran siya ng mga ito at binugbog. Pagkatapos ay umalis sila at iniwan siyang halos patay.
Ang sinumang nagpapahayag na si Jesus ay Anak ng Diyos, ang Diyos ay nananahan sa kanya, at siya'y sa Diyos.
At nawa'y palaguin at pasaganain kayo ng Panginoon sa pag-ibig sa isa't isa at sa lahat ng tao, gaya naman namin sa inyo.
Anuman ang inyong ginagawa, ay inyong gawin ng buong puso, na gaya ng sa Panginoon, at hindi sa mga tao;
Lahat ng mga panganay sa lupain ng Ehipto ay mamamatay, mula sa panganay ng Faraon na nakaupo sa kanyang trono, hanggang sa panganay ng aliping babaing nasa likuran ng gilingan, at ang lahat ng mga panganay ng mga hayop.
Pasakop kayo sa bawat pamahalaan ng tao alang-alang sa Panginoon, maging sa hari, na kataas-taasan,
Sapagkat siya na sinugo ng Diyos ay nagsasalita ng mga salita ng Diyos, sapagkat hindi niya sinusukat ang pagbibigay niya ng Espiritu.
Nang marinig nila ang mga bagay na ito, tumahimik sila at niluwalhati ang Diyos, na sinasabi, “Kung gayo'y binigyan din ng Diyos ang mga Hentil ng pagsisisi tungo sa buhay.”
Ang mga angkan ng mga anak ni Kohat ay magkakampo sa tagiliran ng tabernakulo, sa gawing timog.
Sapagkat kung ang bagay na lumilipas ay may kaluwalhatian, ang nananatili ay may higit pang kaluwalhatian.
Pagkalipas ng mga araw na ito ay naglihi ang kanyang asawang si Elizabeth. Siya ay nagtago nang limang buwan, na nagsasabi,
“Mapapalad ang mga pinatatawad sa kanilang mga masasamang gawa, at ang mga tinakpan ang kanilang mga kasalanan.
Sumagot si Jesus sa kanila, “Isang bagay ang aking ginawa at pinagtatakhan ninyong lahat ito.
Samantala, hinihintay ng mga tao si Zacarias at nagtaka sila sa kanyang pagtatagal sa loob ng templo.
Pagkatapos ng mga bagay na ito ay nakita ko ang isa pang anghel na nananaog mula sa langit, na may dakilang kapangyarihan; at ang lupa ay naliwanagan ng kanyang kaluwalhatian.
Sa pamamagitan nito ay pinupuri natin ang Panginoon at Ama, at sa pamamagitan nito ay nilalait natin ang mga taong ginawa ayon sa larawan ng Diyos.
Sapagkat mula ngayon ang lima sa isang bahay ay magkakabaha-bahagi; tatlo laban sa dalawa, at dalawa laban sa tatlo.
kundi nakikita natin si Jesus, na sa sandaling panahon ay ginawang mababa kaysa mga anghel, na dahil sa pagdurusa ng kamatayan ay pinutungan ng kaluwalhatian at karangalan, upang sa pamamagitan ng biyaya ng Diyos ay maranasan niya ang kamatayan alang-alang sa lahat.
At sinabi sa kanila ni Jesus, “Ang mga anak ng panahong ito ay nag-aasawa at pinag-aasawa,
Nang magkagayo'y lumakas ang loob ng lahat, at sila nama'y kumain din.
Kumuha sina Sem at Jafet ng isang balabal, inilagay sa balikat nilang dalawa, lumakad ng paatras, at tinakpan ang kahubaran ng kanilang ama. At ang mukha nila ay patalikod, at hindi nila nakita ang kahubaran ng kanilang ama.
upang mapasainyong lahat ang matuwid na dugo na dumanak sa ibabaw ng lupa buhat sa dugo ni Abel na matuwid, hanggang sa dugo ni Zacarias na anak ni Baraquias na inyong pinaslang sa pagitan ng templo at ng dambana.
At ang bawat bumigkas ng salita laban sa Anak ng Tao ay patatawarin; ngunit ang magsalita ng kalapastanganan laban sa Espiritu Santo ay hindi patatawarin.
Kaya't pinuntahan nina Moises at Aaron ang Faraon at sinabi sa kanya, “Ganito ang sabi ng Panginoon , ang Diyos ng mga Hebreo, ‘Hanggang kailan ka tatangging magpakumbaba sa harap ko? Payagan mo nang umalis ang aking bayan, upang sila'y makasamba sa akin.
Bukod dito, may isang malaking banging inilagay sa pagitan natin, upang ang mga nagnanais tumawid buhat dito patungo sa inyo ay hindi maaari at wala ring makatatawid mula riyan patungo sa amin.’
at sa kanya ay ibinahagi ni Abraham ang ikasampung bahagi ng lahat. Una, ang kahulugan ng kanyang pangalan ay hari ng katuwiran; ikalawa, siya rin ay hari ng Salem, na ang kahulugan ay hari ng kapayapaan.
Dahil dito'y inusig ng mga Judio si Jesus sapagkat ginagawa niya ang mga bagay na ito sa araw ng Sabbath.
Pumarito ka ngayon, isinasamo ko sa iyo, at sumpain mo ang bayang ito para sa akin; sapagkat sila'y totoong makapangyarihan para sa akin. Baka sakaling ako'y manalo at aming matalo sila, at mapalayas ko sila sa lupain, sapagkat alam ko na ang iyong pinagpala ay nagiging pinagpala at ang iyong sinusumpa ay isusumpa.”
Sinabi ng Panginoon kay Moises sa ilang ng Sinai, sa unang buwan ng ikalawang taon pagkatapos na sila'y makaalis sa lupain ng Ehipto,
Ngunit ang lahat ng mga dalaga na hindi pa nakakilala ng lalaki dahil hindi pa nasisipingan ang mga ito ay hayaan ninyong mabuhay upang mapasainyo.
Aking makikita siya, ngunit hindi ngayon; aking pagmamasdan siya, ngunit hindi sa malapit: Lalabas ang isang bituin sa Jacob, at may isang setro na lilitaw sa Israel, at dudurugin ang noo ng Moab, at lilipulin ang lahat ng mga anak ng kaguluhan.
Hindi rin inilalagay ang bagong alak sa mga lumang sisidlang balat; sapagkat kung gayon, puputok ang mga balat, at matatapon ang alak, at masisira ang mga balat; ngunit inilalagay ang bagong alak sa mga bagong balat, at pareho silang tumatagal.
Mga alipin, sundin ninyo ang inyong mga panginoon sa laman na may takot at panginginig, sa katapatan ng inyong puso, na gaya ng kay Cristo,
Sapagkat kung ipahahayag mo sa pamamagitan ng iyong bibig si Jesus na Panginoon, at sasampalataya ka sa iyong puso na binuhay siyang muli ng Diyos mula sa mga patay, ay maliligtas ka.
at ang mga bagay na iyong narinig sa akin sa harap ng maraming saksi ay siya mo ring ipagkatiwala sa mga taong tapat na makakapagturo rin naman sa iba.
Sila'y sinidlan ng malaking takot at sinabi sa isa't isa, “Sino nga ito, na pati ang hangin at ang dagat ay sumusunod sa kanya?”
At nakita ni Moises ang lahat ng gawain at kanilang ginawa iyon; kung paanong iniutos ng Panginoon ay gayon nila ginawa. At binasbasan sila ni Moises.
Kapag ikaw ay lumapit sa nakatayong trigo ng iyong kapwa, mapipitas mo ng iyong kamay ang mga uhay; ngunit huwag kang gagamit ng karit sa nakatayong trigo ng iyong kapwa.
Sapagkat sa aking pagdaraan, at sa pagmamasid ng mga bagay na inyong sinasamba, ay nakatagpo din naman ako ng isang dambana na may sulat na ganito, ‘SA ISANG DI-KILALANG DIYOS.’ Kaya't ang sinasamba ninyo na hindi kilala ay siyang ipahahayag ko sa inyo.
Kung may magsabi sa inyo, ‘Narito ang Cristo!’ o, ‘Tingnan ninyo naroon siya!’ huwag ninyong paniwalaan.
Sa loob ng tatlong araw, siya'y walang paningin at hindi kumain ni uminom man.
Hinipan ng ikaapat na anghel ang kanyang trumpeta at tinamaan ang ikatlong bahagi ng araw, ang ikatlong bahagi ng buwan, at ang ikatlong bahagi ng bituin kaya't nagdilim ang ikatlong bahagi nila, at ang ikatlong bahagi ng maghapon ay hindi nagliwanag, at gayundin naman ang gabi.
Nang makita ng Panginoon na si Lea ay kinapootan, binuksan niya ang kanyang bahay-bata; subalit si Raquel ay baog.
Samantala, si Pedro ay nakaupo sa labas ng bakuran. Lumapit sa kanya ang isang aliping babae, na nagsasabi, “Ikaw ay kasama rin ni Jesus na taga-Galilea.”
ang kaalaman ng pagpipigil; ang pagpipigil ng pagtitiis; ang pagtitiis ng pagiging maka-Diyos;
Sapagkat ang ating pakikipaglaban ay hindi laban sa laman at dugo, kundi laban sa mga pinuno, laban sa mga may kapangyarihan, laban sa mga kapangyarihang di-nakikita na naghahari sa sanlibutan sa kadilimang ito, laban sa hukbong espirituwal ng kasamaan sa kalangitan.
sa tunog ng trumpeta, at sa tunog ng mga salita na ang nakarinig ay nakiusap na huwag nang magsalita pa sa kanila ng anuman.
Sa pagtanaw nila ay nakita nilang naigulong na ang bato na lubhang napakalaki.
Magkaroon ka lamang ng isang tunay at tapat na pabigat; magkaroon ka lamang ng isang tunay at tapat na takalan upang ang iyong mga araw ay tumagal sa ibabaw ng lupaing ibinibigay sa iyo ng Panginoon mong Diyos.
“Ang isang taga-ibang bayan ay huwag kakain ng mga banal na bagay; sinumang manunuluyan sa pari, o aliping upahan niya ay huwag kakain ng banal na bagay.
at umalis at naglingkod sa ibang mga diyos, at sumamba sa kanila, o sa araw, sa buwan, o sa anumang bagay na nasa langit na ipinagbabawal ko,
at nagsabi, “Panginoon, mahabag ka sa aking anak na lalaki, sapagkat siya'y may epilepsiya at lubhang nahihirapan; sapagkat madalas siyang bumabagsak sa apoy at sa tubig.
at lumakad kayo sa pag-ibig, gaya ng pag-ibig ni Cristo sa atin at ibinigay ang kanyang sarili para sa atin bilang handog at alay sa Diyos upang maging samyo ng masarap na amoy.
Kapag sila'y pumapasok sa toldang tipanan ay maghuhugas sila ng tubig, upang sila'y huwag mamatay, o kapag sila'y lumalapit sa dambana upang maglingkod, upang magsunog ng handog sa Panginoon na pinaraan sa apoy.
At narinig ko ang dambana na nagsasabi, “Opo, Panginoong Diyos na Makapangyarihan sa lahat, tunay at matuwid ang iyong mga hatol!”
Nang dumating ang panahon ng kanyang panganganak, kambal ang nasa kanyang tiyan.
at gagawa ka mula sa mga ito ng banal na langis na pambuhos, isang pabangong tinimpla ayon sa pagtitimpla ng manggagawa ng pabango; siya ngang magiging banal na langis na pambuhos.
Ngunit sinasabi ko sa inyo, isang higit na dakila kaysa templo ang narito.
at sinabi niya sa kanila, ‘Pumunta rin kayo sa ubasan, at anumang nararapat ay ibibigay ko sa inyo.’ At pumunta sila.
Ang ibang mga Israelita ay magtatayo ng kanilang mga tolda, ayon sa kani-kanilang pangkat.
Sa likod ng ikalawang tabing ay ang tabernakulo na tinatawag na Dakong Kabanal-banalan.
Kanyang ginawa ang pitong ilawan niyon, at ang mga sipit at ang mga pinggan niyon, na lantay na ginto.
at upang hintayin ang kanyang Anak mula sa langit, na kanyang binuhay mula sa mga patay, si Jesus na nagliligtas sa atin mula sa poot na darating.
Sapagkat pinagtitiisan ninyo ito kapag inaalipin kayo, o kapag nilalapa kayo, o kapag kayo'y pinagsasamantalahan, o kapag pinagyayabangan, o kapag kayo'y sinasampal sa mukha.
“Hayaang ang mga salitang ito ay pumasok sa inyong mga tainga, sapagkat ang Anak ng Tao ay ibibigay sa mga kamay ng mga tao.”
Maaari din kayong bumili mula sa mga anak ng mga dayuhan na nakikipanirahan sa inyo, at sa kanilang mga sambahayan na kasama ninyo, na kanilang ipinanganak sa inyong lupain, at sila'y magiging inyong pag-aari.
At inyong ituring ang pagtitiyaga ng ating Panginoon bilang kaligtasan. Gaya rin ng ating minamahal na kapatid na si Pablo, ayon sa karunungang ibinigay sa kanya, ay sinulatan kayo;
Subalit ang mga anak ng naging mga asawang-lingkod ni Abraham ay binigyan ni Abraham ng mga kaloob. Habang nabubuhay pa siya ay inilayo niya ang mga ito kay Isaac na kanyang anak. Kanyang pinapunta sila sa lupaing silangan.
‘Ako ang Diyos ng iyong mga ninuno, ang Diyos ni Abraham, at ni Isaac, at ni Jacob.’ Nanginig si Moises at hindi nangahas tumingin.
kahit ibigay sa akin ni Balak ang kanyang bahay na punô ng pilak at ginto ay hindi ako maaaring lumampas sa salita ng Panginoon na gumawa ng mabuti o masama sa aking sariling kalooban. Kung ano ang sabihin ng Panginoon ay siya kong sasabihin?
o sa mga gobernador na sinugo niya upang parusahan ang mga gumagawa ng masama at parangalan ang mga gumagawa ng mabuti.
At sinabi nila sa kanya, “Si Juan na Tagapagbautismo; at sabi ng iba, si Elias; at ng iba pa, isa sa mga propeta.”
Nanganak siya ng isang lalaki at kanyang pinangalanang Gershom sapagkat sinabi ni Moises, “Ako'y manlalakbay sa ibang lupain.”
Sila'y naglilingkod sa anyo at anino ng makalangit na santuwaryo; sapagkat si Moises ay binalaan ng Diyos nang malapit na niyang itayo ang tabernakulo, “Tiyakin mo na iyong gagawin ang lahat ng mga bagay ayon sa huwarang ipinakita sa iyo sa bundok.”
Ang mga ito man ay itinuturing na mga Refaim, na gaya ng mga Anakim; ngunit tinatawag silang Emita ng mga Moabita.
Magdadala ako ng tabak sa inyo upang ipaghiganti ang tipan; at kayo'y matitipon sa loob ng inyong mga lunsod, at magpapadala ako ng salot sa gitna ninyo, at kayo'y babagsak sa kamay ng kaaway.
Nang siya'y inilabas, nagpasabi siya sa kanyang biyenan, “Nagdalang-tao ako sa lalaking nagmamay-ari ng mga ito.” At sinabi pa niya, “Nakikiusap ako sa inyo, inyong kilalanin kung kanino ang mga ito, ang singsing, ang pamigkis, at ang tungkod.”
Itututok ko ang aking mukha laban sa inyo, at kayo'y masasaktan sa harapan ng inyong mga kaaway. Ang mga napopoot sa inyo ay maghahari sa inyo, at kayo'y tatakas nang walang humahabol sa inyo.
At umalis mula sa Pafos si Pablo at ang kanyang mga kasama at nakarating sa Perga sa Pamfilia. Ngunit iniwan sila ni Juan at nagbalik sa Jerusalem.
upang kanyang maiharap sa kanyang sarili ang isang maluwalhating iglesya, na walang batik, o kulubot, o anumang gayong bagay, kundi siya ay maging banal at walang dungis.
Ito ay inyong natutunan kay Epafras na aming minamahal na kapwa alipin. Siya ay isang tapat na lingkod ni Cristo alang-alang sa inyo,
Sa ganito lamang paraan sila papayag na tumirang kasama natin, upang maging isang bayan: na patuli ang lahat ng lalaki sa atin, na gaya naman nila na mga tuli.
At ilalagay mo sa hapag ang tinapay na handog sa harap ko palagi.
At ibinuhos ng ikaapat ang kanyang mangkok sa araw at pinahintulutan itong pasuin ng apoy ang mga tao.
Kanyang inilagay ang tabing para sa pintuan ng tabernakulo.
Ibig mo ba akong patayin, gaya ng pagpatay mo kahapon sa Ehipcio?’
Dito'y naging ganap ang pag-ibig sa atin upang tayo'y magkaroon ng lubos na pagtitiwala sa araw ng paghuhukom; sapagkat kung ano siya, ay gayundin naman tayo sa sanlibutang ito.
Pagpasok ni Pedro, sinalubong siya ni Cornelio at nagpatirapa sa kanyang paanan, at siya'y sinamba.
Kayo'y manatili sa akin, at ako'y sa inyo. Gaya ng sanga na hindi magbubunga buhat sa kanyang sarili malibang nakakabit sa puno, gayundin naman kayo, malibang kayo'y manatili sa akin.
Ang mga lunsod na inyong ibibigay ay ang inyong anim na lunsod-kanlungan.
At nagbuntong-hininga siya nang malalim sa kanyang espiritu at sinabi, “Bakit humahanap ng tanda ang salinlahing ito? Katotohanan ang sinasabi ko sa inyo, walang tanda na ibibigay sa salinlahing ito.”
At lumabas ang isa pang anghel mula sa templo sa langit na siya rin ay may matalas na karit.
Sumagot si Nathanael sa kanya, “Rabi, ikaw ang Anak ng Diyos; ikaw ang Hari ng Israel.”
At siya'y tumanggap ng isang kopa at nang siya'y makapagpasalamat, sinabi niya, “Kunin ninyo ito, at inyong paghati-hatian.
At si Jesus ay tumigil at ipinag-utos na dalhin ang tao sa kanya. Nang lumapit ito ay kanyang tinanong,
Mga kapatid ko, huwag maging guro ang marami sa inyo, yamang nalalaman nating hahatulan tayo ng mas mahigpit.
“Sa araw ng Sabbath ay dalawang korderong lalaki na isang taong gulang na walang kapintasan, at dalawang ikasampung bahagi ng isang efa ng piling harina bilang handog na butil na hinaluan ng langis, at ang handog na inumin niyon.
Ngayon, nais naming malaman ninyo, mga kapatid, ang biyaya ng Diyos na ipinagkaloob sa mga iglesya ng Macedonia;
Nang makalakad pa siya ng kaunti, nakita niya sina Santiago na anak ni Zebedeo at si Juan na kanyang kapatid na naghahayuma ng mga lambat sa kanilang bangka.
Sa telang asul, kulay-ube, at pula ay gumawa sila ng mga kasuotang mahusay ang pagkayari para sa pangangasiwa sa dakong banal; kanilang ginawa ang mga banal na kasuotan para kay Aaron; gaya ng iniutos ng Panginoon kay Moises.
Sinabi ng mga Judio, “Tingnan ninyo kung gaano ang pagmamahal niya sa kanya!”
Sa pananampalataya si Noe, nang mabigyan ng Diyos ng babala tungkol sa mga bagay na hindi pa nakikita, ay pinakinggan ang babala at gumawa ng isang daong para sa kaligtasan ng kanyang sambahayan. Sa pamamagitan nito ay hinatulan niya ang sanlibutan, at siya'y naging tagapagmana ng katuwirang ayon sa pananampalataya.
At kung iyon ay alinmang hayop na marumi na hindi maihahandog na alay sa Panginoon , dadalhin niya ang hayop sa harapan ng pari;
Noon ay dinadala sa kanya maging ang mga sanggol, upang kanyang hawakan sila. Subalit nang makita ito ng mga alagad, sila'y sinaway nila.
Pumaroon sa libingan ang ilang kasama namin at nakita nila ang ayon sa sinabi ng mga babae, subalit siya'y hindi nila nakita.”
Tapat ang salita at nararapat tanggapin nang lubos, na si Cristo Jesus ay pumarito sa sanlibutan upang iligtas ang mga makasalanan; na ako ang pangunahin sa mga ito.
Tutuliin ng Panginoon mong Diyos ang iyong puso at ang puso ng iyong binhi, upang ibigin mo ang Panginoon mong Diyos ng buong puso at kaluluwa mo, upang ikaw ay mabuhay.
Ang mga pinuno ay naghandog rin ng mga alay para sa pagtatalaga ng dambana nang araw na ito ay buhusan ng langis; ang mga pinuno ay naghandog ng kanilang alay sa harap ng dambana.
Habang sila'y naglalakbay, ang matinding takot sa Diyos ay dumating sa mga bayang nasa palibot nila, at hindi nila hinabol ang mga anak ni Jacob.
huwag maging tamad sa pagsisikap, maging maalab sa espiritu, na naglilingkod sa Panginoon.
Subalit ang ikapitong taon ay magiging ganap na kapahingahan sa lupain, isang Sabbath sa Panginoon ; huwag mong hahasikan ang iyong bukid, ni pupungusan ang iyong ubasan.
ang anghel na tumubos sa akin sa bawat kasamaan, nawa'y pagpalain niya ang mga batang ito; at tawagin nawa sila sa aking pangalan, at sa pangalan ng aking mga magulang na sina Abraham at Isaac, at nawa'y dumami sila sa ibabaw ng lupa.”
Sapagkat sasabihin ng Faraon tungkol sa mga anak ni Israel, ‘Nagkabuhul-buhol sila sa lupain; sila'y nakukulong ng ilang.’
Saanman kayo hindi tanggapin, sa pag-alis ninyo sa bayang iyon ay ipagpag ninyo ang alikabok sa inyong mga paa, bilang patotoo laban sa kanila.”
Mabuti ang hindi kumain ng karne, ni uminom ng alak, ni gumawa ng anuman na ikatitisod ng iyong kapatid.
Sapagkat ang ating pagkamamamayan ay nasa langit; mula roon ay hinihintay naman natin ang Tagapagligtas, ang Panginoong Jesu-Cristo,
Ang isa sa dalawang nakarinig ng pagsasalita ni Juan, at sumunod sa kanya, ay si Andres na kapatid ni Simon Pedro.
Gaya ng sinasabi, “Ngayon, kung marinig ninyo ang kanyang tinig, huwag ninyong papagmatigasin ang inyong mga puso, na gaya ng sa paghihimagsik.”
“‘Huwag kang magkakaroon ng ibang mga diyos sa harapan ko.
Sinasabi ko sa inyo, higit pang mapagtitiisan sa araw na iyon ang Sodoma kaysa bayang iyon.
Alin sa dalawa ang gumanap ng kalooban ng kanyang ama?” Sinabi nila, “Ang una.” Sinabi ni Jesus sa kanila, “Katotohanang sinasabi ko sa inyo, ang mga maniningil ng buwis at ang mga masamang babae ay nauuna sa inyo sa pagpasok sa kaharian ng Diyos.
Nakita siya ng lahat ng tao na lumalakad at nagpupuri sa Diyos.
Sila ay sumigaw na nagsasabi, “Anong gagawin mo sa amin, O Anak ng Diyos? Naparito ka ba upang pahirapan kami bago dumating ang takdang panahon?”
Kanyang binalot iyon ng lantay na ginto, ang ibabaw niyon, at ang mga tagiliran niyon sa palibot, ang mga sungay niyon at kanyang iginawa ng isang moldeng ginto sa palibot.
Susumpain ang bunga ng iyong katawan, at ang bunga ng iyong lupa, ang karagdagan ng iyong bakahan at ang mga anak ng iyong kawan.
Pagka-umaga nang unang araw ng linggo, pagkasikat ng araw, pumunta sila sa libingan.
Sa pananampalataya si Abraham, nang tawagin, ay sumunod upang pumunta sa isang lugar na kanyang tatanggapin bilang pamana; at siya'y pumunta na hindi nalalaman ang kanyang pupuntahan.
at sa pamamagitan ng kalooban niya tayo'y ginawang banal sa pamamagitan ng pag-aalay ng katawan ni Cristo minsan magpakailanman.
si Mateo, si Tomas, si Santiago na anak ni Alfeo, si Simon na tinatawag na Masigasig,
Sa muling pagkabuhay, sino sa kanila ang magiging asawa ng babae? Sapagkat siya'y naging asawa ng pito.”
Kaya't maging handa kayo, sapagkat hindi ninyo nalalaman kung kailan darating ang panginoon ng bahay, kung sa gabi, sa hatinggabi, sa pagtilaok ng manok, o sa umaga.
Ang biyaya ng Panginoong Jesus ay mapasa mga banal. Amen.
Gagawin ninyo ang aking mga tuntunin at tutuparin ninyo ang aking mga batas at lakaran ninyo ang mga iyon: Ako ang Panginoon ninyong Diyos.
Ngunit nang makilala nila na siya'y isang Judio, sa loob ng halos dalawang oras silang lahat ay nagsigawan na may isang tinig, “Dakila si Artemis ng mga taga-Efeso!”
Kaya't sinasabi ko sa inyo, ang marami niyang kasalanan ay pinatawad na, sapagkat siya ay nagmahal ng malaki. Subalit ang pinatatawad ng kaunti ay nagmamahal nang kaunti.”
Ngayon, ipagkaloob nawa ng Diyos ng pagtitiis at kaaliwan, na kayo ay magkaisa ng pag-iisip sa isa't isa ayon kay Cristo Jesus,
May umahon sa ilog na pitong bakang magaganda ang anyo at matataba at ang mga ito ay kumain ng damo.
“Bibilang ka ng pitong Sabbath ng taon, makapitong pitong taon; at lahat ng mga araw ng pitong Sabbath ng mga taon ay magiging apatnapu't siyam na taon sa inyo.
Nang sumapit na ang mga araw ng kanilang paglilinis ayon sa kautusan ni Moises, kanilang dinala siya sa Jerusalem upang iharap siya sa Panginoon
Walang sinumang nakakita kailanman sa Diyos. Ang Diyos na tanging Anak na nasa kandungan ng Ama ang nagpakilala sa kanya.
Ngunit nang malaman ni Jesus ay sinabi niya sa kanila, “Bakit ninyo ginugulo ang babae? Sapagkat gumawa siya sa akin ng isang mabuting bagay.
Igagawa mo ito ng pitong ilaw, at ang mga ilaw ay sisindihan upang magbigay liwanag sa dakong katapat nito.
At siya'y lumabas, at umiyak nang buong pait.
Gumising ka, at palakasin mo ang mga bagay na natitira, na malapit nang mamatay, sapagkat hindi ko natagpuang ganap ang iyong mga gawa sa harapan ng aking Diyos.
Ngunit tumayo ang ilan mula sa sinagoga, na tinatawag na Mga Pinalaya at ng mga Cireneo, at ng mga Alejandrino, at ng mga taga-Cilicia, at taga-Asia, at nakipagtalo kay Esteban.
ngunit ang mga lamang-loob at mga paa ay huhugasan niya ng tubig. Susunugin ng pari ang kabuuan nito sa ibabaw ng dambana bilang handog na sinusunog, isang handog na pinaraan sa apoy na isang mabangong samyo sa Panginoon .
“Ito ang mga tuntunin at mga batas na inyong tutuparin sa lupain na ibinibigay sa iyo ng Panginoon , ng Diyos ng iyong mga ninuno upang angkinin, sa lahat ng mga araw na inyong ilalagi sa ibabaw ng lupa.
sapagkat siya ay nakita nilang lahat at sila'y nasindak. Ngunit agad siyang nagsalita sa kanila at sinabi, “Lakasan ninyo ang inyong loob. Ako ito; huwag kayong matakot.”
Subalit paglingon niya at pagtingin sa kanyang mga alagad, sinaway niya si Pedro at sinabi, “Umalis ka diyan, Satanas! Sapagkat hindi mo iniisip ang mga bagay na ukol sa Diyos, kundi ang mga bagay na ukol sa tao.”
Sapagkat ang pangako na kanyang mamanahin ang sanlibutan ay hindi dumating kay Abraham o sa kanyang binhi sa pamamagitan ng kautusan kundi sa pamamagitan ng pagiging matuwid ng pananampalataya.
Mula ngayon ay huwag lalapit ang mga anak ni Israel sa toldang tipanan, baka sila'y magtaglay ng kasalanan, at mamatay.
Siya'y kanyang binasbasan na sinabi, “Pagpalain si Abram ng Kataas-taasang Diyos, na lumikha ng langit at ng lupa;
Higit sa lahat, magkaroon kayo ng maningas na pag-ibig sa isa't isa, sapagkat ang pag-ibig ay nagtatakip ng maraming kasalanan.
At kapag ang maraming kasamaan at kaguluhan ay dumating sa kanila, magpapatotoo ang awit na ito sa harapan nila bilang saksi; sapagkat hindi ito malilimutan sa mga bibig ng kanilang binhi. Sapagkat nalalaman ko ang kanilang iniisip, na kanilang binabalak gawin, bago ko sila dinala sa lupaing ipinangako kong ibibigay.”
Nakita ng lahat ng nakaupo sa Sanhedrin na nakatitig sa kanya na ang kanyang mukha ay katulad ng mukha ng isang anghel.
At inihagis niya sa templo ang mga piraso ng pilak at siya'y umalis. Humayo siya at nagbigti.
yamang taglay ninyo ang gayunding pakikipaglaban na inyong nakita sa akin, at ngayo'y nababalitaan ninyo tungkol sa akin.
At nang makita ito nina Santiago at Juan na kanyang mga alagad ay sinabi nila, “Panginoon, ibig mo bang kami ay magpababa ng apoy mula sa langit upang sila'y tupukin?”
Mga panginoon, pakitunguhan ninyo ang inyong mga alipin nang matuwid at makatarungan, yamang nalalaman ninyo na kayo man ay mayroon ding Panginoon sa langit.
Kung ako'y hindi gumawa sa gitna nila ng mga gawang hindi ginawa ng sinuman, hindi sana sila nagkaroon ng kasalanan. Subalit ngayon ay kanilang nakita at kinapootan nila ako at ang aking Ama.
Sila'y magkakaroon ng magkakaparehong bahagi na kakainin, bukod sa magmumula sa pinagbilhan sa pamana ng kanyang ama.
Iyong ipapangilin ang Pista ng mga Sanlinggo, ang mga unang bunga ng pag-aani ng trigo, at ang kapistahan ng pagtitipon ng ani sa katapusan ng taon.
Bawat panganay ng asno ay tutubusin mo ng isang kordero; at kung hindi mo tutubusin ito, iyong babaliin ang leeg nito. Lahat ng mga panganay na lalaki sa iyong mga anak ay iyong tutubusin.
Kaya't ipinagpag nila ang alikabok ng kanilang mga paa laban sa kanila, at nagtungo sila sa Iconio.
Anim na araw na gagawin ang mga gawain, subalit ang ikapitong araw ay Sabbath na ganap na kapahingahan, isang banal na pagpupulong. Huwag kayong gagawa ng anumang gawain; ito ay Sabbath sa Panginoon sa lahat ng inyong mga paninirahan.
Kung ang bukid ay tutubusin ng nagtalaga nito, siya ay magdaragdag ng ikalimang bahagi ng salaping inihalaga roon, at ito ay mapapasa-kanya.
Kahabag-habag ang sanlibutan dahil sa mga batong katitisuran! Ang mga pangyayaring magbubunga ng pagkatisod ay tiyak na darating. Ngunit kahabag-habag ang taong pagmumulan ng batong katitisuran!
At dinadala ng mga tao sa kanya ang maliliit na bata upang sila'y kanyang hipuin, ngunit sinaway sila ng mga alagad.
Pagkatapos, ang anghel ng Panginoon ay nagpauna uli at tumayo sa isang makipot na dako na walang daang lilikuan maging sa kanan o sa kaliwa.
Sila'y tatayo sa malayo dahil sa takot sa pahirap sa kanya, na nagsasabi, “Kahabag-habag, kahabag-habag ang dakilang lunsod, ikaw na makapangyarihang lunsod ng Babilonia! Sapagkat sa isang oras ay dumating ang hatol sa iyo.”
At hindi tayo binibigo ng pag-asa, sapagkat ang pag-ibig ng Diyos ay ibinuhos sa ating mga puso sa pamamagitan ng Espiritu Santo na ibinigay sa atin.
Si Jesus ay sumagot sa kanya, “Dahil ba sa sinabi ko sa iyo, ‘Nakita kita sa ilalim ng puno ng igos,’ kaya ikaw ay sumasampalataya? Higit na dakilang mga bagay ang makikita mo kaysa rito.”
sina Ruben, Simeon, Levi, Juda,
Sinabi ng Panginoon kina Moises at Aaron,
Ang bawat isa ay gumalang sa kanyang ina at sa kanyang ama, at inyong ingatan ang aking mga Sabbath; ako ang Panginoon ninyong Diyos.
Kaya't kanyang pinahayo ang kanyang mga kapatid, at sila'y umalis at kanyang sinabi sa kanila, “Huwag kayong mag-aaway sa daan.”
Ang Ama na nagsugo sa akin ay siyang nagpatotoo tungkol sa akin. Kailanma'y hindi ninyo narinig ang kanyang tinig, o hindi ninyo nakita ang kanyang anyo.
Patuloy na pinangunahan ni Moises ang Israel mula sa Dagat na Pula, at sila'y lumabas sa ilang ng Shur; sila'y lumakad ng tatlong araw sa ilang at hindi nakatagpo ng tubig.
sa kalinisan, kaalaman, pagtitiyaga, kagandahang-loob, kabanalan ng espiritu, tunay na pag-ibig,
yamang aming nalalaman, mga kapatid na minamahal ng Diyos, ang pagkahirang sa inyo.
Nang kanyang abutan sila, kanyang sinabi sa kanila ang mga salitang ito.
Sa ikalimang araw ay siyam na toro, dalawang lalaking tupa, labing-apat na korderong lalaki na isang taong gulang na walang kapintasan,
At aalalahanin mo na ikaw ay naging alipin sa lupain ng Ehipto, at tinubos ka ng Panginoon mong Diyos, kaya't iniuutos ko sa iyo ngayon ang bagay na ito.
At nakita ko ang isang makapangyarihang anghel na nagpapahayag sa malakas na tinig, “Sino ang karapat-dapat magbukas ng aklat at magtanggal ng mga tatak nito?”
Lumakad tayo nang maayos, gaya ng sa araw; huwag sa kalayawan at paglalasing, huwag sa kalaswaan at sa kahalayan, huwag sa mga away at paninibugho.
Ito ang aklat ng mga salinlahi ni Adan. Nang lalangin ng Diyos ang tao, siya ay nilalang sa wangis ng Diyos.
Nagharap sila ng mga sinungaling na saksi na nagsabi, “Ang taong ito'y hindi tumitigil sa pagsasalita ng mga salitang laban sa Dakong Banal na ito at sa Kautusan.
Pagkatapos ng mga bagay na ito, dumating ang salita ng Panginoon kay Abram sa isang pangitain, “Huwag kang matakot, Abram; ako ang iyong kalasag, ang iyong gantimpala ay magiging napakadakila.”
At kakainin ninyo ang laman ng inyong mga anak na lalaki, at kakainin ninyo ang laman ng inyong mga anak na babae.
Siya'y kanilang tinanong, “Sino ang taong nagsabi sa iyo, ‘Buhatin mo ang iyong higaan at lumakad ka?’”
nagpapatuloy ako tungo sa mithiin para sa gantimpala ng dakilang pagtawag ng Diyos kay Cristo Jesus.
Sapagkat ang sinumang ipinanganak ng Diyos ay dumadaig sa sanlibutan at ito ang tagumpay na dumadaig sa sanlibutan, ang ating pananampalataya.
Itinayo naman ng mga anak ni Ruben ang Hesbon, Eleale, Kiryataim,
“Huwag kayong matakot, munting kawan, sapagkat nakakalugod sa inyong Ama na ibigay sa inyo ang kaharian.
Mas madali pa para sa isang kamelyo ang dumaan sa butas ng isang karayom kaysa isang mayaman ang pumasok sa kaharian ng Diyos.”
Sinabi ni Esau sa kanyang ama, “Wala ka na bang basbas maliban sa isa, ama ko? Basbasan mo rin ako, ama ko.” At sumigaw si Esau at umiyak.
Pagkatapos na muling bigyan ng babala, kanilang hinayaan silang umalis na walang nakitang anumang bagay upang sila'y kanilang maparusahan dahil sa mga tao, sapagkat niluluwalhati nilang lahat ang Diyos dahil sa nangyari.
Si Jetro na pari sa Midian, biyenan ni Moises, ay nakabalita ng lahat na ginawa ng Diyos kay Moises at sa Israel na kanyang bayan, kung paanong inilabas ng Panginoon ang Israel sa Ehipto.
Pitong ulit na iwiwisik ng pari sa pamamagitan ng kanyang kanang daliri ang langis na nasa kanyang kaliwang kamay sa harapan ng Panginoon .
At kapag nagtanong sa iyo ang iyong anak sa panahong darating, na sasabihin, ‘Ano ito?’ iyong sasabihin sa kanya, ‘Sa pamamagitan ng lakas ng kamay ay inilabas tayo ng Panginoon sa Ehipto, mula sa bahay ng pagkaalipin.
Ang mga mata ni Lea ay mapupungay; at si Raquel ay magandang kumilos at kahali-halina.
makatotohanang pananalita, kapangyarihan ng Diyos, sa pamamagitan ng mga sandata ng katuwiran sa kanang kamay at sa kaliwa,
Nang panahong iyon, lumusong si Juda papalayo sa kanyang mga kapatid, at tumira malapit sa isang Adullamita na ang pangalan ay Hira.
At sinasabi ninyo, ‘Kung ipanumpa ninuman ang dambana, ay wala iyong kabuluhan, ngunit kung ipanumpa ninuman ang handog na nasa ibabaw nito, siya ay may pananagutan.’
Subalit nang unang araw ng sanlinggo sa pagbubukang-liwayway, pumunta sila sa libingan, dala ang mga pabango na kanilang inihanda.
Sapagkat lagi ninyong kasama ang mga dukha at kung kailan ninyo nais, magagawan ninyo sila ng mabuti, ngunit ako'y hindi ninyo laging makakasama.
yamang nalalaman na anumang mabuting bagay na gawin ng bawat tao, ito ay kanyang muling tatanggapin mula sa Panginoon, maging alipin o malaya.
at hindi ito dinala sa pintuan ng toldang tipanan, upang ialay sa Panginoon , ang taong iyon ay ititiwalag sa kanyang bayan.
ang dambana ng handog na sinusunog kasama ng lahat ng mga kasangkapan niyon, ang lababo at ang patungan niyon;
at isang ikasampung bahagi para sa bawat kordero sa labing-apat na kordero;
At ang lunsod ay hindi nangangailangan ng araw, o ng buwan man, upang magbigay-liwanag sa kanya, sapagkat ang liwanag niya ay ang kaluwalhatian ng Diyos, at ang ilaw doon ay ang Kordero.
Naghahanap ng paraan ang mga punong pari at ang mga eskriba kung paano nila maipapapatay si Jesus sapagkat natatakot sila sa mga tao.
Hindi ba't ikaw ang nagsabi, ‘Gagawa ako ng mabuti sa iyo at ang iyong binhi ay gagawin kong parang buhangin sa dagat na hindi mabibilang dahil sa karamihan.’”
Ang ilan sa kanyang mga alagad ay nagsabi sa isa't isa, “Ano itong sinasabi niya sa atin, ‘Sandali na lamang, at ako'y hindi na ninyo makikita, at muling sandali pa, at ako'y inyong makikita’ at, ‘Sapagkat ako'y pupunta sa Ama?’”
Kayo'y maninirahan sa mga kubol sa loob ng pitong araw; ang lahat ng katutubo sa Israel ay maninirahan sa mga kubol,
Pagkalulan sa isang barkong Adrameto na maglalayag sa mga daungan sa baybayin ng Asia, tumulak kami kasama si Aristarco na isang taga-Macedonia mula sa Tesalonica.
at nakalasap ng kabutihan ng salita ng Diyos, at ng mga kapangyarihan ng panahong darating,
Kaya't itinanong niya sa kanila ang oras nang siya'y nagsimulang gumaling. At sinabi nila sa kanya, “Kahapon, nang ika-isa ng hapon, nawalan siya ng lagnat.”
Tumingin siya sa kanyang mga alagad at sinabi, “Mapapalad kayong mga dukha, sapagkat sa inyo ang kaharian ng Diyos.
Sapagkat nang ang tinig ng iyong pagbati ay aking nadinig, gumalaw sa tuwa ang sanggol sa aking sinapupunan.
Si Rebecca ay may isang kapatid na ang pangalan ay Laban. Tumakbong papalabas si Laban patungo sa lalaki na nasa bukal.
“Kapag sinabi mo sa iyong puso, ‘Ang mga bansang ito ay higit na dakila kaysa akin; paano ko sila mapapalayas?’
Kaagad nilang iniwan ang kanilang mga lambat at sumunod sa kanya.
“Subalit kapag tiningnan ng pari, at nakitang nangitim ang dakong may sakit pagkatapos na malabhan, ito ay hahapakin mula sa kasuotan, o mula sa paayon, o mula sa pahalang.
Magkaroon kayo sa inyo ng ganitong pag-iisip na na kay Cristo Jesus din naman,
Pagkatapos ay ipinadala siyang nakagapos ni Anas kay Caifas na pinakapunong pari.
Ipinag-utos ni Jose na punuin ng trigo ang kanilang mga sisidlan at ibalik ang salapi ng bawat isa sa kanya-kanyang sako at sila'y bigyan ng mababaon sa daan. At ito ay ginawa para sa kanila.
“Ngunit tumaba si Jeshurun at nanipa; ikaw ay tumataba, ikaw ay lumalapad, ikaw ay naging makinis. Nang magkagayo'y tinalikuran niya ang Diyos na lumalang sa kanya, at hinamak ang Bato ng kanyang kaligtasan.
Kundi pinatnubayan ng Diyos ang taong-bayan paikot sa daang patungo sa ilang sa tabi ng Dagat na Pula. Ang mga anak ni Israel ay umahon mula sa lupain ng Ehipto na handa sa pakikipaglaban.
“Lahat ng mga ito na nasa tubig ay maaari ninyong kainin: anumang may mga kaliskis at mga palikpik, ay maaari ninyong kainin.
Ngunit kung ang isang tao ay nagdurusa bilang Cristiano, huwag niyang ikahiya ito, kundi luwalhatiin niya ang Diyos sa pangalang ito.
sa pamamagitan ng Diyos ng iyong ama, na tutulong sa inyo, ng Makapangyarihan sa lahat na magpapala sa inyo, pagpapala ng langit mula sa itaas, mga pagpapala ng mga kalaliman na nalalagay sa ibaba, mga pagpapala ng mga dibdib at ng bahay-bata.
Sapagkat ito ang pag-ibig sa Diyos, na ating tuparin ang kanyang mga utos at ang kanyang mga utos ay hindi pabigat.
patungkol sa mga hari at sa lahat ng nasa mataas na katungkulan upang tayo'y mamuhay na tahimik at payapa sa buong kabanalan at paggalang.
ang mga lalaki ay mga pastol ng kawan sapagkat sila'y naging tagapag-alaga ng hayop, at kanilang dinala ang kanilang mga kawan, mga bakahan, at ang lahat nilang ari-arian.’
Sinabi sa kanya ni Pedro, “Aeneas, pinapagaling ka ni Jesu-Cristo; bumangon ka, at ayusin mo ang iyong higaan.” Agad naman siyang bumangon.
Subalit kapag ang kawan ay mahina, hindi niya inilalagay ang mga ito, kaya't ang mahihina ay nagiging kay Laban at ang malalakas ay kay Jacob.
Ngunit sinabi ni Jesus, “Hayaan ninyo ang maliliit na bata, at huwag ninyo silang pagbawalang lumapit sa akin, sapagkat sa mga tulad nila nauukol ang kaharian ng langit.”
sapagkat ang Diyos natin ay isang apoy na tumutupok.
Siya'y umahon sa bundok, at tinawag niya ang kanyang mga naibigan at lumapit sila sa kanya.
Samantalang sinisiksik si Jesus ng napakaraming tao upang makinig ng salita ng Diyos, siya'y nakatayo sa tabi ng lawa ng Genesaret.
sa mga diyos ng mga bayan na nasa palibot ninyo na malapit sa iyo, o malayo sa iyo, mula sa isang dulo ng lupa hanggang sa kabilang dulo ng lupa;
Ang mga salamangkero ay nagsikap sa pamamagitan ng kanilang mga lihim na kaalaman na magpalabas ng mga kuto, ngunit hindi nila nagawa. Kaya't nagkaroon ng kuto sa tao at sa hayop.
Gaya naman ng sinasabi niya sa Hoseas, “Tatawagin kong ‘aking bayan’ ang hindi ko dating bayan; at ‘minamahal’ ang hindi dating minamahal.”
Pagkatapos ay makikita nila ang Anak ng Tao na dumarating na nasa isang ulap na may kapangyarihan at dakilang kaluwalhatian.
Pagkaraan nito ay nagkaroon ng pista ang mga Judio, at umahon si Jesus patungo sa Jerusalem.
Ipangingilin ninyo ang ikalimampung taon, at ipahahayag ninyo ang kalayaan sa buong lupain sa lahat ng mga mamamayan; at ito'y magiging jubileo sa inyo; at ang bawat isa sa inyo ay babalik sa kanyang sariling ari-arian, at ang bawat isa sa inyo ay babalik sa kanyang sariling sambahayan.
At nang bumalik si Jesus, masaya siyang tinanggap ng maraming tao, sapagkat silang lahat ay naghihintay sa kanya.
Ang pari na binuhusan ng langis ay kukuha ng dugo ng toro at dadalhin sa toldang tipanan;
At huwag kang sisiping sa anumang hayop upang dungisan mo ang iyong sarili kasama nito, ni ang babae ay huwag ibibigay ang sarili upang makasiping ng hayop, ito ay mahalay na pagtatalik.
Ang mga nagpapakain sa kanila ay tumakas at ibinalita sa lunsod at sa mga nayon. Kaya't nagdatingan ang mga tao upang tingnan kung ano ang nangyari.
Ngunit ang lahat ng mga ito ay pasimula lamang ng matinding paghihirap.
Sa halip, ay ang panloob na pagkatao na may kagandahang walang paglipas, ng isang mahinhin at maamong espiritu na napakahalaga sa paningin ng Diyos.
Habang patungo sila roon, ang ilan sa mga bantay ay pumunta sa lunsod at ibinalita sa mga punong pari ang lahat ng mga bagay na nangyari.
Ako ang pintuan. Ang sinumang pumasok sa pamamagitan ko ay maliligtas, at papasok at lalabas, at makakatagpo ng pastulan.
“Pagkalipas noon, O Haring Agripa, hindi ako naging suwail sa makalangit na pangitain,
Kanilang sinabi sa kanya, “Nasisiraan ka na.” Ngunit ipinilit niya na gayon nga. Ngunit kanilang sinabi, “Iyon ay kanyang anghel.”
At may dalawang tulisan na ipinakong kasama niya, isa sa kanan at isa sa kaliwa.
Ngunit ano ang pinuntahan ninyo upang makita? Isa bang taong nakasuot ng malalambot na damit? Tingnan ninyo, ang mga nagsusuot ng malambot na damit ay nasa mga bahay ng mga hari.
O Teofilo, sa unang aklat ay isinulat ko ang tungkol sa lahat ng ginawa at itinuro ni Jesus mula sa simula,
Hindi ko hinihiling na alisin mo sila sa sanlibutan, kundi ingatan mo sila mula sa masama.
Ito ang ibig kong sabihin: “Ang kautusan, na dumating pagkaraan ng apat na raan at tatlumpung taon, ay hindi nagpapawalang-bisa sa tipan na dati nang pinagtibay ng Diyos, upang pawalang-saysay ang pangako.
Huwag nga kayong tumulad sa kanila, sapagkat alam na ng inyong Ama ang mga bagay na inyong kinakailangan, bago pa kayo humingi sa kanya.
Sapagkat nilingap niya ang abang kalagayan ng kanyang alipin. Sapagkat tiyak na mula ngayon ay tatawagin akong mapalad ng lahat ng salinlahi.
Sapagkat maliwanag na ang ating Panginoon ay nagmula sa Juda at tungkol sa liping iyon ay walang sinabing anuman si Moises tungkol sa mga pari.
At ito ang handog na inyong kukunin sa kanila: ginto, pilak, tanso,
Araw-araw ay maghahandog ka ng toro na handog pangkasalanan bilang pantubos. Maghahandog ka rin ng handog pangkasalanan para sa dambana, kapag iyong iginagawa ng katubusan iyon; at iyong bubuhusan ito ng langis upang ito'y maitalaga.
Sapagkat kung sinasadya nating magkasala, matapos nating tanggapin ang lubos na pagkakilala sa katotohanan, ay wala ng natitira pang alay para sa mga kasalanan,
Itinuro niya ang kamay niya sa kanyang mga alagad, at sinabi, “Narito ang aking ina at ang aking mga kapatid!
At nabuksan ang kanilang mga mata. Mahigpit silang pinagbilinan ni Jesus, “Ingatan ninyo na walang makakaalam nito.”
At ginawa ni Balak ang sinabi ni Balaam, at naghandog ng isang toro at isang lalaking tupa sa bawat dambana.
Kaya't sinabi ng mga Judio sa isa't isa, “Saan pupunta ang taong ito na hindi natin siya matatagpuan? Pupunta kaya siya sa mga lupain kung saan nagkalat ang ating mga kababayan sa lupain ng mga Griyego at magtuturo sa mga Griyego?
Sinabi niya, “Jesus, alalahanin mo ako, pagdating mo sa iyong kaharian.”
“Bakit hindi ipinagbili ang pabangong ito ng tatlong daang denario, at ibinigay sa mga dukha?”
At lumapit din ang tumanggap ng isang talento at sinabi niya, ‘Panginoon, alam kong ikaw ay taong malupit, na gumagapas ka roon sa hindi mo hinasikan, at nagtitipon ka roon sa hindi mo kinalatan ng binhi.
Ang lahat ng taba niyon ay kanyang aalisin, gaya ng pag-aalis ng taba sa kordero na alay bilang handog pangkapayapaan, at ang mga ito ay susunugin ng pari sa dambana, sa ibabaw ng mga handog sa Panginoon na pinaraan sa apoy. Gayon gagawin ng pari ang pagtubos para sa kanya, para sa kanyang kasalanan na kanyang nagawa at siya'y patatawarin.
Siya'y nasa ilang ng apatnapung araw, at tinukso siya ni Satanas. Kasama siya ng mababangis na hayop at pinaglingkuran siya ng mga anghel.
Sinabi ni Moises, “Ganito ang sinasabi ng Panginoon : Sa hatinggabi ay lalabas ako sa gitna ng Ehipto.
at ang dalawang bato at ang tabang nasa mga iyon na nasa mga balakang, at ang lamad na nasa ibabaw ng atay na iyong aalisin na kasama ng mga bato.
Sinabi ng mga anak ni Israel kay Moises, “Narito, kami ay patay, kami ay napahamak, kaming lahat ay napahamak.”
Sa pananampalataya'y tinahak nila ang Dagat na Pula na tulad sa tuyong lupa, ngunit nang tangkaing gawin ito ng mga Ehipcio ay nalunod sila.
Nang kanyang buksan ito, nakita niya ang bata; at narito, ang sanggol ay umiyak. At kanyang kinaawaan siya at sinabi, “Ito'y isa sa mga anak ng mga Hebreo.”
Gayon gagawin ng pari ang pagtubos para sa nagkasala laban sa alinman sa mga bagay na ito, at siya ay patatawarin. Ang nalabi ay para sa pari gaya ng butil na handog.”
Sinabi ng Panginoon kay Moises, “Bakit tumatawag ka sa akin? Sabihin mo sa mga anak ni Israel na sila'y magpatuloy.
Sapagkat ang isang tipan ay pinagtitibay sa kamatayan, yamang ito'y walang bisa habang nabubuhay pa ang gumawa ng tipan.
Gaya ng mga libis na abot hanggang sa malayo, gaya ng mga halamanan sa tabi ng ilog, gaya ng aloe na itinanim ng Panginoon , gaya ng mga puno ng sedro sa tabi ng ilog.
“Ang mga bagay na lihim ay para sa Panginoon nating Diyos, ngunit ang mga bagay na hayag ay para sa atin at sa ating mga anak magpakailanman, upang ating magawa ang lahat ng mga salita ng kautusang ito.
at ipinahayag na Anak ng Diyos na may kapangyarihan ayon sa Espiritu ng kabanalan, sa pamamagitan ng pagkabuhay mula sa mga patay, na ito'y si Jesu-Cristo na Panginoon natin.
Nang makarating si Jesus sa kabilang pampang, sa lupain ng mga Gadareno, ay sinalubong siya ng dalawang inaalihan ng mga demonyo na lumabas mula sa mga libingan. Napakabangis nila kaya't walang makadaan doon.
Bawat higaang mahigaan ng may tulo ay magiging marumi; at bawat bagay na kanyang maupuan ay magiging marumi.
Huwag kang kukuha sa kanya ng patubo o pakinabang, kundi matakot ka sa iyong Diyos; hayaan mo siyang mabuhay na kasama mo.
Mula noon, si Jesus ay hindi na naglalakad nang hayagan sa gitna ng mga Judio, kundi pumunta siya sa lupaing malapit sa ilang, sa isang bayan na tinatawag na Efraim. Siya'y nanirahan doon kasama ng mga alagad.
Sinabi ni Jose sa kanila, “Ano itong ginawa ninyo? Hindi ba ninyo nalalaman na ang isang taong gaya ko ay makapanghuhula?”
O ang kalaliman ng mga kayamanan ng karunungan at ng kaalaman ng Diyos! Hindi masuri ang mga hatol niya, at hindi masiyasat ang kanyang mga daan!
“At sa Tabera, sa Massah, sa Kibrot-hataava ay inyong ginalit ang Panginoon .
Muli, dinala siya ng diyablo sa isang napakataas na bundok at ipinakita sa kanya ang lahat ng mga kaharian sa sanlibutan, at ang karangyaan ng mga ito.
Saan ako kukuha ng karne upang ibigay sa buong bayang ito? Sapagkat sila'y umiyak sa akin, na nagsasabi, ‘Bigyan mo kami ng karneng makakain namin.’
Gayundin naman kayo, kapag nagawa na ninyo ang lahat ng mga bagay na iniutos sa inyo, inyong sabihin, ‘Kami'y mga aliping walang kabuluhan, ginawa lamang namin ang aming katungkulan.’”
Ako mismo ang mananagot para sa kanya. Maaari mo akong panagutin para sa kanya. Kapag hindi ko siya naibalik sa iyo at naiharap sa iyo, ako ang magpapasan ng sisi magpakailanman.
Si Demetrio ay pinatototohanan ng lahat at ng katotohanan mismo; kami rin ay nagpapatotoo tungkol sa kanya at nalalaman mo na ang aming patotoo ay tunay.
Ang kanila nawang isipan ay maging laging ganito, na matakot sa akin, at kanilang tuparin ang lahat ng aking mga utos para sa ikabubuti nila at pati ng kanilang mga anak magpakailanman!
Isuot ninyo ang buong kasuotang pandigma ng Diyos upang kayo'y makatagal laban sa mga pakana ng diyablo.
Sa bahay naman ay muling tinanong siya ng mga alagad tungkol sa bagay na ito.
Ang babae na iyong nakita ay ang dakilang lunsod na naghahari sa mga hari sa lupa.”
Kanyang sinabi, “Ako ang Diyos, ang Diyos ng iyong ama; huwag kang matakot na pumunta sa Ehipto sapagkat doo'y gagawin kitang isang dakilang bansa.
‘Pagkatapos ng mga bagay na ito, ako'y babalik, at muli kong itatayo ang tolda ni David na bumagsak; muli kong itatatag ang guho nito, at ito'y aking itatayo:
Napuno sila ng lahat ng uri ng kasamaan, kalikuan, kasakiman, kahalayan; at punô ng inggit, pagpaslang, pag-aaway, pandaraya, katusuhan, mahihilig sa tsismis,
Gagawa ka ng dalawang haligi para sa mga sulok ng tabernakulo sa likod,
Nagsalita si Moises sa mga pinuno ng mga lipi ng mga anak ni Israel, na sinasabi, “Ito ang ipinag-uutos ng Panginoon .
o ang kanyang amain o ang anak ng kanyang amain ay makakatubos sa kanya; o sinumang malapit na kamag-anak sa kanyang sambahayan ay makakatubos sa kanya. Kung magkaroon siyang kakayahan ay matutubos niya ang kanyang sarili.
At sinabi niya sa babae, “Pinatatawad na ang iyong mga kasalanan.”
Yamang kami ay mayroong gayong pag-asa, kami ay kumikilos na may malaking katapangan,
Ang lahat na mga bagay tungkol sa akin ay ipababatid sa inyo ni Tiquico, na minamahal na kapatid at tapat na ministro, at kapwa alipin sa Panginoon.
Kinagabihan, kanyang kinuha si Lea na kanyang anak at dinala kay Jacob na sumiping naman sa kanya.
“Gagawa ka ng isang pinggan na lantay na ginto, at doo'y iuukit mo na ayon sa ukit ng isang pantatak, ‘Banal sa Panginoon .’
Bumaba ang Panginoon upang tingnan ang lunsod at ang tore na itinayo ng mga anak ng mga tao.
Si Pilato'y muling nagsalita sa kanila sa kagustuhang palayain si Jesus.
Nang marahang humihip ang hanging habagat, na inakala nilang maisasagawa nila ang kanilang layunin; kaya itinaas nila ang angkla at namaybay sa baybayin ng Creta.
Sapagkat sinabi ng Diyos, ‘Igalang mo ang iyong ama at ang iyong ina;’ at ‘Ang magsalita ng masama sa ama o sa ina, ay dapat mamatay.’
at tinipon niya ang lahat ng pagkain sa loob ng pitong taon na may kasaganaan sa lupain ng Ehipto, at inimbak ang pagkain sa mga bayan. Ang pagkain sa mga bukid na nasa palibot ng bawat bayan ay inimbak sa bawat bayan.
Bawat gumagalaw na nabubuhay ay magiging pagkain ninyo; at kung paanong ibinigay ko sa inyo ang mga luntiang halaman, ibinibigay ko sa inyo ang lahat ng mga bagay.
Para sa kalayaan ay pinalaya tayo ni Cristo; kaya't magpakatatag kayo at huwag pasakop na muli sa pamatok ng pagkaalipin.
Sinabi ni Jacob, “Ipagbili mo muna sa akin ngayon ang iyong pagkapanganay.”
Kaya't tumakbo siya at pumunta kay Simon Pedro at sa alagad na minamahal ni Jesus, at sa kanila'y sinabi, “Kinuha nila sa libingan ang Panginoon, at hindi namin alam kung saan nila siya inilagay.”
Sa unang buwan ng ikalawang taon, ng unang araw ng buwan, ang tabernakulo ay itinayo.
Kaya't kailangan na ang mga sinipi mula sa mga bagay sa kalangitan ay linisin ng mga ito, ngunit ang mga bagay sa sangkalangitan ay sa pamamagitan ng higit na mabubuting handog kaysa mga ito.
Kaya't maging maingat kayo baka ang liwanag na nasa iyo ay kadiliman.
maging ito ay paayon o pahalang; o ng lino o ng balahibo ng tupa, maging sa balat o sa alinmang yari sa balat,
ngunit ang ikapitong araw ay Sabbath sa Panginoon mong Diyos. Sa araw na ito ay huwag kang gagawa ng anumang gawain, ikaw o ang iyong anak na lalaki, ang iyong anak na babae, ang iyong aliping lalaki, ang iyong aliping babae, ang iyong mga baka, ang dayuhang nasa loob ng iyong mga pintuan;
Kaya't siya'y minatyagan nila at nagsugo ng mga espiya na nagkunwaring matatapat, upang siya'y hulihin sa kanyang salita, para siya'y maibigay sa mga pinuno at awtoridad ng gobernador.
Ang mga anak ni Israel ay pumasok sa gitna ng dagat sa ibabaw ng tuyong lupa, ang tubig ay naging isang pader sa kanila, sa kanilang gawing kanan at sa kanilang kaliwa.
At nagsalita ang Panginoon kay Moises sa mga kapatagan ng Moab sa tabi ng Jordan sa Jerico, na sinasabi,
Ipinamahala ng bantay sa bilangguan sa pangangalaga ni Jose ang lahat na mga bilanggo na nasa bilangguan; at anumang ginagawa nila roon ay siya ang gumagawa.
Kaya't ang sampung kapatid ni Jose ay bumaba upang bumili ng trigo sa Ehipto.
Katotohanang sinasabi ko sa inyo, sinumang hindi tumatanggap sa kaharian ng Diyos na gaya ng isang maliit na bata ay hindi makakapasok doon.”
Ngunit sinasabi ko sa inyo na dumating na si Elias, at siya'y hindi nila kinilala kundi ginawa nila sa kanya ang anumang kanilang naibigan. Gayundin naman ang Anak ng Tao ay malapit nang magdusa sa kanila.”
Sinabi niya sa kanila, “Bakit kayo natatakot, O kayong maliliit ang pananampalataya?” Kaya't bumangon siya at sinaway ang mga hangin at ang dagat, at nagkaroon ng lubos na kapayapaan.
At ito ay kanyang pagpuputul-putulin, kasama ang ulo at ang kanyang taba, at iaayos ng pari sa ibabaw ng kahoy na nasa apoy sa ibabaw ng dambana;
At anumang bagay na inyong hingin sa panalangin na may pananampalataya ay inyong tatanggapin.”
kundi magsusuot ng sandalyas at hindi magsusuot ng dalawang tunika.
Lahat ng ginto na ginamit sa buong gawain sa santuwaryo, samakatuwid ay ang gintong handog, ay dalawampu't siyam na talento, at pitong daan at tatlumpung siklo, ayon sa siklo ng santuwaryo.
“Ilapit mo sa iyo si Aaron na iyong kapatid at ang kanyang mga anak na kasama niya, mula sa mga anak ni Israel, upang makapaglingkod sa akin bilang mga pari—si Aaron at ang mga anak ni Aaron na sina Nadab, Abihu, Eleazar at Itamar.
At ilalagay mo sa pektoral ng kahatulan ang Urim at ang Tumim; at ang mga iyon ay ilalagay sa tapat ng puso ni Aaron, kapag siya'y pumapasok sa harapan ng Panginoon , at dadalhing palagi ni Aaron sa harapan ng Panginoon ang kahatulan ng mga anak ni Israel sa kanyang puso.
Sapagkat sinumang tumutupad ng buong kautusan, subalit lumalabag sa isa, ay nagkakasala sa lahat.
Sinabi sa kanya ni Pilato, “Ano ang katotohanan?” At nang masabi niya ito ay lumabas siyang muli sa mga Judio at sa kanila'y sinabi, “Wala akong makitang anumang kasalanan sa kanya.
Sapagkat nang ako'y dumating mula sa Padan, si Raquel ay namatay sa lupain ng Canaan sa daan, nang malapit nang makarating sa Efrata; at inilibing ko siya roon sa daan ng Efrata” (na siya ring Bethlehem).
At ibinuka ng lupa ang kanyang bibig at nilamon sila, at ang kanilang mga sambahayan, at ang lahat ng lalaki na kabilang kay Kora, at lahat ng kanilang ari-arian.
Kinuha ni Jose ang bangkay at binalot niya iyon ng isang malinis na telang lino,
Sabihin ninyo sa akin, kayong nagnanais mapasailalim ng kautusan, hindi ba ninyo naririnig ang kautusan?
Sino ang dumadaig sa sanlibutan, kundi ang sumasampalatayang si Jesus ang Anak ng Diyos?
tulad ng mga batong buháy, hayaan ninyong kayo ay maitayo bilang espirituwal na bahay tungo sa banal na pagkapari, upang mag-alay ng mga espirituwal na handog na kasiya-siya sa Diyos sa pamamagitan ni Jesu-Cristo.
Gayunma'y ang mga ito rin na mahilig managinip ay dinudumihan ang laman, at hinahamak ang mga may kapangyarihan at nilalait ang mga maluwalhating mga anghel.
Ang lahat na naging araw ni Set ay siyamnaraan at labindalawang taon at siya'y namatay.
Ang ilaw ay lumiliwanag sa kadiliman; at ito'y hindi nagapi ng kadiliman.
Pagkatapos, ang Panginoon ay nagsalita kay Moises,
Dumating ang araw ng Tinapay na Walang Pampaalsa, na noon ay kailangang ihandog ang kordero ng Paskuwa.
upang kayo'y igalang ng mga nasa labas, at huwag maging palaasa sa sinuman.
Ngayo'y sinumpa ka mula sa lupa. Ibinuka ng lupa ang bibig nito upang tanggapin ang dugo ng iyong kapatid mula sa iyong kamay.
na itinayo sa saligang inilagay ng mga apostol at ng mga propeta, na si Cristo Jesus ang batong panulok.
na mayroon akong malaking kalungkutan at walang tigil na kirot sa aking puso.
Ngunit kinuha kayo ng Panginoon , at hinango kayo sa hurnong bakal, mula sa Ehipto, upang maging isang bayan na kanyang pag-aari, isang pamana, gaya sa araw na ito.
“‘Ngunit kapag kayo'y nagkamali at hindi ninyo tinupad ang lahat ng utos na ito, na sinabi ng Panginoon kay Moises,
Ngunit taglay namin ang kayamanang ito sa mga sisidlang-lupa, upang ipakita na ang nag-uumapaw na kapangyarihan ay mula sa Diyos, at hindi mula sa amin.
Hindi pa ba ninyo nauunawaan o natatandaan ang limang tinapay para sa limang libo at kung ilang kaing ang inyong natipon?
At sinabi niya sa akin, “Huwag mong tatakan ang mga salita ng propesiya ng aklat na ito, sapagkat malapit na ang panahon.
At may isang tinig na nagmula sa langit, “Ikaw ang minamahal kong Anak, sa iyo ako lubos na nalulugod.”
Ang mga ito ay iwawagayway ng pari bilang handog na iwinagayway sa harapan ng Panginoon ; ito'y banal sa pari, pati ang dibdib na iwinagayway at ang hitang inialay; at pagkatapos nito, ang Nazirita ay maaari nang uminom ng alak.
Nagsugo siya ng isa pang alipin, subalit ito'y kanilang binugbog din at hiniya, at pinaalis na walang dala.
Kanilang malalaman na ako ang Panginoon nilang Diyos na naglabas sa kanila sa lupain ng Ehipto, upang ako'y manirahang kasama nila. Ako ang Panginoon nilang Diyos.
Pagkatapos, ang malinis na tao ay kukuha ng isopo at itutubog sa tubig at iwiwisik sa tolda, sa lahat ng kasangkapan, sa mga taong naroon, sa humawak ng buto o ng bangkay ng patay, o ng libingan.
na sinasabi, “Bakit pumunta ka sa mga taong hindi tuli at kumain kang kasalo nila?”
Ang mga punong pari at ang mga Fariseo ay nag-utos na sinumang nakakaalam ng kinaroroonan ni Jesus ay dapat ipagbigay-alam sa kanila upang siya'y kanilang madakip.
“Ang kanilang bibig ay punô ng panunumpa at kapaitan.”
Nagtipun-tipon sa palibot niya ang napakaraming tao, kaya't sumakay siya sa isang bangka at umupo roon samantalang ang lahat ng tao ay nakatayo sa baybayin.
Subalit nakikita ko ang kakaibang kautusan sa aking mga bahagi na nakikipagbaka laban sa kautusan ng aking pag-iisip, at ako'y binibihag sa ilalim ng kautusan ng kasalanan na nasa bahagi ng aking katawan.
Sapagkat ang sinumang nagnanais na iligtas ang kanyang buhay ay mawawalan nito, subalit sinumang mawalan ng kanyang buhay dahil sa akin ay maililigtas niya ito.
Hindi niya babaliin ang tambong nasugatan, o papatayin ang nagbabagang mitsa, hanggang ang katarungan ay dalhin niya sa tagumpay;
Samakatuwid, ang lahat ng salinlahi mula kay Abraham hanggang kay David ay labing-apat. Mula kay David hanggang sa pagkadalang-bihag sa Babilonia ay labing-apat na salinlahi; at mula sa pagkadalang-bihag sa Babilonia hanggang kay Cristo ay labing-apat din na salinlahi.
iniutos ng Panginoon na ibibigay sa kanila sa araw na kanyang buhusan sila ng langis mula sa mga anak ni Israel. Ito ay isang walang hanggang tuntunin sa buong panahon ng kanilang salinlahi.”
Kinaumagahan, si Abraham ay maagang nagtungo sa dakong kinatayuan niya sa harap ng Panginoon .
Ang mga tao sa Ninive ay babangon sa paghuhukom kasama ng lahing ito at ito'y kanilang hahatulan, sapagkat sila'y nagsisi sa pangangaral ni Jonas, at narito, ang isang higit pang dakila kaysa kay Jonas.
At doon ay may isang taong tuyo ang isang kamay. Siya ay tinanong nila, “Matuwid bang magpagaling sa araw ng Sabbath?” upang siya'y maparatangan nila.
Ngunit kung nais kong magmalaki ay hindi ako magiging hangal, sapagkat ako'y magsasabi ng katotohanan. Ngunit nagpipigil ako upang walang sinumang mag-isip ng higit tungkol sa akin kaysa kanyang nakita o narinig sa akin,
Pagkatapos, ilan sa mga eskriba at mga Fariseo ang nagwika sa kanya, “Guro, ibig naming makakita ng isang tanda mula sa iyo.”
Sapagkat si Cristo ay hindi pumasok sa santuwaryo na ginawa ng mga kamay ng tao na mga kahalintulad lamang ng mga tunay na bagay, kundi sa mismong langit, upang dumulog ngayon sa harapan ng Diyos para sa atin.
At siya naman ay lumampas sa unahan nila, at pitong ulit na yumuko sa lupa hanggang sa siya ay mapalapit sa kanyang kapatid.
Pitong araw na iyong gagawan ng katubusan ang dambana, at iyong pakakabanalin ito, at ang dambana ay magiging kabanal-banalan; anumang humipo sa dambana ay magiging banal.
Samantalang nagsasalita pa si Jesus sa maraming tao, ang kanyang ina at mga kapatid na lalaki ay nakatayo sa labas at ibig nilang makausap siya.
Igagawa mo ito ng dalawang argolyang ginto sa ilalim ng molde, sa dakong itaas ng dalawang tagiliran mo iyon gagawin; iyon ay magiging suotan ng mga pasanan upang mabuhat ito.
Sumagot sila, “Si Jesus na taga-Nazaret.” Sinabi sa kanila ni Jesus, “Ako nga iyon.” Si Judas na nagkanulo sa kanya ay nakatayong kasama nila.
Nang mabalitaan ng Cananeo, na hari ng Arad, na naninirahan sa Negeb, na ang Israel ay daraan sa Atarim, nilabanan niya ang Israel at binihag ang iba sa kanila.
“At kayo ay sumagot at sinabi sa akin, ‘Kami ay nagkasala laban sa Panginoon , kami ay aahon at lalaban, ayon sa iniutos sa amin ng Panginoon naming Diyos.’ At bawat isa sa inyo ay nagsakbat ng kanya-kanyang sandatang pandigma, at inyong inakalang madaling akyatin ang lupaing maburol.
Hanggang ngayo'y wala pa kayong hinihinging anuman sa pangalan ko. Kayo'y humingi at kayo'y tatanggap, upang malubos ang inyong kagalakan.
Iyong igagawa sila ng mga salawal na lino, upang takpan ang kanilang hubad na katawan; mula sa mga balakang hanggang sa mga hita aabot ang mga ito.
At sinabi sa kanila ni Jesus, “Sumunod kayo sa akin at gagawin ko kayong mga mamamalakaya ng mga tao.”
Kaya't sinabi niya sa kanyang mga alagad, “Tunay na napakarami ng aanihin, ngunit kakaunti ang manggagawa;
sa kanila ay hindi kami sumuko upang magpasakop, kahit isang saglit, upang ang katotohanan ng ebanghelyo ay manatili sa inyo.
Humatol sila sa bayan sa lahat ng panahon; ang mabibigat na usapin ay kanilang dinadala kay Moises, subalit bawat munting usapin ay sila-sila ang nagpapasiya.
“Kung ang sinuman ay magkasala at sumuway sa Panginoon sa pamamagitan ng pandaraya sa kanyang kapwa tungkol sa isang habilin, o sa isang sangla, o sa pagnanakaw, o pangingikil sa kanyang kapwa,
Kung kami ay wala sa aming sarili, ito ay para sa Diyos; kung kami ay nasa matinong pag-iisip, ito ay para sa inyo.
Sumagot si Jesus, “Ang pangunahin ay, ‘Pakinggan mo Israel: Ang Panginoon nating Diyos, ang Panginoon ay iisa.
at kayong mga pinahihirapan ay bigyan ng kapahingahang kasama namin, sa pagkapahayag ng Panginoong Jesus mula sa langit na kasama ang kanyang mga makapangyarihang anghel,
Bagaman ako'y hindi bihasa sa pagsasalita, gayunma'y hindi sa kaalaman, kundi sa bawat paraan ay ginawa namin itong hayag sa inyo sa lahat ng mga bagay.
Sapagkat ang kasalanan, pagkakita ng pagkakataon sa pamamagitan ng utos, ay dinaya ako, at sa pamamagitan nito ay pinatay ako.
“Ang bawat humihiwalay sa kanyang asawang babae at nag-asawa ng iba ay nagkakasala ng pangangalunya, at ang nag-aasawa sa babaing hiniwalayan ng kanyang asawa ay nagkakasala ng pangangalunya.
Nangunguna sa hukbo ng lipi ng mga anak ni Isacar si Natanael na anak ni Suar.
Ang lahat ng mga ito ay namatay sa pananampalataya na hindi tinanggap ang mga pangako, ngunit mula sa malayo ang mga iyon ay kanilang natanaw at binati. Kanilang ipinahayag na sila'y pawang mga dayuhan at manlalakbay sa ibabaw ng lupa,
At natisod sila sa kanya. Ngunit sinabi sa kanila ni Jesus, “Ang isang propeta ay di nawawalan ng karangalan, maliban sa kanyang sariling bayan at sambahayan.”
Sapagkat nalalaman ninyo ang biyaya ng ating Panginoong Jesu-Cristo, na bagaman siya'y mayaman, subalit alang-alang sa inyo ay naging dukha, upang sa pamamagitan ng kanyang kadukhaan ay maging mayaman kayo.
Gayundin, iniutos niya sa ikalawa, sa ikatlo, at sa lahat ng sumusunod sa mga kawan, na sinasabi, “Sasabihin ninyo ang gayunding bagay kay Esau, kapag nakasalubong ninyo siya,
Huwag mong ipanumpa maging ang iyong ulo, sapagkat hindi mo magagawang puti o itim ang isang buhok.
Ngayon kung ang pagkahulog nila ay siyang kayamanan ng sanlibutan, at ang pagkalugi nila ay siyang kayamanan ng mga Hentil, gaano pa kaya ang lubos na panunumbalik nila?
Ang mga anak ni Benjamin ayon sa kanilang mga angkan: kay Bela, ang angkan ng mga Belaita; kay Asbel, ang angkan ng mga Asbelita; kay Ahiram, ang angkan ng mga Ahiramita;
(At ang mga anak ni Israel ay naglakbay mula sa Beerot Benyaakan hanggang sa Mosera. Doon namatay si Aaron, at doon siya inilibing. Si Eleazar na kanyang anak ay nangasiwa sa katungkulang pari na kapalit niya.
Kaya't huwag ninyong itakuwil ang inyong pagtitiwala na may dakilang gantimpala.
ngunit naglakbay kami mula sa Filipos pagkaraan ng mga araw ng Tinapay na Walang Pampaalsa, at sa loob ng limang araw ay dumating kami sa kanila sa Troas, kung saan kami tumigil ng pitong araw.
Subalit ang lalaking malinis at wala sa paglalakbay na hindi mangingilin ng paskuwa ay ititiwalag sa kanyang bayan sapagkat siya'y hindi nag-alay ng handog sa Panginoon sa takdang panahon, ang taong iyon ay mananagot sa kanyang kasalanan.
Ito ang siyang naparito sa pamamagitan ng tubig at ng dugo, si Jesu-Cristo; hindi sa tubig lamang, kundi sa tubig at sa dugo. At ang Espiritu ang nagpapatotoo, sapagkat ang Espiritu ay katotohanan.
At sa bagay na ito ay nagbibigay ako ng payo: pinakamabuti para sa inyo ngayon na tapusin ang sinimulan ninyo nang nakaraang taon, hindi lamang upang gumawa kundi magkaroon ng pagnanais na gumawa.
Pagkatapos ng mga ito ay nagpakita siya sa ibang anyo sa dalawa sa kanila noong sila'y naglalakad patungo sa bukid.
At ang mga ito'y mapupunta sa walang hanggang kaparusahan, ngunit ang mga matuwid ay sa buhay na walang hanggan.”
Kanyang papatayin ang korderong lalaki sa lugar na pinagpapatayan nila ng handog pangkasalanan at ng handog na sinusunog, sa banal na dako; sapagkat gaya ng handog pangkasalanan, ang handog para sa budhing maysala ay para sa pari; ito ay kabanal-banalan.
at isang kambing na lalaki na handog pangkasalanan upang ipantubos sa inyo.
Sinabi sa kanya ni Jesus, “Humayo ka na, ang anak mo ay mabubuhay.” Pinaniwalaan ng lalaki ang salitang sinabi sa kanya ni Jesus, at siya'y humayo sa kanyang lakad.
Ang mga namatay sa salot ay dalawampu't apat na libo.
At sinabi ng Panginoon sa akin, ‘Tumindig ka, at pangunahan mo ang taong-bayan; sila'y papasok at kanilang aangkinin ang lupain na aking ipinangako sa kanilang mga ninuno upang ibigay sa kanila.’
“Sabihin mo sa mga anak ni Israel na sila'y bumalik at humimpil sa tapat ng Pihahirot, sa pagitan ng Migdol at ng dagat, sa tapat ng Baal-zefon; sa tapat niyon kayo hihimpil, sa tabi ng dagat.
hindi mahilig sa alak, hindi mapusok kundi mahinahon, hindi palaaway, at hindi maibigin sa salapi.
at ang dalawa ay magiging isang laman!’ Kaya't hindi na sila dalawa, kundi isang laman.
Ako'y may pag-asa sa Diyos, na siya rin namang inaasahan nila, na magkakaroon ng muling pagkabuhay ng mga matuwid at ng mga hindi matuwid.
Subalit ano ang pinuntahan ninyo upang makita? Isa bang taong nakasuot ng mga damit na malambot? Masdan ninyo, ang nagdadamit ng magagara at namumuhay ng marangya ay nasa mga palasyo ng mga hari.
Nang sila'y nagkakatipon, siya'y kanilang tinanong, “Panginoon, ito ba ang panahon na panunumbalikin mo ang kaharian sa Israel?”
Ngunit hindi nila naunawaan ang kanyang sinabi at natakot silang magtanong sa kanya.
Gayunma'y hindi na naalala si Jose ng puno ng mga katiwala ng kopa, kundi nakalimutan siya.
Tingnan ninyo, ang sahod ng mga manggagawa na gumapas sa inyong mga bukid na inyong ipinagkakait ay umiiyak; at ang pag-iyak ng mga umani ay nakarating sa pandinig ng Panginoon ng mga hukbo.
At maririnig ng buong bayan at matatakot, at di na gagawa pa nang may kapangahasan.
upang ipahayag ang taon ng biyaya mula sa Panginoon.”
Huwag hamakin ng kumakain ang hindi kumakain; at ang hindi kumakain ay huwag humatol sa kumakain; sapagkat sila'y tinanggap ng Diyos.
Ang mga tapyas ay gawa ng Diyos, at ang sulat ay sulat ng Diyos, na nakaukit sa mga tapyas.
Sa taon ng pagdiriwang, ibabalik ang bukid sa kanyang binilhan, sa kanya na nagmamay-ari ng lupa.
na nagsasabi, “Ang iyong nakikita ay isulat mo sa isang aklat at iyong ipadala sa pitong iglesya, sa Efeso, sa Smirna, sa Pergamo, sa Tiatira, sa Sardis, sa Filadelfia, at sa Laodicea.”
At sinabi niya sa kanila, “Pumunta kayo ng bukod sa isang dakong ilang at magpahinga kayo nang sandali.” Sapagkat marami ang nagpaparoo't parito at sila'y hindi man lamang nagkaroon ng panahong kumain.
Sa malinis ang lahat ng mga bagay ay malinis; ngunit sa marurumi at hindi nananampalataya ay walang anumang malinis; kundi ang kanilang pag-iisip at budhi ay pawang pinarumi.
Nagalit ang Faraon laban sa kanyang dalawang tagapamahala, sa puno ng mga katiwala ng kopa at sa puno ng mga panadero.
O kung ang sinuman ay nakahipo ng alinmang bagay na marumi, o maging ito ay bangkay ng mabangis na hayop na marumi, o bangkay ng umuusad na marumi, at di niya iyon nalaman, siya'y magiging marumi at nagkakasala.
Ang mga ito ang mga salinlahi ng mga anak ni Noe: sina Sem, Ham, at Jafet: at sila'y nagkaanak pagkaraan ng baha.
Kahabag-habag na tao ako! Sino ang magliligtas sa akin mula sa katawang ito ng kamatayan?
Bawat butil na handog na niluto sa hurno, at lahat na inihanda sa kawali ay mapupunta sa pari na naghahandog niyon.
Ngunit ang nag-aalinlangan ay hinahatulan kung kumakain, sapagkat hindi batay sa pananampalataya; at ang anumang hindi batay sa pananampalataya ay kasalanan.
Nang lumingon si Jesus at nakita siya ay sinabi niya, “Anak, lakasan mo ang iyong loob; pinagaling ka ng iyong pananampalataya.” Gumaling nga ang babae sa oras ding iyon.
Aking binabalaan ang bawat taong nakikinig sa mga salita ng propesiya ng aklat na ito: Kung ang sinuman ay magdagdag sa mga ito, idaragdag sa kanya ng Diyos ang mga salot na nakasulat sa aklat na ito,
At sinabi ni Lamec sa kanyang mga asawa, “Ada at Zilla, pakinggan ninyo ang aking tinig. Kayong mga asawa ni Lamec ay makinig sa aking mga salita. Pumatay ako ng isang tao, dahil sa pagsugat sa akin, at ng isang binata, dahil sa ako'y sinaktan.
Kung gayon, hindi ikaw ang Ehipcio, na nag-udyok ng paghihimagsik nang mga nakaraang araw at nagdala sa apat na libong mamamatay-tao sa ilang?”
Kayo, kayo'y nagnasa ng masama laban sa akin, ngunit inilagay ng Diyos para sa kabutihan, upang mangyari ang gaya sa araw na ito, upang mapanatiling buháy ang napakaraming tao.
Ang Panginoon ay nangunguna sa kanila sa araw, sa isang haliging ulap upang patnubayan sila sa daan; at sa gabi ay sa isang haliging apoy upang tanglawan sila; upang sila'y makapaglakad sa araw at sa gabi.
Kapag tiningnan ng pari ang makating karamdaman, at tila hindi mas malalim kaysa balat, at wala iyong buhok na maitim, ibubukod ng pari sa loob ng pitong araw ang may makating karamdaman.
Nagkaroon ng takot ang lahat ng nakatira sa palibot nila, at ang lahat ng mga bagay na ito ay pinag-usapan sa buong lupaing maburol ng Judea.
Maging marangal ang inyong pag-uugali sa gitna ng mga Hentil upang kung magsalita sila laban sa inyo na parang kayo'y gumagawa ng kasamaan, ay makita nila ang inyong mabubuting gawa at luwalhatiin nila ang Diyos sa araw ng pagdalaw.
Habang patungo sa Jerusalem, si Jesus ay dumaan sa pagitan ng Samaria at Galilea.
“At ngayon, mga kapatid, nalalaman kong ginawa ninyo iyon sa inyong kamangmangan tulad ng inyong mga pinuno.
Malapit na noon ang Paskuwa ng mga Judio, at umahon si Jesus patungo sa Jerusalem.
Pangangalatin kayo ng Panginoon sa lahat ng mga bayan, mula sa isang dulo ng lupa hanggang sa kabilang dulo ng lupa; at doo'y maglilingkod kayo sa ibang mga diyos na yari sa kahoy at bato na hindi ninyo kilala, ni ng inyong mga ninuno.
At sinabi ni Maria, “Narito ako na alipin ng Panginoon; mangyari sa akin ang ayon sa iyong salita.” Pagkatapos, iniwan siya ng anghel.
Lahat ng haligi sa palibot ng bulwagan ay pagkakabitin ng mga baras na pilak; ang mga kawit ng mga iyon ay pilak, at ang mga patungan ay tanso.
Nang makarating kami sa Roma, si Pablo ay pinahintulutang manirahang mag-isa kasama ang kawal na sa kanya'y nagbabantay.
Sila'y dumating kina Moises at Aaron at sa buong sambayanan ng mga anak ni Israel, sa ilang ng Paran, sa Kadesh; at kanilang dinalhan sila ng balita at ang buong sambayanan, at kanilang ipinakita sa kanila ang bunga ng lupain.
At maliwanag na sinabi niya ang salitang ito. Inilayo siya ni Pedro at pinasimulang siya'y sawayin.
At sinabi niya sa kanyang mga alagad na ihanda para sa kanya ang isang bangka dahil sa napakaraming tao, baka siya'y kanilang siksikin.
Sa ganitong paraan ninyo kakainin ito: may bigkis ang inyong baywang, ang mga sandalyas ay nakasuot sa inyong mga paa, at ang inyong tungkod ay nasa inyong kamay; at dali-dali ninyong kakainin ito. Ito ang paskuwa ng Panginoon .
Ang bawat isa ay magbigay ayon sa ipinasiya ng kanyang puso, hindi mabigat sa kalooban, o dala ng pangangailangan, sapagkat iniibig ng Diyos ang nagbibigay na masaya.
At isusulat mo ang mga iyon sa mga hamba ng pinto ng iyong bahay, at sa iyong mga pintuang-daan:
Sinabi ng Faraon sa kanyang mga kapatid, “Ano ang inyong hanapbuhay?” At kanilang sinabi sa Faraon, “Ang iyong mga lingkod ay mga pastol, gaya ng aming mga ninuno.”
Ihahandog ni Aaron ang mga Levita sa harap ng Panginoon bilang handog na iwinagayway sa mga anak ni Israel upang kanilang gawin ang paglilingkod sa Panginoon .
“Mapapalad ang mga mapagpayapa, sapagkat sila ay tatawaging mga anak ng Diyos.
at iyong gugulin ang salapi sa anumang nais mo: baka, tupa, alak, matapang na inumin, o sa anumang iyong nasain. Ikaw ay kakain doon sa harapan ng Panginoon mong Diyos, at ikaw at ang iyong sambahayan ay magalak.
Hindi ba't kasama natin ang lahat ng kanyang mga kapatid na babae? Saan kinuha ng taong ito ang lahat ng mga bagay na ito?”
Sinabi sa kanila ni Jesus, “Halikayo at mag-almusal.” Sinuman sa mga alagad ay hindi nangahas na siya'y tanungin, “Sino ka?” yamang alam nila na iyon ay ang Panginoon.
Sila'y lumapit at ginising siya na nagsasabi, “Guro, Guro, tayo'y napapahamak!” Siya'y gumising at sinaway ang hangin at ang pagngangalit ng tubig. Ang mga ito'y huminto at nagkaroon ng kapayapaan.
“Sandali na lamang, at ako'y hindi na ninyo makikita, at muling sandali pa, at ako'y inyong makikita.”
o nagtungo man ako sa Jerusalem sa mga apostol na una sa akin, kundi nagtungo ako sa Arabia at muli akong nagbalik sa Damasco.
Sa isang takdang araw ay isinuot ni Herodes ang damit-hari at naupo sa trono, at sa kanila'y nagtalumpati.
“Ang inyong magiging hangganan sa kanluran ay ang Malaking Dagat at ang baybayin niyon; ito ang magiging hangganan ninyo sa kanluran.
Sinagot sila ni Jesus, “Sinabi ko na sa inyo, at hindi kayo naniwala. Ang mga gawang ginagawa ko sa pangalan ng aking Ama ay siyang nagpapatotoo sa akin.
Gayunma'y ang nasa inyo'y panghawakan ninyong matibay hanggang sa ako'y dumating.
Iniutos niya sa katiwala ng kanyang bahay, “Punuin mo ng mga pagkain ang mga sako ng mga lalaking ito, hangga't madadala nila, at ilagay ang salapi ng bawat isa sa ibabaw ng kanyang sako.
Kung ang isang tao ay tutubos ng alinman sa kanyang ikasampung bahagi, idagdag niya roon ang ikalimang bahagi niyon.
Hindi ko kayang dalhing mag-isa ang buong bayang ito, sapagkat ang pasanin ay napakabigat para sa akin.
“Kapag ang lahat ng mga bagay na ito ay dumating sa iyo, ang pagpapala at ang sumpa na inilagay ko sa harapan mo, at iyong bulay-bulayin ang mga iyon sa gitna ng lahat ng mga bansa na pinagtabuyan sa iyo ng Panginoon mong Diyos
Ngunit kayo, mga kapatid, ay wala sa kadiliman, upang sa araw na iyon ay mabigla kayong gaya sa magnanakaw.
Nang marinig nila ito ay napuno sila ng galit at nagsigawan, “Dakila si Artemis ng mga taga-Efeso!”
Nagpapasalamat ako sa Diyos, na aking pinaglilingkuran na may malinis na budhi gaya ng aking mga ninuno, kapag lagi kitang naaalala sa aking mga panalangin gabi't araw.
at ang bigkis na yari sa hinabing pinong lino, telang asul at kulay-ube, at pula na gawa ng mambuburda; gaya ng iniutos ng Panginoon kay Moises.
Kaya't iniunat ni Moises ang kanyang tungkod sa lupain ng Ehipto, at ang Panginoon ay nagpahihip ng hanging amihan sa lupain ng buong araw na iyon at ng buong gabi; at nang mag-umaga ay dinala ng hanging amihan ang mga balang.
Ang bawat mahulog sa ibabaw ng batong ito ay magkakadurug-durog, at dudurugin nito ang sinumang mabagsakan nito.”
Sapagkat kailangan ninyo ng pagtitiis, upang kapag inyong nagampanan ang kalooban ng Diyos ay tanggapin ninyo ang pangako.
Namatay si Debora na yaya ni Rebecca, at inilibing sa paanan ng Bethel, sa ilalim ng ensina, at ang pangalan nito ay tinawag niyang Allon-bacuth.
Kaya, mga ginoo, lakasan ninyo ang inyong loob, sapagkat ako'y sumasampalataya sa Diyos na mangyayari ito ayon sa sinabi sa akin.
Sapagkat sinasabi ng kasulatan, “Ang bawat sumasampalataya sa kanya ay hindi malalagay sa kahihiyan.”
“Sabihin mo kay Aaron: Sinuman sa iyong mga anak sa buong panahon ng kanilang salinlahi na may kapintasan ay hindi maaaring lumapit upang maghandog ng tinapay sa kanyang Diyos.
Ngunit sinabi niya, “Pumarito ang iyong kapatid sa pamamagitan ng pandaraya, at kinuha ang basbas sa iyo.”
Sa pananampalataya ay iniwan niya ang Ehipto, at hindi natakot sa poot ng hari, sapagkat siya ay matiyagang nagpatuloy na tulad sa nakakakita sa kanya na hindi nakikita.
Kaya't ang mga pinuno ng Edom ay nagimbal; sa matatapang sa Moab, ang panginginig sa kanila ay sumakmal, at naupos ang lahat ng taga-Canaan.
sapagkat walang propesiya na dumating kailanman sa pamamagitan ng kalooban ng tao kundi ang mga taong inudyukan ng Espiritu Santo ay nagsalita mula sa Diyos.
Ang pangalan ng asawa ni Amram ay Jokebed, na anak na babae ni Levi, na ipinanganak kay Levi sa Ehipto. Ipinanganak niya kay Amram sina Aaron at Moises, at si Miriam na kanilang kapatid na babae.
Ngayon sa gumagawa, ang kabayaran ay hindi itinuturing na biyaya, kundi siyang talagang nararapat.
Hindi sa kami ay may kakayahan mula sa aming sarili upang angkinin ang anuman na nagmula sa amin, kundi ang aming kakayahan ay mula sa Diyos;
Pagalingin ninyo ang mga maysakit, buhayin ninyo ang mga patay, linisin ninyo ang mga ketongin, palayasin ninyo ang mga demonyo. Tinanggap ninyong walang bayad, ibigay ninyong walang bayad.
Muling nagsalita sa kanila si Jesus, “Ako ang ilaw ng sanlibutan. Ang sumusunod sa akin ay hindi kailanman lalakad sa kadiliman, kundi magkakaroon ng ilaw ng buhay.”
Ang napopoot sa akin ay napopoot din sa aking Ama.
sapagkat lahat ng mga bansa ay uminom ng alak ng galit ng kanyang pakikiapid, at ang mga hari sa lupa ay nakiapid sa kanya, at ang mga mangangalakal sa lupa ay yumaman dahil sa kapangyarihan ng kanyang kalayawan.”
Kayo'y kapopootan ng lahat ng mga tao dahil sa aking pangalan.
Kanyang sinugo ang mga kabataang lalaki mula sa mga anak ni Israel, na nag-alay ng mga handog na sinusunog at nag-alay ng mga baka bilang handog pangkapayapaan sa Panginoon .
si Andres, si Felipe, si Bartolome, si Mateo, si Tomas, si Santiago na anak ni Alfeo, si Tadeo, si Simon na Cananeo;
Dahil dito, sa pagkakaroon namin ng ministeryong ito sa pamamagitan ng aming tinanggap na habag, kami ay hindi pinanghihinaan ng loob.
ay sinabi sa akin ng Panginoon ,
“At ako'y nagsalita sa inyo nang panahong iyon na sinasabi, ‘Hindi ko kayo kayang dalhing mag-isa.
sapagkat ang galit ng tao ay hindi gumagawa ng katuwiran ng Diyos.
Pagkalipas ng tatlong araw, kanilang natagpuan siya sa templo na nakaupo sa gitna ng mga guro na nakikinig at nagtatanong sa kanila.
Subalit habang pinupulot ng mga punong pari ang mga piraso ng pilak, nagsabi sila, “Hindi matuwid na ilagay ang mga ito sa kabang-yaman, sapagkat dugo ang kapalit ng halagang ito.”
Ito ang paglilingkod ng mga angkan ng mga Gershonita, sa paglilingkod at sa pagdadala ng mga dala-dalahan.
Kaagad siyang lumapit kay Jesus, at sinabi, “Magandang gabi, Rabi!” at kanyang hinagkan siya.
At bumagsak sa mga tao ang ulan ng malalaking yelo na ang bigat ay halos isandaang libra buhat sa langit, at nilait ng mga tao ang Diyos dahil sa salot na ulan ng yelo, sapagkat ang salot na ito ay lubhang nakakatakot.
at ang sinumang kumain nito ay magpapasan ng kanyang kasamaan, sapagkat nilapastangan niya ang isang banal na bagay ng Panginoon ; at ititiwalag ang gayong tao sa kanyang bayan.
Ganyan ang ginawa ng inyong mga ninuno nang sila'y aking suguin, mula sa Kadesh-barnea upang lihim na siyasatin ang lupain.
Ngunit kapag ikaw ay mananalangin, pumasok ka sa iyong silid, at pagkasara mo ng iyong pinto ay manalangin ka sa iyong Ama na nasa lihim, at ang iyong Ama na nakakakita ng mga lihim ay gagantimpalaan ka.
sapagkat natatakot si Herodes kay Juan. Nalalaman niyang si Juan ay isang lalaking matuwid at banal at siya'y ipinagtanggol niya. Nang kanyang mapakinggan siya, labis siyang nabagabag gayunma'y masaya siyang nakinig sa kanya.
Magkakaroon ng labindalawang bato na may mga pangalan ayon sa mga pangalan ng anak ni Israel; magiging tulad ng mga pantatak, bawat isa'y may ukit na pangalan, na ukol sa labindalawang lipi.
Ang iba'y nahasik sa tinikan. Ang mga ito ang nakinig ng salita,
Subalit kung ikaw ay lumihis habang ikaw ay nasa ilalim ng kapamahalaan ng iyong asawa, at kung ikaw ay nadungisan at may ibang lalaking sumiping sa iyo, bukod sa iyong asawa,’
Si Jose noon ang tagapamahala sa lupain. Siya ang nagbibili ng trigo sa lahat ng mga tao sa lupain. At dumating ang mga kapatid ni Jose at sila'y yumuko sa kanya na ang kanilang mga mukha ay nakasubsob sa lupa.
ngunit ang ikapitong araw ay Sabbath sa Panginoon mong Diyos. Sa araw na iyan ay huwag kang gagawa ng anumang gawa, ikaw, ni ang iyong anak na lalaki o anak na babae, ni ang iyong aliping lalaki o aliping babae, ni ang iyong baka, ni ang iyong asno, ni anuman sa iyong hayop, ni ang mga dayuhang nasa loob ng iyong mga pintuan, upang ang iyong aliping lalaki at aliping babae ay makapagpahingang gaya mo.
At nagkaroon ng isang malakas na unos, sumalpok ang mga alon sa bangka, anupa't ang bangka ay halos napupuno na ng tubig.
Inyong ipapangilin ang pista ng Tinapay na Walang Pampaalsa, sapagkat sa araw na ito ay kinuha ko ang inyong mga hukbo mula sa lupain ng Ehipto. Inyong ipapangilin ang araw na ito sa buong panahon ng inyong mga salinlahi bilang isang tuntunin magpakailanman.
mga Creteo at mga Arabe, ay naririnig nating nagsasalita sa ating mga wika tungkol sa mga makapangyarihang gawa ng Diyos.”
At isa sa apat na nilalang na buháy ay nagbigay sa pitong anghel ng pitong mangkok na ginto na punô ng poot ng Diyos, na siyang nabubuhay magpakailanman.
sapagkat mahal niya ang ating bansa at nagtayo siya ng sinagoga para sa atin.”
At sa dakong ito ay muling sinabi, “Sila'y hindi papasok sa aking kapahingahan.”
Baka sa bigla niyang pagdating ay matagpuan niya kayong natutulog.
Sapagkat kung ang sinuman ay tagapakinig ng salita at hindi tagatupad, siya ay katulad ng isang tao na tinitingnan ang kanyang likas na mukha sa salamin;
Gagawa ka ng mga silo na kulay-asul sa gilid ng tabing sa hangganan sa unang pangkat; gayundin, gagawa ka ng mga silo sa gilid ng tabing sa hangganan sa ikalawang pangkat.
At sabihin ninyo sa may-ari ng bahay, ‘Sinasabi ng Guro sa iyo, “Saan ang silid para sa panauhin na doon ay aking kakainin ang Paskuwa na kasalo ng aking mga alagad?”’
Sapagkat kung paanong sa pagsuway ng isa ay naghari ang kamatayan sa pamamagitan ng isa; ang tumatanggap ng kasaganaan ng biyaya at kaloob ng pagiging matuwid ay lalo pang maghahari sa buhay sa pamamagitan ng isa, si Jesu-Cristo.
Nabuhay si Enoc ng animnapu't limang taon at naging anak niya si Matusalem.
Ibinuka ng Panginoon ang bibig ng asno at ito'y nagsabi kay Balaam, “Ano ang ginawa ko sa iyo upang ako'y paluin mo nang tatlong ulit?”
Si Jose ay nag-imbak ng napakaraming trigo na gaya ng buhangin sa dagat, hanggang sa huminto siya sa pagtatala nito, sapagkat hindi na ito mabilang.
Ang mga anak ni Kora: sina Asir, Elkana, at Abiasaf; ito ang mga angkan ng mga Korahita.
Sinabi rin niya sa kanya, “Sagana kami sa dayami at pagkain sa hayop, at mayroon ding lugar na matutuluyan.”
Kaya't si Abraham, nang makapaghintay na may pagtitiis, ay tumanggap ng pangako.
sapagkat ginulo nila kayo ng kanilang mga pandaraya sa inyo sa nangyari sa Peor, at sa pangyayari kay Cozbi, na anak na babae ng pinuno sa Midian, na kanilang kapatid na namatay nang araw ng salot dahil sa pangyayari sa Peor.
Pumunta nga ang mga alagad at ginawa ang ayon sa ipinag-utos ni Jesus sa kanila.
Sa aking unang pagsasanggalang ay walang sinumang kumampi sa akin, bagkus pinabayaan ako ng lahat. Huwag nawang singilin sa kanila ito.
At higit sa lahat ng mga bagay na ito ay magbihis kayo ng pag-ibig na siyang tali ng kasakdalan.
Subalit ngayo'y pinagsisikapan ninyo akong patayin, isang taong nagsasabi sa inyo ng katotohanan na aking narinig sa Diyos. Ito'y hindi ginawa ni Abraham.
Mapalad ang dumarating na kaharian ng ating amang si David! Hosana sa kataas-taasan!”
Si Jesus ay sumigaw at nagsabi, “Ang sumasampalataya sa akin ay hindi sa akin sumasampalataya, kundi doon sa nagsugo sa akin.
Kaya't maging ang unang tipan ay hindi pinagtibay ng walang dugo.
Ang mga ito ang naging anak ni Midian: Efa, Efer, Hanoc, Abida, at Eldaa. Lahat ng ito ay mga anak ni Ketura.
Pitong araw na kakain kayo ng tinapay na walang pampaalsa. Sa unang araw ay inyong aalisin sa inyong mga bahay ang pampaalsa, sapagkat sinumang kumain ng tinapay na may pampaalsa, mula sa unang araw hanggang sa ikapitong araw ay ititiwalag sa Israel.
Ang mga bagay na inyong natutunan, tinanggap, narinig at nakita sa akin, ang mga bagay na ito ang gawin ninyo; at ang Diyos ng kapayapaan ay sasainyo.
sapagkat ang mga iba'y bumaling at sumunod na kay Satanas.
Siya'y dapat manatili sa langit hanggang sa mga panahon ng pagpapanumbalik ng lahat ng mga bagay, na sinabi ng Diyos noong una sa pamamagitan ng bibig ng kanyang mga banal na propeta.
Sumagot si Isaac na kanyang ama, “Tingnan mo, papalayo sa taba ng lupa ang iyong tahanan, at papalayo sa hamog ng langit sa itaas;
Si Pablo na apostol—hindi mula sa mga tao, o sa pamamagitan man ng tao, kundi sa pamamagitan ni Jesu-Cristo, at ng Diyos Ama, na muling bumuhay sa kanya mula sa mga patay—
Nang ang buong lupain ng Ehipto ay nagutom, ang taong-bayan ay humingi ng pagkain sa Faraon. Kaya't sinabi ng Faraon sa lahat ng mga Ehipcio, “Pumunta kayo kay Jose; ang kanyang sabihin sa inyo ay inyong gawin.”
At ang magiging kaaway ng tao ay ang sarili niyang mga kasambahay.
Agad sumigaw ang ama ng bata na sinasabi, “Nananampalataya ako; tulungan mo ang kawalan ko ng pananampalataya!”
Ngunit siya'y sumagot at sinabi sa kanya, “Panginoon, kahit na ang mga aso sa ilalim ng hapag ay kumakain ng mga nalaglag na pagkain ng mga anak.”
Ilan sa mga pilosopong Epicureo at Estoico ay nakipagtalo rin sa kanya. At sinabi ng ilan, “Anong nais sabihin ng madaldal na ito?” Sinabi ng iba, “Parang siya'y isang tagapagbalita ng mga ibang diyos”—sapagkat ipinangangaral niya si Jesus at ang pagkabuhay.
Subalit ang taong nilisan ng mga demonyo ay nakiusap na siya'y makasama niya. Subalit siya'y pinaalis niya, na sinasabi,
Nang ang salot ay tumigil, si Aaron ay bumalik kay Moises sa pintuan ng toldang tipanan.
Sapagkat siya'y tumanggap sa Diyos Ama ng karangalan at kaluwalhatian, at dumating sa kanya ang isang tinig mula sa Marangal na Kaluwalhatian, na nagsasabi, “Ito ang minamahal kong Anak, na siya kong kinalulugdan.”
Kaya't sinasabi rin ng Karunungan ng Diyos, ‘Magsusugo ako sa kanila ng mga propeta at mga apostol, at ang ilan sa kanila ay kanilang papatayin at uusigin,’
Sa pamamagitan nito ay masusubok kayo: Kung paanong nabubuhay si Faraon, hindi kayo aalis dito malibang pumarito ang inyong kapatid na bunso.
at pagkatapos ay hindi na ninyo siya pinahihintulutang gumawa ng anuman para sa kanyang ama o ina,
Ipagbili ninyo ang inyong mga ari-arian at kayo'y magbigay ng limos. Gumawa kayo para sa inyong mga sarili ng mga supot na hindi naluluma, ng isang kayamanan sa langit na hindi nauubos, na doo'y hindi lumalapit ang magnanakaw, o naninira man ang bukbok.
At sinumang tao sa mga anak ni Israel, o sa mga taga-ibang bayan na naninirahang kasama ninyo na humuli ng hayop o ng ibon na makakain, ay ibubuhos niya ang dugo niyon at tatabunan ng lupa.
Nang siya'y hudyatan ng gobernador upang magsalita, si Pablo ay sumagot: “Yamang nalalaman ko na ikaw ay naging hukom sa loob ng maraming mga taon sa bansang ito, ay masigla kong gagawin ang aking pagtatanggol.
Ginawa ni Moises ang ayon sa iniutos ng Panginoon sa kanya at kanyang isinama si Josue. Kanyang iniharap siya sa paring si Eleazar at sa buong kapulungan.
Siya'y yumuko, siya'y lumugmok na parang leon, at parang isang babaing leon, sinong gigising sa kanya? Pagpalain nawa ang lahat na nagpapala sa iyo, at sumpain ang lahat na sumusumpa sa iyo.”
Pagkatapos ay lumapit kay Jesus ang ina ng mga anak ni Zebedeo, na kasama ang kanyang mga anak na lalaki. Siya'y lumuhod sa kanya at may hiniling na isang bagay sa kanya.
Kaya't sinabi ni Esau, “Pahintulutan mong iwan ko sa iyo ang ilan sa mga taong kasama ko.” Kanyang sinabi, “Bakit kailangan pa? Sapat na ang makakita ako ng biyaya sa paningin ng aking panginoon.”
Habang naglalakad sila sa daan ay may nagsabi sa kanya, “Ako'y susunod sa iyo saan ka man magpunta.”
Sinabi ng Panginoon kay Moises, “Pagkabalik mo sa Ehipto, iyong gawin sa harap ng Faraon ang lahat ng kababalaghan na aking ipinagkatiwala sa iyong kamay. Ngunit aking papatigasin ang kanyang puso at hindi niya papayagang umalis ang bayan.
Kanilang tatakpan ang ibabaw ng lupain, kaya't walang makakakita ng lupa. Kanilang kakainin ang naiwan sa inyo pagkaraan ng yelong ulan at kanilang kakainin ang bawat punungkahoy mo sa parang.
At siya'y nagtayo roon ng isang dambana at tinawag niya itong El-Elohe-Israel.
Sa Haring walang hanggan, walang kamatayan, di-nakikita, tanging Diyos, ang karangalan at kaluwalhatian magpakailanpaman. Amen.
Huwag lamang ninyong kakainin ang dugo; ibubuhos ninyo ito sa lupa na parang tubig.
Ngunit nang malugod ang Diyos na sa akin ay nagbukod, buhat pa sa sinapupunan ng aking ina, at sa akin ay tumawag sa pamamagitan ng kanyang biyaya,
At tinawag ni Moises si Josue at sinabi sa kanya sa paningin ng buong Israel, “Ikaw ay magpakalakas at magpakatapang; sapagkat ikaw ay maglalakbay na kasama ng bayang ito patungo sa lupaing ipinangakong ibibigay at ipapamana ng Panginoon sa kanilang mga ninuno.
Ipinatong ni Moises sa kanya ang pektoral, at inilagay ang Urim at ang Tumim sa pektoral.
Sinagot sila ni Jesus, “Dumating na ang oras upang ang Anak ng Tao ay luwalhatiin.
Ang lahat na naging araw ni Lamec ay pitong daan at pitumpu't pitong taon at namatay.
Mayroon doong isang sisidlang punô ng maasim na alak, kaya't naglagay sila ng isang esponghang basa ng suka sa isang sanga ng isopo, kanilang inilagay sa kanyang bibig.
Subalit kung umaasa tayo sa hindi natin nakikita, hinihintay natin itong may pagtitiis.
Sapagkat inanyayahan ng mga ito ang taong-bayan sa mga paghahandog sa kanilang mga diyos; at ang bayan ay kumain at yumukod sa mga diyos ng Moab.
Ito ang mga anak ni Ham ayon sa kanilang angkan, wika, mga lupain, at kanilang mga bansa.
Ako at ang Ama ay iisa.”
Isinalaysay ni Moises sa kanyang biyenan ang lahat ng ginawa ng Panginoon sa Faraon at sa mga Ehipcio alang-alang sa Israel, ang lahat ng hirap na kanilang naranasan sa daan, at kung paanong iniligtas sila ng Panginoon .
Nagsalita si Ruben sa kanyang ama, “Maaari mong ipapatay ang aking dalawang anak kung hindi ko siya maibabalik sa iyo. Ibigay mo siya sa akin at siya'y ibabalik ko sa iyo.”
Paglapit ninyo sa labanan, ang pari ay lalapit at magsasalita sa mga kawal,
Huwag ninyong ipagtaka ito, sapagkat dumarating ang oras na ang lahat ng nasa libingan ay makakarinig ng kanyang tinig,
Ang mga bayan nawa ay maglingkod sa iyo, at ang mga bansa ay magsiyukod sa iyo. Maging panginoon ka nawa ng iyong mga kapatid, at magsiyukod sa iyo ang mga anak ng iyong ina. Sumpain nawa ang mga sumusumpa sa iyo, at maging mapapalad ang mga magpapala sa iyo.”
Sinabi ni Jesus sa senturion, “Humayo ka na; mangyayari para sa iyo ang ayon sa iyong pananampalataya.” At gumaling nga ang alipin nang oras ding iyon.
Gayundin naman kayo, kapag nakita ninyong nangyayari ang mga bagay na ito, nalalaman ninyo na malapit na ang kaharian ng Diyos.
Dinala nila ito kay Jesus at ipinatong nila ang kanilang mga damit sa batang asno at isinakay nila si Jesus doon.
Nang dumating ang ikalabing-apat na gabi, samantalang kami'y ipinapadpad ng hangin sa kabila ng Dagat ng Adriatico, nang maghahating-gabi na ay inakala ng mga mandaragat na sila'y papalapit na sa lupa.
Subalit sinabi ni Abraham, ‘Nasa kanila si Moises at ang mga propeta, hayaan mo silang makinig sa kanila.’
Ang nahulog naman sa tinikan ay ang mga nakinig subalit sa kanilang pagpapatuloy ay sinakal sila ng mga alalahanin, mga kayamanan, at mga kalayawan sa buhay at ang kanilang bunga ay hindi gumulang.
Kanilang ipapatong doon ang lahat ng mga kasangkapan ng dambana na ginagamit sa paglilingkod doon, ang apuyan at ang mga pantusok, ang mga pala at ang mga mangkok, lahat ng mga kasangkapan ng dambana. Kanilang lalatagan iyon ng isang panakip na balat ng kambing, at kanilang ilalagay sa mga pasanan niyon.
Kanilang natanawan siya sa malayo, at bago siya nakalapit sa kanila ay nagsabwatan sila laban sa kanya na siya'y patayin.
Sinabi ng Panginoon kay Moises,
na sa pamamagitan din nito ang daigdig noon ay inapawan ng tubig at nagunaw.
Sapagkat kung ang salita na ipinahayag sa pamamagitan ng mga anghel ay may bisa, at ang bawat paglabag at pagsuway ay tumanggap ng kaukulang parusa,
Kaya't pinakinggan ng Diyos si Lea at siya'y naglihi at ipinanganak kay Jacob ang ikalimang anak.
Sa pawis ng iyong mukha ay kakain ka ng tinapay, hanggang ikaw ay bumalik sa lupa; sapagkat diyan ka kinuha. Ikaw ay alabok at sa alabok ka babalik.”
Huwag silang gagawa ng kalbong bahagi sa kanilang ulo, o gugupitin man ang dulo ng kanilang balbas, o hihiwaan man ang kanilang laman.
‘Sinabi ng Panginoon sa aking Panginoon, “Maupo ka sa aking kanan, hanggang sa mailagay ko ang iyong mga kaaway sa ilalim ng iyong mga paa”’?
Tinuruan ko kayo ng mga tuntunin at ng mga batas, na gaya ng iniutos sa akin ng Panginoon kong Diyos upang inyong gawin sa gitna ng lupain na inyong paroroonan upang angkinin.
At lahat ng mga tulos ng tabernakulo, at ng bulwagan sa palibot ay tanso.
At si Jacob ay nagalit at nakipagtalo kay Laban. Sinabi ni Jacob kay Laban, “Ano ang aking paglabag at ang aking kasalanan, at habulin mo ako na may pag-iinit?
At sa ikalimang taon ay makakakain na kayo ng bunga niyon upang lalong magbunga ang mga ito para sa inyo: Ako ang Panginoon ninyong Diyos.
Nang mangako ang Diyos kay Abraham, palibhasa'y walang sinumang higit na dakila na kanyang panunumpaan, siya ay nanumpa sa kanyang sarili,
Sinabi ni Balak kay Balaam, “Di ba ikaw ay aking pinapuntahan upang tawagin? Bakit nga ba hindi ka naparito sa akin? Hindi ba kita kayang parangalan?”
At ang bukid, ang mga bukas na lupain sa kanilang mga lunsod, ay hindi maipagbibili sapagkat ito ay isang walang hanggang pag-aari.
Subalit tayo'y kailangang mapadpad sa isang pulo.”
at kapag ang iyong mga bakahan at ang iyong mga kawan ay dumami na at ang iyong pilak at ang iyong ginto ay dumami at ang lahat ng nasa iyo ay dumami;
At hinuli ang halimaw at kasama niya ang bulaang propeta na gumawa ng mga tanda sa harapan nito, na siyang ipinandaya sa mga tumanggap ng tanda ng halimaw at sa mga sumamba sa larawan nito. Ang dalawang ito ay buháy na inihagis sa lawa ng apoy na nagliliyab sa asupre.
May ilang tao ang dumating mula sa Judea na nagtuturo sa mga kapatid, “Maliban na kayo'y tuliin ayon sa kaugalian ni Moises, hindi kayo maliligtas.”
Kaya't pinanukala ng mga punong pari na kanilang patayin din si Lazaro,
Sinabi niya sa kanila, “Kilala ba ninyo si Laban na anak ni Nahor?” At kanilang sinabi, “Kilala namin siya.”
Mula sa hapag ni Jose ay dinalhan sila ng mga pagkain, subalit ang pagkain ni Benjamin ay limang ulit na mas marami kaysa alinman sa kanila. Kaya't sila'y nag-inuman at nagkatuwaang kasama niya.
Dito'y tinawag niya kayo sa pamamagitan ng aming ebanghelyo, upang magkamit ng kaluwalhatian ng ating Panginoong Jesu-Cristo.
At isasauli niya ang kanyang ipinagkasala laban sa banal na bagay, at magdaragdag pa siya ng ikalimang bahagi, at ibibigay niya sa pari. Ang pari ay gagawa ng pagtubos para sa nagkasala sa pamamagitan ng lalaking tupang handog para sa budhing maysala at siya ay patatawarin.
Kanilang sinabi, “Hinihikayat ng taong ito ang mga tao na sumamba sa Diyos laban sa kautusan.”
Sapagkat siya'y ibinilang sa atin at siya'y tumanggap ng kanyang bahagi sa paglilingkod na ito.”
Ito ang mga batas at ang mga hatol at ang mga tuntuning ibinigay ng Panginoon sa kanyang sarili at sa mga anak ni Israel sa bundok ng Sinai sa pamamagitan ni Moises.
Nalalaman nating tayo'y dumaan na mula sa kamatayan patungo sa buhay, sapagkat iniibig natin ang isa't isa. Ang hindi umiibig ay nananatili sa kamatayan.
At dahil dito, gawin ninyo ang lahat ng inyong makakaya na tustusan ang inyong pananampalataya ng kabutihan; ang kabutihan ng kaalaman;
Nais ni Pablo na pumunta sa mga tao ngunit hindi siya pinayagan ng mga alagad.
at ang mga Jebuseo, Amoreo, ang mga Gergeseo;
Nang maipanganak na ni Raquel si Jose, sinabi ni Jacob kay Laban, “Hayaan mo na akong umalis upang ako'y makapunta sa aking sariling lugar at sa aking lupain.
Siya'y lumuhod at sumigaw nang malakas, “Panginoon, huwag mo silang papanagutin sa kasalanang ito.” At pagkasabi niya nito ay namatay siya.
Iniunat niya ang kanyang kamay at siya'y hinawakan at sinabi, “Nais ko, maging malinis ka.” At agad nawala ang kanyang ketong.
Kaya't nang makita ng babae na ang bunga ng punungkahoy ay mabuting kainin, nakakalugod sa paningin, na dapat nasain upang maging matalino, siya ay pumitas ng bunga nito at kinain ito; at binigyan din niya ang kanyang asawa na kasama niya, at siya'y kumain.
Kaya't sila'y humukay ng ibang balon at muli nilang pinagtalunan, at ito ay tinawag niya sa pangalang Sitnah.
“Ang kanilang lalamunan ay isang libingang bukas; sa pamamagitan ng kanilang mga dila ay gumagawa sila ng pandaraya.” “Ang kamandag ng mga ulupong ay nasa ilalim ng kanilang mga labi.”
Sinabi sa kanya ni Tomas, “Panginoon, hindi namin alam kung saan ka pupunta. Paano namin malalaman ang daan?”
At ang lahat ng mga ito, bagaman pinuri dahil sa kanilang pananampalataya, ay hindi nila tinanggap ang ipinangako,
At ang Espiritu Santo ay nagpapatotoo rin sa atin, sapagkat pagkatapos niyang sabihin,
kaya't dinala nila sa mga lansangan ang mga maysakit, at inilagay sa mga higaan at mga banig upang sa pagdaan ni Pedro ay madaanan man lamang ng anino niya ang ilan sa kanila.
Subalit kung ayaw ninyo kaming pakinggan na kayo'y matuli, ay kukunin namin ang aming anak na babae at kami ay aalis.”
Aking hinintay ang iyong pagliligtas, O Panginoon .
Kayo ba'y aking dinaya sa pamamagitan ng sinuman na aking sinugo sa inyo?
At kanyang sinabi, “Kung dumating si Esau sa isang pulutong at kanyang puksain ito, ang pulutong na natitira ay tatakas.”
At igagawa mo ng apat na argolyang ginto, at ilalagay mo ang mga argolya sa apat na sulok na nasa apat na paa niyon.
Kayo sa ngayon ay may kalungkutan, ngunit muli ko kayong makikita. Magagalak ang inyong puso, at walang makakapag-alis sa inyo ng inyong kagalakan.
Kukunin ng pari ang buslo sa iyong kamay at ilalagay sa harapan ng dambana ng Panginoon mong Diyos.
At titipunin sa harapan niya ang lahat ng mga bansa at kanyang pagbubukud-bukurin ang mga tao na gaya ng pagbubukud-bukod ng pastol sa mga tupa at sa mga kambing,
Ang iba'y nagtiis ng pagkalibak at paghagupit, at maging ng mga tanikala at pagkabilanggo.
Mayroong isang tao na isinugo mula sa Diyos na ang pangalan ay Juan.
Dahil sa habag ay hinipo ni Jesus ang kanilang mga mata. Kaagad, nakakita silang muli at sila'y sumunod sa kanya.
Siya'y tumingin at nakakita ng isang balon sa parang. May tatlong kawan ng mga tupa na nagpapahinga sa tabi roon, sapagkat sa balong iyon pinaiinom ang mga kawan. Ang batong nasa ibabaw ng labi ng balon ay napakalaki,
Sinabi sa kanya ni Jesus, “Babae, maniwala ka sa akin na darating ang oras na inyong sasambahin ang Ama, hindi sa bundok na ito o sa Jerusalem.
Sinabi ng Faraon kay Jose, “Ikaw ay inatasan ko upang mamahala sa buong lupain ng Ehipto.”
Pagkaraan ng anim na araw, isinama ni Jesus sina Pedro, Santiago at Juan, at dinala silang bukod sa isang mataas na bundok. Siya'y nagbagong-anyo sa harap nila;
Pagkatapos nito ay naglakbay ang bayan mula sa Haserot, at nagkampo sa ilang ng Paran.
Ang taong ito'y hinuli ng mga Judio, at papatayin sana nila, ngunit nang malaman kong siya'y mamamayan ng Roma dumating ako na may kasamang mga kawal at siya'y iniligtas ko.
Inyong nakita ang aking ginawa sa mga Ehipcio, at kung paanong dinala ko kayo sa mga pakpak ng agila, at kayo'y inilapit ko sa akin.
Sila ay nagtataka na kayo ay hindi na nakikisama sa gayong labis na kaguluhan, kaya't kayo'y nilalait nila.
“Kung may magningas na apoy at umabot sa mga tinik, na anupa't ang mga mandala, o ang mga uhay, o ang bukid ay masunog, ang nagpaningas ng apoy ay magbabayad ng buo.
Siya'y kanilang niluraan. Kinuha nila ang tambo at hinampas ang kanyang ulo.
Saka mo kukunin ang langis na pambuhos, at ibubuhos mo sa ibabaw ng kanyang ulo, at bubuhusan mo siya ng langis.
Kaya't kinapootan ni Esau si Jacob dahil sa basbas na ibinigay sa kanya ng kanyang ama. At sinabi ni Esau sa sarili, “Malapit na ang mga araw ng pagluluksa sa aking ama; pagkatapos ay papatayin ko si Jacob na aking kapatid.”
At nagtaka si Pilato na siya'y patay na. Ipinatawag niya ang senturion at itinanong niya sa kanya kung patay na nga siya.
At kapag matagpuan niya ito ay tinatawag niya ang kanyang mga kaibigan at mga kapitbahay, na nagsasabi, ‘Makigalak kayo sa akin, sapagkat natagpuan ko na ang pilak na nawala sa akin.’
Ginawa ng mga anak ni Levi ang ayon sa salita ni Moises; at nabuwal ang halos tatlong libong katao sa mamamayan nang araw na iyon.
Sinabi ni Cornelio, “Apat na araw na ang nakakaraan, mga ganitong oras, nang ikasiyam na oras, ako'y nananalangin sa aking bahay nang biglang tumindig sa harapan ko ang isang lalaki na may nagniningning na damit.
Ang mga alipin at ang mga punong-kawal ay nagpapaningas ng siga sapagkat maginaw. Sila'y nakatayo roon at nagpapainit. Si Pedro ay kasama rin nila na nakatayo at nagpapainit.
Kumuha ang bawat isa ng kanyang suuban, at lagyan ninyo ng insenso, at dalhin ninyo sa harap ng Panginoon , na bawat isa'y magdala ng kanyang suuban, na dalawandaan at limampung suuban; ikaw naman at si Aaron, bawat isa sa inyo'y may kanyang suuban.”
Sinabi ng Faraon sa kanya, “Umalis ka sa harap ko! Tiyakin mong huwag nang makitang muli ang aking mukha, sapagkat sa araw na iyong makita ang aking mukha ay mamamatay ka.”
Sapagkat kung tayo'y sumasampalatayang si Jesus ay namatay at muling binuhay ay gayundin naman, sa pamamagitan ni Jesus, ang mga natutulog ay dadalhin ng Diyos na kasama niya.
at noong ako'y nasa Jerusalem ay ipinagbigay-alam ng mga punong pari at ng matatanda sa mga Judio ang tungkol sa kanya na hinihinging humatol ako laban sa kanya.
Sapagkat sinasabi niya, “Kung mahipo ko man lamang ang kanyang damit ay gagaling na ako.”
Sa dakong hilaga ay isang daang siko, ang mga haligi ay dalawampu, at ang mga patungan ay dalawampu, yari sa tanso; ang mga kawit ng mga haligi at ang mga panali ay pilak.
Subalit sasabihin niya, ‘Hindi ko alam kung saan kayo nanggaling. Lumayas kayo, kayong lahat na gumagawa ng kasamaan!’
Ang mga bata sa loob niya ay naglaban at kanyang sinabi, “Kung ito ay tama, bakit ako mabubuhay?” Kaya't siya'y humayo upang magtanong sa Panginoon .
Ikaw ay magkakaanak ng mga lalaki at mga babae, ngunit sila'y hindi magiging iyo; sapagkat sila'y pupunta sa pagkabihag.
Ang inyong mga bahay ay mapupuno, ang mga bahay ng lahat mong lingkod, at ang mga bahay ng mga Ehipcio, na hindi nakita ng inyong mga magulang ni ng inyong mga ninuno, mula nang araw na sila'y mapasa daigdig hanggang sa araw na ito.’” At siya'y tumalikod at nilisan ang Faraon.
Ngunit si Balaam ay sumagot at nagsabi kay Balak, “Di ba sinabi ko sa iyo, ‘Ang lahat na sinasalita ng Panginoon ay siya kong nararapat gawin?’”
Nang dumating ang kapanahunan, nagsugo siya ng isang alipin sa mga magsasaka upang kunin sa kanila ang kanyang bahagi mula sa mga bunga ng ubasan.
Siya'y nakita ng lahat ng mga naninirahan sa Lidda at sa Sharon, at sila'y bumaling sa Panginoon.
Subalit ang toro, at ang balat nito, ang laman, at ang dumi, ay sinunog niya sa labas ng kampo; gaya ng iniutos ng Panginoon kay Moises.
Huwag kang tatanggap ng suhol, sapagkat ang suhol ay bumubulag sa mga pinuno at sinisira ang mga salita ng mga banal.
Kayo ay maghahandog sa Panginoon sa loob ng pitong araw ng handog na pinaraan sa apoy; at ang ikapitong araw ay magiging banal na pagpupulong. Huwag kayong gagawa ng anumang mabigat na gawain.”
Ngunit nang marinig ito ni Herodes ay sinabi niya, “Si Juan na aking pinugutan ng ulo ay muling nabuhay.”
Subalit ngayon ay nagmamalaki kayo sa inyong mga kayabangan. Ang lahat ng gayong pagmamalaki ay masama.
Sa gitna ng mga bansang ito ay hindi ka makakasumpong ng ginhawa, at mawawalan ng kapahingahan ang talampakan ng iyong paa, kundi bibigyan ka doon ng Panginoon ng isang nanginginig na puso, lumalabong paningin, at nanghihinang kaluluwa.
ay aming sinabi, ‘Hindi kami makakababa. Kung ang aming bunsong kapatid ay kasama namin, ay bababa kami. Sapagkat hindi namin makikita ang mukha ng lalaking iyon, malibang ang aming bunsong kapatid ay kasama namin.’
at ang daan ng kapayapaan ay hindi nila nakilala.”
Ngunit ang totoo, maraming babaing balo sa Israel noong panahon ni Elias, nang sarhan ang langit sa loob ng tatlong taon at anim na buwan at nagkaroon ng malubhang taggutom sa buong lupain.
ang tao na humipo sa gayon ay magiging marumi hanggang sa paglubog ng araw. Huwag siyang kakain ng mga banal na bagay, kundi paliliguan niya ang kanyang katawan sa tubig.
Ano nga ang ating sasabihin? Ang kautusan ba'y kasalanan? Huwag nawang mangyari. Gayunma'y hindi ko sana nakilala ang kasalanan, kung hindi sa pamamagitan ng kautusan; sapagkat hindi ko sana nakilala ang pag-iimbot kung hindi sinasabi ng kautusan, “Huwag kang mag-iimbot.”
Pagkatapos ay namatay naman ang babae.
Nang makita niya ang kanilang pananampalataya ay sinabi niya, “Lalaki, pinatatawad ka na sa iyong mga kasalanan.”
Pagkalooban nawa kayo ng Diyos na Makapangyarihan sa lahat ng awa sa harapan ng lalaking iyon upang ibalik sa inyo ang inyong isa pang kapatid at si Benjamin. At ako, kung ako'y mangulila, ako'y mangungulila.”
Nang dumating si Jose sa kanyang mga kapatid, siya'y kanilang hinubaran ng kanyang mahabang damit na kanyang suot.
Ito ang basbas na iginawad ni Moises, ang tao ng Diyos, sa mga anak ni Israel bago siya namatay.
Sinabi ni Laban, “Ang buntong ito ay saksi sa akin at sa iyo ngayon.” Kaya't tinawag niya ito sa pangalang Gilead;
Ako'y tumayo sa pagitan ninyo at ng Panginoon nang panahong iyon upang ipahayag sa inyo ang salita ng Panginoon ; sapagkat kayo'y natakot dahil sa apoy, at hindi kayo umakyat sa bundok. Kanyang sinabi:
At ito ay aming ginagawa upang huwag kaming malamangan ni Satanas, sapagkat kami ay hindi mangmang tungkol sa kanyang mga balak.
Ang lupain ay hindi maipagbibili magpakailanman, sapagkat akin ang lupain. Kayo'y mga dayuhan at nakikipamayang kasama ko.
At kapag nabasa na ang sulat na ito sa inyo, ay ipabasa rin ninyo sa iglesya ng mga taga-Laodicea; at basahin naman ninyo ang sulat na mula sa Laodicea.
Minsan, nagluto si Jacob ng nilaga. Dumating si Esau mula sa parang at siya'y gutom na gutom.
Ang mga anak ni Israel ay naglakbay at nagkampo sa mga kapatagan ng Moab sa kabila ng Jordan sa Jerico.
o ng anumang bato na ikamamatay ng tao, na hindi niya nakikita at kanyang naihagis sa kanya, na anupa't namatay at hindi niya kaaway, at hindi niya pinaghahangaran ng masama;
Huwag kayong gagawa ng mga diyos na pilak na iaagapay sa akin ni huwag kayong gagawa para sa inyo ng mga diyos na ginto.
Ginawa ng Panginoon ang ayon sa salita ni Moises; at ang mga palaka ay namatay sa mga bahay, sa mga looban at sa mga kabukiran.
Natagpuan niya sa templo ang mga nagtitinda ng mga baka, mga tupa, mga kalapati, at ang mga nagpapalit ng salapi na nakaupo.
Sumagot si Jesus, “Hindi ba ang maghapon ay may labindalawang oras? Ang lumalakad samantalang araw ay hindi natitisod, sapagkat nakikita niya ang ilaw ng sanlibutang ito.
Kaya't natakot nang husto at nabahala si Jacob; at kanyang hinati sa dalawa ang mga taong kasama niya, ang mga kawan, ang mga bakahan, at ang mga kamelyo.
Paano ko madadalang mag-isa ang mabigat na pasan ninyo at ng inyong mga alitan?
Aking itinalagang kasama niya si Aholiab, na anak ni Ahisamac, sa lipi ni Dan; at sa lahat ng may kakayahang gumawa ay nagbigay ako ng karunungan, upang magawa nila ang lahat ng aking iniutos sa iyo:
Sinabi ni Moises, “Kainin ninyo ito ngayon; sapagkat ngayo'y Sabbath para sa Panginoon , ngayo'y hindi kayo makakakita nito sa parang.
Maging mapagpatulóy kayo sa isa't isa nang walang bulung-bulungan.
Ang mga Levita ay sasagot at magsasalita sa malakas na tinig sa lahat ng mga lalaki sa Israel.
Tayo'y huwag nang maging mga bata, na tinatangay-tangay ng mga alon at dinadala-dala ng bawat hangin ng aral, sa pamamagitan ng pandaraya ng mga tao, sa pamamagitan ng kanilang mga katusuhan sa paraang mapandaya.
Nang makita ng puno ng mga panadero na ang kahulugan ay mabuti ay sinabi niya kay Jose, “Ako'y nanaginip din, at may tatlong kaing ng maputing tinapay ang nasa ibabaw ng aking ulo.
Ito ay mayroong isang malaki at mataas na pader, na may labindalawang pintuan, at sa mga pintuan ay may labindalawang anghel; at sa mga pintuan ay nakasulat ang mga pangalan ng labindalawang lipi ng mga anak ni Israel.
Huwag kang magpapasok ng karumaldumal sa iyong bahay, baka ikaw ay maging isang isinumpa na gaya niyon. Lubos mong kasusuklaman iyon at kamumuhian iyon, sapagkat iyon ay bagay na isinumpa.
At kumuha siya ng isang saro at nang makapagpasalamat ay ibinigay sa kanila, na nagsasabi, “Uminom kayong lahat nito,
at iyon ay mamamalagi sa kanya, at kanyang babasahin sa lahat ng mga araw ng kanyang buhay, upang siya'y matutong matakot sa Panginoon niyang Diyos, upang isagawa ang lahat ng mga salita ng kautusang ito at ng mga tuntuning ito;
Palawakin ng Diyos si Jafet, at siya'y titira sa mga tolda ni Sem; at si Canaan ay magiging alipin niya.”
Ang Panginoon ay nagsalita kay Moises,
Subalit ang mga Levita ay hindi binilang na kasama ayon sa lipi ng kanilang mga ninuno.
Ang paring si Eleazar ay kukuha ng dugo sa pamamagitan ng kanyang daliri, at pitong ulit na magwiwisik ng dugo sa dakong harap ng toldang tipanan.
Kakain ka, mabubusog, at iyong pupurihin ang Panginoon mong Diyos dahil sa mabuting lupain na kanyang ibinigay sa iyo.
ang pagpapala, kung inyong diringgin ang mga utos ng Panginoon ninyong Diyos na aking iniutos sa inyo sa araw na ito;
at sa bawat nilikhang may buhay na kasama ninyo, ang mga ibon, ang maamong hayop at bawat mailap na hayop sa lupa na kasama ninyo, sa lahat ng lumabas sa daong, sa bawat hayop sa lupa.
Noon ay isinama ni Jetro, na biyenan ni Moises, si Zifora na asawa ni Moises, pagkatapos niyang paalisin siya,
Nang siya'y aking makita, ako'y parang patay na bumagsak sa kanyang paanan. Ngunit ipinatong niya sa akin ang kanyang kanang kamay, na sinasabi, “Huwag kang matakot; ako ang una at ang huli,
Kinuha ni Rebecca ang pinakamagandang damit ng kanyang panganay na anak na si Esau na nasa kanya sa bahay at isinuot kay Jacob na kanyang bunsong anak.
Ngayon, bakit kailangang mamamatay kami? Sapagkat tutupukin kami ng napakalaking apoy na ito; kapag aming narinig pa ang tinig ng Panginoon nating Diyos, kami ay mamamatay.
Kaya't iniwan ng babae ang kanyang banga ng tubig at pumunta sa lunsod, at sinabi sa mga tao,
“Ang mga karwahe ng Faraon at ang kanyang hukbo sa dagat ay itinapon niya, at ang kanyang mga piling pinuno ay inilubog sa Dagat na Pula.
Ngunit sinasabi ko sa inyo, huwag ninyong ipanumpa ang anuman, maging ang langit, sapagkat iyon ang trono ng Diyos;
At tungkol sa muling pagkabuhay ng mga patay, hindi ba ninyo nabasa ang sinabi sa inyo ng Diyos,
Kayo mismo ang nakakaalam, mga kapatid, na ang aming pagdating sa inyo ay hindi nawalan ng kabuluhan.
“Kapag ang salot na ketong ay nasa isang tao, siya ay dadalhin sa pari.
Siya'y inalipusta ng mga nagdaraan at pailing-iling,
Sapagkat ano ang mapapakinabang ng tao na makamtan ang buong sanlibutan, at mapahamak ang kanyang buhay?
Ngunit ang galit ng Diyos ay nag-aalab sapagkat siya'y pumunta. Ang anghel ng Panginoon ay tumayo sa daan bilang kalaban niya. Siya noon ay nakasakay sa kanyang asno at ang kanyang dalawang alipin ay kasama niya.
“Huwag humipo, huwag tumikim, huwag humawak”?
Ako'y mananahan sa gitna ng mga anak ni Israel, at ako'y magiging kanilang Diyos.
At sinabi nila sa kanila ang sinabi ni Jesus at kanilang pinayagan sila.
Ginawa ito ni Jesus, ang una sa kanyang mga tanda, sa Cana ng Galilea, at ipinahayag ang kanyang kaluwalhatian; at sumampalataya sa kanya ang kanyang mga alagad.
Bagama't ibig niyang ipapatay si Juan, natakot siya sa mga tao sapagkat kanilang itinuturing si Juan na isang propeta.
Sapagkat wala akong sinuman na katulad niya na tunay na magmamalasakit sa inyong kapakanan.
Nang aming matagpuan ang isang barko na daraan sa Fenicia, sumakay kami at naglakbay.
Ang mga pastulan sa mga lunsod na inyong ibibigay sa mga Levita ay isang libong siko sa palibot mula sa pader ng lunsod hanggang sa dakong labas.
Subalit tumanggi ang kanyang ama, “Nalalaman ko, anak ko, nalalaman ko. Siya man ay magiging isang bayan, at siya man ay magiging dakila. Subalit ang kanyang kapatid na mas bata ay magiging higit na dakila kaysa kanya, at ang kanyang binhi ay magiging napakaraming mga bansa.”
At kanilang sinabi, “Manampalataya ka sa Panginoong Jesus at maliligtas ka, ikaw at ang iyong sambahayan.”
sa pag-asa sa buhay na walang hanggan. Bago pa nagsimula ang mga panahon, ito ay ipinangako ng Diyos na hindi nagsisinungaling.
Ang lahat ng mga bagay na nasa Ama ay akin, kaya sinabi ko na kanyang tatanggapin ang sa akin, at sa inyo'y ipahahayag.
“‘Ni huwag kang mangangalunya.
Ngunit tinawag sila ni Jesus at sinabi sa kanila, “Alam ninyo na ang mga pinuno ng mga Hentil ay nangingibabaw na panginoon sa kanila, at ang mga dakila sa kanila ay gumagamit ng kapangyarihan sa kanila.
Siya'y kanilang tutuyain, at duduraan, siya'y hahampasin at papatayin. Pagkaraan ng tatlong araw siya ay muling mabubuhay.”
Minamahal kong mga anak, na para sa inyo ay muli akong nakakaranas ng hirap ng panganganak hanggang si Cristo ay mabuo sa inyo.
Agad niyang pinasakay sa bangka ang kanyang mga alagad at pinauna sa kanya sa kabilang ibayo, sa Bethsaida, hanggang sa mapauwi na niya ang maraming tao.
Pagkatapos ng mga bagay na ito ay tumingin ako, at ang templo ng tolda ng patotoo sa langit ay nabuksan.
Ang mga ito'y lumapit kay Felipe, na taga-Bethsaida ng Galilea, at sinabi sa kanya, “Ginoo, ibig sana naming makita si Jesus.”
Sa ganoon ang buong Israel ay maliligtas; gaya ng nasusulat, “Lalabas mula sa Zion ang Tagapagligtas; ihihiwalay niya ang kasamaan mula sa Jacob.”
Hindi ba ito ang karpintero, ang anak ni Maria at kapatid nina Santiago, Jose, Judas, at Simon? Hindi ba naritong kasama natin ang kanyang mga kapatid na babae?” At sila'y natisod sa kanya.
Nang mga araw ngang ito ay may lumusong sa Antioquia na mga propetang galing sa Jerusalem.
Ingatan mo ang mabuting bagay na ipinagkatiwala sa iyo sa pamamagitan ng Espiritu Santo na nabubuhay sa atin.
Nang sila'y nakaupo na at kumakain, sinabi ni Jesus, “Katotohanang sinasabi ko sa inyo, ipagkakanulo ako ng isa sa inyo, ang kasalo kong kumakain.”
Sapagkat kung paanong ang kidlat ay kumikislap at pinaliliwanag ang langit mula sa isang panig hanggang sa kabila, gayundin naman ang Anak ng Tao sa kanyang araw.
Sa lahat ng araw ng kanyang pagiging Nazirita, hindi siya kakain ng anumang bagay na ibinubunga ng puno ng ubas, magmula sa mga butil hanggang sa balat.
Siya'y ipinaghanda nila roon ng isang hapunan. Si Marta ay naglilingkod, at si Lazaro ay isa sa nakaupo sa may hapag-kainan na kasalo niya.
At nagsalita ang Diyos kay Noe at sa mga anak na kasama niya, na sinasabi,
Humayo kayo, sinusugo ko kayong gaya ng mga kordero sa gitna ng mga asong-gubat.
Ipag-uutos ng pari na alisan ng laman ang bahay bago siya pumasok upang tingnan ang sakit, upang ang lahat na nasa bahay ay huwag maging marumi; at pagkatapos ay papasok ang pari upang tingnan ang bahay.
Ngayo'y isinasamo ko sa inyo, mga kapatid, alang-alang sa ating Panginoong Jesu-Cristo, at sa pag-ibig ng Espiritu, na kayo'y magsikap na kasama ko sa inyong mga panalangin sa Diyos para sa akin,
Sinabi niya sa kanya, ‘Ikaw ay mamamahala sa limang lunsod.’
Walang Judio o Griyego, walang alipin o malaya, walang lalaki o babae, sapagkat kayong lahat ay iisa kay Cristo Jesus.
Sinabi ng hari ng Sodoma kay Abram, “Ibigay mo sa akin ang mga tao at kunin mo ang mga ari-arian para sa iyong sarili.”
“Kapag may hayagang panawagan upang sumaksi, at magagawa ng isang tao na sumaksi bilang isa na nakakita o nakarinig, ngunit ayaw namang magsalita, ang taong iyon ay nagkakasala at dapat parusahan.
Kaya't pinangalanan ang balong iyon na Balon ng Nabubuhay na Nakakakita sa Akin; ito'y nasa pagitan ng Kadesh at Bered.
Ang buong bundok ng Sinai ay nabalot sa usok, sapagkat ang Panginoon ay bumaba sa ibabaw niyon na nasa apoy; at ang usok niyon ay pumailanglang na parang usok ng isang hurno, at nayanig nang malakas ang buong bundok.
At sila'y dumating sa libis ng Escol, at sila'y pumutol doon ng isang sangang may isang kumpol na ubas, at dinala sa isang pingga ng dalawa sa kanila. Sila'y nagdala rin ng mga prutas na granada, at mga igos.
Siya'y magpapatuloy sa panahon ng kanyang paglilinis sa dugo sa loob ng tatlumpu't tatlong araw; huwag siyang hihipo ng anumang bagay na banal, at huwag siyang papasok sa santuwaryo, hanggang sa matapos ang mga araw ng kanyang paglilinis.
“Huwag mong pagmamalupitan ang isang upahang manggagawa na dukha at nangangailangan, maging siya'y mula sa iyong mga kapatid, o sa mga dayuhan na nasa lupain mo sa loob ng iyong mga bayan.
“Sila'y gagawa ng isang kabang yari sa kahoy na akasya na may dalawang siko at kalahati ang haba, isang siko't kalahati ang luwang, isang siko't kalahati ang taas.
Kumalat ang balita tungkol sa kanya sa lahat ng dako sa palibot ng lupaing iyon.
Muli siyang naghintay ng pitong araw at muling pinalipad ang kalapati sa labas ng daong,
Sapagkat pagkaraan ng pitong araw, magpapaulan ako sa ibabaw ng lupa ng apatnapung araw at apatnapung gabi. Aking pupuksain ang lahat ng may buhay na aking nilikha sa balat ng lupa.”
isang Diyos at Ama ng lahat, na siyang nasa ibabaw ng lahat, at sumasa lahat, at nasa lahat.
Dinala nila si Jesus sa pinakapunong pari at nagtipon ang lahat ng mga punong pari, matatanda at mga eskriba.
At siya'y nagsimulang magsalita ng buong tapang sa sinagoga, ngunit nang siya'y marinig nina Priscila at Aquila ay kanilang isinama siya at ipinaliwanag sa kanya nang mas matuwid ang Daan ng Diyos.
At ang Panginoon ay nagpadala ng isang salot sa bayan, sapagkat kanilang ginawa ang guya—yaong ginawa ni Aaron.
Nang magkagayo'y sumagot si Jesus at sinabi sa kanya, “O babae, napakalaki ng iyong pananampalataya! Mangyayari sa iyo ang sinasabi mo.” At gumaling ang kanyang anak sa oras ding iyon.
Ni huwag kang magtatayo ng haligi na kinapopootan ng Panginoon mong Diyos.
“Ang maghandog sa alinmang diyos, maliban sa Panginoon lamang, ay lubos na pupuksain.
Kaya't dinakip at iginapos si Jesus ng mga kawal at ng kanilang kapitan, at ng mga punong-kawal ng mga Judio.
Sapagkat ang Hesbon ay siyang bayan ni Sihon na hari ng mga Amoreo, na siyang nakipaglaban sa unang hari sa Moab, at sumakop ng buong lupain niyon sa kanyang kamay hanggang sa Arnon.
siya ay muling nagtakda ng isang araw, “Ngayon,” na pagkatapos ng ilang panahon ay sinabi sa pamamagitan ni David, gaya ng sinabi noong una, “Ngayon, kung marinig ninyo ang kanyang tinig, huwag ninyong papagmatigasin ang inyong mga puso.”
Makipaglaban ka sa mabuting pakikipaglaban ng pananampalataya, panghawakan mo ang buhay na walang hanggan na dito'y tinawag ka, at ipinahayag mo ang mabuting pagpapahayag sa harapan ng maraming mga saksi.
Magtipun-tipon kayo at makinig, kayong mga anak ni Jacob; at inyong pakinggan si Israel na inyong ama.
Ngunit nang marinig ito ng mga apostol na sina Bernabe at Pablo, pinunit nila ang kanilang mga damit at tumakbo sa gitna ng karamihan, na sumisigaw,
Gayon ang ginawa ng Panginoon , at pumasok ang pulu-pulutong na langaw sa bahay ng Faraon, sa bahay ng kanyang mga lingkod; at sa buong lupain ng Ehipto ay nasira ang lupain dahil sa mga pulu-pulutong na langaw.
Sila'y tiningnan niya ng may galit. Nalulungkot siya sa katigasan ng kanilang puso at sinabi niya sa lalaki, “Iunat mo ang iyong kamay.” Iniunat niya ito at nanumbalik sa dati ang kanyang kamay.
Sinabi niya sa kanila, “Kapag kayo'y nananalangin, inyong sabihin, ‘Ama, sambahin nawa ang pangalan mo. Dumating nawa ang kaharian mo.
Ngunit sumagot siya at sinabi, ‘Katotohanang sinasabi ko sa inyo, hindi ko kayo nakikilala.’
Ngunit pagkamatay ni Herodes, ang isang anghel ng Panginoon ay nagpakita sa panaginip kay Jose sa Ehipto, na nagsasabi,
At kanyang papatayin ang toro sa harapan ng Panginoon ; ang dugo ay ihahandog ng mga anak ni Aaron, na mga pari, at iwiwisik ito sa palibot ng dambana na nasa pintuan ng toldang tipanan.
Tinawag niya ang sampu sa kanyang mga alipin at binigyan sila ng sampung mina, at sinabi sa kanila, ‘Ipangalakal ninyo ito hanggang sa ako'y dumating.’
Ang mga pinuno ay magsasalita sa mga kawal, ‘Sinong tao ang nagtayo ng isang bagong bahay, at hindi pa niya naitatalaga? Hayaan siyang umalis at bumalik sa kanyang bahay, baka siya'y mamatay sa pakikipaglaban at ibang tao ang magtalaga.
Nangyari sa kanila ang ayon sa tunay na kawikaan, “Nagbabalik muli ang aso sa kanyang sariling suka,” at, “Ang babaing baboy na nahugasan na, sa paglulublob sa putik.”
Tumingala ang lalaki at nagsabi, “Nakakakita ako ng mga tao, na parang mga punungkahoy na naglalakad.”
Pag-ingatan ninyong huwag itakuwil ang nagsasalita; sapagkat kung hindi nakatakas ang mga nagtakuwil sa nagbabala sa kanila sa lupa, lalo pa tayo kung tatalikuran natin ang nagbabala buhat sa langit!
Habang ang lupa ay nananatili, ang paghahasik at pag-aani, ang tag-init at taglamig, ang araw at gabi ay hindi hihinto.”
“Anumang bagay na ipinag-uutos ko sa iyo ay siya mong gagawin; huwag mong daragdagan, ni babawasan.
Sumagot ang mga kawal, “Kailanma'y walang taong nagsalita nang gayon.”
Nang siya'y dumating at nakita ang biyaya ng Diyos, ay nagalak siya at kanyang hinimok ang bawat isa upang manatili sa Panginoon na may katapatan ng puso;
Mga anak, huling oras na! Gaya ng inyong narinig na darating ang anti-Cristo, kahit ngayon ay lumitaw na ang maraming anti-Cristo. Kaya nalalaman nating huling oras na.
At ang sampung sungay na iyong nakita, sila at ang halimaw ay mapopoot sa mahalay na babae; siya'y pababayaan at huhubaran nila, lalamunin ang kanyang laman at siya'y lubos na susunugin sa apoy.
na doo'y naunang pumasok para sa atin si Jesus, na naging pinakapunong pari magpakailanman ayon sa pagkapari ni Melquizedek.
Dahil dito'y nagpapagal din naman ako at nagsisikap ayon sa kanyang paggawa na gumagawa sa akin na may kapangyarihan.
Nang buksan ng Kordero ang ikapitong tatak ay nagkaroon ng katahimikan sa langit nang may kalahating oras.
Si Jesus ay dinala ng mga dumakip sa kanya kay Caifas, na pinakapunong pari, na kung saan nagkatipon ang mga eskriba at matatanda.
Pagkatapos ay kanyang tinawag ang dalawa sa mga senturion, at sinabi, “Sa ikatlong oras ng gabi, ihanda ninyo ang dalawandaang kawal kasama ang pitumpung mangangabayo at dalawandaang may sibat upang magtungo sa Cesarea.
Inyong tutuparin ito bilang isang kapistahan sa Panginoon sa loob ng pitong araw sa bawat taon. Ito ay isang tuntunin magpakailanman sa buong panahon ng inyong salinlahi; sa ikapitong buwan ay ipagdiriwang ninyo ang kapistahang ito.
At nagreklamo ang lahat ng mga anak ni Israel laban kina Moises at Aaron. Sinabi sa kanila ng buong sambayanan, “Namatay na sana tayo sa lupain ng Ehipto! O kaya'y namatay na sana tayo sa ilang na ito!
Mga minamahal, kung tayo'y inibig ng Diyos nang gayon, nararapat na mag-ibigan din naman tayo sa isa't isa.
Sinabi ni Agripa kay Festo, “Ang taong ito ay maaari na sanang palayain kung hindi siya dumulog kay Cesar.”
Ang may pandinig ay makinig sa sinasabi ng Espiritu sa mga iglesya.
At nagbalik galing sa Jerusalem sina Bernabe at Saulo nang magampanan na nila ang kanilang paglilingkod at kanilang isinama si Juan na tinatawag ding Marcos.
Nang siya'y makita ni Jesus, kanyang tinawag siya at sinabi sa kanya, “Babae, pinalaya ka na sa iyong sakit.”
Dinala ko siya sa iyong mga alagad, ngunit siya'y hindi nila mapagaling.
Kayo'y mga saksi, at pati ang Diyos, kung gaano kadalisay, matuwid at walang kapintasan ang inasal namin sa inyo na mga mananampalataya.
kabilang sa mga ito sina Himeneo at Alejandro na aking ibinigay kay Satanas, upang sila'y maturuang huwag manlapastangan.
Tinawag ni Abraham na Isaac ang anak na ipinanganak sa kanya ni Sara.
Sapagkat ang sinumang hindi laban sa atin ay panig sa atin.
Magsalita ka ngayon sa pandinig ng bayan at humingi ang bawat lalaki sa kanyang kapwa, at bawat babae sa kanyang kapwa ng mga alahas na pilak, at ng mga alahas na ginto.”
Kaya't lumaganap ang salita ng Panginoon sa buong lupain.
Kaya ngayon ay humayo ka, ako'y sasaiyong bibig at ituturo ko sa iyo kung ano ang iyong sasabihin.”
Nangunguna sa hukbo ng lipi ng mga anak ni Benjamin si Abidan na anak ni Gideoni.
ito ay susuriin ng pari, at kung makitang ang buhok ay pumuti sa bahaging makintab, at tila mas malalim kaysa balat, ito ay ketong. Ito ay lumitaw sa paso, at ipahahayag ng pari na siya ay marumi; ito ay sakit na ketong.
Sumagot si Jesus at sinabi sa kanila, “Nagkakamali kayo, sapagkat hindi ninyo nalalaman ang mga kasulatan, o ang kapangyarihan ng Diyos.
Magbatian kayo ng banal na halik. Binabati kayo ng lahat ng mga iglesya ni Cristo.
Walang kawal na naglilingkod ang nakikisangkot sa mga bagay ng buhay na ito, yamang ang kanyang mithiin ay bigyang-kasiyahan ang nagtala sa kanya.
Kaya't nagkaroon ng pagkakahati-hati sa maraming tao dahil sa kanya.
Ikaw ay humihip ng iyong hangin, at tinabunan sila ng karagatan, Sila'y lumubog na parang tingga sa tubig na makapangyarihan.
At binigkas ni Balaam ang kanyang talinghaga, na sinasabi, “Tumindig ka, Balak, at iyong pakinggan, makinig ka sa akin, ikaw na anak ni Zipor.
Ang mga anak ni Uziel: sina Misael, Elzafan, at Sitri.
Kinuha nila si Jesus, at siya'y lumabas na pasan niya ang krus, patungo sa tinatawag na Pook ng Bungo, na sa wikang Hebreo ay tinatawag na Golgota.
Kayo'y aking mga kaibigan kung ginagawa ninyo ang mga bagay na aking iniuutos sa inyo.
Sapagkat natatakot ako dahil sa galit at maalab na poot na ikinayamot ng Panginoon sa inyo, na lilipulin sana kayo. Ngunit pinakinggan din ako noon ng Panginoon .
Sapagkat tinupad mo ang salita ng aking pagtitiis, ikaw naman ay aking iingatan sa oras ng pagsubok na darating sa buong daigdig, upang subukin ang mga naninirahan sa ibabaw ng lupa.
Ako'y natatakot na kapag ako'y dumating na muli, ako'y gawing mapagpakumbaba ng Diyos sa harapan ninyo, at ako'y kailangang magdalamhati dahil sa marami na nagkasala noong una at hindi nagsisi sa karumihan, pakikiapid, at sa kahalayang ginawa nila.
“Ang aking pamumuhay mula sa aking pagkabata, na simula pa'y ginugol ko na sa aking bansa at sa Jerusalem, ay nalalaman ng lahat ng mga Judio.
Kung ako'y nagpapatotoo para sa aking sarili, ang patotoo ko ay hindi totoo.
Marunong akong magpakababa, at marunong din akong magpakasagana; sa bawat bagay at sa lahat ng bagay ay natutunan ko ang lihim sa kabusugan, at maging sa kagutuman, at maging sa kasaganaan at maging sa kasalatan.
Nang mga araw na iyon, nang magkaroong muli ng napakaraming tao na walang makain, tinawag niya ang kanyang mga alagad at sinabi sa kanila,
Aakyatin ka ng mga palaka at ang iyong bayan, at ang lahat ng iyong mga lingkod.’”
“Huwag kang magpapahiram na may patubo sa iyong kapatid, patubo ng salapi, patubo ng kakainin, patubo ng anumang bagay na ipinapahiram na may patubo.
at kay Apia na ating kapatid na babae, at kay Arquipo na kapwa namin kawal, at sa iglesya na nasa iyong bahay:
Nang araw ding iyon, dumating ang mga alipin ni Isaac at siya'y binalitaan tungkol sa hinukay nilang balon, at sinabi sa kanya, “Nakatagpo kami ng tubig.”
Yaong buhat sa pasimula, na aming narinig, nakita ng aming mga mata, aming napagmasdan, at nahipo ng aming mga kamay, tungkol sa salita ng buhay—
Kung siya ay itinalaga niya para sa kanyang anak na lalaki, kanyang papakitunguhan siya tulad sa isang malayang anak na babae.
Sa palagay ko ay hindi ako pahuhuli sa mga dakilang apostol na ito.
“Huwag kayong kakain ng anumang bagay na kusang namatay; maaari mong ibigay sa dayuhang nasa loob ng iyong mga bayan, upang kanyang kainin; o maaari mong ipagbili sa dayuhan; sapagkat ikaw ay isang banal na bayan sa Panginoon mong Diyos. “Huwag mong lulutuin ang guyang kambing sa gatas ng kanyang ina.”
At si Sarai ay baog; siya'y walang anak.
Napuno ng kaguluhan ang lunsod at sama-sama nilang nilusob ang tanghalan, at sinunggaban sina Gayo at Aristarco, mga taga-Macedonia, na kasama ni Pablo sa paglalakbay.
Ako ang pumili sa inyong mga kapatid na mga Levita sa gitna ng mga anak ni Israel. Sila ay isang kaloob sa inyo, na ibinigay sa Panginoon , upang gawin ang paglilingkod sa toldang tipanan.
Ipinahayag sa kanila na hindi sila naglilingkod sa kanilang sarili kundi sa inyo, sa mga bagay na ngayo'y ibinalita sa inyo sa pamamagitan ng mga nangaral sa inyo ng ebanghelyo sa pamamagitan ng Espiritu Santo na sinugo mula sa langit; na ang mga bagay na ito'y pinananabikang makita ng mga anghel.
Subalit ang kaloob na walang bayad ay hindi gaya ng pagsuway. Sapagkat kung sa pamamagitan ng pagsuway ng isa ang marami ay namatay, lalo pang sumagana para sa marami ang biyaya ng Diyos, at ang kaloob dahil sa biyaya ng isang tao, na si Jesu-Cristo.
Pagkatapos ay kanyang dinala siya sa Jerusalem at inilagay siya sa tuktok ng templo, at sinabi sa kanya, “Kung ikaw ang Anak ng Diyos, magpatihulog ka mula rito,
Hindi siya ang ilaw, kundi dumating siya upang magpatotoo tungkol sa ilaw.
May iisa lamang kautusan para sa ipinanganak sa lupain, at para sa dayuhang naninirahang kasama ninyo.”
At sa kanyang paglakad mula roon ay nakita niya sa bangka ang dalawa pang magkapatid, si Santiago na anak ni Zebedeo at si Juan na kanyang kapatid, kasama si Zebedeo na kanilang ama, na nag-aayos ng lambat; at kanyang tinawag sila.
Sapagkat kanilang ilalayo ang iyong anak na lalaki sa pagsunod sa akin, upang maglingkod sa ibang mga diyos, sa gayo'y mag-aalab ang galit ng Panginoon laban sa iyo, at mabilis ka niyang pupuksain.
Ngunit sinabi sa kanya ni Jesus, “Sumunod ka sa akin; at hayaan mong ang mga patay ang maglibing sa sarili nilang mga patay.”
Katotohanang sinasabi ko sa inyo, ang lahat ng mga bagay na ito ay darating sa lahing ito.
Ipinagbilin niya sa kanya na huwag sabihin kaninuman. “Humayo ka, magpakita ka sa pari, at maghandog ka ayon sa iniutos ni Moises dahil ikaw ay naging malinis, bilang patotoo sa kanila.”
Sinabi ni Esau, “Ako'y malapit nang mamatay. Ano ang mapapakinabang ko sa pagkapanganay?”
At dumating ang mga tao upang tingnan ang nangyari. Lumapit sila kay Jesus at kanilang nadatnan ang taong nilisan ng mga demonyo na nakaupo sa paanan ni Jesus na may damit at matino ang pag-iisip nito; at sila'y natakot.
Ito ang mga nabilang ni Moises at ng paring si Eleazar, na bumilang ng mga anak ni Israel sa mga kapatagan ng Moab sa tabi ng Jordan sa Jerico.
Sinabi ng Panginoon kay Moises, “Umakyat ka rito sa akin sa bundok, at maghintay ka roon at ibibigay ko sa iyo ang mga tapyas ng bato at ang batas at ang kautusan na aking isinulat, upang iyong maituro sa kanila.”
Nagtayo si Jacob ng isang haligi sa ibabaw ng kanyang libingan na siyang haligi ng libingan ni Raquel hanggang ngayon.
Huwag kang magbibigay ng iyong anak upang italaga iyon sa apoy kay Molec; ni huwag mong lalapastanganin ang pangalan ng iyong Diyos; Ako ang Panginoon .
Kaya't kinuha ko ang mga pinuno ng inyong mga lipi, mga taong matatalino at may karanasan, at inilagay sila bilang mga pinuno ninyo, na mga pinuno ng libu-libo, mga pinuno ng daan-daan, mga pinuno ng lima-limampu, mga pinuno ng sampu-sampu, at mga pinuno sa inyong mga lipi.
At buong sikap na hinanap ni Moises ang kambing na handog pangkasalanan, at iyon ay sinunog na! Siya ay nagalit kina Eleazar at Itamar na mga nalalabing anak ni Aaron, at kanyang sinabi,
Ngunit matapos akong maibangon, mauuna ako sa inyo sa Galilea.”
“Sabihin mo sa mga anak ni Israel, ‘Pagtawid ninyo sa Jordan sa lupain ng Canaan,
Ako'y lumingon upang makita kung kanino ang tinig na nagsasalita sa akin. At sa aking paglingon, nakita ko ang pitong gintong ilawan,
Kung tinatawag nga siya ni David na Panginoon, paanong siya'y naging kanyang anak?”
Lumabas si Lot sa pintuan upang humarap sa kanila, at isinara ang pinto sa likuran niya.
Kung nililinis ng sinuman ang kanyang sarili mula sa mga bagay na ito ay magiging tanging kagamitan, itinalaga at mahalaga sa may-ari ng bahay, handa sa lahat ng mabuting gawa.
hindi sa buong bayan, kundi sa amin na hinirang ng Diyos bilang mga saksi na kumain at uminom na kasalo niya, pagkatapos na siya'y mabuhay mula sa mga patay.
Sinabi ng lalaki, “Ang babaing ibinigay mo na aking makakasama ang nagbigay sa akin ng bunga ng punungkahoy at ito'y aking kinain.”
Ngunit hindi pa ako mukhaang nakikilala sa mga iglesya ng Judea na kay Cristo.
“Walang taong pagkatapos magsindi ng ilawan ay tinatakpan ito ng isang takalan, o kaya'y inilalagay ito sa ilalim ng higaan, kundi inilalagay ito sa talagang lalagyan upang makita ng mga pumapasok ang liwanag.
Magalak kayong lagi.
Si Pablo na alipin ni Jesu-Cristo, tinawag upang maging apostol, ibinukod para sa ebanghelyo ng Diyos,
Kaya't siya'y isinama at dinala sa punong kapitan, at sinabi, “Tinawag ako ng bilanggong si Pablo, at ipinakiusap sa aking dalhin ko sa iyo ang binatang ito na mayroong sasabihin sa iyo.”
Nabuhay si Shela ng apatnaraan at tatlumpung taon pagkatapos na maipanganak si Eber, at nagkaanak pa ng mga lalaki at mga babae.
Sina Abraham at Sara ay kapwa matanda na at lipas na sa panahon. Si Sara ay hindi na dinadatnan ng tulad ng likas sa mga babae.
Ang ilawan ng katawan ay ang iyong mata. Kung malusog ang iyong mata, ang buong katawan mo ay punô ng liwanag. Subalit kung ito'y hindi malusog, ang katawan mo ay punô ng kadiliman.
Sila'y gumawa ng dalawang pangkalupkop na ginto, at ng dalawang singsing na ginto; at inilagay ang dalawang singsing sa dalawang dulo ng pektoral.
Sinusulatan ko kayo, hindi dahil sa hindi ninyo nalalaman ang katotohanan, kundi dahil nalalaman ninyo iyon, at nalalaman ninyo na walang kasinungalingan na nagmumula sa katotohanan.
At kapag pinalaya mo siya, ay huwag mo siyang paalisin na walang dala;
At muling ipinagkaila niya ito nang may panunumpa, “Hindi ko kilala ang taong iyon.”
sapagkat siya'y nasa mga balakang pa ng kanyang ninuno nang siya'y salubungin ni Melquizedek.
“Huwag ninyong ibigay sa mga aso ang mga banal na bagay; at huwag kayong magtapon ng inyong mga perlas sa harap ng mga baboy; baka yurakan nila ang mga ito ng kanilang mga paa, at pagbalingan kayo at lapain.
At ibinuka ng lupa ang kanyang bibig, at nilamon sila pati si Kora. Nang mamatay ang pangkat na iyon; noong panahong lamunin ng apoy ang dalawandaan at limampung tao, at sila'y naging isang babala.
Sapagkat ang mga tao'y magiging maibigin sa kanilang sarili, maibigin sa salapi, mayayabang, mga mapagmalaki, mapanlait, suwail sa mga magulang, mga walang utang na loob, walang kabanalan,
Sapagkat ang kaharian ng Diyos ay hindi ang pagkain at pag-inom, kundi ang pagiging matuwid, kapayapaan, at ang kagalakan sa Espiritu Santo.
Ang mga ito'y marumi sa inyo mula sa lahat ng umuusad; sinumang humipo sa mga iyan, kapag ang mga iyan ay patay, ay magiging marumi hanggang sa paglubog ng araw.
Si Lucas lamang ang kasama ko. Sunduin mo si Marcos at isama mo, sapagkat siya'y kapaki-pakinabang sa akin sa ministeryo.
“Pagkatapos ay papatayin niya ang kambing na handog pangkasalanan na para sa bayan, at dadalhin ang dugo niyon sa loob ng tabing. Ang gagawin sa dugo ay ang gaya ng ginawa sa dugo ng toro, at iwiwisik iyon sa ibabaw ng luklukan ng awa at sa harapan ng luklukan ng awa.
Ngunit, yamang kayo'y sumasagana sa lahat ng mga bagay, sa pananampalataya, sa pananalita, sa kaalaman, sa buong kasipagan, at sa inyong pag-ibig sa amin, sikapin din ninyo na kayo ay sumagana sa biyayang ito.
“Narito, magdadalang-tao ang isang birhen at manganganak ng isang lalaki, at ang pangalang itatawag nila sa kanya ay Emmanuel” (na ang ibig sabihin ay kasama natin ang Diyos).
Ngunit may ilang Judio roon na galing sa Asia—na dapat naririto sa harapan mo at magsakdal, kung mayroon silang anumang laban sa akin.
Sila'y dumating sa Elim, kung saan mayroong labindalawang bukal ng tubig, at pitumpung puno ng palma; at sila'y humimpil doon sa tabi ng tubig.
Sapagkat kung ang unang tipang iyon ay walang kapintasan, hindi na sana kailangang humanap pa ng pangalawa.
Tumayo sa malayo ang kanyang kapatid na babae upang malaman ang mangyayari sa bata.
“Subalit mag-ingat kayo sa inyong sarili, baka magumon ang inyong mga puso sa katakawan, at kalasingan, at sa mga alalahanin ukol sa buhay na ito, at biglang dumating ang araw na iyon na parang bitag.
Nagkatipon din ang maraming bilang ng mga tao mula sa mga bayang nasa palibot ng Jerusalem, na nagdadala ng mga maysakit, at ng mga pinahihirapan ng masasamang espiritu at silang lahat ay pinagaling.
samantalang kami, bilang aming bahagi, ay mag-uukol ng aming sarili sa pananalangin at sa paglilingkod sa salita.”
Hindi nila naunawaan na siya ay nagsasalita sa kanila tungkol sa Ama.
Ngunit kung sawayin siya ng kanyang asawa sa araw na marinig iyon, mawawalan ng kabuluhan ang kanyang panata at ang binitiwang pangako ng kanyang mga labi na doo'y itinali niya ang kanyang sarili, at patatawarin siya ng Panginoon .
Sinabi niya sa kanila, “Pinakahahangad kong kainin na kasalo kayo ang kordero ng Paskuwang ito bago ako magdusa,
Ang Israel ay gumawa ng sumpa sa Panginoon at nagsabi, “Kung tunay na ibibigay mo ang bayang ito sa aking kamay, aking lubos na gigibain ang kanilang mga bayan.”
At nang oras na iyon ay nagkaroon ng isang malakas na lindol, at nagiba ang ikasampung bahagi ng lunsod; may namatay sa lindol na pitong libong katao at ang mga iba ay natakot, at nagbigay ng luwalhati sa Diyos ng langit.
Kaya't sinabi sa kanila ni Jesus, “Ang ilaw ay kasama ninyo ng kaunti pang panahon. Kayo'y lumakad habang nasa inyo ang ilaw, upang huwag kayong abutin ng dilim. Ang lumalakad sa dilim ay hindi nalalaman kung saan siya tutungo.
Sinabi ng Panginoong Diyos, “Tingnan ninyo, ang tao'y naging parang isa sa atin, na nakakakilala ng mabuti at ng masama; at ngayon, baka iunat ang kanyang kamay at pumitas din ng bunga ng punungkahoy ng buhay, at kumain, at mabuhay magpakailanman.”
Kaya't kanyang tinanong siya ng matagal subalit si Jesus ay hindi sumagot ng anuman.
Subalit kung sa pamamagitan ng aking kasinungalingan ay sumagana ang katotohanan ng Diyos sa ikaluluwalhati niya, bakit hinahatulan pa rin akong tulad sa isang makasalanan?
Wala bang natagpuang bumalik at nagbigay papuri sa Diyos, maliban sa dayuhang ito?”
Sinabi ni Isaac na kanyang ama sa kanya, “Sino ka?” At kanyang sinabi, “Ako ang iyong anak, ang iyong panganay na si Esau.”
Sumainyo nawa ang biyaya at kapayapaang mula sa Diyos na ating Ama at sa Panginoong Jesu-Cristo.
Kaya't si Zilpa na alila ni Lea ay nagkaanak ng isang lalaki kay Jacob.
Noon ay matindi ang taggutom sa lupain.
Makinig kayo! Akong si Pablo ay nagsasabi sa inyo na kung kayo'y patutuli, si Cristo ay hindi magiging pakinabang sa inyo.
Ngunit siya'y kanilang sinunggaban, binugbog at pinaalis na walang dala.
Sinabi niya sa kanila, “Ngunit ano ang sinasabi ninyo kung sino ako?”
Nang buksan niya ang ikaanim na tatak, nagkaroon ng malakas na lindol; at ang araw ay umitim na gaya ng damit-sako at ang bilog na buwan ay naging gaya ng dugo;
Sinabi sa kanya ni Jesus, “Ako nga iyon na kumakausap sa iyo!”
Ang mga anak ni Juda: sina Er, Onan, Shela, Perez, at si Zera; ngunit sina Er at Onan ay namatay sa lupain ng Canaan. At ang mga anak ni Perez ay sina Hesron at Hamul.
Ang kaaway na naghasik ng mga ito ay ang diyablo. Ang anihan ay ang katapusan ng sanlibutan; at ang mga manggagapas ay ang mga anghel.
Siya'y kailangang tumaas, nguni't ako'y kailangang bumaba.”
Kaya't sila'y sumagot na hindi nila nalalaman kung saan iyon nagmula.
Sapagkat nais naming pumunta sa inyo—lalo na akong si Pablo na paulit-ulit na nais makabalik—ngunit hinadlangan kami ni Satanas.
Ako ay makapagpapatunay na sila ay kusang-loob na nagbigay ayon sa kanilang kakayahan, at higit pa sa kanilang makakaya,
Kaya't iwaksi ninyo ang lahat ng kasamaan, pandaraya, pagkukunwari, inggitan, at lahat ng paninirang-puri.
Aking itatatag ang aking tipan sa iyo at sa iyong binhi kahit sa iyong pagkamatay sa buong lahi nila, isang tipang walang hanggan, upang maging Diyos mo at ng iyong binhi.
hindi ba kayo'y gumagawa ng mga pagtatangi sa inyong mga sarili, at nagiging mga hukom na may masasamang pag-iisip?
Taglay natin ito bilang isang tiyak at matibay na angkla ng kaluluwa, isang pag-asa na pumapasok sa loob ng santuwaryo, sa kabila ng tabing,
Sa gayunding paraan ay nilibak siya ng mga punong pari, kasama ng mga eskriba at ng matatanda, na nagsasabi,
at tinanggap sila ni Jason. Lahat sila ay kumikilos laban sa mga utos ni Cesar, at sinasabi nilang may ibang hari na ang pangalan ay Jesus.”
Hindi siya makikipagtalo, o sisigaw, o maririnig ng sinuman ang kanyang tinig sa mga lansangan.
At sila'y labis na nalungkot, at isa-isang nagpasimulang magsabi sa kanya, “Ako ba, Panginoon?”
kapag naipaalam na sa kanya ang kasalanan niyang nagawa, siya ay magdadala ng kanyang handog na isang babaing kambing na walang kapintasan para sa kasalanang nagawa niya.
Ang mga may among mananampalataya ay huwag maging walang-galang sa kanila, sapagkat sila'y mga kapatid, kundi lalo pa silang maglingkod, sapagkat ang mga makikinabang ay mga mananampalataya at mga minamahal. Iyong ituro at ipangaral ang mga bagay na ito.
Sa paglubog ng araw sa ikalabing-apat na araw ng unang buwan, kakain kayo ng tinapay na walang pampaalsa, hanggang sa ikadalawampu't isang araw ng buwan, sa paglubog ng araw.
At ang mga alagad ay bumalik na sa kani-kanilang mga tahanan.
Ako'y labis na nagalak nang dumating ang mga kapatid at nagpatotoong ikaw ay nasa katotohanan, kung paanong lumalakad ka sa katotohanan.
At biglang nagkaroon ng malakas na lindol, sapagkat bumaba mula sa langit ang isang anghel ng Panginoon, na naparoon at iginulong ang bato, at umupo sa ibabaw nito.
Kayo ay magkakaloob ng pantubos sa lupain sa buong lupain na inyong pag-aari.
Sapagkat ang Diyos ay hindi masama; hindi niya kaliligtaan ang inyong gawa at ang pag-ibig na inyong ipinakita sa kanyang pangalan, sa inyong paglilingkod sa mga banal, gaya ng ginagawa ninyo ngayon.
Tayo ay nahatulan ng matuwid, sapagkat tinanggap natin ang nararapat na kabayaran sa ating mga gawa. Subalit ang taong ito'y hindi gumawa ng anumang masama.”
Nang inaalisan nila ng laman ang kanilang mga sako, sa sako ng bawat isa ay nakalagay ang kanya-kanyang bungkos ng salapi. Nang makita nila at ng kanilang ama ang kanilang mga bungkos ng salapi, sila ay natakot.
Nang makainom ang mga kamelyo, kumuha ang lalaki ng isang singsing na ginto, na may kalahating siklo ang timbang, at dalawang pulseras para sa kanyang mga kamay, na may timbang na sampung siklong ginto.
“Pagpasok mo sa lupaing ibinibigay sa iyo ng Panginoon mong Diyos ay huwag kang mag-aaral gumawa ng ayon sa mga karumaldumal na gawain ng mga bansang iyon.
Kanilang dinala ang lahat ng kanilang nakuha, at ang lahat ng kanilang nasamsam, maging tao at hayop.
sapagkat ang gumawa sa pamamagitan ni Pedro sa pagka-apostol sa mga tuli ay siya ring gumawa sa akin sa pagka-apostol sa mga Hentil;
Subalit sinabi niya, “Ang mga bagay na hindi magagawa ng mga tao ay magagawa ng Diyos.”
Paglabas niyang muli nang malapit na ang ikaanim na oras at ikasiyam, gayundin ang ginawa niya.
Hinawakan niya ang kamay ng babae, at nawala ang kanyang lagnat. Bumangon siya at naglingkod kay Jesus.
Ikaw ay maninirahan sa lupain ng Goshen, at malalapit ka sa akin, ikaw at ang iyong mga anak, ang mga anak ng iyong mga anak, ang iyong mga kawan, mga bakahan, at ang iyong buong pag-aari.
Nang matapos na ni Jesus ang mga talinghagang ito, iniwan niya ang pook na iyon.
Subalit nang kanyang isalaysay ito sa kanyang ama at mga kapatid, siya ay pinagalitan ng kanyang ama, at sinabi sa kanya, “Ano itong iyong napanaginip? Tunay bang ako, ang iyong ina, at ang iyong mga kapatid ay yuyukod sa lupa sa harap mo?”
“Gagawin mo ang dambana na yari sa kahoy na akasya na limang siko ang haba at limang siko ang luwang; ang dambana ay gagawing parisukat at ang taas nito ay tatlong siko.
Ang mga anak ni Israel ay naglakbay mula sa Rameses at nagkampo sa Sucot.
Nang malapit na siya at nakita ang lunsod, ito'y kanyang iniyakan,
Sumiping si Cain sa kanyang asawa, at siya'y naglihi at ipinanganak si Enoc. Siya'y nagtayo ng isang lunsod at tinawag ang lunsod ayon sa pangalan ng kanyang anak na si Enoc.
Dumating din si Nicodemo, na noong una ay lumapit sa kanya noong gabi, na may dalang pinaghalong mira at mga aloe, halos isandaang libra ang timbang.
Gayunma'y kailangang ako'y magpatuloy sa aking lakad ngayon at bukas at sa makalawa, sapagkat hindi maaari na ang isang propeta ay mamatay sa labas ng Jerusalem.’
Tingnan ninyo, sa inyo'y iniwan ang inyong bahay. At sinasabi ko sa inyo, hindi ninyo ako makikita, hanggang sa inyong sabihin, ‘Mapalad ang dumarating sa pangalan ng Panginoon.’”
at ang tanda o ang kababalaghan ay mangyari, na kanyang sabihin sa iyo, ‘Sumunod tayo sa ibang mga diyos,’ na hindi mo kilala, ‘at ating paglingkuran sila,’
Nang malapit na siya sa Jerico, isang bulag ang nakaupo sa tabi ng daan na namamalimos.
Sinabi nga niya, “Isang maharlikang tao ang pumunta sa isang malayong lupain, upang tumanggap ng isang kaharian at pagkatapos ay bumalik.
“Dadalhin ka ng Panginoon at ang haring ilalagay mo upang manguna sa iyo sa isang bansang hindi mo nakilala, maging ng iyong mga ninuno at doo'y maglilingkod ka sa ibang mga diyos na yari sa kahoy at bato.
Habang ako'y nasa sanlibutan, ako ang ilaw ng sanlibutan.”
Sinabi niya sa kanyang mga kapatid, “Ang salapi ko ay isinauli at tingnan din ninyo ang aking sako.” Sila'y nanlupaypay at bawat isa ay takot na nagsasabi sa kanyang kapatid, “Ano itong ginawa ng Diyos sa atin?”
Gayunma'y, kung tumagal ang alipin ng isa o dalawang araw, hindi siya parurusahan; sapagkat siya'y kanyang salapi.
Ngunit sa pagsapit ng gabi, siya'y maliligo sa tubig at kapag lubog na ang araw, ay papasok siya sa kampo.
Pagkatapos, ang Panginoon ay nagsugo ng mga makamandag na ahas sa mga taong-bayan, at tinuklaw ng mga ito ang mga tao, kaya't marami sa Israel ang namatay.
na hindi gaya ni Cain na siya'y sa masama, at pinaslang ang kanyang kapatid. At bakit niya ito pinaslang? Sapagkat ang kanyang mga gawa ay masasama at ang mga gawa ng kanyang kapatid ay matutuwid.
Ako'y nakakaramdam sa inyo ng maka-Diyos na panibugho, sapagkat kayo'y itinakda kong mapangasawa ng isang lalaki, na kayo'y maiharap ko kay Cristo bilang isang malinis na birhen.
At siya'y nangangaral, na nagsasabi, “Dumarating na kasunod ko ang higit na makapangyarihan kaysa akin; hindi ako karapat-dapat yumukod at magkalag ng tali ng kanyang mga sandalyas.
Sinabi sa kanya ni Jacob, “Hindi, nakikiusap ako sa iyo, na kung ngayo'y nakatagpo ako ng biyaya sa iyong paningin, ay tanggapin mo nga ang aking kaloob mula sa aking kamay; sapagkat nakita ko ang iyong mukha, na gaya ng nakakita ng mukha ng Diyos, at ikaw ay nalugod sa akin.
Sumagot si Pablo, “Ako'y Judio, na taga-Tarso sa Cilicia, isang mamamayan ng isang hindi karaniwang lunsod. Nakikiusap ako, pahintulutan mo akong magsalita sa mga taong-bayan.”
at kanyang papagkasunduin ang dalawa sa isang katawan sa Diyos sa pamamagitan ng krus, na sa pamamagitan niyon ay pinatay ang alitan.
Sinabi naman ni Jesus sa kanya, “Dahil sa salitang iyan, makakaalis ka na, lumabas na ang demonyo sa iyong anak.”
Kaya't nagpasugo ang Faraon at ipinatawag si Jose, at madali siyang inilabas sa bilangguan. At nang siya'y makapag-ahit at makapagpalit ng damit ay pumunta sa Faraon.
Siya'y mananatiling marumi hangga't nasa kanya ang karamdaman; siya'y marumi. Siya ay maninirahang mag-isa sa labas ng kampo.
Sino sa inyo na dahil sa pagkabalisa ay mapapahaba ang kanyang buhay?
Pagkatapos ng mga bagay na ito, ang katiwala ng kopa ng hari at ang kanyang panadero ay nagkasala laban sa kanilang panginoon na hari ng Ehipto.
Subalit kung sabihin ng alipin iyon sa kanyang sarili, ‘Matatagalan pa ang pagdating ng aking panginoon;’ at pinasimulan niyang bugbugin ang mga aliping lalaki at mga aliping babae; at siya'y kumain, uminom, at naglasing,
“Ako'y nanalangin sa Panginoon nang panahon ding iyon, na sinasabi,
Hinanap siya ni Simon at ng mga kasamahan niya.
“Huwag kang mangangalunya.
Ngunit, mga minamahal, kami ay lubos na naniniwala sa mga mabubuting bagay tungkol sa inyo, at sa mga bagay na may kinalaman sa kaligtasan, bagama't kami ay nagsasalita ng ganito.
Batiin ninyo si Rufo na hinirang sa Panginoon, at ang kanyang ina at ina ko rin.
Sinabi niya sa kanila, “Pakinggan ninyo ngayon itong aking napanaginip.
ako'y natakot sa iyo, sapagkat ikaw ay taong mahigpit, kinukuha mo ang hindi mo itinabi, at ginagapas mo ang hindi mo inihasik.’
Sinabi ng mga lingkod ng Faraon sa kanya, “Hanggang kailan magiging isang bitag sa atin ang taong ito? Hayaan mo nang umalis ang mga taong iyan upang sila'y makapaglingkod sa Panginoon nilang Diyos; hindi mo pa ba nauunawaan na ang Ehipto ay wasak na?”
“Magsalita ka sa mga anak ni Israel at sabihin mo sa kanila: Ito ang mga takdang kapistahan sa Panginoon na inyong ipahahayag bilang mga banal na pagpupulong.
Muli na naman siyang tinanong ng mga Fariseo kung paano siya nagkaroon ng paningin. At sinabi niya sa kanila, “Nilagyan niya ng putik ang aking mga mata, at hinugasan ko, at ako'y nakakita.”
Ang kopa ng Faraon ay nasa aking kamay; at kinuha ko ang mga ubas at aking piniga ang mga ito sa kopa ng Faraon, at ibinigay ko ang kopa sa kamay ng Faraon.”
Bukod dito'y hindi mo kami dinala sa isang lupain na dinadaluyan ng gatas at pulot, ni binigyan mo kami ng manang bukid at mga ubasan. Dudukitin mo ba pati ang mga mata ng mga taong ito? Hindi kami pupunta!”
“At kung ang sinumang lalaki o babae ay mayroong karamdaman sa ulo o sa balbas,
Tinawag ng labindalawa ang buong kapulungan ng mga alagad, at sinabi, “Hindi nararapat na aming pabayaan ang salita ng Diyos, at maglingkod sa mga hapag.
Kaya't pagkatapos tanggapin ang tinapay ay nagmamadali siyang lumabas. Noon ay gabi na.
Sapagkat ang pangako ay para sa inyo at sa inyong mga anak, at sa lahat ng nasa malayo, bawat isa na tinatawag ng Panginoon nating Diyos sa kanya.”
Tumakbo ang isa, binasa ng suka ang isang espongha, inilagay sa isang tungkod, at ipinainom sa kanya na sinasabi, “Pabayaan ninyo; tingnan natin kung darating si Elias upang siya'y ibaba.”
Kung ang isang kaharian ay nagkakabaha-bahagi laban sa kanyang sarili, hindi makakatayo ang kahariang iyon.
At nakita ko ang pitong anghel na nakatayo sa harapan ng Diyos at sila'y binigyan ng pitong trumpeta.
Sapagkat ito ang kalooban ng aking Ama, na ang bawat nakakakita sa Anak at sa kanya'y sumampalataya ay magkaroon ng buhay na walang hanggan, at muli ko siyang bubuhayin sa huling araw.”
At pinatotohanan ng mga apostol na may dakilang kapangyarihan ang pagkabuhay ng Panginoong Jesus at sumakanilang lahat ang dakilang biyaya.
Huwag kayong magpapaningas ng apoy sa lahat ng inyong tinitirhan sa araw ng Sabbath.”
Samantalang siya'y nasa isa sa mga lunsod, may dumating na isang lalaki na punô ng ketong. Nang makita niya si Jesus, lumuhod siya at nakiusap sa kanya, “Panginoon, kung nais mo ay maaari mo akong linisin.”
Sapagkat ang maaaring malaman tungkol sa Diyos ay hayag sa kanila, yamang ito'y ipinahayag ng Diyos sa kanila.
“Kayong matitigas ang ulo at hindi tuli ang puso't mga tainga, kayo'y laging sumasalungat sa Espiritu Santo. Kung ano ang ginawa ng inyong mga ninuno, ay gayundin ang ginagawa ninyo.
Si Jesus ay may gulang na tatlumpung taon nang magsimula sa kanyang gawain. Anak siya (ayon sa ipinalagay) ni Jose, ni Eli,
Sinabi niya, “Dalhin ninyo rito sa akin.”
Siya mismo ay una sa lahat ng mga bagay, at ang lahat ng mga bagay ay nahahawakang sama-sama sa kanya.
At sa oras ng hapunan ay sinugo niya ang kanyang alipin upang sabihin sa mga inanyayahan, ‘Halikayo, sapagkat ang lahat ay handa na.’
Nawa'y bigyan ka ng Diyos ng hamog ng langit, at ng taba ng lupa, at ng saganang trigo at alak.
Sapagkat ang taggutom ay dalawang taon na sa lupain; at limang taon pang hindi magkakaroon ng pagbubukid o pag-aani man.
Iniutos niyang itigil ang karwahe at lumusong si Felipe at ang eunuko sa tubig. At binautismuhan siya ni Felipe.
“Bigkisan ninyo ang inyong mga baywang at paliwanagin ninyo ang inyong mga ilawan.
Ang aming mga bata, mga asawa, kawan at buong bakahan ay mananatili riyan sa mga bayan ng Gilead.
Huwag mong hahanapin ang kanilang kapayapaan o ang kanilang pag-unlad sa lahat ng iyong mga araw magpakailanman.
Pagkatapos nito, si Jesus ay dinala ng Espiritu Santo sa ilang upang tuksuhin ng diyablo.
Sila'y lumabas sa atin, ngunit sila'y hindi sa atin; sapagkat kung sila'y kabilang sa atin ay magpapatuloy sana silang kasama natin. Ngunit sa paglabas nila ay ginawa nilang maliwanag na silang lahat ay hindi kabilang sa atin.
Sapagkat mula sa inyo'y umalingawngaw ang salita ng Panginoon, hindi lamang sa Macedonia at Acaia, kundi sa lahat ng dako ay napabalita ang inyong pananampalataya sa Diyos; kaya't kami ay hindi na kailangang magsalita pa ng anuman.
Ang halimaw ay binigyan ng isang bibig na nagsasalita ng mga palalong bagay at ng mga kalapastanganan, at pinahintulutan siyang gumamit ng kapangyarihan sa loob ng apatnapu't dalawang buwan.
Tapusin mo ang linggong ito, at ibibigay rin namin sa iyo ang isa, bilang kapalit sa paglilingkod na gagawin mo sa akin na pitong taon pa.”
At kinuha ng anghel ang lalagyan ng insenso at pinuno niya ng apoy ng dambana, itinapon niya sa lupa at nagkaroon ng mga kulog, mga tunog, mga kidlat, at ng lindol.
Tayo'y itinalaga sa pagkukupkop upang maging kanyang mga anak sa pamamagitan ni Jesu-Cristo, ayon sa kabutihan ng kanyang kalooban,
Sapagkat ang Diyos ang nagsabi, “Magningning ang ilaw sa kadiliman,” na siyang tumatanglaw sa aming mga puso upang magbigay-liwanag sa pagkakilala sa kaluwalhatian ng Diyos sa mukha ni Jesu-Cristo.
Sumagot sa kanya si Felipe, “Hindi magkakasiya sa kanila ang dalawang daang denariong tinapay, upang makakain ng kaunti ang bawat isa.”
Maghahandog si Aaron sa ibabaw niyon ng mababangong insenso, tuwing umaga kapag kanyang inaayos ang mga ilaw, ay ihahandog niya iyon,
Sinabi sa kanila ni Pilato, “At anong gagawin ko kay Jesus na tinatawag na Cristo?” Sinabi nilang lahat, “Ipako siya sa krus!”
Nang makasakay si Jesus sa bangka, sumunod sa kanya ang kanyang mga alagad.
Nang makaraan ang may isang oras, may isa pa na nagpipilit na nagsasabi, “Tiyak na ang taong ito'y kasama rin niya, sapagkat siya'y taga-Galilea.”
Pararamihin ko ang iyong binhi na gaya ng mga bituin sa langit at ibibigay ko sa iyong binhi ang lahat ng lupaing ito at pagpapalain ang lahat ng bansa sa lupa sa pamamagitan ng iyong binhi,
At kapag ang isang tao ay naghandog sa Panginoon ng handog pangkapayapaan, sa pagtupad ng isang panata o kaya'y kusang-loob na handog mula sa bakahan o sa kawan, ito ay kailangang sakdal upang matanggap; ito ay kailangang walang kapintasan.
Inilibing siya ng kanyang mga anak na sina Isaac at Ismael sa yungib ng Macpela, sa parang ni Efron na anak ni Zohar na Heteo, na nasa tapat ng Mamre,
samakatuwid ay lahat ng iniutos ng Panginoon sa inyo sa pamamagitan ni Moises, mula sa araw na binigyan kayo ng Panginoon ng utos at mula noon, sa buong panahon ng inyong mga salinlahi;
Ang mga naging araw ni Isaac ay isandaan at walumpung taon.
Sa utos ng Panginoon ay nagkakampo sila, at sa utos ng Panginoon ay naglalakbay sila. Kanilang sinunod ang bilin ng Panginoon , ang utos ng Panginoon sa pamamagitan ni Moises.
Ang bayan ay nagsalita laban sa Diyos at laban kay Moises, “Bakit ninyo kami iniahon mula sa Ehipto, upang mamatay sa ilang? Sapagkat walang pagkain at walang tubig at ang kaluluwa namin ay nasusuya na sa walang kuwentang pagkaing ito.”
Gagawin niya sa toro kung paano ang ginawa niya sa torong handog pangkasalanan, gayundin ang gagawin niya rito. Ang pari ay gagawa ng pagtubos para sa kanila, at sila ay patatawarin.
Ang laman at balat ay sinunog niya sa apoy sa labas ng kampo.
Ang Panginoon ninyong Diyos, na nangunguna sa inyo ay siyang makikipaglaban para sa inyo, gaya ng kanyang ginawa para sa inyo sa Ehipto sa inyong harapan,
At ang nasa bukid ay huwag nang bumalik upang kunin ang kanyang balabal.
Sapagkat dito kami ay dumaraing, na nasasabik mabihisan ng aming makalangit na tahanan,
Ito ang mga anak ni Ismael, at ito ang kanya-kanyang pangalan, ayon sa kanya-kanyang nayon, at ayon sa kanya-kanyang kampo; labindalawang pinuno ayon sa kanilang bansa.
Sapagkat marami ang darating sa aking pangalan, na nagsasabi, ‘Ako ang Cristo’ at ililigaw nila ang marami.
Kailangan dito ang karunungan: ang may pang-unawa ay bilangin ang bilang ng halimaw, sapagkat ito'y bilang ng isang tao. Ang bilang nito ay animnaraan at animnapu't anim.
At nais namin na ang bawat isa sa inyo ay magpakita ng gayunding sigasig upang inyong malaman ang ganap na katiyakan ng pag-asa hanggang sa katapusan;
Kinagabihan, sila'y nagpangkat-pangkat laban sa kaaway, siya at ang kanyang mga alipin, at sila'y kanilang ginapi at hinabol sila hanggang sa Hoba na nasa hilaga ng Damasco.
at ako'y laging lalakad sa gitna ninyo. Ako'y magiging inyong Diyos, at kayo'y magiging aking bayan.
tulad sa nalulungkot, gayunma'y laging nagagalak; tulad sa mga dukha, gayunma'y pinayayaman ang marami, gaya ng walang pag-aari, gayunma'y mayroon ng lahat ng bagay.
Habang sila'y nagtataka tungkol dito, biglang may dalawang lalaki na nakasisilaw ang mga damit ang tumayo sa tabi nila.
At may panganib na hindi lamang mawalan ng dangal ang hanapbuhay nating ito, kundi ang templo ng dakilang diyosang si Artemis ay mawalan din ng halaga. At siya ay maaari pang matanggal sa kanyang kadakilaan, siya na sinasamba ng buong Asia at ng sanlibutan.”
Samantalang sinisikap nilang patayin siya, dumating ang balita sa pinunong kapitan ng mga kawal na ang buong Jerusalem ay nagkakagulo.
ng iyong hayupan at ng mababangis na hayop na nasa iyong lupain. Lahat ng bunga niyon ay magiging inyong pagkain.
Kaya't sila'y kumuha ng abo sa hurno, at tumayo sa harap ni Faraon. Isinaboy ito ni Moises sa himpapawid at naging pigsang sumusugat sa tao at sa hayop.
Haring Agripa, naniniwala ka ba sa mga propeta? Nalalaman kong naniniwala ka.”
Sinabi ni Moises, “Pagkaalis ko sa harapan mo ay aking hihilingin sa Panginoon na bukas ay umalis ang mga pulu-pulutong na langaw mula sa Faraon, sa kanyang mga lingkod, at sa kanyang bayan; ngunit huwag nang mandaya pang muli ang Faraon sa hindi pagpayag na humayo ang bayan upang maghandog sa Panginoon .”
At sinasabi ko sa inyo, mula ngayon ay hindi na ako iinom ng katas ng ubas na ito hanggang sa araw na iyon na iinumin kong panibago na kasalo kayo sa kaharian ng aking Ama.”
at sinabi sa akin, ‘Palalaguin at pararamihin kita, at gagawin kitang isang kapisanan ng mga bayan; at ibibigay ko ang lupaing ito sa iyong binhi pagkamatay mo, bilang isang pag-aari magpakailanman.’
Ngunit marami sa mga nakarinig ang sumampalataya; at ang bilang nila ay mga limang libo.
Kanyang isinama sina Pedro, Santiago at Juan, at nagsimula siyang malungkot at mabagabag.
Ako'y bababa at makikipag-usap sa iyo doon; at ako'y kukuha ng espiritu na nasa iyo at aking isasalin sa kanila. Kanilang dadalhin ang pasanin ng bayan na kasama mo, upang huwag mong dalhing mag-isa.
Nang malapit na ang panahon ng pamumunga, sinugo niya ang kanyang mga alipin sa mga magsasaka upang kunin ang mga bunga nito.
Siya ang kaningningan ng kaluwalhatian ng Diyos at tunay na larawan ng kanyang likas, at kanyang inaalalayan ang lahat ng bagay sa pamamagitan ng kapangyarihan ng kanyang salita. Nang magawa na niya ang paglilinis ng mga kasalanan, siya ay umupo sa kanan ng Kamahalan sa kaitaasan,
At bigla na lamang sa kanilang sinagoga ay may isang tao na may masamang espiritu; at siya'y sumigaw,
Ngunit sumagot si Pedro at ang mga apostol, “Kailangang sa Diyos kami sumunod, sa halip na sa mga tao.
Ngunit sa mga anak ni Kohat ay wala siyang ibinigay, sapagkat iniatas sa kanila ang pangangalaga sa mga banal na bagay na kailangang pasanin sa kanilang mga balikat.
At nang siya'y nakaupo sa hapag-kainan sa bahay ni Levi, maraming maniningil ng buwis at mga makasalanan ang nakaupong kasalo ni Jesus at ng kanyang mga alagad sapagkat marami silang sumunod sa kanya.
At tinipon ni Kora ang buong kapulungan laban sa kanila sa pintuan ng toldang tipanan, at ang kaluwalhatian ng Panginoon ay nagpakita sa buong kapulungan.
Sinabi naman ni Israel, “Bakit ninyo ako ginawan ng ganitong kasamaan, na inyong sinabi sa lalaki na mayroon pa kayong ibang kapatid?”
At ang mga tandang ito ay tataglayin ng mga nananampalataya: sa paggamit ng aking pangalan ay magpapalayas sila ng mga demonyo, magsasalita sila ng mga bagong wika;
Nang mag-uumaga na, hinimok silang lahat ni Pablo na kumain, na sinasabi, “Ang araw na ito ang ikalabing-apat na araw na kayo'y naghihintay na walang kinakaing anuman.
o gumagamit ng anting-anting, o nagpapagamit sa masasamang espiritu, o salamangkero, o sumasangguni sa mga patay.
Nang sila'y makalabas na sa bayan, at hindi pa sila nakakalayo, sinabi ni Jose sa katiwala ng kanyang bahay, “Bumangon ka, habulin mo ang mga lalaki, at kapag sila'y inabutan mo, ay sabihin mo sa kanila, ‘Bakit ginantihan ninyo ng kasamaan ang kabutihan? Bakit ninyo ninakaw ang aking kopang pilak?
Nang isa pang Sabbath, siya'y pumasok sa sinagoga at nagturo. Doon ay may isang lalaki na tuyo ang kanang kamay.
Mag-aalay ang pari ng handog pangkasalanan, at itutubos sa kanya na lilinisin mula sa kanyang karumihan. Pagkatapos ay papatayin niya ang handog na sinusunog,
Huwag ninyong gantihan ng masama ang masama, o ng pag-alipusta ang pag-alipusta, kundi ng pagpapala; sapagkat ukol dito kayo'y tinawag, upang kayo'y magmana ng pagpapala.
at nakakaalam ng kanyang kalooban, at sumasang-ayon sa mga bagay na magagaling, palibhasa'y naturuan ka ng kautusan,
At huwag kayong kakain ng anumang dugo maging ng ibon o ng hayop, sa lahat ng inyong tahanan.
Kung ang isang sinungaling na saksi ay tumindig laban sa kanino man upang sumaksi laban sa kanya tungkol sa isang masamang gawa,
Ipinahayag ng Panginoon sa araw na ito na ikaw ay isang sambayanan na kanyang sariling pag-aari, gaya ng ipinangako niya sa iyo, na iyong tutuparin ang lahat ng kanyang utos,
Huwag kang makikipagtipan sa kanila, ni sa kanilang mga diyus-diyosan.
Ngunit ang panganay ng baka, o ang panganay ng tupa, o ang panganay ng kambing ay huwag mong tutubusin; banal ang mga iyon. Iyong iwiwisik ang kanilang dugo sa ibabaw ng dambana, at iyong susunugin ang kanilang taba bilang handog na pinaraan sa apoy, na mabangong samyo para sa Panginoon .
Nang nakita niya sina Pedro at Juan na papasok sa templo, humingi siya ng limos.
Ako'y nakatayo sa tabi ng balon ng tubig at ang mga anak na babae ng mga tao sa bayan ay darating upang umigib ng tubig.
Ano nga ang ating sasabihin na natuklasan ni Abraham na ating ninuno ayon sa laman?
Lumapit siya at hinawakan ang babae sa kamay at siya'y ibinangon. Nawala ang kanyang lagnat at siya'y naglingkod sa kanila.
Sinabi ni Jesus, “Sino ang humawak sa akin?” Nang tumatanggi ang lahat, sinabi ni Pedro, “Guro, pinapalibutan ka at sinisiksik ng napakaraming tao.”
Nang sa lupa ay wala pang tanim sa parang, at wala pang damo na tumutubo sa parang,—sapagkat hindi pa nagpapaulan ang Panginoong Diyos sa lupa at wala pang taong nagbubungkal ng lupa,
Tunay na sinasabi ko sa inyo, ang sinumang hindi tumanggap sa kaharian ng Diyos na tulad sa isang maliit na bata, ay hindi makakapasok doon.”
at isang ikasampung bahagi ng piling harina na hinaluan ng langis bilang handog na butil para sa bawat kordero; handog na sinusunog na mabangong samyo, handog sa Panginoon na pinaraan sa apoy.
Sapagkat ang mga natutulog ay natutulog sa gabi; at ang naglalasing ay naglalasing sa gabi.
Pagkatapos ay sinabi niya sa kanila, “Babangon ang isang bansa laban sa bansa at ang isang kaharian laban sa kaharian.
“Ang kaharian ng langit ay tulad sa isang hari na nagdaos ng isang handaan para sa kasal ng kanyang anak na lalaki.
Ngunit bawat butil na handog na tuyo o hinaluan ng langis ay pantay-pantay na paghahatian ng lahat ng anak ni Aaron.
At sinabi niya sa kanila, “Hindi ukol sa inyo na malaman ang mga oras o ang mga panahon na itinakda ng Ama sa pamamagitan ng kanyang sariling awtoridad.
Nagsikap siyang makita kung sino si Jesus, subalit hindi magawa dahil sa karamihan ng mga tao, sapagkat siya'y pandak.
Ngunit kanyang sinabi, “Hindi iyon ingay ng sigaw ng pagtatagumpay, o ingay man ng sigaw ng pagkatalo, kundi ingay ng mga umaawit ang aking naririnig.”
Nagsalita ang Panginoon kay Moises at kay Aaron, na sinasabi,
Unang namatay si Haran kaysa sa kanyang amang si Terah sa lupaing kanyang tinubuan, sa Ur ng mga Caldeo.
sapagkat mabilis at tiyak na isasagawa ng Panginoon ang kanyang salita sa lupa.”
Kaya't pagkaraan ng sampung taong paninirahan ni Abram sa lupain ng Canaan, kinuha ni Sarai na asawa ni Abram si Hagar na taga-Ehipto, na kanyang alila, at ibinigay kay Abram na kanyang asawa upang maging asawa niya.
At doo'y sinalubong sila ni Jesus, na nagsasabi, “Kapayapaan ay sumainyo.” At paglapit nila sa kanya ay niyakap ang kanyang mga paa at siya'y sinamba.
At isaalang-alang ninyo sa araw na ito, sapagkat hindi ako nagsasalita sa inyong mga anak (na hindi nakakakilala, at hindi nakakita ng parusa ng Panginoon ninyong Diyos), ng kanyang kadakilaan, ng kanyang makapangyarihang kamay at ng kanyang unat na bisig,
Kayo'y bibili ng pagkain sa kanila sa pamamagitan ng salapi upang kayo'y makakain; at kayo'y bibili rin sa kanila ng tubig sa pamamagitan ng salapi upang kayo'y makainom.
Ang nalabing langis na nasa kamay ng pari ay ilalagay niya sa ulo ng taong lilinisin, upang ipantubos sa kanya sa harapan ng Panginoon .
mga balat ng tupang lalaki na kinulayan ng pula, mga balat ng kambing; at kahoy na akasya,
“Gumawa ka ng dalawang trumpetang pilak; gagawin mo mula sa pinitpit na pilak at iyong gagamitin sa pagtawag sa kapulungan, at kapag kakalasin na ang mga tolda.
at si Judas na anak ni Santiago, at si Judas Iscariote na naging taksil.
at nakita niyang bumukas ang langit, at may isang bagay na bumababa, tulad ng isang malapad na kumot na ibinababa sa lupa na nakabitin sa apat na sulok.
Ang pangalan ng una ay Pishon na siyang umaagos sa palibot ng buong lupain ng Havila, na doo'y may ginto;
At si Isaias ay buong tapang na nagsasabi, “Ako'y natagpuan nila na mga hindi humahanap sa akin; ako'y nahayag sa kanila na hindi nagtatanong tungkol sa akin.”
na isinisigaw, “Mga lalaking taga-Israel, tumulong kayo! Ito ang taong nagtuturo sa mga tao sa lahat ng dako laban sa sambayanan, sa kautusan, at sa dakong ito; at bukod pa rito'y nagdala rin siya ng mga Griyego sa templo, at dinungisan ang banal na lugar na ito.”
Hindi pa ba ninyo nababasa ang kasulatang ito: ‘Ang batong itinakuwil ng mga nagtayo ng gusali, ay siyang naging batong panulukan.
Kung paanong ang katotohanan ni Cristo ay nasa akin, walang makakapigil sa akin sa pagmamalaking ito sa mga lupain ng Acaia.
Siya'y ginawa mong mababa kaysa mga anghel nang sandaling panahon; siya'y pinutungan mo ng kaluwalhatian at ng karangalan, at siya'y inilagay mo sa ibabaw ng mga gawa ng iyong mga kamay.
Kaya't yamang tayo'y inaring-ganap sa pamamagitan ng pananampalataya, mayroon tayong kapayapaan sa Diyos sa pamamagitan ng ating Panginoong Jesu-Cristo.
Ang magtagumpay ay bibihisang gayon ng mapuputing damit; at hindi ko kailanman papawiin ang kanyang pangalan sa aklat ng buhay. At ipahahayag ko ang kanyang pangalan sa harapan ng aking Ama, at sa harapan ng kanyang mga anghel.
Nang dumarami ang nagkakatipong mga tao, nagsimula siyang magsalita, “Ang lahing ito'y isang masamang lahi. Ito'y humahanap ng isang tanda, subalit walang tanda na ibibigay dito maliban sa tanda ni Jonas.
At nakita namin doon ang mga Nefilim, ang mga anak ni Anak, na mula sa mga Nefilim; at kami sa aming sariling paningin ay naging parang mga tipaklong, at gayundin kami sa kanilang paningin.”
Pagkatapos nito ay bumaba siya sa Capernaum, kasama ang kanyang ina, mga kapatid, at ang kanyang mga alagad. Sila'y tumigil doon nang ilang araw.
Ngunit kami ay maghahandang lumaban upang magpauna sa mga anak ni Israel hanggang sa aming madala sila sa kanilang lugar; at ang aming mga bata ay maninirahan sa mga bayang may pader dahil sa mga naninirahan sa lupain.
Subalit batid ni Jesus ang kanilang mga iniisip at sinabi sa kanila, “Bakit ninyo ito pinag-aalinlanganan sa inyong mga puso?
Ngunit sumagot siya at sinabi, “Ang bawat halamang hindi itinanim ng aking Ama na nasa langit ay bubunutin.
Kaya't kanilang pinasama si Rebecca na kanilang kapatid at ang kanyang tagapag-alaga kasama ang alipin ni Abraham at ang kanyang mga tauhan.
Subalit kung ang babae ay ayaw sumama sa iyo, ikaw ay magiging malaya sa aking sumpa; huwag mo lamang pabalikin ang aking anak doon.”
Ako ang Panginoon ninyong Diyos, na naglabas sa inyo sa lupain ng Ehipto, upang ibigay sa inyo ang lupain ng Canaan at maging inyong Diyos.
Kanilang dinalang buháy ang binata, at lubusan silang naaliw.
mabubuhay ka sa pamamagitan ng iyong tabak at maglilingkod ka sa iyong kapatid, at kapag ikaw ay lumaban, babaliin mo ang kanyang pamatok na nasa iyong leeg.”
“Anim na araw na gagawa ka, ngunit sa ikapitong araw ay magpapahinga ka; sa panahon ng pagbubungkal at sa pag-aani ay magpapahinga ka.
Subalit kung italaga niya ang kanyang bukid pagkatapos ng pagdiriwang, bibilangin sa kanya ng pari ang salapi ayon sa mga taong natitira hanggang sa taon ng pagdiriwang at ito ay ibabawas sa iyong inihalaga.
Ito ang batas tungkol sa hayop, sa ibon, at sa lahat na may buhay na gumagalaw na nasa tubig, at sa lahat ng nilikha na umuusad sa ibabaw ng lupa,
At walang sinumang matapos uminom ng alak na laon ay magnanais ng bago, sapagkat sinasabi niya, ‘Masarap ang laon.’”
at pagkatapos ay sa dakong pipiliin ng Panginoon ninyong Diyos na patatahanan sa kanyang pangalan ay doon ninyo dadalhin ang lahat na aking ipinag-uutos sa inyo: ang inyong mga handog na sinusunog, mga alay, mga ikasampung bahagi, ang handog na iwinawagayway ng inyong kamay, at ang lahat ng inyong ipinangakong handog na inyong ipinanata sa Panginoon .
Ngayong nilinis na ninyo ang inyong mga kaluluwa sa pamamagitan ng inyong pagsunod sa katotohanan, kaya't kayo'y may tunay na pag-ibig sa isa't isa, mag-ibigan kayo sa isa't isa nang buong alab mula sa dalisay na puso.
Kukunin mo sa kanilang mga kamay ang mga ito, at iyong susunugin sa dambana bilang karagdagan sa handog na sinusunog, bilang isang mabangong samyo sa harapan ng Panginoon ; ito ay handog sa Panginoon na pinaraan sa apoy.
ngunit ang Diyos na sumisiyasat ng mga puso ay nakakaalam kung ano ang kaisipan ng Espiritu, sapagkat siya ang namamagitan dahil sa mga banal ayon sa kalooban ng Diyos.
Mga mangangalunya! Hindi ba ninyo nalalaman na ang pakikipagkaibigan sa sanlibutan ay pakikipag-away sa Diyos? Kaya't sinumang nagnanais na maging kaibigan ng sanlibutan ay nagiging kaaway ng Diyos.
“Kung ang kanyang alay ay isang handog na sinusunog mula sa bakahan, mag-aalay siya ng isang lalaking walang kapintasan. Ito ay kanyang dadalhin sa pintuan ng toldang tipanan, upang siya ay tanggapin sa harapan ng Panginoon .
Nang si Abram ay siyamnapu't siyam na taon, ang Panginoon ay nagpakita kay Abram, at sa kanya'y nagsabi, “Ako ang Diyos na Makapangyarihan sa lahat! Lumakad ka sa harapan ko, at maging walang kapintasan;
Nang marinig nila ito, pumasok sila sa templo nang magmamadaling-araw, at nagturo. Nang dumating ang pinakapunong pari at ang mga kasamahan niya, pinulong nila ang Sanhedrin at ang buong kapulungan ng matatanda ng mga anak ng Israel, at nagpadala ng utos sa bilangguan upang sila'y dalhin doon.
May sakit ba ang sinuman sa inyo? Ipatawag niya ang matatanda ng iglesya, at kanilang ipanalangin siya, at siya'y pahiran nila ng langis sa pangalan ng Panginoon.
Sinabi ni Balaam kay Balak, “Ngayon, ako'y naparito sa iyo. Mayroon ba ako ngayong anumang kapangyarihan na makapagsalita ng anumang bagay? Ang salitang inilagay ng Diyos sa aking bibig ang aking sasabihin.”
Nang unang araw ng ikalabing-isang buwan ng ikaapatnapung taon, nagsalita si Moises sa mga anak ni Israel ayon sa lahat ng iniutos ng Panginoon sa kanya para sa kanila.
Sapagkat ang Anak ng Tao ay patungo ayon sa itinakda, subalit kahabag-habag ang taong nagkakanulo sa kanya!”
Sinabi ng Diyos kay Abraham, “Huwag kang magdamdam ng dahil sa bata at dahil sa iyong aliping babae. Makinig ka sa lahat ng sasabihin sa iyo ni Sara sapagkat sa pamamagitan ni Isaac papangalanan ang iyong binhi.
At ngayon, Ama, luwalhatiin mo ako sa iyong harapan ng kaluwalhatiang aking tinaglay sa harapan mo bago nagkaroon ng sanlibutan.
Pagkatapos, dinala nila ang batang asno kay Jesus at inilagay nila sa ibabaw ng batang asno ang kanilang mga balabal at siya'y sumakay rito.
Tumakbo sila sa palibot ng buong lupaing iyon at pinasimulan nilang dalhin ang mga maysakit na nasa kanilang higaan, saanman nila mabalitaan na naroon siya.
Bakit ninyo dinala ang kapulungan ng Panginoon sa ilang na ito upang kami at ang aming mga hayop ay mamatay dito?
sapagkat ito ay pinababanal sa pamamagitan ng salita ng Diyos at ng panalangin.
At kaagad na tinanggap niya ang kanyang paningin at sumunod sa kanya, na niluluwalhati ang Diyos. Nang makita ito ng buong bayan ay nagbigay puri sila sa Diyos.
Sapagkat ang anak kong ito ay patay na, at muling nabuhay; siya'y nawala, at natagpuan.’ At sila'y nagsimulang magdiwang.
Kaya't aking iuunat ang aking kamay at sasaktan ko ang Ehipto sa pamamagitan ng lahat kong kababalaghan na aking gagawin sa gitna niyon at pagkatapos, papahintulutan niya kayong umalis.
At ang pitong anghel na may pitong trumpeta ay naghanda upang hipan ang mga trumpeta.
at pinaghihigantihan ang mga napopoot sa kanya, upang puksain sila. Siya'y hindi magpapaliban kundi kanyang gagantihan sila na napopoot sa kanya.
Lahat ay nagsalita ng mabuti tungkol sa kanya at namangha sa mga mapagpalang salita na lumabas sa kanyang bibig. At sinabi nila, “Hindi ba ito ay anak ni Jose?”
“Ang tumatanggap sa inyo ay tumatanggap sa akin at ang tumatanggap sa akin ay tumatanggap sa nagsugo sa akin.
At kanyang inilagay ang bulwagan sa palibot ng tabernakulo at ng dambana, at iniayos ang tabing ng pintuan ng bulwagan. Gayon tinapos ni Moises ang gawain.
Siya lamang ang walang kamatayan at naninirahan sa liwanag na di-malapitan; na hindi nakita ng sinumang tao, o makikita man. Sumakanya nawa ang karangalan at paghaharing walang hanggan. Amen.
Subalit ayaw ninyong lumapit sa akin upang kayo'y magkaroon ng buhay.
Kung ibinigay sa kanila ng Diyos ang gayunding kaloob na gaya naman ng kanyang ibinigay sa atin nang tayo'y nanampalataya sa Panginoong Jesu-Cristo, sino ba ako na makakahadlang sa Diyos?”
Bibiyakin niya ito sa mga pakpak, ngunit hindi hahatiin. Ito'y susunugin ng pari sa ibabaw ng dambana, sa ibabaw ng kahoy na nasa apoy, bilang isang handog na sinusunog. Ito ay isang handog na pinaraan sa apoy, na isang mabangong samyo sa Panginoon .
At pagkatapos niyon ay pumasok ang mga Levita upang gawin ang kanilang paglilingkod sa toldang tipanan sa harap ni Aaron at ng kanyang mga anak. Kung paano ang iniutos ng Panginoon kay Moises tungkol sa mga Levita ay gayon ang ginawa nila sa kanila.
Nakita ko at narinig ang tinig ng maraming mga anghel sa palibot ng trono at ng mga nilalang na buháy at ng matatanda; at ang bilang nila ay milyun-milyon at libu-libo,
upang magdibuho ng magagandang disenyo, upang gumawa sa ginto, sa pilak, at sa tanso,
Katotohanang sinasabi ko sa inyo, ipagkakatiwala niya sa kanya ang lahat ng kanyang ari-arian.
“Ipararating ng Panginoon sa iyo ang sumpa, ang pagkalito at pagkabigo sa lahat ng iyong gagawin, hanggang sa ikaw ay mabuwal at mapuksa dahil sa kasamaan ng iyong mga gawa, sapagkat pinabayaan mo ako.
Mga munting anak, kayo'y sinusulatan ko sapagkat ipinatawad sa inyo ang inyong mga kasalanan dahil sa kanyang pangalan.
Lumabas si Jesus sa templo at paalis na, nang lumapit sa kanya ang mga alagad niya upang ipakita sa kanya ang mga gusali ng templo.
At sinabi ng Panginoon sa akin, ‘Tumindig ka, bumaba ka agad mula riyan; sapagkat ang iyong bayan na inilabas mo sa Ehipto ay nagpakasama. Sila'y mabilis na lumihis sa daang iniutos ko sa kanila; sila'y gumawa para sa kanila ng isang larawang inanyuan.’
Ako kaya ay nag-aatubili nang naisin kong gawin ito? Ginagawa ko ba ang aking mga panukala na gaya ng taong makasanlibutan, na nagsasabi ng “Oo, oo” at gayundin ng “Hindi, hindi?”
isang malaking tinapay, at isang munting tinapay na may langis, at isang manipis na tinapay sa bakol ng tinapay na walang pampaalsa na nasa harapan ng Panginoon .
Sila'y umahon mula sa Ehipto, at dumating sa lupain ng Canaan, kay Jacob na kanilang ama.
kapag nalaman na ang kasalanang kanilang nagawa, ang kapulungan ay magdadala ng isang guyang toro bilang handog pangkasalanan, at dadalhin ito sa harapan ng toldang tipanan.
Nang lumapit ang mga inupahan nang ikalabing-isang oras, tumanggap ang bawat isa sa kanila ng isang denario.
Ang patuloy na gumagawa ng kasalanan ay sa diyablo; sapagkat buhat pa nang pasimula ay nagkakasala na ang diyablo. Dahil dito, nahayag ang Anak ng Diyos upang wasakin ang mga gawa ng diyablo.
Sa paglalakad ni Jesus sa tabi ng Dagat ng Galilea, nakita niya ang dalawang magkapatid, si Simon na tinatawag na Pedro, at si Andres na kanyang kapatid, na naghuhulog ng lambat sa dagat, sapagkat sila'y mga mangingisda.
Gumawa si Jesus ng marami pang ibang mga tanda sa harapan ng kanyang mga alagad, na hindi naisulat sa aklat na ito.
Kaya't kapag binigyan ka ng Panginoon mong Diyos ng kapahingahan sa lahat ng iyong mga kaaway sa palibot, sa lupain na ibinibigay sa iyo ng Panginoon mong Diyos na pinakamana upang angkinin ay iyong papawiin ang alaala ng Amalek sa ilalim ng langit; huwag mong kakalimutan.
Nang makita ng mga kapatid ni Jose na ang kanilang ama'y patay na, ay kanilang sinabi, “Baka si Jose ay may galit sa atin, at tayo'y tiyak na gantihan sa lahat ng kasamaang ginawa natin sa kanya.”
Ingatan ninyo ang inyong sarili, upang huwag ninyong maiwala ang mga bagay na aming pinagpaguran, kundi upang tumanggap kayo ng lubos na gantimpala.
Sumagot si Nicodemo sa kanya, “Paanong mangyayari ang mga bagay na ito?”
Kung minsan ang ulap ay nananatili mula sa hapon hanggang sa kinaumagahan. Kapag ang ulap ay pumaitaas sa kinaumagahan ay naglalakbay sila. Maging araw o gabi kapag ang ulap ay pumaitaas ay naglalakbay sila.
At kukunin ng pari sa kamay ng babae ang handog na butil tungkol sa paninibugho at kanyang iwawagayway ang handog na butil sa harap ng Panginoon , at dadalhin ito sa dambana.
At ibig nila ang pangunahing upuan sa mga sinagoga at ang mga upuang pandangal sa mga handaan.
sa ikalawang hanay ay esmeralda, zafiro, at diamante;
Ako'y biglang nasa Espiritu, at doon sa langit ay may isang tronong nakalagay at sa trono ay may isang nakaupo.
Sapagkat ang kabayaran ng kasalanan ay kamatayan; ngunit ang kaloob ng Diyos na walang bayad ay buhay na walang hanggan kay Cristo Jesus na Panginoon natin.
At nagsalita ang Panginoon kay Moises, na sinasabi,
gayunma'y mawawasak ang Cain. Gaano katagal na bibihagin ka ng Ashur?”
Purihin ang Diyos at Ama ng ating Panginoong Jesu-Cristo! Sa pamamagitan ng kanyang malaking kahabagan ay muli tayong ipinanganak sa isang buháy na pag-asa sa pamamagitan ng muling pagkabuhay ni Jesu-Cristo mula sa mga patay,
At kung si Satanas ay nahahati rin laban sa kanyang sarili, paanong tatatag ang kanyang kaharian? Sapagkat sinasabi ninyong nagpapalayas ako ng mga demonyo sa pamamagitan ni Beelzebul.
Sapagkat kilala natin ang nagsabi, “Akin ang paghihiganti, ako ang gaganti.” At muli, “Huhukuman ng Panginoon ang kanyang bayan.”
Ngunit sa mga bayan ng mga taong ito na ibinibigay sa iyo ng Panginoon mong Diyos bilang pamana ay huwag kang magtitira ng may buhay sa anumang bagay na humihinga.
Inilabas kami ng Panginoon sa Ehipto ng kamay na makapangyarihan, ng unat na bisig, ng malaking pagkasindak, ng mga tanda, at ng mga kababalaghan;
Ito ang mga anak ni Shutela: kay Heran, ang angkan ng mga Heranita.
Ang magtagumpay ay gagawin kong haligi sa templo ng aking Diyos, at hindi na siya lalabas pa roon, at isusulat ko sa kanya ang pangalan ng aking Diyos, at ang pangalan ng lunsod ng aking Diyos, ang bagong Jerusalem, na bumababa buhat sa langit, mula sa aking Diyos, at ang aking sariling bagong pangalan.
Kapag tumayo na ang may-ari ng bahay at maisara na ang pinto, magsisimula kayong tumayo sa labas at tutuktok sa pintuan, na magsasabi, ‘Panginoon, pagbuksan mo kami.’ At siya'y sasagot sa inyo, ‘Hindi ko alam kung saan kayo nanggaling.’
Sapagkat sa pagkabuhay nilang muli mula sa mga patay, hindi na sila mag-aasawa, o pag-aasawahin pa; kundi tulad sila ng mga anghel sa langit.
Nang sila'y makasagwan na ng may lima hanggang anim na kilometro ay kanilang nakita si Jesus na lumalakad sa ibabaw ng dagat at papalapit sa bangka. Sila'y natakot,
Binabati kayo ng babaing nasa Babilonia, na kasama ninyong hinirang, at ni Marcos na aking anak.
Sinabi niya, “Katotohanang sinasabi ko sa inyo, malibang kayo'y magbago at maging tulad sa mga bata, kailanma'y hindi kayo makakapasok sa kaharian ng langit.
At siya'y sumigaw nang may malakas na tinig na nagsasabi, “Bumagsak, bumagsak ang dakilang Babilonia! Ito'y naging tirahan ng mga demonyo, pugad ng bawat espiritung karumaldumal, at pugad ng bawat karumaldumal at kasuklamsuklam na mga ibon;
Sumagot sa kanila si Jesus, “Hindi ba pinili ko kayo, ang labindalawa, at ang isa sa inyo ay diyablo?”
Maghanda ka sa kinaumagahan, at umakyat ka kinaumagahan sa bundok ng Sinai at humarap ka sa akin doon sa tuktok ng bundok.
Ito ang mga pangalan ng mga anak ni Ismael, ayon sa pagkakasunud-sunod ng kanilang kapanganakan: ang panganay ni Ismael ay si Nebayot, pagkatapos ay sina Kedar, Adbeel, Mibsam,
Si Zacarias na kanyang ama ay napuno ng Espiritu Santo at sinabi ang propesiyang ito,
Yamang hindi maikakaila ang mga bagay na ito, dapat kayong huminahon at huwag gumawa ng anumang bagay na padalus-dalos.
Huwag kayong umahon, baka kayo'y masaktan sa harap ng mga kaaway, sapagkat ang Panginoon ay hindi ninyo kasama.
Huwag kayong makipaglaban sa kanila, sapagkat hindi ko ibibigay sa inyo ang alinman sa kanilang lupain, kahit na ang tuntungan ng talampakan ng isang paa, sapagkat ibinigay ko na kay Esau ang bundok ng Seir bilang ari-arian.
Ngayon, sa kanya na makakagawa ng higit na sagana kaysa lahat ng ating hinihingi o iniisip, ayon sa kapangyarihang gumagawa sa atin,
Ang nalabi sa butil na handog ay para kay Aaron at sa kanyang mga anak; ito ay kabanal-banalan sa mga handog sa Panginoon na pinaraan sa apoy.
hindi na siya muling makukuha upang maging asawa ng kanyang unang asawa na humiwalay sa kanya, pagkatapos na siya'y marumihan; sapagkat iyo'y karumaldumal sa harapan ng Panginoon . Huwag mong dadalhan ng pagkakasala ang lupain na ibinibigay bilang pamana sa iyo ng Panginoon mong Diyos.
Siyang nagbibigay ng binhi sa manghahasik at ng tinapay bilang pagkain ay siyang magbibigay at magpaparami ng inyong binhi upang ihasik, at magpaparami ng mga bunga ng inyong pagiging matuwid;
Sinabi ng Panginoon kay Abram pagkatapos na humiwalay si Lot sa kanya, “Itaas mo ngayon ang iyong paningin, at tumanaw ka mula sa dakong iyong kinalalagyan, sa dakong hilaga, timog, silangan, at sa kanluran;
At sinabi ng Panginoon sa kanya, “Ito ang lupain na aking ipinangako kina Abraham, Isaac, at Jacob, na sinasabi, ‘Aking ibibigay sa iyong binhi;’ aking ipinakita sa iyo, ngunit hindi ka daraan doon.”
mula sa mga panganay ng mga anak ni Israel kinuha niya ang salapi; isang libo tatlong daan at animnapu't limang siklo, ayon sa siklo ng santuwaryo.
Yamang naghahanap kayo ng katibayan na si Cristo ay nagsasalita sa akin, na siya ay hindi mahina sa pakikitungo sa inyo, kundi makapangyarihan sa inyo.
Kaya't ang pinagsama ng Diyos ay huwag hayaang paghiwalayin ng tao.”
Ang inyong kordero ay walang kapintasan, isang lalaki na isang taong gulang; inyong kukunin ito sa mga tupa o sa mga kambing.
Pagkaraan ng pitong araw, ang tubig ng baha ay umapaw sa lupa.
na sinasabi, “Naganap na ang panahon at malapit na ang kaharian ng Diyos: kayo'y magsisi at manampalataya sa ebanghelyo.”
Nagpakita sa kanya ang isang anghel ng Panginoon na nakatayo sa gawing kanan ng dambana ng insenso.
Tinanong ng pinakapunong pari si Jesus tungkol sa kanyang mga alagad at sa kanyang itinuturo.
At sinabi niya sa kanya, “Ano ang ibig mo?” Sinabi niya sa kanya, “Ipag-utos mo na itong dalawa kong anak ay umupo, ang isa sa iyong kanan, at ang isa sa iyong kaliwa, sa iyong kaharian.”
kaamuan, at pagpipigil sa sarili. Laban sa mga ito ay walang kautusan.
Ngunit ang isa sa kanila, si Caifas na pinakapunong pari nang panahong iyon ay nagsabi sa kanila, “Wala talaga kayong nalalaman.
Huwag mong ililitaw ang kahubaran ng iyong ama, na siyang kahubaran ng iyong ina. Siya'y iyong ina; huwag mong ililitaw ang kanyang kahubaran.
Dinala nila sa mga Fariseo ang lalaki na dating bulag.
Sapagkat ang mga ayon sa laman ay nagtutuon ng kanilang isipan sa mga bagay ng laman; subalit ang mga ayon sa Espiritu ay sa mga bagay ng Espiritu.
Upang maaliw sana ang kanilang mga puso, sa kanilang pagkakaisa sa pag-ibig, at magkaroon ang lahat ng mga kayamanan ng buong katiyakan ng pagkaunawa, at magkaroon ng kaalaman ng hiwaga ng Diyos, na si Cristo,
Tumawag sila upang magtanong kung si Simon, na tinatawag na Pedro, ay nanunuluyan doon.
