Ngunit ang mga nagnanais yumaman ay nahuhulog sa tukso, at nabibitag sa maraming hangal at nakapipinsalang pagnanasa, na siyang naglulubog sa mga tao sa pagkawasak at kapahamakan.
Ito ang unang pagtatala na ginawa nang si Quirinio ay gobernador sa Siria.
Ngunit si Marta ay naaabala sa maraming paglilingkod. Siya'y lumapit sa kanya at sinabi, “Panginoon, wala bang anuman sa iyo na pinabayaan ako ng aking kapatid na maglingkod na mag-isa? Sabihin mo nga sa kanya na tulungan ako.”
Kayong mga bulag! Sapagkat alin ba ang higit na dakila, ang handog o ang dambana na nagpapabanal sa handog?
Pinunit ng pinakapunong pari ang kanyang damit at nagsabi, “Ano pang kailangan nating mga saksi?
Maging sa pamamagitan ng mga pananalitang ito ay bahagya na nilang napigil ang mga tao sa paghahandog sa kanila.
At ang mga Judio ay nakisama rin sa pagsasakdal, na sinasabing ang lahat ng mga ito ay totoo.
“Kung kayo'y kinapopootan ng sanlibutan, ay alamin ninyo na ako muna ang kinapootan nito bago kayo.
At sa pagtingin ni Jesus sa palibot ay sinabi niya sa kanyang mga alagad, “Napakahirap para sa mga may kayamanan na pumasok sa kaharian ng Diyos.”
sapagkat iniwan ako ni Demas, na umibig sa sanlibutang ito, at nagtungo sa Tesalonica; si Crescente ay nagtungo sa Galacia, at si Tito ay sa Dalmacia.
Sinabi ni Pedro kay Jesus, “Rabi, mabuti sa atin ang dumito. Hayaan ninyong gumawa kami ng tatlong kubol; isa sa iyo, isa kay Moises, at isa kay Elias.”
Ngayon kung ang pagkahulog nila ay siyang kayamanan ng sanlibutan, at ang pagkalugi nila ay siyang kayamanan ng mga Hentil, gaano pa kaya ang lubos na panunumbalik nila?
Mga munting anak, huwag kayong padaya kanino man. Ang gumagawa ng katuwiran ay matuwid, gaya niya na matuwid.
Si Jesus ay muling nagsalita sa kanila sa mga talinghaga, na sinasabi,
Nang madaling-araw na ay lumapit siya sa kanila na lumalakad sa ibabaw ng dagat.
Ang bahagi ng kasulatan na binabasa niya ay ito:
Ang lahat ng mga alituntuning ito ay masisira sa paggamit, palibhasa'y mga utos at mga aral lamang ng mga tao.
Sinagot sila ni Jesus, “Maraming mabubuting gawa mula sa Ama ang ipinakita ko sa inyo. Alin sa mga gawang iyon ang dahilan at babatuhin ninyo ako?”
Umupo ang patay at nagpasimulang magsalita. At siya'y ibinigay ni Jesus sa kanyang ina.
ay sinabi nila sa kanya, “Guro, nahuli ang babaing ito sa akto ng pangangalunya.
“Kahabag-habag kayo, mga eskriba at mga Fariseo, mga mapagkunwari! Sapagkat nag-iikapu kayo ng yerbabuena, ng anis at ng komino, at inyong pinababayaan ang higit na mahahalagang bagay ng kautusan: ang katarungan, ang habag, at ang pananampalataya. Subalit dapat sana ninyong gawin ang mga ito nang hindi pinababayaan ang iba.
Samantala, si Pedro ay nakaupo sa labas ng bakuran. Lumapit sa kanya ang isang aliping babae, na nagsasabi, “Ikaw ay kasama rin ni Jesus na taga-Galilea.”
Pagkatapos gumugol ng ilang panahon doon, umalis siya at nagpalipat-lipat sa mga lupain ng Galacia at Frigia, na pinapalakas ang lahat ng mga alagad.
Kaya't isinugo ni Jesus sina Pedro at Juan, na sinasabi, “Humayo kayo at ihanda ninyo ang paskuwa para sa atin, upang ating kainin ito.”
Pagkatapos ay tinawag ni Jesus ang kanyang labindalawang alagad, at kanyang binigyan sila ng kapangyarihan sa masasamang espiritu, upang kanilang mapalayas sila at pagalingin nila ang bawat sakit at karamdaman.
Nalalaman ko na ang kanyang utos ay buhay na walang hanggan. Kaya't ang mga bagay na sinasabi ko ay aking sinasabi ayon sa sinabi ng Ama.”
Sapagkat siya'y magiging dakila sa harapan ng Panginoon, at hindi siya iinom ng alak o matapang na inumin. Siya'y mapupuno ng Espiritu Santo mula pa sa sinapupunan ng kanyang ina.
Sapagkat ang pangangasiwa sa paglilingkod na ito ay hindi lamang pumupuno sa pangangailangan ng mga banal, kundi umaapaw rin sa pamamagitan ng maraming pasasalamat sa Diyos.
Mahigpit na iniutos niya sa kanila na huwag nilang sasabihin kaninuman ang tungkol sa kanya.
Sapagkat ang kapangyarihan ng mga kabayo ay nasa kanilang bibig at nasa kanilang mga buntot; ang kanilang mga buntot ay katulad ng mga ahas, na may mga ulo; at sa pamamagitan ng mga ito'y nakakapaminsala sila.
Ngunit sinasabi ko sa inyo, na ang bawat nakikipaghiwalay sa kanyang asawang babae maliban sa pakikiapid, ay nagtutulak sa kanya sa pakikiapid; at ang sinumang mag-asawa sa babaing hiniwalayan ay nagkakasala ng pangangalunya.
ni Simeon, ni Juda, ni Jose, ni Jonam, ni Eliakim,
Sapagkat ang anumang mga bagay na isinulat noong una ay isinulat upang tayo ay matuto, upang sa pamamagitan ng pagtitiyaga at sa pagpapasigla ng mga kasulatan ay magkaroon tayo ng pag-asa.
Huwag mong pagsabihan na may kagaspangan ang nakatatandang lalaki, kundi pakiusapan mo siyang tulad sa isang ama; sa mga kabataang lalaki na tulad sa mga kapatid;
Kundi kayo'y magalak, yamang kayo'y nakikibahagi sa mga pagdurusa ni Cristo, upang kayo man ay matuwa at sumigaw sa galak kapag ang kaluwalhatian niya ay nahayag.
Sumagot naman ito, “Paano nga ba, malibang may tumulong sa akin?” At kanyang inanyayahan si Felipe na umakyat at maupong kasama niya.
Samantala, ang iba ay sumisigaw ng isang bagay, at ang ilan ay iba naman, sapagkat ang kapulungan ay nasa kaguluhan at hindi nalalaman ng karamihan kung bakit sila'y nagkakatipon.
Ngunit inudyukan ng mga punong pari ang taong-bayan na sa halip ay palayain niya si Barabas para sa kanila.
“Dahil sa iyo kami'y pinapatay sa buong araw;
Kaya't maging ang unang tipan ay hindi pinagtibay ng walang dugo.
Kaya't nanikluhod ang kanyang kapwa alipin at nakiusap sa kanya, na nagsasabi, ‘Pagpasensyahan mo ako, at babayaran kita.’
Nang dumaong kami sa Siracusa ay tumigil kami roon ng tatlong araw.
May isang babae na labindalawang taon nang dinudugo,
Ang huli ay gumagawa dahil sa pag-ibig, palibhasa'y nalalaman na ako'y itinalaga sa pagtatanggol sa ebanghelyo;
na nasa nagliliyab na apoy, na magbibigay ng parusa sa mga hindi kumikilala sa Diyos at sa mga hindi sumusunod sa ebanghelyo ng ating Panginoong Jesus.
Nakikita mo na ang pananampalataya ay gumagawang kalakip ng kanyang mga gawa, at ang pananampalataya ay naging ganap sa pamamagitan ng mga gawa.
“Mag-ingat kayo sa mga bulaang propeta, na lumalapit sa inyo na may damit tupa, ngunit sa loob ay mga ganid na asong-gubat.
Anumang sinasabi ko sa inyo sa dilim, sabihin ninyo sa liwanag; at ang narinig ninyo sa bulong ay ipagsigawan ninyo sa ibabaw ng mga bubungan.
Kaya't naunawaan nila na ang sinabi ni Jesus ay hindi sa pampaalsa ng tinapay mag-ingat kundi sa mga aral ng mga Fariseo at Saduceo.
Tingnan ninyo, binigyan ko kayo ng awtoridad na tapakan ang mga ahas at mga alakdan, at sa ibabaw ng lahat ng kapangyarihan ng kaaway; at walang makakapanakit sa inyo.
pagsamba sa diyus-diyosan, pangkukulam, alitan, pagtatalo, paninibugho, pagkagalit, pagkamakasarili, pagkakabaha-bahagi, mga pagkakampi-kampi,
sapagkat ang bumabati sa kanya ay nakikibahagi sa kanyang masasamang gawa.
Pinalapit ni Jesus sa kanya ang mga tao at sinabi sa kanila, “Pakinggan ninyo ito at unawain.
Mula sa binhi ng taong ito, ang Diyos ay nagkaloob ng isang Tagapagligtas sa Israel na si Jesus, gaya ng kanyang ipinangako.
Nang hindi nila ito mailapit sa kanya dahil sa karamihan ng tao, kanilang tinanggal ang bubungan sa tapat ng kanyang kinaroroonan. Nang kanilang mabutas iyon, ibinaba nila ang higaang kinahihigan ng lumpo.
at sila'y magiging bayan niya.
At ang nasa bubungan ay huwag nang bumaba, o pumasok upang maglabas ng anuman sa kanyang bahay.
Tinanong din siya ng mga kawal, “At kami, anong dapat naming gawin?” At sinabi niya sa kanila, “Huwag kayong mangikil ng salapi kaninuman sa pamamagitan ng dahas o maling paratang at masiyahan kayo sa inyong sahod.”
Subalit hindi nila naunawaan ang pananalitang ito at ito'y inilihim sa kanila, upang ito'y hindi nila mabatid. At natakot silang magtanong sa kanya tungkol sa salitang ito.
Sinabi ng mga nakatayo sa malapit, “Nilalait mo ba ang pinakapunong pari ng Diyos?”
Igalang mo ang iyong ama at ang iyong ina; at, Ibigin mo ang iyong kapwa na gaya ng iyong sarili.”
Pagkatapos nito, sapagkat alam ni Jesus na ang lahat ng mga bagay ay naganap na, ay sinabi niya (upang matupad ang kasulatan), “Nauuhaw ako.”
At ipinakita sa akin ng anghel ang isang ilog ng tubig ng buhay, na maningning na gaya ng kristal, na lumalabas mula sa trono ng Diyos at ng Kordero
Samantalang sila'y naroroon, dumating ang panahon ng kanyang panganganak.
Kaya't yamang napapalibutan tayo ng gayong kakapal na bilang ng mga saksi, itabi natin ang bawat pabigat at ang pagkakasalang madaling bumibitag sa atin, at tumakbo tayong may pagtitiis sa takbuhing inilagay sa harapan natin.
Pagdating niya sa pampang, nakita niya ang napakaraming tao. Nahabag siya sa kanila at pinagaling niya ang mga maysakit sa kanila.
Ano nga ang ating sasabihin? May kawalang-katarungan ba sa Diyos? Huwag nawang mangyari.
Nagpakita sa kanya ang isang anghel na mula sa langit na nagpalakas sa kanya.
Nagtalo sila sa isa't isa, “Kung sabihin natin, ‘Mula sa langit’ ay sasabihin niya, ‘Bakit nga hindi ninyo siya pinaniwalaan?’
Ngayon ay nalalaman namin na nalalaman mo ang lahat ng mga bagay, at hindi na kailangang tanungin ka ng sinuman. Dahil dito'y sumasampalataya kami na ikaw ay nagbuhat sa Diyos.”
tulad ng mapapatotohanan ng pinakapunong pari ng tungkol sa akin at ng buong kapulungan ng matatanda. Mula sa kanila'y tumanggap ako ng mga sulat para sa mga kapatid sa Damasco at nagpunta ako roon upang gapusin ang mga naroroon at ibalik sila sa Jerusalem upang parusahan.
subalit sa mga huling araw na ito ay nagsalita siya sa atin sa pamamagitan ng Anak, na kanyang itinalagang tagapagmana ng lahat ng mga bagay, na sa pamamagitan din niya'y ginawa ang mga sanlibutan.
Sapagkat maliwanag na ang ating Panginoon ay nagmula sa Juda at tungkol sa liping iyon ay walang sinabing anuman si Moises tungkol sa mga pari.
Isinusulat namin ang mga bagay na ito upang ang aming kagalakan ay malubos.
Ang may pandinig ay makinig sa sinasabi ng Espiritu sa mga iglesya. Ang magtagumpay ay bibigyan ko ng nakatagong mana, at siya'y bibigyan ko ng isang batong puti, at sa ibabaw ng bato ay may nakasulat na isang bagong pangalan, na walang nakakaalam kundi ang tumatanggap.
Subalit sinabi ni Abraham, ‘Nasa kanila si Moises at ang mga propeta, hayaan mo silang makinig sa kanila.’
Ang taong namatay ay lumabas, na ang mga kamay at mga paa ay natatalian ng mga telang panlibing, at ang kanyang mukha ay may balot na tela. Sinabi sa kanila ni Jesus, “Siya'y inyong kalagan, at hayaan ninyong makaalis.”
Sapagkat ang Diyos ay hindi masama; hindi niya kaliligtaan ang inyong gawa at ang pag-ibig na inyong ipinakita sa kanyang pangalan, sa inyong paglilingkod sa mga banal, gaya ng ginagawa ninyo ngayon.
Gayong si David mismo ang nagsasabi sa aklat ng Mga Awit,
“Huwag kayong magtipon ng mga kayamanan para sa inyong sarili sa lupa, na dito ay naninira ang bukbok at ang kalawang at ang mga magnanakaw ay nakakapasok at nakakapagnakaw;
Kaya't nanatili sila ng mahabang panahon na nagsasalita ng buong katapangan para sa Panginoon, na nagpapatotoo sa salita ng kanyang biyaya sa pamamagitan ng pagkakaloob ng mga tanda at mga kababalaghan na gawin ng kanilang mga kamay.
Sila'y sinidlan ng malaking takot at sinabi sa isa't isa, “Sino nga ito, na pati ang hangin at ang dagat ay sumusunod sa kanya?”
At paglabas niya nang ikatlong oras, nakita niya ang iba sa pamilihan na nakatayong walang ginagawa.
Kung ang sinuman ay nagnanais gumawa ng kalooban ng Diyos ay makikilala niya kung ang turo ay mula sa Diyos, o kung ako'y nagsasalita mula sa aking sarili.
Mula ng panahong iyon ay pinasimulan ni Jesus na ipaliwanag sa kanyang mga alagad na kailangang pumunta siya sa Jerusalem at magtiis ng maraming bagay sa kamay ng matatanda, ng mga punong pari at mga eskriba. Siya'y papatayin at muling bubuhayin sa ikatlong araw.
Sumampalataya kayo sa akin na ako'y nasa Ama at ang Ama ay nasa akin. Subalit kung hindi ay sumampalataya kayo sa akin dahil sa mga gawa.
Natagpuan niya roon ang isang Judio na ang pangalan ay Aquila, isang lalaking tubong Ponto, na kararating pa lamang mula sa Italia, kasama si Priscila na kanyang asawa, sapagkat ipinag-utos ni Claudio na ang lahat ng Judio ay umalis sa Roma. Pumunta si Pablo sa kanila;
at nagbabalak ang mga tao ng mga bagay na walang kabuluhan?
Sinasabi ko sa inyo, nanaog patungo sa kanyang bahay ang taong ito na inaring-ganap sa halip na ang isa. Sapagkat ang bawat nagmamataas sa kanyang sarili ay ibababa, ngunit ang nagpapakababa sa kanyang sarili ay itataas.”
Sapagkat tayong sumasampalataya ay pumapasok sa kapahingahang iyon, gaya ng sinabi ng Diyos,
at sinasabi ninyo, ‘Kung nabuhay sana kami sa mga araw ng aming mga ninuno, hindi kami makikibahagi sa kanila sa dugo ng mga propeta.’
Kaya't pagkatapos ay maliwanag na sinabi sa kanila ni Jesus, “Namatay si Lazaro,
Huwag ninyong kalimutan ang magpatulóy ng mga dayuhan, sapagkat sa paggawa nito ang iba ay nakapagpatulóy na ng mga anghel nang hindi nila namamalayan.
Ngunit ito'y sinabi niya, hindi dahil nagmamalasakit siya sa mga dukha, kundi sapagkat siya'y isang magnanakaw. At palibhasa'y nasa kanya ang supot ay kinukuha niya ang inilalagay doon.
Ang kamatayan at ang Hades ay itinapon sa lawa ng apoy. Ito ang ikalawang kamatayan, ang lawa ng apoy;
Iyon ay isang sagisag ng panahong kasalukuyan, na sa panahong yaon ang mga kaloob at ang mga alay na inihahandog ay hindi makapagpapasakdal sa budhi ng sumasamba,
Nang patapos na ang araw na iyon, lumapit ang labindalawa at sinabi sa kanya, “Paalisin mo ang mga tao upang sila'y makapunta sa mga nayon at sa mga lupaing nasa palibot at makahanap ng matutuluyan at makakain, sapagkat tayo'y narito sa isang ilang na dako.”
at nakalasap ng kabutihan ng salita ng Diyos, at ng mga kapangyarihan ng panahong darating,
Subalit habang pinupulot ng mga punong pari ang mga piraso ng pilak, nagsabi sila, “Hindi matuwid na ilagay ang mga ito sa kabang-yaman, sapagkat dugo ang kapalit ng halagang ito.”
Nang kanilang mailagay na ang mga bilanggo sa gitna nila, sila ay kanilang tinanong, “Sa anong kapangyarihan, o sa anong pangalan ninyo ginawa ito?”
At sinabi sa kanila na huwag pinsalain ang damo sa lupa, ni ang anumang luntian, ni ang anumang punungkahoy, kundi ang mga tao lamang na walang tatak ng Diyos sa kanilang mga noo.
Mula pa nang likhain ang sanlibutan, ang kanyang walang hanggang kapangyarihan at pagka-Diyos, bagaman hindi nakikita, ay naunawaan at nakita sa pamamagitan ng mga bagay na kanyang ginawa, upang wala silang maidadahilan;
At ang Espiritu Santo ay nagpapatotoo rin sa atin, sapagkat pagkatapos niyang sabihin,
Nang makita ni Jesus ang napakaraming tao sa palibot niya, ipinag-utos niyang tumawid sa kabilang pampang.
Sapagkat ang taong iyon ay hindi dapat mag-akala na siya'y tatanggap ng anumang bagay mula sa Panginoon.
Sinabi niya sa kanila, “Ngunit ano ang sinasabi ninyo kung sino ako?”
ang inyong kasaganaan sa kasalukuyang panahon ang magpuno sa kanilang kakulangan, upang ang kanilang kasaganaan ay magpuno sa inyong pangangailangan, upang magkaroon ng pagkakapantay-pantay.
Idinadalangin ko sila. Hindi ang sanlibutan ang idinadalangin ko, kundi para doon sa mga ibinigay mo sa akin, sapagkat sila'y iyo.
Siya'y kanilang tinanong, “Sino ang taong nagsabi sa iyo, ‘Buhatin mo ang iyong higaan at lumakad ka?’”
Ngunit sinagot sila ng masamang espiritu, “Kilala ko si Jesus, at kilala ko si Pablo; ngunit sino kayo?”
Sapagkat ang Anak ng Tao ay naparito upang iligtas ang nawala.]
At si Jesus ay muling lumabas sa tabi ng lawa. Nagtipon sa paligid niya ang napakaraming tao at sila'y kanyang tinuruan.
Kung maghihimagsik si Satanas laban sa kanyang sarili at magkabaha-bahagi, hindi siya makakatayo, kundi siya'y magwawakas.
At si Judas na nagkanulo kay Jesus, nang nakitang hinatulan na ito, ay nagsisi at isinauli ang tatlumpung pirasong pilak sa mga punong pari at sa matatanda,
Sinabi ni Jesus sa kanila, “Hindi ba ninyo kailanman nabasa sa mga kasulatan,
Ngunit silang lahat ay pare-parehong nagsimulang magdahilan. Sinabi ng una sa kanya, ‘Bumili ako ng isang bukid, at kailangan kong umalis at tingnan iyon. Hinihiling ko sa iyo na pagpaumanhinan mo ako.’
Sapagkat batid niya na dahil sa inggit ay ipinadakip siya ng mga punong pari.
Sapagkat ang bawat humihingi ay tumatanggap, at ang humahanap ay nakakatagpo, at ang tumutuktok ay pinagbubuksan.
Ang nagsasabing, “Kilala ko siya,” ngunit hindi tinutupad ang kanyang mga utos, ay sinungaling, at ang katotohanan ay wala sa kanya.
At nang kanyang masabi ito ay sinampal si Jesus ng isa sa mga punong-kawal na nakatayo roon, na nagsasabi, “Ganyan ka bang sumagot sa pinakapunong pari?”
Pagkatapos ay sasagutin siya ng mga matuwid, na nagsasabi, ‘Panginoon, kailan ka namin nakitang gutom, at pinakain ka namin, o uhaw, at binigyan ka ng inumin?
sa pamamagitan ng pagkukunwari ng mga nagsasalita ng mga kasinungalingan, na ang mga budhi ay tinatakan ng nagbabagang bakal.
Sa kanya ang buong gusali ay nakalapat na mabuti at lumalaki tungo sa pagiging isang banal na templo sa Panginoon;
Sapagkat sa aking pagdaraan, at sa pagmamasid ng mga bagay na inyong sinasamba, ay nakatagpo din naman ako ng isang dambana na may sulat na ganito, ‘SA ISANG DI-KILALANG DIYOS.’ Kaya't ang sinasamba ninyo na hindi kilala ay siyang ipahahayag ko sa inyo.
sapagkat sinasabi ko sa inyo, ito'y hindi ko kakainin hanggang sa ito'y ganapin sa kaharian ng Diyos.”
Sumagot si Jesus, “Kung ako ma'y nagpapatotoo tungkol sa aking sarili, ang aking patotoo ay totoo; sapagkat nalalaman ko kung saan ako nanggaling, at kung saan ako pupunta. Subalit hindi ninyo nalalaman kung saan ako nanggaling, o kung saan ako pupunta.
at ang inyong mga kabataang lalaki ay makakakita ng mga pangitain,
Subalit dahil batid ni Jesus ang iniisip ng kanilang puso, kumuha siya ng isang maliit na bata at inilagay sa kanyang tabi.
patungo sa dagat, sa ibayo ng Jordan, Galilea ng mga Hentil—
Pagkatapos ay ipinadala siyang nakagapos ni Anas kay Caifas na pinakapunong pari.
“Mapapalad ang mga pinatatawad sa kanilang mga masasamang gawa,
Siya'y muling nagsugo sa kanila ng isa pang alipin at ito'y kanilang pinalo sa ulo at nilait.
Pagkatapos makipagpulong sa matatanda, nagpanukala sila na magbigay ng sapat na salapi sa mga kawal,
na pumaparitong kasunod ko at hindi ako karapat-dapat magkalag ng panali ng kanyang sandalyas.”
Ito ay upang matupad ang salitang sinabi niya, “Sa mga ibinigay mo sa akin ay wala akong iwinala kahit isa.”
Ito ang aklat ng lahi ni Jesu-Cristo, na anak ni David, na anak ni Abraham.
Ako'y labis na nagalak nang dumating ang mga kapatid at nagpatotoong ikaw ay nasa katotohanan, kung paanong lumalakad ka sa katotohanan.
Subalit ang layunin ng aming tagubilin ay pag-ibig na nagmumula sa malinis na puso at sa mabuting budhi at sa pananampalatayang hindi pakunwari.
“Igalang mo ang iyong ama at ina”—ito ang unang utos na may pangako,
subalit sinabi ni Jesus sa kanya, “Judas, ipinagkakanulo mo ba ang Anak ng Tao sa pamamagitan ng isang halik?”
Tumahimik ang buong kapulungan at kanilang pinakinggan sina Bernabe at Pablo na isinasalaysay ang mga tanda at mga kababalaghang ginawa ng Diyos sa pamamagitan nila sa gitna ng mga Hentil.
At huwag ninyong pighatiin ang Espiritu Santo ng Diyos, na sa pamamagitan niya kayo'y tinatakan para sa araw ng pagtubos.
‘At sa mga huling araw, sabi ng Diyos,
Sapagkat ang aming ebanghelyo ay hindi dumating sa inyo sa salita lamang, kundi sa kapangyarihan din at sa Espiritu Santo at sa lubos na pagtitiwala, kung paanong nalalaman ninyo kung anong pagkatao ang aming pinatunayan sa inyo alang-alang sa inyo.
at kapag ang pagnanasang iyon ay naipaglihi, ito ay nanganganak ng kasalanan, at ang kasalanan kapag malaki na ay nagbubunga ng kamatayan.
Batiin ninyo si Rufo na hinirang sa Panginoon, at ang kanyang ina at ina ko rin.
Ang langit ay nahawi na gaya ng isang balumbong nilululon, at ang bawat bundok at pulo ay naalis sa kanilang kinalalagyan.
At sinabi niya sa kanya, “Ano ang ibig mo?” Sinabi niya sa kanya, “Ipag-utos mo na itong dalawa kong anak ay umupo, ang isa sa iyong kanan, at ang isa sa iyong kaliwa, sa iyong kaharian.”
Sumagot sa kanya ang mga Judio, “Hindi dahil sa mabuting gawa ka namin babatuhin, kundi dahil sa paglapastangan. Sapagkat ikaw, na isang tao, ay nag-aangkin na Diyos.”
na nagpakita sa kaluwalhatian at nag-usap tungkol sa pagpanaw niya na malapit na niyang isakatuparan sa Jerusalem.
o papatayin ang nagbabagang mitsa,
Subalit siya'y nagsasalita tungkol sa templo ng kanyang katawan.
Ako ba ngayo'y naging kaaway ninyo sa pagsasabi ko sa inyo ng katotohanan?
Ngunit hindi nila naunawaan ang kanyang sinabi at natakot silang magtanong sa kanya.
Sapagkat nalalaman ninyo ang biyaya ng ating Panginoong Jesu-Cristo, na bagaman siya'y mayaman, subalit alang-alang sa inyo ay naging dukha, upang sa pamamagitan ng kanyang kadukhaan ay maging mayaman kayo.
(“Masdan ninyo, ako'y dumarating na gaya ng magnanakaw. Mapalad ang nananatiling gising at nakadamit, upang siya'y hindi lumakad na hubad at makita ang kanyang kahihiyan.”)
Mga kapatid, nakikiusap ako sa inyo, kayo'y maging kagaya ko, sapagkat ako'y naging katulad din ninyo. Wala kayong ginawang masama sa akin.
Sumunod kayo at pasakop sa mga namumuno sa inyo, sapagkat sila'y matamang nagbabantay alang-alang sa inyong mga kaluluwa bilang mga mananagot. Hayaang gampanan nila ito na may kagalakan at hindi nang may hapis, sapagkat kung ganito'y hindi ito magiging kapaki-pakinabang sa inyo.
at naglalakad si Jesus sa templo sa portiko ni Solomon.
Kanilang sinabi, “Hinihikayat ng taong ito ang mga tao na sumamba sa Diyos laban sa kautusan.”
Sapagkat nagmumula sa puso ang masasamang pag-iisip, pagpatay, pangangalunya, pakikiapid, pagnanakaw, pagsaksi sa kasinungalingan, at paglapastangan.
Sapagkat ito ang dahilan kung bakit ang ebanghelyo ay ipinangaral maging sa mga patay, upang bagaman sila'y nahatulan sa laman na gaya ng mga tao, ay mabubuhay sila sa espiritu tulad ng Diyos.
Kaya't nang sila'y magkatipon dito, hindi ako nagpaliban kundi nang sumunod na araw ay umupo ako sa hukuman at iniutos kong iharap ang tao.
At sinabi ni Agripa kay Pablo, “Sa maikling panahon ay hinihikayat mo akong maging Cristiano!”
“Sa puno nga ng igos ay pag-aralan ninyo ang talinghaga: kapag nananariwa ang kanyang sanga, at sumusupling ang mga dahon, ay nalalaman ninyo na malapit na ang tag-araw.
Huwag ninyong gawin ang anuman sa pagpapaligsahan o pagmamataas, kundi sa kababaan, ituring na ang iba ay higit na mabuti kaysa inyong sarili.
‘Ikaw ay pari magpakailanman.’”
Nang matikman ng pinuno ng handaan ang tubig na naging alak, at hindi niya alam kung saan ito nanggaling (subalit nalalaman ng mga lingkod na kumuha ng tubig), tinawag ng pinuno ng handaan ang lalaking bagong kasal.
Siya'y nagpakita ng lakas sa pamamagitan ng kanyang bisig;
Si Pablo at si Timoteo, na mga alipin ni Cristo Jesus, sa lahat ng mga banal kay Cristo Jesus na nasa Filipos, kasama ang mga obispo at ang mga diakono:
Nang mapatahimik na ng kalihim ng bayan ang maraming tao, ay kanyang sinabi, “Mga lalaking taga-Efeso, sino sa mga tao ang hindi nakakaalam na ang lunsod ng mga taga-Efeso ay tagapag-ingat ng templo ng dakilang Artemis, at ng banal na batong nahulog mula sa langit?
Nang makaraan ang ilang araw, si Haring Agripa at si Bernice ay dumating sa Cesarea upang batiin si Festo.
Sinabi niya sa kanila, “Bakit ninyo ako hinahanap? Hindi ba ninyo nalalaman na dapat ay nasa bahay ako ng aking Ama?”
At sila'y nag-aawitan ng isang bagong awit sa harapan ng trono, at sa harapan ng apat na nilalang na buháy at ng matatanda. Walang sinumang natuto ng awit na iyon kundi ang isandaan at apatnapu't apat na libo lamang, na tinubos mula sa lupa.
Ito ay nangangahulugang nauunawaan na ang kautusan ay hindi ginawa para sa taong matuwid, kundi para sa mga walang kinikilalang batas at mapaghimagsik, para sa masasama at mga makasalanan, para sa mga hindi banal at lapastangan, para sa mga pumapatay sa ama at sa ina, para sa mga mamamatay-tao,
Bumalik ang mga kawal sa mga punong pari at sa mga Fariseo, at sinabi ng mga ito sa kanila, “Bakit hindi ninyo siya dinakip?”
Ang Panginoon nawa'y sumainyong espiritu. Sumainyo nawa ang biyaya.
Kaya, kung sasabihin nila sa inyo, ‘Tingnan ninyo, siya'y nasa ilang,’ huwag kayong lumabas. ‘Tingnan ninyo, siya'y nasa mga silid,’ huwag ninyong paniwalaan.
ay siyang naging batong panulukan.
Sa ami'y ipinagbilin niya na mangaral sa mga tao at sumaksi na siya ang itinalaga ng Diyos na maging hukom ng mga buháy at ng mga patay.
Sinasabi ko nga, natisod ba sila upang mahulog? Huwag nawang mangyari. Subalit sa pagkahulog nila'y dumating ang kaligtasan sa mga Hentil, upang pukawin sila sa paninibugho.
Siya ang aking sinugo sa inyo ukol sa bagay na ito, upang malaman ninyo ang aming kalagayan, at upang kanyang pasiglahin ang inyong mga puso;
At nakita ko ang isang anghel na nananaog mula sa langit, na hawak sa kanyang kamay ang susi ng di-matarok na kalaliman at ang isang malaking tanikala.
Dahil sa awa, iniunat ni Jesus ang kanyang kamay, hinipo ang ketongin at sinabi sa kanya, “Gusto ko, maging malinis ka.”
At nakita kong lumabas sa bibig ng dragon at mula sa bibig ng halimaw at mula sa bibig ng bulaang propeta ang tatlong espiritung karumaldumal, na gaya ng mga palaka.
“Ngunit sinumang maglagay ng batong katitisuran sa isa sa maliliit na ito na sumasampalataya sa akin, ay mas mabuti pa sa kanya na bitinan ang kanyang leeg ng isang malaking batong gilingan, at siya'y malunod sa kalaliman ng dagat.
Ngunit ang isa sa nakatayo roon ay bumunot ng kanyang tabak, tinaga ang alipin ng pinakapunong pari, at tinigpas ang kanyang tainga.
Ito'y sinabi niya, upang ipahiwatig kung sa anong uri ng kamatayan ang ikamamatay niya.
Umalis sila at kanilang natagpuan ang batang asno na nakatali sa pintuan sa labas ng lansangan. At kinalagan nila ito.
sapagkat minamasdan niya ang kanyang sarili at umaalis, at agad niyang nalilimutan kung ano ang kanyang katulad.
Tapat ang salita, at nais kong igiit mo ang mga bagay na ito upang ang mga nananampalataya sa Diyos ay maging maingat na ilaan ang kanilang sarili sa mabubuting gawa. Ang mga bagay na ito ay pawang mabubuti at kapaki-pakinabang sa mga tao.
at ito'y aking itatayo:
Ngunit kung ang isang tao ay nagdurusa bilang Cristiano, huwag niyang ikahiya ito, kundi luwalhatiin niya ang Diyos sa pangalang ito.
upang matupad ang sinabi ni propeta Isaias:
Nanatili sila roon na kasama ang mga alagad nang mahaba-habang panahon.
Nang malaman niya sa senturion, ipinagkaloob niya ang bangkay kay Jose.
Ngunit matapos akong maibangon, mauuna ako sa inyo sa Galilea.”
Sumasakanila ang kamay ng Panginoon at ang napakalaking bilang na sumampalataya ay nagbalik-loob sa Panginoon.
na sa kanya'y nakiapid ang mga hari sa lupa, at ang mga naninirahan sa lupa ay nalasing sa alak ng kanyang pakikiapid.
tunay na inyong mapapakinggan, ngunit hindi kailanman mauunawaan,
Siya'y tumitig sa kanya na may pagkatakot, at nagsabi, “Ano iyon, Panginoon?” Sinabi sa kanya, “Ang mga panalangin mo at ang iyong mga limos ay umakyat bilang alaala sa harapan ng Diyos.
Noon ay may isang malaking kawan ng mga baboy na nanginginain sa libis ng bundok.
Bumagsak ang ulan, at dumating ang baha. Humihip ang mga hangin at hinampas ang bahay na iyon, at iyon ay bumagsak; napakalakas nga ng kanyang pagbagsak.”
Subalit ang kaloob na walang bayad ay hindi gaya ng pagsuway. Sapagkat kung sa pamamagitan ng pagsuway ng isa ang marami ay namatay, lalo pang sumagana para sa marami ang biyaya ng Diyos, at ang kaloob dahil sa biyaya ng isang tao, na si Jesu-Cristo.
Dumating ang una, na nagsasabi, ‘Panginoon, tumubo ang iyong mina ng sampung mina pa.’
Sinabi nila sa kanya, “Ipagkaloob mo sa amin na makaupo kami, ang isa'y sa iyong kanan, at ang isa'y sa kaliwa, sa iyong kaluwalhatian.”
Sapagkat hindi sinugo ng Diyos ang Anak sa sanlibutan upang hatulan ang sanlibutan, kundi upang ang sanlibutan ay maligtas sa pamamagitan niya.
Ngunit ang matibay na saligan ng Diyos ay nananatiling matatag na may tatak na ganito: “Kilala ng Panginoon ang mga kanya,” at, “Lumayo sa kalikuan ang bawat tumatawag sa pangalan ng Panginoon.”
Nang pababa na sila sa bundok, iniutos ni Jesus sa kanila na nagsasabi, “Huwag ninyong sasabihin kanino man ang pangitain, hanggang ang Anak ng Tao ay muling buhayin mula sa mga patay.”
Sumainyo nawa ang biyaya at kapayapaang mula sa Diyos na ating Ama at sa Panginoong Jesu-Cristo.
at sa isang batang asno na anak ng babaing asno.”
Aking pinag-usig ang Daang ito hanggang sa kamatayan, na ginagapos at ipinapasok sa mga bilangguan ang mga lalaki at ang mga babae,
Sinabi sa kanya ng babae, “Ginoo, bigyan mo ako ng tubig na ito upang ako'y hindi na mauhaw o pumarito pa upang umigib.”
Ang biling ito ay ipinagkakatiwala ko sa iyo, Timoteo na aking anak, ayon sa mga propesiya na ginawa noong una tungkol sa iyo, upang sa pamamagitan ng mga ito ay makipaglaban ka ng mabuting pakikipaglaban,
At pinisa ang ubas sa pisaan sa labas ng lunsod, at lumabas sa pisaan ng ubas ang dugo, na umabot hanggang sa mga renda ng mga kabayo, sa layong halos dalawandaang milya.
Tulad ng isang tao na umalis upang maglakbay. Sa pag-alis niya sa kanyang bahay, at pagkabigay ng tagubilin sa kanyang mga alipin, sa bawat isa ang kanyang gawain, ay inutusan ang tanod sa pinto na magbantay.
Dahil dito'y inusig ng mga Judio si Jesus sapagkat ginagawa niya ang mga bagay na ito sa araw ng Sabbath.
Ngayon, maging ang unang tipan ay nagkaroon ng mga alituntunin sa pagsamba at ng isang panlupang santuwaryo.
at si Adan ay hindi nadaya, kundi ang babae nang madaya ay nahulog sa pagkakasala.
at ang mga pinuno ay nagtipon,
Sinasabi ng kanyang mga alagad, “Oo nga, ngayo'y nagsasalita kang malinaw, at hindi patalinghaga.
Sino ang makapaglalarawan sa kanyang lahi?
(Pupunta sa bukid ang dalawang lalaki; ang isa'y kukunin at ang isa'y iiwan.)
Nilibak at hinampas si Jesus ng mga lalaking nagbabantay sa kanya.
Sumagot sa kanya si Felipe, “Hindi magkakasiya sa kanila ang dalawang daang denariong tinapay, upang makakain ng kaunti ang bawat isa.”
Gayunma'y ang nasa inyo'y panghawakan ninyong matibay hanggang sa ako'y dumating.
at lubos ninyo silang igalang na may pag-ibig dahil sa kanilang gawain. Magkaroon kayo ng kapayapaan sa isa't isa.
“Ang tapat sa kakaunti ay tapat din naman sa marami at ang di-tapat sa kakaunti ay di rin naman tapat sa marami.
Humingi siya sa pinakapunong pari ng mga sulat para sa mga sinagoga sa Damasco upang kung siya'y makatagpo ng sinumang kabilang sa Daan, mga lalaki o mga babae, ay dadalhin niya silang nakagapos sa Jerusalem.
Kaya sa muling pagkabuhay, alin sa pito ang magiging asawa ng babae? Yamang siya'y napangasawa nilang lahat.”
Sapagkat hindi ang pumupuri sa kanyang sarili ang tinatanggap, kundi siya na pinupuri ng Panginoon.
Sapagkat sumusulat si Moises tungkol sa pagiging matuwid na batay sa kautusan, na “ang taong gumagawa ng mga bagay na ito ay mabubuhay sa mga ito.”
Dito'y naging ganap ang pag-ibig sa atin upang tayo'y magkaroon ng lubos na pagtitiwala sa araw ng paghuhukom; sapagkat kung ano siya, ay gayundin naman tayo sa sanlibutang ito.
At sinabi niya sa mga nakatayo, ‘Kunin ninyo sa kanya ang mina, at ibigay ninyo sa may sampung mina.’
Mayroon pa akong maraming bagay na sasabihin sa inyo, ngunit hindi ninyo kayang dalhin sa ngayon.
Pagkatapos ay dumating naman ang ibang mga birhen, na nagsasabi, ‘Panginoon, Panginoon, pagbuksan mo kami.’
Subalit nang araw na umalis sa Sodoma si Lot, umulan ng apoy at asupre mula sa langit at pinuksa silang lahat.
Samantala, nakatayo sa tabi ng krus ni Jesus ang kanyang ina, at ang kapatid ng kanyang ina, si Maria na asawa ni Cleopas, at si Maria Magdalena.
At pumasok siya sa isang bahay, at muling nagkatipon ang maraming tao, kaya't sila'y hindi man lamang makakain.
Ngunit paano nga silang tatawag sa kanya na hindi nila sinampalatayanan? At paano sila sasampalataya sa kanya na hindi nila napakinggan? At paano sila makikinig kung walang mangangaral?
Huwag kayong padaya sa mga salitang walang katuturan, sapagkat dahil sa mga bagay na ito'y dumarating ang galit ng Diyos sa mga anak ng pagsuway.
na sinasabi, ‘Tinugtugan namin kayo ng plauta, ngunit hindi kayo sumayaw; tumangis kami, ngunit hindi kayo nahapis.’
Kanilang dinakip ang mga apostol at kanilang inilagay sila sa bilangguang bayan.
Nang dumating sila sa mga alagad, nakita nilang napakaraming tao sa kanilang paligid at ang mga eskriba na nakikipagtalo sa kanila.
Subalit kung kayo'y nagpapakita ng pagtatangi, kayo ay nagkakasala at kayo'y inilalantad ng kautusan bilang mga lumalabag.
Mga ama, kayo'y sinusulatan ko
pinatunayang matuwid sa espiritu, nakita ng mga anghel,
Subalit ngayong dumating na ang pananampalataya, tayo ay wala na sa ilalim ng tagasupil.
Batiin ninyo si Maria, na lubhang maraming nagawa para sa inyo.
Subalit ngayo'y hindi na ako ang gumagawa nito, kundi ang kasalanang nananatili sa akin.
at ang hindi nagpapasan ng kanyang krus at sumusunod sa akin ay hindi karapat-dapat sa akin.
Kaya't kayo, mga minamahal, yamang nalalaman na ninyo noon pa ang mga bagay na ito, mag-ingat kayo, baka mailigaw kayo sa pamamagitan ng kamalian ng masasama at mahulog kayo mula sa inyong sariling katatagan.
na ingatan mong walang dungis at walang kapintasan ang utos hanggang sa pagpapakita ng ating Panginoong Jesu-Cristo;
At nakita ko ang pitong anghel na nakatayo sa harapan ng Diyos at sila'y binigyan ng pitong trumpeta.
Dahil dito, sapagkat narinig ko rin naman ang inyong pananampalataya sa Panginoong Jesus, at ang inyong pag-ibig sa lahat ng mga banal,
“O, ‘Sino ang mananaog sa kailaliman?’” (Ito ay upang iakyat si Cristo mula sa mga patay.)
Subalit paghawak niya sa kanyang kamay, siya'y tumawag at sinabi, “Bata, bumangon ka.”
Sapagkat ang asawang lalaki ang ulo ng asawang babae, gaya ni Cristo na ulo ng iglesya, na siya ang tagapagligtas ng katawan.
At nang oras na iyon ay nagkaroon ng isang malakas na lindol, at nagiba ang ikasampung bahagi ng lunsod; may namatay sa lindol na pitong libong katao at ang mga iba ay natakot, at nagbigay ng luwalhati sa Diyos ng langit.
Ang umiibig sa ama o sa ina nang higit kaysa akin ay hindi karapat-dapat sa akin; at ang umiibig sa anak na lalaki o anak na babae nang higit kaysa akin ay hindi karapat-dapat sa akin;
Kaya sinasabi ko sa inyo, ‘Kukunin sa inyo ang kaharian ng Diyos at ibibigay sa isang bansang nagbibigay ng bunga nito.’
Ingatan ninyo ang inyong sarili at ang buong kawan. Sa kanila'y inilagay kayo ng Espiritu Santo na mga tagapangasiwa upang pangalagaan ninyo ang iglesya ng Diyos na binili niya ng kanyang sariling dugo.
Nasa sa kanya ang buhay at ang buhay ay siyang ilaw ng mga tao.
Ngunit hindi umimik si Jesus. At sinabi ng pinakapunong pari sa kanya, “Pinanunumpa kita sa harapan ng Diyos na buháy, sabihin mo sa amin kung ikaw nga ang Cristo, ang Anak ng Diyos.”
Nakita ng mga kasamahan ko noon ang liwanag, ngunit hindi nila narinig ang tinig ng nagsalita sa akin.
‘Siya'y mag-uutos sa kanyang mga anghel tungkol sa iyo,’
Kayo'y hiwalay kay Cristo, kayong mga nagnanais ariing-ganap sa pamamagitan ng kautusan; nahulog kayo mula sa biyaya.
Ngunit nang dumating si Cefas sa Antioquia, sumalungat ako sa kanya nang mukhaan, sapagkat siya'y nahatulang nagkasala.
sa pag-asa sa buhay na walang hanggan. Bago pa nagsimula ang mga panahon, ito ay ipinangako ng Diyos na hindi nagsisinungaling.
Sapagkat kung hindi pinanghinayangan ng Diyos ang mga likas na sanga, ikaw man ay hindi panghihinayangan.
Ngunit sinumang magsalita ng paglapastangan laban sa Espiritu Santo ay walang kapatawaran magpakailanman, kundi nagkakasala ng isang kasalanang walang hanggan,”
Ang balabal na aking iniwan sa Troas kay Carpo ay iyong dalhin pagparito mo, at ang mga aklat, lalung-lalo na ang mga pergamino.
mula sa aking Espiritu ay magbubuhos ako sa lahat ng laman;
Sapagkat ang mga gayon ay hindi naglilingkod kay Cristo na Panginoon natin kundi sa kanilang sariling tiyan; at sa pamamagitan ng kanilang mahusay na pananalita at matatamis na talumpati ay dinadaya nila ang mga puso ng mga walang muwang.
Nasiyahan ang buong kapulungan sa kanilang sinabi at pinili nila si Esteban, lalaking puspos ng pananampalataya at ng Espiritu Santo, kasama sina Felipe, Procoro, Nicanor, Timon, Parmenas, at si Nicolas na isang naging Judio na taga-Antioquia.
Ako'y malapit nang dumating! Mapalad ang tumutupad ng mga salita ng propesiya ng aklat na ito.”
Sapagkat ang mga tao'y magiging maibigin sa kanilang sarili, maibigin sa salapi, mayayabang, mga mapagmalaki, mapanlait, suwail sa mga magulang, mga walang utang na loob, walang kabanalan,
Ngunit alam ito ni Jesus kaya't sinabi niya, “O kayong maliliit ang pananampalataya, bakit kayo'y nagtatalo na wala kayong tinapay?
at nang maging sakdal, siya ang naging pinagmulan ng walang hanggang kaligtasan ng lahat ng mga sumusunod sa kanya;
Subalit pinalapit sila ni Jesus na sinasabi, “Hayaan ninyong lumapit sa akin ang maliliit na bata, at huwag ninyo silang hadlangan, sapagkat sa mga ganito nauukol ang kaharian ng Diyos.
dahil sa inyong pakikibahagi sa pagpapalaganap ng ebanghelyo, mula nang unang araw hanggang ngayon.
Sumagot si Jesus at sinabi, “O lahing walang pananampalataya at napakasama, hanggang kailan ko pa kayo makakasama? Gaano katagal akong magtitiis sa inyo? Dalhin ninyo siya rito.”
Dito'y nakikilala ninyo ang Espiritu ng Diyos: ang bawat espiritung nagpapahayag na si Jesu-Cristo ay naparito sa laman ay sa Diyos,
Sapagkat kung saan naroroon ang inyong kayamanan ay naroroon din naman ang inyong puso.
Sa udyok ng kanyang ina ay sinabi niya, “Ibigay mo sa akin dito sa isang pinggan ang ulo ni Juan na Tagapagbautismo!”
Ngayo'y isinasamo ko sa inyo, mga kapatid, na tandaan ninyo ang mga lumilikha ng pagkakabaha-bahagi at ng mga katitisuran na laban sa mga aral na inyong natutunan; lumayo kayo sa kanila.
kahit ang lupa, sapagkat ito ang tuntungan ng kanyang mga paa; kahit ang Jerusalem, sapagkat iyon ang lunsod ng dakilang Hari.
Walang ama, walang ina, walang talaan ng angkan, ni walang pasimula ng mga araw o katapusan ng buhay, subalit ginawang katulad ng Anak ng Diyos, siya ay nananatiling pari magpakailanman.
“Sino nga ba ang tapat at matalinong alipin na inatasan ng kanyang panginoon na pangasiwaan ang kanyang sambahayan, upang magbigay sa kanila ng pagkain sa tamang panahon?
At kunin ninyo ang pinatabang guya at patayin ito, at tayo'y kumain at magdiwang.
“At sa anghel ng iglesya sa Tiatira ay isulat mo: Ang mga bagay na ito ay sinasabi ng Anak ng Diyos, na may mga matang gaya ng ningas ng apoy, at ang kanyang mga paa ay gaya ng tansong pinakintab.
At nang masabi niya ito ay lumabas siyang muli sa mga Judio at sa kanila'y sinabi, “Wala akong makitang anumang kasalanan sa kanya.
Sinabi ni Cornelio, “Apat na araw na ang nakakaraan, mga ganitong oras, nang ikasiyam na oras, ako'y nananalangin sa aking bahay nang biglang tumindig sa harapan ko ang isang lalaki na may nagniningning na damit.
Ngunit subukin ng bawat isa ang kanyang sariling gawa, at kung magkagayon, ang kanyang dahilan upang magmalaki ay sa kanyang sarili lamang, at hindi sa kanyang kapwa.
Sinabi ni Jesus, “Paupuin ninyo ang mga tao.” Madamo sa dakong iyon, kaya't umupo ang mga lalaki na may limang libo ang bilang.
Ituon ninyo ang inyong pag-iisip sa mga bagay na nasa itaas, hindi sa mga bagay na nasa ibabaw ng lupa,
“Akong si Jesus ay nagsugo ng aking anghel upang sa inyo'y magpatotoo ng mga bagay na ito sa mga iglesya. Ako ang ugat at ang supling ni David, ang maningning na tala sa umaga.”
na nakikiusap sa amin nang matindi tungkol sa biyaya na makibahagi sa paglilingkod sa mga banal.
Sapagkat saksi ko ang Diyos, na aking pinaglilingkuran sa aking espiritu sa ebanghelyo ng kanyang Anak, na walang tigil na binabanggit ko kayo sa aking panalangin,
Sinabi sa kanya ni Jesus, “Babae, anong kinalaman niyon sa akin at sa iyo? Ang aking oras ay hindi pa dumating.”
Kami'y mga saksi sa mga bagay na ito, gayundin ang Espiritu Santo na ibinigay ng Diyos sa mga sumusunod sa kanya.”
at ang pagtitiis ng pagpapatibay; at ang pagpapatibay ng pag-asa.
Sila'y sinugo niya upang ipangaral ang kaharian ng Diyos at upang magpagaling ng mga may sakit.
Nang sumunod na araw, dahil sa pagnanais na malaman ang tunay na dahilan kung bakit siya'y isinakdal ng mga Judio ay kanyang pinawalan siya at iniutos sa mga punong pari at sa buong Sanhedrin na magpulong. Pinababa niya si Pablo at iniharap sa kanila.
Sinabi rin naman niya sa nag-anyaya sa kanya, “Kapag naghahanda ka ng isang tanghalian o ng isang hapunan, huwag mong tawagin ang iyong mga kaibigan, o ang iyong mga kapatid, o ang iyong mga kamag-anak, o mayayamang kapitbahay, baka ikaw naman ay kanilang anyayahan at ikaw ay gantihan.
Ngayon, hinihiling ko na kapag ako'y kaharap, hindi ko kailangang magpakita ng tapang na may pagtitiwala na nais kong ipakita laban sa mga naghihinalang kami ay lumalakad ayon sa makasanlibutang gawi.
Pagkalooban nawa ng Panginoon ng habag ang sambahayan ni Onesiforo, sapagkat madalas niya akong pinagiginhawa, at hindi niya ikinahiya ang aking tanikala;
at kaluwalhatian sa kataas-taasan!”
at lumapit sa kanya ang isang ketongin, at lumuhod sa harapan niya na nagsasabi, “Panginoon, kung ibig mo ay malilinis mo ako.”
Nang mga araw na iyon ay tumindig si Maria at nagmadaling pumunta sa isang bayan ng Judea, sa lupaing maburol.
At nakita namin at sinasaksihan na sinugo ng Ama ang Anak bilang Tagapagligtas ng sanlibutan.
Siyang nagbibigay ng binhi sa manghahasik at ng tinapay bilang pagkain ay siyang magbibigay at magpaparami ng inyong binhi upang ihasik, at magpaparami ng mga bunga ng inyong pagiging matuwid;
Sinabi sa kanya ng kanyang mga alagad, “Nakikita mong sinisiksik ka ng karamihan, at sinasabi mo pang ‘Sino ang humipo sa akin?’”
Sapagkat kilala natin ang nagsabi, “Akin ang paghihiganti, ako ang gaganti.” At muli, “Huhukuman ng Panginoon ang kanyang bayan.”
Sinabi sa kanya ng anghel, “Huwag kang matakot, Maria, sapagkat nakatagpo ka ng paglingap sa Diyos.
ng aral tungkol sa mga bautismo, pagpapatong ng mga kamay, muling pagkabuhay ng mga patay, at ng walang hanggang paghuhukom.
Ang iba nama'y nahulog sa batuhan na doo'y kakaunti lamang ang lupa; at kaagad silang sumibol yamang hindi malalim ang lupa.
sa kanila ang mga patriyarka, at sa kanila nagmula ang Cristo ayon sa laman, na siyang nangingibabaw sa lahat, Diyos na maluwalhati magpakailanman. Amen.
Ngunit kinagabihan ay binuksan ng isang anghel ng Panginoon ang mga pintuan ng bilangguan, sila'y inilabas, at sinabi,
“Katotohanang sinasabi ko sa inyo, ang pumapasok sa hindi pintuan ng kulungan ng mga tupa kundi umaakyat sa ibang daan, ang taong iyon ay tulisan at magnanakaw.
“upang maging mabuti ang inyong kalagayan at ikaw ay mabuhay nang matagal sa ibabaw ng lupa.”
at siya rin namang sa amin ay nagpahayag ng inyong pag-ibig sa Espiritu.
pagkatapos ng mga araw na iyon, sabi ng Panginoon;
Nang magkagayo'y sinabi sa kanya ni Jesus, “Ibalik mo ang iyong tabak sa kanyang lalagyan, sapagkat ang lahat ng humahawak ng tabak ay sa tabak mamatay.
At sinumang tumanggap sa isang batang ganito sa aking pangalan ay tumatanggap sa akin.
Kayo mismo ang nakakaalam na ang mga kamay na ito ay naglingkod sa aking mga pangangailangan at sa mga kasama ko.
at huwag bigyan ng pagkakataon ang diyablo.
Isang kakilakilabot na bagay ang mahulog sa mga kamay ng Diyos na buháy.
Walang sinuman na pagkatapos magsindi ng ilawan ay inilalagay ito sa isang tagong lugar o sa ilalim ng takalan, kundi sa patungan ng ilaw upang makita ng mga pumapasok ang liwanag.
At nagsugo pa siya ng ikatlo. Ito ay kanilang sinugatan at pinagtabuyan.
At tinanong siya ni Pilato, “Ikaw ba ang Hari ng mga Judio?” Sumagot siya at sinabi, “Ikaw ang nagsasabi.”
Nakiusap sila sa kanya na mahipo man lamang nila ang laylayan ng kanyang damit; at ang lahat ng humipo nito ay gumaling.
“Huwag mabagabag ang inyong puso. Sumampalataya kayo sa Diyos, sumampalataya rin naman kayo sa akin.
Aking binabalaan ang mga nagkasala noong una at lahat ng iba pa, at binabalaan ko sila ngayon habang wala pa, gaya ng ginawa ko nang ako'y kaharap sa ikalawa kong pagdalaw, na kapag ako'y muling dumating, sila ay hindi ko na pagbibigyan.
Makikilala ninyo sila sa kanilang mga bunga. Nakakapitas ba ng mga ubas sa mga tinikan, o ng mga igos sa mga dawagan?
Sa Haring walang hanggan, walang kamatayan, di-nakikita, tanging Diyos, ang karangalan at kaluwalhatian magpakailanpaman. Amen.
Samantalang kanilang pinag-uusapan ang mga bagay na ito, si Jesus ay tumayo sa gitna nila at sinabi sa kanila, “Sumainyo ang kapayapaan.”
At sinabi niya sa kanila, “Nang kayo'y suguin ko na walang supot ng salapi, o supot ng pagkain, at mga sandalyas, kinulang ba kayo ng anuman?” At kanilang sinabi, “Hindi.”
At anumang inyong ginagawa, sa salita, o sa gawa, gawin ninyong lahat sa pangalan ng Panginoong Jesus, na nagpapasalamat kayo sa Diyos Ama sa pamamagitan niya.
Tinatawag siya ni David na Panginoon, kaya't paanong siya'y naging anak niya?”
At sinabi sa kanila ni Pedro, “Magsisi kayo, at magpabautismo ang bawat isa sa inyo sa pangalan ni Jesu-Cristo upang mapatawad ang inyong mga kasalanan; at tatanggapin ninyo ang kaloob ng Espiritu Santo.
Sinabi sa kanya ni Jesus, “Ako ang muling pagkabuhay at ang buhay. Ang sumasampalataya sa akin, bagama't siya'y mamatay, ay mabubuhay.
Doon ay nakatagpo kami ng mga kapatid, at kami'y pinakiusapan nilang tumigil sa kanila sa loob ng pitong araw. Sa gayo'y nakarating kami sa Roma.
At narinig ko ang isang malakas na tinig na mula sa templo, na nagsasabi sa pitong anghel, “Humayo kayo at ibuhos ninyo sa lupa ang pitong mangkok ng poot ng Diyos.”
May isang lumapit sa kanya at nagsabi, “Guro, anong mabuting bagay ang dapat kong gawin upang magkaroon ako ng buhay na walang hanggan?”
Kaya't kami'y naaliw. At sa aming kaaliwan ay lalo pa kaming nagalak dahil sa kagalakan ni Tito, sapagkat ang kanyang espiritu ay pinayapa ninyong lahat.
[
kung paanong sa matinding pagsubok ng kapighatian, ang kasaganaan ng kanilang kagalakan at ang kanilang labis na kahirapan ay sumagana sa kayamanan ng kanilang kagandahang-loob.
Ngunit sumigaw si Pablo nang malakas, “Huwag mong saktan ang iyong sarili, sapagkat naririto kaming lahat.”
At sinabi nila sa akin, “Kailangang muli kang magpahayag ng propesiya tungkol sa maraming mga bayan at mga bansa, mga wika at mga hari.”
lalo na dahil sa kalabisan ng mga pahayag. Kaya't upang ako'y huwag magyabang ng labis, binigyan ako ng isang tinik sa laman, isang sugo ni Satanas upang ako'y saktan, upang ako'y huwag magmalaki ng labis.
Minsan, nang si Jesus ay nananalanging mag-isa, ang mga alagad ay kasama niya at tinanong niya sila, “Ano ang sinasabi ng karamihan kung sino ako?”
Magsisimula ba kaming muli na purihin ang aming sarili? O kailangan ba namin, gaya ng iba, ng mga sulat ng papuri sa inyo, o mula sa inyo?
At habang nakikipag-usap sa kanya, pumasok siya at kanyang naratnan ang maraming taong nagkakatipon.
Sa palagay ba ninyo ay pumarito ako upang magdala ng kapayapaan sa lupa? Hindi! Sinasabi ko sa inyo, sa halip ay pagkakabaha-bahagi.
Ngunit pagkatapos ng tatlong araw at kalahati, ang hininga ng buhay na mula sa Diyos ay pumasok sa kanila. Sila'y tumindig at dinatnan ng malaking takot ang mga nakakita sa kanila.
Pagkatapos ay lumabas ang mga demonyo sa tao, at pumasok sa mga baboy at ang kawan ay dumaluhong sa bangin patungo sa lawa at nalunod.
Kaya't kung sasamba ka sa akin, ang lahat ng ito ay magiging iyo.”
At nang kanyang malaman na siya'y sakop ni Herodes, kanyang ipinadala siya kay Herodes, na nang panahong iyon ay nasa Jerusalem din.
ngunit kung tayo'y may pagkain at damit, masiyahan na tayo sa mga ito.
Gayon ang pagtitiwalang taglay namin sa pamamagitan ni Cristo tungo sa Diyos.
at buhat noon ay naghihintay hanggang sa ang kanyang mga kaaway ay maging tuntungan ng kanyang mga paa.
Sinabi niya sa kanila, “Bakit kayo natakot? Wala ba kayong pananampalataya?”
Sapagkat inihahanda tayo nitong magaan at panandaliang kapighatian para sa walang hanggan at di-masukat na kaluwalhatian,
Nang magugol na niyang lahat ay nagkaroon ng matinding taggutom sa lupaing iyon, at siya'y nagsimulang mangailangan.
May mga taong dumating na may dala sa kanya na isang lalaking lumpo na buhat ng apat.
Sapagkat sinasabi ko sa inyo na ang kasulatang ito ay kailangang matupad sa akin, ‘At ibinilang siya sa mga suwail’; sapagkat ang nasusulat tungkol sa akin ay natutupad.”
Subalit hanggang sa araw na ito, tuwing binabasa ang kautusan ni Moises, may isang talukbong na nakatakip sa kanilang puso.
Nang si Pablo ay tawagin, sinimulan siyang paratangan ni Tertulio, na sinasabi,
“Ngayon, kung marinig ninyo ang kanyang tinig,
Lahat ng mga taga-Atenas at ang mga dayuhang naninirahan doon ay walang pinaggugulan ng panahon kundi ang mag-usap o makinig ng mga bagong bagay.
Siya'y nanunuluyan kay Simon, isang tagapagluto ng balat, na ang bahay ay nasa tabi ng dagat.”
Isang araw ng Sabbath habang bumabagtas si Jesus sa mga triguhan, ang mga alagad niya ay pumitas ng mga uhay at pagkatapos ligisin sa kanilang mga kamay ay kinain ang mga ito.
Subalit ipinagkaila niya ito sa harap nilang lahat, na sinasabi, “Hindi ko alam ang sinasabi mo.”
Iniutos niya sa mga tao na umupo sa lupa.
Sapagkat madali pa sa isang kamelyo ang pumasok sa butas ng isang karayom, kaysa sa isang taong mayaman na pumasok sa kaharian ng Diyos.”
Kinabukasan, nang dumating sila mula sa Betania ay nagutom siya.
si Juan na Tagapagbautismo ay dumating sa ilang at ipinangangaral ang bautismo ng pagsisisi sa ikapagpapatawad ng mga kasalanan.
“Kahabag-habag kayo, mga eskriba at mga Fariseo, mga mapagkunwari! Sapagkat nililinis ninyo ang labas ng kopa at ng pinggan, ngunit sa loob ay punô sila ng kasakiman at kalayawan.
“Ako ang tunay na puno ng ubas, at ang aking Ama ang tagapag-alaga.
Ang tinuturuan ng salita ay dapat magbahagi sa nagtuturo ng lahat ng mga bagay na mabuti.
Nang makita niya ang anghel, nasindak at natakot si Zacarias.
[Ngunit kung hindi kayo magpapatawad, hindi rin kayo patatawarin sa inyong mga kasalanan ng inyong Ama na nasa mga langit.]”
Narinig ito ng mga punong pari at ng mga eskriba at sila'y naghanap ng paraan kung paano nila siya mapapatay, sapagkat natatakot sila sa kanya dahil maraming tao ang namangha sa kanyang aral.
Gayunman, dapat ibigin ng bawat isa sa inyo ang kanyang sariling asawa gaya ng kanyang sarili, at igalang ng babae ang kanyang asawa.
Sinabi sa kanya ng mga Judio, “Wala ka pang limampung taon, at nakita mo na si Abraham?”
Gayunma'y isinusulat ko sa inyo ang isang bagong utos na tunay sa kanya at sa inyo, sapagkat ang kadiliman ay lumilipas at ang tunay na liwanag ay tumatanglaw na.
Sinagot sila ni Jesus, “Ang turo ko ay hindi akin, kundi sa kanya na nagsugo sa akin.
Sinabi sa kanya ng anghel, “Magbihis ka at isuot mo ang iyong mga sandalyas.” At iyon nga ang ginawa niya. At sinabi niya sa kanya, “Ibalot mo sa iyong sarili ang iyong balabal at sumunod ka sa akin.”
Ngunit kapag ang isang tao ay bumabaling sa Panginoon, ang talukbong ay naaalis.
Kaya't ang magkapatid na babae ay nagbalita kay Jesus, “Panginoon, siya na iyong minamahal ay may sakit.”
At ako'y kanyang dinalang nasa Espiritu sa isang ilang at nakita ko ang isang babae na nakasakay sa isang halimaw na pula, na punô ng mga pangalan ng kalapastanganan na may pitong ulo at sampung sungay.
At sinabi ni Pablo, “Hindi ko alam, mga kapatid, na siya'y pinakapunong pari, sapagkat nasusulat, ‘Huwag mong pagsasalitaan ng masama ang isang pinuno ng iyong bayan.’”
Umalis siya sa sinagoga at pumasok sa bahay ni Simon. Noon ay mataas ang lagnat ng biyenang babae ni Simon at pinakiusapan nila si Jesus para sa kanya.
Hindi ako pumarito upang tawagin ang mga matuwid, kundi ang mga makasalanan tungo sa pagsisisi.”
Kaya't ang mga punong pari at ang mga Fariseo ay nagpatawag ng pagpupulong at sinabi, “Ano ang gagawin natin? Ang taong ito'y gumagawa ng maraming tanda.
Sa isang takdang araw ay isinuot ni Herodes ang damit-hari at naupo sa trono, at sa kanila'y nagtalumpati.
Ang iba'y nahikayat sa mga bagay na sinabi niya at ang iba'y hindi naniwala.
Sila'y may mga buntot na gaya ng sa mga alakdan at may mga pantusok; at sa kanilang mga buntot ay naroroon ang kanilang kapangyarihan upang pinsalain ang mga tao ng limang buwan.
Hindi ba ito ang karpintero, ang anak ni Maria at kapatid nina Santiago, Jose, Judas, at Simon? Hindi ba naritong kasama natin ang kanyang mga kapatid na babae?” At sila'y natisod sa kanya.
at kayong mga pinahihirapan ay bigyan ng kapahingahang kasama namin, sa pagkapahayag ng Panginoong Jesus mula sa langit na kasama ang kanyang mga makapangyarihang anghel,
Tulad ng mga masunuring mga anak, huwag kayong gumaya sa masasamang pagnanasa ng inyong kamangmangan noong una.
Ngunit mayroon ka pang ilan sa Sardis na hindi dinungisan ang kanilang mga damit; at sila'y kasama kong lalakad na nakaputi, sapagkat sila'y karapat-dapat.
Noon, ang mga maniningil ng buwis at mga makasalanan ay lumalapit sa kanya upang makinig.
at itatapon sila sa pugon ng apoy. Doon ay magkakaroon ng pagtangis at pagngangalit ng mga ngipin.
Makipaglaban ka sa mabuting pakikipaglaban ng pananampalataya, panghawakan mo ang buhay na walang hanggan na dito'y tinawag ka, at ipinahayag mo ang mabuting pagpapahayag sa harapan ng maraming mga saksi.
Akong si Pablo ay sumusulat ng pagbating ito ng aking sariling kamay. Ito ang palatandaan sa bawat sulat ko; gayon ako sumusulat.
Wala bang natagpuang bumalik at nagbigay papuri sa Diyos, maliban sa dayuhang ito?”
at dahil sa salita ng kanilang patotoo,
Matuwid at tunay ang iyong mga daan,
At siya'y binigyan nila ng alak na hinaluan ng mira, ngunit hindi niya tinanggap iyon.
Sapagkat ang mga bagay na ito ay nangyari upang matupad ang kasulatan, “Kahit isa mang buto niya'y hindi mababali.”
Sana'y mapagtiisan ninyo ako sa kaunting kahangalan. Subalit tunay na nagtitiis kayo sa akin!
“Masdan ninyo, ang tabernakulo ng Diyos ay nasa mga tao.
ayon sa pagkapili niya sa atin sa kanya bago itinatag ang sanlibutan, upang tayo'y maging banal at walang dungis sa harapan niya sa pag-ibig.
Nagkaroon ng takot ang lahat ng nakatira sa palibot nila, at ang lahat ng mga bagay na ito ay pinag-usapan sa buong lupaing maburol ng Judea.
Sapagkat ang lahat ng pinapatnubayan ng Espiritu ng Diyos ay sila ang mga anak ng Diyos.
Nang gabing iyon ay lumitaw ang isang pangitain kay Pablo: may isang lalaking taga-Macedonia na nakatayo at nakikiusap sa kanya na sinasabi, “Tumawid ka patungo sa Macedonia, at tulungan mo kami.”
Ipahayag mo ang mga bagay na ito. Mangaral ka at sumaway na may buong kapamahalaan. Huwag mong hayaang hamakin ka ng sinuman.
Ito'y yaong naroon sa kapulungan sa ilang na kasama ang anghel na nagsalita sa kanya sa Bundok ng Sinai, at kasama ang ating mga ninuno. Tumanggap siya ng mga buháy na aral upang ibigay sa atin.
Nang sila'y makadaong sa lupa, nakakita sila roon ng mga nagbabagang uling, at may isdang nakalagay sa ibabaw, at tinapay.
Isang Sabbath, nang pumasok si Jesus sa bahay ng isa sa mga pinuno ng mga Fariseo upang kumain, kanilang minamatyagan siya.
Ang Diyos na gumawa ng sanlibutan at ng lahat ng mga bagay na naririto, siya na Panginoon ng langit at ng lupa, ay hindi tumitira sa mga templong ginawa ng tao;
Subalit sumama sa kanya ang ilang mga tao at nanampalataya. Isa sa kanila si Dionisio na taga-Areopago, at ang isang babaing ang pangalan ay Damaris at iba pang mga kasama nila.
Binabati kayo ni Epafras, na isa sa inyo, na alipin ni Cristo Jesus, na siyang laging nagsisikap para sa inyo sa kanyang pananalangin, upang kayo'y tumayong sakdal at lubos na nakakatiyak sa lahat ng kalooban ng Diyos.
Kaya't pagdating ko riyan, ay ipapaalala ko ang kanyang mga ginagawa, na nagsasalita ng masasamang salita laban sa amin. At hindi pa nasisiyahan sa ganito, hindi niya tinatanggap ang mga kapatid, at hinahadlangan ang mga nagnanais tumanggap sa kanila at pinapalayas sila sa iglesya.
Sinong hindi matatakot
Sinabi niya sa kanila, “Ako'y lubhang nalulungkot, hanggang sa kamatayan; manatili kayo rito at manatiling gising.”
Iisa ang tagapagbigay ng kautusan at hukom, siya na may kapangyarihang magligtas at pumuksa. Kaya, sino ka na humahatol sa iyong kapwa?
At doo'y sinalubong sila ni Jesus, na nagsasabi, “Kapayapaan ay sumainyo.” At paglapit nila sa kanya ay niyakap ang kanyang mga paa at siya'y sinamba.
Si Tomas na tinatawag na Kambal ay nagsabi sa mga kapwa niya alagad, “Pumunta rin tayo upang mamatay na kasama niya.”
na aming nalalaman na ang bumuhay sa Panginoong Jesus ay siya ring bubuhay sa amin na kasama ni Jesus, at dadalhin kaming kasama ninyo sa kanyang harapan.
Nagpapasalamat ako sa Diyos, na aking pinaglilingkuran na may malinis na budhi gaya ng aking mga ninuno, kapag lagi kitang naaalala sa aking mga panalangin gabi't araw.
Sumagot siya at sinabi sa kanila, “Sapagkat sa inyo ipinagkaloob na malaman ang mga hiwaga ng kaharian ng langit, ngunit hindi ipinagkaloob sa kanila.
Sapagkat sinabi ni Juan sa kanya, “Hindi ipinahihintulot sa iyo na angkinin mo siya.”
Nang matapos ni Jesus ang mga pananalitang ito, umalis siya sa Galilea at nagtungo sa mga nasasakupan ng Judea sa dakong ibayo ng Jordan.
Sapagkat ang lahat ng mga pangako ng Diyos sa kanya ay “Oo.” Kaya't sa pamamagitan niya ay aming sinasambit ang “Amen,” sa ikaluluwalhati ng Diyos.
Samantala, ang labing-isang alagad ay pumunta sa Galilea, sa bundok na itinuro sa kanila ni Jesus.
at nilait nila ang Diyos ng langit dahil sa kanilang mga hirap at sa kanilang mga sugat; at hindi sila nagsisi sa kanilang mga gawa.
Makaraan ang walong araw, dumating ang panahon upang tuliin ang bata. Tinawag siyang Jesus, ang pangalang ibinigay ng anghel bago siya ipinaglihi sa sinapupunan.
Ama, luwalhatiin mo ang iyong pangalan.” At dumating ang isang tinig mula sa langit, “Niluwalhati ko na, at muli kong luluwalhatiin.”
Ako ang puno ng ubas, kayo ang mga sanga. Ang nananatili sa akin at ako'y sa kanya ay siyang nagbubunga ng marami. Sapagkat kung kayo'y hiwalay sa akin ay wala kayong magagawa.
Pagkatapos ng mga bagay na ito, si Jesus at ang kanyang mga alagad ay pumunta sa lupain ng Judea. Doon ay nanatili siyang kasama nila at nagbabautismo.
Ngayon ay nalalaman nila na ang lahat ng mga bagay na ibinigay mo sa akin ay mula sa iyo;
Hindi ang pumapasok sa bibig ang nagpaparumi sa tao, kundi ang lumalabas sa bibig ang nagpaparumi.”
Hindi dahil sa kami ay walang karapatan, kundi upang maibigay namin ang aming mga sarili sa inyo bilang huwaran na dapat tularan.
Huwag kayong padaya kanino man sa anumang paraan, sapagkat ito'y hindi darating malibang maunang maganap ang pagtalikod, at mahayag ang taong makasalanan, ang anak ng kapahamakan.
ni hindi rin naman siya pinaglilingkuran ng mga kamay ng tao, na para bang mayroon siyang kailangan, yamang siya ang nagbibigay sa lahat ng tao ng buhay at ng hininga, at ng lahat ng bagay na ito.
at hindi para sa bansa lamang, kundi upang tipunin niya sa iisa ang mga anak ng Diyos na nagkahiwa-hiwalay.
Hinampas nila ang kanyang ulo ng isang tungkod, dinuraan siya at lumuhod sa harapan niya.
Dumating din ang mga maniningil ng buwis upang magpabautismo at sinabi nila sa kanya, “Guro, ano ang dapat naming gawin?”
At sumagot si Jesus sa kanila, “Magkaroon kayo ng pananampalataya sa Diyos.
na pinawi ang sulat-kamay na laban sa atin na nasa mga tuntuning salungat sa atin, at ito'y kanyang inalis at ipinako sa krus.
Tinanong siya ng maraming tao, “Ano ngayon ang dapat naming gawin?”
At humayo sila, at natagpuan ito ayon sa sinabi niya sa kanila, at inihanda nila ang Paskuwa.
At sinabi niya, “Mag-ingat kayo na hindi kayo mailigaw, sapagkat marami ang darating sa aking pangalan, na magsasabi, ‘Ako siya!’ at, ‘Malapit na ang panahon!’ Huwag kayong sumunod sa kanila.
sapagkat kahit kilala nila ang Diyos, siya ay hindi nila niluwalhati bilang Diyos, ni pinasalamatan man, kundi naging walang kabuluhan sa kanilang mga pangangatuwiran at ang mga puso nilang walang katuturan ay nagdilim.
At nang siya'y maipako nila sa krus, pinaghati-hatian nila ang kanyang mga damit sa pamamagitan ng palabunutan.
Ibinangon ng Diyos ng ating mga ninuno si Jesus, na inyong pinatay nang ibitin siya sa isang punungkahoy.
Gaya ng nasusulat,
Pagkatapos ay nagkaroon ng malakas na sigawan, at tumindig ang ilan sa mga eskriba na kakampi ng mga Fariseo, at mainitang nagtalo na sinasabi, “Wala kaming makitang anumang kasalanan sa taong ito. Ano nga kung siya'y kinausap man ng isang espiritu, o ng isang anghel?”
Nagbulung-bulungan ang mga Fariseo at ang kanilang mga eskriba laban sa kanyang mga alagad na sinasabi, “Bakit kayo'y kumakain at umiinom na kasalo ng mga maniningil ng buwis at ng mga makasalanan?”
Kaya't nang sabihin niya, “Sa ibang tao,” ay sinabi sa kanya ni Jesus, “Kung gayo'y hindi na pinagbabayad ang mga anak.
Ako'y natatakot na nagpagal ako sa inyo nang walang kabuluhan.
Sa mga banal at tapat na mga kapatid kay Cristo na nasa Colosas: Sumainyo nawa ang biyaya at kapayapaang mula sa Diyos na ating Ama.
At sa alinmang bayan kayo pumasok at kayo'y kanilang tanggapin ay kainin ninyo ang anumang inihahain sa inyo.
At hindi lamang iyon, kundi siya ay hinirang ng mga iglesya na maglakbay na kasama namin ukol sa biyayang ito na aming pinangangasiwaan, sa ikaluluwalhati ng Panginoon, at upang ipakita ang aming pagnanais.
Ngunit ang kapatid na hamak ay hayaang magmalaki sa kanyang pagkakataas,
Narito ang panawagan para sa pagtitiis ng mga banal, sa mga tumutupad sa mga utos ng Diyos, at humahawak ng matatag sa pananampalataya ni Jesus.
Ngunit si Timoteo ay dumating na sa amin mula sa inyo, at nagdala sa amin ng magandang balita tungkol sa inyong pananampalataya at pag-ibig. Sinabi rin niya sa amin na lagi ninyo kaming naaalala at nananabik na makita kami na gaya naman namin na nananabik na makita kayo.
Itinuturing ko na ang pagtitiis sa panahong kasalukuyan ay hindi karapat-dapat maihambing sa kaluwalhatiang mahahayag sa atin.
Ngayon, ako'y nagagalak hindi sapagkat kayo'y nalungkot, kundi sapagkat kayo'y nalungkot tungo sa pagsisisi, sapagkat kayo'y pinalumbay nang naaayon sa Diyos, upang kayo'y huwag magdusa ng kalugihan sa pamamagitan namin.
Marahan kaming naglayag nang maraming araw at may kahirapan kaming nakarating sa tapat ng Cnido. Nang hindi kami pinahintulutan ng hanging makasulong pa, naglayag kami na nanganganlong sa Creta, sa tapat ng Salmone.
At tayong lahat, na walang talukbong ang mukha, na nakikita ang kaluwalhatian ng Panginoon gaya ng sa isang salamin, ay nababago sa gayunding larawan, mula sa kaluwalhatian tungo sa kaluwalhatian, sapagkat ito ay mula sa Panginoon na siyang Espiritu.
Sa alinmang bayan o nayon kayo makapasok, hanapin ninyo kung sino roon ang karapat-dapat; at makitira kayo sa kanya hanggang sa inyong pag-alis.
Sapagkat ang bawat mayroon ay bibigyan at siya'y magkakaroon ng kasaganaan, ngunit ang wala, pati ang nasa kanya ay kukunin.
Iniiwasan namin ito upang huwag kaming sisihin tungkol sa kasaganaang ito na aming pinangangasiwaan;
tuwing hahatulan tayo ng ating puso; sapagkat ang Diyos ay higit na dakila kaysa ating puso, at nalalaman niya ang lahat ng mga bagay.
O kaya'y hayaan ang mga tao ring ito na magsabi kung anong masamang gawa ang natagpuan nila nang ako'y tumayo sa harapan ng Sanhedrin,
At sumagot siya, “Katotohanang sinasabi ko sa iyo, ngayon ikaw ay makakasama ko sa Paraiso.”
Nang maitaas na ito, gumawa sila ng paraan upang matalian ng lubid ang barko. Dahil sa takot na baka sila mapapadpad sa Sirte, ibinaba nila ang mga layag at sa gayo'y naanod sila.
“Dalawang lalaki ang pumunta sa templo upang manalangin. Ang isa'y Fariseo, at ang isa'y maniningil ng buwis.
Sinabi niya, “Jesus, alalahanin mo ako, pagdating mo sa iyong kaharian.”
Sapagkat,
Kayo'y naghahangad, at kayo'y wala; kayo'y pumapatay at kayo'y nag-iimbot at kayo'y hindi nagkakamit. Kayo'y nag-aaway at nagdidigmaan. Kayo'y wala, sapagkat hindi kayo humihingi.
“Sa panahong kanais-nais ay pinakinggan kita,
“Ang aking pamumuhay mula sa aking pagkabata, na simula pa'y ginugol ko na sa aking bansa at sa Jerusalem, ay nalalaman ng lahat ng mga Judio.
Ang inyong pananalita nawa'y laging may biyaya, na may timplang asin, upang inyong malaman kung paano ninyo dapat sagutin ang bawat isa.
Ngunit pagtitig sa kanya ni Pedro, kasama si Juan, ay sinabi, “Tingnan mo kami.”
Gayundin ang Sodoma at Gomorra, at ang mga lunsod sa palibot ng mga ito, na gumawa naman ng pakikiapid at nalulong sa kakaibang laman, ay inilagay bilang halimbawa, na nagdaranas ng kaparusahan sa apoy na walang hanggan.
Ano sa palagay mo, alin sa tatlong ito, ang naging kapwa tao sa nahulog sa kamay ng mga tulisan?”
At pagkatapos na mapalaya kayo sa kasalanan ay naging mga alipin kayo sa paggawa ng matuwid.
Sinabi sa kanya ni Pilato, “Ano ang katotohanan?”
Kanilang sinabi, “Hindi ba ito'y si Jesus, ang anak ni Jose, na kilala natin ang kanyang ama at ina? Paano niya nasasabi, ‘Ako'y bumabang galing sa langit?’”
Sabihan mo rin ang matatandang babae na maging magalang sa kanilang asal, hindi mapanirang-puri, ni paalipin man sa alak; dapat silang magturo ng kabutihan,
Sapagkat kung saan nagkakatipon ang dalawa o tatlo sa aking pangalan, ay naroroon ako sa gitna nila.”
Pinapakinggan ng aking mga tupa ang aking tinig, at sila'y aking kilala, at sila'y sumusunod sa akin.
Yamang ang kautusan ay anino lamang ng mabubuting bagay na darating, at hindi ang tunay na larawan ng mga bagay na ito, kailanman ay hindi nito mapapasakdal ang mga lumalapit sa pamamagitan ng gayunding mga alay na laging inihahandog taun-taon.
At si Judas na sa kanya'y nagkanulo, ay sumagot at nagsabi, “Hindi ako iyon, Rabi?” Sinabi niya sa kanya, “Ikaw ang nagsabi.”
At may isang binata na ang pangalan ay Eutico na nakaupo sa bintana. Nakatulog siya nang mahimbing samantalang si Pablo ay nagsasalita nang mahaba; at dahil natalo ng antok ay nahulog siya mula sa ikatlong palapag, at siya'y patay na binuhat.
Ipakita ninyo sa akin ang salaping pambuwis.” At dinala sa kanya ang isang denario.
“Narito, ipinapadala ko ang aking sugo sa iyong unahan,
Sapagkat si Herodes mismo ang nagsugo sa mga kawal na dumakip kay Juan, at nagpagapos sa kanya sa bilangguan dahil kay Herodias, na asawa ni Felipe na kanyang kapatid; sapagkat pinakasalan siya ni Herodes.
Noon ay sumama sa kanya ang napakaraming tao. Siya'y humarap sa kanila at sa kanila'y sinabi,
At aking sinabi, ‘Panginoon, sila mismo ay nakaalam na sa bawat sinagoga ay ibinilanggo ko at hinampas ang mga nanampalataya sa iyo.
Ang bawat sanga sa akin na hindi nagbubunga ay inaalis niya; at ang bawat sanga na nagbubunga ay nililinis niya upang lalong magbunga.
at sa mga nakaupo sa lupain at lilim ng kamatayan,
At sinunggaban niya ang dragon, ang matandang ahas, na siyang Diyablo at Satanas, at ginapos siya ng isang libong taon,
Sapagkat ang buhay ay higit kaysa pagkain at ang katawan ay higit kaysa damit.
Ang hiwagang ito ay dakila, subalit ako ay nagsasalita tungkol kay Cristo at sa iglesya.
Nang kanyang mabatid ito, pumunta siya sa bahay ni Maria, ang ina ni Juan na tinatawag na Marcos, na kinaroroonan ng maraming nagkakatipon at nananalangin.
Sila'y nagsisigaw at nagsabi, “Jesus, Panginoon, maawa ka sa amin.”
ni Melea, ni Mena, ni Matata, ni Natan, ni David,
Hindi pa ba ninyo nalalaman na ang anumang pumapasok sa bibig ay tumutuloy sa tiyan, at inilalabas sa daanan ng dumi?
Ang buong bilang ng mga sumampalataya ay may pagkakaisa sa puso at kaluluwa; sinuma'y walang nagsabing kanya ang anuman sa kanyang mga ari-arian, kundi lahat nilang pag-aari ay para sa lahat.
Kaya't kanilang inutusan sila na umalis sa kapulungan, samantalang pinag-uusapan pa nila ang pangyayari.
Sila'y kumain at nabusog. At may lumabis na mga piraso, pitong kaing na puno.
Isinalaysay niya ang talinghagang ito: “Ang isang tao ay may isang puno ng igos na nakatanim sa kanyang ubasan. Siya'y pumunta upang maghanap ng bunga roon, subalit walang nakita.
Kapag nanggaling sila sa palengke, hindi sila kumakain malibang nalinis nila ang kanilang mga sarili. At marami pang ibang bagay ang kanilang sinusunod gaya ng mga paghuhugas ng mga tasa, mga pitsel, at mga lalagyang tanso.)
Ngunit, yamang kayo'y sumasagana sa lahat ng mga bagay, sa pananampalataya, sa pananalita, sa kaalaman, sa buong kasipagan, at sa inyong pag-ibig sa amin, sikapin din ninyo na kayo ay sumagana sa biyayang ito.
Oo, kapatid, hayaan mo nang magkaroon ako ng kapakinabangan na ito mula sa iyo sa Panginoon! Sariwain mo ang aking puso kay Cristo.
Subalit darating ang mga araw kapag kinuha sa kanila ang lalaking ikakasal, saka pa lamang sila mag-aayuno sa mga araw na iyon.”
na sinasabi, “Naganap na ang panahon at malapit na ang kaharian ng Diyos: kayo'y magsisi at manampalataya sa ebanghelyo.”
Gayon niya ipinagkaloob sa atin ang kanyang mahahalaga at mga dakilang pangako upang sa pamamagitan ng mga ito ay makatakas kayo sa kabulukang nasa sanlibutan dahil sa masamang pagnanasa, at maging kabahagi kayo sa likas ng Diyos.
Batiin ninyo si Urbano na aming kamanggagawa kay Cristo, at si Estaquis na minamahal ko.
May lumapit sa kanyang ilang Saduceo, na nagsasabing walang muling pagkabuhay.
At sinabi niya sa akin, “Ang mga salitang ito'y tapat at tunay. Ang Panginoon, ang Diyos ng mga espiritu ng mga propeta, ay nagsugo ng kanyang anghel upang ipakita sa kanyang mga alipin ang mga bagay na kailangang mangyari kaagad.
ang hiwaga na nakatago sa lahat ng mga panahon at mga salinlahi, ngunit ngayo'y ipinahayag sa kanyang mga banal.
Tunay na sa ganitong kalagayan, ang dating may kaluwalhatian ay nawalan ng kanyang kaluwalhatian, dahil sa kaluwalhatiang nakahihigit dito.
na sa kanya ay mayroon tayong katubusan, na siyang kapatawaran ng mga kasalanan.
sapagkat sila'y hindi nagpatuloy sa aking tipan,
At sila'y muling nagsigawan, “Ipako siya sa krus.”
“Sa anghel ng iglesya sa Efeso ay isulat mo: Ang mga bagay na ito ay sinasabi ng may hawak ng pitong bituin sa kanyang kanang kamay, na lumalakad sa gitna ng pitong gintong ilawan.
“Ako'y malapit nang dumating at dala ko ang aking gantimpala, upang gantihan ang bawat isa ayon sa kanyang ginawa.
Sa mga ito ay nakahiga ang maraming maysakit, mga bulag, mga pilay, at mga lumpo.
Sapagkat siya'y ibinilang sa atin at siya'y tumanggap ng kanyang bahagi sa paglilingkod na ito.”
Mga alipin, magpasakop kayo nang may buong paggalang sa inyong mga amo; hindi lamang sa mabubuti at mahihinahon, kundi gayundin sa mababagsik.
Bumaba siya na kasama nila at tumayo sa isang patag na lugar. Naroon ang marami sa kanyang mga alagad at ang napakaraming tao buhat sa Judea at sa Jerusalem at sa baybayin ng Tiro at Sidon, na pumaroon upang makinig sa kanya at mapagaling sa kanilang mga sakit;
Pagsikapan ninyong magkaroon ng kapayapaan sa lahat at ng kabanalan na kung wala nito'y walang sinumang makakakita sa Panginoon.
sa anumang paraan ay hindi ka pinakamaliit sa mga pangunahing bayan ng Juda;
At ito ang mensahe na aming narinig sa kanya at sa inyo'y aming ipinahahayag, na ang Diyos ay liwanag, at sa kanya'y walang anumang kadiliman.
Subalit kung sabihin ng alipin iyon sa kanyang sarili, ‘Matatagalan pa ang pagdating ng aking panginoon;’ at pinasimulan niyang bugbugin ang mga aliping lalaki at mga aliping babae; at siya'y kumain, uminom, at naglasing,
Mas madali pa para sa isang kamelyo ang dumaan sa butas ng isang karayom kaysa isang mayaman ang pumasok sa kaharian ng Diyos.”
“Kung ang sinuman ay lumalapit sa akin at hindi napopoot sa kanyang sariling ama, ina, asawang babae, mga anak, mga kapatid na lalaki, at mga kapatid na babae, at maging sa kanyang sariling buhay ay hindi maaaring maging alagad ko.
Kanyang isinalaysay sa amin kung paanong nakita niya ang anghel na nakatindig sa kanyang bahay, at nagsasabi, ‘Magsugo ka sa Joppa at ipatawag mo si Simon, na tinatawag na Pedro.
Nang iwan niya ang maraming tao at pumasok siya sa bahay, tinanong siya ng kanyang mga alagad tungkol sa talinghaga.
Hindi dahil sa mayroong nakakita sa Ama maliban sa kanya na mula sa Diyos. Siya ang nakakita sa Ama.
Huwag ninyong tularan ang sanlibutang ito; kundi magbago kayo sa pamamagitan ng pagbabago ng inyong pag-iisip, upang mapatunayan ninyo kung alin ang mabuti, kasiya-siya, at lubos na kalooban ng Diyos.
Nais ni Pablo na pumunta sa mga tao ngunit hindi siya pinayagan ng mga alagad.
“Kayo ang asin ng lupa; ngunit kung ang asin ay tumabang, paano maibabalik ang alat nito? Wala na itong kabuluhan, maliban sa itapon sa labas at tapakan ng mga tao.
Sinasabi ko nga, itinakuwil ba ng Diyos ang kanyang bayan? Huwag nawang mangyari. Sapagkat ako man ay Israelita, mula sa binhi ni Abraham, mula sa lipi ni Benjamin.
kung paanong pumasok siya sa bahay ng Diyos, at kumain siya ng tinapay na handog, na hindi ipinahihintulot na kainin niya o ng mga kasamahan niya, kundi ng mga pari lamang?
At sila'y iyong ginawang isang kaharian at mga pari para sa aming Diyos;
Maging si Cristo man ay hindi lumuwalhati sa kanyang sarili upang maging pinakapunong pari, kundi itinalaga ng nagsabi sa kanya,
Dinala nila sa kanya ang isang lumpo na nakaratay sa isang higaan. Nang makita ni Jesus ang kanilang pananampalataya, sinabi niya sa lumpo, “Anak, lakasan mo ang iyong loob, pinatatawad na ang iyong mga kasalanan.”
“Aleluia!
Kaya't mula ngayon ay nakalaan na sa akin ang putong ng katuwiran, na ibibigay sa akin ng Panginoon na tapat na hukom sa araw na iyon, at hindi lamang sa akin, kundi sa lahat din naman ng mga naghahangad sa kanyang pagpapakita.
At gaya ng sinabi nang una ni Isaias,
At pagkakuha niya sa limang tinapay at sa dalawang isda, tumingala siya sa langit, pinagpala, at pinagputul-putol ang mga ito. Ibinigay niya ang mga ito sa mga alagad upang ihain sa napakaraming tao.
Nang matapos na silang magsalita ay sumagot si Santiago, “Mga kapatid, pakinggan ninyo ako.
at pagkatapos ay hindi na ninyo siya pinahihintulutang gumawa ng anuman para sa kanyang ama o ina,
Ang nahulog naman sa tinikan ay ang mga nakinig subalit sa kanilang pagpapatuloy ay sinakal sila ng mga alalahanin, mga kayamanan, at mga kalayawan sa buhay at ang kanilang bunga ay hindi gumulang.
Huwag kayong magpakalasing sa alak, na ito ay labis na kahalayan, kundi mapuno kayo ng Espiritu.
At inihagis niya sa templo ang mga piraso ng pilak at siya'y umalis. Humayo siya at nagbigti.
Ngunit sa mga duwag, sa mga hindi nananampalataya, mga karumaldumal, mga mamamatay-tao, mga mapakiapid, mga mangkukulam, mga sumasamba sa mga diyus-diyosan, at sa lahat na mga sinungaling, ang kanilang bahagi ay sa lawa na nagliliyab sa apoy at asupre, na siyang ikalawang kamatayan.”
At sumagot ang buong bayan at nagsabi, “Pananagutan namin at ng aming mga anak ang kanyang dugo.”
sapagkat inyong dinaig ang masama.
Yamang marami ang nagsikap mag-ayos ng isang kasaysayan tungkol sa mga bagay na naganap sa gitna natin,
Kaya't agad kitang ipinasundo, at mabuti ang ginawa mo na naparito ka. Ngayon kaming lahat ay naririto sa harapan ng Diyos, upang pakinggan ang lahat ng mga bagay na ipinag-utos sa iyo ng Panginoon.”
Kaya't sinabi ni Jesus kay Pedro, “Ibalik mo ang iyong tabak sa kaluban. Hindi ko ba iinuman ang kopang ibinigay sa akin ng Ama?”
“Ngayon, kung marinig ninyo ang kanyang tinig,
Sama-samang itinalaga ng lahat ng mga ito ang kanilang sarili para sa pananalangin, kasama ang mga babae at si Maria na ina ni Jesus, at ang kanyang mga kapatid.
Ang inyong mga kayamanan ay bulok na, at ang inyong mga damit ay kinakain na ng bukbok.
Ilalagay ko sa kanya ang aking Espiritu,
Pagkatapos ay pinasimulan niyang ituro sa kanila na ang Anak ng Tao ay kinakailangang magdusa ng maraming bagay at itakuwil ng matatanda, ng mga punong pari, at ng mga eskriba, at patayin at pagkaraan ng tatlong araw ay muling mabubuhay.
Kaya't kunin ninyo ang buong baluti ng Diyos, upang kayo'y makatagal sa araw na masama, at kung magawa na ninyo ang lahat ay tumayong matatag.
at nagsumamo sa kanya, na sinasabi, “Ang aking munting anak na babae ay naghihingalo. Pumaroon ka at ipatong mo ang iyong mga kamay sa kanya upang siya'y gumaling at mabuhay.”
At hindi sila nakasagot sa mga bagay na ito.
Magkakaroon ng hirap at pighati sa bawat kaluluwa ng tao na gumagawa ng kasamaan, una'y sa Judio at gayundin sa Griyego;
“Sabihin ninyo sa anak na babae ng Zion,
mga Creteo at mga Arabe, ay naririnig nating nagsasalita sa ating mga wika tungkol sa mga makapangyarihang gawa ng Diyos.”
Subalit hindi siya sumagot sa kanya kahit isang salita man lamang, na lubhang ikinamangha ng gobernador.
at sinuman sa inyo na nagnanais na maging una ay kailangang maging alipin ninyo,
At ito ang patotoo, na tayo'y binigyan ng Diyos ng buhay na walang hanggan at ang buhay na ito ay nasa kanyang Anak.
At nakita ko ang isa pang tanda sa langit, dakila at kamanghamangha: pitong anghel na may pitong salot, na siyang mga panghuli, sapagkat sa mga ito'y matatapos ang poot ng Diyos.
subalit dahil ginagambala ako ng balong ito, bibigyan ko siya ng katarungan. Kung hindi ay magsasawa ako sa kanyang patuloy na pagpunta rito.’”
upang ang Diyos ng ating Panginoong Jesu-Cristo, ang Ama ng kaluwalhatian, ay magkaloob sa inyo ng espiritu ng karunungan at ng pahayag sa isang ganap na pagkakilala sa kanya,
“Bigkisan ninyo ang inyong mga baywang at paliwanagin ninyo ang inyong mga ilawan.
ayon sa iyong salita,
Sinabi niya sa kanila, “Ganyan ang nasusulat, na kailangang magdusa ang Cristo at muling mabuhay mula sa mga patay sa ikatlong araw;
Ang sumasampalataya sa akin, gaya ng sinasabi ng kasulatan, ‘Mula sa kanyang puso ay dadaloy ang mga ilog ng tubig na buháy.’”
At sinabi niya, “Walang sinuman, Panginoon.” Sinabi ni Jesus, “Hindi rin kita hinahatulan. Humayo ka na at mula ngayo'y huwag ka nang magkasala.” ]
Kaya't kami ay mga sugo para kay Cristo, yamang ang Diyos ay nananawagan sa pamamagitan namin. Kami'y nananawagan sa pangalan ni Cristo, na kayo'y makipagkasundo sa Diyos.
Kanyang inilabas sila hanggang sa tapat ng Betania at nang maitaas niya ang kanyang mga kamay, sila'y kanyang binasbasan.
Ang mga bagay na ito'y sinabi ko sa inyo, samantalang ako'y nananatiling kasama pa ninyo.
Nang sila'y papalabas na sa Jerico, sumunod sa kanya ang napakaraming tao.
Sa paglabas niya sa templo, sinabi sa kanya ng isa sa kanyang mga alagad, “Guro, tingnan mo! Pagkalalaking mga bato, at pagkalalaking mga gusali!”
At kanyang inutusan sila na mabautismuhan sa pangalan ni Jesu-Cristo. Pagkatapos, siya'y pinakiusapan nilang manatili ng mga ilang araw.
Samantala, may isang babaing labindalawang taon nang dinudugo ang lumapit sa likuran niya at hinipo nito ang laylayan ng kanyang damit;
Doo'y natagpuan niya ang isang lalaki na ang pangalan ay Aeneas na lumpo at walong taon nang nakaratay.
Marami akong isusulat sa iyo, ngunit hindi ko ibig isulat sa iyo sa pamamagitan ng tinta at panulat;
“Dakila at kamanghamangha ang iyong mga gawa,
Ngunit kung ang sinuman ay hindi kumakalinga sa kanyang kamag-anak, lalung-lalo na sa kanyang sariling sambahayan, tinanggihan niya ang pananampalataya at siya'y masahol pa sa hindi mananampalataya.
Ngunit dumating ang isang pagkakataon na si Herodes sa kanyang kaarawan ay nagbigay ng isang salu-salo para sa kanyang mga mahistrado, mga pinuno ng hukbo at mga pangunahing tao sa Galilea.
Sinasadya nilang hindi pansinin ang katotohanang ito, na sa pamamagitan ng salita ng Diyos ay nagkaroon ng langit nang unang panahon at inanyuan ang lupa mula sa tubig at sa pamamagitan ng tubig,
Sapagkat ako man ay taong inilagay sa ilalim ng kapangyarihan at may mga kawal na nasasakupan ko. At sinasabi ko sa isa, ‘Humayo ka’ at siya'y humahayo; at sa isa naman, ‘Halika,’ at siya'y lumalapit; at sa aking alipin, ‘Gawin mo ito,’ at ito'y kanyang ginagawa.”
Si Pedro at ang kanyang mga kasamahan ay nakatulog nang mahimbing, subalit nang sila'y nagising ay nakita nila ang kanyang kaluwalhatian at ang dalawang lalaking nakatayong kasama niya.
“Nang siya'y apatnapung taong gulang na, naisipan niyang dalawin ang kanyang mga kapatid, na mga anak ni Israel.
Hindi nila ako natagpuang nakikipagtalo sa kanino o kaya'y nanggugulo sa maraming tao sa templo man o sa mga sinagoga, ni sa lunsod,
Sinabi ng pinuno sa kanya, “Ginoo, pumunta ka na bago mamatay ang aking anak.”
Ako at ang Ama ay iisa.”
Nagsimula silang ipagsakdal siya na sinasabi, “Natagpuan namin ang taong ito na inililigaw ang aming bansa, at pinagbabawalan kaming magbuwis kay Cesar, at sinasabi na siya mismo ang Cristo, ang hari.”
O hindi ba ninyo nalalaman na tayong lahat na mga nabautismuhan kay Cristo Jesus ay mga nabautismuhan tungo sa kanyang kamatayan?
Sinabi nila, “Ano ang ibig niyang sabihin na, ‘Sandali na lamang?’ Hindi natin alam kung ano ang sinasabi niya.”
Ang mga punong pari at ang mga eskriba ay nanatili, at marahas siyang pinagbibintangan.
ngunit kapag ito'y naihasik ay tumutubo, nagiging mas malaki kaysa lahat ng mga halaman, at nagsasanga ng malalaki, anupa't ang mga ibon sa himpapawid ay nakakagawa ng mga pugad sa lilim nito.”
subalit ang lahat ng mga bagay na inilantad sa pamamagitan ng liwanag ay nakikita,
At sinabi ng panginoon sa alipin, ‘Lumabas ka sa mga daan at sa mga bakuran, at pilitin mo silang pumasok upang mapuno ang aking bahay.’
Nang masabi niya ang mga bagay na ito, nagpatuloy siya na umakyat tungo sa Jerusalem.
Ito ang mga nasa tabi ng daan na nahasikan ng salita. Nang kanilang mapakinggan ito, agad dumating si Satanas at inagaw ang salitang inihasik sa kanila.
Mga ama, huwag ninyong ibunsod sa galit ang inyong mga anak, baka manghina ang loob nila.
Ngunit iwasan mo ang mga pagtatalo, at ang mga pagsasalaysay ng salinlahi, at ang mga alitan at pag-aaway tungkol sa kautusan, sapagkat ang mga ito ay walang pakinabang at walang katuturan.
sapagkat tayo ay mga bahagi ng kanyang katawan.
Alin sa mga propeta ang hindi inusig ng inyong mga ninuno? Kanilang pinatay ang mga nagpahayag noong una tungkol sa pagdating ng Matuwid, at ngayon kayo'y naging kanyang mga tagapagkanulo at mamamatay-tao.
Bakit nangyari ito sa akin, na ako ay dapat dalawin ng ina ng aking Panginoon?
Ang hindi panig sa akin ay laban sa akin, at ang hindi ko kasamang nagtitipon ay nagkakalat.
Sapagkat sinasabi ng kasulatan, “Ang bawat sumasampalataya sa kanya ay hindi malalagay sa kahihiyan.”
samantalang sa kanila na makasarili at hindi sumusunod sa katotohanan, kundi bagkus ay sumusunod sa kasamaan ay para sa kanila ang poot at galit.
Sinabi ni Jesus sa kanila, “Kung kayo'y mga bulag, hindi kayo magkakaroon ng kasalanan. Subalit ngayong sinasabi ninyo, ‘Kami'y nakakakita,’ nananatili ang inyong kasalanan.”
si Juana na asawa ni Chuza, na katiwala ni Herodes, at si Susana at marami pang iba na nagkaloob sa kanila mula sa kanilang mga ari-arian.
Kumain silang lahat at nabusog. Kinuha nila ang mga lumabis na pinagputul-putol na tinapay, at napuno ang labindalawang kaing.
Ngunit nang siya'y kanilang magapos na ng mga panaling balat, ay sinabi ni Pablo sa senturiong nakatayo sa malapit, “Matuwid ba sa inyo na hagupitin ang isang taong mamamayan ng Roma, na hindi pa nahahatulan?”
“At ang kanilang mga kasalanan at mga kasamaan ay hindi ko na aalalahanin pa.”
Ano sa palagay ninyo?” Sumagot sila at sinabi, “Karapat-dapat siya sa kamatayan.”
Sa silangan ay tatlong pintuan, sa hilaga ay tatlong pintuan, sa timog ay tatlong pintuan, at sa kanluran ay tatlong pintuan.
At hindi nila nagawang hulihin siya sa kanyang salita sa harap ng mga taong-bayan. At sa pagkamangha nila sa kanyang sagot sila ay tumahimik.
Ano nga ang ating sasabihin? Ang mga Hentil na hindi nagsumikap sa katuwiran ay nagkamit ng katuwiran, samakatuwid ay katuwiran sa pamamagitan ng pananampalataya;
“Isang Ananias, na lalaking masipag sa kabanalan ayon sa kautusan, at may magandang patotoo tungkol sa kanya ang mga Judio na naninirahan doon,
ako'y magiging kanilang Diyos,
At upang malaman din ninyo ang mga bagay tungkol sa akin at ang aking kalagayan, si Tiquico ang siyang magsasalaysay sa inyo ng lahat ng mga bagay. Siya na aking minamahal na kapatid at tapat na lingkod sa Panginoon.
Ngunit nang ito ay marinig ni Jesus ay sinabi niya, “Ang sakit na ito'y hindi tungo sa kamatayan, kundi para sa ikaluluwalhati ng Diyos, upang ang Anak ng Diyos ay luwalhatiin sa pamamagitan nito.”
At ating isaalang-alang kung papaano gigisingin ang isa't isa sa pag-ibig at sa mabubuting gawa,
Ngunit muling nagkaila siya. At pagkaraan ng ilang sandali, sinabing muli ng mga nakatayo roon kay Pedro, “Tunay na ikaw ay isa sa kanila, sapagkat ikaw ay taga-Galilea.”
Ngayo'y patnubayan nawa ng ating Diyos at Ama at ng ating Panginoong Jesus ang aming paglalakbay patungo sa inyo.
at naging masunurin hanggang sa kamatayan,
Sa pamamaybay namin dito na may kahirapan ay nakarating kami sa isang lugar na tinatawag na Mabubuting Daungan, malapit sa lunsod ng Lasea.
At ito ay aming ginagawa upang huwag kaming malamangan ni Satanas, sapagkat kami ay hindi mangmang tungkol sa kanyang mga balak.
At sumagot siya sa kanila, “Ano ba ang iniutos sa inyo ni Moises?”
At tinanong niya sila, “Ngunit, sino ako ayon sa sinasabi ninyo?” Sumagot si Pedro at sinabi sa kanya, “Ikaw ang Cristo.”
Nang buksan niya ang ikaapat na tatak ay narinig ko ang tinig ng ikaapat na nilalang na buháy na nagsasabi, “Halika!”
Pakaingatan ninyo na baka ang sinuma'y mahulog mula sa biyaya ng Diyos; baka may ilang ugat ng kapaitan ang sumibol at bumagabag sa inyo at mahawa nito ang marami.
Sumagot si Jesus at sinabi sa kanila, “Tatanungin ko rin kayo ng isang tanong, at kung sasabihin ninyo sa akin ang sagot ay sasabihin ko naman sa inyo kung sa anong awtoridad ginagawa ko ang mga bagay na ito.
Ako'y may pag-asa sa Diyos, na siya rin namang inaasahan nila, na magkakaroon ng muling pagkabuhay ng mga matuwid at ng mga hindi matuwid.
Nang malapit na siya sa Jerico, isang bulag ang nakaupo sa tabi ng daan na namamalimos.
Ngunit hindi nila ito pinansin, at sila'y humayo, ang isa'y sa kanyang sariling bukid, ang isa'y sa kanyang pangangalakal.
Gaano pa ngang higit na mahalaga ang isang tao kaysa isang tupa! Kaya't matuwid na gumawa ng mabuti sa araw ng Sabbath.”
Malalim na ang gabi, at ang araw ay malapit na. Kaya't iwaksi na natin ang mga gawa ng kadiliman, at ating isakbat ang mga sandata ng liwanag.
At ako'y nanguna sa Judaismo nang higit kaysa marami sa mga kasing-gulang ko sa aking mga kababayan, higit na masigasig ako sa mga tradisyon ng aking mga ninuno.
Sumagot ang maraming tao, “Mayroon kang demonyo! Sino ang nagsisikap na ikaw ay patayin?”
Sinenyasan nila ang kanyang ama, kung ano ang ibig niyang itawag sa sanggol.
Isa sa kanila na ang pangalan ay Agabo, ang tumayo at ipinaalam sa pamamagitan ng Espiritu na magkakaroon ng matinding taggutom sa buong sanlibutan; at ito'y nangyari sa kapanahunan ni Claudio.
Dahil sa mga bagay na ito ay dumarating ang poot ng Diyos sa mga anak ng pagsuway.
At nang siya'y kanilang makita, ay kanilang sinamba siya. Subalit ang ilan ay nag-alinlangan.
Sinabi niya, “Ano ang katulad ng kaharian ng Diyos at sa ano ko ito ihahambing?
‘Ikaw ay aking Anak,
Nang matapos pagbilinan ni Jesus ang kanyang labindalawang alagad, umalis siya roon upang magturo at mangaral sa mga bayan nila.
Hindi nila sinisindihan ang isang ilawan at inilalagay sa ilalim ng isang takalan, kundi sa talagang patungan at nagbibigay ng liwanag sa lahat ng nasa bahay.
sapagkat nalalaman ko ang inyong pananabik, na aking ipinagmamalaki tungkol sa inyo sa mga taga-Macedonia, na ang Acaia ay nakapaghanda na noong nakaraang taon pa, at ang inyong sigasig ay nakapukaw sa karamihan sa kanila.
“Pakinggan ninyo ang talinghaga ng manghahasik.
‘Mula sa bibig ng mga sanggol at ng mga sumususo
Isusugo niya ang kanyang mga anghel na may malakas na tunog ng trumpeta at kanilang titipunin ang kanyang mga hinirang mula sa apat na hangin, mula sa isang dulo ng langit hanggang sa kabila.
at nakasuot sa inyong mga paa ang pagiging handa para sa ebanghelyo ng kapayapaan.
At kung ang mata mo ay nakapagpapatisod sa iyo, dukitin mo ito at itapon. Mas mabuti pa sa iyo ang pumasok sa buhay na iisa ang mata, kaysa dalawang mata na maitapon sa impiyerno ng apoy.
Sumagot si Pablo, “Ako'y Judio, na taga-Tarso sa Cilicia, isang mamamayan ng isang hindi karaniwang lunsod. Nakikiusap ako, pahintulutan mo akong magsalita sa mga taong-bayan.”
Siya'y kailangang tumaas, nguni't ako'y kailangang bumaba.”
Nang mahalata ni Jesus na sila'y lalapit at pipilitin siyang gawing hari, siya'y muling umalis na nag-iisa patungo sa bundok.
Nakarating ang balita tungkol sa kanila sa mga pandinig ng iglesya na nasa Jerusalem at kanilang sinugo si Bernabe sa Antioquia.
Subalit sinagot sila ni Jesus, “Hanggang ngayo'y patuloy sa paggawa ang aking Ama, at ako'y patuloy rin sa paggawa.”
Binigyan ko siya ng panahon upang makapagsisi; ngunit ayaw niyang magsisi sa kanyang pakikiapid.
Habang papaalis na ang mga ito, nagpasimulang magsalita si Jesus sa maraming tao tungkol kay Juan: “Ano ang pinuntahan ninyo sa ilang upang makita? Isa bang tambo na inuuga ng hangin?
ang iba'y inyong iligtas, na agawin ninyo mula sa apoy; at ang iba'y inyong kahabagan na may takot; na inyong kapootan maging ang damit na nadungisan ng laman.
Kaya't hindi ka na alipin kundi anak; at kung anak, ay tagapagmana.
Sinabi ng ilang taga-Jerusalem, “Hindi ba ito ang taong kanilang pinagsisikapang patayin?
Isipin mo ang sinasabi ko, sapagkat bibigyan ka ng Panginoon ng pagkaunawa sa lahat ng mga bagay.
Ang babae na iyong nakita ay ang dakilang lunsod na naghahari sa mga hari sa lupa.”
Nang mag-umaga na, hindi nila napansin ang lupa, ngunit nababanaagan nila ang isang look na may baybayin, at sila'y nagbalak na maisadsad doon ang barko.
“Ngayo'y dumating ang kaligtasan at ang kapangyarihan,
ay dinala paitaas patungo sa Paraiso, at nakarinig ng mga salitang hindi dapat sabihin, na hindi ipinahihintulot sa tao na ulitin.
At,
Sinabi niya sa kanila, “Ang ganitong uri ay napapalayas lamang sa pamamagitan ng panalangin.”
Pagkatapos ay tumayo ang hari, ang gobernador, si Bernice, at ang mga nakaupong kasama nila,
Lumapit sa kanya ang napakaraming tao na dala ang mga pilay, mga lumpo, mga bulag, mga pipi, at marami pang iba. Inilagay nila ang mga ito sa kanyang paanan at sila'y pinagaling niya.
Huwag mong pabayaan ang kaloob na sa iyo'y ibinigay sa pamamagitan ng propesiya, na may pagpapatong ng mga kamay ng kapulungan ng matatanda.
At sa bagay na ito ay nagbibigay ako ng payo: pinakamabuti para sa inyo ngayon na tapusin ang sinimulan ninyo nang nakaraang taon, hindi lamang upang gumawa kundi magkaroon ng pagnanais na gumawa.
Ang lima sa kanila'y mga hangal at ang lima'y matatalino.
Nang sila'y tumutol at lapastanganin siya, ipinagpag niya ang kanyang kasuotan at sa kanila'y sinabi, “Ang inyong dugo'y sumainyong sariling mga ulo! Ako'y malinis. Mula ngayon, pupunta ako sa mga Hentil.”
Sapagkat ang Anak ng Tao ay patungo ayon sa itinakda, subalit kahabag-habag ang taong nagkakanulo sa kanya!”
Pagkatapos ay pumunta siyang muli sa Cana ng Galilea na doo'y kanyang ginawang alak ang tubig. At sa Capernaum ay naroroon ang isang pinuno ng pamahalaan na ang anak na lalaki ay maysakit.
at luluwalhati sa iyong pangalan O Panginoon,
Sapagkat kung ang mga Hentil na likas na walang kautusan ay gumagawa ng mga bagay ng kautusan, ang mga ito, bagaman walang kautusan, ay siyang kautusan sa kanilang sarili.
Mayroon bang tao sa inyo, na kung humingi ng tinapay sa kanya ang kanyang anak ay bato ang ibibigay?
Kaya't hinipo niya ang kanilang mga mata, na sinasabi, “Mangyari sa inyo ang ayon sa inyong pananampalataya.”
na siyang sumaksi sa salita ng Diyos at sa patotoo ni Jesu-Cristo, sa lahat ng bagay na nakita niya.
At si Moises ay naging tapat sa buong sambahayan ng Diyos gaya ng isang lingkod, bilang patotoo sa mga bagay na sasabihin.
Alalahanin ninyo ang asawa ni Lot.
Sino ang mahina, at ako ba'y hindi mahina? Sino ang natitisod, at ako'y di nag-iinit?
Nagkaroon ng maraming bulung-bulungan tungkol sa kanya ang mga tao. Sinasabi ng ilan, “Siya'y mabuting tao.” Sinasabi naman ng iba, “Hindi, inililigaw niya ang mga tao.”
o ang nangangaral ay sa pangangaral; ang nagbibigay ay magbigay na may magandang-loob; ang namumuno ay may pagsisikap; ang mahabagin ay may kasiglahan.
kung kami sa araw na ito'y sinisiyasat dahil sa kabutihang ginawa sa isang taong may kapansanan, na tinatanong kung paano napagaling ang taong ito,
Tingnan ninyo, sa inyo'y iniwan ang inyong bahay. At sinasabi ko sa inyo, hindi ninyo ako makikita, hanggang sa inyong sabihin, ‘Mapalad ang dumarating sa pangalan ng Panginoon.’”
at nagagalak ang aking espiritu sa Diyos na aking Tagapagligtas.
Ang pasimula ng ebanghelyo ni Jesu-Cristo, ang Anak ng Diyos.
Ang mga diakono ay dapat na may tig-iisang asawa lamang, at pinamamahalaang mabuti ang kanilang mga anak at ang kanilang sariling mga sambahayan.
At sa pagnanais ni Pilato na bigyang-kasiyahan ang taong-bayan, pinalaya si Barabas para sa kanila. Pagkatapos na ipahagupit si Jesus, siya'y ibinigay niya upang ipako sa krus.
upang kanyang maiharap sa kanyang sarili ang isang maluwalhating iglesya, na walang batik, o kulubot, o anumang gayong bagay, kundi siya ay maging banal at walang dungis.
Sinabi ng isang tinig mula sa langit, “Ito ang minamahal kong Anak, sa kanya ako lubos na nalulugod.”
na ipinanganak hindi sa dugo, o sa kalooban ng laman, o sa kalooban ng tao, kundi ng Diyos.
At tumingin ako, at aking narinig ang isang agila, na lumilipad sa gitna ng himpapawid, na nagsasabi ng malakas na tinig, “Kahabag-habag, kahabag-habag, kahabag-habag ang mga naninirahan sa ibabaw ng lupa, dahil sa mga tunog ng mga trumpeta na malapit nang hipan ng tatlo pang anghel.”
Ang Diyos ay espiritu, at ang mga sumasamba sa kanya ay kailangang sumamba sa espiritu at katotohanan.”
Sapagkat kayo rin ang nakakaalam kung paano ninyo kami dapat tularan; hindi kami tamad noong kami'y kasama ninyo.
Huwag kayong humatol batay sa anyo, kundi humatol kayo nang matuwid na paghatol.”
Sumainyo nawa ang biyaya at kapayapaang mula sa Diyos Ama at sa Panginoong Jesu-Cristo.
Ipaalala mo sa kanila ang mga bagay na ito, na sila'y pagbilinan mo sa harapan ng Diyos na sila'y huwag makipagtalo tungkol sa mga salita na hindi mapapakinabangan kundi sa ikapapahamak lamang ng mga nakikinig.
subalit ang dila ay hindi napapaamo ng tao, isang hindi napipigilang kasamaang punô ng lasong nakamamatay.
Sa halip, may isang babae na ang munting anak na batang babae na may masamang espiritu, na nakabalita tungkol sa kanya ay agad na lumapit at nagpatirapa sa kanyang paanan.
At tinawag ni Pablo ang isa sa mga senturion, at sinabi, “Dalhin mo ang binatang ito sa punong kapitan sapagkat siya'y mayroong sasabihin sa kanya.”
at nakita niyang bumukas ang langit, at may isang bagay na bumababa, tulad ng isang malapad na kumot na ibinababa sa lupa na nakabitin sa apat na sulok.
At sapagkat kayo'y mga anak, isinugo ng Diyos ang Espiritu ng kanyang Anak sa ating mga puso, na sumisigaw, “Abba, Ama!”
Ang inyong ginto at ang inyong pilak ay kinakalawang na, at ang mga kalawang ng mga ito ay magiging patotoo laban sa inyo, at gaya ng apoy ay lalamunin nito ang inyong laman. Kayo'y nag-imbak ng mga kayamanan para sa mga huling araw.
At ngayon ay sinabi ko sa inyo bago pa mangyari, upang kung ito'y mangyari, kayo ay maniwala.
Lumabas si Jesus sa templo at paalis na, nang lumapit sa kanya ang mga alagad niya upang ipakita sa kanya ang mga gusali ng templo.
Ang mga mananampalatayang Judio na dumating na kasama ni Pedro ay namangha sapagkat ibinuhos din maging sa mga Hentil ang kaloob ng Espiritu Santo.
Ngunit si Jesus ay hindi sumagot ng anuman, anupa't nanggilalas si Pilato.
Pagkatapos na makapagpaalam siya sa kanila, umakyat siya sa bundok upang manalangin.
Ang sinumang napopoot sa kanyang kapatid ay isang mamamatay-tao, at nalalaman ninyong ang buhay na walang hanggan ay hindi nananatili sa sinumang mamamatay-tao.
Sapagkat sinasabi niya sa kanyang puso,
Nang ikatlo ng hapon ay sumigaw si Jesus nang may malakas na tinig, “Eloi, Eloi, lama sabacthani?” na ang kahulugan ay, “Diyos ko, Diyos ko, bakit mo ako pinabayaan?”
Subalit noong una, nang hindi pa ninyo kilala ang Diyos, kayo'y naging mga alipin ng mga hindi likas na diyos.
Mayroong isang mabuti at matuwid na lalaking ang pangalan ay Jose, na bagaman kaanib ng sanggunian,
Lumapit si Jesus, dinampot ang tinapay, at ibinigay sa kanila pati ang isda.
maliban sa isang bagay na ito na aking isinigaw habang nakatayo sa gitna nila, ‘Tungkol sa pagkabuhay ng mga patay ako'y nililitis sa harapan mo sa araw na ito.’”
At kung ako'y pumunta roon at maihanda ko ang isang lugar para sa inyo, ako'y babalik at kayo'y tatanggapin ko sa aking sarili, upang kung saan ako naroroon, kayo rin ay naroroon.
Kaya't nang tawagin niyang isa-isa ang mga may utang sa kanyang panginoon, ay sinabi niya sa una, ‘Magkano ang utang mo sa aking panginoon?’
Sapagkat gaya ng kidlat na nanggagaling sa silangan at nagliliwanag hanggang sa kanluran, gayundin naman ang pagdating ng Anak ng Tao.
Nagsalaysay siya sa kanila ng isa pang talinghaga: “Ang kaharian ng langit ay tulad sa pampaalsa na kinuha ng isang babae, at inihalo sa tatlong takal na harina, hanggang sa ang lahat ay malagyan ng pampaalsa.”
At sinabi sa kanya ni Jesus, “Kaibigan, gawin mo ang layunin ng pagparito mo.” Pagkatapos ay lumapit sila at kanilang hinawakan si Jesus at siya'y kanilang dinakip.
Napuno ng kaguluhan ang lunsod at sama-sama nilang nilusob ang tanghalan, at sinunggaban sina Gayo at Aristarco, mga taga-Macedonia, na kasama ni Pablo sa paglalakbay.
Ngunit itong aking mga kaaway, na ayaw na ako'y maghari sa kanila, ay dalhin ninyo rito at patayin sila sa harapan ko.’”
Sumakanya nawa ang kapangyarihan magpakailanman. Amen.
tuwirin ninyo ang kanyang mga landas.’”
At kanilang pinagtawanan siya, dahil ang alam nila'y patay na ang bata.
Kaming lahat na nasa barko ay dalawandaan at pitumpu't anim na kaluluwa.
Sa pamamagitan ng pagsisiyasat ninyo mismo sa kanya, ang lahat ng mga bagay na ito na isinasakdal namin laban sa kanya ay malalaman ninyo mula sa kanya.”
kapag dumating siya sa araw na iyon upang luwalhatiin sa kanyang mga banal, at kamanghaan ng lahat ng mga sumasampalataya, sapagkat ang aming patotoo sa inyo ay pinaniwalaan.
At kami ay patuloy na nagpapasalamat sa Diyos, na nang inyong tanggapin ang salita ng Diyos na inyong narinig sa amin ay inyong tinanggap iyon hindi bilang salita ng mga tao, kundi, ayon sa katotohanan, ay bilang salita ng Diyos, na gumagawa naman sa inyo na sumasampalataya.
Sapagkat ano ngang pasasalamat ang aming maisasauli sa Diyos dahil sa inyo, dahil sa lahat ng kagalakan na aming nadarama dahil sa inyo sa harapan ng aming Diyos?
Sumagot si Jesus sa kanya, “Kung ang isang tao ay nagmamahal sa akin, ay kanyang tutuparin ang aking salita, at siya'y mamahalin ng aking Ama, at kami'y lalapit sa kanya, at kami'y gagawa ng tahanang kasama siya.
Habang sila'y nagtataka tungkol dito, biglang may dalawang lalaki na nakasisilaw ang mga damit ang tumayo sa tabi nila.
At sisikapin ko rin na pagkatapos ng aking pagpanaw ay inyong maaalala ang mga bagay na ito sa anumang panahon.
At pinuri ng panginoon ang madayang katiwala, sapagkat siya'y gumawang may katusuhan, sapagkat ang mga anak ng sanlibutang ito ay higit na tuso sa pakikitungo sa sarili nilang lahi kaysa mga anak ng liwanag.
Ngayon sa gumagawa, ang kabayaran ay hindi itinuturing na biyaya, kundi siyang talagang nararapat.
at magkaroon ng kapangyarihang magpalayas ng mga demonyo:
Sinabi ni Jesus sa kanila, “Katotohanang sinasabi ko sa inyo, na sa pagbabago ng lahat ng mga bagay, kapag uupo na ang Anak ng Tao sa kanyang maluwalhating trono, kayong mga sumunod sa akin ay uupo rin sa labindalawang trono na naghuhukom sa labindalawang lipi ng Israel.
Subalit iwasan mo ang mga usapang walang kabuluhan, sapagkat ito'y magtutulak sa mga tao sa higit pang kasamaan,
Alin ba ang mas madali, ang sabihin sa lumpo, ‘Pinatatawad na ang iyong mga kasalanan;’ o ang sabihin, ‘Tumayo ka, damputin mo ang iyong higaan, at lumakad ka?’
At sinabi sa kanya ng Panginoon, ‘Alisin mo ang mga sandalyas sa iyong mga paa sapagkat ang dakong kinatatayuan mo ay lupang banal.
Sa halip, may ilan silang di-pagkakasundo laban sa kanya tungkol sa kanilang sariling relihiyon, at sa isang Jesus, na namatay na, ngunit pinaninindigan ni Pablo na buháy.
Ang mga ito rin ang nilakaran ninyo noong una, nang kayo'y nabubuhay pa sa mga bagay na ito.
Subalit ang kautusan ay hindi nakasalig sa pananampalataya; sa halip, “Ang gumagawa ng mga iyon ay mabubuhay sa mga iyon.”
At sinabi ng mga eskriba na bumaba mula sa Jerusalem, “Nasa kanya si Beelzebul. Sa pamamagitan ng pinuno ng mga demonyo ay nagpapalayas siya ng mga demonyo.”
Sapagkat ito'y panahon upang simulan ang paghuhukom sa sambahayan ng Diyos; at kung magsimula sa atin, ano kaya ang wakas ng mga hindi sumusunod sa ebanghelyo ng Diyos?
Nang sila'y makapasok sa lunsod, umakyat sila sa silid sa itaas na doon ay nakatira sina Pedro, Juan, Santiago at Andres, Felipe at Tomas, Bartolome at Mateo, si Santiago na anak ni Alfeo, si Simon na Makabayan, at si Judas na anak ni Santiago.
Sapagkat ang Anak ng Tao ay panginoon ng Sabbath.”
